from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData

# @formatter:off
units: dict[int, itemData] = {
    10000: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_herd_1', itemType.unit, 1, 'progressive bst_inf', 'Beastmen Unit: Ungor Herd'),
    10001: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_spearmen_0', itemType.unit, 1, 'progressive bst_inf', 'Beastmen Unit: Ungor Spearmen Herd'),
    10002: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_spearmen_1', itemType.unit, 1, 'progressive bst_inf', 'Beastmen Unit: Ungor Spearmen Herd (Shields)'),
    10003: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_gor_herd_0', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Gor Herd'),
    10004: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_gor_herd_1', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Gor Herd (Shields)'),
    10005: itemData(IC.useful, 1, 'wh3_dlc26_bst_inf_khorngors', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Khorngors'),
    10006: itemData(IC.useful, 1, 'wh3_dlc25_bst_inf_pestigors', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Pestigors'),
    10007: itemData(IC.useful, 1, 'wh3_dlc27_bst_inf_slaangors', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Slaangors'),
    10008: itemData(IC.useful, 1, 'wh3_dlc24_bst_inf_tzaangors', itemType.unit, 2, 'progressive bst_inf', 'Beastmen Unit: Tzaangors'),
    10009: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_bestigor_herd_0', itemType.unit, 3, 'progressive bst_inf', 'Beastmen Unit: Bestigor Herd'),
    10010: itemData(IC.useful, 1, 'wh_dlc03_bst_mon_chaos_spawn_0', itemType.unit, 3, 'progressive bst_inf', 'Beastmen Unit: Chaos Spawn'),
    10011: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_0', itemType.unit, 3, 'progressive bst_inf', 'Beastmen Unit: Minotaurs'),
    10012: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_2', itemType.unit, 4, 'progressive bst_inf', 'Beastmen Unit: Minotaurs (Great Weapons)'),
    10013: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_1', itemType.unit, 4, 'progressive bst_inf', 'Beastmen Unit: Minotaurs (Shields)'),
    10014: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_raiders_0', itemType.unit, 1, 'progressive bst_rng', 'Beastmen Unit: Ungor Raiders'),
    10015: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_0', itemType.unit, 1, 'progressive bst_cav', 'Beastmen Unit: Centigors'),
    10016: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_2', itemType.unit, 1, 'progressive bst_cav', 'Beastmen Unit: Centigors (Great Weapons)'),
    10017: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_1', itemType.unit, 2, 'progressive bst_cav', 'Beastmen Unit: Centigors (Throwing Axes)'),
    10018: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_cygor_0', itemType.unit, 1, 'progressive bst_art', 'Beastmen Unit: Cygor'),
    10019: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_chaos_warhounds_0', itemType.unit, 1, 'progressive bst_bst', 'Beastmen Unit: Chaos Warhounds'),
    10020: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_chaos_warhounds_1', itemType.unit, 2, 'progressive bst_bst', 'Beastmen Unit: Chaos Warhounds (Poison)'),
    10021: itemData(IC.useful, 1, 'wh_dlc05_bst_mon_harpies_0', itemType.unit, 2, 'progressive bst_bst', 'Beastmen Unit: Harpies'),
    10022: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_razorgor_herd_0', itemType.unit, 2, 'progressive bst_bst', 'Beastmen Unit: Razorgor Herd'),
    10023: itemData(IC.useful, 1, 'wh_dlc03_bst_feral_manticore', itemType.unit, 3, 'progressive bst_bst', 'Beastmen Unit: Feral Manticore'),
    10024: itemData(IC.useful, 1, 'wh_dlc03_bst_mon_giant_0', itemType.unit, 3, 'progressive bst_bst', 'Beastmen Unit: Giant'),
    10025: itemData(IC.useful, 1, 'wh3_dlc24_bst_mon_cockatrice', itemType.unit, 3, 'progressive bst_bst', 'Beastmen Unit: Cockatrice'),
    10026: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_0', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Jabberslythe'),
    10027: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_0', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Ghorgon'),
    10028: itemData(IC.useful, 1, 'wh3_dlc27_bst_mon_preyton', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Preyton'),
    10029: itemData(IC.useful, 1, 'wh3_dlc27_bst_mon_chimera', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Chimera'),
    10030: itemData(IC.useful, 1, 'wh3_dlc24_bst_mon_incarnate_elemental_of_beasts', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Incarnate Elemental of Beasts'),
    10031: itemData(IC.useful, 1, 'wh2_dlc17_bst_cav_tuskgor_chariot_0', itemType.unit, 2, 'progressive bst_veh', 'Beastmen Unit: Tuskgor Chariots'),
    10032: itemData(IC.useful, 1, 'wh_dlc03_bst_cav_razorgor_chariot_0', itemType.unit, 3, 'progressive bst_veh', 'Beastmen Unit: Razorgor Chariots'),
    10033: itemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_wild_0', itemType.unit, 1, 'progressive bst_hro', 'Beastmen Unit: Bray-Shaman (Wild)'),
    10034: itemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_shadows_0', itemType.unit, 1, 'progressive bst_hro', 'Beastmen Unit: Bray-Shaman (Shadows)'),
    10035: itemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_death_0', itemType.unit, 1, 'progressive bst_hro', 'Beastmen Unit: Bray-Shaman (Death)'),
    10036: itemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_beasts_0', itemType.unit, 1, 'progressive bst_hro', 'Beastmen Unit: Bray-Shaman (Beasts)'),
    10037: itemData(IC.useful, 1, 'wh_dlc03_bst_cha_gorebull_0', itemType.unit, 2, 'progressive bst_hro', 'Beastmen Unit: Gorebull'),
    10038: itemData(IC.useful, 1, 'wh2_dlc17_bst_cha_wargor_0', itemType.unit, 2, 'progressive bst_hro', 'Beastmen Unit: Wargor'),
    10039: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_ror_0', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: The Vorbergland Broodmother (Jabberslythe)'),
    10040: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_ror_0', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: The Bloodbrute Behemoth (Ghorgon)'),
    10041: itemData(IC.useful, 1, 'wh2_dlc17_bst_inf_centigors_ror_1', itemType.unit, 2, 'progressive bst_cav', "Beastmen Unit: Groghooves of Wolf's Run (Centigors - Throwing Axes)"),
    10042: itemData(IC.useful, 1, 'wh_pro04_bst_inf_ungor_spearmen_ror_0', itemType.unit, 1, 'progressive bst_inf', 'Beastmen Unit: Destroyers of the Drakwald (Ungor Spearmen Herd - Shields)'),
    10043: itemData(IC.useful, 1, 'wh_pro04_bst_inf_gor_herd_ror_0', itemType.unit, 1, 'progressive bst_inf', "Beastmen Unit: Black-Horn's Ravagers (Gor Herd - Shields)"),
    10044: itemData(IC.useful, 1, 'wh_pro04_bst_inf_minotaurs_ror_0', itemType.unit, 4, 'progressive bst_inf', 'Beastmen Unit: Butchers of Kalkengard (Minotaurs - Shields)'),
    10045: itemData(IC.useful, 1, 'wh_pro04_bst_inf_cygor_ror_0', itemType.unit, 1, 'progressive bst_art', 'Beastmen Unit: The Eye of Morrslieb (Cygor)'),
    10046: itemData(IC.useful, 1, 'wh_pro04_bst_inf_centigors_ror_0', itemType.unit, 1, 'progressive bst_cav', 'Beastmen Unit: Sons of Ghorros (Centigors - Great Weapons)'),
    10047: itemData(IC.useful, 1, 'wh_pro04_bst_inf_bestigor_herd_ror_0', itemType.unit, 3, 'progressive bst_inf', "Beastmen Unit: Khorrok's Manrippers (Bestigor Herd)"),
    10048: itemData(IC.useful, 1, 'wh3_dlc27_bst_mon_chimera_ror', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Bloodshriek Chimera (Chimera)'),
    10049: itemData(IC.useful, 1, 'wh3_dlc27_bst_mon_preyton_ror', itemType.unit, 4, 'progressive bst_bst', 'Beastmen Unit: Scourge of Arden (Preyton)')
}

buildings: dict[int, itemData] = {
    10400: itemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Herdstone'),
    10401: itemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Rune-Covered Herdstone'),
    10402: itemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Bone-Strewn Herdstone'),
    10403: itemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Spired Herdstone'),
    10404: itemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Great Herdstone'),
    10405: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes_2', itemType.building, 1, 'progressive bst_special_secondary_attributes', 'Beastmen Building: Viscera-Bound Captives'),
    10406: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes_3', itemType.building, 2, 'progressive bst_special_secondary_attributes', 'Beastmen Building: Shroud of Discord'),
    10407: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes', itemType.building, 0, 'progressive bst_special_secondary_attributes', 'Beastmen Building: Carrion Offerings'),
    10408: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition_2', itemType.building, 1, 'progressive bst_special_secondary_attrition', 'Beastmen Building: Miasmic Rain'),
    10409: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition_3', itemType.building, 2, 'progressive bst_special_secondary_attrition', 'Beastmen Building: Storm of Suffering'),
    10410: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition', itemType.building, 0, 'progressive bst_special_secondary_attrition', 'Beastmen Building: Winds of Malady'),
    10411: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances_2', itemType.building, 1, 'progressive bst_special_secondary_resistances', 'Beastmen Building: Rancorous Braying'),
    10412: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances_3', itemType.building, 2, 'progressive bst_special_secondary_resistances', 'Beastmen Building: Beastly Pandemonium'),
    10413: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances', itemType.building, 0, 'progressive bst_special_secondary_resistances', 'Beastmen Building: Rucking Pits'),
    10414: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell_2', itemType.building, 1, 'progressive bst_special_secondary_spell', 'Beastmen Building: Ruinous Seances'),
    10415: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell_3', itemType.building, 2, 'progressive bst_special_secondary_spell', 'Beastmen Building: Dreadful Shamanic Rituals'),
    10416: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell', itemType.building, 0, 'progressive bst_special_secondary_spell', 'Beastmen Building: Shamanic Challenges'),
    10417: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10418: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10419: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10420: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10421: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Fall of Man'),
    10422: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10423: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10424: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10425: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10426: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Crag of the Cloven'),
    10427: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10428: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10429: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10430: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10431: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Bloodfeastersâ€™ Ruin'),
    10432: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10433: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10434: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10435: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10436: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Defiled Tournament Grounds'),
    10437: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10438: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10439: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10440: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10441: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Morrsliebâ€™s Eclipse'),
    10442: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10443: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10444: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10445: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10446: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Age of Desecration'),
    10447: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10448: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10449: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10450: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10451: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Ruins of Urskoy'),
    10452: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10453: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10454: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10455: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10456: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Sepulchral Gate'),
    10457: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10458: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10459: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10460: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10461: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Great Herdstone of Cold'),
    10462: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10463: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10464: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10465: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10466: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Scorched Oak'),
    10467: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10468: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10469: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10470: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10471: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Splintered Compass'),
    10472: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_1', itemType.building, 0, 'progressive bst_settlement_major', 'Beastmen Building: Chosen Herdstone'),
    10473: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_2', itemType.building, 1, 'progressive bst_settlement_major', 'Beastmen Building: Blasphemous Clearing'),
    10474: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_3', itemType.building, 2, 'progressive bst_settlement_major', 'Beastmen Building: Nexus of Depravity'),
    10475: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_4', itemType.building, 3, 'progressive bst_settlement_major', 'Beastmen Building: Heart of Doom'),
    10476: itemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_5', itemType.building, 4, 'progressive bst_settlement_major', 'Beastmen Building: Wasteland of Hashut'),
    10477: itemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_1', itemType.building, 0, 'progressive bst_allied_outpost', 'Beastmen Building: Beastmen Outpost'),
    10478: itemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_2', itemType.building, 1, 'progressive bst_allied_outpost', 'Beastmen Building: Beastmen District'),
    10479: itemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_3', itemType.building, 2, 'progressive bst_allied_outpost', 'Beastmen Building: Beastmen Colony'),

    10480: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_arcane_1', itemType.building, 0, 'progressive bst_horde_arcane', "Beastmen Horde Building: Shaman's Flame Pit"),
    10481: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_arcane_2', itemType.building, 1, 'progressive bst_horde_arcane', "Beastmen Horde Building: Shaman's Pyre"),
    10506: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_arcane_3', itemType.building, 2, 'progressive bst_horde_arcane', "Beastmen Horde Building: Immolation Grounds"),
    10482: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_centigors_1', itemType.building, 0, 'progressive bst_horde_centigors', 'Beastmen Horde Building: Scorched Grass Plains'),
    10483: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_centigors_2', itemType.building, 1, 'progressive bst_horde_centigors', "Beastmen Horde Building: Centigor's Hollow"),
    10484: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_creatures_1', itemType.building, 0, 'progressive bst_horde_creatures', 'Beastmen Horde Building: Den'),
    10485: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_creatures_2', itemType.building, 1, 'progressive bst_horde_creatures', 'Beastmen Horde Building: Pits of Horror'),
    10486: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_creatures_3', itemType.building, 2, 'progressive bst_horde_creatures', 'Beastmen Horde Building: Toxic Grounds'),
    10487: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_giants_1', itemType.building, 0, 'progressive bst_horde_giants', "Beastmen Horde Building: Giant's Lair"),
    10488: itemData(IC.useful, 1, 'wh_dlc17_horde_beastmen_ghorgon_1', itemType.building, 1, 'progressive bst_horde_giants', "Beastmen Horde Building: Ghorgon's Lair"),
    10489: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_gors_1', itemType.building, 0, 'progressive bst_horde_gors', 'Beastmen Horde Building: Dug-Out'),
    10490: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_gors_2', itemType.building, 1, 'progressive bst_horde_gors', 'Beastmen Horde Building: Pit-Hovel'),
    10491: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_gors_3', itemType.building, 2, 'progressive bst_horde_gors', 'Beastmen Horde Building: Pelt Totem'),
    10492: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_herd_1', itemType.building, 0, 'progressive bst_horde_herd', 'Beastmen Horde Building: Pyre Clearing'),
    10493: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_herd_2', itemType.building, 1, 'progressive bst_horde_herd', 'Beastmen Horde Building: Hag Tree Copse'),
    10494: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_herd_3', itemType.building, 2, 'progressive bst_horde_herd', 'Beastmen Horde Building: Squalid Encampment'),
    10495: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_herd_4', itemType.building, 3, 'progressive bst_horde_herd', 'Beastmen Horde Building: Bloodied Lair'),
    10496: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_herd_5', itemType.building, 4, 'progressive bst_horde_herd', 'Beastmen Horde Building: Cursed Labyrinth'),
    10497: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_minotaurs_1', itemType.building, 0, 'progressive bst_horde_minotaurs', 'Beastmen Horde Building: Fire Pit'),
    10498: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_minotaurs_2', itemType.building, 1, 'progressive bst_horde_minotaurs', 'Beastmen Horde Building: Meat Larder'),
    10499: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_terror_1', itemType.building, 0, 'progressive bst_horde_dread', 'Beastmen Horde Building: Heads on Spikes'),
    10500: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_terror_2', itemType.building, 1, 'progressive bst_horde_dread', 'Beastmen Horde Building: Impaled Corpses'),
    10501: itemData(IC.useful, 1, 'wh2_dlc17_horde_beastmen_army_buffs_terror_3', itemType.building, 2, 'progressive bst_horde_dread', 'Beastmen Horde Building: Hole of Beast-Filth'),
    10502: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_weapons_1', itemType.building, 0, 'progressive bst_horde_weapons', 'Beastmen Horde Building: Mound of Blades'),
    10503: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_weapons_2', itemType.building, 1, 'progressive bst_horde_weapons', 'Beastmen Horde Building: Totem of Horns'),
    10504: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_ruination_1', itemType.building, 0, 'progressive bst_horde_ruination', 'Beastmen Horde Building: Pile of Flesh'),
    10505: itemData(IC.useful, 1, 'wh_dlc03_horde_beastmen_ruination_2', itemType.building, 1, 'progressive bst_horde_ruination', 'Beastmen Horde Building: Desecrated Altar')
}

techs: dict[int, itemData] = {
    10800: itemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_locked', itemType.tech, 1, 'progressive tech_bst_wrath', 'Beastmen Tech: Days of Wrath'),
    10801: itemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_1', itemType.tech, 2, 'progressive tech_bst_wrath', 'Beastmen Tech: Rampage!'),
    10808: itemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_2', itemType.tech, 2, 'progressive tech_bst_wrath', 'Beastmen Tech: The Rewards of Ruin'),
    10812: itemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_3', itemType.tech, 2, 'progressive tech_bst_wrath', 'Beastmen Tech: Roaming Torment'),
    10816: itemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_4', itemType.tech, 2, 'progressive tech_bst_wrath', 'Beastmen Tech: The Kalkengard Larder'),

    10802: itemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_locked', itemType.tech, 1, 'progressive tech_bst_beasts', 'Beastmen Tech: Empire of Beasts'),
    10803: itemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_4', itemType.tech, 2, 'progressive tech_bst_beasts', 'Beastmen Tech: Bestial Resilience'),
    10809: itemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_2', itemType.tech, 2, 'progressive tech_bst_beasts', 'Beastmen Tech: Rolling Death'),
    10813: itemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_3', itemType.tech, 2, 'progressive tech_bst_beasts', 'Beastmen Tech: Man-Cleavers'),
    10817: itemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_1', itemType.tech, 2, 'progressive tech_bst_beasts', 'Beastmen Tech: Gaze of the Dark Gods'),

    10804: itemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_locked', itemType.tech, 1, 'progressive tech_bst_order', 'Beastmen Tech: The Unnatural Order'),
    10805: itemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_1', itemType.tech, 2, 'progressive tech_bst_order', 'Beastmen Tech: Savage Mantle'),
    10810: itemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_4', itemType.tech, 2, 'progressive tech_bst_order', 'Beastmen Tech: Death from the Shadows'),
    10814: itemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_3', itemType.tech, 2, 'progressive tech_bst_order', 'Beastmen Tech: Vitriolic Temperament'),
    10818: itemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_2', itemType.tech, 2, 'progressive tech_bst_order', 'Beastmen Tech: Smell Their Fear'),

    10806: itemData(IC.useful, 1, 'tech_dlc17_bst_empire_locked', itemType.tech, 1, 'progressive tech_bst_horns', 'Beastmen Tech: Plight of the No-Horns'),
    10807: itemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_1', itemType.tech, 2, 'progressive tech_bst_horns', 'Beastmen Tech: Raining Blood'),
    10811: itemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_2', itemType.tech, 2, 'progressive tech_bst_horns', 'Beastmen Tech: Worldbane'),
    10815: itemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_3', itemType.tech, 2, 'progressive tech_bst_horns', 'Beastmen Tech: Born to Lead'),
    10819: itemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_4', itemType.tech, 2, 'progressive tech_bst_horns', 'Beastmen Tech: On Cloven Hoof & Twisted Claw'),

    10820: itemData(IC.useful, 1, 'tech_dlc17_bst_the_single_entity_tech', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Horns of War'),
    10821: itemData(IC.useful, 1, 'tech_dlc17_bst_unfavoured_battle', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: The Strong Survive'),
    10822: itemData(IC.useful, 1, 'tech_dlc17_bst_the_no_unit_loss', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Messenger of the Bray'),
    10823: itemData(IC.useful, 1, 'tech_dlc17_bst_chariot_only', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Primal Fury'),
    10824: itemData(IC.useful, 1, 'tech_dlc17_bst_four_battles', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: The Warherd Ravages'),
    10825: itemData(IC.useful, 1, 'tech_dlc17_bst_fifteen_spells', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Kadon Unleashed'),
    10826: itemData(IC.useful, 1, 'tech_dlc17_bst_bloodgrounds_everywhere', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Dominate the World'),
    10827: itemData(IC.useful, 1, 'tech_dlc17_bst_wipe_out_faction', itemType.tech, 1, 'progressive bst_tech_challenges', 'Beastmen Tech: Consume Order')
}

progUnits: dict[int, itemData] = {
    11200: itemData(IC.useful, 4, "progressive bst_inf", itemType.unit, 4, None, "Progressive Beastmen Unit: Infantry"),
    11201: itemData(IC.useful, 1, "progressive bst_rng", itemType.unit, 1, None, "Progressive Beastmen Unit: Ranged"),
    11202: itemData(IC.useful, 2, "progressive bst_cav", itemType.unit, 2, None, "Progressive Beastmen Unit: Cavalry"),
    11203: itemData(IC.useful, 1, "progressive bst_art", itemType.unit, 1, None, "Progressive Beastmen Unit: Artillery"),
    11205: itemData(IC.useful, 4, "progressive bst_bst", itemType.unit, 4, None, "Progressive Beastmen Unit: Beast"),
    11206: itemData(IC.useful, 2, "progressive bst_hro", itemType.unit, 2, None, "Progressive Beastmen Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    11300: itemData(IC.useful, 5, 'progressive bst_settlement_major', itemType.building, 5, None, 'Progressive Beastmen Building: Settlement Major'),
    11301: itemData(IC.useful, 3, 'progressive bst_special_secondary_attributes', itemType.building, 3, None, 'Progressive Beastmen Building: Special Secondary Attributes'),
    11302: itemData(IC.useful, 3, 'progressive bst_special_secondary_attrition', itemType.building, 3, None, 'Progressive Beastmen Building: Special Secondary Attrition'),
    11303: itemData(IC.useful, 3, 'progressive bst_special_secondary_resistances', itemType.building, 3, None, 'Progressive Beastmen Building: Special Secondary Resistances'),
    11304: itemData(IC.useful, 3, 'progressive bst_special_secondary_spell', itemType.building, 3, None, 'Progressive Beastmen Building: Special Secondary Spell'),
    11305: itemData(IC.useful, 3, 'progressive bst_allied_outpost', itemType.building, 3, None, 'Progressive Beastmen Building: Allied Outpost'),
    11306: itemData(IC.useful, 2, 'progressive bst_horde_arcane', itemType.building, 3, None, 'Progressive Beastmen Horde: Magic'),
    11307: itemData(IC.useful, 2, 'progressive bst_horde_centigors', itemType.building, 2, None, 'Progressive Beastmen Horde: Centigors'),
    11308: itemData(IC.useful, 2, 'progressive bst_horde_creatures', itemType.building, 3, None, 'Progressive Beastmen Horde: Creatures'),
    11309: itemData(IC.useful, 2, 'progressive bst_horde_giants', itemType.building, 2, None, 'Progressive Beastmen Horde: Giants'),
    11310: itemData(IC.useful, 2, 'progressive bst_horde_gors', itemType.building, 3, None, 'Progressive Beastmen Horde: Cloven Ones'),
    11311: itemData(IC.useful, 2, 'progressive bst_horde_herd', itemType.building, 5, None, 'Progressive Beastmen Horde: Warherd'),
    11312: itemData(IC.useful, 2, 'progressive bst_horde_minotaurs', itemType.building, 2, None, 'Progressive Beastmen Horde: Minotaurs'),
    11313: itemData(IC.useful, 2, 'progressive bst_horde_dread', itemType.building, 3, None, 'Progressive Beastmen Horde: Dread'),
    11314: itemData(IC.useful, 2, 'progressive bst_horde_weapons', itemType.building, 2, None, 'Progressive Beastmen Horde: Weapons'),
    11315: itemData(IC.useful, 2, 'progressive bst_horde_ruination', itemType.building, 2, None, 'Progressive Beastmen Horde: Ruination'),
}

progTechs: dict[int, itemData] = {
    11400: itemData(IC.useful, 1, "progressive tech_bst_wrath", itemType.tech, 1, None, "Progressive Beastmen Tech: Tech Tree 4"),
    11401: itemData(IC.useful, 1, "progressive tech_bst_beasts", itemType.tech, 1, None, "Progressive Beastmen Tech: Tech Tree 3"),
    11402: itemData(IC.useful, 1, "progressive tech_bst_order", itemType.tech, 1, None, "Progressive Beastmen Tech: Tech Tree 2"),
    11403: itemData(IC.useful, 1, "progressive bst_horns", itemType.tech, 1, None, "Progressive Beastmen Tech: Tech Tree 1"),
    11404: itemData(IC.useful, 1, "progressive bst_tech_challenges", itemType.tech, 1, None, "Progressive Beastmen Tech: Challenges"),
}

special: dict[int, specialItemData] = {

}

rituals: dict[int, specialItemData] = {
    11600: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_bestigor_herd", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Bestigor Herd Capacity"),
    11601: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_centigors_all", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Centigors Capacity"),
    11602: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_chaos_spawn_giants", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Chaos Spawn & Giants Capacity"),
    11603: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_chaos_warhounds_poison_razorgor_herd", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Warhounds & Razorgor Herd Capacity"),
    11604: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_cygor", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Cygor Capacity"),
    11605: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_ghorgon", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Ghorgon Capacity"),
    11606: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_gor_herd_all", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Gor Herd Capacity"),
    11607: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_harpies_feral_manticore", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Harpies & Manticore Capacity"),
    11608: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_jabberslythe", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Jabberslythe Capacity"),
    11609: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_minotaurs", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Minotaurs Capacity"),
    11610: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_minotaurs_great_weapons", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Minotaurs (Great Weapons) Capacity"),
    11611: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_minotaurs_shield", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Minotaurs (Shields) Capacity"),
    11612: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_tuskgor_chariots_razorgor_chariot", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Chariots Capacity"),
    11613: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_unit_cap_ungor_herd_spearmen_herd", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Ungor Herd & Spearmen Herd Capacity"),
    11614: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc24_bst_ritual_unit_cap_incarnate_elemental_beasts", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Incarnate Elemental of Beasts Capacity"),
    11615: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc24_bst_ritual_unit_cap_tzaangors", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Tzaangors Capacity"),
    11616: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc25_bst_ritual_unit_cap_pestigors", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Pestigors Capacity"),
    11617: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc26_bst_ritual_unit_cap_khorngors", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Khorngors Capacity"),
    11618: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc27_bst_ritual_unit_cap_chimera_preyton", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Chimera and Preyton Capacity"),
    11619: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh3_dlc27_bst_ritual_unit_cap_slaangors", itemType.ritual, 1, "progressive bst_ritual_capacity", False, False, "Beastmen Unit Caps: Slaangors Capacity"),

    11620: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_horde_lvl_1", itemType.ritual, 1, "progressive bst_ritual_horde_upgrade", False, False, "Beastmen Upgrade: Horde level 1"),
    11621: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_horde_lvl_2", itemType.ritual, 2, "progressive bst_ritual_horde_upgrade", True, False, "Beastmen Upgrade: Horde level 2"),
    11622: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_horde_lvl_3", itemType.ritual, 3, "progressive bst_ritual_horde_upgrade", True, False, "Beastmen Upgrade: Horde level 3"),
    11623: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_lord_level_5", itemType.ritual, 1, "progressive bst_ritual_lord_upgrade", False, False, "Beastmen Upgrade: Lord & Hero Rank 5"),
    11624: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_lord_level_10", itemType.ritual, 2, "progressive bst_ritual_lord_upgrade", True, False, "Beastmen Upgrade: Lord & Hero Rank 10"),
    11625: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_upgrade_lord_level_15", itemType.ritual, 3, "progressive bst_ritual_lord_upgrade", True, False, "Beastmen Upgrade: Lord & Hero Rank 15"),
    11626: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_herdstone_upgrade_1", itemType.ritual, 1, "progressive bst_ritual_herdstone_upgrade", False, False, "Beastmen Upgrade: Rune-Covered Herdstones Upgrade"),
    11627: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_herdstone_upgrade_2", itemType.ritual, 2, "progressive bst_ritual_herdstone_upgrade", True, False, "Beastmen Upgrade: Bone-Strewn Herdstones Upgrade"),
    11628: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_herdstone_upgrade_3", itemType.ritual, 3, "progressive bst_ritual_herdstone_upgrade", True, False, "Beastmen Upgrade: Spired Herdstones Upgrade"),
    11629: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_herdstone_upgrade_4", itemType.ritual, 4, "progressive bst_ritual_herdstone_upgrade", True, False, "Beastmen Upgrade: Great Herdstones Upgrade"),

    11630: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_common_1", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Fell-Axe of the Drakwald"),
    11631: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_common_2", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Shardstone Amulet"),
    11632: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_common_3", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Battle-Scarred Ungor Raider"),
    11633: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_uncommon_1", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Mutated Ghorgon Hide"),
    11634: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_uncommon_2", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Cloak of Unreality"),
    11635: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_uncommon_3", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Banner of Unholy Exultation"),
    11636: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_rare_1", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Banner of Ghorok"),
    11637: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_rare_2", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Blind Eye of Seeing"),
    11638: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_unique_1", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Champion's Essence"),
    11639: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_item_unique_2", itemType.ritual, 1, "progressive bst_ritual_item", False, False, "Beastmen Item: Banner of Madness"),

    11640: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_hero_capacity_bray_shaman", itemType.ritual, 1, "progressive bst_ritual_hero_capacity", False, False, "Beastmen Heroes: Bray Shaman Hero Capacity"),
    11641: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_hero_capacity_gorebull", itemType.ritual, 1, "progressive bst_ritual_hero_capacity", False, False, "Beastmen Heroes: Gorebull Hero Capacity"),
    11642: specialItemData(IC.useful, 1, ["wh_dlc03_bst_beastmen","wh2_dlc17_bst_malagor","wh_dlc05_bst_morghur_herd","wh2_dlc17_bst_taurox", "wh2_main_bst_manblight", "wh2_main_bst_ripper_horn"], "wh2_dlc17_bst_ritual_hero_capacity_wargor", itemType.ritual, 1, "progressive bst_ritual_hero_capacity", False, False, "Beastmen Heroes: Increase Wargor Hero Capacity"),

    11643: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_1_option_1", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 1: Eldritch Onslaught"),
    11644: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_1_option_2", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 1: Unyielding Onslaught"),
    11645: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_1_option_3", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 1: Bloodthirsty Onslaught"),
    11646: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_1_option_4", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 1: Horrific Onslaught"),
    11647: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_2_option_1", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 2: Stampede of Spoils"),
    11648: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_2_option_2", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 2: Stampede of Dread"),
    11649: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_2_option_3", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 2: Stampede of Morrslieb"),
    11650: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_2_option_4", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 2: Stampede of the Chosen"),
    11651: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_3_option_1", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 3: Call of the Gorebulls"),
    11652: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_3_option_2", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 3: Call of the Bray-Shamans"),
    11653: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_3_option_3", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 3: Call of the Wargors"),
    11654: specialItemData(IC.useful, 1, ["wh2_dlc17_bst_taurox"], "wh2_dlc17_taurox_bst_rampage_tier_3_option_4", itemType.ritual, 1, "progressive bst_ritual_rampage", True, False, "Beastmen Rampage Tier 3: Call of the Minotaurs"),
}
"""
wh2_dlc17_bst_ritual_legendary_lord_khazrak	Unlock Khazrak, the One-Eyed	Khazrak will be recruitable for your army!
wh2_dlc17_bst_ritual_legendary_lord_malagor	Unlock Malagor, the Dark Omen	Malagor will be recruitable for your army!
wh2_dlc17_bst_ritual_legendary_lord_morgur	Unlock Morghur, the Shadowgave	Morghur will be recruitable for your army!
wh2_dlc17_bst_ritual_legendary_lord_taurox	Unlock Taurox, the Brass Bull!	Taurox will be recruitable for your army!
"""