from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData

# @formatter:off
units: dict[int, itemData] = {
    14000: itemData(IC.useful, 1, 'wh3_main_cth_inf_peasant_spearmen_1', itemType.unit, 1, 'Progressive cth_inf', 'Cathay Unit: Peasant Long Spearmen'),
    14001: itemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warriors_0', itemType.unit, 1, 'Progressive cth_inf', 'Cathay Unit: Jade Warriors'),
    14002: itemData(IC.useful, 1, 'wh3_dlc24_cth_inf_onyx_crowmen', itemType.unit, 2, 'Progressive cth_inf', 'Cathay Unit: Onyx Crowmen'),
    14003: itemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warriors_1', itemType.unit, 3, 'Progressive cth_inf', 'Cathay Unit: Jade Warriors (Halberds)'),
    14004: itemData(IC.useful, 1, 'wh3_main_cth_inf_dragon_guard_0', itemType.unit, 4, 'Progressive cth_inf', 'Cathay Unit: Celestial Dragon Guard'),
    14005: itemData(IC.useful, 1, 'wh3_main_cth_inf_peasant_archers_0', itemType.unit, 1, 'Progressive cth_rng', 'Cathay Unit: Peasant Archers'),
    14006: itemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warrior_crossbowmen_0', itemType.unit, 2, 'Progressive cth_rng', 'Cathay Unit: Jade Warrior Crossbows'),
    14007: itemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warrior_crossbowmen_1', itemType.unit, 3, 'Progressive cth_rng', 'Cathay Unit: Jade Warrior Crossbows (Shields)'),
    14008: itemData(IC.useful, 1, 'wh3_main_cth_inf_iron_hail_gunners_0', itemType.unit, 2, 'Progressive cth_rng', 'Cathay Unit: Iron Hail Gunners'),
    14009: itemData(IC.useful, 1, 'wh3_main_cth_inf_grenadiers', itemType.unit, 2, 'Progressive cth_rng', 'Cathay Unit: Nan-Gau Grenadiers'),
    14010: itemData(IC.useful, 1, 'wh3_main_cth_inf_crane_gunners_0', itemType.unit, 3, 'Progressive cth_rng', 'Cathay Unit: Crane Gunners'),
    14011: itemData(IC.useful, 1, 'wh3_main_cth_inf_dragon_guard_crossbowmen_0', itemType.unit, 4, 'Progressive cth_rng', 'Cathay Unit: Celestial Dragon Crossbows'),
    14012: itemData(IC.useful, 1, 'wh3_main_cth_cav_peasant_horsemen_0', itemType.unit, 1, 'Progressive cth_cav', 'Cathay Unit: Peasant Horsemen'),
    14013: itemData(IC.useful, 1, 'wh3_main_cth_cav_jade_lancers_0', itemType.unit, 2, 'Progressive cth_cav', 'Cathay Unit: Jade Lancers'),
    14014: itemData(IC.useful, 1, 'wh3_main_cth_cav_jade_longma_riders_0', itemType.unit, 3, 'Progressive cth_cav', 'Cathay Unit: Great Longma Riders'),
    14015: itemData(IC.useful, 1, 'wh3_main_cth_art_grand_cannon_0', itemType.unit, 1, 'Progressive cth_art', 'Cathay Unit: Grand Cannons'),
    14016: itemData(IC.useful, 1, 'wh3_main_cth_art_fire_rain_rocket_battery_0', itemType.unit, 2, 'Progressive cth_art', 'Cathay Unit: Fire Rain Rocket Battery'),
    14017: itemData(IC.useful, 1, 'wh3_dlc24_cth_veh_zhangu_war_drum', itemType.unit, 1, 'Progressive cth_veh', 'Cathay Unit: Zhangu War Drum'),
    14018: itemData(IC.useful, 1, 'wh3_main_cth_veh_sky_lantern_0', itemType.unit, 2, 'Progressive cth_veh', 'Cathay Unit: Sky Lantern'),
    14019: itemData(IC.useful, 1, 'wh3_main_cth_veh_war_compass_0', itemType.unit, 3, 'Progressive cth_veh', 'Cathay Unit: Wu Xing War Compass'),
    14020: itemData(IC.useful, 1, 'wh3_main_cth_veh_sky_junk_0', itemType.unit, 4, 'Progressive cth_veh', 'Cathay Unit: Sky-junk'),
    14021: itemData(IC.useful, 1, 'wh3_dlc24_cth_mon_jet_lion', itemType.unit, 1, 'Progressive cth_bst', 'Cathay Unit: Jet Lion'),
    14022: itemData(IC.useful, 1, 'wh3_dlc24_cth_mon_jade_lion', itemType.unit, 1, 'Progressive cth_bst', 'Cathay Unit: Jade Lion'),
    14023: itemData(IC.useful, 1, 'wh3_dlc24_cth_mon_celestial_lion', itemType.unit, 1, 'Progressive cth_bst', 'Cathay Unit: Celestial Lion'),
    14024: itemData(IC.useful, 1, 'wh3_dlc24_cth_mon_great_moon_bird', itemType.unit, 2, 'Progressive cth_bst', 'Cathay Unit: Great Moon Bird'),
    14025: itemData(IC.useful, 1, 'wh3_main_cth_mon_terracotta_sentinel_0', itemType.unit, 3, 'Progressive cth_bst', 'Cathay Unit: Terracotta Sentinel'),
    14026: itemData(IC.useful, 1, 'wh3_dlc24_cth_cha_gate_master', itemType.unit, 1, 'Progressive cth_hro', 'Cathay Unit: Gate Master'),
    14027: itemData(IC.useful, 1, 'wh3_main_cth_cha_astromancer_0', itemType.unit, 1, 'Progressive cth_hro', 'Cathay Unit: Astromancer'),
    14028: itemData(IC.useful, 1, 'wh3_main_cth_cha_alchemist_0', itemType.unit, 1, 'Progressive cth_hro', 'Cathay Unit: Alchemist'),
    14029: itemData(IC.useful, 1, 'wh3_twa10_cth_inf_peasant_archers_ror', itemType.unit, 1, 'Progressive cth_rng', 'Cathay Unit: Bandits of the Silver Road (Peasant Archers)'),
    14030: itemData(IC.useful, 1, 'wh3_twa08_cth_mon_terracotta_sentinel_0_ror', itemType.unit, 3, 'Progressive cth_bst', 'Cathay Unit: The Green Guardian (Terracotta Sentinel)'),
    14031: itemData(IC.useful, 1, 'wh3_twa07_cth_cav_jade_longma_riders_ror_0', itemType.unit, 3, 'Progressive cth_cav', 'Cathay Unit: Righteous Lances of Wei-Jin (Great Longma Riders)'),
    14032: itemData(IC.useful, 1, 'wh3_twa06_cth_inf_dragon_guard_ror_0', itemType.unit, 4, 'Progressive cth_inf', 'Cathay Unit: The Dune Dragons (Celestial Dragon Guard)'),
    14033: itemData(IC.useful, 1, 'wh3_dlc24_cth_inf_dragon_guard_crossbowmen_ror', itemType.unit, 4, 'Progressive cth_rng', 'Cathay Unit: The Grace of Quai Yin (Celestial Dragon Crossbows)'),
    14034: itemData(IC.useful, 1, 'wh3_dlc24_cth_inf_onyx_crowmen_ror', itemType.unit, 2, 'Progressive cth_inf', 'Cathay Unit: Empress Crowmen (Onyx Crowmen)'),
    14035: itemData(IC.useful, 1, 'wh3_dlc24_cth_veh_zhangu_war_drum_ror', itemType.unit, 1, 'Progressive cth_veh', 'Cathay Unit: The Jade War Drum (Zhangu War Drum)')
}

buildings: dict[int, itemData] = {
    14400: itemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_1', itemType.building, 0, 'Progressive cth_allied_outpost', 'Cathay Building: Cathayan Outpost'),
    14401: itemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_2', itemType.building, 1, 'Progressive cth_allied_outpost', 'Cathay Building: Cathayan District'),
    14402: itemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_3', itemType.building, 2, 'Progressive cth_allied_outpost', 'Cathay Building: Cathayan Colony'),
    14403: itemData(IC.useful, 1, 'wh3_main_cth_artillery_1', itemType.building, 0, 'Progressive cth_artillery', 'Cathay Building: Alchemist Tower'),
    14404: itemData(IC.useful, 1, 'wh3_main_cth_artillery_2', itemType.building, 1, 'Progressive cth_artillery', 'Cathay Building: Powder Tower'),
    14405: itemData(IC.useful, 1, 'wh3_main_cth_artillery_3', itemType.building, 1, 'Progressive cth_artillery', 'Cathay Building: Mooring Tower'),
    14406: itemData(IC.useful, 1, 'wh3_main_cth_bastion_1_1', itemType.building, 0, 'Progressive cth_bastion', 'Cathay Building: Bastion Gaol'),
    14407: itemData(IC.useful, 1, 'wh3_main_cth_bastion_1_2', itemType.building, 1, 'Progressive cth_bastion', 'Cathay Building: Bastion Hospice'),
    14408: itemData(IC.useful, 1, 'wh3_main_cth_bastion_1_3', itemType.building, 2, 'Progressive cth_bastion', 'Cathay Building: Bastion Shrine'),
    14409: itemData(IC.useful, 1, 'wh3_main_cth_bastion_1_4', itemType.building, 3, 'Progressive cth_bastion', 'Cathay Building: Bastion Temple'),
    14410: itemData(IC.useful, 1, 'wh3_main_cth_bastion_1_5', itemType.building, 4, 'Progressive cth_bastion', 'Cathay Building: Bastion Pagoda'),
    14411: itemData(IC.useful, 1, 'wh3_main_cth_bastion_2_1', itemType.building, 0, 'Progressive cth_bastion', 'Cathay Building: Bastion Watch Mast'),
    14412: itemData(IC.useful, 1, 'wh3_main_cth_bastion_2_2', itemType.building, 1, 'Progressive cth_bastion', 'Cathay Building: Bastion Barracks'),
    14413: itemData(IC.useful, 1, 'wh3_main_cth_bastion_2_3', itemType.building, 2, 'Progressive cth_bastion', 'Cathay Building: Bastion Quarters'),
    14414: itemData(IC.useful, 1, 'wh3_main_cth_bastion_2_4', itemType.building, 3, 'Progressive cth_bastion', 'Cathay Building: Bastion Overlook'),
    14415: itemData(IC.useful, 1, 'wh3_main_cth_bastion_2_5', itemType.building, 4, 'Progressive cth_bastion', 'Cathay Building: Bastion Command Tower'),
    14416: itemData(IC.useful, 1, 'wh3_main_cth_bastion_3_1', itemType.building, 0, 'Progressive cth_bastion', 'Cathay Building: Bastion Lumber Pile'),
    14417: itemData(IC.useful, 1, 'wh3_main_cth_bastion_3_2', itemType.building, 1, 'Progressive cth_bastion', 'Cathay Building: Bastion Mill'),
    14418: itemData(IC.useful, 1, 'wh3_main_cth_bastion_3_3', itemType.building, 2, 'Progressive cth_bastion', 'Cathay Building: Bastion Siegeworks'),
    14419: itemData(IC.useful, 1, 'wh3_main_cth_bastion_3_4', itemType.building, 3, 'Progressive cth_bastion', 'Cathay Building: Bastion Foundry'),
    14420: itemData(IC.useful, 1, 'wh3_main_cth_bastion_3_5', itemType.building, 4, 'Progressive cth_bastion', 'Cathay Building: Bastion Arsenal'),
    14421: itemData(IC.useful, 1, 'wh3_main_cth_bastion_4_1', itemType.building, 0, 'Progressive cth_bastion', 'Cathay Building: Bastion Water Station'),
    14422: itemData(IC.useful, 1, 'wh3_main_cth_bastion_4_2', itemType.building, 1, 'Progressive cth_bastion', 'Cathay Building: Bastion Mess Hall'),
    14423: itemData(IC.useful, 1, 'wh3_main_cth_bastion_4_3', itemType.building, 2, 'Progressive cth_bastion', 'Cathay Building: Bastion Feast Hall'),
    14424: itemData(IC.useful, 1, 'wh3_main_cth_bastion_4_4', itemType.building, 3, 'Progressive cth_bastion', 'Cathay Building: Bastion Parlour'),
    14425: itemData(IC.useful, 1, 'wh3_main_cth_bastion_4_5', itemType.building, 4, 'Progressive cth_bastion', 'Cathay Building: Bastion Grand Parlour'),
    #14426: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_1', ItemType.building, 1, 'Progressive cth_settlement_major', 'Cathay Building: Bastion Gatehouse'),
    #14427: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_2', ItemType.building, 2, 'Progressive cth_settlement_major', 'Cathay Building: Bastion Tower'),
    #14428: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_3', ItemType.building, 3, 'Progressive cth_settlement_major', 'Cathay Building: Bastion Citadel'),
    #14429: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_4', ItemType.building, 4, 'Progressive cth_settlement_major', 'Cathay Building: Bastion Stronghold'),
    #14430: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_5', ItemType.building, 5, 'Progressive cth_settlement_major', 'Cathay Building: Bastion Fortress'),
    14431: itemData(IC.useful, 1, 'wh3_main_cth_cavalry_1', itemType.building, 0, 'Progressive cth_cavalry', 'Cathay Building: Corral'),
    14432: itemData(IC.useful, 1, 'wh3_main_cth_cavalry_2', itemType.building, 1, 'Progressive cth_cavalry', 'Cathay Building: Jade Stables'),
    14433: itemData(IC.useful, 1, 'wh3_main_cth_cavalry_3', itemType.building, 2, 'Progressive cth_cavalry', 'Cathay Building: Longma Paddocks'),
    14434: itemData(IC.useful, 1, 'wh3_main_cth_celestial_1', itemType.building, 0, 'Progressive cth_celestial', 'Cathay Building: Celestial Barracks'),
    14435: itemData(IC.useful, 1, 'wh3_main_cth_celestial_2', itemType.building, 1, 'Progressive cth_celestial', 'Cathay Building: Celestial Armoury'),
    14436: itemData(IC.useful, 1, 'wh3_main_cth_defence_yang_1', itemType.building, 0, 'Progressive cth_defence_yang', 'Cathay Building: Ramparts'),
    14437: itemData(IC.useful, 1, 'wh3_main_cth_defence_yang_2', itemType.building, 1, 'Progressive cth_defence_yang', 'Cathay Building: Cannon Emplacements'),
    14438: itemData(IC.useful, 1, 'wh3_main_cth_defence_yang_3', itemType.building, 2, 'Progressive cth_defence_yang', 'Cathay Building: Artillery Batteries'),
    14439: itemData(IC.useful, 1, 'wh3_main_cth_defence_yin_1', itemType.building, 0, 'Progressive cth_defence_yin', 'Cathay Building: Archer Platforms'),
    14440: itemData(IC.useful, 1, 'wh3_main_cth_defence_yin_2', itemType.building, 1, 'Progressive cth_defence_yin', 'Cathay Building: Archer Towers'),
    14441: itemData(IC.useful, 1, 'wh3_main_cth_defence_yin_3', itemType.building, 2, 'Progressive cth_defence_yin', 'Cathay Building: Sky Lantern Roosts'),
    14442: itemData(IC.useful, 1, 'wh3_main_cth_growth_yang_1', itemType.building, 0, 'Progressive cth_growth_yang', 'Cathay Building: Labour Conscription Bureau'),
    14443: itemData(IC.useful, 1, 'wh3_main_cth_growth_yang_2', itemType.building, 1, 'Progressive cth_growth_yang', 'Cathay Building: Bamboo Scaffold Depot'),
    14444: itemData(IC.useful, 1, 'wh3_main_cth_growth_yang_3', itemType.building, 2, 'Progressive cth_growth_yang', 'Cathay Building: Lumber Mill'),
    14445: itemData(IC.useful, 1, 'wh3_main_cth_growth_yin_1', itemType.building, 0, 'Progressive cth_growth_yin', 'Cathay Building: Tea Parlour'),
    14446: itemData(IC.useful, 1, 'wh3_main_cth_growth_yin_2', itemType.building, 1, 'Progressive cth_growth_yin', 'Cathay Building: Contemplation Gardens'),
    14447: itemData(IC.useful, 1, 'wh3_main_cth_growth_yin_3', itemType.building, 2, 'Progressive cth_growth_yin', 'Cathay Building: Administration Centre'),
    14448: itemData(IC.useful, 1, 'wh3_main_cth_gunners_1', itemType.building, 0, 'Progressive cth_gunners', 'Cathay Building: Nan-Gau Forge'),
    14449: itemData(IC.useful, 1, 'wh3_main_cth_gunners_2', itemType.building, 1, 'Progressive cth_gunners', 'Cathay Building: Powder Magazine'),
    14450: itemData(IC.useful, 1, 'wh3_main_cth_gunners_3', itemType.building, 2, 'Progressive cth_gunners', 'Cathay Building: Fire Rain Silo'),
    14451: itemData(IC.useful, 1, 'wh3_main_cth_income_yang_1', itemType.building, 0, 'Progressive cth_income_yang', 'Cathay Building: Wares Market'),
    14452: itemData(IC.useful, 1, 'wh3_main_cth_income_yang_2', itemType.building, 1, 'Progressive cth_income_yang', 'Cathay Building: Merchant Caravans'),
    14453: itemData(IC.useful, 1, 'wh3_main_cth_income_yang_3', itemType.building, 2, 'Progressive cth_income_yang', 'Cathay Building: Trade Exchange'),
    14454: itemData(IC.useful, 1, 'wh3_main_cth_income_yin_1', itemType.building, 0, 'Progressive cth_income_yin', 'Cathay Building: Yin Spice Market'),
    14455: itemData(IC.useful, 1, 'wh3_main_cth_income_yin_2', itemType.building, 1, 'Progressive cth_income_yin', 'Cathay Building: Gem Factors'),
    14456: itemData(IC.useful, 1, 'wh3_main_cth_income_yin_3', itemType.building, 2, 'Progressive cth_income_yin', 'Cathay Building: Goods Emporium'),
    14457: itemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_1', itemType.building, 0, 'Progressive cth_jade_barracks', 'Cathay Building: Training Camp'),
    14458: itemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_2', itemType.building, 1, 'Progressive cth_jade_barracks', 'Cathay Building: Dormitory'),
    14459: itemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_3', itemType.building, 2, 'Progressive cth_jade_barracks', 'Cathay Building: Jade Barracks'),
    14460: itemData(IC.useful, 1, 'wh3_main_cth_magic_tower_1', itemType.building, 0, 'Progressive cth_magic_tower', 'Cathay Building: Celestial Tower'),
    14461: itemData(IC.useful, 1, 'wh3_main_cth_magic_tower_2', itemType.building, 1, 'Progressive cth_magic_tower', 'Cathay Building: Celestial Observatory'),
    14462: itemData(IC.useful, 1, 'wh3_main_cth_magic_tower_3', itemType.building, 2, 'Progressive cth_magic_tower', 'Cathay Building: Celestial Beacon'),
    14463: itemData(IC.useful, 1, 'wh3_main_cth_order_yang_1', itemType.building, 0, 'Progressive cth_order_yang', 'Cathay Building: Conscription Office'),
    14464: itemData(IC.useful, 1, 'wh3_main_cth_order_yang_2', itemType.building, 1, 'Progressive cth_order_yang', 'Cathay Building: Temple of Yang'),
    14465: itemData(IC.useful, 1, 'wh3_main_cth_order_yang_3', itemType.building, 2, 'Progressive cth_order_yang', 'Cathay Building: Yang Sanctuary'),
    14466: itemData(IC.useful, 1, 'wh3_main_cth_order_yin_1', itemType.building, 0, 'Progressive cth_order_yin', 'Cathay Building: Conscription Field'),
    14467: itemData(IC.useful, 1, 'wh3_main_cth_order_yin_2', itemType.building, 1, 'Progressive cth_order_yin', 'Cathay Building: Shrine of Yin'),
    14468: itemData(IC.useful, 1, 'wh3_main_cth_order_yin_3', itemType.building, 2, 'Progressive cth_order_yin', 'Cathay Building: Yin Lodge'),
    14469: itemData(IC.useful, 1, 'wh3_main_cth_port_1', itemType.building, 0, 'Progressive cth_port', 'Cathay Building: Dock'),
    14470: itemData(IC.useful, 1, 'wh3_main_cth_port_2', itemType.building, 1, 'Progressive cth_port', 'Cathay Building: River Port'),
    14471: itemData(IC.useful, 1, 'wh3_main_cth_port_3', itemType.building, 2, 'Progressive cth_port', 'Cathay Building: Sea Port'),
    14472: itemData(IC.useful, 1, 'wh3_main_cth_resource_animals_1', itemType.building, 0, 'Progressive cth_resource_animals', 'Cathay Building: Exotic Animal Tamer'),
    14473: itemData(IC.useful, 1, 'wh3_main_cth_resource_animals_2', itemType.building, 1, 'Progressive cth_resource_animals', 'Cathay Building: Exotic Animal Pen'),
    14474: itemData(IC.useful, 1, 'wh3_main_cth_resource_animals_3', itemType.building, 2, 'Progressive cth_resource_animals', 'Cathay Building: Exotic Animal Market'),
    14475: itemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_1', itemType.building, 0, 'Progressive cth_resource_dyes', 'Cathay Building: Cinnabar Mining Pit'),
    14476: itemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_2', itemType.building, 1, 'Progressive cth_resource_dyes', 'Cathay Building: Cinnabar Mine'),
    14477: itemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_3', itemType.building, 2, 'Progressive cth_resource_dyes', 'Cathay Building: Dyemaker'),
    14478: itemData(IC.useful, 1, 'wh3_main_cth_resource_furs_1', itemType.building, 0, 'Progressive cth_resource_furs', 'Cathay Building: Hunting Camp'),
    14479: itemData(IC.useful, 1, 'wh3_main_cth_resource_furs_2', itemType.building, 1, 'Progressive cth_resource_furs', 'Cathay Building: Hunting Lodge'),
    14480: itemData(IC.useful, 1, 'wh3_main_cth_resource_furs_3', itemType.building, 2, 'Progressive cth_resource_furs', 'Cathay Building: Tannery'),
    14481: itemData(IC.useful, 1, 'wh3_main_cth_resource_gems_1', itemType.building, 0, 'Progressive cth_resource_gems', 'Cathay Building: Gem Mineshaft'),
    14482: itemData(IC.useful, 1, 'wh3_main_cth_resource_gems_2', itemType.building, 1, 'Progressive cth_resource_gems', 'Cathay Building: Gem Mine'),
    14483: itemData(IC.useful, 1, 'wh3_main_cth_resource_gems_3', itemType.building, 2, 'Progressive cth_resource_gems', "Cathay Building: Gemcutter's Workshop"),
    14484: itemData(IC.useful, 1, 'wh3_main_cth_resource_gold_1', itemType.building, 0, 'Progressive cth_resource_gold', 'Cathay Building: Gold Mining Pit'),
    14485: itemData(IC.useful, 1, 'wh3_main_cth_resource_gold_2', itemType.building, 1, 'Progressive cth_resource_gold', 'Cathay Building: Gold Mine'),
    14486: itemData(IC.useful, 1, 'wh3_main_cth_resource_gold_3', itemType.building, 2, 'Progressive cth_resource_gold', 'Cathay Building: Gold Smelter'),
    14487: itemData(IC.useful, 1, 'wh3_main_cth_resource_iron_1', itemType.building, 0, 'Progressive cth_resource_iron', 'Cathay Building: Iron Mining Pit'),
    14488: itemData(IC.useful, 1, 'wh3_main_cth_resource_iron_2', itemType.building, 1, 'Progressive cth_resource_iron', 'Cathay Building: Iron Mines'),
    14489: itemData(IC.useful, 1, 'wh3_main_cth_resource_iron_3', itemType.building, 2, 'Progressive cth_resource_iron', 'Cathay Building: Iron Smelter'),
    14490: itemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_1', itemType.building, 0, 'Progressive cth_resource_ivory', 'Cathay Building: Animal Store'),
    14491: itemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_2', itemType.building, 1, 'Progressive cth_resource_ivory', 'Cathay Building: Tusk Market'),
    14492: itemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_3', itemType.building, 2, 'Progressive cth_resource_ivory', 'Cathay Building: Tusk Compound'),
    14493: itemData(IC.useful, 1, 'wh3_main_cth_resource_marble_1', itemType.building, 0, 'Progressive cth_resource_marble', 'Cathay Building: Sawyer'),
    14494: itemData(IC.useful, 1, 'wh3_main_cth_resource_marble_2', itemType.building, 1, 'Progressive cth_resource_marble', 'Cathay Building: Marble Quarry'),
    14495: itemData(IC.useful, 1, 'wh3_main_cth_resource_marble_3', itemType.building, 2, 'Progressive cth_resource_marble', "Cathay Building: Stone Mason's Workshop"),
    14496: itemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_1', itemType.building, 0, 'Progressive cth_resource_medicine', "Cathay Building: Herb Gatherer's Camp"),
    14497: itemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_2', itemType.building, 1, 'Progressive cth_resource_medicine', 'Cathay Building: Exotic Hothouse'),
    14498: itemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_3', itemType.building, 2, 'Progressive cth_resource_medicine', 'Cathay Building: Alchemy Workshop'),
    14499: itemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_1', itemType.building, 0, 'Progressive cth_resource_obsidian', 'Cathay Building: Obsidian Quarry'),
    14500: itemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_2', itemType.building, 1, 'Progressive cth_resource_obsidian', 'Cathay Building: Obsidian Trinket Maker'),
    14501: itemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_3', itemType.building, 2, 'Progressive cth_resource_obsidian', 'Cathay Building: Obsidian Amulet Carver'),
    14502: itemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_1', itemType.building, 0, 'Progressive cth_resource_pasture', 'Cathay Building: Grazing Pastures'),
    14503: itemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_2', itemType.building, 1, 'Progressive cth_resource_pasture', 'Cathay Building: Livestock Pens'),
    14504: itemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_3', itemType.building, 2, 'Progressive cth_resource_pasture', 'Cathay Building: Cattle Ranch'),
    14505: itemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_1', itemType.building, 0, 'Progressive cth_resource_pottery', 'Cathay Building: Clay Pit'),
    14506: itemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_2', itemType.building, 1, 'Progressive cth_resource_pottery', 'Cathay Building: Pottery Maker'),
    14507: itemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_3', itemType.building, 2, 'Progressive cth_resource_pottery', 'Cathay Building: Kilns'),
    14508: itemData(IC.useful, 1, 'wh3_main_cth_resource_salt_1', itemType.building, 0, 'Progressive cth_resource_salt', 'Cathay Building: Brine Mining Pans'),
    14509: itemData(IC.useful, 1, 'wh3_main_cth_resource_salt_2', itemType.building, 1, 'Progressive cth_resource_salt', 'Cathay Building: Brine Mining Basin'),
    14510: itemData(IC.useful, 1, 'wh3_main_cth_resource_salt_3', itemType.building, 2, 'Progressive cth_resource_salt', 'Cathay Building: Saltworks'),
    14511: itemData(IC.useful, 1, 'wh3_main_cth_resource_spices_1', itemType.building, 0, 'Progressive cth_resource_spices', 'Cathay Building: Spice Market'),
    14512: itemData(IC.useful, 1, 'wh3_main_cth_resource_spices_2', itemType.building, 1, 'Progressive cth_resource_spices', 'Cathay Building: Spice Trading Post'),
    14513: itemData(IC.useful, 1, 'wh3_main_cth_resource_spices_3', itemType.building, 2, 'Progressive cth_resource_spices', 'Cathay Building: Eastern Bazaar'),
    14514: itemData(IC.useful, 1, 'wh3_main_cth_resource_wine_1', itemType.building, 0, 'Progressive cth_resource_wine', 'Cathay Building: Orchards'),
    14515: itemData(IC.useful, 1, 'wh3_main_cth_resource_wine_2', itemType.building, 1, 'Progressive cth_resource_wine', 'Cathay Building: Vineyard'),
    14516: itemData(IC.useful, 1, 'wh3_main_cth_resource_wine_3', itemType.building, 2, 'Progressive cth_resource_wine', 'Cathay Building: Vintner'),
    14517: itemData(IC.useful, 1, 'wh3_main_cth_resource_wood_1', itemType.building, 0, 'Progressive cth_resource_wood', "Cathay Building: Woodman's Hut"),
    14518: itemData(IC.useful, 1, 'wh3_main_cth_resource_wood_2', itemType.building, 1, 'Progressive cth_resource_wood', 'Cathay Building: Timber Mill'),
    14519: itemData(IC.useful, 1, 'wh3_main_cth_resource_wood_3', itemType.building, 2, 'Progressive cth_resource_wood', 'Cathay Building: Lumberyard'),
    14520: itemData(IC.useful, 1, 'wh3_main_cth_settlement_major_1', itemType.building, 0, 'Progressive cth_settlement_major', 'Cathay Building: Hamlet (Major)'),
    14521: itemData(IC.useful, 1, 'wh3_main_cth_settlement_major_2', itemType.building, 1, 'Progressive cth_settlement_major', 'Cathay Building: Village (Major)'),
    14522: itemData(IC.useful, 1, 'wh3_main_cth_settlement_major_3', itemType.building, 2, 'Progressive cth_settlement_major', 'Cathay Building: Town (Major)'),
    14523: itemData(IC.useful, 1, 'wh3_main_cth_settlement_major_4', itemType.building, 3, 'Progressive cth_settlement_major', 'Cathay Building: City (Major)'),
    14524: itemData(IC.useful, 1, 'wh3_main_cth_settlement_major_5', itemType.building, 4, 'Progressive cth_settlement_major', 'Cathay Building: Province Capital (Major)'),
    14525: itemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_1', itemType.building, 0, 'Progressive cth_settlement_minor', 'Cathay Building: Hamlet (Minor)'),
    14526: itemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_2', itemType.building, 1, 'Progressive cth_settlement_minor', 'Cathay Building: Village (Minor)'),
    14527: itemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_3', itemType.building, 2, 'Progressive cth_settlement_minor', 'Cathay Building: Town (Minor)'),
    14528: itemData(IC.useful, 1, 'wh3_main_cth_walls_minor_1', itemType.building, 0, 'Progressive cth_walls_minor', 'Cathay Building: Stockades'),
    14529: itemData(IC.useful, 1, 'wh3_main_cth_walls_minor_2', itemType.building, 1, 'Progressive cth_walls_minor', 'Cathay Building: Pagodan Walls'),
    14530: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_1', itemType.building, 0, 'Progressive foreign_slot_discovery_cth', 'Cathay Building: Sky Lantern Lookouts'),
    14531: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_2', itemType.building, 1, 'Progressive foreign_slot_discovery_cth', 'Cathay Building: Sky Lantern Scouts'),
    14532: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_3', itemType.building, 2, 'Progressive foreign_slot_discovery_cth', 'Cathay Building: Dragon Sentries')
}

techs: dict[int, itemData] = {
    14800: itemData(IC.useful, 1, 'wh3_main_tech_cth_1', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Horse Bonding'),
    14801: itemData(IC.useful, 1, 'wh3_main_tech_cth_24', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Jade Veteran Facility'),
    14802: itemData(IC.useful, 1, 'wh3_main_tech_cth_48', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Longma Bridles'),
    14803: itemData(IC.useful, 1, 'wh3_main_tech_cth_2', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Rite of Yang'),
    14804: itemData(IC.useful, 1, 'wh3_main_tech_cth_25', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Sentinel Rites'),
    14805: itemData(IC.useful, 1, 'wh3_main_tech_cth_47', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Improved Husbandry'),
    14806: itemData(IC.useful, 1, 'wh3_main_tech_cth_26', itemType.tech, 8, 'Progressive tech_cth', 'Cathay Tech: Inner Strength'),
    14807: itemData(IC.useful, 1, 'wh3_main_tech_cth_27', itemType.tech, 8, 'Progressive tech_cth', 'Cathay Tech: Yang Kiln'),
    14808: itemData(IC.useful, 1, 'wh3_main_tech_cth_28', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Mastery of Yang'),
    14809: itemData(IC.useful, 1, 'wh3_main_tech_cth_29', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Flanking Stratagems'),
    14810: itemData(IC.useful, 1, 'wh3_main_tech_cth_3', itemType.tech, 3, 'Progressive tech_cth', 'Cathay Tech: Jade Stance'),
    14811: itemData(IC.useful, 1, 'wh3_main_tech_cth_4', itemType.tech, 3, 'Progressive tech_cth', 'Cathay Tech: Bureaucrat Training'),
    14812: itemData(IC.useful, 1, 'wh3_main_tech_cth_49', itemType.tech, 14, 'Progressive tech_cth', 'Cathay Tech: Enhanced Yang Sight'),
    14813: itemData(IC.useful, 1, 'wh3_main_tech_cth_5', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Inner Chai'),
    14814: itemData(IC.useful, 1, 'wh3_main_tech_cth_50', itemType.tech, 14, 'Progressive tech_cth', 'Cathay Tech: Grace of Xen Yang'),
    14815: itemData(IC.useful, 1, 'wh3_main_tech_cth_51', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Kunlan Anvil'),
    14816: itemData(IC.useful, 1, 'wh3_main_tech_cth_52', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Dragon Fleet Aegis'),
    14817: itemData(IC.useful, 1, 'wh3_main_tech_cth_6', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Inner Speed'),
    14818: itemData(IC.useful, 1, 'wh3_main_tech_cth_30', itemType.tech, 7, 'Progressive tech_cth', 'Cathay Tech: Improved Winches'),
    14819: itemData(IC.useful, 1, 'wh3_main_tech_cth_31', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Peasant Triage'),
    14820: itemData(IC.useful, 1, 'wh3_main_tech_cth_32', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Magnetic Polarity'),
    14821: itemData(IC.useful, 1, 'wh3_main_tech_cth_53', itemType.tech, 13, 'Progressive tech_cth', 'Cathay Tech: Celestial Endurance Training'),
    14822: itemData(IC.useful, 1, 'wh3_main_tech_cth_54', itemType.tech, 15, 'Progressive tech_cth', "Cathay Tech: Thieves' Guild"),
    14823: itemData(IC.useful, 1, 'wh3_main_tech_cth_55', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Yang Reflection'),
    14824: itemData(IC.useful, 1, 'wh3_main_tech_cth_7', itemType.tech, 2, 'Progressive tech_cth', 'Cathay Tech: Drill Training'),
    14825: itemData(IC.useful, 1, 'wh3_main_tech_cth_8', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Contained Aggression'),
    14826: itemData(IC.useful, 1, 'wh3_main_tech_cth_9', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Improved Brazier'),
    14827: itemData(IC.useful, 1, 'wh3_main_tech_cth_10', itemType.tech, 1, 'Progressive tech_cth', 'Cathay Tech: Seasoned Trackers'),
    14828: itemData(IC.useful, 1, 'wh3_main_tech_cth_11', itemType.tech, 2, 'Progressive tech_cth', 'Cathay Tech: Hardened Bamboo'),
    14829: itemData(IC.useful, 1, 'wh3_main_tech_cth_12', itemType.tech, 8, 'Progressive tech_cth', 'Cathay Tech: Blessed Temple Guardians'),
    14830: itemData(IC.useful, 1, 'wh3_main_tech_cth_13', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Alchemic Mortar'),
    14831: itemData(IC.useful, 1, 'wh3_main_tech_cth_14', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Administrative Subsidies'),
    14832: itemData(IC.useful, 1, 'wh3_main_tech_cth_33', itemType.tech, 6, 'Progressive tech_cth', 'Cathay Tech: Dynastic Finishing'),
    14833: itemData(IC.useful, 1, 'wh3_main_tech_cth_34', itemType.tech, 7, 'Progressive tech_cth', 'Cathay Tech: Astromantic Choir'),
    14834: itemData(IC.useful, 1, 'wh3_main_tech_cth_35', itemType.tech, 3, 'Progressive tech_cth', 'Cathay Tech: Peasant Levy Edict'),
    14835: itemData(IC.useful, 1, 'wh3_main_tech_cth_36', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Sea Dragon Edict'),
    14836: itemData(IC.useful, 1, 'wh3_main_tech_cth_37', itemType.tech, 11, 'Progressive tech_cth', 'Cathay Tech: Nan-Gau Forges'),
    14837: itemData(IC.useful, 1, 'wh3_main_tech_cth_56', itemType.tech, 12, 'Progressive tech_cth', 'Cathay Tech: Alchemist Compact'),
    14838: itemData(IC.useful, 1, 'wh3_main_tech_cth_57', itemType.tech, 13, 'Progressive tech_cth', 'Cathay Tech: Festival Edict'),
    14839: itemData(IC.useful, 1, 'wh3_main_tech_cth_58', itemType.tech, 14, 'Progressive tech_cth', 'Cathay Tech: Incorruptible Dogma'),
    14840: itemData(IC.useful, 1, 'wh3_main_tech_cth_59', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Alignment Calibration'),
    14841: itemData(IC.useful, 1, 'wh3_main_tech_cth_60', itemType.tech, 16, 'Progressive tech_cth', "Cathay Tech: Dragon Emperor's Blessing"),
    14842: itemData(IC.useful, 1, 'wh3_main_tech_cth_70', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Widened Roads'),
    14843: itemData(IC.useful, 1, 'wh3_main_tech_cth_15', itemType.tech, 2, 'Progressive tech_cth', 'Cathay Tech: Fletching Mentors'),
    14844: itemData(IC.useful, 1, 'wh3_main_tech_cth_16', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Harmonic Balance'),
    14845: itemData(IC.useful, 1, 'wh3_main_tech_cth_17', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Chelonian Stance'),
    14846: itemData(IC.useful, 1, 'wh3_main_tech_cth_38', itemType.tech, 7, 'Progressive tech_cth', 'Cathay Tech: Nan-Gau Weaponry'),
    14847: itemData(IC.useful, 1, 'wh3_main_tech_cth_39', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Stalking Techniques'),
    14848: itemData(IC.useful, 1, 'wh3_main_tech_cth_40', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Harmonic Mindfulness'),
    14849: itemData(IC.useful, 1, 'wh3_main_tech_cth_61', itemType.tech, 13, 'Progressive tech_cth', 'Cathay Tech: Jade Bolts'),
    14850: itemData(IC.useful, 1, 'wh3_main_tech_cth_62', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Clay-Scrying'),
    14851: itemData(IC.useful, 1, 'wh3_main_tech_cth_63', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Yin Healing'),
    14852: itemData(IC.useful, 1, 'wh3_main_tech_cth_18', itemType.tech, 3, 'Progressive tech_cth', 'Cathay Tech: Dragon Scales'),
    14853: itemData(IC.useful, 1, 'wh3_main_tech_cth_19', itemType.tech, 3, 'Progressive tech_cth', 'Cathay Tech: Harmonic Discipline'),
    14854: itemData(IC.useful, 1, 'wh3_main_tech_cth_20', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Harmonic Mastery'),
    14855: itemData(IC.useful, 1, 'wh3_main_tech_cth_21', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Yin Hex'),
    14856: itemData(IC.useful, 1, 'wh3_main_tech_cth_41', itemType.tech, 8, 'Progressive tech_cth', 'Cathay Tech: Yin Defence'),
    14857: itemData(IC.useful, 1, 'wh3_main_tech_cth_42', itemType.tech, 8, 'Progressive tech_cth', 'Cathay Tech: Moon Wood'),
    14858: itemData(IC.useful, 1, 'wh3_main_tech_cth_43', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Yin Muse'),
    14859: itemData(IC.useful, 1, 'wh3_main_tech_cth_44', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Wadding Cartridges'),
    14860: itemData(IC.useful, 1, 'wh3_main_tech_cth_64', itemType.tech, 14, 'Progressive tech_cth', 'Cathay Tech: Moon Reflecting'),
    14861: itemData(IC.useful, 1, 'wh3_main_tech_cth_65', itemType.tech, 14, 'Progressive tech_cth', 'Cathay Tech: Grace of the Dragon Empress'),
    14862: itemData(IC.useful, 1, 'wh3_main_tech_cth_66', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Powder Mixing'),
    14863: itemData(IC.useful, 1, 'wh3_main_tech_cth_67', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Yin Flow'),
    14864: itemData(IC.useful, 1, 'wh3_main_tech_cth_22', itemType.tech, 4, 'Progressive tech_cth', 'Cathay Tech: Grace of Quai Yin'),
    14865: itemData(IC.useful, 1, 'wh3_main_tech_cth_45', itemType.tech, 9, 'Progressive tech_cth', 'Cathay Tech: Jagged Shrapnel'),
    14866: itemData(IC.useful, 1, 'wh3_main_tech_cth_68', itemType.tech, 15, 'Progressive tech_cth', 'Cathay Tech: Crane Sights'),
    14867: itemData(IC.useful, 1, 'wh3_main_tech_cth_23', itemType.tech, 5, 'Progressive tech_cth', 'Cathay Tech: Defensive Formations'),
    14868: itemData(IC.useful, 1, 'wh3_main_tech_cth_46', itemType.tech, 10, 'Progressive tech_cth', 'Cathay Tech: Target Ranges'),
    14869: itemData(IC.useful, 1, 'wh3_main_tech_cth_69', itemType.tech, 16, 'Progressive tech_cth', 'Cathay Tech: Sky Junk Rigging')
}

progUnits: dict[int, itemData] = {
    15200: itemData(IC.useful, 4, "Progressive cth_inf", itemType.unit, 4, "", "Progressive Cathay Unit: Infantry"),
    15201: itemData(IC.useful, 4, "Progressive cth_rng", itemType.unit, 4, "", "Progressive Cathay Unit: Ranged"),
    15202: itemData(IC.useful, 3, "Progressive cth_cav", itemType.unit, 3, "", "Progressive Cathay Unit: Cavalry"),
    15203: itemData(IC.useful, 2, "Progressive cth_art", itemType.unit, 2, "", "Progressive Cathay Unit: Artillery"),
    15204: itemData(IC.useful, 4, "Progressive cth_veh", itemType.unit, 4, "", "Progressive Cathay Unit: War Machine"),
    15205: itemData(IC.useful, 3, "Progressive cth_bst", itemType.unit, 3, "", "Progressive Cathay Unit: Beast"),
    15206: itemData(IC.useful, 1, "Progressive cth_hro", itemType.unit, 1, "", "Progressive Cathay Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    15300: itemData(IC.useful, 3, 'Progressive cth_allied_outpost', itemType.building, 3, None, 'Progressive Cathay Building: Allied Outpost'),
    15301: itemData(IC.useful, 2, 'Progressive cth_artillery', itemType.building, 2, None, 'Progressive Cathay Building: Artillery'),
    15302: itemData(IC.useful, 5, 'Progressive cth_bastion', itemType.building, 5, None, 'Progressive Cathay Building: Bastion'),
    15303: itemData(IC.useful, 3, 'Progressive cth_cavalry', itemType.building, 3, None, 'Progressive Cathay Building: Cavalry'),
    15304: itemData(IC.useful, 2, 'Progressive cth_celestial', itemType.building, 2, None, 'Progressive Cathay Building: Celestial'),
    15305: itemData(IC.useful, 3, 'Progressive cth_defence_yang', itemType.building, 3, None, 'Progressive Cathay Building: Defence Yang'),
    15306: itemData(IC.useful, 3, 'Progressive cth_defence_yin', itemType.building, 3, None, 'Progressive Cathay Building: Defence Yin'),
    15307: itemData(IC.useful, 3, 'Progressive cth_growth_yang', itemType.building, 3, None, 'Progressive Cathay Building: Growth Yang'),
    15308: itemData(IC.useful, 3, 'Progressive cth_growth_yin', itemType.building, 3, None, 'Progressive Cathay Building: Growth Yin'),
    15309: itemData(IC.useful, 3, 'Progressive cth_gunners', itemType.building, 3, None, 'Progressive Cathay Building: Gunners'),
    15310: itemData(IC.useful, 3, 'Progressive cth_income_yang', itemType.building, 3, None, 'Progressive Cathay Building: Income Yang'),
    15311: itemData(IC.useful, 3, 'Progressive cth_income_yin', itemType.building, 3, None, 'Progressive Cathay Building: Income Yin'),
    15312: itemData(IC.useful, 3, 'Progressive cth_jade_barracks', itemType.building, 3, None, 'Progressive Cathay Building: Jade Barracks'),
    15313: itemData(IC.useful, 3, 'Progressive cth_magic_tower', itemType.building, 3, None, 'Progressive Cathay Building: Magic Tower'),
    15314: itemData(IC.useful, 3, 'Progressive cth_order_yang', itemType.building, 3, None, 'Progressive Cathay Building: Order Yang'),
    15315: itemData(IC.useful, 3, 'Progressive cth_order_yin', itemType.building, 3, None, 'Progressive Cathay Building: Order Yin'),
    15316: itemData(IC.useful, 3, 'Progressive cth_port', itemType.building, 3, None, 'Progressive Cathay Building: Port'),
    15317: itemData(IC.useful, 3, 'Progressive cth_resource_animals', itemType.building, 3, None, 'Progressive Cathay Building: Animals'),
    15318: itemData(IC.useful, 3, 'Progressive cth_resource_dyes', itemType.building, 3, None, 'Progressive Cathay Building: Dyes'),
    15319: itemData(IC.useful, 3, 'Progressive cth_resource_furs', itemType.building, 3, None, 'Progressive Cathay Building: Furs'),
    15320: itemData(IC.useful, 3, 'Progressive cth_resource_gems', itemType.building, 3, None, 'Progressive Cathay Building: Gems'),
    15321: itemData(IC.useful, 3, 'Progressive cth_resource_gold', itemType.building, 3, None, 'Progressive Cathay Building: Gold'),
    15322: itemData(IC.useful, 3, 'Progressive cth_resource_iron', itemType.building, 3, None, 'Progressive Cathay Building: Iron'),
    15323: itemData(IC.useful, 3, 'Progressive cth_resource_ivory', itemType.building, 3, None, 'Progressive Cathay Building: Ivory'),
    15324: itemData(IC.useful, 3, 'Progressive cth_resource_marble', itemType.building, 3, None, 'Progressive Cathay Building: Marble'),
    15325: itemData(IC.useful, 3, 'Progressive cth_resource_medicine', itemType.building, 3, None, 'Progressive Cathay Building: Medicine'),
    15326: itemData(IC.useful, 3, 'Progressive cth_resource_obsidian', itemType.building, 3, None, 'Progressive Cathay Building: Obsidian'),
    15327: itemData(IC.useful, 3, 'Progressive cth_resource_pasture', itemType.building, 3, None, 'Progressive Cathay Building: Pasture'),
    15328: itemData(IC.useful, 3, 'Progressive cth_resource_pottery', itemType.building, 3, None, 'Progressive Cathay Building: Pottery'),
    15329: itemData(IC.useful, 3, 'Progressive cth_resource_salt', itemType.building, 3, None, 'Progressive Cathay Building: Salt'),
    15330: itemData(IC.useful, 3, 'Progressive cth_resource_spices', itemType.building, 3, None, 'Progressive Cathay Building: Spices'),
    15331: itemData(IC.useful, 3, 'Progressive cth_resource_wine', itemType.building, 3, None, 'Progressive Cathay Building: Wine'),
    15332: itemData(IC.useful, 3, 'Progressive cth_resource_wood', itemType.building, 3, None, 'Progressive Cathay Building: Wood'),
    15333: itemData(IC.useful, 5, 'Progressive cth_settlement_major', itemType.building, 5, None, 'Progressive Cathay Building: Settlement Major'),
    15334: itemData(IC.useful, 3, 'Progressive cth_settlement_minor', itemType.building, 3, None, 'Progressive Cathay Building: Settlement Minor'),
    15335: itemData(IC.useful, 2, 'Progressive cth_walls_minor', itemType.building, 2, None, 'Progressive Cathay Building: Walls Minor'),
    15336: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_cth', itemType.building, 3, None, 'Progressive Cathay Building: Foreign Slot Discovery Cth')
}

progTechs: dict[int, itemData] = {
    15400: itemData(IC.useful, 16, "Progressive tech_cth", itemType.tech, 16, None, "Progressive Cathay Tech: Technology"),
}

special: dict[int, itemData] = {

}

rituals: dict[int, specialItemData] = {

}