from BaseClasses import ItemClassification as IC
from worlds.tww3.itemTypes import itemType, itemData, specialItemData
# @formatter:off
units: dict[int, itemData] = {
    20008: itemData(IC.useful, 1, 'wh2_main_def_inf_dreadspears_0', itemType.unit, 1, 'Progressive def_inf', 'DarkElf Unit: Dreadspears'),
    20011: itemData(IC.useful, 1, 'wh2_main_def_inf_bleakswords_0', itemType.unit, 1, 'Progressive def_inf', 'DarkElf Unit: Bleakswords'),
    20014: itemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_0', itemType.unit, 1, 'Progressive def_inf', 'DarkElf Unit: Black Ark Corsairs'),
    20002: itemData(IC.useful, 1, 'wh2_main_def_inf_witch_elves_0', itemType.unit, 2, 'Progressive def_inf', 'DarkElf Unit: Witch Elves'),
    20050: itemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_slaughter', itemType.unit, 3, 'Progressive def_inf', 'DarkElf Unit: Sisters of Slaughter'),
    20007: itemData(IC.useful, 1, 'wh2_main_def_inf_har_ganeth_executioners_0', itemType.unit, 4, 'Progressive def_inf', 'DarkElf Unit: Har Ganeth Executioners'),
    20012: itemData(IC.useful, 1, 'wh2_main_def_inf_black_guard_0', itemType.unit, 4, 'Progressive def_inf', 'DarkElf Unit: Black Guard of Naggarond'),

    20010: itemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_0', itemType.unit, 1, 'Progressive def_rng', 'DarkElf Unit: Darkshards'),
    20009: itemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_1', itemType.unit, 2, 'Progressive def_rng', 'DarkElf Unit: Darkshards (Shields)'),
    20013: itemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_1', itemType.unit, 1, 'Progressive def_rng', 'DarkElf Unit: Black Ark Corsairs (Handbows)'),
    20005: itemData(IC.useful, 1, 'wh2_main_def_inf_shades_0', itemType.unit, 2, 'Progressive def_rng', 'DarkElf Unit: Shades'),
    20004: itemData(IC.useful, 1, 'wh2_main_def_inf_shades_1', itemType.unit, 3, 'Progressive def_rng', 'DarkElf Unit: Shades (Dual Weapons)'),
    20003: itemData(IC.useful, 1, 'wh2_main_def_inf_shades_2', itemType.unit, 3, 'Progressive def_rng', 'DarkElf Unit: Shades (Greatswords)'),

    20024: itemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_0', itemType.unit, 1, 'Progressive def_cav', 'DarkElf Unit: Dark Riders'),
    20022: itemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_2', itemType.unit, 1, 'Progressive def_cav', 'DarkElf Unit: Dark Riders (Repeater Crossbows)'),
    20023: itemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_1', itemType.unit, 2, 'Progressive def_cav', 'DarkElf Unit: Dark Riders (Shields)'),
    20059: itemData(IC.useful, 1, 'wh2_dlc10_def_cav_doomfire_warlocks_0', itemType.unit, 2, 'Progressive def_cav', 'DarkElf Unit: Doomfire Warlocks'),
    20026: itemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_0', itemType.unit, 3, 'Progressive def_cav', 'DarkElf Unit: Cold One Knights'),
    20025: itemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_1', itemType.unit, 4, 'Progressive def_cav', 'DarkElf Unit: Cold One Dread Knights'),

    20028: itemData(IC.useful, 1, 'wh2_main_def_art_reaper_bolt_thrower', itemType.unit, 1, 'Progressive def_art', 'DarkElf Unit: Reaper Bolt Throwers'),

    20041: itemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_0', itemType.unit, 1, 'Progressive def_veh', 'DarkElf Unit: Scourgerunner Chariots'),
    20027: itemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_chariot', itemType.unit, 2, 'Progressive def_veh', 'DarkElf Unit: Cold One Chariots'),
    20029: itemData(IC.useful, 1, 'wh2_dlc14_def_veh_bloodwrack_shrine_0', itemType.unit, 3, 'Progressive def_veh', 'DarkElf Unit: Bloodwrack Shrine'),

    20006: itemData(IC.useful, 1, 'wh2_main_def_inf_harpies', itemType.unit, 1, 'Progressive def_bst', 'DarkElf Unit: Harpies'),
    20031: itemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_0', itemType.unit, 1, 'Progressive def_bst', 'DarkElf Unit: Bloodwrack Medusa'),
    20045: itemData(IC.useful, 1, 'wh2_dlc10_def_mon_feral_manticore_0', itemType.unit, 2, 'Progressive def_bst', 'DarkElf Unit: Feral Manticore'),
    20064: itemData(IC.useful, 1, "wh2_main_def_mon_war_hydra", itemType.unit, 2, "Progressive def_bst", "DarkElf Unit: War Hydra"),
    20044: itemData(IC.useful, 1, 'wh2_dlc10_def_mon_kharibdyss_0', itemType.unit, 2, 'Progressive def_bst', 'DarkElf Unit: Kharibdyss'),
    20001: itemData(IC.useful, 1, 'wh2_main_def_mon_black_dragon', itemType.unit, 3, 'Progressive def_bst', 'DarkElf Unit: Black Dragon'),

    20030: itemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_ror_0', itemType.unit, 1, 'Progressive def_bst', 'DarkElf Unit: The Siren of Red Ruin (Bloodwrack Medusa)'),
    20032: itemData(IC.useful, 1, 'wh2_dlc14_def_inf_harpies_ror_0', itemType.unit, 1, 'Progressive def_bst', 'DarkElf Unit: The Crows of Khaine (Harpies)'),
    20040: itemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_ror_0', itemType.unit, 1, 'Progressive def_veh', 'DarkElf Unit: Ravagers of Rakarth (Scourgerunner Chariots)'),
    20046: itemData(IC.useful, 1, 'wh2_dlc10_def_mon_chill_of_sontar_ror_0', itemType.unit, 2, 'Progressive def_bst', 'DarkElf Unit: Chill of Sontar (War Hydra)'),
    20047: itemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_hellebronai_ror_0', itemType.unit, 1, 'Progressive def_inf', 'DarkElf Unit: The Hellebronai (Dreadspears)'),
    20048: itemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_bolt_fiends_ror_0', itemType.unit, 2, 'Progressive def_rng', 'DarkElf Unit: The Bolt-fiends (Darkshards - Shields)'),
    20049: itemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_the_singing_doom_ror_0', itemType.unit, 2, 'Progressive def_inf', 'DarkElf Unit: Sisters of the Singing Doom (Witch Elves)'),
    20051: itemData(IC.useful, 1, 'wh2_dlc10_def_inf_blades_of_the_blood_queen_ror_0', itemType.unit, 4, 'Progressive def_inf', 'DarkElf Unit: Blades of the Blood Queen (Har Ganeth Executioners)'),
    20056: itemData(IC.useful, 1, 'wh2_dlc10_def_cav_slaanesh_harvesters_ror_0', itemType.unit, 2, 'cavalry', "DarkElf Unit: Slaanesh's Harvesters (Doomfire Warlocks)"),
    20057: itemData(IC.useful, 1, 'wh2_dlc10_def_cav_raven_heralds_ror_0', itemType.unit, 1, 'cavalry', 'DarkElf Unit: Raven Heralds (Dark Riders)'),
    20058: itemData(IC.useful, 1, 'wh2_dlc10_def_cav_knights_of_the_ebon_claw_ror_0', itemType.unit, 4, 'cavalry', 'DarkElf Unit: Knights of the Ebon Claw (Dread Knights)'),

    20035: itemData(IC.useful, 1, 'wh2_dlc14_def_cha_master_0', itemType.unit, 1, 'Progressive def_hro', 'DarkElf Unit: Master'),
    20016: itemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_dark_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Sorceress (Dark)'),
    20060: itemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_death_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Sorceress (Death)'),
    20061: itemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_shadows_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Sorceress (Shadows)'),
    20062: itemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_fire_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Sorceress (Fire)'),
    20063: itemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_beasts_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Sorceress (Beasts)'),
    20018: itemData(IC.useful, 1, 'wh2_main_def_cha_khainite_assassin_0', itemType.unit, 2, 'Progressive def_hro', 'DarkElf Unit: Khainite Assassin'),
    20021: itemData(IC.useful, 1, 'wh2_main_def_cha_death_hag_0', itemType.unit, 2, 'Progressive def_inf', 'DarkElf Unit: Death Hag'),
}

buildings: dict[int, itemData] = {
    20400: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_1', itemType.building, 0, 'Progressive horde_def_aristocracy', 'DarkElf Black Ark: Dread Manse'),
    20401: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_2', itemType.building, 1, 'Progressive horde_def_aristocracy', 'DarkElf Black Ark: Palace of Dread Knights'),
    20402: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_1', itemType.building, 0, 'Progressive horde_def_exiles', 'DarkElf Black Ark: Den of Outlaws'),
    20403: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_2', itemType.building, 1, 'Progressive horde_def_exiles', 'DarkElf Black Ark: House of Exiles'),
    20404: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_1', itemType.building, 0, 'Progressive horde_def_residence', 'DarkElf Black Ark: Dark Elf Manors'),
    20405: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_2', itemType.building, 1, 'Progressive horde_def_residence', 'DarkElf Black Ark: Dark Elf Residences'),
    20406: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_3', itemType.building, 2, 'Progressive horde_def_residence', 'DarkElf Black Ark: Estates of the Masters'),
    20407: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_1', itemType.building, 0, 'Progressive horde_def_riders', 'DarkElf Building: Reaver Stables'),
    20408: itemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_2', itemType.building, 1, 'Progressive horde_def_riders', "DarkElf Building: Messengers' Lodgehouse"),
    #20409: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Tor Yvresse (Black Spire)'),
    #20410: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Tor Yvresse (Dark Hold)'),
    #20411: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Tor Yvresse (Dark Tower)'),
    #20412: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Tor Yvresse (Dark Citadel)'),
    #20413: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Tor Yvresse (Dark City)'),
    20414: itemData(IC.useful, 1, 'wh2_main_def_barracks_1', itemType.building, 0, 'Progressive def_barracks', 'DarkElf Building: Conscription Halls'),
    20415: itemData(IC.useful, 1, 'wh2_main_def_barracks_2', itemType.building, 1, 'Progressive def_barracks', 'DarkElf Building: Halls of Mustering'),
    20416: itemData(IC.useful, 1, 'wh2_main_def_barracks_3', itemType.building, 2, 'Progressive def_barracks', 'DarkElf Building: Halls of Ravaging'),
    20417: itemData(IC.useful, 1, 'wh2_main_def_beasts_1', itemType.building, 0, 'Progressive def_beasts', 'DarkElf Building: Harpy Roost'),
    20418: itemData(IC.useful, 1, 'wh2_main_def_beasts_2', itemType.building, 1, 'Progressive def_beasts', "DarkElf Building: Beastmaster's Stables"),
    20419: itemData(IC.useful, 1, 'wh2_main_def_beasts_3', itemType.building, 2, 'Progressive def_beasts', 'DarkElf Building: Dragon Hatchery'),
    20420: itemData(IC.useful, 1, 'wh2_main_def_coldones_1', itemType.building, 0, 'Progressive def_coldones', 'DarkElf Building: Dread Manse'),
    20421: itemData(IC.useful, 1, 'wh2_main_def_coldones_2', itemType.building, 1, 'Progressive def_coldones', 'DarkElf Building: Palace of Dread Knights'),
    20422: itemData(IC.useful, 1, 'wh2_main_def_defence_major_1', itemType.building, 0, 'Progressive def_defence_major', 'DarkElf Building: Slave Gate'),
    20423: itemData(IC.useful, 1, 'wh2_main_def_defence_major_2', itemType.building, 1, 'Progressive def_defence_major', 'DarkElf Building: Blackstone Walls'),
    20424: itemData(IC.useful, 1, 'wh2_main_def_defence_major_3', itemType.building, 2, 'Progressive def_defence_major', 'DarkElf Building: Dread Bulwark'),
    20425: itemData(IC.useful, 1, 'wh2_main_def_defence_minor_1', itemType.building, 0, 'Progressive def_defence_minor', 'DarkElf Building: Watchtowers'),
    20426: itemData(IC.useful, 1, 'wh2_main_def_defence_minor_2', itemType.building, 1, 'Progressive def_defence_minor', 'DarkElf Building: Dark Palisade'),
    20427: itemData(IC.useful, 1, 'wh2_main_def_defence_norsca_1', itemType.building, 0, 'Progressive def_defence_norsca', 'DarkElf Building: Outpost Garrison'),
    20428: itemData(IC.useful, 1, 'wh2_main_def_exiles_1', itemType.building, 0, 'Progressive def_exiles', 'DarkElf Building: Den of Outlaws'),
    20429: itemData(IC.useful, 1, 'wh2_main_def_exiles_2', itemType.building, 1, 'Progressive def_exiles', 'DarkElf Building: House of Exiles'),
    20430: itemData(IC.useful, 1, 'wh2_main_def_farm_1', itemType.building, 0, 'Progressive def_farm', 'DarkElf Building: Dark Elf Manors'),
    20431: itemData(IC.useful, 1, 'wh2_main_def_farm_2', itemType.building, 1, 'Progressive def_farm', 'DarkElf Building: Dark Elf Residences'),
    20432: itemData(IC.useful, 1, 'wh2_main_def_farm_3', itemType.building, 2, 'Progressive def_farm', 'DarkElf Building: Estates of the Masters'),
    20433: itemData(IC.useful, 1, 'wh2_main_def_industry_1', itemType.building, 0, 'Progressive def_industry', "DarkElf Building: Artisan's House"),
    20434: itemData(IC.useful, 1, 'wh2_main_def_industry_2', itemType.building, 1, 'Progressive def_industry', 'DarkElf Building: Crafting District'),
    20435: itemData(IC.useful, 1, 'wh2_main_def_industry_3', itemType.building, 2, 'Progressive def_industry', 'DarkElf Building: Guild Halls'),
    20439: itemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_1', itemType.building, 0, 'Progressive horde_def_entertainment', 'DarkElf Black Ark: Torture Posts'),
    20443: itemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_2', itemType.building, 1, 'Progressive horde_def_entertainment', 'DarkElf Black Ark: Fighting Pits'),
    20447: itemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_3', itemType.building, 2, 'Progressive horde_def_entertainment', 'DarkElf Black Ark: Arena'),
    20448: itemData(IC.useful, 1, 'wh2_main_def_port_1', itemType.building, 0, 'Progressive def_port', 'DarkElf Building: Dark Elf Landing'),
    20449: itemData(IC.useful, 1, 'wh2_main_def_port_2', itemType.building, 1, 'Progressive def_port', 'DarkElf Building: Dark Elf Harbour'),
    20450: itemData(IC.useful, 1, 'wh2_main_def_port_3', itemType.building, 2, 'Progressive def_port', 'DarkElf Building: Dark Elf Port'),
    20451: itemData(IC.useful, 1, 'wh2_main_def_resource_animals_1', itemType.building, 0, 'Progressive def_resource_animals', 'DarkElf Building: Exotic Animal Tamer'),
    20452: itemData(IC.useful, 1, 'wh2_main_def_resource_animals_2', itemType.building, 1, 'Progressive def_resource_animals', 'DarkElf Building: Exotic Animal Pen'),
    20453: itemData(IC.useful, 1, 'wh2_main_def_resource_animals_3', itemType.building, 2, 'Progressive def_resource_animals', 'DarkElf Building: Exotic Animal Market'),
    20454: itemData(IC.useful, 1, 'wh2_main_def_resource_dyes_1', itemType.building, 0, 'Progressive def_resource_dyes', 'DarkElf Building: Cinnabar Mining Pit'),
    20455: itemData(IC.useful, 1, 'wh2_main_def_resource_dyes_2', itemType.building, 1, 'Progressive def_resource_dyes', 'DarkElf Building: Cinnabar Mine'),
    20456: itemData(IC.useful, 1, 'wh2_main_def_resource_dyes_3', itemType.building, 2, 'Progressive def_resource_dyes', 'DarkElf Building: Dyemaker'),
    20457: itemData(IC.useful, 1, 'wh2_main_def_resource_furs_1', itemType.building, 0, 'Progressive def_resource_furs', 'DarkElf Building: Hunting Camp'),
    20458: itemData(IC.useful, 1, 'wh2_main_def_resource_furs_2', itemType.building, 1, 'Progressive def_resource_furs', 'DarkElf Building: Hunting Lodge'),
    20459: itemData(IC.useful, 1, 'wh2_main_def_resource_furs_3', itemType.building, 2, 'Progressive def_resource_furs', 'DarkElf Building: Tannery'),
    20460: itemData(IC.useful, 1, 'wh2_main_def_resource_gems_1', itemType.building, 0, 'Progressive def_resource_gems', 'DarkElf Building: Gem Mineshaft'),
    20461: itemData(IC.useful, 1, 'wh2_main_def_resource_gems_2', itemType.building, 1, 'Progressive def_resource_gems', 'DarkElf Building: Gem Mine'),
    20462: itemData(IC.useful, 1, 'wh2_main_def_resource_gems_3', itemType.building, 2, 'Progressive def_resource_gems', "DarkElf Building: Gemcutter's Workshop"),
    20463: itemData(IC.useful, 1, 'wh2_main_def_resource_gold_1', itemType.building, 0, 'Progressive def_resource_gold', 'DarkElf Building: Gold Mining Pit'),
    20464: itemData(IC.useful, 1, 'wh2_main_def_resource_gold_2', itemType.building, 1, 'Progressive def_resource_gold', 'DarkElf Building: Gold Mine'),
    20465: itemData(IC.useful, 1, 'wh2_main_def_resource_gold_3', itemType.building, 2, 'Progressive def_resource_gold', 'DarkElf Building: Gold Smelter'),
    20466: itemData(IC.useful, 1, 'wh2_main_def_resource_iron_1', itemType.building, 0, 'Progressive def_resource_iron', 'DarkElf Building: Iron Mining Pit'),
    20467: itemData(IC.useful, 1, 'wh2_main_def_resource_iron_2', itemType.building, 1, 'Progressive def_resource_iron', 'DarkElf Building: Iron Mines'),
    20468: itemData(IC.useful, 1, 'wh2_main_def_resource_iron_3', itemType.building, 2, 'Progressive def_resource_iron', 'DarkElf Building: Iron Smelter'),
    20469: itemData(IC.useful, 1, 'wh2_main_def_resource_marble_1', itemType.building, 0, 'Progressive def_resource_marble', 'DarkElf Building: Sawyer'),
    20470: itemData(IC.useful, 1, 'wh2_main_def_resource_marble_2', itemType.building, 1, 'Progressive def_resource_marble', 'DarkElf Building: Marble Quarry'),
    20471: itemData(IC.useful, 1, 'wh2_main_def_resource_marble_3', itemType.building, 2, 'Progressive def_resource_marble', "DarkElf Building: Stone Mason's Workshop"),
    20472: itemData(IC.useful, 1, 'wh2_main_def_resource_medicine_1', itemType.building, 0, 'Progressive def_resource_medicine', "DarkElf Building: Herb Gatherer's Camp"),
    20473: itemData(IC.useful, 1, 'wh2_main_def_resource_medicine_2', itemType.building, 1, 'Progressive def_resource_medicine', 'DarkElf Building: Exotic Hothouse'),
    20474: itemData(IC.useful, 1, 'wh2_main_def_resource_medicine_3', itemType.building, 2, 'Progressive def_resource_medicine', 'DarkElf Building: Alchemy Workshop'),
    20475: itemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_1', itemType.building, 0, 'Progressive def_resource_obsidian', 'DarkElf Building: Obsidian Quarry'),
    20476: itemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_2', itemType.building, 1, 'Progressive def_resource_obsidian', 'DarkElf Building: Obsidian Trinket Maker'),
    20477: itemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_3', itemType.building, 2, 'Progressive def_resource_obsidian', 'DarkElf Building: Obsidian Amulet Carver'),
    20478: itemData(IC.useful, 1, 'wh2_main_def_resource_pasture_1', itemType.building, 0, 'Progressive def_resource_pasture', 'DarkElf Building: Grazing Pastures'),
    20479: itemData(IC.useful, 1, 'wh2_main_def_resource_pasture_2', itemType.building, 1, 'Progressive def_resource_pasture', 'DarkElf Building: Livestock Pens'),
    20480: itemData(IC.useful, 1, 'wh2_main_def_resource_pasture_3', itemType.building, 2, 'Progressive def_resource_pasture', 'DarkElf Building: Cattle Ranch'),
    20481: itemData(IC.useful, 1, 'wh2_main_def_resource_pottery_1', itemType.building, 0, 'Progressive def_resource_pottery', 'DarkElf Building: Clay Pit'),
    20482: itemData(IC.useful, 1, 'wh2_main_def_resource_pottery_2', itemType.building, 1, 'Progressive def_resource_pottery', 'DarkElf Building: Pottery Maker'),
    20483: itemData(IC.useful, 1, 'wh2_main_def_resource_pottery_3', itemType.building, 2, 'Progressive def_resource_pottery', 'DarkElf Building: Kilns'),
    20484: itemData(IC.useful, 1, 'wh2_main_def_resource_salt_1', itemType.building, 0, 'Progressive def_resource_salt', 'DarkElf Building: Brine Mining Pans'),
    20485: itemData(IC.useful, 1, 'wh2_main_def_resource_salt_2', itemType.building, 1, 'Progressive def_resource_salt', 'DarkElf Building: Brine Mining Basin'),
    20486: itemData(IC.useful, 1, 'wh2_main_def_resource_salt_3', itemType.building, 2, 'Progressive def_resource_salt', 'DarkElf Building: Saltworks'),
    20487: itemData(IC.useful, 1, 'wh2_main_def_resource_spices_1', itemType.building, 0, 'Progressive def_resource_spices', 'DarkElf Building: Spice Market'),
    20488: itemData(IC.useful, 1, 'wh2_main_def_resource_spices_2', itemType.building, 1, 'Progressive def_resource_spices', 'DarkElf Building: Spice Trading Post'),
    20489: itemData(IC.useful, 1, 'wh2_main_def_resource_spices_3', itemType.building, 2, 'Progressive def_resource_spices', 'DarkElf Building: Eastern Bazaar'),
    20490: itemData(IC.useful, 1, 'wh2_main_def_resource_wine_1', itemType.building, 0, 'Progressive def_resource_wine', 'DarkElf Building: Orchards'),
    20491: itemData(IC.useful, 1, 'wh2_main_def_resource_wine_2', itemType.building, 1, 'Progressive def_resource_wine', 'DarkElf Building: Vineyard'),
    20492: itemData(IC.useful, 1, 'wh2_main_def_resource_wine_3', itemType.building, 2, 'Progressive def_resource_wine', 'DarkElf Building: Vintner'),
    20493: itemData(IC.useful, 1, 'wh2_main_def_resource_wood_1', itemType.building, 0, 'Progressive def_resource_wood', "DarkElf Building: Woodman's Hut"),
    20494: itemData(IC.useful, 1, 'wh2_main_def_resource_wood_2', itemType.building, 1, 'Progressive def_resource_wood', 'DarkElf Building: Timber Mill'),
    20495: itemData(IC.useful, 1, 'wh2_main_def_resource_wood_3', itemType.building, 2, 'Progressive def_resource_wood', 'DarkElf Building: Lumberyard'),
    20498: itemData(IC.useful, 1, 'wh2_main_def_roads_1', itemType.building, 0, 'Progressive def_roads', 'DarkElf Building: Black Roads'),
    20499: itemData(IC.useful, 1, 'wh2_main_def_settlement_major_1', itemType.building, 0, 'Progressive def_settlement_major', 'DarkElf Building: Black Spire (Major)'),
    20500: itemData(IC.useful, 1, 'wh2_main_def_settlement_major_2', itemType.building, 1, 'Progressive def_settlement_major', 'DarkElf Building: Dark Hold (Major)'),
    20501: itemData(IC.useful, 1, 'wh2_main_def_settlement_major_3', itemType.building, 2, 'Progressive def_settlement_major', 'DarkElf Building: Dark Tower (Major)'),
    20502: itemData(IC.useful, 1, 'wh2_main_def_settlement_major_4', itemType.building, 3, 'Progressive def_settlement_major', 'DarkElf Building: Dark Citadel (Major)'),
    20503: itemData(IC.useful, 1, 'wh2_main_def_settlement_major_5', itemType.building, 4, 'Progressive def_settlement_major', 'DarkElf Building: Dark City (Major)'),
    20504: itemData(IC.useful, 1, 'wh2_main_def_settlement_minor_1', itemType.building, 0, 'Progressive def_settlement_minor', 'DarkElf Building: Black Spire (Minor)'),
    20505: itemData(IC.useful, 1, 'wh2_main_def_settlement_minor_2', itemType.building, 1, 'Progressive def_settlement_minor', 'DarkElf Building: Dark Hold (Minor)'),
    20506: itemData(IC.useful, 1, 'wh2_main_def_settlement_minor_3', itemType.building, 2, 'Progressive def_settlement_minor', 'DarkElf Building: Dark Tower (Minor)'),
    20507: itemData(IC.useful, 1, 'wh2_main_def_slaves_1', itemType.building, 0, 'Progressive def_slaves', 'DarkElf Building: Slave Pens'),
    20508: itemData(IC.useful, 1, 'wh2_main_def_slaves_2', itemType.building, 1, 'Progressive def_slaves', 'DarkElf Building: Slave Market'),
    20509: itemData(IC.useful, 1, 'wh2_main_def_sorcery_1', itemType.building, 0, 'Progressive def_sorcery', "DarkElf Building: Sorceress' Abode"),
    20510: itemData(IC.useful, 1, 'wh2_main_def_sorcery_2', itemType.building, 1, 'Progressive def_sorcery', 'DarkElf Building: Tower of Dark Sorcery'),
    20523: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_1', itemType.building, 0, 'Progressive foreign_slot_discovery_def', 'DarkElf Building: City Tunnels'),
    20524: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_2', itemType.building, 1, 'Progressive foreign_slot_discovery_def', 'DarkElf Building: Guarded Tunnels'),
    20525: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_3', itemType.building, 2, 'Progressive foreign_slot_discovery_def', 'DarkElf Building: Barricaded Tunnels'),
    20526: itemData(IC.useful, 1, 'wh2_main_horde_def_beasts_1', itemType.building, 0, 'Progressive horde_def_beasts', 'DarkElf Black Ark: Harpy Cages'),
    20527: itemData(IC.useful, 1, 'wh2_main_horde_def_beasts_2', itemType.building, 1, 'Progressive horde_def_beasts', 'DarkElf Black Ark: Monster Holds'),
    20528: itemData(IC.useful, 1, 'wh2_main_horde_def_beasts_3', itemType.building, 2, 'Progressive horde_def_beasts', 'DarkElf Black Ark: Dragon Tower'),
    20529: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_1', itemType.building, 0, 'Progressive horde_def_bombardment_a', 'DarkElf Black Ark: Sacrificial Pit of Khaine'),
    20530: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_2', itemType.building, 1, 'Progressive horde_def_bombardment_a', 'DarkElf Black Ark: Abbatoir of Khaine'),
    20531: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_1', itemType.building, 0, 'Progressive horde_def_bombardment_b', 'DarkElf Black Ark: Soul Brazier'),
    20532: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_2', itemType.building, 1, 'Progressive horde_def_bombardment_b', 'DarkElf Black Ark: Soul Furnance'),
    20533: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_1', itemType.building, 0, 'Progressive horde_def_bombardment_c', 'DarkElf Black Ark: Brazen Cauldron'),
    20534: itemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_2', itemType.building, 1, 'Progressive horde_def_bombardment_c', 'DarkElf Black Ark: Bloodwrack Cauldron'),
    20538: itemData(IC.useful, 1, 'wh2_main_horde_def_military_1', itemType.building, 0, 'Progressive horde_def_military', 'DarkElf Black Ark: Corsair Cabins'),
    20539: itemData(IC.useful, 1, 'wh2_main_horde_def_military_2', itemType.building, 1, 'Progressive horde_def_military', 'DarkElf Black Ark: Raider Lodges'),
    20540: itemData(IC.useful, 1, 'wh2_main_horde_def_military_3', itemType.building, 2, 'Progressive horde_def_military', 'DarkElf Black Ark: Warrior Hall'),
    20541: itemData(IC.useful, 1, 'wh2_main_horde_def_settlement_1', itemType.building, 0, 'Progressive horde_def_settlement', 'DarkElf Black Ark: Small Black Ark'),
    20542: itemData(IC.useful, 1, 'wh2_main_horde_def_settlement_2', itemType.building, 0, 'Progressive horde_def_settlement', 'DarkElf Black Ark: Black Ark'),
    20543: itemData(IC.useful, 1, 'wh2_main_horde_def_settlement_3', itemType.building, 1, 'Progressive horde_def_settlement', 'DarkElf Black Ark: Grand Black Ark'),
    20544: itemData(IC.useful, 1, 'wh2_main_horde_def_settlement_4', itemType.building, 2, 'Progressive horde_def_settlement', 'DarkElf Black Ark: Enormous Black Ark'),
    20545: itemData(IC.useful, 1, 'wh2_main_horde_def_settlement_5', itemType.building, 3, 'Progressive horde_def_settlement', 'DarkElf Black Ark: Gargantuan Black Ark'),
    20546: itemData(IC.useful, 1, 'wh2_main_horde_def_slavery_1', itemType.building, 0, 'Progressive horde_def_slavery', 'DarkElf Black Ark: Slave Hold'),
    20547: itemData(IC.useful, 1, 'wh2_main_horde_def_slavery_2', itemType.building, 1, 'Progressive horde_def_slavery', 'DarkElf Black Ark: Cell Decks'),
    20548: itemData(IC.useful, 1, 'wh2_main_horde_def_slavery_3', itemType.building, 2, 'Progressive horde_def_slavery', 'DarkElf Black Ark: Prison Wing'),
    20549: itemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_1', itemType.building, 0, 'Progressive horde_def_sorcery', 'DarkElf Black Ark: Sorceress Cabin'),
    20550: itemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_2', itemType.building, 1, 'Progressive horde_def_sorcery', 'DarkElf Black Ark: Spire of Sorcery'),
    20553: itemData(IC.useful, 1, 'wh2_main_horde_def_worship_1', itemType.building, 0, 'Progressive horde_def_worship', 'DarkElf Black Ark: Altar of Khaine'),
    20554: itemData(IC.useful, 1, 'wh2_main_horde_def_worship_2', itemType.building, 1, 'Progressive horde_def_worship', 'DarkElf Black Ark: Shrine of Khaine'),
    #20562: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Lothern (Black Spire)'),
    #20563: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Lothern (Dark Hold)'),
    #20564: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Lothern (Dark Tower)'),
    #20565: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Lothern (Dark Citadel)'),
    #20566: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Lothern (Dark City)'),
    #20567: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Sartosa Level 1'),
    #20568: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Sartosa Level 2'),
    #20569: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Sartosa Level 3'),
    #20570: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Sartosa Level 4'),
    #20571: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'DarkElf Building: Occupied Sartosa Level 5'),
    20577: itemData(IC.useful, 1, 'wh3_main_def_allied_outpost_1', itemType.building, 0, 'Progressive def_allied_outpost', 'DarkElf Building: Dark Elf Outpost'),
    20578: itemData(IC.useful, 1, 'wh3_main_def_allied_outpost_2', itemType.building, 1, 'Progressive def_allied_outpost', 'DarkElf Building: Dark Elf District'),
    20579: itemData(IC.useful, 1, 'wh3_main_def_allied_outpost_3', itemType.building, 2, 'Progressive def_allied_outpost', 'DarkElf Building: Dark Elf Colony'),
    20580: itemData(IC.useful, 1, 'wh3_main_def_resource_ivory_1', itemType.building, 0, 'Progressive def_resource_ivory', 'DarkElf Building: Animal Store'),
    20581: itemData(IC.useful, 1, 'wh3_main_def_resource_ivory_2', itemType.building, 1, 'Progressive def_resource_ivory', 'DarkElf Building: Tusk Market'),
    20582: itemData(IC.useful, 1, 'wh3_main_def_resource_ivory_3', itemType.building, 2, 'Progressive def_resource_ivory', 'DarkElf Building: Tusk Compound'),
}

techs: dict[int, itemData] = {
    20820: itemData(IC.useful, 1, 'wh2_main_tech_def_0_0_0', itemType.tech, 1, 'Progressive tech_def_0', 'DarkElf Tech: Choose or Die!'),
    20804: itemData(IC.useful, 1, 'wh2_main_tech_def_0_1_0', itemType.tech, 2, 'Progressive tech_def_0', 'DarkElf Tech: Driven by Vengeance'),
    20800: itemData(IC.useful, 1, 'wh2_main_tech_def_0_1_1', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Marching to War'),
    20805: itemData(IC.useful, 1, 'wh2_main_tech_def_0_1_2', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Martial Society'),
    20812: itemData(IC.useful, 1, 'wh2_main_tech_def_0_1_3', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Ascension Through Battle'),
    20821: itemData(IC.useful, 1, 'wh2_main_tech_def_0_2_0', itemType.tech, 2, 'Progressive tech_def_0', 'DarkElf Tech: Battle as Business'),
    20816: itemData(IC.useful, 1, 'wh2_main_tech_def_0_2_1', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Chartered Piracy'),
    20822: itemData(IC.useful, 1, 'wh2_main_tech_def_0_2_2', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Naval Training'),
    20832: itemData(IC.useful, 1, 'wh2_main_tech_def_0_2_3', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Bloodthirsty Companions'),
    20840: itemData(IC.useful, 1, 'wh2_main_tech_def_0_3_0', itemType.tech, 2, 'Progressive tech_def_0', 'DarkElf Tech: Founded on Tyranny'),
    20836: itemData(IC.useful, 1, 'wh2_main_tech_def_0_3_1', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Revel in Suffering'),
    20841: itemData(IC.useful, 1, 'wh2_main_tech_def_0_3_2', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Continuous Slave Supply'),
    20848: itemData(IC.useful, 1, 'wh2_main_tech_def_0_3_3', itemType.tech, 3, 'Progressive tech_def_0', 'DarkElf Tech: Exploit Feuds'),

    20823: itemData(IC.useful, 1, 'wh2_main_tech_def_1_0_0', itemType.tech, 1, 'Progressive tech_def_1', 'DarkElf Tech: Upgrade I'),
    20806: itemData(IC.useful, 1, 'wh2_main_tech_def_1_1_0', itemType.tech, 2, 'Progressive tech_def_1', 'DarkElf Tech: Forged to Kill'),
    20801: itemData(IC.useful, 1, 'wh2_main_tech_def_1_1_1', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Bolt Cartridges'),
    20807: itemData(IC.useful, 1, 'wh2_main_tech_def_1_1_2', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Hit & Run'),
    20813: itemData(IC.useful, 1, 'wh2_main_tech_def_1_1_3', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Reworked Crossbows'),
    20824: itemData(IC.useful, 1, 'wh2_main_tech_def_1_2_0', itemType.tech, 2, 'Progressive tech_def_1', 'DarkElf Tech: Broken by the Lash'),
    20817: itemData(IC.useful, 1, 'wh2_main_tech_def_1_2_1', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Sadistic Handlers'),
    20825: itemData(IC.useful, 1, 'wh2_main_tech_def_1_2_2', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Dominating the Beasts'),
    20833: itemData(IC.useful, 1, 'wh2_main_tech_def_1_2_3', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Daylight Denied'),
    20842: itemData(IC.useful, 1, 'wh2_main_tech_def_1_3_0', itemType.tech, 2, 'Progressive tech_def_1', 'DarkElf Tech: Tempered in Blood'),
    20837: itemData(IC.useful, 1, 'wh2_main_tech_def_1_3_1', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Temple Training Grounds'),
    20843: itemData(IC.useful, 1, 'wh2_main_tech_def_1_3_2', itemType.tech, 3, 'Progressive tech_def_1', 'DarkElf Tech: Purge the Weak'),

    20826: itemData(IC.useful, 1, 'wh2_main_tech_def_2_0_0', itemType.tech, 1, 'Progressive tech_def_2', 'DarkElf Tech: Upgrade II'),
    20808: itemData(IC.useful, 1, 'wh2_main_tech_def_2_1_0', itemType.tech, 2, 'Progressive tech_def_2', 'DarkElf Tech: An Instrument of War'),
    20802: itemData(IC.useful, 1, 'wh2_main_tech_def_2_1_1', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Black Iron Armour'),
    20809: itemData(IC.useful, 1, 'wh2_main_tech_def_2_1_2', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Exotic Beast Hide Armour'),
    20814: itemData(IC.useful, 1, 'wh2_main_tech_def_2_1_3', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Walking in Darkness'),
    20827: itemData(IC.useful, 1, 'wh2_main_tech_def_2_2_0', itemType.tech, 2, 'Progressive tech_def_2', 'DarkElf Tech: Pressed into Servitude'),
    20818: itemData(IC.useful, 1, 'wh2_main_tech_def_2_2_1', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Recruit Convicts'),
    20828: itemData(IC.useful, 1, 'wh2_main_tech_def_2_2_2', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Hunt Outlaws'),
    20834: itemData(IC.useful, 1, 'wh2_main_tech_def_2_2_3', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Spoils of War'),
    20844: itemData(IC.useful, 1, 'wh2_main_tech_def_2_3_0', itemType.tech, 2, 'Progressive tech_def_2', 'DarkElf Tech: Consumed by Rivalry'),
    20838: itemData(IC.useful, 1, 'wh2_main_tech_def_2_3_1', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Hardship & Cruelty'),
    20845: itemData(IC.useful, 1, 'wh2_main_tech_def_2_3_2', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Divide & Conquer'),
    20850: itemData(IC.useful, 1, 'wh2_main_tech_def_2_3_3', itemType.tech, 3, 'Progressive tech_def_2', 'DarkElf Tech: Masters of Murder'),

    20829: itemData(IC.useful, 1, 'wh2_main_tech_def_3_0_0', itemType.tech, 1, 'Progressive tech_def_3', 'DarkElf Tech: Upgrade III'),
    20810: itemData(IC.useful, 1, 'wh2_main_tech_def_3_1_0', itemType.tech, 2, 'Progressive tech_def_3', 'DarkElf Tech: No Signs of Weakness'),
    20803: itemData(IC.useful, 1, 'wh2_main_tech_def_3_1_1', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Bloodforged Platemail'),
    20811: itemData(IC.useful, 1, 'wh2_main_tech_def_3_1_2', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Ceremonial Weapons'),
    20815: itemData(IC.useful, 1, 'wh2_main_tech_def_3_1_3', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Serrated Blades'),
    20830: itemData(IC.useful, 1, 'wh2_main_tech_def_3_2_0', itemType.tech, 2, 'Progressive tech_def_3', 'DarkElf Tech: Under the Yoke'),
    20819: itemData(IC.useful, 1, 'wh2_main_tech_def_3_2_1', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Bewitch Dragon Eggs'),
    20831: itemData(IC.useful, 1, 'wh2_main_tech_def_3_2_2', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Harnessed Fury'),
    20835: itemData(IC.useful, 1, 'wh2_main_tech_def_3_2_3', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Bred in Captivity'),
    20846: itemData(IC.useful, 1, 'wh2_main_tech_def_3_3_0', itemType.tech, 2, 'Progressive tech_def_3', 'DarkElf Tech: A Life of Dread'),
    20839: itemData(IC.useful, 1, 'wh2_main_tech_def_3_3_1', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Deadly Accountability'),
    20851: itemData(IC.useful, 1, 'wh2_main_tech_def_3_3_3', itemType.tech, 3, 'Progressive tech_def_3', 'DarkElf Tech: Study the Chaos Wastes')
}

progUnits: dict[int, itemData] = {
    21200: itemData(IC.useful, 4, "Progressive def_inf", itemType.unit, 4, "", "Progressive DarkElf Unit: Infantry"),
    21201: itemData(IC.useful, 3, "Progressive def_rng", itemType.unit, 3, "", "Progressive DarkElf Unit: Ranged"),
    21202: itemData(IC.useful, 4, "Progressive def_cav", itemType.unit, 4, "", "Progressive DarkElf Unit: Cavalry"),
    21203: itemData(IC.useful, 1, "Progressive def_art", itemType.unit, 1, "", "Progressive DarkElf Unit: Artillery"),
    21204: itemData(IC.useful, 3, "Progressive def_veh", itemType.unit, 3, "", "Progressive DarkElf Unit: Chariot"),
    21205: itemData(IC.useful, 3, "Progressive def_bst", itemType.unit, 3, "", "Progressive DarkElf Unit: Beast"),
    21206: itemData(IC.useful, 2, "Progressive def_hro", itemType.unit, 2, "", "Progressive DarkElf Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    21300: itemData(IC.useful, 2, 'Progressive horde_def_aristocracy', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Aristocracy'),
    21301: itemData(IC.useful, 2, 'Progressive horde_def_exiles', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Exiles'),
    21302: itemData(IC.useful, 3, 'Progressive horde_def_residence', itemType.building, 3, None, 'Progressive DarkElf Black Ark: Residence'),
    21303: itemData(IC.useful, 2, 'Progressive horde_def_riders', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Riders'),
    21304: itemData(IC.useful, 3, 'Progressive def_barracks', itemType.building, 3, None, 'Progressive DarkElf Building: Barracks'),
    21305: itemData(IC.useful, 3, 'Progressive def_beasts', itemType.building, 3, None, 'Progressive DarkElf Building: Beasts'),
    21306: itemData(IC.useful, 2, 'Progressive def_coldones', itemType.building, 2, None, 'Progressive DarkElf Building: Coldones'),
    21307: itemData(IC.useful, 3, 'Progressive def_defence_major', itemType.building, 3, None, 'Progressive DarkElf Building: Defence Major'),
    21308: itemData(IC.useful, 2, 'Progressive def_defence_minor', itemType.building, 2, None, 'Progressive DarkElf Building: Defence Minor'),
    21309: itemData(IC.useful, 2, 'Progressive def_exiles', itemType.building, 2, None, 'Progressive DarkElf Building: Exiles'),
    21310: itemData(IC.useful, 3, 'Progressive def_farm', itemType.building, 3, None, 'Progressive DarkElf Building: Farm'),
    21311: itemData(IC.useful, 3, 'Progressive def_industry', itemType.building, 3, None, 'Progressive DarkElf Building: Industry'),
    21312: itemData(IC.useful, 3, 'Progressive def_order', itemType.building, 3, None, 'Progressive DarkElf Building: Order'),
    21313: itemData(IC.useful, 3, 'Progressive def_port', itemType.building, 3, None, 'Progressive DarkElf Building: Port'),
    21314: itemData(IC.useful, 3, 'Progressive def_resource_animals', itemType.building, 3, None, 'Progressive DarkElf Building: Animals'),
    21315: itemData(IC.useful, 3, 'Progressive def_resource_dyes', itemType.building, 3, None, 'Progressive DarkElf Building: Dyes'),
    21316: itemData(IC.useful, 3, 'Progressive def_resource_furs', itemType.building, 3, None, 'Progressive DarkElf Building: Furs'),
    21317: itemData(IC.useful, 3, 'Progressive def_resource_gems', itemType.building, 3, None, 'Progressive DarkElf Building: Gems'),
    21318: itemData(IC.useful, 3, 'Progressive def_resource_gold', itemType.building, 3, None, 'Progressive DarkElf Building: Gold'),
    21319: itemData(IC.useful, 3, 'Progressive def_resource_iron', itemType.building, 3, None, 'Progressive DarkElf Building: Iron'),
    21320: itemData(IC.useful, 3, 'Progressive def_resource_marble', itemType.building, 3, None, 'Progressive DarkElf Building: Marble'),
    21321: itemData(IC.useful, 3, 'Progressive def_resource_medicine', itemType.building, 3, None, 'Progressive DarkElf Building: Medicine'),
    21322: itemData(IC.useful, 3, 'Progressive def_resource_obsidian', itemType.building, 3, None, 'Progressive DarkElf Building: Obsidian'),
    21323: itemData(IC.useful, 3, 'Progressive def_resource_pasture', itemType.building, 3, None, 'Progressive DarkElf Building: Pasture'),
    21324: itemData(IC.useful, 3, 'Progressive def_resource_pottery', itemType.building, 3, None, 'Progressive DarkElf Building: Pottery'),
    21325: itemData(IC.useful, 3, 'Progressive def_resource_salt', itemType.building, 3, None, 'Progressive DarkElf Building: Salt'),
    21326: itemData(IC.useful, 3, 'Progressive def_resource_spices', itemType.building, 3, None, 'Progressive DarkElf Building: Spices'),
    21327: itemData(IC.useful, 3, 'Progressive def_resource_wine', itemType.building, 3, None, 'Progressive DarkElf Building: Wine'),
    21328: itemData(IC.useful, 3, 'Progressive def_resource_wood', itemType.building, 3, None, 'Progressive DarkElf Building: Wood'),
    21329: itemData(IC.useful, 2, 'Progressive def_riders', itemType.building, 2, None, 'Progressive DarkElf Building: Riders'),
    21330: itemData(IC.useful, 1, 'Progressive def_roads', itemType.building, 1, None, 'Progressive DarkElf Building: Roads'),
    21331: itemData(IC.useful, 5, 'Progressive def_settlement_major', itemType.building, 5, None, 'Progressive DarkElf Building: Settlement Major'),
    21332: itemData(IC.useful, 3, 'Progressive def_settlement_minor', itemType.building, 3, None, 'Progressive DarkElf Building: Settlement Minor'),
    21333: itemData(IC.useful, 2, 'Progressive def_slaves', itemType.building, 2, None, 'Progressive DarkElf Building: Slaves'),
    21334: itemData(IC.useful, 2, 'Progressive def_sorcery', itemType.building, 2, None, 'Progressive DarkElf Building: Sorcery'),
    21335: itemData(IC.useful, 3, 'Progressive def_worship', itemType.building, 3, None, 'Progressive DarkElf Building: Worship'),
    21336: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_def', itemType.building, 3, None, 'Progressive DarkElf Building: Foreign Slot Discovery Def'),
    21337: itemData(IC.useful, 3, 'Progressive horde_def_beasts', itemType.building, 3, None, 'Progressive DarkElf Black Ark: Beasts'),
    21338: itemData(IC.useful, 2, 'Progressive horde_def_bombardment_a', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Bombardment'),
    21339: itemData(IC.useful, 3, 'Progressive horde_def_entertainment', itemType.building, 3, None, 'Progressive DarkElf Black Ark: Entertainment'),
    21340: itemData(IC.useful, 3, 'Progressive horde_def_military', itemType.building, 3, None, 'Progressive DarkElf Black Ark: Military'),
    21341: itemData(IC.useful, 4, 'Progressive horde_def_settlement', itemType.building, 4, None, 'Progressive DarkElf Black Ark: Settlement'),
    21342: itemData(IC.useful, 3, 'Progressive horde_def_slavery', itemType.building, 3, None, 'Progressive DarkElf Black Ark: Slavery'),
    21343: itemData(IC.useful, 2, 'Progressive horde_def_sorcery', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Sorcery'),
    21344: itemData(IC.useful, 2, 'Progressive horde_def_worship', itemType.building, 2, None, 'Progressive DarkElf Black Ark: Worship'),
    21345: itemData(IC.useful, 3, 'Progressive def_allied_outpost', itemType.building, 3, None, 'Progressive DarkElf Building: Allied Outpost'),
    21346: itemData(IC.useful, 3, 'Progressive def_resource_ivory', itemType.building, 3, None, 'Progressive DarkElf Building: Ivory')
}

progTechs: dict[int, itemData] = {
    21400: itemData(IC.useful, 3, "Progressive tech_def_0", itemType.tech, 3, None, "Progressive DarkElf Tech: Base"),
    21401: itemData(IC.useful, 3, "Progressive tech_def_1", itemType.tech, 3, None, "Progressive DarkElf Tech: Upgrade 1"),
    21402: itemData(IC.useful, 3, "Progressive tech_def_2", itemType.tech, 3, None, "Progressive DarkElf Tech: Upgrade 2"),
    21403: itemData(IC.useful, 3, "Progressive tech_def_3", itemType.tech, 3, None, "Progressive DarkElf Tech: Upgrade 3"),
}

special: dict[int, specialItemData] = {
    21500: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh3_main_sla_inf_daemonette_0', itemType.unit, 2, 'Progressive def_inf', False, False, 'DarkElf Unit: Daemonettes of Slaanesh'),
    21501: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh3_main_sla_inf_daemonette_1', itemType.unit, 4, 'Progressive def_inf', False, False, 'DarkElf Unit: Exalted Daemonettes of Slaanesh'),
    21502: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh3_dlc27_sla_inf_devotees_of_slaanesh', itemType.unit, 4, 'Progressive def_inf', False, False, 'DarkElf Unit: Devotees of Slaanesh'),
    21503: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh3_dlc27_sla_inf_devotees_of_slaanesh_crossbows', itemType.unit, 3, 'Progressive def_rng', False, False, 'DarkElf Unit: Devotees of Slaanesh (Crossbows)'),
    21504: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh3_dlc27_sla_cha_druchii_anointed', itemType.unit, 2, 'Progressive def_hro', False, False, 'DarkElf Unit: Druchii Anointed'),
    21505: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_worship_1', itemType.building, 0, 'Progressive def_worship', False, False, 'DarkElf Building: Altar of Khaine'),
    21506: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_worship_2', itemType.building, 1, 'Progressive def_worship', False, False, 'DarkElf Building: Shrine of Khaine'),
    21507: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_worship_3', itemType.building, 2, 'Progressive def_worship', False, False, 'DarkElf Building: Temple of Khaine'),
    21520: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_order_1', itemType.building, 0, 'Progressive def_order', False, False, 'DarkElf Building: Torture Posts'),
    21521: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_order_2', itemType.building, 1, 'Progressive def_order', False, False, 'DarkElf Building: Fighting Pits'),
    21522: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_def_order_3', itemType.building, 2, 'Progressive def_order', False, False, 'DarkElf Building: Arena'),
    21535: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_murder_1', itemType.building, 0, 'Progressive def_murder', False, False, 'DarkElf Building: House of Assassins'),
    21536: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_murder_2', itemType.building, 1, 'Progressive def_murder', False, False, 'DarkElf Building: Shrine of Khaine (Morathi)'),
    21537: specialItemData(IC.useful, 2, ['wh2_main_def_cult_of_pleasure'], 'Progressive def_murder', itemType.building, 2, None, False, True, 'Progressive DarkElf Building: Hired Killers'),
    21538: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_pleasure_cult_1', itemType.building, 0, 'Progressive def_pleasure', False, False, 'DarkElf Building: Cultist Gathering'),
    21539: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_pleasure_cult_2', itemType.building, 1, 'Progressive def_pleasure', False, False, 'DarkElf Building: Den of Indulgence'),
    21540: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_pleasure_cult_3', itemType.building, 2, 'Progressive def_pleasure', False, False, 'DarkElf Building: House of Pleasure'),
    21541: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_pleasure_cult_4', itemType.building, 3, 'Progressive def_pleasure', False, False, 'DarkElf Building: Halls of Hedonism'),
    21542: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_def_pleasure_cult_5', itemType.building, 4, 'Progressive def_pleasure', False, False, 'DarkElf Building: Court of the Dark Prince'),
    21543: specialItemData(IC.useful, 5, ['wh2_main_def_cult_of_pleasure'], 'Progressive def_pleasure', itemType.building, 5, None, False, True, 'Progressive DarkElf Building: Pleasure Cult'),
    21544: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_tech_def_1_3_3', itemType.tech, 3, 'Progressive tech_def_1', False, False, 'DarkElf Tech: Festivals of Khaine'),
    21545: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_tech_def_3_3_2', itemType.tech, 3, 'Progressive tech_def_3', False, False, 'DarkElf Tech: Blood & Death'),
    21554: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_tech_def_1_3_3_slaanesh', itemType.tech, 3, 'Progressive tech_def_1', False, False, 'DarkElf Tech: Festivals of Ruin'),
    21555: specialItemData(IC.useful, 1, ['wh2_main_def_cult_of_pleasure'], 'wh2_main_tech_def_3_3_2_slaanesh', itemType.tech, 3, 'Progressive tech_def_3', False, False, 'DarkElf Tech: Endless Debauchery')
}

rituals: dict[int, specialItemData] = {
    21600: specialItemData(IC.useful, 1, ['wh2_main_def_har_ganeth'], 'wh2_dlc10_ritual_def_drakira', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Drakira'),
    21601: specialItemData(IC.useful, 1, ['wh2_dlc11_def_the_blessed_dread'], 'wh2_dlc11_ritual_def_anath_raema', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Anath Raema'),
    21602: specialItemData(IC.useful, 1, ['wh2_main_def_hag_graef'], 'wh2_dlc14_ritual_def_warmaster', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Rite of the Warmaster'),
    21603: specialItemData(IC.useful, 1, ['wh2_main_def_hag_graef'], 'wh2_dlc14_ritual_def_witch_king', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Gift to the Witch King'),
    21604: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_har_ganeth', 'wh2_dlc11_def_the_blessed_dread', 'wh2_twa03_def_rakarth'], 'wh2_main_ritual_def_atharti', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Atharti'),
    21605: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_cult_of_pleasure', 'wh2_dlc11_def_the_blessed_dread'], 'wh2_main_ritual_def_hekarti', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Hekarti'),
    21606: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_har_ganeth', 'wh2_twa03_def_rakarth', 'wh2_main_def_hag_graef', 'wh2_dlc11_def_the_blessed_dread'], 'wh2_main_ritual_def_khaine', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Khaine'),
    21607: specialItemData(IC.useful, 1, ['wh2_main_def_naggarond', 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_har_ganeth', 'wh2_main_def_hag_graef', 'wh2_twa03_def_rakarth'], 'wh2_main_ritual_def_mathlann', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Sacrifice to Mathlann'),
    21608: specialItemData(IC.useful, 1, ['wh2_twa03_def_rakarth'], 'wh2_twa03_ritual_def_beasthunt', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, 'DarkElf Rite: Convocation of Hunters'),
    21609: specialItemData(IC.useful, 1, ['wh2_main_def_hag_graef'], 'wh2_dlc14_malus_call_tzarkan', itemType.tech, 1, 'Progressive def_ritual_rite', False, False, "DarkElf Rite: Call upon Tz'arkan")
}