from BaseClasses import ItemClassification as IC
from worlds.tww3.itemTypes import itemType, itemData, specialItemData

# @formatter:off
units: dict[int, itemData] = {
    24000: itemData(IC.useful, 1, 'wh_main_emp_inf_spearmen_0', itemType.unit, 1, 'Progressive emp_inf', 'Empire Unit: Spearmen'),
    24001: itemData(IC.useful, 1, 'wh_main_emp_inf_swordsmen', itemType.unit, 1, 'Progressive emp_inf', 'Empire Unit: Swordsmen'),
    24002: itemData(IC.useful, 1, 'wh_main_emp_inf_spearmen_1', itemType.unit, 1, 'Progressive emp_inf', 'Empire Unit: Spearmen (Shields)'),
    24003: itemData(IC.useful, 1, 'wh_main_emp_inf_halberdiers', itemType.unit, 2, 'Progressive emp_inf', 'Empire Unit: Halberdiers'),
    24004: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_flagellants_0', itemType.unit, 2, 'Progressive emp_inf', 'Empire Unit: Flagellants'),
    24005: itemData(IC.useful, 1, 'wh_main_emp_inf_greatswords', itemType.unit, 3, 'Progressive emp_inf', 'Empire Unit: Greatswords'),
    24006: itemData(IC.useful, 1, 'wh2_dlc13_emp_inf_archers_0', itemType.unit, 1, 'Progressive emp_rng', 'Empire Unit: Archers'),
    24007: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_free_company_militia_0', itemType.unit, 1, 'Progressive emp_rng', 'Empire Unit: Free Company Militia'),
    24008: itemData(IC.useful, 1, 'wh_main_emp_inf_crossbowmen', itemType.unit, 2, 'Progressive emp_rng', 'Empire Unit: Crossbowmen'),
    24009: itemData(IC.useful, 1, 'wh_main_emp_inf_handgunners', itemType.unit, 2, 'Progressive emp_rng', 'Empire Unit: Handgunners'),
    24010: itemData(IC.useful, 1, 'wh2_dlc13_emp_inf_huntsmen_0', itemType.unit, 3, 'Progressive emp_rng', 'Empire Unit: Huntsmen'),
    24011: itemData(IC.useful, 1, 'wh3_dlc25_emp_inf_nuln_ironsides', itemType.unit, 3, 'Progressive emp_rng', 'Empire Unit: Nuln Ironsides'),
    24012: itemData(IC.useful, 1, 'wh3_dlc25_emp_inf_hochland_long_rifles', itemType.unit, 3, 'Progressive emp_rng', 'Empire Unit: Hochland Long Rifles'),
    24013: itemData(IC.useful, 1, 'wh_main_emp_cav_pistoliers_1', itemType.unit, 1, 'Progressive emp_cav', 'Empire Unit: Pistoliers'),
    24014: itemData(IC.useful, 1, 'wh_main_emp_cav_outriders_0', itemType.unit, 2, 'Progressive emp_cav', 'Empire Unit: Outriders'),
    24015: itemData(IC.useful, 1, 'wh_main_emp_cav_empire_knights', itemType.unit, 2, 'Progressive emp_cav', 'Empire Unit: Empire Knights'),
    24016: itemData(IC.useful, 1, 'wh_main_emp_cav_outriders_1', itemType.unit, 3, 'Progressive emp_cav', 'Empire Unit: Outriders (Grenade Launchers)'),
    24017: itemData(IC.useful, 1, 'wh_dlc04_emp_cav_knights_blazing_sun_0', itemType.unit, 3, 'Progressive emp_cav', 'Empire Unit: Knights of the Blazing Sun'),
    24018: itemData(IC.useful, 1, 'wh_main_emp_cav_reiksguard', itemType.unit, 3, 'Progressive emp_cav', 'Empire Unit: Reiksguard'),
    24019: itemData(IC.useful, 1, 'wh3_dlc25_emp_cav_knights_of_the_black_rose', itemType.unit, 3, 'Progressive emp_cav', 'Empire Unit: Knights of the Black Rose'),
    24020: itemData(IC.useful, 1, 'wh_main_emp_cav_demigryph_knights_0', itemType.unit, 4, 'Progressive emp_cav', 'Empire Unit: Demigryph Knights'),
    24021: itemData(IC.useful, 1, 'wh_main_emp_cav_demigryph_knights_1', itemType.unit, 4, 'Progressive emp_cav', 'Empire Unit: Demigryph Knights (Halberds)'),
    24022: itemData(IC.useful, 1, 'wh_main_emp_art_mortar', itemType.unit, 1, 'Progressive emp_art', 'Empire Unit: Mortars'),
    24023: itemData(IC.useful, 1, 'wh_main_emp_art_great_cannon', itemType.unit, 2, 'Progressive emp_art', 'Empire Unit: Great Cannons'),
    24024: itemData(IC.useful, 1, 'wh_main_emp_art_helstorm_rocket_battery', itemType.unit, 3, 'Progressive emp_art', 'Empire Unit: Helstorm Rocket Battery'),
    24025: itemData(IC.useful, 1, 'wh_main_emp_art_helblaster_volley_gun', itemType.unit, 3, 'Progressive emp_art', 'Empire Unit: Helblaster Volley Guns'),
    24026: itemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_0', itemType.unit, 1, 'Progressive emp_veh', 'Empire Unit: War Wagons'),
    24027: itemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_1', itemType.unit, 2, 'Progressive emp_veh', 'Empire Unit: War Wagons (Mortars)'),
    24028: itemData(IC.useful, 1, 'wh3_dlc25_emp_veh_marienburg_land_ship', itemType.unit, 3, 'Progressive emp_veh', 'Empire Unit: Land Ship'),
    24029: itemData(IC.useful, 1, 'wh_main_emp_veh_steam_tank_driver', itemType.unit, 4, 'Progressive emp_veh', 'Empire Unit: Steam Tank'),
    24030: itemData(IC.useful, 1, 'wh3_dlc25_emp_veh_steam_tank_volley_gun', itemType.unit, 4, 'Progressive emp_veh', 'Empire Unit: Steam Tank (Volley Gun)'),
    24031: itemData(IC.useful, 1, 'wh_main_emp_veh_luminark_of_hysh_0', itemType.unit, 4, 'Progressive emp_veh', 'Empire Unit: Luminark of Hysh'),
    24032: itemData(IC.useful, 1, 'wh3_dlc25_emp_cha_wizard_metal', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Gold Wizard'),
    24033: itemData(IC.useful, 1, 'wh_main_emp_cha_wizard_light_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Light Wizard'),
    24034: itemData(IC.useful, 1, 'wh_dlc05_emp_cha_wizard_shadows_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Grey Wizard'),
    24035: itemData(IC.useful, 1, 'wh_main_emp_cha_wizard_heavens_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Celestial Wizard'),
    24036: itemData(IC.useful, 1, 'wh_dlc05_emp_cha_wizard_life_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Jade Wizard'),
    24037: itemData(IC.useful, 1, 'wh_dlc03_emp_cha_wizard_beasts_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Amber Wizard'),
    24038: itemData(IC.useful, 1, 'wh2_pro07_emp_cha_wizard_death_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Amethyst Wizard'),
    24039: itemData(IC.useful, 1, 'wh_main_emp_cha_wizard_fire_0', itemType.unit, 2, 'Progressive emp_hro', 'Empire Unit: Bright Wizard'),
    24040: itemData(IC.useful, 1, 'wh3_dlc25_emp_cha_engineer', itemType.unit, 1, 'Progressive emp_hro', 'Empire Unit: Engineer'),
    24041: itemData(IC.useful, 1, 'wh_main_emp_cha_witch_hunter', itemType.unit, 1, 'Progressive emp_hro', 'Empire Unit: Witch Hunter'),
    24042: itemData(IC.useful, 1, 'wh_main_emp_cha_warrior_priest_0', itemType.unit, 1, 'Progressive emp_hro', 'Empire Unit: Warrior Priest'),
    24043: itemData(IC.useful, 1, 'wh_main_emp_cha_captain_0', itemType.unit, 1, 'Progressive emp_hro', 'Empire Unit: Empire Captain'),
    24044: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_sigmars_sons_0', itemType.unit, 2, 'Progressive emp_inf', "Empire Unit: Sigmar's Sons (Swordsmen)"),
    24045: itemData(IC.useful, 1, 'wh2_dlc13_emp_inf_archers_ror_0', itemType.unit, 1, 'Progressive emp_rng', 'Empire Unit: Deathjacks (Archers)'),
    24046: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_stirlands_revenge_0', itemType.unit, 1, 'Progressive emp_rng', "Empire Unit: Stirland's Revenge (Free Company Militia)"),
    24047: itemData(IC.useful, 1, 'wh3_dlc25_emp_inf_spearmen_shields_ror', itemType.unit, 1, 'Progressive emp_inf', "Empire Unit: Grundel's Defenders (Spearmen – Shields)"),
    24048: itemData(IC.useful, 1, 'wh2_dlc13_emp_inf_huntsmen_ror_0', itemType.unit, 3, 'Progressive emp_rng', 'Empire Unit: The White Wolves (Huntsmen)'),
    24049: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_silver_bullets_0', itemType.unit, 2, 'Progressive emp_rng', 'Empire Unit: The Silver Bullets (Handgunners)'),
    24050: itemData(IC.useful, 1, 'wh3_dlc25_emp_inf_hochland_long_rifles_ror', itemType.unit, 3, 'Progressive emp_rng', 'Empire Unit: The Hergig Jaegerkorps (Hochland Long Rifles)'),
    24051: itemData(IC.useful, 1, 'wh_dlc04_emp_inf_tattersouls_0', itemType.unit, 2, 'Progressive emp_inf', 'Empire Unit: The Tattersouls (Flagellants)'),
    24052: itemData(IC.useful, 1, 'wh_dlc04_emp_cav_zintlers_reiksguard_0', itemType.unit, 3, 'Progressive emp_inf', "Empire Unit: Zintler's Reiksguard (Reiksguard)"),
    24053: itemData(IC.useful, 1, 'wh_dlc04_emp_veh_templehof_luminark_0', itemType.unit, 4, 'Progressive emp_veh', 'Empire Unit: Templehof Luminark (Luminark of Hysh)'),
    24054: itemData(IC.useful, 1, 'wh_dlc04_emp_art_hammer_of_the_witches_0', itemType.unit, 2, 'Progressive emp_art', 'Empire Unit: Hammer of the Witches (Great Cannons)'),
    24055: itemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_ror_0', itemType.unit, 3, 'Progressive emp_veh', 'Empire Unit: The Black Lions (War Wagons – Helblasters)'),
    24056: itemData(IC.useful, 1, 'wh3_dlc25_emp_veh_marienburg_land_ship_ror', itemType.unit, 4, 'Progressive emp_veh', 'Empire Unit: The Wonder of the Age (Land Ship)'),
    24057: itemData(IC.useful, 1, 'wh_dlc04_emp_cav_royal_altdorf_gryphites_0', itemType.unit, 3, 'Progressive emp_art', 'Empire Unit: The Sunmaker (Helstorm Rocket Battery)'),
    24058: itemData(IC.useful, 1, 'wh_dlc04_emp_veh_templehof_luminark_0', itemType.unit, 4, 'Progressive emp_cav', 'Empire Unit: The Royal Altdorf Gryphites (Demigryph Knights)'),
}

buildings: dict[int, itemData] = {
    #24400: itemData(IC.useful, 1, 'wh2_main_emp_defence_norsca_1', itemType.building, 0, 'Progressive emp_defence_norsca', 'Empire Building: Outpost Garrison'),
    24401: itemData(IC.useful, 1, 'wh2_main_emp_resource_animals_1', itemType.building, 0, 'Progressive emp_resource_animals', 'Empire Building: Exotic Animal Tamer'),
    24402: itemData(IC.useful, 1, 'wh2_main_emp_resource_animals_2', itemType.building, 1, 'Progressive emp_resource_animals', 'Empire Building: Exotic Animal Pen'),
    24403: itemData(IC.useful, 1, 'wh2_main_emp_resource_animals_3', itemType.building, 2, 'Progressive emp_resource_animals', 'Empire Building: Exotic Animal Market'),
    24404: itemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_1', itemType.building, 0, 'Progressive emp_resource_gemstones', 'Empire Building: Gem Mineshaft'),
    24405: itemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_2', itemType.building, 1, 'Progressive emp_resource_gemstones', 'Empire Building: Gem Mine'),
    24406: itemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_3', itemType.building, 2, 'Progressive emp_resource_gemstones', "Empire Building: Gemcutter's Workshop"),
    24407: itemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_1', itemType.building, 0, 'Progressive emp_resource_medicine', "Empire Building: Herb Gatherer's Camp"),
    24408: itemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_2', itemType.building, 1, 'Progressive emp_resource_medicine', 'Empire Building: Exotic Hothouse'),
    24409: itemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_3', itemType.building, 2, 'Progressive emp_resource_medicine', 'Empire Building: Alchemy Workshop'),
    24410: itemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_1', itemType.building, 0, 'Progressive emp_resource_obsidian', 'Empire Building: Obsidian Quarry'),
    24411: itemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_2', itemType.building, 1, 'Progressive emp_resource_obsidian', 'Empire Building: Obsidian Trinket Maker'),
    24412: itemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_3', itemType.building, 2, 'Progressive emp_resource_obsidian', 'Empire Building: Obsidian Amulet Carver'),
    24413: itemData(IC.useful, 1, 'wh2_main_emp_resource_spices_1', itemType.building, 0, 'Progressive emp_resource_spices', 'Empire Building: Spice Market'),
    24414: itemData(IC.useful, 1, 'wh2_main_emp_resource_spices_2', itemType.building, 1, 'Progressive emp_resource_spices', 'Empire Building: Spice Trading Post'),
    24415: itemData(IC.useful, 1, 'wh2_main_emp_resource_spices_3', itemType.building, 2, 'Progressive emp_resource_spices', 'Empire Building: Eastern Bazaar'),
    24416: itemData(IC.useful, 1, 'wh2_main_emp_roads_1', itemType.building, 0, 'Progressive emp_roads', 'Empire Building: Paved Roads'),
    24417: itemData(IC.useful, 1, 'wh2_main_emp_roads_2', itemType.building, 1, 'Progressive emp_roads', 'Empire Building: Toll Gates'),
    24418: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_1', itemType.building, 0, 'Progressive foreign_slot_discovery_emp', 'Empire Building: Night Watch'),
    24419: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_2', itemType.building, 1, 'Progressive foreign_slot_discovery_emp', 'Empire Building: Armoured Watchers'),
    24420: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_3', itemType.building, 2, 'Progressive foreign_slot_discovery_emp', 'Empire Building: Elite Watchers'),
    #24421: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_1', ItemType.building, 1, 'Progressive emp_settlement_major', 'Empire Building: Small Fort'),
    #24422: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_2', ItemType.building, 2, 'Progressive emp_settlement_major', 'Empire Building: Fort'),
    #24423: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_3', ItemType.building, 3, 'Progressive emp_settlement_major', 'Empire Building: Grand Fort'),
    #24424: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_4', ItemType.building, 4, 'Progressive emp_settlement_major', 'Empire Building: Imposing Fort'),
    #24425: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_5', ItemType.building, 5, 'Progressive emp_settlement_major', 'Empire Building: Impregnable Fort'),
    #24426: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_1', ItemType.building, 0, 'Progressive emp_settlement_major', 'Empire Building: Occupied Sartosa Level 1'),
    #24427: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_2', ItemType.building, 1, 'Progressive emp_settlement_major', 'Empire Building: Occupied Sartosa Level 2'),
    #24428: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_3', ItemType.building, 2, 'Progressive emp_settlement_major', 'Empire Building: Occupied Sartosa Level 3'),
    #24429: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_4', ItemType.building, 3, 'Progressive emp_settlement_major', 'Empire Building: Occupied Sartosa Level 4'),
    #24430: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_5', ItemType.building, 4, 'Progressive emp_settlement_major', 'Empire Building: Occupied Sartosa Level 5'),
    24431: itemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_1', itemType.building, 0, 'Progressive emp_shooting_range', 'Empire Building: Shooting Range'),
    24432: itemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_2', itemType.building, 1, 'Progressive emp_shooting_range', 'Empire Building: Firearms Academy'),
    24433: itemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_3', itemType.building, 2, 'Progressive emp_shooting_range', 'Empire Building: Gunnery School'),
    24434: itemData(IC.useful, 1, 'wh3_dlc25_emp_wizards_3', itemType.building, 2, 'Progressive emp_wizards', "Empire Building: Wizard's Tower"),
    24435: itemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_1', itemType.building, 0, 'Progressive emp_allied_outpost', 'Empire Building: Empire Outpost'),
    24436: itemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_2', itemType.building, 1, 'Progressive emp_allied_outpost', 'Empire Building: Empire District'),
    24437: itemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_3', itemType.building, 2, 'Progressive emp_allied_outpost', 'Empire Building: Empire Colony'),
    24438: itemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_1', itemType.building, 0, 'Progressive emp_resource_ivory', 'Empire Building: Animal Store'),
    24439: itemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_2', itemType.building, 1, 'Progressive emp_resource_ivory', 'Empire Building: Tusk Market'),
    24440: itemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_3', itemType.building, 2, 'Progressive emp_resource_ivory', 'Empire Building: Tusk Compound'),
    24441: itemData(IC.useful, 1, 'wh_main_emp_barracks_1', itemType.building, 0, 'Progressive emp_barracks', 'Empire Building: Training Field'),
    24442: itemData(IC.useful, 1, 'wh_main_emp_barracks_2', itemType.building, 1, 'Progressive emp_barracks', 'Empire Building: Rally Field'),
    24443: itemData(IC.useful, 1, 'wh_main_emp_barracks_3', itemType.building, 2, 'Progressive emp_barracks', 'Empire Building: Barracks'),
    24444: itemData(IC.useful, 1, 'wh_main_emp_farm_basic_1', itemType.building, 0, 'Progressive emp_farm_basic', 'Empire Building: Fields'),
    24445: itemData(IC.useful, 1, 'wh_main_emp_farm_basic_2', itemType.building, 1, 'Progressive emp_farm_basic', 'Empire Building: Farm'),
    24446: itemData(IC.useful, 1, 'wh_main_emp_farm_basic_3', itemType.building, 2, 'Progressive emp_farm_basic', 'Empire Building: Landed Estate'),
    24447: itemData(IC.useful, 1, 'wh_main_emp_forges_1', itemType.building, 0, 'Progressive emp_forges', 'Empire Building: Gunsmith'),
    24448: itemData(IC.useful, 1, 'wh_main_emp_forges_2', itemType.building, 1, 'Progressive emp_forges', 'Empire Building: Foundry'),
    24449: itemData(IC.useful, 1, 'wh_main_emp_forges_3', itemType.building, 2, 'Progressive emp_forges', "Empire Building: Engineer's Workshop"),
    24450: itemData(IC.useful, 1, 'wh_main_emp_forges_4', itemType.building, 3, 'Progressive emp_forges', "Empire Building: Engineer's Guildhall"),
    24451: itemData(IC.useful, 1, 'wh_main_emp_garrison_1', itemType.building, 0, 'Progressive emp_garrison', 'Empire Building: Guard House'),
    24452: itemData(IC.useful, 1, 'wh_main_emp_garrison_2', itemType.building, 1, 'Progressive emp_garrison', 'Empire Building: City Watch'),
    24453: itemData(IC.useful, 1, 'wh_main_emp_industry_basic_1', itemType.building, 0, 'Progressive emp_industry_basic', 'Empire Building: Weaving House'),
    24454: itemData(IC.useful, 1, 'wh_main_emp_industry_basic_2', itemType.building, 1, 'Progressive emp_industry_basic', 'Empire Building: Clothier'),
    24455: itemData(IC.useful, 1, 'wh_main_emp_industry_basic_3', itemType.building, 2, 'Progressive emp_industry_basic', "Empire Building: Tailors' Guild"),
    24456: itemData(IC.useful, 1, 'wh_main_emp_port_1', itemType.building, 0, 'Progressive emp_port', 'Empire Building: Imperial Wharf'),
    24457: itemData(IC.useful, 1, 'wh_main_emp_port_2', itemType.building, 1, 'Progressive emp_port', 'Empire Building: Imperial Harbour'),
    24458: itemData(IC.useful, 1, 'wh_main_emp_port_3', itemType.building, 2, 'Progressive emp_port', 'Empire Building: Imperial Port'),
    24459: itemData(IC.useful, 1, 'wh_main_emp_resource_dyes_1', itemType.building, 0, 'Progressive emp_resource_dyes', 'Empire Building: Cinnabar Mining Pit'),
    24460: itemData(IC.useful, 1, 'wh_main_emp_resource_dyes_2', itemType.building, 1, 'Progressive emp_resource_dyes', 'Empire Building: Cinnabar Mine'),
    24461: itemData(IC.useful, 1, 'wh_main_emp_resource_dyes_3', itemType.building, 2, 'Progressive emp_resource_dyes', 'Empire Building: Dyemaker'),
    24462: itemData(IC.useful, 1, 'wh_main_emp_resource_furs_1', itemType.building, 0, 'Progressive emp_resource_furs', 'Empire Building: Hunting Camp'),
    24463: itemData(IC.useful, 1, 'wh_main_emp_resource_furs_2', itemType.building, 1, 'Progressive emp_resource_furs', 'Empire Building: Hunting Lodge'),
    24464: itemData(IC.useful, 1, 'wh_main_emp_resource_furs_3', itemType.building, 2, 'Progressive emp_resource_furs', 'Empire Building: Tannery'),
    24465: itemData(IC.useful, 1, 'wh_main_emp_resource_gold_1', itemType.building, 0, 'Progressive emp_resource_gold', 'Empire Building: Gold Mining Pit'),
    24466: itemData(IC.useful, 1, 'wh_main_emp_resource_gold_2', itemType.building, 1, 'Progressive emp_resource_gold', 'Empire Building: Gold Mine'),
    24467: itemData(IC.useful, 1, 'wh_main_emp_resource_gold_3', itemType.building, 2, 'Progressive emp_resource_gold', 'Empire Building: Gold Smelter'),
    24468: itemData(IC.useful, 1, 'wh_main_emp_resource_iron_1', itemType.building, 0, 'Progressive emp_resource_iron', 'Empire Building: Iron Mining Pit'),
    24469: itemData(IC.useful, 1, 'wh_main_emp_resource_iron_2', itemType.building, 1, 'Progressive emp_resource_iron', 'Empire Building: Iron Mine'),
    24470: itemData(IC.useful, 1, 'wh_main_emp_resource_iron_3', itemType.building, 2, 'Progressive emp_resource_iron', 'Empire Building: Iron Smelter'),
    24472: itemData(IC.useful, 1, 'wh_main_emp_resource_marble_1', itemType.building, 0, 'Progressive emp_resource_marble', 'Empire Building: Stone Cutter'),
    24473: itemData(IC.useful, 1, 'wh_main_emp_resource_marble_2', itemType.building, 1, 'Progressive emp_resource_marble', 'Empire Building: Marble Quarry'),
    24474: itemData(IC.useful, 1, 'wh_main_emp_resource_marble_3', itemType.building, 2, 'Progressive emp_resource_marble', 'Empire Building: Mason'),
    24475: itemData(IC.useful, 1, 'wh_main_emp_resource_pastures_1', itemType.building, 0, 'Progressive emp_resource_pastures', 'Empire Building: Grazing Pastures'),
    24476: itemData(IC.useful, 1, 'wh_main_emp_resource_pastures_2', itemType.building, 1, 'Progressive emp_resource_pastures', 'Empire Building: Livestock Pens'),
    24477: itemData(IC.useful, 1, 'wh_main_emp_resource_pastures_3', itemType.building, 2, 'Progressive emp_resource_pastures', 'Empire Building: Cattle Ranch'),
    24479: itemData(IC.useful, 1, 'wh_main_emp_resource_pottery_1', itemType.building, 0, 'Progressive emp_resource_pottery', 'Empire Building: Clay Pit'),
    24480: itemData(IC.useful, 1, 'wh_main_emp_resource_pottery_2', itemType.building, 1, 'Progressive emp_resource_pottery', 'Empire Building: Pottery Maker'),
    24481: itemData(IC.useful, 1, 'wh_main_emp_resource_pottery_3', itemType.building, 2, 'Progressive emp_resource_pottery', 'Empire Building: Kilns'),
    24482: itemData(IC.useful, 1, 'wh_main_emp_resource_salt_1', itemType.building, 0, 'Progressive emp_resource_salt', 'Empire Building: Brine Mining Pit'),
    24483: itemData(IC.useful, 1, 'wh_main_emp_resource_salt_2', itemType.building, 1, 'Progressive emp_resource_salt', 'Empire Building: Brine Mine'),
    24484: itemData(IC.useful, 1, 'wh_main_emp_resource_salt_3', itemType.building, 2, 'Progressive emp_resource_salt', 'Empire Building: Saltworks'),
    24485: itemData(IC.useful, 1, 'wh_main_emp_resource_timber_1', itemType.building, 0, 'Progressive emp_resource_timber', "Empire Building: Woodman's Hut"),
    24486: itemData(IC.useful, 1, 'wh_main_emp_resource_timber_2', itemType.building, 1, 'Progressive emp_resource_timber', 'Empire Building: Timber Mill'),
    24487: itemData(IC.useful, 1, 'wh_main_emp_resource_timber_3', itemType.building, 2, 'Progressive emp_resource_timber', 'Empire Building: Lumberyard'),
    24489: itemData(IC.useful, 1, 'wh_main_emp_resource_wine_1', itemType.building, 0, 'Progressive emp_resource_wine', 'Empire Building: Orchards'),
    24490: itemData(IC.useful, 1, 'wh_main_emp_resource_wine_2', itemType.building, 1, 'Progressive emp_resource_wine', 'Empire Building: Vineyard'),
    24491: itemData(IC.useful, 1, 'wh_main_emp_resource_wine_3', itemType.building, 2, 'Progressive emp_resource_wine', 'Empire Building: Vintner'),
    24492: itemData(IC.useful, 1, 'wh_main_emp_settlement_major_1', itemType.building, 0, 'Progressive emp_settlement_major', 'Empire Building: Hamlet (Major)'),
    24493: itemData(IC.useful, 1, 'wh_main_emp_settlement_major_2', itemType.building, 1, 'Progressive emp_settlement_major', 'Empire Building: Village (Major)'),
    24494: itemData(IC.useful, 1, 'wh_main_emp_settlement_major_3', itemType.building, 2, 'Progressive emp_settlement_major', 'Empire Building: Town (Major)'),
    24495: itemData(IC.useful, 1, 'wh_main_emp_settlement_major_4', itemType.building, 3, 'Progressive emp_settlement_major', 'Empire Building: City (Major)'),
    24496: itemData(IC.useful, 1, 'wh_main_emp_settlement_major_5', itemType.building, 4, 'Progressive emp_settlement_major', 'Empire Building: City-State (Major)'),
    24497: itemData(IC.useful, 1, 'wh_main_emp_settlement_minor_1', itemType.building, 0, 'Progressive emp_settlement_minor', 'Empire Building: Hamlet (Minor)'),
    24498: itemData(IC.useful, 1, 'wh_main_emp_settlement_minor_2', itemType.building, 1, 'Progressive emp_settlement_minor', 'Empire Building: Village (Minor)'),
    24499: itemData(IC.useful, 1, 'wh_main_emp_settlement_minor_3', itemType.building, 2, 'Progressive emp_settlement_minor', 'Empire Building: Town (Minor)'),
    24500: itemData(IC.useful, 1, 'wh_main_emp_stables_1', itemType.building, 0, 'Progressive emp_stables', 'Empire Building: Stables'),
    24501: itemData(IC.useful, 1, 'wh_main_emp_stables_2', itemType.building, 1, 'Progressive emp_stables', 'Empire Building: Livery'),
    24502: itemData(IC.useful, 1, 'wh_main_emp_stables_3', itemType.building, 2, 'Progressive emp_stables', 'Empire Building: Menagerie'),
    24503: itemData(IC.useful, 1, 'wh_main_emp_tavern_1', itemType.building, 0, 'Progressive emp_tavern', 'Empire Building: Tap Room'),
    24504: itemData(IC.useful, 1, 'wh_main_emp_tavern_2', itemType.building, 1, 'Progressive emp_tavern', 'Empire Building: Tavern'),
    24505: itemData(IC.useful, 1, 'wh_main_emp_tavern_3', itemType.building, 2, 'Progressive emp_tavern', 'Empire Building: Coaching Inn'),
    24506: itemData(IC.useful, 1, 'wh_main_emp_walls_1', itemType.building, 0, 'Progressive emp_walls', 'Empire Building: Basic Walls'),
    24507: itemData(IC.useful, 1, 'wh_main_emp_walls_2', itemType.building, 1, 'Progressive emp_walls', 'Empire Building: Tall Walls'),
    24508: itemData(IC.useful, 1, 'wh_main_emp_walls_3', itemType.building, 2, 'Progressive emp_walls', 'Empire Building: Reinforced Walls'),
    24509: itemData(IC.useful, 1, 'wh_main_emp_wizards_1', itemType.building, 0, 'Progressive emp_wizards', "Empire Building: Wizard's Conclave"),
    24510: itemData(IC.useful, 1, 'wh_main_emp_wizards_2', itemType.building, 1, 'Progressive emp_wizards', "Empire Building: Wizard's Campus"),
    24511: itemData(IC.useful, 1, 'wh_main_emp_worship_1', itemType.building, 0, 'Progressive emp_worship', 'Empire Building: Shrine of Sigmar'),
    24514: itemData(IC.useful, 1, 'wh_main_emp_worship_2', itemType.building, 1, 'Progressive emp_worship', 'Empire Building: Temple of Sigmar'),
}

techs: dict[int, itemData] = {
    24803: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1', itemType.tech, 1, 'Progressive tech_emp_infantry', 'Empire Tech: State Troop Standards'),
    24804: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_a', itemType.tech, 2, 'Progressive tech_emp_infantry', 'Empire Tech: State-Issued Infantry Armour'),
    24813: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_b', itemType.tech, 2, 'Progressive tech_emp_infantry', 'Empire Tech: State-Issued Weapons'),
    24814: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_c', itemType.tech, 3, 'Progressive tech_emp_infantry', 'Empire Tech: Improved Heavy Weapons'),
    24806: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1', itemType.tech, 1, 'Progressive tech_emp_missiles', 'Empire Tech: Mass-Produced Small Ammunition'),
    24807: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1_a', itemType.tech, 2, 'Progressive tech_emp_missiles', 'Empire Tech: Mounted Weaponry'),
    24817: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1_b', itemType.tech, 3, 'Progressive tech_emp_missiles', 'Empire Tech: Rifled Barrels'),
    24818: itemData(IC.useful, 1, 'wh2_dlc25_tech_emp_missile_1_c', itemType.tech, 2, 'Progressive tech_emp_missiles', 'Empire Tech: Trained Marksmen'),
    24801: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1', itemType.tech, 1, 'Progressive tech_emp_cavalry', 'Empire Tech: Improved Cavalry Armour'),
    24811: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_a', itemType.tech, 2, 'Progressive tech_emp_cavalry', 'Empire Tech: Blinkers'),
    24802: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_b', itemType.tech, 2, 'Progressive tech_emp_cavalry', 'Empire Tech: Endurance Training'),
    24812: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_c', itemType.tech, 3, 'Progressive tech_emp_cavalry', 'Empire Tech: The Inner Circle'),
    24805: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1_b', itemType.tech, 1, 'Progressive tech_emp_artillery', 'Empire Tech: Ordnance Canisters'),
    24815: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1', itemType.tech, 2, 'Progressive tech_emp_artillery', 'Empire Tech: Firing Drills'),
    24808: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_art_c', itemType.tech, 2, 'Progressive tech_emp_artillery', 'Empire Tech: Refined Schematics'),
    24810: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2_b', itemType.tech, 3, 'Progressive tech_emp_artillery', 'Empire Tech: Combustion Agent'),
    21816: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3_b', itemType.tech, 1, 'Progressive tech_emp_machines', 'Empire Tech: Improved Piston Technology'),
    24816: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1_a', itemType.tech, 2, 'Progressive tech_emp_machines', 'Empire Tech: Reinforced Armour Plating'),
    24809: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_machine_1_c', itemType.tech, 2, 'Progressive tech_emp_machines', 'Empire Tech: Greater Channelling'),
    24819: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_machine_1_d', itemType.tech, 3, 'Progressive tech_emp_machines', 'Empire Tech: Pinnacle of the Empire'),

    24825: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_3', itemType.tech, 1, 'Progressive tech_emp_industry', 'Empire Tech: Supply Wagons'),
    24824: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_2_a', itemType.tech, 2, 'Progressive tech_emp_industry', 'Empire Tech: Colonial Factors'),
    24821: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2_a', itemType.tech, 3, 'Progressive tech_emp_industry', 'Empire Tech: Guildmaster Professors'),
    24823: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_1_a', itemType.tech, 4, 'Progressive tech_emp_industry', 'Empire Tech: Commodity Trading'),
    24835: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_2', itemType.tech, 1, 'Progressive tech_emp_industry', 'Empire Tech: Grain Silos'),
    24832: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2', itemType.tech, 2, 'Progressive tech_emp_industry', 'Empire Tech: Continuous Production'),
    24830: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1', itemType.tech, 3, 'Progressive tech_emp_industry', 'Empire Tech: Assembly Line'),
    24833: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3', itemType.tech, 4, 'Progressive tech_emp_industry', 'Empire Tech: Imperial Architects'),

    24820: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1_b', itemType.tech, 1, 'Progressive tech_emp_imperial', 'Empire Tech: Imperial University'),
    24834: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_1_b', itemType.tech, 1, 'Progressive tech_emp_imperial', 'Empire Tech: Clergy of Sigmar'),
    24831: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1_a', itemType.tech, 1, 'Progressive tech_emp_imperial', "Empire Tech: Engineers' Guild"),
    24822: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3_a', itemType.tech, 1, 'Progressive tech_emp_imperial', 'Empire Tech: Intelligence Sharing'),
    24826: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_3_a', itemType.tech, 2, 'Progressive tech_emp_imperial', 'Empire Tech: Manorialism'),

    24827: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_1', itemType.tech, 1, 'Progressive tech_emp_magic', 'Empire Tech: Teachings of Teclis'),
    24828: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_3', itemType.tech, 2, 'Progressive tech_emp_magic', 'Empire Tech: Protection of the Patriarch'),
    24836: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_2', itemType.tech, 2, 'Progressive tech_emp_magic', 'Empire Tech: The Eight Orders'),
    24829: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_4', itemType.tech, 3, 'Progressive tech_emp_magic', 'Empire Tech: Hall of Duels'),

    24837: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_a', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Tzarina'),
    24838: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_b', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Phoenix King'),
    24842: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_d', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Royarch of Bretonnia'),
    24839: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_c', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Karaz Ankor'),
    24845: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_e', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Dragon Emperor'),
    24846: itemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_f', itemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Empire Tech: Ambassador to the Overtyrant'),

    24840: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_1', itemType.tech, 1, 'Progressive tech_emp_enemies', 'Empire Tech: Purge of the Foul'),
    24841: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_2', itemType.tech, 1, 'Progressive tech_emp_enemies', 'Empire Tech: Purge of the Fell'),
    24843: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_3', itemType.tech, 1, 'Progressive tech_emp_enemies', 'Empire Tech: Purge of the Knife-Ears'),
    24844: itemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_4', itemType.tech, 1, 'Progressive tech_emp_enemies', 'Empire Tech: Purge of the Ruinous Breeds'),
}

progUnits: dict[int, itemData] = {
    25200: itemData(IC.useful, 3, "Progressive emp_inf", itemType.unit, 3, "", "Progressive Empire Unit: Infantry"),
    25201: itemData(IC.useful, 3, "Progressive emp_rng", itemType.unit, 3, "", "Progressive Empire Unit: Ranged"),
    25202: itemData(IC.useful, 4, "Progressive emp_cav", itemType.unit, 4, "", "Progressive Empire Unit: Cavalry"),
    25203: itemData(IC.useful, 3, "Progressive emp_art", itemType.unit, 3, "", "Progressive Empire Unit: Artillery"),
    25204: itemData(IC.useful, 4, "Progressive emp_veh", itemType.unit, 4, "", "Progressive Empire Unit: War Machine"),
    25206: itemData(IC.useful, 2, "Progressive emp_hro", itemType.unit, 2, "", "Progressive Empire Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    25300: itemData(IC.useful, 3, 'Progressive emp_resource_animals', itemType.building, 3, None, 'Progressive Empire Building: Animals'),
    25301: itemData(IC.useful, 3, 'Progressive emp_resource_gemstones', itemType.building, 3, None, 'Progressive Empire Building: Gemstones'),
    25302: itemData(IC.useful, 3, 'Progressive emp_resource_medicine', itemType.building, 3, None, 'Progressive Empire Building: Medicine'),
    25303: itemData(IC.useful, 3, 'Progressive emp_resource_obsidian', itemType.building, 3, None, 'Progressive Empire Building: Obsidian'),
    25304: itemData(IC.useful, 3, 'Progressive emp_resource_spices', itemType.building, 3, None, 'Progressive Empire Building: Spices'),
    25305: itemData(IC.useful, 2, 'Progressive emp_roads', itemType.building, 2, None, 'Progressive Empire Building: Roads'),
    25306: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_emp', itemType.building, 3, None, 'Progressive Empire Building: Foreign Slot Discovery Emp'),
    25307: itemData(IC.useful, 3, 'Progressive emp_shooting_range', itemType.building, 3, None, 'Progressive Empire Building: Shooting Range'),
    25308: itemData(IC.useful, 3, 'Progressive emp_wizards', itemType.building, 3, None, 'Progressive Empire Building: Wizards'),
    25309: itemData(IC.useful, 3, 'Progressive emp_allied_outpost', itemType.building, 3, None, 'Progressive Empire Building: Allied Outpost'),
    25310: itemData(IC.useful, 3, 'Progressive emp_resource_ivory', itemType.building, 3, None, 'Progressive Empire Building: Ivory'),
    25311: itemData(IC.useful, 3, 'Progressive emp_barracks', itemType.building, 3, None, 'Progressive Empire Building: Barracks'),
    25312: itemData(IC.useful, 3, 'Progressive emp_farm_basic', itemType.building, 3, None, 'Progressive Empire Building: Farm Basic'),
    25313: itemData(IC.useful, 4, 'Progressive emp_forges', itemType.building, 4, None, 'Progressive Empire Building: Forges'),
    25314: itemData(IC.useful, 2, 'Progressive emp_garrison', itemType.building, 2, None, 'Progressive Empire Building: Garrison'),
    25315: itemData(IC.useful, 3, 'Progressive emp_industry_basic', itemType.building, 3, None, 'Progressive Empire Building: Industry Basic'),
    25316: itemData(IC.useful, 3, 'Progressive emp_port', itemType.building, 3, None, 'Progressive Empire Building: Port'),
    25317: itemData(IC.useful, 3, 'Progressive emp_resource_dyes', itemType.building, 3, None, 'Progressive Empire Building: Dyes'),
    25318: itemData(IC.useful, 3, 'Progressive emp_resource_furs', itemType.building, 3, None, 'Progressive Empire Building: Furs'),
    25319: itemData(IC.useful, 3, 'Progressive emp_resource_gold', itemType.building, 3, None, 'Progressive Empire Building: Gold'),
    25320: itemData(IC.useful, 3, 'Progressive emp_resource_iron', itemType.building, 3, None, 'Progressive Empire Building: Iron'),
    25321: itemData(IC.useful, 3, 'Progressive emp_resource_marble', itemType.building, 3, None, 'Progressive Empire Building: Marble'),
    25322: itemData(IC.useful, 3, 'Progressive emp_resource_pastures', itemType.building, 3, None, 'Progressive Empire Building: Pastures'),
    25323: itemData(IC.useful, 3, 'Progressive emp_resource_pottery', itemType.building, 3, None, 'Progressive Empire Building: Pottery'),
    25324: itemData(IC.useful, 3, 'Progressive emp_resource_salt', itemType.building, 3, None, 'Progressive Empire Building: Salt'),
    25325: itemData(IC.useful, 3, 'Progressive emp_resource_timber', itemType.building, 3, None, 'Progressive Empire Building: Timber'),
    25326: itemData(IC.useful, 3, 'Progressive emp_resource_wine', itemType.building, 3, None, 'Progressive Empire Building: Wine'),
    25327: itemData(IC.useful, 5, 'Progressive emp_settlement_major', itemType.building, 5, None, 'Progressive Empire Building: 4 Major'),
    25328: itemData(IC.useful, 3, 'Progressive emp_settlement_minor', itemType.building, 3, None, 'Progressive Empire Building: Settlement Minor'),
    25329: itemData(IC.useful, 3, 'Progressive emp_stables', itemType.building, 3, None, 'Progressive Empire Building: Stables'),
    25330: itemData(IC.useful, 3, 'Progressive emp_tavern', itemType.building, 3, None, 'Progressive Empire Building: Tavern'),
    25331: itemData(IC.useful, 3, 'Progressive emp_walls', itemType.building, 3, None, 'Progressive Empire Building: Walls'),
    25332: itemData(IC.useful, 2, 'Progressive emp_wizards', itemType.building, 2, None, 'Progressive Empire Building: Wizards'),
    25333: itemData(IC.useful, 2, 'Progressive emp_worship', itemType.building, 2, None, 'Progressive Empire Building: Worship')
}

progTechs: dict[int, itemData] = {
    25400: itemData(IC.useful, 3, "Progressive tech_emp_infantry", itemType.tech, 3, None, "Progressive Empire Tech: Infantry"),
    25401: itemData(IC.useful, 3, "Progressive tech_emp_missiles", itemType.tech, 3, None, "Progressive Empire Tech: Missiles"),
    25402: itemData(IC.useful, 3, "Progressive tech_emp_cavalry", itemType.tech, 3, None, "Progressive Empire Tech: Cavalry"),
    25403: itemData(IC.useful, 3, "Progressive tech_emp_artillery", itemType.tech, 3, None, "Progressive Empire Tech: Artillery"),
    25404: itemData(IC.useful, 3, "Progressive tech_emp_machines", itemType.tech, 3, None, "Progressive Empire Tech: War Machines"),
    25405: itemData(IC.useful, 4, "Progressive tech_emp_industry", itemType.tech, 4, None, "Progressive Empire Tech: Trade & Industry"),
    25406: itemData(IC.useful, 2, "Progressive tech_emp_imperial", itemType.tech, 2, None, "Progressive Empire Tech: Imperial Colleges"),
    25407: itemData(IC.useful, 3, "Progressive tech_emp_magic", itemType.tech, 3, None, "Progressive Empire Tech: Colleges of Magic"),
    25408: itemData(IC.useful, 1, "Progressive tech_emp_diplomacy", itemType.tech, 1, None, "Progressive Empire Tech: Diplomatic Corps"),
    25409: itemData(IC.useful, 1, "Progressive tech_emp_enemies", itemType.tech, 1, None, "Progressive Empire Tech: Enemies of State"),
    25411: itemData(IC.useful, 2, "Progressive tech_emp_faction", itemType.tech, 2, None, "Progressive Empire Tech: Faction"),
}

special: dict[int, specialItemData] = {
    #25500: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_emp_art_helstorm_rocket_battery_morr', itemType.unit, 3, 'Progressive emp_art', False, False, 'Empire Unit: Amethyst Helstorm Rocket Battery'),
    #25501: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_emp_cav_outriders_morr', itemType.unit, 2, 'Progressive emp_cav', False, False, 'Empire Unit: Amethyst Outriders'),
    #25502: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_emp_inf_nuln_ironsides_morr', itemType.unit, 3, 'Progressive emp_rng', False, False, 'Empire Unit: Amethyst Ironsides'),
    #25503: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_emp_veh_marienburg_land_ship_morr', itemType.unit, 4, 'Progressive emp_veh', False, False, 'Empire Unit: Amethyst Land Ship'),
    25504: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_the_huntmarshals_expedition'], 'wh2_dlc13_huntmarshall_veh_obsinite_gyrocopter_0', itemType.unit, 1, 'Progressive emp_veh', False, False, 'Empire Unit: Obsinite Gyrocopters'),
    25505: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_greatswords_ror_0', itemType.unit, 3, 'Progressive emp_inf', False, False, 'Empire Unit: Carroburg Greatswords (Greatswords)'),
    25506: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_halberdiers_ror_0', itemType.unit, 2, 'Progressive emp_inf', False, False, 'Empire Unit: Nordland Mariners (Halberdiers)'),
    25507: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_spearmen_ror_0', itemType.unit, 1, 'Progressive emp_inf', False, False, "Empire Unit: Eldred's Guard (Spearmen – Shields)"),
    25508: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_swordsmen_ror_0', itemType.unit, 1, 'Progressive emp_inf', False, False, 'Empire Unit: Swords of Ulric (Swordsmen)'),
    25509: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_handgunners_ror_0', itemType.unit, 2, 'Progressive emp_rng', False, False, "Empire Unit: Gunderman's Surefires (Handgunners)"),
    25510: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_inf_crossbowmen_ror_0', itemType.unit, 2, 'Progressive emp_rng', False, False, 'Empire Unit: Stir River Patrol (Crossbowmen)'),
    25511: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_cav_empire_knights_ror_0', itemType.unit, 2, 'Progressive emp_cav', False, False, 'Empire Unit: Knights of the Everlasting Light (Empire Knights)'),
    25512: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_cav_empire_knights_ror_1', itemType.unit, 2, 'Progressive emp_cav', False, False, 'Empire Unit: Knights of Morr (Empire Knights)'),
    25513: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_cav_empire_knights_ror_2', itemType.unit, 2, 'Progressive emp_cav', False, False, 'Empire Unit: The Stubborn Bulls (Empire Knights – Greatswords)'),
    25514: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_cav_outriders_ror_0', itemType.unit, 3, 'Progressive emp_cav', False, False, 'Empire Unit: The Bordermen (Outriders – Grenade Launchers)'),
    25515: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_cav_pistoliers_ror_0', itemType.unit, 1, 'Progressive emp_cav', False, False, 'Empire Unit: The Noble Sons Abroad (Pistoliers)'),
    25516: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_veh_steam_tank_driver_ror_0', itemType.unit, 4, 'Progressive emp_veh', False, False, "Empire Unit: The Emperor's Wrath (Steam Tank)"),
    25517: specialItemData(IC.useful, 1, ['wh_main_emp_empire', 'wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh2_dlc13_emp_art_mortar_ror_0', itemType.unit, 1, 'Progressive emp_art', False, False, "Empire Unit: Sootson's Guns (Mortars)"),
    25557: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh2_dlc13_tech_emp_elector_counts_2', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Empire Tech: The Conclave of Light'),
    25558: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh2_dlc13_tech_emp_elector_counts_1', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Emperor of the Empire'),
    25559: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_tech_emp_elspeth_1', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Advisor to Nuln'),
    25560: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_tech_emp_elspeth_2', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: The Amethyst Armourer'),
    25561: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_tech_emp_elspeth_3', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Seeker of Knowledge'),
    25562: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_tech_emp_elspeth_4', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Scion of the Empire'),
    25563: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_tech_emp_gelt_1', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Empire Tech: College Archives'),
    25564: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_tech_emp_gelt_2', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Cataclysmic Power'),
    25565: specialItemData(IC.useful, 1, ['wh3_main_emp_cult_of_sigmar'], 'wh3_main_tech_emp_fanatics_decree_volkmar', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, "Empire Tech: Fanatic's Decree"),
    25566: specialItemData(IC.useful, 1, ['wh3_main_emp_cult_of_sigmar'], 'wh3_main_tech_emp_divine_mandate_volkmar', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Divine Mandate'),
    25567: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_the_huntmarshals_expedition'], 'wh2_dlc13_tech_emp_wulfhart_1', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, "Empire Tech: Hunters' Guild"),
    25568: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_the_huntmarshals_expedition'], 'wh2_dlc13_tech_emp_wulfhart_2', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Colonial Fort'),
    25569: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_the_huntmarshals_expedition'], 'wh2_dlc13_tech_emp_wulfhart_3', itemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Seaborne Logistics'),
    25570: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_the_huntmarshals_expedition'], 'wh2_dlc13_tech_emp_wulfhart_4', itemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Empire Tech: Imperial Reinforcements'),
    25571: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_1', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Swords of the Empire'),
    25572: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_2', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Spears of the Empire'),
    25573: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_3', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Marksman of the Empire'),
    25574: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_4', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Machines of the Empire'),
    25575: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_5', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Riders of the Empire'),
    25576: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'wh3_dlc25_tech_emp_state_troops_6', itemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Empire Tech: Knights of the Empire'),
    25577: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland', 'wh2_dlc13_emp_golden_order', 'wh3_main_emp_cult_of_sigmar'], 'Progressive tech_emp_troops', itemType.tech, 1, None, False, True, 'Progressive Empire Tech: State Troops'),
}

rituals: dict[int, specialItemData] = {
    25600: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_call_to_arms', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Call to Arms'),
    25601: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_casus_belli', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Casus Belli'),
    25602: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_conscription', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Conscription'),
    25603: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_imperial_commendation', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Commendation'),
    25604: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_inquisition', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Inquisition'),
    25605: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_open_the_gates', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Open the Gates'),
    25606: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_requisition', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Requisition'),
    25607: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_send_aid', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Send Aid'),
    25608: specialItemData(IC.useful, 1, ['wh_main_emp_empire'], 'wh3_dlc25_emperors_decrees_unify', itemType.ritual, 1, 'Progressive emp_ritual_decree', True, False, 'Empire Decree: Unify'),

    25609: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_amber', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Amber Wizard'),
    25610: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_amethyst', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Amethyst Wizard'),
    25611: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_bright', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Bright Wizard'),
    25612: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_celestial', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Celestial Wizard'),
    25613: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_grey', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Grey Wizard'),
    25614: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_jade', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Jade Wizard'),
    25615: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_light', itemType.ritual, 1, 'Progressive emp_ritual_college', False, False, 'Empire College of Magic: Light Wizard'),
    25616: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_wizard_metal', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Gold Wizard'),

    25617: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amethyst_damage_enemies', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Shyish Storm'),
    25618: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amethyst_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Ashes & Dust'),
    25619: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amethyst_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Amethyst Magisters'),
    25620: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amethyst_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Hourglass of the Shyish Sands'),

    25621: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amber_summon', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Call of the Wild'),
    25622: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amber_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, "Empire College of Magic: Merciw's Monstrous Regiment"),
    25623: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amber_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Amber Magisters'),
    25624: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_amber_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Cloak of Anraheir'),

    25625: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_bright_damage_walls', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: The Bright Key'),
    25626: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_bright_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Magma Storm'),
    25627: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_bright_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Bright Magisters'),
    25628: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_bright_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Torched Staff of Wrath'),

    25629: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_celestial_action_points', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Celestial Scrying'),
    25630: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_celestial_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, "Empire College of Magic: Thorsen's Thunderstorm"),
    25631: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_celestial_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Celestial Magisters'),
    25632: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_celestial_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Astrolobe of Tomorrows Moon'),

    25633: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_grey_ambush_attack', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Mass Concealment'),
    25634: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_grey_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Dance of Despair'),
    25635: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_grey_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Grey Magisters'),
    25636: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_grey_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: The Grey Wand'),

    25637: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_jade_heal', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Restoration'),
    25638: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_jade_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Storm of Renewal'),
    25639: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_jade_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Jade Magisters'),
    25640: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_jade_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Oaken Sickle of Ghyran'),

    25641: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_light_barrier', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Barrier of Light'),
    25642: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_light_cata_spell', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Time Amok'),
    25643: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_light_costs', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Light Magisters'),
    25644: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_light_item', itemType.ritual, 2, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Amulet of Refraction'),

    25645: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_transmutation', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Transmutation'),
    25646: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_corrosion', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Compelled Corrosion'),
    25647: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_costs', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Metal Magisters'),
    25648: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_cata_spell', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, "Empire College of Magic: Gehenna's Golden Globe"),
    25649: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_armour', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Robes of the Supreme Patriarch'),
    25650: specialItemData(IC.useful, 1, ['wh2_dlc13_emp_golden_order'], 'wh3_dlc25_college_of_magic_metal_weapon', itemType.ritual, 1, 'Progressive emp_ritual_college', True, False, 'Empire College of Magic: Transmuted Blade'),

    25651: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_inf_guns_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_infantry', False, False, "Empire Gunnery School: Artisan Firearm Shot"),
    25652: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_inf_guns_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_infantry', True, False, "Empire Gunnery School: Quick-Load Mechanisms"),
    25653: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_inf_guns_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_infantry', True, False, "Empire Gunnery School: Exploding Bullets"),
    25654: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cav_guns_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_cavalry', False, False, "Empire Gunnery School: Thoroughbred Steeds"),
    25655: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cav_guns_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_cavalry', True, False, "Empire Gunnery School: Saddle Sack Munitions"),
    25656: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cav_guns_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_cavalry', True, False, "Empire Gunnery School: Interference Tactics"),
    25657: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_mortors_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_mortar', False, False, "Empire Gunnery School: Extra Gunpowder"),
    25658: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_mortors_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_mortar', True, False, "Empire Gunnery School: Camouflaged Netting"),
    25659: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_mortors_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_mortar', True, False, "Empire Gunnery School: Concussive Blasts"),
    25660: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cannons_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_cannon', False, False, "Empire Gunnery School: Weighted Munitions"),
    25661: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cannons_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_cannon', True, False, "Empire Gunnery School: High-Pressure Barrels"),
    25662: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_cannons_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_cannon', True, False, "Empire Gunnery School: Grapeshot"),
    25663: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helblasters_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_blaster', False, False, "Empire Gunnery School: Rapid Reposition Drills"),
    25664: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helblasters_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_blaster', True, False, "Empire Gunnery School: Suppressive Fire"),
    25665: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helblasters_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_blaster', True, False, "Empire Gunnery School: Penetrating Shots"),
    25666: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helstorm_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_helstorm', False, False, "Empire Gunnery School: More Rockets"),
    25667: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helstorm_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_helstorm', True, False, "Empire Gunnery School: More Rockets!!"),
    25668: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_helstorm_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_helstorm', True, False, "Empire Gunnery School: MORE ROCKETS!!!"),
    25669: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_steam_tank_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_tank', False, False, "Empire Gunnery School: Better Engines"),
    25670: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_steam_tank_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_tank', True, False, "Empire Gunnery School: Exploding Cannon Balls"),
    25671: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_steam_tank_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_tank', True, False, "Empire Gunnery School: Field Engineers"),
    25672: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_land_ship_1', itemType.ritual, 1, 'Progressive emp_ritual_gunnery_landship', False, False, "Empire Gunnery School: External Spearports"),
    25673: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_land_ship_2', itemType.ritual, 2, 'Progressive emp_ritual_gunnery_landship', True, False, "Empire Gunnery School: Reinforced Hulls"),
    25674: specialItemData(IC.useful, 1, ['wh_main_emp_wissenland'], 'wh3_dlc25_ritual_emp_don_land_ship_3', itemType.ritual, 3, 'Progressive emp_ritual_gunnery_landship', True, False, "Empire Gunnery School: Land Mines"),

    25675: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_amethyst_ironsides_1", itemType.ritual, 1, "Progressive emp_ritual_gunnery_amethyst_ironside", True, False, "Empire Gunnery School: Frontline Training"),
    25676: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_amethyst_ironsides_2", itemType.ritual, 2, "Progressive emp_ritual_gunnery_amethyst_ironside", True, False, "Empire Gunnery School: Ballistics Plating"),
    25677: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_amethyst_ironsides_3", itemType.ritual, 3, "Progressive emp_ritual_gunnery_amethyst_ironside", True, False, "Empire Gunnery School: Debilitating Shots"),
    25678: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_amethyst_ironsides_4", itemType.ritual, 4, "Progressive emp_ritual_gunnery_amethyst_ironside", True, False, "Empire Gunnery School: Iron Resolve"),

    25679: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_buckshot_reaper_1", itemType.ritual, 1, "Progressive emp_ritual_gunnery_amethyst_outrider", True, False, "Empire Gunnery School: Cycle Charge Drills"),
    25680: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_buckshot_reaper_2", itemType.ritual, 2, "Progressive emp_ritual_gunnery_amethyst_outrider", True, False, "Empire Gunnery School: Guerrilla Warfare"),
    25681: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_buckshot_reaper_3", itemType.ritual, 3, "Progressive emp_ritual_gunnery_amethyst_outrider", True, False, "Empire Gunnery School: Dreadknight"),
    25682: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_buckshot_reaper_4", itemType.ritual, 4, "Progressive emp_ritual_gunnery_amethyst_outrider", True, False, "Empire Gunnery School: Flared Muzzles"),

    25683: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_deathstorm_battery_1", itemType.ritual, 1, "Progressive emp_ritual_gunnery_amethyst_helstorm", True, False, "Empire Gunnery School: Improved Trajectories"),
    25684: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_deathstorm_battery_2", itemType.ritual, 2, "Progressive emp_ritual_gunnery_amethyst_helstorm", True, False, "Empire Gunnery School: Extended Training Drills"),
    25685: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_deathstorm_battery_3", itemType.ritual, 3, "Progressive emp_ritual_gunnery_amethyst_helstorm", True, False, "Empire Gunnery School: Greater Infusions"),
    25686: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_deathstorm_battery_4", itemType.ritual, 4, "Progressive emp_ritual_gunnery_amethyst_helstorm", True, False, "Empire Gunnery School: Last Rites"),

    #25687: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_black_rose_1", itemType.ritual, 1, "Progressive emp_ritual_gunnery_amethyst_landship", True, False, "Empire Gunnery School: Sails of Shyish"),
    #25688: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_black_rose_2", itemType.ritual, 2, "Progressive emp_ritual_gunnery_amethyst_landship", True, False, "Empire Gunnery School: Catacomb Cannon"),
    #25689: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_black_rose_3", itemType.ritual, 3, "Progressive emp_ritual_gunnery_amethyst_landship", True, False, "Empire Gunnery School: Amethyst Admiral"),
    #25690: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_black_rose_4", itemType.ritual, 4, "Progressive emp_ritual_gunnery_amethyst_landship", True, False, "Empire Gunnery School: Cremation Engines"),

    25691: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_amethyst_ironsides_cap", itemType.ritual, 1, "Progressive emp_ritual_gunnery_ironside_cap", True, False, "Empire Gunnery School: Amethyst Ironsides Cap Increase"),
    25692: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_buckshot_reaper_cap", itemType.ritual, 1, "Progressive emp_ritual_gunnery_outrider_cap", True, False, "Empire Gunnery School: Amethyst Outriders Cap Increase"),
    25693: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_deathstorm_battery_cap", itemType.ritual, 1, "Progressive emp_ritual_gunnery_helstorm_cap", True, False, "Empire Gunnery School: Amethyst Helstorm Rocket Battery Cap Increase"),
    #25694: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_black_rose_cap", itemType.ritual, 1, "Progressive emp_ritual_gunnery_landship_cap", True, False, "Empire Gunnery School: Amethyst Land Ship Cap Increase"),

    25695: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_bjuna_bombard", itemType.ritual, 1, "Progressive emp_ritual_gunnery_bjuna", True, False, "Empire Gunnery School: Bjuna Bombard"),
    25696: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_spirit_barrage", itemType.ritual, 1, "Progressive emp_ritual_gunnery_barrage", True, False, "Empire Gunnery School: Spirit Barrage"),
    #25697: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_emp_don_purple_eclipse", itemType.ritual, 1, "Progressive emp_ritual_gunnery_eclipse", True, False, "Empire Gunnery School: The Purple Eclipse"),

    25698: specialItemData(IC.useful, 1, ["wh_main_emp_wissenland"], "wh3_dlc25_ritual_construct_black_tower", itemType.ritual, 1, "Progressive emp_ritual_garden", True, False, "Empire Gardens of Morr: Construct Garden"),

    #"wh_main_ritual_emp_policy"
}