from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData

# @formatter:off
units: dict[int, itemData] = {
    30035: itemData(IC.useful, 1, 'wh2_dlc15_hef_inf_rangers_0', itemType.unit, 1, 'progressive hef_inf', 'HighElf Unit: Rangers'),
    30071: itemData(IC.useful, 1, 'wh3_dlc27_hef_inf_ships_company', itemType.unit, 1, 'progressive hef_inf', "HighElf Unit: Ship's Company"),
    30008: itemData(IC.useful, 1, 'wh2_main_hef_inf_spearmen_0', itemType.unit, 1, 'progressive hef_inf', 'HighElf Unit: Spearmen'),
    30011: itemData(IC.useful, 1, 'wh2_main_hef_inf_lothern_sea_guard_0', itemType.unit, 2, 'progressive hef_inf', 'HighElf Unit: Lothern Sea Guard'),
    30010: itemData(IC.useful, 1, 'wh2_main_hef_inf_lothern_sea_guard_1', itemType.unit, 3, 'progressive hef_inf', 'HighElf Unit: Lothern Sea Guard (Shields)'),
    30034: itemData(IC.useful, 1, 'wh2_dlc15_hef_inf_silverin_guard_0', itemType.unit, 3, 'progressive hef_inf', 'HighElf Unit: Silverin Guard'),
    30006: itemData(IC.useful, 1, 'wh2_main_hef_inf_white_lions_of_chrace_0', itemType.unit, 3, 'progressive hef_inf', 'HighElf Unit: White Lions of Chrace'),
    30007: itemData(IC.useful, 1, 'wh2_main_hef_inf_swordmasters_of_hoeth_0', itemType.unit, 4, 'progressive hef_inf', 'HighElf Unit: Swordmasters of Hoeth'),
    30009: itemData(IC.useful, 1, 'wh2_main_hef_inf_phoenix_guard', itemType.unit, 4, 'progressive hef_inf', 'HighElf Unit: Phoenix Guard'),

    30013: itemData(IC.useful, 1, 'wh2_main_hef_inf_archers_1', itemType.unit, 1, 'progressive hef_rng', 'HighElf Unit: Archers (Light Armour)'),
    30014: itemData(IC.useful, 1, 'wh2_main_hef_inf_archers_0', itemType.unit, 1, 'progressive hef_rng', 'HighElf Unit: Archers'),
    30050: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_shadow_warriors_0', itemType.unit, 2, 'progressive hef_rng', 'HighElf Unit: Shadow Warriors'),
    30048: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_sisters_of_avelorn_0', itemType.unit, 3, 'progressive hef_rng', 'HighElf Unit: Sisters of Avelorn'),

    30028: itemData(IC.useful, 1, 'wh2_main_hef_cav_ellyrian_reavers_0', itemType.unit, 1, 'progressive hef_cav', 'HighElf Unit: Ellyrian Reavers'),
    30027: itemData(IC.useful, 1, 'wh2_main_hef_cav_ellyrian_reavers_1', itemType.unit, 1, 'progressive hef_cav', 'HighElf Unit: Ellyrian Reaver Archers'),
    30025: itemData(IC.useful, 1, 'wh2_main_hef_cav_silver_helms_0', itemType.unit, 2, 'progressive hef_cav', 'HighElf Unit: Silver Helms'),
    30024: itemData(IC.useful, 1, 'wh2_main_hef_cav_silver_helms_1', itemType.unit, 2, 'progressive hef_cav', 'HighElf Unit: Silver Helms (Shields)'),
    30029: itemData(IC.useful, 1, 'wh2_main_hef_cav_dragon_princes', itemType.unit, 3, 'progressive hef_cav', 'HighElf Unit: Dragon Princes'),

    30030: itemData(IC.useful, 1, 'wh2_main_hef_art_eagle_claw_bolt_thrower', itemType.unit, 1, 'progressive hef_art', 'HighElf Unit: Eagle Claw Bolt Throwers'),

    30000: itemData(IC.useful, 1, 'wh2_main_hef_mon_sun_dragon', itemType.unit, 3, 'progressive hef_bst', 'HighElf Unit: Sun Dragon'),
    30004: itemData(IC.useful, 1, 'wh2_main_hef_mon_moon_dragon', itemType.unit, 3, 'progressive hef_bst', 'HighElf Unit: Moon Dragon'),
    30001: itemData(IC.useful, 1, 'wh2_main_hef_mon_star_dragon', itemType.unit, 4, 'progressive hef_bst', 'HighElf Unit: Star Dragon'),
    30002: itemData(IC.useful, 1, 'wh2_main_hef_mon_phoenix_frostheart', itemType.unit, 3, 'progressive hef_bst', 'HighElf Unit: Frostheart Phoenix'),
    30003: itemData(IC.useful, 1, 'wh2_main_hef_mon_phoenix_flamespyre', itemType.unit, 2, 'progressive hef_bst', 'HighElf Unit: Flamespyre Phoenix'),
    30005: itemData(IC.useful, 1, 'wh2_main_hef_mon_great_eagle', itemType.unit, 1, 'progressive hef_bst', 'HighElf Unit: Great Eagle'),
    30032: itemData(IC.useful, 1, 'wh2_dlc15_hef_mon_war_lions_of_chrace_0', itemType.unit, 1, 'progressive hef_bst', 'HighElf Unit: War Lions of Chrace'),
    30033: itemData(IC.useful, 1, 'wh2_dlc15_hef_mon_arcane_phoenix_0', itemType.unit, 4, 'progressive hef_bst', 'HighElf Unit: Arcane Phoenix'),
    30070: itemData(IC.useful, 1, 'wh3_dlc27_hef_inf_oceanids', itemType.unit, 2, 'progressive hef_bst', 'HighElf Unit: Oceanids'),
    30068: itemData(IC.useful, 1, 'wh3_dlc27_hef_mon_sea_elemental', itemType.unit, 3, 'progressive hef_bst', 'HighElf Unit: Sea Elemental'),
    30069: itemData(IC.useful, 1, 'wh3_dlc27_hef_mon_merwyrm', itemType.unit, 4, 'progressive hef_bst', 'HighElf Unit: Merwyrm'),

    30023: itemData(IC.useful, 1, 'wh2_main_hef_cav_tiranoc_chariot', itemType.unit, 2, 'progressive hef_veh', 'HighElf Unit: Tiranoc Chariots'),
    30026: itemData(IC.useful, 1, 'wh2_main_hef_cav_ithilmar_chariot', itemType.unit, 1, 'progressive hef_veh', 'HighElf Unit: Ithilmar Chariots'),
    30031: itemData(IC.useful, 1, 'wh2_dlc15_hef_veh_lion_chariot_of_chrace_0', itemType.unit, 3, 'progressive hef_veh', 'HighElf Unit: Lion Chariots of Chrace'),
    30073: itemData(IC.useful, 1, 'wh3_dlc27_hef_veh_skycutter_bows', itemType.unit, 3, 'progressive hef_veh', 'HighElf Unit: Lothern Skycutters'),
    30074: itemData(IC.useful, 1, 'wh3_dlc27_hef_veh_skycutter_bolt_thrower', itemType.unit, 3, 'progressive hef_veh', 'HighElf Unit: Lothern Skycutters (Bolt Thrower)'),

    30044: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_the_storm_riders_ror_0', itemType.unit, 2, 'progressive hef_inf', 'HighElf Unit: The Storm Riders (Lothern Sea Guard)'),
    30045: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_the_silverpelts_ror_0', itemType.unit, 3, 'progressive hef_inf', 'HighElf Unit: The Puremane Company (White Lions of Chrace)'),
    30046: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_the_scions_of_mathlann_ror_0', itemType.unit, 1, 'progressive hef_inf', 'HighElf Unit: The Scions of Mathlann (Spearmen)'),
    30047: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_the_grey_ror_0', itemType.unit, 2, 'progressive hef_rng', 'HighElf Unit: The Grey (Shadow Warriors)'),
    30051: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_keepers_of_the_flame_ror_0', itemType.unit, 4, 'progressive hef_inf', 'HighElf Unit: Keepers of the Flame (Phoenix Guard)'),
    30052: itemData(IC.useful, 1, 'wh2_dlc10_hef_inf_everqueens_court_guards_ror_0', itemType.unit, 3, 'progressive hef_rng', "HighElf Unit: Everqueen's Court Guards (Sisters of Avelorn)"),
    30057: itemData(IC.useful, 1, 'wh2_dlc10_hef_cav_the_heralds_of_the_wind_ror_0', itemType.unit, 1, 'progressive hef_cav', 'HighElf Unit: Heralds of the Wind (Ellyrian Reavers - Bows)'),
    30058: itemData(IC.useful, 1, 'wh2_dlc10_hef_cav_the_fireborn_ror_0', itemType.unit, 3, 'progressive hef_cav', 'HighElf Unit: The Fireborn (Dragon Princes)'),
    30075: itemData(IC.useful, 1, 'wh3_dlc27_hef_inf_ships_company_ror', itemType.unit, 1, 'progressive hef_inf', "HighElf Unit: Company of the Kalendirian (Ship's Company)"),
    30076: itemData(IC.useful, 1, 'wh3_dlc27_hef_inf_swordmasters_of_hoeth_ror', itemType.unit, 4, 'progressive hef_inf', 'HighElf Unit: Blades of Hoeth (Swordmasters of Hoeth)'),
    30077: itemData(IC.useful, 1, 'wh3_dlc27_hef_mon_merwyrm_ror', itemType.unit, 4, 'progressive hef_bst', 'HighElf Unit: Silak One-eye (Merwyrm)'),

    30019: itemData(IC.useful, 1, 'wh2_main_hef_cha_noble_0', itemType.unit, 1, 'progressive hef_hro', 'HighElf Unit: Noble'),
    30054: itemData(IC.useful, 1, 'wh2_dlc10_hef_cha_handmaiden_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Handmaiden of the Everqueen'),
    30022: itemData(IC.useful, 1, 'wh2_main_hef_cha_loremaster_of_hoeth_0', itemType.unit, 3, 'progressive hef_hro', 'HighElf Unit: Loremaster of Hoeth'),
    30021: itemData(IC.useful, 1, 'wh2_main_hef_cha_mage_high_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (High)'),
    30059: itemData(IC.useful, 1, 'wh2_dlc10_hef_cha_mage_heavens_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Heavens)'),
    30060: itemData(IC.useful, 1, 'wh2_dlc15_hef_cha_mage_fire_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Fire)'),
    30061: itemData(IC.useful, 1, 'wh2_dlc15_hef_cha_mage_metal_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Metal)'),
    30062: itemData(IC.useful, 1, 'wh2_dlc15_hef_cha_mage_beasts_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Beasts)'),
    30063: itemData(IC.useful, 1, 'wh2_dlc10_hef_cha_mage_shadows_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Shadows)'),
    30064: itemData(IC.useful, 1, 'wh2_main_hef_cha_mage_light_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Light)'),
    30065: itemData(IC.useful, 1, 'wh2_main_hef_cha_mage_life_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Life)'),
    30066: itemData(IC.useful, 1, 'wh2_dlc15_hef_cha_mage_death_0', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mage (Death)'),
    30067: itemData(IC.useful, 1, 'wh3_dlc27_hef_cha_mist_mage', itemType.unit, 2, 'progressive hef_hro', 'HighElf Unit: Mist Mage'),
}

buildings: dict[int, itemData] = {
    #30407: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_hef_1', ItemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Tor Yvresse (Elven Hamlet)'),
    #30409: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_hef_2', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Tor Yvresse (Elven Village)'),
    #30411: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_hef_3', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Tor Yvresse (Elven Town)'),
    #30413: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_hef_4', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Tor Yvresse (Elven City)'),
    #30414: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_hef_5', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Tor Yvresse (Spired Citadel)'),
    30416: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_hef_1', itemType.building, 0, 'Progressive foreign_slot_discovery_hef', 'HighElf Building: City Tunnels'),
    30417: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_hef_2', itemType.building, 1, 'Progressive foreign_slot_discovery_hef', 'HighElf Building: Tunnel Watchmen'),
    30418: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_hef_3', itemType.building, 2, 'Progressive foreign_slot_discovery_hef', 'HighElf Building: Blockaded Tunnels'),
    30419: itemData(IC.useful, 1, 'wh2_main_hef_barracks_1', itemType.building, 0, 'progressive hef_barracks', 'HighElf Building: Militia Camp'),
    30420: itemData(IC.useful, 1, 'wh2_main_hef_barracks_2', itemType.building, 1, 'progressive hef_barracks', 'HighElf Building: Rally Field'),
    30421: itemData(IC.useful, 1, 'wh2_main_hef_barracks_3', itemType.building, 2, 'progressive hef_barracks', 'HighElf Building: War Hall'),
    30422: itemData(IC.useful, 1, 'wh2_main_hef_court_1', itemType.building, 0, 'progressive hef_court', 'HighElf Building: Elven Gardens'),
    30423: itemData(IC.useful, 1, 'wh2_main_hef_court_2', itemType.building, 1, 'progressive hef_court', 'HighElf Building: Elven Court'),
    30424: itemData(IC.useful, 1, 'wh2_main_hef_defence_major_1', itemType.building, 0, 'progressive hef_defence_major', 'HighElf Building: Stone Walls'),
    30425: itemData(IC.useful, 1, 'wh2_main_hef_defence_major_2', itemType.building, 1, 'progressive hef_defence_major', 'HighElf Building: Enchanted Walls'),
    30426: itemData(IC.useful, 1, 'wh2_main_hef_defence_major_3', itemType.building, 2, 'progressive hef_defence_major', 'HighElf Building: Warded Walls'),
    30427: itemData(IC.useful, 1, 'wh2_main_hef_defence_minor_1', itemType.building, 0, 'progressive hef_defence_minor', 'HighElf Building: Watchtower'),
    30428: itemData(IC.useful, 1, 'wh2_main_hef_defence_minor_2', itemType.building, 1, 'progressive hef_defence_minor', 'HighElf Building: Royal Garrison'),
    30430: itemData(IC.useful, 1, 'wh2_main_hef_dragons_1', itemType.building, 0, 'progressive hef_dragons', "HighElf Building: Dragon's Lair"),
    30431: itemData(IC.useful, 1, 'wh2_main_hef_dragons_2', itemType.building, 1, 'progressive hef_dragons', 'HighElf Building: Dragon Keep'),
    30432: itemData(IC.useful, 1, 'wh2_main_hef_embassy_1', itemType.building, 0, 'progressive hef_embassy', 'HighElf Building: Elven Embassy'),
    30433: itemData(IC.useful, 1, 'wh2_main_hef_farm_1', itemType.building, 0, 'progressive hef_farm', 'HighElf Building: Homestead'),
    30434: itemData(IC.useful, 1, 'wh2_main_hef_farm_2', itemType.building, 1, 'progressive hef_farm', 'HighElf Building: Manor'),
    30435: itemData(IC.useful, 1, 'wh2_main_hef_farm_3', itemType.building, 2, 'progressive hef_farm', 'HighElf Building: Estate'),
    30436: itemData(IC.useful, 1, 'wh2_main_hef_hunters_1', itemType.building, 0, 'progressive hef_hunters', 'HighElf Building: Grove'),
    30437: itemData(IC.useful, 1, 'wh2_main_hef_hunters_2', itemType.building, 1, 'progressive hef_hunters', 'HighElf Building: Greater Grove'),
    30402: itemData(IC.useful, 1, 'wh2_dlc10_hef_hunters_3', itemType.building, 2, 'progressive hef_hunters', 'HighElf Building: Blessed Grove'),
    30438: itemData(IC.useful, 1, 'wh2_main_hef_industry_1', itemType.building, 0, 'progressive hef_industry', 'HighElf Building: Elven Craftsman'),
    30439: itemData(IC.useful, 1, 'wh2_main_hef_industry_2', itemType.building, 1, 'progressive hef_industry', 'HighElf Building: Elven Artisan'),
    30440: itemData(IC.useful, 1, 'wh2_main_hef_industry_3', itemType.building, 2, 'progressive hef_industry', 'HighElf Building: Elven Fairground'),
    30441: itemData(IC.useful, 1, 'wh2_main_hef_mages_1', itemType.building, 0, 'progressive hef_mages', 'HighElf Building: Archive'),
    30442: itemData(IC.useful, 1, 'wh2_main_hef_mages_2', itemType.building, 1, 'progressive hef_mages', 'HighElf Building: Grand Repository'),
    30443: itemData(IC.useful, 1, 'wh2_main_hef_mages_3', itemType.building, 2, 'progressive hef_mages', 'HighElf Building: Tower of Mages'),
    30444: itemData(IC.useful, 1, 'wh2_main_hef_order_1', itemType.building, 0, 'progressive hef_order', 'HighElf Building: Plaza'),
    30445: itemData(IC.useful, 1, 'wh2_main_hef_order_2', itemType.building, 1, 'progressive hef_order', 'HighElf Building: Colonnade'),
    30446: itemData(IC.useful, 1, 'wh2_main_hef_order_3', itemType.building, 2, 'progressive hef_order', 'HighElf Building: Promenade'),
    30447: itemData(IC.useful, 1, 'wh2_main_hef_order_4', itemType.building, 3, 'progressive hef_order', 'HighElf Building: Theatre'),
    30448: itemData(IC.useful, 1, 'wh2_main_hef_order_5', itemType.building, 4, 'progressive hef_order', 'HighElf Building: Amphitheatre'),
    30449: itemData(IC.useful, 1, 'wh2_main_hef_port_1', itemType.building, 0, 'progressive hef_port', 'HighElf Building: Docks'),
    30450: itemData(IC.useful, 1, 'wh2_main_hef_port_2', itemType.building, 1, 'progressive hef_port', 'HighElf Building: Harbour'),
    30451: itemData(IC.useful, 1, 'wh2_main_hef_port_3', itemType.building, 2, 'progressive hef_port', 'HighElf Building: Seaport'),
    30452: itemData(IC.useful, 1, 'wh2_main_hef_resource_animals_1', itemType.building, 0, 'progressive hef_resource_animals', 'HighElf Building: Exotic Animal Tamer'),
    30453: itemData(IC.useful, 1, 'wh2_main_hef_resource_animals_2', itemType.building, 1, 'progressive hef_resource_animals', 'HighElf Building: Exotic Pet Store'),
    30454: itemData(IC.useful, 1, 'wh2_main_hef_resource_animals_3', itemType.building, 2, 'progressive hef_resource_animals', 'HighElf Building: Exotic Animal Bazaar'),
    30455: itemData(IC.useful, 1, 'wh2_main_hef_resource_dyes_1', itemType.building, 0, 'progressive hef_resource_dyes', 'HighElf Building: Cinnabar Mining Pit'),
    30456: itemData(IC.useful, 1, 'wh2_main_hef_resource_dyes_2', itemType.building, 1, 'progressive hef_resource_dyes', 'HighElf Building: Cinnabar Mine'),
    30457: itemData(IC.useful, 1, 'wh2_main_hef_resource_dyes_3', itemType.building, 2, 'progressive hef_resource_dyes', 'HighElf Building: Dyemaker'),
    30458: itemData(IC.useful, 1, 'wh2_main_hef_resource_furs_1', itemType.building, 0, 'progressive hef_resource_furs', 'HighElf Building: Hunting Camp'),
    30459: itemData(IC.useful, 1, 'wh2_main_hef_resource_furs_2', itemType.building, 1, 'progressive hef_resource_furs', 'HighElf Building: Hunting Lodge'),
    30460: itemData(IC.useful, 1, 'wh2_main_hef_resource_furs_3', itemType.building, 2, 'progressive hef_resource_furs', 'HighElf Building: Tannery'),
    30461: itemData(IC.useful, 1, 'wh2_main_hef_resource_gems_1', itemType.building, 0, 'progressive hef_resource_gems', 'HighElf Building: Gem Mineshaft'),
    30462: itemData(IC.useful, 1, 'wh2_main_hef_resource_gems_2', itemType.building, 1, 'progressive hef_resource_gems', 'HighElf Building: Gem Mine'),
    30463: itemData(IC.useful, 1, 'wh2_main_hef_resource_gems_3', itemType.building, 2, 'progressive hef_resource_gems', "HighElf Building: Gemcutter's Atelier"),
    30464: itemData(IC.useful, 1, 'wh2_main_hef_resource_gold_1', itemType.building, 0, 'progressive hef_resource_gold', 'HighElf Building: Gold Mining Pit'),
    30465: itemData(IC.useful, 1, 'wh2_main_hef_resource_gold_2', itemType.building, 1, 'progressive hef_resource_gold', 'HighElf Building: Gold Mine'),
    30466: itemData(IC.useful, 1, 'wh2_main_hef_resource_gold_3', itemType.building, 2, 'progressive hef_resource_gold', 'HighElf Building: Mint'),
    30467: itemData(IC.useful, 1, 'wh2_main_hef_resource_iron_1', itemType.building, 0, 'progressive hef_resource_iron', 'HighElf Building: Iron Mining Pit'),
    30468: itemData(IC.useful, 1, 'wh2_main_hef_resource_iron_2', itemType.building, 1, 'progressive hef_resource_iron', 'HighElf Building: Iron Mine'),
    30469: itemData(IC.useful, 1, 'wh2_main_hef_resource_iron_3', itemType.building, 2, 'progressive hef_resource_iron', 'HighElf Building: Iron Smelter'),
    30470: itemData(IC.useful, 1, 'wh2_main_hef_resource_marble_1', itemType.building, 0, 'progressive hef_resource_marble', 'HighElf Building: Sawyer'),
    30471: itemData(IC.useful, 1, 'wh2_main_hef_resource_marble_2', itemType.building, 1, 'progressive hef_resource_marble', 'HighElf Building: Marble Quarry'),
    30472: itemData(IC.useful, 1, 'wh2_main_hef_resource_marble_3', itemType.building, 2, 'progressive hef_resource_marble', "HighElf Building: Sculptor's Workshop"),
    30473: itemData(IC.useful, 1, 'wh2_main_hef_resource_medicine_1', itemType.building, 0, 'progressive hef_resource_medicine', "HighElf Building: Herb Gatherer's Camp"),
    30474: itemData(IC.useful, 1, 'wh2_main_hef_resource_medicine_2', itemType.building, 1, 'progressive hef_resource_medicine', 'HighElf Building: Exotic Hothouse'),
    30475: itemData(IC.useful, 1, 'wh2_main_hef_resource_medicine_3', itemType.building, 2, 'progressive hef_resource_medicine', 'HighElf Building: Alchemy Workshop'),
    30476: itemData(IC.useful, 1, 'wh2_main_hef_resource_obsidian_1', itemType.building, 0, 'progressive hef_resource_obsidian', 'HighElf Building: Obsidian Quarry'),
    30477: itemData(IC.useful, 1, 'wh2_main_hef_resource_obsidian_2', itemType.building, 1, 'progressive hef_resource_obsidian', 'HighElf Building: Obsidian Trinket Maker'),
    30478: itemData(IC.useful, 1, 'wh2_main_hef_resource_obsidian_3', itemType.building, 2, 'progressive hef_resource_obsidian', 'HighElf Building: Obsidian Amulet Carver'),
    30479: itemData(IC.useful, 1, 'wh2_main_hef_resource_pasture_1', itemType.building, 0, 'progressive hef_resource_pasture', 'HighElf Building: Grazing Pastures'),
    30480: itemData(IC.useful, 1, 'wh2_main_hef_resource_pasture_2', itemType.building, 1, 'progressive hef_resource_pasture', 'HighElf Building: Livestock Pens'),
    30481: itemData(IC.useful, 1, 'wh2_main_hef_resource_pasture_3', itemType.building, 2, 'progressive hef_resource_pasture', 'HighElf Building: Cattle Ranch'),
    30482: itemData(IC.useful, 1, 'wh2_main_hef_resource_pottery_1', itemType.building, 0, 'progressive hef_resource_pottery', 'HighElf Building: Clay Pit'),
    30483: itemData(IC.useful, 1, 'wh2_main_hef_resource_pottery_2', itemType.building, 1, 'progressive hef_resource_pottery', 'HighElf Building: Pottery Maker'),
    30484: itemData(IC.useful, 1, 'wh2_main_hef_resource_pottery_3', itemType.building, 2, 'progressive hef_resource_pottery', 'HighElf Building: Kilns'),
    30485: itemData(IC.useful, 1, 'wh2_main_hef_resource_salt_1', itemType.building, 0, 'progressive hef_resource_salt', 'HighElf Building: Salt Flats'),
    30486: itemData(IC.useful, 1, 'wh2_main_hef_resource_salt_2', itemType.building, 1, 'progressive hef_resource_salt', 'HighElf Building: Salt Pans'),
    30487: itemData(IC.useful, 1, 'wh2_main_hef_resource_salt_3', itemType.building, 2, 'progressive hef_resource_salt', 'HighElf Building: Salt Distillery'),
    30488: itemData(IC.useful, 1, 'wh2_main_hef_resource_spices_1', itemType.building, 0, 'progressive hef_resource_spices', 'HighElf Building: Spice Market'),
    30489: itemData(IC.useful, 1, 'wh2_main_hef_resource_spices_2', itemType.building, 1, 'progressive hef_resource_spices', 'HighElf Building: Spice Trading Post'),
    30490: itemData(IC.useful, 1, 'wh2_main_hef_resource_spices_3', itemType.building, 2, 'progressive hef_resource_spices', 'HighElf Building: Eastern Bazaar'),
    30491: itemData(IC.useful, 1, 'wh2_main_hef_resource_wine_1', itemType.building, 0, 'progressive hef_resource_wine', 'HighElf Building: Orchards'),
    30492: itemData(IC.useful, 1, 'wh2_main_hef_resource_wine_2', itemType.building, 1, 'progressive hef_resource_wine', 'HighElf Building: Vineyard'),
    30493: itemData(IC.useful, 1, 'wh2_main_hef_resource_wine_3', itemType.building, 2, 'progressive hef_resource_wine', 'HighElf Building: Vintner'),
    30494: itemData(IC.useful, 1, 'wh2_main_hef_resource_wood_1', itemType.building, 0, 'progressive hef_resource_wood', "HighElf Building: Woodman's Hut"),
    30495: itemData(IC.useful, 1, 'wh2_main_hef_resource_wood_2', itemType.building, 1, 'progressive hef_resource_wood', 'HighElf Building: Timber Mill'),
    30496: itemData(IC.useful, 1, 'wh2_main_hef_resource_wood_3', itemType.building, 2, 'progressive hef_resource_wood', 'HighElf Building: Lumberyard'),
    30497: itemData(IC.useful, 1, 'wh2_main_hef_settlement_major_1', itemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Hamlet (Major)'),
    30498: itemData(IC.useful, 1, 'wh2_main_hef_settlement_major_2', itemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Haven (Major)'),
    30499: itemData(IC.useful, 1, 'wh2_main_hef_settlement_major_3', itemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Tower (Major)'),
    30500: itemData(IC.useful, 1, 'wh2_main_hef_settlement_major_4', itemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Citadel (Major)'),
    30501: itemData(IC.useful, 1, 'wh2_main_hef_settlement_major_5', itemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Tor (Major)'),
    30502: itemData(IC.useful, 1, 'wh2_main_hef_settlement_minor_1', itemType.building, 0, 'progressive hef_settlement_minor', 'HighElf Building: Hamlet (Minor)'),
    30503: itemData(IC.useful, 1, 'wh2_main_hef_settlement_minor_2', itemType.building, 1, 'progressive hef_settlement_minor', 'HighElf Building: Haven (Minor)'),
    30504: itemData(IC.useful, 1, 'wh2_main_hef_settlement_minor_3', itemType.building, 2, 'progressive hef_settlement_minor', 'HighElf Building: Tower (Minor)'),
    30568: itemData(IC.useful, 1, 'wh3_dlc27_hef_smith_0', itemType.building, 0, 'progressive hef_smith', 'HighElf Building: Elven Workshop'),
    30505: itemData(IC.useful, 1, 'wh2_main_hef_smith_1', itemType.building, 1, 'progressive hef_smith', 'HighElf Building: Elven Forge'),
    30506: itemData(IC.useful, 1, 'wh2_main_hef_smith_2', itemType.building, 2, 'progressive hef_smith', 'HighElf Building: Ithilmar Smith'),
    30507: itemData(IC.useful, 1, 'wh2_main_hef_stables_1', itemType.building, 0, 'progressive hef_stables', 'HighElf Building: Grazing Meadows'),
    30508: itemData(IC.useful, 1, 'wh2_main_hef_stables_2', itemType.building, 1, 'progressive hef_stables', 'HighElf Building: Farrier'),
    30509: itemData(IC.useful, 1, 'wh2_main_hef_worship_1', itemType.building, 0, 'progressive hef_worship', 'HighElf Building: Shrine of Asuryan'),
    30510: itemData(IC.useful, 1, 'wh2_main_hef_worship_2', itemType.building, 1, 'progressive hef_worship', 'HighElf Building: Temple of Asuryan'),
    30511: itemData(IC.useful, 1, 'wh2_main_hef_worship_3', itemType.building, 2, 'progressive hef_worship', 'HighElf Building: Sanctuary of Asuryan'),
    #30515: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_eagle_hef_1', ItemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Small Fortress Gate (Eagle)'),
    #30516: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_eagle_hef_2', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Fortress Gate (Eagle)'),
    #30517: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_eagle_hef_3', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Grand Fortress Gate (Eagle)'),
    #30518: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_eagle_hef_4', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Imposing Fortress Gate (Eagle)'),
    #30519: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_eagle_hef_5', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Impregnable Fortress Gate (Eagle)'),
    #30520: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_griffon_hef_1', ItemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Small Fortress Gate (Griffon)'),
    #30521: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_griffon_hef_2', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Fortress Gate'),
    #30522: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_griffon_hef_3', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Grand Fortress Gate'),
    #30523: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_griffon_hef_4', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Imposing Fortress Gate'),
    #30524: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_griffon_hef_5', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Impregnable Fortress Gate'),
    #30525: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_phoenix_hef_1', ItemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Small Fortress Gate'),
    #30526: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_phoenix_hef_2', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Fortress Gate'),
    #30527: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_phoenix_hef_3', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Grand Fortress Gate'),
    #30528: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_phoenix_hef_4', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Imposing Fortress Gate'),
    #30529: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_phoenix_hef_5', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Impregnable Fortress Gate'),
    #30530: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_unicorn_hef_1', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Small Fortress Gate'),
    #30531: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_unicorn_hef_2', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Fortress Gate'),
    #30532: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_unicorn_hef_3', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Grand Fortress Gate'),
    #30533: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_unicorn_hef_4', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Imposing Fortress Gate'),
    #30534: ItemData(IC.useful, 1, 'wh2_main_fortress_gate_unicorn_hef_5', ItemType.building, 5, 'progressive hef_settlement_major', 'HighElf Building: Impregnable Fortress Gate'),
    30542: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_major_hef_1', itemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Asur Sanctuary (Major)'),
    30543: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_major_hef_2', itemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Fledgling Colony (Major)'),
    30544: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_major_hef_3', itemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Asur Colony (Major)'),
    30545: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_major_hef_4', itemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Colony Citadel (Major)'),
    30546: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_major_hef_5', itemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Colony Tor (Major)'),
    30547: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_minor_hef_1', itemType.building, 0, 'progressive hef_settlement_minor', 'HighElf Building: Asur Sanctuary (Minor)'),
    30548: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_minor_hef_2', itemType.building, 1, 'progressive hef_settlement_minor', 'HighElf Building: Fledgling Colony (Minor)'),
    30549: itemData(IC.useful, 1, 'wh2_main_special_settlement_colony_minor_hef_3', itemType.building, 2, 'progressive hef_settlement_minor', 'HighElf Building: Asur Colony (Minor)'),
    #30550: ItemData(IC.useful, 1, 'wh2_main_special_settlement_naggarond_hef_1', ItemType.building, 0, 'progressive hef_settlement_major', 'HighElf Building: Occupied Naggarond (Elven Hamlet)'),
    #30551: ItemData(IC.useful, 1, 'wh2_main_special_settlement_naggarond_hef_2', ItemType.building, 1, 'progressive hef_settlement_major', 'HighElf Building: Occupied Naggarond (Elven Village)'),
    #30552: ItemData(IC.useful, 1, 'wh2_main_special_settlement_naggarond_hef_3', ItemType.building, 2, 'progressive hef_settlement_major', 'HighElf Building: Occupied Naggarond (Elven Town)'),
    #30553: ItemData(IC.useful, 1, 'wh2_main_special_settlement_naggarond_hef_4', ItemType.building, 3, 'progressive hef_settlement_major', 'HighElf Building: Occupied Naggarond (Elven City)'),
    #30554: ItemData(IC.useful, 1, 'wh2_main_special_settlement_naggarond_hef_5', ItemType.building, 4, 'progressive hef_settlement_major', 'HighElf Building: Occupied Naggarond (Spired Citadel)'),
    30562: itemData(IC.useful, 1, 'wh3_main_hef_allied_outpost_1', itemType.building, 0, 'progressive hef_allied_outpost', 'HighElf Building: High Elf Outpost'),
    30563: itemData(IC.useful, 1, 'wh3_main_hef_allied_outpost_2', itemType.building, 1, 'progressive hef_allied_outpost', 'HighElf Building: High Elf District'),
    30564: itemData(IC.useful, 1, 'wh3_main_hef_allied_outpost_3', itemType.building, 2, 'progressive hef_allied_outpost', 'HighElf Building: High Elf Colony'),
    30565: itemData(IC.useful, 1, 'wh3_main_hef_resource_ivory_1', itemType.building, 0, 'progressive hef_resource_ivory', 'HighElf Building: Animal Store'),
    30566: itemData(IC.useful, 1, 'wh3_main_hef_resource_ivory_2', itemType.building, 1, 'progressive hef_resource_ivory', 'HighElf Building: Tusk Market'),
    30567: itemData(IC.useful, 1, 'wh3_main_hef_resource_ivory_3', itemType.building, 2, 'progressive hef_resource_ivory', 'HighElf Building: Tusk Compound')
}

techs: dict[int, itemData] = {
    30816: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_00', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: The Endless Muster'),
    30800: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_01', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Spearwall'),
    30801: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_02', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Militia Training'),
    30802: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_01', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Precise Fletching'),
    30803: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_02', itemType.tech, 5, 'Progressive tech_hef_hosts', 'HighElf Tech: Martial Law'),
    30804: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_01', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Hierarchical Manoeuvre'),
    30805: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_02', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Disciplines of Hoeth'),
    30806: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_01', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Fire & Water'),
    30807: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_02', itemType.tech, 1, 'Progressive tech_hef_hosts', "HighElf Tech: Dragon's Bond"),
    30808: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_03', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Craft Logistics'),
    30809: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_04', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Appoint Sea Masters'),
    30810: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_03', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Light Ithilmar Armoury'),
    30811: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_04', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Recall Colonists'),
    30812: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_03', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Highborn Champions'),
    30813: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_04', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Chariot Anthems'),
    30814: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_03', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Obligations of Nobility'),
    30815: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_04', itemType.tech, 2, 'Progressive tech_hef_hosts', "HighElf Tech: Dragons' Offerings"),
    30817: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_05', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Light Cavalry Barding'),
    30818: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_06', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Horsemasters'),
    30819: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_00', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Forgemasters of Vaul'),
    30820: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_05', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Skirmishing Saddles'),
    30821: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_06', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Protection of Loec'),
    30822: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_00', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Seasoned Militia'),
    30823: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_05', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Foretelling'),
    30824: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_06', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Wardens of Ulthuan'),
    30825: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_00', itemType.tech, 5, 'Progressive tech_hef_hosts', 'HighElf Tech: Studies of the Vortex'),
    30826: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_05', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Wardings of Vaul'),
    30827: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_06', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Blessings of Asuryan'),
    30828: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_07', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Archery Prowess'),
    30829: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_08', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Cartridge Ammunition'),
    30830: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_07', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Allies of the Elements'),
    30831: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_08', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Vows of Fealty'),
    30832: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_07', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Arcane Studies'),
    30833: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_08', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Magical Infusion'),
    30834: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_07', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Elite Champions'),
    30835: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_08', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Ancient Lair Warding'),
    30836: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_09', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Trumpeters'),
    30837: itemData(IC.useful, 1, 'wh2_main_tech_hef_0_10', itemType.tech, 1, 'Progressive tech_hef_hosts', 'HighElf Tech: Swiftsense'),
    30838: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_09', itemType.tech, 2, 'Progressive tech_hef_hosts', "HighElf Tech: Hunter's Instincts"),
    30839: itemData(IC.useful, 1, 'wh2_main_tech_hef_1_10', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Ward of Kurnous'),
    30840: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_09', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Enchanted Projectiles'),
    30841: itemData(IC.useful, 1, 'wh2_main_tech_hef_2_10', itemType.tech, 4, 'Progressive tech_hef_hosts', 'HighElf Tech: Broadhead Arrows'),
    30842: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_09', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Strength of Avelorn'),
    30843: itemData(IC.useful, 1, 'wh2_main_tech_hef_3_10', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Teachings of Hoeth'),
    30866: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_0_01', itemType.tech, 2, 'Progressive tech_hef_hosts', 'HighElf Tech: Seaborn Creatures'),
    30867: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_0_02', itemType.tech, 3, 'Progressive tech_hef_hosts', 'HighElf Tech: Behemoths of the Seas'),
    30868: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_0_03', itemType.tech, 1, 'Progressive tech_hef_hosts', "HighElf Tech: The Creator's Gift"),
    30869: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_0_04', itemType.tech, 6, 'Progressive tech_hef_hosts', 'HighElf Tech: Starmetal Blades'),
    30870: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_0_05', itemType.tech, 6, 'Progressive tech_hef_hosts', 'HighElf Tech: The Path of Khaine'),

    30854: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_00', itemType.tech, 1, 'Progressive tech_hef_trade', 'HighElf Tech: Trade Advancements'),
    30844: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_01', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Call the Great Herds'),
    30845: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_02', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Awakening the Ancient Ones'),
    30846: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_03', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Great Weapons'),
    30847: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_04', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Gemsetting'),
    30848: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_05', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Marble Stockpiles'),
    30849: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_06', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Healing Salve'),
    30855: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_07', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Hardwood Construction'),
    30856: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_08', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Eastern Trade Contracts'),
    30857: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_09', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Preserved Seafood'),
    30858: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_10', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Monthly Festivals'),
    30859: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_11', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Extravagant Murals'),
    30860: itemData(IC.useful, 1, 'wh2_main_tech_hef_4_12', itemType.tech, 2, 'Progressive tech_hef_trade', 'HighElf Tech: Porcelain Kilns'),

    30861: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_00', itemType.tech, 1, 'Progressive tech_hef_culture', 'HighElf Tech: Cultural Advancements'),
    30862: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_06', itemType.tech, 2, 'Progressive tech_hef_culture', 'HighElf Tech: Heralds of Civilisation'),
    30863: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_05', itemType.tech, 3, 'Progressive tech_hef_culture', 'HighElf Tech: Unite Local Nobility'),
    30871: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_5_09', itemType.tech, 4, 'Progressive tech_hef_culture', "HighElf Tech: Echelon Manipulation"),
    30872: itemData(IC.useful, 1, 'wh3_dlc27_tech_hef_5_10', itemType.tech, 5, 'Progressive tech_hef_culture', 'HighElf Tech: Pillars of Accord'),
    30865: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_08', itemType.tech, 6, 'Progressive tech_hef_culture', 'HighElf Tech: Pinnacle of Civilisation'),
    30850: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_01', itemType.tech, 2, 'Progressive tech_hef_culture', 'HighElf Tech: Waystone Network'),
    30851: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_02', itemType.tech, 3, 'Progressive tech_hef_culture', 'HighElf Tech: Upholders of Order'),
    30852: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_03', itemType.tech, 5, 'Progressive tech_hef_culture', 'HighElf Tech: Court Advisors'),
    30864: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_07', itemType.tech, 6, 'Progressive tech_hef_culture', 'HighElf Tech: Rapid Resettlement'),
    30853: itemData(IC.useful, 1, 'wh2_main_tech_hef_5_04', itemType.tech, 7, 'Progressive tech_hef_culture', 'HighElf Tech: Spy Networks'),
}

progUnits: dict[int, itemData] = {
    31200: itemData(IC.useful, 4, "progressive hef_inf", itemType.unit, 4, None, "Progressive HighElf Unit: Infantry"),
    31201: itemData(IC.useful, 3, "progressive hef_rng", itemType.unit, 3, None, "Progressive HighElf Unit: Ranged"),
    31202: itemData(IC.useful, 3, "progressive hef_cav", itemType.unit, 3, None, "Progressive HighElf Unit: Cavalry"),
    31203: itemData(IC.useful, 1, "progressive hef_art", itemType.unit, 1, None, "Progressive HighElf Unit: Artillery"),
    31204: itemData(IC.useful, 3, "progressive hef_veh", itemType.unit, 3, None, "Progressive HighElf Unit: Chariot"),
    31205: itemData(IC.useful, 4, "progressive hef_bst", itemType.unit, 4, None, "Progressive HighElf Unit: Beast"),
    31206: itemData(IC.useful, 3, "progressive hef_hro", itemType.unit, 3, None, "Progressive HighElf Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    31301: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_hef', itemType.building, 3, None, 'Progressive HighElf Building: Foreign Slot Discovery'),
    31302: itemData(IC.useful, 3, 'progressive hef_barracks', itemType.building, 3, None, 'Progressive HighElf Building: Barracks'),
    31303: itemData(IC.useful, 2, 'progressive hef_court', itemType.building, 2, None, 'Progressive HighElf Building: Court'),
    31304: itemData(IC.useful, 3, 'progressive hef_defence_major', itemType.building, 3, None, 'Progressive HighElf Building: Defence Major'),
    31305: itemData(IC.useful, 2, 'progressive hef_defence_minor', itemType.building, 2, None, 'Progressive HighElf Building: Defence Minor'),
    31306: itemData(IC.useful, 2, 'progressive hef_dragons', itemType.building, 2, None, 'Progressive HighElf Building: Dragons'),
    31307: itemData(IC.useful, 1, 'progressive hef_embassy', itemType.building, 1, None, 'Progressive HighElf Building: Embassy'),
    31308: itemData(IC.useful, 3, 'progressive hef_farm', itemType.building, 3, None, 'Progressive HighElf Building: Farm'),
    31309: itemData(IC.useful, 3, 'progressive hef_hunters', itemType.building, 3, None, 'Progressive HighElf Building: Hunters'),
    31310: itemData(IC.useful, 3, 'progressive hef_industry', itemType.building, 3, None, 'Progressive HighElf Building: Industry'),
    31311: itemData(IC.useful, 3, 'progressive hef_mages', itemType.building, 3, None, 'Progressive HighElf Building: Mages'),
    31312: itemData(IC.useful, 5, 'progressive hef_order', itemType.building, 5, None, 'Progressive HighElf Building: Order'),
    31313: itemData(IC.useful, 3, 'progressive hef_port', itemType.building, 3, None, 'Progressive HighElf Building: Port'),
    31314: itemData(IC.useful, 3, 'progressive hef_resource_animals', itemType.building, 3, None, 'Progressive HighElf Building: Animals'),
    31315: itemData(IC.useful, 3, 'progressive hef_resource_dyes', itemType.building, 3, None, 'Progressive HighElf Building: Dyes'),
    31316: itemData(IC.useful, 3, 'progressive hef_resource_furs', itemType.building, 3, None, 'Progressive HighElf Building: Furs'),
    31317: itemData(IC.useful, 3, 'progressive hef_resource_gems', itemType.building, 3, None, 'Progressive HighElf Building: Gems'),
    31318: itemData(IC.useful, 3, 'progressive hef_resource_gold', itemType.building, 3, None, 'Progressive HighElf Building: Gold'),
    31319: itemData(IC.useful, 3, 'progressive hef_resource_iron', itemType.building, 3, None, 'Progressive HighElf Building: Iron'),
    31320: itemData(IC.useful, 3, 'progressive hef_resource_marble', itemType.building, 3, None, 'Progressive HighElf Building: Marble'),
    31321: itemData(IC.useful, 3, 'progressive hef_resource_medicine', itemType.building, 3, None, 'Progressive HighElf Building: Medicine'),
    31322: itemData(IC.useful, 3, 'progressive hef_resource_obsidian', itemType.building, 3, None, 'Progressive HighElf Building: Obsidian'),
    31323: itemData(IC.useful, 3, 'progressive hef_resource_pasture', itemType.building, 3, None, 'Progressive HighElf Building: Pasture'),
    31324: itemData(IC.useful, 3, 'progressive hef_resource_pottery', itemType.building, 3, None, 'Progressive HighElf Building: Pottery'),
    31325: itemData(IC.useful, 3, 'progressive hef_resource_salt', itemType.building, 3, None, 'Progressive HighElf Building: Salt'),
    31326: itemData(IC.useful, 3, 'progressive hef_resource_spices', itemType.building, 3, None, 'Progressive HighElf Building: Spices'),
    31327: itemData(IC.useful, 3, 'progressive hef_resource_wine', itemType.building, 3, None, 'Progressive HighElf Building: Wine'),
    31328: itemData(IC.useful, 3, 'progressive hef_resource_wood', itemType.building, 3, None, 'Progressive HighElf Building: Wood'),
    31329: itemData(IC.useful, 5, 'progressive hef_settlement_major', itemType.building, 5, None, 'Progressive HighElf Building: Settlement Major'),
    31330: itemData(IC.useful, 3, 'progressive hef_settlement_minor', itemType.building, 3, None, 'Progressive HighElf Building: Settlement Minor'),
    31331: itemData(IC.useful, 3, 'progressive hef_smith', itemType.building, 3, None, 'Progressive HighElf Building: Smith'),
    31332: itemData(IC.useful, 2, 'progressive hef_stables', itemType.building, 2, None, 'Progressive HighElf Building: Stables'),
    31333: itemData(IC.useful, 3, 'progressive hef_worship', itemType.building, 3, None, 'Progressive HighElf Building: Worship'),
    31334: itemData(IC.useful, 3, 'progressive hef_allied_outpost', itemType.building, 3, None, 'Progressive HighElf Building: Allied Outpost'),
    31335: itemData(IC.useful, 3, 'progressive hef_resource_ivory', itemType.building, 3, None, 'Progressive HighElf Building: Ivory')
}

progTechs: dict[int, itemData] = {
    31400: itemData(IC.useful, 6, "Progressive tech_hef_hosts", itemType.tech, 6, None, "Progressive HighElf Tech: The Hosts"),
    31401: itemData(IC.useful, 2, "Progressive tech_hef_trade", itemType.tech, 2, None, "Progressive HighElf Tech: Trade"),
    31402: itemData(IC.useful, 7, "Progressive tech_hef_culture", itemType.tech, 7, None, "Progressive HighElf Tech: Culture"),
}

special: dict[int, specialItemData] = {
    31500: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], 'wh2_dlc15_hef_inf_mistwalkers_spireguard_0', itemType.unit, 2, 'progressive hef_rng', False, False, 'HighElf Unit: Spire Guard of Tor Yvresse'),
    31501: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], 'wh2_dlc15_hef_inf_mistwalkers_skyhawks_0', itemType.unit, 3, 'progressive hef_inf', False, False, 'HighElf Unit: The Skyhawks'),
    31502: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], 'wh2_dlc15_hef_inf_mistwalkers_sentinels_0', itemType.unit, 2, 'progressive hef_rng', False, False, 'HighElf Unit: Sentinels of Astaril'),
    31503: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], 'wh2_dlc15_hef_inf_mistwalkers_griffon_knights_0', itemType.unit, 3, 'progressive hef_bst', False, False, 'HighElf Unit: Knights of Tor Gaval'),
    31504: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], 'wh2_dlc15_hef_inf_mistwalkers_faithbearers_0', itemType.unit, 3, 'progressive hef_inf', False, False, 'HighElf Unit: Athel Tamarha Faithbearers'),
    31505: specialItemData(IC.useful, 1, ["wh2_main_hef_nagarythe"], "wh2_dlc10_hef_inf_shadow_walkers_0", itemType.unit, 3, 'progressive hef_rng', False, False, 'HighElf Unit: Shadow-walkers'),
    31506: specialItemData(IC.useful, 1, ["wh2_main_hef_avelorn"], "wh2_dlc10_hef_inf_dryads_0", itemType.unit, 1, 'progressive hef_inf', False, False, 'HighElf Unit: Dryads'),
    31507: specialItemData(IC.useful, 1, ["wh2_main_hef_avelorn"], "wh2_dlc10_hef_mon_treeman_0", itemType.unit, 4, 'progressive hef_bst', False, False, 'HighElf Unit: Treeman'),
    31508: specialItemData(IC.useful, 1, ["wh2_main_hef_avelorn"], "wh2_dlc10_hef_mon_treekin_0", itemType.unit, 2, 'progressive hef_bst', False, False, 'HighElf Unit: Tree Kin'),

    31509: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_hef_field_hq_1", itemType.building, 0, 'progressive hef_mistwalker', False, False, "HighElf Building: Mistwalkers' Sanctum"),
    31510: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_hef_field_hq_2", itemType.building, 1, 'progressive hef_mistwalker', False, False, "HighElf Building: Mistwalkers' Keep"),
    31511: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_hef_field_hq_3", itemType.building, 2, 'progressive hef_mistwalker', False, False, "HighElf Building: Mistwalkers' Citadel"),
    31512: specialItemData(IC.useful, 3, ["wh2_main_hef_yvresse"], "progressive hef_mistwalker", itemType.building, 3, None, False, True, "Progressive HighElf Building: Mistwalkers"),
    31513: specialItemData(IC.useful, 1, ["wh2_main_hef_nagarythe"], "wh2_dlc10_hef_aesanar_camp", itemType.building, 1, "progressive aesanar_camp", False, False, "HighElf Building: Aesanar Camp"),
    31514: specialItemData(IC.useful, 1, ["wh2_main_hef_nagarythe"], "progressive aesanar_camp", itemType.building, 1, None, False, True, "Progressive HighElf Building: Aesanar Camp"),
}

rituals: dict[int, specialItemData] = {
    31600: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine", "wh2_main_hef_yvresse"], "wh2_main_ritual_hef_hoeth", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Hoeth"),
    31601: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine", "wh2_main_hef_order_of_loremasters", "wh2_main_hef_nagarythe", "wh2_dlc15_hef_imrik", "wh3_dlc27_hef_aislinn"], "wh2_main_ritual_hef_isha", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Isha"),
    31602: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine", "wh2_main_hef_order_of_loremasters", "wh2_main_hef_avelorn", "wh2_main_hef_nagarythe", "wh2_main_hef_yvresse", "wh2_dlc15_hef_imrik", "wh3_dlc27_hef_aislinn"], "wh2_main_ritual_hef_asuryan", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Asuryan"),
    31603: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine", "wh2_main_hef_order_of_loremasters", "wh2_main_hef_avelorn", "wh2_main_hef_nagarythe", "wh2_main_hef_yvresse", "wh2_dlc15_hef_imrik", "wh3_dlc27_hef_aislinn"], "wh2_main_ritual_hef_vaul", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Vaul"),

    31604: specialItemData(IC.useful, 1, ["wh2_main_hef_avelorn"], "wh2_dlc10_ritual_hef_lileath", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Lileath"),
    31605: specialItemData(IC.useful, 1, ["wh2_main_hef_avelorn"], "wh2_dlc15_ritual_hef_isha_greater", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Greater Invocation of Isha"),
    31606: specialItemData(IC.useful, 1, ["wh2_main_hef_nagarythe"], "wh2_dlc10_ritual_hef_morai_heg", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Morai-Heg"),
    31607: specialItemData(IC.useful, 1, ["wh2_dlc15_hef_imrik"], "wh2_dlc15_ritual_hef_vaul_greater", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Greater Invocation of Vaul"),
    31608: specialItemData(IC.useful, 1, ["wh2_dlc15_hef_imrik"], "wh2_dlc15_ritual_hef_eldrazor", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Eldrazor"),
    31609: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_ritual_hef_ladrielle", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Eldrazor"),
    31610: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_ritual_hef_hoeth_greater", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Greater Invocation of Hoeth"),
    31702: specialItemData(IC.useful, 1, ["wh3_dlc27_hef_aislinn"], "wh3_dlc27_ritual_hef_mathlann", itemType.ritual, 1, "progressive hef_ritual_rite", True, False, "HighElf Rite: Invocation of Mathlann"),

    31611: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_rank_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_being", False, False, "HighElf White Tower: Disciples of Being (1)"),
    31612: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_rank_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_being", True, False, "HighElf White Tower: Disciples of Being (2)"),
    31613: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_rank_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_being", True, False, "HighElf White Tower: Disciples of Being (3)"),
    31614: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_wom_cost_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_being_wom", False, False, "HighElf White Tower: High Teachings of Being (1)"),
    31615: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_wom_cost_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_being_wom", True, False, "HighElf White Tower: High Teachings of Being (2)"),
    31616: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_wom_cost_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_being_wom", True, False, "HighElf White Tower: High Teachings of Being (3)"),

    31617: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_rank_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_brilliance", False, False, "HighElf White Tower: Disciples of Brilliance (1)"),
    31618: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_rank_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_brilliance", True, False, "HighElf White Tower: Disciples of Brilliance (2)"),
    31619: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_rank_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_brilliance", True, False, "HighElf White Tower: Disciples of Brilliance (3)"),
    31620: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_wom_cost_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_brilliance_wom", False, False, "HighElf White Tower: High Teachings of Brilliance (1)"),
    31621: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_wom_cost_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_brilliance_wom", True, False, "HighElf White Tower: High Teachings of Brilliance (2)"),
    31622: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_wom_cost_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_brilliance_wom", True, False, "HighElf White Tower: High Teachings of Brilliance (3)"),

    31623: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_rank_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_darkness", False, False, "HighElf White Tower: Disciples of Darkness (1)"),
    31624: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_rank_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_darkness", True, False, "HighElf White Tower: Disciples of Darkness (2)"),
    31625: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_rank_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_darkness", True, False, "HighElf White Tower: Disciples of Darkness (3)"),
    31626: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_wom_cost_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_darkness_wom", False, False, "HighElf White Tower: High Teachings of Darkness (1)"),
    31627: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_wom_cost_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_darkness_wom", True, False, "HighElf White Tower: High Teachings of Darkness (2)"),
    31628: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_wom_cost_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_darkness_wom", True, False, "HighElf White Tower: High Teachings of Darkness (3)"),

    31629: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_rank_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_high_loremaster", False, False, "HighElf White Tower: Disciples of the High Loremaster  (1)"),
    31630: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_rank_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_high_loremaster", True, False, "HighElf White Tower: Disciples of the High Loremaster  (2)"),
    31631: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_rank_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_high_loremaster", True, False, "HighElf White Tower: Disciples of the High Loremaster  (3)"),
    31632: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_wom_cost_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_high_loremaster_wom", False, False, "HighElf White Tower: High Teachings of Hoeth (1)"),
    31633: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_wom_cost_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_high_loremaster_wom", True, False, "HighElf White Tower: High Teachings of Hoeth (2)"),
    31634: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_wom_cost_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_high_loremaster_wom", True, False, "HighElf White Tower: High Teachings of Hoeth (3)"),

    31635: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_rank_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_oblivion", False, False, "HighElf White Tower: Disciples of Oblivion (1)"),
    31636: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_rank_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_oblivion", True, False, "HighElf White Tower: Disciples of Oblivion (2)"),
    31637: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_rank_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_oblivion", True, False, "HighElf White Tower: Disciples of Oblivion (3)"),
    31638: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_wom_cost_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_oblivion_wom", False, False, "HighElf White Tower: High Teachings of Oblivion (1)"),
    31639: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_wom_cost_2", itemType.ritual, 2, "progressive hef_ritual_white_tower_oblivion_wom", True, False, "HighElf White Tower: High Teachings of Oblivion (2)"),
    31640: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_wom_cost_3", itemType.ritual, 3, "progressive hef_ritual_white_tower_oblivion_wom", True, False, "HighElf White Tower: High Teachings of Oblivion (3)"),

    31641: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_summon_life", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Life"),
    31642: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_summon_beasts", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Beasts"),
    31643: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_summon_heavens", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Heavens"),
    31644: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_summon_light", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Light"),
    31645: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_summon_death", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Death"),
    31646: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_summon_shadows", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Shadows"),
    31647: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_summon_high", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of High Magic"),
    31648: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_mastery_of_elemental_winds", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Conclave of Mages"),
    31649: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_summon_fire", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Fire"),
    31650: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_summon_metal", itemType.ritual, 1, "progressive hef_ritual_white_tower_summon", False, False, "HighElf White Tower: Exemplar of Metal"),

    31651: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_ritual_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Invocation of Resilience"),
    31652: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_ritual_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Discipline of the Wild Kin"),
    31653: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_ritual_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Arcane Prism of Focus"),
    31654: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_ritual_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Surging of the Winds"),
    31655: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_ritual_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Art of the Soul Snare"),
    31656: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_ritual_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Mysteries of the Silent Form"),
    31657: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_ritual_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Arcane Attrition"),
    31658: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_ritual_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_ritual", False, False, "HighElf White Tower: Theory of Ember Binding"),

    31660: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_cata_spell_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Storm of Renewal"),
    31661: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_being_cata_spell_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Merciw's Monstrous Regiment"),
    31662: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_cata_spell_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Time Amok"),
    31663: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_brilliance_cata_spell_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Thorsen's Thunderstorm"),
    31664: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_cata_spells_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Loremaster of Brilliance"),
    31665: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_cata_spells_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Loremaster of Being"),
    31666: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_cata_spells_3", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Loremaster of Oblivion"),
    31667: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_high_loremaster_cata_spells_4", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Loremaster of Darkness"),
    31668: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_cata_spell_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Ashes & Dust"),
    31669: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_darkness_cata_spell_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Dance of Despair"),
    31670: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_cata_spell_1", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Magma Storm"),
    31671: specialItemData(IC.useful, 1, ["wh2_main_hef_order_of_loremasters"], "wh3_dlc27_secrets_of_the_white_tower_oblivion_cata_spell_2", itemType.ritual, 1, "progressive hef_ritual_white_tower_cata_spell", False, False, "HighElf White Tower: Gehenna's Golden Globe"),

    31672: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_influence_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_influence", True, False, "HighElf Athel Tamarha: Shrine to Loec"),
    31673: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_influence_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_influence", True, False, "HighElf Athel Tamarha: Altar to Loec"),
    31674: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_interrogation_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_interrogation", True, False, "HighElf Athel Tamarha: Interrogation Chamber"),
    31675: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_interrogation_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_interrogation", True, False, "HighElf Athel Tamarha: Enhanced Interrogation Chamber"),
    31676: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_melee_mistwalkers_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_melee", True, False, "HighElf Athel Tamarha: Training Grounds"),
    31677: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_melee_mistwalkers_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_melee", True, False, "HighElf Athel Tamarha: Combat School"),
    31678: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mist_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_mist", True, False, "HighElf Athel Tamarha: Waystone"),
    31679: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mist_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_mist", True, False, "HighElf Athel Tamarha: Waystone Network"),
    31680: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mistwalkers_recruitment_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_recruitment", True, False, "HighElf Athel Tamarha: Mistwalker Command Post"),
    31681: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mistwalkers_recruitment_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_recruitment", True, False, "HighElf Athel Tamarha: Mistwalker High Command"),
    31682: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mistwalkers_upgrades_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_upgrades", True, False, "HighElf Athel Tamarha: Halls of Eldrazor"),
    31683: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_mistwalkers_upgrades_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_upgrades", True, False, "HighElf Athel Tamarha: Ornate Halls of Eldrazor"),
    31684: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_ranged_mistwalkers_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_ranged", True, False, "HighElf Athel Tamarha: Archery Range"),
    31685: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_ranged_mistwalkers_3", itemType.ritual, 2, "progressive hef_ritual_athel_tamarha_ranged", True, False, "HighElf Athel Tamarha: Archery Complex"),
    31686: specialItemData(IC.useful, 1, ["wh2_main_hef_yvresse"], "wh2_dlc15_athel_tamarha_prison_2", itemType.ritual, 1, "progressive hef_ritual_athel_tamarha_prison", True, False, "HighElf Athel Tamarha: Extra Prison Cell"),

    31687: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_1", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: White Tower Support"),
    31688: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_2", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: Shadow Walker Ambush"),
    31689: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_3", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: Mistwalker Reinforcements"),
    31690: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_4", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: Dragonscorch"),
    31691: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_5", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: Expeditionary Force"),
    31692: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_alliance_6", itemType.ritual, 1, "progressive hef_ritual_champion_alliance", False, False, "HighElf Chamion of Ulthuan: Blessing of the Everqueen"),
    31693: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_1", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Supply Host"),
    31694: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_2", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Garrison Aid"),
    31695: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_3", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Elven Militia"),
    31696: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_4", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Defender's Authority"),
    31697: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_5", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Warrior Council"),
    31698: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_6", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Military Relief"),
    31699: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_7", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Lead by Experience"),
    31700: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_8", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Champion's Demand"),
    31701: specialItemData(IC.useful, 1, ["wh2_main_hef_eataine"], "wh3_dlc27_hef_tyrion_imperatives_general_9", itemType.ritual, 1, "progressive hef_ritual_champion_heir", False, False, "HighElf Chamion of Ulthuan: Elven Initiative"),
}

#"wh2_main_hef_chrace", "wh2_main_hef_saphery", "wh2_main_hef_citadel_of_dusk"