from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData

# @formatter:off
units: dict[int, itemData] = {
    38000: itemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_0', itemType.unit, 1, 'Progressive nor_inf', 'Norsca Unit: Marauders'),
    38001: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_spearman_0', itemType.unit, 1, 'Progressive nor_inf', 'Norsca Unit: Marauder Spearmen'),
    38002: itemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_1', itemType.unit, 1, 'Progressive nor_inf', 'Norsca Unit: Marauders (Great Weapons)'),
    38003: itemData(IC.useful, 1, 'wh3_dlc27_nor_inf_marauder_bearmen', itemType.unit, 2, 'Progressive nor_inf', 'Norsca Unit: Marauder Bearmen'),
    38004: itemData(IC.useful, 1, 'wh3_dlc27_nor_inf_marauder_bearmen_greatweapons', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Marauder Bearmen (Great Weapons)'),
    38005: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_berserkers_0', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Marauder Berserkers'),
    38006: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_0', itemType.unit, 4, 'Progressive nor_inf', 'Norsca Unit: Marauder Champions'),
    38007: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_1', itemType.unit, 4, 'Progressive nor_inf', 'Norsca Unit: Marauder Champions (Great Weapons)'),
    38008: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_0', itemType.unit, 2, 'Progressive nor_inf', 'Norsca Unit: Skin Wolves'),
    38009: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_1', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Skin Wolves (Armoured)'),
    38010: itemData(IC.useful, 1, 'wh_main_nor_mon_chaos_trolls', itemType.unit, 2, 'Progressive nor_inf', 'Norsca Unit: Norscan Trolls'),
    38011: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_ice_trolls_0', itemType.unit, 2, 'Progressive nor_inf', 'Norsca Unit: Norscan Ice Trolls'),
    38012: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_0', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Fimir Warriors'),
    38013: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_1', itemType.unit, 4, 'Progressive nor_inf', 'Norsca Unit: Fimir Warriors (Great Weapons)'),
    38014: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_0', itemType.unit, 1, 'Progressive nor_rng', 'Norsca Unit: Marauder Hunters'),
    38015: itemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_1', itemType.unit, 1, 'Progressive nor_rng', 'Norsca Unit: Marauder Hunters (Javelins)'),
    38016: itemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_0', itemType.unit, 1, 'Progressive nor_cav', 'Norsca Unit: Marauder Horsemen'),
    38017: itemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_1', itemType.unit, 2, 'Progressive nor_cav', 'Norsca Unit: Marauder Horsemen (Throwing Axes)'),
    38018: itemData(IC.useful, 1, 'wh_dlc08_nor_cav_marauder_horsemasters_0', itemType.unit, 3, 'Progressive nor_cav', 'Norsca Unit: Marauder Horsemasters'),
    38019: itemData(IC.useful, 1, 'wh3_dlc27_nor_cav_kurgan_horsemen_dualweapons', itemType.unit, 3, 'Progressive nor_cav', 'Norsca Unit: Kurgan Horsemen (Dual Weapons)'),
    38020: itemData(IC.useful, 1, 'wh3_dlc27_nor_cav_kurgan_horsemen_greatweapons', itemType.unit, 3, 'Progressive nor_cav', 'Norsca Unit: Kurgan Horsemen (Great Weapons)'),
    38021: itemData(IC.useful, 1, 'wh_main_nor_cav_chaos_chariot', itemType.unit, 1, 'Progressive nor_veh', 'Norsca Unit: Marauder Chariots'),
    38022: itemData(IC.useful, 1, 'wh_dlc08_nor_cav_marauder_warwolves_chariot_0', itemType.unit, 2, 'Progressive nor_veh', 'Norsca Unit: Marauder Ice Wolf Chariots'),
    38023: itemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_0', itemType.unit, 1, 'Progressive nor_bst', 'Norsca Unit: Norscan Warhounds'),
    38024: itemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_1', itemType.unit, 1, 'Progressive nor_bst', 'Norsca Unit: Norscan Warhounds (Poison)'),
    38025: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_marauder_warwolves_0', itemType.unit, 2, 'Progressive nor_bst', 'Norsca Unit: Norscan Ice Wolves'),
    38026: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_giant_0', itemType.unit, 3, 'Progressive nor_bst', 'Norsca Unit: Norscan Giant'),
    38027: itemData(IC.useful, 1, 'wh3_dlc27_nor_mon_cursd_ettin', itemType.unit, 4, 'Progressive nor_bst', "Norsca Unit: Curs'd Ettin"),
    38028: itemData(IC.useful, 1, 'wh3_dlc27_nor_mon_cursd_ettin_runecaller', itemType.unit, 4, 'Progressive nor_bst', "Norsca Unit: Curs'd Ettin (Runecaller)"),
    38029: itemData(IC.useful, 1, 'wh_dlc08_nor_feral_manticore', itemType.unit, 3, 'Progressive nor_bst', 'Norsca Unit: Feral Manticore'),
    38030: itemData(IC.useful, 1, 'wh3_dlc27_nor_mon_dread_maw', itemType.unit, 3, 'Progressive nor_bst', 'Norsca Unit: Dread Maw'),
    38031: itemData(IC.useful, 1, 'wh3_dlc27_nor_mon_chimera', itemType.unit, 4, 'Progressive nor_bst', 'Norsca Unit: Chimera'),
    38032: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_0', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Chaos Frost Dragon'),
    38033: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_0', itemType.unit, 4, 'Progressive nor_bst', 'Norsca Unit: Feral Mammoth'),
    38034: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_1', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: War Mammoth'),
    38035: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_2', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: War Mammoth (Warshrine)'),
    38036: itemData(IC.useful, 1, 'wh3_dlc27_nor_cha_fimir_noble', itemType.unit, 1, 'Progressive nor_hro', 'Norsca Unit: Fimir Noble'),
    38037: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_skin_wolf_werekin_0', itemType.unit, 2, 'Progressive nor_hro', 'Norsca Unit: Skin Wolf Werekin'),
    38038: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_metal_0', itemType.unit, 2, 'Progressive nor_hro', 'Norsca Unit: Shaman-Sorcerer (Metal)'),
    38039: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_fire_0', itemType.unit, 2, 'Progressive nor_hro', 'Norsca Unit: Shaman-Sorcerer (Fire)'),
    38040: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_death_0', itemType.unit, 2, 'Progressive nor_hro', 'Norsca Unit: Shaman-Sorcerer (Death)'),
    38041: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_shadow_0', itemType.unit, 3, 'Progressive nor_hro', 'Norsca Unit: Fimir Balefiend (Shadows)'),
    38042: itemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_fire_0', itemType.unit, 3, 'Progressive nor_hro', 'Norsca Unit: Fimir Balefiend (Fire)'),
    38043: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_ror_1', itemType.unit, 4, 'Progressive nor_bst', 'Norsca Unit: The Great Mawherd of Bloodfjord (Feral Mammoths)'),
    38044: itemData(IC.useful, 1, 'wh3_dlc27_nor_mon_chimera_ror', itemType.unit, 4, 'Progressive nor_bst', 'Norsca Unit: Bloodshriek Chimera (Chimera)'),
    38045: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_ror_0', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: The Cold-Voider (Chaos Frost Dragon)'),
    38046: itemData(IC.useful, 1, 'wh3_dlc27_nor_inf_chaos_marauders_great_weapons_ror', itemType.unit, 1, 'Progressive nor_inf', 'Norsca Unit: Worshippers of the Crow (Marauders - Great Weapons)'),
    38047: itemData(IC.useful, 1, 'wh_pro04_nor_inf_chaos_marauders_ror_0', itemType.unit, 1, 'Progressive nor_inf', 'Norsca Unit: Icehorn Marauders (Marauders)'),
    38048: itemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_ror_0', itemType.unit, 1, 'Progressive nor_cav', 'Norsca Unit: Riders of the Mighty Serpent (Marauder Horsemen)'),
    38049: itemData(IC.useful, 1, 'wh3_dlc27_nor_cav_marauder_horsemen_ror', itemType.unit, 1, 'Progressive nor_bst', 'Norsca Unit: Beasts of Tashnar (Norscan Warhounds)'),
    38050: itemData(IC.useful, 1, 'wh3_dlc27_nor_cav_chaos_chariot_ror', itemType.unit, 1, 'Progressive nor_veh', 'Norsca Unit: Followers of the Great Eagle (Marauder Chariots)'),
    38051: itemData(IC.useful, 1, 'wh_pro04_nor_inf_marauder_berserkers_ror_0', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Brutes of the Hound (Marauder Berserkers)'),
    38052: itemData(IC.useful, 1, 'wh_pro04_nor_mon_skinwolves_ror_0', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Maws of Savagery (Skin Wolves - Armoured)'),
    38053: itemData(IC.useful, 1, 'wh_pro04_nor_mon_fimir_ror_0', itemType.unit, 3, 'Progressive nor_inf', 'Norsca Unit: Mist Stalkers (Fimir Warriors)'),
    38054: itemData(IC.useful, 1, 'wh_pro04_nor_mon_war_mammoth_ror_0', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Soulcrusher (War Mammoth)'),
    38055: itemData(IC.useful, 1, 'wh_dlc08_nor_art_hellcannon_battery', itemType.unit, 1, 'Progressive nor_art', 'Norsca Unit: The Ice-Forged Legion (Hellcannons)'),
    38056: itemData(IC.useful, 1, 'wh_dlc03_bst_inf_cygor_0', itemType.unit, 1, 'Progressive nor_art', 'Norsca Unit: Cygor'),
    38057: itemData(IC.useful, 1, 'wh3_dlc24_tze_mon_cockatrice', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Cockatrice'),
    38058: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_0', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: JabberSlythe'),
    38059: itemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Preyton'),
    38060: itemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_0', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Ghorgon'),
    38061: itemData(IC.useful, 1, 'wh3_dlc25_nur_mon_toad_dragon', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Toad Dragon'),
    38062: itemData(IC.useful, 1, 'wh_dlc01_chs_mon_dragon_ogre_shaggoth', itemType.unit, 5, 'Progressive nor_bst', 'Norsca Unit: Dragon Ogre Shaggoth'),
}

buildings: dict[int, itemData] = {
    38400: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_1', itemType.building, 0, 'Progressive foreign_slot_discovery_nor', 'Norsca Building: Marauder Patrols'),
    38401: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_2', itemType.building, 1, 'Progressive foreign_slot_discovery_nor', 'Norsca Building: Marauder Trackers'),
    38402: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_3', itemType.building, 2, 'Progressive foreign_slot_discovery_nor', 'Norsca Building: Marauder Outposts'),
    38403: itemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_1', itemType.building, 0, 'Progressive nor_allied_outpost', 'Norsca Building: Norscan Outpost'),
    38404: itemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_2', itemType.building, 1, 'Progressive nor_allied_outpost', 'Norsca Building: Norscan District'),
    38405: itemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_3', itemType.building, 2, 'Progressive nor_allied_outpost', 'Norsca Building: Norscan Colony'),
    38406: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_1', itemType.building, 0, 'Progressive nor_settlement_major', 'Norsca Building: Warrior Gathering'),
    38407: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_2', itemType.building, 1, 'Progressive nor_settlement_major', 'Norsca Building: Warband Camp'),
    38408: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_3', itemType.building, 2, 'Progressive nor_settlement_major', 'Norsca Building: Clan Enclave'),
    38409: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_4', itemType.building, 3, 'Progressive nor_settlement_major', 'Norsca Building: Tribal Stronghold'),
    38410: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_5', itemType.building, 4, 'Progressive nor_settlement_major', 'Norsca Building: Greater Tribal Stronghold'),
    38411: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_1', itemType.building, 0, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Encampment'),
    38412: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_2', itemType.building, 1, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Moot'),
    38413: itemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_3', itemType.building, 2, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Village'),
    38414: itemData(IC.useful, 1, 'wh_dlc08_nor_resource_iron_1', itemType.building, 0, 'Progressive nor_resource_iron', 'Norsca Building: Iron Mine'),
    38415: itemData(IC.useful, 1, 'wh_dlc08_nor_resource_marble_1', itemType.building, 0, 'Progressive nor_resource_marble', 'Norsca Building: Marble Quarry'),
    38416: itemData(IC.useful, 1, 'wh_dlc08_nor_resource_obsidian_1', itemType.building, 0, 'Progressive nor_resource_obsidian', 'Norsca Building: Obsidian Quarry'),
    38417: itemData(IC.useful, 1, 'wh_main_nor_beasts_1', itemType.building, 0, 'Progressive nor_beasts', 'Norsca Building: Warhound Kennels'),
    38418: itemData(IC.useful, 1, 'wh_main_nor_beasts_2', itemType.building, 1, 'Progressive nor_beasts', 'Norsca Building: Warwolf Dens'),
    38419: itemData(IC.useful, 1, 'wh_main_nor_beasts_3', itemType.building, 2, 'Progressive nor_beasts', 'Norsca Building: Cave of Dark Offerings'),
    38420: itemData(IC.useful, 1, 'wh_main_nor_chaos_1', itemType.building, 0, 'Progressive nor_chaos', 'Norsca Building: Chaos Totem'),
    38421: itemData(IC.useful, 1, 'wh_main_nor_chaos_2', itemType.building, 1, 'Progressive nor_chaos', 'Norsca Building: Altar of the Bloodfathers'),
    38422: itemData(IC.useful, 1, 'wh_main_nor_chaos_2b', itemType.building, 1, 'Progressive nor_chaos', 'Norsca Building: Shamanic Tribute'),
    38423: itemData(IC.useful, 1, 'wh_main_nor_chaos_3', itemType.building, 2, 'Progressive nor_chaos', 'Norsca Building: Shamanic Pyre'),
    38424: itemData(IC.useful, 1, 'wh_main_nor_creatures_0', itemType.building, 0, 'Progressive nor_creatures', 'Norsca Building: Fog-Shrouded Fens'),
    38425: itemData(IC.useful, 1, 'wh_main_nor_creatures_1', itemType.building, 1, 'Progressive nor_creatures', 'Norsca Building: Wyrmchasm'),
    38426: itemData(IC.useful, 1, 'wh_main_nor_creatures_2', itemType.building, 2, 'Progressive nor_creatures', 'Norsca Building: Storm-Beaten Cliffs'),
    38427: itemData(IC.useful, 1, 'wh_main_nor_creatures_2b', itemType.building, 2, 'Progressive nor_creatures', 'Norsca Building: Henge of Totems'),
    38428: itemData(IC.useful, 1, 'wh_main_nor_creatures_3', itemType.building, 3, 'Progressive nor_creatures', 'Norsca Building: Glacial Passages'),
    38429: itemData(IC.useful, 1, 'wh_main_nor_garrison_1', itemType.building, 0, 'Progressive nor_garrison', 'Norsca Building: Guard Shack'),
    38430: itemData(IC.useful, 1, 'wh_main_nor_garrison_2', itemType.building, 1, 'Progressive nor_garrison', 'Norsca Building: Watchtower'),
    38431: itemData(IC.useful, 1, 'wh_main_nor_garrison_3', itemType.building, 2, 'Progressive nor_garrison', 'Norsca Building: Marauding Militia'),
    38432: itemData(IC.useful, 1, 'wh_main_nor_garrison_3b', itemType.building, 2, 'Progressive nor_garrison', 'Norsca Building: Feral Wardens'),
    38433: itemData(IC.useful, 1, 'wh_main_nor_loot_1', itemType.building, 0, 'Progressive nor_loot', 'Norsca Building: Loot Pile'),
    38434: itemData(IC.useful, 1, 'wh_main_nor_loot_2', itemType.building, 1, 'Progressive nor_loot', 'Norsca Building: Trophies of Battle'),
    38435: itemData(IC.useful, 1, 'wh_main_nor_loot_2b', itemType.building, 1, 'Progressive nor_loot', 'Norsca Building: Hoard Pit'),
    38436: itemData(IC.useful, 1, 'wh_main_nor_loot_3', itemType.building, 2, 'Progressive nor_loot', 'Norsca Building: Plunder Hall'),
    38437: itemData(IC.useful, 1, 'wh_main_nor_loot_3b', itemType.building, 2, 'Progressive nor_loot', 'Norsca Building: Barrow Hoard'),
    38438: itemData(IC.useful, 1, 'wh_main_nor_military_1', itemType.building, 0, 'Progressive nor_military', 'Norsca Building: Proving Pits'),
    38439: itemData(IC.useful, 1, 'wh_main_nor_military_2', itemType.building, 1, 'Progressive nor_military', 'Norsca Building: Raiding Camps'),
    38440: itemData(IC.useful, 1, 'wh_main_nor_military_3', itemType.building, 2, 'Progressive nor_military', "Norsca Building: Warriors' Hall"),
    38441: itemData(IC.useful, 1, 'wh3_dlc27_nor_military_3b', itemType.building, 2, 'Progressive nor_military', "Norsca Building: Raiders' Bazaar"),
    38442: itemData(IC.useful, 1, 'wh3_dlc27_nor_military_4', itemType.building, 3, 'Progressive nor_military', "Norsca Building: Chieftain's Hall"),
    38443: itemData(IC.useful, 1, 'wh_main_nor_offerings_1', itemType.building, 0, 'Progressive nor_offerings', 'Norsca Building: Ice Troll Lair'),
    38444: itemData(IC.useful, 1, 'wh_main_nor_offerings_2', itemType.building, 1, 'Progressive nor_offerings', 'Norsca Building: Frozen Cairn Field'),
    38445: itemData(IC.useful, 1, 'wh_main_nor_port_1', itemType.building, 0, 'Progressive nor_port', 'Norsca Building: Norsca Wharf'),
    38446: itemData(IC.useful, 1, 'wh_main_nor_port_2', itemType.building, 1, 'Progressive nor_port', 'Norsca Building: Longship Builder'),
    38447: itemData(IC.useful, 1, 'wh_main_nor_port_3', itemType.building, 2, 'Progressive nor_port', 'Norsca Building: Raiding Port'),
    #38448: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_1', ItemType.building, 0, 'Progressive nor_settlement_major', 'Norsca Building: Warrior Gathering'),
    #38449: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_2', ItemType.building, 1, 'Progressive nor_settlement_major', 'Norsca Building: Warband Camp'),
    #38450: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_3', ItemType.building, 2, 'Progressive nor_settlement_major', 'Norsca Building: Clan Enclave'),
    #38451: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_4', ItemType.building, 3, 'Progressive nor_settlement_major', 'Norsca Building: Tribal Stronghold'),
    #38452: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_5', ItemType.building, 4, 'Progressive nor_settlement_major', 'Norsca Building: Greater Tribal Stronghold'),
    #38453: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_1', ItemType.building, 0, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Encampment'),
    #38454: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_2', ItemType.building, 1, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Moot'),
    #38455: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_3', ItemType.building, 2, 'Progressive nor_settlement_minor', 'Norsca Building: Norse Village'),
    38456: itemData(IC.useful, 1, 'wh_main_nor_slaves_1', itemType.building, 0, 'Progressive nor_slaves', 'Norsca Building: Fur Stash'),
    38457: itemData(IC.useful, 1, 'wh_main_nor_slaves_2', itemType.building, 1, 'Progressive nor_slaves', 'Norsca Building: Beast Tanner'),
    38458: itemData(IC.useful, 1, 'wh_main_nor_slaves_3', itemType.building, 2, 'Progressive nor_slaves', "Norsca Building: Slaver's Camp"),
    38459: itemData(IC.useful, 1, 'wh3_dlc27_nor_slaves_4', itemType.building, 3, 'Progressive nor_slaves', 'Norsca Building: Longhouse Under-Hall'),
    38460: itemData(IC.useful, 1, 'wh_main_nor_smith_1', itemType.building, 0, 'Progressive nor_smith', 'Norsca Building: Smithy'),
    38461: itemData(IC.useful, 1, 'wh_main_nor_smith_2', itemType.building, 1, 'Progressive nor_smith', 'Norsca Building: Ruinous Kiln'),
    38462: itemData(IC.useful, 1, 'wh_main_nor_smith_3', itemType.building, 2, 'Progressive nor_smith', 'Norsca Building: Dark Furnace'),
    38463: itemData(IC.useful, 1, 'wh_main_nor_stables_1', itemType.building, 0, 'Progressive nor_stables', 'Norsca Building: Shieling'),
    38464: itemData(IC.useful, 1, 'wh_main_nor_stables_2', itemType.building, 1, 'Progressive nor_stables', 'Norsca Building: Corral'),
    38465: itemData(IC.useful, 1, 'wh_main_nor_stables_3', itemType.building, 2, 'Progressive nor_stables', 'Norsca Building: Ruinous Stables'),
    38466: itemData(IC.useful, 1, 'wh_main_nor_walls_1', itemType.building, 0, 'Progressive nor_walls', 'Norsca Building: Bloody Bulwark'),
    38467: itemData(IC.useful, 1, 'wh_main_nor_walls_2', itemType.building, 1, 'Progressive nor_walls', 'Norsca Building: Skull-Laden Embankment'),
    38468: itemData(IC.useful, 1, 'wh_main_nor_walls_3', itemType.building, 2, 'Progressive nor_walls', 'Norsca Building: Wall of Carcasses'),
    38469: itemData(IC.useful, 1, 'wh_main_nor_walls_4', itemType.building, 3, 'Progressive nor_walls', 'Norsca Building: Figurehead Palisade'),
    38470: itemData(IC.useful, 1, 'wh_main_nor_worship_1', itemType.building, 0, 'Progressive nor_worship', 'Norsca Building: Ruinous Altar'),
    38471: itemData(IC.useful, 1, 'wh_main_nor_worship_2', itemType.building, 1, 'Progressive nor_worship', 'Norsca Building: Chaos Shrine'),
    38472: itemData(IC.useful, 1, 'wh_main_nor_worship_3', itemType.building, 2, 'Progressive nor_worship', 'Norsca Building: Vitki Temple')
    #38436: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_1', ItemType.building, 0, 'Progressive nor_outpost_experience', 'Norsca Building: Tattooist'),
    #38437: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_2', ItemType.building, 1, 'Progressive nor_outpost_experience', 'Norsca Building: Flesh Brander'),
    #38438: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_3', ItemType.building, 2, 'Progressive nor_outpost_experience', 'Norsca Building: Flesh Carver'),
    #38439: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_1', ItemType.building, 0, 'Progressive nor_outpost_garrison', 'Norsca Building: Guard Shack'),
    #38440: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_2', ItemType.building, 1, 'Progressive nor_outpost_garrison', 'Norsca Building: Watchtower'),
    #38441: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_3', ItemType.building, 2, 'Progressive nor_outpost_garrison', 'Norsca Building: Marauding Militia'),
    #38442: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_1', ItemType.building, 0, 'Progressive nor_outpost_growth', 'Norsca Building: Ruinous Altar'),
    #38443: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_2', ItemType.building, 1, 'Progressive nor_outpost_growth', 'Norsca Building: Chaos Shrine'),
    #38444: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_3', ItemType.building, 2, 'Progressive nor_outpost_growth', 'Norsca Building: Sacrificial Pyre'),
    #38445: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_1', ItemType.building, 0, 'Progressive nor_outpost_income', "Norsca Building: Whorl of Raiders' Remains"),
    #38446: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_2', ItemType.building, 1, 'Progressive nor_outpost_income', 'Norsca Building: Marauder Blood-Grove'),
    #38447: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_3', ItemType.building, 2, 'Progressive nor_outpost_income', 'Norsca Building: Trove Temple of Champions'),
    #38448: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_1', ItemType.building, 0, 'Progressive nor_outpost_major_human', 'Norsca Building: Coastal Enclave'),
    #38449: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_2', ItemType.building, 1, 'Progressive nor_outpost_major_human', 'Norsca Building: Tribal Anchorage'),
    #38450: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_3', ItemType.building, 2, 'Progressive nor_outpost_major_human', 'Norsca Building: Manmade Fjord'),
    #38451: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_1', ItemType.building, 0, 'Progressive nor_outpost_military', 'Norsca Building: Sparring Fields'),
    #38452: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_2', ItemType.building, 1, 'Progressive nor_outpost_military', "Norsca Building: Raiders' Camp"),
    #38453: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_3', ItemType.building, 2, 'Progressive nor_outpost_military', "Norsca Building: Chieftain's Hall"),
    #38454: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_1', ItemType.building, 0, 'Progressive nor_outpost_stables', 'Norsca Building: Shieling'),
    #38455: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_2', ItemType.building, 1, 'Progressive nor_outpost_stables', 'Norsca Building: Corral'),
    #38456: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_3', ItemType.building, 2, 'Progressive nor_outpost_stables', 'Norsca Building: Ruinous Stables'),
}

techs: dict[int, itemData] = {
    38800: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_20', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Burning of the Wood Elves'),
    38801: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_07', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Destruction of Bretonnia'),
    38802: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_16', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Ruination of the Vampire Counts'),
    38803: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_11', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Ravaging of the Dwarfs'),
    38804: itemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_hate_kislev', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Desolation of Kislev'),
    38805: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_14', itemType.tech, 1, 'Progressive tech_nor_old_world', 'Norsca Tech: Razing of the Empire'),
    38806: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_02', itemType.tech, 1, 'Progressive tech_nor_new_world', 'Norsca Tech: Devastation of the Dark Elves'),
    38807: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_04', itemType.tech, 1, 'Progressive tech_nor_new_world', 'Norsca Tech: Butchering of the High Elves'),
    38808: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_06', itemType.tech, 1, 'Progressive tech_nor_new_world', 'Norsca Tech: Pillaging of the Lizardmen'),
    38809: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_20', itemType.tech, 1, 'Progressive tech_nor_new_world', 'Norsca Tech: Blockading the Vampire Coast'),
    38810: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_10', itemType.tech, 1, 'Progressive tech_nor_badlands', 'Norsca Tech: Plundering of the Tomb Kings'),
    38811: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_08', itemType.tech, 1, 'Progressive tech_nor_badlands', 'Norsca Tech: Annihilation of the Skaven'),
    38812: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_18', itemType.tech, 1, 'Progressive tech_nor_badlands', 'Norsca Tech: Slaughtering of the Greenskins'),
    38813: itemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_chaos_dwarfs', itemType.tech, 1, 'Progressive tech_nor_beyond', 'Norsca Tech: Demolition of the Chaos Dwarfs'),
    38814: itemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_cathay', itemType.tech, 1, 'Progressive tech_nor_beyond', 'Norsca Tech: Collapse of Grand Cathay'),
    38815: itemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_ogre_kingdoms', itemType.tech, 1, 'Progressive tech_nor_beyond', 'Norsca Tech: Smashing the Ogre Kingdoms'),
    38816: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_slaanesh', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: As the serpent '),
    38817: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_khorne', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: Running With the Hound'),
    38818: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_tzeentch', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: Dreams Become Real'),
    38819: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_nurgle', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: The Cold and the Crow'),
    38820: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_norsca', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: Masters of the North'),
    38821: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_beastmen', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: Hunting of the Beastmen '),
    38822: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_chaos', itemType.tech, 1, 'Progressive tech_nor_wastes', 'Norsca Tech: True Warriors of Chaos '),
    38823: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_02', itemType.tech, 1, 'Progressive tech_nor_customs', 'Norsca Tech: Chaos Surge'),
    38824: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_03', itemType.tech, 2, 'Progressive tech_nor_customs', "Norsca Tech: Bladeworker's Hammer"),
    38825: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_04', itemType.tech, 2, 'Progressive tech_nor_customs', "Norsca Tech: Axemaker's Stone"),
    38826: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_05', itemType.tech, 3, 'Progressive tech_nor_customs', "Norsca Tech: Crafter's Barding"),
    38827: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_06', itemType.tech, 3, 'Progressive tech_nor_customs', "Norsca Tech: Horsemaster's Clinchers"),
    38828: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_02', itemType.tech, 4, 'Progressive tech_nor_customs', "Norsca Tech: Metalworker's Anvil"),
    38829: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_05', itemType.tech, 5, 'Progressive tech_nor_customs', 'Norsca Tech: Champions of War'),
    38830: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_nocturnality', itemType.tech, 1, 'Progressive tech_nor_customs', 'Norsca Tech: Natural Selection'),
    38831: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_06', itemType.tech, 2, 'Progressive tech_nor_customs', 'Norsca Tech: One with Beasts'),
    38832: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_elder_trolls', itemType.tech, 2, 'Progressive tech_nor_customs', 'Norsca Tech: Elder Trolls'),
    38833: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_04', itemType.tech, 3, 'Progressive tech_nor_customs', 'Norsca Tech: Blood-Fuelled Hunger'),
    38834: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_leading', itemType.tech, 3, 'Progressive tech_nor_customs', 'Norsca Tech: Occasional Appeasement'),
    38835: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_tough_skin', itemType.tech, 4, 'Progressive tech_nor_customs', 'Norsca Tech: Violent Evolution'),
    38836: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_taming', itemType.tech, 1, 'Progressive tech_nor_customs', 'Norsca Tech: Secrets of Taming'),
    38837: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_05', itemType.tech, 2, 'Progressive tech_nor_customs', 'Norsca Tech: Baying to Morrslieb'),
    38838: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_great_deal', itemType.tech, 2, 'Progressive tech_nor_customs', 'Norsca Tech: Gigantic Armaments'),
    38839: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_01', itemType.tech, 3, 'Progressive tech_nor_customs', 'Norsca Tech: Monster Hunter'),
    38840: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_lumbering', itemType.tech, 3, 'Progressive tech_nor_customs', 'Norsca Tech: Everliving Spite'),
    38841: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_hardened_tusks', itemType.tech, 4, 'Progressive tech_nor_customs', 'Norsca Tech: Deadly Prey'),
    38842: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_07', itemType.tech, 5, 'Progressive tech_nor_customs', 'Norsca Tech: Master of Beasts'),
    38843: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_rally_tribes', itemType.tech, 5, 'Progressive tech_nor_customs', 'Norsca Tech: Rally the Tribes'),
    38844: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_feasting', itemType.tech, 6, 'Progressive tech_nor_customs', 'Norsca Tech: Seat at the Table'),
    38845: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_03', itemType.tech, 7, 'Progressive tech_nor_customs', 'Norsca Tech: Secrets of Dark Sorcery'),
    38846: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_03', itemType.tech, 8, 'Progressive tech_nor_customs', 'Norsca Tech: Ice-Blooded Strength'),
    38847: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_potions', itemType.tech, 6, 'Progressive tech_nor_customs', 'Norsca Tech: What the Blood Shows'),
    38848: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_shamans', itemType.tech, 7, 'Progressive tech_nor_customs', 'Norsca Tech: What the Shamans Know'),
    38849: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_regenerating', itemType.tech, 8, 'Progressive tech_nor_customs', 'Norsca Tech: What Starts the War'),
    38850: itemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_kislev_capital', itemType.tech, 9, 'Progressive tech_nor_customs', 'Norsca Tech: Secrets of the Ice'),
    38851: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_watchtower', itemType.tech, 1, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Untiring Sentries'),
    38852: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_palisade', itemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Norsca Tech: None Shall Enter'),
    38853: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_purpose', itemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Dark Purpose'),
    38854: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_crow', itemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Beware the Crow'),
    38855: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_weapons', itemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Call of the Horn'),
    38856: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_cartographers', itemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Deliberate Service'),
    38857: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_envoy', itemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Norsca Tech: A Reminder of Strength'),
    38858: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_campfire', itemType.tech, 4, 'Progressive tech_nor_tribal_1', 'Norsca Tech: A Taste of Bloody Triumph'),
    38859: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_cam_advantage', itemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Rousing Advantage'),
    38860: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_worship', itemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Norsca Tech: The Eyes of the Four'),
    38861: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_01', itemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Norsca Tech: War Tools'),
    38862: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_02', itemType.tech, 6, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Longer Hulls'),
    38863: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_scavenge', itemType.tech, 6, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Under Their Gaze'),
    38864: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_watchtower', itemType.tech, 6, 'Progressive wh3_dlc27_tech_nor_cam_quartermasters', 'Norsca Tech: Tools of War'),
    38865: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_leaders', itemType.tech, 7, 'Progressive tech_nor_tribal_1', 'Norsca Tech: Those Who Are Seen'),
    38866: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_other_22', itemType.tech, 1, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Sagas of the Stars'),
    38867: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_pillagers', itemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Scourges of the World'),
    38868: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_walkers', itemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Norsca Tech: The Wanderers'),
    38869: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_large_traps', itemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Norscan Hunter Traps'),
    38870: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_whispers', itemType.tech, 3, 'Progressive tech_nor_tribal_2', 'Norsca Tech: What is Taken'),
    38871: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_01', itemType.tech, 3, 'Progressive tech_nor_tribal_2', "Norsca Tech: Sea Marauder's Tools"),
    38872: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_northlands', itemType.tech, 3, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Secrets of the Northlands'),
    38873: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_04', itemType.tech, 4, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Stronger Oars'),
    38874: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_10', itemType.tech, 5, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Secrets of War & Coin'),
    38875: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_07', itemType.tech, 5, 'Progressive tech_nor_tribal_2', "Norsca Tech: Butcher's Captives"),
    38876: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_wind', itemType.tech, 5, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Winds of the North'),
    38877: itemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_03', itemType.tech, 6, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Corpulent Sails'),
    38878: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_waters', itemType.tech, 6, 'Progressive tech_nor_tribal_2', 'Norsca Tech: Sail With the Waters'),
    38879: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_familiar', itemType.tech, 6, 'Progressive wh3_dlc27_tech_nor_cam_quartermasters', 'Norsca Tech: The Fourfold Voice'),
    38880: itemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_persistence', itemType.tech, 7, 'Progressive tech_nor_tribal_2', 'Norsca Tech: The Hound Watches')
}

progUnits: dict[int, itemData] = {
    39200: itemData(IC.useful, 5, "Progressive nor_inf", itemType.unit, 5, "", "Progressive Norsca Unit: Infantry"),
    39201: itemData(IC.useful, 1, "Progressive nor_rng", itemType.unit, 1, "", "Progressive Norsca Unit: Ranged"),
    39202: itemData(IC.useful, 3, "Progressive nor_cav", itemType.unit, 3, "", "Progressive Norsca Unit: Cavalry"),
    39203: itemData(IC.useful, 1, "Progressive nor_art", itemType.unit, 1, "", "Progressive Norsca Unit: Artillery"),
    39204: itemData(IC.useful, 2, "Progressive nor_veh", itemType.unit, 2, "", "Progressive Norsca Unit: Chariot"),
    39205: itemData(IC.useful, 5, "Progressive nor_bst", itemType.unit, 5, "", "Progressive Norsca Unit: Beast"),
    39206: itemData(IC.useful, 3, "Progressive nor_hro", itemType.unit, 3, "", "Progressive Norsca Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    39300: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_nor', itemType.building, 3, None, 'Progressive Norsca Building: Foreign Slot Discovery Nor'),
    39301: itemData(IC.useful, 3, 'Progressive nor_allied_outpost', itemType.building, 3, None, 'Progressive Norsca Building: Allied Outpost'),
    39302: itemData(IC.useful, 5, 'Progressive nor_settlement_major', itemType.building, 5, None, 'Progressive Norsca Building: Settlement Major'),
    39303: itemData(IC.useful, 3, 'Progressive nor_settlement_major', itemType.building, 3, None, 'Progressive Norsca Building: Settlement Minor'),
    39304: itemData(IC.useful, 1, 'Progressive nor_resource_iron', itemType.building, 1, None, 'Progressive Norsca Building: Iron'),
    39305: itemData(IC.useful, 1, 'Progressive nor_resource_marble', itemType.building, 1, None, 'Progressive Norsca Building: Marble'),
    39306: itemData(IC.useful, 1, 'Progressive nor_resource_obsidian', itemType.building, 1, None, 'Progressive Norsca Building: Obsidian'),
    39307: itemData(IC.useful, 3, 'Progressive nor_beasts', itemType.building, 3, None, 'Progressive Norsca Building: Beasts'),
    39308: itemData(IC.useful, 2, 'Progressive nor_chaos', itemType.building, 2, None, 'Progressive Norsca Building: Chaos'),
    39309: itemData(IC.useful, 3, 'Progressive nor_creatures', itemType.building, 3, None, 'Progressive Norsca Building: Creatures'),
    39310: itemData(IC.useful, 3, 'Progressive nor_garrison', itemType.building, 3, None, 'Progressive Norsca Building: Garrison'),
    39311: itemData(IC.useful, 3, 'Progressive nor_loot', itemType.building, 3, None, 'Progressive Norsca Building: Loot'),
    39312: itemData(IC.useful, 3, 'Progressive nor_military', itemType.building, 3, None, 'Progressive Norsca Building: Military'),
    39313: itemData(IC.useful, 2, 'Progressive nor_offerings', itemType.building, 2, None, 'Progressive Norsca Building: Offerings'),
    39314: itemData(IC.useful, 3, 'Progressive nor_outpost_experience', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Experience'),
    39315: itemData(IC.useful, 3, 'Progressive nor_outpost_garrison', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Garrison'),
    39316: itemData(IC.useful, 3, 'Progressive nor_outpost_growth', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Growth'),
    39317: itemData(IC.useful, 3, 'Progressive nor_outpost_income', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Income'),
    39318: itemData(IC.useful, 3, 'Progressive nor_outpost_major_human', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Major Human'),
    39319: itemData(IC.useful, 3, 'Progressive nor_outpost_military', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Military'),
    39320: itemData(IC.useful, 3, 'Progressive nor_outpost_stables', itemType.building, 3, None, 'Progressive Norsca Building: Outpost Stables'),
    39321: itemData(IC.useful, 3, 'Progressive nor_port', itemType.building, 3, None, 'Progressive Norsca Building: Port'),
    39322: itemData(IC.useful, 3, 'Progressive nor_slaves', itemType.building, 3, None, 'Progressive Norsca Building: Slaves'),
    39323: itemData(IC.useful, 3, 'Progressive nor_smith', itemType.building, 3, None, 'Progressive Norsca Building: Smith'),
    39324: itemData(IC.useful, 3, 'Progressive nor_stables', itemType.building, 3, None, 'Progressive Norsca Building: Stables'),
    39325: itemData(IC.useful, 3, 'Progressive nor_walls', itemType.building, 3, None, 'Progressive Norsca Building: Walls'),
    39326: itemData(IC.useful, 4, 'Progressive nor_worship', itemType.building, 4, None, 'Progressive Norsca Building: Worship'),
    39327: itemData(IC.useful, 3, 'Progressive nor_settlement_shrine', itemType.building, 2, None, 'Progressive Norsca Building: Altar'),
    39328: itemData(IC.useful, 3, 'Progressive nor_shrine_raiding', itemType.building, 2, None, 'Progressive Norsca Building: Raiding'),
    39329: itemData(IC.useful, 3, 'Progressive nor_shrine_recruitment', itemType.building, 2, None, 'Progressive Norsca Building: Desecrated Site'),
    39330: itemData(IC.useful, 3, 'Progressive nor_shrine_replenishment', itemType.building, 2, None, 'Progressive Norsca Building: Replenishment'),
    39331: itemData(IC.useful, 3, 'Progressive nor_shrine_garrison', itemType.building, 1, None, 'Progressive Norsca Building: Garrison')
}

progTechs: dict[int, itemData] = {
    39400: itemData(IC.useful, 9, "Progressive tech_nor_customs", itemType.tech, 9, None, "Progressive Norsca Tech: War Customs"),
    39401: itemData(IC.useful, 7, "Progressive tech_nor_tribal_1", itemType.tech, 7, None, "Progressive Norsca Tech: Tribal Suffering Upper"),
    39402: itemData(IC.useful, 7, "Progressive tech_nor_tribal_2", itemType.tech, 7, None, "Progressive Norsca Tech: Tribal Suffering Lower"),
    39403: itemData(IC.useful, 1, "Progressive tech_nor_new_world", itemType.tech, 1, None, "Progressive Norsca Tech: The New World"),
    39404: itemData(IC.useful, 1, "Progressive tech_nor_old_world", itemType.tech, 1, None, "Progressive Norsca Tech: The Old World"),
    39405: itemData(IC.useful, 1, "Progressive tech_nor_badlands", itemType.tech, 1, None, "Progressive Norsca Tech: Badlands & Below"),
    39406: itemData(IC.useful, 1, "Progressive tech_nor_wastes", itemType.tech, 1, None, "Progressive Norsca Tech: Chaos Wastes"),
    39407: itemData(IC.useful, 1, "Progressive tech_nor_beyond", itemType.tech, 1, None, "Progressive Norsca Tech: Beyond the World's Edge"),
}

special: dict[int, specialItemData] = {
    39500: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_main_kho_inf_chaos_warriors_2', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors of Khorne (Dual Weapons)'),
    39501: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_main_kho_mon_spawn_of_khorne_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Spawn of Khorne'),
    39502: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    39503: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_main_nur_mon_spawn_of_nurgle_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Spawn of Nurgle'),
    39504: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    39505: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_main_sla_mon_spawn_of_slaanesh_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Spawn of Slaanesh'),
    39506: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors of Tzeentch (Halberds)'),
    39507: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_main_tze_mon_spawn_of_tzeentch_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Spawn of Tzeentch'),
    39516: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh_main_chs_inf_chaos_warriors_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Trolls'),
    39517: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh_main_chs_inf_chaos_warriors_1', itemType.unit, 3, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Trolls (Armoured)'),
    39518: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh_main_chs_inf_chaos_warriors_2', itemType.unit, 3, 'Progressive nor_inf', False, False, 'Norsca Unit: Stone Trolls'),
    39519: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh_main_chs_inf_chaos_warriors_2', itemType.unit, 3, 'Progressive nor_inf', False, False, 'Norsca Unit: River Trolls'),
    39520: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh_main_chs_inf_chaos_warriors_2', itemType.unit, 3, 'Progressive nor_inf', False, False, 'Norsca Unit: Bile Trolls'),
    39521: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh_main_chs_inf_chaos_warriors_0', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors'),
    39522: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh_main_chs_inf_chaos_warriors_1', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors (Halberds)'),
    39523: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh_main_chs_inf_chaos_warriors_2', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Warriors (Great Weapons)'),
    39524: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh_main_chs_mon_chaos_spawn', itemType.unit, 2, 'Progressive nor_inf', False, False, 'Norsca Unit: Chaos Spawn'),
    39525: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_offerings_2b', itemType.building, 1, 'Progressive nor_offerings', False, False, 'Norsca Building: Colossal Offerings'),
    39526: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_offerings_3', itemType.building, 2, 'Progressive nor_offerings', False, False, "Norsca Building: Curs'd Cavern"),
    39527: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_offerings_2b', itemType.building, 1, 'Progressive nor_offerings', False, False, 'Norsca Building: Colossal Offerings (Sayl)'),
    39528: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_offerings_3', itemType.building, 2, 'Progressive nor_offerings', False, False, "Norsca Building: Curs'd Cavern (Sayl)"),
    39531: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_garrison_1', itemType.building, 0, 'Progressive nor_shrine_garrison', False, False, 'Norsca Building: Marauding Militia'),
    39532: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_major_human_1', itemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Fanged Monolith'),
    39533: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_major_human_2', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Ravenous Monolith'),
    39534: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_raiding_1', itemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Trophies of Battle'),
    39535: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_raiding_2A', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Ravager Cairn'),
    39536: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_raiding_2B', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, "Norsca Building: Butcher's Plinth"),
    39537: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_recruitment_1', itemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Skull-Rise'),
    39538: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2A', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Mock-God'),
    39539: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2B', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Carcass-Heap'),
    39540: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_replenishment_1', itemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Bleeding Grounds'),
    39541: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2A', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Warhowl Barrow'),
    39542: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2B', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Gorepit'),
    39543: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_major_human_1', itemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Coiling Monolith'),
    39544: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_major_human_2', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Undulant Monolith'),
    39545: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_raiding_1', itemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Trophies of Battle'),
    39546: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_raiding_2A', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Ravager Cairn'),
    39547: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_raiding_2B', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Heady Brazier'),
    39548: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_recruitment_1', itemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Skull-Rise'),
    39549: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2A', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Mock-God'),
    39550: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2B', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Carcass-Heap'),
    39551: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_replenishment_1', itemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Bleeding Grounds'),
    39552: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2A', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Warhowl Barrow'),
    39553: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2B', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Ophidian Arch'),
    39554: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_major_human_1', itemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Blighted Monolith'),
    39555: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_major_human_2', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Pestilent Monolith'),
    39556: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_raiding_1', itemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Trophies of Battle'),
    39557: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_raiding_2A', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Ravager Cairn'),
    39558: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_raiding_2B', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Flystone'),
    39559: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_recruitment_1', itemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Skull-Rise'),
    39560: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2A', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Mock-God'),
    39561: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2B', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Carcass-Heap'),
    39562: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_replenishment_1', itemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Bleeding Grounds'),
    39563: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2A', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Warhowl Barrow'),
    39564: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2B', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Blighted Vat'),
    39565: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_major_human_1', itemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Many-Faced Monolith'),
    39566: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_major_human_2', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Ever-Changing Monolith'),
    39567: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_raiding_1', itemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Trophies of Battle'),
    39568: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_raiding_2A', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Ravager Cairn'),
    39569: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_raiding_2B', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Twisting Spire'),
    39570: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_recruitment_1', itemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Skull-Rise'),
    39571: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2A', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Mock-God'),
    39572: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2B', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Carcass-Heap'),
    39573: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_replenishment_1', itemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Bleeding Grounds'),
    39574: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2A', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Warhowl Barrow'),
    39575: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca', 'wh_dlc08_nor_wintertooth'], 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2B', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, "Norsca Building: Scryer's Hollow"),
    39621: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_1', itemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Unshaped Monolith'),
    39622: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_2', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Aberrant Monolith'),
    39623: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_3', itemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Norsca Building: Pandaemonic Monolith'),
    39624: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_raiding_1', itemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Trophies of Battle'),
    39625: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_raiding_2A', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Ravager Cairn'),
    39626: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_raiding_2B', itemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Norsca Building: Glowering Totem'),
    39627: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_recruitment_1', itemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Skull-Rise'),
    39628: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_recruitment_2A', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Mock-God'),
    39629: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_recruitment_2B', itemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Norsca Building: Carcass-Heap'),
    39630: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_replenishment_1', itemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Bleeding Grounds'),
    39631: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_replenishment_2A', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Warhowl Barrow'),
    39632: specialItemData(IC.useful, 1, ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_nor_chaos_altar_und_replenishment_2B', itemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Norsca Building: Creeping Morass'),
    39633: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca'], 'wh3_dlc27_tech_nor_ship_faction_wulfrik_deep_seafang', itemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Norsca Tech: Sail the Impossible Seas'),
    39634: specialItemData(IC.useful, 1, ['wh_dlc08_nor_norsca'], 'wh3_dlc27_tech_nor_ship_faction_wulfrik_seafang', itemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Norsca Tech: The Ways of the Monstrous Horde'),
    39635: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh3_dlc27_tech_nor_ship_faction_throgg_raiding', itemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Norsca Tech: Prophetic Seer-Craft'),
    39636: specialItemData(IC.useful, 1, ['wh_dlc08_nor_wintertooth'], 'wh3_dlc27_tech_nor_ship_faction_throgg_troll_loyalty', itemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Norsca Tech: Loyalty to Royalty'),
    39637: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_tech_nor_ship_faction_sayl_betrayal', itemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Norsca Tech: Prophetic Seer-Craft'),
    39638: specialItemData(IC.useful, 1,  ['wh3_dlc27_nor_sayl'], 'wh3_dlc27_tech_nor_ship_faction_sayl_faithlessness', itemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Norsca Tech: Pacts of Enmity')
}

rituals: dict[int, specialItemData] = {

}