from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData

# @formatter:off
units: dict[int, itemData] = {
    40000: itemData(IC.useful, 1, 'wh3_main_nur_inf_nurglings_0', itemType.unit, 1, 'Progressive nur_inf', 'Nurgle Unit: Nurglings'),
    40001: itemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_0', itemType.unit, 2, 'Progressive nur_inf', 'Nurgle Unit: Plaguebearers of Nurgle'),
    40002: itemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_1', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Exalted Plaguebearers of Nurgle'),
    40003: itemData(IC.useful, 1, 'wh3_main_nur_inf_forsaken_0', itemType.unit, 1, 'Progressive nur_inf', 'Nurgle Unit: Forsaken of Nurgle'),
    40004: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mnur', itemType.unit, 1, 'Progressive nur_inf', 'Nurgle Unit: Marauders of Nurgle'),
    40005: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mnur_greatweapons', itemType.unit, 2, 'Progressive nur_inf', 'Nurgle Unit: Marauders of Nurgle (Great Weapons)'),
    40006: itemData(IC.useful, 1, 'wh3_dlc25_nur_inf_pestigors', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Pestigors'),
    40007: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mnur', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Chaos Warriors of Nurgle'),
    40008: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    40009: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mnur', itemType.unit, 4, 'Progressive nur_inf', 'Nurgle Unit: Chosen of Nurgle'),
    40010: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mnur_greatweapons', itemType.unit, 5, 'Progressive nur_inf', 'Nurgle Unit: Chosen of Nurgle (Great Weapons)'),
    40011: itemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Plague Ogres'),
    40012: itemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres_great_weapons', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Plague Ogres (Great Weapons)'),
    40013: itemData(IC.useful, 1, 'wh3_main_nur_cav_plague_drones_0', itemType.unit, 1, 'Progressive nur_cav', 'Nurgle Unit: Plague Drones of Nurgle'),
    40014: itemData(IC.useful, 1, 'wh3_main_nur_cav_pox_riders_of_nurgle_0', itemType.unit, 1, 'Progressive nur_cav', 'Nurgle Unit: Pox Riders of Nurgle'),
    40015: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes', itemType.unit, 1, 'Progressive nur_cav', 'Nurgle Unit: Marauder Horsemen of Nurgle (Throwing Axes)'),
    40016: itemData(IC.useful, 1, 'wh3_main_nur_cav_plague_drones_1', itemType.unit, 2, 'Progressive nur_cav', "Nurgle Unit: Plague Drones of Nurgle (Death's Heads)"),
    40017: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mnur', itemType.unit, 3, 'Progressive nur_cav', 'Nurgle Unit: Chaos Knights of Nurgle'),
    40018: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mnur_lances', itemType.unit, 4, 'Progressive nur_cav', 'Nurgle Unit: Chaos Knights of Nurgle (Lances)'),
    40019: itemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights', itemType.unit, 4, 'Progressive nur_cav', 'Nurgle Unit: Rot Knights'),
    40020: itemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_1', itemType.unit, 1, 'Progressive nur_bst', 'Nurgle Unit: Chaos Warhounds (Poison)'),
    40021: itemData(IC.useful, 1, 'wh3_main_nur_inf_chaos_furies_0', itemType.unit, 1, 'Progressive nur_bst', 'Nurgle Unit: Chaos Furies (Nurgle)'),
    40022: itemData(IC.useful, 1, 'wh3_main_nur_mon_plague_toads_0', itemType.unit, 2, 'Progressive nur_bst', 'Nurgle Unit: Plague Toads of Nurgle'),
    40023: itemData(IC.useful, 1, 'wh3_main_nur_mon_rot_flies_0', itemType.unit, 3, 'Progressive nur_bst', 'Nurgle Unit: Rot Flies'),
    40024: itemData(IC.useful, 1, 'wh3_dlc25_nur_mon_bile_trolls', itemType.unit, 4, 'Progressive nur_bst', 'Nurgle Unit: Bile Trolls'),
    40025: itemData(IC.useful, 1, 'wh3_main_nur_mon_spawn_of_nurgle_0', itemType.unit, 5, 'Progressive nur_bst', 'Nurgle Unit: Spawn of Nurgle'),
    40026: itemData(IC.useful, 1, 'wh3_main_nur_mon_beast_of_nurgle_0', itemType.unit, 1, 'Progressive nur_bst', 'Nurgle Unit: Beast of Nurgle'),
    40027: itemData(IC.useful, 1, 'wh3_main_nur_mon_soul_grinder_0', itemType.unit, 4, 'Progressive nur_bst', 'Nurgle Unit: Soul Grinder of Nurgle'),
    40028: itemData(IC.useful, 1, 'wh3_main_nur_mon_great_unclean_one_0', itemType.unit, 5, 'Progressive nur_bst', 'Nurgle Unit: Great Unclean One'),
    40029: itemData(IC.useful, 1, 'wh3_dlc25_nur_mon_toad_dragon', itemType.unit, 6, 'Progressive nur_bst', 'Nurgle Unit: Toad Dragon'),
    40030: itemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mnur', itemType.unit, 1, 'Progressive nur_veh', 'Nurgle Unit: Chaos Warshrine of Nurgle'),
    40031: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_mnur', itemType.unit, 1, 'Progressive nur_veh', 'Nurgle Unit: Chaos Chariots of Nurgle'),
    40032: itemData(IC.useful, 1, 'wh3_main_nur_cha_cultist_0', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Cultist of Nurgle'),
    40033: itemData(IC.useful, 1, 'wh3_main_nur_cha_plagueridden_nurgle_0', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Plagueridden (Nurgle)'),
    40034: itemData(IC.useful, 1, 'wh3_main_nur_cha_plagueridden_death_0', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Plagueridden (Death)'),
    40035: itemData(IC.useful, 1, 'wh3_dlc20_chs_cha_exalted_hero_mnur', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Exalted Hero of Nurgle'),
    40036: itemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_death_mnur', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Chaos Sorcerer of Nurgle (Death)'),
    40037: itemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_nurgle_mnur', itemType.unit, 1, 'Progressive nur_hro', 'Nurgle Unit: Chaos Sorcerer of Nurgle (Nurgle)'),
    40038: itemData(IC.useful, 1, 'wh3_twa10_nur_inf_nurglings_ror', itemType.unit, 1, 'Progressive nur_inf', 'Nurgle Unit: The Frolickers Bubonic (Nurglings)'),
    40039: itemData(IC.useful, 1, 'wh3_twa08_nur_mon_great_unclean_one_0_ror', itemType.unit, 5, 'Progressive nur_bst', 'Nurgle Unit: Uncle Furuncle (Great Unclean One)'),
    40040: itemData(IC.useful, 1, 'wh3_twa07_nur_cav_pox_riders_of_nurgle_ror_0', itemType.unit, 1, 'Progressive nur_cav', 'Nurgle Unit: Barons of the Bog (Pox Riders of Nurgle)'),
    40041: itemData(IC.useful, 1, 'wh3_twa06_nur_inf_plaguebearers_ror_0', itemType.unit, 3, 'Progressive nur_inf', 'Nurgle Unit: Festering Stooges (Exalted Plaguebearers of Nurgle)'),
    40042: itemData(IC.useful, 1, 'wh3_dlc25_nur_mon_soul_grinder_0_ror', itemType.unit, 4, 'Progressive nur_bst', 'Nurgle Unit: Noxbringer (Soul Grinder of Nurgle)'),
    40043: itemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights_ror', itemType.unit, 4, 'Progressive nur_cav', 'Nurgle Unit: The Rotting Riders (Rot Knights)'),
    40044: itemData(IC.useful, 1, 'wh3_dlc25_nur_cav_plague_drones_1_ror', itemType.unit, 2, 'Progressive nur_cav', "Nurgle Unit: The Angels of Decay (Plague Drones - Death's Heads)"),
    40045: itemData(IC.useful, 1, 'wh3_dlc27_nor_inf_chaos_marauders_great_weapons_ror', itemType.unit, 2, 'Progressive nur_inf', 'Nurgle Unit: Worshippers of the Crow (Marauders – Great Weapons)'),
    40046: itemData(IC.useful, 1, 'wh_pro04_chs_inf_forsaken_ror_0', itemType.unit, 1, 'Progressive nur_inf', 'Nurgle Unit: The Daemonspew (Forsaken)'),
    40047: itemData(IC.useful, 1, 'wh3_dlc20_chs_mon_giant_mnur_ror', itemType.unit, 4, 'Progressive nur_bst', 'Nurgle Unit: Bilious Thunderguff (Chaos Giant)')
}

buildings: dict[int, itemData] = {
    40401: itemData(IC.useful, 1, 'wh3_dlc25_nur_garrison_1', itemType.building, 0, 'Progressive nur_garrison', 'Nurgle Building: Festering Pit'),
    40402: itemData(IC.useful, 1, 'wh3_dlc25_nur_garrison_2', itemType.building, 1, 'Progressive nur_garrison', 'Nurgle Building: Hall of Hosts'),
    40403: itemData(IC.useful, 1, 'wh3_dlc25_nur_walls_1', itemType.building, 0, 'Progressive nur_walls', 'Nurgle Building: Spiked Palisade'),
    40404: itemData(IC.useful, 1, 'wh3_dlc25_nur_walls_2', itemType.building, 1, 'Progressive nur_walls', 'Nurgle Building: Barricade of Bones'),
    40405: itemData(IC.useful, 1, 'wh3_dlc25_nur_walls_3', itemType.building, 2, 'Progressive nur_walls', 'Nurgle Building: Rotten Ramparts'),
    40408: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_nur_1', itemType.building, 0, 'Progressive foreign_slot_discovery_nur', 'Nurgle Building: Warpstone Locus'),
    40409: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_nur_2', itemType.building, 1, 'Progressive foreign_slot_discovery_nur', 'Nurgle Building: Warpstone Traps'),
    40410: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_nur_3', itemType.building, 2, 'Progressive foreign_slot_discovery_nur', 'Nurgle Building: Guarded Warpstone'),
    40411: itemData(IC.useful, 1, 'wh3_main_nur_1_1', itemType.building, 0, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Seeding)'),
    40412: itemData(IC.useful, 1, 'wh3_main_nur_1_2', itemType.building, 1, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Germinating)'),
    40413: itemData(IC.useful, 1, 'wh3_main_nur_1_3', itemType.building, 2, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Budding)'),
    40414: itemData(IC.useful, 1, 'wh3_main_nur_1_4', itemType.building, 3, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Pollinating)'),
    40415: itemData(IC.useful, 1, 'wh3_main_nur_1_5', itemType.building, 4, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Withering)'),
    40416: itemData(IC.useful, 1, 'wh3_main_nur_1_6', itemType.building, 5, 'Progressive nur_1', 'Nurgle Building: Plagueflesh Poppies (Decomposing)'),
    40417: itemData(IC.useful, 1, 'wh3_main_nur_2_1', itemType.building, 0, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Seeding)'),
    40418: itemData(IC.useful, 1, 'wh3_main_nur_2_2', itemType.building, 1, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Germinating)'),
    40419: itemData(IC.useful, 1, 'wh3_main_nur_2_3', itemType.building, 2, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Budding)'),
    40420: itemData(IC.useful, 1, 'wh3_main_nur_2_4', itemType.building, 3, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Pollinating)'),
    40421: itemData(IC.useful, 1, 'wh3_main_nur_2_5', itemType.building, 4, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Withering)'),
    40422: itemData(IC.useful, 1, 'wh3_main_nur_2_6', itemType.building, 5, 'Progressive nur_2', 'Nurgle Building: Rancid Aloe (Decomposing)'),
    40423: itemData(IC.useful, 1, 'wh3_main_nur_3_1', itemType.building, 0, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Fertilisation)'),
    40424: itemData(IC.useful, 1, 'wh3_main_nur_3_2', itemType.building, 1, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Incubation)'),
    40425: itemData(IC.useful, 1, 'wh3_main_nur_3_3', itemType.building, 2, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Metamorphosis)'),
    40426: itemData(IC.useful, 1, 'wh3_main_nur_3_4', itemType.building, 3, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Larvae)'),
    40427: itemData(IC.useful, 1, 'wh3_main_nur_3_5', itemType.building, 4, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Pupae)'),
    40428: itemData(IC.useful, 1, 'wh3_main_nur_3_6', itemType.building, 5, 'Progressive nur_3', 'Nurgle Building: Daemonic Egg Sacs (Spawn)'),
    40429: itemData(IC.useful, 1, 'wh3_main_nur_4_1', itemType.building, 0, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Seeding)'),
    40430: itemData(IC.useful, 1, 'wh3_main_nur_4_2', itemType.building, 1, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Germinating)'),
    40431: itemData(IC.useful, 1, 'wh3_main_nur_4_3', itemType.building, 2, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Budding)'),
    40432: itemData(IC.useful, 1, 'wh3_main_nur_4_4', itemType.building, 3, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Leafing)'),
    40433: itemData(IC.useful, 1, 'wh3_main_nur_4_5', itemType.building, 4, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Fruiting)'),
    40434: itemData(IC.useful, 1, 'wh3_main_nur_4_6', itemType.building, 5, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Maturing)'),
    40435: itemData(IC.useful, 1, 'wh3_main_nur_4_7', itemType.building, 6, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Withering)'),
    40436: itemData(IC.useful, 1, 'wh3_main_nur_4_8', itemType.building, 7, 'Progressive nur_4', 'Nurgle Building: Living Tree of Decay (Decomposing)'),
    40437: itemData(IC.useful, 1, 'wh3_main_nur_5_1', itemType.building, 0, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Seeding)'),
    40438: itemData(IC.useful, 1, 'wh3_main_nur_5_2', itemType.building, 1, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Germinating)'),
    40439: itemData(IC.useful, 1, 'wh3_main_nur_5_3', itemType.building, 2, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Budding)'),
    40440: itemData(IC.useful, 1, 'wh3_main_nur_5_4', itemType.building, 3, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Flowering)'),
    40441: itemData(IC.useful, 1, 'wh3_main_nur_5_5', itemType.building, 4, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Pollinating)'),
    40442: itemData(IC.useful, 1, 'wh3_main_nur_5_6', itemType.building, 5, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Maturing)'),
    40443: itemData(IC.useful, 1, 'wh3_main_nur_5_7', itemType.building, 6, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Withering)'),
    40444: itemData(IC.useful, 1, 'wh3_main_nur_5_8', itemType.building, 7, 'Progressive nur_5', 'Nurgle Building: Lesser Garden of Blight (Decomposing)'),
    40445: itemData(IC.useful, 1, 'wh3_main_nur_6_1', itemType.building, 0, 'Progressive nur_6', 'Nurgle Building: Microbial Bog'),
    40446: itemData(IC.useful, 1, 'wh3_main_nur_6_2', itemType.building, 1, 'Progressive nur_6', 'Nurgle Building: Decomposing Swamp'),
    40447: itemData(IC.useful, 1, 'wh3_main_nur_6_3', itemType.building, 2, 'Progressive nur_6', 'Nurgle Building: Vile Synthesis'),
    40448: itemData(IC.useful, 1, 'wh3_main_nur_6_4', itemType.building, 3, 'Progressive nur_6', 'Nurgle Building: Replicating Mould'),
    40449: itemData(IC.useful, 1, 'wh3_main_nur_7_1', itemType.building, 0, 'Progressive nur_7', 'Nurgle Building: Weeping Creepers'),
    40450: itemData(IC.useful, 1, 'wh3_main_nur_7_2', itemType.building, 1, 'Progressive nur_7', 'Nurgle Building: Extending Tendrils'),
    40451: itemData(IC.useful, 1, 'wh3_main_nur_7_3', itemType.building, 2, 'Progressive nur_7', 'Nurgle Building: Deadly Secretions'),
    40452: itemData(IC.useful, 1, 'wh3_main_nur_7_4', itemType.building, 3, 'Progressive nur_7', 'Nurgle Building: Putrid Roots'),
    40400: itemData(IC.useful, 1, 'wh3_dlc25_nur_7_5', itemType.building, 4, 'Progressive nur_7', 'Nurgle Building: Vines of Decay'),
    40453: itemData(IC.useful, 1, 'wh3_main_nur_8_1', itemType.building, 0, 'Progressive nur_8', 'Nurgle Building: Fungi of Defilement'),
    40454: itemData(IC.useful, 1, 'wh3_main_nur_8_2', itemType.building, 1, 'Progressive nur_8', 'Nurgle Building: Toxic Spores'),
    40455: itemData(IC.useful, 1, 'wh3_main_nur_8_3', itemType.building, 2, 'Progressive nur_8', 'Nurgle Building: Malevolent Mycelium'),
    40456: itemData(IC.useful, 1, 'wh3_main_nur_8_4', itemType.building, 3, 'Progressive nur_8', 'Nurgle Building: Matured Saprophyte'),
    40457: itemData(IC.useful, 1, 'wh3_main_nur_9_1', itemType.building, 0, 'Progressive nur_9', 'Nurgle Building: Carnivorous Compost'),
    40458: itemData(IC.useful, 1, 'wh3_main_nur_9_2', itemType.building, 1, 'Progressive nur_9', 'Nurgle Building: Detritus Pit'),
    40459: itemData(IC.useful, 1, 'wh3_main_nur_allied_outpost_1', itemType.building, 0, 'Progressive nur_allied_outpost', 'Nurgle Building: Nurglish Outpost'),
    40460: itemData(IC.useful, 1, 'wh3_main_nur_allied_outpost_2', itemType.building, 1, 'Progressive nur_allied_outpost', 'Nurgle Building: Nurglish District'),
    40461: itemData(IC.useful, 1, 'wh3_main_nur_allied_outpost_3', itemType.building, 2, 'Progressive nur_allied_outpost', 'Nurgle Building: Nurglish Colony'),
    40462: itemData(IC.useful, 1, 'wh3_main_nur_cult_1', itemType.building, 0, 'Progressive nur_cult', 'Nurgle Building: Pox Weaver'),
    40463: itemData(IC.useful, 1, 'wh3_main_nur_cult_2', itemType.building, 0, 'Progressive nur_cult', 'Nurgle Building: Pathogen Propagator'),
    40464: itemData(IC.useful, 1, 'wh3_main_nur_cult_3', itemType.building, 0, 'Progressive nur_cult', 'Nurgle Building: Plague Inducer'),
    40465: itemData(IC.useful, 1, 'wh3_main_nur_cult_4', itemType.building, 0, 'Progressive nur_cult', 'Nurgle Building: Ritual of Plague'),
    40466: itemData(IC.useful, 1, 'wh3_main_nur_cult_corruption_1', itemType.building, 0, 'Progressive nur_cult_corruption', 'Nurgle Building: Pestilence Spreader'),
    40467: itemData(IC.useful, 1, 'wh3_main_nur_cult_corruption_2', itemType.building, 0, 'Progressive nur_cult_corruption', 'Nurgle Building: Concoction Chamber'),
    40468: itemData(IC.useful, 1, 'wh3_main_nur_cult_magus', itemType.building, 0, 'Progressive nur_cult_extra', 'Nurgle Building: Cult Magus Chambers'),
    40469: itemData(IC.useful, 1, 'wh3_main_nur_cult_special', itemType.building, 0, 'Progressive nur_cult_extra', 'Nurgle Building: Ritual of Pestilence'),
    40470: itemData(IC.useful, 1, 'wh3_main_nur_cult_teleport', itemType.building, 0, 'Progressive nur_cult_extra', 'Nurgle Building: Ritual of Summoning'),
    40471: itemData(IC.useful, 1, 'wh3_main_nur_port_1', itemType.building, 0, 'Progressive nur_port', 'Nurgle Building: Infernal Harbour'),
    40472: itemData(IC.useful, 1, 'wh3_main_nur_port_2', itemType.building, 1, 'Progressive nur_port', 'Nurgle Building: Hell Port'),
    40473: itemData(IC.useful, 1, 'wh3_main_nur_port_3', itemType.building, 2, 'Progressive nur_port', 'Nurgle Building: Eye of Terror'),
    40474: itemData(IC.useful, 1, 'wh3_main_nur_resource_animals_1', itemType.building, 0, 'Progressive nur_resource_animals', 'Nurgle Building: Cultist Camp (Animals)'),
    40475: itemData(IC.useful, 1, 'wh3_main_nur_resource_animals_2', itemType.building, 1, 'Progressive nur_resource_animals', 'Nurgle Building: Cultist Outpost (Animals)'),
    40476: itemData(IC.useful, 1, 'wh3_main_nur_resource_animals_3', itemType.building, 2, 'Progressive nur_resource_animals', 'Nurgle Building: Cultist Enclave (Animals)'),
    40477: itemData(IC.useful, 1, 'wh3_main_nur_resource_dyes_1', itemType.building, 0, 'Progressive nur_resource_dyes', 'Nurgle Building: Cultist Camp (Dyes)'),
    40478: itemData(IC.useful, 1, 'wh3_main_nur_resource_dyes_2', itemType.building, 1, 'Progressive nur_resource_dyes', 'Nurgle Building: Cultist Outpost (Dyes)'),
    40479: itemData(IC.useful, 1, 'wh3_main_nur_resource_dyes_3', itemType.building, 2, 'Progressive nur_resource_dyes', 'Nurgle Building: Cultist Enclave (Dyes)'),
    40480: itemData(IC.useful, 1, 'wh3_main_nur_resource_furs_1', itemType.building, 0, 'Progressive nur_resource_furs', 'Nurgle Building: Cultist Camp (Furs)'),
    40481: itemData(IC.useful, 1, 'wh3_main_nur_resource_furs_2', itemType.building, 1, 'Progressive nur_resource_furs', 'Nurgle Building: Cultist Outpost (Furs)'),
    40482: itemData(IC.useful, 1, 'wh3_main_nur_resource_furs_3', itemType.building, 2, 'Progressive nur_resource_furs', 'Nurgle Building: Cultist Enclave (Furs)'),
    40483: itemData(IC.useful, 1, 'wh3_main_nur_resource_gems_1', itemType.building, 0, 'Progressive nur_resource_gems', 'Nurgle Building: Cultist Camp (Gems)'),
    40484: itemData(IC.useful, 1, 'wh3_main_nur_resource_gems_2', itemType.building, 1, 'Progressive nur_resource_gems', 'Nurgle Building: Cultist Outpost (Gems)'),
    40485: itemData(IC.useful, 1, 'wh3_main_nur_resource_gems_3', itemType.building, 2, 'Progressive nur_resource_gems', 'Nurgle Building: Cultist Enclave (Gems)'),
    40486: itemData(IC.useful, 1, 'wh3_main_nur_resource_gold_1', itemType.building, 0, 'Progressive nur_resource_gold', 'Nurgle Building: Cultist Camp (Gold)'),
    40487: itemData(IC.useful, 1, 'wh3_main_nur_resource_gold_2', itemType.building, 1, 'Progressive nur_resource_gold', 'Nurgle Building: Cultist Outpost (Gold)'),
    40488: itemData(IC.useful, 1, 'wh3_main_nur_resource_gold_3', itemType.building, 2, 'Progressive nur_resource_gold', 'Nurgle Building: Cultist Enclave (Gold)'),
    40489: itemData(IC.useful, 1, 'wh3_main_nur_resource_iron_1', itemType.building, 0, 'Progressive nur_resource_iron', 'Nurgle Building: Cultist Camp (Iron)'),
    40490: itemData(IC.useful, 1, 'wh3_main_nur_resource_iron_2', itemType.building, 1, 'Progressive nur_resource_iron', 'Nurgle Building: Cultist Outpost (Iron)'),
    40491: itemData(IC.useful, 1, 'wh3_main_nur_resource_iron_3', itemType.building, 2, 'Progressive nur_resource_iron', 'Nurgle Building: Cultist Enclave (Iron)'),
    40492: itemData(IC.useful, 1, 'wh3_main_nur_resource_ivory_1', itemType.building, 0, 'Progressive nur_resource_ivory', 'Nurgle Building: Cultist Camp (Tusks)'),
    40493: itemData(IC.useful, 1, 'wh3_main_nur_resource_ivory_2', itemType.building, 1, 'Progressive nur_resource_ivory', 'Nurgle Building: Cultist Outpost (Tusks)'),
    40494: itemData(IC.useful, 1, 'wh3_main_nur_resource_ivory_3', itemType.building, 2, 'Progressive nur_resource_ivory', 'Nurgle Building: Cultist Enclave (Tusks)'),
    40495: itemData(IC.useful, 1, 'wh3_main_nur_resource_marble_1', itemType.building, 0, 'Progressive nur_resource_marble', 'Nurgle Building: Cultist Camp (Marble)'),
    40496: itemData(IC.useful, 1, 'wh3_main_nur_resource_marble_2', itemType.building, 1, 'Progressive nur_resource_marble', 'Nurgle Building: Cultist Outpost (Marble)'),
    40497: itemData(IC.useful, 1, 'wh3_main_nur_resource_marble_3', itemType.building, 2, 'Progressive nur_resource_marble', 'Nurgle Building: Cultist Enclave (Marble)'),
    40498: itemData(IC.useful, 1, 'wh3_main_nur_resource_medicine_1', itemType.building, 0, 'Progressive nur_resource_medicine', 'Nurgle Building: Cultist Camp (Medicine)'),
    40499: itemData(IC.useful, 1, 'wh3_main_nur_resource_medicine_2', itemType.building, 1, 'Progressive nur_resource_medicine', 'Nurgle Building: Cultist Outpost (Medicine)'),
    40500: itemData(IC.useful, 1, 'wh3_main_nur_resource_medicine_3', itemType.building, 2, 'Progressive nur_resource_medicine', 'Nurgle Building: Cultist Enclave (Medicine)'),
    40501: itemData(IC.useful, 1, 'wh3_main_nur_resource_obsidian_1', itemType.building, 0, 'Progressive nur_resource_obsidian', 'Nurgle Building: Cultist Camp (Obsidian)'),
    40502: itemData(IC.useful, 1, 'wh3_main_nur_resource_obsidian_2', itemType.building, 1, 'Progressive nur_resource_obsidian', 'Nurgle Building: Cultist Outpost (Obsidian)'),
    40503: itemData(IC.useful, 1, 'wh3_main_nur_resource_obsidian_3', itemType.building, 2, 'Progressive nur_resource_obsidian', 'Nurgle Building: Cultist Enclave (Obsidian)'),
    40504: itemData(IC.useful, 1, 'wh3_main_nur_resource_pasture_1', itemType.building, 0, 'Progressive nur_resource_pasture', 'Nurgle Building: Cultist Camp (Pasture)'),
    40505: itemData(IC.useful, 1, 'wh3_main_nur_resource_pasture_2', itemType.building, 1, 'Progressive nur_resource_pasture', 'Nurgle Building: Cultist Outpost (Pasture)'),
    40506: itemData(IC.useful, 1, 'wh3_main_nur_resource_pasture_3', itemType.building, 2, 'Progressive nur_resource_pasture', 'Nurgle Building: Cultist Enclave (Pasture)'),
    40507: itemData(IC.useful, 1, 'wh3_main_nur_resource_pottery_1', itemType.building, 0, 'Progressive nur_resource_pottery', 'Nurgle Building: Cultist Camp (Pottery)'),
    40508: itemData(IC.useful, 1, 'wh3_main_nur_resource_pottery_2', itemType.building, 1, 'Progressive nur_resource_pottery', 'Nurgle Building: Cultist Outpost (Pottery)'),
    40509: itemData(IC.useful, 1, 'wh3_main_nur_resource_pottery_3', itemType.building, 2, 'Progressive nur_resource_pottery', 'Nurgle Building: Cultist Enclave (Pottery)'),
    40510: itemData(IC.useful, 1, 'wh3_main_nur_resource_salt_1', itemType.building, 0, 'Progressive nur_resource_salt', 'Nurgle Building: Cultist Camp (Salt)'),
    40511: itemData(IC.useful, 1, 'wh3_main_nur_resource_salt_2', itemType.building, 1, 'Progressive nur_resource_salt', 'Nurgle Building: Cultist Outpost (Salt)'),
    40512: itemData(IC.useful, 1, 'wh3_main_nur_resource_salt_3', itemType.building, 2, 'Progressive nur_resource_salt', 'Nurgle Building: Cultist Enclave (Salt)'),
    40513: itemData(IC.useful, 1, 'wh3_main_nur_resource_spices_1', itemType.building, 0, 'Progressive nur_resource_spices', 'Nurgle Building: Cultist Camp (Spices)'),
    40514: itemData(IC.useful, 1, 'wh3_main_nur_resource_spices_2', itemType.building, 1, 'Progressive nur_resource_spices', 'Nurgle Building: Cultist Outpost (Spices)'),
    40515: itemData(IC.useful, 1, 'wh3_main_nur_resource_spices_3', itemType.building, 2, 'Progressive nur_resource_spices', 'Nurgle Building: Cultist Enclave (Spices)'),
    40516: itemData(IC.useful, 1, 'wh3_main_nur_resource_wine_1', itemType.building, 0, 'Progressive nur_resource_wine', 'Nurgle Building: Cultist Camp (Wine)'),
    40517: itemData(IC.useful, 1, 'wh3_main_nur_resource_wine_2', itemType.building, 1, 'Progressive nur_resource_wine', 'Nurgle Building: Cultist Outpost (Wine)'),
    40518: itemData(IC.useful, 1, 'wh3_main_nur_resource_wine_3', itemType.building, 2, 'Progressive nur_resource_wine', 'Nurgle Building: Cultist Enclave (Wine)'),
    40519: itemData(IC.useful, 1, 'wh3_main_nur_resource_wood_1', itemType.building, 0, 'Progressive nur_resource_wood', 'Nurgle Building: Cultist Camp (Wood)'),
    40520: itemData(IC.useful, 1, 'wh3_main_nur_resource_wood_2', itemType.building, 1, 'Progressive nur_resource_wood', 'Nurgle Building: Cultist Outpost (Wood)'),
    40521: itemData(IC.useful, 1, 'wh3_main_nur_resource_wood_3', itemType.building, 2, 'Progressive nur_resource_wood', 'Nurgle Building: Cultist Enclave (Wood)'),
    40522: itemData(IC.useful, 1, 'wh3_main_nur_settlement_major_1', itemType.building, 0, 'Progressive nur_settlement_major', 'Nurgle Building: Withering Roots'),
    40523: itemData(IC.useful, 1, 'wh3_main_nur_settlement_major_2', itemType.building, 1, 'Progressive nur_settlement_major', 'Nurgle Building: Tumid Hollow'),
    40524: itemData(IC.useful, 1, 'wh3_main_nur_settlement_major_3', itemType.building, 2, 'Progressive nur_settlement_major', 'Nurgle Building: Unclean Copse'),
    40525: itemData(IC.useful, 1, 'wh3_main_nur_settlement_major_4', itemType.building, 3, 'Progressive nur_settlement_major', 'Nurgle Building: Diseased Grove'),
    40526: itemData(IC.useful, 1, 'wh3_main_nur_settlement_major_5', itemType.building, 4, 'Progressive nur_settlement_major', 'Nurgle Building: Great Blight Oak'),
    40527: itemData(IC.useful, 1, 'wh3_main_nur_settlement_minor_1', itemType.building, 0, 'Progressive nur_settlement_minor', 'Nurgle Building: Nurgle Nest'),
    40528: itemData(IC.useful, 1, 'wh3_main_nur_settlement_minor_2', itemType.building, 1, 'Progressive nur_settlement_minor', 'Nurgle Building: Nurgle Hollow'),
    40529: itemData(IC.useful, 1, 'wh3_main_nur_settlement_minor_3', itemType.building, 2, 'Progressive nur_settlement_minor', 'Nurgle Building: Nurgle Thicket')
}

techs: dict[int, itemData] = {
    40846: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_1', itemType.tech, 1, 'Progressive tech_nur_faction', 'Nurgle Tech: Pestiferous Life'),
    40847: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_2', itemType.tech, 2, 'Progressive tech_nur_faction', 'Nurgle Tech: Creeping Corruption'),
    40849: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_5', itemType.tech, 1, 'Progressive tech_nur_faction', 'Nurgle Tech: Maddening Crowds'),
    40848: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_4', itemType.tech, 2, 'Progressive tech_nur_faction', 'Nurgle Tech: Carcinogenic'),
    40843: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_3', itemType.tech, 3, 'Progressive tech_nur_faction', 'Nurgle Tech: Foetid Corpses'),
    40837: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_6', itemType.tech, 4, 'Progressive tech_nur_faction', "Nurgle Tech: Nurgle's Blessed"),
    40838: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_7', itemType.tech, 4, 'Progressive tech_nur_faction', 'Nurgle Tech: Despicable Rivals'),
    40830: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_8', itemType.tech, 5, 'Progressive tech_nur_faction', 'Nurgle Tech: Contagious Horde'),
    40827: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_9', itemType.tech, 6, 'Progressive tech_nur_faction', 'Nurgle Tech: Locus of Virulence'),
    40826: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_10', itemType.tech, 6, 'Progressive tech_nur_faction', 'Nurgle Tech: Fever Incubation'),
    40819: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_11', itemType.tech, 7, 'Progressive tech_nur_faction', 'Nurgle Tech: Plague Sight'),
    40820: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_12', itemType.tech, 7, 'Progressive tech_nur_faction', 'Nurgle Tech: Tumorous Squirt'),
    40817: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_13', itemType.tech, 8, 'Progressive tech_nur_faction', 'Nurgle Tech: Cyst Growth'),
    40818: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_14', itemType.tech, 8, 'Progressive tech_nur_faction', 'Nurgle Tech: Plague Incubation'),
    40807: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_20', itemType.tech, 9, 'Progressive tech_nur_faction', 'Nurgle Tech: Fattening Seeds'),
    40808: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_26', itemType.tech, 9, 'Progressive tech_nur_faction', 'Nurgle Tech: Metastasis'),
    40801: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_21', itemType.tech, 10, 'Progressive tech_nur_faction', 'Nurgle Tech: Come to Grandfather'),
    40802: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_28', itemType.tech, 10, 'Progressive tech_nur_faction', 'Nurgle Tech: Festering'),
    40806: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_19', itemType.tech, 11, 'Progressive tech_nur_faction', 'Nurgle Tech: Eye Rot Incubation'),
    40809: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_27', itemType.tech, 11, 'Progressive tech_nur_faction', 'Nurgle Tech: Soldiers of Pestilence'),
    40812: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_17', itemType.tech, 12, 'Progressive tech_nur_faction', 'Nurgle Tech: Spore Diffusion'),
    40813: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_18', itemType.tech, 12, 'Progressive tech_nur_faction', 'Nurgle Tech: Favourite Children'),
    40814: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_24', itemType.tech, 12, 'Progressive tech_nur_faction', 'Nurgle Tech: Temperate Strain'),
    40815: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_25', itemType.tech, 12, 'Progressive tech_nur_faction', 'Nurgle Tech: Gates of Rot'),
    40821: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_15', itemType.tech, 13, 'Progressive tech_nur_faction', 'Nurgle Tech: Rot Incubation'),
    40822: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_16', itemType.tech, 13, 'Progressive tech_nur_faction', 'Nurgle Tech: Preferred Strain'),
    40823: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_22', itemType.tech, 13, 'Progressive tech_nur_faction', 'Nurgle Tech: Sickening Winds'),
    40824: itemData(IC.useful, 1, 'wh3_main_tech_nur_growth_23', itemType.tech, 13, 'Progressive tech_nur_faction', 'Nurgle Tech: Curse of the Slug'),

    40825: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_22', itemType.tech, 1, 'Progressive tech_nur_faction', 'Nurgle Tech: Fecundity'),
    40828: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_15', itemType.tech, 2, 'Progressive tech_nur_faction', 'Nurgle Tech: Specimen Collection'),
    40833: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_16', itemType.tech, 3, 'Progressive tech_nur_faction', 'Nurgle Tech: Contaminating Claws'),
    40835: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_18', itemType.tech, 3, 'Progressive tech_nur_faction', 'Nurgle Tech: Ravenous Tadpoles'),
    40841: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_19', itemType.tech, 4, 'Progressive tech_nur_faction', 'Nurgle Tech: Fleshy Growths'),
    40842: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_20', itemType.tech, 4, 'Progressive tech_nur_faction', 'Nurgle Tech: Overcoming Resistance'),
    40845: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_21', itemType.tech, 5, 'Progressive tech_nur_faction', 'Nurgle Tech: Eye Crusts'),

    40829: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_8', itemType.tech, 2, 'Progressive tech_nur_military', 'Nurgle Tech: Monstrous Abundance'),
    40832: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_11', itemType.tech, 3, 'Progressive tech_nur_military', 'Nurgle Tech: Children of Nurgle'),
    40836: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_9', itemType.tech, 3, 'Progressive tech_nur_military', 'Nurgle Tech: Strain Resistance'),
    40839: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_12', itemType.tech, 4, 'Progressive tech_nur_military', 'Nurgle Tech: Humanity is a Virus'),
    40840: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_13', itemType.tech, 4, 'Progressive tech_nur_military', 'Nurgle Tech: Highly Infectious'),
    40844: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_14', itemType.tech, 5, 'Progressive tech_nur_military', 'Nurgle Tech: Revel in Malady'),
    40834: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_17', itemType.tech, 6, 'Progressive tech_nur_military', 'Nurgle Tech: Avatars of the Plague God'),

    40816: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_7', itemType.tech, 2, 'Progressive tech_nur_military', 'Nurgle Tech: Plague Beasts'),
    40810: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_5', itemType.tech, 3, 'Progressive tech_nur_military', 'Nurgle Tech: Rancid Boils'),
    40811: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_6', itemType.tech, 3, 'Progressive tech_nur_military', 'Nurgle Tech: Pox Tally'),
    40803: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_2', itemType.tech, 4, 'Progressive tech_nur_military', 'Nurgle Tech: Leprous Flesh'),
    40805: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_4', itemType.tech, 4, 'Progressive tech_nur_military', 'Nurgle Tech: The Touch'),
    40800: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_1', itemType.tech, 5, 'Progressive tech_nur_military', 'Nurgle Tech: Viral Incubation'),
    40804: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_3', itemType.tech, 6, 'Progressive tech_nur_military', 'Nurgle Tech: Plague Paragon'),
    40831: itemData(IC.useful, 1, 'wh3_main_tech_nur_decay_10', itemType.tech, 6, 'Progressive tech_nur_military', 'Nurgle Tech: Growing Buboes'),
}

progUnits: dict[int, itemData] = {
    41200: itemData(IC.useful, 4, "Progressive nur_inf", itemType.unit, 4, "", "Progressive Nurgle Unit: Infantry"),
    41202: itemData(IC.useful, 4, "Progressive nur_cav", itemType.unit, 4, "", "Progressive Nurgle Unit: Cavalry"),
    41204: itemData(IC.useful, 1, "Progressive nur_veh", itemType.unit, 1, "", "Progressive Nurgle Unit: Chariot"),
    41205: itemData(IC.useful, 6, "Progressive nur_bst", itemType.unit, 6, "", "Progressive Nurgle Unit: Beast"),
    41206: itemData(IC.useful, 1, "Progressive nur_hro", itemType.unit, 1, "", "Progressive Nurgle Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    41300: itemData(IC.useful, 2, 'Progressive nur_garrison', itemType.building, 2, None, 'Progressive Nurgle Building: Garrison'),
    41301: itemData(IC.useful, 1, 'Progressive nur_walls', itemType.building, 1, None, 'Progressive Nurgle Building: Walls'),
    41302: itemData(IC.useful, 2, 'Progressive nur_walls', itemType.building, 2, None, 'Progressive Nurgle Building: Walls'),
    41303: itemData(IC.useful, 3, 'Progressive nur_walls', itemType.building, 3, None, 'Progressive Nurgle Building: Walls'),
    41304: itemData(IC.useful, 1, 'Progressive special_the_gallows', itemType.building, 1, None, 'Progressive Nurgle Building: Special The Gallows'),
    41305: itemData(IC.useful, 1, 'Progressive foreign_slot_discovery_nur', itemType.building, 1, None, 'Progressive Nurgle Building: Foreign Slot Discovery Nur'),
    41306: itemData(IC.useful, 2, 'Progressive foreign_slot_discovery_nur', itemType.building, 2, None, 'Progressive Nurgle Building: Foreign Slot Discovery Nur'),
    41307: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_nur', itemType.building, 3, None, 'Progressive Nurgle Building: Foreign Slot Discovery Nur'),
    41308: itemData(IC.useful, 6, 'Progressive nur_1', itemType.building, 6, None, 'Progressive Nurgle Building: 1'),
    41309: itemData(IC.useful, 6, 'Progressive nur_2', itemType.building, 6, None, 'Progressive Nurgle Building: 2'),
    41310: itemData(IC.useful, 6, 'Progressive nur_3', itemType.building, 6, None, 'Progressive Nurgle Building: 3'),
    41311: itemData(IC.useful, 8, 'Progressive nur_4', itemType.building, 8, None, 'Progressive Nurgle Building: 4'),
    41312: itemData(IC.useful, 8, 'Progressive nur_5', itemType.building, 8, None, 'Progressive Nurgle Building: 5'),
    41313: itemData(IC.useful, 4, 'Progressive nur_6', itemType.building, 4, None, 'Progressive Nurgle Building: 6'),
    41314: itemData(IC.useful, 5, 'Progressive nur_7', itemType.building, 5, None, 'Progressive Nurgle Building: 7'),
    41315: itemData(IC.useful, 4, 'Progressive nur_8', itemType.building, 4, None, 'Progressive Nurgle Building: 8'),
    41316: itemData(IC.useful, 2, 'Progressive nur_9', itemType.building, 2, None, 'Progressive Nurgle Building: 9'),
    41317: itemData(IC.useful, 3, 'Progressive nur_allied_outpost', itemType.building, 3, None, 'Progressive Nurgle Building: Allied Outpost'),
    41318: itemData(IC.useful, 1, 'Progressive nur_cult', itemType.building, 1, None, 'Progressive Nurgle Building: Cult'),
    41319: itemData(IC.useful, 1, 'Progressive nur_cult_corruption', itemType.building, 1, None, 'Progressive Nurgle Building: Cult Corruption'),
    41320: itemData(IC.useful, 1, 'Progressive nur_cult_extra', itemType.building, 1, None, 'Progressive Nurgle Building: Cult Extra'),
    41321: itemData(IC.useful, 3, 'Progressive nur_port', itemType.building, 3, None, 'Progressive Nurgle Building: Port'),
    41322: itemData(IC.useful, 3, 'Progressive nur_resource_animals', itemType.building, 3, None, 'Progressive Nurgle Building: Animals'),
    41323: itemData(IC.useful, 3, 'Progressive nur_resource_dyes', itemType.building, 3, None, 'Progressive Nurgle Building: Dyes'),
    41324: itemData(IC.useful, 3, 'Progressive nur_resource_furs', itemType.building, 3, None, 'Progressive Nurgle Building: Furs'),
    41325: itemData(IC.useful, 3, 'Progressive nur_resource_gems', itemType.building, 3, None, 'Progressive Nurgle Building: Gems'),
    41326: itemData(IC.useful, 3, 'Progressive nur_resource_gold', itemType.building, 3, None, 'Progressive Nurgle Building: Gold'),
    41327: itemData(IC.useful, 3, 'Progressive nur_resource_iron', itemType.building, 3, None, 'Progressive Nurgle Building: Iron'),
    41328: itemData(IC.useful, 3, 'Progressive nur_resource_ivory', itemType.building, 3, None, 'Progressive Nurgle Building: Ivory'),
    41329: itemData(IC.useful, 3, 'Progressive nur_resource_marble', itemType.building, 3, None, 'Progressive Nurgle Building: Marble'),
    41330: itemData(IC.useful, 3, 'Progressive nur_resource_medicine', itemType.building, 3, None, 'Progressive Nurgle Building: Medicine'),
    41331: itemData(IC.useful, 3, 'Progressive nur_resource_obsidian', itemType.building, 3, None, 'Progressive Nurgle Building: Obsidian'),
    41332: itemData(IC.useful, 3, 'Progressive nur_resource_pasture', itemType.building, 3, None, 'Progressive Nurgle Building: Pasture'),
    41333: itemData(IC.useful, 3, 'Progressive nur_resource_pottery', itemType.building, 3, None, 'Progressive Nurgle Building: Pottery'),
    41334: itemData(IC.useful, 3, 'Progressive nur_resource_salt', itemType.building, 3, None, 'Progressive Nurgle Building: Salt'),
    41335: itemData(IC.useful, 3, 'Progressive nur_resource_spices', itemType.building, 3, None, 'Progressive Nurgle Building: Spices'),
    41336: itemData(IC.useful, 3, 'Progressive nur_resource_wine', itemType.building, 3, None, 'Progressive Nurgle Building: Wine'),
    41337: itemData(IC.useful, 3, 'Progressive nur_resource_wood', itemType.building, 3, None, 'Progressive Nurgle Building: Wood'),
    41338: itemData(IC.useful, 5, 'Progressive nur_settlement_major', itemType.building, 5, None, 'Progressive Nurgle Building: Settlement Major'),
    41339: itemData(IC.useful, 3, 'Progressive nur_settlement_minor', itemType.building, 3, None, 'Progressive Nurgle Building: Settlement Minor')
}

progTechs: dict[int, itemData] = {
    41400: itemData(IC.useful, 13, "Progressive tech_nur_faction", itemType.tech, 13, None, "Progressive Nurgle Tech: Faction"),
    41401: itemData(IC.useful, 6, "Progressive tech_nur_military", itemType.tech, 6, None, "Progressive Nurgle Tech: Military"),
}

special: dict[int, itemData] = {

}