from BaseClasses import ItemClassification as IC
from worlds.tww3.itemTypes import itemType, itemData

# @formatter:off
units: dict[int, itemData] = {
    26000: itemData(IC.useful, 1, 'wh3_main_ogr_inf_gnoblars_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Gnoblars'),
    26001: itemData(IC.useful, 1, 'wh3_main_ogr_inf_ogres_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Ogre Bulls'),
    26002: itemData(IC.useful, 1, 'wh3_dlc26_ogr_inf_pigback_riders', itemType.unit, 2, 'Progressive ogr_inf', 'Ogre Unit: Pigback Riders'),
    26003: itemData(IC.useful, 1, 'wh3_main_ogr_inf_ogres_2', itemType.unit, 2, 'Progressive ogr_inf', 'Ogre Unit: Ogre Bulls (Ironfists)'),
    26004: itemData(IC.useful, 1, 'wh3_main_ogr_inf_ogres_1', itemType.unit, 2, 'Progressive ogr_inf', 'Ogre Unit: Ogre Bulls (Dual Weapons)'),
    26005: itemData(IC.useful, 1, 'wh3_main_ogr_inf_ironguts_0', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Ironguts'),
    26006: itemData(IC.useful, 1, 'wh3_main_ogr_mon_gorgers_0', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Gorgers'),
    26007: itemData(IC.useful, 1, 'wh3_dlc26_ogr_mon_yhetees', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Yhetees'),
    26008: itemData(IC.useful, 1, 'wh3_main_ogr_inf_maneaters_0', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Maneaters'),
    26009: itemData(IC.useful, 1, 'wh3_main_ogr_inf_maneaters_2', itemType.unit, 4, 'Progressive ogr_inf', 'Ogre Unit: Maneaters (Great Weapons)'),
    26010: itemData(IC.useful, 1, 'wh3_main_ogr_inf_maneaters_1', itemType.unit, 4, 'Progressive ogr_inf', 'Ogre Unit: Maneaters (Ironfists)'),
    26011: itemData(IC.useful, 1, 'wh3_dlc26_ogr_inf_golgfags_maneaters', itemType.unit, 4, 'Progressive ogr_inf', "Ogre Unit: Golgfag's Maneaters"),
    26012: itemData(IC.useful, 1, 'wh3_main_ogr_inf_gnoblars_flingers', itemType.unit, 1, 'Progressive ogr_rng', 'Ogre Unit: Gnoblar Flingers'),
    26013: itemData(IC.useful, 1, 'wh3_main_ogr_inf_gnoblars_1', itemType.unit, 2, 'Progressive ogr_inf', 'Ogre Unit: Gnoblar Trappers'),
    26014: itemData(IC.useful, 1, 'wh3_main_ogr_inf_leadbelchers_0', itemType.unit, 3, 'Progressive ogr_rng', 'Ogre Unit: Leadbelchers'),
    26015: itemData(IC.useful, 1, 'wh3_main_ogr_inf_maneaters_3', itemType.unit, 4, 'Progressive ogr_rng', 'Ogre Unit: Maneaters (Ogre Pistols)'),
    26016: itemData(IC.useful, 1, 'wh3_main_ogr_cav_mournfang_cavalry_0', itemType.unit, 1, 'Progressive ogr_cav', 'Ogre Unit: Mournfang Cavalry'),
    26017: itemData(IC.useful, 1, 'wh3_main_ogr_cav_mournfang_cavalry_2', itemType.unit, 2, 'Progressive ogr_cav', 'Ogre Unit: Mournfang Cavalry (Great Weapons)'),
    26018: itemData(IC.useful, 1, 'wh3_main_ogr_cav_mournfang_cavalry_1', itemType.unit, 2, 'Progressive ogr_cav', 'Ogre Unit: Mournfang Cavalry (Ironfists)'),
    26019: itemData(IC.useful, 1, 'wh3_main_ogr_cav_crushers_1', itemType.unit, 3, 'Progressive ogr_cav', 'Ogre Unit: Crushers (Great Weapons)'),
    26020: itemData(IC.useful, 1, 'wh3_main_ogr_cav_crushers_0', itemType.unit, 3, 'Progressive ogr_cav', 'Ogre Unit: Crushers (Ironfists)'),
    26021: itemData(IC.useful, 1, 'wh3_main_ogr_veh_gnoblar_scraplauncher_0', itemType.unit, 1, 'Progressive ogr_art', 'Ogre Unit: Gnoblar Scraplauncher'),
    26022: itemData(IC.useful, 1, 'wh3_main_ogr_veh_ironblaster_0', itemType.unit, 2, 'Progressive ogr_art', 'Ogre Unit: Ironblaster'),
    26023: itemData(IC.useful, 1, 'wh3_dlc26_ogr_mon_blood_vultures', itemType.unit, 1, 'Progressive ogr_bst', 'Ogre Unit: Blood Vultures'),
    26024: itemData(IC.useful, 1, 'wh3_main_ogr_mon_sabretusk_pack_0', itemType.unit, 1, 'Progressive ogr_bst', 'Ogre Unit: Sabretusk Pack'),
    26025: itemData(IC.useful, 1, 'wh3_main_ogr_mon_giant_0', itemType.unit, 2, 'Progressive ogr_bst', 'Ogre Unit: Giant'),
    26026: itemData(IC.useful, 1, 'wh3_main_ogr_mon_stonehorn_0', itemType.unit, 3, 'Progressive ogr_bst', 'Ogre Unit: Stonehorn'),
    26027: itemData(IC.useful, 1, 'wh3_dlc26_ogr_mon_thundertusk', itemType.unit, 4, 'Progressive ogr_bst', 'Ogre Unit: Thundertusk'),
    26028: itemData(IC.useful, 1, 'wh3_main_ogr_mon_stonehorn_1', itemType.unit, 4, 'Progressive ogr_bst', 'Ogre Unit: Stonehorn (Harpoon Launcher)'),
    26029: itemData(IC.useful, 1, 'wh3_dlc26_ogr_cha_butcher_heavens', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Butcher (Heavens)'),
    26030: itemData(IC.useful, 1, 'wh3_dlc26_ogr_cha_butcher_death', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Butcher (Death)'),
    26031: itemData(IC.useful, 1, 'wh3_main_ogr_cha_butcher_great_maw_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Butcher (Great Maw)'),
    26032: itemData(IC.useful, 1, 'wh3_main_ogr_cha_butcher_beasts_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Butcher (Beasts)'),
    26033: itemData(IC.useful, 1, 'wh3_main_ogr_cha_hunter_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Hunter'),
    26034: itemData(IC.useful, 1, 'wh3_main_ogr_cha_firebelly_0', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Firebelly'),
    26035: itemData(IC.useful, 1, 'wh3_dlc26_ogr_cha_bruiser', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Bruiser'),
    26036: itemData(IC.useful, 1, 'wh3_twa10_ogr_inf_gnoblars_ror', itemType.unit, 1, 'Progressive ogr_inf', 'Ogre Unit: Boglars of the Mad Marshes (Gnoblars)'),
    26037: itemData(IC.useful, 1, 'wh3_twa08_ogr_mon_stonehorn_0_ror', itemType.unit, 4, 'Progressive ogr_bst', 'Ogre Unit: The Snowhorn of Mourn (Stonehorn)'),
    26038: itemData(IC.useful, 1, 'wh3_twa07_ogr_cav_crushers_ror_0', itemType.unit, 3, 'Progressive ogr_cav', 'Ogre Unit: Sky-Striders (Crushers - Great Weapons)'),
    26039: itemData(IC.useful, 1, 'wh3_twa06_ogr_inf_maneaters_ror_0', itemType.unit, 4, 'Progressive ogr_rng', 'Ogre Unit: Powder-Guts (Maneaters - Ogre Pistols)'),
    26040: itemData(IC.useful, 1, 'wh3_dlc26_ogr_mon_yhetees_ror', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Amblepeak Greybacks (Yhetees)'),
    26041: itemData(IC.useful, 1, 'wh3_dlc26_ogr_inf_pigback_riders_ror', itemType.unit, 2, 'Progressive ogr_inf', 'Ogre Unit: Piggyback Knights (Pigback Riders)'),
    26042: itemData(IC.useful, 1, 'wh3_dlc26_ogr_inf_eshin_maneater_ror', itemType.unit, 3, 'Progressive ogr_inf', 'Ogre Unit: Eshin Maneater')
}

buildings: dict[int, itemData] = {
    26400: itemData(IC.useful, 1, 'wh3_dlc26_ogr_camp_gnoblars_1', itemType.building, 0, 'Progressive ogr_camp_gnoblars', 'Ogre Camp Building: Pig-Jousting Fields'),
    26401: itemData(IC.useful, 1, 'wh3_dlc26_ogr_camp_gnoblars_2', itemType.building, 1, 'Progressive ogr_camp_gnoblars', 'Ogre Camp Building: Trapper Huts'),
    26402: itemData(IC.useful, 1, 'wh3_dlc26_ogr_camp_gnoblars_3', itemType.building, 2, 'Progressive ogr_camp_gnoblars', 'Ogre Camp Building: Cast-Off Workyards'),
    26403: itemData(IC.useful, 1, 'wh3_dlc26_ogr_gnoblars_1', itemType.building, 0, 'Progressive ogr_gnoblars', 'Ogre Building: Pig-Jousting Fields'),
    26404: itemData(IC.useful, 1, 'wh3_dlc26_ogr_gnoblars_2', itemType.building, 1, 'Progressive ogr_gnoblars', 'Ogre Building: Trapper Huts'),
    26405: itemData(IC.useful, 1, 'wh3_dlc26_ogr_gnoblars_3', itemType.building, 2, 'Progressive ogr_gnoblars', 'Ogre Building: Cast-Off Workyards'),
    26407: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_ogr_1', itemType.building, 0, 'Progressive foreign_slot_discovery_ogr', 'Ogre Building: Big Rat-Trap'),
    26408: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_ogr_2', itemType.building, 1, 'Progressive foreign_slot_discovery_ogr', 'Ogre Building: Refined Rat Trap'),
    26409: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_ogr_3', itemType.building, 2, 'Progressive foreign_slot_discovery_ogr', 'Ogre Building: Rodent Lures'),
    26410: itemData(IC.useful, 1, 'wh3_main_ogr_allied_outpost_1', itemType.building, 0, 'Progressive ogr_allied_outpost', 'Ogre Building: Ogre Outpost'),
    26411: itemData(IC.useful, 1, 'wh3_main_ogr_allied_outpost_2', itemType.building, 1, 'Progressive ogr_allied_outpost', 'Ogre Building: Ogre District'),
    26412: itemData(IC.useful, 1, 'wh3_main_ogr_allied_outpost_3', itemType.building, 2, 'Progressive ogr_allied_outpost', 'Ogre Building: Ogre Colony'),
    26413: itemData(IC.useful, 1, 'wh3_main_ogr_barracks_1', itemType.building, 0, 'Progressive ogr_barracks', 'Ogre Building: Bull Pen'),
    26414: itemData(IC.useful, 1, 'wh3_main_ogr_barracks_2', itemType.building, 1, 'Progressive ogr_barracks', 'Ogre Building: Weapon Pile'),
    26415: itemData(IC.useful, 1, 'wh3_main_ogr_barracks_3', itemType.building, 2, 'Progressive ogr_barracks', 'Ogre Building: Bestest Weapon Pile'),
    26416: itemData(IC.useful, 1, 'wh3_main_ogr_camp_barracks_1', itemType.building, 0, 'Progressive ogr_camp_barracks', 'Ogre Camp Building: Bull Pen'),
    26417: itemData(IC.useful, 1, 'wh3_main_ogr_camp_barracks_2', itemType.building, 1, 'Progressive ogr_camp_barracks', 'Ogre Camp Building: Weapon Pile'),
    26418: itemData(IC.useful, 1, 'wh3_main_ogr_camp_barracks_3', itemType.building, 2, 'Progressive ogr_camp_barracks', 'Ogre Camp Building: Bestest Weapon Pile'),
    26419: itemData(IC.useful, 1, 'wh3_main_ogr_camp_cav_1', itemType.building, 0, 'Progressive ogr_camp_cav', 'Ogre Camp Building: Pack Cave'),
    26420: itemData(IC.useful, 1, 'wh3_main_ogr_camp_cav_2', itemType.building, 1, 'Progressive ogr_camp_cav', 'Ogre Camp Building: Gorger Cave'),
    26421: itemData(IC.useful, 1, 'wh3_main_ogr_camp_cav_3', itemType.building, 2, 'Progressive ogr_camp_cav', 'Ogre Camp Building: Giant Pens'),
    26422: itemData(IC.useful, 1, 'wh3_main_ogr_camp_cav_4', itemType.building, 3, 'Progressive ogr_camp_cav', 'Ogre Camp Building: Boulder Fields'),
    26423: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_replenishment_1', itemType.building, 0, 'Progressive ogr_camp_defence_replenishment', 'Ogre Camp Building: Camp Pot'),
    26424: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_replenishment_2', itemType.building, 1, 'Progressive ogr_camp_defence_replenishment', 'Ogre Camp Building: Camp Bowl'),
    26425: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_replenishment_3', itemType.building, 2, 'Progressive ogr_camp_defence_replenishment', 'Ogre Camp Building: Huge Cauldron'),
    #26426: ItemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_replenishment_4', ItemType.building, 3, 'Progressive ogr_camp_defence_replenishment', 'Ogre Camp Building: Camp Boiler'),
    #26427: ItemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_replenishment_5', ItemType.building, 4, 'Progressive ogr_camp_defence_replenishment', 'Ogre Camp Building: Huge Cauldron'),
    26428: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_upkeep_1', itemType.building, 0, 'Progressive ogr_camp_defence_upkeep', "Ogre Camp Building: Gnoblars' Box"),
    26429: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_upkeep_2', itemType.building, 1, 'Progressive ogr_camp_defence_upkeep', "Ogre Camp Building: Trader's Tent"),
    26430: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_upkeep_3', itemType.building, 2, 'Progressive ogr_camp_defence_upkeep', "Ogre Camp Building: Trader's Hut"),
    26431: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_upkeep_4', itemType.building, 3, 'Progressive ogr_camp_defence_upkeep', 'Ogre Camp Building: Meat Market'),
    26432: itemData(IC.useful, 1, 'wh3_main_ogr_camp_defence_upkeep_5', itemType.building, 4, 'Progressive ogr_camp_defence_upkeep', 'Ogre Camp Building: Flesh Bazaar'),
    26433: itemData(IC.useful, 1, 'wh3_main_ogr_camp_growth_1', itemType.building, 0, 'Progressive ogr_camp_growth', 'Ogre Camp Building: Loot Pile'),
    26434: itemData(IC.useful, 1, 'wh3_main_ogr_camp_growth_2', itemType.building, 1, 'Progressive ogr_camp_growth', 'Ogre Camp Building: Loot Hoard'),
    26435: itemData(IC.useful, 1, 'wh3_main_ogr_camp_growth_3', itemType.building, 2, 'Progressive ogr_camp_growth', 'Ogre Camp Building: Bounty Tent'),
    26436: itemData(IC.useful, 1, 'wh3_main_ogr_camp_growth_4', itemType.building, 3, 'Progressive ogr_camp_growth', 'Ogre Camp Building: Bounty Hut'),
    26437: itemData(IC.useful, 1, 'wh3_main_ogr_camp_growth_5', itemType.building, 4, 'Progressive ogr_camp_growth', 'Ogre Camp Building: Bounty Shack'),
    26438: itemData(IC.useful, 1, 'wh3_main_ogr_camp_gunpowder_1', itemType.building, 0, 'Progressive ogr_camp_gunpowder', 'Ogre Camp Building: Mineral Seam'),
    26439: itemData(IC.useful, 1, 'wh3_main_ogr_camp_gunpowder_2', itemType.building, 1, 'Progressive ogr_camp_gunpowder', 'Ogre Camp Building: Camp Oven'),
    26440: itemData(IC.useful, 1, 'wh3_main_ogr_camp_gunpowder_3', itemType.building, 2, 'Progressive ogr_camp_gunpowder', 'Ogre Camp Building: Camp Furnace'),
    26441: itemData(IC.useful, 1, 'wh3_main_ogr_camp_heavy_cav_1', itemType.building, 0, 'Progressive ogr_camp_heavy_cav', 'Ogre Camp Building: Mournfang Cage'),
    26442: itemData(IC.useful, 1, 'wh3_main_ogr_camp_heavy_cav_2', itemType.building, 1, 'Progressive ogr_camp_heavy_cav', 'Ogre Camp Building: Favoured Mournfang Cage'),
    26443: itemData(IC.useful, 1, 'wh3_main_ogr_camp_heavy_cav_3', itemType.building, 2, 'Progressive ogr_camp_heavy_cav', 'Ogre Camp Building: Big Crusher Rock'),
    26444: itemData(IC.useful, 1, 'wh3_main_ogr_camp_hunting_1', itemType.building, 0, 'Progressive ogr_camp_hunting', 'Ogre Camp Building: Feast Table'),
    26445: itemData(IC.useful, 1, 'wh3_main_ogr_camp_hunting_2', itemType.building, 1, 'Progressive ogr_camp_hunting', 'Ogre Camp Building: Feast Yurt'),
    26446: itemData(IC.useful, 1, 'wh3_main_ogr_camp_hunting_3', itemType.building, 2, 'Progressive ogr_camp_hunting', 'Ogre Camp Building: Feast Tent'),
    26447: itemData(IC.useful, 1, 'wh3_main_ogr_camp_hunting_4', itemType.building, 3, 'Progressive ogr_camp_hunting', 'Ogre Camp Building: Big Feast Tent'),
    26448: itemData(IC.useful, 1, 'wh3_main_ogr_camp_hunting_5', itemType.building, 4, 'Progressive ogr_camp_hunting', 'Ogre Camp Building: Feasting Stones'),
    26449: itemData(IC.useful, 1, 'wh3_main_ogr_camp_monster_1', itemType.building, 0, 'Progressive ogr_camp_monster', 'Ogre Camp Building: Bounty Pot'),
    26450: itemData(IC.useful, 1, 'wh3_main_ogr_camp_monster_2', itemType.building, 1, 'Progressive ogr_camp_monster', 'Ogre Camp Building: Bounty Tent'),
    26451: itemData(IC.useful, 1, 'wh3_main_ogr_camp_monster_3', itemType.building, 2, 'Progressive ogr_camp_monster', 'Ogre Camp Building: Stash Hut'),
    26452: itemData(IC.useful, 1, 'wh3_main_ogr_camp_recruitment_1', itemType.building, 0, 'Progressive ogr_camp_recruitment', 'Ogre Camp Building: Spare Tent'),
    26453: itemData(IC.useful, 1, 'wh3_main_ogr_camp_recruitment_2', itemType.building, 1, 'Progressive ogr_camp_recruitment', "Ogre Camp Building: Recrooter'z Table"),
    26454: itemData(IC.useful, 1, 'wh3_main_ogr_camp_recruitment_3', itemType.building, 2, 'Progressive ogr_camp_recruitment', "Ogre Camp Building: Recrooter'z Tent"),
    26455: itemData(IC.useful, 1, 'wh3_main_ogr_camp_recruitment_4', itemType.building, 3, 'Progressive ogr_camp_recruitment', "Ogre Camp Building: Recrooter'z Hut"),
    26456: itemData(IC.useful, 1, 'wh3_main_ogr_camp_town_centre_1', itemType.building, 0, 'Progressive ogr_camp_town_centre', 'Ogre Camp Building: Ogre Shelter'),
    26457: itemData(IC.useful, 1, 'wh3_main_ogr_camp_town_centre_2', itemType.building, 1, 'Progressive ogr_camp_town_centre', 'Ogre Camp Building: Ogre Camp'),
    26458: itemData(IC.useful, 1, 'wh3_main_ogr_camp_town_centre_3', itemType.building, 2, 'Progressive ogr_camp_town_centre', 'Ogre Camp Building: Tribal Campground'),
    26459: itemData(IC.useful, 1, 'wh3_main_ogr_camp_town_centre_4', itemType.building, 3, 'Progressive ogr_camp_town_centre', 'Ogre Camp Building: Ancient Tooth Circle'),
    26460: itemData(IC.useful, 1, 'wh3_main_ogr_camp_town_centre_5', itemType.building, 4, 'Progressive ogr_camp_town_centre', 'Ogre Camp Building: Great Maw Site'),
    26461: itemData(IC.useful, 1, 'wh3_main_ogr_camp_upkeep_1', itemType.building, 0, 'Progressive ogr_camp_upkeep', 'Ogre Camp Building: Gut Stone'),
    26462: itemData(IC.useful, 1, 'wh3_main_ogr_camp_upkeep_2', itemType.building, 1, 'Progressive ogr_camp_upkeep', 'Ogre Camp Building: Plate Store'),
    26463: itemData(IC.useful, 1, 'wh3_main_ogr_camp_upkeep_3', itemType.building, 2, 'Progressive ogr_camp_upkeep', 'Ogre Camp Building: Gut Henge'),
    26464: itemData(IC.useful, 1, 'wh3_main_ogr_camp_upkeep_4', itemType.building, 3, 'Progressive ogr_camp_upkeep', "Ogre Camp Building: Butcher's Slab"),
    26465: itemData(IC.useful, 1, 'wh3_main_ogr_camp_upkeep_5', itemType.building, 4, 'Progressive ogr_camp_upkeep', "Ogre Camp Building: Slaughtermaster's Table"),
    26466: itemData(IC.useful, 1, 'wh3_main_ogr_cav_1', itemType.building, 0, 'Progressive ogr_cav', 'Ogre Building: Pack Cave'),
    26467: itemData(IC.useful, 1, 'wh3_main_ogr_cav_2', itemType.building, 1, 'Progressive ogr_cav', 'Ogre Building: Gorger Cave'),
    26468: itemData(IC.useful, 1, 'wh3_main_ogr_corruption_1', itemType.building, 0, 'Progressive ogr_corruption', 'Ogre Building: Fire Shrine'),
    26469: itemData(IC.useful, 1, 'wh3_main_ogr_corruption_2', itemType.building, 1, 'Progressive ogr_corruption', 'Ogre Building: Fire Cave'),
    26470: itemData(IC.useful, 1, 'wh3_main_ogr_corruption_3', itemType.building, 2, 'Progressive ogr_corruption', 'Ogre Building: Fire Mount'),
    26471: itemData(IC.useful, 1, 'wh3_main_ogr_defence_minor_1', itemType.building, 0, 'Progressive ogr_defence_minor', 'Ogre Building: Muck Trench'),
    26472: itemData(IC.useful, 1, 'wh3_main_ogr_defence_minor_2', itemType.building, 1, 'Progressive ogr_defence_minor', 'Ogre Building: Crap Moat'),
    26473: itemData(IC.useful, 1, 'wh3_main_ogr_defence_minor_3', itemType.building, 2, 'Progressive ogr_defence_minor', 'Ogre Building: Giant Stones'),
    26474: itemData(IC.useful, 1, 'wh3_main_ogr_farm_1', itemType.building, 0, 'Progressive ogr_farm', 'Ogre Building: Big Slab'),
    26475: itemData(IC.useful, 1, 'wh3_main_ogr_farm_2', itemType.building, 1, 'Progressive ogr_farm', 'Ogre Building: Maw Hole'),
    26476: itemData(IC.useful, 1, 'wh3_main_ogr_farm_3', itemType.building, 2, 'Progressive ogr_farm', 'Ogre Building: Maw Pit'),
    26477: itemData(IC.useful, 1, 'wh3_main_ogr_industry_1', itemType.building, 0, 'Progressive ogr_industry', 'Ogre Building: Gold Hoard'),
    26478: itemData(IC.useful, 1, 'wh3_main_ogr_industry_2', itemType.building, 1, 'Progressive ogr_industry', 'Ogre Building: Paychest Store'),
    26479: itemData(IC.useful, 1, 'wh3_main_ogr_industry_3', itemType.building, 2, 'Progressive ogr_industry', 'Ogre Building: Counting House'),
    26480: itemData(IC.useful, 1, 'wh3_main_ogr_order_1', itemType.building, 0, 'Progressive ogr_order', 'Ogre Building: Larder'),
    26481: itemData(IC.useful, 1, 'wh3_main_ogr_order_2', itemType.building, 1, 'Progressive ogr_order', 'Ogre Building: Meat Store'),
    26482: itemData(IC.useful, 1, 'wh3_main_ogr_order_3', itemType.building, 2, 'Progressive ogr_order', 'Ogre Building: Steak Locker'),
    26483: itemData(IC.useful, 1, 'wh3_main_ogr_port_1', itemType.building, 0, 'Progressive ogr_port', 'Ogre Building: Raft Jetty'),
    26484: itemData(IC.useful, 1, 'wh3_main_ogr_port_2', itemType.building, 1, 'Progressive ogr_port', 'Ogre Building: Big Wharf'),
    26485: itemData(IC.useful, 1, 'wh3_main_ogr_resource_animals_1', itemType.building, 0, 'Progressive ogr_resource_animals', 'Ogre Building: Exotic Animal Tamer'),
    26486: itemData(IC.useful, 1, 'wh3_main_ogr_resource_animals_2', itemType.building, 1, 'Progressive ogr_resource_animals', 'Ogre Building: Exotic Pet Store'),
    26487: itemData(IC.useful, 1, 'wh3_main_ogr_resource_animals_3', itemType.building, 2, 'Progressive ogr_resource_animals', 'Ogre Building: Exotic Animal Bazaar'),
    26488: itemData(IC.useful, 1, 'wh3_main_ogr_resource_dyes_1', itemType.building, 0, 'Progressive ogr_resource_dyes', 'Ogre Building: Cinnabar Mining Pit'),
    26489: itemData(IC.useful, 1, 'wh3_main_ogr_resource_dyes_2', itemType.building, 1, 'Progressive ogr_resource_dyes', 'Ogre Building: Cinnabar Mine'),
    26490: itemData(IC.useful, 1, 'wh3_main_ogr_resource_dyes_3', itemType.building, 2, 'Progressive ogr_resource_dyes', 'Ogre Building: Dyemaker'),
    26491: itemData(IC.useful, 1, 'wh3_main_ogr_resource_furs_1', itemType.building, 0, 'Progressive ogr_resource_furs', "Ogre Building: Skinner's Tent"),
    26492: itemData(IC.useful, 1, 'wh3_main_ogr_resource_furs_2', itemType.building, 1, 'Progressive ogr_resource_furs', "Ogre Building: Skinner's Hut"),
    26493: itemData(IC.useful, 1, 'wh3_main_ogr_resource_furs_3', itemType.building, 2, 'Progressive ogr_resource_furs', "Ogre Building: Tanner's Place"),
    26494: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gems_1', itemType.building, 0, 'Progressive ogr_resource_gems', 'Ogre Building: Gem Mineshaft'),
    26495: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gems_2', itemType.building, 1, 'Progressive ogr_resource_gems', 'Ogre Building: Gem Mine'),
    26496: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gems_3', itemType.building, 2, 'Progressive ogr_resource_gems', 'Ogre Building: Big Gem Mine'),
    26497: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gold_1', itemType.building, 0, 'Progressive ogr_resource_gold', 'Ogre Building: Gold Mining Pit'),
    26498: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gold_2', itemType.building, 1, 'Progressive ogr_resource_gold', 'Ogre Building: Gold Mine'),
    26499: itemData(IC.useful, 1, 'wh3_main_ogr_resource_gold_3', itemType.building, 2, 'Progressive ogr_resource_gold', 'Ogre Building: Mint'),
    26500: itemData(IC.useful, 1, 'wh3_main_ogr_resource_iron_1', itemType.building, 0, 'Progressive ogr_resource_iron', 'Ogre Building: Iron Mining Pit'),
    26501: itemData(IC.useful, 1, 'wh3_main_ogr_resource_iron_2', itemType.building, 1, 'Progressive ogr_resource_iron', 'Ogre Building: Iron Mine'),
    26502: itemData(IC.useful, 1, 'wh3_main_ogr_resource_iron_3', itemType.building, 2, 'Progressive ogr_resource_iron', 'Ogre Building: Iron Smelter'),
    26503: itemData(IC.useful, 1, 'wh3_main_ogr_resource_ivory_1', itemType.building, 0, 'Progressive ogr_resource_ivory', 'Ogre Building: Animal Store'),
    26504: itemData(IC.useful, 1, 'wh3_main_ogr_resource_ivory_2', itemType.building, 1, 'Progressive ogr_resource_ivory', 'Ogre Building: Tusk Market'),
    26505: itemData(IC.useful, 1, 'wh3_main_ogr_resource_ivory_3', itemType.building, 2, 'Progressive ogr_resource_ivory', 'Ogre Building: Tusk Compound'),
    26506: itemData(IC.useful, 1, 'wh3_main_ogr_resource_marble_1', itemType.building, 0, 'Progressive ogr_resource_marble', 'Ogre Building: Quarry'),
    26507: itemData(IC.useful, 1, 'wh3_main_ogr_resource_marble_2', itemType.building, 1, 'Progressive ogr_resource_marble', 'Ogre Building: Granite Werks'),
    26508: itemData(IC.useful, 1, 'wh3_main_ogr_resource_marble_3', itemType.building, 2, 'Progressive ogr_resource_marble', 'Ogre Building: Marble Werks'),
    26509: itemData(IC.useful, 1, 'wh3_main_ogr_resource_medicine_1', itemType.building, 0, 'Progressive ogr_resource_medicine', 'Ogre Building: Herb Patch'),
    26510: itemData(IC.useful, 1, 'wh3_main_ogr_resource_medicine_2', itemType.building, 1, 'Progressive ogr_resource_medicine', 'Ogre Building: Herb Garden'),
    26511: itemData(IC.useful, 1, 'wh3_main_ogr_resource_medicine_3', itemType.building, 2, 'Progressive ogr_resource_medicine', 'Ogre Building: Herb Tent'),
    26512: itemData(IC.useful, 1, 'wh3_main_ogr_resource_obsidian_1', itemType.building, 0, 'Progressive ogr_resource_obsidian', 'Ogre Building: Obsidian Quarry'),
    26513: itemData(IC.useful, 1, 'wh3_main_ogr_resource_obsidian_2', itemType.building, 1, 'Progressive ogr_resource_obsidian', 'Ogre Building: Obsidian Trinket Maker'),
    26514: itemData(IC.useful, 1, 'wh3_main_ogr_resource_obsidian_3', itemType.building, 2, 'Progressive ogr_resource_obsidian', 'Ogre Building: Obsidian Amulet Carver'),
    26515: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pasture_1', itemType.building, 0, 'Progressive ogr_resource_pasture', 'Ogre Building: Grazing Pastures'),
    26516: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pasture_2', itemType.building, 1, 'Progressive ogr_resource_pasture', 'Ogre Building: Livestock Pens'),
    26517: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pasture_3', itemType.building, 2, 'Progressive ogr_resource_pasture', 'Ogre Building: Mountain Ranch'),
    26518: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pottery_1', itemType.building, 0, 'Progressive ogr_resource_pottery', 'Ogre Building: Clay Pit'),
    26519: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pottery_2', itemType.building, 1, 'Progressive ogr_resource_pottery', "Ogre Building: Potter's Tent"),
    26520: itemData(IC.useful, 1, 'wh3_main_ogr_resource_pottery_3', itemType.building, 2, 'Progressive ogr_resource_pottery', 'Ogre Building: Mountain Kilns'),
    26521: itemData(IC.useful, 1, 'wh3_main_ogr_resource_salt_1', itemType.building, 0, 'Progressive ogr_resource_salt', 'Ogre Building: Salt Flats'),
    26522: itemData(IC.useful, 1, 'wh3_main_ogr_resource_salt_2', itemType.building, 1, 'Progressive ogr_resource_salt', 'Ogre Building: Salt Pans'),
    26523: itemData(IC.useful, 1, 'wh3_main_ogr_resource_salt_3', itemType.building, 2, 'Progressive ogr_resource_salt', 'Ogre Building: Salt Distillery'),
    26524: itemData(IC.useful, 1, 'wh3_main_ogr_resource_spices_1', itemType.building, 0, 'Progressive ogr_resource_spices', 'Ogre Building: Spice Market'),
    26525: itemData(IC.useful, 1, 'wh3_main_ogr_resource_spices_2', itemType.building, 1, 'Progressive ogr_resource_spices', 'Ogre Building: Spice Trading Post'),
    26526: itemData(IC.useful, 1, 'wh3_main_ogr_resource_spices_3', itemType.building, 2, 'Progressive ogr_resource_spices', 'Ogre Building: Eastern Bazaar'),
    26527: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wine_1', itemType.building, 0, 'Progressive ogr_resource_wine', 'Ogre Building: Orchards'),
    26528: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wine_2', itemType.building, 1, 'Progressive ogr_resource_wine', 'Ogre Building: Vineyard'),
    26529: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wine_3', itemType.building, 2, 'Progressive ogr_resource_wine', 'Ogre Building: Vintner'),
    26530: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wood_1', itemType.building, 0, 'Progressive ogr_resource_wood', "Ogre Building: Woodman's Hut"),
    26531: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wood_2', itemType.building, 1, 'Progressive ogr_resource_wood', 'Ogre Building: Timber Mill'),
    26532: itemData(IC.useful, 1, 'wh3_main_ogr_resource_wood_3', itemType.building, 2, 'Progressive ogr_resource_wood', 'Ogre Building: Lumberyard'),
    26533: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_major_1', itemType.building, 0, 'Progressive ogr_settlement_major', "Ogre Building: Stew Kitch'n (Major)"),
    26534: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_major_2', itemType.building, 1, 'Progressive ogr_settlement_major', 'Ogre Building: Maw Cave (Major)'),
    26535: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_major_3', itemType.building, 2, 'Progressive ogr_settlement_major', 'Ogre Building: Cauldron Town (Major)'),
    26536: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_minor_1', itemType.building, 0, 'Progressive ogr_settlement_minor', "Ogre Building: Stew Kitch'n (Minor)"),
    26537: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_minor_2', itemType.building, 1, 'Progressive ogr_settlement_minor', 'Ogre Building: Maw Cave (Minor)'),
    26538: itemData(IC.useful, 1, 'wh3_main_ogr_settlement_minor_3', itemType.building, 2, 'Progressive ogr_settlement_minor', 'Ogre Building: Cauldron Town (Minor)'),
    26539: itemData(IC.useful, 1, 'wh3_main_ogr_supplies_1', itemType.building, 0, 'Progressive ogr_supplies', 'Ogre Building: Guard Tent'),
    26540: itemData(IC.useful, 1, 'wh3_main_ogr_supplies_2', itemType.building, 1, 'Progressive ogr_supplies', 'Ogre Building: Guard Hut'),
    26541: itemData(IC.useful, 1, 'wh3_main_ogr_supplies_3', itemType.building, 2, 'Progressive ogr_supplies', 'Ogre Building: Guard House'),
}

techs: dict[int, itemData] = {
    26800: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_0_0', itemType.tech, 1, 'Progressive tech_ogr_campaign', 'Ogre Tech: Camp Huddle'),
    26801: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_0_0', itemType.tech, 2, 'Progressive tech_ogr_campaign', "Ogre Tech: Gnoblar Scavengin'"),
    26802: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_4_1', itemType.tech, 3, 'Progressive tech_ogr_campaign', 'Ogre Tech: Warpstone Rub'),
    26803: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_4_0', itemType.tech, 4, 'Progressive tech_ogr_campaign', 'Ogre Tech: Big Migration'),
    26804: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_5_1', itemType.tech, 5, 'Progressive tech_ogr_campaign', "Ogre Tech: Over-Eatin'"),
    26805: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_0_1', itemType.tech, 3, 'Progressive tech_ogr_campaign', 'Ogre Tech: Betta Bribes'),
    26806: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_11_0', itemType.tech, 4, 'Progressive tech_ogr_campaign', 'Ogre Tech: Bigga Camps'),
    26807: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_2_0', itemType.tech, 4, 'Progressive tech_ogr_campaign', 'Ogre Tech: Bigga Spit'),
    26808: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_10_0', itemType.tech, 5, 'Progressive tech_ogr_campaign', "Ogre Tech: Butcher's Apron"),
    26809: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_1_0', itemType.tech, 4, 'Progressive tech_ogr_campaign', "Ogre Tech: Camp Foragin'"),
    26810: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_7_0', itemType.tech, 5, 'Progressive tech_ogr_campaign', "Ogre Tech: Huntin' Tricks"),
    26811: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_2_0', itemType.tech, 1, 'Progressive tech_ogr_settlement', 'Ogre Tech: Dinner Gong'),
    26812: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_10_1', itemType.tech, 2, 'Progressive tech_ogr_settlement', 'Ogre Tech: Mawtooth Fealty'),
    26813: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_3_0', itemType.tech, 3, 'Progressive tech_ogr_settlement', 'Ogre Tech: Tribal Gathering'),
    26814: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_1_0', itemType.tech, 4, 'Progressive tech_ogr_settlement', "Ogre Tech: Butcher's Spices"),
    26815: itemData(IC.useful, 1, 'wh3_dlc26_ogr_kingdom_22', itemType.tech, 5, 'Progressive tech_ogr_settlement', 'Ogre Tech: Mountain Tyrants'),
    26816: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_5_1', itemType.tech, 3, 'Progressive tech_ogr_settlement', "Ogre Tech: Trade 'Relations'"),
    26817: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_8_0', itemType.tech, 4, 'Progressive tech_ogr_settlement', 'Ogre Tech: Trade Negotiator'),
    26818: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_3_1', itemType.tech, 4, 'Progressive tech_ogr_settlement', 'Ogre Tech: Fire Mouth Tribute'),
    26819: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_4_0', itemType.tech, 5, 'Progressive tech_ogr_settlement', 'Ogre Tech: Preachers of Fire'),
    26820: itemData(IC.useful, 1, 'wh3_dlc26_ogr_kingdom_16', itemType.tech, 4, 'Progressive tech_ogr_settlement', 'Ogre Tech: Mountain Metropolis'),
    26821: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_7_1', itemType.tech, 5, 'Progressive tech_ogr_settlement', 'Ogre Tech: Sky-Titan Defences'),
    26822: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_3_0', itemType.tech, 1, 'Progressive tech_ogr', 'Ogre Tech: Contract Scrawls'),
    26823: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_8_0', itemType.tech, 2, 'Progressive tech_ogr', 'Ogre Tech: Bigga Tents'),
    26824: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_2_1', itemType.tech, 3, 'Progressive tech_ogr', 'Ogre Tech: Gold Standard'),
    26825: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_2_0', itemType.tech, 4, 'Progressive tech_ogr', 'Ogre Tech: Ogre Throng'),
    26826: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_9_0', itemType.tech, 4, 'Progressive tech_ogr', 'Ogre Tech: Belonging to da Maw'),
    26827: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_11_0', itemType.tech, 4, 'Progressive tech_ogr', 'Ogre Tech: Sky-Titan Plateaus'),
    26828: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_4_1', itemType.tech, 1, 'Progressive tech_ogr_ogres', 'Ogre Tech: Ogre Breath'),
    26829: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_6_1', itemType.tech, 2, 'Progressive tech_ogr_ogres', 'Ogre Tech: Sinew Bindings'),
    26830: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_0_0', itemType.tech, 3, 'Progressive tech_ogr_ogres', 'Ogre Tech: Whetstones'),
    26831: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_04', itemType.tech, 3, 'Progressive tech_ogr_ogres', 'Ogre Tech: Improvised Munitions'),
    26832: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_05', itemType.tech, 4, 'Progressive tech_ogr_ogres', 'Ogre Tech: Leadsmashers'),
    26833: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_7_0', itemType.tech, 4, 'Progressive tech_ogr_ogres', 'Ogre Tech: Mournfang Scent'),
    26834: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_07', itemType.tech, 5, 'Progressive tech_ogr_ogres', 'Ogre Tech: Led by Their Noses'),
    26835: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_10_1', itemType.tech, 5, 'Progressive tech_ogr_ogres', 'Ogre Tech: Stolen Black Powder Recipe'),
    26836: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_8_1', itemType.tech, 6, 'Progressive tech_ogr_ogres', 'Ogre Tech: Tribal Tribute'),
    26837: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_0_1', itemType.tech, 7, 'Progressive tech_ogr_ogres', "Ogre Tech: Ridin' Stick"),
    26838: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_10_0', itemType.tech, 8, 'Progressive tech_ogr_ogres', 'Ogre Tech: Heavier Gut Plates'),
    26839: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_7_1', itemType.tech, 9, 'Progressive tech_ogr_ogres', "Ogre Tech: Finder's Fee"),
    26840: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_6_0', itemType.tech, 10, 'Progressive tech_ogr_ogres', 'Ogre Tech: Betta Plunda'),
    26841: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_3_0', itemType.tech, 11, 'Progressive tech_ogr_ogres', 'Ogre Tech: Ravening Hordes'),
    26842: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_15', itemType.tech, 1, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Stringy Tendons'),
    26843: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_16', itemType.tech, 2, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Busy Work'),
    26844: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_18', itemType.tech, 3, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Razor Sharp'),
    26845: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_3_1', itemType.tech, 3, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Bait the Trappers'),
    26846: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_20', itemType.tech, 4, 'Progressive tech_ogr_gnoblar', "Ogre Tech: What Doesn't Kill You"),
    26847: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_19', itemType.tech, 4, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Tyrannical Trainers'),
    26848: itemData(IC.useful, 1, 'wh3_main_tech_ogr_2_8_1', itemType.tech, 5, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Scrap Collectors'),
    26849: itemData(IC.useful, 1, 'wh3_main_tech_ogr_1_4_0', itemType.tech, 5, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Live Bait'),
    26850: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_23', itemType.tech, 6, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Nomadic Beast Pens'),
    26851: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_25', itemType.tech, 7, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Weighted Clubs'),
    26852: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_28', itemType.tech, 8, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Arctic Air'),
    26853: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_24', itemType.tech, 9, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Toughened Skin'),
    26854: itemData(IC.useful, 1, 'wh3_dlc26_ogr_horde_26', itemType.tech, 10, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Spiked Tuskguards'),
    26855: itemData(IC.useful, 1, 'wh3_main_tech_ogr_0_5_0', itemType.tech, 11, 'Progressive tech_ogr_gnoblar', 'Ogre Tech: Stonehorn Breeding')

}

progUnits: dict[int, itemData] = {
    27200: itemData(IC.useful, 4, "Progressive ogr_inf", itemType.unit, 4, "", "Progressive Ogre Unit: Infantry"),
    27201: itemData(IC.useful, 4, "Progressive ogr_rng", itemType.unit, 4, "", "Progressive Ogre Unit: Ranged"),
    27202: itemData(IC.useful, 3, "Progressive ogr_cav", itemType.unit, 3, "", "Progressive Ogre Unit: Cavalry"),
    27203: itemData(IC.useful, 2, "Progressive ogr_art", itemType.unit, 2, "", "Progressive Ogre Unit: Artillery"),
    27205: itemData(IC.useful, 4, "Progressive ogr_bst", itemType.unit, 4, "", "Progressive Ogre Unit: Beast"),
    27206: itemData(IC.useful, 1, "Progressive ogr_hro", itemType.unit, 1, "", "Progressive Ogre Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    27300: itemData(IC.useful, 3, 'Progressive ogr_camp_gnoblars', itemType.building, 3, None, 'Progressive Ogre Building: Camp Gnoblars'),
    27301: itemData(IC.useful, 3, 'Progressive ogr_gnoblars', itemType.building, 3, None, 'Progressive Ogre Building: Gnoblars'),
    27302: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_ogr', itemType.building, 3, None, 'Progressive Ogre Building: Foreign Slot Discovery Ogr'),
    27303: itemData(IC.useful, 3, 'Progressive ogr_allied_outpost', itemType.building, 3, None, 'Progressive Ogre Building: Allied Outpost'),
    27304: itemData(IC.useful, 3, 'Progressive ogr_barracks', itemType.building, 3, None, 'Progressive Ogre Building: Barracks'),
    27305: itemData(IC.useful, 3, 'Progressive ogr_camp_barracks', itemType.building, 3, None, 'Progressive Ogre Building: Camp Barracks'),
    27306: itemData(IC.useful, 4, 'Progressive ogr_camp_cav', itemType.building, 4, None, 'Progressive Ogre Building: Camp Cav'),
    27307: itemData(IC.useful, 5, 'Progressive ogr_camp_defence_replenishment', itemType.building, 3, None, 'Progressive Ogre Building: Camp Defence Replenishment'),
    27308: itemData(IC.useful, 5, 'Progressive ogr_camp_defence_upkeep', itemType.building, 5, None, 'Progressive Ogre Building: Camp Defence Upkeep'),
    27309: itemData(IC.useful, 5, 'Progressive ogr_camp_growth', itemType.building, 5, None, 'Progressive Ogre Building: Camp Growth'),
    27310: itemData(IC.useful, 3, 'Progressive ogr_camp_gunpowder', itemType.building, 3, None, 'Progressive Ogre Building: Camp Gunpowder'),
    27311: itemData(IC.useful, 3, 'Progressive ogr_camp_heavy_cav', itemType.building, 3, None, 'Progressive Ogre Building: Camp Heavy Cav'),
    27312: itemData(IC.useful, 5, 'Progressive ogr_camp_hunting', itemType.building, 5, None, 'Progressive Ogre Building: Camp Hunting'),
    27313: itemData(IC.useful, 3, 'Progressive ogr_camp_monster', itemType.building, 3, None, 'Progressive Ogre Building: Camp Monster'),
    27314: itemData(IC.useful, 4, 'Progressive ogr_camp_recruitment', itemType.building, 4, None, 'Progressive Ogre Building: Camp Recruitment'),
    27315: itemData(IC.useful, 5, 'Progressive ogr_camp_town_centre', itemType.building, 5, None, 'Progressive Ogre Building: Camp Town Centre'),
    27316: itemData(IC.useful, 5, 'Progressive ogr_camp_upkeep', itemType.building, 5, None, 'Progressive Ogre Building: Camp Upkeep'),
    27317: itemData(IC.useful, 2, 'Progressive ogr_cav', itemType.building, 2, None, 'Progressive Ogre Building: Cav'),
    27318: itemData(IC.useful, 3, 'Progressive ogr_corruption', itemType.building, 3, None, 'Progressive Ogre Building: Corruption'),
    27319: itemData(IC.useful, 3, 'Progressive ogr_defence_minor', itemType.building, 3, None, 'Progressive Ogre Building: Defence Minor'),
    27320: itemData(IC.useful, 3, 'Progressive ogr_farm', itemType.building, 3, None, 'Progressive Ogre Building: Farm'),
    27321: itemData(IC.useful, 3, 'Progressive ogr_industry', itemType.building, 3, None, 'Progressive Ogre Building: Industry'),
    27322: itemData(IC.useful, 3, 'Progressive ogr_order', itemType.building, 3, None, 'Progressive Ogre Building: Order'),
    27323: itemData(IC.useful, 2, 'Progressive ogr_port', itemType.building, 2, None, 'Progressive Ogre Building: Port'),
    27324: itemData(IC.useful, 3, 'Progressive ogr_resource_animals', itemType.building, 3, None, 'Progressive Ogre Building: Animals'),
    27325: itemData(IC.useful, 3, 'Progressive ogr_resource_dyes', itemType.building, 3, None, 'Progressive Ogre Building: Dyes'),
    27326: itemData(IC.useful, 3, 'Progressive ogr_resource_furs', itemType.building, 3, None, 'Progressive Ogre Building: Furs'),
    27327: itemData(IC.useful, 3, 'Progressive ogr_resource_gems', itemType.building, 3, None, 'Progressive Ogre Building: Gems'),
    27328: itemData(IC.useful, 3, 'Progressive ogr_resource_gold', itemType.building, 3, None, 'Progressive Ogre Building: Gold'),
    27329: itemData(IC.useful, 3, 'Progressive ogr_resource_iron', itemType.building, 3, None, 'Progressive Ogre Building: Iron'),
    27330: itemData(IC.useful, 3, 'Progressive ogr_resource_ivory', itemType.building, 3, None, 'Progressive Ogre Building: Ivory'),
    27331: itemData(IC.useful, 3, 'Progressive ogr_resource_marble', itemType.building, 3, None, 'Progressive Ogre Building: Marble'),
    27332: itemData(IC.useful, 3, 'Progressive ogr_resource_medicine', itemType.building, 3, None, 'Progressive Ogre Building: Medicine'),
    27333: itemData(IC.useful, 3, 'Progressive ogr_resource_obsidian', itemType.building, 3, None, 'Progressive Ogre Building: Obsidian'),
    27334: itemData(IC.useful, 3, 'Progressive ogr_resource_pasture', itemType.building, 3, None, 'Progressive Ogre Building: Pasture'),
    27335: itemData(IC.useful, 3, 'Progressive ogr_resource_pottery', itemType.building, 3, None, 'Progressive Ogre Building: Pottery'),
    27336: itemData(IC.useful, 3, 'Progressive ogr_resource_salt', itemType.building, 3, None, 'Progressive Ogre Building: Salt'),
    27337: itemData(IC.useful, 3, 'Progressive ogr_resource_spices', itemType.building, 3, None, 'Progressive Ogre Building: Spices'),
    27338: itemData(IC.useful, 3, 'Progressive ogr_resource_wine', itemType.building, 3, None, 'Progressive Ogre Building: Wine'),
    27339: itemData(IC.useful, 3, 'Progressive ogr_resource_wood', itemType.building, 3, None, 'Progressive Ogre Building: Wood'),
    27340: itemData(IC.useful, 3, 'Progressive ogr_settlement_major', itemType.building, 3, None, 'Progressive Ogre Building: Settlement Major'),
    27341: itemData(IC.useful, 3, 'Progressive ogr_settlement_minor', itemType.building, 3, None, 'Progressive Ogre Building: Settlement Minor'),
    27342: itemData(IC.useful, 3, 'Progressive ogr_supplies', itemType.building, 3, None, 'Progressive Ogre Building: Supplies')
}

progTechs: dict[int, itemData] = {
    27400: itemData(IC.useful, 5, "Progressive tech_ogr_campaign", itemType.tech, 5, None, "Progressive Ogre Tech: Campaign"),
    27401: itemData(IC.useful, 5, "Progressive tech_ogr_settlement", itemType.tech, 5, None, "Progressive Ogre Tech: Settlement"),
    27402: itemData(IC.useful, 3, "Progressive tech_ogr_tents", itemType.tech, 3, None, "Progressive Ogre Tech: Tents"),
    27403: itemData(IC.useful, 11, "Progressive tech_ogr_ogres", itemType.tech, 11, None, "Progressive Ogre Tech: Ogres"),
    27404: itemData(IC.useful, 11, "Progressive tech_ogr_gnoblar", itemType.tech, 11, None, "Progressive Ogre Tech: Gnoblars and Beasts"),
}

special: dict[int, itemData] = {

}