from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData

# @formatter:off
units: dict[int, itemData] = {
    44000: itemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_0', itemType.unit, 1, 'Progressive sla_inf', 'Slaanesh Unit: Devoted Marauders of Slaanesh'),
    44001: itemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_1', itemType.unit, 1, 'Progressive sla_inf', 'Slaanesh Unit: Devoted Marauders of Slaanesh (Spears)'),
    44002: itemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_2', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: Devoted Marauders of Slaanesh (Hellscourges)'),
    44003: itemData(IC.useful, 1, 'wh3_dlc27_sla_inf_slaangors', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: Slaangors'),
    44004: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_forsaken_msla', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: Forsaken of Slaanesh'),
    44005: itemData(IC.useful, 1, 'wh3_dlc27_sla_inf_devotees_of_slaanesh', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Devotees of Slaanesh'),
    44006: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_msla', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: Chaos Warriors of Slaanesh'),
    44007: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    44008: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_msla', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Chosen of Slaanesh'),
    44009: itemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_msla_hellscourges', itemType.unit, 4, 'Progressive sla_inf', 'Slaanesh Unit: Chosen of Slaanesh (Hellscourges)'),
    44010: itemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_0', itemType.unit, 1, 'Progressive sla_inf', 'Slaanesh Unit: Daemonettes of Slaanesh'),
    44011: itemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_1', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Exalted Daemonettes of Slaanesh'),
    44012: itemData(IC.useful, 1, 'wh3_main_sla_mon_fiends_of_slaanesh_0', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Fiends of Slaanesh'),
    44013: itemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh', itemType.unit, 4, 'Progressive sla_inf', 'Slaanesh Unit: Champions of Slaanesh'),
    44014: itemData(IC.useful, 1, 'wh3_dlc27_sla_inf_devotees_of_slaanesh_crossbows', itemType.unit, 1, 'Progressive sla_rng', 'Def Unit: Devotees of Slaanesh (Crossbows)'),
    44015: itemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_0', itemType.unit, 1, 'Progressive sla_cav', 'Slaanesh Unit: Hellstriders of Slaanesh'),
    44016: itemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_1', itemType.unit, 2, 'Progressive sla_cav', 'Slaanesh Unit: Hellstriders of Slaanesh (Hellscourges)'),
    44017: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins', itemType.unit, 2, 'Progressive sla_cav', 'Slaanesh Unit: Marauder Horsemen of Slaanesh'),
    44018: itemData(IC.useful, 1, 'wh3_main_sla_cav_seekers_of_slaanesh_0', itemType.unit, 3, 'Progressive sla_cav', 'Slaanesh Unit: Seekers of Slaanesh'),
    44019: itemData(IC.useful, 1, 'wh3_main_sla_cav_heartseekers_of_slaanesh_0', itemType.unit, 3, 'Progressive sla_cav', 'Slaanesh Unit: Heartseekers of Slaanesh'),
    44020: itemData(IC.useful, 1, 'wh3_dlc27_sla_cav_pleasureseekers', itemType.unit, 5, 'Progressive sla_cav', 'Slaanesh Unit: Pleasureseekers'),
    44021: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_msla', itemType.unit, 4, 'Progressive sla_cav', 'Slaanesh Unit: Chaos Knights of Slaanesh'),
    44022: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_msla_lances', itemType.unit, 4, 'Progressive sla_cav', 'Slaanesh Unit: Chaos Knights of Slaanesh (Lances)'),
    44023: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_msla', itemType.unit, 1, 'Progressive sla_veh', 'Slaanesh Unit: Chaos Chariots of Slaanesh'),
    44024: itemData(IC.useful, 1, 'wh3_main_sla_veh_seeker_chariot_0', itemType.unit, 1, 'Progressive sla_veh', 'Slaanesh Unit: Seeker Chariots'),
    44025: itemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_msla', itemType.unit, 1, 'Progressive sla_veh', 'Slaanesh Unit: Chaos Warshrine of Slaanesh'),
    44026: itemData(IC.useful, 1, 'wh3_main_sla_veh_hellflayer_0', itemType.unit, 2, 'Progressive sla_veh', 'Slaanesh Unit: Hellflayers'),
    44027: itemData(IC.useful, 1, 'wh3_main_sla_veh_exalted_seeker_chariot_0', itemType.unit, 2, 'Progressive sla_veh', 'Slaanesh Unit: Exalted Seeker Chariot'),
    44028: itemData(IC.useful, 1, 'wh3_main_sla_inf_chaos_furies_0', itemType.unit, 1, 'Progressive sla_bst', 'Slaanesh Unit: Chaos Furies (Slaanesh)'),
    44029: itemData(IC.useful, 1, 'wh3_main_sla_mon_spawn_of_slaanesh_0', itemType.unit, 2, 'Progressive sla_bst', 'Slaanesh Unit: Spawn of Slaanesh'),
    44030: itemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton', itemType.unit, 3, 'Progressive sla_bst', 'Slaanesh Unit: Preyton'),
    44031: itemData(IC.useful, 1, 'wh3_main_sla_mon_soul_grinder_0', itemType.unit, 4, 'Progressive sla_bst', 'Slaanesh Unit: Soul Grinder of Slaanesh'),
    44032: itemData(IC.useful, 1, 'wh3_main_sla_mon_keeper_of_secrets_0', itemType.unit, 4, 'Progressive sla_bst', 'Slaanesh Unit: Keeper of Secrets'),
    44033: itemData(IC.useful, 1, 'wh3_main_sla_cha_cultist_0', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Cultist of Slaanesh'),
    44034: itemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_slaanesh_0', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Alluress (Slaanesh)'),
    44035: itemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_shadow_0', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Alluress (Shadows)'),
    44036: itemData(IC.useful, 1, 'wh3_dlc27_chs_cha_exalted_hero_msla', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Exalted Hero of Slaanesh'),
    44037: itemData(IC.useful, 1, 'wh3_dlc27_sla_cha_druchii_anointed', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Druchii Anointed'),
    44038: itemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_shadows_msla', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Chaos Sorcerer of Slaanesh (Shadows)'),
    44039: itemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_slaanesh_msla', itemType.unit, 1, 'Progressive sla_hro', 'Slaanesh Unit: Chaos Sorcerer of Slaanesh (Slaanesh)'),

    44040: itemData(IC.useful, 1, 'wh3_twa10_sla_inf_marauders_spears_ror', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: The Princes of Perfection (Devoted Marauders of Slaanesh - Spears)'),
    44041: itemData(IC.useful, 1, 'wh3_twa08_sla_mon_keeper_of_secrets_0_ror', itemType.unit, 5, 'Progressive sla_bst', 'Slaanesh Unit: The Marquis of Masochism (Keeper of Secrets)'),
    44042: itemData(IC.useful, 1, 'wh3_twa07_sla_cav_heartseekers_of_slaanesh_ror_0', itemType.unit, 3, 'Progressive sla_cav', 'Slaanesh Unit: Eternal Entourage (Heartseekers of Slaanesh)'),
    44043: itemData(IC.useful, 1, 'wh3_twa06_sla_inf_daemonette_ror_0', itemType.unit, 3, 'Progressive sla_inf', 'Slaanesh Unit: Bringers of Beguilement (Exalted Daemonettes of Slaanesh)'),
    44044: itemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton_ror', itemType.unit, 3, 'Progressive sla_bst', 'Slaanesh Unit: Scourge of Arden (Preyton)'),
    44045: itemData(IC.useful, 1, 'wh3_dlc27_nor_cav_marauder_horsemen_ror', itemType.unit, 2, 'Progressive sla_cav', 'Slaanesh Unit: Riders of the Mighty Serpent (Marauder Horsemen)'),
    44046: itemData(IC.useful, 1, 'wh_pro04_chs_inf_chaos_warriors_ror_0', itemType.unit, 2, 'Progressive sla_inf', 'Slaanesh Unit: Mirror Guard (Chaos Warriors)'),
    44047: itemData(IC.useful, 1, 'wh3_dlc27_sla_veh_seeker_chariot_ror', itemType.unit, 1, 'Progressive sla_veh', 'Slaanesh Unit: Heralds of Excess (Seeker Chariots)'),
    44048: itemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_msla_ror', itemType.unit, 1, 'Progressive sla_veh', 'Slaanesh Unit: The Sibilant Slaughtercade (Chaos Chariots)'),
    44049: itemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh_ror', itemType.unit, 4, 'Progressive sla_inf', 'Slaanesh Unit: Pleasure Guard (Champions of Slaanesh)'),
    #44026: ItemData(IC.useful, 1, 'wh3_main_sla_cha_exalted_keeper_of_secrets_slaanesh_0', ItemType.unit, 0, 'Progressive sla_inf', 'Slaanesh Unit: Exalted Keeper of Secrets (Slaanesh)'),
    #44027: ItemData(IC.useful, 1, 'wh3_main_sla_cha_exalted_keeper_of_secrets_shadow_0', ItemType.unit, 0, 'Progressive sla_inf', 'Slaanesh Unit: Exalted Keeper of Secrets (Shadows)'),
}

buildings: dict[int, itemData] = {
    44400: itemData(IC.useful, 1, 'wh3_dlc27_sla_barracks_0', itemType.building, 0, 'Progressive sla_barracks', 'Slaanesh Building: Shrine of Decadence'),
    44401: itemData(IC.useful, 1, 'wh3_main_sla_barracks_1', itemType.building, 1, 'Progressive sla_barracks', 'Slaanesh Building: Temple of Decadence'),

    44403: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_1', itemType.building, 0, 'Progressive sla_foreign_slot_discovery', 'Slaanesh Building: Warpstone Locus'),
    44404: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_2', itemType.building, 1, 'Progressive sla_foreign_slot_discovery', 'Slaanesh Building: Warpstone Traps'),
    44405: itemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_3', itemType.building, 2, 'Progressive sla_foreign_slot_discovery', 'Slaanesh Building: Guarded Warpstone'),
    44406: itemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_1', itemType.building, 0, 'Progressive sla_allied_outpost', 'Slaanesh Building: Slaaneshi Outpost'),
    44407: itemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_2', itemType.building, 1, 'Progressive sla_allied_outpost', 'Slaanesh Building: Slaaneshi District'),
    44408: itemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_3', itemType.building, 2, 'Progressive sla_allied_outpost', 'Slaanesh Building: Slaaneshi Colony'),
    44409: itemData(IC.useful, 1, 'wh3_main_sla_cav_1', itemType.building, 0, 'Progressive sla_cav', 'Slaanesh Building: Addiction Pens'),
    44410: itemData(IC.useful, 1, 'wh3_main_sla_cav_2', itemType.building, 1, 'Progressive sla_cav', 'Slaanesh Building: The Yearning Cages'),
    44411: itemData(IC.useful, 1, 'wh3_main_sla_cav_4', itemType.building, 4, 'Progressive sla_cav', 'Slaanesh Building: Darkling Grove'),
    44412: itemData(IC.useful, 1, 'wh3_main_sla_chariots_1', itemType.building, 0, 'Progressive sla_chariots', 'Slaanesh Building: Divine Circus'),
    44413: itemData(IC.useful, 1, 'wh3_main_sla_chariots_2', itemType.building, 1, 'Progressive sla_chariots', 'Slaanesh Building: Rapturous Circus'),
    44414: itemData(IC.useful, 1, 'wh3_main_sla_chariots_3', itemType.building, 2, 'Progressive sla_chariots', 'Slaanesh Building: Exalted Circus'),
    44415: itemData(IC.useful, 1, 'wh3_main_sla_cult_1', itemType.building, 0, 'Progressive sla_cult', 'Slaanesh Building: Devotee Enticement'),
    44416: itemData(IC.useful, 1, 'wh3_main_sla_cult_2', itemType.building, 0, 'Progressive sla_cult', 'Slaanesh Building: Charm Offensive'),
    44417: itemData(IC.useful, 1, 'wh3_main_sla_cult_3', itemType.building, 0, 'Progressive sla_cult', 'Slaanesh Building: Lure of Slaanesh'),
    44418: itemData(IC.useful, 1, 'wh3_main_sla_cult_4', itemType.building, 0, 'Progressive sla_cult', 'Slaanesh Building: Ritual of the Disciples'),
    44419: itemData(IC.useful, 1, 'wh3_main_sla_cult_corruption_1', itemType.building, 0, 'Progressive sla_cult_corruption', 'Slaanesh Building: Words of Temptation'),
    44420: itemData(IC.useful, 1, 'wh3_main_sla_cult_corruption_2', itemType.building, 0, 'Progressive sla_cult_corruption', 'Slaanesh Building: Population Preparation'),
    44421: itemData(IC.useful, 1, 'wh3_main_sla_cult_magus', itemType.building, 0, 'Progressive sla_cult_extra', 'Slaanesh Building: Cult Magus Chambers'),
    44422: itemData(IC.useful, 1, 'wh3_main_sla_cult_special', itemType.building, 0, 'Progressive sla_cult_extra', 'Slaanesh Building: Ritual of Excess'),
    44423: itemData(IC.useful, 1, 'wh3_main_sla_cult_teleport', itemType.building, 0, 'Progressive sla_cult_extra', 'Slaanesh Building: Ritual of Summoning'),
    44424: itemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_1', itemType.building, 0, 'Progressive sla_infra_corruption', 'Slaanesh Building: Lodge of the Succubi'),
    44425: itemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_2', itemType.building, 1, 'Progressive sla_infra_corruption', "Slaanesh Building: Bewitcher's Manse"),
    44426: itemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_3', itemType.building, 2, 'Progressive sla_infra_corruption', 'Slaanesh Building: Palace of the High Seductress'),
    44427: itemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_1', itemType.building, 0, 'Progressive sla_infra_devotee', 'Slaanesh Building: Cult of Pleasure'),
    44428: itemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_2', itemType.building, 1, 'Progressive sla_infra_devotee', 'Slaanesh Building: Cult of Pain'),
    44429: itemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_3', itemType.building, 2, 'Progressive sla_infra_devotee', 'Slaanesh Building: Cult of Agony'),
    44430: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_1', itemType.building, 0, 'Progressive sla_infra_growth_income', 'Slaanesh Building: Lavish Ciborium'),
    44431: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_2', itemType.building, 1, 'Progressive sla_infra_growth_income', 'Slaanesh Building: Grandiose Feretory'),
    44432: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_3', itemType.building, 2, 'Progressive sla_infra_growth_income', 'Slaanesh Building: Opulent Antiquity'),
    44433: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_1', itemType.building, 0, 'Progressive sla_infra_growth_xp', 'Slaanesh Building: Crystalline Pool'),
    44434: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_2', itemType.building, 1, 'Progressive sla_infra_growth_xp', 'Slaanesh Building: Eternal Mirror'),
    44435: itemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_3', itemType.building, 2, 'Progressive sla_infra_growth_xp', 'Slaanesh Building: Pellucid Globe'),
    44436: itemData(IC.useful, 1, 'wh3_main_sla_infra_order_1', itemType.building, 0, 'Progressive sla_infra_order', 'Slaanesh Building: The Dance of Dreaming'),
    44437: itemData(IC.useful, 1, 'wh3_main_sla_infra_order_2', itemType.building, 1, 'Progressive sla_infra_order', 'Slaanesh Building: The Pageant of Pain '),
    44438: itemData(IC.useful, 1, 'wh3_main_sla_infra_order_3', itemType.building, 2, 'Progressive sla_infra_order', 'Slaanesh Building: Opera of Dawn & Dusk'),
    44439: itemData(IC.useful, 1, 'wh3_main_sla_infra_order_4', itemType.building, 3, 'Progressive sla_infra_order', "Slaanesh Building: Rhan'k'adanra, the Final Dance"),

    44444: itemData(IC.useful, 1, 'wh3_main_sla_port_1', itemType.building, 0, 'Progressive sla_port', 'Slaanesh Building: Infernal Harbour'),
    44445: itemData(IC.useful, 1, 'wh3_main_sla_port_2', itemType.building, 1, 'Progressive sla_port', 'Slaanesh Building: Hell Port'),
    44446: itemData(IC.useful, 1, 'wh3_main_sla_port_3', itemType.building, 2, 'Progressive sla_port', 'Slaanesh Building: Eye of Terror'),

    44447: itemData(IC.useful, 1, 'wh3_main_sla_resource_animals_1', itemType.building, 0, 'Progressive sla_resource_animals', 'Slaanesh Building: Cultist Camp (Animals)'),
    44448: itemData(IC.useful, 1, 'wh3_main_sla_resource_animals_2', itemType.building, 1, 'Progressive sla_resource_animals', 'Slaanesh Building: Cultist Outpost (Animals)'),
    44449: itemData(IC.useful, 1, 'wh3_main_sla_resource_animals_3', itemType.building, 2, 'Progressive sla_resource_animals', 'Slaanesh Building: Cultist Enclave (Animals)'),
    44450: itemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_1', itemType.building, 0, 'Progressive sla_resource_dyes', 'Slaanesh Building: Cultist Camp (Dyes)'),
    44451: itemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_2', itemType.building, 1, 'Progressive sla_resource_dyes', 'Slaanesh Building: Cultist Outpost (Dyes)'),
    44452: itemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_3', itemType.building, 2, 'Progressive sla_resource_dyes', 'Slaanesh Building: Cultist Enclave (Dyes)'),
    44453: itemData(IC.useful, 1, 'wh3_main_sla_resource_furs_1', itemType.building, 0, 'Progressive sla_resource_furs', 'Slaanesh Building: Cultist Camp (Furs)'),
    44454: itemData(IC.useful, 1, 'wh3_main_sla_resource_furs_2', itemType.building, 1, 'Progressive sla_resource_furs', 'Slaanesh Building: Cultist Outpost (Furs)'),
    44455: itemData(IC.useful, 1, 'wh3_main_sla_resource_furs_3', itemType.building, 2, 'Progressive sla_resource_furs', 'Slaanesh Building: Cultist Enclave (Furs)'),
    44456: itemData(IC.useful, 1, 'wh3_main_sla_resource_gems_1', itemType.building, 0, 'Progressive sla_resource_gems', 'Slaanesh Building: Cultist Camp (Gems)'),
    44457: itemData(IC.useful, 1, 'wh3_main_sla_resource_gems_2', itemType.building, 1, 'Progressive sla_resource_gems', 'Slaanesh Building: Cultist Outpost (Gems)'),
    44458: itemData(IC.useful, 1, 'wh3_main_sla_resource_gems_3', itemType.building, 2, 'Progressive sla_resource_gems', 'Slaanesh Building: Cultist Enclave (Gems)'),
    44459: itemData(IC.useful, 1, 'wh3_main_sla_resource_gold_1', itemType.building, 0, 'Progressive sla_resource_gold', 'Slaanesh Building: Cultist Camp (Gold)'),
    44460: itemData(IC.useful, 1, 'wh3_main_sla_resource_gold_2', itemType.building, 1, 'Progressive sla_resource_gold', 'Slaanesh Building: Cultist Outpost (Gold)'),
    44461: itemData(IC.useful, 1, 'wh3_main_sla_resource_gold_3', itemType.building, 2, 'Progressive sla_resource_gold', 'Slaanesh Building: Cultist Enclave (Gold)'),
    44462: itemData(IC.useful, 1, 'wh3_main_sla_resource_iron_1', itemType.building, 0, 'Progressive sla_resource_iron', 'Slaanesh Building: Cultist Camp (Iron)'),
    44463: itemData(IC.useful, 1, 'wh3_main_sla_resource_iron_2', itemType.building, 1, 'Progressive sla_resource_iron', 'Slaanesh Building: Cultist Outpost (Iron)'),
    44464: itemData(IC.useful, 1, 'wh3_main_sla_resource_iron_3', itemType.building, 2, 'Progressive sla_resource_iron', 'Slaanesh Building: Cultist Enclave (Iron)'),
    44465: itemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_1', itemType.building, 0, 'Progressive sla_resource_ivory', 'Slaanesh Building: Cultist Camp (Tusks)'),
    44466: itemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_2', itemType.building, 1, 'Progressive sla_resource_ivory', 'Slaanesh Building: Cultist Outpost (Tusks)'),
    44467: itemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_3', itemType.building, 2, 'Progressive sla_resource_ivory', 'Slaanesh Building: Cultist Enclave (Tusks)'),
    44468: itemData(IC.useful, 1, 'wh3_main_sla_resource_marble_1', itemType.building, 0, 'Progressive sla_resource_marble', 'Slaanesh Building: Cultist Camp (Marble)'),
    44469: itemData(IC.useful, 1, 'wh3_main_sla_resource_marble_2', itemType.building, 1, 'Progressive sla_resource_marble', 'Slaanesh Building: Cultist Outpost (Marble)'),
    44470: itemData(IC.useful, 1, 'wh3_main_sla_resource_marble_3', itemType.building, 2, 'Progressive sla_resource_marble', 'Slaanesh Building: Cultist Enclave (Marble)'),
    44471: itemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_1', itemType.building, 0, 'Progressive sla_resource_medicine', 'Slaanesh Building: Cultist Camp (Medicine)'),
    44472: itemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_2', itemType.building, 1, 'Progressive sla_resource_medicine', 'Slaanesh Building: Cultist Outpost (Medicine)'),
    44473: itemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_3', itemType.building, 2, 'Progressive sla_resource_medicine', 'Slaanesh Building: Cultist Enclave (Medicine)'),
    44474: itemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_1', itemType.building, 0, 'Progressive sla_resource_obsidian', 'Slaanesh Building: Cultist Camp (Obsidian)'),
    44475: itemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_2', itemType.building, 1, 'Progressive sla_resource_obsidian', 'Slaanesh Building: Cultist Outpost (Obsidian)'),
    44476: itemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_3', itemType.building, 2, 'Progressive sla_resource_obsidian', 'Slaanesh Building: Cultist Enclave (Obsidian)'),
    44477: itemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_1', itemType.building, 0, 'Progressive sla_resource_pasture', 'Slaanesh Building: Cultist Camp (Pasture)'),
    44478: itemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_2', itemType.building, 1, 'Progressive sla_resource_pasture', 'Slaanesh Building: Cultist Outpost (Pasture)'),
    44479: itemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_3', itemType.building, 2, 'Progressive sla_resource_pasture', 'Slaanesh Building: Cultist Enclave (Pasture)'),
    44480: itemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_1', itemType.building, 0, 'Progressive sla_resource_pottery', 'Slaanesh Building: Cultist Camp (Pottery)'),
    44481: itemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_2', itemType.building, 1, 'Progressive sla_resource_pottery', 'Slaanesh Building: Cultist Outpost (Pottery)'),
    44482: itemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_3', itemType.building, 2, 'Progressive sla_resource_pottery', 'Slaanesh Building: Cultist Enclave (Pottery)'),
    44483: itemData(IC.useful, 1, 'wh3_main_sla_resource_salt_1', itemType.building, 0, 'Progressive sla_resource_salt', 'Slaanesh Building: Cultist Camp (Salt)'),
    44484: itemData(IC.useful, 1, 'wh3_main_sla_resource_salt_2', itemType.building, 1, 'Progressive sla_resource_salt', 'Slaanesh Building: Cultist Outpost (Salt)'),
    44485: itemData(IC.useful, 1, 'wh3_main_sla_resource_salt_3', itemType.building, 2, 'Progressive sla_resource_salt', 'Slaanesh Building: Cultist Enclave (Salt)'),
    44486: itemData(IC.useful, 1, 'wh3_main_sla_resource_spices_1', itemType.building, 0, 'Progressive sla_resource_spices', 'Slaanesh Building: Cultist Camp (Spices)'),
    44487: itemData(IC.useful, 1, 'wh3_main_sla_resource_spices_2', itemType.building, 1, 'Progressive sla_resource_spices', 'Slaanesh Building: Cultist Outpost (Spices)'),
    44488: itemData(IC.useful, 1, 'wh3_main_sla_resource_spices_3', itemType.building, 2, 'Progressive sla_resource_spices', 'Slaanesh Building: Cultist Enclave (Spices)'),
    44489: itemData(IC.useful, 1, 'wh3_main_sla_resource_wine_1', itemType.building, 0, 'Progressive sla_resource_wine', 'Slaanesh Building: Cultist Camp (Wine)'),
    44490: itemData(IC.useful, 1, 'wh3_main_sla_resource_wine_2', itemType.building, 1, 'Progressive sla_resource_wine', 'Slaanesh Building: Cultist Outpost (Wine)'),
    44491: itemData(IC.useful, 1, 'wh3_main_sla_resource_wine_3', itemType.building, 2, 'Progressive sla_resource_wine', 'Slaanesh Building: Cultist Enclave (Wine)'),
    44492: itemData(IC.useful, 1, 'wh3_main_sla_resource_wood_1', itemType.building, 0, 'Progressive sla_resource_wood', 'Slaanesh Building: Cultist Camp (Wood)'),
    44493: itemData(IC.useful, 1, 'wh3_main_sla_resource_wood_2', itemType.building, 1, 'Progressive sla_resource_wood', 'Slaanesh Building: Cultist Outpost (Wood)'),
    44494: itemData(IC.useful, 1, 'wh3_main_sla_resource_wood_3', itemType.building, 2, 'Progressive sla_resource_wood', 'Slaanesh Building: Cultist Enclave (Wood)'),

    44495: itemData(IC.useful, 1, 'wh3_main_sla_seekers_1', itemType.building, 0, 'Progressive sla_seekers', 'Slaanesh Building: Drifting Tower'),
    44496: itemData(IC.useful, 1, 'wh3_main_sla_seekers_2', itemType.building, 1, 'Progressive sla_seekers', 'Slaanesh Building: Drifting Forge'),
    44497: itemData(IC.useful, 1, 'wh3_main_sla_seekers_3', itemType.building, 2, 'Progressive sla_seekers', 'Slaanesh Building: Drifting Bastion'),
    44498: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_1_a', itemType.building, 0, 'Progressive sla_settlement_major', 'Slaanesh Building: Soul Keep (Major)'),
    44499: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_1', itemType.building, 0, 'Progressive sla_settlement_major', 'Slaanesh Building: Dimensional Tear (Major)'),
    44500: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_2_a', itemType.building, 1, 'Progressive sla_settlement_major', 'Slaanesh Building: Dark Bastion (Major)'),
    44501: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_2', itemType.building, 1, 'Progressive sla_settlement_major', 'Slaanesh Building: Dimensional Breach (Major)'),
    44502: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_3_a', itemType.building, 2, 'Progressive sla_settlement_major', 'Slaanesh Building: Infernal Citadel (Major)'),
    44503: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_3', itemType.building, 2, 'Progressive sla_settlement_major', 'Slaanesh Building: Dimensional Rift (Major)'),
    44504: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_4_a', itemType.building, 3, 'Progressive sla_settlement_major', 'Slaanesh Building: Daemonic Fortress (Major)'),
    44505: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_4', itemType.building, 3, 'Progressive sla_settlement_major', 'Slaanesh Building: Dimensional Nexus (Major)'),
    44506: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_5_a', itemType.building, 4, 'Progressive sla_settlement_major', 'Slaanesh Building: Chaos Dreadhold (Major)'),
    44507: itemData(IC.useful, 1, 'wh3_main_sla_settlement_major_5', itemType.building, 4, 'Progressive sla_settlement_major', 'Slaanesh Building: Dimensional Cascade (Major)'),
    44508: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_1', itemType.building, 0, 'Progressive sla_settlement_minor', 'Slaanesh Building: Dimensional Tear (Minor)'),
    44509: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_2', itemType.building, 1, 'Progressive sla_settlement_minor', 'Slaanesh Building: Dimensional Breach (Minor)'),
    44510: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_3', itemType.building, 2, 'Progressive sla_settlement_minor', 'Slaanesh Building: Dimensional Rift (Minor)'),
    44511: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_1_a', itemType.building, 0, 'Progressive sla_settlement_minor', 'Slaanesh Building: Soul Keep (Minor)'),
    44512: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_2_a', itemType.building, 1, 'Progressive sla_settlement_minor', 'Slaanesh Building: Dark Bastion (Minor)'),
    44513: itemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_3_a', itemType.building, 2, 'Progressive sla_settlement_minor', 'Slaanesh Building: Infernal Citadel (Minor)'),
    44514: itemData(IC.useful, 1, 'wh3_main_sla_walls_major_1', itemType.building, 0, 'Progressive sla_walls_major', 'Slaanesh Building: Daemonic Lurkers'),
    44515: itemData(IC.useful, 1, 'wh3_main_sla_walls_major_2', itemType.building, 1, 'Progressive sla_walls_major', 'Slaanesh Building: Daemonic Gathering'),
    44516: itemData(IC.useful, 1, 'wh3_main_sla_walls_major_3', itemType.building, 2, 'Progressive sla_walls_major', 'Slaanesh Building: Daemonic Locus'),
    44517: itemData(IC.useful, 1, 'wh3_main_sla_walls_minor_1', itemType.building, 0, 'Progressive sla_walls_minor', 'Slaanesh Building: Fog of Revelation'),
    44518: itemData(IC.useful, 1, 'wh3_main_sla_walls_minor_2', itemType.building, 1, 'Progressive sla_walls_minor', 'Slaanesh Building: Soporific Mist'),

    44519: itemData(IC.useful, 1, 'wh3_dlc27_sla_riders_1', itemType.building, 0, 'Progressive sla_riders', 'Slaanesh Building: Challenge Stone'),
    44520: itemData(IC.useful, 1, 'wh3_dlc27_sla_riders_2', itemType.building, 1, 'Progressive sla_riders', 'Slaanesh Building: Arena of Excess'),

    44521: itemData(IC.useful, 1, 'wh3_dlc27_sla_followers_1', itemType.building, 0, 'Progressive sla_followers', "Slaanesh Building: Dark Prince's Icon"),
    44522: itemData(IC.useful, 1, 'wh3_dlc27_sla_followers_2', itemType.building, 1, 'Progressive sla_followers', "Slaanesh Building: Dark Prince's Banner"),
    44523: itemData(IC.useful, 1, 'wh3_dlc27_sla_followers_3', itemType.building, 2, 'Progressive sla_followers', "Slaanesh Building: Dark Prince's Rally"),

    44524: itemData(IC.useful, 1, 'wh3_main_sla_keeper_1', itemType.building, 0, 'Progressive sla_keeper', 'Slaanesh Building: Sensuous Caress'),
    44525: itemData(IC.useful, 1, 'wh3_main_sla_keeper_2', itemType.building, 1, 'Progressive sla_keeper', 'Slaanesh Building: Tormented Whisper'),
    44526: itemData(IC.useful, 1, 'wh3_dlc27_sla_keeper_3', itemType.building, 2, 'Progressive sla_keeper', 'Slaanesh Building: Daemonic Lure'),

    44527: itemData(IC.useful, 1, 'wh3_main_sla_marauders_1', itemType.building, 0, 'Progressive sla_marauders', 'Slaanesh Building: Scented Pavilion'),
    44528: itemData(IC.useful, 1, 'wh3_main_sla_marauders_2', itemType.building, 1, 'Progressive sla_marauders', 'Slaanesh Building: Fragrant Pavilion'),
    44529: itemData(IC.useful, 1, 'wh3_dlc27_sla_marauders_3', itemType.building, 2, 'Progressive sla_marauders', 'Slaanesh Building: Pavilion of Excess'),

    44530: itemData(IC.useful, 1, 'wh3_dlc27_sla_cult_garrison_1', itemType.building, 0, 'Progressive sla_cult_garrison', 'Slaanesh Building: Alluring Suggestions'),
    44531: itemData(IC.useful, 1, 'wh3_dlc27_sla_cult_garrison_2', itemType.building, 1, 'Progressive sla_cult_garrison', 'Slaanesh Building: Irresistible Temptation'),

    44532: itemData(IC.useful, 1, 'wh3_main_cult_magus_trial_1', itemType.building, 0, 'Progressive sla_cult_magus', "Slaanesh Building: Acolyte Trials"),
    44533: itemData(IC.useful, 1, 'wh3_main_cult_magus_trial_2', itemType.building, 1, 'Progressive sla_cult_magus', "Slaanesh Building: The Dark God's Choice"),
}

techs: dict[int, itemData] = {
    44806: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_feats_of_cruelty', itemType.tech, 1, 'Progressive tech_sla_odour', 'Slaanesh Tech: Triumph and Torture'),
    44807: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_scent_of_agony', itemType.tech, 2, 'Progressive tech_sla_odour', 'Slaanesh Tech: Scent of Agony'),
    44808: itemData(IC.useful, 1, 'wh3_main_tech_sla_2_5', itemType.tech, 2, 'Progressive tech_sla_odour', 'Slaanesh Tech: Seeking Affluence'),
    44809: itemData(IC.useful, 1, 'wh3_main_tech_sla_2_4', itemType.tech, 2, 'Progressive tech_sla_odour', 'Slaanesh Tech: Enriching Toil'),
    44810: itemData(IC.useful, 1, 'wh3_main_tech_sla_2_3', itemType.tech, 2, 'Progressive tech_sla_odour', 'Slaanesh Tech: Wanton Destruction'),
    44811: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_passionate_torment', itemType.tech, 3, 'Progressive tech_sla_odour', 'Slaanesh Tech: Passionate Surrender'),
    44812: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_sinful_bravery', itemType.tech, 1, 'Progressive tech_sla_fragrance', 'Slaanesh Tech: Sinful Sanctity'),
    44813: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_1', itemType.tech, 2, 'Progressive tech_sla_fragrance', 'Slaanesh Tech: Carnal Incense'),
    44814: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_5', itemType.tech, 2, 'Progressive tech_sla_fragrance', 'Slaanesh Tech: Mortal Lust'),
    44815: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_4', itemType.tech, 2, 'Progressive tech_sla_fragrance', 'Slaanesh Tech: The Divine'),
    44816: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_3', itemType.tech, 2, 'Progressive tech_sla_fragrance', "Slaanesh Tech: Dark Prince's Emanation"),
    44817: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_6', itemType.tech, 3, 'Progressive tech_sla_fragrance', 'Slaanesh Tech: Ill-Repute'),
    44818: itemData(IC.useful, 1, 'wh3_main_tech_sla_4_2', itemType.tech, 1, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Intoxicating Heroism'),
    44819: itemData(IC.useful, 1, 'wh3_main_tech_sla_3_2', itemType.tech, 2, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Eternal Pleasures'),
    44820: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_lessons_of_immorality', itemType.tech, 2, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Lessons of Immorality'),
    44821: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_depraved_audacity', itemType.tech, 2, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Depraved Audacity'),
    44822: itemData(IC.useful, 1, 'wh3_main_tech_sla_4_3', itemType.tech, 2, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Spreading Perfection'),
    44823: itemData(IC.useful, 1, 'wh3_main_tech_sla_4_6', itemType.tech, 3, 'Progressive tech_sla_aroma', 'Slaanesh Tech: Invigorating Essence'),
    44824: itemData(IC.useful, 1, 'wh3_main_tech_sla_5_2', itemType.tech, 1, 'Progressive tech_sla_incense', 'Slaanesh Tech: Alluring Sisters'),
    44825: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_lethal_seduction', itemType.tech, 2, 'Progressive tech_sla_incense', 'Slaanesh Tech: Locus of Seduction'),
    44826: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_masterful_beguilement', itemType.tech, 2, 'Progressive tech_sla_incense', 'Slaanesh Tech: Master Beguilement'),
    44827: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_yearning_to_obey', itemType.tech, 2, 'Progressive tech_sla_incense', 'Slaanesh Tech: Yearning to Obey'),
    44828: itemData(IC.useful, 1, 'wh3_main_tech_sla_5_1', itemType.tech, 2, 'Progressive tech_sla_incense', 'Slaanesh Tech: Chromatic Servitude'),
    44829: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_inquisitive_servants', itemType.tech, 3, 'Progressive tech_sla_incense', 'Slaanesh Tech: Inquisitive Servants'),
    44830: itemData(IC.useful, 1, 'wh3_main_tech_sla_1_1', itemType.tech, 1, 'Progressive tech_sla_scent', 'Slaanesh Tech: Aberrant Promiscuity'),
    44831: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_deviant_authority', itemType.tech, 2, 'Progressive tech_sla_scent', 'Slaanesh Tech: Deviant Authority'),
    44832: itemData(IC.useful, 1, 'wh3_main_tech_sla_1_5', itemType.tech, 2, 'Progressive tech_sla_scent', 'Slaanesh Tech: Rigorous Chastisement'),
    44833: itemData(IC.useful, 1, 'wh3_main_tech_sla_1_4', itemType.tech, 2, 'Progressive tech_sla_scent', 'Slaanesh Tech: Grateful Enslavement'),
    44834: itemData(IC.useful, 1, 'wh3_main_tech_sla_1_3', itemType.tech, 2, 'Progressive tech_sla_scent', 'Slaanesh Tech: Euphoric Dominance'),
    44835: itemData(IC.useful, 1, 'wh3_main_tech_sla_1_6', itemType.tech, 3, 'Progressive tech_sla_scent', 'Slaanesh Tech: Rampant Consumerism'),
    44836: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_the_princes_protection', itemType.tech, 1, 'Progressive tech_sla_disciples', "Slaanesh Tech: The Prince's Protection"),
    44837: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_staunch_fighters', itemType.tech, 1, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Staunch Fighters'),
    44838: itemData(IC.useful, 1, 'wh3_main_tech_sla_5_5', itemType.tech, 2, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Glorious Doomriders'),
    44839: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_instinctive_reactions', itemType.tech, 2, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Frustrated Affinity'),
    44840: itemData(IC.useful, 1, 'wh3_main_tech_sla_4_4', itemType.tech, 2, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Decadent Apostles'),
    44841: itemData(IC.useful, 1, 'wh3_main_tech_sla_4_5', itemType.tech, 2, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Soul Hunters'),
    44842: itemData(IC.useful, 1, 'wh3_main_tech_sla_5_4', itemType.tech, 3, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Darkling Delights'),
    44843: itemData(IC.useful, 1, 'wh3_main_tech_sla_5_3', itemType.tech, 3, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Blessed Young'),
    44844: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_marvelous_executioners', itemType.tech, 3, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Marvelous Executioners'),
    44845: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_riders_of_hell', itemType.tech, 3, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Riders of Hell'),
    44846: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_fiends_of_torment', itemType.tech, 4, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Fiends of Torment'),
    44847: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_madness_and_mutation', itemType.tech, 4, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Madness and Mutation'),
    44848: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_eternal_agony', itemType.tech, 4, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Eternal Agony'),
    44849: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_warp_metal_hulks', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Warpmetal Absolute'),
    44850: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_seekers_of_pain_and_pleasure', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Seekers of Pain and Pleasure'),
    44851: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_unending_depravity', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Unending Depravity'),
    44852: itemData(IC.useful, 1, 'wh3_main_tech_sla_2_2', itemType.tech, 5, 'Progressive tech_sla_disciples', "Slaanesh Tech: Blood God's Disgust"),
    44853: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_blasphemous_blessings', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Blasphemous Promises'),
    44854: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_champions_of_anguish', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Champions of Anguish'),
    44855: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_immense_force', itemType.tech, 5, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Overbearing Force'),
    44856: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_daemonic_wave', itemType.tech, 6, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Daemonic Wave'),
    44857: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_dazzling_sturdiness', itemType.tech, 6, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Dazzling Sturdiness'),
    44858: itemData(IC.useful, 1, 'wh3_dlc27_tech_sla_mortal_acolytes', itemType.tech, 6, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Mortal Obsession'),
    44859: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_6', itemType.tech, 7, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Pained Feaster'),
    44860: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_1', itemType.tech, 7, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Rapturous Bliss'),
    44861: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_2', itemType.tech, 7, 'Progressive tech_sla_disciples', "Slaanesh Tech: Slaanesh's Lash"),
    44862: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_3', itemType.tech, 7, 'Progressive tech_sla_disciples', "Slaanesh Tech: Phantom's Goria"),
    44863: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_4', itemType.tech, 7, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Shards Slicing'),
    44864: itemData(IC.useful, 1, 'wh3_main_tech_sla_6_5', itemType.tech, 7, 'Progressive tech_sla_disciples', 'Slaanesh Tech: Frenzied Hysteria')
}

progUnits: dict[int, itemData] = {
    45200: itemData(IC.useful, 3, "Progressive sla_inf", itemType.unit, 3, None, "Progressive Slaanesh Unit: Infantry"),
    45201: itemData(IC.useful, 1, "Progressive sla_rng", itemType.unit, 1, None, "Progressive Slaanesh Unit: Ranged"),
    45202: itemData(IC.useful, 5, "Progressive sla_cav", itemType.unit, 5, None, "Progressive Slaanesh Unit: Cavalry"),
    45204: itemData(IC.useful, 2, "Progressive sla_veh", itemType.unit, 2, None, "Progressive Slaanesh Unit: Chariot"),
    45205: itemData(IC.useful, 4, "Progressive sla_bst", itemType.unit, 4, None, "Progressive Slaanesh Unit: Beast"),
    45206: itemData(IC.useful, 1, "Progressive sla_hro", itemType.unit, 1, None, "Progressive Slaanesh Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    45300: itemData(IC.useful, 3, 'Progressive sla_foreign_slot_discovery', itemType.building, 3, None, 'Progressive Slaanesh Building: Foreign Slot Discovery'),
    45301: itemData(IC.useful, 3, 'Progressive sla_allied_outpost', itemType.building, 3, None, 'Progressive Slaanesh Building: Allied Outpost'),
    45302: itemData(IC.useful, 2, 'Progressive sla_barracks', itemType.building, 2, None, 'Progressive Slaanesh Building: Barracks'),
    45303: itemData(IC.useful, 1, 'Progressive sla_cav', itemType.building, 1, None, 'Progressive Slaanesh Building: Cav'),
    45304: itemData(IC.useful, 2, 'Progressive sla_cav', itemType.building, 2, None, 'Progressive Slaanesh Building: Cav'),
    45305: itemData(IC.useful, 4, 'Progressive sla_cav', itemType.building, 4, None, 'Progressive Slaanesh Building: Cav'),
    45306: itemData(IC.useful, 5, 'Progressive sla_cav', itemType.building, 5, None, 'Progressive Slaanesh Building: Cav'),
    45307: itemData(IC.useful, 3, 'Progressive sla_chariots', itemType.building, 3, None, 'Progressive Slaanesh Building: Chariots'),
    45308: itemData(IC.useful, 1, 'Progressive sla_cult', itemType.building, 1, None, 'Progressive Slaanesh Building: Cult'),
    45309: itemData(IC.useful, 1, 'Progressive sla_cult_corruption', itemType.building, 1, None, 'Progressive Slaanesh Building: Cult Corruption'),
    45310: itemData(IC.useful, 1, 'Progressive sla_cult', itemType.building, 1, None, 'Progressive Slaanesh Building: Cult Extra'),
    45311: itemData(IC.useful, 3, 'Progressive sla_infra_corruption', itemType.building, 3, None, 'Progressive Slaanesh Building: Infra Corruption'),
    45312: itemData(IC.useful, 3, 'Progressive sla_infra_devotee', itemType.building, 3, None, 'Progressive Slaanesh Building: Infra Devotee'),
    45313: itemData(IC.useful, 3, 'Progressive sla_infra_growth_income', itemType.building, 3, None, 'Progressive Slaanesh Building: Infra Growth Income'),
    45314: itemData(IC.useful, 3, 'Progressive sla_infra_growth_xp', itemType.building, 3, None, 'Progressive Slaanesh Building: Infra Growth Xp'),
    45315: itemData(IC.useful, 4, 'Progressive sla_infra_order', itemType.building, 4, None, 'Progressive Slaanesh Building: Infra Order'),
    45316: itemData(IC.useful, 3, 'Progressive sla_keeper', itemType.building, 3, None, 'Progressive Slaanesh Building: Keeper'),
    45317: itemData(IC.useful, 3, 'Progressive sla_marauders', itemType.building, 3, None, 'Progressive Slaanesh Building: Marauders'),
    45318: itemData(IC.useful, 3, 'Progressive sla_port', itemType.building, 3, None, 'Progressive Slaanesh Building: Port'),
    45319: itemData(IC.useful, 3, 'Progressive sla_resource_animals', itemType.building, 3, None, 'Progressive Slaanesh Building: Animals'),
    45320: itemData(IC.useful, 3, 'Progressive sla_resource_dyes', itemType.building, 3, None, 'Progressive Slaanesh Building: Dyes'),
    45321: itemData(IC.useful, 3, 'Progressive sla_resource_furs', itemType.building, 3, None, 'Progressive Slaanesh Building: Furs'),
    45322: itemData(IC.useful, 3, 'Progressive sla_resource_gems', itemType.building, 3, None, 'Progressive Slaanesh Building: Gems'),
    45323: itemData(IC.useful, 3, 'Progressive sla_resource_gold', itemType.building, 3, None, 'Progressive Slaanesh Building: Gold'),
    45324: itemData(IC.useful, 3, 'Progressive sla_resource_iron', itemType.building, 3, None, 'Progressive Slaanesh Building: Iron'),
    45325: itemData(IC.useful, 3, 'Progressive sla_resource_ivory', itemType.building, 3, None, 'Progressive Slaanesh Building: Ivory'),
    45326: itemData(IC.useful, 3, 'Progressive sla_resource_marble', itemType.building, 3, None, 'Progressive Slaanesh Building: Marble'),
    45327: itemData(IC.useful, 3, 'Progressive sla_resource_medicine', itemType.building, 3, None, 'Progressive Slaanesh Building: Medicine'),
    45328: itemData(IC.useful, 3, 'Progressive sla_resource_obsidian', itemType.building, 3, None, 'Progressive Slaanesh Building: Obsidian'),
    45329: itemData(IC.useful, 3, 'Progressive sla_resource_pasture', itemType.building, 3, None, 'Progressive Slaanesh Building: Pasture'),
    45330: itemData(IC.useful, 3, 'Progressive sla_resource_pottery', itemType.building, 3, None, 'Progressive Slaanesh Building: Pottery'),
    45331: itemData(IC.useful, 3, 'Progressive sla_resource_salt', itemType.building, 3, None, 'Progressive Slaanesh Building: Salt'),
    45332: itemData(IC.useful, 3, 'Progressive sla_resource_spices', itemType.building, 3, None, 'Progressive Slaanesh Building: Spices'),
    45333: itemData(IC.useful, 3, 'Progressive sla_resource_wine', itemType.building, 3, None, 'Progressive Slaanesh Building: Wine'),
    45334: itemData(IC.useful, 3, 'Progressive sla_resource_wood', itemType.building, 3, None, 'Progressive Slaanesh Building: Wood'),
    45335: itemData(IC.useful, 3, 'Progressive sla_seekers', itemType.building, 3, None, 'Progressive Slaanesh Building: Seekers'),
    45336: itemData(IC.useful, 5, 'Progressive sla_settlement_major', itemType.building, 5, None, 'Progressive Slaanesh Building: Settlement Major'),
    45337: itemData(IC.useful, 3, 'Progressive sla_settlement_minor', itemType.building, 3, None, 'Progressive Slaanesh Building: Settlement Minor'),
    45338: itemData(IC.useful, 3, 'Progressive sla_walls_major', itemType.building, 3, None, 'Progressive Slaanesh Building: Walls Major'),
    45339: itemData(IC.useful, 2, 'Progressive sla_walls_minor', itemType.building, 2, None, 'Progressive Slaanesh Building: Walls Minor'),

    45340: itemData(IC.useful, 2, 'Progressive sla_riders', itemType.building, 2, None, 'Progressive Slaanesh Building: Mortal Riders'),
    45341: itemData(IC.useful, 3, 'Progressive sla_followers', itemType.building, 3, None, 'Progressive Slaanesh Building: Followers'),
    45342: itemData(IC.useful, 2, 'Progressive sla_cult_garrison', itemType.building, 2, None, 'Progressive Slaanesh Building: Cult Garrison'),
    45343: itemData(IC.useful, 2, 'Progressive sla_cult_magus', itemType.building, 2, None, 'Progressive Slaanesh Building: Cult Magus'),
}

progTechs: dict[int, itemData] = {
    45401: itemData(IC.useful, 3, "Progressive tech_sla_odour", itemType.tech, 3, None, "Progressive Slaanesh Tech: Odour of Lustful Agony"),
    45402: itemData(IC.useful, 3, "Progressive tech_sla_fragrance", itemType.tech, 3, None, "Progressive Slaanesh Tech: Fragrance of the Divine"),
    45403: itemData(IC.useful, 3, "Progressive tech_sla_aroma", itemType.tech, 3, None, "Progressive Slaanesh Tech: Aroma of Intoxicating Heroism"),
    45404: itemData(IC.useful, 3, "Progressive tech_sla_incense", itemType.tech, 3, None, "Progressive Slaanesh Tech: Incense of Chromatic Servitude"),
    45405: itemData(IC.useful, 3, "Progressive tech_sla_scent", itemType.tech, 3, None, "Progressive Slaanesh Tech: Scent of Aberrant Promiscuity"),
    45406: itemData(IC.useful, 8, "Progressive tech_sla_disciples", itemType.tech, 8, None, "Progressive Slaanesh Tech: Disciples"),
}

special: dict[int, specialItemData] = {
    45500: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_main_tech_sla_2_6', itemType.tech, 1, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: The Promise'),
    45501: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_main_tech_sla_2_1', itemType.tech, 2, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: Captivating Musk'),
    45502: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_main_tech_sla_1_2', itemType.tech, 2, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: Blissful Coquetry'),
    45503: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_main_tech_sla_4_1', itemType.tech, 2, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: Everlasting Gift'),
    45504: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_main_tech_sla_5_6', itemType.tech, 2, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: Darkling Disciples'),
    45505: specialItemData(IC.useful, 1, ["wh3_main_sla_seducers_of_slaanesh"], 'wh3_dlc27_tech_sla_delicious_agony', itemType.tech, 3, 'Progressive tech_sla_perfume', False, False, 'Slaanesh Tech: Delicious Agony'),
    45506: specialItemData(IC.useful, 3, ["wh3_main_sla_seducers_of_slaanesh"], "Progressive tech_sla_perfume", itemType.tech, 3, None, False, True, "Progressive Slaanesh Tech: Perfume of the Perverse"),

    45507: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_grasp_of_servitude', itemType.tech, 1, 'Progressive tech_sla_perfume_masque', False, False, "Slaanesh Tech: Servitude's Grasp"),
    45508: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_enticing_visage', itemType.tech, 2, 'Progressive tech_sla_perfume_masque', False, False, 'Slaanesh Tech: Dance of the Mind'),
    45509: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_changing_the_feet', itemType.tech, 2, 'Progressive tech_sla_perfume_masque', False, False, 'Slaanesh Tech: Lithe Improvisation'),
    45510: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_eternal_commitement', itemType.tech, 2, 'Progressive tech_sla_perfume_masque', False, False, 'Slaanesh Tech: Eternal Commitment'),
    45511: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_incessant_dance', itemType.tech, 2, 'Progressive tech_sla_perfume_masque', False, False, 'Slaanesh Tech: Incessant Dance'),
    45512: specialItemData(IC.useful, 1, ["wh3_dlc27_sla_masque_of_slaanesh"], 'wh3_dlc27_tech_sla_enthusiastic_devotees', itemType.tech, 3, 'Progressive tech_sla_perfume_masque', False, False, 'Slaanesh Tech: Maddening Devotion'),
    45513: specialItemData(IC.useful, 3, ["wh3_dlc27_sla_masque_of_slaanesh"], "Progressive tech_sla_perfume_masque", itemType.tech, 3, None, False, True, "Progressive Slaanesh Tech: Perfume of Sensations")
}

rituals: dict[int, specialItemData] = {

}