from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData
# @formatter:off
units: dict[int, itemData] = {
    46000: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_warriors_0', itemType.unit, 1, 'Progressive tmb_inf', 'TombKing Unit: Skeleton Warriors'),
    46001: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_0', itemType.unit, 1, 'Progressive tmb_inf', 'TombKing Unit: Skeleton Spearmen'),
    46002: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_0', itemType.unit, 1, 'Progressive tmb_inf', 'TombKing Unit: Nehekharan Warriors'),
    46003: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_1', itemType.unit, 3, 'Progressive tmb_inf', 'TombKing Unit: Tomb Guard (Halberds)'),
    46004: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_0', itemType.unit, 2, 'Progressive tmb_inf', 'TombKing Unit: Tomb Guard'),
    46005: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_0', itemType.unit, 2, 'Progressive tmb_inf', 'TombKing Unit: Ushabti'),
    46006: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_0', itemType.unit, 1, 'Progressive tmb_rng', 'TombKing Unit: Skeleton Archers'),
    46007: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_1', itemType.unit, 2, 'Progressive tmb_rng', 'TombKing Unit: Ushabti (Great Bows)'),
    46008: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_0', itemType.unit, 1, 'cavalry', 'TombKing Unit: Skeleton Horsemen'),
    46009: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0', itemType.unit, 1, 'cavalry', 'TombKing Unit: Skeleton Horse Archers'),
    46010: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_0', itemType.unit, 2, 'cavalry', 'TombKing Unit: Nehekharan Horsemen'),
    46011: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_0', itemType.unit, 3, 'Progressive tmb_cav', 'TombKing Unit: Sepulchral Stalkers'),
    46012: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_0', itemType.unit, 3, 'cavalry', 'TombKing Unit: Necropolis Knights'),
    46013: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_1', itemType.unit, 4, 'cavalry', 'TombKing Unit: Necropolis Knights (Halberds)'),
    46014: itemData(IC.useful, 1, 'wh2_dlc09_tmb_art_screaming_skull_catapult_0', itemType.unit, 1, 'Progressive tmb_art', 'TombKing Unit: Screaming Skull Catapults'),
    #46015: itemData(IC.useful, 1, 'wh2_dlc09_tmb_art_casket_of_souls_0', itemType.unit, 1, 'Progressive tmb_veh', 'TombKing Unit: Casket of Souls'),
    46016: itemData(IC.useful, 1, 'wh2_pro06_tmb_mon_bone_giant_0', itemType.unit, 2, 'Progressive tmb_art', 'TombKing Unit: Bone Giant'),
    46017: itemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_chariot_0', itemType.unit, 1, 'Progressive tmb_veh', 'TombKing Unit: Skeleton Chariots'),
    46018: itemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_archer_chariot_0', itemType.unit, 2, 'Progressive tmb_veh', 'TombKing Unit: Skeleton Archer Chariots'),
    46019: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_0', itemType.unit, 1, 'Progressive tmb_bst', 'TombKing Unit: Carrion'),
    46020: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_tomb_scorpion_0', itemType.unit, 2, 'Progressive tmb_bst', 'TombKing Unit: Tomb Scorpion'),
    46021: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_0', itemType.unit, 3, 'Progressive tmb_bst', 'TombKing Unit: Necrosphinx'),
    46022: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_heirotitan_0', itemType.unit, 3, 'Progressive tmb_bst', 'TombKing Unit: Hierotitan'),
    46023: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_tomb_prince_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Tomb Prince'),
    46024: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_necrotect_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Necrotect'),
    46025: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_shadow_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Liche Priest (Shadows)'),
    46026: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_nehekhara_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Liche Priest (Nehekhara)'),
    46027: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_light_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Liche Priest (Light)'),
    46028: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_death_0', itemType.unit, 1, 'Progressive tmb_hro', 'TombKing Unit: Liche Priest (Death)'),
    #46029: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_ror', itemType.unit, 1, 'Progressive tmb_bst', 'TombKing Unit: The Flock of Djaf (Carrion)'),
    46030: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_ror', itemType.unit, 2, 'Progressive tmb_rng', 'TombKing Unit: Chosen of the Gods (Ushabti - Great Bows)'),
    46031: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_ror', itemType.unit, 3, 'Progressive tmb_cav', 'TombKing Unit: Eyes of the Desert (Sepulchral Stalkers)'),
    46032: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_ror', itemType.unit, 3, 'Progressive tmb_bst', 'TombKing Unit: The Sphinx of Usekph (Necrosphinx)'),
    46033: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_ror', itemType.unit, 2, 'Progressive tmb_inf', 'TombKing Unit: The Khepra Guard (Tomb Guard)'),
    46034: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_ror', itemType.unit, 1, 'Progressive tmb_inf', "TombKing Unit: King Nekhesh's Scorpion Legion (Skeleton Spearmen)"),
    46035: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_ror', itemType.unit, 1, 'Progressive tmb_rng', 'TombKing Unit: Blessed Legion of Phakth (Skeleton Archers)'),
    #46036: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_ror', itemType.unit, 1, 'Progressive tmb_inf', "TombKing Unit: Usirian's Legion of the Netherworld (Nehekharan Warriors)"),
    #46037: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_ror', itemType.unit, 2, 'cavalry', 'TombKing Unit: Storm Riders of Khsar (Nehekharan Horsemen)'),
    #46038: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_ror', itemType.unit, 3, 'cavalry', 'TombKing Unit: Venom Knights of Asaph (Necropolis Knights)')
}

buildings: dict[int, itemData] = {
    #46400: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'TombKing Building: Khemri (Crypts)'),
    #46401: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'TombKing Building: Khemri (Mastaba)'),
    #46402: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'TombKing Building: Khemri (Mausoleum)'),
    #46403: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'TombKing Building: Khemri (Tomb City)'),
    #46404: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'TombKing Building: Khemri (Necropolis)'),
    #46405: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'TombKing Building: Lahmia (Crypts)'),
    #46406: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'TombKing Building: Lahmia (Mastaba)'),
    #46407: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'TombKing Building: Lahmia (Mausoleum)'),
    #46408: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'TombKing Building: Lahmia (Tomb City)'),
    #46409: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'TombKing Building: Lahmia (Necropolis)'),
    #46410: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'TombKing Building: Pyramid of Nagash (Dormant)'),
    #46411: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'TombKing Building: Pyramid of Nagash (Awakened)'),
    #46412: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'TombKing Building: Pyramid of Nagash (Powered)'),
    #46413: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'TombKing Building: Pyramid of Nagash (Charged)'),
    #46414: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'TombKing Building: Pyramid of Nagash (Exalted)'),
    46415: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_1', itemType.building, 0, 'Progressive tmb_cavalry', 'TombKing Building: Quicksand Swamp'),
    46416: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_2', itemType.building, 1, 'Progressive tmb_cavalry', 'TombKing Building: Ancient Battle Site'),
    46417: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_3', itemType.building, 2, 'Progressive tmb_cavalry', 'TombKing Building: Necroserpent Nest'),
    46418: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_4', itemType.building, 3, 'Progressive tmb_cavalry', 'TombKing Building: Royal Menagerie'),
    46419: itemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_1', itemType.building, 0, 'Progressive tmb_chariots', 'TombKing Building: Bone Shaper'),
    46420: itemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_2', itemType.building, 1, 'Progressive tmb_chariots', 'TombKing Building: Brass Works'),
    46421: itemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_3', itemType.building, 2, 'Progressive tmb_chariots', 'TombKing Building: Skull Repository'),
    46422: itemData(IC.useful, 1, 'wh2_dlc09_tmb_citadel_1', itemType.building, 0, 'Progressive tmb_citadel', 'TombKing Building: Ruined Nehekharan Citadel'),
    46423: itemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_1', itemType.building, 0, 'Progressive tmb_defence_major', 'TombKing Building: Skeletal Garrison'),
    46424: itemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_2', itemType.building, 1, 'Progressive tmb_defence_major', 'TombKing Building: Sandstone Walls'),
    46425: itemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_3', itemType.building, 2, 'Progressive tmb_defence_major', 'TombKing Building: Engraved Walls'),
    46426: itemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_1', itemType.building, 0, 'Progressive tmb_defence_minor', 'TombKing Building: Desert Lookout'),
    46427: itemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_2', itemType.building, 1, 'Progressive tmb_defence_minor', 'TombKing Building: Tower of Bone'),
    46429: itemData(IC.useful, 1, 'wh2_dlc09_tmb_estate_1', itemType.building, 0, 'Progressive tmb_estate', 'TombKing Building: Royal Burial Chamber'),
    46430: itemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_1', itemType.building, 0, 'Progressive tmb_growth', 'TombKing Building: Mortuary House'),
    46431: itemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_2', itemType.building, 1, 'Progressive tmb_growth', 'TombKing Building: Regnant Catacombs'),
    46432: itemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_3', itemType.building, 2, 'Progressive tmb_growth', 'TombKing Building: Grand Ossuary'),
    46433: itemData(IC.useful, 1, 'wh2_dlc09_tmb_hierotitan_1', itemType.building, 0, 'Progressive tmb_hierotitan', 'TombKing Building: Damaged Hierotitan Statue'),
    46494: itemData(IC.useful, 1, 'wh2_dlc09_tmb_hierotitan_2', itemType.building, 0, 'Progressive tmb_hierotitan', 'TombKing Building: Damaged Restored Statue'),
    46434: itemData(IC.useful, 1, 'wh2_dlc09_tmb_income_1', itemType.building, 0, 'Progressive tmb_income', 'TombKing Building: Charnel Plaza'),
    46435: itemData(IC.useful, 1, 'wh2_dlc09_tmb_income_2', itemType.building, 1, 'Progressive tmb_income', 'TombKing Building: Funerary District'),
    46436: itemData(IC.useful, 1, 'wh2_dlc09_tmb_income_3', itemType.building, 2, 'Progressive tmb_income', 'TombKing Building: Avenue of Monuments'),
    46437: itemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_1', itemType.building, 0, 'Progressive tmb_infantry', 'TombKing Building: Open Graves'),
    46438: itemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_2', itemType.building, 1, 'Progressive tmb_infantry', 'TombKing Building: Crypt Barracks'),
    46439: itemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_3', itemType.building, 2, 'Progressive tmb_infantry', 'TombKing Building: Royal Barracks'),
    46440: itemData(IC.useful, 1, 'wh2_dlc09_tmb_necrosphinx_1', itemType.building, 0, 'Progressive tmb_necrosphinx', 'TombKing Building: Damaged Necrosphinx Statue'),
    46495: itemData(IC.useful, 1, 'wh2_dlc09_tmb_necrosphinx_2', itemType.building, 0, 'Progressive tmb_necrosphinx', 'TombKing Building: Restored Necrosphinx Statue'),
    46441: itemData(IC.useful, 1, 'wh2_dlc09_tmb_port_1', itemType.building, 0, 'Progressive tmb_port', 'TombKing Building: Bone Wharf'),
    46442: itemData(IC.useful, 1, 'wh2_dlc09_tmb_port_2', itemType.building, 1, 'Progressive tmb_port', 'TombKing Building: Grave Port'),
    46443: itemData(IC.useful, 1, 'wh2_dlc09_tmb_port_3', itemType.building, 2, 'Progressive tmb_port', 'TombKing Building: Undead Fleetport'),
    46444: itemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_1', itemType.building, 0, 'Progressive tmb_public_order', 'TombKing Building: Obelisk'),
    46445: itemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_2', itemType.building, 1, 'Progressive tmb_public_order', 'TombKing Building: Sepulchre'),
    46446: itemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_3', itemType.building, 2, 'Progressive tmb_public_order', 'TombKing Building: Mortiferous Sanctuary'),
    46447: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_animals_1', itemType.building, 0, 'Progressive tmb_resource_animals', 'TombKing Building: Taxidermist Tomb'),
    46448: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_dyes_1', itemType.building, 0, 'Progressive tmb_resource_dyes', 'TombKing Building: Cinnabar Mining Pit'),
    46449: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_furs_1', itemType.building, 0, 'Progressive tmb_resource_furs', 'TombKing Building: Tannery'),
    46450: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gems_1', itemType.building, 0, 'Progressive tmb_resource_gems', 'TombKing Building: Gemstone Mine'),
    46451: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gold_1', itemType.building, 0, 'Progressive tmb_resource_gold', 'TombKing Building: Gold Mine'),
    46452: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_iron_1', itemType.building, 0, 'Progressive tmb_resource_iron', 'TombKing Building: Iron Mine'),
    46453: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_marble_1', itemType.building, 0, 'Progressive tmb_resource_marble', 'TombKing Building: Marble Quarry'),
    46454: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_medicine_1', itemType.building, 0, 'Progressive tmb_resource_medicine', 'TombKing Building: Alchemy Workshop'),
    46455: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_obsidian_1', itemType.building, 0, 'Progressive tmb_resource_obsidian', 'TombKing Building: Obsidian Quarry'),
    46456: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pasture_1', itemType.building, 0, 'Progressive tmb_resource_pasture', 'TombKing Building: Parched Oasis'),
    46457: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pottery_1', itemType.building, 0, 'Progressive tmb_resource_pottery', "TombKing Building: Potter's Hut"),
    46458: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_salt_1', itemType.building, 0, 'Progressive tmb_resource_salt', 'TombKing Building: Salt Mine'),
    46459: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_spices_1', itemType.building, 0, 'Progressive tmb_resource_spices', 'TombKing Building: Caravan Master'),
    46460: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wine_1', itemType.building, 0, 'Progressive tmb_resource_wine', 'TombKing Building: Vineyard'),
    46461: itemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wood_1', itemType.building, 0, 'Progressive tmb_resource_wood', 'TombKing Building: Lumber Camp'),
    46462: itemData(IC.useful, 1, 'wh2_dlc09_tmb_scorpions_1', itemType.building, 0, 'Progressive tmb_scorpions', 'TombKing Building: Scorpion Nest'),
    46463: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_1', itemType.building, 0, 'Progressive tmb_settlement_major', 'TombKing Building: Crypts (Major)'),
    46464: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_2', itemType.building, 1, 'Progressive tmb_settlement_major', 'TombKing Building: Mastaba (Major)'),
    46465: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_3', itemType.building, 2, 'Progressive tmb_settlement_major', 'TombKing Building: Mausoleum (Major)'),
    46466: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_4', itemType.building, 3, 'Progressive tmb_settlement_major', 'TombKing Building: Tomb City (Major)'),
    46467: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_5', itemType.building, 4, 'Progressive tmb_settlement_major', 'TombKing Building: Necropolis (Major)'),
    46468: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_1', itemType.building, 0, 'Progressive tmb_settlement_minor', 'TombKing Building: Crypts (Minor)'),
    46469: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_2', itemType.building, 1, 'Progressive tmb_settlement_minor', 'TombKing Building: Mastaba (Minor)'),
    46470: itemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_3', itemType.building, 2, 'Progressive tmb_settlement_minor', 'TombKing Building: Mausoleum (Minor)'),
    46471: itemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_1', itemType.building, 0, 'Progressive tmb_ushabti', 'TombKing Building: Statuary of Khemri'),
    46472: itemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_2', itemType.building, 1, 'Progressive tmb_ushabti', 'TombKing Building: Statue of Phakth'),
    46473: itemData(IC.useful, 1, 'wh2_dlc09_tmb_warsphinx_1', itemType.building, 0, 'Progressive tmb_warsphinx', 'TombKing Building: Ruined Warsphinx Statue'),
    46493: itemData(IC.useful, 1, 'wh2_dlc09_tmb_warsphinx_2', itemType.building, 1, 'Progressive tmb_warsphinx', 'TombKing Building: Restored Warsphinx Statue'),
    46474: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_1', itemType.building, 0, 'Progressive foreign_slot_discovery_tmb', 'TombKing Building: Catacomb Watchers'),
    46475: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_2', itemType.building, 1, 'Progressive foreign_slot_discovery_tmb', 'TombKing Building: Vault Guards'),
    46476: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_3', itemType.building, 2, 'Progressive foreign_slot_discovery_tmb', 'TombKing Building: Tomb Patrol'),
    46489: itemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_1', itemType.building, 0, 'Progressive tmb_allied_outpost', 'TombKing Building: Khemian Outpost'),
    46490: itemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_2', itemType.building, 1, 'Progressive tmb_allied_outpost', 'TombKing Building: Khemian District'),
    46491: itemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_3', itemType.building, 2, 'Progressive tmb_allied_outpost', 'TombKing Building: Khemian Colony'),
    46492: itemData(IC.useful, 1, 'wh3_main_tmb_resource_ivory_1', itemType.building, 0, 'Progressive tmb_resource_ivory', 'TombKing Building: Animal Store'),
}

techs: dict[int, itemData] = {
    46800: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_1', itemType.tech, 1, 'Progressive tech_tmb_1', 'TombKing Tech: Wisdom of the First Dynasty'),
    46801: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_1', itemType.tech, 2, 'Progressive tech_tmb_1', 'TombKing Tech: Proclamation of the First Dynasty'),
    46802: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Patronage of the First Dynasty'),
    46803: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_1', itemType.tech, 2, 'Progressive tech_tmb_1', 'TombKing Tech: Runic Inscriptions'),
    46804: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_2', itemType.tech, 2, 'Progressive tech_tmb_1', 'TombKing Tech: The Ossuary Dirge'),
    46805: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_3', itemType.tech, 2, 'Progressive tech_tmb_1', 'TombKing Tech: First Dynasty Plans'),
    46806: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Wakhaf of the First Dynasty'),
    46868: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Unremitting Devotion'),
    46807: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Priesthood of Ptra'),
    46808: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Apprenticeship of Pehenna'),
    46809: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_1', itemType.tech, 3, 'Progressive tech_tmb_1', 'TombKing Tech: Patronage of Wakhaf'),
    46810: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_2', itemType.tech, 1, 'Progressive tech_tmb_2', 'TombKing Tech: Wisdom of the Second Dynasty'),
    46811: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_2', itemType.tech, 2, 'Progressive tech_tmb_2', 'TombKing Tech: Proclamation of the Second Dynasty'),
    46812: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Patronage of the Second Dynasty'),
    46813: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_1', itemType.tech, 1, 'Progressive tech_tmb_2', 'TombKing Tech: The Quickening'),
    46814: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_2', itemType.tech, 1, 'Progressive tech_tmb_2', 'TombKing Tech: Nomad Stock'),
    46815: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_3', itemType.tech, 1, 'Progressive tech_tmb_2', 'TombKing Tech: Bone Edifice'),
    46816: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Rakhash of the Second Dynasty'),
    46869: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Ageless Colossi'),
    46817: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Priesthood of Neru'),
    46818: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Apprenticeship of Beka'),
    46819: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_2', itemType.tech, 3, 'Progressive tech_tmb_2', 'TombKing Tech: Patronage of Queen Rasut'),
    46820: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_3', itemType.tech, 1, 'Progressive tech_tmb_3', 'TombKing Tech: Wisdom of the Third Dynasty'),
    46821: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_3', itemType.tech, 2, 'Progressive tech_tmb_3', 'TombKing Tech: Proclamation of the Third Dynasty'),
    46822: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Patronage of the Third Dynasty'),
    46823: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_1', itemType.tech, 1, 'Progressive tech_tmb_3', 'TombKing Tech: The Boon of Ualatp'),
    46824: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_2', itemType.tech, 1, 'Progressive tech_tmb_3', 'TombKing Tech: The Ritual of Sokth'),
    46825: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_3', itemType.tech, 1, 'Progressive tech_tmb_3', 'TombKing Tech: Liche Administrators'),
    46826: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Thutep of the Third Dynasty'),
    46870: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Tireless Scavenging'),
    46827: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Priesthood of Djaf'),
    46828: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Apprenticeship of Thutmosa'),
    46829: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_3', itemType.tech, 3, 'Progressive tech_tmb_3', 'TombKing Tech: Patronage of Khetep'),
    46830: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_4', itemType.tech, 1, 'Progressive tech_tmb_4', 'TombKing Tech: Wisdom of the Fourth Dynasty'),
    46831: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_4', itemType.tech, 2, 'Progressive tech_tmb_4', 'TombKing Tech: Proclamation of the Fourth Dynasty'),
    46832: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Patronage of the Fourth Dynasty'),
    46833: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_1', itemType.tech, 1, 'Progressive tech_tmb_4', 'TombKing Tech: Pride in Service'),
    46834: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_2', itemType.tech, 1, 'Progressive tech_tmb_4', 'TombKing Tech: Dark Brotherhood'),
    46835: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_3', itemType.tech, 1, 'Progressive tech_tmb_4', 'TombKing Tech: Stronger Binding'),
    46836: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Lahmizzash of the Fourth Dynasty'),
    46871: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Magical Loci'),
    46837: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Priesthood of Khsar'),
    46838: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Apprenticeship of Hemiunus'),
    46839: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_4', itemType.tech, 3, 'Progressive tech_tmb_4', 'TombKing Tech: Patronage of Lahmizzash'),
    46840: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_5', itemType.tech, 1, 'Progressive tech_tmb_5', 'TombKing Tech: Wisdom of the Fifth Dynasty'),
    46841: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_5', itemType.tech, 2, 'Progressive tech_tmb_5', 'TombKing Tech: Proclamation of the Fifth Dynasty'),
    46842: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Patronage of the Fifth Dynasty'),
    46843: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_1', itemType.tech, 1, 'Progressive tech_tmb_5', 'TombKing Tech: Ancient Battle Sites'),
    46844: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_2', itemType.tech, 1, 'Progressive tech_tmb_5', "TombKing Tech: Invocation of Qu'Aph"),
    46845: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_3', itemType.tech, 1, 'Progressive tech_tmb_5', 'TombKing Tech: Ancient Quarries'),
    46846: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Setep of the Fifth Dynasty'),
    46872: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Coiling Alacrity'),
    46847: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Priesthood of Sokth'),
    46848: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Apprenticeship of Imhetop'),
    46849: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_5', itemType.tech, 3, 'Progressive tech_tmb_5', 'TombKing Tech: Patronage of Setep'),
    46850: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_6', itemType.tech, 1, 'Progressive tech_tmb_6', 'TombKing Tech: Wisdom of the Sixth Dynasty'),
    46851: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_6', itemType.tech, 2, 'Progressive tech_tmb_6', 'TombKing Tech: Proclamation of the Sixth Dynasty'),
    46852: itemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Patronage of the Sixth Dynasty'),
    46853: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_1', itemType.tech, 1, 'Progressive tech_tmb_6', 'TombKing Tech: Clothed in the Divine'),
    46854: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_2', itemType.tech, 1, 'Progressive tech_tmb_6', 'TombKing Tech: Underworld Gate'),
    46855: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_3', itemType.tech, 1, 'Progressive tech_tmb_6', 'TombKing Tech: The Lost Gold of Alkharad'),
    46856: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Alkhazzar II of the Sixth Dynasty'),
    46873: itemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Hearts of Stone'),
    46857: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Priesthood of Asaph'),
    46858: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Apprenticeship of Inenna'),
    46859: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_6', itemType.tech, 3, 'Progressive tech_tmb_6', 'TombKing Tech: Patronage of Alkhazzar'),
    46860: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_legions_of_legend', itemType.tech, 1, 'Progressive tech_tmb_herald', 'TombKing Tech: The Heralds Empowered'),
    46861: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_1', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of Rasetra'),
    46862: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_2', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of Djaf'),
    46863: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_3', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of Mahrak'),
    46864: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_4', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of the Sphinx'),
    46865: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_5', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of Zandri'),
    46866: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_6', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of Khemri'),
    46867: itemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_7', itemType.tech, 2, 'Progressive tech_tmb_herald', 'TombKing Tech: Herald of the Scorpion')
}

progUnits: dict[int, itemData] = {
    47200: itemData(IC.useful, 3, "Progressive tmb_inf", itemType.unit, 3, "", "Progressive TombKing Unit: Infantry"),
    47201: itemData(IC.useful, 2, "Progressive tmb_rng", itemType.unit, 2, "", "Progressive TombKing Unit: Ranged"),
    47202: itemData(IC.useful, 4, "Progressive tmb_cav", itemType.unit, 4, "", "Progressive TombKing Unit: Cavalry"),
    47203: itemData(IC.useful, 2, "Progressive tmb_art", itemType.unit, 2, "", "Progressive TombKing Unit: Artillery"),
    47204: itemData(IC.useful, 2, "Progressive tmb_veh", itemType.unit, 2, "", "Progressive TombKing Unit: Chariot"),
    47205: itemData(IC.useful, 3, "Progressive tmb_bst", itemType.unit, 3, "", "Progressive TombKing Unit: Beast"),
    47206: itemData(IC.useful, 1, "Progressive tmb_hro", itemType.unit, 1, "", "Progressive TombKing Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    47300: itemData(IC.useful, 4, 'Progressive tmb_cavalry', itemType.building, 4, None, 'Progressive TombKing Building: Cavalry'),
    47301: itemData(IC.useful, 3, 'Progressive tmb_chariots', itemType.building, 3, None, 'Progressive TombKing Building: Chariots'),
    47302: itemData(IC.useful, 1, 'Progressive tmb_citadel', itemType.building, 1, None, 'Progressive TombKing Building: Citadel'),
    47303: itemData(IC.useful, 3, 'Progressive tmb_defence_major', itemType.building, 3, None, 'Progressive TombKing Building: Defence Major'),
    47304: itemData(IC.useful, 2, 'Progressive tmb_defence_minor', itemType.building, 2, None, 'Progressive TombKing Building: Defence Minor'),
    47305: itemData(IC.useful, 1, 'Progressive tmb_estate', itemType.building, 1, None, 'Progressive TombKing Building: Estate'),
    47306: itemData(IC.useful, 3, 'Progressive tmb_growth', itemType.building, 3, None, 'Progressive TombKing Building: Growth'),
    47307: itemData(IC.useful, 1, 'Progressive tmb_hierotitan', itemType.building, 2, None, 'Progressive TombKing Building: Hierotitan'),
    47308: itemData(IC.useful, 3, 'Progressive tmb_income', itemType.building, 3, None, 'Progressive TombKing Building: Income'),
    47309: itemData(IC.useful, 3, 'Progressive tmb_infantry', itemType.building, 3, None, 'Progressive TombKing Building: Infantry'),
    47310: itemData(IC.useful, 1, 'Progressive tmb_necrosphinx', itemType.building, 2, None, 'Progressive TombKing Building: Necrosphinx'),
    47311: itemData(IC.useful, 3, 'Progressive tmb_port', itemType.building, 3, None, 'Progressive TombKing Building: Port'),
    47312: itemData(IC.useful, 3, 'Progressive tmb_public_order', itemType.building, 3, None, 'Progressive TombKing Building: Public Order'),
    47313: itemData(IC.useful, 1, 'Progressive tmb_resource_animals', itemType.building, 1, None, 'Progressive TombKing Building: Animals'),
    47314: itemData(IC.useful, 1, 'Progressive tmb_resource_dyes', itemType.building, 1, None, 'Progressive TombKing Building: Dyes'),
    47315: itemData(IC.useful, 1, 'Progressive tmb_resource_furs', itemType.building, 1, None, 'Progressive TombKing Building: Furs'),
    47316: itemData(IC.useful, 1, 'Progressive tmb_resource_gems', itemType.building, 1, None, 'Progressive TombKing Building: Gems'),
    47317: itemData(IC.useful, 1, 'Progressive tmb_resource_gold', itemType.building, 1, None, 'Progressive TombKing Building: Gold'),
    47318: itemData(IC.useful, 1, 'Progressive tmb_resource_iron', itemType.building, 1, None, 'Progressive TombKing Building: Iron'),
    47319: itemData(IC.useful, 1, 'Progressive tmb_resource_marble', itemType.building, 1, None, 'Progressive TombKing Building: Marble'),
    47320: itemData(IC.useful, 1, 'Progressive tmb_resource_medicine', itemType.building, 1, None, 'Progressive TombKing Building: Medicine'),
    47321: itemData(IC.useful, 1, 'Progressive tmb_resource_obsidian', itemType.building, 1, None, 'Progressive TombKing Building: Obsidian'),
    47322: itemData(IC.useful, 1, 'Progressive tmb_resource_pasture', itemType.building, 1, None, 'Progressive TombKing Building: Pasture'),
    47323: itemData(IC.useful, 1, 'Progressive tmb_resource_pottery', itemType.building, 1, None, 'Progressive TombKing Building: Pottery'),
    47324: itemData(IC.useful, 1, 'Progressive tmb_resource_salt', itemType.building, 1, None, 'Progressive TombKing Building: Salt'),
    47325: itemData(IC.useful, 1, 'Progressive tmb_resource_spices', itemType.building, 1, None, 'Progressive TombKing Building: Spices'),
    47326: itemData(IC.useful, 1, 'Progressive tmb_resource_wine', itemType.building, 1, None, 'Progressive TombKing Building: Wine'),
    47327: itemData(IC.useful, 1, 'Progressive tmb_resource_wood', itemType.building, 1, None, 'Progressive TombKing Building: Wood'),
    47328: itemData(IC.useful, 1, 'Progressive tmb_scorpions', itemType.building, 1, None, 'Progressive TombKing Building: Scorpions'),
    47329: itemData(IC.useful, 5, 'Progressive tmb_settlement_major', itemType.building, 5, None, 'Progressive TombKing Building: Settlement Major'),
    47330: itemData(IC.useful, 3, 'Progressive tmb_settlement_minor', itemType.building, 3, None, 'Progressive TombKing Building: Settlement Minor'),
    47331: itemData(IC.useful, 2, 'Progressive tmb_ushabti', itemType.building, 2, None, 'Progressive TombKing Building: Ushabti'),
    47332: itemData(IC.useful, 1, 'Progressive tmb_warsphinx', itemType.building, 2, None, 'Progressive TombKing Building: Warsphinx'),
    47333: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_tmb', itemType.building, 3, None, 'Progressive TombKing Building: Foreign Slot Discovery Tmb'),
    47334: itemData(IC.useful, 3, 'Progressive tmb_allied_outpost', itemType.building, 3, None, 'Progressive TombKing Building: Allied Outpost'),
    47335: itemData(IC.useful, 1, 'Progressive tmb_resource_ivory', itemType.building, 1, None, 'Progressive TombKing Building: Ivory')
}

progTechs: dict[int, itemData] = {
    47400: itemData(IC.useful, 3, "Progressive tech_tmb_1", itemType.tech, 3, None, "Progressive TombKing Tech: First Dynasty"),
    47401: itemData(IC.useful, 3, "Progressive tech_tmb_2", itemType.tech, 3, None, "Progressive TombKing Tech: Second Dynasty"),
    47402: itemData(IC.useful, 3, "Progressive tech_tmb_3", itemType.tech, 3, None, "Progressive TombKing Tech: Third Dynasty"),
    47403: itemData(IC.useful, 3, "Progressive tech_tmb_4", itemType.tech, 3, None, "Progressive TombKing Tech: Fourth Dynasty"),
    47404: itemData(IC.useful, 3, "Progressive tech_tmb_5", itemType.tech, 3, None, "Progressive TombKing Tech: Fifth Dynasty"),
    47405: itemData(IC.useful, 3, "Progressive tech_tmb_6", itemType.tech, 3, None, "Progressive TombKing Tech: Sixth Dynasty"),
    47406: itemData(IC.useful, 2, "Progressive tech_tmb_herald", itemType.tech, 2, None, "Progressive TombKing Tech: Heralds")

}

special: dict[int, specialItemData] = {
    47500: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_army_capacity_25", itemType.effect_faction, 0, None, True, False, "TombKing Effect: +1 Army Capacity"),
    47501: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_inf_crypt_ghouls", itemType.unit, 1, "Progressive tmb_inf", False, False, "TombKing Unit: Crypt Ghouls"),
    47502: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_cav_hexwraiths", itemType.unit, 3, "Progressive tmb_cav", False, False, "TombKing Unit: Hexwraiths"),
    47503: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_mon_dire_wolves", itemType.unit, 1, "Progressive tmb_bst", False, False, "TombKing Unit: Hexwraiths"),
    47504: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_mon_fell_bats", itemType.unit, 1, "Progressive tmb_bst", False, False, "TombKing Unit: Hexwraiths"),
    46505: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_arkhan_burial_mound", itemType.building, 0, "Progressive tmb_creatures", False, False, "TombKing Building: Grave Hill"),
    46506: specialItemData(IC.useful, 1, ["wh2_dlc09_tmb_followers_of_nagash"], "wh2_dlc09_tmb_arkhan_burial_mound_2", itemType.building, 1, "Progressive tmb_creatures", False, False, "TombKing Building: Ancient Burial Mound"),
    46507: specialItemData(IC.useful, 2, ["wh2_dlc09_tmb_followers_of_nagash"], "Progressive tmb_creatures", itemType.building, 2, "Progressive tmb_creatures", False, True, "Progressive TombKing Building: Dark Creatures")
}

rituals: dict[int, specialItemData] = {
    46600: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_blade_of_antarhak", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Blade of Antarhak"),
    46601: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_blade_of_mourning_fire", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Blade of Mourning Fire"),
    46602: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_blade_of_setep", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Blade of Setep"),
    46603: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_crook_and_flail_of_radiance", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Crook & Flail of Radiance"),
    46604: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_destroyer_of_eternities", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Destroyer of Eternities"),
    46605: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_double_crescent_of_neru", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Double Crescent of Neru"),
    46606: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_enchanted_lapis_mace", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Enchanted Lapis Mace"),
    46607: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_fang_of_quaph", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Fang of Qu'aph"),
    46608: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_golden_dagger", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Golden Dagger"),
    46609: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_inscribed_khopesh", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Inscribed Khopesh"),
    46610: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_weapon_spear_of_pakth", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_weapons", False, False, "TombKing Mortuary Cult: Spear of Pakth"),

    46611: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_armour_of_dawn", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Armour of Dawn"),
    46612: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_armour_of_eternity", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Armour of Eternity"),
    46613: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_armour_of_the_ages", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Armour of the Ages"),
    46614: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_helmet_of_khsar", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Helmet of Khsar"),
    46615: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_mortuary_robes", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Mortuary Robes"),
    46616: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_scorpion_armour", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Scorpion Armour"),
    46617: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_shield_of_ptra", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Shield of Ptra"),
    46618: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_armour_skull_cap_of_the_moon", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_armour", False, False, "TombKing Mortuary Cult: Skull Cap of the Moon"),

    46619: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_brooch_of_the_great_desert", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Brooch of the Great Desert"),
    46620: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_death_mask_of_kharnut", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Death Mask of Kharnut"),
    46621: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_elixir_of_might", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Elixir of Might"),
    46622: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_hieratic_jar", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Hieratic Jar"),
    46623: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_icon_of_rulership", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Icon of Rulership"),
    46624: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_ouroboros", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Ouroboros"),
    46625: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_potion_of_foolhardiness", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Potion of Foolhardiness"),
    46626: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_potion_of_speed", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Potion of Speed"),
    46627: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_potion_of_strength", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Potion of Strength"),
    46628: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_potion_of_toughness", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Potion of Toughness"),
    46629: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_shroud_of_sokth", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Shroud of Sokth"),
    46630: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_enchanted_item_vambraces_of_the_sun", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_enchanted", False, False, "TombKing Mortuary Cult: Vambraces of the Sun"),

    46631: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_amulet_of_pha_stah", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Amulet of Pha-Stah"),
    46632: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_collar_of_shakkara", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Collar of Shakkara"),
    46633: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_dawnstone", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Sun Scarab"),
    46634: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_golden_ankhra", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Golden Ankhra"),
    46635: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_golden_eye_of_rah_nutt", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Golden Eye of Rah-Nutt"),
    46636: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_talisman_obsidian_lodestone", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_talisman", False, False, "TombKing Mortuary Cult: Obsidian Pendant"),

    46637: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_blue_khepra", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Blue Khepra"),
    46638: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_enkhils_kanopi", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Enkhil's Kanopi"),
    46639: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_neferras_scrolls_of_mighty_incantations", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Neferra's Scrolls of Mighty Incantations"),
    46640: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_power_scroll", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Scroll of Power"),
    46641: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_scroll_of_leeching", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Scroll of Leeching"),
    46642: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_arcane_item_scroll_of_shielding", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Scroll of Shielding"),
    46643: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_arcane_item_viziers_kanopi", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_arcane", False, False, "TombKing Mortuary Cult: Vizier's Kanopi"),

    46644: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_centuries_sigil", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Indefatigable Pennant"),
    46645: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_cursing_word", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Emblem of Withering"),
    46646: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_khsar_fury", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Standard to Khsar's Fury"),
    46647: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_sacred_eye", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Icon of the Sacred Eye"),
    46648: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_settra_banner", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Royal Standard of Settra"),
    46649: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_ualatp_order", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_banner", False, False, "TombKing Mortuary Cult: Ualatp's Order"),

    46650: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_army_capacity", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: A New Dynasty"),
    46651: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_carrion", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: The Flock of Djaf (Carrions)"),
    46652: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_necropolis_knights", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: Venom Knights of Asaph (Necropolis Knights)"),
    46653: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_nehekhara_horsemen", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: Storm Riders of Khsar (Nehekhara Horsemen)"),
    46654: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_crafting_tmb_nehekhara_warriors", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: Usirian's Legion of the Netherworld (Nehekhara Warriors)"),
    46655: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_liche_priest_capacity", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: A New Servant (Liche Priest)"),
    46656: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_necrotect_capacity", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: A New Servant (Necrotect)"),
    46657: specialItemData(IC.useful, 1, [], "wh3_main_ritual_crafting_tmb_prince_capacity", itemType.ritual, 1, "Progressive tmb_ritual_mortuary_dynasty", False, False, "TombKing Mortuary Cult: A New Servant (Tomb Prince)"),

    46658: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_tmb_geheb", itemType.ritual, 1, "Progressive tmb_ritual_rite", False, False, "TombKing Rite: Great Incantation of Geheb"),
    46659: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_tmb_khsar", itemType.ritual, 1, "Progressive tmb_ritual_rite", False, False, "TombKing Rite: Great Incantation of Khsar"),
    46660: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_tmb_ptra", itemType.ritual, 1, "Progressive tmb_ritual_rite", False, False, "TombKing Rite: Great Incantation of Ptra"),
    46661: specialItemData(IC.useful, 1, [], "wh2_dlc09_ritual_tmb_tahoth", itemType.ritual, 1, "Progressive tmb_ritual_rite", False, False, "TombKing Rite: Great Incantation of Tahoth"),
}