from BaseClasses import ItemClassification as IC
from worlds.tww3.dataStructs import itemType, itemData, specialItemData
# @formatter:off

#74000
units: dict[int, itemData] = {
    74000: itemData(IC.useful, 1, 'wh_main_vmp_inf_zombie', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Zombies'),
    74001: itemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_1', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Skeleton Spearmen'),
    74002: itemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Skeleton Warriors'),
    74003: itemData(IC.useful, 1, 'wh_main_vmp_inf_crypt_ghouls', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Crypt Ghouls'),
    74004: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_warriors_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Skeleton Warriors'),
    74005: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Skeleton Spearmen'),
    74006: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Nehekharan Warriors'),
    74007: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Zombie Pirate Deckhand Mob'),
    74008: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_1', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: Zombie Pirate Deckhand Mob (Polearms)'),
    74009: itemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_0', itemType.unit, 2, 'Progressive nag_inf', 'Nagash Unit: Grave Guard'),
    74010: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_0', itemType.unit, 2, 'Progressive nag_inf', 'Nagash Unit: Tomb Guard'),
    74011: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_0', itemType.unit, 2, 'Progressive nag_inf', 'Nagash Unit: Ushabti'),
    74012: itemData(IC.useful, 1, 'wh3_main_vmp_inf_grave_guard_2', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Grave Guard (Halberds)'),
    74013: itemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_1', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Grave Guard (Great Weapons)'),
    74014: itemData(IC.useful, 1, 'wh_main_vmp_inf_cairn_wraiths', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Cairn Wraiths'),
    74015: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_1', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Tomb Guard (Halberds)'),
    74016: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_syreens', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Syreens'),
    74017: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_0', itemType.unit, 4, 'Progressive nag_inf', 'Nagash Unit: Depth Guard'),
    74018: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_1', itemType.unit, 4, 'Progressive nag_inf', 'Nagash Unit: Depth Guard (Polearms)'),
    74019: itemData(IC.useful, 1, 'wh3_dlc29_vmp_inf_lahmian_handmaidens_death', itemType.unit, 5, 'Progressive nag_inf', 'Nagash Unit: Lahmian Handmaidens (Death)'),
    74020: itemData(IC.useful, 1, 'wh3_dlc29_vmp_inf_lahmian_handmaidens_shadow', itemType.unit, 5, 'Progressive nag_inf', 'Nagash Unit: Lahmian Handmaidens (Shadows)'),

    74021: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_0', itemType.unit, 1, 'Progressive nag_rng', 'Nagash Unit: Skeleton Archers'),
    74022: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_0', itemType.unit, 1, 'Progressive nag_rng', 'Nagash Unit: Zombie Pirate Gunnery Mob'),
    74023: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_3', itemType.unit, 1, 'Progressive nag_rng', 'Nagash Unit: Zombie Pirate Gunnery Mob (Bombers)'),
    74024: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_1', itemType.unit, 2, 'Progressive nag_rng', 'Nagash Unit: Ushabti (Great Bows)'),
    74025: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_1', itemType.unit, 2, 'Progressive nag_rng', 'Nagash Unit: Zombie Pirate Gunnery Mob (Handgunners)'),
    74026: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_2', itemType.unit, 2, 'Progressive nag_rng', 'Nagash Unit: Zombie Pirate Gunnery Mob (Hand Cannons)'),
    74027: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_deck_gunners_0', itemType.unit, 3, 'Progressive nag_rng', 'Nagash Unit: Deck Gunners'),
    74028: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_0', itemType.unit, 4, 'Progressive nag_rng', 'Nagash Unit: Rotting Prometheans (Gunnery Mob)'),

    74029: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_0', itemType.unit, 1, 'Progressive nag_cav', 'Nagash Unit: Skeleton Horsemen'),
    74030: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0', itemType.unit, 1, 'Progressive nag_cav', 'Nagash Unit: Skeleton Horse Archers'),
    74031: itemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_0', itemType.unit, 1, 'Progressive nag_cav', 'Nagash Unit: Deck Droppers'),
    74032: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_0', itemType.unit, 2, 'Progressive nag_cav', 'Nagash Unit: Nehekharan Horsemen'),
    74033: itemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_1', itemType.unit, 2, 'Progressive nag_cav', 'Nagash Unit: Deck Droppers (Bombers)'),
    74034: itemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_0', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Black Knights'),
    74035: itemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_3', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Black Knights (Lances & Barding)'),
    74036: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_0', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Sepulchral Stalkers'),
    74037: itemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_2', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Deck Droppers (Handgunners)'),
    74038: itemData(IC.useful, 1, 'wh_main_vmp_cav_hexwraiths', itemType.unit, 4, 'Progressive nag_cav', 'Nagash Unit: Hexwraiths'),
    74039: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_0', itemType.unit, 4, 'Progressive nag_cav', 'Nagash Unit: Necropolis Knights'),
    74040: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_1', itemType.unit, 4, 'Progressive nag_cav', 'Nagash Unit: Necropolis Knights (Halberds)'),
    74041: itemData(IC.useful, 1, 'wh3_main_vmp_blood_knights_sword_shield', itemType.unit, 5, 'Progressive nag_cav', 'Nagash Unit: Blood Knights'),
    74042: itemData(IC.useful, 1, 'wh_dlc02_vmp_cav_blood_knights_0', itemType.unit, 5, 'Progressive nag_cav', 'Nagash Unit: Blood Knights (Lances)'),

    74043: itemData(IC.useful, 1, 'wh2_dlc11_cst_art_mortar', itemType.unit, 1, 'Progressive nag_art', 'Nagash Unit: Mortars'),
    74044: itemData(IC.useful, 1, 'wh2_dlc11_cst_art_carronade', itemType.unit, 1, 'Progressive nag_art', 'Nagash Unit: Carronades'),
    74045: itemData(IC.useful, 1, 'wh2_dlc09_tmb_art_screaming_skull_catapult_0', itemType.unit, 2, 'Progressive nag_art', 'Nagash Unit: Screaming Skull Catapults'),
    74046: itemData(IC.useful, 1, 'wh2_dlc09_tmb_art_casket_of_souls_0', itemType.unit, 2, 'Progressive nag_art', 'Nagash Unit: Casket of Souls'),
    74047: itemData(IC.useful, 1, 'wh2_pro06_tmb_mon_bone_giant_0', itemType.unit, 3, 'Progressive nag_art', 'Nagash Unit: Bone Giant'),
    
    74048: itemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_0', itemType.unit, 1, 'Progressive nag_veh', 'Nagash Unit: Corpse Cart'),
    74049: itemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_1', itemType.unit, 2, 'Progressive nag_veh', 'Nagash Unit: Corpse Cart (Balefire)'),
    74050: itemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_chariot_0', itemType.unit, 2, 'Progressive nag_veh', 'Nagash Unit: Skeleton Chariots'),
    74051: itemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_archer_chariot_0', itemType.unit, 2, 'Progressive nag_veh', 'Nagash Unit: Skeleton Archer Chariots'),
    74052: itemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_2', itemType.unit, 3, 'Progressive nag_veh', 'Nagash Unit: Corpse Cart (Unholy Lodestone)'),
    74053: itemData(IC.useful, 1, 'wh_main_vmp_veh_black_coach', itemType.unit, 3, 'Progressive nag_veh', 'Nagash Unit: Black Coach'),
    74054: itemData(IC.useful, 1, 'wh_dlc04_vmp_veh_mortis_engine_0', itemType.unit, 4, 'Progressive nag_veh', 'Nagash Unit: Mortis Engine'),

    74055: itemData(IC.useful, 1, 'wh_main_vmp_mon_fell_bats', itemType.unit, 1, 'Progressive nag_bst', 'Nagash Unit: Fell Bats'),
    74056: itemData(IC.useful, 1, 'wh_main_vmp_mon_dire_wolves', itemType.unit, 1, 'Progressive nag_bst', 'Nagash Unit: Dire Wolves'),
    74057: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_0', itemType.unit, 1, 'Progressive nag_bst', 'Nagash Unit: Carrion'),
    74058: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_bloated_corpse_0', itemType.unit, 1, 'Progressive nag_bst', 'Nagash Unit: Bloated Corpse'),
    74059: itemData(IC.useful, 1, 'wh_main_vmp_mon_crypt_horrors', itemType.unit, 2, 'Progressive nag_bst', 'Nagash Unit: Crypt Horrors'),
    74060: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_mournguls_0', itemType.unit, 2, 'Progressive nag_bst', 'Nagash Unit: Mournguls'),
    74061: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_tomb_scorpion_0', itemType.unit, 2, 'Progressive nag_bst', 'Nagash Unit: Tomb Scorpion'),
    74062: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_animated_hulks_0', itemType.unit, 2, 'Progressive nag_bst', 'Nagash Unit: Animated Hulks'),
    74063: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_0', itemType.unit, 2, 'Progressive nag_bst', 'Nagash Unit: Rotting Prometheans'),
    74064: itemData(IC.useful, 1, 'wh_main_vmp_mon_vargheists', itemType.unit, 3, 'Progressive nag_bst', 'Nagash Unit: Vargheists'),
    74065: itemData(IC.useful, 1, 'wh_main_vmp_mon_varghulf', itemType.unit, 3, 'Progressive nag_bst', 'Nagash Unit: Varghulf'),
    74066: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_khemrian_warsphinx_0', itemType.unit, 4, 'Progressive tmb_bst', 'Nagash Unit: Warsphinx'),
    74067: itemData(IC.useful, 1, 'wh_main_vmp_mon_terrorgheist', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Terrorgheist'),
    74068: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_0', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Necrosphinx'),
    74069: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_heirotitan_0', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Hierotitan'),
    74070: itemData(IC.useful, 1, 'wh3_dlc29_tmb_mon_khemric_titan', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Khemric Titan'),
    74071: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_leviathan_0', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Rotting Leviathan'),
    74072: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_necrofex_colossus_0', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Necrofex Colossus'),

    #52049: itemData(IC.useful, 1, 'wh_dlc04_vmp_veh_claw_of_nagash_0', itemType.unit, 4, 'Progressive nag_veh', 'Nagash Unit: The Claw of Nagash (Mortis Engine)'),
    #52050: itemData(IC.useful, 1, 'wh_dlc04_vmp_mon_direpack_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: The Direpack (Dire Wolves)'),
    #52051: itemData(IC.useful, 1, 'wh_dlc04_vmp_mon_devils_swartzhafen_0', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: The Devils of Swartzhafen (Vargheists)'),
    #52052: itemData(IC.useful, 1, 'wh_dlc04_vmp_inf_tithe_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: The Tithe (Zombies)'),
    #52053: itemData(IC.useful, 1, 'wh_dlc04_vmp_inf_sternsmen_0', itemType.unit, 2, 'Progressive nag_inf', 'Nagash Unit: The Sternsmen (Grave Guard)'),
    #52054: itemData(IC.useful, 1, 'wh_dlc04_vmp_inf_konigstein_stalkers_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: The Konigstein Stalkers (Skeleton Warriors)'),
    #52055: itemData(IC.useful, 1, 'wh_dlc04_vmp_inf_feasters_in_the_dusk_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: The Feasters in the Dusk (Crypt Ghouls)'),
    #52056: itemData(IC.useful, 1, 'wh_dlc04_vmp_cav_vereks_reavers_0', itemType.unit, 2, 'Progressive nag_cav', "Nagash Unit: Verek's Reavers (Black Knights - Lances & Barding)"),
    #52057: itemData(IC.useful, 1, 'wh_dlc04_vmp_cav_chillgheists_0', itemType.unit, 2, 'Progressive nag_cav', 'Nagash Unit: The Chillgheists (Hexwraiths)'),

    #50031: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_ror_0', itemType.unit, 4, 'Progressive nag_inf', 'Nagash Unit: The Bloody Reaver Deck Guard (Depth Guard)'),
    #50032: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_deck_gunners_ror_0', itemType.unit, 4, 'Progressive nag_rng', 'Nagash Unit: Shadewraith Gunners (Deck Gunners)'),
    #50033: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_ror_0', itemType.unit, 1, 'Progressive nag_inf', 'Nagash Unit: The Tide of Skjold (Zombie Pirate Deckhand Mob)'),
    #50034: itemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_ror_0', itemType.unit, 2, 'Progressive nag_rng', 'Nagash Unit: The Black Spot (Zombie Pirate Gunnery Mob - Handgunners)'),
    #50035: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_mournguls_ror_0', itemType.unit, 3, 'Progressive nag_inf', 'Nagash Unit: Night Terrors (Mournguls)'),
    #50036: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_necrofex_colossus_ror_0', itemType.unit, 5, 'Progressive nag_bst', 'Nagash Unit: Gallows Giant (Necrofex Colossus)'),
    #50037: itemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_ror', itemType.unit, 4, 'Progressive nag_bst', "Nagash Unit: The Lamprey's Revenge (Rotting Promethean Gunnery Mob)"),
    #50038: itemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_ror_0', itemType.unit, 2, 'Progressive nag_cav', 'Nagash Unit: Salt Lord Scuttlers (Deck Droppers - Bombers)')

    #46029: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_ror', itemType.unit, 1, 'Progressive nag_bst', 'Nagash Unit: The Flock of Djaf (Carrion)'),
    #46030: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_ror', itemType.unit, 2, 'Progressive nag_rng', 'Nagash Unit: Chosen of the Gods (Ushabti - Great Bows)'),
    #46031: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_ror', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Eyes of the Desert (Sepulchral Stalkers)'),
    #46032: itemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_ror', itemType.unit, 3, 'Progressive nag_bst', 'Nagash Unit: The Sphinx of Usekph (Necrosphinx)'),
    #46033: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_ror', itemType.unit, 2, 'Progressive nag_inf', 'Nagash Unit: The Khepra Guard (Tomb Guard)'),
    #46034: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_ror', itemType.unit, 1, 'Progressive nag_inf', "Nagash Unit: King Nekhesh's Scorpion Legion (Skeleton Spearmen)"),
    #46035: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_ror', itemType.unit, 1, 'Progressive nag_rng', 'Nagash Unit: Blessed Legion of Phakth (Skeleton Archers)'),
    #46036: itemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_ror', itemType.unit, 1, 'Progressive nag_inf', "Nagash Unit: Usirian's Legion of the Netherworld (Nehekharan Warriors)"),
    #46037: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_ror', itemType.unit, 2, 'Progressive nag_cav', 'Nagash Unit: Storm Riders of Khsar (Nehekharan Horsemen)'),
    #46038: itemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_ror', itemType.unit, 3, 'Progressive nag_cav', 'Nagash Unit: Venom Knights of Asaph (Necropolis Knights)')
    #46037: itemData(IC.useful, 1, 'wh3_dlc29_tmb_mon_khemric_titan_ror', itemType.unit, 3, 'Progressive tmb_bst', 'Nagash Unit: Icon of Usirian (Khemric Titan)'),
}

buildings: dict[int, itemData] = {
    74400: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_corruption_1', itemType.building, 0, 'Progressive nag_necropolis_corruption', "Nagash Building: Chambers of the Risen"),
    74401: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_corruption_2', itemType.building, 1, 'Progressive nag_necropolis_corruption', "Nagash Building: Hallways of the Twice-risen"),
    74402: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_corruption_3', itemType.building, 2, 'Progressive nag_necropolis_corruption', "Nagash Building: Wing of the Undying"),
    74403: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_dark_magic_1', itemType.building, 0, 'Progressive nag_necropolis_dark_magic', "Nagash Building: The Place of Endings"),
    74404: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_dark_magic_2', itemType.building, 1, 'Progressive nag_necropolis_dark_magic', "Nagash Building: Leeching Obelisks"),
    74405: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_dark_magic_3', itemType.building, 2, 'Progressive nag_necropolis_dark_magic', "Nagash Building: Walls of Eternity"),
    74406: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_dark_magic_4', itemType.building, 3, 'Progressive nag_necropolis_dark_magic', "Nagash Building: Vistas of Desolation"),
    74407: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_dark_magic_5', itemType.building, 4, 'Progressive nag_necropolis_dark_magic', "Nagash Building: Currents of Emptiness"),
    74408: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_garrison_1', itemType.building, 0, 'Progressive nag_necropolis_garrison', "Nagash Building: Battlements of the Undead"),
    74409: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_garrison_2', itemType.building, 1, 'Progressive nag_necropolis_garrison', "Nagash Building: Gates of the Fell Riders"),
    74410: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_garrison_3', itemType.building, 2, 'Progressive nag_necropolis_garrison', "Nagash Building: Ancient Armories"),
    74411: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_garrison_4', itemType.building, 3, 'Progressive nag_necropolis_garrison', "Nagash Building: Screaming Entrenchments"),
    74412: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_artillery_1', itemType.building, 0, 'Progressive nag_necropolis_artillery', "Nagash Building: Black Powder Drifts"),
    74413: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_artillery_2', itemType.building, 1, 'Progressive nag_necropolis_artillery', "Nagash Building: Reliquary Expanse"),
    74414: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_artillery_3', itemType.building, 2, 'Progressive nag_necropolis_artillery', "Nagash Building: Titanic Weapon-Yard"),
    74415: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_artillery_4', itemType.building, 3, 'Progressive nag_necropolis_artillery', "Nagash Building: Unholy Nexus"),
    74416: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_cavalry_1', itemType.building, 0, 'Progressive nag_necropolis_cavalry', "Nagash Building: Bone Repository"),
    74417: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_cavalry_2', itemType.building, 1, 'Progressive nag_necropolis_cavalry', "Nagash Building: Crypt Stables"),
    74418: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_cavalry_3', itemType.building, 2, 'Progressive nag_necropolis_cavalry', "Nagash Building: Statuary Passage"),
    74419: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_cavalry_4', itemType.building, 3, 'Progressive nag_necropolis_cavalry', "Nagash Building: Ornamental Passage"),
    74420: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_constructs_1', itemType.building, 0, 'Progressive nag_necropolis_constructs', "Nagash Building: Unliving Statuary"),
    74421: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_constructs_2', itemType.building, 1, 'Progressive nag_necropolis_constructs', "Nagash Building: Vault of Reckoning"),
    74422: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_constructs_3', itemType.building, 2, 'Progressive nag_necropolis_constructs', "Nagash Building: Cavern of Hollow Predators"),
    74423: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_constructs_4', itemType.building, 3, 'Progressive nag_necropolis_constructs', "Nagash Building: Chamber of the Servant Gods"),
    74424: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_melee_1', itemType.building, 0, 'Progressive nag_necropolis_melee', "Nagash Building: Warrior Forges"),
    74425: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_melee_2', itemType.building, 1, 'Progressive nag_necropolis_melee', "Nagash Building: Tombs of Vigilance"),
    74426: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_melee_3', itemType.building, 2, 'Progressive nag_necropolis_melee', "Nagash Building: Galleries of Observance"),
    74427: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_melee_4', itemType.building, 3, 'Progressive nag_necropolis_melee', "Nagash Building: Mausoleum of First Mates"),
    74428: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_monsters_1', itemType.building, 0, 'Progressive nag_necropolis_monsters', "Nagash Building: Petrified Grove"),
    74429: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_monsters_2', itemType.building, 1, 'Progressive nag_necropolis_monsters', "Nagash Building: Abyssal Pits"),
    74430: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_monsters_3', itemType.building, 2, 'Progressive nag_necropolis_monsters', "Nagash Building: Heights of Disunion"),
    74431: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_monsters_4', itemType.building, 3, 'Progressive nag_necropolis_monsters', "Nagash Building: Gorge of Fallen Grace"),
    74432: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_monsters_5', itemType.building, 4, 'Progressive nag_necropolis_monsters', "Nagash Building: Caverns of Nature's Surrender"),
    74433: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_ranged_1', itemType.building, 0, 'Progressive nag_necropolis_ranged', "Nagash Building: Whistling Ranges"),
    74434: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_ranged_2', itemType.building, 1, 'Progressive nag_necropolis_ranged', "Nagash Building: Shrieking Ranges"),
    74435: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_ranged_3', itemType.building, 2, 'Progressive nag_necropolis_ranged', "Nagash Building: Booming Ranges"),
    74436: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_ranged_4', itemType.building, 3, 'Progressive nag_necropolis_ranged', "Nagash Building: Sunken Ranges"),
    74437: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_spirits_1', itemType.building, 0, 'Progressive nag_necropolis_spirits', "Nagash Building: Spirit Rent"),
    74438: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_spirits_2', itemType.building, 1, 'Progressive nag_necropolis_spirits', "Nagash Building: Tarn of Terror"),
    74439: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_military_spirits_3', itemType.building, 2, 'Progressive nag_necropolis_spirits', "Nagash Building: Obsidian Promenades"),
    74440: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_1', itemType.building, 0, 'Progressive nag_necropolis_upkeep', "Nagash Building: Shyish Obelisk"),
    74441: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_2b', itemType.building, 1, 'Progressive nag_necropolis_upkeep', "Nagash Building: Ivory Gate"),
    74442: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_2c', itemType.building, 1, 'Progressive nag_necropolis_upkeep', "Nagash Building: Cyclopean Bestiary"),
    74443: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_2', itemType.building, 1, 'Progressive nag_necropolis_upkeep', "Nagash Building: Mirrors of Mortality"),
    74444: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_3a', itemType.building, 2, 'Progressive nag_necropolis_upkeep', "Nagash Building: Fluted Stalagmites"),
    74445: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_3b', itemType.building, 2, 'Progressive nag_necropolis_upkeep', "Nagash Building: Clarion of Silence"),
    74446: itemData(IC.useful, 1, 'wh3_dlc29_nag_necropolis_upkeep_3c', itemType.building, 2, 'Progressive nag_necropolis_upkeep', "Nagash Building: Amethyst Shroud"),
    74447: itemData(IC.useful, 1, 'wh3_dlc29_nag_settlement_necropolis_1', itemType.building, 0, 'Progressive nag_necropolis_settlement_major', "Nagash Building: Crypt Colony"),
    74448: itemData(IC.useful, 1, 'wh3_dlc29_nag_settlement_necropolis_2', itemType.building, 1, 'Progressive nag_necropolis_settlement_major', "Nagash Building: City of Catacombs"),
    74449: itemData(IC.useful, 1, 'wh3_dlc29_nag_settlement_necropolis_3', itemType.building, 2, 'Progressive nag_necropolis_settlement_major', "Nagash Building: Sepulchral Sprawl"),
    74450: itemData(IC.useful, 1, 'wh3_dlc29_nag_settlement_necropolis_4', itemType.building, 3, 'Progressive nag_necropolis_settlement_major', "Nagash Building: Charnel Scape"),
    74451: itemData(IC.useful, 1, 'wh3_dlc29_nag_settlement_necropolis_5', itemType.building, 4, 'Progressive nag_necropolis_settlement_major', "Nagash Building: Great Necropolis"),
    74452: itemData(IC.useful, 1, 'wh3_dlc29_nag_port_1', itemType.building, 0, 'Progressive nag_port', "Nagash Building: Ever-rotting Pier"),
    74453: itemData(IC.useful, 1, 'wh3_dlc29_nag_port_2', itemType.building, 1, 'Progressive nag_port', "Nagash Building: Shoals of Hollow Promise"),
    74454: itemData(IC.useful, 1, 'wh3_dlc29_nag_port_3', itemType.building, 2, 'Progressive nag_port', "Nagash Building: Silent Shipyards"),
    74455: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_animals_1', itemType.building, 0, 'Progressive nag_resopurce_animals', "Nagash Building: Hunting Clearing"),
    74456: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_dyes_1', itemType.building, 0, 'Progressive nag_resource_dyes', "Nagash Building: Red Pit"),
    74457: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_furs_1', itemType.building, 0, 'Progressive nag_resource_furs', "Nagash Building: Death’s Kennels"),
    74458: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_gemstones_1', itemType.building, 0, 'Progressive nag_resource_gemstones', "Nagash Building: Cursed Gemstone Mineshaft"),
    74459: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_gold_1', itemType.building, 0, 'Progressive nag_resource_gold', "Nagash Building: Tarnished Gold Shaft"),
    74460: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_iron_1', itemType.building, 0, 'Progressive nag_resource_iron', "Nagash Building: Dark Iron Pit"),
    74461: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_ivory_1', itemType.building, 0, 'Progressive nag_resource_ivory', "Nagash Building: Ivory Vein"),
    74462: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_marble_1', itemType.building, 0, 'Progressive nag_resource_marble', "Nagash Building: Marble Vein"),
    74463: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_medicine_1', itemType.building, 0, 'Progressive nag_resource_medicine', "Nagash Building: Withering Herb Field"),
    74464: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_obsidian_1', itemType.building, 0, 'Progressive nag_resource_obsidian', "Nagash Building: Obsidian Quarry"),
    74465: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_pastures_1', itemType.building, 0, 'Progressive nag_resource_pastures', "Nagash Building: Cursed Fields"),
    74466: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_pottery_1', itemType.building, 0, 'Progressive nag_resource_pottery', "Nagash Building: Pits of Clay and Bone"),
    74467: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_salt_1', itemType.building, 0, 'Progressive nag_resource_salt', "Nagash Building: Salt Crater"),
    74468: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_spices_1', itemType.building, 0, 'Progressive nag_resource_spices', "Nagash Building: Dust Repository"),
    74469: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_timber_1', itemType.building, 0, 'Progressive nag_resource_timber', "Nagash Building: Felled Forest Patch"),
    74470: itemData(IC.useful, 1, 'wh3_dlc29_nag_resource_wine_1', itemType.building, 0, 'Progressive nag_resource_wine', "Nagash Building: Withered Vines"),
    74471: itemData(IC.useful, 1, 'wh3_dlc29_foreign_slot_discovery_nag_1', itemType.building, 0, 'Progressive nag_foreign_discovery', "Nagash Building: Halls of Forbiddance"),
    74472: itemData(IC.useful, 1, 'wh3_dlc29_foreign_slot_discovery_nag_2', itemType.building, 1, 'Progressive nag_foreign_discovery', "Nagash Building: Halls of Cessation"),
    74473: itemData(IC.useful, 1, 'wh3_dlc29_nag_chambers_control_1', itemType.building, 0, 'Progressive nag_chambers_control', "Nagash Building: Field of Plinths"),
    74474: itemData(IC.useful, 1, 'wh3_dlc29_nag_chambers_garrison_1', itemType.building, 0, 'Progressive nag_chambers_garrison', "Nagash Building: Deserted Lookout"),
    74475: itemData(IC.useful, 1, 'wh3_dlc29_nag_chambers_horsemen_1', itemType.building, 0, 'Progressive nag_chambers_horsemen', "Nagash Building: Fields of Reunification"),
    74476: itemData(IC.useful, 1, 'wh3_dlc29_nag_chambers_income_1', itemType.building, 0, 'Progressive nag_chambers_income', "Nagash Building: Mortuary Quarter"),
    74477: itemData(IC.useful, 1, 'wh3_dlc29_nag_chambers_melee_1', itemType.building, 0, 'Progressive nag_chambers_melee', "Nagash Building: Open Graves"),
    74478: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_dark_power_1', itemType.building, 0, 'Progressive nag_cove_dark_power', "Nagash Building: Lynching Post"),
    74479: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_garrison_1', itemType.building, 0, 'Progressive nag_cove_garrison', "Nagash Building: Walls of Dark Intent"),
    74480: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_military_artillery_1', itemType.building, 0, 'Progressive nag_cove_artillery', "Nagash Building: Cannonry Hoard"),
    74481: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_military_beasts_1', itemType.building, 0, 'Progressive nag_cove_beasts', "Nagash Building: Merciless Shoals"),
    74482: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_military_zombies_1', itemType.building, 0, 'Progressive nag_cove_zombies', "Nagash Building: Rusty Pistol-Trove"),
    74483: itemData(IC.useful, 1, 'wh3_dlc29_nag_cove_trade_1', itemType.building, 0, 'Progressive nag_cove_trade', "Nagash Building: A Hushed Tavern"),
    74484: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_corruption_1', itemType.building, 0, 'Progressive nag_mausoleum_corruption', "Nagash Building: Necromantic Light"),
    74485: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_garrison_1', itemType.building, 0, 'Progressive nag_mausoleum_garrison', "Nagash Building: Corpse Mound"),
    74486: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_military_infantry_1', itemType.building, 0, 'Progressive nag_mausoleum_infantry', "Nagash Building: Pauper’s Graves"),
    74487: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_monsters_1', itemType.building, 0, 'Progressive nag_mausoleum_monsters', "Nagash Building: Groves of Endless Hunger"),
    74488: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_necromantic_1', itemType.building, 0, 'Progressive nag_mausoleum_necromantic', "Nagash Building: Charnel Labyrinth"),
    74489: itemData(IC.useful, 1, 'wh3_dlc29_nag_mausoleum_spirits_1', itemType.building, 0, 'Progressive nag_mausoleum_spirits', "Nagash Building: Altar of Dispossession")
}

#Hahaha, no.
techs: dict[int, itemData] = {}

progUnits: dict[int, itemData] = {
    75200: itemData(IC.useful, 5, "Progressive nag_inf", itemType.unit, 5, None, "Progressive Nagash Unit: Infantry"),
    75201: itemData(IC.useful, 4, "Progressive nag_rng", itemType.unit, 4, None, "Progressive Nagash Unit: Ranged"),
    75202: itemData(IC.useful, 5, "Progressive nag_cav", itemType.unit, 5, None, "Progressive Nagash Unit: Cavalry"),
    75203: itemData(IC.useful, 3, "Progressive nag_art", itemType.unit, 3, None, "Progressive Nagash Unit: Artillery"),
    75204: itemData(IC.useful, 4, "Progressive nag_veh", itemType.unit, 4, None, "Progressive Nagash Unit: Chariot"),
    75205: itemData(IC.useful, 5, "Progressive nag_bst", itemType.unit, 5, None, "Progressive Nagash Unit: Beast"),
}

progBuildings: dict[int, itemData] = {
    75300: itemData(IC.useful, 3, 'Progressive nag_necropolis_corruption', itemType.building, 3, None, "Progressive Nagash Building: Corruption (Necropolis)"),
    75301: itemData(IC.useful, 5, 'Progressive nag_necropolis_dark_magic', itemType.building, 5, None, "Progressive Nagash Building: Dark Magic (Necropolis)"),
    75302: itemData(IC.useful, 4, 'Progressive nag_necropolis_garrison', itemType.building, 3, None, "Progressive Nagash Building: Garrison (Necropolis)"),
    75303: itemData(IC.useful, 4, 'Progressive nag_necropolis_artillery', itemType.building, 3, None, "Progressive Nagash Building: Artillery (Necropolis)"),
    75304: itemData(IC.useful, 4, 'Progressive nag_necropolis_cavalry', itemType.building, 3, None, "Progressive Nagash Building: Cavalry (Necropolis)"),
    75305: itemData(IC.useful, 4, 'Progressive nag_necropolis_constructs', itemType.building, 3, None, "Progressive Nagash Building: Constructs (Necropolis)"),
    75306: itemData(IC.useful, 4, 'Progressive nag_necropolis_melee', itemType.building, 3, None, "Progressive Nagash Building: Melee (Necropolis)"),
    75307: itemData(IC.useful, 5, 'Progressive nag_necropolis_monsters', itemType.building, 4, None, "Progressive Nagash Building: Monsterss (Necropolis)"),
    75308: itemData(IC.useful, 4, 'Progressive nag_necropolis_ranged', itemType.building, 3, None, "Progressive Nagash Building: Ranged (Necropolis)"),
    75309: itemData(IC.useful, 3, 'Progressive nag_necropolis_spirits', itemType.building, 2, None, "Progressive Nagash Building: Spirits (Necropolis)"),
    75310: itemData(IC.useful, 3, 'Progressive nag_necropolis_upkeep', itemType.building, 2, None, "Progressive Nagash Building: Upkeep (Necropolis)"),
    75311: itemData(IC.useful, 5, 'Progressive nag_necropolis_settlement_major', itemType.building, 4, None, "Progressive Nagash Building: Settlement (Necropolis)"),
    75312: itemData(IC.useful, 3, 'Progressive nag_port', itemType.building, 2, None, "Progressive Nagash Building: Port"),
    75313: itemData(IC.useful, 1, 'Progressive nag_resopurce_animals', itemType.building, 0, None, "Progressive Nagash Building: Resource Animals"),
    75314: itemData(IC.useful, 1, 'Progressive nag_resource_dyes', itemType.building, 0, None, "Progressive Nagash Building: Resource Dyes"),
    75315: itemData(IC.useful, 1, 'Progressive nag_resource_furs', itemType.building, 0, None, "Progressive Nagash Building: Resource Furs"),
    75316: itemData(IC.useful, 1, 'Progressive nag_resource_gemstones', itemType.building, 0, None, "Progressive Nagash Building: Resource Gemstones"),
    75317: itemData(IC.useful, 1, 'Progressive nag_resource_gold', itemType.building, 0, None, "Progressive Nagash Building: Resource Gold"),
    75318: itemData(IC.useful, 1, 'Progressive nag_resource_iron', itemType.building, 0, None, "Progressive Nagash Building: Resource Iron"),
    75319: itemData(IC.useful, 1, 'Progressive nag_resource_ivory', itemType.building, 0, None, "Progressive Nagash Building: Resource Ivory"),
    75320: itemData(IC.useful, 1, 'Progressive nag_resource_marble', itemType.building, 0, None, "Progressive Nagash Building: Resource Marble"),
    75321: itemData(IC.useful, 1, 'Progressive nag_resource_medicine', itemType.building, 0, None, "Progressive Nagash Building: Resource Medicine"),
    75322: itemData(IC.useful, 1, 'Progressive nag_resource_obsidian', itemType.building, 0, None, "Progressive Nagash Building: Resource Obsidian"),
    75323: itemData(IC.useful, 1, 'Progressive nag_resource_pastures', itemType.building, 0, None, "Progressive Nagash Building: Resource Pastures"),
    75324: itemData(IC.useful, 1, 'Progressive nag_resource_pottery', itemType.building, 0, None, "Progressive Nagash Building: Resource Pottery"),
    75325: itemData(IC.useful, 1, 'Progressive nag_resource_salt', itemType.building, 0, None, "Progressive Nagash Building: Resource Salt"),
    75326: itemData(IC.useful, 1, 'Progressive nag_resource_spices', itemType.building, 0, None, "Progressive Nagash Building: Resource Spices"),
    75327: itemData(IC.useful, 1, 'Progressive nag_resource_timber', itemType.building, 0, None, "Progressive Nagash Building: Resource Timber"),
    75328: itemData(IC.useful, 1, 'Progressive nag_resource_wine', itemType.building, 0, None, "Progressive Nagash Building: Resource Wine"),
    75329: itemData(IC.useful, 2, 'Progressive nag_foreign_discovery', itemType.building, 1, None, "Progressive Nagash Building: Foreign Discovery"),
    75330: itemData(IC.useful, 1, 'Progressive nag_chambers_control', itemType.building, 0, None, "Progressive Nagash Building: Control (Chambers)"),
    75331: itemData(IC.useful, 1, 'Progressive nag_chambers_garrison', itemType.building, 0, None, "Progressive Nagash Building: Garrison (Chambers)"),
    75332: itemData(IC.useful, 1, 'Progressive nag_chambers_horsemen', itemType.building, 0, None, "Progressive Nagash Building: Horsemen (Chambers)"),
    75333: itemData(IC.useful, 1, 'Progressive nag_chambers_income', itemType.building, 0, None, "Progressive Nagash Building: Income (Chambers)"),
    75334: itemData(IC.useful, 1, 'Progressive nag_chambers_melee', itemType.building, 0, None, "Progressive Nagash Building: Melee (Chambers)"),
    75335: itemData(IC.useful, 1, 'Progressive nag_cove_dark_power', itemType.building, 0, None, "Progressive Nagash Building: Dark Power (Cove)"),
    75336: itemData(IC.useful, 1, 'Progressive nag_cove_garrison', itemType.building, 0, None, "Progressive Nagash Building: Garrison (Cove)"),
    75337: itemData(IC.useful, 1, 'Progressive nag_cove_artillery', itemType.building, 0, None, "Progressive Nagash Building: Artillery (Cove)"),
    75338: itemData(IC.useful, 1, 'Progressive nag_cove_beasts', itemType.building, 0, None, "Progressive Nagash Building: Beasts (Cove)"),
    75339: itemData(IC.useful, 1, 'Progressive nag_cove_zombies', itemType.building, 0, None, "Progressive Nagash Building: Zombies (Cove)"),
    75340: itemData(IC.useful, 1, 'Progressive nag_cove_trade', itemType.building, 0, None, "Progressive Nagash Building: Trade (Cove)"),
    75341: itemData(IC.useful, 1, 'Progressive nag_mausoleum_corruption', itemType.building, 0, None, "Progressive Nagash Building: Corruption (Mausoleum)"),
    75342: itemData(IC.useful, 1, 'Progressive nag_mausoleum_garrison', itemType.building, 0, None, "Progressive Nagash Building: Garrison (Mausoleum)"),
    75343: itemData(IC.useful, 1, 'Progressive nag_mausoleum_infantry', itemType.building, 0, None, "Progressive Nagash Building: Infantry (Mausoleum)"),
    75344: itemData(IC.useful, 1, 'Progressive nag_mausoleum_monsters', itemType.building, 0, None, "Progressive Nagash Building: Monsters (Mausoleum)"),
    75345: itemData(IC.useful, 1, 'Progressive nag_mausoleum_necromantic', itemType.building, 0, None, "Progressive Nagash Building: Necromantic (Mausoleum)"),
    75346: itemData(IC.useful, 1, 'Progressive nag_mausoleum_spirits', itemType.building, 0, None, "Progressive Nagash Building: Spirits (Mausoleum)"),
}

#Hahaha, no.
progTechs: dict[int, itemData] = {}

special: dict[int, specialItemData] = {}

rituals: dict[int, specialItemData] = {}