from BaseClasses import ItemClassification as IC
from worlds.tww3.itemTypes import itemType, itemData, specialItemData
# @formatter:off
units: dict[int, itemData] = {
    54023: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_0', itemType.unit, 1, 'Progressive wef_inf', 'WoodElf Unit: Eternal Guard'),
    54022: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_1', itemType.unit, 1, 'Progressive wef_inf', 'WoodElf Unit: Eternal Guard (Shields)'),
    54018: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_0', itemType.unit, 2, 'Progressive wef_inf', 'WoodElf Unit: Wardancers'),
    54017: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_1', itemType.unit, 2, 'Progressive wef_inf', 'WoodElf Unit: Wardancers (Asrai Spears)'),
    54005: itemData(IC.useful, 1, 'wh2_dlc16_wef_inf_bladesingers_0', itemType.unit, 3, 'Progressive wef_inf', 'WoodElf Unit: Bladesingers'),
    54015: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_wildwood_rangers_0', itemType.unit, 3, 'Progressive wef_inf', 'WoodElf Unit: Wildwood Rangers'),

    54021: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_0', itemType.unit, 1, 'Progressive wef_rng', 'WoodElf Unit: Glade Guard'),
    54019: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_2', itemType.unit, 1, 'Progressive wef_rng', 'WoodElf Unit: Glade Guard (Hagbane Tips)'),
    54020: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_1', itemType.unit, 1, 'Progressive wef_rng', 'WoodElf Unit: Glade Guard (Starfire Shafts)'),
    54026: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_0', itemType.unit, 2, 'Progressive wef_rng', 'WoodElf Unit: Deepwood Scouts'),
    54025: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_1', itemType.unit, 2, 'Progressive wef_rng', 'WoodElf Unit: Deepwood Scouts (Swiftshiver Shards)'),
    54016: itemData(IC.useful, 1, 'wh_dlc05_wef_inf_waywatchers_0', itemType.unit, 3, 'Progressive wef_rng', 'WoodElf Unit: Waywatchers'),

    54057: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_0', itemType.unit, 1, 'Progressive wef_cav', 'WoodElf Unit: Glade Riders'),
    54056: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_1', itemType.unit, 1, 'Progressive wef_cav', 'WoodElf Unit: Glade Riders (Hagbane Tips)'),
    54011: itemData(IC.useful, 1, 'wh2_dlc16_wef_cav_glade_riders_2', itemType.unit, 1, 'Progressive wef_cav', 'WoodElf Unit: Glade Riders (Spears)'),
    54053: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_0', itemType.unit, 2, 'Progressive wef_cav', 'WoodElf Unit: Wild Riders'),
    54052: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_1', itemType.unit, 2, 'Progressive wef_cav', 'WoodElf Unit: Wild Riders (Shields)'),
    54055: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_hawk_riders_0', itemType.unit, 2, 'Progressive wef_cav', 'WoodElf Unit: Hawk Riders'),
    54054: itemData(IC.useful, 1, 'wh_dlc05_wef_cav_sisters_thorn_0', itemType.unit, 3, 'Progressive wef_cav', 'WoodElf Unit: Sisters of the Thorn'),
    54010: itemData(IC.useful, 1, 'wh2_dlc16_wef_cav_great_stag_knights_0', itemType.unit, 4, 'Progressive wef_cav', 'WoodElf Unit: Great Stag Knights'),

    54014: itemData(IC.useful, 1, 'wh_dlc05_wef_mon_great_eagle_0', itemType.unit, 1, 'Progressive wef_inf', 'WoodElf Unit: Great Eagle'),
    54004: itemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats', itemType.unit, 3, 'Progressive wef_bst', 'WoodElf Unit: Zoats'),
    54027: itemData(IC.useful, 1, 'wh_dlc05_wef_forest_dragon_0', itemType.unit, 4, 'Progressive wef_inf', 'WoodElf Unit: Forest Dragon'),

    54003: itemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_0', itemType.unit, 1, 'Progressive wef_hro', 'WoodElf Unit: Glade Captain'),
    54028: itemData(IC.useful, 1, 'wh_dlc05_wef_cha_waystalker_0', itemType.unit, 1, 'Progressive wef_hro', 'WoodElf Unit: Waystalker'),
    54032: itemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_0', itemType.unit, 1, 'Progressive wef_hro', 'WoodElf Unit: Spellsinger (Shadows)'),
    54036: itemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_0', itemType.unit, 1, 'Progressive wef_hro', 'WoodElf Unit: Spellsinger (Life)'),
    54040: itemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_0', itemType.unit, 1, 'Progressive wef_hro', 'WoodElf Unit: Spellsinger (Beasts)'),

    54042: itemData(IC.useful, 1, 'wh2_dlc16_wef_inf_dryads_ror_0', itemType.unit, 1, 'Progressive wef_inf', 'WoodElf Unit: Wraiths of the Frozen Heart (Dryads)'),
    54043: itemData(IC.useful, 1, 'wh2_dlc16_wef_cav_great_stag_knights_ror_0', itemType.unit, 4, 'Progressive wef_cav', 'WoodElf Unit: Lost Sylvan Knights (Great Stag Knights)'),
    54044: itemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats_ror_0', itemType.unit, 3, 'Progressive wef_bst', 'WoodElf Unit: Enigmas of Ghyran (Zoats)'),
    54045: itemData(IC.useful, 1, 'wh_pro04_wef_cav_wild_riders_ror_0', itemType.unit, 2, 'Progressive wef_cav', 'WoodElf Unit: Wild Hunters of Kurnous (Wild Riders – Shields)'),
    54046: itemData(IC.useful, 1, 'wh_pro04_wef_inf_eternal_guard_ror_0', itemType.unit, 1, 'Progressive wef_inf', 'WoodElf Unit: Winterheart Guard (Eternal Guard – Shields)'),
    54047: itemData(IC.useful, 1, 'wh_pro04_wef_inf_wardancers_ror_0', itemType.unit, 2, 'Progressive wef_inf', "WoodElf Unit: Loec's Tricksters (Wardancers – Asrai Spears)"),
    54048: itemData(IC.useful, 1, 'wh_pro04_wef_inf_waywatchers_ror_0', itemType.unit, 3, 'Progressive wef_rng', 'WoodElf Unit: Hawk-Eyes of Drakira (Waywatchers)'),
    54049: itemData(IC.useful, 1, 'wh_pro04_wef_inf_wildwood_rangers_ror_0', itemType.unit, 3, 'Progressive wef_inf', 'WoodElf Unit: Wardens of Cythral (Wildwood Rangers)'),
    54050: itemData(IC.useful, 1, 'wh_pro04_wef_mon_treekin_ror_0', itemType.unit, 2, 'Progressive wef_bst', 'WoodElf Unit: Firebark Elders (Tree Kin)'),
}

buildings: dict[int, itemData] = {
    54400: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_1', itemType.building, 0, 'Progressive foreign_slot_discovery_wef', 'WoodElf Building: Undergrowth Lookouts'),
    54401: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_2', itemType.building, 1, 'Progressive foreign_slot_discovery_wef', 'WoodElf Building: Woodland Trenches'),
    54402: itemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_3', itemType.building, 2, 'Progressive foreign_slot_discovery_wef', 'WoodElf Building: Forest Caves'),
    54403: itemData(IC.useful, 1, 'wh2_main_wef_resource_animals_1', itemType.building, 0, 'Progressive wef_resource_animals', 'WoodElf Building: Exotic Animal Tamer'),
    54404: itemData(IC.useful, 1, 'wh2_main_wef_resource_gems_1', itemType.building, 0, 'Progressive wef_resource_gems', 'WoodElf Building: Gem Mine'),
    54405: itemData(IC.useful, 1, 'wh2_main_wef_resource_medicine_1', itemType.building, 0, 'Progressive wef_resource_medicine', "WoodElf Building: Herb Gatherer's Camp"),
    54406: itemData(IC.useful, 1, 'wh2_main_wef_resource_obsidian_1', itemType.building, 0, 'Progressive wef_resource_obsidian', 'WoodElf Building: Obsidian Quarry'),
    54407: itemData(IC.useful, 1, 'wh2_main_wef_resource_spices_1', itemType.building, 0, 'Progressive wef_resource_spices', 'WoodElf Building: Spice Market'),
    54408: itemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_1', itemType.building, 0, 'Progressive wef_allied_outpost', 'WoodElf Building: Wood Elf Outpost'),
    54409: itemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_2', itemType.building, 1, 'Progressive wef_allied_outpost', 'WoodElf Building: Wood Elf District'),
    54410: itemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_3', itemType.building, 2, 'Progressive wef_allied_outpost', 'WoodElf Building: Wood Elf Colony'),
    54411: itemData(IC.useful, 1, 'wh3_main_wef_resource_ivory_1', itemType.building, 0, 'Progressive wef_resource_ivory', 'WoodElf Building: Animal Store'),
    54412: itemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_1', itemType.building, 0, 'Progressive wef_agent_protection', 'WoodElf Building: Forest Lookouts'),
    54413: itemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_2', itemType.building, 1, 'Progressive wef_agent_protection', 'WoodElf Building: Forest Patrols'),
    54414: itemData(IC.useful, 1, 'wh_dlc05_wef_armoury_1', itemType.building, 0, 'Progressive wef_armoury', 'WoodElf Building: Asrai Forge'),
    54415: itemData(IC.useful, 1, 'wh_dlc05_wef_armoury_2', itemType.building, 1, 'Progressive wef_armoury', 'WoodElf Building: Asrai Armoury'),
    54416: itemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_1', itemType.building, 0, 'Progressive wef_cavalry', 'WoodElf Building: Muster Stone'),
    54417: itemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_2', itemType.building, 1, 'Progressive wef_cavalry', 'WoodElf Building: Grove of the Horse'),
    54418: itemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_3', itemType.building, 2, 'Progressive wef_cavalry', 'WoodElf Building: Pastures of Skymark'),
    54419: itemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_4', itemType.building, 3, 'Progressive wef_cavalry', 'WoodElf Building: Arboreal Paddock'),
    54420: itemData(IC.useful, 1, 'wh_dlc05_wef_flying_1', itemType.building, 0, 'Progressive wef_flying', 'WoodElf Building: Eyrie'),
    54421: itemData(IC.useful, 1, 'wh_dlc05_wef_flying_2', itemType.building, 1, 'Progressive wef_flying', 'WoodElf Building: Warhawk Crags'),
    54422: itemData(IC.useful, 1, 'wh_dlc05_wef_flying_3', itemType.building, 2, 'Progressive wef_flying', 'WoodElf Building: Dragon Lair'),
    54423: itemData(IC.useful, 1, 'wh_dlc05_wef_garrison_1', itemType.building, 0, 'Progressive wef_garrison', 'WoodElf Building: Guard Platform'),
    54424: itemData(IC.useful, 1, 'wh_dlc05_wef_garrison_2', itemType.building, 1, 'Progressive wef_garrison', "WoodElf Building: Arbiter's Perch"),
    54425: itemData(IC.useful, 1, 'wh_dlc05_wef_garrison_3', itemType.building, 2, 'Progressive wef_garrison', "WoodElf Building: Eternal Watcher's Garrison"),
    54426: itemData(IC.useful, 1, 'wh_dlc05_wef_growth_1', itemType.building, 0, 'Progressive wef_growth', "WoodElf Building: Trapper's Den"),
    54427: itemData(IC.useful, 1, 'wh_dlc05_wef_growth_2', itemType.building, 1, 'Progressive wef_growth', 'WoodElf Building: Game Lodge'),
    54428: itemData(IC.useful, 1, 'wh_dlc05_wef_growth_3', itemType.building, 2, 'Progressive wef_growth', "WoodElf Building: Hunter's Vault"),
    54429: itemData(IC.useful, 1, 'wh_dlc05_wef_income_1', itemType.building, 0, 'Progressive wef_income', 'WoodElf Building: Grape Vines'),
    54430: itemData(IC.useful, 1, 'wh_dlc05_wef_income_2', itemType.building, 1, 'Progressive wef_income', 'WoodElf Building: Vineyard'),
    54431: itemData(IC.useful, 1, 'wh_dlc05_wef_income_3', itemType.building, 2, 'Progressive wef_income', 'WoodElf Building: Winery'),
    54432: itemData(IC.useful, 1, 'wh_dlc05_wef_income_4', itemType.building, 3, 'Progressive wef_income', 'WoodElf Building: Wine Nexus'),
    54433: itemData(IC.useful, 1, 'wh_dlc05_wef_melee_1', itemType.building, 0, 'Progressive wef_melee', 'WoodElf Building: Selathoi Gallery'),
    54434: itemData(IC.useful, 1, 'wh_dlc05_wef_melee_2', itemType.building, 1, 'Progressive wef_melee', 'WoodElf Building: Tricksters Gallery'),
    54435: itemData(IC.useful, 1, 'wh_dlc05_wef_melee_3', itemType.building, 2, 'Progressive wef_melee', 'WoodElf Building: Forest Lookout'),
    54436: itemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_1', itemType.building, 1, 'Progressive wef_settlement_major', 'WoodElf Building: Oak of Ages (Dormant)'),
    54437: itemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_2', itemType.building, 2, 'Progressive wef_settlement_major', 'WoodElf Building: Oak of Ages (Withered)'),
    54438: itemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_3', itemType.building, 3, 'Progressive wef_settlement_major', 'WoodElf Building: Oak of Ages (Budding)'),
    54439: itemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_4', itemType.building, 4, 'Progressive wef_settlement_major', 'WoodElf Building: Oak of Ages (Thriving)'),
    54440: itemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_5', itemType.building, 5, 'Progressive wef_settlement_major', 'WoodElf Building: Oak of Ages (Flourishing)'),
    54445: itemData(IC.useful, 1, 'wh_dlc05_wef_outpost_foraging_1', itemType.building, 0, 'Progressive wef_outpost_foraging', 'WoodElf Building: Foraging Groves'),
    54447: itemData(IC.useful, 1, 'wh_dlc05_wef_outpost_recruitment_1', itemType.building, 0, 'Progressive wef_outpost_recruitment', 'WoodElf Building: Worldroot Pathway'),
    54448: itemData(IC.useful, 1, 'wh_dlc05_wef_outpost_replenishment_1', itemType.building, 0, 'Progressive wef_outpost_replenishment', 'WoodElf Building: Waystone'),
    54449: itemData(IC.useful, 1, 'wh_dlc05_wef_outpost_slaughter_1', itemType.building, 0, 'Progressive wef_outpost_slaughter', 'WoodElf Building: Sacrificial Grounds'),
    54450: itemData(IC.useful, 1, 'wh_dlc05_wef_port_1', itemType.building, 0, 'Progressive wef_port', 'WoodElf Building: Elven Haven'),
    54451: itemData(IC.useful, 1, 'wh_dlc05_wef_public_order_1', itemType.building, 0, 'Progressive wef_public_order', "WoodElf Building: Craftmen's Tree"),
    54452: itemData(IC.useful, 1, 'wh_dlc05_wef_public_order_2', itemType.building, 1, 'Progressive wef_public_order', "WoodElf Building: Sculptor's Cavern"),
    54453: itemData(IC.useful, 1, 'wh_dlc05_wef_public_order_3', itemType.building, 2, 'Progressive wef_public_order', "WoodElf Building: Artisan's Nexus"),
    54454: itemData(IC.useful, 1, 'wh_dlc05_wef_ranged_1', itemType.building, 0, 'Progressive wef_ranged', 'WoodElf Building: Glade Guard Hide'),
    54455: itemData(IC.useful, 1, 'wh_dlc05_wef_ranged_2', itemType.building, 1, 'Progressive wef_ranged', 'WoodElf Building: Deepwood Camp'),
    54456: itemData(IC.useful, 1, 'wh_dlc05_wef_ranged_3', itemType.building, 2, 'Progressive wef_ranged', "WoodElf Building: Waywatcher's Perch"),
    54457: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_dyes_1', itemType.building, 0, 'Progressive wef_resource_dyes', 'WoodElf Building: Cinnabar Mining Pit'),
    54458: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_furs_1', itemType.building, 0, 'Progressive wef_resource_furs', 'WoodElf Building: Hunting Camp'),
    54459: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_gold_1', itemType.building, 0, 'Progressive wef_resource_gold', 'WoodElf Building: Gold Mining Pit'),
    54460: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_iron_1', itemType.building, 0, 'Progressive wef_resource_iron', 'WoodElf Building: Iron Mining Pit'),
    54461: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_marble_1', itemType.building, 0, 'Progressive wef_resource_marble', 'WoodElf Building: Stone Cutter'),
    54462: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_pastures_1', itemType.building, 0, 'Progressive wef_resource_pastures', 'WoodElf Building: Cattle Pastures'),
    54463: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_pottery_1', itemType.building, 0, 'Progressive wef_resource_pottery', 'WoodElf Building: Clay Pit'),
    54464: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_salt_1', itemType.building, 0, 'Progressive wef_resource_salt', 'WoodElf Building: Brine Mining Pit'),
    54465: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_timber_1', itemType.building, 0, 'Progressive wef_resource_timber', "WoodElf Building: Woodman's Hut"),
    54466: itemData(IC.useful, 1, 'wh_dlc05_wef_resource_wine_1', itemType.building, 0, 'Progressive wef_resource_wine', 'WoodElf Building: Orchards'),
    54467: itemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_1', itemType.building, 0, 'Progressive wef_settlement_major', 'WoodElf Building: Copse'),
    54468: itemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_2', itemType.building, 1, 'Progressive wef_settlement_major', 'WoodElf Building: Glade'),
    54469: itemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_3', itemType.building, 2, 'Progressive wef_settlement_major', 'WoodElf Building: Hollow'),
    54470: itemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_4', itemType.building, 3, 'Progressive wef_settlement_major', 'WoodElf Building: Hall'),
    54471: itemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_5', itemType.building, 4, 'Progressive wef_settlement_major', 'WoodElf Building: Great Hall'),
    54472: itemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_1', itemType.building, 0, 'Progressive wef_spellsingers', 'WoodElf Building: Roots of Ghyran'),
    54473: itemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_2', itemType.building, 1, 'Progressive wef_spellsingers', 'WoodElf Building: Branches of Ghur'),
    54474: itemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_3', itemType.building, 2, 'Progressive wef_spellsingers', 'WoodElf Building: Canopy of Hysh'),
    54475: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_0', itemType.building, 0, 'Progressive wef_temple_anath_raema', 'WoodElf Building: Sacred Grounds of Anath Raema'),
    54476: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_1', itemType.building, 1, 'Progressive wef_temple_anath_raema', 'WoodElf Building: Temple of Anath Raema'),
    54477: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_ereth_khial_1', itemType.building, 0, 'Progressive wef_temple_ereth_khial', 'WoodElf Building: Temple of Ereth Khial'),
    54478: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_isha_1', itemType.building, 0, 'Progressive wef_temple_isha', 'WoodElf Building: Temple of Isha'),
    54479: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', itemType.building, 0, 'Progressive wef_temple_kurnous', 'WoodElf Building: Temple of Kurnous'),
    54480: itemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', itemType.building, 0, 'Progressive wef_temple_kurnous', 'WoodElf Building: Overgrown Temple of Kurnous'),
    54481: itemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_1', itemType.building, 0, 'Progressive wef_tree_spirits', 'WoodElf Building: Haunted Groves'),
    54482: itemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_2', itemType.building, 1, 'Progressive wef_tree_spirits', 'WoodElf Building: Tribal Stones'),
    54483: itemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_3', itemType.building, 2, 'Progressive wef_tree_spirits', 'WoodElf Building: Nimbus-Shrouded Copse'),
    54484: itemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_4', itemType.building, 3, 'Progressive wef_tree_spirits', 'WoodElf Building: Moonstone Clearing'),
    54485: itemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_1_wef', itemType.building, 0, 'Progressive wef_settlement_major', 'WoodElf Building: Gaean Vale (Copse)'),
    54486: itemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_2_wef', itemType.building, 1, 'Progressive wef_settlement_major', 'WoodElf Building: Gaean Vale (Glade)'),
    54487: itemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_3_wef', itemType.building, 2, 'Progressive wef_settlement_major', 'WoodElf Building: Gaean Vale (Hollow)'),
    54488: itemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_4_wef', itemType.building, 3, 'Progressive wef_settlement_major', 'WoodElf Building: Gaean Vale (Hall)'),
    54489: itemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_5_wef', itemType.building, 4, 'Progressive wef_settlement_major', 'WoodElf Building: Gaean Vale (Great Hall)')
}

techs: dict[int, itemData] = {
    54814: itemData(IC.useful, 1, 'wh_dlc05_tech_2_morai_heg', itemType.tech, 1, 'Progressive tech_wef_cadai', 'WoodElf Tech: Morai-Heg, the Crone'),
    54808: itemData(IC.useful, 1, 'wh_dlc05_tech_1_vaul', itemType.tech, 1, 'Progressive tech_wef_cadai', 'WoodElf Tech: Vaul, the Maker'),
    54823: itemData(IC.useful, 1, 'wh_dlc05_tech_2_ellinill', itemType.tech, 1, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Ellinill, Lord of Destruction'),
    54803: itemData(IC.useful, 1, 'wh_dlc05_tech_1_loec', itemType.tech, 2, 'Progressive tech_wef_cadai', 'WoodElf Tech: Loec, the Trickster'),
    54825: itemData(IC.useful, 1, 'wh_dlc05_tech_2_anath_raema', itemType.tech, 2, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Anath Raema, the Savage Huntress'),
    54804: itemData(IC.useful, 1, 'wh_dlc05_tech_1_ladrielle', itemType.tech, 2, 'Progressive tech_wef_cadai', 'WoodElf Tech: Ladrielle, Lady of Mists'),
    54826: itemData(IC.useful, 1, 'wh_dlc05_tech_2_drakira', itemType.tech, 2, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Drakira, Queen of Vengeance'),
    54800: itemData(IC.useful, 1, 'wh_dlc05_tech_1_isha', itemType.tech, 3, 'Progressive tech_wef_cadai', 'WoodElf Tech: Isha, the Mother'),
    54830: itemData(IC.useful, 1, 'wh_dlc05_tech_2_hukon', itemType.tech, 3, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Hukon, the Sunderer'),
    54805: itemData(IC.useful, 1, 'wh_dlc05_tech_1_hoeth', itemType.tech, 3, 'Progressive tech_wef_cadai', 'WoodElf Tech: Hoeth, Lord of Wisdom'),
    54827: itemData(IC.useful, 1, 'wh_dlc05_tech_2_eldrazor', itemType.tech, 3, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Eldrazor, Lord of Blades'),
    54801: itemData(IC.useful, 1, 'wh_dlc05_tech_2_mathlann', itemType.tech, 4, 'Progressive tech_wef_cadai', 'WoodElf Tech: Mathlann, Lord of the Deeps'),
    54831: itemData(IC.useful, 1, 'wh_dlc05_tech_2_nethu', itemType.tech, 4, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Nethu, Keeper of the Last Door'),
    54806: itemData(IC.useful, 1, 'wh_dlc05_tech_1_kurnous', itemType.tech, 4, 'Progressive tech_wef_cadai', 'WoodElf Tech: Kurnous, the Hunter'),
    54828: itemData(IC.useful, 1, 'wh_dlc05_tech_2_addaioth', itemType.tech, 4, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Addaioth, Bringer of Fire'),
    54802: itemData(IC.useful, 1, 'wh_dlc05_tech_2_estreath', itemType.tech, 5, 'Progressive tech_wef_cadai', 'WoodElf Tech: Estreath, Lord of Hunger'),
    54832: itemData(IC.useful, 1, 'wh_dlc05_tech_2_atharti', itemType.tech, 5, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Atharti, Lady of Desire'),
    54809: itemData(IC.useful, 1, 'wh_dlc05_tech_1_lileath', itemType.tech, 5, 'Progressive tech_wef_cadai', 'WoodElf Tech: Lileath, the Maiden'),
    54824: itemData(IC.useful, 1, 'wh_dlc05_tech_2_ereth_khial', itemType.tech, 5, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Ereth Khial, the Pale Queen'),
    54807: itemData(IC.useful, 1, 'wh_dlc05_tech_1_asuryan', itemType.tech, 6, 'Progressive tech_wef_cadai', 'WoodElf Tech: Asuryan, the Creator'),
    54829: itemData(IC.useful, 1, 'wh_dlc05_tech_2_hekarti', itemType.tech, 6, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Hekarti, Mistress of Magic'),
    54810: itemData(IC.useful, 1, 'wh_dlc05_tech_1_cadai', itemType.tech, 6, 'Progressive tech_wef_cadai', 'WoodElf Tech: Cadai'),
    54822: itemData(IC.useful, 1, 'wh_dlc05_tech_2_cytharai', itemType.tech, 6, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Cytharai'),
    54815: itemData(IC.useful, 1, 'wh_dlc05_tech_2_khaine', itemType.tech, 6, 'Progressive tech_wef_cytharai', 'WoodElf Tech: Khaine, the Bloody-Handed God'),

    54816: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_eagles', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Eagle Lords'),
    54811: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_pine', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Pine'),
    54812: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_poplar', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Poplar'),
    54817: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_willow', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Willow'),
    54818: itemData(IC.useful, 1, 'wh_dlc05_tech_1_the_ancients', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Ancients'),
    54819: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_ash', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Ash'),
    54820: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_yew', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Yew'),
    54821: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_cypress', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Cypress'),
    54813: itemData(IC.useful, 1, 'tech_dlc16_wef_ancients_oak', itemType.tech, 1, 'Progressive tech_wef_wisdom', 'WoodElf Tech: Wisdom of the Oak'),
}

progUnits: dict[int, itemData] = {
    55200: itemData(IC.useful, 3, "Progressive wef_inf", itemType.unit, 3, "", "Progressive WoodElf Unit: Infantry"),
    55201: itemData(IC.useful, 3, "Progressive wef_rng", itemType.unit, 3, "", "Progressive WoodElf Unit: Ranged"),
    55202: itemData(IC.useful, 4, "Progressive wef_cav", itemType.unit, 4, "", "Progressive WoodElf Unit: Cavalry"),
    55205: itemData(IC.useful, 4, "Progressive wef_bst", itemType.unit, 4, "", "Progressive WoodElf Unit: Beast"),
    55206: itemData(IC.useful, 2, "Progressive wef_hro", itemType.unit, 2, "", "Progressive WoodElf Unit: Hero")
}

progBuildings: dict[int, itemData] = {
    55300: itemData(IC.useful, 3, 'Progressive foreign_slot_discovery_wef', itemType.building, 3, None, 'Progressive WoodElf Building: Foreign Slot Discovery Wef'),
    55301: itemData(IC.useful, 1, 'Progressive wef_resource_animals', itemType.building, 1, None, 'Progressive WoodElf Building: Animals'),
    55302: itemData(IC.useful, 1, 'Progressive wef_resource_gems', itemType.building, 1, None, 'Progressive WoodElf Building: Gems'),
    55303: itemData(IC.useful, 1, 'Progressive wef_resource_medicine', itemType.building, 1, None, 'Progressive WoodElf Building: Medicine'),
    55304: itemData(IC.useful, 1, 'Progressive wef_resource_obsidian', itemType.building, 1, None, 'Progressive WoodElf Building: Obsidian'),
    55305: itemData(IC.useful, 1, 'Progressive wef_resource_spices', itemType.building, 1, None, 'Progressive WoodElf Building: Spices'),
    55306: itemData(IC.useful, 3, 'Progressive wef_allied_outpost', itemType.building, 3, None, 'Progressive WoodElf Building: Allied Outpost'),
    55307: itemData(IC.useful, 1, 'Progressive wef_resource_ivory', itemType.building, 1, None, 'Progressive WoodElf Building: Ivory'),
    55308: itemData(IC.useful, 2, 'Progressive wef_agent_protection', itemType.building, 2, None, 'Progressive WoodElf Building: Agent Protection'),
    55309: itemData(IC.useful, 2, 'Progressive wef_armoury', itemType.building, 2, None, 'Progressive WoodElf Building: Armoury'),
    55310: itemData(IC.useful, 4, 'Progressive wef_cavalry', itemType.building, 4, None, 'Progressive WoodElf Building: Cavalry'),
    55311: itemData(IC.useful, 3, 'Progressive wef_flying', itemType.building, 3, None, 'Progressive WoodElf Building: Flying'),
    55312: itemData(IC.useful, 3, 'Progressive wef_garrison', itemType.building, 3, None, 'Progressive WoodElf Building: Garrison'),
    55313: itemData(IC.useful, 3, 'Progressive wef_growth', itemType.building, 3, None, 'Progressive WoodElf Building: Growth'),
    55314: itemData(IC.useful, 4, 'Progressive wef_income', itemType.building, 4, None, 'Progressive WoodElf Building: Income'),
    55315: itemData(IC.useful, 3, 'Progressive wef_melee', itemType.building, 3, None, 'Progressive WoodElf Building: Melee'),
    55320: itemData(IC.useful, 1, 'Progressive wef_outpost_foraging', itemType.building, 1, None, 'Progressive WoodElf Building: Outpost Foraging'),
    55322: itemData(IC.useful, 1, 'Progressive wef_outpost_recruitment', itemType.building, 1, None, 'Progressive WoodElf Building: Outpost Recruitment'),
    55323: itemData(IC.useful, 1, 'Progressive wef_outpost_replenishment', itemType.building, 1, None, 'Progressive WoodElf Building: Outpost Replenishment'),
    55324: itemData(IC.useful, 1, 'Progressive wef_outpost_slaughter', itemType.building, 1, None, 'Progressive WoodElf Building: Outpost Slaughter'),
    55325: itemData(IC.useful, 1, 'Progressive wef_port', itemType.building, 1, None, 'Progressive WoodElf Building: Port'),
    55326: itemData(IC.useful, 3, 'Progressive wef_public_order', itemType.building, 3, None, 'Progressive WoodElf Building: Public Order'),
    55327: itemData(IC.useful, 3, 'Progressive wef_ranged', itemType.building, 3, None, 'Progressive WoodElf Building: Ranged'),
    55328: itemData(IC.useful, 1, 'Progressive wef_resource_dyes', itemType.building, 1, None, 'Progressive WoodElf Building: Dyes'),
    55329: itemData(IC.useful, 1, 'Progressive wef_resource_furs', itemType.building, 1, None, 'Progressive WoodElf Building: Furs'),
    55330: itemData(IC.useful, 1, 'Progressive wef_resource_gold', itemType.building, 1, None, 'Progressive WoodElf Building: Gold'),
    55331: itemData(IC.useful, 1, 'Progressive wef_resource_iron', itemType.building, 1, None, 'Progressive WoodElf Building: Iron'),
    55332: itemData(IC.useful, 1, 'Progressive wef_resource_marble', itemType.building, 1, None, 'Progressive WoodElf Building: Marble'),
    55333: itemData(IC.useful, 1, 'Progressive wef_resource_pastures', itemType.building, 1, None, 'Progressive WoodElf Building: Pastures'),
    55334: itemData(IC.useful, 1, 'Progressive wef_resource_pottery', itemType.building, 1, None, 'Progressive WoodElf Building: Pottery'),
    55335: itemData(IC.useful, 1, 'Progressive wef_resource_salt', itemType.building, 1, None, 'Progressive WoodElf Building: Salt'),
    55336: itemData(IC.useful, 1, 'Progressive wef_resource_timber', itemType.building, 1, None, 'Progressive WoodElf Building: Timber'),
    55337: itemData(IC.useful, 1, 'Progressive wef_resource_wine', itemType.building, 1, None, 'Progressive WoodElf Building: Wine'),
    55338: itemData(IC.useful, 5, 'Progressive wef_settlement_major', itemType.building, 5, None, 'Progressive WoodElf Building: Settlement Major'),
    55339: itemData(IC.useful, 3, 'Progressive wef_spellsingers', itemType.building, 3, None, 'Progressive WoodElf Building: Spellsingers'),
    55340: itemData(IC.useful, 2, 'Progressive wef_temple_anath_raema', itemType.building, 2, None, 'Progressive WoodElf Building: Temple Anath Raema'),
    55341: itemData(IC.useful, 1, 'Progressive wef_temple_ereth_khial', itemType.building, 1, None, 'Progressive WoodElf Building: Temple Ereth Khial'),
    55342: itemData(IC.useful, 1, 'Progressive wef_temple_isha', itemType.building, 1, None, 'Progressive WoodElf Building: Temple Isha'),
    55343: itemData(IC.useful, 1, 'Progressive wef_temple_kurnous', itemType.building, 1, None, 'Progressive WoodElf Building: Temple Kurnous'),
    55344: itemData(IC.useful, 4, 'Progressive wef_tree_spirits', itemType.building, 4, None, 'Progressive WoodElf Building: Tree Spirits')
}

progTechs: dict[int, itemData] = {
    55400: itemData(IC.useful, 6, "Progressive tech_wef_cadai", itemType.tech, 6, None, "Progressive WoodElf Tech: Cadai"),
    55401: itemData(IC.useful, 6, "Progressive tech_wef_cytharai", itemType.tech, 6, None, "Progressive WoodElf Tech: Cytharai"),
    55402: itemData(IC.useful, 1, "Progressive tech_wef_wisdom", itemType.tech, 1, None, "Progressive WoodElf Tech: Wisdom"),
}

special: dict[int, specialItemData] = {
    55500: specialItemData(IC.useful, 1, ['wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_argwylon', 'wh2_dlc16_wef_sisters_of_twilight'], 'wh_dlc05_wef_inf_dryads_0', itemType.unit, 1, 'Progressive wef_inf', False, False, 'WoodElf Unit: Dryads'),
    55501: specialItemData(IC.useful, 1, ['wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_argwylon', 'wh2_dlc16_wef_sisters_of_twilight'], 'wh_dlc05_wef_cha_branchwraith_0', itemType.unit, 2, 'Progressive wef_hro', False, False, 'WoodElf Unit: Branchwraith'),
    55502: specialItemData(IC.useful, 1, ['wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_argwylon', 'wh2_dlc16_wef_sisters_of_twilight'], 'wh_dlc05_wef_mon_treeman_0', itemType.unit, 4, 'Progressive wef_bst', False, False, 'WoodElf Unit: Treeman'),
    55503: specialItemData(IC.useful, 1, ['wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_argwylon', 'wh2_dlc16_wef_sisters_of_twilight'], 'wh_dlc05_wef_mon_treekin_0', itemType.unit, 2, 'Progressive wef_bst', False, False, 'WoodElf Unit: Tree Kin'),
    55512: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_inf_malicious_dryads_0', itemType.unit, 1, 'Progressive wef_inf', False, False, 'WoodElf Unit: Malevolent Dryads'),
    55513: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_malicious_treekin_0', itemType.unit, 2, 'Progressive wef_bst', False, False, 'WoodElf Unit: Malevolent Tree Kin'),
    55514: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_malicious_treeman_0', itemType.unit, 4, 'Progressive wef_bst', False, False, 'WoodElf Unit: Malevolent Treeman'),
    55515: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_cha_malicious_branchwraith_beasts_0', itemType.unit, 2, 'Progressive wef_hro', False, False, 'WoodElf Unit: Malevolent Branchwraith (Beasts)'),
    55516: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_cha_malicious_branchwraith_life_0', itemType.unit, 2, 'Progressive wef_hro', False, False, 'WoodElf Unit: Malevolent Branchwraith (Life)'),
    55517: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_cha_malicious_branchwraith_shadows_0', itemType.unit, 2, 'Progressive wef_hro', False, False, 'WoodElf Unit: Malevolent Branchwraith (Shadows)'),
    55518: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'tech_dlc16_wef_ancients_addaivoch', itemType.tech, 1, 'Progressive tech_wef_wisdom', False, False, 'WoodElf Tech: Wisdom of Addaivoch'),
    55519: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'tech_dlc16_wef_ancients_wildwood', itemType.tech, 1, 'Progressive tech_wef_wisdom', False, False, 'WoodElf Tech: Wisdom of the Wildwood'),
    55520: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_cave_bats', itemType.unit, 1, 'Progressive wef_bst', False, False, 'WoodElf Unit: Cave Bats'),
    55521: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_feral_manticore', itemType.unit, 2, 'Progressive wef_bst', False, False, 'WoodElf Unit: Feral Manticore'),
    55522: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_giant_spiders_0', itemType.unit, 1, 'Progressive wef_bst', False, False, 'WoodElf Unit: Giant Spiders'),
    55523: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_wolves_0', itemType.unit, 1, 'Progressive wef_bst', False, False, 'WoodElf Unit: Giant Wolves'),
    55524: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh3_main_monster_feral_bears', itemType.unit, 2, 'Progressive wef_bst', False, False, 'WoodElf Unit: Feral Bears'),
    55525: specialItemData(IC.useful, 1, ['wh2_dlc16_wef_drycha'], 'wh2_dlc16_wef_mon_hawks_0', itemType.unit, 1, 'Progressive wef_bst', False, False, 'WoodElf Unit: Great Hawks')
}