from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    10000: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_ror_0', ItemType.unit, 5, 'Progressive bst_inf', 'Bst Unit: The Vorbergland Broodmother (Jabberslythe)'),
    10001: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_0', ItemType.unit, 4, 'Progressive bst_inf', 'Bst Unit: Jabberslythe'),
    10002: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_ror_0', ItemType.unit, 5, 'Progressive bst_inf', 'Bst Unit: The Bloodbrute Behemoth (Ghorgon)'),
    10003: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_0', ItemType.unit, 5, 'Progressive bst_inf', 'Bst Unit: Ghorgon'),
    10004: ItemData(IC.useful, 1, 'wh2_dlc17_bst_inf_centigors_ror_1', ItemType.unit, 3, 'Progressive bst_rng', "Bst Unit: Groghooves of Wolf's Run (Centigors â€“ Throwing Axes)"),
    10005: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cha_wargor_2', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Wargor'),
    10006: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cha_wargor_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Wargor'),
    10007: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cha_wargor_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Wargor'),
    10008: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cha_taurox_the_brass_bull_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Taurox the Brass Bull'),
    10009: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cha_doombull_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Doombull'),
    10010: ItemData(IC.useful, 1, 'wh2_dlc17_bst_cav_tuskgor_chariot_0', ItemType.unit, 2, 'Progressive bst_veh', 'Bst Unit: Tuskgor Chariots'),
    10011: ItemData(IC.useful, 1, 'wh_dlc05_bst_mon_harpies_0', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Harpies'),
    10012: ItemData(IC.useful, 1, 'wh_dlc05_bst_cha_morghur_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Morghur the Shadowgave'),
    10013: ItemData(IC.useful, 1, 'wh_dlc03_bst_mon_giant_0', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Giant'),
    10014: ItemData(IC.useful, 1, 'wh_dlc03_bst_mon_chaos_spawn_0', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Chaos Spawn'),
    10015: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_spearmen_1', ItemType.unit, 1, 'Progressive bst_inf', 'Bst Unit: Ungor Spearmen Herd (Shields)'),
    10016: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_spearmen_0', ItemType.unit, 1, 'Progressive bst_inf', 'Bst Unit: Ungor Spearmen Herd'),
    10017: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_raiders_0', ItemType.unit, 1, 'Progressive bst_rng', 'Bst Unit: Ungor Raiders'),
    10018: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_ungor_herd_1', ItemType.unit, 1, 'Progressive bst_inf', 'Bst Unit: Ungor Herd'),
    10019: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_razorgor_herd_0', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Razorgor Herd'),
    10020: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_2', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Minotaurs (Great Weapons)'),
    10021: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_1', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Minotaurs (Shields)'),
    10022: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_minotaurs_0', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Minotaurs'),
    10023: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_gor_herd_1', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Gor Herd (Shields)'),
    10024: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_gor_herd_0', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Gor Herd'),
    10025: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_cygor_0', ItemType.unit, 3, 'Progressive bst_rng', 'Bst Unit: Cygor'),
    10026: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_chaos_warhounds_1', ItemType.unit, 1, 'Progressive bst_inf', 'Bst Unit: Chaos Warhounds (Poison)'),
    10027: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_chaos_warhounds_0', ItemType.unit, 1, 'Progressive bst_inf', 'Bst Unit: Chaos Warhounds'),
    10028: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_2', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Centigors (Great Weapons)'),
    10029: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_1', ItemType.unit, 2, 'Progressive bst_rng', 'Bst Unit: Centigors (Throwing Axes)'),
    10030: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_centigors_0', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Centigors'),
    10031: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_bestigor_herd_0', ItemType.unit, 3, 'Progressive bst_inf', 'Bst Unit: Bestigor Herd'),
    10032: ItemData(IC.useful, 1, 'wh_dlc03_bst_feral_manticore', ItemType.unit, 2, 'Progressive bst_inf', 'Bst Unit: Feral Manticore'),
    10033: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_malagor_the_dark_omen_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Malagor the Dark Omen'),
    10034: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_khazrak_one_eye_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Khazrak the One-Eye'),
    10035: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_khazrak_one_eye_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Khazrak the One-Eye'),
    10036: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_gorebull_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Gorebull'),
    10037: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_wild_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Bray-Shaman (Wild)'),
    10038: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_wild_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Bray-Shaman (Wild)'),
    10039: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_shadows_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Bray-Shaman (Shadows)'),
    10040: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_shadows_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Bray-Shaman (Shadows)'),
    10041: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_death_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Bray-Shaman (Death)'),
    10042: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_death_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Bray-Shaman (Death)'),
    10043: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_beasts_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Bray-Shaman (Beasts)'),
    10044: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_bray_shaman_beasts_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Bray-Shaman (Beasts)'),
    10045: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_beastlord_1', ItemType.unit, 0, 'Progressive bst_veh', 'Bst Unit: Beastlord'),
    10046: ItemData(IC.useful, 1, 'wh_dlc03_bst_cha_beastlord_0', ItemType.unit, 0, 'Progressive bst_inf', 'Bst Unit: Beastlord'),
    10047: ItemData(IC.useful, 1, 'wh_dlc03_bst_cav_razorgor_chariot_0', ItemType.unit, 3, 'Progressive bst_veh', 'Bst Unit: Razorgor Chariots')
}

buildings: dict[int, ItemData] = {
    10400: ItemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Herdstone'),
    10401: ItemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Rune-Covered Herdstone'),
    10402: ItemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Bone-Strewn Herdstone'),
    10403: ItemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Spired Herdstone'),
    10404: ItemData(IC.useful, 1, 'wh2_dlc17_bst_settlement_major_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Great Herdstone'),
    10405: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes_2', ItemType.building, 1, 'Progressive bst_special_secondary_attributes', 'Bst Building: Viscera-Bound Captives'),
    10406: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes_3', ItemType.building, 2, 'Progressive bst_special_secondary_attributes', 'Bst Building: Shroud of Discord'),
    10407: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attributes', ItemType.building, 0, 'Progressive bst_special_secondary_attributes', 'Bst Building: Carrion Offerings'),
    10408: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition_2', ItemType.building, 1, 'Progressive bst_special_secondary_attrition', 'Bst Building: Miasmic Rain'),
    10409: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition_3', ItemType.building, 2, 'Progressive bst_special_secondary_attrition', 'Bst Building: Storm of Suffering'),
    10410: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_attrition', ItemType.building, 0, 'Progressive bst_special_secondary_attrition', 'Bst Building: Winds of Malady'),
    10411: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances_2', ItemType.building, 1, 'Progressive bst_special_secondary_resistances', 'Bst Building: Rancorous Braying'),
    10412: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances_3', ItemType.building, 2, 'Progressive bst_special_secondary_resistances', 'Bst Building: Beastly Pandemonium'),
    10413: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_resistances', ItemType.building, 0, 'Progressive bst_special_secondary_resistances', 'Bst Building: Rucking Pits'),
    10414: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell_2', ItemType.building, 1, 'Progressive bst_special_secondary_spell', 'Bst Building: Ruinous Seances'),
    10415: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell_3', ItemType.building, 2, 'Progressive bst_special_secondary_spell', 'Bst Building: Dreadful Shamanic Rituals'),
    10416: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_secondary_spell', ItemType.building, 0, 'Progressive bst_special_secondary_spell', 'Bst Building: Shamanic Challenges'),
    10417: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10418: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10419: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10420: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10421: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_altdorf_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Fall of Man'),
    10422: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10423: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10424: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10425: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10426: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_black_crag_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Crag of the Cloven'),
    10427: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10428: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10429: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10430: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10431: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_castle_drakenhof_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Bloodfeastersâ€™ Ruin'),
    10432: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10433: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10434: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10435: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10436: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_couronne_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Defiled Tournament Grounds'),
    10437: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10438: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10439: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10440: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10441: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_hexoatl_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Morrsliebâ€™s Eclipse'),
    10442: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10443: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10444: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10445: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10446: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_karaz_a_karak_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Age of Desecration'),
    10447: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10448: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10449: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10450: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10451: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_kislev_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Ruins of Urskoy'),
    10452: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10453: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10454: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10455: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10456: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_lothern_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Sepulchral Gate'),
    10457: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10458: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10459: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10460: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10461: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_naggarond_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Great Herdstone of Cold'),
    10462: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10463: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10464: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10465: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10466: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_oak_of_ages_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Scorched Oak'),
    10467: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10468: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10469: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10470: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10471: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_wei_jin_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Splintered Compass'),
    10472: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_1', ItemType.building, 0, 'Progressive bst_settlement_major', 'Bst Building: Chosen Herdstone'),
    10473: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_2', ItemType.building, 1, 'Progressive bst_settlement_major', 'Bst Building: Blasphemous Clearing'),
    10474: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_3', ItemType.building, 2, 'Progressive bst_settlement_major', 'Bst Building: Nexus of Depravity'),
    10475: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_4', ItemType.building, 3, 'Progressive bst_settlement_major', 'Bst Building: Heart of Doom'),
    10476: ItemData(IC.useful, 1, 'wh2_dlc17_bst_special_settlement_zharr_naggrund_5', ItemType.building, 4, 'Progressive bst_settlement_major', 'Bst Building: Wasteland of Hashut'),
    10477: ItemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_1', ItemType.building, 0, 'Progressive bst_allied_outpost', 'Bst Building: Beastmen Outpost'),
    10478: ItemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_2', ItemType.building, 1, 'Progressive bst_allied_outpost', 'Bst Building: Beastmen District'),
    10479: ItemData(IC.useful, 1, 'wh3_main_bst_allied_outpost_3', ItemType.building, 2, 'Progressive bst_allied_outpost', 'Bst Building: Beastmen Colony'),
    10480: ItemData(IC.useful, 1, 'wh_dlc03_bst_port', ItemType.building, 1, 'Progressive bst_port', 'Bst Building: Bestial Landings')
}

techs: dict[int, ItemData] = {
    10800: ItemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_locked', ItemType.tech, 0, 'Progressive bst_bretonnia', 'Bst Tech: Days of Wrath'),
    10801: ItemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_1', ItemType.tech, 1, 'Progressive bst_bretonnia', 'Bst Tech: Rampage!'),
    10802: ItemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_locked', ItemType.tech, 0, 'Progressive bst_dwarf', 'Bst Tech: Empire of Beasts'),
    10803: ItemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_4', ItemType.tech, 1, 'Progressive bst_dwarf', 'Bst Tech: Bestial Resilience'),
    10804: ItemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_locked', ItemType.tech, 0, 'Progressive bst_high', 'Bst Tech: The Unnatural Order'),
    10805: ItemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_1', ItemType.tech, 1, 'Progressive bst_high', 'Bst Tech: Savage Mantle'),
    10806: ItemData(IC.useful, 1, 'tech_dlc17_bst_empire_locked', ItemType.tech, 0, 'Progressive bst_empire', 'Bst Tech: Plight of the No-Horns'),
    10807: ItemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_1', ItemType.tech, 1, 'Progressive bst_empire', 'Bst Tech: Raining Blood'),
    10808: ItemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_2', ItemType.tech, 1, 'Progressive bst_bretonnia', 'Bst Tech: The Rewards of Ruin'),
    10809: ItemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_2', ItemType.tech, 1, 'Progressive bst_dwarf', 'Bst Tech: Rolling Death'),
    10810: ItemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_4', ItemType.tech, 1, 'Progressive bst_high', 'Bst Tech: Death from the Shadows'),
    10811: ItemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_2', ItemType.tech, 1, 'Progressive bst_empire', 'Bst Tech: Worldbane'),
    10812: ItemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_3', ItemType.tech, 1, 'Progressive bst_bretonnia', 'Bst Tech: Roaming Torment'),
    10813: ItemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_3', ItemType.tech, 1, 'Progressive bst_dwarf', 'Bst Tech: Man-Cleavers'),
    10814: ItemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_3', ItemType.tech, 1, 'Progressive bst_high', 'Bst Tech: Vitriolic Temperament'),
    10815: ItemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_3', ItemType.tech, 1, 'Progressive bst_empire', 'Bst Tech: Born to Lead'),
    10816: ItemData(IC.useful, 1, 'tech_dlc17_bst_bretonnia_unlock_4', ItemType.tech, 1, 'Progressive bst_bretonnia', 'Bst Tech: The Kalkengard Larder'),
    10817: ItemData(IC.useful, 1, 'tech_dlc17_bst_dwarf_unlock_1', ItemType.tech, 1, 'Progressive bst_dwarf', 'Bst Tech: Gaze of the Dark Gods'),
    10818: ItemData(IC.useful, 1, 'tech_dlc17_bst_high_elves_2', ItemType.tech, 1, 'Progressive bst_high', 'Bst Tech: Smell Their Fear'),
    10819: ItemData(IC.useful, 1, 'tech_dlc17_bst_empire_unlock_4', ItemType.tech, 1, 'Progressive bst_empire', 'Bst Tech: On Cloven Hoof & Twisted Claw'),
    10820: ItemData(IC.useful, 1, 'tech_dlc17_bst_the_single_entity_tech', ItemType.tech, 0, 'Progressive bst_the', 'Bst Tech: Horns of War'),
    10821: ItemData(IC.useful, 1, 'tech_dlc17_bst_unfavoured_battle', ItemType.tech, 0, 'Progressive bst_unfavoured', 'Bst Tech: The Strong Survive'),
    10822: ItemData(IC.useful, 1, 'tech_dlc17_bst_the_no_unit_loss', ItemType.tech, 0, 'Progressive bst_the', 'Bst Tech: Messenger of the Bray'),
    10823: ItemData(IC.useful, 1, 'tech_dlc17_bst_chariot_only', ItemType.tech, 0, 'Progressive bst_chariot', 'Bst Tech: Primal Fury'),
    10824: ItemData(IC.useful, 1, 'tech_dlc17_bst_four_battles', ItemType.tech, 0, 'Progressive bst_four', 'Bst Tech: The Warherd Ravages'),
    10825: ItemData(IC.useful, 1, 'tech_dlc17_bst_fifteen_spells', ItemType.tech, 0, 'Progressive bst_fifteen', 'Bst Tech: Kadon Unleashed'),
    10826: ItemData(IC.useful, 1, 'tech_dlc17_bst_bloodgrounds_everywhere', ItemType.tech, 0, 'Progressive bst_bloodgrounds', 'Bst Tech: Dominate the World'),
    10827: ItemData(IC.useful, 1, 'tech_dlc17_bst_wipe_out_faction', ItemType.tech, 0, 'Progressive bst_wipe', 'Bst Tech: Consume Order')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    11300: ItemData(IC.useful, 5, 'Progressive bst_settlement_major', ItemType.building, 5, None, 'Progressive Bst Building: Settlement Major'),
    11301: ItemData(IC.useful, 3, 'Progressive bst_special_secondary_attributes', ItemType.building, 3, None, 'Progressive Bst Building: Special Secondary Attributes'),
    11302: ItemData(IC.useful, 3, 'Progressive bst_special_secondary_attrition', ItemType.building, 3, None, 'Progressive Bst Building: Special Secondary Attrition'),
    11303: ItemData(IC.useful, 3, 'Progressive bst_special_secondary_resistances', ItemType.building, 3, None, 'Progressive Bst Building: Special Secondary Resistances'),
    11304: ItemData(IC.useful, 3, 'Progressive bst_special_secondary_spell', ItemType.building, 3, None, 'Progressive Bst Building: Special Secondary Spell'),
    11305: ItemData(IC.useful, 3, 'Progressive bst_allied_outpost', ItemType.building, 3, None, 'Progressive Bst Building: Allied Outpost'),
    11306: ItemData(IC.useful, 2, 'Progressive bst_port', ItemType.building, 1, None, 'Progressive Bst Building: Bst')
}

progTechs: dict[int, ItemData] = {
    11400: ItemData(IC.useful, 1, "Progressive tech_bst", ItemType.tech, 1, None, "Progressive Bst Tech"),
}

special: dict[int, ItemData] = {

}