from BaseClasses import ItemClassification as IC
from worlds.tww3.item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    12000: ItemData(IC.useful, 1, 'wh_dlc07_brt_peasant_mob_0', ItemType.unit, 1, 'Progressive brt_inf', 'Bretonnia Unit: Peasant Mob'),
    12001: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_men_at_arms_1', ItemType.unit, 2, 'Progressive brt_inf', 'Bretonnia Unit: Men-at-Arms'),
    12002: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_men_at_arms_2', ItemType.unit, 1, 'Progressive brt_inf', 'Bretonnia Unit: Men-at-Arms (Shields)'),
    12003: ItemData(IC.useful, 1, 'wh_main_brt_inf_men_at_arms', ItemType.unit, 3, 'Progressive brt_inf', 'Bretonnia Unit: Men-at-Arms (Polearms)'),
    12004: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_spearmen_at_arms_1', ItemType.unit, 1, 'Progressive brt_inf', 'Bretonnia Unit: Spearmen-at-Arms'),
    12005: ItemData(IC.useful, 1, 'wh_main_brt_inf_spearmen_at_arms', ItemType.unit, 2, 'Progressive brt_inf', 'Bretonnia Unit: Spearmen-at-Arms (Shields)'),
    12006: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_grail_reliquae_0', ItemType.unit, 3, 'Progressive brt_inf', 'Bretonnia Unit: Grail Relique'),
    12007: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_foot_squires_0', ItemType.unit, 4, 'Progressive brt_inf', 'Bretonnia Unit: Foot Squires'),
    12008: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_battle_pilgrims_0', ItemType.unit, 3, 'Progressive brt_inf', 'Bretonnia Unit: Battle Pilgrims'),
    12009: ItemData(IC.useful, 1, 'wh_main_brt_inf_peasant_bowmen', ItemType.unit, 1, 'Progressive brt_rng', 'Bretonnia Unit: Peasant Bowmen'),
    12010: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_peasant_bowmen_1', ItemType.unit, 2, 'Progressive brt_rng', 'Bretonnia Unit: Peasant Bowmen (Fire Arrows)'),
    12011: ItemData(IC.useful, 1, 'wh_dlc07_brt_inf_peasant_bowmen_2', ItemType.unit, 2, 'Progressive brt_rng', 'Bretonnia Unit: Peasant Bowmen (Pox Arrows)'),
    12012: ItemData(IC.useful, 1, 'wh_main_brt_cav_mounted_yeomen_0', ItemType.unit, 1, 'Progressive brt_cav', 'Bretonnia Unit: Mounted Yeomen'),
    12013: ItemData(IC.useful, 1, 'wh_main_brt_cav_mounted_yeomen_1', ItemType.unit, 1, 'Progressive brt_cav', 'Bretonnia Unit: Mounted Yeomen Archers'),
    12014: ItemData(IC.useful, 1, 'wh_dlc07_brt_cav_knights_errant_0', ItemType.unit, 2, 'Progressive brt_cav', 'Bretonnia Unit: Knights Errant'),
    12015: ItemData(IC.useful, 1, 'wh_main_brt_cav_knights_of_the_realm', ItemType.unit, 3, 'Progressive brt_cav', 'Bretonnia Unit: Knights of the Realm'),
    12016: ItemData(IC.useful, 1, 'wh_dlc07_brt_cav_questing_knights_0', ItemType.unit, 3, 'Progressive brt_cav', 'Bretonnia Unit: Questing Knights'),
    12017: ItemData(IC.useful, 1, 'wh_main_brt_cav_grail_knights', ItemType.unit, 4, 'Progressive brt_cav', 'Bretonnia Unit: Grail Knights'),
    12018: ItemData(IC.useful, 1, 'wh_dlc07_brt_cav_grail_guardians_0', ItemType.unit, 5, 'Progressive brt_cav', 'Bretonnia Unit: Grail Guardians'),
    12019: ItemData(IC.useful, 1, 'wh_main_brt_cav_pegasus_knights', ItemType.unit, 4, 'Progressive brt_cav', 'Bretonnia Unit: Pegasus Knights'),
    12020: ItemData(IC.useful, 1, 'wh_dlc07_brt_cav_royal_pegasus_knights_0', ItemType.unit, 5, 'Progressive brt_cav', 'Bretonnia Unit: Royal Pegasus Knights'),
    12021: ItemData(IC.useful, 1, 'wh_dlc07_brt_cav_royal_hippogryph_knights_0', ItemType.unit, 5, 'Progressive brt_cav', 'Bretonnia Unit: Royal Hippogryph Knights'),
    12022: ItemData(IC.useful, 1, 'wh_main_brt_art_field_trebuchet', ItemType.unit, 1, 'Progressive brt_art', 'Bretonnia Unit: Field Trebuchet'),
    12023: ItemData(IC.useful, 1, 'wh_pro04_brt_cav_knights_errant_ror_0', ItemType.unit, 2, 'Progressive brt_art', 'Bretonnia Unit: Blessed Field Trebuchet'),
    12024: ItemData(IC.useful, 1, 'wh_pro04_brt_cav_knights_of_the_realm_ror_0', ItemType.unit, 2, 'Progressive brt_cav', 'Bretonnia Unit: Defenders of the Fleur-de-lis (Knights Errant)'),
    12025: ItemData(IC.useful, 1, 'wh_pro04_brt_cav_mounted_yeomen_ror_0', ItemType.unit, 3, 'Progressive brt_cav', 'Bretonnia Unit: Knights of the Lionhearted (Knights of the Realm)'),
    12026: ItemData(IC.useful, 1, 'wh_pro04_brt_cav_questing_knights_ror_0', ItemType.unit, 2, 'Progressive brt_cav', 'Bretonnia Unit: Wardens of Montfort (Mounted Yeomen Archers)'),
    12027: ItemData(IC.useful, 1, 'wh_pro04_brt_inf_battle_pilgrims_ror_0', ItemType.unit, 3, 'Progressive brt_cav', 'Bretonnia Unit: The Companions of Quenelles (Questing Knights)'),
    12028: ItemData(IC.useful, 1, 'wh_pro04_brt_inf_foot_squires_ror_0', ItemType.unit, 3, 'Progressive brt_inf', 'Bretonnia Unit: The Holy Wardens of La Maisontaal (Battle Pilgrims)'),
    12029: ItemData(IC.useful, 1, 'wh_pro04_bst_inf_bestigor_herd_ror_0', ItemType.unit, 4, 'Progressive brt_inf', 'Bretonnia Unit: Beastslayers of Bastonne (Foot Squires)'),
    12030: ItemData(IC.useful, 1, "wh_main_brt_cha_paladin_0", ItemType.unit, 1, "Progressive brt_hro", "Bretonnia Unit: Paladin"),
    12031: ItemData(IC.useful, 1, "wh_main_brt_cha_damsel_0", ItemType.unit, 2, "Progressive brt_hro", "Bretonnia Unit: Damsel (Heavens)"),
    12032: ItemData(IC.useful, 1, "wh_dlc07_brt_cha_damsel_life_0", ItemType.unit, 2, "Progressive brt_hro", "Bretonnia Unit: Damsel (Life)"),
    12033: ItemData(IC.useful, 1, "wh_dlc07_brt_cha_damsel_beasts_0", ItemType.unit, 2, "Progressive brt_hro", "Bretonnia Unit: Damsel (Beasts)")
}

buildings: dict[int, ItemData] = {
    12400: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_brt_1', ItemType.building, 0, 'Progressive brt_settlement_major', 'Bretonnia Building: Massif Orcal Settlement 1'),
    12401: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_brt_2', ItemType.building, 1, 'Progressive brt_settlement_major', 'Bretonnia Building: Massif Orcal Settlement 2'),
    12402: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_brt_3', ItemType.building, 2, 'Progressive brt_settlement_major', 'Bretonnia Building: Massif Orcal Settlement 3'),
    12403: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_brt_4', ItemType.building, 3, 'Progressive brt_settlement_major', 'Bretonnia Building: Massif Orcal Settlement 4'),
    12404: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_brt_5', ItemType.building, 4, 'Progressive brt_settlement_major', 'Bretonnia Building: Massif Orcal Settlement 5'),
    12405: ItemData(IC.useful, 1, 'wh2_main_brt_resource_animals_1', ItemType.building, 0, 'Progressive brt_resource_animals', 'Bretonnia Building: Animals 1'),
    12406: ItemData(IC.useful, 1, 'wh2_main_brt_resource_animals_2', ItemType.building, 1, 'Progressive brt_resource_animals', 'Bretonnia Building: Animals 2'),
    12407: ItemData(IC.useful, 1, 'wh2_main_brt_resource_animals_3', ItemType.building, 2, 'Progressive brt_resource_animals', 'Bretonnia Building: Animals 3'),
    12408: ItemData(IC.useful, 1, 'wh2_main_brt_resource_dyes_1', ItemType.building, 0, 'Progressive brt_resource_dyes', 'Bretonnia Building: Dyes 1'),
    12409: ItemData(IC.useful, 1, 'wh2_main_brt_resource_dyes_2', ItemType.building, 1, 'Progressive brt_resource_dyes', 'Bretonnia Building: Dyes 2'),
    12410: ItemData(IC.useful, 1, 'wh2_main_brt_resource_dyes_3', ItemType.building, 2, 'Progressive brt_resource_dyes', 'Bretonnia Building: Dyes 3'),
    12411: ItemData(IC.useful, 1, 'wh2_main_brt_resource_furs_1', ItemType.building, 0, 'Progressive brt_resource_furs', 'Bretonnia Building: Furs 1'),
    12412: ItemData(IC.useful, 1, 'wh2_main_brt_resource_furs_2', ItemType.building, 1, 'Progressive brt_resource_furs', 'Bretonnia Building: Furs 2'),
    12413: ItemData(IC.useful, 1, 'wh2_main_brt_resource_furs_3', ItemType.building, 2, 'Progressive brt_resource_furs', 'Bretonnia Building: Furs 3'),
    12414: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gemstones_1', ItemType.building, 0, 'Progressive brt_resource_gemstones', 'Bretonnia Building: Gemstones 1'),
    12415: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gemstones_2', ItemType.building, 1, 'Progressive brt_resource_gemstones', 'Bretonnia Building: Gemstones 2'),
    12416: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gemstones_3', ItemType.building, 2, 'Progressive brt_resource_gemstones', 'Bretonnia Building: Gemstones 3'),
    12417: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gold_1', ItemType.building, 0, 'Progressive brt_resource_gold', 'Bretonnia Building: Gold 1'),
    12418: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gold_2', ItemType.building, 1, 'Progressive brt_resource_gold', 'Bretonnia Building: Gold 2'),
    12419: ItemData(IC.useful, 1, 'wh2_main_brt_resource_gold_3', ItemType.building, 2, 'Progressive brt_resource_gold', 'Bretonnia Building: Gold 3'),
    12420: ItemData(IC.useful, 1, 'wh2_main_brt_resource_iron_1', ItemType.building, 0, 'Progressive brt_resource_iron', 'Bretonnia Building: Iron 1'),
    12421: ItemData(IC.useful, 1, 'wh2_main_brt_resource_iron_2', ItemType.building, 1, 'Progressive brt_resource_iron', 'Bretonnia Building: Iron 2'),
    12422: ItemData(IC.useful, 1, 'wh2_main_brt_resource_iron_3', ItemType.building, 2, 'Progressive brt_resource_iron', 'Bretonnia Building: Iron 3'),
    12423: ItemData(IC.useful, 1, 'wh2_main_brt_resource_marble_1', ItemType.building, 0, 'Progressive brt_resource_marble', 'Bretonnia Building: Marble 1'),
    12424: ItemData(IC.useful, 1, 'wh2_main_brt_resource_marble_2', ItemType.building, 1, 'Progressive brt_resource_marble', 'Bretonnia Building: Marble 2'),
    12425: ItemData(IC.useful, 1, 'wh2_main_brt_resource_marble_3', ItemType.building, 2, 'Progressive brt_resource_marble', 'Bretonnia Building: Marble 3'),
    12426: ItemData(IC.useful, 1, 'wh2_main_brt_resource_medicine_1', ItemType.building, 0, 'Progressive brt_resource_medicine', 'Bretonnia Building: Medicine 1'),
    12427: ItemData(IC.useful, 1, 'wh2_main_brt_resource_medicine_2', ItemType.building, 1, 'Progressive brt_resource_medicine', 'Bretonnia Building: Medicine 2'),
    12428: ItemData(IC.useful, 1, 'wh2_main_brt_resource_medicine_3', ItemType.building, 2, 'Progressive brt_resource_medicine', 'Bretonnia Building: Medicine 3'),
    12429: ItemData(IC.useful, 1, 'wh2_main_brt_resource_obsidian_1', ItemType.building, 0, 'Progressive brt_resource_obsidian', 'Bretonnia Building: Obsidian 1'),
    12430: ItemData(IC.useful, 1, 'wh2_main_brt_resource_obsidian_2', ItemType.building, 1, 'Progressive brt_resource_obsidian', 'Bretonnia Building: Obsidian 2'),
    12431: ItemData(IC.useful, 1, 'wh2_main_brt_resource_obsidian_3', ItemType.building, 2, 'Progressive brt_resource_obsidian', 'Bretonnia Building: Obsidian 3'),
    12432: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pastures_1', ItemType.building, 0, 'Progressive brt_resource_pastures', 'Bretonnia Building: Pastures 1'),
    12433: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pastures_2', ItemType.building, 1, 'Progressive brt_resource_pastures', 'Bretonnia Building: Pastures 2'),
    12434: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pastures_3', ItemType.building, 2, 'Progressive brt_resource_pastures', 'Bretonnia Building: Pastures 3'),
    12435: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pottery_1', ItemType.building, 0, 'Progressive brt_resource_pottery', 'Bretonnia Building: Pottery 1'),
    12436: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pottery_2', ItemType.building, 1, 'Progressive brt_resource_pottery', 'Bretonnia Building: Pottery 2'),
    12437: ItemData(IC.useful, 1, 'wh2_main_brt_resource_pottery_3', ItemType.building, 2, 'Progressive brt_resource_pottery', 'Bretonnia Building: Pottery 3'),
    12438: ItemData(IC.useful, 1, 'wh2_main_brt_resource_salt_1', ItemType.building, 0, 'Progressive brt_resource_salt', 'Bretonnia Building: Salt 1'),
    12439: ItemData(IC.useful, 1, 'wh2_main_brt_resource_salt_2', ItemType.building, 1, 'Progressive brt_resource_salt', 'Bretonnia Building: Salt 2'),
    12440: ItemData(IC.useful, 1, 'wh2_main_brt_resource_salt_3', ItemType.building, 2, 'Progressive brt_resource_salt', 'Bretonnia Building: Salt 3'),
    12441: ItemData(IC.useful, 1, 'wh2_main_brt_resource_spices_1', ItemType.building, 0, 'Progressive brt_resource_spices', 'Bretonnia Building: Spices 1'),
    12442: ItemData(IC.useful, 1, 'wh2_main_brt_resource_spices_2', ItemType.building, 1, 'Progressive brt_resource_spices', 'Bretonnia Building: Spices 2'),
    12443: ItemData(IC.useful, 1, 'wh2_main_brt_resource_spices_3', ItemType.building, 2, 'Progressive brt_resource_spices', 'Bretonnia Building: Spices 3'),
    12444: ItemData(IC.useful, 1, 'wh2_main_brt_resource_timber_1', ItemType.building, 0, 'Progressive brt_resource_timber', 'Bretonnia Building: Timber 1'),
    12445: ItemData(IC.useful, 1, 'wh2_main_brt_resource_timber_2', ItemType.building, 1, 'Progressive brt_resource_timber', 'Bretonnia Building: Timber 2'),
    12446: ItemData(IC.useful, 1, 'wh2_main_brt_resource_timber_3', ItemType.building, 2, 'Progressive brt_resource_timber', 'Bretonnia Building: Timber 3'),
    12447: ItemData(IC.useful, 1, 'wh2_main_brt_resource_wine_1', ItemType.building, 0, 'Progressive brt_resource_wine', 'Bretonnia Building: Wine 1'),
    12448: ItemData(IC.useful, 1, 'wh2_main_brt_resource_wine_2', ItemType.building, 1, 'Progressive brt_resource_wine', 'Bretonnia Building: Wine 2'),
    12449: ItemData(IC.useful, 1, 'wh2_main_brt_resource_wine_3', ItemType.building, 2, 'Progressive brt_resource_wine', 'Bretonnia Building: Wine 3'),
    12450: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_brt_1', ItemType.building, 0, 'Progressive brt_protection', 'Bretonnia Building: Protection 1'),
    12451: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_brt_2', ItemType.building, 1, 'Progressive brt_protection', 'Bretonnia Building: Protection 1'),
    12452: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_brt_3', ItemType.building, 2, 'Progressive brt_protection', 'Bretonnia Building: Protection 1'),
    12453: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_brt_1', ItemType.building, 0, 'Progressive brt_settlement_major', 'Bretonnia Building: Sartosa Settlement 1'),
    12454: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_brt_2', ItemType.building, 1, 'Progressive brt_settlement_major', 'Bretonnia Building: Sartosa Settlement 2'),
    12455: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_brt_3', ItemType.building, 2, 'Progressive brt_settlement_major', 'Bretonnia Building: Sartosa Settlement 3'),
    12456: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_brt_4', ItemType.building, 3, 'Progressive brt_settlement_major', 'Bretonnia Building: Sartosa Settlement 4'),
    12457: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_brt_5', ItemType.building, 4, 'Progressive brt_settlement_major', 'Bretonnia Building: Sartosa Settlement 5'),
    12458: ItemData(IC.useful, 1, 'wh3_main_brt_allied_outpost_1', ItemType.building, 0, 'Progressive brt_allied_outpost', 'Bretonnia Building: Allied Outpost 1'),
    12459: ItemData(IC.useful, 1, 'wh3_main_brt_allied_outpost_2', ItemType.building, 1, 'Progressive brt_allied_outpost', 'Bretonnia Building: Allied Outpost 2'),
    12460: ItemData(IC.useful, 1, 'wh3_main_brt_allied_outpost_3', ItemType.building, 2, 'Progressive brt_allied_outpost', 'Bretonnia Building: Allied Outpost 3'),
    12461: ItemData(IC.useful, 1, 'wh3_main_brt_resource_ivory_1', ItemType.building, 0, 'Progressive brt_resource_ivory', 'Bretonnia Building: Ivory 1'),
    12462: ItemData(IC.useful, 1, 'wh3_main_brt_resource_ivory_2', ItemType.building, 1, 'Progressive brt_resource_ivory', 'Bretonnia Building: Ivory 2'),
    12463: ItemData(IC.useful, 1, 'wh3_main_brt_resource_ivory_3', ItemType.building, 2, 'Progressive brt_resource_ivory', 'Bretonnia Building: Ivory 3'),
    12464: ItemData(IC.useful, 1, 'wh_main_brt_barracks_1', ItemType.building, 0, 'Progressive brt_barracks', 'Bretonnia Building: Barracks 1'),
    12465: ItemData(IC.useful, 1, 'wh_main_brt_barracks_2', ItemType.building, 1, 'Progressive brt_barracks', 'Bretonnia Building: Barracks 2'),
    12466: ItemData(IC.useful, 1, 'wh_main_brt_barracks_3', ItemType.building, 2, 'Progressive brt_barracks', 'Bretonnia Building: Barracks 3'),
    12467: ItemData(IC.useful, 1, 'wh_main_brt_barracks_4', ItemType.building, 3, 'Progressive brt_barracks', 'Bretonnia Building: Barracks 4'),
    12468: ItemData(IC.useful, 1, 'wh_main_brt_carpenter_1', ItemType.building, 0, 'Progressive brt_carpenter', 'Bretonnia Building: Carpenter 1'),
    12469: ItemData(IC.useful, 1, 'wh_main_brt_carpenter_2', ItemType.building, 1, 'Progressive brt_carpenter', 'Bretonnia Building: Carpenter 2'),
    12470: ItemData(IC.useful, 1, 'wh_main_brt_farm_1', ItemType.building, 0, 'Progressive brt_farm', 'Bretonnia Building: Farm 1'),
    12471: ItemData(IC.useful, 1, 'wh_main_brt_farm_2', ItemType.building, 1, 'Progressive brt_farm', 'Bretonnia Building: Farm 2'),
    12472: ItemData(IC.useful, 1, 'wh_main_brt_farm_3', ItemType.building, 2, 'Progressive brt_farm', 'Bretonnia Building: Farm 3'),
    12473: ItemData(IC.useful, 1, 'wh_main_brt_farm_extra_1', ItemType.building, 0, 'Progressive brt_farm_extra', 'Bretonnia Building: Milling 1'),
    12474: ItemData(IC.useful, 1, 'wh_main_brt_farm_extra_2', ItemType.building, 1, 'Progressive brt_farm_extra', 'Bretonnia Building: Milling 2'),
    12475: ItemData(IC.useful, 1, 'wh_main_brt_garrison_1', ItemType.building, 0, 'Progressive brt_garrison', 'Bretonnia Building: Garrison 1'),
    12476: ItemData(IC.useful, 1, 'wh_main_brt_garrison_2', ItemType.building, 1, 'Progressive brt_garrison', 'Bretonnia Building: Garrison 2'),
    12477: ItemData(IC.useful, 1, 'wh_main_brt_hospital_1', ItemType.building, 0, 'Progressive brt_hospital', 'Bretonnia Building: Healing 1'),
    12478: ItemData(IC.useful, 1, 'wh_main_brt_hospital_2', ItemType.building, 1, 'Progressive brt_hospital', 'Bretonnia Building: Healing 2'),
    12479: ItemData(IC.useful, 1, 'wh_main_brt_hospital_3', ItemType.building, 2, 'Progressive brt_hospital', 'Bretonnia Building: Healing 3'),
    12480: ItemData(IC.useful, 1, 'wh_main_brt_industry_basic_1', ItemType.building, 0, 'Progressive brt_industry', 'Bretonnia Building: Industry 1'),
    12481: ItemData(IC.useful, 1, 'wh_main_brt_industry_basic_2', ItemType.building, 1, 'Progressive brt_industry', 'Bretonnia Building: Industry 2'),
    12482: ItemData(IC.useful, 1, 'wh_main_brt_industry_basic_3', ItemType.building, 2, 'Progressive brt_industry', 'Bretonnia Building: Industry 3'),
    12483: ItemData(IC.useful, 1, 'wh_main_brt_industry_extra_1', ItemType.building, 0, 'Progressive brt_industry_extra', 'Bretonnia Building: Storage 1'),
    12484: ItemData(IC.useful, 1, 'wh_main_brt_industry_extra_2', ItemType.building, 1, 'Progressive brt_industry_extra', 'Bretonnia Building: Storage 2'),
    12485: ItemData(IC.useful, 1, 'wh_main_brt_port_1', ItemType.building, 0, 'Progressive brt_port', 'Bretonnia Building: Port 1'),
    12486: ItemData(IC.useful, 1, 'wh_main_brt_port_2', ItemType.building, 1, 'Progressive brt_port', 'Bretonnia Building: Port 2'),
    12487: ItemData(IC.useful, 1, 'wh_main_brt_port_3', ItemType.building, 2, 'Progressive brt_port', 'Bretonnia Building: Port 3'),
    12488: ItemData(IC.useful, 1, 'wh_main_brt_settlement_major_1', ItemType.building, 0, 'Progressive brt_settlement_major', 'Bretonnia Building: Major Settlement 1'),
    12489: ItemData(IC.useful, 1, 'wh_main_brt_settlement_major_2', ItemType.building, 1, 'Progressive brt_settlement_major', 'Bretonnia Building: Major Settlement 2'),
    12490: ItemData(IC.useful, 1, 'wh_main_brt_settlement_major_3', ItemType.building, 2, 'Progressive brt_settlement_major', 'Bretonnia Building: Major Settlement 3'),
    12491: ItemData(IC.useful, 1, 'wh_main_brt_settlement_major_4', ItemType.building, 3, 'Progressive brt_settlement_major', 'Bretonnia Building: Major Settlement 4'),
    12492: ItemData(IC.useful, 1, 'wh_main_brt_settlement_major_5', ItemType.building, 4, 'Progressive brt_settlement_major', 'Bretonnia Building: Major Settlement 5'),
    12493: ItemData(IC.useful, 1, 'wh_main_brt_settlement_minor_1', ItemType.building, 0, 'Progressive brt_settlement_minor', 'Bretonnia Building: Minor Settlement 1'),
    12494: ItemData(IC.useful, 1, 'wh_main_brt_settlement_minor_2', ItemType.building, 1, 'Progressive brt_settlement_minor', 'Bretonnia Building: Minor Settlement 2'),
    12495: ItemData(IC.useful, 1, 'wh_main_brt_settlement_minor_3', ItemType.building, 2, 'Progressive brt_settlement_minor', 'Bretonnia Building: Minor Settlement 3'),
    12496: ItemData(IC.useful, 1, 'wh_main_brt_smiths_1', ItemType.building, 0, 'Progressive brt_smiths', 'Bretonnia Building: Smiths 1'),
    12497: ItemData(IC.useful, 1, 'wh_main_brt_smiths_2', ItemType.building, 1, 'Progressive brt_smiths', 'Bretonnia Building: Smiths 2'),
    12498: ItemData(IC.useful, 1, 'wh_main_brt_stables_1', ItemType.building, 0, 'Progressive brt_stables', 'Bretonnia Building: Stables 1'),
    12499: ItemData(IC.useful, 1, 'wh_main_brt_stables_2', ItemType.building, 1, 'Progressive brt_stables', 'Bretonnia Building: Stables 2'),
    12500: ItemData(IC.useful, 1, 'wh_main_brt_stables_3', ItemType.building, 2, 'Progressive brt_stables', 'Bretonnia Building: Stables 3'),
    12501: ItemData(IC.useful, 1, 'wh_main_brt_stables_4', ItemType.building, 3, 'Progressive brt_stables', 'Bretonnia Building: Stables 4'),
    12502: ItemData(IC.useful, 1, 'wh_main_brt_stables_5', ItemType.building, 4, 'Progressive brt_stables', 'Bretonnia Building: Stables 5'),
    12503: ItemData(IC.useful, 1, 'wh_main_brt_tavern_1', ItemType.building, 0, 'Progressive brt_tavern', 'Bretonnia Building: Hostelry 1'),
    12504: ItemData(IC.useful, 1, 'wh_main_brt_tavern_2', ItemType.building, 1, 'Progressive brt_tavern', 'Bretonnia Building: Hostelry 2'),
    12505: ItemData(IC.useful, 1, 'wh_main_brt_tavern_3', ItemType.building, 2, 'Progressive brt_tavern', 'Bretonnia Building: Hostelry 3'),
    12506: ItemData(IC.useful, 1, 'wh_main_brt_tavern_4', ItemType.building, 3, 'Progressive brt_tavern', 'Bretonnia Building: Hostelry 4'),
    12507: ItemData(IC.useful, 1, 'wh_main_brt_walls_1', ItemType.building, 0, 'Progressive brt_walls', 'Bretonnia Building: Walls 1'),
    12508: ItemData(IC.useful, 1, 'wh_main_brt_walls_2', ItemType.building, 1, 'Progressive brt_walls', 'Bretonnia Building: Walls 2'),
    12509: ItemData(IC.useful, 1, 'wh_main_brt_walls_3', ItemType.building, 2, 'Progressive brt_walls', 'Bretonnia Building: Walls 3'),
    12510: ItemData(IC.useful, 1, 'wh_main_brt_worship_1', ItemType.building, 0, 'Progressive brt_worship', 'Bretonnia Building: Worship 1'),
    12511: ItemData(IC.useful, 1, 'wh_main_brt_worship_2', ItemType.building, 1, 'Progressive brt_worship', 'Bretonnia Building: Worship 2'),
    12512: ItemData(IC.useful, 1, 'wh_main_brt_worship_3', ItemType.building, 2, 'Progressive brt_worship', 'Bretonnia Building: Worship 3')
}

techs: dict[int, ItemData] = {
    12800: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_start', ItemType.tech, 1, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: The Chivalric Code'),
    12801: ItemData(IC.useful, 1, 'tech_dlc14_brt_heraldry_oversea_repanse', ItemType.tech, 2, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Overseas Diplomacy'),
    12802: ItemData(IC.useful, 1, 'wh2_dlc12_tech_brt_heraldry_oversea_dwf', ItemType.tech, 2, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Kings of the Mountains Diplomacy'),
    12803: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_errantry', ItemType.tech, 3, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Support Religious Errantry'),
    12804: ItemData(IC.useful, 1, 'wh2_dlc12_tech_brt_heraldry_oversea_men', ItemType.tech, 3, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Leaders of Men Diplomacy'),
    12805: ItemData(IC.useful, 1, 'wh2_dlc12_tech_brt_heraldry_oversea_wef', ItemType.tech, 4, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Lords of Athel Loren'),
    12806: ItemData(IC.useful, 1, 'wh2_dlc12_tech_brt_heraldry_oversea_tmb', ItemType.tech, 4, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Kings of the Desert Diplomacy'),
    12807: ItemData(IC.useful, 1, 'wh3_main_tech_brt_heraldry_aquitaine', ItemType.tech, 2, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Aquitaine'),
    12808: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_lyonesse', ItemType.tech, 2, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Lyonesse'),
    12809: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_bastonne', ItemType.tech, 3, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Bastonne'),
    12810: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_parravon', ItemType.tech, 3, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Parravon'),
    12811: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_artois', ItemType.tech, 4, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Artois'),
    12812: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_carcassonne', ItemType.tech, 4, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Carcassonne'),
    12813: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_bordeleaux', ItemType.tech, 4, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: Heraldry of Bordeleaux'),
    12814: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_heraldry_unification', ItemType.tech, 6, 'Progressive tech_brt_heraldry', 'Bretonnia Tech: The Unification of Bretonnia'),
    12815: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_start', ItemType.tech, 1, 'Progressive tech_brt_economy', 'Bretonnia Tech: Economic Investment'),
    12816: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_1', ItemType.tech, 2, 'Progressive tech_brt_economy', 'Bretonnia Tech: Almshouses'),
    12817: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_2', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Town Census'),
    12818: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_3', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Subsidised Tools'),
    12819: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_4', ItemType.tech, 4, 'Progressive tech_brt_economy', 'Bretonnia Tech: Charity'),
    12820: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_carpenters', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Commission Carpenters'),
    12821: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_draft', ItemType.tech, 5, 'Progressive tech_brt_economy', 'Bretonnia Tech: Registered Draft'),
    12822: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_spears', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Longer Spears'),
    12823: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_siege', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Siege Engineering'),
    12824: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_fletchers', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Professional Fletchers'),
    12825: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_fanaticism', ItemType.tech, 5, 'Progressive tech_brt_economy', 'Bretonnia Tech: Encourage Fanaticism'),
    12826: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_other_tithes', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Temple Tithes'),
    12827: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_trade_1', ItemType.tech, 2, 'Progressive tech_brt_economy', 'Bretonnia Tech: Improved Trade Vessels'),
    12828: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_trade_2', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Harbourmaster Bribes'),
    12829: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_1', ItemType.tech, 2, 'Progressive tech_brt_economy', 'Bretonnia Tech: Improved Agriculture Tools'),
    12830: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_2', ItemType.tech, 2, 'Progressive tech_brt_economy', 'Bretonnia Tech: Wider Ploughs'),
    12831: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_3', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Irrigation Ditches'),
    12832: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_4', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Water Pumps'),
    12833: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_hay', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Hay Stores'),
    12834: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_farriers', ItemType.tech, 4, 'Progressive tech_brt_economy', 'Bretonnia Tech: Farriers'),
    12835: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_farm_hoods', ItemType.tech, 4, 'Progressive tech_brt_economy', 'Bretonnia Tech: Blinker Hoods'),
    12836: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_start', ItemType.tech, 1, 'Progressive tech_brt_economy', 'Bretonnia Tech: Improved Construction'),
    12837: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_mines', ItemType.tech, 4, 'Progressive tech_brt_economy', 'Bretonnia Tech: Improved Smelters'),
    12838: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_steel', ItemType.tech, 5, 'Progressive tech_brt_economy', 'Bretonnia Tech: Steel Furnaces'),
    12839: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_pottery', ItemType.tech, 5, 'Progressive tech_brt_economy', 'Bretonnia Tech: Glazing Kilns'),
    12840: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_swords', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Master Swordsmiths'),
    12841: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_tournaments', ItemType.tech, 6, 'Progressive tech_brt_economy', 'Bretonnia Tech: Regular Tournaments'),
    12842: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_1', ItemType.tech, 2, 'Progressive tech_brt_economy', 'Bretonnia Tech: Bigger Bobbins'),
    12843: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_2', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Improved Loom Technology'),
    12844: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_3', ItemType.tech, 3, 'Progressive tech_brt_economy', 'Bretonnia Tech: Weaving Apprenticeships'),
    12845: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_economy_industry_4', ItemType.tech, 4, 'Progressive tech_brt_economy', 'Bretonnia Tech: Seamstresses'),
    12846: ItemData(IC.useful, 1, 'wh2_dlc12_tech_brt_chivalry_start', ItemType.tech, 1, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Decrees of Bretonnia'),
    12847: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_greenskins_1', ItemType.tech, 2, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Green Tide Decree'),
    12848: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_greenskins_2', ItemType.tech, 3, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Grey Mountain Watch'),
    12849: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_norsca_1', ItemType.tech, 2, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Winter Woes Decree'),
    12850: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_norsca_2', ItemType.tech, 3, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: The North Guard'),
    12851: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_skaven', ItemType.tech, 3, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Sewer Cleaning Decree'),
    12852: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_wood_elves_1', ItemType.tech, 3, 'Progressive tech_brt_chivalry', "Bretonnia Tech: Forest's Edge Decree"),
    12853: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_beastmen_1', ItemType.tech, 2, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Safer Woods Decree'),
    12854: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_chaos_1', ItemType.tech, 2, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Ruinous Powers Decree'),
    12855: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_vampires_1', ItemType.tech, 2, 'Progressive tech_brt_chivalry', "Bretonnia Tech: Death's Grip Decree"),
    12856: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_dark_elves', ItemType.tech, 3, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Secure Shores Decree'),
    12857: ItemData(IC.useful, 1, 'wh2_dlc11_tech_brt_chivalry_vampire_coast_1', ItemType.tech, 4, 'Progressive tech_brt_chivalry', "Bretonnia Tech: High Seas' Decree"),
    12858: ItemData(IC.useful, 1, 'wh_dlc07_tech_brt_chivalry_tomb_kings', ItemType.tech, 4, 'Progressive tech_brt_chivalry', 'Bretonnia Tech: Desert Purge Decree')
}

progUnits: dict[int, ItemData] = {
    13200: ItemData(IC.useful, 4, "Progressive brt_inf", ItemType.unit, 4, None, "Progressive Bretonnia Unit: Infantry"),
    13201: ItemData(IC.useful, 4, "Progressive brt_rng", ItemType.unit, 2, None, "Progressive Bretonnia Unit: Ranged"),
    13202: ItemData(IC.useful, 5, "Progressive brt_cav", ItemType.unit, 5, None, "Progressive Bretonnia Unit: Cavalry"),
    13203: ItemData(IC.useful, 2, "Progressive brt_art", ItemType.unit, 2, None, "Progressive Bretonnia Unit: Artillery"),
    31206: ItemData(IC.useful, 1, "Progressive brt_hro", ItemType.unit, 1, "", "Progressive Bretonnia Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    13300: ItemData(IC.useful, 5, "Progressive brt_settlement_major", ItemType.building, 5, None, "Progressive Bretonnia Building: Major Settlement"),
    13301: ItemData(IC.useful, 3, "progressive brt_settlement_minor", ItemType.building, 3, None, "Progressive Bretonnia Building: Minor Settlement"),

    13302: ItemData(IC.useful, 3, "Progressive brt_resource_animals", ItemType.building, 3, None, "Progressive Bretonnia Building: Animals"),
    13303: ItemData(IC.useful, 3, "progressive brt_resource_dyes", ItemType.building, 3, None, "Progressive Bretonnia Building: Dyes"),
    11704: ItemData(IC.useful, 3, "progressive brt_resource_furs", ItemType.building, 3, None, "Progressive Bretonnia Building: Furs"),
    11705: ItemData(IC.useful, 3, "progressive brt_resource_gemstones", ItemType.building, 3, None, "Progressive Bretonnia Building: Gemstones"),
    11706: ItemData(IC.useful, 3, "progressive brt_resource_gold", ItemType.building, 3, None, "Progressive Bretonnia Building: Gold"),
    11707: ItemData(IC.useful, 3, "progressive brt_resource_iron", ItemType.building, 3, None, "Progressive Bretonnia Building: Iron"),
    11708: ItemData(IC.useful, 3, "progressive brt_resource_marble", ItemType.building, 3, None, "Progressive Bretonnia Building: Marble"),
    11709: ItemData(IC.useful, 3, "progressive brt_resource_medicine", ItemType.building, 3, None, "Progressive Bretonnia Building: Medicine"),
    13310: ItemData(IC.useful, 3, "progressive brt_resource_obsidian", ItemType.building, 3, None, "Progressive Bretonnia Building: Obsidian"),
    13311: ItemData(IC.useful, 3, "progressive brt_resource_pastures", ItemType.building, 3, None, "Progressive Bretonnia Building: Pastures"),
    13312: ItemData(IC.useful, 3, "progressive brt_resource_pottery", ItemType.building, 3, None, "Progressive Bretonnia Building: Pottery"),
    13313: ItemData(IC.useful, 3, "progressive brt_resource_salt", ItemType.building, 3, None, "Progressive Bretonnia Building: Salt"),
    13314: ItemData(IC.useful, 3, "progressive brt_resource_spices", ItemType.building, 3, None, "Progressive Bretonnia Building: Spices"),
    13315: ItemData(IC.useful, 3, "progressive brt_resource_timber", ItemType.building, 3, None, "Progressive Bretonnia Building: Timber"),
    13316: ItemData(IC.useful, 3, "progressive brt_resource_wine", ItemType.building, 3, None, "Progressive Bretonnia Building: Wine"),
    13317: ItemData(IC.useful, 3, "progressive brt_resource_ivory", ItemType.building, 3, None, "Progressive Bretonnia Building: Ivory"),

    13318: ItemData(IC.useful, 3, "progressive brt_farm", ItemType.building, 3, None, "Progressive Bretonnia Building: Farm"),
    13319: ItemData(IC.useful, 2, "progressive brt_farm_extra", ItemType.building, 3, None, "Progressive Bretonnia Building: Milling"),
    13320: ItemData(IC.useful, 3, "progressive brt_industry", ItemType.building, 3, None, "Progressive Bretonnia Building: Industry"),
    13321: ItemData(IC.useful, 2, "progressive brt_industry_extra", ItemType.building, 3, None, "Progressive Bretonnia Building: Storage"),
    13322: ItemData(IC.useful, 4, "progressive brt_tavern", ItemType.building, 3, None, "Progressive Bretonnia Building: Hostelry"),
    13323: ItemData(IC.useful, 3, "progressive brt_port", ItemType.building, 3, None, "Progressive Bretonnia Building: Port"),

    13324: ItemData(IC.useful, 3, "progressive brt_allied_outpost", ItemType.building, 3, None, "Progressive Bretonnia Building: Allied Outpost"),
    13325: ItemData(IC.useful, 4, "progressive brt_barracks", ItemType.building, 4, None, "Progressive Bretonnia Building: Barracks"),
    13326: ItemData(IC.useful, 5, "progressive brt_stables", ItemType.building, 5, None, "Progressive Bretonnia Building: Stable"),
    13327: ItemData(IC.useful, 2, "progressive brt_carpenter", ItemType.building, 3, None, "Progressive Bretonnia Building: Carpentry"),
    13328: ItemData(IC.useful, 2, "progressive brt_smiths", ItemType.building, 3, None, "Progressive Bretonnia Building: Smiths"),
    13329: ItemData(IC.useful, 3, "progressive brt_worship", ItemType.building, 3, None, "Progressive Bretonnia Building: Worship"),

    13330: ItemData(IC.useful, 3, "progressive brt_resource_protection", ItemType.building, 3, None, "Progressive Bretonnia Building: Protection"),
    13331: ItemData(IC.useful, 2, "progressive brt_garrison", ItemType.building, 3, None, "Progressive Bretonnia Building: Protection"),
    13332: ItemData(IC.useful, 3, "progressive brt_walls", ItemType.building, 3, None, "Progressive Bretonnia Building: Protection")
}

progTechs: dict[int, ItemData] = {
    13400: ItemData(IC.useful, 5, "Progressive tech_brt_heraldry", ItemType.tech, 5, None, "Progressive Bretonnia Tech: Heraldry"),
    13401: ItemData(IC.useful, 5, "Progressive tech_brt_chivalry", ItemType.tech, 5, None, "Progressive Bretonnia Tech: Chivalry"),
    13402: ItemData(IC.useful, 5, "Progressive tech_brt_economy", ItemType.tech, 5, None, "Progressive Bretonnia Tech: Economy"),
}

special: dict[int, specialItemData] = {

}