from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    14000: ItemData(IC.useful, 1, 'wh3_main_cth_inf_peasant_spearmen_1', ItemType.unit, 1, 'Progressive cth_inf', 'Cth Unit: Peasant Long Spearmen'),
    14001: ItemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warriors_0', ItemType.unit, 1, 'Progressive cth_inf', 'Cth Unit: Jade Warriors'),
    14002: ItemData(IC.useful, 1, 'wh3_dlc24_cth_inf_onyx_crowmen', ItemType.unit, 2, 'Progressive cth_inf', 'Cth Unit: Onyx Crowmen'),
    14003: ItemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warriors_1', ItemType.unit, 3, 'Progressive cth_inf', 'Cth Unit: Jade Warriors (Halberds)'),
    14004: ItemData(IC.useful, 1, 'wh3_main_cth_inf_dragon_guard_0', ItemType.unit, 4, 'Progressive cth_inf', 'Cth Unit: Celestial Dragon Guard'),
    14005: ItemData(IC.useful, 1, 'wh3_main_cth_inf_peasant_archers_0', ItemType.unit, 1, 'Progressive cth_rng', 'Cth Unit: Peasant Archers'),
    14006: ItemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warrior_crossbowmen_0', ItemType.unit, 2, 'Progressive cth_rng', 'Cth Unit: Jade Warrior Crossbows'),
    14007: ItemData(IC.useful, 1, 'wh3_main_cth_inf_jade_warrior_crossbowmen_1', ItemType.unit, 3, 'Progressive cth_rng', 'Cth Unit: Jade Warrior Crossbows (Shields)'),
    14008: ItemData(IC.useful, 1, 'wh3_main_cth_inf_iron_hail_gunners_0', ItemType.unit, 2, 'Progressive cth_rng', 'Cth Unit: Iron Hail Gunners'),
    14009: ItemData(IC.useful, 1, 'wh3_main_cth_inf_grenadiers', ItemType.unit, 2, 'Progressive cth_rng', 'Cth Unit: Nan-Gau Grenadiers'),
    14010: ItemData(IC.useful, 1, 'wh3_main_cth_inf_crane_gunners_0', ItemType.unit, 3, 'Progressive cth_rng', 'Cth Unit: Crane Gunners'),
    14011: ItemData(IC.useful, 1, 'wh3_main_cth_inf_dragon_guard_crossbowmen_0', ItemType.unit, 4, 'Progressive cth_rng', 'Cth Unit: Celestial Dragon Crossbows'),
    14012: ItemData(IC.useful, 1, 'wh3_main_cth_cav_peasant_horsemen_0', ItemType.unit, 1, 'Progressive cth_cav', 'Cth Unit: Peasant Horsemen'),
    14013: ItemData(IC.useful, 1, 'wh3_main_cth_cav_jade_lancers_0', ItemType.unit, 2, 'Progressive cth_cav', 'Cth Unit: Jade Lancers'),
    14014: ItemData(IC.useful, 1, 'wh3_main_cth_cav_jade_longma_riders_0', ItemType.unit, 3, 'Progressive cth_cav', 'Cth Unit: Great Longma Riders'),
    14015: ItemData(IC.useful, 1, 'wh3_main_cth_art_grand_cannon_0', ItemType.unit, 1, 'Progressive cth_art', 'Cth Unit: Grand Cannons'),
    14016: ItemData(IC.useful, 1, 'wh3_main_cth_art_fire_rain_rocket_battery_0', ItemType.unit, 2, 'Progressive cth_art', 'Cth Unit: Fire Rain Rocket Battery'),
    14017: ItemData(IC.useful, 1, 'wh3_dlc24_cth_veh_zhangu_war_drum', ItemType.unit, 1, 'Progressive cth_veh', 'Cth Unit: Zhangu War Drum'),
    14018: ItemData(IC.useful, 1, 'wh3_main_cth_veh_sky_lantern_0', ItemType.unit, 2, 'Progressive cth_veh', 'Cth Unit: Sky Lantern'),
    14019: ItemData(IC.useful, 1, 'wh3_main_cth_veh_war_compass_0', ItemType.unit, 3, 'Progressive cth_veh', 'Cth Unit: Wu Xing War Compass'),
    14020: ItemData(IC.useful, 1, 'wh3_main_cth_veh_sky_junk_0', ItemType.unit, 4, 'Progressive cth_veh', 'Cth Unit: Sky-junk'),
    14021: ItemData(IC.useful, 1, 'wh3_dlc24_cth_mon_jet_lion', ItemType.unit, 1, 'Progressive cth_bst', 'Cth Unit: Jet Lion'),
    14022: ItemData(IC.useful, 1, 'wh3_dlc24_cth_mon_jade_lion', ItemType.unit, 1, 'Progressive cth_bst', 'Cth Unit: Jade Lion'),
    14023: ItemData(IC.useful, 1, 'wh3_dlc24_cth_mon_celestial_lion', ItemType.unit, 1, 'Progressive cth_bst', 'Cth Unit: Celestial Lion'),
    14024: ItemData(IC.useful, 1, 'wh3_dlc24_cth_mon_great_moon_bird', ItemType.unit, 2, 'Progressive cth_bst', 'Cth Unit: Great Moon Bird'),
    14025: ItemData(IC.useful, 1, 'wh3_main_cth_mon_terracotta_sentinel_0', ItemType.unit, 3, 'Progressive cth_bst', 'Cth Unit: Terracotta Sentinel'),
    14026: ItemData(IC.useful, 1, 'wh3_dlc24_cth_cha_gate_master', ItemType.unit, 1, 'Progressive cth_hro', 'Cth Unit: Gate Master'),
    14027: ItemData(IC.useful, 1, 'wh3_main_cth_cha_astromancer_0', ItemType.unit, 1, 'Progressive cth_hro', 'Cth Unit: Astromancer'),
    14028: ItemData(IC.useful, 1, 'wh3_main_cth_cha_alchemist_0', ItemType.unit, 1, 'Progressive cth_hro', 'Cth Unit: Alchemist'),
    14029: ItemData(IC.useful, 1, 'wh3_twa10_cth_inf_peasant_archers_ror', ItemType.unit, 1, 'Progressive cth_rng', 'Cth Unit: Bandits of the Silver Road (Peasant Archers)'),
    14030: ItemData(IC.useful, 1, 'wh3_twa08_cth_mon_terracotta_sentinel_0_ror', ItemType.unit, 3, 'Progressive cth_bst', 'Cth Unit: The Green Guardian (Terracotta Sentinel)'),
    14031: ItemData(IC.useful, 1, 'wh3_twa07_cth_cav_jade_longma_riders_ror_0', ItemType.unit, 3, 'Progressive cth_cav', 'Cth Unit: Righteous Lances of Wei-Jin (Great Longma Riders)'),
    14032: ItemData(IC.useful, 1, 'wh3_twa06_cth_inf_dragon_guard_ror_0', ItemType.unit, 4, 'Progressive cth_inf', 'Cth Unit: The Dune Dragons (Celestial Dragon Guard)'),
    14033: ItemData(IC.useful, 1, 'wh3_dlc24_cth_inf_dragon_guard_crossbowmen_ror', ItemType.unit, 4, 'Progressive cth_rng', 'Cth Unit: The Grace of Quai Yin (Celestial Dragon Crossbows)'),
    14034: ItemData(IC.useful, 1, 'wh3_dlc24_cth_inf_onyx_crowmen_ror', ItemType.unit, 2, 'Progressive cth_inf', 'Cth Unit: Empress Crowmen (Onyx Crowmen)'),
    14035: ItemData(IC.useful, 1, 'wh3_dlc24_cth_veh_zhangu_war_drum_ror', ItemType.unit, 1, 'Progressive cth_veh', 'Cth Unit: The Jade War Drum (Zhangu War Drum)')
}

buildings: dict[int, ItemData] = {
    14400: ItemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_1', ItemType.building, 0, 'Progressive cth_allied_outpost', 'Cth Building: Cathayan Outpost'),
    14401: ItemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_2', ItemType.building, 1, 'Progressive cth_allied_outpost', 'Cth Building: Cathayan District'),
    14402: ItemData(IC.useful, 1, 'wh3_main_cth_allied_outpost_3', ItemType.building, 2, 'Progressive cth_allied_outpost', 'Cth Building: Cathayan Colony'),
    14403: ItemData(IC.useful, 1, 'wh3_main_cth_artillery_1', ItemType.building, 0, 'Progressive cth_artillery', 'Cth Building: Alchemist Tower'),
    14404: ItemData(IC.useful, 1, 'wh3_main_cth_artillery_2', ItemType.building, 1, 'Progressive cth_artillery', 'Cth Building: Powder Tower'),
    14405: ItemData(IC.useful, 1, 'wh3_main_cth_artillery_3', ItemType.building, 1, 'Progressive cth_artillery', 'Cth Building: Mooring Tower'),
    14406: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_1_1', ItemType.building, 0, 'Progressive cth_bastion', 'Cth Building: Bastion Gaol'),
    14407: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_1_2', ItemType.building, 1, 'Progressive cth_bastion', 'Cth Building: Bastion Hospice'),
    14408: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_1_3', ItemType.building, 2, 'Progressive cth_bastion', 'Cth Building: Bastion Shrine'),
    14409: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_1_4', ItemType.building, 3, 'Progressive cth_bastion', 'Cth Building: Bastion Temple'),
    14410: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_1_5', ItemType.building, 4, 'Progressive cth_bastion', 'Cth Building: Bastion Pagoda'),
    14411: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_2_1', ItemType.building, 0, 'Progressive cth_bastion', 'Cth Building: Bastion Watch Mast'),
    14412: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_2_2', ItemType.building, 1, 'Progressive cth_bastion', 'Cth Building: Bastion Barracks'),
    14413: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_2_3', ItemType.building, 2, 'Progressive cth_bastion', 'Cth Building: Bastion Quarters'),
    14414: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_2_4', ItemType.building, 3, 'Progressive cth_bastion', 'Cth Building: Bastion Overlook'),
    14415: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_2_5', ItemType.building, 4, 'Progressive cth_bastion', 'Cth Building: Bastion Command Tower'),
    14416: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_3_1', ItemType.building, 0, 'Progressive cth_bastion', 'Cth Building: Bastion Lumber Pile'),
    14417: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_3_2', ItemType.building, 1, 'Progressive cth_bastion', 'Cth Building: Bastion Mill'),
    14418: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_3_3', ItemType.building, 2, 'Progressive cth_bastion', 'Cth Building: Bastion Siegeworks'),
    14419: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_3_4', ItemType.building, 3, 'Progressive cth_bastion', 'Cth Building: Bastion Foundry'),
    14420: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_3_5', ItemType.building, 4, 'Progressive cth_bastion', 'Cth Building: Bastion Arsenal'),
    14421: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_4_1', ItemType.building, 0, 'Progressive cth_bastion', 'Cth Building: Bastion Water Station'),
    14422: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_4_2', ItemType.building, 1, 'Progressive cth_bastion', 'Cth Building: Bastion Mess Hall'),
    14423: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_4_3', ItemType.building, 2, 'Progressive cth_bastion', 'Cth Building: Bastion Feast Hall'),
    14424: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_4_4', ItemType.building, 3, 'Progressive cth_bastion', 'Cth Building: Bastion Parlour'),
    14425: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_4_5', ItemType.building, 4, 'Progressive cth_bastion', 'Cth Building: Bastion Grand Parlour'),
    #14426: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_1', ItemType.building, 1, 'Progressive cth_settlement_major', 'Cth Building: Bastion Gatehouse'),
    #14427: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_2', ItemType.building, 2, 'Progressive cth_settlement_major', 'Cth Building: Bastion Tower'),
    #14428: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_3', ItemType.building, 3, 'Progressive cth_settlement_major', 'Cth Building: Bastion Citadel'),
    #14429: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_4', ItemType.building, 4, 'Progressive cth_settlement_major', 'Cth Building: Bastion Stronghold'),
    #14430: ItemData(IC.useful, 1, 'wh3_main_cth_bastion_primary_5', ItemType.building, 5, 'Progressive cth_settlement_major', 'Cth Building: Bastion Fortress'),
    14431: ItemData(IC.useful, 1, 'wh3_main_cth_cavalry_1', ItemType.building, 0, 'Progressive cth_cavalry', 'Cth Building: Corral'),
    14432: ItemData(IC.useful, 1, 'wh3_main_cth_cavalry_2', ItemType.building, 1, 'Progressive cth_cavalry', 'Cth Building: Jade Stables'),
    14433: ItemData(IC.useful, 1, 'wh3_main_cth_cavalry_3', ItemType.building, 2, 'Progressive cth_cavalry', 'Cth Building: Longma Paddocks'),
    14434: ItemData(IC.useful, 1, 'wh3_main_cth_celestial_1', ItemType.building, 0, 'Progressive cth_celestial', 'Cth Building: Celestial Barracks'),
    14435: ItemData(IC.useful, 1, 'wh3_main_cth_celestial_2', ItemType.building, 1, 'Progressive cth_celestial', 'Cth Building: Celestial Armoury'),
    14436: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yang_1', ItemType.building, 0, 'Progressive cth_defence_yang', 'Cth Building: Ramparts'),
    14437: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yang_2', ItemType.building, 1, 'Progressive cth_defence_yang', 'Cth Building: Cannon Emplacements'),
    14438: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yang_3', ItemType.building, 2, 'Progressive cth_defence_yang', 'Cth Building: Artillery Batteries'),
    14439: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yin_1', ItemType.building, 0, 'Progressive cth_defence_yin', 'Cth Building: Archer Platforms'),
    14440: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yin_2', ItemType.building, 1, 'Progressive cth_defence_yin', 'Cth Building: Archer Towers'),
    14441: ItemData(IC.useful, 1, 'wh3_main_cth_defence_yin_3', ItemType.building, 2, 'Progressive cth_defence_yin', 'Cth Building: Sky Lantern Roosts'),
    14442: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yang_1', ItemType.building, 0, 'Progressive cth_growth_yang', 'Cth Building: Labour Conscription Bureau'),
    14443: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yang_2', ItemType.building, 1, 'Progressive cth_growth_yang', 'Cth Building: Bamboo Scaffold Depot'),
    14444: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yang_3', ItemType.building, 2, 'Progressive cth_growth_yang', 'Cth Building: Lumber Mill'),
    14445: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yin_1', ItemType.building, 0, 'Progressive cth_growth_yin', 'Cth Building: Tea Parlour'),
    14446: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yin_2', ItemType.building, 1, 'Progressive cth_growth_yin', 'Cth Building: Contemplation Gardens'),
    14447: ItemData(IC.useful, 1, 'wh3_main_cth_growth_yin_3', ItemType.building, 2, 'Progressive cth_growth_yin', 'Cth Building: Administration Centre'),
    14448: ItemData(IC.useful, 1, 'wh3_main_cth_gunners_1', ItemType.building, 0, 'Progressive cth_gunners', 'Cth Building: Nan-Gau Forge'),
    14449: ItemData(IC.useful, 1, 'wh3_main_cth_gunners_2', ItemType.building, 1, 'Progressive cth_gunners', 'Cth Building: Powder Magazine'),
    14450: ItemData(IC.useful, 1, 'wh3_main_cth_gunners_3', ItemType.building, 2, 'Progressive cth_gunners', 'Cth Building: Fire Rain Silo'),
    14451: ItemData(IC.useful, 1, 'wh3_main_cth_income_yang_1', ItemType.building, 0, 'Progressive cth_income_yang', 'Cth Building: Wares Market'),
    14452: ItemData(IC.useful, 1, 'wh3_main_cth_income_yang_2', ItemType.building, 1, 'Progressive cth_income_yang', 'Cth Building: Merchant Caravans'),
    14453: ItemData(IC.useful, 1, 'wh3_main_cth_income_yang_3', ItemType.building, 2, 'Progressive cth_income_yang', 'Cth Building: Trade Exchange'),
    14454: ItemData(IC.useful, 1, 'wh3_main_cth_income_yin_1', ItemType.building, 0, 'Progressive cth_income_yin', 'Cth Building: Spice Market'),
    14455: ItemData(IC.useful, 1, 'wh3_main_cth_income_yin_2', ItemType.building, 1, 'Progressive cth_income_yin', 'Cth Building: Gem Factors'),
    14456: ItemData(IC.useful, 1, 'wh3_main_cth_income_yin_3', ItemType.building, 2, 'Progressive cth_income_yin', 'Cth Building: Goods Emporium'),
    14457: ItemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_1', ItemType.building, 0, 'Progressive cth_jade_barracks', 'Cth Building: Training Camp'),
    14458: ItemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_2', ItemType.building, 1, 'Progressive cth_jade_barracks', 'Cth Building: Dormitory'),
    14459: ItemData(IC.useful, 1, 'wh3_main_cth_jade_barracks_3', ItemType.building, 2, 'Progressive cth_jade_barracks', 'Cth Building: Jade Barracks'),
    14460: ItemData(IC.useful, 1, 'wh3_main_cth_magic_tower_1', ItemType.building, 0, 'Progressive cth_magic_tower', 'Cth Building: Celestial Tower'),
    14461: ItemData(IC.useful, 1, 'wh3_main_cth_magic_tower_2', ItemType.building, 1, 'Progressive cth_magic_tower', 'Cth Building: Celestial Observatory'),
    14462: ItemData(IC.useful, 1, 'wh3_main_cth_magic_tower_3', ItemType.building, 2, 'Progressive cth_magic_tower', 'Cth Building: Celestial Beacon'),
    14463: ItemData(IC.useful, 1, 'wh3_main_cth_order_yang_1', ItemType.building, 0, 'Progressive cth_order_yang', 'Cth Building: Conscription Office'),
    14464: ItemData(IC.useful, 1, 'wh3_main_cth_order_yang_2', ItemType.building, 1, 'Progressive cth_order_yang', 'Cth Building: Temple of Yang'),
    14465: ItemData(IC.useful, 1, 'wh3_main_cth_order_yang_3', ItemType.building, 2, 'Progressive cth_order_yang', 'Cth Building: Yang Sanctuary'),
    14466: ItemData(IC.useful, 1, 'wh3_main_cth_order_yin_1', ItemType.building, 0, 'Progressive cth_order_yin', 'Cth Building: Conscription Field'),
    14467: ItemData(IC.useful, 1, 'wh3_main_cth_order_yin_2', ItemType.building, 1, 'Progressive cth_order_yin', 'Cth Building: Shrine of Yin'),
    14468: ItemData(IC.useful, 1, 'wh3_main_cth_order_yin_3', ItemType.building, 2, 'Progressive cth_order_yin', 'Cth Building: Yin Lodge'),
    14469: ItemData(IC.useful, 1, 'wh3_main_cth_port_1', ItemType.building, 0, 'Progressive cth_port', 'Cth Building: Dock'),
    14470: ItemData(IC.useful, 1, 'wh3_main_cth_port_2', ItemType.building, 1, 'Progressive cth_port', 'Cth Building: River Port'),
    14471: ItemData(IC.useful, 1, 'wh3_main_cth_port_3', ItemType.building, 2, 'Progressive cth_port', 'Cth Building: Sea Port'),
    14472: ItemData(IC.useful, 1, 'wh3_main_cth_resource_animals_1', ItemType.building, 0, 'Progressive cth_resource_animals', 'Cth Building: Exotic Animal Tamer'),
    14473: ItemData(IC.useful, 1, 'wh3_main_cth_resource_animals_2', ItemType.building, 1, 'Progressive cth_resource_animals', 'Cth Building: Exotic Animal Pen'),
    14474: ItemData(IC.useful, 1, 'wh3_main_cth_resource_animals_3', ItemType.building, 2, 'Progressive cth_resource_animals', 'Cth Building: Exotic Animal Market'),
    14475: ItemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_1', ItemType.building, 0, 'Progressive cth_resource_dyes', 'Cth Building: Cinnabar Mining Pit'),
    14476: ItemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_2', ItemType.building, 1, 'Progressive cth_resource_dyes', 'Cth Building: Cinnabar Mine'),
    14477: ItemData(IC.useful, 1, 'wh3_main_cth_resource_dyes_3', ItemType.building, 2, 'Progressive cth_resource_dyes', 'Cth Building: Dyemaker'),
    14478: ItemData(IC.useful, 1, 'wh3_main_cth_resource_furs_1', ItemType.building, 0, 'Progressive cth_resource_furs', 'Cth Building: Hunting Camp'),
    14479: ItemData(IC.useful, 1, 'wh3_main_cth_resource_furs_2', ItemType.building, 1, 'Progressive cth_resource_furs', 'Cth Building: Hunting Lodge'),
    14480: ItemData(IC.useful, 1, 'wh3_main_cth_resource_furs_3', ItemType.building, 2, 'Progressive cth_resource_furs', 'Cth Building: Tannery'),
    14481: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gems_1', ItemType.building, 0, 'Progressive cth_resource_gems', 'Cth Building: Gem Mineshaft'),
    14482: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gems_2', ItemType.building, 1, 'Progressive cth_resource_gems', 'Cth Building: Gem Mine'),
    14483: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gems_3', ItemType.building, 2, 'Progressive cth_resource_gems', "Cth Building: Gemcutter's Workshop"),
    14484: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gold_1', ItemType.building, 0, 'Progressive cth_resource_gold', 'Cth Building: Gold Mining Pit'),
    14485: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gold_2', ItemType.building, 1, 'Progressive cth_resource_gold', 'Cth Building: Gold Mine'),
    14486: ItemData(IC.useful, 1, 'wh3_main_cth_resource_gold_3', ItemType.building, 2, 'Progressive cth_resource_gold', 'Cth Building: Gold Smelter'),
    14487: ItemData(IC.useful, 1, 'wh3_main_cth_resource_iron_1', ItemType.building, 0, 'Progressive cth_resource_iron', 'Cth Building: Iron Mining Pit'),
    14488: ItemData(IC.useful, 1, 'wh3_main_cth_resource_iron_2', ItemType.building, 1, 'Progressive cth_resource_iron', 'Cth Building: Iron Mines'),
    14489: ItemData(IC.useful, 1, 'wh3_main_cth_resource_iron_3', ItemType.building, 2, 'Progressive cth_resource_iron', 'Cth Building: Iron Smelter'),
    14490: ItemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_1', ItemType.building, 0, 'Progressive cth_resource_ivory', 'Cth Building: Animal Store'),
    14491: ItemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_2', ItemType.building, 1, 'Progressive cth_resource_ivory', 'Cth Building: Tusk Market'),
    14492: ItemData(IC.useful, 1, 'wh3_main_cth_resource_ivory_3', ItemType.building, 2, 'Progressive cth_resource_ivory', 'Cth Building: Tusk Compound'),
    14493: ItemData(IC.useful, 1, 'wh3_main_cth_resource_marble_1', ItemType.building, 0, 'Progressive cth_resource_marble', 'Cth Building: Sawyer'),
    14494: ItemData(IC.useful, 1, 'wh3_main_cth_resource_marble_2', ItemType.building, 1, 'Progressive cth_resource_marble', 'Cth Building: Marble Quarry'),
    14495: ItemData(IC.useful, 1, 'wh3_main_cth_resource_marble_3', ItemType.building, 2, 'Progressive cth_resource_marble', "Cth Building: Stone Mason's Workshop"),
    14496: ItemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_1', ItemType.building, 0, 'Progressive cth_resource_medicine', "Cth Building: Herb Gatherer's Camp"),
    14497: ItemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_2', ItemType.building, 1, 'Progressive cth_resource_medicine', 'Cth Building: Exotic Hothouse'),
    14498: ItemData(IC.useful, 1, 'wh3_main_cth_resource_medicine_3', ItemType.building, 2, 'Progressive cth_resource_medicine', 'Cth Building: Alchemy Workshop'),
    14499: ItemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_1', ItemType.building, 0, 'Progressive cth_resource_obsidian', 'Cth Building: Obsidian Quarry'),
    14500: ItemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_2', ItemType.building, 1, 'Progressive cth_resource_obsidian', 'Cth Building: Obsidian Trinket Maker'),
    14501: ItemData(IC.useful, 1, 'wh3_main_cth_resource_obsidian_3', ItemType.building, 2, 'Progressive cth_resource_obsidian', 'Cth Building: Obsidian Amulet Carver'),
    14502: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_1', ItemType.building, 0, 'Progressive cth_resource_pasture', 'Cth Building: Grazing Pastures'),
    14503: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_2', ItemType.building, 1, 'Progressive cth_resource_pasture', 'Cth Building: Livestock Pens'),
    14504: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pasture_3', ItemType.building, 2, 'Progressive cth_resource_pasture', 'Cth Building: Cattle Ranch'),
    14505: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_1', ItemType.building, 0, 'Progressive cth_resource_pottery', 'Cth Building: Clay Pit'),
    14506: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_2', ItemType.building, 1, 'Progressive cth_resource_pottery', 'Cth Building: Pottery Maker'),
    14507: ItemData(IC.useful, 1, 'wh3_main_cth_resource_pottery_3', ItemType.building, 2, 'Progressive cth_resource_pottery', 'Cth Building: Kilns'),
    14508: ItemData(IC.useful, 1, 'wh3_main_cth_resource_salt_1', ItemType.building, 0, 'Progressive cth_resource_salt', 'Cth Building: Brine Mining Pans'),
    14509: ItemData(IC.useful, 1, 'wh3_main_cth_resource_salt_2', ItemType.building, 1, 'Progressive cth_resource_salt', 'Cth Building: Brine Mining Basin'),
    14510: ItemData(IC.useful, 1, 'wh3_main_cth_resource_salt_3', ItemType.building, 2, 'Progressive cth_resource_salt', 'Cth Building: Saltworks'),
    14511: ItemData(IC.useful, 1, 'wh3_main_cth_resource_spices_1', ItemType.building, 0, 'Progressive cth_resource_spices', 'Cth Building: Spice Market'),
    14512: ItemData(IC.useful, 1, 'wh3_main_cth_resource_spices_2', ItemType.building, 1, 'Progressive cth_resource_spices', 'Cth Building: Spice Trading Post'),
    14513: ItemData(IC.useful, 1, 'wh3_main_cth_resource_spices_3', ItemType.building, 2, 'Progressive cth_resource_spices', 'Cth Building: Eastern Bazaar'),
    14514: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wine_1', ItemType.building, 0, 'Progressive cth_resource_wine', 'Cth Building: Orchards'),
    14515: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wine_2', ItemType.building, 1, 'Progressive cth_resource_wine', 'Cth Building: Vineyard'),
    14516: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wine_3', ItemType.building, 2, 'Progressive cth_resource_wine', 'Cth Building: Vintner'),
    14517: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wood_1', ItemType.building, 0, 'Progressive cth_resource_wood', "Cth Building: Woodman's Hut"),
    14518: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wood_2', ItemType.building, 1, 'Progressive cth_resource_wood', 'Cth Building: Timber Mill'),
    14519: ItemData(IC.useful, 1, 'wh3_main_cth_resource_wood_3', ItemType.building, 2, 'Progressive cth_resource_wood', 'Cth Building: Lumberyard'),
    14520: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_major_1', ItemType.building, 0, 'Progressive cth_settlement_major', 'Cth Building: Hamlet'),
    14521: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_major_2', ItemType.building, 1, 'Progressive cth_settlement_major', 'Cth Building: Village'),
    14522: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_major_3', ItemType.building, 2, 'Progressive cth_settlement_major', 'Cth Building: Town'),
    14523: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_major_4', ItemType.building, 3, 'Progressive cth_settlement_major', 'Cth Building: City'),
    14524: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_major_5', ItemType.building, 4, 'Progressive cth_settlement_major', 'Cth Building: Province Capital'),
    14525: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_1', ItemType.building, 0, 'Progressive cth_settlement_minor', 'Cth Building: Hamlet'),
    14526: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_2', ItemType.building, 1, 'Progressive cth_settlement_minor', 'Cth Building: Village'),
    14527: ItemData(IC.useful, 1, 'wh3_main_cth_settlement_minor_3', ItemType.building, 2, 'Progressive cth_settlement_minor', 'Cth Building: Town'),
    14528: ItemData(IC.useful, 1, 'wh3_main_cth_walls_minor_1', ItemType.building, 0, 'Progressive cth_walls_minor', 'Cth Building: Stockades'),
    14529: ItemData(IC.useful, 1, 'wh3_main_cth_walls_minor_2', ItemType.building, 1, 'Progressive cth_walls_minor', 'Cth Building: Pagodan Walls'),
    14530: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_cth', 'Cth Building: Sky Lantern Lookouts'),
    14531: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_cth', 'Cth Building: Sky Lantern Scouts'),
    14532: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_cth_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_cth', 'Cth Building: Dragon Sentries')
}

techs: dict[int, ItemData] = {
    14800: ItemData(IC.useful, 1, 'wh3_main_tech_cth_1', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Horse Bonding'),
    14801: ItemData(IC.useful, 1, 'wh3_main_tech_cth_24', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Jade Veteran Facility'),
    14802: ItemData(IC.useful, 1, 'wh3_main_tech_cth_48', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Longma Bridles'),
    14803: ItemData(IC.useful, 1, 'wh3_main_tech_cth_2', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Rite of Yang'),
    14804: ItemData(IC.useful, 1, 'wh3_main_tech_cth_25', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Sentinel Rites'),
    14805: ItemData(IC.useful, 1, 'wh3_main_tech_cth_47', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Improved Husbandry'),
    14806: ItemData(IC.useful, 1, 'wh3_main_tech_cth_26', ItemType.tech, 8, 'Progressive tech_cth', 'Cth Tech: Inner Strength'),
    14807: ItemData(IC.useful, 1, 'wh3_main_tech_cth_27', ItemType.tech, 8, 'Progressive tech_cth', 'Cth Tech: Yang Kiln'),
    14808: ItemData(IC.useful, 1, 'wh3_main_tech_cth_28', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Mastery of Yang'),
    14809: ItemData(IC.useful, 1, 'wh3_main_tech_cth_29', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Flanking Stratagems'),
    14810: ItemData(IC.useful, 1, 'wh3_main_tech_cth_3', ItemType.tech, 3, 'Progressive tech_cth', 'Cth Tech: Jade Stance'),
    14811: ItemData(IC.useful, 1, 'wh3_main_tech_cth_4', ItemType.tech, 3, 'Progressive tech_cth', 'Cth Tech: Bureaucrat Training'),
    14812: ItemData(IC.useful, 1, 'wh3_main_tech_cth_49', ItemType.tech, 14, 'Progressive tech_cth', 'Cth Tech: Enhanced Yang Sight'),
    14813: ItemData(IC.useful, 1, 'wh3_main_tech_cth_5', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Inner Chai'),
    14814: ItemData(IC.useful, 1, 'wh3_main_tech_cth_50', ItemType.tech, 14, 'Progressive tech_cth', 'Cth Tech: Grace of Xen Yang'),
    14815: ItemData(IC.useful, 1, 'wh3_main_tech_cth_51', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Kunlan Anvil'),
    14816: ItemData(IC.useful, 1, 'wh3_main_tech_cth_52', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Dragon Fleet Aegis'),
    14817: ItemData(IC.useful, 1, 'wh3_main_tech_cth_6', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Inner Speed'),
    14818: ItemData(IC.useful, 1, 'wh3_main_tech_cth_30', ItemType.tech, 7, 'Progressive tech_cth', 'Cth Tech: Improved Winches'),
    14819: ItemData(IC.useful, 1, 'wh3_main_tech_cth_31', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Peasant Triage'),
    14820: ItemData(IC.useful, 1, 'wh3_main_tech_cth_32', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Magnetic Polarity'),
    14821: ItemData(IC.useful, 1, 'wh3_main_tech_cth_53', ItemType.tech, 13, 'Progressive tech_cth', 'Cth Tech: Celestial Endurance Training'),
    14822: ItemData(IC.useful, 1, 'wh3_main_tech_cth_54', ItemType.tech, 15, 'Progressive tech_cth', "Cth Tech: Thieves' Guild"),
    14823: ItemData(IC.useful, 1, 'wh3_main_tech_cth_55', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Yang Reflection'),
    14824: ItemData(IC.useful, 1, 'wh3_main_tech_cth_7', ItemType.tech, 2, 'Progressive tech_cth', 'Cth Tech: Drill Training'),
    14825: ItemData(IC.useful, 1, 'wh3_main_tech_cth_8', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Contained Aggression'),
    14826: ItemData(IC.useful, 1, 'wh3_main_tech_cth_9', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Improved Brazier'),
    14827: ItemData(IC.useful, 1, 'wh3_main_tech_cth_10', ItemType.tech, 1, 'Progressive tech_cth', 'Cth Tech: Seasoned Trackers'),
    14828: ItemData(IC.useful, 1, 'wh3_main_tech_cth_11', ItemType.tech, 2, 'Progressive tech_cth', 'Cth Tech: Hardened Bamboo'),
    14829: ItemData(IC.useful, 1, 'wh3_main_tech_cth_12', ItemType.tech, 8, 'Progressive tech_cth', 'Cth Tech: Blessed Temple Guardians'),
    14830: ItemData(IC.useful, 1, 'wh3_main_tech_cth_13', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Alchemic Mortar'),
    14831: ItemData(IC.useful, 1, 'wh3_main_tech_cth_14', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Administrative Subsidies'),
    14832: ItemData(IC.useful, 1, 'wh3_main_tech_cth_33', ItemType.tech, 6, 'Progressive tech_cth', 'Cth Tech: Dynastic Finishing'),
    14833: ItemData(IC.useful, 1, 'wh3_main_tech_cth_34', ItemType.tech, 7, 'Progressive tech_cth', 'Cth Tech: Astromantic Choir'),
    14834: ItemData(IC.useful, 1, 'wh3_main_tech_cth_35', ItemType.tech, 3, 'Progressive tech_cth', 'Cth Tech: Peasant Levy Edict'),
    14835: ItemData(IC.useful, 1, 'wh3_main_tech_cth_36', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Sea Dragon Edict'),
    14836: ItemData(IC.useful, 1, 'wh3_main_tech_cth_37', ItemType.tech, 11, 'Progressive tech_cth', 'Cth Tech: Nan-Gau Forges'),
    14837: ItemData(IC.useful, 1, 'wh3_main_tech_cth_56', ItemType.tech, 12, 'Progressive tech_cth', 'Cth Tech: Alchemist Compact'),
    14838: ItemData(IC.useful, 1, 'wh3_main_tech_cth_57', ItemType.tech, 13, 'Progressive tech_cth', 'Cth Tech: Festival Edict'),
    14839: ItemData(IC.useful, 1, 'wh3_main_tech_cth_58', ItemType.tech, 14, 'Progressive tech_cth', 'Cth Tech: Incorruptible Dogma'),
    14840: ItemData(IC.useful, 1, 'wh3_main_tech_cth_59', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Alignment Calibration'),
    14841: ItemData(IC.useful, 1, 'wh3_main_tech_cth_60', ItemType.tech, 16, 'Progressive tech_cth', "Cth Tech: Dragon Emperor's Blessing"),
    14842: ItemData(IC.useful, 1, 'wh3_main_tech_cth_70', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Widened Roads'),
    14843: ItemData(IC.useful, 1, 'wh3_main_tech_cth_15', ItemType.tech, 2, 'Progressive tech_cth', 'Cth Tech: Fletching Mentors'),
    14844: ItemData(IC.useful, 1, 'wh3_main_tech_cth_16', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Harmonic Balance'),
    14845: ItemData(IC.useful, 1, 'wh3_main_tech_cth_17', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Chelonian Stance'),
    14846: ItemData(IC.useful, 1, 'wh3_main_tech_cth_38', ItemType.tech, 7, 'Progressive tech_cth', 'Cth Tech: Nan-Gau Weaponry'),
    14847: ItemData(IC.useful, 1, 'wh3_main_tech_cth_39', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Stalking Techniques'),
    14848: ItemData(IC.useful, 1, 'wh3_main_tech_cth_40', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Harmonic Mindfulness'),
    14849: ItemData(IC.useful, 1, 'wh3_main_tech_cth_61', ItemType.tech, 13, 'Progressive tech_cth', 'Cth Tech: Jade Bolts'),
    14850: ItemData(IC.useful, 1, 'wh3_main_tech_cth_62', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Clay-Scrying'),
    14851: ItemData(IC.useful, 1, 'wh3_main_tech_cth_63', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Yin Healing'),
    14852: ItemData(IC.useful, 1, 'wh3_main_tech_cth_18', ItemType.tech, 3, 'Progressive tech_cth', 'Cth Tech: Dragon Scales'),
    14853: ItemData(IC.useful, 1, 'wh3_main_tech_cth_19', ItemType.tech, 3, 'Progressive tech_cth', 'Cth Tech: Harmonic Discipline'),
    14854: ItemData(IC.useful, 1, 'wh3_main_tech_cth_20', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Harmonic Mastery'),
    14855: ItemData(IC.useful, 1, 'wh3_main_tech_cth_21', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Yin Hex'),
    14856: ItemData(IC.useful, 1, 'wh3_main_tech_cth_41', ItemType.tech, 8, 'Progressive tech_cth', 'Cth Tech: Yin Defence'),
    14857: ItemData(IC.useful, 1, 'wh3_main_tech_cth_42', ItemType.tech, 8, 'Progressive tech_cth', 'Cth Tech: Moon Wood'),
    14858: ItemData(IC.useful, 1, 'wh3_main_tech_cth_43', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Yin Muse'),
    14859: ItemData(IC.useful, 1, 'wh3_main_tech_cth_44', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Wadding Cartridges'),
    14860: ItemData(IC.useful, 1, 'wh3_main_tech_cth_64', ItemType.tech, 14, 'Progressive tech_cth', 'Cth Tech: Moon Reflecting'),
    14861: ItemData(IC.useful, 1, 'wh3_main_tech_cth_65', ItemType.tech, 14, 'Progressive tech_cth', 'Cth Tech: Grace of the Dragon Empress'),
    14862: ItemData(IC.useful, 1, 'wh3_main_tech_cth_66', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Powder Mixing'),
    14863: ItemData(IC.useful, 1, 'wh3_main_tech_cth_67', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Yin Flow'),
    14864: ItemData(IC.useful, 1, 'wh3_main_tech_cth_22', ItemType.tech, 4, 'Progressive tech_cth', 'Cth Tech: Grace of Quai Yin'),
    14865: ItemData(IC.useful, 1, 'wh3_main_tech_cth_45', ItemType.tech, 9, 'Progressive tech_cth', 'Cth Tech: Jagged Shrapnel'),
    14866: ItemData(IC.useful, 1, 'wh3_main_tech_cth_68', ItemType.tech, 15, 'Progressive tech_cth', 'Cth Tech: Crane Sights'),
    14867: ItemData(IC.useful, 1, 'wh3_main_tech_cth_23', ItemType.tech, 5, 'Progressive tech_cth', 'Cth Tech: Defensive Formations'),
    14868: ItemData(IC.useful, 1, 'wh3_main_tech_cth_46', ItemType.tech, 10, 'Progressive tech_cth', 'Cth Tech: Target Ranges'),
    14869: ItemData(IC.useful, 1, 'wh3_main_tech_cth_69', ItemType.tech, 16, 'Progressive tech_cth', 'Cth Tech: Sky Junk Rigging')
}

progUnits: dict[int, ItemData] = {
    15200: ItemData(IC.useful, 4, "Progressive cth_inf", ItemType.unit, 4, "", "Progressive Cth Unit: Infantry"),
    15201: ItemData(IC.useful, 4, "Progressive cth_rng", ItemType.unit, 4, "", "Progressive Cth Unit: Ranged"),
    15202: ItemData(IC.useful, 3, "Progressive cth_cav", ItemType.unit, 3, "", "Progressive Cth Unit: Cavalry"),
    15203: ItemData(IC.useful, 2, "Progressive cth_art", ItemType.unit, 2, "", "Progressive Cth Unit: Artillery"),
    15204: ItemData(IC.useful, 4, "Progressive cth_veh", ItemType.unit, 4, "", "Progressive Cth Unit: War Machine"),
    15205: ItemData(IC.useful, 3, "Progressive cth_bst", ItemType.unit, 3, "", "Progressive Cth Unit: Beast"),
    15206: ItemData(IC.useful, 1, "Progressive cth_hro", ItemType.unit, 1, "", "Progressive Cth Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    15300: ItemData(IC.useful, 3, 'Progressive cth_allied_outpost', ItemType.building, 3, None, 'Progressive Cth Building: Allied Outpost'),
    15301: ItemData(IC.useful, 2, 'Progressive cth_artillery', ItemType.building, 2, None, 'Progressive Cth Building: Artillery'),
    15302: ItemData(IC.useful, 5, 'Progressive cth_bastion', ItemType.building, 5, None, 'Progressive Cth Building: Bastion'),
    15303: ItemData(IC.useful, 3, 'Progressive cth_cavalry', ItemType.building, 3, None, 'Progressive Cth Building: Cavalry'),
    15304: ItemData(IC.useful, 2, 'Progressive cth_celestial', ItemType.building, 2, None, 'Progressive Cth Building: Celestial'),
    15305: ItemData(IC.useful, 3, 'Progressive cth_defence_yang', ItemType.building, 3, None, 'Progressive Cth Building: Defence Yang'),
    15306: ItemData(IC.useful, 3, 'Progressive cth_defence_yin', ItemType.building, 3, None, 'Progressive Cth Building: Defence Yin'),
    15307: ItemData(IC.useful, 3, 'Progressive cth_growth_yang', ItemType.building, 3, None, 'Progressive Cth Building: Growth Yang'),
    15308: ItemData(IC.useful, 3, 'Progressive cth_growth_yin', ItemType.building, 3, None, 'Progressive Cth Building: Growth Yin'),
    15309: ItemData(IC.useful, 3, 'Progressive cth_gunners', ItemType.building, 3, None, 'Progressive Cth Building: Gunners'),
    15310: ItemData(IC.useful, 3, 'Progressive cth_income_yang', ItemType.building, 3, None, 'Progressive Cth Building: Income Yang'),
    15311: ItemData(IC.useful, 3, 'Progressive cth_income_yin', ItemType.building, 3, None, 'Progressive Cth Building: Income Yin'),
    15312: ItemData(IC.useful, 3, 'Progressive cth_jade_barracks', ItemType.building, 3, None, 'Progressive Cth Building: Jade Barracks'),
    15313: ItemData(IC.useful, 3, 'Progressive cth_magic_tower', ItemType.building, 3, None, 'Progressive Cth Building: Magic Tower'),
    15314: ItemData(IC.useful, 3, 'Progressive cth_order_yang', ItemType.building, 3, None, 'Progressive Cth Building: Order Yang'),
    15315: ItemData(IC.useful, 3, 'Progressive cth_order_yin', ItemType.building, 3, None, 'Progressive Cth Building: Order Yin'),
    15316: ItemData(IC.useful, 3, 'Progressive cth_port', ItemType.building, 3, None, 'Progressive Cth Building: Port'),
    15317: ItemData(IC.useful, 3, 'Progressive cth_resource_animals', ItemType.building, 3, None, 'Progressive Cth Building: Animals'),
    15318: ItemData(IC.useful, 3, 'Progressive cth_resource_dyes', ItemType.building, 3, None, 'Progressive Cth Building: Dyes'),
    15319: ItemData(IC.useful, 3, 'Progressive cth_resource_furs', ItemType.building, 3, None, 'Progressive Cth Building: Furs'),
    15320: ItemData(IC.useful, 3, 'Progressive cth_resource_gems', ItemType.building, 3, None, 'Progressive Cth Building: Gems'),
    15321: ItemData(IC.useful, 3, 'Progressive cth_resource_gold', ItemType.building, 3, None, 'Progressive Cth Building: Gold'),
    15322: ItemData(IC.useful, 3, 'Progressive cth_resource_iron', ItemType.building, 3, None, 'Progressive Cth Building: Iron'),
    15323: ItemData(IC.useful, 3, 'Progressive cth_resource_ivory', ItemType.building, 3, None, 'Progressive Cth Building: Ivory'),
    15324: ItemData(IC.useful, 3, 'Progressive cth_resource_marble', ItemType.building, 3, None, 'Progressive Cth Building: Marble'),
    15325: ItemData(IC.useful, 3, 'Progressive cth_resource_medicine', ItemType.building, 3, None, 'Progressive Cth Building: Medicine'),
    15326: ItemData(IC.useful, 3, 'Progressive cth_resource_obsidian', ItemType.building, 3, None, 'Progressive Cth Building: Obsidian'),
    15327: ItemData(IC.useful, 3, 'Progressive cth_resource_pasture', ItemType.building, 3, None, 'Progressive Cth Building: Pasture'),
    15328: ItemData(IC.useful, 3, 'Progressive cth_resource_pottery', ItemType.building, 3, None, 'Progressive Cth Building: Pottery'),
    15329: ItemData(IC.useful, 3, 'Progressive cth_resource_salt', ItemType.building, 3, None, 'Progressive Cth Building: Salt'),
    15330: ItemData(IC.useful, 3, 'Progressive cth_resource_spices', ItemType.building, 3, None, 'Progressive Cth Building: Spices'),
    15331: ItemData(IC.useful, 3, 'Progressive cth_resource_wine', ItemType.building, 3, None, 'Progressive Cth Building: Wine'),
    15332: ItemData(IC.useful, 3, 'Progressive cth_resource_wood', ItemType.building, 3, None, 'Progressive Cth Building: Wood'),
    15333: ItemData(IC.useful, 5, 'Progressive cth_settlement_major', ItemType.building, 5, None, 'Progressive Cth Building: Settlement Major'),
    15334: ItemData(IC.useful, 3, 'Progressive cth_settlement_minor', ItemType.building, 3, None, 'Progressive Cth Building: Settlement Minor'),
    15335: ItemData(IC.useful, 2, 'Progressive cth_walls_minor', ItemType.building, 2, None, 'Progressive Cth Building: Walls Minor'),
    15336: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_cth', ItemType.building, 3, None, 'Progressive Cth Building: Foreign Slot Discovery Cth')
}

progTechs: dict[int, ItemData] = {
    15400: ItemData(IC.useful, 16, "Progressive tech_cth", ItemType.tech, 16, None, "Progressive Cth Tech: Technology"),
}

special: dict[int, ItemData] = {

}