from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    16024: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_goblin_labourers', ItemType.unit, 1, 'Progressive chd_inf', 'Chd Unit: Goblin Labourers'),
    16015: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_orc_labourers', ItemType.unit, 1, 'Progressive chd_inf', 'Chd Unit: Orc Labourers'),
    16021: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_hobgoblin_sneaky_gits', ItemType.unit, 1, 'Progressive chd_inf', 'Chd Unit: Hobgoblin Sneaky Gits'),
    16022: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_hobgoblin_cutthroats', ItemType.unit, 1, 'Progressive chd_inf', 'Chd Unit: Hobgoblin Cutthroats'),
    16027: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_chaos_dwarf_warriors', ItemType.unit, 2, 'Progressive chd_inf', 'Chd Unit: Chaos Dwarf Warriors'),
    16026: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_chaos_dwarf_warriors_great_weapons', ItemType.unit, 2, 'Progressive chd_inf', 'Chd Unit: Chaos Dwarf Warriors (Great Weapons)'),
    16020: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_infernal_guard', ItemType.unit, 3, 'Progressive chd_inf', 'Chd Unit: Infernal Guard'),
    16018: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_infernal_guard_great_weapons', ItemType.unit, 3, 'Progressive chd_inf', 'Chd Unit: Infernal Guard (Great Weapons)'),
    16011: ItemData(IC.useful, 1, 'wh3_dlc23_chd_mon_kdaai_fireborn', ItemType.unit, 3, 'Progressive chd_inf', "Chd Unit: K'daai Fireborn"),
    16017: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_infernal_ironsworn', ItemType.unit, 4, 'Progressive chd_inf', 'Chd Unit: Infernal Ironsworn'),

    16023: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_hobgoblin_archers', ItemType.unit, 1, 'Progressive chd_rng', 'Chd Unit: Hobgoblin Archers'),
    16029: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_chaos_dwarf_blunderbusses', ItemType.unit, 2, 'Progressive chd_rng', 'Chd Unit: Chaos Dwarf Blunderbusses'),
    16019: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_infernal_guard_fireglaives', ItemType.unit, 3, 'Progressive chd_rng', 'Chd Unit: Infernal Guard (Fireglaives)'),

    16074: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_spears', ItemType.unit, 1, 'Progressive chd_cav', 'Chd Unit: Hobgoblin Wolf Raiders (Spears)'),
    16076: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_bows', ItemType.unit, 1, 'Progressive chd_cav', 'Chd Unit: Hobgoblin Wolf Raiders (Bows)'),
    16080: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_bull_centaurs_axe', ItemType.unit, 1, 'Progressive chd_cav', 'Chd Unit: Bull Centaur Renders'),
    16079: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_bull_centaurs_dual_axe', ItemType.unit, 2, 'Progressive chd_cav', 'Chd Unit: Bull Centaur Renders (Dual Axes)'),
    16077: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_bull_centaurs_greatweapons', ItemType.unit, 2, 'Progressive chd_cav', 'Chd Unit: Bull Centaur Renders (Great Weapons)'),

    16000: ItemData(IC.useful, 1, 'wh3_main_chd_art_hobgob_bolt_thrower', ItemType.unit, 1, 'Progressive chd_art', 'Chd Unit: Hobgoblin Bolt Thrower'),
    16002: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_skullcracker', ItemType.unit, 1, 'Progressive chd_art', 'Chd Unit: Skullcracker'),
    16003: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_magma_cannon', ItemType.unit, 1, 'Progressive chd_art', 'Chd Unit: Magma Cannon'),
    16007: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_iron_daemon', ItemType.unit, 1, 'Progressive chd_art', 'Chd Unit: Iron Daemon'),
    16009: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_deathshrieker_rocket_launcher', ItemType.unit, 2, 'Progressive chd_art', 'Chd Unit: Deathshrieker Rocket Launcher'),
    16082: ItemData(IC.useful, 1, 'wh_main_chs_art_hellcannon', ItemType.unit, 2, 'Progressive chd_art', 'Chd Unit: Hellcannon'),
    16008: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_dreadquake_mortar', ItemType.unit, 3, 'Progressive chd_art', 'Chd Unit: Dreadquake Mortar'),
    16006: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_iron_daemon_1dreadquake', ItemType.unit, 3, 'Progressive chd_art', 'Chd Unit: Iron Daemon - Dreadquake Mortar'),
    16001: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_skullcracker_1dreadquake', ItemType.unit, 3, 'Progressive chd_art', 'Chd Unit: Skullcracker - Dreadquake Mortar'),

    16013: ItemData(IC.useful, 1, 'wh3_dlc23_chd_mon_great_taurus', ItemType.unit, 1, 'Progressive chd_bst', 'Chd Unit: Great Taurus'),
    16010: ItemData(IC.useful, 1, 'wh3_dlc23_chd_mon_lammasu', ItemType.unit, 2, 'Progressive chd_bst', 'Chd Unit: Lammasu'),
    16014: ItemData(IC.useful, 1, 'wh3_dlc23_chd_mon_bale_taurus', ItemType.unit, 3, 'Progressive chd_bst', 'Chd Unit: Bale Taurus'),
    16012: ItemData(IC.useful, 1, 'wh3_dlc23_chd_mon_kdaai_destroyer', ItemType.unit, 4, 'Progressive chd_bst', "Chd Unit: K'daai Destroyer"),

    16051: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_infernal_castellan', ItemType.unit, 1, 'Progressive chd_cav', 'Chd Unit: Infernal Castellan'),
    16072: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_bull_centaur_taurruk', ItemType.unit, 1, 'Progressive chd_hro', "Chd Unit: Bull Centaur Taur'ruk"),
    16059: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_daemonsmith_sorcerer_metal', ItemType.unit, 1, 'Progressive chd_hro', 'Chd Unit: Daemonsmith Sorcerer (Metal)'),
    16063: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_daemonsmith_sorcerer_hashut', ItemType.unit, 1, 'Progressive chd_hro', 'Chd Unit: Daemonsmith Sorcerer (Hashut)'),
    16067: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_daemonsmith_sorcerer_fire', ItemType.unit, 1, 'Progressive chd_hro', 'Chd Unit: Daemonsmith Sorcerer (Fire)'),
    16071: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cha_daemonsmith_sorcerer_death', ItemType.unit, 1, 'Progressive chd_hro', 'Chd Unit: Daemonsmith Sorcerer (Death)'),

    16075: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_ror', ItemType.unit, 1, 'Progressive chd_cav', "Chd Unit: Oglah Khan's Wolfboyz"),
    16025: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_chaos_dwarf_warriors_ror', ItemType.unit, 2, 'Progressive chd_inf', 'Chd Unit: The Blazing Beards of Bazherak (Chaos Dwarf Warriors)'),
    16028: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_chaos_dwarf_blunderbusses_ror', ItemType.unit, 2, 'Progressive chd_rng', 'Chd Unit: The Granite Guard (Chaos Dwarf Blunderbusses)'),
    16016: ItemData(IC.useful, 1, 'wh3_dlc23_chd_inf_infernal_ironsworn_ror', ItemType.unit, 4, 'Progressive chd_inf', 'Chd Unit: The Immortals (Infernal Ironsworn)'),
    16078: ItemData(IC.useful, 1, 'wh3_dlc23_chd_cav_bull_centaurs_dual_axe_ror', ItemType.unit, 2, 'Progressive chd_cav', "Chd Unit: Hashut's Dark Ravagers (Bull Centaur Renders - Dual Axes)"),
    16004: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_iron_daemon_ror_1dreadquake', ItemType.unit, 3, 'Progressive chd_art', "Chd Unit: The Daemon's Tongue - Dreadquake Mortar"),
    16081: ItemData(IC.useful, 1, 'wh_pro04_chs_art_hellcannon_ror_0', ItemType.unit, 2, 'Progressive chd_art', 'Chd Unit: The Soul of Damnation (Hellcannon)'),
    16083: ItemData(IC.useful, 1, 'wh_dlc08_nor_art_hellcannon_battery', ItemType.unit, 2, 'Progressive chd_art', 'Chd Unit: The Ice-Forged Legion (Hellcannons)'),
    #16005: ItemData(IC.useful, 1, 'wh3_dlc23_chd_veh_iron_daemon_ror', ItemType.unit, 4, 'Progressive chd_veh', "Chd Unit: The Daemon's Tongue (Iron Daemon)"),
}

buildings: dict[int, ItemData] = {
    16400: ItemData(IC.useful, 1, 'wh3_dlc23_chd_allied_outpost_1', ItemType.building, 0, 'Progressive chd_allied_outpost', 'Chd Building: Chaos Dwarf Outpost'),
    16401: ItemData(IC.useful, 1, 'wh3_dlc23_chd_allied_outpost_2', ItemType.building, 1, 'Progressive chd_allied_outpost', 'Chd Building: Chaos Dwarf District'),
    16402: ItemData(IC.useful, 1, 'wh3_dlc23_chd_allied_outpost_3', ItemType.building, 2, 'Progressive chd_allied_outpost', 'Chd Building: Chaos Dwarf Colony'),
    16403: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_assembly_line_1', ItemType.building, 0, 'Progressive chd_factory_assembly_line', 'Chd Building: Gunsmith'),
    16404: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_assembly_line_2', ItemType.building, 1, 'Progressive chd_factory_assembly_line', 'Chd Building: Weapons Workshop'),
    16405: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_assembly_line_3', ItemType.building, 2, 'Progressive chd_factory_assembly_line', 'Chd Building: Armament Assembly Line'),
    16406: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_drills_1', ItemType.building, 0, 'Progressive chd_factory_drills', "Chd Building: Miners' Workshop"),
    16407: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_drills_2', ItemType.building, 1, 'Progressive chd_factory_drills', 'Chd Building: Tools Manufactory'),
    16408: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_garrison_1', ItemType.building, 0, 'Progressive chd_factory_garrison', 'Chd Building: Factory Guardhouse'),
    16409: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_garrison_2', ItemType.building, 1, 'Progressive chd_factory_garrison', 'Chd Building: Factory Walls'),
    16410: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_garrison_3', ItemType.building, 2, 'Progressive chd_factory_garrison', 'Chd Building: Factory Compound'),
    16411: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_port_1', ItemType.building, 0, 'Progressive chd_factory_port', 'Chd Building: Redirected River'),
    16412: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_port_2', ItemType.building, 1, 'Progressive chd_factory_port', 'Chd Building: Sluice Gate'),
    16413: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_port_3', ItemType.building, 2, 'Progressive chd_factory_port', 'Chd Building: Black Water Sluice Gates'),
    16414: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_refinery_1', ItemType.building, 0, 'Progressive chd_factory_refinery', 'Chd Building: Gold Panners'),
    16415: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_refinery_2', ItemType.building, 1, 'Progressive chd_factory_refinery', 'Chd Building: Gold Sluice'),
    16416: ItemData(IC.useful, 1, 'wh3_dlc23_chd_factory_refinery_3', ItemType.building, 2, 'Progressive chd_factory_refinery', 'Chd Building: Gold Refinery'),
    16417: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_beasts_1', ItemType.building, 0, 'Progressive chd_military_beasts', 'Chd Building: Lava Fields'),
    16418: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_beasts_2', ItemType.building, 1, 'Progressive chd_military_beasts', 'Chd Building: Monster Pens'),
    16419: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_beasts_3', ItemType.building, 2, 'Progressive chd_military_beasts', 'Chd Building: Fire Enclave'),
    16420: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_chaos_dwarf_infantry_1', ItemType.building, 0, 'Progressive chd_military_chaos_dwarf_infantry', 'Chd Building: Ash Level'),
    16421: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_chaos_dwarf_infantry_2', ItemType.building, 1, 'Progressive chd_military_chaos_dwarf_infantry', 'Chd Building: Ore Level'),
    16422: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_chaos_dwarf_infantry_3', ItemType.building, 2, 'Progressive chd_military_chaos_dwarf_infantry', 'Chd Building: Iron Level'),
    16423: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_hobgoblins_1', ItemType.building, 0, 'Progressive chd_military_hobgoblins', 'Chd Building: Hobgoblin Mustering Camp'),
    16424: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_hobgoblins_2', ItemType.building, 1, 'Progressive chd_military_hobgoblins', 'Chd Building: Hobgoblin Bivouacs'),
    16425: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_kdaai_1', ItemType.building, 0, 'Progressive chd_military_kdaai', 'Chd Building: Daemonsmithy'),
    16426: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_kdaai_2', ItemType.building, 1, 'Progressive chd_military_kdaai', 'Chd Building: Altar of Fire'),
    16427: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_kdaai_3', ItemType.building, 2, 'Progressive chd_military_kdaai', 'Chd Building: Great Kiln of Hashut'),
    16428: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_war_machines_1', ItemType.building, 0, 'Progressive chd_military_war_machines', 'Chd Building: Ironworks'),
    16429: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_war_machines_2', ItemType.building, 1, 'Progressive chd_military_war_machines', 'Chd Building: Grand Manufactory'),
    16430: ItemData(IC.useful, 1, 'wh3_dlc23_chd_military_war_machines_3', ItemType.building, 2, 'Progressive chd_military_war_machines', 'Chd Building: Manufactory Complex'),
    16431: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_mine_1', ItemType.building, 0, 'Progressive chd_outpost_mine', 'Chd Building: Strip Mine'),
    16432: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_mine_2', ItemType.building, 1, 'Progressive chd_outpost_mine', 'Chd Building: Mineshaft'),
    16433: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_mine_3', ItemType.building, 2, 'Progressive chd_outpost_mine', 'Chd Building: Underground Caverns'),
    16434: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_overseer_hut_1', ItemType.building, 0, 'Progressive chd_outpost_overseer_hut', 'Chd Building: Garrison Outpost'),
    16435: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_overseer_hut_2', ItemType.building, 1, 'Progressive chd_outpost_overseer_hut', 'Chd Building: Garrison Base'),
    16436: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_overseer_hut_3', ItemType.building, 2, 'Progressive chd_outpost_overseer_hut', 'Chd Building: Garrison Headquarters'),
    16437: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_port_1', ItemType.building, 0, 'Progressive chd_outpost_port', 'Chd Building: Irrigation Canals'),
    16438: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_port_2', ItemType.building, 1, 'Progressive chd_outpost_port', 'Chd Building: Qanat'),
    16439: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_port_3', ItemType.building, 2, 'Progressive chd_outpost_port', 'Chd Building: Yakhchal'),
    16440: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_scavangers_hovel_1', ItemType.building, 0, 'Progressive chd_outpost_scavangers_hovel', 'Chd Building: Money Pit'),
    16441: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_scavangers_hovel_2', ItemType.building, 1, 'Progressive chd_outpost_scavangers_hovel', 'Chd Building: Locked Stores'),
    16442: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_scavangers_hovel_3', ItemType.building, 2, 'Progressive chd_outpost_scavangers_hovel', 'Chd Building: Treasure Trove'),
    16443: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_watch_towers_1', ItemType.building, 0, 'Progressive chd_outpost_watch_towers', 'Chd Building: Guard Tower'),
    16444: ItemData(IC.useful, 1, 'wh3_dlc23_chd_outpost_watch_towers_2', ItemType.building, 1, 'Progressive chd_outpost_watch_towers', 'Chd Building: Watchtower'),
    16445: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_animals_1', ItemType.building, 0, 'Progressive chd_resource_animals', 'Chd Building: Wolf Tamer'),
    16446: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_animals_2', ItemType.building, 1, 'Progressive chd_resource_animals', 'Chd Building: Wolf Taming Pens'),
    16447: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_animals_3', ItemType.building, 2, 'Progressive chd_resource_animals', 'Chd Building: Giant Wolf Stables'),
    16448: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_dyes_1', ItemType.building, 0, 'Progressive chd_resource_dyes', 'Chd Building: Blood Rock Strip Mine'),
    16449: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_dyes_2', ItemType.building, 1, 'Progressive chd_resource_dyes', 'Chd Building: Cinnabar Mine'),
    16450: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_dyes_3', ItemType.building, 2, 'Progressive chd_resource_dyes', 'Chd Building: Dye-Maker'),
    16451: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_furs_1', ItemType.building, 0, 'Progressive chd_resource_furs', 'Chd Building: Tannery'),
    16452: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_furs_2', ItemType.building, 1, 'Progressive chd_resource_furs', 'Chd Building: Hatmakers'),
    16453: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_furs_3', ItemType.building, 2, 'Progressive chd_resource_furs', 'Chd Building: Hattery'),
    16454: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_gems_1', ItemType.building, 0, 'Progressive chd_resource_gems', 'Chd Building: Gem Refinery'),
    16455: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_gold_1', ItemType.building, 0, 'Progressive chd_resource_gold', 'Chd Building: Gold Mine'),
    16456: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_gold_2', ItemType.building, 1, 'Progressive chd_resource_gold', 'Chd Building: Gold Smelter'),
    16457: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_gold_3', ItemType.building, 2, 'Progressive chd_resource_gold', "Chd Building: Goldsmiths' Guild Hall"),
    16458: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_iron_1', ItemType.building, 0, 'Progressive chd_resource_iron', 'Chd Building: High-Quality Assembly Line'),
    16459: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_ivory_1', ItemType.building, 0, 'Progressive chd_resource_ivory', 'Chd Building: Animal Store'),
    16460: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_ivory_2', ItemType.building, 1, 'Progressive chd_resource_ivory', 'Chd Building: Tusk Market'),
    16461: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_ivory_3', ItemType.building, 2, 'Progressive chd_resource_ivory', 'Chd Building: Tusk Compound'),
    16462: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_marble_1', ItemType.building, 0, 'Progressive chd_resource_marble', 'Chd Building: Marble Quarry'),
    16463: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_medicine_1', ItemType.building, 0, 'Progressive chd_resource_medicine', "Chd Building: Herbalist's Camp"),
    16464: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_medicine_2', ItemType.building, 1, 'Progressive chd_resource_medicine', "Chd Building: Alchemist's Workshop"),
    16465: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_medicine_3', ItemType.building, 2, 'Progressive chd_resource_medicine', "Chd Building: Alchemists' Guild Hall"),
    16466: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_obsidian_1', ItemType.building, 0, 'Progressive chd_resource_obsidian', 'Chd Building: Obsidian Quarry'),
    16467: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pastures_1', ItemType.building, 0, 'Progressive chd_resource_pastures', 'Chd Building: Goat Pastures'),
    16468: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pastures_2', ItemType.building, 1, 'Progressive chd_resource_pastures', 'Chd Building: Goat Herd'),
    16469: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pastures_3', ItemType.building, 2, 'Progressive chd_resource_pastures', 'Chd Building: Goat Farm'),
    16470: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pottery_1', ItemType.building, 0, 'Progressive chd_resource_pottery', 'Chd Building: Clay Pit'),
    16471: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pottery_2', ItemType.building, 1, 'Progressive chd_resource_pottery', 'Chd Building: Potter'),
    16472: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_pottery_3', ItemType.building, 2, 'Progressive chd_resource_pottery', 'Chd Building: Kilns'),
    16473: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_salt_1', ItemType.building, 0, 'Progressive chd_resource_salt', 'Chd Building: Brine Well'),
    16474: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_salt_2', ItemType.building, 1, 'Progressive chd_resource_salt', 'Chd Building: Brine Mine'),
    16475: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_salt_3', ItemType.building, 2, 'Progressive chd_resource_salt', 'Chd Building: Saltworks'),
    16476: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_spices_1', ItemType.building, 0, 'Progressive chd_resource_spices', 'Chd Building: Spice Trading Post'),
    16477: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_spices_2', ItemType.building, 1, 'Progressive chd_resource_spices', 'Chd Building: Spice Market'),
    16478: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_spices_3', ItemType.building, 2, 'Progressive chd_resource_spices', 'Chd Building: Eastern Bazaar'),
    16479: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_timber_1', ItemType.building, 0, 'Progressive chd_resource_timber', 'Chd Building: Charcoal Forge'),
    16480: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_wine_1', ItemType.building, 0, 'Progressive chd_resource_wine', 'Chd Building: Orchards'),
    16481: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_wine_2', ItemType.building, 1, 'Progressive chd_resource_wine', 'Chd Building: Vineyard'),
    16482: ItemData(IC.useful, 1, 'wh3_dlc23_chd_resource_wine_3', ItemType.building, 2, 'Progressive chd_resource_wine', 'Chd Building: Distillery'),
    16483: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_factory_1', ItemType.building, 0, 'Progressive chd_settlement_factory', 'Chd Building: Workshop'),
    16484: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_factory_2', ItemType.building, 1, 'Progressive chd_settlement_factory', 'Chd Building: Factory'),
    16485: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_factory_3', ItemType.building, 2, 'Progressive chd_settlement_factory', 'Chd Building: Production Plant'),
    16486: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_outpost_1', ItemType.building, 0, 'Progressive chd_settlement_outpost', 'Chd Building: Outpost'),
    16487: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_outpost_2', ItemType.building, 1, 'Progressive chd_settlement_outpost', "Chd Building: Overseers' Camp"),
    16488: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_outpost_3', ItemType.building, 2, 'Progressive chd_settlement_outpost', "Chd Building: Overseers' Tower"),
    16489: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_tower_1', ItemType.building, 0, 'Progressive chd_settlement_tower', 'Chd Building: Foundations'),
    16490: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_tower_2', ItemType.building, 1, 'Progressive chd_settlement_tower', 'Chd Building: Ramparts'),
    16491: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_tower_3', ItemType.building, 2, 'Progressive chd_settlement_tower', 'Chd Building: Battlements'),
    16492: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_tower_4', ItemType.building, 3, 'Progressive chd_settlement_tower', 'Chd Building: Gun Turrets'),
    16493: ItemData(IC.useful, 1, 'wh3_dlc23_chd_settlement_tower_5', ItemType.building, 4, 'Progressive chd_settlement_tower', 'Chd Building: Tower of Hashut'),
    16494: ItemData(IC.useful, 1, 'wh3_dlc23_chd_special_settlement_tower_1', ItemType.building, 0, 'Progressive chd_settlement_tower', 'Chd Building: Foundations'),
    16495: ItemData(IC.useful, 1, 'wh3_dlc23_chd_special_settlement_tower_2', ItemType.building, 1, 'Progressive chd_settlement_tower', 'Chd Building: Ramparts'),
    16496: ItemData(IC.useful, 1, 'wh3_dlc23_chd_special_settlement_tower_3', ItemType.building, 2, 'Progressive chd_settlement_tower', 'Chd Building: Battlements'),
    16497: ItemData(IC.useful, 1, 'wh3_dlc23_chd_special_settlement_tower_4', ItemType.building, 3, 'Progressive chd_settlement_tower', 'Chd Building: Gun Turrets'),
    16498: ItemData(IC.useful, 1, 'wh3_dlc23_chd_special_settlement_tower_5', ItemType.building, 4, 'Progressive chd_settlement_tower', 'Chd Building: Tower of Hashut'),
    16499: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_ballistics_1', ItemType.building, 0, 'Progressive chd_tower_ballistics', 'Chd Building: Prototype Megamortar'),
    16500: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_ballistics_2', ItemType.building, 1, 'Progressive chd_tower_ballistics', 'Chd Building: Dreadquake Megamortar'),
    16501: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_furnace_1', ItemType.building, 0, 'Progressive chd_tower_furnace', 'Chd Building: Cinerator'),
    16502: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_furnace_2', ItemType.building, 1, 'Progressive chd_tower_furnace', 'Chd Building: Grand Furnace'),
    16503: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_living_quaters_1', ItemType.building, 0, 'Progressive chd_tower_living_quaters', 'Chd Building: Ziggurat Tenements'),
    16504: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_living_quaters_2', ItemType.building, 1, 'Progressive chd_tower_living_quaters', "Chd Building: Overseers' Quarters"),
    16505: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_living_quaters_3', ItemType.building, 2, 'Progressive chd_tower_living_quaters', "Chd Building: Sorcerer-Prophet's Tower"),
    16506: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_living_quaters_4', ItemType.building, 3, 'Progressive chd_tower_living_quaters', "Chd Building: Sorcerer-Prophet's Estate"),
    16507: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_patrol_1', ItemType.building, 0, 'Progressive chd_tower_patrol', 'Chd Building: Patrol Routes'),
    16508: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_patrol_2', ItemType.building, 1, 'Progressive chd_tower_patrol', 'Chd Building: Tower Roads'),
    16509: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_patrol_3', ItemType.building, 2, 'Progressive chd_tower_patrol', 'Chd Building: Rail Network'),
    16510: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_port_1', ItemType.building, 0, 'Progressive chd_tower_port', 'Chd Building: Trade Landing'),
    16511: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_port_2', ItemType.building, 1, 'Progressive chd_tower_port', 'Chd Building: Trade Wharf'),
    16512: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_port_3', ItemType.building, 2, 'Progressive chd_tower_port', 'Chd Building: Trading Hub'),
    16513: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_guardhouse_1', ItemType.building, 0, 'Progressive chd_tower_temple_guardhouse', 'Chd Building: Fane Guard'),
    16514: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_guardhouse_2', ItemType.building, 1, 'Progressive chd_tower_temple_guardhouse', 'Chd Building: Fane Guardhouse'),
    16515: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_guardhouse_3', ItemType.building, 2, 'Progressive chd_tower_temple_guardhouse', 'Chd Building: Fane Barracks'),
    16516: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_guardhouse_4', ItemType.building, 3, 'Progressive chd_tower_temple_guardhouse', 'Chd Building: Temple Guard'),
    16517: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_guardhouse_5', ItemType.building, 4, 'Progressive chd_tower_temple_guardhouse', 'Chd Building: Temple Guardhouse'),
    16518: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_temple_of_hashut_1', ItemType.building, 0, 'Progressive chd_tower_temple_of_hashut', 'Chd Building: Temple of Hashut'),
    16519: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_tribute_halls_1', ItemType.building, 0, 'Progressive chd_tower_tribute_halls', 'Chd Building: Donation Barrel'),
    16520: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_tribute_halls_2', ItemType.building, 1, 'Progressive chd_tower_tribute_halls', 'Chd Building: Tribute Collectors'),
    16521: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_tribute_halls_3', ItemType.building, 2, 'Progressive chd_tower_tribute_halls', 'Chd Building: Tribute Shrine'),
    16522: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_tribute_halls_4', ItemType.building, 3, 'Progressive chd_tower_tribute_halls', 'Chd Building: Tithe Chamber'),
    16523: ItemData(IC.useful, 1, 'wh3_dlc23_chd_tower_tribute_halls_5', ItemType.building, 4, 'Progressive chd_tower_tribute_halls', 'Chd Building: Treasure Hall')
}

techs: dict[int, ItemData] = {
    16872: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_2', ItemType.tech, 1, 'Progressive tech_chd_military_1', 'Chd Tech: Stronghold Syndrome'),
    16871: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_1', ItemType.tech, 2, 'Progressive tech_chd_military_1', 'Chd Tech: Starved Wolves'),
    16844: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_13', ItemType.tech, 3, 'Progressive tech_chd_military_1', 'Chd Tech: Hobgoblin Quartermasters'),
    16835: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_15', ItemType.tech, 4, 'Progressive tech_chd_military_1', 'Chd Tech: Living Metal'),
    16830: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_17', ItemType.tech, 5, 'Progressive tech_chd_military_1', 'Chd Tech: Temple Training'),
    16811: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_22', ItemType.tech, 6, 'Progressive tech_chd_military_1', 'Chd Tech: Mighty Monsters'),
    16802: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_27', ItemType.tech, 7, 'Progressive tech_chd_military_1', 'Chd Tech: Beasts of Zharr'),
    16858: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_6', ItemType.tech, 2, 'Progressive tech_chd_military_1', 'Chd Tech: Mandatory Service'),
    16859: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_7', ItemType.tech, 3, 'Progressive tech_chd_military_1', 'Chd Tech: Roaming Round-ups'),
    16857: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_5', ItemType.tech, 4, 'Progressive tech_chd_military_1', 'Chd Tech: Scorched Earth'),
    16848: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_11', ItemType.tech, 5, 'Progressive tech_chd_military_1', 'Chd Tech: Mass Production'),

    16873: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_3', ItemType.tech, 1, 'Progressive tech_chd_military_2', 'Chd Tech: The Call to War'),
    16874: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_4', ItemType.tech, 2, 'Progressive tech_chd_military_2', 'Chd Tech: Hollow Rounds'),
    16845: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_14', ItemType.tech, 3, 'Progressive tech_chd_military_2', 'Chd Tech: Varied Training '),
    16836: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_16', ItemType.tech, 4, 'Progressive tech_chd_military_2', 'Chd Tech: Boiling Blood Sacrifices'),
    16831: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_19', ItemType.tech, 5, 'Progressive tech_chd_military_2', 'Chd Tech: Daemon Forges'),
    16815: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_26', ItemType.tech, 6, 'Progressive tech_chd_military_2', 'Chd Tech: Continuous Bombardment'),
    16804: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_29', ItemType.tech, 7, 'Progressive tech_chd_military_2', 'Chd Tech: Weapons of War'),
    16861: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_9', ItemType.tech, 2, 'Progressive tech_chd_military_2', 'Chd Tech: Martial Training'),
    16860: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_8', ItemType.tech, 3, 'Progressive tech_chd_military_2', 'Chd Tech: Smog Shroud'),
    16849: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_12', ItemType.tech, 4, 'Progressive tech_chd_military_2', 'Chd Tech: Ceaseless March'),
    16856: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_10', ItemType.tech, 5, 'Progressive tech_chd_military_2', 'Chd Tech: Tactical Review'),

    16837: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_18', ItemType.tech, 1, 'Progressive tech_chd_military_3', 'Chd Tech: Reduced Rations'),
    16832: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_20', ItemType.tech, 2, 'Progressive tech_chd_military_3', 'Chd Tech: Alchemical Remedies'),
    16822: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_21', ItemType.tech, 3, 'Progressive tech_chd_military_3', 'Chd Tech: Ammunition Caches'),
    16813: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_24', ItemType.tech, 4, 'Progressive tech_chd_military_3', 'Chd Tech: Weapons Depots'),
    16803: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_28', ItemType.tech, 5, 'Progressive tech_chd_military_3', 'Chd Tech: Total War!'),
    16812: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_23', ItemType.tech, 5, 'Progressive tech_chd_military_3', 'Chd Tech: Medical Supplies'),
    16814: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_military_25', ItemType.tech, 5, 'Progressive tech_chd_military_3', 'Chd Tech: Chosen by the Father'),

    16875: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_1', ItemType.tech, 1, 'Progressive tech_chd_sorcery', 'Chd Tech: Tallest Towers'),
    16864: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_2', ItemType.tech, 2, 'Progressive tech_chd_sorcery', 'Chd Tech: Pandemic Preparations'),
    16862: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_3', ItemType.tech, 3, 'Progressive tech_chd_sorcery', 'Chd Tech: Future of the Dawi-Zharr'),
    16850: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_5', ItemType.tech, 4, 'Progressive tech_chd_sorcery', 'Chd Tech: Finest Leaders'),
    16846: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_7', ItemType.tech, 5, 'Progressive tech_chd_sorcery', 'Chd Tech: Signature Spellcasting'),
    16839: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_9', ItemType.tech, 6, 'Progressive tech_chd_sorcery', 'Chd Tech: Mutual Benefits'),
    16833: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_11', ItemType.tech, 7, 'Progressive tech_chd_sorcery', "Chd Tech: Architect's Decrees"),
    16824: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_14', ItemType.tech, 8, 'Progressive tech_chd_sorcery', 'Chd Tech: Hashut Bound'),
    16823: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_13', ItemType.tech, 9, 'Progressive tech_chd_sorcery', 'Chd Tech: Sacrificial Vats'),
    16816: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_18', ItemType.tech, 10, 'Progressive tech_chd_sorcery', 'Chd Tech: Shyish Bound'),
    16805: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_22', ItemType.tech, 11, 'Progressive tech_chd_sorcery', 'Chd Tech: Mass Sacrifices'),
    16817: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_19', ItemType.tech, 9, 'Progressive tech_chd_sorcery', 'Chd Tech: Imperishability Rituals'),
    16863: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_4', ItemType.tech, 3, 'Progressive tech_chd_sorcery', 'Chd Tech: Brazen Bodyguard'),
    16851: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_6', ItemType.tech, 4, 'Progressive tech_chd_sorcery', 'Chd Tech: Envoys to the Conclave'),
    16847: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_8', ItemType.tech, 5, 'Progressive tech_chd_sorcery', 'Chd Tech: Malicious Compliance'),
    16838: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_10', ItemType.tech, 6, 'Progressive tech_chd_sorcery', 'Chd Tech: Ruinous Negotiations'),
    16834: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_12', ItemType.tech, 7, 'Progressive tech_chd_sorcery', 'Chd Tech: Tyrannical Decrees'),
    16826: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_16', ItemType.tech, 8, 'Progressive tech_chd_sorcery', 'Chd Tech: Metallurgy'),
    16827: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_17', ItemType.tech, 9, 'Progressive tech_chd_sorcery', 'Chd Tech: Hashut Reverence'),
    16819: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_21', ItemType.tech, 10, 'Progressive tech_chd_sorcery', 'Chd Tech: Aqshy Bound'),
    16806: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_23', ItemType.tech, 11, 'Progressive tech_chd_sorcery', 'Chd Tech: Powers of the Conclave'),
    16818: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_20', ItemType.tech, 9, 'Progressive tech_chd_sorcery', 'Chd Tech: Conclave Dominance'),
    16825: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_sorcery_15', ItemType.tech, 10, 'Progressive tech_chd_sorcery', 'Chd Tech: Communing Altar'),

    16867: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_3', ItemType.tech, 1, 'Progressive tech_chd_industry_1', 'Chd Tech: Labour Quotas'),
    16866: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_2', ItemType.tech, 2, 'Progressive tech_chd_industry_1', 'Chd Tech: Live to Work, Work to Live'),
    16865: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_1', ItemType.tech, 3, 'Progressive tech_chd_industry_1', 'Chd Tech: Applied Assignments'),
    16855: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_9', ItemType.tech, 4, 'Progressive tech_chd_industry_1', 'Chd Tech: Wagon Engineering'),
    16842: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_13', ItemType.tech, 5, 'Progressive tech_chd_industry_1', 'Chd Tech: Extended Shifts'),
    16853: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_7', ItemType.tech, 2, 'Progressive tech_chd_industry_1', 'Chd Tech: Harbour Guilds'),
    16840: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_11', ItemType.tech, 3, 'Progressive tech_chd_industry_1', 'Chd Tech: Hotter Furnaces'),
    16828: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_15', ItemType.tech, 4, 'Progressive tech_chd_industry_1', 'Chd Tech: Industrial Revolution'),
    16820: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_17', ItemType.tech, 5, 'Progressive tech_chd_industry_1', 'Chd Tech: Stockpiling'),
    16808: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_20', ItemType.tech, 6, 'Progressive tech_chd_industry_1', 'Chd Tech: Increased Resource Allocation'),
    16800: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_23', ItemType.tech, 7, 'Progressive tech_chd_industry_1', 'Chd Tech: Labour Organisation'),
    16807: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_19', ItemType.tech, 7, 'Progressive tech_chd_industry_1', 'Chd Tech: Workforce Diktats'),

    16868: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_4', ItemType.tech, 1, 'Progressive tech_chd_industry_2', 'Chd Tech: Merchant Guilds'),
    16869: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_5', ItemType.tech, 2, 'Progressive tech_chd_industry_2', 'Chd Tech: Wartime Economy'),
    16870: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_6', ItemType.tech, 3, 'Progressive tech_chd_industry_2', 'Chd Tech: Territorial Consignments'),
    16852: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_10', ItemType.tech, 4, 'Progressive tech_chd_industry_2', 'Chd Tech: Siege Logistics'),
    16843: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_14', ItemType.tech, 5, 'Progressive tech_chd_industry_2', 'Chd Tech: Siege Supplies'),
    16854: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_8', ItemType.tech, 2, 'Progressive tech_chd_industry_2', 'Chd Tech: Veteran Convoy Master'),
    16841: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_12', ItemType.tech, 3, 'Progressive tech_chd_industry_2', 'Chd Tech: Overseer Organisation'),
    16829: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_16', ItemType.tech, 4, 'Progressive tech_chd_industry_2', 'Chd Tech: Industrial Security'),
    16821: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_18', ItemType.tech, 5, 'Progressive tech_chd_industry_2', 'Chd Tech: Resource Extractors'),
    16809: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_21', ItemType.tech, 6, 'Progressive tech_chd_industry_2', 'Chd Tech: Arms Monopoly'),
    16801: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_24', ItemType.tech, 7, 'Progressive tech_chd_industry_2', 'Chd Tech: Unilateral Agreements'),
    16810: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_industry_22', ItemType.tech, 7, 'Progressive tech_chd_industry_2', 'Chd Tech: Convoy Cartographers'),

    #16876: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_third_carriage_hidden', ItemType.tech, 0, 'Progressive tech_chd', 'Chd Tech: Reach 12 unit capacity for Warmachines to unlock second carriage'),
    #16877: ItemData(IC.useful, 1, 'wh3_dlc23_tech_chd_second_carriage_hidden', ItemType.tech, 0, 'Progressive tech_chd', 'Chd Tech: Reach 10 unit capacity for Warmachines to unlock second carriage')
}

progUnits: dict[int, ItemData] = {
    17200: ItemData(IC.useful, 4, "Progressive chd_inf", ItemType.unit, 4, "", "Progressive Chd Unit: Infantry"),
    17201: ItemData(IC.useful, 3, "Progressive chd_rng", ItemType.unit, 3, "", "Progressive Chd Unit: Ranged"),
    17202: ItemData(IC.useful, 2, "Progressive chd_cav", ItemType.unit, 2, "", "Progressive Chd Unit: Cavalry"),
    17203: ItemData(IC.useful, 3, "Progressive chd_art", ItemType.unit, 3, "", "Progressive Chd Unit: Artillery"),
    17205: ItemData(IC.useful, 4, "Progressive chd_bst", ItemType.unit, 4, "", "Progressive Chd Unit: Beast"),
    17206: ItemData(IC.useful, 1, "Progressive chd_hro", ItemType.unit, 1, "", "Progressive Chd Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    17302: ItemData(IC.useful, 3, 'Progressive chd_allied_outpost', ItemType.building, 3, None, 'Progressive Chd Building: Allied Outpost'),
    17305: ItemData(IC.useful, 3, 'Progressive chd_factory_assembly_line', ItemType.building, 3, None, 'Progressive Chd Building: Factory Assembly Line'),
    17307: ItemData(IC.useful, 2, 'Progressive chd_factory_drills', ItemType.building, 2, None, 'Progressive Chd Building: Factory Drills'),
    17310: ItemData(IC.useful, 3, 'Progressive chd_factory_garrison', ItemType.building, 3, None, 'Progressive Chd Building: Factory Garrison'),
    17313: ItemData(IC.useful, 3, 'Progressive chd_factory_port', ItemType.building, 3, None, 'Progressive Chd Building: Factory Port'),
    17316: ItemData(IC.useful, 3, 'Progressive chd_factory_refinery', ItemType.building, 3, None, 'Progressive Chd Building: Factory Refinery'),
    17319: ItemData(IC.useful, 3, 'Progressive chd_military_beasts', ItemType.building, 3, None, 'Progressive Chd Building: Military Beasts'),
    17322: ItemData(IC.useful, 3, 'Progressive chd_military_chaos_dwarf_infantry', ItemType.building, 3, None, 'Progressive Chd Building: Military Chaos Dwarf Infantry'),
    17324: ItemData(IC.useful, 2, 'Progressive chd_military_hobgoblins', ItemType.building, 2, None, 'Progressive Chd Building: Military Hobgoblins'),
    17327: ItemData(IC.useful, 3, 'Progressive chd_military_kdaai', ItemType.building, 3, None, 'Progressive Chd Building: Military Kdaai'),
    17330: ItemData(IC.useful, 3, 'Progressive chd_military_war_machines', ItemType.building, 3, None, 'Progressive Chd Building: Military War Machines'),
    17333: ItemData(IC.useful, 3, 'Progressive chd_outpost_mine', ItemType.building, 3, None, 'Progressive Chd Building: Outpost Mine'),
    17336: ItemData(IC.useful, 3, 'Progressive chd_outpost_overseer_hut', ItemType.building, 3, None, 'Progressive Chd Building: Outpost Overseer Hut'),
    17339: ItemData(IC.useful, 3, 'Progressive chd_outpost_port', ItemType.building, 3, None, 'Progressive Chd Building: Outpost Port'),
    17342: ItemData(IC.useful, 3, 'Progressive chd_outpost_scavangers_hovel', ItemType.building, 3, None, 'Progressive Chd Building: Outpost Scavangers Hovel'),
    17344: ItemData(IC.useful, 2, 'Progressive chd_outpost_watch_towers', ItemType.building, 2, None, 'Progressive Chd Building: Outpost Watch Towers'),
    17347: ItemData(IC.useful, 3, 'Progressive chd_resource_animals', ItemType.building, 3, None, 'Progressive Chd Building: Animals'),
    17350: ItemData(IC.useful, 3, 'Progressive chd_resource_dyes', ItemType.building, 3, None, 'Progressive Chd Building: Dyes'),
    17353: ItemData(IC.useful, 3, 'Progressive chd_resource_furs', ItemType.building, 3, None, 'Progressive Chd Building: Furs'),
    17354: ItemData(IC.useful, 1, 'Progressive chd_resource_gems', ItemType.building, 1, None, 'Progressive Chd Building: Gems'),
    17357: ItemData(IC.useful, 3, 'Progressive chd_resource_gold', ItemType.building, 3, None, 'Progressive Chd Building: Gold'),
    17358: ItemData(IC.useful, 1, 'Progressive chd_resource_iron', ItemType.building, 1, None, 'Progressive Chd Building: Iron'),
    17361: ItemData(IC.useful, 3, 'Progressive chd_resource_ivory', ItemType.building, 3, None, 'Progressive Chd Building: Ivory'),
    17362: ItemData(IC.useful, 1, 'Progressive chd_resource_marble', ItemType.building, 1, None, 'Progressive Chd Building: Marble'),
    17365: ItemData(IC.useful, 3, 'Progressive chd_resource_medicine', ItemType.building, 3, None, 'Progressive Chd Building: Medicine'),
    17366: ItemData(IC.useful, 1, 'Progressive chd_resource_obsidian', ItemType.building, 1, None, 'Progressive Chd Building: Obsidian'),
    17369: ItemData(IC.useful, 3, 'Progressive chd_resource_pastures', ItemType.building, 3, None, 'Progressive Chd Building: Pastures'),
    17372: ItemData(IC.useful, 3, 'Progressive chd_resource_pottery', ItemType.building, 3, None, 'Progressive Chd Building: Pottery'),
    17375: ItemData(IC.useful, 3, 'Progressive chd_resource_salt', ItemType.building, 3, None, 'Progressive Chd Building: Salt'),
    17378: ItemData(IC.useful, 3, 'Progressive chd_resource_spices', ItemType.building, 3, None, 'Progressive Chd Building: Spices'),
    17379: ItemData(IC.useful, 1, 'Progressive chd_resource_timber', ItemType.building, 1, None, 'Progressive Chd Building: Timber'),
    17382: ItemData(IC.useful, 3, 'Progressive chd_resource_wine', ItemType.building, 3, None, 'Progressive Chd Building: Wine'),
    17385: ItemData(IC.useful, 3, 'Progressive chd_settlement_factory', ItemType.building, 3, None, 'Progressive Chd Building: Settlement Factory'),
    17388: ItemData(IC.useful, 3, 'Progressive chd_settlement_outpost', ItemType.building, 3, None, 'Progressive Chd Building: Settlement Outpost'),
    17393: ItemData(IC.useful, 5, 'Progressive chd_settlement_tower', ItemType.building, 5, None, 'Progressive Chd Building: Settlement Tower'),
    17400: ItemData(IC.useful, 2, 'Progressive chd_tower_ballistics', ItemType.building, 2, None, 'Progressive Chd Building: Tower Ballistics'),
    17402: ItemData(IC.useful, 2, 'Progressive chd_tower_furnace', ItemType.building, 2, None, 'Progressive Chd Building: Tower Furnace'),
    17406: ItemData(IC.useful, 4, 'Progressive chd_tower_living_quaters', ItemType.building, 4, None, 'Progressive Chd Building: Tower Living Quaters'),
    17409: ItemData(IC.useful, 3, 'Progressive chd_tower_patrol', ItemType.building, 3, None, 'Progressive Chd Building: Tower Patrol'),
    17412: ItemData(IC.useful, 3, 'Progressive chd_tower_port', ItemType.building, 3, None, 'Progressive Chd Building: Tower Port'),
    17417: ItemData(IC.useful, 5, 'Progressive chd_tower_temple_guardhouse', ItemType.building, 5, None, 'Progressive Chd Building: Tower Temple Guardhouse'),
    17418: ItemData(IC.useful, 1, 'Progressive chd_tower_temple_of_hashut', ItemType.building, 1, None, 'Progressive Chd Building: Tower Temple Of Hashut'),
    17423: ItemData(IC.useful, 5, 'Progressive chd_tower_tribute_halls', ItemType.building, 5, None, 'Progressive Chd Building: Tower Tribute Halls')
}

progTechs: dict[int, ItemData] = {
    17400: ItemData(IC.useful, 7, "Progressive tech_chd_military_1", ItemType.tech, 7, None, "Progressive Chd Tech: Military Left"),
    17401: ItemData(IC.useful, 7, "Progressive tech_chd_military_2", ItemType.tech, 7, None, "Progressive Chd Tech: Military Right"),
    17402: ItemData(IC.useful, 5, "Progressive tech_chd_military_3", ItemType.tech, 5, None, "Progressive Chd Tech: Military Top"),
    17403: ItemData(IC.useful, 11, "Progressive tech_chd_sorcery", ItemType.tech, 11, None, "Progressive Chd Tech: Sorcery"),
    17404: ItemData(IC.useful, 7, "Progressive tech_chd_industry_1", ItemType.tech, 7, None, "Progressive Chd Tech: Industry Left"),
    17405: ItemData(IC.useful, 7, "Progressive tech_chd_industry_2", ItemType.tech, 7, None, "Progressive Chd Tech: Industry Right"),
}

special: dict[int, ItemData] = {

}