from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    18000: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: Marauders of Khorne (Dual Weapons)'),
    18001: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mnur', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: Marauders of Nurgle'),
    18002: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_0', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: Devoted Marauders of Slaanesh'),
    18003: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_1', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Devoted Marauders of Slaanesh (Spears)'),
    18004: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_2', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Devoted Marauders of Slaanesh (Hellscourges)'),
    18005: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mtze_spears', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: Marauders of Tzeentch (Spears)'),
    18006: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Khorne'),
    18007: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_1', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Khorne (Halberds)'),
    18008: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_2', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Khorne (Dual Weapons)'),
    18009: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    18010: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    18011: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Chaos Warriors of Tzeentch (Halberds)'),
    18012: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_forsaken_mkho', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Forsaken of Khorne'),
    18013: ItemData(IC.useful, 1, 'wh3_main_nur_inf_forsaken_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Forsaken of Nurgle'),
    18014: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_forsaken_msla', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Forsaken of Slaanesh'),
    18015: ItemData(IC.useful, 1, 'wh3_main_tze_inf_forsaken_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Forsaken of Tzeentch'),
    18016: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_khorngors', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Khorngors'),
    18017: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_pestigors', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Pestigors'),
    18018: ItemData(IC.useful, 1, 'wh3_dlc27_tze_inf_slaangors', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Slaangors'),
    18019: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_tzaangors', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Tzaangors'),
    18020: ItemData(IC.useful, 1, 'wh3_main_kho_inf_bloodletters_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Bloodletters of Khorne'),
    18021: ItemData(IC.useful, 1, 'wh3_main_kho_inf_bloodletters_1', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Exalted Bloodletters of Khorne'),
    18022: ItemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Plaguebearers of Nurgle'),
    18023: ItemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_1', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Exalted Plaguebearers of Nurgle'),
    18024: ItemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_0', ItemType.unit, 2, 'Progressive dae_inf', 'Dae Unit: Daemonettes of Slaanesh'),
    18025: ItemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_1', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Exalted Daemonettes of Slaanesh'),
    18026: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_0', ItemType.unit, 2, 'Progressive dae_rng', 'Dae Unit: Pink Horrors of Tzeentch'),
    18027: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_1', ItemType.unit, 3, 'Progressive dae_rng', 'Dae Unit: Exalted Pink Horrors of Tzeentch'),
    18028: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_skullreapers', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Skullreapers'),
    18029: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_wrathmongers', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Wrathmongers'),
    18030: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Plague Ogres'),
    18031: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres_great_weapons', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Plague Ogres (Great Weapons)'),
    18032: ItemData(IC.useful, 1, 'wh3_main_nur_inf_nurglings_0', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: Nurglings'),
    18033: ItemData(IC.useful, 1, 'wh3_main_tze_inf_blue_horrors_0', ItemType.unit, 1, 'Progressive dae_rng', 'Dae Unit: Blue Horrors of Tzeentch'),
    18034: ItemData(IC.useful, 1, 'wh3_main_tze_mon_flamers_0', ItemType.unit, 3, 'Progressive dae_rng', 'Dae Unit: Flamers of Tzeentch'),
    18035: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_flamers_changebringers', ItemType.unit, 4, 'Progressive dae_rng', 'Dae Unit: Changebringers'),
    18036: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Champions of Slaanesh'),
    18037: ItemData(IC.useful, 1, 'wh3_main_kho_mon_spawn_of_khorne_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Spawn of Khorne'),
    18038: ItemData(IC.useful, 1, 'wh3_main_nur_mon_spawn_of_nurgle_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Spawn of Nurgle'),
    18039: ItemData(IC.useful, 1, 'wh3_main_sla_mon_spawn_of_slaanesh_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Spawn of Slaanesh'),
    18040: ItemData(IC.useful, 1, 'wh3_main_tze_mon_spawn_of_tzeentch_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Spawn of Tzeentch'),
    18041: ItemData(IC.useful, 1, 'wh3_main_sla_mon_fiends_of_slaanesh_0', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Fiends of Slaanesh'),

    18071: ItemData(IC.useful, 1, 'wh3_main_kho_mon_khornataurs_0', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Minotaurs of Khorne'),
    18072: ItemData(IC.useful, 1, 'wh3_main_kho_mon_khornataurs_1', ItemType.unit, 5, 'Progressive dae_inf', 'Dae Unit: Minotaurs of Khorne (Great Weapons)'),

    18042: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins', ItemType.unit, 1, 'Progressive dae_cav', 'Dae Unit: Marauder Horsemen of Slaanesh'),
    18043: ItemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_0', ItemType.unit, 1, 'Progressive dae_cav', 'Dae Unit: Hellstriders of Slaanesh'),
    18044: ItemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_1', ItemType.unit, 2, 'Progressive dae_cav', 'Dae Unit: Hellstriders of Slaanesh (Hellscourges)'),
    18045: ItemData(IC.useful, 1, 'wh3_main_sla_cav_seekers_of_slaanesh_0', ItemType.unit, 3, 'Progressive dae_cav', 'Dae Unit: Seekers of Slaanesh'),
    18046: ItemData(IC.useful, 1, 'wh3_main_sla_cav_heartseekers_of_slaanesh_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Heartseekers of Slaanesh'),
    18047: ItemData(IC.useful, 1, 'wh3_dlc27_sla_cav_pleasureseekers', ItemType.unit, 5, 'Progressive dae_cav', 'Dae Unit: Pleasureseekers'),
    18048: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Rot Knights'),
    18049: ItemData(IC.useful, 1, 'wh3_main_nur_cav_pox_riders_of_nurgle_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Pox Riders of Nurgle'),
    18050: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_centigors_great_weapons', ItemType.unit, 3, 'Progressive dae_cav', 'Dae Unit: Centigors of Tzeentch'),
    18051: ItemData(IC.useful, 1, 'wh3_main_tze_cav_chaos_knights_0', ItemType.unit, 3, 'Progressive dae_cav', 'Dae Unit: Chaos Knights of Tzeentch'),
    18052: ItemData(IC.useful, 1, 'wh3_main_tze_cav_doom_knights_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Doom Knights of Tzeentch'),
    18053: ItemData(IC.useful, 1, 'wh3_main_kho_cav_bloodcrushers_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Bloodcrushers of Khorne'),
    18054: ItemData(IC.useful, 1, 'wh3_main_kho_cav_skullcrushers_0', ItemType.unit, 5, 'Progressive dae_cav', 'Dae Unit: Skullcrushers of Khorne'),
    18055: ItemData(IC.useful, 1, 'wh3_main_nur_cav_plague_drones_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Plague Drones of Nurgle'),
    18056: ItemData(IC.useful, 1, 'wh3_main_nur_cav_plague_drones_1', ItemType.unit, 4, 'Progressive dae_cav', "Dae Unit: Plague Drones of Nurgle (Death's Heads)"),
    18057: ItemData(IC.useful, 1, 'wh3_main_kho_veh_skullcannon_0', ItemType.unit, 1, 'Progressive dae_art', 'Dae Unit: Skullcannon'),
    18058: ItemData(IC.useful, 1, 'wh3_main_dae_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Furies'),
    18059: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Furies (Khorne)'),
    18060: ItemData(IC.useful, 1, 'wh3_main_nur_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Furies (Nurgle)'),
    18061: ItemData(IC.useful, 1, 'wh3_main_sla_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Furies (Slaanesh)'),
    18062: ItemData(IC.useful, 1, 'wh3_main_tze_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Furies (Tzeentch)'),
    18063: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mkho', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Chaos Warshrine of Khorne'),
    18064: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mnur', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Chaos Warshrine of Nurgle'),
    18065: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_msla', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Chaos Warshrine of Slaanesh'),
    18066: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mtze', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Chaos Warshrine of Tzeentch'),
    18067: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Chaos Warshrine'),
    18068: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warhounds_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Warhounds of Khorne'),
    18069: ItemData(IC.useful, 1, 'wh3_main_kho_inf_flesh_hounds_of_khorne_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Flesh Hounds of Khorne'),
    18070: ItemData(IC.useful, 1, 'wh3_dlc26_kho_mon_bloodbeast_of_khorne', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Bloodbeasts of Khorne'),
    18073: ItemData(IC.useful, 1, 'wh3_dlc26_kho_mon_slaughterbrute', ItemType.unit, 5, 'Progressive dae_bst', 'Dae Unit: Slaughterbrute'),
    18074: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_1', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Chaos Warhounds (Poison)'),
    18075: ItemData(IC.useful, 1, 'wh3_main_nur_mon_plague_toads_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Plague Toads of Nurgle'),
    18076: ItemData(IC.useful, 1, 'wh3_main_nur_mon_beast_of_nurgle_0', ItemType.unit, 2, 'Progressive dae_bst', 'Dae Unit: Beast of Nurgle'),
    18077: ItemData(IC.useful, 1, 'wh3_main_nur_mon_rot_flies_0', ItemType.unit, 3, 'Progressive dae_bst', 'Dae Unit: Rot Flies'),
    18078: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_toad_dragon', ItemType.unit, 5, 'Progressive dae_bst', 'Dae Unit: Toad Dragon'),
    18079: ItemData(IC.useful, 1, 'wh3_main_tze_mon_screamers_0', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Screamers of Tzeentch'),
    18080: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_cockatrice', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Cockatrice'),
    18081: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_mutalith_vortex_beast', ItemType.unit, 5, 'Progressive dae_bst', 'Dae Unit: Mutalith Vortex Beast'),
    18082: ItemData(IC.useful, 1, 'wh3_main_kho_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Soul Grinder of Khorne'),
    18083: ItemData(IC.useful, 1, 'wh3_main_nur_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Soul Grinder of Nurgle'),
    18084: ItemData(IC.useful, 1, 'wh3_main_sla_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Soul Grinder of Slaanesh'),
    18085: ItemData(IC.useful, 1, 'wh3_main_tze_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Soul Grinder of Tzeentch'),
    18086: ItemData(IC.useful, 1, 'wh3_main_kho_mon_bloodthirster_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Bloodthirster'),
    18087: ItemData(IC.useful, 1, 'wh3_main_nur_mon_great_unclean_one_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Great Unclean One'),
    18088: ItemData(IC.useful, 1, 'wh3_main_sla_mon_keeper_of_secrets_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Keeper of Secrets'),
    18089: ItemData(IC.useful, 1, 'wh_main_chs_cha_lord_of_change_0', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Lord of Change'),
    18090: ItemData(IC.useful, 1, 'wh3_main_kho_veh_blood_shrine_0', ItemType.unit, 1, 'Progressive dae_veh', 'Dae Unit: Blood Shrine of Khorne'),
    18091: ItemData(IC.useful, 1, 'wh3_main_kho_cav_gorebeast_chariot', ItemType.unit, 2, 'Progressive dae_veh', 'Dae Unit: Gorebeast Chariots of Khorne'),
    18092: ItemData(IC.useful, 1, 'wh3_main_sla_veh_seeker_chariot_0', ItemType.unit, 2, 'Progressive dae_veh', 'Dae Unit: Seeker Chariots'),
    18093: ItemData(IC.useful, 1, 'wh3_main_sla_veh_hellflayer_0', ItemType.unit, 4, 'Progressive dae_veh', 'Dae Unit: Hellflayers'),
    18094: ItemData(IC.useful, 1, 'wh3_main_sla_veh_exalted_seeker_chariot_0', ItemType.unit, 5, 'Progressive dae_veh', 'Dae Unit: Exalted Seeker Chariot'),
    18095: ItemData(IC.useful, 1, 'wh3_main_tze_veh_burning_chariot_0', ItemType.unit, 5, 'Progressive dae_veh', 'Dae Unit: Burning Chariot of Tzeentch'),
    18096: ItemData(IC.useful, 1, 'wh3_main_kho_cha_bloodreaper_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Bloodreaper'),
    18097: ItemData(IC.useful, 1, 'wh3_main_nur_cha_plagueridden_death_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Plagueridden (Death)'),
    18098: ItemData(IC.useful, 1, 'wh3_main_nur_cha_plagueridden_nurgle_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Plagueridden (Nurgle)'),
    18099: ItemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_shadow_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Alluress (Shadows)'),
    18100: ItemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_slaanesh_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Alluress (Slaanesh)'),
    18101: ItemData(IC.useful, 1, 'wh3_main_tze_cha_iridescent_horror_metal_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Iridescent Horror (Metal)'),
    18102: ItemData(IC.useful, 1, 'wh3_main_tze_cha_iridescent_horror_tzeentch_0', ItemType.unit, 1, 'Progressive dae_hro', 'Dae Unit: Iridescent Horror (Tzeentch)'),

    18103: ItemData(IC.useful, 1, 'wh3_twa06_kho_inf_bloodletters_ror_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Hellforged Host (Exalted Bloodletters of Khorne)'),
    18104: ItemData(IC.useful, 1, 'wh3_twa06_nur_inf_plaguebearers_ror_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Festering Stooges (Exalted Plaguebearers of Nurgle)'),
    18105: ItemData(IC.useful, 1, 'wh3_twa06_sla_inf_daemonette_ror_0', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Bringers of Beguilement (Exalted Daemonettes of Slaanesh)'),
    18106: ItemData(IC.useful, 1, 'wh3_twa06_tze_inf_pink_horrors_ror_0', ItemType.unit, 3, 'Progressive dae_rng', 'Dae Unit: Blazing Squealers (Exalted Pink Horrors of Tzeentch)'),
    18107: ItemData(IC.useful, 1, 'wh3_twa07_kho_cav_bloodcrushers_ror_0', ItemType.unit, 4, 'Progressive dae_cav', "Dae Unit: Heralds of Khorne's Fury (Bloodcrushers of Khorne)"),
    18108: ItemData(IC.useful, 1, 'wh3_twa07_nur_cav_pox_riders_of_nurgle_ror_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Barons of the Bog (Pox Riders of Nurgle)'),
    18109: ItemData(IC.useful, 1, 'wh3_twa07_sla_cav_heartseekers_of_slaanesh_ror_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Eternal Entourage (Heartseekers of Slaanesh)'),
    18110: ItemData(IC.useful, 1, 'wh3_twa07_tze_cav_doom_knights_ror_0', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: Knights of Immolation (Doom Knights of Tzeentch)'),
    18111: ItemData(IC.useful, 1, 'wh3_twa08_kho_mon_bloodthirster_0_ror', ItemType.unit, 4, 'Progressive dae_bst', "Dae Unit: Khorne's Bloody Fist (Bloodthirster)"),
    18112: ItemData(IC.useful, 1, 'wh3_twa08_nur_mon_great_unclean_one_0_ror', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Uncle Furuncle (Great Unclean One)'),
    18113: ItemData(IC.useful, 1, 'wh3_twa08_sla_mon_keeper_of_secrets_0_ror', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: The Marquis of Masochism (Keeper of Secrets)'),
    18114: ItemData(IC.useful, 1, 'wh3_twa08_tze_mon_lord_of_change_0_ror', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: The Golden Griffin of Theurgy (Lord of Change)'),
    18115: ItemData(IC.useful, 1, 'wh3_twa10_kho_inf_flesh_hounds_of_khorne_ror', ItemType.unit, 1, 'Progressive dae_bst', 'Dae Unit: Hounds of the Blood Hunt (Flesh Hounds of Khorne)'),
    18116: ItemData(IC.useful, 1, 'wh3_twa10_nur_inf_nurglings_ror', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: The Frolickers Bubonic (Nurglings)'),
    18117: ItemData(IC.useful, 1, 'wh3_twa10_tze_inf_blue_horrors_ror', ItemType.unit, 1, 'Progressive dae_rng', 'Dae Unit: The Chromatic Abominations (Blue Horrors of Tzeentch)'),
    18118: ItemData(IC.useful, 1, 'wh3_dlc26_kho_veh_skullcannon_ror', ItemType.unit, 1, 'Progressive dae_art', 'Dae Unit: Hellforged Bellowers (Skullcannon)'),
    18119: ItemData(IC.useful, 1, 'wh3_dlc26_chs_inf_chosen_mkho_ror', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: The Slaughtergard (Chosen of Khorne - Halberds)'),
    18120: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_pink_horrors_ror', ItemType.unit, 2, 'Progressive dae_rng', 'Dae Unit: The Sourguts (Pink Horrors of Tzeentch)'),
    18121: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_plague_drones_1_ror', ItemType.unit, 4, 'Progressive dae_cav', "Dae Unit: The Angels of Decay (Plague Drones - Death's Heads)"),
    18122: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights_ror', ItemType.unit, 4, 'Progressive dae_cav', 'Dae Unit: The Rotting Riders (Rot Knights)'),
    18123: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_soul_grinder_0_ror', ItemType.unit, 4, 'Progressive dae_bst', 'Dae Unit: Noxbringer (Soul Grinder of Nurgle)'),
    18124: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_wrathmongers_ror', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Bloodwake Berserkers (Wrathmongers)'),
    18125: ItemData(IC.useful, 1, 'wh3_twa10_sla_inf_marauders_spears_ror', ItemType.unit, 1, 'Progressive dae_inf', 'Dae Unit: The Princes of Perfection (Devoted Marauders of Slaanesh - Spears)'),
    18126: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh_ror', ItemType.unit, 4, 'Progressive dae_inf', 'Dae Unit: Pleasure Guard (Champions of Slaanesh)'),
    18127: ItemData(IC.useful, 1, 'wh3_dlc27_sla_veh_seeker_chariot_ror', ItemType.unit, 2, 'Progressive dae_veh', 'Dae Unit: Heralds of Excess (Seeker Chariots)')
    #18030: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_bile_trolls', ItemType.unit, 3, 'Progressive dae_inf', 'Dae Unit: Bile Trolls'),
}

buildings: dict[int, ItemData] = {
    18401: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_kho_1', ItemType.building, 0, 'Progressive dae_advanced_2_kho', 'Dae Building: Keep of Khorne'),
    18402: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_kho_2', ItemType.building, 1, 'Progressive dae_advanced_2_kho', 'Dae Building: Bastion of Khorne'),
    18403: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_kho_3', ItemType.building, 2, 'Progressive dae_advanced_2_kho', 'Dae Building: Fortress of Khorne'),
    18404: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_nur_1', ItemType.building, 0, 'Progressive dae_advanced_2_nur', 'Dae Building: Keep of Nurgle'),
    18405: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_nur_2', ItemType.building, 1, 'Progressive dae_advanced_2_nur', 'Dae Building: Bastion of Nurgle'),
    18406: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_nur_3', ItemType.building, 2, 'Progressive dae_advanced_2_nur', 'Dae Building: Fortress of Nurgle'),
    18407: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_sla_1', ItemType.building, 0, 'Progressive dae_advanced_2_sla', 'Dae Building: Keep of Slaanesh'),
    18408: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_sla_2', ItemType.building, 1, 'Progressive dae_advanced_2_sla', 'Dae Building: Bastion of Slaanesh'),
    18409: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_sla_3', ItemType.building, 2, 'Progressive dae_advanced_2_sla', 'Dae Building: Fortress of Slaanesh'),
    18410: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_tze_1', ItemType.building, 0, 'Progressive dae_advanced_2_tze', 'Dae Building: Flying Tower of Tzeentch'),
    18411: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_tze_2', ItemType.building, 1, 'Progressive dae_advanced_2_tze', 'Dae Building: Flying Bastion of Tzeentch'),
    18412: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_2_tze_3', ItemType.building, 2, 'Progressive dae_advanced_2_tze', 'Dae Building: Soaring Fortress of Tzeentch'),
    18413: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_kho_1', ItemType.building, 0, 'Progressive dae_advanced_kho', 'Dae Building: Obelisk of Khorne'),
    18414: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_kho_2', ItemType.building, 1, 'Progressive dae_advanced_kho', 'Dae Building: Monolith of Khorne'),
    18415: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_kho_3', ItemType.building, 2, 'Progressive dae_advanced_kho', 'Dae Building: Monument of Khorne'),
    18416: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_kho_4', ItemType.building, 3, 'Progressive dae_advanced_kho', 'Dae Building: Temple of Khorne'),
    18417: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_kho_5', ItemType.building, 4, 'Progressive dae_advanced_kho', 'Dae Building: Cathedral of Blood'),
    18418: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_nur_1', ItemType.building, 0, 'Progressive dae_advanced_nur', 'Dae Building: Obelisk of Nurgle'),
    18419: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_nur_2', ItemType.building, 1, 'Progressive dae_advanced_nur', 'Dae Building: Monolith of Nurgle'),
    18420: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_nur_3', ItemType.building, 2, 'Progressive dae_advanced_nur', 'Dae Building: Monument of Nurgle'),
    18421: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_nur_4', ItemType.building, 3, 'Progressive dae_advanced_nur', 'Dae Building: Temple of Nurgle'),
    18422: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_nur_5', ItemType.building, 4, 'Progressive dae_advanced_nur', 'Dae Building: Cathedral of Decay'),
    18423: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_sla_1', ItemType.building, 0, 'Progressive dae_advanced_sla', 'Dae Building: Obelisk of Slaanesh'),
    18424: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_sla_2', ItemType.building, 1, 'Progressive dae_advanced_sla', 'Dae Building: Monolith of Slaanesh'),
    18425: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_sla_3', ItemType.building, 2, 'Progressive dae_advanced_sla', 'Dae Building: Monument of Slaanesh'),
    18426: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_sla_4', ItemType.building, 3, 'Progressive dae_advanced_sla', 'Dae Building: Temple of Slaanesh'),
    18427: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_sla_5', ItemType.building, 4, 'Progressive dae_advanced_sla', 'Dae Building: Cathedral of Pain'),
    18428: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_tze_1', ItemType.building, 0, 'Progressive dae_advanced_tze', 'Dae Building: Obelisk of Tzeentch'),
    18429: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_tze_2', ItemType.building, 1, 'Progressive dae_advanced_tze', 'Dae Building: Monolith of Tzeentch'),
    18430: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_tze_3', ItemType.building, 2, 'Progressive dae_advanced_tze', 'Dae Building: Monument of Tzeentch'),
    18431: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_tze_4', ItemType.building, 3, 'Progressive dae_advanced_tze', 'Dae Building: Temple of Tzeentch'),
    18432: ItemData(IC.useful, 1, 'wh3_main_dae_advanced_tze_5', ItemType.building, 4, 'Progressive dae_advanced_tze', 'Dae Building: Cathedral of Change'),
    18433: ItemData(IC.useful, 1, 'wh3_main_dae_allied_outpost_1', ItemType.building, 0, 'Progressive dae_allied_outpost', 'Dae Building: Daemonic Outpost'),
    18434: ItemData(IC.useful, 1, 'wh3_main_dae_allied_outpost_2', ItemType.building, 1, 'Progressive dae_allied_outpost', 'Dae Building: Daemonic District'),
    18435: ItemData(IC.useful, 1, 'wh3_main_dae_allied_outpost_3', ItemType.building, 2, 'Progressive dae_allied_outpost', 'Dae Building: Daemonic Colony'),
    18436: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_kho_1', ItemType.building, 2, 'Progressive dae_barracks_kho', 'Dae Building: Khornate Fane'),
    18437: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_kho_2', ItemType.building, 0, 'Progressive dae_barracks_kho', 'Dae Building: Khornate Altar'),
    18438: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_kho_3', ItemType.building, 1, 'Progressive dae_barracks_kho', 'Dae Building: Khornate Shrine'),
    18439: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_nur_1', ItemType.building, 3, 'Progressive dae_barracks_nur', 'Dae Building: Nurglish Fane'),
    18440: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_nur_2', ItemType.building, 0, 'Progressive dae_barracks_nur', 'Dae Building: Nurglish Altar'),
    18441: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_nur_3', ItemType.building, 1, 'Progressive dae_barracks_nur', 'Dae Building: Nurglish Shrine'),
    18442: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_sla_1', ItemType.building, 4, 'Progressive dae_barracks_sla', 'Dae Building: Slaaneshi Fane'),
    18443: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_sla_2', ItemType.building, 0, 'Progressive dae_barracks_sla', 'Dae Building: Slaaneshi Altar'),
    18444: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_sla_3', ItemType.building, 1, 'Progressive dae_barracks_sla', 'Dae Building: Slaaneshi Shrine'),
    18445: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_tze_1', ItemType.building, 5, 'Progressive dae_barracks_tze', 'Dae Building: Tzeenchian Fane'),
    18446: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_tze_2', ItemType.building, 0, 'Progressive dae_barracks_tze', 'Dae Building: Tzeenchian Altar'),
    18447: ItemData(IC.useful, 1, 'wh3_main_dae_barracks_tze_3', ItemType.building, 1, 'Progressive dae_barracks_tze', 'Dae Building: Tzeenchian Shrine'),
    18448: ItemData(IC.useful, 1, 'wh3_main_dae_control_kho_1', ItemType.building, 0, 'Progressive dae_control_kho', 'Dae Building: Eight-Fold Path'),
    18449: ItemData(IC.useful, 1, 'wh3_main_dae_control_kho_2', ItemType.building, 1, 'Progressive dae_control_kho', 'Dae Building: Sixty-Four-Fold Path'),
    18450: ItemData(IC.useful, 1, 'wh3_main_dae_control_kho_3', ItemType.building, 2, 'Progressive dae_control_kho', 'Dae Building: The 4096th Way'),
    18451: ItemData(IC.useful, 1, 'wh3_main_dae_control_kho_4', ItemType.building, 3, 'Progressive dae_control_kho', "Dae Building: The Skulltaker's Modus"),
    18452: ItemData(IC.useful, 1, 'wh3_main_dae_control_nur_1', ItemType.building, 0, 'Progressive dae_control_nur', 'Dae Building: Seventh Mortuary'),
    18453: ItemData(IC.useful, 1, 'wh3_main_dae_control_nur_2', ItemType.building, 1, 'Progressive dae_control_nur', 'Dae Building: Liber Bacterium'),
    18454: ItemData(IC.useful, 1, 'wh3_main_dae_control_nur_3', ItemType.building, 2, 'Progressive dae_control_nur', 'Dae Building: Daemonic Assembly'),
    18455: ItemData(IC.useful, 1, 'wh3_main_dae_control_nur_4', ItemType.building, 3, 'Progressive dae_control_nur', 'Dae Building: Daemonic Cavalcade'),
    18456: ItemData(IC.useful, 1, 'wh3_main_dae_control_sla_1', ItemType.building, 0, 'Progressive dae_control_sla', 'Dae Building: Carnal Dens'),
    18457: ItemData(IC.useful, 1, 'wh3_main_dae_control_sla_2', ItemType.building, 1, 'Progressive dae_control_sla', 'Dae Building: Inn of Excess'),
    18458: ItemData(IC.useful, 1, 'wh3_main_dae_control_sla_3', ItemType.building, 2, 'Progressive dae_control_sla', "Dae Building: Masochists' Lodge"),
    18459: ItemData(IC.useful, 1, 'wh3_main_dae_control_sla_4', ItemType.building, 3, 'Progressive dae_control_sla', 'Dae Building: Brothel of Six Senses'),
    18460: ItemData(IC.useful, 1, 'wh3_main_dae_control_tze_1', ItemType.building, 0, 'Progressive dae_control_tze', 'Dae Building: Condors of the Steppes'),
    18461: ItemData(IC.useful, 1, 'wh3_main_dae_control_tze_2', ItemType.building, 1, 'Progressive dae_control_tze', 'Dae Building: Convocation of Agitators'),
    18462: ItemData(IC.useful, 1, 'wh3_main_dae_control_tze_3', ItemType.building, 2, 'Progressive dae_control_tze', 'Dae Building: Mirror of Fates'),
    18463: ItemData(IC.useful, 1, 'wh3_main_dae_control_tze_4', ItemType.building, 3, 'Progressive dae_control_tze', 'Dae Building: Occult Aviary'),
    18464: ItemData(IC.useful, 1, 'wh3_main_dae_garrison_major_1', ItemType.building, 0, 'Progressive dae_garrison_major', 'Dae Building: Daemonic Lurkers'),
    18465: ItemData(IC.useful, 1, 'wh3_main_dae_garrison_major_2', ItemType.building, 1, 'Progressive dae_garrison_major', 'Dae Building: Daemonic Gathering'),
    18466: ItemData(IC.useful, 1, 'wh3_main_dae_garrison_major_3', ItemType.building, 2, 'Progressive dae_garrison_major', 'Dae Building: Daemonic Locus'),
    18467: ItemData(IC.useful, 1, 'wh3_main_dae_garrison_minor_1', ItemType.building, 0, 'Progressive dae_garrison_minor', 'Dae Building: Lookouts'),
    18468: ItemData(IC.useful, 1, 'wh3_main_dae_garrison_minor_2', ItemType.building, 1, 'Progressive dae_garrison_minor', 'Dae Building: Carcass-Laden Embankment'),
    18469: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_kho_1', ItemType.building, 0, 'Progressive dae_growth_gold_kho', 'Dae Building: Brass Tower'),
    18470: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_kho_2', ItemType.building, 1, 'Progressive dae_growth_gold_kho', 'Dae Building: Gibbets & Gallows'),
    18471: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_kho_3', ItemType.building, 2, 'Progressive dae_growth_gold_kho', 'Dae Building: Field of Bones'),
    18472: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_kho_4', ItemType.building, 3, 'Progressive dae_growth_gold_kho', 'Dae Building: Offerings to Karanak'),
    18473: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_nur_1', ItemType.building, 0, 'Progressive dae_growth_gold_nur', 'Dae Building: Plague Vault'),
    18474: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_nur_2', ItemType.building, 1, 'Progressive dae_growth_gold_nur', 'Dae Building: Great Nest of Flies'),
    18475: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_nur_3', ItemType.building, 2, 'Progressive dae_growth_gold_nur', 'Dae Building: Captives of Decay'),
    18476: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_nur_4', ItemType.building, 3, 'Progressive dae_growth_gold_nur', 'Dae Building: Bilious Altar'),
    18477: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_sla_1', ItemType.building, 0, 'Progressive dae_growth_gold_sla', 'Dae Building: Vault of Pheromones'),
    18478: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_sla_2', ItemType.building, 1, 'Progressive dae_growth_gold_sla', 'Dae Building: Aroma Merchant'),
    18479: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_sla_3', ItemType.building, 2, 'Progressive dae_growth_gold_sla', 'Dae Building: Dark Perfumery'),
    18480: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_sla_4', ItemType.building, 3, 'Progressive dae_growth_gold_sla', 'Dae Building: Perfume House'),
    18481: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_tze_1', ItemType.building, 0, 'Progressive dae_growth_gold_tze', 'Dae Building: Soaring Siphon'),
    18482: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_tze_2', ItemType.building, 1, 'Progressive dae_growth_gold_tze', "Dae Building: The Architects' Column"),
    18483: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_tze_3', ItemType.building, 2, 'Progressive dae_growth_gold_tze', 'Dae Building: The Nine Ascents'),
    18484: ItemData(IC.useful, 1, 'wh3_main_dae_growth_gold_tze_4', ItemType.building, 3, 'Progressive dae_growth_gold_tze', 'Dae Building: Silver Spire'),
    18485: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_kho_1', ItemType.building, 0, 'Progressive dae_growth_recruit_kho', 'Dae Building: Totem of the Hound'),
    18486: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_kho_2', ItemType.building, 1, 'Progressive dae_growth_recruit_kho', 'Dae Building: Iron Gargoyles'),
    18487: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_kho_3', ItemType.building, 2, 'Progressive dae_growth_recruit_kho', 'Dae Building: Khornate Inscriptions'),
    18488: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_kho_4', ItemType.building, 3, 'Progressive dae_growth_recruit_kho', 'Dae Building: Skull of Skulls'),
    18489: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_nur_1', ItemType.building, 0, 'Progressive dae_growth_recruit_nur', 'Dae Building: Totem of the Crow'),
    18490: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_nur_2', ItemType.building, 1, 'Progressive dae_growth_recruit_nur', 'Dae Building: Well of Contagions'),
    18491: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_nur_3', ItemType.building, 2, 'Progressive dae_growth_recruit_nur', 'Dae Building: Quagmire of Waste'),
    18492: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_nur_4', ItemType.building, 3, 'Progressive dae_growth_recruit_nur', 'Dae Building: Cankerous Patch'),
    18493: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_sla_1', ItemType.building, 0, 'Progressive dae_growth_recruit_sla', 'Dae Building: Totem of the Serpent'),
    18494: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_sla_2', ItemType.building, 1, 'Progressive dae_growth_recruit_sla', 'Dae Building: Glittering Statuary'),
    18495: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_sla_3', ItemType.building, 2, 'Progressive dae_growth_recruit_sla', 'Dae Building: Dark Princeâ€™s Stave'),
    18496: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_sla_4', ItemType.building, 3, 'Progressive dae_growth_recruit_sla', 'Dae Building: Hedonistsâ€™ Altar'),
    18497: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_tze_1', ItemType.building, 0, 'Progressive dae_growth_recruit_tze', 'Dae Building: Totem of the Eagle'),
    18498: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_tze_2', ItemType.building, 1, 'Progressive dae_growth_recruit_tze', 'Dae Building: Haruspex Tent'),
    18499: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_tze_3', ItemType.building, 2, 'Progressive dae_growth_recruit_tze', 'Dae Building: Forbidden Tomes'),
    18500: ItemData(IC.useful, 1, 'wh3_main_dae_growth_recruit_tze_4', ItemType.building, 3, 'Progressive dae_growth_recruit_tze', 'Dae Building: Sundial of the Weaver'),
    18501: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_major_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Hovel'),
    18502: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_major_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Village'),
    18503: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_major_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Town'),
    18504: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_major_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Bastion of Chaos'),
    18505: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_major_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Dreadhold Fortress'),
    18506: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_minor_1', ItemType.building, 0, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Hovel'),
    18507: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_minor_2', ItemType.building, 1, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Village'),
    18508: ItemData(IC.useful, 1, 'wh3_main_dae_kho_settlement_minor_3', ItemType.building, 2, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Town'),
    18509: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_major_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Hovel'),
    18510: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_major_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Village'),
    18511: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_major_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Town'),
    18512: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_major_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Bastion of Chaos'),
    18513: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_major_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Dreadhold Fortress'),
    18514: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_minor_1', ItemType.building, 0, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Hovel'),
    18515: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_minor_2', ItemType.building, 1, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Village'),
    18516: ItemData(IC.useful, 1, 'wh3_main_dae_nur_settlement_minor_3', ItemType.building, 2, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Town'),
    18517: ItemData(IC.useful, 1, 'wh3_main_dae_port_1', ItemType.building, 0, 'Progressive dae_port', 'Dae Building: Infernal Harbour'),
    18518: ItemData(IC.useful, 1, 'wh3_main_dae_port_2', ItemType.building, 1, 'Progressive dae_port', 'Dae Building: Hell Port'),
    18519: ItemData(IC.useful, 1, 'wh3_main_dae_port_3', ItemType.building, 2, 'Progressive dae_port', 'Dae Building: Eye of Terror'),
    18520: ItemData(IC.useful, 1, 'wh3_main_dae_resource_animals_1', ItemType.building, 0, 'Progressive dae_resource_animals', 'Dae Building: Cultist Camp (Animals)'),
    18521: ItemData(IC.useful, 1, 'wh3_main_dae_resource_animals_2', ItemType.building, 1, 'Progressive dae_resource_animals', 'Dae Building: Cultist Outpost (Animals)'),
    18522: ItemData(IC.useful, 1, 'wh3_main_dae_resource_animals_3', ItemType.building, 2, 'Progressive dae_resource_animals', 'Dae Building: Cultist Enclave (Animals)'),
    18523: ItemData(IC.useful, 1, 'wh3_main_dae_resource_dyes_1', ItemType.building, 0, 'Progressive dae_resource_dyes', 'Dae Building: Cultist Camp (Dyes)'),
    18524: ItemData(IC.useful, 1, 'wh3_main_dae_resource_dyes_2', ItemType.building, 1, 'Progressive dae_resource_dyes', 'Dae Building: Cultist Outpost (Dyes)'),
    18525: ItemData(IC.useful, 1, 'wh3_main_dae_resource_dyes_3', ItemType.building, 2, 'Progressive dae_resource_dyes', 'Dae Building: Cultist Enclave (Dyes)'),
    18526: ItemData(IC.useful, 1, 'wh3_main_dae_resource_furs_1', ItemType.building, 0, 'Progressive dae_resource_furs', 'Dae Building: Cultist Camp (Furs)'),
    18527: ItemData(IC.useful, 1, 'wh3_main_dae_resource_furs_2', ItemType.building, 1, 'Progressive dae_resource_furs', 'Dae Building: Cultist Outpost (Furs)'),
    18528: ItemData(IC.useful, 1, 'wh3_main_dae_resource_furs_3', ItemType.building, 2, 'Progressive dae_resource_furs', 'Dae Building: Cultist Enclave (Furs)'),
    18529: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gems_1', ItemType.building, 0, 'Progressive dae_resource_gems', 'Dae Building: Cultist Camp (Gems)'),
    18530: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gems_2', ItemType.building, 1, 'Progressive dae_resource_gems', 'Dae Building: Cultist Outpost (Gems)'),
    18531: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gems_3', ItemType.building, 2, 'Progressive dae_resource_gems', 'Dae Building: Cultist Enclave (Gems)'),
    18532: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gold_1', ItemType.building, 0, 'Progressive dae_resource_gold', 'Dae Building: Cultist Camp (Gold)'),
    18533: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gold_2', ItemType.building, 1, 'Progressive dae_resource_gold', 'Dae Building: Cultist Outpost (Gold)'),
    18534: ItemData(IC.useful, 1, 'wh3_main_dae_resource_gold_3', ItemType.building, 2, 'Progressive dae_resource_gold', 'Dae Building: Cultist Enclave (Gold)'),
    18535: ItemData(IC.useful, 1, 'wh3_main_dae_resource_iron_1', ItemType.building, 0, 'Progressive dae_resource_iron', 'Dae Building: Cultist Camp (Iron)'),
    18536: ItemData(IC.useful, 1, 'wh3_main_dae_resource_iron_2', ItemType.building, 1, 'Progressive dae_resource_iron', 'Dae Building: Cultist Outpost (Iron)'),
    18537: ItemData(IC.useful, 1, 'wh3_main_dae_resource_iron_3', ItemType.building, 2, 'Progressive dae_resource_iron', 'Dae Building: Cultist Enclave (Iron)'),
    18538: ItemData(IC.useful, 1, 'wh3_main_dae_resource_ivory_1', ItemType.building, 0, 'Progressive dae_resource_ivory', 'Dae Building: Cultist Camp (Tusks)'),
    18539: ItemData(IC.useful, 1, 'wh3_main_dae_resource_ivory_2', ItemType.building, 1, 'Progressive dae_resource_ivory', 'Dae Building: Cultist Outpost (Tusks)'),
    18540: ItemData(IC.useful, 1, 'wh3_main_dae_resource_ivory_3', ItemType.building, 2, 'Progressive dae_resource_ivory', 'Dae Building: Cultist Enclave (Tusks)'),
    18541: ItemData(IC.useful, 1, 'wh3_main_dae_resource_marble_1', ItemType.building, 0, 'Progressive dae_resource_marble', 'Dae Building: Cultist Camp (Marble)'),
    18542: ItemData(IC.useful, 1, 'wh3_main_dae_resource_marble_2', ItemType.building, 1, 'Progressive dae_resource_marble', 'Dae Building: Cultist Outpost (Marble)'),
    18543: ItemData(IC.useful, 1, 'wh3_main_dae_resource_marble_3', ItemType.building, 2, 'Progressive dae_resource_marble', 'Dae Building: Cultist Enclave (Marble)'),
    18544: ItemData(IC.useful, 1, 'wh3_main_dae_resource_medicine_1', ItemType.building, 0, 'Progressive dae_resource_medicine', 'Dae Building: Cultist Camp (Medicine)'),
    18545: ItemData(IC.useful, 1, 'wh3_main_dae_resource_medicine_2', ItemType.building, 1, 'Progressive dae_resource_medicine', 'Dae Building: Cultist Outpost (Medicine)'),
    18546: ItemData(IC.useful, 1, 'wh3_main_dae_resource_medicine_3', ItemType.building, 2, 'Progressive dae_resource_medicine', 'Dae Building: Cultist Enclave (Medicine)'),
    18547: ItemData(IC.useful, 1, 'wh3_main_dae_resource_obsidian_1', ItemType.building, 0, 'Progressive dae_resource_obsidian', 'Dae Building: Cultist Camp (Obsidian)'),
    18548: ItemData(IC.useful, 1, 'wh3_main_dae_resource_obsidian_2', ItemType.building, 1, 'Progressive dae_resource_obsidian', 'Dae Building: Cultist Outpost (Obsidian)'),
    18549: ItemData(IC.useful, 1, 'wh3_main_dae_resource_obsidian_3', ItemType.building, 2, 'Progressive dae_resource_obsidian', 'Dae Building: Cultist Enclave (Obsidian)'),
    18550: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pasture_1', ItemType.building, 0, 'Progressive dae_resource_pasture', 'Dae Building: Cultist Camp (Pasture)'),
    18551: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pasture_2', ItemType.building, 1, 'Progressive dae_resource_pasture', 'Dae Building: Cultist Outpost (Pasture)'),
    18552: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pasture_3', ItemType.building, 2, 'Progressive dae_resource_pasture', 'Dae Building: Cultist Enclave (Pasture)'),
    18553: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pottery_1', ItemType.building, 0, 'Progressive dae_resource_pottery', 'Dae Building: Cultist Camp (Pottery)'),
    18554: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pottery_2', ItemType.building, 1, 'Progressive dae_resource_pottery', 'Dae Building: Cultist Outpost (Pottery)'),
    18555: ItemData(IC.useful, 1, 'wh3_main_dae_resource_pottery_3', ItemType.building, 2, 'Progressive dae_resource_pottery', 'Dae Building: Cultist Enclave (Pottery)'),
    18556: ItemData(IC.useful, 1, 'wh3_main_dae_resource_salt_1', ItemType.building, 0, 'Progressive dae_resource_salt', 'Dae Building: Cultist Camp (Salt)'),
    18557: ItemData(IC.useful, 1, 'wh3_main_dae_resource_salt_2', ItemType.building, 1, 'Progressive dae_resource_salt', 'Dae Building: Cultist Outpost (Salt)'),
    18558: ItemData(IC.useful, 1, 'wh3_main_dae_resource_salt_3', ItemType.building, 2, 'Progressive dae_resource_salt', 'Dae Building: Cultist Enclave (Salt)'),
    18559: ItemData(IC.useful, 1, 'wh3_main_dae_resource_spices_1', ItemType.building, 0, 'Progressive dae_resource_spices', 'Dae Building: Cultist Camp (Spices)'),
    18560: ItemData(IC.useful, 1, 'wh3_main_dae_resource_spices_2', ItemType.building, 1, 'Progressive dae_resource_spices', 'Dae Building: Cultist Outpost (Spices)'),
    18561: ItemData(IC.useful, 1, 'wh3_main_dae_resource_spices_3', ItemType.building, 2, 'Progressive dae_resource_spices', 'Dae Building: Cultist Enclave (Spices)'),
    18562: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wine_1', ItemType.building, 0, 'Progressive dae_resource_wine', 'Dae Building: Cultist Camp (Wine)'),
    18563: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wine_2', ItemType.building, 1, 'Progressive dae_resource_wine', 'Dae Building: Cultist Outpost (Wine)'),
    18564: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wine_3', ItemType.building, 2, 'Progressive dae_resource_wine', 'Dae Building: Cultist Enclave (Wine)'),
    18565: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wood_1', ItemType.building, 0, 'Progressive dae_resource_wood', 'Dae Building: Cultist Camp (Wood)'),
    18566: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wood_2', ItemType.building, 1, 'Progressive dae_resource_wood', 'Dae Building: Cultist Outpost (Wood)'),
    18567: ItemData(IC.useful, 1, 'wh3_main_dae_resource_wood_3', ItemType.building, 2, 'Progressive dae_resource_wood', 'Dae Building: Cultist Enclave (Wood)'),
    18568: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_major_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Hovel'),
    18569: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_major_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Village'),
    18570: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_major_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Town'),
    18571: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_major_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Bastion of Chaos'),
    18572: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_major_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Dreadhold Fortress'),
    18573: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_minor_1', ItemType.building, 0, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Hovel'),
    18574: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_minor_2', ItemType.building, 1, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Village'),
    18575: ItemData(IC.useful, 1, 'wh3_main_dae_settlement_minor_3', ItemType.building, 2, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Town'),
    18576: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_major_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Hovel'),
    18577: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_major_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Village'),
    18578: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_major_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Town'),
    18579: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_major_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Bastion of Chaos'),
    18580: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_major_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Dreadhold Fortress'),
    18581: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_minor_1', ItemType.building, 0, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Hovel'),
    18582: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_minor_2', ItemType.building, 1, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Village'),
    18583: ItemData(IC.useful, 1, 'wh3_main_dae_sla_settlement_minor_3', ItemType.building, 2, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Town'),
    18584: ItemData(IC.useful, 1, 'wh3_main_dae_temple_kho_1', ItemType.building, 0, 'Progressive dae_temple_kho', 'Dae Building: Pit of Massacres'),
    18585: ItemData(IC.useful, 1, 'wh3_main_dae_temple_kho_2', ItemType.building, 1, 'Progressive dae_temple_kho', 'Dae Building: Death Podium'),
    18586: ItemData(IC.useful, 1, 'wh3_main_dae_temple_kho_3', ItemType.building, 2, 'Progressive dae_temple_kho', 'Dae Building: Crucible of Blood'),
    18587: ItemData(IC.useful, 1, 'wh3_main_dae_temple_kho_4', ItemType.building, 3, 'Progressive dae_temple_kho', 'Dae Building: Slaughtercage'),
    18588: ItemData(IC.useful, 1, 'wh3_main_dae_temple_kho_5', ItemType.building, 4, 'Progressive dae_temple_kho', 'Dae Building: Khornate Coliseum'),
    18589: ItemData(IC.useful, 1, 'wh3_main_dae_temple_nur_1', ItemType.building, 0, 'Progressive dae_temple_nur', "Dae Building: Plague Doctor's Surgery"),
    18590: ItemData(IC.useful, 1, 'wh3_main_dae_temple_nur_2', ItemType.building, 1, 'Progressive dae_temple_nur', 'Dae Building: Leprosarium'),
    18591: ItemData(IC.useful, 1, 'wh3_main_dae_temple_nur_3', ItemType.building, 2, 'Progressive dae_temple_nur', "Dae Building: Plaguelord's Almshouse"),
    18592: ItemData(IC.useful, 1, 'wh3_main_dae_temple_nur_4', ItemType.building, 3, 'Progressive dae_temple_nur', 'Dae Building: The Grand Morgue'),
    18593: ItemData(IC.useful, 1, 'wh3_main_dae_temple_nur_5', ItemType.building, 4, 'Progressive dae_temple_nur', 'Dae Building: Putrefaction Mound'),
    18594: ItemData(IC.useful, 1, 'wh3_main_dae_temple_sla_1', ItemType.building, 0, 'Progressive dae_temple_sla', 'Dae Building: Gallery of Delusions'),
    18595: ItemData(IC.useful, 1, 'wh3_main_dae_temple_sla_2', ItemType.building, 1, 'Progressive dae_temple_sla', 'Dae Building: Halls of Ovation'),
    18596: ItemData(IC.useful, 1, 'wh3_main_dae_temple_sla_3', ItemType.building, 2, 'Progressive dae_temple_sla', 'Dae Building: Pagaents of Perfection'),
    18597: ItemData(IC.useful, 1, 'wh3_main_dae_temple_sla_4', ItemType.building, 3, 'Progressive dae_temple_sla', 'Dae Building: The Eternal Banquet'),
    18598: ItemData(IC.useful, 1, 'wh3_main_dae_temple_sla_5', ItemType.building, 4, 'Progressive dae_temple_sla', 'Dae Building: Baroque Pavane'),
    18599: ItemData(IC.useful, 1, 'wh3_main_dae_temple_tze_1', ItemType.building, 0, 'Progressive dae_temple_tze', 'Dae Building: Scrying Crystal'),
    18600: ItemData(IC.useful, 1, 'wh3_main_dae_temple_tze_2', ItemType.building, 1, 'Progressive dae_temple_tze', 'Dae Building: Conjuring Stones'),
    18601: ItemData(IC.useful, 1, 'wh3_main_dae_temple_tze_3', ItemType.building, 2, 'Progressive dae_temple_tze', 'Dae Building: Augural Charts'),
    18602: ItemData(IC.useful, 1, 'wh3_main_dae_temple_tze_4', ItemType.building, 3, 'Progressive dae_temple_tze', 'Dae Building: Gyroscope Room'),
    18603: ItemData(IC.useful, 1, 'wh3_main_dae_temple_tze_5', ItemType.building, 4, 'Progressive dae_temple_tze', 'Dae Building: Thaumaturgic Orrery'),
    18604: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_major_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Hovel'),
    18605: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_major_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Village'),
    18606: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_major_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Dedicated Town'),
    18607: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_major_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Bastion of Chaos'),
    18608: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_major_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Dreadhold Fortress'),
    18609: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_minor_1', ItemType.building, 0, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Hovel'),
    18610: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_minor_2', ItemType.building, 1, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Village'),
    18611: ItemData(IC.useful, 1, 'wh3_main_dae_tze_settlement_minor_3', ItemType.building, 2, 'Progressive dae_settlement_minor', 'Dae Building: Dedicated Town'),
    18612: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_dae_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_dae', 'Dae Building: Warpstone Locus'),
    18613: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_dae_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_dae', 'Dae Building: Warpstone Traps'),
    18614: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_dae_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_dae', 'Dae Building: Guarded Warpstone'),
    18615: ItemData(IC.useful, 1, 'wh3_main_special_settlement_gate_dae_1', ItemType.building, 0, 'Progressive dae_settlement_major', 'Dae Building: Occupied Gate (Small Fortress)'),
    18616: ItemData(IC.useful, 1, 'wh3_main_special_settlement_gate_dae_2', ItemType.building, 1, 'Progressive dae_settlement_major', 'Dae Building: Occupied Gate (Fortress)'),
    18617: ItemData(IC.useful, 1, 'wh3_main_special_settlement_gate_dae_3', ItemType.building, 2, 'Progressive dae_settlement_major', 'Dae Building: Occupied Gate (Grand Fortress)'),
    18618: ItemData(IC.useful, 1, 'wh3_main_special_settlement_gate_dae_4', ItemType.building, 3, 'Progressive dae_settlement_major', 'Dae Building: Occupied Gate (Imposing Fortress)'),
    18619: ItemData(IC.useful, 1, 'wh3_main_special_settlement_gate_dae_5', ItemType.building, 4, 'Progressive dae_settlement_major', 'Dae Building: Occupied Gate (Impregnable Fortress)')
}

techs: dict[int, ItemData] = {}

progUnits: dict[int, ItemData] = {
    19200: ItemData(IC.useful, 5, "Progressive dae_inf", ItemType.unit, 5, "", "Progressive Dae Unit: Infantry"),
    19201: ItemData(IC.useful, 4, "Progressive dae_rng", ItemType.unit, 4, "", "Progressive Dae Unit: Ranged"),
    19202: ItemData(IC.useful, 5, "Progressive dae_cav", ItemType.unit, 5, "", "Progressive Dae Unit: Cavalry"),
    19203: ItemData(IC.useful, 1, "Progressive dae_art", ItemType.unit, 1, "", "Progressive Dae Unit: Artillery"),
    19204: ItemData(IC.useful, 5, "Progressive dae_veh", ItemType.unit, 5, "", "Progressive Dae Unit: Chariot"),
    19205: ItemData(IC.useful, 4, "Progressive dae_bst", ItemType.unit, 4, "", "Progressive Dae Unit: Beast"),
    19206: ItemData(IC.useful, 1, "Progressive dae_hro", ItemType.unit, 1, "", "Progressive Dae Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    19303: ItemData(IC.useful, 3, 'Progressive dae_advanced_2_kho', ItemType.building, 3, None, 'Progressive Dae Building: Advanced 2 Kho'),
    19306: ItemData(IC.useful, 3, 'Progressive dae_advanced_2_nur', ItemType.building, 3, None, 'Progressive Dae Building: Advanced 2 Nur'),
    19309: ItemData(IC.useful, 3, 'Progressive dae_advanced_2_sla', ItemType.building, 3, None, 'Progressive Dae Building: Advanced 2 Sla'),
    19312: ItemData(IC.useful, 3, 'Progressive dae_advanced_2_tze', ItemType.building, 3, None, 'Progressive Dae Building: Advanced 2 Tze'),
    19317: ItemData(IC.useful, 5, 'Progressive dae_advanced_kho', ItemType.building, 5, None, 'Progressive Dae Building: Advanced Kho'),
    19322: ItemData(IC.useful, 5, 'Progressive dae_advanced_nur', ItemType.building, 5, None, 'Progressive Dae Building: Advanced Nur'),
    19327: ItemData(IC.useful, 5, 'Progressive dae_advanced_sla', ItemType.building, 5, None, 'Progressive Dae Building: Advanced Sla'),
    19332: ItemData(IC.useful, 5, 'Progressive dae_advanced_tze', ItemType.building, 5, None, 'Progressive Dae Building: Advanced Tze'),
    19335: ItemData(IC.useful, 3, 'Progressive dae_allied_outpost', ItemType.building, 3, None, 'Progressive Dae Building: Allied Outpost'),
    19336: ItemData(IC.useful, 3, 'Progressive dae_barracks_kho', ItemType.building, 3, None, 'Progressive Dae Building: Barracks Kho'),
    19339: ItemData(IC.useful, 4, 'Progressive dae_barracks_nur', ItemType.building, 3, None, 'Progressive Dae Building: Barracks Nur'),
    19342: ItemData(IC.useful, 5, 'Progressive dae_barracks_sla', ItemType.building, 3, None, 'Progressive Dae Building: Barracks Sla'),
    19345: ItemData(IC.useful, 6, 'Progressive dae_barracks_tze', ItemType.building, 3, None, 'Progressive Dae Building: Barracks Tze'),
    19351: ItemData(IC.useful, 4, 'Progressive dae_control_kho', ItemType.building, 4, None, 'Progressive Dae Building: Control Kho'),
    19355: ItemData(IC.useful, 4, 'Progressive dae_control_nur', ItemType.building, 4, None, 'Progressive Dae Building: Control Nur'),
    19359: ItemData(IC.useful, 4, 'Progressive dae_control_sla', ItemType.building, 4, None, 'Progressive Dae Building: Control Sla'),
    19363: ItemData(IC.useful, 4, 'Progressive dae_control_tze', ItemType.building, 4, None, 'Progressive Dae Building: Control Tze'),
    19366: ItemData(IC.useful, 3, 'Progressive dae_garrison_major', ItemType.building, 3, None, 'Progressive Dae Building: Garrison Major'),
    19368: ItemData(IC.useful, 2, 'Progressive dae_garrison_minor', ItemType.building, 2, None, 'Progressive Dae Building: Garrison Minor'),
    19372: ItemData(IC.useful, 4, 'Progressive dae_growth_gold_kho', ItemType.building, 4, None, 'Progressive Dae Building: Growth Gold Kho'),
    19376: ItemData(IC.useful, 4, 'Progressive dae_growth_gold_nur', ItemType.building, 4, None, 'Progressive Dae Building: Growth Gold Nur'),
    19380: ItemData(IC.useful, 4, 'Progressive dae_growth_gold_sla', ItemType.building, 4, None, 'Progressive Dae Building: Growth Gold Sla'),
    19384: ItemData(IC.useful, 4, 'Progressive dae_growth_gold_tze', ItemType.building, 4, None, 'Progressive Dae Building: Growth Gold Tze'),
    19388: ItemData(IC.useful, 4, 'Progressive dae_growth_recruit_kho', ItemType.building, 4, None, 'Progressive Dae Building: Growth Recruit Kho'),
    19392: ItemData(IC.useful, 4, 'Progressive dae_growth_recruit_nur', ItemType.building, 4, None, 'Progressive Dae Building: Growth Recruit Nur'),
    19396: ItemData(IC.useful, 4, 'Progressive dae_growth_recruit_sla', ItemType.building, 4, None, 'Progressive Dae Building: Growth Recruit Sla'),
    19400: ItemData(IC.useful, 4, 'Progressive dae_growth_recruit_tze', ItemType.building, 4, None, 'Progressive Dae Building: Growth Recruit Tze'),
    19419: ItemData(IC.useful, 3, 'Progressive dae_port', ItemType.building, 3, None, 'Progressive Dae Building: Port'),
    19422: ItemData(IC.useful, 3, 'Progressive dae_resource_animals', ItemType.building, 3, None, 'Progressive Dae Building: Animals'),
    19425: ItemData(IC.useful, 3, 'Progressive dae_resource_dyes', ItemType.building, 3, None, 'Progressive Dae Building: Dyes'),
    19428: ItemData(IC.useful, 3, 'Progressive dae_resource_furs', ItemType.building, 3, None, 'Progressive Dae Building: Furs'),
    19431: ItemData(IC.useful, 3, 'Progressive dae_resource_gems', ItemType.building, 3, None, 'Progressive Dae Building: Gems'),
    19434: ItemData(IC.useful, 3, 'Progressive dae_resource_gold', ItemType.building, 3, None, 'Progressive Dae Building: Gold'),
    19437: ItemData(IC.useful, 3, 'Progressive dae_resource_iron', ItemType.building, 3, None, 'Progressive Dae Building: Iron'),
    19440: ItemData(IC.useful, 3, 'Progressive dae_resource_ivory', ItemType.building, 3, None, 'Progressive Dae Building: Ivory'),
    19443: ItemData(IC.useful, 3, 'Progressive dae_resource_marble', ItemType.building, 3, None, 'Progressive Dae Building: Marble'),
    19446: ItemData(IC.useful, 3, 'Progressive dae_resource_medicine', ItemType.building, 3, None, 'Progressive Dae Building: Medicine'),
    19449: ItemData(IC.useful, 3, 'Progressive dae_resource_obsidian', ItemType.building, 3, None, 'Progressive Dae Building: Obsidian'),
    19452: ItemData(IC.useful, 3, 'Progressive dae_resource_pasture', ItemType.building, 3, None, 'Progressive Dae Building: Pasture'),
    19455: ItemData(IC.useful, 3, 'Progressive dae_resource_pottery', ItemType.building, 3, None, 'Progressive Dae Building: Pottery'),
    19458: ItemData(IC.useful, 3, 'Progressive dae_resource_salt', ItemType.building, 3, None, 'Progressive Dae Building: Salt'),
    19461: ItemData(IC.useful, 3, 'Progressive dae_resource_spices', ItemType.building, 3, None, 'Progressive Dae Building: Spices'),
    19464: ItemData(IC.useful, 3, 'Progressive dae_resource_wine', ItemType.building, 3, None, 'Progressive Dae Building: Wine'),
    19467: ItemData(IC.useful, 3, 'Progressive dae_resource_wood', ItemType.building, 3, None, 'Progressive Dae Building: Wood'),
    19472: ItemData(IC.useful, 5, 'Progressive dae_settlement_major', ItemType.building, 5, None, 'Progressive Dae Building: Settlement Major'),
    19475: ItemData(IC.useful, 3, 'Progressive dae_settlement_minor', ItemType.building, 3, None, 'Progressive Dae Building: Settlement Minor'),
    19488: ItemData(IC.useful, 5, 'Progressive dae_temple_kho', ItemType.building, 5, None, 'Progressive Dae Building: Temple Kho'),
    19493: ItemData(IC.useful, 5, 'Progressive dae_temple_nur', ItemType.building, 5, None, 'Progressive Dae Building: Temple Nur'),
    19498: ItemData(IC.useful, 5, 'Progressive dae_temple_sla', ItemType.building, 5, None, 'Progressive Dae Building: Temple Sla'),
    19503: ItemData(IC.useful, 5, 'Progressive dae_temple_tze', ItemType.building, 5, None, 'Progressive Dae Building: Temple Tze'),
    19514: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_dae', ItemType.building, 3, None, 'Progressive Dae Building: Foreign Slot Discovery Dae')
}
progTechs: dict[int, ItemData] = {}

special: dict[int, ItemData] = {}