from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    20008: ItemData(IC.useful, 1, 'wh2_main_def_inf_dreadspears_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: Dreadspears'),
    20011: ItemData(IC.useful, 1, 'wh2_main_def_inf_bleakswords_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: Bleakswords'),
    20014: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: Black Ark Corsairs'),
    20002: ItemData(IC.useful, 1, 'wh2_main_def_inf_witch_elves_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Witch Elves'),
    20050: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_slaughter', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Sisters of Slaughter'),
    20007: ItemData(IC.useful, 1, 'wh2_main_def_inf_har_ganeth_executioners_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Har Ganeth Executioners'),
    20012: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_guard_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Black Guard of Naggarond'),

    20010: ItemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_0', ItemType.unit, 1, 'Progressive def_rng', 'Def Unit: Darkshards'),
    20009: ItemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_1', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Darkshards (Shields)'),
    20013: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_1', ItemType.unit, 1, 'Progressive def_rng', 'Def Unit: Black Ark Corsairs (Handbows)'),
    20005: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_0', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Shades'),
    20004: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_1', ItemType.unit, 3, 'Progressive def_rng', 'Def Unit: Shades (Dual Weapons)'),
    20003: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_2', ItemType.unit, 3, 'Progressive def_rng', 'Def Unit: Shades (Greatswords)'),

    20024: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_0', ItemType.unit, 1, 'Progressive def_cav', 'Def Unit: Dark Riders'),
    20022: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_2', ItemType.unit, 1, 'Progressive def_cav', 'Def Unit: Dark Riders (Repeater Crossbows)'),
    20023: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_1', ItemType.unit, 2, 'Progressive def_cav', 'Def Unit: Dark Riders (Shields)'),
    20059: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_doomfire_warlocks_0', ItemType.unit, 2, 'Progressive def_cav', 'Def Unit: Doomfire Warlocks'),
    20026: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_0', ItemType.unit, 3, 'Progressive def_cav', 'Def Unit: Cold One Knights'),
    20025: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_1', ItemType.unit, 4, 'Progressive def_cav', 'Def Unit: Cold One Dread Knights'),

    20028: ItemData(IC.useful, 1, 'wh2_main_def_art_reaper_bolt_thrower', ItemType.unit, 1, 'Progressive def_art', 'Def Unit: Reaper Bolt Throwers'),

    20041: ItemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_0', ItemType.unit, 1, 'Progressive def_veh', 'Def Unit: Scourgerunner Chariots'),
    20027: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_chariot', ItemType.unit, 2, 'Progressive def_veh', 'Def Unit: Cold One Chariots'),
    20029: ItemData(IC.useful, 1, 'wh2_dlc14_def_veh_bloodwrack_shrine_0', ItemType.unit, 3, 'Progressive def_veh', 'Def Unit: Bloodwrack Shrine'),

    20006: ItemData(IC.useful, 1, 'wh2_main_def_inf_harpies', ItemType.unit, 1, 'Progressive def_bst', 'Def Unit: Harpies'),
    20031: ItemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_0', ItemType.unit, 1, 'Progressive def_bst', 'Def Unit: Bloodwrack Medusa'),
    20045: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_feral_manticore_0', ItemType.unit, 2, 'Progressive def_bst', 'Def Unit: Feral Manticore'),
    20064: ItemData(IC.useful, 1, "wh2_main_def_mon_war_hydra", ItemType.unit, 2, "Progressive def_bst", "Def Unit: War Hydra"),
    20044: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_kharibdyss_0', ItemType.unit, 2, 'Progressive def_bst', 'Def Unit: Kharibdyss'),
    20001: ItemData(IC.useful, 1, 'wh2_main_def_mon_black_dragon', ItemType.unit, 3, 'Progressive def_bst', 'Def Unit: Black Dragon'),

    20030: ItemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_ror_0', ItemType.unit, 1, 'Progressive def_bst', 'Def Unit: The Siren of Red Ruin (Bloodwrack Medusa)'),
    20032: ItemData(IC.useful, 1, 'wh2_dlc14_def_inf_harpies_ror_0', ItemType.unit, 1, 'Progressive def_bst', 'Def Unit: The Crows of Khaine (Harpies)'),
    20040: ItemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_ror_0', ItemType.unit, 1, 'Progressive def_veh', 'Def Unit: Ravagers of Rakarth (Scourgerunner Chariots)'),
    20046: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_chill_of_sontar_ror_0', ItemType.unit, 2, 'Progressive def_bst', 'Def Unit: Chill of Sontar (War Hydra)'),
    20047: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_hellebronai_ror_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: The Hellebronai (Dreadspears)'),
    20048: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_bolt_fiends_ror_0', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: The Bolt-fiends (Darkshards - Shields)'),
    20049: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_the_singing_doom_ror_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Sisters of the Singing Doom (Witch Elves)'),
    20051: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_blades_of_the_blood_queen_ror_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Blades of the Blood Queen (Har Ganeth Executioners)'),
    20056: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_slaanesh_harvesters_ror_0', ItemType.unit, 2, 'cavalry', "Def Unit: Slaanesh's Harvesters (Doomfire Warlocks)"),
    20057: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_raven_heralds_ror_0', ItemType.unit, 1, 'cavalry', 'Def Unit: Raven Heralds (Dark Riders)'),
    20058: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_knights_of_the_ebon_claw_ror_0', ItemType.unit, 4, 'cavalry', 'Def Unit: Knights of the Ebon Claw (Dread Knights)'),

    20035: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_master_0', ItemType.unit, 1, 'Progressive def_hro', 'Def Unit: Master'),
    20016: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_dark_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Sorceress (Dark)'),
    20060: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_death_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Sorceress (Death)'),
    20061: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_shadows_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Sorceress (Shadows)'),
    20062: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_fire_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Sorceress (Fire)'),
    20063: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_beasts_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Sorceress (Beasts)'),
    20018: ItemData(IC.useful, 1, 'wh2_main_def_cha_khainite_assassin_0', ItemType.unit, 2, 'Progressive def_hro', 'Def Unit: Khainite Assassin'),
    20021: ItemData(IC.useful, 1, 'wh2_main_def_cha_death_hag_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Death Hag'),
}

buildings: dict[int, ItemData] = {
    20400: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_1', ItemType.building, 0, 'Progressive horde_def_aristocracy', 'Def Black Ark: Dread Manse'),
    20401: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_2', ItemType.building, 1, 'Progressive horde_def_aristocracy', 'Def Black Ark: Palace of Dread Knights'),
    20402: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_1', ItemType.building, 0, 'Progressive horde_def_exiles', 'Def Black Ark: Den of Outlaws'),
    20403: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_2', ItemType.building, 1, 'Progressive horde_def_exiles', 'Def Black Ark: House of Exiles'),
    20404: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_1', ItemType.building, 0, 'Progressive horde_def_residence', 'Def Black Ark: Dark Elf Manors'),
    20405: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_2', ItemType.building, 1, 'Progressive horde_def_residence', 'Def Black Ark: Dark Elf Residences'),
    20406: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_3', ItemType.building, 2, 'Progressive horde_def_residence', 'Def Black Ark: Estates of the Masters'),
    20407: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_1', ItemType.building, 0, 'Progressive horde_def_riders', 'Def Building: Reaver Stables'),
    20408: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_2', ItemType.building, 1, 'Progressive horde_def_riders', "Def Building: Messengers' Lodgehouse"),
    20409: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'Def Building: Occupied Tor Yvresse (Black Spire)'),
    20410: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'Def Building: Occupied Tor Yvresse (Dark Hold)'),
    20411: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'Def Building: Occupied Tor Yvresse (Dark Tower)'),
    20412: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'Def Building: Occupied Tor Yvresse (Dark Citadel)'),
    20413: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'Def Building: Occupied Tor Yvresse (Dark City)'),
    20414: ItemData(IC.useful, 1, 'wh2_main_def_barracks_1', ItemType.building, 0, 'Progressive def_barracks', 'Def Building: Conscription Halls'),
    20415: ItemData(IC.useful, 1, 'wh2_main_def_barracks_2', ItemType.building, 1, 'Progressive def_barracks', 'Def Building: Halls of Mustering'),
    20416: ItemData(IC.useful, 1, 'wh2_main_def_barracks_3', ItemType.building, 2, 'Progressive def_barracks', 'Def Building: Halls of Ravaging'),
    20417: ItemData(IC.useful, 1, 'wh2_main_def_beasts_1', ItemType.building, 0, 'Progressive def_beasts', 'Def Building: Harpy Roost'),
    20418: ItemData(IC.useful, 1, 'wh2_main_def_beasts_2', ItemType.building, 1, 'Progressive def_beasts', "Def Building: Beastmaster's Stables"),
    20419: ItemData(IC.useful, 1, 'wh2_main_def_beasts_3', ItemType.building, 2, 'Progressive def_beasts', 'Def Building: Dragon Hatchery'),
    20420: ItemData(IC.useful, 1, 'wh2_main_def_coldones_1', ItemType.building, 0, 'Progressive def_coldones', 'Def Building: Dread Manse'),
    20421: ItemData(IC.useful, 1, 'wh2_main_def_coldones_2', ItemType.building, 1, 'Progressive def_coldones', 'Def Building: Palace of Dread Knights'),
    20422: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_1', ItemType.building, 0, 'Progressive def_defence_major', 'Def Building: Slave Gate'),
    20423: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_2', ItemType.building, 1, 'Progressive def_defence_major', 'Def Building: Blackstone Walls'),
    20424: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_3', ItemType.building, 2, 'Progressive def_defence_major', 'Def Building: Dread Bulwark'),
    20425: ItemData(IC.useful, 1, 'wh2_main_def_defence_minor_1', ItemType.building, 0, 'Progressive def_defence_minor', 'Def Building: Watchtowers'),
    20426: ItemData(IC.useful, 1, 'wh2_main_def_defence_minor_2', ItemType.building, 1, 'Progressive def_defence_minor', 'Def Building: Dark Palisade'),
    20427: ItemData(IC.useful, 1, 'wh2_main_def_defence_norsca_1', ItemType.building, 0, 'Progressive def_defence_norsca', 'Def Building: Outpost Garrison'),
    20428: ItemData(IC.useful, 1, 'wh2_main_def_exiles_1', ItemType.building, 0, 'Progressive def_exiles', 'Def Building: Den of Outlaws'),
    20429: ItemData(IC.useful, 1, 'wh2_main_def_exiles_2', ItemType.building, 1, 'Progressive def_exiles', 'Def Building: House of Exiles'),
    20430: ItemData(IC.useful, 1, 'wh2_main_def_farm_1', ItemType.building, 0, 'Progressive def_farm', 'Def Building: Dark Elf Manors'),
    20431: ItemData(IC.useful, 1, 'wh2_main_def_farm_2', ItemType.building, 1, 'Progressive def_farm', 'Def Building: Dark Elf Residences'),
    20432: ItemData(IC.useful, 1, 'wh2_main_def_farm_3', ItemType.building, 2, 'Progressive def_farm', 'Def Building: Estates of the Masters'),
    20433: ItemData(IC.useful, 1, 'wh2_main_def_industry_1', ItemType.building, 0, 'Progressive def_industry', "Def Building: Artisan's House"),
    20434: ItemData(IC.useful, 1, 'wh2_main_def_industry_2', ItemType.building, 1, 'Progressive def_industry', 'Def Building: Crafting District'),
    20435: ItemData(IC.useful, 1, 'wh2_main_def_industry_3', ItemType.building, 2, 'Progressive def_industry', 'Def Building: Guild Halls'),
    20439: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_1', ItemType.building, 0, 'Progressive horde_def_entertainment', 'Def Black Ark: Torture Posts'),
    20443: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_2', ItemType.building, 1, 'Progressive horde_def_entertainment', 'Def Black Ark: Fighting Pits'),
    20447: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_3', ItemType.building, 2, 'Progressive horde_def_entertainment', 'Def Black Ark: Arena'),
    20448: ItemData(IC.useful, 1, 'wh2_main_def_port_1', ItemType.building, 0, 'Progressive def_port', 'Def Building: Dark Elf Landing'),
    20449: ItemData(IC.useful, 1, 'wh2_main_def_port_2', ItemType.building, 1, 'Progressive def_port', 'Def Building: Dark Elf Harbour'),
    20450: ItemData(IC.useful, 1, 'wh2_main_def_port_3', ItemType.building, 2, 'Progressive def_port', 'Def Building: Dark Elf Port'),
    20451: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_1', ItemType.building, 0, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Tamer'),
    20452: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_2', ItemType.building, 1, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Pen'),
    20453: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_3', ItemType.building, 2, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Market'),
    20454: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_1', ItemType.building, 0, 'Progressive def_resource_dyes', 'Def Building: Cinnabar Mining Pit'),
    20455: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_2', ItemType.building, 1, 'Progressive def_resource_dyes', 'Def Building: Cinnabar Mine'),
    20456: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_3', ItemType.building, 2, 'Progressive def_resource_dyes', 'Def Building: Dyemaker'),
    20457: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_1', ItemType.building, 0, 'Progressive def_resource_furs', 'Def Building: Hunting Camp'),
    20458: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_2', ItemType.building, 1, 'Progressive def_resource_furs', 'Def Building: Hunting Lodge'),
    20459: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_3', ItemType.building, 2, 'Progressive def_resource_furs', 'Def Building: Tannery'),
    20460: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_1', ItemType.building, 0, 'Progressive def_resource_gems', 'Def Building: Gem Mineshaft'),
    20461: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_2', ItemType.building, 1, 'Progressive def_resource_gems', 'Def Building: Gem Mine'),
    20462: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_3', ItemType.building, 2, 'Progressive def_resource_gems', "Def Building: Gemcutter's Workshop"),
    20463: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_1', ItemType.building, 0, 'Progressive def_resource_gold', 'Def Building: Gold Mining Pit'),
    20464: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_2', ItemType.building, 1, 'Progressive def_resource_gold', 'Def Building: Gold Mine'),
    20465: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_3', ItemType.building, 2, 'Progressive def_resource_gold', 'Def Building: Gold Smelter'),
    20466: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_1', ItemType.building, 0, 'Progressive def_resource_iron', 'Def Building: Iron Mining Pit'),
    20467: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_2', ItemType.building, 1, 'Progressive def_resource_iron', 'Def Building: Iron Mines'),
    20468: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_3', ItemType.building, 2, 'Progressive def_resource_iron', 'Def Building: Iron Smelter'),
    20469: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_1', ItemType.building, 0, 'Progressive def_resource_marble', 'Def Building: Sawyer'),
    20470: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_2', ItemType.building, 1, 'Progressive def_resource_marble', 'Def Building: Marble Quarry'),
    20471: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_3', ItemType.building, 2, 'Progressive def_resource_marble', "Def Building: Stone Mason's Workshop"),
    20472: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_1', ItemType.building, 0, 'Progressive def_resource_medicine', "Def Building: Herb Gatherer's Camp"),
    20473: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_2', ItemType.building, 1, 'Progressive def_resource_medicine', 'Def Building: Exotic Hothouse'),
    20474: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_3', ItemType.building, 2, 'Progressive def_resource_medicine', 'Def Building: Alchemy Workshop'),
    20475: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_1', ItemType.building, 0, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Quarry'),
    20476: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_2', ItemType.building, 1, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Trinket Maker'),
    20477: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_3', ItemType.building, 2, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Amulet Carver'),
    20478: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_1', ItemType.building, 0, 'Progressive def_resource_pasture', 'Def Building: Grazing Pastures'),
    20479: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_2', ItemType.building, 1, 'Progressive def_resource_pasture', 'Def Building: Livestock Pens'),
    20480: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_3', ItemType.building, 2, 'Progressive def_resource_pasture', 'Def Building: Cattle Ranch'),
    20481: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_1', ItemType.building, 0, 'Progressive def_resource_pottery', 'Def Building: Clay Pit'),
    20482: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_2', ItemType.building, 1, 'Progressive def_resource_pottery', 'Def Building: Pottery Maker'),
    20483: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_3', ItemType.building, 2, 'Progressive def_resource_pottery', 'Def Building: Kilns'),
    20484: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_1', ItemType.building, 0, 'Progressive def_resource_salt', 'Def Building: Brine Mining Pans'),
    20485: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_2', ItemType.building, 1, 'Progressive def_resource_salt', 'Def Building: Brine Mining Basin'),
    20486: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_3', ItemType.building, 2, 'Progressive def_resource_salt', 'Def Building: Saltworks'),
    20487: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_1', ItemType.building, 0, 'Progressive def_resource_spices', 'Def Building: Spice Market'),
    20488: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_2', ItemType.building, 1, 'Progressive def_resource_spices', 'Def Building: Spice Trading Post'),
    20489: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_3', ItemType.building, 2, 'Progressive def_resource_spices', 'Def Building: Eastern Bazaar'),
    20490: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_1', ItemType.building, 0, 'Progressive def_resource_wine', 'Def Building: Orchards'),
    20491: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_2', ItemType.building, 1, 'Progressive def_resource_wine', 'Def Building: Vineyard'),
    20492: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_3', ItemType.building, 2, 'Progressive def_resource_wine', 'Def Building: Vintner'),
    20493: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_1', ItemType.building, 0, 'Progressive def_resource_wood', "Def Building: Woodman's Hut"),
    20494: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_2', ItemType.building, 1, 'Progressive def_resource_wood', 'Def Building: Timber Mill'),
    20495: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_3', ItemType.building, 2, 'Progressive def_resource_wood', 'Def Building: Lumberyard'),
    20496: ItemData(IC.useful, 1, 'wh2_main_def_riders_1', ItemType.building, 0, 'Progressive def_riders', 'Def Building: Plateau of Dark Steeds'),
    20497: ItemData(IC.useful, 1, 'wh2_main_def_riders_2', ItemType.building, 1, 'Progressive def_riders', "Def Building: Messengers' Lodgehouse"),
    20498: ItemData(IC.useful, 1, 'wh2_main_def_roads_1', ItemType.building, 0, 'Progressive def_roads', 'Def Building: Black Roads'),
    20499: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_1', ItemType.building, 0, 'Progressive def_settlement_major', 'Def Building: Black Spire'),
    20500: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_2', ItemType.building, 1, 'Progressive def_settlement_major', 'Def Building: Dark Hold'),
    20501: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_3', ItemType.building, 2, 'Progressive def_settlement_major', 'Def Building: Dark Tower'),
    20502: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_4', ItemType.building, 3, 'Progressive def_settlement_major', 'Def Building: Dark Citadel'),
    20503: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_5', ItemType.building, 4, 'Progressive def_settlement_major', 'Def Building: Dark City'),
    20504: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_1', ItemType.building, 0, 'Progressive def_settlement_minor', 'Def Building: Black Spire'),
    20505: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_2', ItemType.building, 1, 'Progressive def_settlement_minor', 'Def Building: Dark Hold'),
    20506: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_3', ItemType.building, 2, 'Progressive def_settlement_minor', 'Def Building: Dark Tower'),
    20507: ItemData(IC.useful, 1, 'wh2_main_def_slaves_1', ItemType.building, 0, 'Progressive def_slaves', 'Def Building: Slave Pens'),
    20508: ItemData(IC.useful, 1, 'wh2_main_def_slaves_2', ItemType.building, 1, 'Progressive def_slaves', 'Def Building: Slave Market'),
    20509: ItemData(IC.useful, 1, 'wh2_main_def_sorcery_1', ItemType.building, 0, 'Progressive def_sorcery', "Def Building: Sorceress' Abode"),
    20510: ItemData(IC.useful, 1, 'wh2_main_def_sorcery_2', ItemType.building, 1, 'Progressive def_sorcery', 'Def Building: Tower of Dark Sorcery'),
    20523: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_def', 'Def Building: City Tunnels'),
    20524: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_def', 'Def Building: Guarded Tunnels'),
    20525: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_def', 'Def Building: Barricaded Tunnels'),
    20526: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_1', ItemType.building, 0, 'Progressive horde_def_beasts', 'Def Black Ark: Harpy Cages'),
    20527: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_2', ItemType.building, 1, 'Progressive horde_def_beasts', 'Def Black Ark: Monster Holds'),
    20528: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_3', ItemType.building, 2, 'Progressive horde_def_beasts', 'Def Black Ark: Dragon Tower'),
    20529: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_1', ItemType.building, 0, 'Progressive horde_def_bombardment_a', 'Def Black Ark: Sacrificial Pit of Khaine'),
    20530: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_2', ItemType.building, 1, 'Progressive horde_def_bombardment_a', 'Def Black Ark: Abbatoir of Khaine'),
    20531: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_1', ItemType.building, 0, 'Progressive horde_def_bombardment_b', 'Def Black Ark: Soul Brazier'),
    20532: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_2', ItemType.building, 1, 'Progressive horde_def_bombardment_b', 'Def Black Ark: Soul Furnance'),
    20533: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_1', ItemType.building, 0, 'Progressive horde_def_bombardment_c', 'Def Black Ark: Brazen Cauldron'),
    20534: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_2', ItemType.building, 1, 'Progressive horde_def_bombardment_c', 'Def Black Ark: Bloodwrack Cauldron'),
    20538: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_1', ItemType.building, 0, 'Progressive horde_def_military', 'Def Black Ark: Corsair Cabins'),
    20539: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_2', ItemType.building, 1, 'Progressive horde_def_military', 'Def Black Ark: Raider Lodges'),
    20540: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_3', ItemType.building, 2, 'Progressive horde_def_military', 'Def Black Ark: Warrior Hall'),
    20541: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_1', ItemType.building, 0, 'Progressive horde_def_settlement', 'Def Black Ark: Small Black Ark'),
    20542: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_2', ItemType.building, 0, 'Progressive horde_def_settlement', 'Def Black Ark: Black Ark'),
    20543: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_3', ItemType.building, 1, 'Progressive horde_def_settlement', 'Def Black Ark: Grand Black Ark'),
    20544: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_4', ItemType.building, 2, 'Progressive horde_def_settlement', 'Def Black Ark: Enormous Black Ark'),
    20545: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_5', ItemType.building, 3, 'Progressive horde_def_settlement', 'Def Black Ark: Gargantuan Black Ark'),
    20546: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_1', ItemType.building, 0, 'Progressive horde_def_slavery', 'Def Black Ark: Slave Hold'),
    20547: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_2', ItemType.building, 1, 'Progressive horde_def_slavery', 'Def Black Ark: Cell Decks'),
    20548: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_3', ItemType.building, 2, 'Progressive horde_def_slavery', 'Def Black Ark: Prison Wing'),
    20549: ItemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_1', ItemType.building, 0, 'Progressive horde_def_sorcery', 'Def Black Ark: Sorceress Cabin'),
    20550: ItemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_2', ItemType.building, 1, 'Progressive horde_def_sorcery', 'Def Black Ark: Spire of Sorcery'),
    20553: ItemData(IC.useful, 1, 'wh2_main_horde_def_worship_1', ItemType.building, 0, 'Progressive horde_def_worship', 'Def Black Ark: Altar of Khaine'),
    20554: ItemData(IC.useful, 1, 'wh2_main_horde_def_worship_2', ItemType.building, 1, 'Progressive horde_def_worship', 'Def Black Ark: Shrine of Khaine'),
    20562: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'Def Building: Occupied Lothern (Black Spire)'),
    20563: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'Def Building: Occupied Lothern (Dark Hold)'),
    20564: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'Def Building: Occupied Lothern (Dark Tower)'),
    20565: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'Def Building: Occupied Lothern (Dark Citadel)'),
    20566: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'Def Building: Occupied Lothern (Dark City)'),
    20567: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_1', ItemType.building, 0, 'Progressive def_settlement_major', 'Def Building: Occupied Sartosa Level 1'),
    20568: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_2', ItemType.building, 1, 'Progressive def_settlement_major', 'Def Building: Occupied Sartosa Level 2'),
    20569: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_3', ItemType.building, 2, 'Progressive def_settlement_major', 'Def Building: Occupied Sartosa Level 3'),
    20570: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_4', ItemType.building, 3, 'Progressive def_settlement_major', 'Def Building: Occupied Sartosa Level 4'),
    20571: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_5', ItemType.building, 4, 'Progressive def_settlement_major', 'Def Building: Occupied Sartosa Level 5'),
    20577: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_1', ItemType.building, 0, 'Progressive def_allied_outpost', 'Def Building: Dark Elf Outpost'),
    20578: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_2', ItemType.building, 1, 'Progressive def_allied_outpost', 'Def Building: Dark Elf District'),
    20579: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_3', ItemType.building, 2, 'Progressive def_allied_outpost', 'Def Building: Dark Elf Colony'),
    20580: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_1', ItemType.building, 0, 'Progressive def_resource_ivory', 'Def Building: Animal Store'),
    20581: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_2', ItemType.building, 1, 'Progressive def_resource_ivory', 'Def Building: Tusk Market'),
    20582: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_3', ItemType.building, 2, 'Progressive def_resource_ivory', 'Def Building: Tusk Compound'),
}

techs: dict[int, ItemData] = {
    20820: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_0_0', ItemType.tech, 1, 'Progressive tech_def_0', 'Def Tech: Choose or Die!'),
    20804: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_0', ItemType.tech, 2, 'Progressive tech_def_0', 'Def Tech: Driven by Vengeance'),
    20800: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_1', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Marching to War'),
    20805: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_2', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Martial Society'),
    20812: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_3', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Ascension Through Battle'),
    20821: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_0', ItemType.tech, 2, 'Progressive tech_def_0', 'Def Tech: Battle as Business'),
    20816: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_1', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Chartered Piracy'),
    20822: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_2', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Naval Training'),
    20832: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_3', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Bloodthirsty Companions'),
    20840: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_0', ItemType.tech, 2, 'Progressive tech_def_0', 'Def Tech: Founded on Tyranny'),
    20836: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_1', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Revel in Suffering'),
    20841: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_2', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Continuous Slave Supply'),
    20848: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_3', ItemType.tech, 3, 'Progressive tech_def_0', 'Def Tech: Exploit Feuds'),

    20823: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_0_0', ItemType.tech, 1, 'Progressive tech_def_1', 'Def Tech: Upgrade I'),
    20806: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_0', ItemType.tech, 2, 'Progressive tech_def_1', 'Def Tech: Forged to Kill'),
    20801: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_1', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Bolt Cartridges'),
    20807: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_2', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Hit & Run'),
    20813: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_3', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Reworked Crossbows'),
    20824: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_0', ItemType.tech, 2, 'Progressive tech_def_1', 'Def Tech: Broken by the Lash'),
    20817: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_1', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Sadistic Handlers'),
    20825: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_2', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Dominating the Beasts'),
    20833: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_3', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Daylight Denied'),
    20842: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_0', ItemType.tech, 2, 'Progressive tech_def_1', 'Def Tech: Tempered in Blood'),
    20837: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_1', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Temple Training Grounds'),
    20843: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_2', ItemType.tech, 3, 'Progressive tech_def_1', 'Def Tech: Purge the Weak'),

    20826: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_0_0', ItemType.tech, 1, 'Progressive tech_def_2', 'Def Tech: Upgrade II'),
    20808: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_0', ItemType.tech, 2, 'Progressive tech_def_2', 'Def Tech: An Instrument of War'),
    20802: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_1', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Black Iron Armour'),
    20809: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_2', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Exotic Beast Hide Armour'),
    20814: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_3', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Walking in Darkness'),
    20827: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_0', ItemType.tech, 2, 'Progressive tech_def_2', 'Def Tech: Pressed into Servitude'),
    20818: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_1', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Recruit Convicts'),
    20828: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_2', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Hunt Outlaws'),
    20834: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_3', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Spoils of War'),
    20844: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_0', ItemType.tech, 2, 'Progressive tech_def_2', 'Def Tech: Consumed by Rivalry'),
    20838: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_1', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Hardship & Cruelty'),
    20845: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_2', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Divide & Conquer'),
    20850: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_3', ItemType.tech, 3, 'Progressive tech_def_2', 'Def Tech: Masters of Murder'),

    20829: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_0_0', ItemType.tech, 1, 'Progressive tech_def_3', 'Def Tech: Upgrade III'),
    20810: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_0', ItemType.tech, 2, 'Progressive tech_def_3', 'Def Tech: No Signs of Weakness'),
    20803: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_1', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Bloodforged Platemail'),
    20811: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_2', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Ceremonial Weapons'),
    20815: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_3', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Serrated Blades'),
    20830: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_0', ItemType.tech, 2, 'Progressive tech_def_3', 'Def Tech: Under the Yoke'),
    20819: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_1', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Bewitch Dragon Eggs'),
    20831: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_2', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Harnessed Fury'),
    20835: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_3', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Bred in Captivity'),
    20846: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_0', ItemType.tech, 2, 'Progressive tech_def_3', 'Def Tech: A Life of Dread'),
    20839: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_1', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Deadly Accountability'),
    20851: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_3', ItemType.tech, 3, 'Progressive tech_def_3', 'Def Tech: Study the Chaos Wastes')
}

progUnits: dict[int, ItemData] = {
    21200: ItemData(IC.useful, 4, "Progressive def_inf", ItemType.unit, 4, "", "Progressive Def Unit: Infantry"),
    21201: ItemData(IC.useful, 3, "Progressive def_rng", ItemType.unit, 3, "", "Progressive Def Unit: Ranged"),
    21202: ItemData(IC.useful, 4, "Progressive def_cav", ItemType.unit, 4, "", "Progressive Def Unit: Cavalry"),
    21203: ItemData(IC.useful, 1, "Progressive def_art", ItemType.unit, 1, "", "Progressive Def Unit: Artillery"),
    21204: ItemData(IC.useful, 3, "Progressive def_veh", ItemType.unit, 3, "", "Progressive Def Unit: Chariot"),
    21205: ItemData(IC.useful, 3, "Progressive def_bst", ItemType.unit, 3, "", "Progressive Def Unit: Beast"),
    21206: ItemData(IC.useful, 2, "Progressive def_hro", ItemType.unit, 2, "", "Progressive Def Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    21300: ItemData(IC.useful, 2, 'Progressive horde_def_aristocracy', ItemType.building, 2, None, 'Progressive Def Black Ark: Aristocracy'),
    21301: ItemData(IC.useful, 2, 'Progressive horde_def_exiles', ItemType.building, 2, None, 'Progressive Def Black Ark: Exiles'),
    21302: ItemData(IC.useful, 3, 'Progressive horde_def_residence', ItemType.building, 3, None, 'Progressive Def Black Ark: Residence'),
    21303: ItemData(IC.useful, 2, 'Progressive horde_def_riders', ItemType.building, 2, None, 'Progressive Def Black Ark: Riders'),
    21304: ItemData(IC.useful, 3, 'Progressive def_barracks', ItemType.building, 3, None, 'Progressive Def Building: Barracks'),
    21305: ItemData(IC.useful, 3, 'Progressive def_beasts', ItemType.building, 3, None, 'Progressive Def Building: Beasts'),
    21306: ItemData(IC.useful, 2, 'Progressive def_coldones', ItemType.building, 2, None, 'Progressive Def Building: Coldones'),
    21307: ItemData(IC.useful, 3, 'Progressive def_defence_major', ItemType.building, 3, None, 'Progressive Def Building: Defence Major'),
    21308: ItemData(IC.useful, 2, 'Progressive def_defence_minor', ItemType.building, 2, None, 'Progressive Def Building: Defence Minor'),
    21309: ItemData(IC.useful, 2, 'Progressive def_exiles', ItemType.building, 2, None, 'Progressive Def Building: Exiles'),
    21310: ItemData(IC.useful, 3, 'Progressive def_farm', ItemType.building, 3, None, 'Progressive Def Building: Farm'),
    21311: ItemData(IC.useful, 3, 'Progressive def_industry', ItemType.building, 3, None, 'Progressive Def Building: Industry'),
    21312: ItemData(IC.useful, 3, 'Progressive def_order', ItemType.building, 3, None, 'Progressive Def Building: Order'),
    21313: ItemData(IC.useful, 3, 'Progressive def_port', ItemType.building, 3, None, 'Progressive Def Building: Port'),
    21314: ItemData(IC.useful, 3, 'Progressive def_resource_animals', ItemType.building, 3, None, 'Progressive Def Building: Animals'),
    21315: ItemData(IC.useful, 3, 'Progressive def_resource_dyes', ItemType.building, 3, None, 'Progressive Def Building: Dyes'),
    21316: ItemData(IC.useful, 3, 'Progressive def_resource_furs', ItemType.building, 3, None, 'Progressive Def Building: Furs'),
    21317: ItemData(IC.useful, 3, 'Progressive def_resource_gems', ItemType.building, 3, None, 'Progressive Def Building: Gems'),
    21318: ItemData(IC.useful, 3, 'Progressive def_resource_gold', ItemType.building, 3, None, 'Progressive Def Building: Gold'),
    21319: ItemData(IC.useful, 3, 'Progressive def_resource_iron', ItemType.building, 3, None, 'Progressive Def Building: Iron'),
    21320: ItemData(IC.useful, 3, 'Progressive def_resource_marble', ItemType.building, 3, None, 'Progressive Def Building: Marble'),
    21321: ItemData(IC.useful, 3, 'Progressive def_resource_medicine', ItemType.building, 3, None, 'Progressive Def Building: Medicine'),
    21322: ItemData(IC.useful, 3, 'Progressive def_resource_obsidian', ItemType.building, 3, None, 'Progressive Def Building: Obsidian'),
    21323: ItemData(IC.useful, 3, 'Progressive def_resource_pasture', ItemType.building, 3, None, 'Progressive Def Building: Pasture'),
    21324: ItemData(IC.useful, 3, 'Progressive def_resource_pottery', ItemType.building, 3, None, 'Progressive Def Building: Pottery'),
    21325: ItemData(IC.useful, 3, 'Progressive def_resource_salt', ItemType.building, 3, None, 'Progressive Def Building: Salt'),
    21326: ItemData(IC.useful, 3, 'Progressive def_resource_spices', ItemType.building, 3, None, 'Progressive Def Building: Spices'),
    21327: ItemData(IC.useful, 3, 'Progressive def_resource_wine', ItemType.building, 3, None, 'Progressive Def Building: Wine'),
    21328: ItemData(IC.useful, 3, 'Progressive def_resource_wood', ItemType.building, 3, None, 'Progressive Def Building: Wood'),
    21329: ItemData(IC.useful, 2, 'Progressive def_riders', ItemType.building, 2, None, 'Progressive Def Building: Riders'),
    21330: ItemData(IC.useful, 1, 'Progressive def_roads', ItemType.building, 1, None, 'Progressive Def Building: Roads'),
    21331: ItemData(IC.useful, 5, 'Progressive def_settlement_major', ItemType.building, 5, None, 'Progressive Def Building: Settlement Major'),
    21332: ItemData(IC.useful, 3, 'Progressive def_settlement_minor', ItemType.building, 3, None, 'Progressive Def Building: Settlement Minor'),
    21333: ItemData(IC.useful, 2, 'Progressive def_slaves', ItemType.building, 2, None, 'Progressive Def Building: Slaves'),
    21334: ItemData(IC.useful, 2, 'Progressive def_sorcery', ItemType.building, 2, None, 'Progressive Def Building: Sorcery'),
    21335: ItemData(IC.useful, 3, 'Progressive def_worship', ItemType.building, 3, None, 'Progressive Def Building: Worship'),
    21336: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_def', ItemType.building, 3, None, 'Progressive Def Building: Foreign Slot Discovery Def'),
    21337: ItemData(IC.useful, 3, 'Progressive horde_def_beasts', ItemType.building, 3, None, 'Progressive Def Black Ark: Beasts'),
    21338: ItemData(IC.useful, 2, 'Progressive horde_def_bombardment_a', ItemType.building, 2, None, 'Progressive Def Black Ark: Bombardment'),
    21339: ItemData(IC.useful, 3, 'Progressive horde_def_entertainment', ItemType.building, 3, None, 'Progressive Def Black Ark: Entertainment'),
    21340: ItemData(IC.useful, 3, 'Progressive horde_def_military', ItemType.building, 3, None, 'Progressive Def Black Ark: Military'),
    21341: ItemData(IC.useful, 4, 'Progressive horde_def_settlement', ItemType.building, 4, None, 'Progressive Def Black Ark: Settlement'),
    21342: ItemData(IC.useful, 3, 'Progressive horde_def_slavery', ItemType.building, 3, None, 'Progressive Def Black Ark: Slavery'),
    21343: ItemData(IC.useful, 2, 'Progressive horde_def_sorcery', ItemType.building, 2, None, 'Progressive Def Black Ark: Sorcery'),
    21344: ItemData(IC.useful, 2, 'Progressive horde_def_worship', ItemType.building, 2, None, 'Progressive Def Black Ark: Worship'),
    21345: ItemData(IC.useful, 3, 'Progressive def_allied_outpost', ItemType.building, 3, None, 'Progressive Def Building: Allied Outpost'),
    21346: ItemData(IC.useful, 3, 'Progressive def_resource_ivory', ItemType.building, 3, None, 'Progressive Def Building: Ivory')
}

progTechs: dict[int, ItemData] = {
    21400: ItemData(IC.useful, 3, "Progressive tech_def_0", ItemType.tech, 3, None, "Progressive Def Tech: Base"),
    21401: ItemData(IC.useful, 3, "Progressive tech_def_1", ItemType.tech, 3, None, "Progressive Def Tech: Upgrade 1"),
    21402: ItemData(IC.useful, 3, "Progressive tech_def_2", ItemType.tech, 3, None, "Progressive Def Tech: Upgrade 2"),
    21403: ItemData(IC.useful, 3, "Progressive tech_def_3", ItemType.tech, 3, None, "Progressive Def Tech: Upgrade 3"),
}

special: dict[int, specialItemData] = {
    21500: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh3_main_sla_inf_daemonette_0', ItemType.unit, 2, 'Progressive def_inf', False, False, 'Def Unit: Daemonettes of Slaanesh'),
    21501: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh3_main_sla_inf_daemonette_1', ItemType.unit, 4, 'Progressive def_inf', False, False, 'Def Unit: Exalted Daemonettes of Slaanesh'),
    21502: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh3_dlc27_sla_inf_devotees_of_slaanesh', ItemType.unit, 4, 'Progressive def_inf', False, False, 'Def Unit: Devotees of Slaanesh'),
    21503: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh3_dlc27_sla_inf_devotees_of_slaanesh_crossbows', ItemType.unit, 3, 'Progressive def_rng', False, False, 'Def Unit: Devotees of Slaanesh (Crossbows)'),
    21504: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh3_dlc27_sla_cha_druchii_anointed', ItemType.unit, 2, 'Progressive def_hro', False, False, 'Def Unit: Druchii Anointed'),
    21505: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', False, False, 'Def Building: Altar of Khaine'),
    21506: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', False, False, 'Def Building: Shrine of Khaine'),
    21507: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', False, False, 'Def Building: Temple of Khaine'),
    21508: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', False, False, 'Def Building: Altar of Khaine'),
    21509: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', False, False, 'Def Building: Shrine of Khaine'),
    21510: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', False, False, 'Def Building: Temple of Khaine'),
    21511: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', False, False, 'Def Building: Altar of Khaine'),
    21512: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', False, False, 'Def Building: Shrine of Khaine'),
    21513: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', False, False, 'Def Building: Temple of Khaine'),
    21514: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', False, False, 'Def Building: Altar of Khaine'),
    21515: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', False, False, 'Def Building: Shrine of Khaine'),
    21516: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', False, False, 'Def Building: Temple of Khaine'),
    21517: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', False, False, 'Def Building: Altar of Khaine'),
    21518: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', False, False, 'Def Building: Shrine of Khaine'),
    21519: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', False, False, 'Def Building: Temple of Khaine'),
    21520: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', False, False, 'Def Building: Torture Posts'),
    21521: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', False, False, 'Def Building: Fighting Pits'),
    21522: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', False, False, 'Def Building: Arena'),
    21523: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', False, False, 'Def Building: Torture Posts'),
    21524: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', False, False, 'Def Building: Fighting Pits'),
    21525: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', False, False, 'Def Building: Arena'),
    21526: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', False, False, 'Def Building: Torture Posts'),
    21527: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', False, False, 'Def Building: Fighting Pits'),
    21528: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', False, False, 'Def Building: Arena'),
    21529: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', False, False, 'Def Building: Torture Posts'),
    21530: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', False, False, 'Def Building: Fighting Pits'),
    21531: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', False, False, 'Def Building: Arena'),
    21532: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', False, False, 'Def Building: Torture Posts'),
    21533: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', False, False, 'Def Building: Fighting Pits'),
    21534: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', False, False, 'Def Building: Arena'),
    21535: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_murder_1', ItemType.building, 0, 'Progressive def_murder', False, False, 'Def Building: House of Assassins'),
    21536: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_murder_2', ItemType.building, 1, 'Progressive def_murder', False, False, 'Def Building: Shrine of Khaine'),
    21537: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'Progressive def_murder', ItemType.building, 2, None, False, True, 'Progressive Def Building: Hired Killers'),
    21538: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_pleasure_cult_1', ItemType.building, 2, 'Progressive def_pleasure', False, False, 'Def Building: Cultist Gathering'),
    21539: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_pleasure_cult_2', ItemType.building, 2, 'Progressive def_pleasure', False, False, 'Def Building: Den of Indulgence'),
    21540: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_pleasure_cult_3', ItemType.building, 2, 'Progressive def_pleasure', False, False, 'Def Building: House of Pleasure'),
    21541: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_pleasure_cult_4', ItemType.building, 2, 'Progressive def_pleasure', False, False, 'Def Building: Halls of Hedonism'),
    21542: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_def_pleasure_cult_5', ItemType.building, 2, 'Progressive def_pleasure', False, False, 'Def Building: Court of the Dark Prince'),
    21543: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'Progressive def_pleasure', ItemType.building, 2, None, False, True, 'Progressive Def Building: Pleasure Cult'),
    21544: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_tech_def_1_3_3', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Khaine'),
    21545: specialItemData(IC.useful, 1, 'wh2_main_def_naggarond', 'wh2_main_tech_def_3_3_2', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Blood & Death'),
    21546: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_tech_def_1_3_3', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Khaine'),
    21547: specialItemData(IC.useful, 1, 'wh2_main_def_har_ganeth', 'wh2_main_tech_def_3_3_2', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Blood & Death'),
    21548: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_tech_def_1_3_3', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Khaine'),
    21549: specialItemData(IC.useful, 1, 'wh2_dlc11_def_the_blessed_dread', 'wh2_main_tech_def_3_3_2', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Blood & Death'),
    21550: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_tech_def_1_3_3', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Khaine'),
    21551: specialItemData(IC.useful, 1, 'wh2_main_def_hag_graef', 'wh2_main_tech_def_3_3_2', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Blood & Death'),
    21552: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_tech_def_1_3_3', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Khaine'),
    21553: specialItemData(IC.useful, 1, 'wh2_twa03_def_rakarth', 'wh2_main_tech_def_3_3_2', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Blood & Death'),
    21554: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_tech_def_1_3_3_slaanesh', ItemType.tech, 3, 'Progressive tech_def_1', False, False, 'Def Tech: Festivals of Ruin'),
    21555: specialItemData(IC.useful, 1, 'wh2_main_def_cult_of_pleasure', 'wh2_main_tech_def_3_3_2_slaanesh', ItemType.tech, 3, 'Progressive tech_def_3', False, False, 'Def Tech: Endless Debauchery')
}

