from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    20000: ItemData(IC.useful, 1, 'wh2_twa03_def_cha_rakarth_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Rakarth'),
    20001: ItemData(IC.useful, 1, 'wh2_main_def_mon_black_dragon', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Black Dragon'),
    20002: ItemData(IC.useful, 1, 'wh2_main_def_inf_witch_elves_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Witch Elves'),
    20003: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_2', ItemType.unit, 3, 'Progressive def_rng', 'Def Unit: Shades (Greatswords)'),
    20004: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_1', ItemType.unit, 3, 'Progressive def_rng', 'Def Unit: Shades (Dual Weapons)'),
    20005: ItemData(IC.useful, 1, 'wh2_main_def_inf_shades_0', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Shades'),
    20006: ItemData(IC.useful, 1, 'wh2_main_def_inf_harpies', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Harpies'),
    20007: ItemData(IC.useful, 1, 'wh2_main_def_inf_har_ganeth_executioners_0', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Har Ganeth Executioners'),
    20008: ItemData(IC.useful, 1, 'wh2_main_def_inf_dreadspears_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: Dreadspears'),
    20009: ItemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_1', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Darkshards (Shields)'),
    20010: ItemData(IC.useful, 1, 'wh2_main_def_inf_darkshards_0', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Darkshards'),
    20011: ItemData(IC.useful, 1, 'wh2_main_def_inf_bleakswords_0', ItemType.unit, 1, 'Progressive def_inf', 'Def Unit: Bleakswords'),
    20012: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_guard_0', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Black Guard of Naggarond'),
    20013: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_1', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: Black Ark Corsairs (Handbows)'),
    20014: ItemData(IC.useful, 1, 'wh2_main_def_inf_black_ark_corsairs_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Black Ark Corsairs'),
    20015: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_dark_1', ItemType.unit, 0, 'cavalry', 'Def Unit: Sorceress (Dark)'),
    20016: ItemData(IC.useful, 1, 'wh2_main_def_cha_sorceress_dark_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Sorceress (Dark)'),
    20017: ItemData(IC.useful, 1, 'wh2_main_def_cha_malekith_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Malekith'),
    20018: ItemData(IC.useful, 1, 'wh2_main_def_cha_khainite_assassin_0', ItemType.unit, 0, 'Progressive def_rng', 'Def Unit: Khainite Assassin'),
    20019: ItemData(IC.useful, 1, 'wh2_main_def_cha_dreadlord_1', ItemType.unit, 0, 'cavalry', 'Def Unit: Dreadlord (Sword & Crossbow)'),
    20020: ItemData(IC.useful, 1, 'wh2_main_def_cha_dreadlord_0', ItemType.unit, 0, 'Progressive def_rng', 'Def Unit: Dreadlord (Sword & Crossbow)'),
    20021: ItemData(IC.useful, 1, 'wh2_main_def_cha_death_hag_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Death Hag'),
    20022: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_2', ItemType.unit, 2, 'cavalry', 'Def Unit: Dark Riders (Repeater Crossbows)'),
    20023: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_1', ItemType.unit, 2, 'cavalry', 'Def Unit: Dark Riders (Shields)'),
    20024: ItemData(IC.useful, 1, 'wh2_main_def_cav_dark_riders_0', ItemType.unit, 1, 'cavalry', 'Def Unit: Dark Riders'),
    20025: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_1', ItemType.unit, 3, 'cavalry', 'Def Unit: Cold One Dread Knights'),
    20026: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_knights_0', ItemType.unit, 3, 'cavalry', 'Def Unit: Cold One Knights'),
    20027: ItemData(IC.useful, 1, 'wh2_main_def_cav_cold_one_chariot', ItemType.unit, 3, 'Progressive def_veh', 'Def Unit: Cold One Chariots'),
    20028: ItemData(IC.useful, 1, 'wh2_main_def_art_reaper_bolt_thrower', ItemType.unit, 2, 'Progressive def_art', 'Def Unit: Reaper Bolt Throwers'),
    20029: ItemData(IC.useful, 1, 'wh2_dlc14_def_veh_bloodwrack_shrine_0', ItemType.unit, 4, 'Progressive def_veh', 'Def Unit: Bloodwrack Shrine'),
    20030: ItemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_ror_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: The Siren of Red Ruin (Bloodwrack Medusa)'),
    20031: ItemData(IC.useful, 1, 'wh2_dlc14_def_mon_bloodwrack_medusa_0', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Bloodwrack Medusa'),
    20032: ItemData(IC.useful, 1, 'wh2_dlc14_def_inf_harpies_ror_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: The Crows of Khaine (Harpies)'),
    20033: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_master_2', ItemType.unit, 0, 'cavalry', 'Def Unit: Master'),
    20034: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_master_1', ItemType.unit, 0, 'cavalry', 'Def Unit: Master'),
    20035: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_master_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Master'),
    20036: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_malus_darkblade_1', ItemType.unit, 0, 'cavalry', 'Def Unit: Malus Darkblade'),
    20037: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_malus_darkblade_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Malus Darkblade'),
    20038: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_high_beastmaster_1', ItemType.unit, 0, 'Progressive def_veh', 'Def Unit: High Beastmaster'),
    20039: ItemData(IC.useful, 1, 'wh2_dlc14_def_cha_high_beastmaster_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: High Beastmaster'),
    20040: ItemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_ror_0', ItemType.unit, 3, 'Progressive def_veh', 'Def Unit: Ravagers of Rakarth (Scourgerunner Chariots)'),
    20041: ItemData(IC.useful, 1, 'wh2_dlc14_def_cav_scourgerunner_chariot_0', ItemType.unit, 2, 'Progressive def_veh', 'Def Unit: Scourgerunner Chariots'),
    20042: ItemData(IC.useful, 1, 'wh2_dlc11_def_cha_lokhir_fellheart_1', ItemType.unit, 0, 'war_beast', 'Def Unit: Lokhir Fellheart'),
    20043: ItemData(IC.useful, 1, 'wh2_dlc11_def_cha_lokhir_fellheart_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Lokhir Fellheart'),
    20044: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_kharibdyss_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Kharibdyss'),
    20045: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_feral_manticore_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: Feral Manticore'),
    20046: ItemData(IC.useful, 1, 'wh2_dlc10_def_mon_chill_of_sontar_ror_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Chill of Sontar (War Hydra)'),
    20047: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_hellebronai_ror_0', ItemType.unit, 2, 'Progressive def_inf', 'Def Unit: The Hellebronai (Dreadspears)'),
    20048: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_the_bolt_fiends_ror_0', ItemType.unit, 2, 'Progressive def_rng', 'Def Unit: The Bolt-fiends (Darkshards â€“ Shields)'),
    20049: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_the_singing_doom_ror_0', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Sisters of the Singing Doom (Witch Elves)'),
    20050: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_sisters_of_slaughter', ItemType.unit, 3, 'Progressive def_inf', 'Def Unit: Sisters of Slaughter'),
    20051: ItemData(IC.useful, 1, 'wh2_dlc10_def_inf_blades_of_the_blood_queen_ror_0', ItemType.unit, 4, 'Progressive def_inf', 'Def Unit: Blades of the Blood Queen (Har Ganeth Executioners)'),
    20052: ItemData(IC.useful, 1, 'wh2_dlc10_def_cha_supreme_sorceress_shadow_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Supreme Sorceress (Shadows)'),
    20053: ItemData(IC.useful, 1, 'wh2_dlc10_def_cha_supreme_sorceress_fire_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Supreme Sorceress (Fire)'),
    20054: ItemData(IC.useful, 1, 'wh2_dlc10_def_cha_supreme_sorceress_dark_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Supreme Sorceress (Dark)'),
    20055: ItemData(IC.useful, 1, 'wh2_dlc10_def_cha_crone_0', ItemType.unit, 0, 'Progressive def_inf', 'Def Unit: Crone Hellebron'),
    20056: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_slaanesh_harvesters_ror_0', ItemType.unit, 3, 'cavalry', "Def Unit: Slaanesh's Harvesters (Doomfire Warlocks)"),
    20057: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_raven_heralds_ror_0', ItemType.unit, 2, 'cavalry', 'Def Unit: Raven Heralds (Dark Riders)'),
    20058: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_knights_of_the_ebon_claw_ror_0', ItemType.unit, 4, 'cavalry', 'Def Unit: Knights of the Ebon Claw (Dread Knights)'),
    20059: ItemData(IC.useful, 1, 'wh2_dlc10_def_cav_doomfire_warlocks_0', ItemType.unit, 3, 'cavalry', 'Def Unit: Doomfire Warlocks')
}

buildings: dict[int, ItemData] = {
    20400: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_1', ItemType.building, 0, 'Progressive horde_def_aristocracy', 'Def Building: Dread Manse'),
    20401: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_2', ItemType.building, 1, 'Progressive horde_def_aristocracy', 'Def Building: Palace of Dread Knights'),
    20402: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_1', ItemType.building, 0, 'Progressive horde_def_exiles', 'Def Building: Den of Outlaws'),
    20403: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_2', ItemType.building, 1, 'Progressive horde_def_exiles', 'Def Building: House of Exiles'),
    20404: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_1', ItemType.building, 0, 'Progressive horde_def_residence', 'Def Building: Dark Elf Manors'),
    20405: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_2', ItemType.building, 1, 'Progressive horde_def_residence', 'Def Building: Dark Elf Residences'),
    20406: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_3', ItemType.building, 2, 'Progressive horde_def_residence', 'Def Building: Estates of the Masters'),
    20407: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_1', ItemType.building, 0, 'Progressive horde_def_riders', 'Def Building: Reaver Stables'),
    20408: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_2', ItemType.building, 1, 'Progressive horde_def_riders', "Def Building: Messengers' Lodgehouse"),
    20409: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_1', ItemType.building, 0, 'Progressive special_settlement_tor_yvresse_def', 'Def Building: Occupied Tor Yvresse (Black Spire)'),
    20410: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_2', ItemType.building, 1, 'Progressive special_settlement_tor_yvresse_def', 'Def Building: Occupied Tor Yvresse (Dark Hold)'),
    20411: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_3', ItemType.building, 2, 'Progressive special_settlement_tor_yvresse_def', 'Def Building: Occupied Tor Yvresse (Dark Tower)'),
    20412: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_4', ItemType.building, 3, 'Progressive special_settlement_tor_yvresse_def', 'Def Building: Occupied Tor Yvresse (Dark Citadel)'),
    20413: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_tor_yvresse_def_5', ItemType.building, 4, 'Progressive special_settlement_tor_yvresse_def', 'Def Building: Occupied Tor Yvresse (Dark City)'),
    20414: ItemData(IC.useful, 1, 'wh2_main_def_barracks_1', ItemType.building, 0, 'Progressive def_barracks', 'Def Building: Conscription Halls'),
    20415: ItemData(IC.useful, 1, 'wh2_main_def_barracks_2', ItemType.building, 1, 'Progressive def_barracks', 'Def Building: Halls of Mustering'),
    20416: ItemData(IC.useful, 1, 'wh2_main_def_barracks_3', ItemType.building, 2, 'Progressive def_barracks', 'Def Building: Halls of Ravaging'),
    20417: ItemData(IC.useful, 1, 'wh2_main_def_beasts_1', ItemType.building, 0, 'Progressive def_beasts', 'Def Building: Harpy Roost'),
    20418: ItemData(IC.useful, 1, 'wh2_main_def_beasts_2', ItemType.building, 1, 'Progressive def_beasts', "Def Building: Beastmaster's Stables"),
    20419: ItemData(IC.useful, 1, 'wh2_main_def_beasts_3', ItemType.building, 2, 'Progressive def_beasts', 'Def Building: Dragon Hatchery'),
    20420: ItemData(IC.useful, 1, 'wh2_main_def_coldones_1', ItemType.building, 0, 'Progressive def_coldones', 'Def Building: Dread Manse'),
    20421: ItemData(IC.useful, 1, 'wh2_main_def_coldones_2', ItemType.building, 1, 'Progressive def_coldones', 'Def Building: Palace of Dread Knights'),
    20422: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_1', ItemType.building, 0, 'Progressive def_defence_major', 'Def Building: Slave Gate'),
    20423: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_2', ItemType.building, 1, 'Progressive def_defence_major', 'Def Building: Blackstone Walls'),
    20424: ItemData(IC.useful, 1, 'wh2_main_def_defence_major_3', ItemType.building, 2, 'Progressive def_defence_major', 'Def Building: Dread Bulwark'),
    20425: ItemData(IC.useful, 1, 'wh2_main_def_defence_minor_1', ItemType.building, 0, 'Progressive def_defence_minor', 'Def Building: Watchtowers'),
    20426: ItemData(IC.useful, 1, 'wh2_main_def_defence_minor_2', ItemType.building, 1, 'Progressive def_defence_minor', 'Def Building: Dark Palisade'),
    20427: ItemData(IC.useful, 1, 'wh2_main_def_defence_norsca_1', ItemType.building, 0, 'Progressive def_defence_norsca', 'Def Building: Outpost Garrison'),
    20428: ItemData(IC.useful, 1, 'wh2_main_def_exiles_1', ItemType.building, 0, 'Progressive def_exiles', 'Def Building: Den of Outlaws'),
    20429: ItemData(IC.useful, 1, 'wh2_main_def_exiles_2', ItemType.building, 1, 'Progressive def_exiles', 'Def Building: House of Exiles'),
    20430: ItemData(IC.useful, 1, 'wh2_main_def_farm_1', ItemType.building, 0, 'Progressive def_farm', 'Def Building: Dark Elf Manors'),
    20431: ItemData(IC.useful, 1, 'wh2_main_def_farm_2', ItemType.building, 1, 'Progressive def_farm', 'Def Building: Dark Elf Residences'),
    20432: ItemData(IC.useful, 1, 'wh2_main_def_farm_3', ItemType.building, 2, 'Progressive def_farm', 'Def Building: Estates of the Masters'),
    20433: ItemData(IC.useful, 1, 'wh2_main_def_industry_1', ItemType.building, 0, 'Progressive def_industry', "Def Building: Artisan's House"),
    20434: ItemData(IC.useful, 1, 'wh2_main_def_industry_2', ItemType.building, 1, 'Progressive def_industry', 'Def Building: Crafting District'),
    20435: ItemData(IC.useful, 1, 'wh2_main_def_industry_3', ItemType.building, 2, 'Progressive def_industry', 'Def Building: Guild Halls'),
    20436: ItemData(IC.useful, 1, 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', 'Def Building: Torture Posts'),
    20437: ItemData(IC.useful, 1, 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', 'Def Building: Torture Posts'),
    20438: ItemData(IC.useful, 1, 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', 'Def Building: Torture Posts'),
    20439: ItemData(IC.useful, 1, 'wh2_main_def_order_1', ItemType.building, 0, 'Progressive def_order', 'Def Building: Torture Posts'),
    20440: ItemData(IC.useful, 1, 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', 'Def Building: Fighting Pits'),
    20441: ItemData(IC.useful, 1, 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', 'Def Building: Fighting Pits'),
    20442: ItemData(IC.useful, 1, 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', 'Def Building: Fighting Pits'),
    20443: ItemData(IC.useful, 1, 'wh2_main_def_order_2', ItemType.building, 1, 'Progressive def_order', 'Def Building: Fighting Pits'),
    20444: ItemData(IC.useful, 1, 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', 'Def Building: Arena'),
    20445: ItemData(IC.useful, 1, 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', 'Def Building: Arena'),
    20446: ItemData(IC.useful, 1, 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', 'Def Building: Arena'),
    20447: ItemData(IC.useful, 1, 'wh2_main_def_order_3', ItemType.building, 2, 'Progressive def_order', 'Def Building: Arena'),
    20448: ItemData(IC.useful, 1, 'wh2_main_def_port_1', ItemType.building, 0, 'Progressive def_port', 'Def Building: Dark Elf Landing'),
    20449: ItemData(IC.useful, 1, 'wh2_main_def_port_2', ItemType.building, 1, 'Progressive def_port', 'Def Building: Dark Elf Harbour'),
    20450: ItemData(IC.useful, 1, 'wh2_main_def_port_3', ItemType.building, 2, 'Progressive def_port', 'Def Building: Dark Elf Port'),
    20451: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_1', ItemType.building, 0, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Tamer'),
    20452: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_2', ItemType.building, 1, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Pen'),
    20453: ItemData(IC.useful, 1, 'wh2_main_def_resource_animals_3', ItemType.building, 2, 'Progressive def_resource_animals', 'Def Building: Exotic Animal Market'),
    20454: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_1', ItemType.building, 0, 'Progressive def_resource_dyes', 'Def Building: Cinnabar Mining Pit'),
    20455: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_2', ItemType.building, 1, 'Progressive def_resource_dyes', 'Def Building: Cinnabar Mine'),
    20456: ItemData(IC.useful, 1, 'wh2_main_def_resource_dyes_3', ItemType.building, 2, 'Progressive def_resource_dyes', 'Def Building: Dyemaker'),
    20457: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_1', ItemType.building, 0, 'Progressive def_resource_furs', 'Def Building: Hunting Camp'),
    20458: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_2', ItemType.building, 1, 'Progressive def_resource_furs', 'Def Building: Hunting Lodge'),
    20459: ItemData(IC.useful, 1, 'wh2_main_def_resource_furs_3', ItemType.building, 2, 'Progressive def_resource_furs', 'Def Building: Tannery'),
    20460: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_1', ItemType.building, 0, 'Progressive def_resource_gems', 'Def Building: Gem Mineshaft'),
    20461: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_2', ItemType.building, 1, 'Progressive def_resource_gems', 'Def Building: Gem Mine'),
    20462: ItemData(IC.useful, 1, 'wh2_main_def_resource_gems_3', ItemType.building, 2, 'Progressive def_resource_gems', "Def Building: Gemcutter's Workshop"),
    20463: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_1', ItemType.building, 0, 'Progressive def_resource_gold', 'Def Building: Gold Mining Pit'),
    20464: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_2', ItemType.building, 1, 'Progressive def_resource_gold', 'Def Building: Gold Mine'),
    20465: ItemData(IC.useful, 1, 'wh2_main_def_resource_gold_3', ItemType.building, 2, 'Progressive def_resource_gold', 'Def Building: Gold Smelter'),
    20466: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_1', ItemType.building, 0, 'Progressive def_resource_iron', 'Def Building: Iron Mining Pit'),
    20467: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_2', ItemType.building, 1, 'Progressive def_resource_iron', 'Def Building: Iron Mines'),
    20468: ItemData(IC.useful, 1, 'wh2_main_def_resource_iron_3', ItemType.building, 2, 'Progressive def_resource_iron', 'Def Building: Iron Smelter'),
    20469: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_1', ItemType.building, 0, 'Progressive def_resource_marble', 'Def Building: Sawyer'),
    20470: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_2', ItemType.building, 1, 'Progressive def_resource_marble', 'Def Building: Marble Quarry'),
    20471: ItemData(IC.useful, 1, 'wh2_main_def_resource_marble_3', ItemType.building, 2, 'Progressive def_resource_marble', "Def Building: Stone Mason's Workshop"),
    20472: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_1', ItemType.building, 0, 'Progressive def_resource_medicine', "Def Building: Herb Gatherer's Camp"),
    20473: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_2', ItemType.building, 1, 'Progressive def_resource_medicine', 'Def Building: Exotic Hothouse'),
    20474: ItemData(IC.useful, 1, 'wh2_main_def_resource_medicine_3', ItemType.building, 2, 'Progressive def_resource_medicine', 'Def Building: Alchemy Workshop'),
    20475: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_1', ItemType.building, 0, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Quarry'),
    20476: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_2', ItemType.building, 1, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Trinket Maker'),
    20477: ItemData(IC.useful, 1, 'wh2_main_def_resource_obsidian_3', ItemType.building, 2, 'Progressive def_resource_obsidian', 'Def Building: Obsidian Amulet Carver'),
    20478: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_1', ItemType.building, 0, 'Progressive def_resource_pasture', 'Def Building: Grazing Pastures'),
    20479: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_2', ItemType.building, 1, 'Progressive def_resource_pasture', 'Def Building: Livestock Pens'),
    20480: ItemData(IC.useful, 1, 'wh2_main_def_resource_pasture_3', ItemType.building, 2, 'Progressive def_resource_pasture', 'Def Building: Cattle Ranch'),
    20481: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_1', ItemType.building, 0, 'Progressive def_resource_pottery', 'Def Building: Clay Pit'),
    20482: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_2', ItemType.building, 1, 'Progressive def_resource_pottery', 'Def Building: Pottery Maker'),
    20483: ItemData(IC.useful, 1, 'wh2_main_def_resource_pottery_3', ItemType.building, 2, 'Progressive def_resource_pottery', 'Def Building: Kilns'),
    20484: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_1', ItemType.building, 0, 'Progressive def_resource_salt', 'Def Building: Brine Mining Pans'),
    20485: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_2', ItemType.building, 1, 'Progressive def_resource_salt', 'Def Building: Brine Mining Basin'),
    20486: ItemData(IC.useful, 1, 'wh2_main_def_resource_salt_3', ItemType.building, 2, 'Progressive def_resource_salt', 'Def Building: Saltworks'),
    20487: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_1', ItemType.building, 0, 'Progressive def_resource_spices', 'Def Building: Spice Market'),
    20488: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_2', ItemType.building, 1, 'Progressive def_resource_spices', 'Def Building: Spice Trading Post'),
    20489: ItemData(IC.useful, 1, 'wh2_main_def_resource_spices_3', ItemType.building, 2, 'Progressive def_resource_spices', 'Def Building: Eastern Bazaar'),
    20490: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_1', ItemType.building, 0, 'Progressive def_resource_wine', 'Def Building: Orchards'),
    20491: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_2', ItemType.building, 1, 'Progressive def_resource_wine', 'Def Building: Vineyard'),
    20492: ItemData(IC.useful, 1, 'wh2_main_def_resource_wine_3', ItemType.building, 2, 'Progressive def_resource_wine', 'Def Building: Vintner'),
    20493: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_1', ItemType.building, 0, 'Progressive def_resource_wood', "Def Building: Woodman's Hut"),
    20494: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_2', ItemType.building, 1, 'Progressive def_resource_wood', 'Def Building: Timber Mill'),
    20495: ItemData(IC.useful, 1, 'wh2_main_def_resource_wood_3', ItemType.building, 2, 'Progressive def_resource_wood', 'Def Building: Lumberyard'),
    20496: ItemData(IC.useful, 1, 'wh2_main_def_riders_1', ItemType.building, 0, 'Progressive def_riders', 'Def Building: Plateau of Dark Steeds'),
    20497: ItemData(IC.useful, 1, 'wh2_main_def_riders_2', ItemType.building, 1, 'Progressive def_riders', "Def Building: Messengers' Lodgehouse"),
    20498: ItemData(IC.useful, 1, 'wh2_main_def_roads_1', ItemType.building, 0, 'Progressive def_roads', 'Def Building: Black Roads'),
    20499: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_1', ItemType.building, 0, 'Progressive def_settlement_major', 'Def Building: Black Spire'),
    20500: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_2', ItemType.building, 1, 'Progressive def_settlement_major', 'Def Building: Dark Hold'),
    20501: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_3', ItemType.building, 2, 'Progressive def_settlement_major', 'Def Building: Dark Tower'),
    20502: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_4', ItemType.building, 3, 'Progressive def_settlement_major', 'Def Building: Dark Citadel'),
    20503: ItemData(IC.useful, 1, 'wh2_main_def_settlement_major_5', ItemType.building, 4, 'Progressive def_settlement_major', 'Def Building: Dark City'),
    20504: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_1', ItemType.building, 0, 'Progressive def_settlement_minor', 'Def Building: Black Spire'),
    20505: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_2', ItemType.building, 1, 'Progressive def_settlement_minor', 'Def Building: Dark Hold'),
    20506: ItemData(IC.useful, 1, 'wh2_main_def_settlement_minor_3', ItemType.building, 2, 'Progressive def_settlement_minor', 'Def Building: Dark Tower'),
    20507: ItemData(IC.useful, 1, 'wh2_main_def_slaves_1', ItemType.building, 0, 'Progressive def_slaves', 'Def Building: Slave Pens'),
    20508: ItemData(IC.useful, 1, 'wh2_main_def_slaves_2', ItemType.building, 1, 'Progressive def_slaves', 'Def Building: Slave Market'),
    20509: ItemData(IC.useful, 1, 'wh2_main_def_sorcery_1', ItemType.building, 0, 'Progressive def_sorcery', "Def Building: Sorceress' Abode"),
    20510: ItemData(IC.useful, 1, 'wh2_main_def_sorcery_2', ItemType.building, 1, 'Progressive def_sorcery', 'Def Building: Tower of Dark Sorcery'),
    20511: ItemData(IC.useful, 1, 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', 'Def Building: Altar of Khaine'),
    20512: ItemData(IC.useful, 1, 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', 'Def Building: Altar of Khaine'),
    20513: ItemData(IC.useful, 1, 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', 'Def Building: Altar of Khaine'),
    20514: ItemData(IC.useful, 1, 'wh2_main_def_worship_1', ItemType.building, 0, 'Progressive def_worship', 'Def Building: Altar of Khaine'),
    20515: ItemData(IC.useful, 1, 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', 'Def Building: Shrine of Khaine'),
    20516: ItemData(IC.useful, 1, 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', 'Def Building: Shrine of Khaine'),
    20517: ItemData(IC.useful, 1, 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', 'Def Building: Shrine of Khaine'),
    20518: ItemData(IC.useful, 1, 'wh2_main_def_worship_2', ItemType.building, 1, 'Progressive def_worship', 'Def Building: Shrine of Khaine'),
    20519: ItemData(IC.useful, 1, 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', 'Def Building: Temple of Khaine'),
    20520: ItemData(IC.useful, 1, 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', 'Def Building: Temple of Khaine'),
    20521: ItemData(IC.useful, 1, 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', 'Def Building: Temple of Khaine'),
    20522: ItemData(IC.useful, 1, 'wh2_main_def_worship_3', ItemType.building, 2, 'Progressive def_worship', 'Def Building: Temple of Khaine'),
    20523: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_def', 'Def Building: City Tunnels'),
    20524: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_def', 'Def Building: Guarded Tunnels'),
    20525: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_def_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_def', 'Def Building: Barricaded Tunnels'),
    20526: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_1', ItemType.building, 0, 'Progressive horde_def_beasts', 'Def Building: Harpy Cages'),
    20527: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_2', ItemType.building, 1, 'Progressive horde_def_beasts', 'Def Building: Monster Holds'),
    20528: ItemData(IC.useful, 1, 'wh2_main_horde_def_beasts_3', ItemType.building, 2, 'Progressive horde_def_beasts', 'Def Building: Dragon Tower'),
    20529: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_1', ItemType.building, 0, 'Progressive horde_def_bombardment_a', 'Def Building: Sacrificial Pit of Khaine'),
    20530: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_a_2', ItemType.building, 1, 'Progressive horde_def_bombardment_a', 'Def Building: Abbatoir of Khaine'),
    20531: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_1', ItemType.building, 0, 'Progressive horde_def_bombardment_b', 'Def Building: Soul Brazier'),
    20532: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_b_2', ItemType.building, 1, 'Progressive horde_def_bombardment_b', 'Def Building: Soul Furnance'),
    20533: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_1', ItemType.building, 0, 'Progressive horde_def_bombardment_c', 'Def Building: Brazen Cauldron'),
    20534: ItemData(IC.useful, 1, 'wh2_main_horde_def_bombardment_c_2', ItemType.building, 1, 'Progressive horde_def_bombardment_c', 'Def Building: Bloodwrack Cauldron'),
    20535: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_1', ItemType.building, 0, 'Progressive horde_def_entertainment', 'Def Building: Torture Posts'),
    20536: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_2', ItemType.building, 1, 'Progressive horde_def_entertainment', 'Def Building: Fighting Pits'),
    20537: ItemData(IC.useful, 1, 'wh2_main_horde_def_entertainment_3', ItemType.building, 2, 'Progressive horde_def_entertainment', 'Def Building: Arena'),
    20538: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_1', ItemType.building, 0, 'Progressive horde_def_military', 'Def Building: Corsair Cabins'),
    20539: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_2', ItemType.building, 1, 'Progressive horde_def_military', 'Def Building: Raider Lodges'),
    20540: ItemData(IC.useful, 1, 'wh2_main_horde_def_military_3', ItemType.building, 2, 'Progressive horde_def_military', 'Def Building: Warrior Hall'),
    20541: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_1', ItemType.building, 0, 'Progressive horde_def_settlement', 'Def Building: Small Black Ark'),
    20542: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_2', ItemType.building, 0, 'Progressive horde_def_settlement', 'Def Building: Black Ark'),
    20543: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_3', ItemType.building, 1, 'Progressive horde_def_settlement', 'Def Building: Grand Black Ark'),
    20544: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_4', ItemType.building, 2, 'Progressive horde_def_settlement', 'Def Building: Enormous Black Ark'),
    20545: ItemData(IC.useful, 1, 'wh2_main_horde_def_settlement_5', ItemType.building, 3, 'Progressive horde_def_settlement', 'Def Building: Gargantuan Black Ark'),
    20546: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_1', ItemType.building, 0, 'Progressive horde_def_slavery', 'Def Building: Slave Hold'),
    20547: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_2', ItemType.building, 1, 'Progressive horde_def_slavery', 'Def Building: Cell Decks'),
    20548: ItemData(IC.useful, 1, 'wh2_main_horde_def_slavery_3', ItemType.building, 2, 'Progressive horde_def_slavery', 'Def Building: Prison Wing'),
    20549: ItemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_1', ItemType.building, 0, 'Progressive horde_def_sorcery', 'Def Building: Sorceress Cabin'),
    20550: ItemData(IC.useful, 1, 'wh2_main_horde_def_sorcery_2', ItemType.building, 1, 'Progressive horde_def_sorcery', 'Def Building: Spire of Sorcery'),
    20551: ItemData(IC.useful, 1, 'wh2_main_horde_def_special_blessed_dread_1', ItemType.building, 0, 'Progressive horde_def_special_blessed_dread', 'Def Building: Helm of the Blessed Dread'),
    20552: ItemData(IC.useful, 1, 'wh2_main_horde_def_special_blessed_dread_2', ItemType.building, 1, 'Progressive horde_def_special_blessed_dread', 'Def Building: Tower of the Blessed Dread'),
    20553: ItemData(IC.useful, 1, 'wh2_main_horde_def_worship_1', ItemType.building, 0, 'Progressive horde_def_worship', 'Def Building: Altar of Khaine'),
    20554: ItemData(IC.useful, 1, 'wh2_main_horde_def_worship_2', ItemType.building, 1, 'Progressive horde_def_worship', 'Def Building: Shrine of Khaine'),
    20555: ItemData(IC.useful, 1, 'wh2_main_special_def_vauls_anvil', ItemType.building, 0, 'Progressive special_def_vauls', 'Def Building: Temple of Vaul'),
    20556: ItemData(IC.useful, 1, 'wh2_main_special_def_vauls_anvil_hef', ItemType.building, 0, 'Progressive special_def_vauls_anvil', 'Def Building: Temple of Vaul'),
    20557: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_def_1', ItemType.building, 0, 'Progressive special_hag_graef_mines_def', 'Def Building: Face of Hag Graef'),
    20558: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_def_2', ItemType.building, 1, 'Progressive special_hag_graef_mines_def', 'Def Building: Eye of Hag Graef'),
    20559: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_def_3', ItemType.building, 2, 'Progressive special_hag_graef_mines_def', 'Def Building: Mines of Hag Graef'),
    20560: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_def_4', ItemType.building, 3, 'Progressive special_hag_graef_mines_def', 'Def Building: The Dark Crag'),
    20561: ItemData(IC.useful, 1, 'wh2_main_special_salzenmund_laurelorn_def_1', ItemType.building, 0, 'Progressive special_salzenmund_laurelorn_def', 'Def Building: Laurelorn Forest'),
    20562: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_1', ItemType.building, 0, 'Progressive special_settlement_lothern_def', 'Def Building: Occupied Lothern (Black Spire)'),
    20563: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_2', ItemType.building, 1, 'Progressive special_settlement_lothern_def', 'Def Building: Occupied Lothern (Dark Hold)'),
    20564: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_3', ItemType.building, 2, 'Progressive special_settlement_lothern_def', 'Def Building: Occupied Lothern (Dark Tower)'),
    20565: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_4', ItemType.building, 3, 'Progressive special_settlement_lothern_def', 'Def Building: Occupied Lothern (Dark Citadel)'),
    20566: ItemData(IC.useful, 1, 'wh2_main_special_settlement_lothern_def_5', ItemType.building, 4, 'Progressive special_settlement_lothern_def', 'Def Building: Occupied Lothern (Dark City)'),
    20567: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_1', ItemType.building, 0, 'Progressive special_settlement_sartosa_def', 'Def Building: Occupied Sartosa Level 1'),
    20568: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_2', ItemType.building, 1, 'Progressive special_settlement_sartosa_def', 'Def Building: Occupied Sartosa Level 2'),
    20569: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_3', ItemType.building, 2, 'Progressive special_settlement_sartosa_def', 'Def Building: Occupied Sartosa Level 3'),
    20570: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_4', ItemType.building, 3, 'Progressive special_settlement_sartosa_def', 'Def Building: Occupied Sartosa Level 4'),
    20571: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_def_5', ItemType.building, 4, 'Progressive special_settlement_sartosa_def', 'Def Building: Occupied Sartosa Level 5'),
    20572: ItemData(IC.useful, 1, 'wh2_main_special_shrine_of_khaine_def_1', ItemType.building, 1, 'Progressive special_shrine_of_khaine_def', 'Def Building: Shrine of Widowmaker'),
    20573: ItemData(IC.useful, 1, 'wh2_main_special_shrine_of_khaine_def_base', ItemType.building, 0, 'Progressive special_shrine_of_khaine_def', 'Def Building: Abandoned Shrine of Widowmaker'),
    20574: ItemData(IC.useful, 1, 'wh3_dlc23_special_fortress_of_dawn_dawns_harbour_def_1', ItemType.building, 1, 'Progressive special_fortress_of_dawn_dawns_harbour_def', "Def Building: Dawn's Harbour"),
    20575: ItemData(IC.useful, 1, 'wh3_dlc23_special_fortress_of_dawn_dawns_harbour_def_2', ItemType.building, 2, 'Progressive special_fortress_of_dawn_dawns_harbour_def', "Def Building: Dawn's Harbour"),
    20576: ItemData(IC.useful, 1, 'wh3_dlc23_special_fortress_of_dawn_dawns_harbour_def_3', ItemType.building, 3, 'Progressive special_fortress_of_dawn_dawns_harbour_def', "Def Building: Dawn's Harbour"),
    20577: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_1', ItemType.building, 0, 'Progressive def_allied_outpost', 'Def Building: Dark Elf Outpost'),
    20578: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_2', ItemType.building, 1, 'Progressive def_allied_outpost', 'Def Building: Dark Elf District'),
    20579: ItemData(IC.useful, 1, 'wh3_main_def_allied_outpost_3', ItemType.building, 2, 'Progressive def_allied_outpost', 'Def Building: Dark Elf Colony'),
    20580: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_1', ItemType.building, 0, 'Progressive def_resource_ivory', 'Def Building: Animal Store'),
    20581: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_2', ItemType.building, 1, 'Progressive def_resource_ivory', 'Def Building: Tusk Market'),
    20582: ItemData(IC.useful, 1, 'wh3_main_def_resource_ivory_3', ItemType.building, 2, 'Progressive def_resource_ivory', 'Def Building: Tusk Compound'),
    20583: ItemData(IC.useful, 1, 'wh_twa03_special_albion_port_def_1', ItemType.building, 0, 'Progressive special_albion_port_def', 'Def Building: Forsaken Port of Nagronath'),
    20584: ItemData(IC.useful, 1, 'wh_twa03_special_albion_port_def_2', ItemType.building, 1, 'Progressive special_albion_port_def', 'Def Building: Restored Port of Nagronath')
}

techs: dict[int, ItemData] = {
    20800: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Marching to War'),
    20801: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Bolt Cartridges'),
    20802: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Black Iron Armour'),
    20803: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Bloodforged Platemail'),
    20804: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Driven by Vengeance'),
    20805: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Martial Society'),
    20806: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Forged to Kill'),
    20807: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Hit & Run'),
    20808: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: An Instrument of War'),
    20809: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Exotic Beast Hide Armour'),
    20810: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: No Signs of Weakness'),
    20811: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Ceremonial Weapons'),
    20812: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_1_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Ascension Through Battle'),
    20813: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_1_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Reworked Crossbows'),
    20814: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_1_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Walking in Darkness'),
    20815: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_1_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Serrated Blades'),
    20816: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Chartered Piracy'),
    20817: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Sadistic Handlers'),
    20818: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Recruit Convicts'),
    20819: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Bewitch Dragon Eggs'),
    20820: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_0_0', ItemType.tech, 0, 'Progressive tech_def', 'Def Tech: Choose or Die!'),
    20821: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Battle as Business'),
    20822: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Naval Training'),
    20823: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_0_0', ItemType.tech, 0, 'Progressive tech_def', 'Def Tech: Upgrade I'),
    20824: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Broken by the Lash'),
    20825: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Dominating the Beasts'),
    20826: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_0_0', ItemType.tech, 0, 'Progressive tech_def', 'Def Tech: Upgrade II'),
    20827: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Pressed into Servitude'),
    20828: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Hunt Outlaws'),
    20829: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_0_0', ItemType.tech, 0, 'Progressive tech_def', 'Def Tech: Upgrade III'),
    20830: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Under the Yoke'),
    20831: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Harnessed Fury'),
    20832: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_2_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Bloodthirsty Companions'),
    20833: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_2_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Daylight Denied'),
    20834: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_2_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Spoils of War'),
    20835: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_2_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Bred in Captivity'),
    20836: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Revel in Suffering'),
    20837: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Temple Training Grounds'),
    20838: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Hardship & Cruelty'),
    20839: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_1', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Deadly Accountability'),
    20840: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Founded on Tyranny'),
    20841: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Continuous Slave Supply'),
    20842: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Tempered in Blood'),
    20843: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Purge the Weak'),
    20844: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: Consumed by Rivalry'),
    20845: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Divide & Conquer'),
    20846: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_0', ItemType.tech, 1, 'Progressive tech_def', 'Def Tech: A Life of Dread'),
    20847: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_2', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Blood & Death'),
    20848: ItemData(IC.useful, 1, 'wh2_main_tech_def_0_3_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Exploit Feuds'),
    20849: ItemData(IC.useful, 1, 'wh2_main_tech_def_1_3_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Festivals of Khaine'),
    20850: ItemData(IC.useful, 1, 'wh2_main_tech_def_2_3_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Masters of Murder'),
    20851: ItemData(IC.useful, 1, 'wh2_main_tech_def_3_3_3', ItemType.tech, 2, 'Progressive tech_def', 'Def Tech: Study the Chaos Wastes')
}

progUnits: dict[int, ItemData] = {
    
}

progBuildings: dict[int, ItemData] = {
    21300: ItemData(IC.useful, 1, 'Progressive horde_def_aristocracy', ItemType.building, 1, None, 'Progressive Def Building: Horde Aristocracy'),
    21301: ItemData(IC.useful, 2, 'Progressive horde_def_aristocracy', ItemType.building, 2, None, 'Progressive Def Building: Horde Aristocracy'),
    21302: ItemData(IC.useful, 1, 'Progressive horde_def_exiles', ItemType.building, 1, None, 'Progressive Def Building: Horde Exiles'),
    21303: ItemData(IC.useful, 2, 'Progressive horde_def_exiles', ItemType.building, 2, None, 'Progressive Def Building: Horde Exiles'),
    21304: ItemData(IC.useful, 1, 'Progressive horde_def_residence', ItemType.building, 1, None, 'Progressive Def Building: Horde Residence'),
    21305: ItemData(IC.useful, 2, 'Progressive horde_def_residence', ItemType.building, 2, None, 'Progressive Def Building: Horde Residence'),
    21306: ItemData(IC.useful, 3, 'Progressive horde_def_residence', ItemType.building, 3, None, 'Progressive Def Building: Horde Residence'),
    21307: ItemData(IC.useful, 1, 'Progressive horde_def_riders', ItemType.building, 1, None, 'Progressive Def Building: Horde Riders'),
    21308: ItemData(IC.useful, 2, 'Progressive horde_def_riders', ItemType.building, 2, None, 'Progressive Def Building: Horde Riders'),
    21309: ItemData(IC.useful, 1, 'Progressive special_settlement_tor_yvresse_def', ItemType.building, 1, None, 'Progressive Def Building: Special Settlement Tor Yvresse Def'),
    21310: ItemData(IC.useful, 2, 'Progressive special_settlement_tor_yvresse_def', ItemType.building, 2, None, 'Progressive Def Building: Special Settlement Tor Yvresse Def'),
    21311: ItemData(IC.useful, 3, 'Progressive special_settlement_tor_yvresse_def', ItemType.building, 3, None, 'Progressive Def Building: Special Settlement Tor Yvresse Def'),
    21312: ItemData(IC.useful, 4, 'Progressive special_settlement_tor_yvresse_def', ItemType.building, 4, None, 'Progressive Def Building: Special Settlement Tor Yvresse Def'),
    21313: ItemData(IC.useful, 5, 'Progressive special_settlement_tor_yvresse_def', ItemType.building, 5, None, 'Progressive Def Building: Special Settlement Tor Yvresse Def'),
    21314: ItemData(IC.useful, 1, 'Progressive def_barracks', ItemType.building, 1, None, 'Progressive Def Building: Barracks'),
    21315: ItemData(IC.useful, 2, 'Progressive def_barracks', ItemType.building, 2, None, 'Progressive Def Building: Barracks'),
    21316: ItemData(IC.useful, 3, 'Progressive def_barracks', ItemType.building, 3, None, 'Progressive Def Building: Barracks'),
    21317: ItemData(IC.useful, 1, 'Progressive def_beasts', ItemType.building, 1, None, 'Progressive Def Building: Beasts'),
    21318: ItemData(IC.useful, 2, 'Progressive def_beasts', ItemType.building, 2, None, 'Progressive Def Building: Beasts'),
    21319: ItemData(IC.useful, 3, 'Progressive def_beasts', ItemType.building, 3, None, 'Progressive Def Building: Beasts'),
    21320: ItemData(IC.useful, 1, 'Progressive def_coldones', ItemType.building, 1, None, 'Progressive Def Building: Coldones'),
    21321: ItemData(IC.useful, 2, 'Progressive def_coldones', ItemType.building, 2, None, 'Progressive Def Building: Coldones'),
    21322: ItemData(IC.useful, 1, 'Progressive def_defence_major', ItemType.building, 1, None, 'Progressive Def Building: Defence Major'),
    21323: ItemData(IC.useful, 2, 'Progressive def_defence_major', ItemType.building, 2, None, 'Progressive Def Building: Defence Major'),
    21324: ItemData(IC.useful, 3, 'Progressive def_defence_major', ItemType.building, 3, None, 'Progressive Def Building: Defence Major'),
    21325: ItemData(IC.useful, 1, 'Progressive def_defence_minor', ItemType.building, 1, None, 'Progressive Def Building: Defence Minor'),
    21326: ItemData(IC.useful, 2, 'Progressive def_defence_minor', ItemType.building, 2, None, 'Progressive Def Building: Defence Minor'),
    21327: ItemData(IC.useful, 1, 'Progressive def_defence_norsca', ItemType.building, 1, None, 'Progressive Def Building: Defence Norsca'),
    21328: ItemData(IC.useful, 1, 'Progressive def_exiles', ItemType.building, 1, None, 'Progressive Def Building: Exiles'),
    21329: ItemData(IC.useful, 2, 'Progressive def_exiles', ItemType.building, 2, None, 'Progressive Def Building: Exiles'),
    21330: ItemData(IC.useful, 1, 'Progressive def_farm', ItemType.building, 1, None, 'Progressive Def Building: Farm'),
    21331: ItemData(IC.useful, 2, 'Progressive def_farm', ItemType.building, 2, None, 'Progressive Def Building: Farm'),
    21332: ItemData(IC.useful, 3, 'Progressive def_farm', ItemType.building, 3, None, 'Progressive Def Building: Farm'),
    21333: ItemData(IC.useful, 1, 'Progressive def_industry', ItemType.building, 1, None, 'Progressive Def Building: Industry'),
    21334: ItemData(IC.useful, 2, 'Progressive def_industry', ItemType.building, 2, None, 'Progressive Def Building: Industry'),
    21335: ItemData(IC.useful, 3, 'Progressive def_industry', ItemType.building, 3, None, 'Progressive Def Building: Industry'),
    21336: ItemData(IC.useful, 1, 'Progressive def_order', ItemType.building, 1, None, 'Progressive Def Building: Order'),
    21337: ItemData(IC.useful, 2, 'Progressive def_order', ItemType.building, 2, None, 'Progressive Def Building: Order'),
    21338: ItemData(IC.useful, 3, 'Progressive def_order', ItemType.building, 3, None, 'Progressive Def Building: Order'),
    21339: ItemData(IC.useful, 1, 'Progressive def_port', ItemType.building, 1, None, 'Progressive Def Building: Port'),
    21340: ItemData(IC.useful, 2, 'Progressive def_port', ItemType.building, 2, None, 'Progressive Def Building: Port'),
    21341: ItemData(IC.useful, 3, 'Progressive def_port', ItemType.building, 3, None, 'Progressive Def Building: Port'),
    21342: ItemData(IC.useful, 1, 'Progressive def_resource_animals', ItemType.building, 1, None, 'Progressive Def Building: Animals'),
    21343: ItemData(IC.useful, 2, 'Progressive def_resource_animals', ItemType.building, 2, None, 'Progressive Def Building: Animals'),
    21344: ItemData(IC.useful, 3, 'Progressive def_resource_animals', ItemType.building, 3, None, 'Progressive Def Building: Animals'),
    21345: ItemData(IC.useful, 1, 'Progressive def_resource_dyes', ItemType.building, 1, None, 'Progressive Def Building: Dyes'),
    21346: ItemData(IC.useful, 2, 'Progressive def_resource_dyes', ItemType.building, 2, None, 'Progressive Def Building: Dyes'),
    21347: ItemData(IC.useful, 3, 'Progressive def_resource_dyes', ItemType.building, 3, None, 'Progressive Def Building: Dyes'),
    21348: ItemData(IC.useful, 1, 'Progressive def_resource_furs', ItemType.building, 1, None, 'Progressive Def Building: Furs'),
    21349: ItemData(IC.useful, 2, 'Progressive def_resource_furs', ItemType.building, 2, None, 'Progressive Def Building: Furs'),
    21350: ItemData(IC.useful, 3, 'Progressive def_resource_furs', ItemType.building, 3, None, 'Progressive Def Building: Furs'),
    21351: ItemData(IC.useful, 1, 'Progressive def_resource_gems', ItemType.building, 1, None, 'Progressive Def Building: Gems'),
    21352: ItemData(IC.useful, 2, 'Progressive def_resource_gems', ItemType.building, 2, None, 'Progressive Def Building: Gems'),
    21353: ItemData(IC.useful, 3, 'Progressive def_resource_gems', ItemType.building, 3, None, 'Progressive Def Building: Gems'),
    21354: ItemData(IC.useful, 1, 'Progressive def_resource_gold', ItemType.building, 1, None, 'Progressive Def Building: Gold'),
    21355: ItemData(IC.useful, 2, 'Progressive def_resource_gold', ItemType.building, 2, None, 'Progressive Def Building: Gold'),
    21356: ItemData(IC.useful, 3, 'Progressive def_resource_gold', ItemType.building, 3, None, 'Progressive Def Building: Gold'),
    21357: ItemData(IC.useful, 1, 'Progressive def_resource_iron', ItemType.building, 1, None, 'Progressive Def Building: Iron'),
    21358: ItemData(IC.useful, 2, 'Progressive def_resource_iron', ItemType.building, 2, None, 'Progressive Def Building: Iron'),
    21359: ItemData(IC.useful, 3, 'Progressive def_resource_iron', ItemType.building, 3, None, 'Progressive Def Building: Iron'),
    21360: ItemData(IC.useful, 1, 'Progressive def_resource_marble', ItemType.building, 1, None, 'Progressive Def Building: Marble'),
    21361: ItemData(IC.useful, 2, 'Progressive def_resource_marble', ItemType.building, 2, None, 'Progressive Def Building: Marble'),
    21362: ItemData(IC.useful, 3, 'Progressive def_resource_marble', ItemType.building, 3, None, 'Progressive Def Building: Marble'),
    21363: ItemData(IC.useful, 1, 'Progressive def_resource_medicine', ItemType.building, 1, None, 'Progressive Def Building: Medicine'),
    21364: ItemData(IC.useful, 2, 'Progressive def_resource_medicine', ItemType.building, 2, None, 'Progressive Def Building: Medicine'),
    21365: ItemData(IC.useful, 3, 'Progressive def_resource_medicine', ItemType.building, 3, None, 'Progressive Def Building: Medicine'),
    21366: ItemData(IC.useful, 1, 'Progressive def_resource_obsidian', ItemType.building, 1, None, 'Progressive Def Building: Obsidian'),
    21367: ItemData(IC.useful, 2, 'Progressive def_resource_obsidian', ItemType.building, 2, None, 'Progressive Def Building: Obsidian'),
    21368: ItemData(IC.useful, 3, 'Progressive def_resource_obsidian', ItemType.building, 3, None, 'Progressive Def Building: Obsidian'),
    21369: ItemData(IC.useful, 1, 'Progressive def_resource_pasture', ItemType.building, 1, None, 'Progressive Def Building: Pasture'),
    21370: ItemData(IC.useful, 2, 'Progressive def_resource_pasture', ItemType.building, 2, None, 'Progressive Def Building: Pasture'),
    21371: ItemData(IC.useful, 3, 'Progressive def_resource_pasture', ItemType.building, 3, None, 'Progressive Def Building: Pasture'),
    21372: ItemData(IC.useful, 1, 'Progressive def_resource_pottery', ItemType.building, 1, None, 'Progressive Def Building: Pottery'),
    21373: ItemData(IC.useful, 2, 'Progressive def_resource_pottery', ItemType.building, 2, None, 'Progressive Def Building: Pottery'),
    21374: ItemData(IC.useful, 3, 'Progressive def_resource_pottery', ItemType.building, 3, None, 'Progressive Def Building: Pottery'),
    21375: ItemData(IC.useful, 1, 'Progressive def_resource_salt', ItemType.building, 1, None, 'Progressive Def Building: Salt'),
    21376: ItemData(IC.useful, 2, 'Progressive def_resource_salt', ItemType.building, 2, None, 'Progressive Def Building: Salt'),
    21377: ItemData(IC.useful, 3, 'Progressive def_resource_salt', ItemType.building, 3, None, 'Progressive Def Building: Salt'),
    21378: ItemData(IC.useful, 1, 'Progressive def_resource_spices', ItemType.building, 1, None, 'Progressive Def Building: Spices'),
    21379: ItemData(IC.useful, 2, 'Progressive def_resource_spices', ItemType.building, 2, None, 'Progressive Def Building: Spices'),
    21380: ItemData(IC.useful, 3, 'Progressive def_resource_spices', ItemType.building, 3, None, 'Progressive Def Building: Spices'),
    21381: ItemData(IC.useful, 1, 'Progressive def_resource_wine', ItemType.building, 1, None, 'Progressive Def Building: Wine'),
    21382: ItemData(IC.useful, 2, 'Progressive def_resource_wine', ItemType.building, 2, None, 'Progressive Def Building: Wine'),
    21383: ItemData(IC.useful, 3, 'Progressive def_resource_wine', ItemType.building, 3, None, 'Progressive Def Building: Wine'),
    21384: ItemData(IC.useful, 1, 'Progressive def_resource_wood', ItemType.building, 1, None, 'Progressive Def Building: Wood'),
    21385: ItemData(IC.useful, 2, 'Progressive def_resource_wood', ItemType.building, 2, None, 'Progressive Def Building: Wood'),
    21386: ItemData(IC.useful, 3, 'Progressive def_resource_wood', ItemType.building, 3, None, 'Progressive Def Building: Wood'),
    21387: ItemData(IC.useful, 1, 'Progressive def_riders', ItemType.building, 1, None, 'Progressive Def Building: Riders'),
    21388: ItemData(IC.useful, 2, 'Progressive def_riders', ItemType.building, 2, None, 'Progressive Def Building: Riders'),
    21389: ItemData(IC.useful, 1, 'Progressive def_roads', ItemType.building, 1, None, 'Progressive Def Building: Roads'),
    21390: ItemData(IC.useful, 1, 'Progressive def_settlement_major', ItemType.building, 1, None, 'Progressive Def Building: Settlement Major'),
    21391: ItemData(IC.useful, 2, 'Progressive def_settlement_major', ItemType.building, 2, None, 'Progressive Def Building: Settlement Major'),
    21392: ItemData(IC.useful, 3, 'Progressive def_settlement_major', ItemType.building, 3, None, 'Progressive Def Building: Settlement Major'),
    21393: ItemData(IC.useful, 4, 'Progressive def_settlement_major', ItemType.building, 4, None, 'Progressive Def Building: Settlement Major'),
    21394: ItemData(IC.useful, 5, 'Progressive def_settlement_major', ItemType.building, 5, None, 'Progressive Def Building: Settlement Major'),
    21395: ItemData(IC.useful, 1, 'Progressive def_settlement_minor', ItemType.building, 1, None, 'Progressive Def Building: Settlement Minor'),
    21396: ItemData(IC.useful, 2, 'Progressive def_settlement_minor', ItemType.building, 2, None, 'Progressive Def Building: Settlement Minor'),
    21397: ItemData(IC.useful, 3, 'Progressive def_settlement_minor', ItemType.building, 3, None, 'Progressive Def Building: Settlement Minor'),
    21398: ItemData(IC.useful, 1, 'Progressive def_slaves', ItemType.building, 1, None, 'Progressive Def Building: Slaves'),
    21399: ItemData(IC.useful, 2, 'Progressive def_slaves', ItemType.building, 2, None, 'Progressive Def Building: Slaves'),
    21400: ItemData(IC.useful, 1, 'Progressive def_sorcery', ItemType.building, 1, None, 'Progressive Def Building: Sorcery'),
    21401: ItemData(IC.useful, 2, 'Progressive def_sorcery', ItemType.building, 2, None, 'Progressive Def Building: Sorcery'),
    21402: ItemData(IC.useful, 1, 'Progressive def_worship', ItemType.building, 1, None, 'Progressive Def Building: Worship'),
    21403: ItemData(IC.useful, 2, 'Progressive def_worship', ItemType.building, 2, None, 'Progressive Def Building: Worship'),
    21404: ItemData(IC.useful, 3, 'Progressive def_worship', ItemType.building, 3, None, 'Progressive Def Building: Worship'),
    21405: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_def', ItemType.building, 1, None, 'Progressive Def Building: Foreign Slot Discovery Def'),
    21406: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_def', ItemType.building, 2, None, 'Progressive Def Building: Foreign Slot Discovery Def'),
    21407: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_def', ItemType.building, 3, None, 'Progressive Def Building: Foreign Slot Discovery Def'),
    21408: ItemData(IC.useful, 1, 'Progressive horde_def_beasts', ItemType.building, 1, None, 'Progressive Def Building: Horde Beasts'),
    21409: ItemData(IC.useful, 2, 'Progressive horde_def_beasts', ItemType.building, 2, None, 'Progressive Def Building: Horde Beasts'),
    21410: ItemData(IC.useful, 3, 'Progressive horde_def_beasts', ItemType.building, 3, None, 'Progressive Def Building: Horde Beasts'),
    21411: ItemData(IC.useful, 1, 'Progressive horde_def_bombardment_a', ItemType.building, 1, None, 'Progressive Def Building: Horde Bombardment A'),
    21412: ItemData(IC.useful, 2, 'Progressive horde_def_bombardment_a', ItemType.building, 2, None, 'Progressive Def Building: Horde Bombardment A'),
    21413: ItemData(IC.useful, 1, 'Progressive horde_def_bombardment_b', ItemType.building, 1, None, 'Progressive Def Building: Horde Bombardment B'),
    21414: ItemData(IC.useful, 2, 'Progressive horde_def_bombardment_b', ItemType.building, 2, None, 'Progressive Def Building: Horde Bombardment B'),
    21415: ItemData(IC.useful, 1, 'Progressive horde_def_bombardment_c', ItemType.building, 1, None, 'Progressive Def Building: Horde Bombardment C'),
    21416: ItemData(IC.useful, 2, 'Progressive horde_def_bombardment_c', ItemType.building, 2, None, 'Progressive Def Building: Horde Bombardment C'),
    21417: ItemData(IC.useful, 1, 'Progressive horde_def_entertainment', ItemType.building, 1, None, 'Progressive Def Building: Horde Entertainment'),
    21418: ItemData(IC.useful, 2, 'Progressive horde_def_entertainment', ItemType.building, 2, None, 'Progressive Def Building: Horde Entertainment'),
    21419: ItemData(IC.useful, 3, 'Progressive horde_def_entertainment', ItemType.building, 3, None, 'Progressive Def Building: Horde Entertainment'),
    21420: ItemData(IC.useful, 1, 'Progressive horde_def_military', ItemType.building, 1, None, 'Progressive Def Building: Horde Military'),
    21421: ItemData(IC.useful, 2, 'Progressive horde_def_military', ItemType.building, 2, None, 'Progressive Def Building: Horde Military'),
    21422: ItemData(IC.useful, 3, 'Progressive horde_def_military', ItemType.building, 3, None, 'Progressive Def Building: Horde Military'),
    21423: ItemData(IC.useful, 1, 'Progressive horde_def_settlement', ItemType.building, 1, None, 'Progressive Def Building: Horde Settlement'),
    21424: ItemData(IC.useful, 1, 'Progressive horde_def_settlement', ItemType.building, 1, None, 'Progressive Def Building: Horde Settlement'),
    21425: ItemData(IC.useful, 2, 'Progressive horde_def_settlement', ItemType.building, 2, None, 'Progressive Def Building: Horde Settlement'),
    21426: ItemData(IC.useful, 3, 'Progressive horde_def_settlement', ItemType.building, 3, None, 'Progressive Def Building: Horde Settlement'),
    21427: ItemData(IC.useful, 4, 'Progressive horde_def_settlement', ItemType.building, 4, None, 'Progressive Def Building: Horde Settlement'),
    21428: ItemData(IC.useful, 1, 'Progressive horde_def_slavery', ItemType.building, 1, None, 'Progressive Def Building: Horde Slavery'),
    21429: ItemData(IC.useful, 2, 'Progressive horde_def_slavery', ItemType.building, 2, None, 'Progressive Def Building: Horde Slavery'),
    21430: ItemData(IC.useful, 3, 'Progressive horde_def_slavery', ItemType.building, 3, None, 'Progressive Def Building: Horde Slavery'),
    21431: ItemData(IC.useful, 1, 'Progressive horde_def_sorcery', ItemType.building, 1, None, 'Progressive Def Building: Horde Sorcery'),
    21432: ItemData(IC.useful, 2, 'Progressive horde_def_sorcery', ItemType.building, 2, None, 'Progressive Def Building: Horde Sorcery'),
    21433: ItemData(IC.useful, 1, 'Progressive horde_def_special_blessed_dread', ItemType.building, 1, None, 'Progressive Def Building: Horde Special Blessed Dread'),
    21434: ItemData(IC.useful, 2, 'Progressive horde_def_special_blessed_dread', ItemType.building, 2, None, 'Progressive Def Building: Horde Special Blessed Dread'),
    21435: ItemData(IC.useful, 1, 'Progressive horde_def_worship', ItemType.building, 1, None, 'Progressive Def Building: Horde Worship'),
    21436: ItemData(IC.useful, 2, 'Progressive horde_def_worship', ItemType.building, 2, None, 'Progressive Def Building: Horde Worship'),
    21437: ItemData(IC.useful, 1, 'Progressive special_def_vauls', ItemType.building, 1, None, 'Progressive Def Building: Special Vauls'),
    21438: ItemData(IC.useful, 1, 'Progressive special_def_vauls_anvil', ItemType.building, 1, None, 'Progressive Def Building: Special Vauls Anvil'),
    21439: ItemData(IC.useful, 1, 'Progressive special_hag_graef_mines_def', ItemType.building, 1, None, 'Progressive Def Building: Special Hag Graef Mines Def'),
    21440: ItemData(IC.useful, 2, 'Progressive special_hag_graef_mines_def', ItemType.building, 2, None, 'Progressive Def Building: Special Hag Graef Mines Def'),
    21441: ItemData(IC.useful, 3, 'Progressive special_hag_graef_mines_def', ItemType.building, 3, None, 'Progressive Def Building: Special Hag Graef Mines Def'),
    21442: ItemData(IC.useful, 4, 'Progressive special_hag_graef_mines_def', ItemType.building, 4, None, 'Progressive Def Building: Special Hag Graef Mines Def'),
    21443: ItemData(IC.useful, 1, 'Progressive special_salzenmund_laurelorn_def', ItemType.building, 1, None, 'Progressive Def Building: Special Salzenmund Laurelorn Def'),
    21444: ItemData(IC.useful, 1, 'Progressive special_settlement_lothern_def', ItemType.building, 1, None, 'Progressive Def Building: Special Settlement Lothern Def'),
    21445: ItemData(IC.useful, 2, 'Progressive special_settlement_lothern_def', ItemType.building, 2, None, 'Progressive Def Building: Special Settlement Lothern Def'),
    21446: ItemData(IC.useful, 3, 'Progressive special_settlement_lothern_def', ItemType.building, 3, None, 'Progressive Def Building: Special Settlement Lothern Def'),
    21447: ItemData(IC.useful, 4, 'Progressive special_settlement_lothern_def', ItemType.building, 4, None, 'Progressive Def Building: Special Settlement Lothern Def'),
    21448: ItemData(IC.useful, 5, 'Progressive special_settlement_lothern_def', ItemType.building, 5, None, 'Progressive Def Building: Special Settlement Lothern Def'),
    21449: ItemData(IC.useful, 1, 'Progressive special_settlement_sartosa_def', ItemType.building, 1, None, 'Progressive Def Building: Special Settlement Sartosa Def'),
    21450: ItemData(IC.useful, 2, 'Progressive special_settlement_sartosa_def', ItemType.building, 2, None, 'Progressive Def Building: Special Settlement Sartosa Def'),
    21451: ItemData(IC.useful, 3, 'Progressive special_settlement_sartosa_def', ItemType.building, 3, None, 'Progressive Def Building: Special Settlement Sartosa Def'),
    21452: ItemData(IC.useful, 4, 'Progressive special_settlement_sartosa_def', ItemType.building, 4, None, 'Progressive Def Building: Special Settlement Sartosa Def'),
    21453: ItemData(IC.useful, 5, 'Progressive special_settlement_sartosa_def', ItemType.building, 5, None, 'Progressive Def Building: Special Settlement Sartosa Def'),
    21454: ItemData(IC.useful, 2, 'Progressive special_shrine_of_khaine_def', ItemType.building, 2, None, 'Progressive Def Building: Special Shrine Of Khaine Def'),
    21455: ItemData(IC.useful, 1, 'Progressive special_shrine_of_khaine_def', ItemType.building, 1, None, 'Progressive Def Building: Special Shrine Of Khaine Def'),
    21456: ItemData(IC.useful, 2, 'Progressive special_fortress_of_dawn_dawns_harbour_def', ItemType.building, 2, None, 'Progressive Def Building: Special Fortress Of Dawn Dawns Harbour Def'),
    21457: ItemData(IC.useful, 3, 'Progressive special_fortress_of_dawn_dawns_harbour_def', ItemType.building, 3, None, 'Progressive Def Building: Special Fortress Of Dawn Dawns Harbour Def'),
    21458: ItemData(IC.useful, 4, 'Progressive special_fortress_of_dawn_dawns_harbour_def', ItemType.building, 4, None, 'Progressive Def Building: Special Fortress Of Dawn Dawns Harbour Def'),
    21459: ItemData(IC.useful, 1, 'Progressive def_allied_outpost', ItemType.building, 1, None, 'Progressive Def Building: Allied Outpost'),
    21460: ItemData(IC.useful, 2, 'Progressive def_allied_outpost', ItemType.building, 2, None, 'Progressive Def Building: Allied Outpost'),
    21461: ItemData(IC.useful, 3, 'Progressive def_allied_outpost', ItemType.building, 3, None, 'Progressive Def Building: Allied Outpost'),
    21462: ItemData(IC.useful, 1, 'Progressive def_resource_ivory', ItemType.building, 1, None, 'Progressive Def Building: Ivory'),
    21463: ItemData(IC.useful, 2, 'Progressive def_resource_ivory', ItemType.building, 2, None, 'Progressive Def Building: Ivory'),
    21464: ItemData(IC.useful, 3, 'Progressive def_resource_ivory', ItemType.building, 3, None, 'Progressive Def Building: Ivory'),
    21465: ItemData(IC.useful, 1, 'Progressive special_albion_port_def', ItemType.building, 1, None, 'Progressive Def Building: Special Albion Port Def'),
    21466: ItemData(IC.useful, 2, 'Progressive special_albion_port_def', ItemType.building, 2, None, 'Progressive Def Building: Special Albion Port Def')
}

progTechs: dict[int, ItemData] = {
    21500: ItemData(IC.useful, 15, "Progressive tech_def", ItemType.tech, 15, None, "Progressive Def Tech"),
}

special: dict[int, ItemData] = {

}

