from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    22000: ItemData(IC.useful, 1, 'wh_main_dwf_inf_miners_0', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Miners'),
    22001: ItemData(IC.useful, 1, 'wh_main_dwf_inf_miners_1', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Miners (Blasting Charges)'),
    22002: ItemData(IC.useful, 1, 'wh_main_dwf_inf_dwarf_warrior_0', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Dwarf Warriors'),
    22003: ItemData(IC.useful, 1, 'wh_main_dwf_inf_dwarf_warrior_1', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Dwarf Warriors (Great Weapons)'),
    22004: ItemData(IC.useful, 1, 'wh_main_dwf_inf_longbeards', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Longbeards'),
    22005: ItemData(IC.useful, 1, 'wh_main_dwf_inf_longbeards_1', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Longbeards (Great Weapons)'),
    22006: ItemData(IC.useful, 1, 'wh_main_dwf_inf_slayers', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Slayers'),
    22007: ItemData(IC.useful, 1, 'wh_main_dwf_inf_hammerers', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Hammerers'),
    22008: ItemData(IC.useful, 1, 'wh_main_dwf_inf_ironbreakers', ItemType.unit, 3, 'Progressive dwf_inf', 'Dwf Unit: Ironbreakers'),
    22009: ItemData(IC.useful, 1, 'wh2_dlc10_dwf_inf_giant_slayers', ItemType.unit, 3, 'Progressive dwf_inf', 'Dwf Unit: Giant Slayers'),
    22010: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_doomseekers', ItemType.unit, 3, 'Progressive dwf_inf', 'Dwf Unit: Doomseekers'),
    22011: ItemData(IC.useful, 1, 'wh_main_dwf_inf_quarrellers_0', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Quarrellers'),
    22012: ItemData(IC.useful, 1, 'wh_main_dwf_inf_quarrellers_1', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Quarrellers (Great Weapons)'),
    22013: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_rangers_0', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Rangers'),
    22014: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_rangers_1', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Rangers (Great Weapons)'),
    22015: ItemData(IC.useful, 1, 'wh_main_dwf_inf_thunderers_0', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Thunderers'),
    22016: ItemData(IC.useful, 1, 'wh_main_dwf_inf_irondrakes_0', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Irondrakes'),
    22017: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_bugmans_rangers_0', ItemType.unit, 2, 'Progressive dwf_rng', "Dwf Unit: Bugman's Rangers"),
    22018: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_thunderers_grudge_rakers', ItemType.unit, 2, 'Progressive dwf_rng', 'Dwf Unit: Thunderers (Grudge-Rakers)'),
    22019: ItemData(IC.useful, 1, 'wh_main_dwf_inf_irondrakes_2', ItemType.unit, 2, 'Progressive dwf_rng', 'Dwf Unit: Irondrakes (Trollhammer Torpedoes)'),
    22020: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_slayer_pirates', ItemType.unit, 2, 'Progressive dwf_rng', 'Dwf Unit: Slayer Pirates'),
    22021: ItemData(IC.useful, 1, 'wh_dlc06_dwf_art_bolt_thrower_0', ItemType.unit, 1, 'Progressive dwf_art', 'Dwf Unit: Bolt Throwers'),
    22022: ItemData(IC.useful, 1, 'wh_main_dwf_art_grudge_thrower', ItemType.unit, 1, 'Progressive dwf_art', 'Dwf Unit: Grudge Throwers'),
    22023: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_art_goblin_hewer', ItemType.unit, 2, 'Progressive dwf_art', 'Dwf Unit: Goblin Hewers'),
    22024: ItemData(IC.useful, 1, 'wh_main_dwf_art_cannon', ItemType.unit, 2, 'Progressive dwf_art', 'Dwf Unit: Cannons'),
    22025: ItemData(IC.useful, 1, 'wh_main_dwf_art_organ_gun', ItemType.unit, 3, 'Progressive dwf_art', 'Dwf Unit: Organ Guns'),
    22026: ItemData(IC.useful, 1, 'wh_main_dwf_art_flame_cannon', ItemType.unit, 3, 'Progressive dwf_art', 'Dwf Unit: Flame Cannons'),
    22027: ItemData(IC.useful, 1, 'wh_main_dwf_cha_thane', ItemType.unit, 1, 'Progressive dwf_hro', 'Dwf Unit: Thane'),
    22028: ItemData(IC.useful, 1, 'wh_main_dwf_cha_rune_smith_0', ItemType.unit, 1, 'Progressive dwf_hro', 'Dwf Unit: Runesmith'),
    22029: ItemData(IC.useful, 1, 'wh_main_dwf_cha_master_engineer_0', ItemType.unit, 1, 'Progressive dwf_hro', 'Dwf Unit: Master Engineer'),
    22030: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_cha_dragon_slayer', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Dragon Slayer'),
    22031: ItemData(IC.useful, 1, 'wh_main_dwf_veh_gyrocopter_0', ItemType.unit, 1, 'Progressive dwf_veh', 'Dwf Unit: Gyrocopters'),
    22032: ItemData(IC.useful, 1, 'wh_main_dwf_veh_gyrocopter_1', ItemType.unit, 2, 'Progressive dwf_veh', 'Dwf Unit: Gyrocopters (Brimstone Guns)'),
    22033: ItemData(IC.useful, 1, 'wh_main_dwf_veh_gyrobomber', ItemType.unit, 3, 'Progressive dwf_veh', 'Dwf Unit: Gyrobombers'),
    22034: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_veh_thunderbarge', ItemType.unit, 4, 'progressive dwf_veh', 'Dwf Unit: Thunderbarge'),
    22035: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_hammerers_grudge_unit', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Hammerers (Grudge Settlers)'),
    22036: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_slayers_grudge_unit', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Slayers (Grudge Settlers)'),
    22037: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_longbeards_1_grudge_unit', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Longbeards (Great Weapons - Grudge Settlers)'),
    22038: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_irondrakes_0_grudge_unit', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Irondrakes (Grudge Settlers)'),
    22039: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_quarrellers_1_grudge_unit', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: Quarrellers (Great Weapons - Grudge Settlers)'),
    22040: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_veh_gyrocopter_1_grudge_unit', ItemType.unit, 2, 'Progressive dwf_veh', 'Dwf Unit: Gyrocopters (Trollhammers - Grudge Settlers'),
    22041: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_art_flame_cannon_grudge_unit', ItemType.unit, 3, 'Progressive dwf_art', 'Dwf Unit: Flame Cannons (Grudge Settlers)'),
    22042: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_art_grudge_thrower_grudge_unit', ItemType.unit, 1, 'Progressive dwf_art', 'Dwf Unit: Grudge Throwers (Grudge Settlers)'),
    22043: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_ekrund_miners_0', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Ekrund Miners (Miners - Blasting Charges)'),
    22044: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_warriors_dragonfire_pass_0', ItemType.unit, 1, 'Progressive dwf_inf', 'Dwf Unit: Warriors of Dragonfire Pass (Dwarf Warriors)'),
    22045: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_slayer_pirates_ror', ItemType.unit, 2, 'Progressive dwf_rng', "Dwf Unit: Long Drong's Slayer Pirates"),
    22046: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_thunderers_ror', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: The Grimdelvers (Thunderers)'),
    22047: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_dragonback_slayers_0', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Dragonback Slayers (Slayers)'),
    22048: ItemData(IC.useful, 1, 'wh_dlc06_dwf_art_gob_lobber_0', ItemType.unit, 1, 'Progressive dwf_art', 'Dwf Unit: Gob-Lobbers (Grudge Throwers)'),
    22049: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_inf_doomseekers_ror', ItemType.unit, 3, 'Progressive dwf_inf', 'Dwf Unit: The Brotherhood of Grimnir (Doomseekers)'),
    22050: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_old_grumblers_0', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: The Grumbling Guard (Longbeards - Great Weapons)'),
    22051: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_peak_gate_guard_0', ItemType.unit, 2, 'Progressive dwf_inf', 'Dwf Unit: Peak Gate Guard (Hammerers)'),
    22052: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_ulthars_raiders_0', ItemType.unit, 1, 'Progressive dwf_rng', "Dwf Unit: Ulthar's Raiders (Rangers - Great Weapons)"),
    22053: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_norgrimlings_ironbreakers_0', ItemType.unit, 3, 'Progressive dwf_inf', 'Dwf Unit: Norgrimlings Ironbreakers (Ironbreakers)'),
    22054: ItemData(IC.useful, 1, 'wh_dlc06_dwf_inf_norgrimlings_irondrakes_0', ItemType.unit, 1, 'Progressive dwf_rng', 'Dwf Unit: The Skolder Guard (Irondrakes)'),
    22055: ItemData(IC.useful, 1, 'wh_dlc06_dwf_veh_skyhammer_0', ItemType.unit, 3, 'Progressive dwf_veh', 'Dwf Unit: Skyhammer Squadron (Gyrobombers)')
}

buildings: dict[int, ItemData] = {
    22401: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_animals_1', ItemType.building, 0, 'Progressive dwf_resource_animals', 'Dwf Building: Exotic Animal Tamer'),
    22402: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_animals_2', ItemType.building, 1, 'Progressive dwf_resource_animals', 'Dwf Building: Exotic Animal Pen'),
    22403: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_animals_3', ItemType.building, 2, 'Progressive dwf_resource_animals', 'Dwf Building: Exotic Animal Market'),
    22404: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_animals_4', ItemType.building, 3, 'Progressive dwf_resource_animals', "Dwf Building: Animal Trainers' Guild Hall"),
    22405: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_medicine_1', ItemType.building, 0, 'Progressive dwf_resource_medicine', "Dwf Building: Herb Gatherer's Camp"),
    22406: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_medicine_2', ItemType.building, 1, 'Progressive dwf_resource_medicine', 'Dwf Building: Exotic Hothouse'),
    22407: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_medicine_3', ItemType.building, 2, 'Progressive dwf_resource_medicine', "Dwf Building: Alchemist's Workshop"),
    22408: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_medicine_4', ItemType.building, 3, 'Progressive dwf_resource_medicine', "Dwf Building: Alchemists' Guild Hall"),
    22409: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_obsidian_1', ItemType.building, 0, 'Progressive dwf_resource_obsidian', 'Dwf Building: Obsidian Quarry'),
    22410: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_obsidian_2', ItemType.building, 1, 'Progressive dwf_resource_obsidian', 'Dwf Building: Obsidian Trinket Maker'),
    22411: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_obsidian_3', ItemType.building, 2, 'Progressive dwf_resource_obsidian', 'Dwf Building: Obsidian Sculptor'),
    22412: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_obsidian_4', ItemType.building, 3, 'Progressive dwf_resource_obsidian', "Dwf Building: Obsidian Sculptors' Guild Hall"),
    22413: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_pottery_1', ItemType.building, 0, 'Progressive dwf_resource_pottery', 'Dwf Building: Clay Pit'),
    22414: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_pottery_2', ItemType.building, 1, 'Progressive dwf_resource_pottery', 'Dwf Building: Pottery Maker'),
    22415: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_pottery_3', ItemType.building, 2, 'Progressive dwf_resource_pottery', 'Dwf Building: Kilns'),
    22416: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_pottery_4', ItemType.building, 3, 'Progressive dwf_resource_pottery', "Dwf Building: Glaziers' Guild Hall"),
    22417: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_spices_1', ItemType.building, 0, 'Progressive dwf_resource_spices', 'Dwf Building: Spice Market'),
    22418: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_spices_2', ItemType.building, 1, 'Progressive dwf_resource_spices', 'Dwf Building: Spice Trading Post'),
    22419: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_spices_3', ItemType.building, 2, 'Progressive dwf_resource_spices', 'Dwf Building: Eastern Bazaar'),
    22420: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_spices_4', ItemType.building, 3, 'Progressive dwf_resource_spices', "Dwf Building: Caravan Masters' Guild Hall"),
    22421: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_wine_1', ItemType.building, 0, 'Progressive dwf_resource_wine', 'Dwf Building: Orchards'),
    22422: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_wine_2', ItemType.building, 1, 'Progressive dwf_resource_wine', 'Dwf Building: Vineyard'),
    22423: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_wine_3', ItemType.building, 2, 'Progressive dwf_resource_wine', 'Dwf Building: Distillery'),
    22424: ItemData(IC.useful, 1, 'wh2_main_dwf_resource_wine_4', ItemType.building, 3, 'Progressive dwf_resource_wine', "Dwf Building: Distillers' Guild Hall"),
    22425: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_dwf_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_dwf', 'Dwf Building: Underway Lookouts'),
    22426: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_dwf_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_dwf', 'Dwf Building: Lookout Posts'),
    22427: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_dwf_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_dwf', 'Dwf Building: Lookout Camps'),
    22430: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_ranger_hub_2_all', ItemType.building, 1, 'Progressive dwf_ranger_hub_2', 'Dwf Building: Ranger Barracks'),
    22432: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_trade_depot_3', ItemType.building, 2, 'Progressive dwf_trade_depot', 'Dwf Building: Guild Marketplace'),
    22433: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_trade_depot_4', ItemType.building, 3, 'Progressive dwf_trade_depot', 'Dwf Building: Guild Market District'),
    22434: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_trade_depot_5', ItemType.building, 4, 'Progressive dwf_trade_depot', "Dwf Building: Traders' Guild Hall"),
    22435: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_1', ItemType.building, 0, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Forge'),
    22436: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_1', ItemType.building, 0, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Forge'),
    22437: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_1', ItemType.building, 0, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Forge'),
    22438: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_1', ItemType.building, 0, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Forge'),
    22439: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_2', ItemType.building, 1, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Foundry'),
    22440: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_2', ItemType.building, 1, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Foundry'),
    22441: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_2', ItemType.building, 1, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Foundry'),
    22442: ItemData(IC.useful, 1, 'wh3_dlc25_dwf_workshop_infantry_2', ItemType.building, 1, 'Progressive dwf_workshop_infantry', 'Dwf Building: Arms Foundry'),
    22445: ItemData(IC.useful, 1, 'wh3_main_dwf_allied_outpost_1', ItemType.building, 0, 'Progressive dwf_allied_outpost', 'Dwf Building: Dwarf Outpost'),
    22446: ItemData(IC.useful, 1, 'wh3_main_dwf_allied_outpost_2', ItemType.building, 1, 'Progressive dwf_allied_outpost', 'Dwf Building: Dwarf District'),
    22447: ItemData(IC.useful, 1, 'wh3_main_dwf_allied_outpost_3', ItemType.building, 2, 'Progressive dwf_allied_outpost', 'Dwf Building: Dwarf Colony'),
    22448: ItemData(IC.useful, 1, 'wh3_main_dwf_resource_ivory_1', ItemType.building, 0, 'Progressive dwf_resource_ivory', 'Dwf Building: Animal Store'),
    22449: ItemData(IC.useful, 1, 'wh3_main_dwf_resource_ivory_2', ItemType.building, 1, 'Progressive dwf_resource_ivory', 'Dwf Building: Tusk Market'),
    22450: ItemData(IC.useful, 1, 'wh3_main_dwf_resource_ivory_3', ItemType.building, 2, 'Progressive dwf_resource_ivory', 'Dwf Building: Tusk Compound'),
    22451: ItemData(IC.useful, 1, 'wh3_main_dwf_resource_ivory_4', ItemType.building, 3, 'Progressive dwf_resource_ivory', 'Dwf Building: Tusk Guild Hall'),
    #22452: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Blocked Tunnels'),
    #22453: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_beer_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Dwarf Beer Stash'),
    #22454: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_doomsphere_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Old Doomsphere'),
    #22455: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_gold_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Gold Vein'),
    #22456: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_lab_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Abandoned Laboratory'),
    #22457: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_machines_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Broken War Machines'),
    #22458: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_skaven_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Skaven Burrow'),
    #22459: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_blocker_warpstone_1', ItemType.building, 0, 'Progressive underdeep_dwf_blocker', 'Dwf Deep Building: Warpstone Cache'),
    22460: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_defence_hold_1', ItemType.building, 0, 'Progressive underdeep_dwf_defence_hold', 'Dwf Deep Building: Seal the Hold!'),
    22461: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_defence_slayers_1', ItemType.building, 0, 'Progressive underdeep_dwf_defence_slayers', 'Dwf Deep Building: To the Last Dawi!'),
    22462: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_counting_room_1', ItemType.building, 0, 'Progressive underdeep_dwf_economy_counting_room', 'Dwf Deep Building: Ruined Counting Room'),
    22463: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_counting_room_2_a', ItemType.building, 1, 'Progressive underdeep_dwf_economy_counting_room', 'Dwf Deep Building: Repurposed Counting Room'),
    22464: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_counting_room_2', ItemType.building, 1, 'Progressive underdeep_dwf_economy_counting_room', 'Dwf Deep Building: Counting Room'),
    22465: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_counting_room_3', ItemType.building, 2, 'Progressive underdeep_dwf_economy_counting_room', 'Dwf Deep Building: Ornate Counting Room'),
    22466: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_drinking_1', ItemType.building, 0, 'Progressive underdeep_dwf_economy_drinking', 'Dwf Deep Building: Ruined Drinking Halls'),
    22467: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_drinking_2', ItemType.building, 1, 'Progressive underdeep_dwf_economy_drinking', 'Dwf Deep Building: Drinking Halls'),
    22468: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_oathgold_1', ItemType.building, 0, 'Progressive underdeep_dwf_economy_oathgold', 'Dwf Deep Building: Ruined Clan Goldsmiths'),
    22469: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_oathgold_2_a', ItemType.building, 1, 'Progressive underdeep_dwf_economy_oathgold', 'Dwf Deep Building: Repurposed Clan Goldsmiths'),
    22470: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_oathgold_2', ItemType.building, 1, 'Progressive underdeep_dwf_economy_oathgold', 'Dwf Deep Building: Clan Goldsmiths'),
    22471: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_oathgold_3', ItemType.building, 2, 'Progressive underdeep_dwf_economy_oathgold', 'Dwf Deep Building: Ornate Clan Goldsmiths'),
    22472: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_economy_trade_1', ItemType.building, 0, 'Progressive underdeep_dwf_economy_trade', 'Dwf Deep Building: Underdeep Trade Routes'),
    22473: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_grudges_1', ItemType.building, 0, 'Progressive underdeep_dwf_grudges', 'Dwf Deep Building: Hall of Remembering'),
    22474: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_grudges_2_a', ItemType.building, 1, 'Progressive underdeep_dwf_grudges', 'Dwf Deep Building: Hall of Remembering (Sealed)'),
    22475: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_grudges_2', ItemType.building, 1, 'Progressive underdeep_dwf_grudges', 'Dwf Deep Building: Hall of Remembering (Decorated)'),
    22476: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_grudges_3', ItemType.building, 2, 'Progressive underdeep_dwf_grudges', 'Dwf Deep Building: Hall of Remembering (Ornate)'),
    22477: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_deeper_1', ItemType.building, 0, 'Progressive underdeep_dwf_main_deeper', 'Dwf Deep Building: Unstable Magma Caverns'),
    22478: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_deeper_2', ItemType.building, 1, 'Progressive underdeep_dwf_main_deeper', 'Dwf Deep Building: Magma Caverns'),
    22479: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_karak_eight_peaks_1', ItemType.building, 0, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Ruined Entrance Halls'),
    22480: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_karak_eight_peaks_2', ItemType.building, 1, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Entrance Halls'),
    22481: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_karak_eight_peaks_3', ItemType.building, 2, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Grand Entrance Halls'),
    22482: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_major_1', ItemType.building, 0, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Ruined Entrance Halls'),
    22483: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_major_2', ItemType.building, 1, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Entrance Halls'),
    22484: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_major_3', ItemType.building, 2, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Grand Entrance Halls'),
    22485: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_minor_1', ItemType.building, 0, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Ruined Entrance Halls'),
    22486: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_minor_2', ItemType.building, 1, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Entrance Halls'),
    22487: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_minor_3', ItemType.building, 2, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Grand Entrance Halls'),
    22488: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_skavenblight_1', ItemType.building, 0, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Ruined Entrance Halls'),
    22489: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_skavenblight_2', ItemType.building, 1, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Entrance Halls'),
    22490: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_skavenblight_3', ItemType.building, 2, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Grand Entrance Halls'),
    22491: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_zharr_naggrund_1', ItemType.building, 0, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Ruined Entrance Halls'),
    22492: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_zharr_naggrund_2', ItemType.building, 1, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Entrance Halls'),
    22493: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_main_zharr_naggrund_3', ItemType.building, 2, 'Progressive underdeep_dwf_main', 'Dwf Deep Building: Grand Entrance Halls'),
    22494: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_resources_1', ItemType.building, 0, 'Progressive underdeep_dwf_resources', 'Dwf Deep Building: Underdeep Mine'),
    22495: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_tall_1', ItemType.building, 0, 'Progressive underdeep_dwf_tall', 'Dwf Deep Building: Ruined Guild Foundries'),
    22496: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_tall_2_a', ItemType.building, 1, 'Progressive underdeep_dwf_tall', 'Dwf Deep Building: Repurposed Guild Foundries'),
    22497: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_tall_2', ItemType.building, 1, 'Progressive underdeep_dwf_tall', 'Dwf Deep Building: Guild Foundries'),
    22498: ItemData(IC.useful, 1, 'wh3_main_underdeep_dwf_tall_3', ItemType.building, 2, 'Progressive underdeep_dwf_tall', 'Dwf Deep Building: Ornate Guild Foundries'),
    22499: ItemData(IC.useful, 1, 'wh_dlc06_dwf_ranger_hub_1_all', ItemType.building, 0, 'Progressive dwf_ranger_hub_1', 'Dwf Building: Ranger Outpost'),
    22500: ItemData(IC.useful, 1, 'wh_dlc06_dwf_ranger_hub_1_all', ItemType.building, 0, 'Progressive dwf_ranger_hub_1', 'Dwf Building: Ranger Barracks'),
    22501: ItemData(IC.useful, 1, 'wh_dlc25_dwf_engineer_4', ItemType.building, 3, 'Progressive dwf_engineer', "Dwf Building: Guild Masters' Council"),
    22502: ItemData(IC.useful, 1, 'wh_dlc25_dwf_engineer_4', ItemType.building, 3, 'Progressive dwf_engineer', "Dwf Building: Guild Masters' Council"),
    22503: ItemData(IC.useful, 1, 'wh_dlc25_dwf_engineer_4', ItemType.building, 3, 'Progressive dwf_engineer', "Dwf Building: Guild Masters' Council"),
    22504: ItemData(IC.useful, 1, 'wh_dlc25_dwf_engineer_4', ItemType.building, 3, 'Progressive dwf_engineer', "Dwf Building: Guild Masters' Council"),
    22505: ItemData(IC.useful, 1, 'wh_main_dwf_barracks_1', ItemType.building, 0, 'Progressive dwf_barracks', 'Dwf Building: Sparring Chamber'),
    22506: ItemData(IC.useful, 1, 'wh_main_dwf_barracks_2', ItemType.building, 1, 'Progressive dwf_barracks', 'Dwf Building: Clan Barracks'),
    22507: ItemData(IC.useful, 1, 'wh_main_dwf_barracks_3', ItemType.building, 2, 'Progressive dwf_barracks', 'Dwf Building: Mustering Hall'),
    22508: ItemData(IC.useful, 1, 'wh_main_dwf_barracks_4', ItemType.building, 0, 'Progressive dwf_barracks', 'Dwf Building: Hall of Oaths'),
    22509: ItemData(IC.useful, 1, 'wh_main_dwf_engineer_1', ItemType.building, 0, 'Progressive dwf_engineer', "Dwf Building: Tinker's Den"),
    22510: ItemData(IC.useful, 1, 'wh_main_dwf_engineer_2', ItemType.building, 1, 'Progressive dwf_engineer', "Dwf Building: Engineer's Workshop"),
    22511: ItemData(IC.useful, 1, 'wh_main_dwf_engineer_3', ItemType.building, 2, 'Progressive dwf_engineer', "Dwf Building: Engineers' Guild Hall"),
    22512: ItemData(IC.useful, 1, 'wh_main_dwf_farm_1', ItemType.building, 0, 'Progressive dwf_farm', 'Dwf Building: Barley Field'),
    22513: ItemData(IC.useful, 1, 'wh_main_dwf_farm_2', ItemType.building, 1, 'Progressive dwf_farm', 'Dwf Building: Granary'),
    22514: ItemData(IC.useful, 1, 'wh_main_dwf_farm_3', ItemType.building, 2, 'Progressive dwf_farm', 'Dwf Building: Stone Bread Bakery'),
    22515: ItemData(IC.useful, 1, 'wh_main_dwf_farm_4', ItemType.building, 1, 'Progressive dwf_farm', "Dwf Building: Bakers' Guild Hall"),
    22516: ItemData(IC.useful, 1, 'wh_main_dwf_garrison_1', ItemType.building, 0, 'Progressive dwf_garrison', 'Dwf Building: Watch Room'),
    22517: ItemData(IC.useful, 1, 'wh_main_dwf_garrison_2', ItemType.building, 1, 'Progressive dwf_garrison', 'Dwf Building: Guard Hall'),
    22518: ItemData(IC.useful, 1, 'wh_main_dwf_industry_1', ItemType.building, 0, 'Progressive dwf_industry', 'Dwf Building: Trinket Maker'),
    22519: ItemData(IC.useful, 1, 'wh_main_dwf_industry_2', ItemType.building, 1, 'Progressive dwf_industry', "Dwf Building: Dwarf Tinkerer's Shop"),
    22520: ItemData(IC.useful, 1, 'wh_main_dwf_industry_3', ItemType.building, 2, 'Progressive dwf_industry', "Dwf Building: Toolmaker's Workshop"),
    22521: ItemData(IC.useful, 1, 'wh_main_dwf_industry_4', ItemType.building, 3, 'Progressive dwf_industry', "Dwf Building: Toolmakers' Foundry"),
    22522: ItemData(IC.useful, 1, 'wh_main_dwf_industry_5', ItemType.building, 4, 'Progressive dwf_industry', "Dwf Building: Toolmakers' Guild Hall"),
    22523: ItemData(IC.useful, 1, 'wh_main_dwf_port_1', ItemType.building, 0, 'Progressive dwf_port', 'Dwf Building: Dwarf Wharf'),
    22524: ItemData(IC.useful, 1, 'wh_main_dwf_port_2', ItemType.building, 1, 'Progressive dwf_port', 'Dwf Building: Dwarf Docks'),
    22525: ItemData(IC.useful, 1, 'wh_main_dwf_port_3', ItemType.building, 2, 'Progressive dwf_port', 'Dwf Building: Dwarf Shipyard'),
    22526: ItemData(IC.useful, 1, 'wh_main_dwf_resource_beer_1', ItemType.building, 0, 'Progressive dwf_resource_beer', 'Dwf Building: Ale Store'),
    22527: ItemData(IC.useful, 1, 'wh_main_dwf_resource_beer_2', ItemType.building, 1, 'Progressive dwf_resource_beer', 'Dwf Building: Dwarf Brewery'),
    22528: ItemData(IC.useful, 1, 'wh_main_dwf_resource_beer_3', ItemType.building, 2, 'Progressive dwf_resource_beer', 'Dwf Building: Renowned Brewery'),
    22529: ItemData(IC.useful, 1, 'wh_main_dwf_resource_beer_4', ItemType.building, 3, 'Progressive dwf_resource_beer', "Dwf Building: Brewmaster's Kettles"),
    22530: ItemData(IC.useful, 1, 'wh_main_dwf_resource_dyes_1', ItemType.building, 0, 'Progressive dwf_resource_dyes', 'Dwf Building: Cinnabar Mining Pit'),
    22531: ItemData(IC.useful, 1, 'wh_main_dwf_resource_dyes_2', ItemType.building, 1, 'Progressive dwf_resource_dyes', 'Dwf Building: Cinnabar Mine'),
    22532: ItemData(IC.useful, 1, 'wh_main_dwf_resource_dyes_3', ItemType.building, 2, 'Progressive dwf_resource_dyes', "Dwf Building: Dye-Makers' Plant"),
    22533: ItemData(IC.useful, 1, 'wh_main_dwf_resource_dyes_4', ItemType.building, 3, 'Progressive dwf_resource_dyes', "Dwf Building: Dyers' Guild Hall"),
    22534: ItemData(IC.useful, 1, 'wh_main_dwf_resource_game_1', ItemType.building, 0, 'Progressive dwf_resource_game', 'Dwf Building: Hunting Lodge'),
    22535: ItemData(IC.useful, 1, 'wh_main_dwf_resource_game_2', ItemType.building, 1, 'Progressive dwf_resource_game', 'Dwf Building: Hunting Camp'),
    22536: ItemData(IC.useful, 1, 'wh_main_dwf_resource_game_3', ItemType.building, 2, 'Progressive dwf_resource_game', 'Dwf Building: Tannery'),
    22537: ItemData(IC.useful, 1, 'wh_main_dwf_resource_game_4', ItemType.building, 3, 'Progressive dwf_resource_game', "Dwf Building: Leatherworkers' Guild Hall"),
    22538: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gems_1', ItemType.building, 0, 'Progressive dwf_resource_gems', 'Dwf Building: Gem Mineshaft'),
    22539: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gems_2', ItemType.building, 1, 'Progressive dwf_resource_gems', 'Dwf Building: Gem Mine'),
    22540: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gems_3', ItemType.building, 2, 'Progressive dwf_resource_gems', "Dwf Building: Gemcutter's Workshop"),
    22541: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gems_4', ItemType.building, 3, 'Progressive dwf_resource_gems', "Dwf Building: Gemcutters' Guild Hall"),
    22542: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gold_1', ItemType.building, 0, 'Progressive dwf_resource_gold', 'Dwf Building: Gold Mining Pit'),
    22543: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gold_2', ItemType.building, 1, 'Progressive dwf_resource_gold', 'Dwf Building: Gold Mine'),
    22544: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gold_3', ItemType.building, 2, 'Progressive dwf_resource_gold', 'Dwf Building: Gold Smelter'),
    22545: ItemData(IC.useful, 1, 'wh_main_dwf_resource_gold_4', ItemType.building, 3, 'Progressive dwf_resource_gold', "Dwf Building: Goldsmiths' Guild Hall"),
    22546: ItemData(IC.useful, 1, 'wh_main_dwf_resource_iron_1', ItemType.building, 0, 'Progressive dwf_resource_iron', 'Dwf Building: Iron Mining Pit'),
    22547: ItemData(IC.useful, 1, 'wh_main_dwf_resource_iron_2', ItemType.building, 1, 'Progressive dwf_resource_iron', 'Dwf Building: Iron Mines'),
    22548: ItemData(IC.useful, 1, 'wh_main_dwf_resource_iron_3', ItemType.building, 2, 'Progressive dwf_resource_iron', 'Dwf Building: Iron Smelter'),
    22549: ItemData(IC.useful, 1, 'wh_main_dwf_resource_iron_4', ItemType.building, 3, 'Progressive dwf_resource_iron', "Dwf Building: Iron Miners' Guild Hall"),
    22551: ItemData(IC.useful, 1, 'wh_main_dwf_resource_marble_1', ItemType.building, 0, 'Progressive dwf_resource_marble', "Dwf Building: Stonecutter's Shop"),
    22552: ItemData(IC.useful, 1, 'wh_main_dwf_resource_marble_2', ItemType.building, 1, 'Progressive dwf_resource_marble', 'Dwf Building: Marble Quarry'),
    22553: ItemData(IC.useful, 1, 'wh_main_dwf_resource_marble_3', ItemType.building, 2, 'Progressive dwf_resource_marble', 'Dwf Building: Mason'),
    22554: ItemData(IC.useful, 1, 'wh_main_dwf_resource_marble_4', ItemType.building, 3, 'Progressive dwf_resource_marble', "Dwf Building: Masons' Guild Hall"),
    22555: ItemData(IC.useful, 1, 'wh_main_dwf_resource_pastures_1', ItemType.building, 0, 'Progressive dwf_resource_pastures', 'Dwf Building: Goat Pastures'),
    22556: ItemData(IC.useful, 1, 'wh_main_dwf_resource_pastures_2', ItemType.building, 1, 'Progressive dwf_resource_pastures', 'Dwf Building: Goat Herd'),
    22557: ItemData(IC.useful, 1, 'wh_main_dwf_resource_pastures_3', ItemType.building, 2, 'Progressive dwf_resource_pastures', 'Dwf Building: Goat Farm'),
    22558: ItemData(IC.useful, 1, 'wh_main_dwf_resource_pastures_4', ItemType.building, 3, 'Progressive dwf_resource_pastures', "Dwf Building: Herders' Guild Hall"),
    22559: ItemData(IC.useful, 1, 'wh_main_dwf_resource_salt_1', ItemType.building, 0, 'Progressive dwf_resource_salt', 'Dwf Building: Brine Mining Pit'),
    22560: ItemData(IC.useful, 1, 'wh_main_dwf_resource_salt_2', ItemType.building, 1, 'Progressive dwf_resource_salt', 'Dwf Building: Brine Mine'),
    22561: ItemData(IC.useful, 1, 'wh_main_dwf_resource_salt_3', ItemType.building, 2, 'Progressive dwf_resource_salt', 'Dwf Building: Saltworks'),
    22562: ItemData(IC.useful, 1, 'wh_main_dwf_resource_salt_4', ItemType.building, 3, 'Progressive dwf_resource_salt', "Dwf Building: Saltworkers' Guild Hall"),
    22564: ItemData(IC.useful, 1, 'wh_main_dwf_resource_timber_1', ItemType.building, 0, 'Progressive dwf_resource_timber', "Dwf Building: Woodman's Hut"),
    22565: ItemData(IC.useful, 1, 'wh_main_dwf_resource_timber_2', ItemType.building, 1, 'Progressive dwf_resource_timber', 'Dwf Building: Timber Mill'),
    22566: ItemData(IC.useful, 1, 'wh_main_dwf_resource_timber_3', ItemType.building, 2, 'Progressive dwf_resource_timber', 'Dwf Building: Lumberyard'),
    22567: ItemData(IC.useful, 1, 'wh_main_dwf_resource_timber_4', ItemType.building, 3, 'Progressive dwf_resource_timber', "Dwf Building: Carpenters' Guild Hall"),
    22568: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_major_1', ItemType.building, 0, 'Progressive dwf_settlement_major', 'Dwf Building: Dwarf Mining Colony'),
    22569: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_major_2', ItemType.building, 1, 'Progressive dwf_settlement_major', 'Dwf Building: Dwarf Outpost'),
    22570: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_major_3', ItemType.building, 2, 'Progressive dwf_settlement_major', 'Dwf Building: Dwarf Keep'),
    22571: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_major_4', ItemType.building, 3, 'Progressive dwf_settlement_major', 'Dwf Building: Dwarfhold'),
    22572: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_major_5', ItemType.building, 4, 'Progressive dwf_settlement_major', 'Dwf Building: Great Hold'),
    22573: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_minor_1', ItemType.building, 0, 'Progressive dwf_settlement_minor', 'Dwf Building: Dwarf Mining Colony'),
    22574: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_minor_2', ItemType.building, 1, 'Progressive dwf_settlement_minor', 'Dwf Building: Dwarf Outpost'),
    22575: ItemData(IC.useful, 1, 'wh_main_dwf_settlement_minor_3', ItemType.building, 2, 'Progressive dwf_settlement_minor', 'Dwf Building: Dwarf Keep'),
    22576: ItemData(IC.useful, 1, 'wh_main_dwf_slayer_1', ItemType.building, 0, 'Progressive dwf_slayer', 'Dwf Building: Slayer Shrine'),
    22577: ItemData(IC.useful, 1, 'wh_main_dwf_slayer_2', ItemType.building, 1, 'Progressive dwf_slayer', 'Dwf Building: Monument of Grimnir'),
    22578: ItemData(IC.useful, 1, 'wh_main_dwf_smith_1', ItemType.building, 0, 'Progressive dwf_smith', 'Dwf Building: Armoury'),
    22579: ItemData(IC.useful, 1, 'wh_main_dwf_smith_2', ItemType.building, 1, 'Progressive dwf_smith', 'Dwf Building: Gromril Forge'),
    22580: ItemData(IC.useful, 1, 'wh_main_dwf_smith_3', ItemType.building, 2, 'Progressive dwf_smith', 'Dwf Building: Runeforge'),
    22581: ItemData(IC.useful, 1, 'wh_main_dwf_smith_4', ItemType.building, 3, 'Progressive dwf_smith', 'Dwf Building: Runelordsâ€™ Hall'),
    22582: ItemData(IC.useful, 1, 'wh_main_dwf_tavern_1', ItemType.building, 0, 'Progressive dwf_tavern', 'Dwf Building: Refectory'),
    22583: ItemData(IC.useful, 1, 'wh_main_dwf_tavern_2', ItemType.building, 1, 'Progressive dwf_tavern', 'Dwf Building: Drinking Hall'),
    22584: ItemData(IC.useful, 1, 'wh_main_dwf_tavern_3', ItemType.building, 2, 'Progressive dwf_tavern', 'Dwf Building: Feast Hall'),
    22585: ItemData(IC.useful, 1, 'wh_main_dwf_trade_depot_1', ItemType.building, 0, 'Progressive dwf_trade_depot', 'Dwf Building: Trading Depot'),
    22586: ItemData(IC.useful, 1, 'wh_main_dwf_trade_depot_2', ItemType.building, 1, 'Progressive dwf_trade_depot', 'Dwf Building: Trading Warehouse'),
    22587: ItemData(IC.useful, 1, 'wh_main_dwf_wall_1', ItemType.building, 0, 'Progressive dwf_wall', 'Dwf Building: Gate'),
    22588: ItemData(IC.useful, 1, 'wh_main_dwf_wall_2', ItemType.building, 1, 'Progressive dwf_wall', 'Dwf Building: Reinforced Gate'),
    22589: ItemData(IC.useful, 1, 'wh_main_dwf_wall_3', ItemType.building, 2, 'Progressive dwf_wall', 'Dwf Building: Runic Gate'),
    22590: ItemData(IC.useful, 1, 'wh_main_dwf_workshop_1', ItemType.building, 0, 'Progressive dwf_workshop', 'Dwf Building: Siege Workshop'),
    22591: ItemData(IC.useful, 1, 'wh_main_dwf_workshop_2', ItemType.building, 1, 'Progressive dwf_workshop', "Dwf Building: Gunsmith's Forge"),
    22592: ItemData(IC.useful, 1, 'wh_main_dwf_workshop_3', ItemType.building, 2, 'Progressive dwf_workshop', 'Dwf Building: Foundry'),
    22593: ItemData(IC.useful, 1, 'wh_main_dwf_workshop_4', ItemType.building, 3, 'Progressive dwf_workshop', 'Dwf Building: Hangar')
}

techs: dict[int, ItemData] = {
    22800: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_0_2', ItemType.tech, 1, 'Progressive tech_dwf_guilds', 'Dwf Tech: The Way of the Guilds'),
    22801: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_3_1', ItemType.tech, 2, 'Progressive tech_dwf_guilds', 'Dwf Tech: Heavy Quernstones'),
    22802: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_1_1', ItemType.tech, 3, 'Progressive tech_dwf_guilds', 'Dwf Tech: Khazid Subsidies'),
    22803: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_1_0', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Dwarf Treasuries'),
    22804: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_4_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', "Dwf Tech: High King's Authority"),
    22805: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_7_4', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Rat Poison'),
    22806: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_3_0', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Storage Vaults'),
    22807: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_6_0', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Dwarfen Grims'),
    22808: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_7_0', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Halls of Great Guilds'),
    22809: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_4_2', ItemType.tech, 3, 'Progressive tech_dwf_guilds', "Dwf Tech: The King's Share"),
    22810: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_2_0', ItemType.tech, 4, 'Progressive tech_dwf_guilds', "Dwf Tech: Toolmakers' Guild"),
    22811: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_5_2', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Construction Duty'),
    22812: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_7_1', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Deep Resource Extraction'),
    22813: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_4_1', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Gromril Picks'),
    22814: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_2_1', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Tool Market'),
    22815: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_6_1', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Water-Proof Packaging'),
    22816: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_3_2', ItemType.tech, 3, 'Progressive tech_dwf_guilds', 'Dwf Tech: Underway Trade Caravans'),
    22817: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_2_3', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Scrutinise Guild Leaders'),
    22818: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_2_2', ItemType.tech, 5, 'Progressive tech_dwf_guilds', "Dwf Tech: Thane's Authority"),
    22819: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_6_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', "Dwf Tech: Valaya's Protection"),
    22820: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_3_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Oaths of Loyalty'),
    22821: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_3_3', ItemType.tech, 4, 'Progressive tech_dwf_guilds', 'Dwf Tech: Autonomy of the Holds'),
    22822: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_7_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Operations Training'),
    22823: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_5_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Sealstones'),
    22824: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_1_3', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Include Related Families'),
    22825: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_7_2', ItemType.tech, 4, 'Progressive tech_dwf_guilds', "Dwf Tech: Grungni's Blessing"),
    22826: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_6_2', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Construction Guilds'),
    22827: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_2_4', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Dwarfen Emissaries'),
    22828: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_6_3', ItemType.tech, 5, 'Progressive tech_dwf_guilds', 'Dwf Tech: Grand Throne Chamber'),
    22829: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_5_1', ItemType.tech, 1, 'Progressive tech_dwf_clans', 'Dwf Tech: Marching Songs'),
    22830: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_1_1', ItemType.tech, 2, 'Progressive tech_dwf_clans', 'Dwf Tech: Gather the Throngs'),
    22831: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_1_0', ItemType.tech, 3, 'Progressive tech_dwf_clans', 'Dwf Tech: Militia Training'),
    22832: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_4_0', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Improved Blast Charges'),
    22833: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_2_0', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Call to Clan'),
    22834: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_6_0', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Iron Readiness'),
    22835: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_3_1', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Interlocking Shields'),
    22836: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_7_1', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Sacred Duty'),
    22837: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_4_0', ItemType.tech, 5, 'Progressive tech_dwf_clans', "Dwf Tech: Veterans' Pride"),
    22838: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_7_0', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Iron Veterans'),
    22839: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_4_5', ItemType.tech, 3, 'Progressive tech_dwf_clans', 'Dwf Tech: Vanguard Proficiency'),
    22840: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_1_4', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Masterwork Crossbows'),
    22841: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_3_4', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Superior Black Powder'),
    22842: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_2_4', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Renowned Deadeyes'),
    22843: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_9_3', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Pressure-Regulating Valves'),
    22844: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_6_1', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Iron Price'),
    22845: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_6_4', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Assembly Lines'),
    22846: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_4_4', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Volatile Volley'),
    22847: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_1_3', ItemType.tech, 3, 'Progressive tech_dwf_clans', "Dwf Tech: Warrior's Guild"),
    22848: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_5_2', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Rune-Bearing Relics'),
    22849: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_8_1', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Recite Ancient Grudges'),
    22850: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_8_0', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Royal Guard'),
    22851: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_6_2', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Master-Crafted Armour'),
    22852: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_5_0', ItemType.tech, 7, 'Progressive tech_dwf_clans', 'Dwf Tech: Tales of Many Wars'),
    22853: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_9_1', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: The Slayer Oath'),
    22854: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_9_2', ItemType.tech, 6, 'Progressive tech_dwf_clans', "Dwf Tech: Grimnir's Favour"),
    22855: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_9_0', ItemType.tech, 7, 'Progressive tech_dwf_clans', "Dwf Tech: Slayer's Onslaught"),
    22856: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_3_2', ItemType.tech, 4, 'Progressive tech_dwf_clans', "Dwf Tech: Retainers' Vows"),
    22857: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_4_2', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Master-Crafted Weapons'),
    22858: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_5_4', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Large Scale Shell Production'),
    22859: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_6_3', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Field Engineers'),
    22860: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_7_3', ItemType.tech, 7, 'Progressive tech_dwf_clans', 'Dwf Tech: Artillery Entrenchment'),
    22861: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_8_3', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Heavy Armour Plating'),
    22862: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_5_3', ItemType.tech, 6, 'Progressive tech_dwf_clans', 'Dwf Tech: Interchangeable Parts'),
    22863: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_8_4', ItemType.tech, 7, 'Progressive tech_dwf_clans', 'Dwf Tech: Improved Gyrocopter Engines'),
    22864: ItemData(IC.useful, 1, 'wh_main_tech_dwf_civ_5_3', ItemType.tech, 4, 'Progressive tech_dwf_clans', 'Dwf Tech: Ancestral Tombs'),
    22865: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_0_2', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: The Way of the Clans'),
    22866: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_2_2', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Oath Stones'),
    22867: ItemData(IC.useful, 1, 'wh_main_tech_dwf_mil_4_1', ItemType.tech, 5, 'Progressive tech_dwf_clans', 'Dwf Tech: Call Upon Oaths of Old')
}

progUnits: dict[int, ItemData] = {
    23200: ItemData(IC.useful, 3, "Progressive dwf_inf", ItemType.unit, 3, "", "Progressive Dwf Unit: Infantry"),
    23201: ItemData(IC.useful, 2, "Progressive dwf_rng", ItemType.unit, 2, "", "Progressive Dwf Unit: Ranged"),
    23203: ItemData(IC.useful, 3, "Progressive dwf_art", ItemType.unit, 3, "", "Progressive Dwf Unit: Artillery"),
    23204: ItemData(IC.useful, 4, "Progressive dwf_veh", ItemType.unit, 4, "", "Progressive Dwf Unit: War Machine"),
    23206: ItemData(IC.useful, 2, "Progressive dwf_hro", ItemType.unit, 2, "", "Progressive Dwf Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    23300: ItemData(IC.useful, 4, 'Progressive dwf_resource_animals', ItemType.building, 4, None, 'Progressive Dwf Building: Animals'),
    23301: ItemData(IC.useful, 4, 'Progressive dwf_resource_medicine', ItemType.building, 4, None, 'Progressive Dwf Building: Medicine'),
    23302: ItemData(IC.useful, 4, 'Progressive dwf_resource_obsidian', ItemType.building, 4, None, 'Progressive Dwf Building: Obsidian'),
    23303: ItemData(IC.useful, 4, 'Progressive dwf_resource_pottery', ItemType.building, 4, None, 'Progressive Dwf Building: Pottery'),
    23304: ItemData(IC.useful, 4, 'Progressive dwf_resource_spices', ItemType.building, 4, None, 'Progressive Dwf Building: Spices'),
    23305: ItemData(IC.useful, 4, 'Progressive dwf_resource_wine', ItemType.building, 4, None, 'Progressive Dwf Building: Wine'),
    23306: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_dwf', ItemType.building, 3, None, 'Progressive Dwf Building: Foreign Slot Discovery Dwf'),
    23307: ItemData(IC.useful, 2, 'Progressive dwf_ranger_hub_2', ItemType.building, 2, None, 'Progressive Dwf Building: Ranger Hub 2'),
    23308: ItemData(IC.useful, 5, 'Progressive dwf_trade_depot', ItemType.building, 5, None, 'Progressive Dwf Building: Trade Depot'),
    23309: ItemData(IC.useful, 2, 'Progressive dwf_workshop_infantry', ItemType.building, 2, None, 'Progressive Dwf Building: Workshop Infantry'),
    23310: ItemData(IC.useful, 3, 'Progressive dwf_allied_outpost', ItemType.building, 3, None, 'Progressive Dwf Building: Allied Outpost'),
    23311: ItemData(IC.useful, 4, 'Progressive dwf_resource_ivory', ItemType.building, 4, None, 'Progressive Dwf Building: Ivory'),
    23312: ItemData(IC.useful, 1, 'Progressive underdeep_dwf_defence_hold', ItemType.building, 1, None, 'Progressive Dwf Deep Building: Underdeep Defence Hold'),
    23313: ItemData(IC.useful, 1, 'Progressive underdeep_dwf_defence_slayers', ItemType.building, 1, None, 'Progressive Dwf Deep Building: Underdeep Defence Slayers'),
    23314: ItemData(IC.useful, 3, 'Progressive underdeep_dwf_economy_counting_room', ItemType.building, 3, None, 'Progressive Dwf Deep Building: Underdeep Economy Counting Room'),
    23315: ItemData(IC.useful, 2, 'Progressive underdeep_dwf_economy_drinking', ItemType.building, 2, None, 'Progressive Dwf Deep Building: Underdeep Economy Drinking'),
    23316: ItemData(IC.useful, 3, 'Progressive underdeep_dwf_economy_oathgold', ItemType.building, 3, None, 'Progressive Dwf Deep Building: Underdeep Economy Oathgold'),
    23317: ItemData(IC.useful, 1, 'Progressive underdeep_dwf_economy_trade', ItemType.building, 1, None, 'Progressive Dwf Deep Building: Underdeep Economy Trade'),
    23318: ItemData(IC.useful, 3, 'Progressive underdeep_dwf_grudges', ItemType.building, 3, None, 'Progressive Dwf Deep Building: Underdeep Grudges'),
    23319: ItemData(IC.useful, 2, 'Progressive underdeep_dwf_main_deeper', ItemType.building, 2, None, 'Progressive Dwf Deep Building: Underdeep Main Deeper'),
    23320: ItemData(IC.useful, 3, 'Progressive underdeep_dwf_main', ItemType.building, 3, None, 'Progressive Dwf Deep Building: Underdeep Main'),
    23321: ItemData(IC.useful, 1, 'Progressive underdeep_dwf_resources', ItemType.building, 1, None, 'Progressive Dwf Deep Building: Underdeep Resources'),
    23322: ItemData(IC.useful, 3, 'Progressive underdeep_dwf_tall', ItemType.building, 3, None, 'Progressive Dwf Deep Building: Underdeep Tall'),
    23323: ItemData(IC.useful, 1, 'Progressive dwf_ranger_hub_1', ItemType.building, 1, None, 'Progressive Dwf Building: Ranger Hub 1'),
    23324: ItemData(IC.useful, 4, 'Progressive dwf_engineer', ItemType.building, 4, None, 'Progressive Dwf Building: Engineer'),
    23325: ItemData(IC.useful, 1, 'Progressive dwf_barracks', ItemType.building, 1, None, 'Progressive Dwf Building: Barracks'),
    23326: ItemData(IC.useful, 2, 'Progressive dwf_farm', ItemType.building, 2, None, 'Progressive Dwf Building: Farm'),
    23327: ItemData(IC.useful, 2, 'Progressive dwf_garrison', ItemType.building, 2, None, 'Progressive Dwf Building: Garrison'),
    23328: ItemData(IC.useful, 5, 'Progressive dwf_industry', ItemType.building, 5, None, 'Progressive Dwf Building: Industry'),
    23329: ItemData(IC.useful, 3, 'Progressive dwf_port', ItemType.building, 3, None, 'Progressive Dwf Building: Port'),
    23330: ItemData(IC.useful, 4, 'Progressive dwf_resource_beer', ItemType.building, 4, None, 'Progressive Dwf Building: Beer'),
    23331: ItemData(IC.useful, 4, 'Progressive dwf_resource_dyes', ItemType.building, 4, None, 'Progressive Dwf Building: Dyes'),
    23332: ItemData(IC.useful, 4, 'Progressive dwf_resource_game', ItemType.building, 4, None, 'Progressive Dwf Building: Game'),
    23333: ItemData(IC.useful, 4, 'Progressive dwf_resource_gems', ItemType.building, 4, None, 'Progressive Dwf Building: Gems'),
    23334: ItemData(IC.useful, 4, 'Progressive dwf_resource_gold', ItemType.building, 4, None, 'Progressive Dwf Building: Gold'),
    23335: ItemData(IC.useful, 4, 'Progressive dwf_resource_iron', ItemType.building, 4, None, 'Progressive Dwf Building: Iron'),
    23336: ItemData(IC.useful, 4, 'Progressive dwf_resource_marble', ItemType.building, 4, None, 'Progressive Dwf Building: Marble'),
    23337: ItemData(IC.useful, 4, 'Progressive dwf_resource_pastures', ItemType.building, 4, None, 'Progressive Dwf Building: Pastures'),
    23338: ItemData(IC.useful, 4, 'Progressive dwf_resource_salt', ItemType.building, 4, None, 'Progressive Dwf Building: Salt'),
    23339: ItemData(IC.useful, 4, 'Progressive dwf_resource_timber', ItemType.building, 4, None, 'Progressive Dwf Building: Timber'),
    23340: ItemData(IC.useful, 5, 'Progressive dwf_settlement_major', ItemType.building, 5, None, 'Progressive Dwf Building: Settlement Major'),
    23341: ItemData(IC.useful, 3, 'Progressive dwf_settlement_minor', ItemType.building, 3, None, 'Progressive Dwf Building: Settlement Minor'),
    23342: ItemData(IC.useful, 2, 'Progressive dwf_slayer', ItemType.building, 2, None, 'Progressive Dwf Building: Slayer'),
    23343: ItemData(IC.useful, 4, 'Progressive dwf_smith', ItemType.building, 4, None, 'Progressive Dwf Building: Smith'),
    23344: ItemData(IC.useful, 3, 'Progressive dwf_tavern', ItemType.building, 3, None, 'Progressive Dwf Building: Tavern'),
    23345: ItemData(IC.useful, 2, 'Progressive dwf_trade_depot', ItemType.building, 2, None, 'Progressive Dwf Building: Trade Depot'),
    23346: ItemData(IC.useful, 3, 'Progressive dwf_wall', ItemType.building, 3, None, 'Progressive Dwf Building: Wall'),
    23347: ItemData(IC.useful, 4, 'Progressive dwf_workshop', ItemType.building, 4, None, 'Progressive Dwf Building: Workshop')
}

progTechs: dict[int, ItemData] = {
    23400: ItemData(IC.useful, 5, "Progressive tech_dwf_guilds", ItemType.tech, 5, None, "Progressive Dwf Tech: Guilds"),
    23401: ItemData(IC.useful, 7, "Progressive tech_dwf_clans", ItemType.tech, 7, None, "Progressive Dwf Tech: Clans"),
}

special: dict[int, specialItemData] = {
    23500: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_airship_hull_1', ItemType.building, 0, 'Progressive dwf_airship_hull', False, False, 'Dwf Airship: Basic Airship Frame'),
    23501: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_airship_hull_2', ItemType.building, 1, 'Progressive dwf_airship_hull', False, False, 'Dwf Airship: Hardened Hull'),
    23502: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_airship_hull_3', ItemType.building, 2, 'Progressive dwf_airship_hull', False, False, 'Dwf Airship: Rune Inscribed Frame'),
    23503: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_airship_hull_4', ItemType.building, 3, 'Progressive dwf_airship_hull', False, False, 'Dwf Airship: Reinforced Airship Frame'),
    23504: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_airship_hull_5', ItemType.building, 4, 'Progressive dwf_airship_hull', False, False, 'Dwf Airship: Rune-Etched Hull'),
    23505: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_artillery_workshop_1', ItemType.building, 0, 'Progressive dwf_airship_workshop', False, False, 'Dwf Airship: Compact Forge'),
    23506: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_artillery_workshop_2', ItemType.building, 1, 'Progressive dwf_airship_workshop', False, False, 'Dwf Airship: Streamlined Smelters'),
    23507: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_artillery_workshop_3', ItemType.building, 2, 'Progressive dwf_airship_workshop', False, False, 'Dwf Airship: Automated Foundry'),
    23508: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_barracks_1', ItemType.building, 0, 'Progressive dwf_airship_barracks', False, False, 'Dwf Airship: Bunks'),
    23509: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_barracks_2', ItemType.building, 1, 'Progressive dwf_airship_barracks', False, False, 'Dwf Airship: Billets'),
    23510: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_barracks_3', ItemType.building, 2, 'Progressive dwf_airship_barracks', False, False, 'Dwf Airship: Barracks'),
    23511: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_beer_hall_1', ItemType.building, 0, 'Progressive dwf_airship_beer', False, False, 'Dwf Airship: Beer Hall'),
    23512: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_beer_hall_2', ItemType.building, 1, 'Progressive dwf_airship_beer', False, False, 'Dwf Airship: Mess Hall'),
    23513: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_beer_hall_3', ItemType.building, 2, 'Progressive dwf_airship_beer', False, False, 'Dwf Airship: Air Distillery'),
    23514: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_cargo_hold_1', ItemType.building, 0, 'Progressive dwf_airship_cargo', False, False, 'Dwf Airship: Cargo Racks'),
    23515: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_cargo_hold_2', ItemType.building, 1, 'Progressive dwf_airship_cargo', False, False, 'Dwf Airship: Storage Hold'),
    23516: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_cargo_hold_3', ItemType.building, 2, 'Progressive dwf_airship_cargo', False, False, 'Dwf Airship: Optimised External Access Port'),
    23517: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_crew_weapons_1', ItemType.building, 0, 'Progressive dwf_airship_weapons', False, False, 'Dwf Airship: Target Practice Dummy'),
    23518: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_crew_weapons_2', ItemType.building, 1, 'Progressive dwf_airship_weapons', False, False, 'Dwf Airship: Shooting Gallery'),
    23519: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_crew_weapons_3', ItemType.building, 2, 'Progressive dwf_airship_weapons', False, False, 'Dwf Airship: Firing Range'),
    23520: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engineering_workshop_1', ItemType.building, 0, 'Progressive dwf_airship_engineering', False, False, 'Dwf Airship: Engineering Workbench'),
    23521: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engineering_workshop_2', ItemType.building, 1, 'Progressive dwf_airship_engineering', False, False, "Dwf Airship: Engineer's Compartment"),
    23522: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engineering_workshop_3', ItemType.building, 2, 'Progressive dwf_airship_engineering', False, False, 'Dwf Airship: Assembly Line'),
    23523: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engines_1', ItemType.building, 0, 'Progressive dwf_airship_engines', False, False, 'Dwf Airship: Engine Room'),
    23524: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engines_2', ItemType.building, 1, 'Progressive dwf_airship_engines', False, False, 'Dwf Airship: Improved Engine Output'),
    23525: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_engines_3', ItemType.building, 2, 'Progressive dwf_airship_engines', False, False, 'Dwf Airship: Larger Propellers'),
    23526: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_infantry_workshop_1', ItemType.building, 0, 'Progressive dwf_airship_infantry', False, False, 'Dwf Airship: Arms Store'),
    23527: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_infantry_workshop_2', ItemType.building, 1, 'Progressive dwf_airship_infantry', False, False, 'Dwf Airship: Arms Locker'),
    23528: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_support_radius_1', ItemType.building, 0, 'Progressive dwf_airship_support', False, False, 'Dwf Airship: Signals System'),
    23529: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'wh3_dlc25_dwarf_spirit_of_grungni_support_radius_2', ItemType.building, 1, 'Progressive dwf_airship_support', False, False, 'Dwf Airship: Signals Network'),
    23530: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_hull', ItemType.building, 5, None, False, False, 'Progressive Dwf Airship: Hull'),
    23531: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_workshop', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Artillery Workshop'),
    23532: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_barracks', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Barracks'),
    23533: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_beer', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Beer Taps'),
    23534: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_cargo', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Cargo Hold'),
    23535: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_weapons', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Crew Training'),
    23536: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_engineering', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Engineering Workshop'),
    23537: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_engines', ItemType.building, 3, None, False, False, 'Progressive Dwf Airship: Engines'),
    23538: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_infantry', ItemType.building, 2, None, False, False, 'Progressive Dwf Airship: Infantry Workshop'),
    23539: specialItemData(IC.useful, 1, 'wh3_dlc25_dwf_malakai', 'Progressive dwf_airship_support', ItemType.building, 2, None, False, False, 'Progressive Dwf Airship: Support Radius'),
}