from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    24000: ItemData(IC.useful, 1, 'wh_main_emp_inf_spearmen_0', ItemType.unit, 1, 'Progressive emp_inf', 'Emp Unit: Spearmen'),
    24001: ItemData(IC.useful, 1, 'wh_main_emp_inf_swordsmen', ItemType.unit, 1, 'Progressive emp_inf', 'Emp Unit: Swordsmen'),
    24002: ItemData(IC.useful, 1, 'wh_main_emp_inf_spearmen_1', ItemType.unit, 1, 'Progressive emp_inf', 'Emp Unit: Spearmen (Shields)'),
    24003: ItemData(IC.useful, 1, 'wh_main_emp_inf_halberdiers', ItemType.unit, 2, 'Progressive emp_inf', 'Emp Unit: Halberdiers'),
    24004: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_flagellants_0', ItemType.unit, 2, 'Progressive emp_inf', 'Emp Unit: Flagellants'),
    24005: ItemData(IC.useful, 1, 'wh_main_emp_inf_greatswords', ItemType.unit, 3, 'Progressive emp_inf', 'Emp Unit: Greatswords'),
    24006: ItemData(IC.useful, 1, 'wh2_dlc13_emp_inf_archers_0', ItemType.unit, 1, 'Progressive emp_rng', 'Emp Unit: Archers'),
    24007: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_free_company_militia_0', ItemType.unit, 1, 'Progressive emp_rng', 'Emp Unit: Free Company Militia'),
    24008: ItemData(IC.useful, 1, 'wh_main_emp_inf_crossbowmen', ItemType.unit, 2, 'Progressive emp_rng', 'Emp Unit: Crossbowmen'),
    24009: ItemData(IC.useful, 1, 'wh_main_emp_inf_handgunners', ItemType.unit, 2, 'Progressive emp_rng', 'Emp Unit: Handgunners'),
    24010: ItemData(IC.useful, 1, 'wh2_dlc13_emp_inf_huntsmen_0', ItemType.unit, 3, 'Progressive emp_rng', 'Emp Unit: Huntsmen'),
    24011: ItemData(IC.useful, 1, 'wh3_dlc25_emp_inf_nuln_ironsides', ItemType.unit, 3, 'Progressive emp_rng', 'Emp Unit: Nuln Ironsides'),
    24012: ItemData(IC.useful, 1, 'wh3_dlc25_emp_inf_hochland_long_rifles', ItemType.unit, 3, 'Progressive emp_rng', 'Emp Unit: Hochland Long Rifles'),
    24013: ItemData(IC.useful, 1, 'wh_main_emp_cav_pistoliers_1', ItemType.unit, 1, 'Progressive emp_cav', 'Emp Unit: Pistoliers'),
    24014: ItemData(IC.useful, 1, 'wh_main_emp_cav_outriders_0', ItemType.unit, 2, 'Progressive emp_cav', 'Emp Unit: Outriders'),
    24015: ItemData(IC.useful, 1, 'wh_main_emp_cav_empire_knights', ItemType.unit, 2, 'Progressive emp_cav', 'Emp Unit: Empire Knights'),
    24016: ItemData(IC.useful, 1, 'wh_main_emp_cav_outriders_1', ItemType.unit, 3, 'Progressive emp_cav', 'Emp Unit: Outriders (Grenade Launchers)'),
    24017: ItemData(IC.useful, 1, 'wh_dlc04_emp_cav_knights_blazing_sun_0', ItemType.unit, 3, 'Progressive emp_cav', 'Emp Unit: Knights of the Blazing Sun'),
    24018: ItemData(IC.useful, 1, 'wh_main_emp_cav_reiksguard', ItemType.unit, 3, 'Progressive emp_cav', 'Emp Unit: Reiksguard'),
    24019: ItemData(IC.useful, 1, 'wh3_dlc25_emp_cav_knights_of_the_black_rose', ItemType.unit, 3, 'Progressive emp_cav', 'Emp Unit: Knights of the Black Rose'),
    24020: ItemData(IC.useful, 1, 'wh_main_emp_cav_demigryph_knights_0', ItemType.unit, 4, 'Progressive emp_cav', 'Emp Unit: Demigryph Knights'),
    24021: ItemData(IC.useful, 1, 'wh_main_emp_cav_demigryph_knights_1', ItemType.unit, 4, 'Progressive emp_cav', 'Emp Unit: Demigryph Knights (Halberds)'),
    24022: ItemData(IC.useful, 1, 'wh_main_emp_art_mortar', ItemType.unit, 1, 'Progressive emp_art', 'Emp Unit: Mortars'),
    24023: ItemData(IC.useful, 1, 'wh_main_emp_art_great_cannon', ItemType.unit, 2, 'Progressive emp_art', 'Emp Unit: Great Cannons'),
    24024: ItemData(IC.useful, 1, 'wh_main_emp_art_helstorm_rocket_battery', ItemType.unit, 3, 'Progressive emp_art', 'Emp Unit: Helstorm Rocket Battery'),
    24025: ItemData(IC.useful, 1, 'wh_main_emp_art_helblaster_volley_gun', ItemType.unit, 3, 'Progressive emp_art', 'Emp Unit: Helblaster Volley Guns'),
    24026: ItemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_0', ItemType.unit, 1, 'Progressive emp_veh', 'Emp Unit: War Wagons'),
    24027: ItemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_1', ItemType.unit, 2, 'Progressive emp_veh', 'Emp Unit: War Wagons (Mortars)'),
    24028: ItemData(IC.useful, 1, 'wh3_dlc25_emp_veh_marienburg_land_ship', ItemType.unit, 3, 'Progressive emp_veh', 'Emp Unit: Land Ship'),
    24029: ItemData(IC.useful, 1, 'wh_main_emp_veh_steam_tank_driver', ItemType.unit, 4, 'Progressive emp_veh', 'Emp Unit: Steam Tank'),
    24030: ItemData(IC.useful, 1, 'wh3_dlc25_emp_veh_steam_tank_volley_gun', ItemType.unit, 4, 'Progressive emp_veh', 'Emp Unit: Steam Tank (Volley Gun)'),
    24031: ItemData(IC.useful, 1, 'wh_main_emp_veh_luminark_of_hysh_0', ItemType.unit, 4, 'Progressive emp_veh', 'Emp Unit: Luminark of Hysh'),
    24032: ItemData(IC.useful, 1, 'wh3_dlc25_emp_cha_wizard_metal', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Gold Wizard'),
    24033: ItemData(IC.useful, 1, 'wh_main_emp_cha_wizard_light_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Light Wizard'),
    24034: ItemData(IC.useful, 1, 'wh_dlc05_emp_cha_wizard_shadows_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Grey Wizard'),
    24035: ItemData(IC.useful, 1, 'wh_main_emp_cha_wizard_heavens_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Celestial Wizard'),
    24036: ItemData(IC.useful, 1, 'wh_dlc05_emp_cha_wizard_life_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Jade Wizard'),
    24037: ItemData(IC.useful, 1, 'wh_dlc03_emp_cha_wizard_beasts_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Amber Wizard'),
    24038: ItemData(IC.useful, 1, 'wh2_pro07_emp_cha_wizard_death_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Amethyst Wizard'),
    24039: ItemData(IC.useful, 1, 'wh_main_emp_cha_wizard_fire_0', ItemType.unit, 2, 'Progressive emp_hro', 'Emp Unit: Bright Wizard'),
    24040: ItemData(IC.useful, 1, 'wh3_dlc25_emp_cha_engineer', ItemType.unit, 1, 'Progressive emp_hro', 'Emp Unit: Engineer'),
    24041: ItemData(IC.useful, 1, 'wh_main_emp_cha_witch_hunter', ItemType.unit, 1, 'Progressive emp_hro', 'Emp Unit: Witch Hunter'),
    24042: ItemData(IC.useful, 1, 'wh_main_emp_cha_warrior_priest_0', ItemType.unit, 1, 'Progressive emp_hro', 'Emp Unit: Warrior Priest'),
    24043: ItemData(IC.useful, 1, 'wh_main_emp_cha_captain_0', ItemType.unit, 1, 'Progressive emp_hro', 'Emp Unit: Empire Captain'),
    24044: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_sigmars_sons_0', ItemType.unit, 2, 'Progressive emp_inf', "Emp Unit: Sigmar's Sons (Swordsmen)"),
    24045: ItemData(IC.useful, 1, 'wh2_dlc13_emp_inf_archers_ror_0', ItemType.unit, 1, 'Progressive emp_rng', 'Emp Unit: Deathjacks (Archers)'),
    24046: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_stirlands_revenge_0', ItemType.unit, 1, 'Progressive emp_rng', "Emp Unit: Stirland's Revenge (Free Company Militia)"),
    24047: ItemData(IC.useful, 1, 'wh3_dlc25_emp_inf_spearmen_shields_ror', ItemType.unit, 1, 'Progressive emp_inf', "Emp Unit: Grundel's Defenders (Spearmen – Shields)"),
    24048: ItemData(IC.useful, 1, 'wh2_dlc13_emp_inf_huntsmen_ror_0', ItemType.unit, 3, 'Progressive emp_rng', 'Emp Unit: The White Wolves (Huntsmen)'),
    24049: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_silver_bullets_0', ItemType.unit, 2, 'Progressive emp_rng', 'Emp Unit: The Silver Bullets (Handgunners)'),
    24050: ItemData(IC.useful, 1, 'wh3_dlc25_emp_inf_hochland_long_rifles_ror', ItemType.unit, 3, 'Progressive emp_rng', 'Emp Unit: The Hergig Jaegerkorps (Hochland Long Rifles)'),
    24051: ItemData(IC.useful, 1, 'wh_dlc04_emp_inf_tattersouls_0', ItemType.unit, 2, 'Progressive emp_inf', 'Emp Unit: The Tattersouls (Flagellants)'),
    24052: ItemData(IC.useful, 1, 'wh_dlc04_emp_cav_zintlers_reiksguard_0', ItemType.unit, 3, 'Progressive emp_inf', "Emp Unit: Zintler's Reiksguard (Reiksguard)"),
    24053: ItemData(IC.useful, 1, 'wh_dlc04_emp_veh_templehof_luminark_0', ItemType.unit, 4, 'Progressive emp_veh', 'Emp Unit: Templehof Luminark (Luminark of Hysh)'),
    24054: ItemData(IC.useful, 1, 'wh_dlc04_emp_art_hammer_of_the_witches_0', ItemType.unit, 2, 'Progressive emp_art', 'Emp Unit: Hammer of the Witches (Great Cannons)'),
    24055: ItemData(IC.useful, 1, 'wh2_dlc13_emp_veh_war_wagon_ror_0', ItemType.unit, 3, 'Progressive emp_veh', 'Emp Unit: The Black Lions (War Wagons – Helblasters)'),
    24056: ItemData(IC.useful, 1, 'wh3_dlc25_emp_veh_marienburg_land_ship_ror', ItemType.unit, 4, 'Progressive emp_veh', 'Emp Unit: The Wonder of the Age (Land Ship)'),
    24057: ItemData(IC.useful, 1, 'wh_dlc04_emp_cav_royal_altdorf_gryphites_0', ItemType.unit, 3, 'Progressive emp_art', 'Emp Unit: The Sunmaker (Helstorm Rocket Battery)'),
    24058: ItemData(IC.useful, 1, 'wh_dlc04_emp_veh_templehof_luminark_0', ItemType.unit, 4, 'Progressive emp_cav', 'Emp Unit: The Royal Altdorf Gryphites (Demigryph Knights)'),
}

buildings: dict[int, ItemData] = {
    24400: ItemData(IC.useful, 1, 'wh2_main_emp_defence_norsca_1', ItemType.building, 0, 'Progressive emp_defence_norsca', 'Emp Building: Outpost Garrison'),
    24401: ItemData(IC.useful, 1, 'wh2_main_emp_resource_animals_1', ItemType.building, 0, 'Progressive emp_resource_animals', 'Emp Building: Exotic Animal Tamer'),
    24402: ItemData(IC.useful, 1, 'wh2_main_emp_resource_animals_2', ItemType.building, 1, 'Progressive emp_resource_animals', 'Emp Building: Exotic Animal Pen'),
    24403: ItemData(IC.useful, 1, 'wh2_main_emp_resource_animals_3', ItemType.building, 2, 'Progressive emp_resource_animals', 'Emp Building: Exotic Animal Market'),
    24404: ItemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_1', ItemType.building, 0, 'Progressive emp_resource_gemstones', 'Emp Building: Gem Mineshaft'),
    24405: ItemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_2', ItemType.building, 1, 'Progressive emp_resource_gemstones', 'Emp Building: Gem Mine'),
    24406: ItemData(IC.useful, 1, 'wh2_main_emp_resource_gemstones_3', ItemType.building, 2, 'Progressive emp_resource_gemstones', "Emp Building: Gemcutter's Workshop"),
    24407: ItemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_1', ItemType.building, 0, 'Progressive emp_resource_medicine', "Emp Building: Herb Gatherer's Camp"),
    24408: ItemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_2', ItemType.building, 1, 'Progressive emp_resource_medicine', 'Emp Building: Exotic Hothouse'),
    24409: ItemData(IC.useful, 1, 'wh2_main_emp_resource_medicine_3', ItemType.building, 2, 'Progressive emp_resource_medicine', 'Emp Building: Alchemy Workshop'),
    24410: ItemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_1', ItemType.building, 0, 'Progressive emp_resource_obsidian', 'Emp Building: Obsidian Quarry'),
    24411: ItemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_2', ItemType.building, 1, 'Progressive emp_resource_obsidian', 'Emp Building: Obsidian Trinket Maker'),
    24412: ItemData(IC.useful, 1, 'wh2_main_emp_resource_obsidian_3', ItemType.building, 2, 'Progressive emp_resource_obsidian', 'Emp Building: Obsidian Amulet Carver'),
    24413: ItemData(IC.useful, 1, 'wh2_main_emp_resource_spices_1', ItemType.building, 0, 'Progressive emp_resource_spices', 'Emp Building: Spice Market'),
    24414: ItemData(IC.useful, 1, 'wh2_main_emp_resource_spices_2', ItemType.building, 1, 'Progressive emp_resource_spices', 'Emp Building: Spice Trading Post'),
    24415: ItemData(IC.useful, 1, 'wh2_main_emp_resource_spices_3', ItemType.building, 2, 'Progressive emp_resource_spices', 'Emp Building: Eastern Bazaar'),
    24416: ItemData(IC.useful, 1, 'wh2_main_emp_roads_1', ItemType.building, 0, 'Progressive emp_roads', 'Emp Building: Paved Roads'),
    24417: ItemData(IC.useful, 1, 'wh2_main_emp_roads_2', ItemType.building, 1, 'Progressive emp_roads', 'Emp Building: Toll Gates'),
    24418: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_emp', 'Emp Building: Night Watch'),
    24419: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_emp', 'Emp Building: Armoured Watchers'),
    24420: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_emp_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_emp', 'Emp Building: Elite Watchers'),
    24421: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_1', ItemType.building, 1, 'Progressive emp_settlement_major', 'Emp Building: Small Fort'),
    24422: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_2', ItemType.building, 2, 'Progressive emp_settlement_major', 'Emp Building: Fort'),
    24423: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_3', ItemType.building, 3, 'Progressive emp_settlement_major', 'Emp Building: Grand Fort'),
    24424: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_4', ItemType.building, 4, 'Progressive emp_settlement_major', 'Emp Building: Imposing Fort'),
    24425: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_emp_5', ItemType.building, 5, 'Progressive emp_settlement_major', 'Emp Building: Impregnable Fort'),
    24426: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_1', ItemType.building, 0, 'Progressive emp_settlement_major', 'Emp Building: Occupied Sartosa Level 1'),
    24427: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_2', ItemType.building, 1, 'Progressive emp_settlement_major', 'Emp Building: Occupied Sartosa Level 2'),
    24428: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_3', ItemType.building, 2, 'Progressive emp_settlement_major', 'Emp Building: Occupied Sartosa Level 3'),
    24429: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_4', ItemType.building, 3, 'Progressive emp_settlement_major', 'Emp Building: Occupied Sartosa Level 4'),
    24430: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_emp_5', ItemType.building, 4, 'Progressive emp_settlement_major', 'Emp Building: Occupied Sartosa Level 5'),
    24431: ItemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_1', ItemType.building, 0, 'Progressive emp_shooting_range', 'Emp Building: Shooting Range'),
    24432: ItemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_2', ItemType.building, 1, 'Progressive emp_shooting_range', 'Emp Building: Firearms Academy'),
    24433: ItemData(IC.useful, 1, 'wh3_dlc25_emp_shooting_range_3', ItemType.building, 2, 'Progressive emp_shooting_range', 'Emp Building: Gunnery School'),
    24434: ItemData(IC.useful, 1, 'wh3_dlc25_emp_wizards_3', ItemType.building, 2, 'Progressive emp_wizards', "Emp Building: Wizard's Tower"),
    24435: ItemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_1', ItemType.building, 0, 'Progressive emp_allied_outpost', 'Emp Building: Empire Outpost'),
    24436: ItemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_2', ItemType.building, 1, 'Progressive emp_allied_outpost', 'Emp Building: Empire District'),
    24437: ItemData(IC.useful, 1, 'wh3_main_emp_allied_outpost_3', ItemType.building, 2, 'Progressive emp_allied_outpost', 'Emp Building: Empire Colony'),
    24438: ItemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_1', ItemType.building, 0, 'Progressive emp_resource_ivory', 'Emp Building: Animal Store'),
    24439: ItemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_2', ItemType.building, 1, 'Progressive emp_resource_ivory', 'Emp Building: Tusk Market'),
    24440: ItemData(IC.useful, 1, 'wh3_main_emp_resource_ivory_3', ItemType.building, 2, 'Progressive emp_resource_ivory', 'Emp Building: Tusk Compound'),
    24441: ItemData(IC.useful, 1, 'wh_main_emp_barracks_1', ItemType.building, 0, 'Progressive emp_barracks', 'Emp Building: Training Field'),
    24442: ItemData(IC.useful, 1, 'wh_main_emp_barracks_2', ItemType.building, 1, 'Progressive emp_barracks', 'Emp Building: Rally Field'),
    24443: ItemData(IC.useful, 1, 'wh_main_emp_barracks_3', ItemType.building, 2, 'Progressive emp_barracks', 'Emp Building: Barracks'),
    24444: ItemData(IC.useful, 1, 'wh_main_emp_farm_basic_1', ItemType.building, 0, 'Progressive emp_farm_basic', 'Emp Building: Fields'),
    24445: ItemData(IC.useful, 1, 'wh_main_emp_farm_basic_2', ItemType.building, 1, 'Progressive emp_farm_basic', 'Emp Building: Farm'),
    24446: ItemData(IC.useful, 1, 'wh_main_emp_farm_basic_3', ItemType.building, 2, 'Progressive emp_farm_basic', 'Emp Building: Landed Estate'),
    24447: ItemData(IC.useful, 1, 'wh_main_emp_forges_1', ItemType.building, 0, 'Progressive emp_forges', 'Emp Building: Gunsmith'),
    24448: ItemData(IC.useful, 1, 'wh_main_emp_forges_2', ItemType.building, 1, 'Progressive emp_forges', 'Emp Building: Foundry'),
    24449: ItemData(IC.useful, 1, 'wh_main_emp_forges_3', ItemType.building, 2, 'Progressive emp_forges', "Emp Building: Engineer's Workshop"),
    24450: ItemData(IC.useful, 1, 'wh_main_emp_forges_4', ItemType.building, 3, 'Progressive emp_forges', "Emp Building: Engineer's Guildhall"),
    24451: ItemData(IC.useful, 1, 'wh_main_emp_garrison_1', ItemType.building, 0, 'Progressive emp_garrison', 'Emp Building: Guard House'),
    24452: ItemData(IC.useful, 1, 'wh_main_emp_garrison_2', ItemType.building, 1, 'Progressive emp_garrison', 'Emp Building: City Watch'),
    24453: ItemData(IC.useful, 1, 'wh_main_emp_industry_basic_1', ItemType.building, 0, 'Progressive emp_industry_basic', 'Emp Building: Weaving House'),
    24454: ItemData(IC.useful, 1, 'wh_main_emp_industry_basic_2', ItemType.building, 1, 'Progressive emp_industry_basic', 'Emp Building: Clothier'),
    24455: ItemData(IC.useful, 1, 'wh_main_emp_industry_basic_3', ItemType.building, 2, 'Progressive emp_industry_basic', "Emp Building: Tailors' Guild"),
    24456: ItemData(IC.useful, 1, 'wh_main_emp_port_1', ItemType.building, 0, 'Progressive emp_port', 'Emp Building: Imperial Wharf'),
    24457: ItemData(IC.useful, 1, 'wh_main_emp_port_2', ItemType.building, 1, 'Progressive emp_port', 'Emp Building: Imperial Harbour'),
    24458: ItemData(IC.useful, 1, 'wh_main_emp_port_3', ItemType.building, 2, 'Progressive emp_port', 'Emp Building: Imperial Port'),
    24459: ItemData(IC.useful, 1, 'wh_main_emp_resource_dyes_1', ItemType.building, 0, 'Progressive emp_resource_dyes', 'Emp Building: Cinnabar Mining Pit'),
    24460: ItemData(IC.useful, 1, 'wh_main_emp_resource_dyes_2', ItemType.building, 1, 'Progressive emp_resource_dyes', 'Emp Building: Cinnabar Mine'),
    24461: ItemData(IC.useful, 1, 'wh_main_emp_resource_dyes_3', ItemType.building, 2, 'Progressive emp_resource_dyes', 'Emp Building: Dyemaker'),
    24462: ItemData(IC.useful, 1, 'wh_main_emp_resource_furs_1', ItemType.building, 0, 'Progressive emp_resource_furs', 'Emp Building: Hunting Camp'),
    24463: ItemData(IC.useful, 1, 'wh_main_emp_resource_furs_2', ItemType.building, 1, 'Progressive emp_resource_furs', 'Emp Building: Hunting Lodge'),
    24464: ItemData(IC.useful, 1, 'wh_main_emp_resource_furs_3', ItemType.building, 2, 'Progressive emp_resource_furs', 'Emp Building: Tannery'),
    24465: ItemData(IC.useful, 1, 'wh_main_emp_resource_gold_1', ItemType.building, 0, 'Progressive emp_resource_gold', 'Emp Building: Gold Mining Pit'),
    24466: ItemData(IC.useful, 1, 'wh_main_emp_resource_gold_2', ItemType.building, 1, 'Progressive emp_resource_gold', 'Emp Building: Gold Mine'),
    24467: ItemData(IC.useful, 1, 'wh_main_emp_resource_gold_3', ItemType.building, 2, 'Progressive emp_resource_gold', 'Emp Building: Gold Smelter'),
    24468: ItemData(IC.useful, 1, 'wh_main_emp_resource_iron_1', ItemType.building, 0, 'Progressive emp_resource_iron', 'Emp Building: Iron Mining Pit'),
    24469: ItemData(IC.useful, 1, 'wh_main_emp_resource_iron_2', ItemType.building, 1, 'Progressive emp_resource_iron', 'Emp Building: Iron Mine'),
    24470: ItemData(IC.useful, 1, 'wh_main_emp_resource_iron_3', ItemType.building, 2, 'Progressive emp_resource_iron', 'Emp Building: Iron Smelter'),
    24472: ItemData(IC.useful, 1, 'wh_main_emp_resource_marble_1', ItemType.building, 0, 'Progressive emp_resource_marble', 'Emp Building: Stone Cutter'),
    24473: ItemData(IC.useful, 1, 'wh_main_emp_resource_marble_2', ItemType.building, 1, 'Progressive emp_resource_marble', 'Emp Building: Marble Quarry'),
    24474: ItemData(IC.useful, 1, 'wh_main_emp_resource_marble_3', ItemType.building, 2, 'Progressive emp_resource_marble', 'Emp Building: Mason'),
    24475: ItemData(IC.useful, 1, 'wh_main_emp_resource_pastures_1', ItemType.building, 0, 'Progressive emp_resource_pastures', 'Emp Building: Grazing Pastures'),
    24476: ItemData(IC.useful, 1, 'wh_main_emp_resource_pastures_2', ItemType.building, 1, 'Progressive emp_resource_pastures', 'Emp Building: Livestock Pens'),
    24477: ItemData(IC.useful, 1, 'wh_main_emp_resource_pastures_3', ItemType.building, 2, 'Progressive emp_resource_pastures', 'Emp Building: Cattle Ranch'),
    24479: ItemData(IC.useful, 1, 'wh_main_emp_resource_pottery_1', ItemType.building, 0, 'Progressive emp_resource_pottery', 'Emp Building: Clay Pit'),
    24480: ItemData(IC.useful, 1, 'wh_main_emp_resource_pottery_2', ItemType.building, 1, 'Progressive emp_resource_pottery', 'Emp Building: Pottery Maker'),
    24481: ItemData(IC.useful, 1, 'wh_main_emp_resource_pottery_3', ItemType.building, 2, 'Progressive emp_resource_pottery', 'Emp Building: Kilns'),
    24482: ItemData(IC.useful, 1, 'wh_main_emp_resource_salt_1', ItemType.building, 0, 'Progressive emp_resource_salt', 'Emp Building: Brine Mining Pit'),
    24483: ItemData(IC.useful, 1, 'wh_main_emp_resource_salt_2', ItemType.building, 1, 'Progressive emp_resource_salt', 'Emp Building: Brine Mine'),
    24484: ItemData(IC.useful, 1, 'wh_main_emp_resource_salt_3', ItemType.building, 2, 'Progressive emp_resource_salt', 'Emp Building: Saltworks'),
    24485: ItemData(IC.useful, 1, 'wh_main_emp_resource_timber_1', ItemType.building, 0, 'Progressive emp_resource_timber', "Emp Building: Woodman's Hut"),
    24486: ItemData(IC.useful, 1, 'wh_main_emp_resource_timber_2', ItemType.building, 1, 'Progressive emp_resource_timber', 'Emp Building: Timber Mill'),
    24487: ItemData(IC.useful, 1, 'wh_main_emp_resource_timber_3', ItemType.building, 2, 'Progressive emp_resource_timber', 'Emp Building: Lumberyard'),
    24489: ItemData(IC.useful, 1, 'wh_main_emp_resource_wine_1', ItemType.building, 0, 'Progressive emp_resource_wine', 'Emp Building: Orchards'),
    24490: ItemData(IC.useful, 1, 'wh_main_emp_resource_wine_2', ItemType.building, 1, 'Progressive emp_resource_wine', 'Emp Building: Vineyard'),
    24491: ItemData(IC.useful, 1, 'wh_main_emp_resource_wine_3', ItemType.building, 2, 'Progressive emp_resource_wine', 'Emp Building: Vintner'),
    24492: ItemData(IC.useful, 1, 'wh_main_emp_settlement_major_1', ItemType.building, 0, 'Progressive emp_settlement_major', 'Emp Building: Hamlet'),
    24493: ItemData(IC.useful, 1, 'wh_main_emp_settlement_major_2', ItemType.building, 1, 'Progressive emp_settlement_major', 'Emp Building: Village'),
    24494: ItemData(IC.useful, 1, 'wh_main_emp_settlement_major_3', ItemType.building, 2, 'Progressive emp_settlement_major', 'Emp Building: Town'),
    24495: ItemData(IC.useful, 1, 'wh_main_emp_settlement_major_4', ItemType.building, 3, 'Progressive emp_settlement_major', 'Emp Building: City'),
    24496: ItemData(IC.useful, 1, 'wh_main_emp_settlement_major_5', ItemType.building, 4, 'Progressive emp_settlement_major', 'Emp Building: City-State'),
    24497: ItemData(IC.useful, 1, 'wh_main_emp_settlement_minor_1', ItemType.building, 0, 'Progressive emp_settlement_minor', 'Emp Building: Hamlet'),
    24498: ItemData(IC.useful, 1, 'wh_main_emp_settlement_minor_2', ItemType.building, 1, 'Progressive emp_settlement_minor', 'Emp Building: Village'),
    24499: ItemData(IC.useful, 1, 'wh_main_emp_settlement_minor_3', ItemType.building, 2, 'Progressive emp_settlement_minor', 'Emp Building: Town'),
    24500: ItemData(IC.useful, 1, 'wh_main_emp_stables_1', ItemType.building, 0, 'Progressive emp_stables', 'Emp Building: Stables'),
    24501: ItemData(IC.useful, 1, 'wh_main_emp_stables_2', ItemType.building, 1, 'Progressive emp_stables', 'Emp Building: Livery'),
    24502: ItemData(IC.useful, 1, 'wh_main_emp_stables_3', ItemType.building, 2, 'Progressive emp_stables', 'Emp Building: Menagerie'),
    24503: ItemData(IC.useful, 1, 'wh_main_emp_tavern_1', ItemType.building, 0, 'Progressive emp_tavern', 'Emp Building: Tap Room'),
    24504: ItemData(IC.useful, 1, 'wh_main_emp_tavern_2', ItemType.building, 1, 'Progressive emp_tavern', 'Emp Building: Tavern'),
    24505: ItemData(IC.useful, 1, 'wh_main_emp_tavern_3', ItemType.building, 2, 'Progressive emp_tavern', 'Emp Building: Coaching Inn'),
    24506: ItemData(IC.useful, 1, 'wh_main_emp_walls_1', ItemType.building, 0, 'Progressive emp_walls', 'Emp Building: Basic Walls'),
    24507: ItemData(IC.useful, 1, 'wh_main_emp_walls_2', ItemType.building, 1, 'Progressive emp_walls', 'Emp Building: Tall Walls'),
    24508: ItemData(IC.useful, 1, 'wh_main_emp_walls_3', ItemType.building, 2, 'Progressive emp_walls', 'Emp Building: Reinforced Walls'),
    24509: ItemData(IC.useful, 1, 'wh_main_emp_wizards_1', ItemType.building, 0, 'Progressive emp_wizards', "Emp Building: Wizard's Conclave"),
    24510: ItemData(IC.useful, 1, 'wh_main_emp_wizards_2', ItemType.building, 1, 'Progressive emp_wizards', "Emp Building: Wizard's Campus"),
    24511: ItemData(IC.useful, 1, 'wh_main_emp_worship_1', ItemType.building, 0, 'Progressive emp_worship', 'Emp Building: Shrine of Sigmar'),
    24512: ItemData(IC.useful, 1, 'wh_main_emp_worship_1', ItemType.building, 0, 'Progressive emp_worship', 'Emp Building: Shrine of Sigmar'),
    24513: ItemData(IC.useful, 1, 'wh_main_emp_worship_1', ItemType.building, 0, 'Progressive emp_worship', 'Emp Building: Shrine of Sigmar'),
    24514: ItemData(IC.useful, 1, 'wh_main_emp_worship_2', ItemType.building, 1, 'Progressive emp_worship', 'Emp Building: Temple of Sigmar'),
    24515: ItemData(IC.useful, 1, 'wh_main_emp_worship_2', ItemType.building, 1, 'Progressive emp_worship', 'Emp Building: Temple of Sigmar'),
    24516: ItemData(IC.useful, 1, 'wh_main_emp_worship_2', ItemType.building, 1, 'Progressive emp_worship', 'Emp Building: Temple of Sigmar')
}

techs: dict[int, ItemData] = {
    24800: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3_b', ItemType.tech, 3, 'Progressive tech_emp', 'Emp Tech: Improved Piston Technology'),
    24803: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1', ItemType.tech, 1, 'Progressive tech_emp_infantry', 'Emp Tech: State Troop Standards'),
    24804: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_a', ItemType.tech, 2, 'Progressive tech_emp_infantry', 'Emp Tech: State-Issued Infantry Armour'),
    24813: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_b', ItemType.tech, 2, 'Progressive tech_emp_infantry', 'Emp Tech: State-Issued Weapons'),
    24814: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_infantry_1_c', ItemType.tech, 3, 'Progressive tech_emp_infantry', 'Emp Tech: Improved Heavy Weapons'),
    24806: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1', ItemType.tech, 1, 'Progressive tech_emp_missiles', 'Emp Tech: Mass-Produced Small Ammunition'),
    24807: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1_a', ItemType.tech, 2, 'Progressive tech_emp_missiles', 'Emp Tech: Mounted Weaponry'),
    24817: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_missile_1_b', ItemType.tech, 3, 'Progressive tech_emp_missiles', 'Emp Tech: Rifled Barrels'),
    24818: ItemData(IC.useful, 1, 'wh2_dlc25_tech_emp_missile_1_c', ItemType.tech, 2, 'Progressive tech_emp_missiles', 'Emp Tech: Trained Marksmen'),
    24801: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1', ItemType.tech, 1, 'Progressive tech_emp_cavalry', 'Emp Tech: Improved Cavalry Armour'),
    24811: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_a', ItemType.tech, 2, 'Progressive tech_emp_cavalry', 'Emp Tech: Blinkers'),
    24802: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_b', ItemType.tech, 2, 'Progressive tech_emp_cavalry', 'Emp Tech: Endurance Training'),
    24812: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_cav_1_c', ItemType.tech, 3, 'Progressive tech_emp_cavalry', 'Emp Tech: The Inner Circle'),
    24805: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1_b', ItemType.tech, 1, 'Progressive tech_emp_artillery', 'Emp Tech: Ordnance Canisters'),
    24815: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1', ItemType.tech, 2, 'Progressive tech_emp_artillery', 'Emp Tech: Firing Drills'),
    24808: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_art_c', ItemType.tech, 2, 'Progressive tech_emp_artillery', 'Emp Tech: Refined Schematics'),
    24810: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2_b', ItemType.tech, 3, 'Progressive tech_emp_artillery', 'Emp Tech: Combustion Agent'),
    21816: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3_b', ItemType.tech, 1, 'Progressive tech_emp_machines', 'Emp Tech: Improved Piston Technology'),
    24816: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_machine_1_a', ItemType.tech, 2, 'Progressive tech_emp_machines', 'Emp Tech: Reinforced Armour Plating'),
    24809: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_machine_1_c', ItemType.tech, 2, 'Progressive tech_emp_machines', 'Emp Tech: Greater Channelling'),
    24819: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_machine_1_d', ItemType.tech, 3, 'Progressive tech_emp_machines', 'Emp Tech: Pinnacle of the Empire'),

    24825: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_3', ItemType.tech, 1, 'Progressive tech_emp_industry', 'Emp Tech: Supply Wagons'),
    24824: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_2_a', ItemType.tech, 2, 'Progressive tech_emp_industry', 'Emp Tech: Colonial Factors'),
    24821: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2_a', ItemType.tech, 3, 'Progressive tech_emp_industry', 'Emp Tech: Guildmaster Professors'),
    24823: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_1_a', ItemType.tech, 4, 'Progressive tech_emp_industry', 'Emp Tech: Commodity Trading'),
    24835: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_2', ItemType.tech, 1, 'Progressive tech_emp_industry', 'Emp Tech: Grain Silos'),
    24832: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_2', ItemType.tech, 2, 'Progressive tech_emp_industry', 'Emp Tech: Continuous Production'),
    24830: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1', ItemType.tech, 3, 'Progressive tech_emp_industry', 'Emp Tech: Assembly Line'),
    24833: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3', ItemType.tech, 4, 'Progressive tech_emp_industry', 'Emp Tech: Imperial Architects'),

    24820: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1_b', ItemType.tech, 1, 'Progressive tech_emp_imperial', 'Emp Tech: Imperial University'),
    24834: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_1_b', ItemType.tech, 1, 'Progressive tech_emp_imperial', 'Emp Tech: Clergy of Sigmar'),
    24831: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_1_a', ItemType.tech, 1, 'Progressive tech_emp_imperial', "Emp Tech: Engineers' Guild"),
    24822: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_academia_3_a', ItemType.tech, 1, 'Progressive tech_emp_imperial', 'Emp Tech: Intelligence Sharing'),
    24826: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_economy_3_a', ItemType.tech, 2, 'Progressive tech_emp_imperial', 'Emp Tech: Manorialism'),

    24827: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_1', ItemType.tech, 1, 'Progressive tech_emp_magic', 'Emp Tech: Teachings of Teclis'),
    24828: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_3', ItemType.tech, 2, 'Progressive tech_emp_magic', 'Emp Tech: Protection of the Patriarch'),
    24836: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_2', ItemType.tech, 2, 'Progressive tech_emp_magic', 'Emp Tech: The Eight Orders'),
    24829: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_magic_4', ItemType.tech, 3, 'Progressive tech_emp_magic', 'Emp Tech: Hall of Duels'),

    24837: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_a', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Tzarina'),
    24838: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_b', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Phoenix King'),
    24842: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_d', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Royarch of Bretonnia'),
    24839: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_diplomacy_1_c', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Karaz Ankor'),
    24845: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_e', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Dragon Emperor'),
    24846: ItemData(IC.useful, 1, 'wh3_dlc25_tech_emp_diplomacy_1_f', ItemType.tech, 1, 'Progressive tech_emp_diplomacy', 'Emp Tech: Ambassador to the Overtyrant'),

    24840: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_1', ItemType.tech, 1, 'Progressive tech_emp_enemies', 'Emp Tech: Purge of the Foul'),
    24841: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_2', ItemType.tech, 1, 'Progressive tech_emp_enemies', 'Emp Tech: Purge of the Fell'),
    24843: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_3', ItemType.tech, 1, 'Progressive tech_emp_enemies', 'Emp Tech: Purge of the Knife-Ears'),
    24844: ItemData(IC.useful, 1, 'wh2_dlc13_tech_emp_purge_4', ItemType.tech, 1, 'Progressive tech_emp_enemies', 'Emp Tech: Purge of the Ruinous Breeds'),
}

progUnits: dict[int, ItemData] = {
    25200: ItemData(IC.useful, 3, "Progressive emp_inf", ItemType.unit, 3, "", "Progressive Emp Unit: Infantry"),
    25201: ItemData(IC.useful, 3, "Progressive emp_rng", ItemType.unit, 3, "", "Progressive Emp Unit: Ranged"),
    25202: ItemData(IC.useful, 4, "Progressive emp_cav", ItemType.unit, 4, "", "Progressive Emp Unit: Cavalry"),
    25203: ItemData(IC.useful, 3, "Progressive emp_art", ItemType.unit, 3, "", "Progressive Emp Unit: Artillery"),
    25204: ItemData(IC.useful, 4, "Progressive emp_veh", ItemType.unit, 4, "", "Progressive Emp Unit: War Machine"),
    25206: ItemData(IC.useful, 2, "Progressive emp_hro", ItemType.unit, 2, "", "Progressive Emp Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    25300: ItemData(IC.useful, 3, 'Progressive emp_resource_animals', ItemType.building, 3, None, 'Progressive Emp Building: Animals'),
    25301: ItemData(IC.useful, 3, 'Progressive emp_resource_gemstones', ItemType.building, 3, None, 'Progressive Emp Building: Gemstones'),
    25302: ItemData(IC.useful, 3, 'Progressive emp_resource_medicine', ItemType.building, 3, None, 'Progressive Emp Building: Medicine'),
    25303: ItemData(IC.useful, 3, 'Progressive emp_resource_obsidian', ItemType.building, 3, None, 'Progressive Emp Building: Obsidian'),
    25304: ItemData(IC.useful, 3, 'Progressive emp_resource_spices', ItemType.building, 3, None, 'Progressive Emp Building: Spices'),
    25305: ItemData(IC.useful, 2, 'Progressive emp_roads', ItemType.building, 2, None, 'Progressive Emp Building: Roads'),
    25306: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_emp', ItemType.building, 3, None, 'Progressive Emp Building: Foreign Slot Discovery Emp'),
    25307: ItemData(IC.useful, 3, 'Progressive emp_shooting_range', ItemType.building, 3, None, 'Progressive Emp Building: Shooting Range'),
    25308: ItemData(IC.useful, 3, 'Progressive emp_wizards', ItemType.building, 3, None, 'Progressive Emp Building: Wizards'),
    25309: ItemData(IC.useful, 3, 'Progressive emp_allied_outpost', ItemType.building, 3, None, 'Progressive Emp Building: Allied Outpost'),
    25310: ItemData(IC.useful, 3, 'Progressive emp_resource_ivory', ItemType.building, 3, None, 'Progressive Emp Building: Ivory'),
    25311: ItemData(IC.useful, 3, 'Progressive emp_barracks', ItemType.building, 3, None, 'Progressive Emp Building: Barracks'),
    25312: ItemData(IC.useful, 3, 'Progressive emp_farm_basic', ItemType.building, 3, None, 'Progressive Emp Building: Farm Basic'),
    25313: ItemData(IC.useful, 4, 'Progressive emp_forges', ItemType.building, 4, None, 'Progressive Emp Building: Forges'),
    25314: ItemData(IC.useful, 2, 'Progressive emp_garrison', ItemType.building, 2, None, 'Progressive Emp Building: Garrison'),
    25315: ItemData(IC.useful, 3, 'Progressive emp_industry_basic', ItemType.building, 3, None, 'Progressive Emp Building: Industry Basic'),
    25316: ItemData(IC.useful, 3, 'Progressive emp_port', ItemType.building, 3, None, 'Progressive Emp Building: Port'),
    25317: ItemData(IC.useful, 3, 'Progressive emp_resource_dyes', ItemType.building, 3, None, 'Progressive Emp Building: Dyes'),
    25318: ItemData(IC.useful, 3, 'Progressive emp_resource_furs', ItemType.building, 3, None, 'Progressive Emp Building: Furs'),
    25319: ItemData(IC.useful, 3, 'Progressive emp_resource_gold', ItemType.building, 3, None, 'Progressive Emp Building: Gold'),
    25320: ItemData(IC.useful, 3, 'Progressive emp_resource_iron', ItemType.building, 3, None, 'Progressive Emp Building: Iron'),
    25321: ItemData(IC.useful, 3, 'Progressive emp_resource_marble', ItemType.building, 3, None, 'Progressive Emp Building: Marble'),
    25322: ItemData(IC.useful, 3, 'Progressive emp_resource_pastures', ItemType.building, 3, None, 'Progressive Emp Building: Pastures'),
    25323: ItemData(IC.useful, 3, 'Progressive emp_resource_pottery', ItemType.building, 3, None, 'Progressive Emp Building: Pottery'),
    25324: ItemData(IC.useful, 3, 'Progressive emp_resource_salt', ItemType.building, 3, None, 'Progressive Emp Building: Salt'),
    25325: ItemData(IC.useful, 3, 'Progressive emp_resource_timber', ItemType.building, 3, None, 'Progressive Emp Building: Timber'),
    25326: ItemData(IC.useful, 3, 'Progressive emp_resource_wine', ItemType.building, 3, None, 'Progressive Emp Building: Wine'),
    25327: ItemData(IC.useful, 5, 'Progressive emp_settlement_major', ItemType.building, 5, None, 'Progressive Emp Building: Settlement Major'),
    25328: ItemData(IC.useful, 3, 'Progressive emp_settlement_minor', ItemType.building, 3, None, 'Progressive Emp Building: Settlement Minor'),
    25329: ItemData(IC.useful, 3, 'Progressive emp_stables', ItemType.building, 3, None, 'Progressive Emp Building: Stables'),
    25330: ItemData(IC.useful, 3, 'Progressive emp_tavern', ItemType.building, 3, None, 'Progressive Emp Building: Tavern'),
    25331: ItemData(IC.useful, 3, 'Progressive emp_walls', ItemType.building, 3, None, 'Progressive Emp Building: Walls'),
    25332: ItemData(IC.useful, 2, 'Progressive emp_wizards', ItemType.building, 2, None, 'Progressive Emp Building: Wizards'),
    25333: ItemData(IC.useful, 2, 'Progressive emp_worship', ItemType.building, 2, None, 'Progressive Emp Building: Worship')
}

progTechs: dict[int, ItemData] = {
    25400: ItemData(IC.useful, 3, "Progressive tech_emp_infantry", ItemType.tech, 3, None, "Progressive Emp Tech: Infantry"),
    25401: ItemData(IC.useful, 3, "Progressive tech_emp_missiles", ItemType.tech, 3, None, "Progressive Emp Tech: Missiles"),
    25402: ItemData(IC.useful, 3, "Progressive tech_emp_cavalry", ItemType.tech, 3, None, "Progressive Emp Tech: Cavalry"),
    25403: ItemData(IC.useful, 3, "Progressive tech_emp_artillery", ItemType.tech, 3, None, "Progressive Emp Tech: Artillery"),
    25404: ItemData(IC.useful, 3, "Progressive tech_emp_machines", ItemType.tech, 3, None, "Progressive Emp Tech: War Machines"),
    25405: ItemData(IC.useful, 4, "Progressive tech_emp_industry", ItemType.tech, 4, None, "Progressive Emp Tech: Trade & Industry"),
    25406: ItemData(IC.useful, 2, "Progressive tech_emp_imperial", ItemType.tech, 2, None, "Progressive Emp Tech: Imperial Colleges"),
    25407: ItemData(IC.useful, 3, "Progressive tech_emp_magic", ItemType.tech, 3, None, "Progressive Emp Tech: Colleges of Magic"),
    25408: ItemData(IC.useful, 1, "Progressive tech_emp_diplomacy", ItemType.tech, 1, None, "Progressive Emp Tech: Diplomatic Corps"),
    25409: ItemData(IC.useful, 1, "Progressive tech_emp_enemies", ItemType.tech, 1, None, "Progressive Emp Tech: Enemies of State"),
    25411: ItemData(IC.useful, 2, "Progressive tech_emp_faction", ItemType.tech, 2, None, "Progressive Emp Tech: Faction"),
}

special: dict[int, specialItemData] = {
    25500: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_emp_art_helstorm_rocket_battery_morr', ItemType.unit, 3, 'Progressive emp_art', False, False, 'Emp Unit: Amethyst Helstorm Rocket Battery'),
    25501: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_emp_cav_outriders_morr', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Amethyst Outriders'),
    25502: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_emp_inf_nuln_ironsides_morr', ItemType.unit, 3, 'Progressive emp_rng', False, False, 'Emp Unit: Amethyst Ironsides'),
    25503: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_emp_veh_marienburg_land_ship_morr', ItemType.unit, 4, 'Progressive emp_veh', False, False, 'Emp Unit: Amethyst Land Ship'),
    25504: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_the_huntmarshals_expedition', 'wh2_dlc13_huntmarshall_veh_obsinite_gyrocopter_0', ItemType.unit, 1, 'Progressive emp_veh', False, False, 'Emp Unit: Obsinite Gyrocopters'),
    25505: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_greatswords_ror_0', ItemType.unit, 3, 'Progressive emp_inf', False, False, 'Emp Unit: Carroburg Greatswords (Greatswords)'),
    25506: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_halberdiers_ror_0', ItemType.unit, 2, 'Progressive emp_inf', False, False, 'Emp Unit: Nordland Mariners (Halberdiers)'),
    25507: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_spearmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, "Emp Unit: Eldred's Guard (Spearmen – Shields)"),
    25508: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_swordsmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, 'Emp Unit: Swords of Ulric (Swordsmen)'),
    25509: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_handgunners_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, "Emp Unit: Gunderman's Surefires (Handgunners)"),
    25510: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_inf_crossbowmen_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, 'Emp Unit: Stir River Patrol (Crossbowmen)'),
    25511: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_cav_empire_knights_ror_0', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of the Everlasting Light (Empire Knights)'),
    25512: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_cav_empire_knights_ror_1', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of Morr (Empire Knights)'),
    25513: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_cav_empire_knights_ror_2', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: The Stubborn Bulls (Empire Knights – Greatswords)'),
    25514: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_cav_outriders_ror_0', ItemType.unit, 3, 'Progressive emp_cav', False, False, 'Emp Unit: The Bordermen (Outriders – Grenade Launchers)'),
    25515: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_cav_pistoliers_ror_0', ItemType.unit, 1, 'Progressive emp_cav', False, False, 'Emp Unit: The Noble Sons Abroad (Pistoliers)'),
    25516: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_veh_steam_tank_driver_ror_0', ItemType.unit, 4, 'Progressive emp_veh', False, False, "Emp Unit: The Emperor's Wrath (Steam Tank)"),
    25517: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_emp_art_mortar_ror_0', ItemType.unit, 1, 'Progressive emp_art', False, False, "Emp Unit: Sootson's Guns (Mortars)"),
    25518: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_greatswords_ror_0', ItemType.unit, 3, 'Progressive emp_inf', False, False, 'Emp Unit: Carroburg Greatswords (Greatswords)'),
    25519: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_halberdiers_ror_0', ItemType.unit, 2, 'Progressive emp_inf', False, False, 'Emp Unit: Nordland Mariners (Halberdiers)'),
    25520: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_spearmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, "Emp Unit: Eldred's Guard (Spearmen – Shields)"),
    25521: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_swordsmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, 'Emp Unit: Swords of Ulric (Swordsmen)'),
    25522: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_handgunners_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, "Emp Unit: Gunderman's Surefires (Handgunners)"),
    25523: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_inf_crossbowmen_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, 'Emp Unit: Stir River Patrol (Crossbowmen)'),
    25524: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_cav_empire_knights_ror_0', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of the Everlasting Light (Empire Knights)'),
    25525: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_cav_empire_knights_ror_1', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of Morr (Empire Knights)'),
    25526: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_cav_empire_knights_ror_2', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: The Stubborn Bulls (Empire Knights – Greatswords)'),
    25527: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_cav_outriders_ror_0', ItemType.unit, 3, 'Progressive emp_cav', False, False, 'Emp Unit: The Bordermen (Outriders – Grenade Launchers)'),
    25528: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_cav_pistoliers_ror_0', ItemType.unit, 1, 'Progressive emp_cav', False, False, 'Emp Unit: The Noble Sons Abroad (Pistoliers)'),
    25529: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_veh_steam_tank_driver_ror_0', ItemType.unit, 4, 'Progressive emp_veh', False, False, "Emp Unit: The Emperor's Wrath (Steam Tank)"),
    25530: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh2_dlc13_emp_art_mortar_ror_0', ItemType.unit, 1, 'Progressive emp_art', False, False, "Emp Unit: Sootson's Guns (Mortars)"),
    25531: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_greatswords_ror_0', ItemType.unit, 3, 'Progressive emp_inf', False, False, 'Emp Unit: Carroburg Greatswords (Greatswords)'),
    25532: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_halberdiers_ror_0', ItemType.unit, 2, 'Progressive emp_inf', False, False, 'Emp Unit: Nordland Mariners (Halberdiers)'),
    25533: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_spearmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, "Emp Unit: Eldred's Guard (Spearmen – Shields)"),
    25534: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_swordsmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, 'Emp Unit: Swords of Ulric (Swordsmen)'),
    25535: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_handgunners_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, "Emp Unit: Gunderman's Surefires (Handgunners)"),
    25536: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_inf_crossbowmen_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, 'Emp Unit: Stir River Patrol (Crossbowmen)'),
    25537: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_cav_empire_knights_ror_0', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of the Everlasting Light (Empire Knights)'),
    25538: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_cav_empire_knights_ror_1', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of Morr (Empire Knights)'),
    25539: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_cav_empire_knights_ror_2', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: The Stubborn Bulls (Empire Knights – Greatswords)'),
    25540: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_cav_outriders_ror_0', ItemType.unit, 3, 'Progressive emp_cav', False, False, 'Emp Unit: The Bordermen (Outriders – Grenade Launchers)'),
    25541: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_cav_pistoliers_ror_0', ItemType.unit, 1, 'Progressive emp_cav', False, False, 'Emp Unit: The Noble Sons Abroad (Pistoliers)'),
    25542: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_veh_steam_tank_driver_ror_0', ItemType.unit, 4, 'Progressive emp_veh', False, False, "Emp Unit: The Emperor's Wrath (Steam Tank)"),
    25543: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh2_dlc13_emp_art_mortar_ror_0', ItemType.unit, 1, 'Progressive emp_art', False, False, "Emp Unit: Sootson's Guns (Mortars)"),
    25544: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_greatswords_ror_0', ItemType.unit, 3, 'Progressive emp_inf', False, False, 'Emp Unit: Carroburg Greatswords (Greatswords)'),
    25545: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_halberdiers_ror_0', ItemType.unit, 2, 'Progressive emp_inf', False, False, 'Emp Unit: Nordland Mariners (Halberdiers)'),
    25546: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_spearmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, "Emp Unit: Eldred's Guard (Spearmen – Shields)"),
    25547: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_swordsmen_ror_0', ItemType.unit, 1, 'Progressive emp_inf', False, False, 'Emp Unit: Swords of Ulric (Swordsmen)'),
    25548: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_handgunners_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, "Emp Unit: Gunderman's Surefires (Handgunners)"),
    25549: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_inf_crossbowmen_ror_0', ItemType.unit, 2, 'Progressive emp_rng', False, False, 'Emp Unit: Stir River Patrol (Crossbowmen)'),
    25550: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_cav_empire_knights_ror_0', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of the Everlasting Light (Empire Knights)'),
    25551: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_cav_empire_knights_ror_1', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: Knights of Morr (Empire Knights)'),
    25552: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_cav_empire_knights_ror_2', ItemType.unit, 2, 'Progressive emp_cav', False, False, 'Emp Unit: The Stubborn Bulls (Empire Knights – Greatswords)'),
    25553: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_cav_outriders_ror_0', ItemType.unit, 3, 'Progressive emp_cav', False, False, 'Emp Unit: The Bordermen (Outriders – Grenade Launchers)'),
    25554: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_cav_pistoliers_ror_0', ItemType.unit, 1, 'Progressive emp_cav', False, False, 'Emp Unit: The Noble Sons Abroad (Pistoliers)'),
    25555: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_veh_steam_tank_driver_ror_0', ItemType.unit, 4, 'Progressive emp_veh', False, False, "Emp Unit: The Emperor's Wrath (Steam Tank)"),
    25556: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh2_dlc13_emp_art_mortar_ror_0', ItemType.unit, 1, 'Progressive emp_art', False, False, "Emp Unit: Sootson's Guns (Mortars)"),
    25557: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_tech_emp_elector_counts_2', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Emp Tech: The Conclave of Light'),
    25558: specialItemData(IC.useful, 1, 'wh_main_emp_empire', 'wh2_dlc13_tech_emp_elector_counts_1', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Emperor of the Empire'),
    25559: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_elspeth_1', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Advisor to Nuln'),
    25560: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_elspeth_2', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: The Amethyst Armourer'),
    25561: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_elspeth_3', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Seeker of Knowledge'),
    25562: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_elspeth_4', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Scion of the Empire'),
    25563: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_gelt_1', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Emp Tech: College Archives'),
    25564: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_gelt_2', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Cataclysmic Power'),
    25565: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_main_tech_emp_fanatics_decree_volkmar', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, "Emp Tech: Fanatic's Decree"),
    25566: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_main_tech_emp_divine_mandate_volkmar', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Divine Mandate'),
    25567: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_the_huntmarshals_expedition', 'wh2_dlc13_tech_emp_wulfhart_1', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, "Emp Tech: Hunters' Guild"),
    25568: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_the_huntmarshals_expedition', 'wh2_dlc13_tech_emp_wulfhart_2', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Colonial Fort'),
    25569: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_the_huntmarshals_expedition', 'wh2_dlc13_tech_emp_wulfhart_3', ItemType.tech, 1, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Seaborne Logistics'),
    25570: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_the_huntmarshals_expedition', 'wh2_dlc13_tech_emp_wulfhart_4', ItemType.tech, 2, 'Progressive tech_emp_faction', False, False, 'Emp Tech: Imperial Reinforcements'),
    25571: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_1', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Swords of the Empire'),
    25572: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_2', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Spears of the Empire'),
    25573: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_3', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Marksman of the Empire'),
    25574: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_4', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Machines of the Empire'),
    25575: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_5', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Riders of the Empire'),
    25576: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'wh3_dlc25_tech_emp_state_troops_6', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Knights of the Empire'),
    25577: specialItemData(IC.useful, 1, 'wh_main_emp_wissenland', 'Progressive tech_emp_troops', ItemType.tech, 1, None, False, True, 'Progressive Emp Tech: State Troops'),
    25578: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_1', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Swords of the Empire'),
    25579: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_2', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Spears of the Empire'),
    25580: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_3', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Marksman of the Empire'),
    25581: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_4', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Machines of the Empire'),
    25582: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_5', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Riders of the Empire'),
    25583: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'wh3_dlc25_tech_emp_state_troops_6', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Knights of the Empire'),
    25584: specialItemData(IC.useful, 1, 'wh2_dlc13_emp_golden_order', 'Progressive tech_emp_troops', ItemType.tech, 1, None, False, True, 'Progressive Emp Tech: State Troops'),
    25585: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_1', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Swords of the Empire'),
    25586: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_2', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Spears of the Empire'),
    25587: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_3', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Marksman of the Empire'),
    25588: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_4', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Machines of the Empire'),
    25589: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_5', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Riders of the Empire'),
    25590: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'wh3_dlc25_tech_emp_state_troops_6', ItemType.tech, 1, 'Progressive tech_emp_troops', False, False, 'Emp Tech: Knights of the Empire'),
    25591: specialItemData(IC.useful, 1, 'wh3_main_emp_cult_of_sigmar', 'Progressive tech_emp_troops', ItemType.tech, 1, None, False, True, 'Progressive Emp Tech: State Troops')
}