from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    28000: ItemData(IC.useful, 1, 'wh3_main_grn_inf_orc_boyz_spear_shield', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Orc Boyz (Spears)'),
    28001: ItemData(IC.useful, 1, 'wh3_main_grn_inf_goblins_sword_shield', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Goblins'),
    28002: ItemData(IC.useful, 1, 'wh3_dlc26_grn_mon_colossal_squig_ror', ItemType.unit, 4, 'Progressive grn_inf', 'Grn Unit: Da Acid Burpa (Colossal Squig)'),
    28003: ItemData(IC.useful, 1, 'wh3_dlc26_grn_mon_colossal_squig', ItemType.unit, 4, 'Progressive grn_inf', 'Grn Unit: Colossal Squig'),
    28004: ItemData(IC.useful, 1, 'wh3_dlc26_grn_mon_arachnarok_spider_flinger', ItemType.unit, 4, 'war_beast', 'Grn Unit: Arachnarok Spider (Flinger)'),
    28005: ItemData(IC.useful, 1, 'wh3_dlc26_grn_inf_rugluds_armoured_orcs', ItemType.unit, 2, 'Progressive grn_rng', "Grn Unit: Ruglud's Armoured Orcs"),
    28006: ItemData(IC.useful, 1, 'wh3_dlc26_grn_inf_black_orcs_shield', ItemType.unit, 3, 'Progressive grn_inf', 'Grn Unit: Black Orcs'),
    28007: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_snagla_grobspit', ItemType.unit, 0, 'cavalry', 'Grn Unit: Snagla Grobspit'),
    28008: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_savage_orc_great_shaman_wyvern', ItemType.unit, 0, 'war_beast', 'Grn Unit: {{tr:land_units_onscreen_name_wh3_dlc26_grn_cha_savage_orc_great_shaman}}'),
    28009: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_savage_orc_great_shaman_boar', ItemType.unit, 0, 'cavalry', 'Grn Unit: {{tr:land_units_onscreen_name_wh3_dlc26_grn_cha_savage_orc_great_shaman}}'),
    28010: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_savage_orc_great_shaman', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Savage Orc Great Shaman'),
    28011: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_night_goblin_big_boss_squig', ItemType.unit, 0, 'cavalry', 'Grn Unit: Night Goblin Big Boss'),
    28012: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_night_goblin_big_boss', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Night Goblin Big Boss'),
    28013: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_gorbad_ironclaw_gnarla', ItemType.unit, 0, 'cavalry', 'Grn Unit: Gorbad Ironclaw'),
    28014: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cha_gorbad_ironclaw', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Gorbad Ironclaw'),
    28015: ItemData(IC.useful, 1, 'wh3_dlc26_grn_cav_mangler_squig', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: Mangler Squigs'),
    28016: ItemData(IC.useful, 1, 'wh3_dlc26_grn_art_bolt_throwa_ror', ItemType.unit, 2, 'Progressive grn_art', "Grn Unit: Snagla's Deff Throwa (Goblin Bolt Throwa)"),
    28017: ItemData(IC.useful, 1, 'wh3_dlc26_grn_art_bolt_throwa', ItemType.unit, 2, 'Progressive grn_art', 'Grn Unit: Goblin Bolt Throwa'),
    28018: ItemData(IC.useful, 1, 'wh2_pro09_grn_cha_black_orc_big_boss_1', ItemType.unit, 0, 'cavalry', 'Grn Unit: Black Orc Big Boss'),
    28019: ItemData(IC.useful, 1, 'wh2_pro09_grn_cha_black_orc_big_boss_0', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Black Orc Big Boss'),
    28020: ItemData(IC.useful, 1, 'wh2_dlc15_grn_veh_snotling_pump_wagon_roller_0', ItemType.unit, 2, 'Progressive grn_veh', 'Grn Unit: Snotling Pump Wagons (Spiky Rollers)'),
    28021: ItemData(IC.useful, 1, 'wh2_dlc15_grn_veh_snotling_pump_wagon_flappas_0', ItemType.unit, 2, 'Progressive grn_veh', 'Grn Unit: Snotling Pump Wagons (Flappas)'),
    28022: ItemData(IC.useful, 1, 'wh2_dlc15_grn_veh_snotling_pump_wagon_0', ItemType.unit, 2, 'Progressive grn_veh', 'Grn Unit: Snotling Pump Wagons'),
    28023: ItemData(IC.useful, 1, 'wh2_dlc15_grn_mon_wyvern_waaagh_0', ItemType.unit, 4, 'Progressive grn_inf', 'Grn Unit: Feral Wyvern'),
    28024: ItemData(IC.useful, 1, 'wh2_dlc15_grn_mon_stone_trolls_0', ItemType.unit, 3, 'Progressive grn_inf', 'Grn Unit: Stone Trolls'),
    28025: ItemData(IC.useful, 1, 'wh2_dlc15_grn_mon_rogue_idol_0', ItemType.unit, 5, 'Progressive grn_inf', 'Grn Unit: Rogue Idol'),
    28026: ItemData(IC.useful, 1, 'wh2_dlc15_grn_mon_river_trolls_0', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: River Trolls'),
    28027: ItemData(IC.useful, 1, 'wh2_dlc15_grn_mon_feral_hydra_waaagh_0', ItemType.unit, 4, 'Progressive grn_inf', 'Grn Unit: Feral Hydra'),
    28028: ItemData(IC.useful, 1, 'wh2_dlc15_grn_cav_squig_hoppers_waaagh_0', ItemType.unit, 2, 'cavalry', 'Grn Unit: Armoured Squig Hoppers'),
    28029: ItemData(IC.useful, 1, 'wh2_dlc15_grn_cav_forest_goblin_spider_riders_waaagh_0', ItemType.unit, 1, 'cavalry', 'Grn Unit: Lava Spider Rider Archers'),
    28030: ItemData(IC.useful, 1, 'wh_main_grn_mon_trolls', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: Trolls'),
    28031: ItemData(IC.useful, 1, 'wh_main_grn_mon_giant', ItemType.unit, 3, 'Progressive grn_inf', 'Grn Unit: Giant'),
    28032: ItemData(IC.useful, 1, 'wh_main_grn_mon_arachnarok_spider_0', ItemType.unit, 4, 'war_beast', 'Grn Unit: Arachnarok Spider'),
    28033: ItemData(IC.useful, 1, 'wh_main_grn_inf_savage_orcs', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: Savage Orcs'),
    28034: ItemData(IC.useful, 1, 'wh_main_grn_inf_savage_orc_big_uns', ItemType.unit, 2, 'Progressive grn_inf', "Grn Unit: Savage Orc Big 'Uns"),
    28035: ItemData(IC.useful, 1, 'wh_main_grn_inf_savage_orc_arrer_boyz', ItemType.unit, 2, 'Progressive grn_rng', 'Grn Unit: Savage Orc Arrer Boyz'),
    28036: ItemData(IC.useful, 1, 'wh_main_grn_inf_orc_boyz', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Orc Boyz'),
    28037: ItemData(IC.useful, 1, 'wh_main_grn_inf_orc_big_uns', ItemType.unit, 2, 'Progressive grn_inf', "Grn Unit: Orc Big 'Uns"),
    28038: ItemData(IC.useful, 1, 'wh_main_grn_inf_orc_arrer_boyz', ItemType.unit, 2, 'Progressive grn_rng', 'Grn Unit: Orc Arrer Boyz'),
    28039: ItemData(IC.useful, 1, 'wh_main_grn_inf_night_goblins', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Night Goblins'),
    28040: ItemData(IC.useful, 1, 'wh_main_grn_inf_night_goblin_fanatics_1', ItemType.unit, 2, 'Progressive grn_rng', 'Grn Unit: Night Goblin Archers (Fanatics)'),
    28041: ItemData(IC.useful, 1, 'wh_main_grn_inf_night_goblin_fanatics', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: Night Goblins (Fanatics)'),
    28042: ItemData(IC.useful, 1, 'wh_main_grn_inf_night_goblin_archers', ItemType.unit, 1, 'Progressive grn_rng', 'Grn Unit: Night Goblin Archers'),
    28043: ItemData(IC.useful, 1, 'wh_main_grn_inf_goblin_spearmen', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Goblins (Spears)'),
    28044: ItemData(IC.useful, 1, 'wh_main_grn_inf_goblin_archers', ItemType.unit, 1, 'Progressive grn_rng', 'Grn Unit: Goblin Archers'),
    28045: ItemData(IC.useful, 1, 'wh_main_grn_inf_black_orcs', ItemType.unit, 3, 'Progressive grn_inf', 'Grn Unit: Black Orcs (Great Weapons)'),
    28046: ItemData(IC.useful, 1, 'wh_main_grn_cha_orc_shaman_1', ItemType.unit, 0, 'cavalry', 'Grn Unit: Orc Shaman'),
    28047: ItemData(IC.useful, 1, 'wh_main_grn_cha_orc_shaman_0', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Orc Shaman'),
    28048: ItemData(IC.useful, 1, 'wh_main_grn_cha_night_goblin_shaman', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Night Goblin Shaman'),
    28049: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_great_shaman_2', ItemType.unit, 0, 'Progressive grn_veh', 'Grn Unit: Goblin Great Shaman'),
    28050: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_great_shaman_1', ItemType.unit, 0, 'cavalry', 'Grn Unit: Goblin Great Shaman'),
    28051: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_great_shaman_0', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Goblin Great Shaman'),
    28052: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_big_boss_4', ItemType.unit, 0, 'Progressive grn_veh', 'Grn Unit: Goblin Big Boss'),
    28053: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_big_boss_2', ItemType.unit, 0, 'cavalry', 'Grn Unit: Goblin Big Boss'),
    28054: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_big_boss_1', ItemType.unit, 0, 'cavalry', 'Grn Unit: Goblin Big Boss'),
    28055: ItemData(IC.useful, 1, 'wh_main_grn_cha_goblin_big_boss_0', ItemType.unit, 0, 'Progressive grn_inf', 'Grn Unit: Goblin Big Boss'),
    28056: ItemData(IC.useful, 1, 'wh_main_grn_cav_savage_orc_boar_boyz', ItemType.unit, 2, 'cavalry', 'Grn Unit: Savage Orc Boar Boyz'),
    28057: ItemData(IC.useful, 1, 'wh_main_grn_cav_savage_orc_boar_boy_big_uns', ItemType.unit, 3, 'cavalry', "Grn Unit: Savage Orc Boar Boy Big 'Uns"),
    28058: ItemData(IC.useful, 1, 'wh_main_grn_cav_orc_boar_chariot', ItemType.unit, 2, 'Progressive grn_veh', 'Grn Unit: Orc Boar Chariots'),
    28059: ItemData(IC.useful, 1, 'wh_main_grn_cav_orc_boar_boyz', ItemType.unit, 2, 'cavalry', 'Grn Unit: Orc Boar Boyz'),
    28060: ItemData(IC.useful, 1, 'wh_main_grn_cav_orc_boar_boy_big_uns', ItemType.unit, 2, 'cavalry', "Grn Unit: Orc Boar Boy Big 'Uns"),
    28061: ItemData(IC.useful, 1, 'wh_main_grn_cav_goblin_wolf_riders_1', ItemType.unit, 1, 'cavalry', 'Grn Unit: Goblin Wolf Rider Archers'),
    28062: ItemData(IC.useful, 1, 'wh_main_grn_cav_goblin_wolf_riders_0', ItemType.unit, 1, 'cavalry', 'Grn Unit: Goblin Wolf Riders'),
    28063: ItemData(IC.useful, 1, 'wh_main_grn_cav_goblin_wolf_chariot', ItemType.unit, 2, 'Progressive grn_veh', 'Grn Unit: Goblin Wolf Chariots'),
    28064: ItemData(IC.useful, 1, 'wh_main_grn_cav_forest_goblin_spider_riders_1', ItemType.unit, 1, 'cavalry', 'Grn Unit: Forest Goblin Spider Rider Archers'),
    28065: ItemData(IC.useful, 1, 'wh_main_grn_cav_forest_goblin_spider_riders_0', ItemType.unit, 1, 'cavalry', 'Grn Unit: Forest Goblin Spider Riders'),
    28066: ItemData(IC.useful, 1, 'wh_main_grn_art_goblin_rock_lobber', ItemType.unit, 2, 'Progressive grn_art', 'Grn Unit: Goblin Rock Lobbers'),
    28067: ItemData(IC.useful, 1, 'wh_main_grn_art_doom_diver_catapult', ItemType.unit, 3, 'Progressive grn_art', 'Grn Unit: Doom Diver Catapults'),
    28068: ItemData(IC.useful, 1, 'wh_dlc06_grn_mon_spider_hatchlings_0', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Spider Hatchlings'),
    28069: ItemData(IC.useful, 1, 'wh_dlc06_grn_inf_squig_herd_0', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Squig Herd'),
    28070: ItemData(IC.useful, 1, 'wh_dlc06_grn_inf_squig_explosive_0', ItemType.unit, 1, 'Progressive grn_inf', 'Grn Unit: Soopa-Squig!'),
    28071: ItemData(IC.useful, 1, 'wh_dlc06_grn_inf_nasty_skulkers_0', ItemType.unit, 2, 'Progressive grn_inf', 'Grn Unit: Nasty Skulkers'),
    28072: ItemData(IC.useful, 1, 'wh_dlc06_grn_cav_squig_hoppers_0', ItemType.unit, 2, 'cavalry', 'Grn Unit: Night Goblin Squig Hoppers')
}

buildings: dict[int, ItemData] = {
    28402: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_grn_1', ItemType.building, 0, 'Progressive special_settlement_massif_orcal_grn', 'Grn Building: Massif Orcal (Greenskin Hideout)'),
    28403: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_grn_2', ItemType.building, 1, 'Progressive special_settlement_massif_orcal_grn', 'Grn Building: Massif Orcal (Greenskin Camp)'),
    28404: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_grn_3', ItemType.building, 2, 'Progressive special_settlement_massif_orcal_grn', 'Grn Building: Massif Orcal (Greenskin Encampment)'),
    28405: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_grn_4', ItemType.building, 3, 'Progressive special_settlement_massif_orcal_grn', 'Grn Building: Massif Orcal (Greenskin Fort)'),
    28406: ItemData(IC.useful, 1, 'wh2_dlc15_special_settlement_massif_orcal_grn_5', ItemType.building, 4, 'Progressive special_settlement_massif_orcal_grn', 'Grn Building: Massif Orcal (Greenskin Stronghold)'),
    28407: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_grn_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_grn', 'Grn Building: Rat Trapperz'),
    28408: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_grn_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_grn', 'Grn Building: Gobbo Trackerz'),
    28409: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_grn_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_grn', 'Grn Building: Trapperz Shack'),
    28411: ItemData(IC.useful, 1, 'wh2_main_grn_raiders_1', ItemType.building, 0, 'Progressive grn_raiders', "Grn Building: Raidin' Stashes"),
    28415: ItemData(IC.useful, 1, 'wh2_main_grn_resource_animals', ItemType.building, 0, 'Progressive grn_resource', 'Grn Building: Squig Nest'),
    28416: ItemData(IC.useful, 1, 'wh2_main_special_galbaraz_mourkain_grn_1', ItemType.building, 0, 'Progressive special_galbaraz_mourkain_grn', 'Grn Building: Da Biggest Bonez'),
    28417: ItemData(IC.useful, 1, 'wh2_main_special_galbaraz_oathgold_grn_1', ItemType.building, 0, 'Progressive special_galbaraz_oathgold_grn', 'Grn Building: Oathgold Mine'),
    28418: ItemData(IC.useful, 1, 'wh3_dlc26_grn_boars_3', ItemType.building, 2, 'Progressive grn_boars', 'Grn Building: Boar Penz'),
    28419: ItemData(IC.useful, 1, 'wh3_dlc26_grn_goblins_1', ItemType.building, 0, 'Progressive grn_goblins', 'Grn Building: Goblin Camp'),
    28420: ItemData(IC.useful, 1, 'wh3_dlc26_grn_goblins_2', ItemType.building, 1, 'Progressive grn_goblins', 'Grn Building: Night Goblin Hovels'),
    28421: ItemData(IC.useful, 1, 'wh3_dlc26_grn_goblins_3', ItemType.building, 2, 'Progressive grn_goblins', 'Grn Building: Mushroom Distillery'),
    28422: ItemData(IC.useful, 1, 'wh3_dlc26_grn_raiders_2', ItemType.building, 1, 'Progressive grn_raiders', "Grn Building: Raidin' Hideout"),
    28423: ItemData(IC.useful, 1, 'wh3_dlc26_grn_raiders_2', ItemType.building, 1, 'Progressive grn_raiders', "Grn Building: Raidin' Hideout"),
    28424: ItemData(IC.useful, 1, 'wh3_dlc26_grn_raiders_2', ItemType.building, 1, 'Progressive grn_raiders', "Grn Building: Grn Building: Raidin' Hideout"),
    28425: ItemData(IC.useful, 1, 'wh3_dlc26_grn_raiders_2', ItemType.building, 1, 'Progressive grn_raiders', "Grn Building: Grn Building: Raidin' Hideout"),
    28426: ItemData(IC.useful, 1, 'wh3_dlc26_grn_squigs_2', ItemType.building, 1, 'Progressive grn_squigs', 'Grn Building: Squig Chasm'),
    28427: ItemData(IC.useful, 1, 'wh3_main_grn_allied_outpost_1', ItemType.building, 0, 'Progressive grn_allied_outpost', 'Grn Building: Greenskin Outpost'),
    28428: ItemData(IC.useful, 1, 'wh3_main_grn_allied_outpost_2', ItemType.building, 1, 'Progressive grn_allied_outpost', 'Grn Building: Greenskin District'),
    28429: ItemData(IC.useful, 1, 'wh3_main_grn_allied_outpost_3', ItemType.building, 2, 'Progressive grn_allied_outpost', 'Grn Building: Greenskin Colony'),
    28430: ItemData(IC.useful, 1, 'wh_dlc06_grn_resource_animals', ItemType.building, 0, 'Progressive grn_resource', 'Grn Building: Squig Nest'),
    28431: ItemData(IC.useful, 1, 'wh_dlc06_grn_squigs_1', ItemType.building, 0, 'Progressive grn_squigs', 'Grn Building: Squig Cages'),
    28434: ItemData(IC.useful, 1, 'wh_main_grn_boars_1', ItemType.building, 0, 'Progressive grn_boars', 'Grn Building: Wolf Den'),
    28435: ItemData(IC.useful, 1, 'wh_main_grn_boars_2', ItemType.building, 1, 'Progressive grn_boars', 'Grn Building: Boar Sty'),
    28436: ItemData(IC.useful, 1, 'wh_main_grn_boss_1', ItemType.building, 0, 'Progressive grn_boss', "Grn Building: Boss' Tent"),
    28489: ItemData(IC.useful, 1, 'wh_main_grn_boss_2', ItemType.building, 1, 'Progressive grn_boss', "Grn Building: Boss' Shack"),
    28490: ItemData(IC.useful, 1, 'wh_main_grn_boss_3', ItemType.building, 2, 'Progressive grn_boss', "Grn Building: Boss' Camp"),
    28517: ItemData(IC.useful, 1, 'wh_main_grn_farm_1', ItemType.building, 0, 'Progressive grn_farm', 'Grn Building: Idolz'),
    28518: ItemData(IC.useful, 1, 'wh_main_grn_farm_2', ItemType.building, 1, 'Progressive grn_farm', 'Grn Building: Totem Pole'),
    28519: ItemData(IC.useful, 1, 'wh_main_grn_farm_3', ItemType.building, 2, 'Progressive grn_farm', 'Grn Building: Boss Pole'),
    28520: ItemData(IC.useful, 1, 'wh_main_grn_forest_beasts_1', ItemType.building, 0, 'Progressive grn_forest_beasts', 'Grn Building: Gloomy Hollowz'),
    28521: ItemData(IC.useful, 1, 'wh_main_grn_forest_beasts_2', ItemType.building, 1, 'Progressive grn_forest_beasts', 'Grn Building: Sacred Spider Groundz'),
    28522: ItemData(IC.useful, 1, 'wh_main_grn_forest_beasts_3', ItemType.building, 2, 'Progressive grn_forest_beasts', 'Grn Building: Deep Spider Lairz'),
    28523: ItemData(IC.useful, 1, 'wh_main_grn_garrison_1', ItemType.building, 0, 'Progressive grn_garrison', 'Grn Building: Goblin Watch Tower'),
    28526: ItemData(IC.useful, 1, 'wh_main_grn_garrison_2', ItemType.building, 1, 'Progressive grn_garrison', 'Grn Building: Orc Guard House'),
    28529: ItemData(IC.useful, 1, 'wh_main_grn_industry_1', ItemType.building, 0, 'Progressive grn_industry', 'Grn Building: Pile of Shiny Stuff'),
    28533: ItemData(IC.useful, 1, 'wh_main_grn_industry_2', ItemType.building, 1, 'Progressive grn_industry', 'Grn Building: Heap of Shiny Stuff'),
    28537: ItemData(IC.useful, 1, 'wh_main_grn_industry_3', ItemType.building, 2, 'Progressive grn_industry', 'Grn Building: Da Hoard'),
    28541: ItemData(IC.useful, 1, 'wh_main_grn_military_1', ItemType.building, 0, 'Progressive grn_military', 'Grn Building: Musta Fieldz'),
    28542: ItemData(IC.useful, 1, 'wh_main_grn_military_2', ItemType.building, 1, 'Progressive grn_military', "Grn Building: Fightin' Pit"),
    28543: ItemData(IC.useful, 1, 'wh_main_grn_military_3', ItemType.building, 2, 'Progressive grn_military', 'Grn Building: Black Orc Barracks'),
    28544: ItemData(IC.useful, 1, 'wh_main_grn_monsters_1', ItemType.building, 0, 'Progressive grn_monsters', 'Grn Building: Troll Cave'),
    28545: ItemData(IC.useful, 1, 'wh_main_grn_monsters_2', ItemType.building, 1, 'Progressive grn_monsters', "Grn Building: Stompin' Groundz"),
    28546: ItemData(IC.useful, 1, 'wh_main_grn_monsters_3', ItemType.building, 2, 'Progressive grn_monsters', 'Grn Building: Rock Mounds'),
    28549: ItemData(IC.useful, 1, 'wh_main_grn_port_1', ItemType.building, 0, 'Progressive grn_port', 'Grn Building: Greenskin Wharf'),
    28550: ItemData(IC.useful, 1, 'wh_main_grn_port_2', ItemType.building, 1, 'Progressive grn_port', 'Grn Building: Greenskin Docks'),
    28551: ItemData(IC.useful, 1, 'wh_main_grn_port_3', ItemType.building, 2, 'Progressive grn_port', 'Grn Building: Greenskin Shipyard'),
    28552: ItemData(IC.useful, 1, 'wh_main_grn_resource_gems_1', ItemType.building, 0, 'Progressive grn_resource_gems', 'Grn Building: Cave of Shinies'),
    28553: ItemData(IC.useful, 1, 'wh_main_grn_resource_gems_2', ItemType.building, 1, 'Progressive grn_resource_gems', 'Grn Building: Shiny Pit'),
    28554: ItemData(IC.useful, 1, 'wh_main_grn_resource_gems_3', ItemType.building, 2, 'Progressive grn_resource_gems', 'Grn Building: Stunty Mine'),
    28555: ItemData(IC.useful, 1, 'wh_main_grn_resource_gold_1', ItemType.building, 0, 'Progressive grn_resource_gold', 'Grn Building: Cave of Shinies'),
    28556: ItemData(IC.useful, 1, 'wh_main_grn_resource_gold_2', ItemType.building, 1, 'Progressive grn_resource_gold', 'Grn Building: Shiny Pit'),
    28557: ItemData(IC.useful, 1, 'wh_main_grn_resource_gold_3', ItemType.building, 2, 'Progressive grn_resource_gold', 'Grn Building: Stunty Mine'),
    28561: ItemData(IC.useful, 1, 'wh_main_grn_settlement_major_1', ItemType.building, 0, 'Progressive grn_settlement_major', 'Grn Building: Greenskin Hideout'),
    28564: ItemData(IC.useful, 1, 'wh_main_grn_settlement_major_2', ItemType.building, 1, 'Progressive grn_settlement_major', 'Grn Building: Greenskin Camp'),
    28567: ItemData(IC.useful, 1, 'wh_main_grn_settlement_major_3', ItemType.building, 2, 'Progressive grn_settlement_major', 'Grn Building: Greenskin Encampment'),
    28570: ItemData(IC.useful, 1, 'wh_main_grn_settlement_major_4', ItemType.building, 3, 'Progressive grn_settlement_major', 'Grn Building: Greenskin Fort'),
    28573: ItemData(IC.useful, 1, 'wh_main_grn_settlement_major_5', ItemType.building, 4, 'Progressive grn_settlement_major', 'Grn Building: Greenskin Stronghold'),
    28576: ItemData(IC.useful, 1, 'wh_main_grn_settlement_minor_1', ItemType.building, 0, 'Progressive grn_settlement_minor', 'Grn Building: Greenskin Hideout'),
    28579: ItemData(IC.useful, 1, 'wh_main_grn_settlement_minor_2', ItemType.building, 1, 'Progressive grn_settlement_minor', 'Grn Building: Greenskin Camp'),
    28584: ItemData(IC.useful, 1, 'wh_main_grn_settlement_minor_3', ItemType.building, 2, 'Progressive grn_settlement_minor', 'Grn Building: Greenskin Burrows'),
    28585: ItemData(IC.useful, 1, 'wh_main_grn_shaman_1', ItemType.building, 0, 'Progressive grn_shaman', "Grn Building: Shaman's Hut"),
    28586: ItemData(IC.useful, 1, 'wh_main_grn_shaman_2', ItemType.building, 1, 'Progressive grn_shaman', "Grn Building: Shaman's Hovel"),
    28587: ItemData(IC.useful, 1, 'wh_main_grn_shaman_3', ItemType.building, 2, 'Progressive grn_shaman', 'Grn Building: Shamanic Tepee'),
    28588: ItemData(IC.useful, 1, 'wh_main_grn_walls_1', ItemType.building, 0, 'Progressive grn_walls', 'Grn Building: Ditches'),
    28591: ItemData(IC.useful, 1, 'wh_main_grn_walls_2', ItemType.building, 1, 'Progressive grn_walls', 'Grn Building: Stakes'),
    28594: ItemData(IC.useful, 1, 'wh_main_grn_walls_3', ItemType.building, 2, 'Progressive grn_walls', 'Grn Building: Big Walls'),
    28597: ItemData(IC.useful, 1, 'wh_main_grn_workshop_1', ItemType.building, 0, 'Progressive grn_workshop', 'Grn Building: Goblin Toolbox'),
    28598: ItemData(IC.useful, 1, 'wh_main_grn_workshop_2', ItemType.building, 1, 'Progressive grn_workshop', 'Grn Building: Goblin Tinkerer Bench'),
    28599: ItemData(IC.useful, 1, 'wh_main_grn_workshop_3', ItemType.building, 2, 'Progressive grn_workshop', 'Grn Building: Goblin Workshop')
}

techs: dict[int, ItemData] = {
    28800: ItemData(IC.useful, 1, 'tech_grn_extra_1_3', ItemType.tech, 4, 'Progressive extra_1', 'Grn Tech: Spider Worship'),
    28801: ItemData(IC.useful, 1, 'tech_grn_end_1_1', ItemType.tech, 9, 'Progressive end_1', 'Grn Tech: Big Creep'),
    28802: ItemData(IC.useful, 1, 'tech_grn_start_2_1', ItemType.tech, 2, 'Progressive start_2', 'Grn Tech: More Grub'),
    28803: ItemData(IC.useful, 1, 'tech_grn_extra_1_1', ItemType.tech, 3, 'Progressive extra_1', "Grn Tech: Bouncin'"),
    28804: ItemData(IC.useful, 1, 'tech_grn_start_2_2', ItemType.tech, 1, 'Progressive start_2', 'Grn Tech: Tuff Fodda'),
    28805: ItemData(IC.useful, 1, 'tech_grn_end_1_3', ItemType.tech, 8, 'Progressive end_1', 'Grn Tech: Levvery Skin'),
    28806: ItemData(IC.useful, 1, 'tech_grn_extra_1_2', ItemType.tech, 3, 'Progressive extra_1', 'Grn Tech: Creature Comforts'),
    28807: ItemData(IC.useful, 1, 'tech_grn_extra_2_2', ItemType.tech, 2, 'Progressive extra_2', "Grn Tech: Wolf Paddin'"),
    28808: ItemData(IC.useful, 1, 'tech_grn_extra_1_4', ItemType.tech, 4, 'Progressive extra_1', "Grn Tech: Betta Arrer 'Eads"),
    28809: ItemData(IC.useful, 1, 'tech_grn_mid_1_1', ItemType.tech, 5, 'Progressive mid_1', 'Grn Tech: Raknik Spiderclaw'),
    28810: ItemData(IC.useful, 1, 'tech_grn_start_3_1', ItemType.tech, 2, 'Progressive start_3', 'Grn Tech: Go Bigga!'),
    28811: ItemData(IC.useful, 1, 'tech_grn_extra_2_3', ItemType.tech, 4, 'Progressive extra_2', "Grn Tech: No Complainin'"),
    28812: ItemData(IC.useful, 1, 'tech_grn_end_3_2', ItemType.tech, 7, 'Progressive end_3', "Grn Tech: Night Raidin'"),
    28813: ItemData(IC.useful, 1, 'tech_grn_start_1_3', ItemType.tech, 8, 'Progressive start_1', 'Grn Tech: Healy Mushrooms'),
    28814: ItemData(IC.useful, 1, 'tech_grn_end_2_1', ItemType.tech, 8, 'Progressive end_2', "Grn Tech: Sneakin'"),
    28815: ItemData(IC.useful, 1, 'tech_grn_end_4_3', ItemType.tech, 9, 'Progressive end_4', 'Grn Tech: Da Longest Waaagh!'),
    28816: ItemData(IC.useful, 1, 'tech_grn_start_0_1', ItemType.tech, 0, 'Progressive start_0', 'Grn Tech: Waaagh!!!'),
    28817: ItemData(IC.useful, 1, 'tech_grn_start_2_3', ItemType.tech, 1, 'Progressive start_2', 'Grn Tech: Big Boss Business'),
    28818: ItemData(IC.useful, 1, 'tech_grn_end_2_3', ItemType.tech, 2, 'Progressive end_2', "Grn Tech: Gork n' Mork"),
    28819: ItemData(IC.useful, 1, 'tech_grn_extra_2_4', ItemType.tech, 3, 'Progressive extra_2', "Grn Tech: Warbossin'"),
    28820: ItemData(IC.useful, 1, 'tech_grn_end_5_2', ItemType.tech, 4, 'Progressive end_5', "Grn Tech: Bigga 'n' Betta Bosses"),
    28821: ItemData(IC.useful, 1, 'tech_grn_start_3_3', ItemType.tech, 5, 'Progressive start_3', "Grn Tech: Less Eatin', More Buildin'"),
    28822: ItemData(IC.useful, 1, 'tech_grn_end_3_1', ItemType.tech, 6, 'Progressive end_3', "Grn Tech: Beyond Countin'"),
    28823: ItemData(IC.useful, 1, 'tech_grn_final_1_1', ItemType.tech, 7, 'Progressive final_1', 'Grn Tech: Scrap Compactor'),
    28824: ItemData(IC.useful, 1, 'tech_grn_end_5_3', ItemType.tech, 8, 'Progressive end_5', 'Grn Tech: Ladz, Ladz, Ladz'),
    28825: ItemData(IC.useful, 1, 'tech_grn_final_1_2', ItemType.tech, 9, 'Progressive final_1', 'Grn Tech: Da Biggest Waaagh!!!'),
    28826: ItemData(IC.useful, 1, 'tech_grn_start_1_1', ItemType.tech, 2, 'Progressive start_1', 'Grn Tech: Go Fasta!'),
    28827: ItemData(IC.useful, 1, 'tech_grn_start_1_2', ItemType.tech, 4, 'Progressive start_1', "Grn Tech: No Infightin'!"),
    28828: ItemData(IC.useful, 1, 'tech_grn_start_3_2', ItemType.tech, 7, 'Progressive start_3', "Grn Tech: Big 'Un Bullies"),
    28829: ItemData(IC.useful, 1, 'tech_grn_end_4_1', ItemType.tech, 8, 'Progressive end_4', 'Grn Tech: Shiny Magic Fings'),
    28830: ItemData(IC.useful, 1, 'tech_grn_end_1_2', ItemType.tech, 8, 'Progressive end_1', 'Grn Tech: Bigga Loot Cart'),
    28831: ItemData(IC.useful, 1, 'tech_grn_end_5_1', ItemType.tech, 9, 'Progressive end_5', 'Grn Tech: Da Strongest Waaagh!'),
    28832: ItemData(IC.useful, 1, 'tech_grn_start_2_4', ItemType.tech, 1, 'Progressive start_2', 'Grn Tech: Eaga ta Fight!'),
    28833: ItemData(IC.useful, 1, 'tech_grn_extra_2_1', ItemType.tech, 2, 'Progressive extra_2', 'Grn Tech: Bigga Wagonz'),
    28834: ItemData(IC.useful, 1, 'tech_grn_extra_3_2', ItemType.tech, 3, 'Progressive extra_3', 'Grn Tech: Pointy Tusks'),
    28835: ItemData(IC.useful, 1, 'tech_grn_end_2_2', ItemType.tech, 4, 'Progressive end_2', "Grn Tech: Trollin'"),
    28836: ItemData(IC.useful, 1, 'tech_grn_mid_2_1', ItemType.tech, 5, 'Progressive mid_2', "Grn Tech: Oglok the 'Orrible"),
    28837: ItemData(IC.useful, 1, 'tech_grn_end_3_3', ItemType.tech, 8, 'Progressive end_3', "Grn Tech: Sunderin' Blades"),
    28838: ItemData(IC.useful, 1, 'tech_grn_extra_3_1', ItemType.tech, 2, 'Progressive extra_3', 'Grn Tech: Eavy Metal'),
    28839: ItemData(IC.useful, 1, 'tech_grn_extra_3_4', ItemType.tech, 3, 'Progressive extra_3', 'Grn Tech: Paint It Red!'),
    28840: ItemData(IC.useful, 1, 'tech_grn_extra_3_3', ItemType.tech, 4, 'Progressive extra_3', 'Grn Tech: Fatta Pigs'),
    28841: ItemData(IC.useful, 1, 'tech_grn_end_4_2', ItemType.tech, 9, 'Progressive end_4', 'Grn Tech: Avalanche Smash')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    29300: ItemData(IC.useful, 1, 'Progressive special_grn_nuln_grand', ItemType.building, 1, None, 'Progressive Grn Building: Special Nuln Grand'),
    29301: ItemData(IC.useful, 1, 'Progressive special_settlement_massif_orcal_grn', ItemType.building, 1, None, 'Progressive Grn Building: Special Settlement Massif Orcal Grn'),
    29302: ItemData(IC.useful, 2, 'Progressive special_settlement_massif_orcal_grn', ItemType.building, 2, None, 'Progressive Grn Building: Special Settlement Massif Orcal Grn'),
    29303: ItemData(IC.useful, 3, 'Progressive special_settlement_massif_orcal_grn', ItemType.building, 3, None, 'Progressive Grn Building: Special Settlement Massif Orcal Grn'),
    29304: ItemData(IC.useful, 4, 'Progressive special_settlement_massif_orcal_grn', ItemType.building, 4, None, 'Progressive Grn Building: Special Settlement Massif Orcal Grn'),
    29305: ItemData(IC.useful, 5, 'Progressive special_settlement_massif_orcal_grn', ItemType.building, 5, None, 'Progressive Grn Building: Special Settlement Massif Orcal Grn'),
    29306: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_grn', ItemType.building, 1, None, 'Progressive Grn Building: Foreign Slot Discovery Grn'),
    29307: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_grn', ItemType.building, 2, None, 'Progressive Grn Building: Foreign Slot Discovery Grn'),
    29308: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_grn', ItemType.building, 3, None, 'Progressive Grn Building: Foreign Slot Discovery Grn'),
    29309: ItemData(IC.useful, 1, 'Progressive grn_defence_norsca', ItemType.building, 1, None, 'Progressive Grn Building: Defence Norsca'),
    29310: ItemData(IC.useful, 1, 'Progressive grn_raiders', ItemType.building, 1, None, 'Progressive Grn Building: Raiders'),
    29311: ItemData(IC.useful, 1, 'Progressive grn_raiders', ItemType.building, 1, None, 'Progressive Grn Building: Raiders'),
    29312: ItemData(IC.useful, 1, 'Progressive grn_resource', ItemType.building, 1, None, 'Progressive Grn Building: Resource'),
    29313: ItemData(IC.useful, 1, 'Progressive special_galbaraz_mourkain_grn', ItemType.building, 1, None, 'Progressive Grn Building: Special Galbaraz Mourkain Grn'),
    29314: ItemData(IC.useful, 1, 'Progressive special_galbaraz_oathgold_grn', ItemType.building, 1, None, 'Progressive Grn Building: Special Galbaraz Oathgold Grn'),
    29315: ItemData(IC.useful, 3, 'Progressive grn_boars', ItemType.building, 3, None, 'Progressive Grn Building: Boars'),
    29316: ItemData(IC.useful, 1, 'Progressive grn_goblins', ItemType.building, 1, None, 'Progressive Grn Building: Goblins'),
    29317: ItemData(IC.useful, 2, 'Progressive grn_goblins', ItemType.building, 2, None, 'Progressive Grn Building: Goblins'),
    29318: ItemData(IC.useful, 3, 'Progressive grn_goblins', ItemType.building, 3, None, 'Progressive Grn Building: Goblins'),
    29319: ItemData(IC.useful, 2, 'Progressive grn_raiders', ItemType.building, 2, None, 'Progressive Grn Building: Raiders'),
    29320: ItemData(IC.useful, 2, 'Progressive grn_raiders', ItemType.building, 2, None, 'Progressive Grn Building: Raiders'),
    29321: ItemData(IC.useful, 2, 'Progressive grn_squigs', ItemType.building, 2, None, 'Progressive Grn Building: Squigs'),
    29322: ItemData(IC.useful, 1, 'Progressive grn_allied_outpost', ItemType.building, 1, None, 'Progressive Grn Building: Allied Outpost'),
    29323: ItemData(IC.useful, 2, 'Progressive grn_allied_outpost', ItemType.building, 2, None, 'Progressive Grn Building: Allied Outpost'),
    29324: ItemData(IC.useful, 3, 'Progressive grn_allied_outpost', ItemType.building, 3, None, 'Progressive Grn Building: Allied Outpost'),
    29325: ItemData(IC.useful, 1, 'Progressive grn_resource', ItemType.building, 1, None, 'Progressive Grn Building: Resource'),
    29326: ItemData(IC.useful, 1, 'Progressive grn_squigs', ItemType.building, 1, None, 'Progressive Grn Building: Squigs'),
    29327: ItemData(IC.useful, 1, 'Progressive grn_boars', ItemType.building, 1, None, 'Progressive Grn Building: Boars'),
    29328: ItemData(IC.useful, 2, 'Progressive grn_boars', ItemType.building, 2, None, 'Progressive Grn Building: Boars'),
    29329: ItemData(IC.useful, 1, 'Progressive grn_boss', ItemType.building, 1, None, 'Progressive Grn Building: Boss'),
    29330: ItemData(IC.useful, 2, 'Progressive grn_boss', ItemType.building, 2, None, 'Progressive Grn Building: Boss'),
    29331: ItemData(IC.useful, 3, 'Progressive grn_boss', ItemType.building, 3, None, 'Progressive Grn Building: Boss'),
    29332: ItemData(IC.useful, 1, 'Progressive grn_farm', ItemType.building, 1, None, 'Progressive Grn Building: Farm'),
    29333: ItemData(IC.useful, 2, 'Progressive grn_farm', ItemType.building, 2, None, 'Progressive Grn Building: Farm'),
    29334: ItemData(IC.useful, 3, 'Progressive grn_farm', ItemType.building, 3, None, 'Progressive Grn Building: Farm'),
    29335: ItemData(IC.useful, 1, 'Progressive grn_forest_beasts', ItemType.building, 1, None, 'Progressive Grn Building: Forest Beasts'),
    29336: ItemData(IC.useful, 2, 'Progressive grn_forest_beasts', ItemType.building, 2, None, 'Progressive Grn Building: Forest Beasts'),
    29337: ItemData(IC.useful, 3, 'Progressive grn_forest_beasts', ItemType.building, 3, None, 'Progressive Grn Building: Forest Beasts'),
    29338: ItemData(IC.useful, 1, 'Progressive grn_garrison', ItemType.building, 1, None, 'Progressive Grn Building: Garrison'),
    29339: ItemData(IC.useful, 2, 'Progressive grn_garrison', ItemType.building, 2, None, 'Progressive Grn Building: Garrison'),
    29340: ItemData(IC.useful, 1, 'Progressive grn_industry', ItemType.building, 1, None, 'Progressive Grn Building: Industry'),
    29341: ItemData(IC.useful, 1, 'Progressive grn_industry', ItemType.building, 1, None, 'Progressive Grn Building: Industry'),
    29342: ItemData(IC.useful, 2, 'Progressive grn_industry', ItemType.building, 2, None, 'Progressive Grn Building: Industry'),
    29343: ItemData(IC.useful, 2, 'Progressive grn_industry', ItemType.building, 2, None, 'Progressive Grn Building: Industry'),
    29344: ItemData(IC.useful, 3, 'Progressive grn_industry', ItemType.building, 3, None, 'Progressive Grn Building: Industry'),
    29345: ItemData(IC.useful, 3, 'Progressive grn_industry', ItemType.building, 3, None, 'Progressive Grn Building: Industry'),
    29346: ItemData(IC.useful, 1, 'Progressive grn_military', ItemType.building, 1, None, 'Progressive Grn Building: Military'),
    29347: ItemData(IC.useful, 2, 'Progressive grn_military', ItemType.building, 2, None, 'Progressive Grn Building: Military'),
    29348: ItemData(IC.useful, 3, 'Progressive grn_military', ItemType.building, 3, None, 'Progressive Grn Building: Military'),
    29349: ItemData(IC.useful, 1, 'Progressive grn_monsters', ItemType.building, 1, None, 'Progressive Grn Building: Monsters'),
    29350: ItemData(IC.useful, 2, 'Progressive grn_monsters', ItemType.building, 2, None, 'Progressive Grn Building: Monsters'),
    29351: ItemData(IC.useful, 3, 'Progressive grn_monsters', ItemType.building, 3, None, 'Progressive Grn Building: Monsters'),
    29352: ItemData(IC.useful, 1, 'Progressive grn_port', ItemType.building, 1, None, 'Progressive Grn Building: Port'),
    29353: ItemData(IC.useful, 2, 'Progressive grn_port', ItemType.building, 2, None, 'Progressive Grn Building: Port'),
    29354: ItemData(IC.useful, 3, 'Progressive grn_port', ItemType.building, 3, None, 'Progressive Grn Building: Port'),
    29355: ItemData(IC.useful, 1, 'Progressive grn_resource_gems', ItemType.building, 1, None, 'Progressive Grn Building: Gems'),
    29356: ItemData(IC.useful, 2, 'Progressive grn_resource_gems', ItemType.building, 2, None, 'Progressive Grn Building: Gems'),
    29357: ItemData(IC.useful, 3, 'Progressive grn_resource_gems', ItemType.building, 3, None, 'Progressive Grn Building: Gems'),
    29358: ItemData(IC.useful, 1, 'Progressive grn_resource_gold', ItemType.building, 1, None, 'Progressive Grn Building: Gold'),
    29359: ItemData(IC.useful, 2, 'Progressive grn_resource_gold', ItemType.building, 2, None, 'Progressive Grn Building: Gold'),
    29360: ItemData(IC.useful, 3, 'Progressive grn_resource_gold', ItemType.building, 3, None, 'Progressive Grn Building: Gold'),
    29361: ItemData(IC.useful, 1, 'Progressive grn_resource_iron', ItemType.building, 1, None, 'Progressive Grn Building: Iron'),
    29362: ItemData(IC.useful, 1, 'Progressive grn_resource_pasture_furs', ItemType.building, 1, None, 'Progressive Grn Building: Pasture Furs'),
    29363: ItemData(IC.useful, 1, 'Progressive grn_resource_timber', ItemType.building, 1, None, 'Progressive Grn Building: Timber'),
    29364: ItemData(IC.useful, 1, 'Progressive grn_settlement_major', ItemType.building, 1, None, 'Progressive Grn Building: Settlement Major'),
    29365: ItemData(IC.useful, 2, 'Progressive grn_settlement_major', ItemType.building, 2, None, 'Progressive Grn Building: Settlement Major'),
    29366: ItemData(IC.useful, 3, 'Progressive grn_settlement_major', ItemType.building, 3, None, 'Progressive Grn Building: Settlement Major'),
    29367: ItemData(IC.useful, 4, 'Progressive grn_settlement_major', ItemType.building, 4, None, 'Progressive Grn Building: Settlement Major'),
    29368: ItemData(IC.useful, 5, 'Progressive grn_settlement_major', ItemType.building, 5, None, 'Progressive Grn Building: Settlement Major'),
    29369: ItemData(IC.useful, 1, 'Progressive grn_settlement_minor', ItemType.building, 1, None, 'Progressive Grn Building: Settlement Minor'),
    29370: ItemData(IC.useful, 2, 'Progressive grn_settlement_minor', ItemType.building, 2, None, 'Progressive Grn Building: Settlement Minor'),
    29371: ItemData(IC.useful, 3, 'Progressive grn_settlement_minor', ItemType.building, 3, None, 'Progressive Grn Building: Settlement Minor'),
    29372: ItemData(IC.useful, 1, 'Progressive grn_shaman', ItemType.building, 1, None, 'Progressive Grn Building: Shaman'),
    29373: ItemData(IC.useful, 2, 'Progressive grn_shaman', ItemType.building, 2, None, 'Progressive Grn Building: Shaman'),
    29374: ItemData(IC.useful, 3, 'Progressive grn_shaman', ItemType.building, 3, None, 'Progressive Grn Building: Shaman'),
    29375: ItemData(IC.useful, 1, 'Progressive grn_walls', ItemType.building, 1, None, 'Progressive Grn Building: Walls'),
    29376: ItemData(IC.useful, 2, 'Progressive grn_walls', ItemType.building, 2, None, 'Progressive Grn Building: Walls'),
    29377: ItemData(IC.useful, 3, 'Progressive grn_walls', ItemType.building, 3, None, 'Progressive Grn Building: Walls'),
    29378: ItemData(IC.useful, 1, 'Progressive grn_workshop', ItemType.building, 1, None, 'Progressive Grn Building: Workshop'),
    29379: ItemData(IC.useful, 2, 'Progressive grn_workshop', ItemType.building, 2, None, 'Progressive Grn Building: Workshop'),
    29380: ItemData(IC.useful, 3, 'Progressive grn_workshop', ItemType.building, 3, None, 'Progressive Grn Building: Workshop')
}

progTechs: dict[int, ItemData] = {

}

special: dict[int, ItemData] = {

}