from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    32000: ItemData(IC.useful, 1, 'wh3_twa10_kho_inf_flesh_hounds_of_khorne_ror', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Hounds of the Blood Hunt (Flesh Hounds of Khorne)'),
    32001: ItemData(IC.useful, 1, 'wh3_twa08_kho_mon_bloodthirster_0_ror', ItemType.unit, 5, 'Progressive kho_inf', "Kho Unit: Khorne's Bloody Fist (Bloodthirster)"),
    32002: ItemData(IC.useful, 1, 'wh3_twa07_kho_cav_bloodcrushers_ror_0', ItemType.unit, 4, 'cavalry', "Kho Unit: Heralds of Khorne's Fury (Bloodcrushers of Khorne)"),
    32003: ItemData(IC.useful, 1, 'wh3_twa06_kho_inf_bloodletters_ror_0', ItemType.unit, 4, 'Progressive kho_inf', 'Kho Unit: Hellforged Host (Exalted Bloodletters of Khorne)'),
    32004: ItemData(IC.useful, 1, 'wh3_pro12_kho_cha_karanak', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Karanak'),
    32005: ItemData(IC.useful, 1, 'wh3_main_kho_veh_skullcannon_0', ItemType.unit, 3, 'war_beast', 'Kho Unit: Skullcannon'),
    32006: ItemData(IC.useful, 1, 'wh3_main_kho_veh_blood_shrine_0', ItemType.unit, 2, 'war_beast', 'Kho Unit: Blood Shrine of Khorne'),
    32007: ItemData(IC.useful, 1, 'wh3_main_kho_mon_spawn_of_khorne_0', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Spawn of Khorne'),
    32008: ItemData(IC.useful, 1, 'wh3_main_kho_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive kho_rng', 'Kho Unit: Soul Grinder of Khorne'),
    32009: ItemData(IC.useful, 1, 'wh3_main_kho_mon_khornataurs_1', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Minotaurs of Khorne (Great Weapons)'),
    32010: ItemData(IC.useful, 1, 'wh3_main_kho_mon_khornataurs_0', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Minotaurs of Khorne'),
    32011: ItemData(IC.useful, 1, 'wh3_main_kho_mon_bloodthirster_0', ItemType.unit, 5, 'Progressive kho_inf', 'Kho Unit: Bloodthirster'),
    32012: ItemData(IC.useful, 1, 'wh3_main_kho_inf_flesh_hounds_of_khorne_0', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Flesh Hounds of Khorne'),
    32013: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Chaos Warriors of Khorne (Dual Weapons)'),
    32014: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_1', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Chaos Warriors of Khorne (Halberds)'),
    32015: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Chaos Warriors of Khorne'),
    32016: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_warhounds_0', ItemType.unit, 1, 'Progressive kho_inf', 'Kho Unit: Chaos Warhounds of Khorne'),
    32017: ItemData(IC.useful, 1, 'wh3_main_kho_inf_chaos_furies_0', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Chaos Furies (Khorne)'),
    32018: ItemData(IC.useful, 1, 'wh3_main_kho_inf_bloodletters_1', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Exalted Bloodletters of Khorne'),
    32019: ItemData(IC.useful, 1, 'wh3_main_kho_inf_bloodletters_0', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Bloodletters of Khorne'),
    32020: ItemData(IC.useful, 1, 'wh3_main_kho_cha_herald_of_khorne_0', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Herald of Khorne'),
    32021: ItemData(IC.useful, 1, 'wh3_main_kho_cha_cultist_1', ItemType.unit, 0, 'war_beast', 'Kho Unit: Cultist of Khorne'),
    32022: ItemData(IC.useful, 1, 'wh3_main_kho_cha_cultist_0', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Cultist of Khorne'),
    32023: ItemData(IC.useful, 1, 'wh3_main_kho_cha_bloodreaper_0', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Bloodreaper'),
    32024: ItemData(IC.useful, 1, 'wh3_main_kho_cav_skullcrushers_0', ItemType.unit, 4, 'cavalry', 'Kho Unit: Skullcrushers of Khorne'),
    32025: ItemData(IC.useful, 1, 'wh3_main_kho_cav_gorebeast_chariot', ItemType.unit, 3, 'Progressive kho_veh', 'Kho Unit: Gorebeast Chariots of Khorne'),
    32026: ItemData(IC.useful, 1, 'wh3_main_kho_cav_bloodcrushers_0', ItemType.unit, 4, 'cavalry', 'Kho Unit: Bloodcrushers of Khorne'),
    32027: ItemData(IC.useful, 1, 'wh3_dlc26_kho_veh_skullcannon_ror', ItemType.unit, 3, 'war_beast', 'Kho Unit: Hellforged Bellowers (Skullcannon)'),
    32028: ItemData(IC.useful, 1, 'wh3_dlc26_kho_mon_slaughterbrute', ItemType.unit, 5, 'Progressive kho_inf', 'Kho Unit: Slaughterbrute'),
    32029: ItemData(IC.useful, 1, 'wh3_dlc26_kho_mon_bloodbeast_of_khorne', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Bloodbeasts of Khorne'),
    32030: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_wrathmongers_ror', ItemType.unit, 4, 'Progressive kho_inf', 'Kho Unit: Bloodwake Berserkers (Wrathmongers)'),
    32031: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_wrathmongers', ItemType.unit, 4, 'Progressive kho_inf', 'Kho Unit: Wrathmongers'),
    32032: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_skullreapers', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Skullreapers'),
    32033: ItemData(IC.useful, 1, 'wh3_dlc26_kho_inf_khorngors', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Khorngors'),
    32034: ItemData(IC.useful, 1, 'wh3_dlc26_kho_cha_skarr_bloodwrath', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Skarr Bloodwrath'),
    32035: ItemData(IC.useful, 1, 'wh3_dlc26_kho_cha_scyla_anfingrimm', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Scyla Anfingrimm'),
    32036: ItemData(IC.useful, 1, 'wh3_dlc26_kho_cha_bloodspeaker_warshrine', ItemType.unit, 0, 'war_beast', 'Kho Unit: Bloodspeaker'),
    32037: ItemData(IC.useful, 1, 'wh3_dlc26_kho_cha_bloodspeaker_chaos_steed', ItemType.unit, 0, 'war_beast', 'Kho Unit: Bloodspeaker'),
    32038: ItemData(IC.useful, 1, 'wh3_dlc26_kho_cha_bloodspeaker', ItemType.unit, 0, 'Progressive kho_inf', 'Kho Unit: Bloodspeaker'),
    32039: ItemData(IC.useful, 1, 'wh3_dlc26_chs_inf_chosen_mkho_ror', ItemType.unit, 4, 'Progressive kho_inf', 'Kho Unit: The Slaughtergard (Chosen of Khorne Halberds)'),
    32040: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mkho', ItemType.unit, 3, 'war_beast', 'Kho Unit: Chaos Warshrine of Khorne'),
    32041: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_forsaken_mkho', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Forsaken of Khorne'),
    32042: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mkho_dualweapons', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Chosen of Khorne (Dual Weapons)'),
    32043: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mkho', ItemType.unit, 3, 'Progressive kho_inf', 'Kho Unit: Chosen of Khorne'),
    32044: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons', ItemType.unit, 2, 'Progressive kho_inf', 'Kho Unit: Marauders of Khorne (Dual Weapons)'),
    32045: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mkho', ItemType.unit, 1, 'Progressive kho_inf', 'Kho Unit: Marauders of Khorne'),
    32046: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes', ItemType.unit, 2, 'war_beast', 'Kho Unit: Marauder Horsemen of Khorne (Throwing Axes)'),
    32047: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mkho_lances', ItemType.unit, 4, 'war_beast', 'Kho Unit: Chaos Knights of Khorne (Lances)'),
    32048: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mkho', ItemType.unit, 3, 'war_beast', 'Kho Unit: Chaos Knights of Khorne'),
    32049: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_mkho', ItemType.unit, 2, 'Progressive kho_veh', 'Kho Unit: Chaos Chariots of Khorne')
}

buildings: dict[int, ItemData] = {
    32400: ItemData(IC.useful, 1, 'wh3_dlc25_sch_special_nuln_throne_of_chaos_kho', ItemType.building, 0, 'Progressive sch_special_nuln_throne_of_chaos', 'Kho Building: {{tr:building_culture_variants_name_wh3_dlc25_sch_special_nuln_throne_of_chaoswh_main_chs_chaos}}'),
    32401: ItemData(IC.useful, 1, 'wh3_dlc26_kho_heavy_cav_4', ItemType.building, 3, 'Progressive kho_heavy_cav', 'Kho Building: Brass Ziggurat'),
    32402: ItemData(IC.useful, 1, 'wh3_dlc26_kho_monster_4', ItemType.building, 3, 'Progressive kho_monster', 'Kho Building: Blood-Drenched Herdstones'),
    32403: ItemData(IC.useful, 1, 'wh3_dlc26_kho_monster_5', ItemType.building, 4, 'Progressive kho_monster', 'Kho Building: Domain of Slaughter'),
    32404: ItemData(IC.useful, 1, 'wh3_dlc26_kho_settlement_minor_1_a', ItemType.building, 0, 'Progressive kho_settlement_minor_1', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_1_awh3_main_kho_khorne}}'),
    32405: ItemData(IC.useful, 1, 'wh3_dlc26_kho_settlement_minor_2_a', ItemType.building, 1, 'Progressive kho_settlement_minor_2', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_2_awh3_main_kho_khorne}}'),
    32406: ItemData(IC.useful, 1, 'wh3_dlc26_kho_settlement_minor_3_a', ItemType.building, 2, 'Progressive kho_settlement_minor_3', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_3_awh3_main_kho_khorne}}'),
    32407: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_kho_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_kho', 'Kho Building: Warpstone Locus'),
    32408: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_kho_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_kho', 'Kho Building: Warpstone Traps'),
    32409: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_kho_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_kho', 'Kho Building: Guarded Warpstone'),
    32410: ItemData(IC.useful, 1, 'wh3_main_kho_allied_outpost_1', ItemType.building, 0, 'Progressive kho_allied_outpost', 'Kho Building: Khornate Outpost'),
    32411: ItemData(IC.useful, 1, 'wh3_main_kho_allied_outpost_2', ItemType.building, 1, 'Progressive kho_allied_outpost', 'Kho Building: Khornate District'),
    32412: ItemData(IC.useful, 1, 'wh3_main_kho_allied_outpost_3', ItemType.building, 2, 'Progressive kho_allied_outpost', 'Kho Building: Khornate Colony'),
    32413: ItemData(IC.useful, 1, 'wh3_main_kho_bloodletters_1', ItemType.building, 0, 'Progressive kho_bloodletters', 'Kho Building: Khornate Calefactor'),
    32414: ItemData(IC.useful, 1, 'wh3_main_kho_bloodletters_2', ItemType.building, 1, 'Progressive kho_bloodletters', 'Kho Building: Khornate Furnace'),
    32415: ItemData(IC.useful, 1, 'wh3_main_kho_bloodthirster_1', ItemType.building, 0, 'Progressive kho_bloodthirster', 'Kho Building: Hunting Fields'),
    32416: ItemData(IC.useful, 1, 'wh3_main_kho_bloodthirster_2', ItemType.building, 1, 'Progressive kho_bloodthirster', 'Kho Building: The Battlefields'),
    32417: ItemData(IC.useful, 1, 'wh3_main_kho_cult_1', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Pledge of Blood'),
    32418: ItemData(IC.useful, 1, 'wh3_main_kho_cult_2', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Halls of Challenge'),
    32419: ItemData(IC.useful, 1, 'wh3_main_kho_cult_3', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Cries of Havoc'),
    32420: ItemData(IC.useful, 1, 'wh3_main_kho_cult_4', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Ritual of Blood'),
    32421: ItemData(IC.useful, 1, 'wh3_main_kho_cult_corruption_1', ItemType.building, 0, 'Progressive kho_cult_corruption', 'Kho Building: Call of Khorne'),
    32422: ItemData(IC.useful, 1, 'wh3_main_kho_cult_corruption_2', ItemType.building, 0, 'Progressive kho_cult_corruption', 'Kho Building: Battle Howls'),
    32423: ItemData(IC.useful, 1, 'wh3_main_kho_cult_magus', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Cult Magus Chambers'),
    32424: ItemData(IC.useful, 1, 'wh3_main_kho_cult_special', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Ritual of Skulls'),
    32425: ItemData(IC.useful, 1, 'wh3_main_kho_cult_teleport', ItemType.building, 0, 'Progressive kho_cult', 'Kho Building: Ritual of Summoning'),
    32426: ItemData(IC.useful, 1, 'wh3_main_kho_heavy_cav_1', ItemType.building, 0, 'Progressive kho_heavy_cav', 'Kho Building: Skull Harvester'),
    32427: ItemData(IC.useful, 1, 'wh3_main_kho_heavy_cav_2', ItemType.building, 1, 'Progressive kho_heavy_cav', 'Kho Building: Juggerplant'),
    32428: ItemData(IC.useful, 1, 'wh3_main_kho_heavy_cav_3', ItemType.building, 2, 'Progressive kho_heavy_cav', 'Kho Building: Juggerplex'),
    32429: ItemData(IC.useful, 1, 'wh3_main_kho_infra_champion_1', ItemType.building, 0, 'Progressive kho_infra_champion', 'Kho Building: Khornate Tribute'),
    32430: ItemData(IC.useful, 1, 'wh3_main_kho_infra_champion_2', ItemType.building, 1, 'Progressive kho_infra_champion', 'Kho Building: Khornate Totem'),
    32431: ItemData(IC.useful, 1, 'wh3_main_kho_infra_champion_3', ItemType.building, 2, 'Progressive kho_infra_champion', 'Kho Building: Khornate Cathedra'),
    32432: ItemData(IC.useful, 1, 'wh3_main_kho_infra_corruption_1', ItemType.building, 0, 'Progressive kho_infra_corruption', 'Kho Building: Cruor Geyser'),
    32433: ItemData(IC.useful, 1, 'wh3_main_kho_infra_corruption_2', ItemType.building, 1, 'Progressive kho_infra_corruption', 'Kho Building: Crimson Lake'),
    32434: ItemData(IC.useful, 1, 'wh3_main_kho_infra_corruption_3', ItemType.building, 2, 'Progressive kho_infra_corruption', 'Kho Building: Sea of Blood'),
    32435: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_income_1', ItemType.building, 0, 'Progressive kho_infra_growth_income', 'Kho Building: Trophy Racks'),
    32436: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_income_2', ItemType.building, 1, 'Progressive kho_infra_growth_income', 'Kho Building: Trophy Chamber'),
    32437: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_income_3', ItemType.building, 2, 'Progressive kho_infra_growth_income', 'Kho Building: Trophy Hall'),
    32438: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_replenish_1', ItemType.building, 0, 'Progressive kho_infra_growth_replenish', 'Kho Building: War Amphitheatre'),
    32439: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_replenish_2', ItemType.building, 1, 'Progressive kho_infra_growth_replenish', 'Kho Building: War Arena'),
    32440: ItemData(IC.useful, 1, 'wh3_main_kho_infra_growth_replenish_3', ItemType.building, 2, 'Progressive kho_infra_growth_replenish', 'Kho Building: War Crucible'),
    32441: ItemData(IC.useful, 1, 'wh3_main_kho_infra_order_1', ItemType.building, 0, 'Progressive kho_infra_order', 'Kho Building: Simmering Anger'),
    32442: ItemData(IC.useful, 1, 'wh3_main_kho_infra_order_2', ItemType.building, 1, 'Progressive kho_infra_order', 'Kho Building: Growing Rage'),
    32443: ItemData(IC.useful, 1, 'wh3_main_kho_infra_order_3', ItemType.building, 2, 'Progressive kho_infra_order', 'Kho Building: Apocalyptic Fury'),
    32444: ItemData(IC.useful, 1, 'wh3_main_kho_monster_1', ItemType.building, 0, 'Progressive kho_monster', 'Kho Building: Kennels'),
    32445: ItemData(IC.useful, 1, 'wh3_main_kho_monster_2', ItemType.building, 1, 'Progressive kho_monster', 'Kho Building: Baleful Lair'),
    32446: ItemData(IC.useful, 1, 'wh3_main_kho_monster_3', ItemType.building, 2, 'Progressive kho_monster', 'Kho Building: Abattoir'),
    32447: ItemData(IC.useful, 1, 'wh3_main_kho_port_1', ItemType.building, 0, 'Progressive kho_port', 'Kho Building: Infernal Harbour'),
    32448: ItemData(IC.useful, 1, 'wh3_main_kho_port_2', ItemType.building, 1, 'Progressive kho_port', 'Kho Building: Hell Port'),
    32449: ItemData(IC.useful, 1, 'wh3_main_kho_port_3', ItemType.building, 2, 'Progressive kho_port', 'Kho Building: Eye of Terror'),
    32450: ItemData(IC.useful, 1, 'wh3_main_kho_resource_animals_1', ItemType.building, 0, 'Progressive kho_resource_animals', 'Kho Building: Cultist Camp (Animals)'),
    32451: ItemData(IC.useful, 1, 'wh3_main_kho_resource_animals_2', ItemType.building, 1, 'Progressive kho_resource_animals', 'Kho Building: Cultist Outpost (Animals)'),
    32452: ItemData(IC.useful, 1, 'wh3_main_kho_resource_animals_3', ItemType.building, 2, 'Progressive kho_resource_animals', 'Kho Building: Cultist Enclave (Animals)'),
    32453: ItemData(IC.useful, 1, 'wh3_main_kho_resource_dyes_1', ItemType.building, 0, 'Progressive kho_resource_dyes', 'Kho Building: Cultist Camp (Dyes)'),
    32454: ItemData(IC.useful, 1, 'wh3_main_kho_resource_dyes_2', ItemType.building, 1, 'Progressive kho_resource_dyes', 'Kho Building: Cultist Outpost (Dyes)'),
    32455: ItemData(IC.useful, 1, 'wh3_main_kho_resource_dyes_3', ItemType.building, 2, 'Progressive kho_resource_dyes', 'Kho Building: Cultist Enclave (Dyes)'),
    32456: ItemData(IC.useful, 1, 'wh3_main_kho_resource_furs_1', ItemType.building, 0, 'Progressive kho_resource_furs', 'Kho Building: Cultist Camp (Furs)'),
    32457: ItemData(IC.useful, 1, 'wh3_main_kho_resource_furs_2', ItemType.building, 1, 'Progressive kho_resource_furs', 'Kho Building: Cultist Outpost (Furs)'),
    32458: ItemData(IC.useful, 1, 'wh3_main_kho_resource_furs_3', ItemType.building, 2, 'Progressive kho_resource_furs', 'Kho Building: Cultist Enclave (Furs)'),
    32459: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gems_1', ItemType.building, 0, 'Progressive kho_resource_gems', 'Kho Building: Cultist Camp (Gems)'),
    32460: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gems_2', ItemType.building, 1, 'Progressive kho_resource_gems', 'Kho Building: Cultist Outpost (Gems)'),
    32461: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gems_3', ItemType.building, 2, 'Progressive kho_resource_gems', 'Kho Building: Cultist Enclave (Gems)'),
    32462: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gold_1', ItemType.building, 0, 'Progressive kho_resource_gold', 'Kho Building: Cultist Camp (Gold)'),
    32463: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gold_2', ItemType.building, 1, 'Progressive kho_resource_gold', 'Kho Building: Cultist Outpost (Gold)'),
    32464: ItemData(IC.useful, 1, 'wh3_main_kho_resource_gold_3', ItemType.building, 2, 'Progressive kho_resource_gold', 'Kho Building: Cultist Enclave (Gold)'),
    32465: ItemData(IC.useful, 1, 'wh3_main_kho_resource_iron_1', ItemType.building, 0, 'Progressive kho_resource_iron', 'Kho Building: Cultist Camp (Iron)'),
    32466: ItemData(IC.useful, 1, 'wh3_main_kho_resource_iron_2', ItemType.building, 1, 'Progressive kho_resource_iron', 'Kho Building: Cultist Outpost (Iron)'),
    32467: ItemData(IC.useful, 1, 'wh3_main_kho_resource_iron_3', ItemType.building, 2, 'Progressive kho_resource_iron', 'Kho Building: Cultist Enclave (Iron)'),
    32468: ItemData(IC.useful, 1, 'wh3_main_kho_resource_ivory_1', ItemType.building, 0, 'Progressive kho_resource_ivory', 'Kho Building: Cultist Camp (Tusks)'),
    32469: ItemData(IC.useful, 1, 'wh3_main_kho_resource_ivory_2', ItemType.building, 1, 'Progressive kho_resource_ivory', 'Kho Building: Cultist Outpost (Tusks)'),
    32470: ItemData(IC.useful, 1, 'wh3_main_kho_resource_ivory_3', ItemType.building, 2, 'Progressive kho_resource_ivory', 'Kho Building: Cultist Enclave (Tusks)'),
    32471: ItemData(IC.useful, 1, 'wh3_main_kho_resource_marble_1', ItemType.building, 0, 'Progressive kho_resource_marble', 'Kho Building: Cultist Camp (Marble)'),
    32472: ItemData(IC.useful, 1, 'wh3_main_kho_resource_marble_2', ItemType.building, 1, 'Progressive kho_resource_marble', 'Kho Building: Cultist Outpost (Marble)'),
    32473: ItemData(IC.useful, 1, 'wh3_main_kho_resource_marble_3', ItemType.building, 2, 'Progressive kho_resource_marble', 'Kho Building: Cultist Enclave (Marble)'),
    32474: ItemData(IC.useful, 1, 'wh3_main_kho_resource_medicine_1', ItemType.building, 0, 'Progressive kho_resource_medicine', 'Kho Building: Cultist Camp (Medicine)'),
    32475: ItemData(IC.useful, 1, 'wh3_main_kho_resource_medicine_2', ItemType.building, 1, 'Progressive kho_resource_medicine', 'Kho Building: Cultist Outpost (Medicine)'),
    32476: ItemData(IC.useful, 1, 'wh3_main_kho_resource_medicine_3', ItemType.building, 2, 'Progressive kho_resource_medicine', 'Kho Building: Cultist Enclave (Medicine)'),
    32477: ItemData(IC.useful, 1, 'wh3_main_kho_resource_obsidian_1', ItemType.building, 0, 'Progressive kho_resource_obsidian', 'Kho Building: Cultist Camp (Obsidian)'),
    32478: ItemData(IC.useful, 1, 'wh3_main_kho_resource_obsidian_2', ItemType.building, 1, 'Progressive kho_resource_obsidian', 'Kho Building: Cultist Outpost (Obsidian)'),
    32479: ItemData(IC.useful, 1, 'wh3_main_kho_resource_obsidian_3', ItemType.building, 2, 'Progressive kho_resource_obsidian', 'Kho Building: Cultist Enclave (Obsidian)'),
    32480: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pasture_1', ItemType.building, 0, 'Progressive kho_resource_pasture', 'Kho Building: Cultist Camp (Pasture)'),
    32481: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pasture_2', ItemType.building, 1, 'Progressive kho_resource_pasture', 'Kho Building: Cultist Outpost (Pasture)'),
    32482: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pasture_3', ItemType.building, 2, 'Progressive kho_resource_pasture', 'Kho Building: Cultist Enclave (Pasture)'),
    32483: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pottery_1', ItemType.building, 0, 'Progressive kho_resource_pottery', 'Kho Building: Cultist Camp (Pottery)'),
    32484: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pottery_2', ItemType.building, 1, 'Progressive kho_resource_pottery', 'Kho Building: Cultist Outpost (Pottery)'),
    32485: ItemData(IC.useful, 1, 'wh3_main_kho_resource_pottery_3', ItemType.building, 2, 'Progressive kho_resource_pottery', 'Kho Building: Cultist Enclave (Pottery)'),
    32486: ItemData(IC.useful, 1, 'wh3_main_kho_resource_salt_1', ItemType.building, 0, 'Progressive kho_resource_salt', 'Kho Building: Cultist Camp (Salt)'),
    32487: ItemData(IC.useful, 1, 'wh3_main_kho_resource_salt_2', ItemType.building, 1, 'Progressive kho_resource_salt', 'Kho Building: Cultist Outpost (Salt)'),
    32488: ItemData(IC.useful, 1, 'wh3_main_kho_resource_salt_3', ItemType.building, 2, 'Progressive kho_resource_salt', 'Kho Building: Cultist Enclave (Salt)'),
    32489: ItemData(IC.useful, 1, 'wh3_main_kho_resource_spices_1', ItemType.building, 0, 'Progressive kho_resource_spices', 'Kho Building: Cultist Camp (Spices)'),
    32490: ItemData(IC.useful, 1, 'wh3_main_kho_resource_spices_2', ItemType.building, 1, 'Progressive kho_resource_spices', 'Kho Building: Cultist Outpost (Spices)'),
    32491: ItemData(IC.useful, 1, 'wh3_main_kho_resource_spices_3', ItemType.building, 2, 'Progressive kho_resource_spices', 'Kho Building: Cultist Enclave (Spices)'),
    32492: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wine_1', ItemType.building, 0, 'Progressive kho_resource_wine', 'Kho Building: Cultist Camp (Wine)'),
    32493: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wine_2', ItemType.building, 1, 'Progressive kho_resource_wine', 'Kho Building: Cultist Outpost (Wine)'),
    32494: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wine_3', ItemType.building, 2, 'Progressive kho_resource_wine', 'Kho Building: Cultist Enclave (Wine)'),
    32495: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wood_1', ItemType.building, 0, 'Progressive kho_resource_wood', 'Kho Building: Cultist Camp (Wood)'),
    32496: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wood_2', ItemType.building, 1, 'Progressive kho_resource_wood', 'Kho Building: Cultist Outpost (Wood)'),
    32497: ItemData(IC.useful, 1, 'wh3_main_kho_resource_wood_3', ItemType.building, 2, 'Progressive kho_resource_wood', 'Kho Building: Cultist Enclave (Wood)'),
    32498: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_1_a', ItemType.building, 0, 'Progressive kho_settlement_major_1', 'Kho Building: Soul Keep'),
    32499: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_1', ItemType.building, 0, 'Progressive kho_settlement_major', 'Kho Building: Dimensional Tear'),
    32500: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_2_a', ItemType.building, 1, 'Progressive kho_settlement_major_2', 'Kho Building: Dark Bastion'),
    32501: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_2', ItemType.building, 1, 'Progressive kho_settlement_major', 'Kho Building: Dimensional Breach'),
    32502: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_3_a', ItemType.building, 2, 'Progressive kho_settlement_major_3', 'Kho Building: Infernal Citadel'),
    32503: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_3', ItemType.building, 2, 'Progressive kho_settlement_major', 'Kho Building: Dimensional Rift'),
    32504: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_4_a', ItemType.building, 3, 'Progressive kho_settlement_major_4', 'Kho Building: Daemonic Fortress'),
    32505: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_4', ItemType.building, 3, 'Progressive kho_settlement_major', 'Kho Building: Dimensional Nexus'),
    32506: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_5_a', ItemType.building, 4, 'Progressive kho_settlement_major_5', 'Kho Building: Chaos Dreadhold'),
    32507: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_major_5', ItemType.building, 4, 'Progressive kho_settlement_major', 'Kho Building: Dimensional Cascade'),
    32508: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_minor_1', ItemType.building, 0, 'Progressive kho_settlement_minor', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_1wh3_main_kho_khorne}}'),
    32509: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_minor_2', ItemType.building, 1, 'Progressive kho_settlement_minor', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_2wh3_main_kho_khorne}}'),
    32510: ItemData(IC.useful, 1, 'wh3_main_kho_settlement_minor_3', ItemType.building, 2, 'Progressive kho_settlement_minor', 'Kho Building: {{tr:building_culture_variants_name_wh3_main_kho_settlement_major_3wh3_main_kho_khorne}}'),
    32511: ItemData(IC.useful, 1, 'wh3_main_kho_vehicle_1', ItemType.building, 0, 'Progressive kho_vehicle', 'Kho Building: Foundry of Scythes'),
    32512: ItemData(IC.useful, 1, 'wh3_main_kho_vehicle_2', ItemType.building, 1, 'Progressive kho_vehicle', 'Kho Building: Foundry of Blood'),
    32513: ItemData(IC.useful, 1, 'wh3_main_kho_vehicle_3', ItemType.building, 2, 'Progressive kho_vehicle', 'Kho Building: Foundry of Skulls'),
    32514: ItemData(IC.useful, 1, 'wh3_main_kho_walls_major_1', ItemType.building, 0, 'Progressive kho_walls_major', 'Kho Building: Daemonic Lurkers'),
    32515: ItemData(IC.useful, 1, 'wh3_main_kho_walls_major_2', ItemType.building, 1, 'Progressive kho_walls_major', 'Kho Building: Daemonic Gathering'),
    32516: ItemData(IC.useful, 1, 'wh3_main_kho_walls_major_3', ItemType.building, 2, 'Progressive kho_walls_major', 'Kho Building: Daemonic Locus'),
    32517: ItemData(IC.useful, 1, 'wh3_main_kho_walls_minor_1', ItemType.building, 0, 'Progressive kho_walls_minor', 'Kho Building: Three-Headed Scenthounds'),
    32518: ItemData(IC.useful, 1, 'wh3_main_kho_walls_minor_2', ItemType.building, 1, 'Progressive kho_walls_minor', 'Kho Building: Brass Fortifications'),
    32519: ItemData(IC.useful, 1, 'wh3_main_kho_warriors_1', ItemType.building, 0, 'Progressive kho_warriors', 'Kho Building: The Forge'),
    32520: ItemData(IC.useful, 1, 'wh3_main_kho_warriors_2', ItemType.building, 1, 'Progressive kho_warriors', 'Kho Building: The Armoury'),
    32521: ItemData(IC.useful, 1, 'wh3_main_kho_warriors_3', ItemType.building, 2, 'Progressive kho_warriors', 'Kho Building: The Arsenal'),
    32522: ItemData(IC.useful, 1, 'wh3_main_special_galbaraz_mourkain_kho_1', ItemType.building, 0, 'Progressive special_galbaraz_mourkain_kho', 'Kho Building: Ancient Boneyard')
}

techs: dict[int, ItemData] = {
    32800: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_4', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: Denying the Warp'),
    32801: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_5', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Unburning Might'),
    32802: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_7', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Daemonic-Melding'),
    32803: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_1', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Wrathful Slaughter'),
    32804: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_2', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: The Way of Wrath'),
    32805: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_5', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: Gates of Wrath'),
    32806: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_6', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Juggernaut Anger'),
    32807: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_8', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: Skull of the Enemy'),
    32808: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_5', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: Glorious Deaths'),
    32809: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_7', ItemType.tech, 5, 'Progressive tech_kho', 'Kho Tech: Exist Always'),
    32810: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_2', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Siege Rectitude'),
    32811: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_1_1', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Red in Hoof & Blade'),
    32812: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_2_1', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Bone & Brass As One'),
    32813: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_8', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Skulls to Bring'),
    32814: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_7', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Renegotiate Bargains'),
    32815: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_3', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Defiant Muster'),
    32816: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_6', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Abjuration-Reaper'),
    32817: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_5', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Favoured One'),
    32818: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_6', ItemType.tech, 4, 'Progressive tech_kho', 'Kho Tech: Repel the Honourless'),
    32819: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_1_2', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Let Fury Fly'),
    32820: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_2_2', ItemType.tech, 2, 'Progressive tech_kho', "Kho Tech: Break the Mountain's Back"),
    32821: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_blood_hosts_1', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: The Living Fire'),
    32822: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_2', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: Skull Harvesting'),
    32823: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_6', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: Raging Denial'),
    32824: ItemData(IC.useful, 1, 'wh3_main_tech_kho_2_2', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: War Tributes'),
    32825: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_6', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Better Breeding'),
    32826: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_3', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Gift of Martial Skill'),
    32827: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_2', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Deny Them Life'),
    32828: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_3', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: Staunch Defender'),
    32829: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_7', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Hail Skullcrusher'),
    32830: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_8', ItemType.tech, 3, 'Progressive tech_kho', 'Kho Tech: Return for Honour'),
    32831: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_campaign_4_3', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Sow Death, Reap Blood'),
    32832: ItemData(IC.useful, 1, 'wh3_main_tech_kho_2_4', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Spoils of Battle'),
    32833: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_1', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Slaughtererâ€™s Pride'),
    32834: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_2', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Admiring the Corrupt'),
    32835: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_7', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Pride to Continue'),
    32836: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_8', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Skull Flensing'),
    32837: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_4', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Reaper of Ages'),
    32838: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_4', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Bitter Raiding'),
    32839: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_8', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Skulls for the Skull Throne'),
    32840: ItemData(IC.useful, 1, 'wh3_main_tech_kho_2_3', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: War Leaders'),
    32841: ItemData(IC.useful, 1, 'wh3_main_tech_kho_2_8', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Hounds of War'),
    32842: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_3', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Harvesterâ€™s Pride'),
    32843: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_4', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Skull-Reaper'),
    32844: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_3_2', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Giant Slayer'),
    32845: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_campaign_4_1', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Nothing Upon Nothing'),
    32846: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_1', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Serial Killing'),
    32847: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_3', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Spread Rage'),
    32848: ItemData(IC.useful, 1, 'wh3_main_tech_kho_2_7', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Hungrier Spawn'),
    32849: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_1', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Beast Fighting'),
    32850: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_2', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Unrelenting Conflict'),
    32851: ItemData(IC.useful, 1, 'wh3_main_tech_kho_5_4', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Too Hateful to Die'),
    32852: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_1', ItemType.tech, 0, 'Progressive tech_kho', 'Kho Tech: Gift of Defiance'),
    32853: ItemData(IC.useful, 1, 'wh3_main_tech_kho_8_1', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Honour in Blood'),
    32854: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_3_1', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: War-Born'),
    32855: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_4_1', ItemType.tech, 1, 'Progressive tech_kho', 'Kho Tech: Lord of Monstrosities'),
    32856: ItemData(IC.useful, 1, 'wh3_dlc26_tech_kho_battle_3_3', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Blood Whirlwind'),
    32857: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_5', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Blood Feasting'),
    32858: ItemData(IC.useful, 1, 'wh3_main_tech_kho_1_7', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Rage Within'),
    32859: ItemData(IC.useful, 1, 'wh3_main_tech_kho_3_5', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Killerâ€™s Trophy'),
    32860: ItemData(IC.useful, 1, 'wh3_main_tech_kho_4_6', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Snorting Blood'),
    32861: ItemData(IC.useful, 1, 'wh3_main_tech_kho_6_4', ItemType.tech, 2, 'Progressive tech_kho', 'Kho Tech: Deathbringers Defiant')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    33300: ItemData(IC.useful, 1, 'Progressive sch_special_nuln_throne_of_chaos', ItemType.building, 1, None, 'Progressive Kho Building: Sch Special Nuln Throne Of Chaos'),
    33301: ItemData(IC.useful, 4, 'Progressive kho_heavy_cav', ItemType.building, 4, None, 'Progressive Kho Building: Heavy Cav'),
    33302: ItemData(IC.useful, 4, 'Progressive kho_monster', ItemType.building, 4, None, 'Progressive Kho Building: Monster'),
    33303: ItemData(IC.useful, 5, 'Progressive kho_monster', ItemType.building, 5, None, 'Progressive Kho Building: Monster'),
    33304: ItemData(IC.useful, 1, 'Progressive kho_settlement_minor_1', ItemType.building, 1, None, 'Progressive Kho Building: Settlement Minor 1'),
    33305: ItemData(IC.useful, 2, 'Progressive kho_settlement_minor_2', ItemType.building, 2, None, 'Progressive Kho Building: Settlement Minor 2'),
    33306: ItemData(IC.useful, 3, 'Progressive kho_settlement_minor_3', ItemType.building, 3, None, 'Progressive Kho Building: Settlement Minor 3'),
    33307: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_kho', ItemType.building, 1, None, 'Progressive Kho Building: Foreign Slot Discovery Kho'),
    33308: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_kho', ItemType.building, 2, None, 'Progressive Kho Building: Foreign Slot Discovery Kho'),
    33309: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_kho', ItemType.building, 3, None, 'Progressive Kho Building: Foreign Slot Discovery Kho'),
    33310: ItemData(IC.useful, 1, 'Progressive kho_allied_outpost', ItemType.building, 1, None, 'Progressive Kho Building: Allied Outpost'),
    33311: ItemData(IC.useful, 2, 'Progressive kho_allied_outpost', ItemType.building, 2, None, 'Progressive Kho Building: Allied Outpost'),
    33312: ItemData(IC.useful, 3, 'Progressive kho_allied_outpost', ItemType.building, 3, None, 'Progressive Kho Building: Allied Outpost'),
    33313: ItemData(IC.useful, 1, 'Progressive kho_bloodletters', ItemType.building, 1, None, 'Progressive Kho Building: Bloodletters'),
    33314: ItemData(IC.useful, 2, 'Progressive kho_bloodletters', ItemType.building, 2, None, 'Progressive Kho Building: Bloodletters'),
    33315: ItemData(IC.useful, 1, 'Progressive kho_bloodthirster', ItemType.building, 1, None, 'Progressive Kho Building: Bloodthirster'),
    33316: ItemData(IC.useful, 2, 'Progressive kho_bloodthirster', ItemType.building, 2, None, 'Progressive Kho Building: Bloodthirster'),
    33317: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33318: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33319: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33320: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33321: ItemData(IC.useful, 1, 'Progressive kho_cult_corruption', ItemType.building, 1, None, 'Progressive Kho Building: Cult Corruption'),
    33322: ItemData(IC.useful, 1, 'Progressive kho_cult_corruption', ItemType.building, 1, None, 'Progressive Kho Building: Cult Corruption'),
    33323: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33324: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33325: ItemData(IC.useful, 1, 'Progressive kho_cult', ItemType.building, 1, None, 'Progressive Kho Building: Cult'),
    33326: ItemData(IC.useful, 1, 'Progressive kho_heavy_cav', ItemType.building, 1, None, 'Progressive Kho Building: Heavy Cav'),
    33327: ItemData(IC.useful, 2, 'Progressive kho_heavy_cav', ItemType.building, 2, None, 'Progressive Kho Building: Heavy Cav'),
    33328: ItemData(IC.useful, 3, 'Progressive kho_heavy_cav', ItemType.building, 3, None, 'Progressive Kho Building: Heavy Cav'),
    33329: ItemData(IC.useful, 1, 'Progressive kho_infra_champion', ItemType.building, 1, None, 'Progressive Kho Building: Infra Champion'),
    33330: ItemData(IC.useful, 2, 'Progressive kho_infra_champion', ItemType.building, 2, None, 'Progressive Kho Building: Infra Champion'),
    33331: ItemData(IC.useful, 3, 'Progressive kho_infra_champion', ItemType.building, 3, None, 'Progressive Kho Building: Infra Champion'),
    33332: ItemData(IC.useful, 1, 'Progressive kho_infra_corruption', ItemType.building, 1, None, 'Progressive Kho Building: Infra Corruption'),
    33333: ItemData(IC.useful, 2, 'Progressive kho_infra_corruption', ItemType.building, 2, None, 'Progressive Kho Building: Infra Corruption'),
    33334: ItemData(IC.useful, 3, 'Progressive kho_infra_corruption', ItemType.building, 3, None, 'Progressive Kho Building: Infra Corruption'),
    33335: ItemData(IC.useful, 1, 'Progressive kho_infra_growth_income', ItemType.building, 1, None, 'Progressive Kho Building: Infra Growth Income'),
    33336: ItemData(IC.useful, 2, 'Progressive kho_infra_growth_income', ItemType.building, 2, None, 'Progressive Kho Building: Infra Growth Income'),
    33337: ItemData(IC.useful, 3, 'Progressive kho_infra_growth_income', ItemType.building, 3, None, 'Progressive Kho Building: Infra Growth Income'),
    33338: ItemData(IC.useful, 1, 'Progressive kho_infra_growth_replenish', ItemType.building, 1, None, 'Progressive Kho Building: Infra Growth Replenish'),
    33339: ItemData(IC.useful, 2, 'Progressive kho_infra_growth_replenish', ItemType.building, 2, None, 'Progressive Kho Building: Infra Growth Replenish'),
    33340: ItemData(IC.useful, 3, 'Progressive kho_infra_growth_replenish', ItemType.building, 3, None, 'Progressive Kho Building: Infra Growth Replenish'),
    33341: ItemData(IC.useful, 1, 'Progressive kho_infra_order', ItemType.building, 1, None, 'Progressive Kho Building: Infra Order'),
    33342: ItemData(IC.useful, 2, 'Progressive kho_infra_order', ItemType.building, 2, None, 'Progressive Kho Building: Infra Order'),
    33343: ItemData(IC.useful, 3, 'Progressive kho_infra_order', ItemType.building, 3, None, 'Progressive Kho Building: Infra Order'),
    33344: ItemData(IC.useful, 1, 'Progressive kho_monster', ItemType.building, 1, None, 'Progressive Kho Building: Monster'),
    33345: ItemData(IC.useful, 2, 'Progressive kho_monster', ItemType.building, 2, None, 'Progressive Kho Building: Monster'),
    33346: ItemData(IC.useful, 3, 'Progressive kho_monster', ItemType.building, 3, None, 'Progressive Kho Building: Monster'),
    33347: ItemData(IC.useful, 1, 'Progressive kho_port', ItemType.building, 1, None, 'Progressive Kho Building: Port'),
    33348: ItemData(IC.useful, 2, 'Progressive kho_port', ItemType.building, 2, None, 'Progressive Kho Building: Port'),
    33349: ItemData(IC.useful, 3, 'Progressive kho_port', ItemType.building, 3, None, 'Progressive Kho Building: Port'),
    33350: ItemData(IC.useful, 1, 'Progressive kho_resource_animals', ItemType.building, 1, None, 'Progressive Kho Building: Animals'),
    33351: ItemData(IC.useful, 2, 'Progressive kho_resource_animals', ItemType.building, 2, None, 'Progressive Kho Building: Animals'),
    33352: ItemData(IC.useful, 3, 'Progressive kho_resource_animals', ItemType.building, 3, None, 'Progressive Kho Building: Animals'),
    33353: ItemData(IC.useful, 1, 'Progressive kho_resource_dyes', ItemType.building, 1, None, 'Progressive Kho Building: Dyes'),
    33354: ItemData(IC.useful, 2, 'Progressive kho_resource_dyes', ItemType.building, 2, None, 'Progressive Kho Building: Dyes'),
    33355: ItemData(IC.useful, 3, 'Progressive kho_resource_dyes', ItemType.building, 3, None, 'Progressive Kho Building: Dyes'),
    33356: ItemData(IC.useful, 1, 'Progressive kho_resource_furs', ItemType.building, 1, None, 'Progressive Kho Building: Furs'),
    33357: ItemData(IC.useful, 2, 'Progressive kho_resource_furs', ItemType.building, 2, None, 'Progressive Kho Building: Furs'),
    33358: ItemData(IC.useful, 3, 'Progressive kho_resource_furs', ItemType.building, 3, None, 'Progressive Kho Building: Furs'),
    33359: ItemData(IC.useful, 1, 'Progressive kho_resource_gems', ItemType.building, 1, None, 'Progressive Kho Building: Gems'),
    33360: ItemData(IC.useful, 2, 'Progressive kho_resource_gems', ItemType.building, 2, None, 'Progressive Kho Building: Gems'),
    33361: ItemData(IC.useful, 3, 'Progressive kho_resource_gems', ItemType.building, 3, None, 'Progressive Kho Building: Gems'),
    33362: ItemData(IC.useful, 1, 'Progressive kho_resource_gold', ItemType.building, 1, None, 'Progressive Kho Building: Gold'),
    33363: ItemData(IC.useful, 2, 'Progressive kho_resource_gold', ItemType.building, 2, None, 'Progressive Kho Building: Gold'),
    33364: ItemData(IC.useful, 3, 'Progressive kho_resource_gold', ItemType.building, 3, None, 'Progressive Kho Building: Gold'),
    33365: ItemData(IC.useful, 1, 'Progressive kho_resource_iron', ItemType.building, 1, None, 'Progressive Kho Building: Iron'),
    33366: ItemData(IC.useful, 2, 'Progressive kho_resource_iron', ItemType.building, 2, None, 'Progressive Kho Building: Iron'),
    33367: ItemData(IC.useful, 3, 'Progressive kho_resource_iron', ItemType.building, 3, None, 'Progressive Kho Building: Iron'),
    33368: ItemData(IC.useful, 1, 'Progressive kho_resource_ivory', ItemType.building, 1, None, 'Progressive Kho Building: Ivory'),
    33369: ItemData(IC.useful, 2, 'Progressive kho_resource_ivory', ItemType.building, 2, None, 'Progressive Kho Building: Ivory'),
    33370: ItemData(IC.useful, 3, 'Progressive kho_resource_ivory', ItemType.building, 3, None, 'Progressive Kho Building: Ivory'),
    33371: ItemData(IC.useful, 1, 'Progressive kho_resource_marble', ItemType.building, 1, None, 'Progressive Kho Building: Marble'),
    33372: ItemData(IC.useful, 2, 'Progressive kho_resource_marble', ItemType.building, 2, None, 'Progressive Kho Building: Marble'),
    33373: ItemData(IC.useful, 3, 'Progressive kho_resource_marble', ItemType.building, 3, None, 'Progressive Kho Building: Marble'),
    33374: ItemData(IC.useful, 1, 'Progressive kho_resource_medicine', ItemType.building, 1, None, 'Progressive Kho Building: Medicine'),
    33375: ItemData(IC.useful, 2, 'Progressive kho_resource_medicine', ItemType.building, 2, None, 'Progressive Kho Building: Medicine'),
    33376: ItemData(IC.useful, 3, 'Progressive kho_resource_medicine', ItemType.building, 3, None, 'Progressive Kho Building: Medicine'),
    33377: ItemData(IC.useful, 1, 'Progressive kho_resource_obsidian', ItemType.building, 1, None, 'Progressive Kho Building: Obsidian'),
    33378: ItemData(IC.useful, 2, 'Progressive kho_resource_obsidian', ItemType.building, 2, None, 'Progressive Kho Building: Obsidian'),
    33379: ItemData(IC.useful, 3, 'Progressive kho_resource_obsidian', ItemType.building, 3, None, 'Progressive Kho Building: Obsidian'),
    33380: ItemData(IC.useful, 1, 'Progressive kho_resource_pasture', ItemType.building, 1, None, 'Progressive Kho Building: Pasture'),
    33381: ItemData(IC.useful, 2, 'Progressive kho_resource_pasture', ItemType.building, 2, None, 'Progressive Kho Building: Pasture'),
    33382: ItemData(IC.useful, 3, 'Progressive kho_resource_pasture', ItemType.building, 3, None, 'Progressive Kho Building: Pasture'),
    33383: ItemData(IC.useful, 1, 'Progressive kho_resource_pottery', ItemType.building, 1, None, 'Progressive Kho Building: Pottery'),
    33384: ItemData(IC.useful, 2, 'Progressive kho_resource_pottery', ItemType.building, 2, None, 'Progressive Kho Building: Pottery'),
    33385: ItemData(IC.useful, 3, 'Progressive kho_resource_pottery', ItemType.building, 3, None, 'Progressive Kho Building: Pottery'),
    33386: ItemData(IC.useful, 1, 'Progressive kho_resource_salt', ItemType.building, 1, None, 'Progressive Kho Building: Salt'),
    33387: ItemData(IC.useful, 2, 'Progressive kho_resource_salt', ItemType.building, 2, None, 'Progressive Kho Building: Salt'),
    33388: ItemData(IC.useful, 3, 'Progressive kho_resource_salt', ItemType.building, 3, None, 'Progressive Kho Building: Salt'),
    33389: ItemData(IC.useful, 1, 'Progressive kho_resource_spices', ItemType.building, 1, None, 'Progressive Kho Building: Spices'),
    33390: ItemData(IC.useful, 2, 'Progressive kho_resource_spices', ItemType.building, 2, None, 'Progressive Kho Building: Spices'),
    33391: ItemData(IC.useful, 3, 'Progressive kho_resource_spices', ItemType.building, 3, None, 'Progressive Kho Building: Spices'),
    33392: ItemData(IC.useful, 1, 'Progressive kho_resource_wine', ItemType.building, 1, None, 'Progressive Kho Building: Wine'),
    33393: ItemData(IC.useful, 2, 'Progressive kho_resource_wine', ItemType.building, 2, None, 'Progressive Kho Building: Wine'),
    33394: ItemData(IC.useful, 3, 'Progressive kho_resource_wine', ItemType.building, 3, None, 'Progressive Kho Building: Wine'),
    33395: ItemData(IC.useful, 1, 'Progressive kho_resource_wood', ItemType.building, 1, None, 'Progressive Kho Building: Wood'),
    33396: ItemData(IC.useful, 2, 'Progressive kho_resource_wood', ItemType.building, 2, None, 'Progressive Kho Building: Wood'),
    33397: ItemData(IC.useful, 3, 'Progressive kho_resource_wood', ItemType.building, 3, None, 'Progressive Kho Building: Wood'),
    33398: ItemData(IC.useful, 1, 'Progressive kho_settlement_major_1', ItemType.building, 1, None, 'Progressive Kho Building: Settlement Major 1'),
    33399: ItemData(IC.useful, 1, 'Progressive kho_settlement_major', ItemType.building, 1, None, 'Progressive Kho Building: Settlement Major'),
    33400: ItemData(IC.useful, 2, 'Progressive kho_settlement_major_2', ItemType.building, 2, None, 'Progressive Kho Building: Settlement Major 2'),
    33401: ItemData(IC.useful, 2, 'Progressive kho_settlement_major', ItemType.building, 2, None, 'Progressive Kho Building: Settlement Major'),
    33402: ItemData(IC.useful, 3, 'Progressive kho_settlement_major_3', ItemType.building, 3, None, 'Progressive Kho Building: Settlement Major 3'),
    33403: ItemData(IC.useful, 3, 'Progressive kho_settlement_major', ItemType.building, 3, None, 'Progressive Kho Building: Settlement Major'),
    33404: ItemData(IC.useful, 4, 'Progressive kho_settlement_major_4', ItemType.building, 4, None, 'Progressive Kho Building: Settlement Major 4'),
    33405: ItemData(IC.useful, 4, 'Progressive kho_settlement_major', ItemType.building, 4, None, 'Progressive Kho Building: Settlement Major'),
    33406: ItemData(IC.useful, 5, 'Progressive kho_settlement_major_5', ItemType.building, 5, None, 'Progressive Kho Building: Settlement Major 5'),
    33407: ItemData(IC.useful, 5, 'Progressive kho_settlement_major', ItemType.building, 5, None, 'Progressive Kho Building: Settlement Major'),
    33408: ItemData(IC.useful, 1, 'Progressive kho_settlement_minor', ItemType.building, 1, None, 'Progressive Kho Building: Settlement Minor'),
    33409: ItemData(IC.useful, 2, 'Progressive kho_settlement_minor', ItemType.building, 2, None, 'Progressive Kho Building: Settlement Minor'),
    33410: ItemData(IC.useful, 3, 'Progressive kho_settlement_minor', ItemType.building, 3, None, 'Progressive Kho Building: Settlement Minor'),
    33411: ItemData(IC.useful, 1, 'Progressive kho_vehicle', ItemType.building, 1, None, 'Progressive Kho Building: Vehicle'),
    33412: ItemData(IC.useful, 2, 'Progressive kho_vehicle', ItemType.building, 2, None, 'Progressive Kho Building: Vehicle'),
    33413: ItemData(IC.useful, 3, 'Progressive kho_vehicle', ItemType.building, 3, None, 'Progressive Kho Building: Vehicle'),
    33414: ItemData(IC.useful, 1, 'Progressive kho_walls_major', ItemType.building, 1, None, 'Progressive Kho Building: Walls Major'),
    33415: ItemData(IC.useful, 2, 'Progressive kho_walls_major', ItemType.building, 2, None, 'Progressive Kho Building: Walls Major'),
    33416: ItemData(IC.useful, 3, 'Progressive kho_walls_major', ItemType.building, 3, None, 'Progressive Kho Building: Walls Major'),
    33417: ItemData(IC.useful, 1, 'Progressive kho_walls_minor', ItemType.building, 1, None, 'Progressive Kho Building: Walls Minor'),
    33418: ItemData(IC.useful, 2, 'Progressive kho_walls_minor', ItemType.building, 2, None, 'Progressive Kho Building: Walls Minor'),
    33419: ItemData(IC.useful, 1, 'Progressive kho_warriors', ItemType.building, 1, None, 'Progressive Kho Building: Warriors'),
    33420: ItemData(IC.useful, 2, 'Progressive kho_warriors', ItemType.building, 2, None, 'Progressive Kho Building: Warriors'),
    33421: ItemData(IC.useful, 3, 'Progressive kho_warriors', ItemType.building, 3, None, 'Progressive Kho Building: Warriors'),
    33422: ItemData(IC.useful, 1, 'Progressive special_galbaraz_mourkain_kho', ItemType.building, 1, None, 'Progressive Kho Building: Special Galbaraz Mourkain Kho')
}

progTechs: dict[int, ItemData] = {

}

special: dict[int, ItemData] = {

}