from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    36000: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_stegadon_blessed_1', ItemType.unit, 4, 'war_beast', 'Ksl Unit: Blessed Stegadon'),
    36001: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_stegadon_1', ItemType.unit, 4, 'war_beast', 'Ksl Unit: Stegadon'),
    36002: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_stegadon_0', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Feral Stegadon'),
    36003: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_kroxigors_blessed', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Blessed Kroxigor'),
    36004: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_kroxigors', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Kroxigor'),
    36005: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_carnosaur_blessed_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Blessed Carnosaur'),
    36006: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_carnosaur_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Feral Carnosaur'),
    36007: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_bastiladon_blessed_2', ItemType.unit, 3, 'war_beast', 'Ksl Unit: Blessed Bastiladon (Solar Engine)'),
    36008: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_bastiladon_2', ItemType.unit, 3, 'war_beast', 'Ksl Unit: Bastiladon (Solar Engine)'),
    36009: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_bastiladon_1', ItemType.unit, 3, 'war_beast', 'Ksl Unit: Bastiladon (Revivification Crystal)'),
    36010: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_bastiladon_0', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Feral Bastiladon'),
    36011: ItemData(IC.useful, 1, 'wh2_main_lzd_mon_ancient_stegadon', ItemType.unit, 4, 'war_beast', 'Ksl Unit: Ancient Stegadon'),
    36012: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_temple_guards_blessed', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Blessed Temple Guard'),
    36013: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_temple_guards', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Temple Guard'),
    36014: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_skink_skirmishers_blessed_0', ItemType.unit, 2, 'Progressive ksl_rng', 'Ksl Unit: Blessed Skink Skirmishers'),
    36015: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_skink_skirmishers_0', ItemType.unit, 1, 'Progressive ksl_rng', 'Ksl Unit: Skink Skirmishers'),
    36016: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_skink_cohort_1', ItemType.unit, 1, 'Progressive ksl_rng', 'Ksl Unit: Skink Cohort (Javelins)'),
    36017: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_skink_cohort_0', ItemType.unit, 1, 'Progressive ksl_inf', 'Ksl Unit: Skink Cohort'),
    36018: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_warriors_blessed_1', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Blessed Saurus Warriors (Shields)'),
    36019: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_warriors_1', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Saurus Warriors (Shields)'),
    36020: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_warriors_0', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Saurus Warriors'),
    36021: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_spearmen_blessed_1', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Blessed Saurus Spears (Shields)'),
    36022: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_spearmen_1', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Saurus Spears (Shields)'),
    36023: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_saurus_spearmen_0', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Saurus Spears'),
    36024: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_chameleon_skinks_blessed_0', ItemType.unit, 2, 'Progressive ksl_rng', 'Ksl Unit: Blessed Chameleon Skinks'),
    36025: ItemData(IC.useful, 1, 'wh2_main_lzd_inf_chameleon_skinks_0', ItemType.unit, 2, 'Progressive ksl_rng', 'Ksl Unit: Chameleon Skinks'),
    36026: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_slann_mage_priest_high_0', ItemType.unit, 0, 'Progressive ksl_veh', 'Ksl Unit: Slann Mage-Priest (High)'),
    36027: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_skink_priest_heavens_0', ItemType.unit, 0, 'Progressive ksl_inf', 'Ksl Unit: Skink Priest (Heavens)'),
    36028: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_skink_priest_beasts_0', ItemType.unit, 0, 'Progressive ksl_inf', 'Ksl Unit: Skink Priest (Beasts)'),
    36029: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_skink_chief_0', ItemType.unit, 0, 'Progressive ksl_rng', 'Ksl Unit: Skink Chief'),
    36030: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_saurus_scar_veteran_2', ItemType.unit, 0, 'war_beast', 'Ksl Unit: Saurus Scar-Veteran'),
    36031: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_saurus_scar_veteran_1', ItemType.unit, 0, 'cavalry', 'Ksl Unit: Saurus Scar-Veteran'),
    36032: ItemData(IC.useful, 1, 'wh2_main_lzd_cha_saurus_scar_veteran_0', ItemType.unit, 0, 'Progressive ksl_inf', 'Ksl Unit: Saurus Scar-Veteran'),
    36033: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_terradon_riders_blessed_1', ItemType.unit, 2, 'cavalry', 'Ksl Unit: Blessed Terradon Riders (Fireleech Bolas)'),
    36034: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_terradon_riders_1', ItemType.unit, 2, 'cavalry', 'Ksl Unit: Terradon Riders (Fireleech Bolas)'),
    36035: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_terradon_riders_0', ItemType.unit, 2, 'cavalry', 'Ksl Unit: Terradon Riders'),
    36036: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_horned_ones_blessed_0', ItemType.unit, 4, 'cavalry', 'Ksl Unit: Blessed Horned Ones'),
    36037: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_horned_ones_0', ItemType.unit, 4, 'cavalry', 'Ksl Unit: Horned Ones'),
    36038: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_cold_ones_feral_0', ItemType.unit, 1, 'Progressive ksl_inf', 'Ksl Unit: Feral Cold Ones'),
    36039: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_cold_ones_1', ItemType.unit, 2, 'cavalry', 'Ksl Unit: Cold One Riders'),
    36040: ItemData(IC.useful, 1, 'wh2_main_lzd_cav_cold_one_spearriders_blessed_0', ItemType.unit, 3, 'cavalry', 'Ksl Unit: Blessed Cold One Spear-Riders'),
    36041: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_mon_troglodon_ror_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: The Pale Death (Feral Troglodon)'),
    36042: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_mon_troglodon_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Feral Troglodon'),
    36043: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_mon_coatl_ror_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Spirit of Tepok (Coatl)'),
    36044: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_mon_coatl_0', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Coatl'),
    36045: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_mon_carnosaur_ror_0', ItemType.unit, 4, 'Progressive ksl_inf', "Ksl Unit: GeltblÃ¶m's Terror (Feral Carnosaur)"),
    36046: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_inf_chameleon_stalkers_0', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Chameleon Stalkers'),
    36047: ItemData(IC.useful, 1, 'wh2_dlc17_lzd_cha_skink_oracle_troglodon_0', ItemType.unit, 0, 'war_beast', 'Ksl Unit: Skink Oracle'),
    36048: ItemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats', ItemType.unit, 4, 'Progressive ksl_inf', 'Ksl Unit: Zoats'),
    36049: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_mon_sacred_kroxigors_0', ItemType.unit, 3, 'Progressive ksl_inf', 'Ksl Unit: Sacred Kroxigor'),
    36050: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_mon_razordon_pack_0', ItemType.unit, 2, 'Progressive ksl_rng', 'Ksl Unit: Razordon Hunting Pack'),
    36051: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_mon_dread_saurian_1', ItemType.unit, 5, 'war_beast', 'Ksl Unit: Dread Saurian'),
    36052: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_mon_dread_saurian_0', ItemType.unit, 5, 'Progressive ksl_inf', 'Ksl Unit: Feral Dread Saurian'),
    36053: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_cha_nakai_0', ItemType.unit, 0, 'Progressive ksl_inf', 'Ksl Unit: Nakai the Wanderer'),
    36054: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_mon_salamander_pack_0', ItemType.unit, 2, 'Progressive ksl_rng', 'Ksl Unit: Salamander Hunting Pack'),
    36055: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_mon_bastiladon_3', ItemType.unit, 3, 'war_beast', 'Ksl Unit: Bastiladon (Ark of Sotek)'),
    36056: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_mon_ancient_stegadon_1', ItemType.unit, 5, 'war_beast', 'Ksl Unit: Ancient Stegadon (Engine of the Gods)'),
    36057: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_mon_ancient_salamander_0', ItemType.unit, 3, 'Progressive ksl_rng', 'Ksl Unit: Ancient Salamander'),
    36058: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_inf_skink_red_crested_0', ItemType.unit, 2, 'Progressive ksl_inf', 'Ksl Unit: Red Crested Skinks'),
    36059: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_cav_ripperdactyl_riders_0', ItemType.unit, 3, 'cavalry', 'Ksl Unit: Ripperdactyl Riders')
}

buildings: dict[int, ItemData] = {
    36400: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_terradons_2', ItemType.building, 1, 'Progressive lzd_terradons', 'Ksl Building: Ripperdactyl Hatchery'),
    36401: ItemData(IC.useful, 1, 'wh2_dlc12_lzd_terradons_2', ItemType.building, 1, 'Progressive lzd_terradons', 'Ksl Building: Ripperdactyl Hatchery'),
    36402: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_nakai_itzl', ItemType.building, 0, 'Progressive lzd_nakai', 'Ksl Building: Temple of Itzl'),
    36403: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_nakai_quetzl', ItemType.building, 0, 'Progressive lzd_nakai', 'Ksl Building: Temple of Quetzl'),
    36404: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_nakai_xholankha', ItemType.building, 0, 'Progressive lzd_nakai', 'Ksl Building: Temple of Xholankha'),
    36405: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_port_nakai_itzl', ItemType.building, 0, 'Progressive lzd_port_nakai', 'Ksl Building: Temple of Itzl'),
    36406: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_port_nakai_quetzl', ItemType.building, 0, 'Progressive lzd_port_nakai', 'Ksl Building: Temple of Quetzl'),
    36407: ItemData(IC.useful, 1, 'wh2_dlc13_lzd_port_nakai_xholankha', ItemType.building, 0, 'Progressive lzd_port_nakai', 'Ksl Building: Temple of Xholankha'),
    36408: ItemData(IC.useful, 1, 'wh2_dlc14_special_lzd_konquata', ItemType.building, 0, 'Progressive special_lzd', 'Ksl Building: Jungles of the Old Ones'),
    36409: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_lzd_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_lzd', 'Ksl Building: Reclaimed Tunnels'),
    36410: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_lzd_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_lzd', 'Ksl Building: Mapped Passageways'),
    36411: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_lzd_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_lzd', 'Ksl Building: Rebuilt Labyrinth'),
    36412: ItemData(IC.useful, 1, 'wh2_main_lzd_beasts_1', ItemType.building, 0, 'Progressive lzd_beasts', 'Ksl Building: Taming Pen'),
    36413: ItemData(IC.useful, 1, 'wh2_main_lzd_beasts_2', ItemType.building, 1, 'Progressive lzd_beasts', 'Ksl Building: Beast Lair'),
    36414: ItemData(IC.useful, 1, 'wh2_main_lzd_beasts_3', ItemType.building, 2, 'Progressive lzd_beasts', 'Ksl Building: Corral-Arena'),
    36415: ItemData(IC.useful, 1, 'wh2_main_lzd_beasts_4', ItemType.building, 3, 'Progressive lzd_beasts', 'Ksl Building: Pyramid of Itzl'),
    36416: ItemData(IC.useful, 1, 'wh2_main_lzd_coldones_1', ItemType.building, 0, 'Progressive lzd_coldones', 'Ksl Building: Cold One Caves'),
    36417: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_major_1', ItemType.building, 0, 'Progressive lzd_defence_major', 'Ksl Building: Mystic Barriers'),
    36418: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_major_2', ItemType.building, 1, 'Progressive lzd_defence_major', 'Ksl Building: Force Walls'),
    36419: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_major_3', ItemType.building, 2, 'Progressive lzd_defence_major', 'Ksl Building: Energy Dome'),
    36420: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_minor_1', ItemType.building, 0, 'Progressive lzd_defence_minor', 'Ksl Building: Skink Lookouts'),
    36421: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_minor_2', ItemType.building, 1, 'Progressive lzd_defence_minor', 'Ksl Building: Saurus Garrison'),
    36422: ItemData(IC.useful, 1, 'wh2_main_lzd_defence_norsca_1', ItemType.building, 0, 'Progressive lzd_defence_norsca', 'Ksl Building: Outpost Garrison'),
    36423: ItemData(IC.useful, 1, 'wh2_main_lzd_energy_1', ItemType.building, 0, 'Progressive lzd_energy', 'Ksl Building: Stone Marker'),
    36424: ItemData(IC.useful, 1, 'wh2_main_lzd_energy_2', ItemType.building, 1, 'Progressive lzd_energy', 'Ksl Building: Lodestone'),
    36425: ItemData(IC.useful, 1, 'wh2_main_lzd_energy_3', ItemType.building, 0, 'Progressive lzd_energy', 'Ksl Building: Geomantic Pylon'),
    36426: ItemData(IC.useful, 1, 'wh2_main_lzd_energy_4', ItemType.building, 1, 'Progressive lzd_energy', 'Ksl Building: Geomantic Spire'),
    36427: ItemData(IC.useful, 1, 'wh2_main_lzd_energy_5', ItemType.building, 2, 'Progressive lzd_energy', 'Ksl Building: Geomantic Locus'),
    36428: ItemData(IC.useful, 1, 'wh2_main_lzd_farm_1', ItemType.building, 0, 'Progressive lzd_farm', 'Ksl Building: Skink Foraging Camp'),
    36429: ItemData(IC.useful, 1, 'wh2_main_lzd_farm_2', ItemType.building, 1, 'Progressive lzd_farm', 'Ksl Building: Insect Breeding Farm'),
    36430: ItemData(IC.useful, 1, 'wh2_main_lzd_farm_3', ItemType.building, 2, 'Progressive lzd_farm', 'Ksl Building: Meat Storage Hall'),
    36431: ItemData(IC.useful, 1, 'wh2_main_lzd_industry_1', ItemType.building, 0, 'Progressive lzd_industry', 'Ksl Building: Skink Favelas'),
    36432: ItemData(IC.useful, 1, 'wh2_main_lzd_industry_2', ItemType.building, 1, 'Progressive lzd_industry', 'Ksl Building: Skink Barrios'),
    36433: ItemData(IC.useful, 1, 'wh2_main_lzd_industry_3', ItemType.building, 2, 'Progressive lzd_industry', 'Ksl Building: Kroxigor Labour District'),
    36434: ItemData(IC.useful, 1, 'wh2_main_lzd_order_1', ItemType.building, 0, 'Progressive lzd_order', 'Ksl Building: Old One Monument'),
    36435: ItemData(IC.useful, 1, 'wh2_main_lzd_order_2', ItemType.building, 1, 'Progressive lzd_order', 'Ksl Building: Grand Plaza'),
    36436: ItemData(IC.useful, 1, 'wh2_main_lzd_order_3', ItemType.building, 2, 'Progressive lzd_order', 'Ksl Building: Floating Gardens'),
    36437: ItemData(IC.useful, 1, 'wh2_main_lzd_port_1', ItemType.building, 0, 'Progressive lzd_port', 'Ksl Building: Pliodon Landing'),
    36438: ItemData(IC.useful, 1, 'wh2_main_lzd_port_2', ItemType.building, 1, 'Progressive lzd_port', 'Ksl Building: Ancient Harbour'),
    36439: ItemData(IC.useful, 1, 'wh2_main_lzd_port_3', ItemType.building, 2, 'Progressive lzd_port', 'Ksl Building: Temple-Port'),
    36440: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_animals_1', ItemType.building, 0, 'Progressive lzd_resource_animals', 'Ksl Building: Chameleon Menagerie'),
    36441: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_animals_2', ItemType.building, 1, 'Progressive lzd_resource_animals', 'Ksl Building: Terradon Cages'),
    36442: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_animals_3', ItemType.building, 2, 'Progressive lzd_resource_animals', 'Ksl Building: Dinosaur Reserve'),
    36443: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_dyes_1', ItemType.building, 0, 'Progressive lzd_resource_dyes', 'Ksl Building: Cinnabar Mining Pit'),
    36444: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_dyes_2', ItemType.building, 1, 'Progressive lzd_resource_dyes', 'Ksl Building: Cinnabar Mine'),
    36445: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_dyes_3', ItemType.building, 2, 'Progressive lzd_resource_dyes', 'Ksl Building: Dyemaker'),
    36446: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_furs_1', ItemType.building, 0, 'Progressive lzd_resource_furs', 'Ksl Building: Hunting Grounds'),
    36447: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_furs_2', ItemType.building, 1, 'Progressive lzd_resource_furs', 'Ksl Building: Hunting Camp'),
    36448: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_furs_3', ItemType.building, 2, 'Progressive lzd_resource_furs', 'Ksl Building: Tannery'),
    36449: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gems_1', ItemType.building, 0, 'Progressive lzd_resource_gems', 'Ksl Building: Gem Mineshaft'),
    36450: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gems_2', ItemType.building, 1, 'Progressive lzd_resource_gems', 'Ksl Building: Gem Mine'),
    36451: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gems_3', ItemType.building, 2, 'Progressive lzd_resource_gems', "Ksl Building: Gemcutter's Workshop"),
    36452: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gold_1', ItemType.building, 0, 'Progressive lzd_resource_gold', 'Ksl Building: Gold Mining Pit'),
    36453: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gold_2', ItemType.building, 1, 'Progressive lzd_resource_gold', 'Ksl Building: Gold Mine'),
    36454: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_gold_3', ItemType.building, 2, 'Progressive lzd_resource_gold', 'Ksl Building: Gold Smelter'),
    36455: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_iron_1', ItemType.building, 0, 'Progressive lzd_resource_iron', 'Ksl Building: Iron Mining Pit'),
    36456: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_iron_2', ItemType.building, 1, 'Progressive lzd_resource_iron', 'Ksl Building: Iron Mines'),
    36457: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_iron_3', ItemType.building, 2, 'Progressive lzd_resource_iron', 'Ksl Building: Iron Smelter'),
    36458: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_marble_1', ItemType.building, 0, 'Progressive lzd_resource_marble', 'Ksl Building: Sawyer'),
    36459: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_marble_2', ItemType.building, 1, 'Progressive lzd_resource_marble', 'Ksl Building: Marble Quarry'),
    36460: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_marble_3', ItemType.building, 2, 'Progressive lzd_resource_marble', "Ksl Building: Stone Mason's Workshop"),
    36461: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_medicine_1', ItemType.building, 0, 'Progressive lzd_resource_medicine', 'Ksl Building: Glowing Berry Patches'),
    36462: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_medicine_2', ItemType.building, 1, 'Progressive lzd_resource_medicine', 'Ksl Building: Mystic Fern Grove'),
    36463: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_medicine_3', ItemType.building, 2, 'Progressive lzd_resource_medicine', 'Ksl Building: Lotus Gathering Camp'),
    36464: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_obsidian_1', ItemType.building, 0, 'Progressive lzd_resource_obsidian', 'Ksl Building: Obsidian Quarry'),
    36465: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_obsidian_2', ItemType.building, 1, 'Progressive lzd_resource_obsidian', 'Ksl Building: Obsidian Trinket Maker'),
    36466: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_obsidian_3', ItemType.building, 2, 'Progressive lzd_resource_obsidian', 'Ksl Building: Obsidian Amulet Carver'),
    36467: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pasture_1', ItemType.building, 0, 'Progressive lzd_resource_pasture', 'Ksl Building: Grazing Pastures'),
    36468: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pasture_2', ItemType.building, 1, 'Progressive lzd_resource_pasture', 'Ksl Building: Livestock Pens'),
    36469: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pasture_3', ItemType.building, 2, 'Progressive lzd_resource_pasture', 'Ksl Building: Hothouse Hatchery'),
    36470: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pottery_1', ItemType.building, 0, 'Progressive lzd_resource_pottery', 'Ksl Building: Clay Pit'),
    36471: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pottery_2', ItemType.building, 1, 'Progressive lzd_resource_pottery', 'Ksl Building: Pottery Maker'),
    36472: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_pottery_3', ItemType.building, 2, 'Progressive lzd_resource_pottery', 'Ksl Building: Kilns'),
    36473: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_salt_1', ItemType.building, 0, 'Progressive lzd_resource_salt', 'Ksl Building: Brine Mining Pans'),
    36474: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_salt_2', ItemType.building, 1, 'Progressive lzd_resource_salt', 'Ksl Building: Brine Mining Basin'),
    36475: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_salt_3', ItemType.building, 2, 'Progressive lzd_resource_salt', 'Ksl Building: Saltworks'),
    36476: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_spices_1', ItemType.building, 0, 'Progressive lzd_resource_spices', 'Ksl Building: Spice Market'),
    36477: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_spices_2', ItemType.building, 1, 'Progressive lzd_resource_spices', 'Ksl Building: Spice Trading Post'),
    36478: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_spices_3', ItemType.building, 2, 'Progressive lzd_resource_spices', 'Ksl Building: Eastern Bazaar'),
    36479: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wine_1', ItemType.building, 0, 'Progressive lzd_resource_wine', 'Ksl Building: Fruit Draft Compressors'),
    36480: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wine_2', ItemType.building, 1, 'Progressive lzd_resource_wine', 'Ksl Building: Fruit Draft Storage '),
    36481: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wine_3', ItemType.building, 2, 'Progressive lzd_resource_wine', 'Ksl Building: Fruit Libation Factor'),
    36482: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wood_1', ItemType.building, 0, 'Progressive lzd_resource_wood', 'Ksl Building: Logging Camp'),
    36483: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wood_2', ItemType.building, 1, 'Progressive lzd_resource_wood', "Ksl Building: Foresters' Barrios"),
    36484: ItemData(IC.useful, 1, 'wh2_main_lzd_resource_wood_3', ItemType.building, 2, 'Progressive lzd_resource_wood', 'Ksl Building: Bastiladon Lumber Carriers'),
    36485: ItemData(IC.useful, 1, 'wh2_main_lzd_saurus_1', ItemType.building, 0, 'Progressive lzd_saurus', 'Ksl Building: Underground Lagoon'),
    36486: ItemData(IC.useful, 1, 'wh2_main_lzd_saurus_2', ItemType.building, 1, 'Progressive lzd_saurus', 'Ksl Building: Sacred Spawning Caverns'),
    36487: ItemData(IC.useful, 1, 'wh2_main_lzd_saurus_3', ItemType.building, 2, 'Progressive lzd_saurus', 'Ksl Building: Temple Guard Barracks'),
    36488: ItemData(IC.useful, 1, 'wh2_main_lzd_scrying_1', ItemType.building, 0, 'Progressive lzd_scrying', 'Ksl Building: Scrying Pool'),
    36489: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_major_1', ItemType.building, 0, 'Progressive lzd_settlement_major', 'Ksl Building: Coldblood Commune'),
    36490: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_major_2', ItemType.building, 1, 'Progressive lzd_settlement_major', 'Ksl Building: Temple-Precinct'),
    36491: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_major_3', ItemType.building, 2, 'Progressive lzd_settlement_major', 'Ksl Building: Holy Ziggurat'),
    36492: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_major_4', ItemType.building, 3, 'Progressive lzd_settlement_major', 'Ksl Building: Temple-City'),
    36493: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_major_5', ItemType.building, 4, 'Progressive lzd_settlement_major', 'Ksl Building: Temple-Nexus'),
    36494: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_minor_1', ItemType.building, 0, 'Progressive lzd_settlement_minor', 'Ksl Building: Lizardmen Commune'),
    36495: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_minor_2', ItemType.building, 1, 'Progressive lzd_settlement_minor', 'Ksl Building: Lizardmen Plaza'),
    36496: ItemData(IC.useful, 1, 'wh2_main_lzd_settlement_minor_3', ItemType.building, 2, 'Progressive lzd_settlement_minor', 'Ksl Building: Holy Ziggurat'),
    36497: ItemData(IC.useful, 1, 'wh2_main_lzd_skinks_1', ItemType.building, 0, 'Progressive lzd_skinks', 'Ksl Building: Spawn-Pools of the Lower Castes'),
    36498: ItemData(IC.useful, 1, 'wh2_main_lzd_skinks_2', ItemType.building, 1, 'Progressive lzd_skinks', 'Ksl Building: Spawn-Pools of the Braves'),
    36499: ItemData(IC.useful, 1, 'wh2_main_lzd_skinks_3', ItemType.building, 2, 'Progressive lzd_skinks', 'Ksl Building: Spawn-Pools of the Chosen'),
    36500: ItemData(IC.useful, 1, 'wh2_main_lzd_slann_1', ItemType.building, 0, 'Progressive lzd_slann', 'Ksl Building: Star Chamber'),
    36501: ItemData(IC.useful, 1, 'wh2_main_lzd_smith_1', ItemType.building, 0, 'Progressive lzd_smith', "Ksl Building: Weapon-Crafters' Commune"),
    36502: ItemData(IC.useful, 1, 'wh2_main_lzd_terradons_1', ItemType.building, 0, 'Progressive lzd_terradons', 'Ksl Building: Terradon Hatchery'),
    36503: ItemData(IC.useful, 1, 'wh2_main_lzd_terradons_1', ItemType.building, 0, 'Progressive lzd_terradons', 'Ksl Building: Terradon Hatchery'),
    36504: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_oldones_1', ItemType.building, 0, 'Progressive lzd_worship_oldones', 'Ksl Building: Shrine of the Old Ones'),
    36505: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_oldones_2', ItemType.building, 1, 'Progressive lzd_worship_oldones', 'Ksl Building: Temple of the Old Ones'),
    36506: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_oldones_3', ItemType.building, 2, 'Progressive lzd_worship_oldones', 'Ksl Building: Ziggurat of the Old Ones'),
    36507: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_sotek_1', ItemType.building, 0, 'Progressive lzd_worship_sotek', 'Ksl Building: Sacrificial Altar of Sotek'),
    36508: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_sotek_2', ItemType.building, 1, 'Progressive lzd_worship_sotek', 'Ksl Building: Blood Shrines of Sotek'),
    36509: ItemData(IC.useful, 1, 'wh2_main_lzd_worship_sotek_3', ItemType.building, 2, 'Progressive lzd_worship_sotek', 'Ksl Building: Crimson Pyramid of Sotek'),
    36510: ItemData(IC.useful, 1, 'wh2_main_special_golden_tower_of_the_gods_lzd', ItemType.building, 0, 'Progressive special_golden_tower_of_the_gods', 'Ksl Building: Golden Tower of the Gods'),
    36511: ItemData(IC.useful, 1, 'wh2_main_special_golden_tower_of_the_gods_lzd', ItemType.building, 0, 'Progressive special_golden_tower_of_the_gods', 'Ksl Building: Golden Tower of the Gods'),
    36512: ItemData(IC.useful, 1, 'wh2_main_special_settlement_hexoatl_lzd_1', ItemType.building, 0, 'Progressive special_settlement_hexoatl_lzd', 'Ksl Building: Hexoatl (Coldblood Commune)'),
    36513: ItemData(IC.useful, 1, 'wh2_main_special_settlement_hexoatl_lzd_2', ItemType.building, 1, 'Progressive special_settlement_hexoatl_lzd', 'Ksl Building: Hexoatl (Temple-Precinct)'),
    36514: ItemData(IC.useful, 1, 'wh2_main_special_settlement_hexoatl_lzd_3', ItemType.building, 2, 'Progressive special_settlement_hexoatl_lzd', 'Ksl Building: Hexoatl (Holy Ziggurat)'),
    36515: ItemData(IC.useful, 1, 'wh2_main_special_settlement_hexoatl_lzd_4', ItemType.building, 3, 'Progressive special_settlement_hexoatl_lzd', 'Ksl Building: Hexoatl (Temple-City)'),
    36516: ItemData(IC.useful, 1, 'wh2_main_special_settlement_hexoatl_lzd_5', ItemType.building, 4, 'Progressive special_settlement_hexoatl_lzd', 'Ksl Building: Hexoatl (Temple-Citadel)'),
    36517: ItemData(IC.useful, 1, 'wh2_main_special_settlement_itza_lzd_1', ItemType.building, 0, 'Progressive special_settlement_itza_lzd', 'Ksl Building: Itza (Lizardmen Commune)'),
    36518: ItemData(IC.useful, 1, 'wh2_main_special_settlement_itza_lzd_2', ItemType.building, 1, 'Progressive special_settlement_itza_lzd', 'Ksl Building: Itza (Lizardmen Plaza)'),
    36519: ItemData(IC.useful, 1, 'wh2_main_special_settlement_itza_lzd_3', ItemType.building, 2, 'Progressive special_settlement_itza_lzd', 'Ksl Building: Itza (Holy Ziggurat)'),
    36520: ItemData(IC.useful, 1, 'wh2_main_special_settlement_itza_lzd_4', ItemType.building, 3, 'Progressive special_settlement_itza_lzd', 'Ksl Building: Itza (Temple-City)'),
    36521: ItemData(IC.useful, 1, 'wh2_main_special_settlement_itza_lzd_5', ItemType.building, 4, 'Progressive special_settlement_itza_lzd', 'Ksl Building: Itza (Temple-Citadel)'),
    36522: ItemData(IC.useful, 1, 'wh2_twa03_special_settlement_konquata_lzd_1', ItemType.building, 0, 'Progressive special_settlement_konquata_lzd', 'Ksl Building: Konquata (Lizardmen Commune)'),
    36523: ItemData(IC.useful, 1, 'wh2_twa03_special_settlement_konquata_lzd_2', ItemType.building, 1, 'Progressive special_settlement_konquata_lzd', 'Ksl Building: Konquata (Lizardmen Plaza)'),
    36524: ItemData(IC.useful, 1, 'wh2_twa03_special_settlement_konquata_lzd_3', ItemType.building, 2, 'Progressive special_settlement_konquata_lzd', 'Ksl Building: Konquata (Holy Ziggurat)'),
    36525: ItemData(IC.useful, 1, 'wh2_twa03_special_settlement_konquata_lzd_4', ItemType.building, 3, 'Progressive special_settlement_konquata_lzd', 'Ksl Building: Konquata (Temple-City)'),
    36526: ItemData(IC.useful, 1, 'wh2_twa03_special_settlement_konquata_lzd_5', ItemType.building, 4, 'Progressive special_settlement_konquata_lzd', 'Ksl Building: Konquata (Temple-Citadel)'),
    36527: ItemData(IC.useful, 1, 'wh3_dlc24_special_glacial_caves_lzd', ItemType.building, 0, 'Progressive special_glacial_caves', 'Ksl Building: Glacial Caves'),
    36528: ItemData(IC.useful, 1, 'wh3_main_lzd_allied_outpost_1', ItemType.building, 0, 'Progressive lzd_allied_outpost', 'Ksl Building: Lizardmen Outpost'),
    36529: ItemData(IC.useful, 1, 'wh3_main_lzd_allied_outpost_2', ItemType.building, 1, 'Progressive lzd_allied_outpost', 'Ksl Building: Lizardmen District'),
    36530: ItemData(IC.useful, 1, 'wh3_main_lzd_allied_outpost_3', ItemType.building, 2, 'Progressive lzd_allied_outpost', 'Ksl Building: Lizardmen Colony'),
    36531: ItemData(IC.useful, 1, 'wh3_main_lzd_resource_ivory_1', ItemType.building, 0, 'Progressive lzd_resource_ivory', 'Ksl Building: Animal Store'),
    36532: ItemData(IC.useful, 1, 'wh3_main_lzd_resource_ivory_2', ItemType.building, 1, 'Progressive lzd_resource_ivory', 'Ksl Building: Tusk Market'),
    36533: ItemData(IC.useful, 1, 'wh3_main_lzd_resource_ivory_3', ItemType.building, 2, 'Progressive lzd_resource_ivory', 'Ksl Building: Tusk Compound')
}

techs: dict[int, ItemData] = {
    36800: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_0_1', ItemType.tech, 0, 'Progressive tech_lzd', "Ksl Tech: Interpreting the Old Ones' Meaning"),
    36801: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_0_2', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Determining the Great Plan'),
    36802: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of Spawning'),
    36803: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Skink Spawning'),
    36804: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Saurus Spawning'),
    36805: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Enhanced Instinct'),
    36806: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Creature Bonding'),
    36807: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Guardian Spawning'),
    36808: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_1_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Strengthening'),
    36809: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of War'),
    36810: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Stoicism'),
    36811: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Marching'),
    36812: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Utilitarianism'),
    36813: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Annihilation'),
    36814: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Absolute Obedience'),
    36815: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_2_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Geomantic Healing'),
    36816: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of Order'),
    36817: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Scrying'),
    36818: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Civilisation'),
    36819: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Protection'),
    36820: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Infiltration'),
    36821: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Purification'),
    36822: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_3_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Projected Presence'),
    36823: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of Monuments'),
    36824: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the City'),
    36825: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Construction'),
    36826: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Expansion'),
    36827: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Great Temples'),
    36828: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Star Chambers'),
    36829: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_4_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Global Plan'),
    36830: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of Crafts'),
    36831: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Artisan'),
    36832: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Exploitation'),
    36833: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Coexistence'),
    36834: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Sea'),
    36835: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Labourers'),
    36836: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_5_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Geological Prospecting'),
    36837: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of the Skinks'),
    36838: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Skirmishing'),
    36839: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Purpose'),
    36840: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Skink Invigoration'),
    36841: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Quickness'),
    36842: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Kroxigor'),
    36843: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_6_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Hardened Scales'),
    36844: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of the Saurus'),
    36845: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Weapon Crafting'),
    36846: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Massed Combat'),
    36847: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Saurus Invigoration'),
    36848: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_5', ItemType.tech, 4, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Armour Crafting'),
    36849: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_6', ItemType.tech, 5, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Honoured Guardians'),
    36850: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_7_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Martial Excellence'),
    36851: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_1', ItemType.tech, 0, 'Progressive tech_lzd', 'Ksl Tech: Tablet of Beasts'),
    36852: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_2', ItemType.tech, 1, 'Progressive tech_lzd', 'Ksl Tech: Sequence of Exotic Weapons'),
    36853: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_3', ItemType.tech, 2, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Ferocity'),
    36854: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_4', ItemType.tech, 3, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Hunt'),
    36855: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_5', ItemType.tech, 4, 'Progressive tech_lzd', "Ksl Tech: Sequence of the Great Beast's Resilience"),
    36856: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_6', ItemType.tech, 5, 'Progressive tech_lzd', "Ksl Tech: Sequence of the Great Beast's Rampage"),
    36857: ItemData(IC.useful, 1, 'wh2_main_tech_lzd_8_7', ItemType.tech, 6, 'Progressive tech_lzd', 'Ksl Tech: Sequence of the Beastkeepers')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    37300: ItemData(IC.useful, 2, 'Progressive lzd_terradons', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Terradons'),
    37301: ItemData(IC.useful, 1, 'Progressive lzd_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Nakai'),
    37302: ItemData(IC.useful, 1, 'Progressive lzd_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Nakai'),
    37303: ItemData(IC.useful, 1, 'Progressive lzd_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Nakai'),
    37304: ItemData(IC.useful, 1, 'Progressive lzd_port_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Port Nakai'),
    37305: ItemData(IC.useful, 1, 'Progressive lzd_port_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Port Nakai'),
    37306: ItemData(IC.useful, 1, 'Progressive lzd_port_nakai', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Port Nakai'),
    37307: ItemData(IC.useful, 1, 'Progressive special_lzd', ItemType.building, 1, None, 'Progressive Ksl Building: Special Lzd'),
    37308: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_lzd', ItemType.building, 1, None, 'Progressive Ksl Building: Foreign Slot Discovery Lzd'),
    37309: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_lzd', ItemType.building, 2, None, 'Progressive Ksl Building: Foreign Slot Discovery Lzd'),
    37310: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_lzd', ItemType.building, 3, None, 'Progressive Ksl Building: Foreign Slot Discovery Lzd'),
    37311: ItemData(IC.useful, 1, 'Progressive lzd_beasts', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Beasts'),
    37312: ItemData(IC.useful, 2, 'Progressive lzd_beasts', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Beasts'),
    37313: ItemData(IC.useful, 3, 'Progressive lzd_beasts', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Beasts'),
    37314: ItemData(IC.useful, 4, 'Progressive lzd_beasts', ItemType.building, 4, None, 'Progressive Ksl Building: Lzd Beasts'),
    37315: ItemData(IC.useful, 1, 'Progressive lzd_coldones', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Coldones'),
    37316: ItemData(IC.useful, 1, 'Progressive lzd_defence_major', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Defence Major'),
    37317: ItemData(IC.useful, 2, 'Progressive lzd_defence_major', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Defence Major'),
    37318: ItemData(IC.useful, 3, 'Progressive lzd_defence_major', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Defence Major'),
    37319: ItemData(IC.useful, 1, 'Progressive lzd_defence_minor', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Defence Minor'),
    37320: ItemData(IC.useful, 2, 'Progressive lzd_defence_minor', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Defence Minor'),
    37321: ItemData(IC.useful, 1, 'Progressive lzd_defence_norsca', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Defence Norsca'),
    37322: ItemData(IC.useful, 1, 'Progressive lzd_energy', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Energy'),
    37323: ItemData(IC.useful, 2, 'Progressive lzd_energy', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Energy'),
    37324: ItemData(IC.useful, 1, 'Progressive lzd_energy', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Energy'),
    37325: ItemData(IC.useful, 2, 'Progressive lzd_energy', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Energy'),
    37326: ItemData(IC.useful, 3, 'Progressive lzd_energy', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Energy'),
    37327: ItemData(IC.useful, 1, 'Progressive lzd_farm', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Farm'),
    37328: ItemData(IC.useful, 2, 'Progressive lzd_farm', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Farm'),
    37329: ItemData(IC.useful, 3, 'Progressive lzd_farm', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Farm'),
    37330: ItemData(IC.useful, 1, 'Progressive lzd_industry', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Industry'),
    37331: ItemData(IC.useful, 2, 'Progressive lzd_industry', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Industry'),
    37332: ItemData(IC.useful, 3, 'Progressive lzd_industry', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Industry'),
    37333: ItemData(IC.useful, 1, 'Progressive lzd_order', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Order'),
    37334: ItemData(IC.useful, 2, 'Progressive lzd_order', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Order'),
    37335: ItemData(IC.useful, 3, 'Progressive lzd_order', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Order'),
    37336: ItemData(IC.useful, 1, 'Progressive lzd_port', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Port'),
    37337: ItemData(IC.useful, 2, 'Progressive lzd_port', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Port'),
    37338: ItemData(IC.useful, 3, 'Progressive lzd_port', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Port'),
    37339: ItemData(IC.useful, 1, 'Progressive lzd_resource_animals', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Animals'),
    37340: ItemData(IC.useful, 2, 'Progressive lzd_resource_animals', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Animals'),
    37341: ItemData(IC.useful, 3, 'Progressive lzd_resource_animals', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Animals'),
    37342: ItemData(IC.useful, 1, 'Progressive lzd_resource_dyes', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Dyes'),
    37343: ItemData(IC.useful, 2, 'Progressive lzd_resource_dyes', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Dyes'),
    37344: ItemData(IC.useful, 3, 'Progressive lzd_resource_dyes', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Dyes'),
    37345: ItemData(IC.useful, 1, 'Progressive lzd_resource_furs', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Furs'),
    37346: ItemData(IC.useful, 2, 'Progressive lzd_resource_furs', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Furs'),
    37347: ItemData(IC.useful, 3, 'Progressive lzd_resource_furs', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Furs'),
    37348: ItemData(IC.useful, 1, 'Progressive lzd_resource_gems', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Gems'),
    37349: ItemData(IC.useful, 2, 'Progressive lzd_resource_gems', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Gems'),
    37350: ItemData(IC.useful, 3, 'Progressive lzd_resource_gems', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Gems'),
    37351: ItemData(IC.useful, 1, 'Progressive lzd_resource_gold', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Gold'),
    37352: ItemData(IC.useful, 2, 'Progressive lzd_resource_gold', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Gold'),
    37353: ItemData(IC.useful, 3, 'Progressive lzd_resource_gold', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Gold'),
    37354: ItemData(IC.useful, 1, 'Progressive lzd_resource_iron', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Iron'),
    37355: ItemData(IC.useful, 2, 'Progressive lzd_resource_iron', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Iron'),
    37356: ItemData(IC.useful, 3, 'Progressive lzd_resource_iron', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Iron'),
    37357: ItemData(IC.useful, 1, 'Progressive lzd_resource_marble', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Marble'),
    37358: ItemData(IC.useful, 2, 'Progressive lzd_resource_marble', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Marble'),
    37359: ItemData(IC.useful, 3, 'Progressive lzd_resource_marble', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Marble'),
    37360: ItemData(IC.useful, 1, 'Progressive lzd_resource_medicine', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Medicine'),
    37361: ItemData(IC.useful, 2, 'Progressive lzd_resource_medicine', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Medicine'),
    37362: ItemData(IC.useful, 3, 'Progressive lzd_resource_medicine', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Medicine'),
    37363: ItemData(IC.useful, 1, 'Progressive lzd_resource_obsidian', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Obsidian'),
    37364: ItemData(IC.useful, 2, 'Progressive lzd_resource_obsidian', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Obsidian'),
    37365: ItemData(IC.useful, 3, 'Progressive lzd_resource_obsidian', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Obsidian'),
    37366: ItemData(IC.useful, 1, 'Progressive lzd_resource_pasture', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Pasture'),
    37367: ItemData(IC.useful, 2, 'Progressive lzd_resource_pasture', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Pasture'),
    37368: ItemData(IC.useful, 3, 'Progressive lzd_resource_pasture', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Pasture'),
    37369: ItemData(IC.useful, 1, 'Progressive lzd_resource_pottery', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Pottery'),
    37370: ItemData(IC.useful, 2, 'Progressive lzd_resource_pottery', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Pottery'),
    37371: ItemData(IC.useful, 3, 'Progressive lzd_resource_pottery', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Pottery'),
    37372: ItemData(IC.useful, 1, 'Progressive lzd_resource_salt', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Salt'),
    37373: ItemData(IC.useful, 2, 'Progressive lzd_resource_salt', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Salt'),
    37374: ItemData(IC.useful, 3, 'Progressive lzd_resource_salt', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Salt'),
    37375: ItemData(IC.useful, 1, 'Progressive lzd_resource_spices', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Spices'),
    37376: ItemData(IC.useful, 2, 'Progressive lzd_resource_spices', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Spices'),
    37377: ItemData(IC.useful, 3, 'Progressive lzd_resource_spices', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Spices'),
    37378: ItemData(IC.useful, 1, 'Progressive lzd_resource_wine', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Wine'),
    37379: ItemData(IC.useful, 2, 'Progressive lzd_resource_wine', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Wine'),
    37380: ItemData(IC.useful, 3, 'Progressive lzd_resource_wine', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Wine'),
    37381: ItemData(IC.useful, 1, 'Progressive lzd_resource_wood', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Wood'),
    37382: ItemData(IC.useful, 2, 'Progressive lzd_resource_wood', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Wood'),
    37383: ItemData(IC.useful, 3, 'Progressive lzd_resource_wood', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Wood'),
    37384: ItemData(IC.useful, 1, 'Progressive lzd_saurus', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Saurus'),
    37385: ItemData(IC.useful, 2, 'Progressive lzd_saurus', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Saurus'),
    37386: ItemData(IC.useful, 3, 'Progressive lzd_saurus', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Saurus'),
    37387: ItemData(IC.useful, 1, 'Progressive lzd_scrying', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Scrying'),
    37388: ItemData(IC.useful, 1, 'Progressive lzd_settlement_major', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Settlement Major'),
    37389: ItemData(IC.useful, 2, 'Progressive lzd_settlement_major', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Settlement Major'),
    37390: ItemData(IC.useful, 3, 'Progressive lzd_settlement_major', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Settlement Major'),
    37391: ItemData(IC.useful, 4, 'Progressive lzd_settlement_major', ItemType.building, 4, None, 'Progressive Ksl Building: Lzd Settlement Major'),
    37392: ItemData(IC.useful, 5, 'Progressive lzd_settlement_major', ItemType.building, 5, None, 'Progressive Ksl Building: Lzd Settlement Major'),
    37393: ItemData(IC.useful, 1, 'Progressive lzd_settlement_minor', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Settlement Minor'),
    37394: ItemData(IC.useful, 2, 'Progressive lzd_settlement_minor', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Settlement Minor'),
    37395: ItemData(IC.useful, 3, 'Progressive lzd_settlement_minor', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Settlement Minor'),
    37396: ItemData(IC.useful, 1, 'Progressive lzd_skinks', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Skinks'),
    37397: ItemData(IC.useful, 2, 'Progressive lzd_skinks', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Skinks'),
    37398: ItemData(IC.useful, 3, 'Progressive lzd_skinks', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Skinks'),
    37399: ItemData(IC.useful, 1, 'Progressive lzd_slann', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Slann'),
    37400: ItemData(IC.useful, 1, 'Progressive lzd_smith', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Smith'),
    37401: ItemData(IC.useful, 1, 'Progressive lzd_terradons', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Terradons'),
    37402: ItemData(IC.useful, 1, 'Progressive lzd_worship_oldones', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Worship Oldones'),
    37403: ItemData(IC.useful, 2, 'Progressive lzd_worship_oldones', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Worship Oldones'),
    37404: ItemData(IC.useful, 3, 'Progressive lzd_worship_oldones', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Worship Oldones'),
    37405: ItemData(IC.useful, 1, 'Progressive lzd_worship_sotek', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Worship Sotek'),
    37406: ItemData(IC.useful, 2, 'Progressive lzd_worship_sotek', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Worship Sotek'),
    37407: ItemData(IC.useful, 3, 'Progressive lzd_worship_sotek', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Worship Sotek'),
    37408: ItemData(IC.useful, 1, 'Progressive special_golden_tower_of_the_gods', ItemType.building, 1, None, 'Progressive Ksl Building: Special Golden Tower Of The Gods'),
    37409: ItemData(IC.useful, 1, 'Progressive special_settlement_hexoatl_lzd', ItemType.building, 1, None, 'Progressive Ksl Building: Special Settlement Hexoatl Lzd'),
    37410: ItemData(IC.useful, 2, 'Progressive special_settlement_hexoatl_lzd', ItemType.building, 2, None, 'Progressive Ksl Building: Special Settlement Hexoatl Lzd'),
    37411: ItemData(IC.useful, 3, 'Progressive special_settlement_hexoatl_lzd', ItemType.building, 3, None, 'Progressive Ksl Building: Special Settlement Hexoatl Lzd'),
    37412: ItemData(IC.useful, 4, 'Progressive special_settlement_hexoatl_lzd', ItemType.building, 4, None, 'Progressive Ksl Building: Special Settlement Hexoatl Lzd'),
    37413: ItemData(IC.useful, 5, 'Progressive special_settlement_hexoatl_lzd', ItemType.building, 5, None, 'Progressive Ksl Building: Special Settlement Hexoatl Lzd'),
    37414: ItemData(IC.useful, 1, 'Progressive special_settlement_itza_lzd', ItemType.building, 1, None, 'Progressive Ksl Building: Special Settlement Itza Lzd'),
    37415: ItemData(IC.useful, 2, 'Progressive special_settlement_itza_lzd', ItemType.building, 2, None, 'Progressive Ksl Building: Special Settlement Itza Lzd'),
    37416: ItemData(IC.useful, 3, 'Progressive special_settlement_itza_lzd', ItemType.building, 3, None, 'Progressive Ksl Building: Special Settlement Itza Lzd'),
    37417: ItemData(IC.useful, 4, 'Progressive special_settlement_itza_lzd', ItemType.building, 4, None, 'Progressive Ksl Building: Special Settlement Itza Lzd'),
    37418: ItemData(IC.useful, 5, 'Progressive special_settlement_itza_lzd', ItemType.building, 5, None, 'Progressive Ksl Building: Special Settlement Itza Lzd'),
    37419: ItemData(IC.useful, 1, 'Progressive special_settlement_konquata_lzd', ItemType.building, 1, None, 'Progressive Ksl Building: Special Settlement Konquata Lzd'),
    37420: ItemData(IC.useful, 2, 'Progressive special_settlement_konquata_lzd', ItemType.building, 2, None, 'Progressive Ksl Building: Special Settlement Konquata Lzd'),
    37421: ItemData(IC.useful, 3, 'Progressive special_settlement_konquata_lzd', ItemType.building, 3, None, 'Progressive Ksl Building: Special Settlement Konquata Lzd'),
    37422: ItemData(IC.useful, 4, 'Progressive special_settlement_konquata_lzd', ItemType.building, 4, None, 'Progressive Ksl Building: Special Settlement Konquata Lzd'),
    37423: ItemData(IC.useful, 5, 'Progressive special_settlement_konquata_lzd', ItemType.building, 5, None, 'Progressive Ksl Building: Special Settlement Konquata Lzd'),
    37424: ItemData(IC.useful, 1, 'Progressive special_glacial_caves', ItemType.building, 1, None, 'Progressive Ksl Building: Special Glacial Caves'),
    37425: ItemData(IC.useful, 1, 'Progressive lzd_allied_outpost', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Allied Outpost'),
    37426: ItemData(IC.useful, 2, 'Progressive lzd_allied_outpost', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Allied Outpost'),
    37427: ItemData(IC.useful, 3, 'Progressive lzd_allied_outpost', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Allied Outpost'),
    37428: ItemData(IC.useful, 1, 'Progressive lzd_resource_ivory', ItemType.building, 1, None, 'Progressive Ksl Building: Lzd Ivory'),
    37429: ItemData(IC.useful, 2, 'Progressive lzd_resource_ivory', ItemType.building, 2, None, 'Progressive Ksl Building: Lzd Ivory'),
    37430: ItemData(IC.useful, 3, 'Progressive lzd_resource_ivory', ItemType.building, 3, None, 'Progressive Ksl Building: Lzd Ivory')
}

progTechs: dict[int, ItemData] = {
    37500: ItemData(IC.useful, 15, "Progressive tech_lzd", ItemType.tech, 15, None, "Progressive Lzd Tech"),
}

special: dict[int, ItemData] = {

}