from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    38000: ItemData(IC.useful, 1, 'wh3_main_ie_nor_cha_exalted_hero_mkho_killgore_slaymaim', ItemType.unit, 0, 'cavalry', 'Nor Unit: Killgore Slaymaim'),
    38001: ItemData(IC.useful, 1, 'wh3_main_ie_nor_cha_exalted_great_unclean_one_burplesmirk_spewpit', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Burplesmirk Spewpit'),
    38002: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_1', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Norscan Warhounds (Poison)'),
    38003: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Norscan Warhounds'),
    38004: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_trolls', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Norscan Trolls'),
    38005: ItemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_1', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Marauders (Great Weapons)'),
    38006: ItemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Marauders'),
    38007: ItemData(IC.useful, 1, 'wh_main_nor_cha_marauder_chieftan_3', ItemType.unit, 0, 'war_beast', 'Nor Unit: Marauder Chieftain'),
    38008: ItemData(IC.useful, 1, 'wh_main_nor_cha_marauder_chieftan_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Marauder Chieftain'),
    38009: ItemData(IC.useful, 1, 'wh_main_nor_cha_marauder_chieftan_1', ItemType.unit, 0, 'war_beast', 'Nor Unit: Marauder Chieftain'),
    38010: ItemData(IC.useful, 1, 'wh_main_nor_cha_marauder_chieftan_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Marauder Chieftain'),
    38011: ItemData(IC.useful, 1, 'wh_main_nor_cha_chaos_sorcerer_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Chaos Sorcerer (Metal)'),
    38012: ItemData(IC.useful, 1, 'wh_main_nor_cha_chaos_sorcerer_1', ItemType.unit, 0, 'war_beast', 'Nor Unit: Chaos Sorcerer (Metal)'),
    38013: ItemData(IC.useful, 1, 'wh_main_nor_cha_chaos_sorcerer_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Chaos Sorcerer (Metal)'),
    38014: ItemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_1', ItemType.unit, 2, 'war_beast', 'Nor Unit: Marauder Horsemen (Throwing Axes)'),
    38015: ItemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_0', ItemType.unit, 2, 'war_beast', 'Nor Unit: Marauder Horsemen'),
    38016: ItemData(IC.useful, 1, 'wh_main_nor_cav_chaos_chariot', ItemType.unit, 2, 'Progressive nor_veh', 'Nor Unit: Marauder Chariots'),
    38017: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_ror_1', ItemType.unit, 5, 'Progressive nor_inf', 'Nor Unit: The Great Mawherd of Bloodfjord (Feral Mammoths)'),
    38018: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_boss', ItemType.unit, 5, 'Progressive nor_inf', 'Nor Unit: The Great Mawherd of Bloodfjord (Feral Mammoths)'),
    38019: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_2', ItemType.unit, 5, 'war_beast', 'Nor Unit: War Mammoth (Warshrine)'),
    38020: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_1', ItemType.unit, 5, 'war_beast', 'Nor Unit: War Mammoth'),
    38021: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_0', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Feral Mammoth'),
    38022: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_1', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Skin Wolves (Armoured)'),
    38023: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_0', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Skin Wolves'),
    38024: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_ice_trolls_0', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Norscan Ice Trolls'),
    38025: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_giant_0', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Norscan Giant'),
    38026: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_ror_0', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: The Cold-Voider (Chaos Frost Dragon)'),
    38027: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_boss', ItemType.unit, 5, 'Progressive nor_inf', 'Nor Unit: Frigustrex, Scion of the Cold-Void'),
    38028: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_0', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Chaos Frost Dragon'),
    38029: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_1', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Fimir Warriors (Great Weapons)'),
    38030: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Fimir Warriors'),
    38031: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_spearman_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Marauder Spearmen'),
    38032: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_1', ItemType.unit, 2, 'Progressive nor_rng', 'Nor Unit: Marauder Hunters (Javelins)'),
    38033: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_0', ItemType.unit, 2, 'Progressive nor_rng', 'Nor Unit: Marauder Hunters'),
    38034: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_1', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Marauder Champions (Great Weapons)'),
    38035: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Marauder Champions'),
    38036: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_berserkers_0', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Marauder Berserkers'),
    38037: ItemData(IC.useful, 1, 'wh_dlc08_nor_feral_manticore', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Feral Manticore'),
    38038: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_wulfrik_3', ItemType.unit, 0, 'war_beast', 'Nor Unit: Wulfrik the Wanderer'),
    38039: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_wulfrik_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Wulfrik the Wanderer'),
    38040: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_wulfrik_1', ItemType.unit, 0, 'war_beast', 'Nor Unit: Wulfrik the Wanderer'),
    38041: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_wulfrik_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Wulfrik the Wanderer'),
    38042: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_throgg_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Throgg'),
    38043: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_skin_wolf_werekin_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Skin Wolf Werekin'),
    38044: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_metal_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Shaman-Sorcerer (Metal)'),
    38045: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_metal_1', ItemType.unit, 0, 'cavalry', 'Nor Unit: Shaman-Sorcerer (Metal)'),
    38046: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_metal_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Shaman-Sorcerer (Metal)'),
    38047: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_fire_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Shaman-Sorcerer (Fire)'),
    38048: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_fire_1', ItemType.unit, 0, 'cavalry', 'Nor Unit: Shaman-Sorcerer (Fire)'),
    38049: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_fire_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Shaman-Sorcerer (Fire)'),
    38050: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_death_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Shaman-Sorcerer (Death)'),
    38051: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_death_1', ItemType.unit, 0, 'cavalry', 'Nor Unit: Shaman-Sorcerer (Death)'),
    38052: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_death_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Shaman-Sorcerer (Death)'),
    38053: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_shadow_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Fimir Balefiend (Shadows)'),
    38054: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_fire_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Fimir Balefiend (Fire)'),
    38055: ItemData(IC.useful, 1, 'wh_dlc08_nor_cav_marauder_horsemasters_0', ItemType.unit, 2, 'war_beast', 'Nor Unit: Marauder Horsemasters'),
    38056: ItemData(IC.useful, 1, 'wh_dlc01_nor_cha_chaos_sorcerer_lord_2', ItemType.unit, 0, 'Progressive nor_veh', 'Nor Unit: Chaos Sorcerer Lord (Metal)'),
    38057: ItemData(IC.useful, 1, 'wh_dlc01_nor_cha_chaos_sorcerer_lord_1', ItemType.unit, 0, 'war_beast', 'Nor Unit: Chaos Sorcerer Lord (Metal)'),
    38058: ItemData(IC.useful, 1, 'wh_dlc01_nor_cha_chaos_sorcerer_lord_0', ItemType.unit, 0, 'Progressive nor_inf', 'Nor Unit: Chaos Sorcerer Lord (Metal)')
}

buildings: dict[int, ItemData] = {
    38400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Patrols'),
    38401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Trackers'),
    38402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Outposts'),
    38403: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_1', ItemType.building, 0, 'Progressive nor_allied_outpost', 'Nor Building: Norscan Outpost'),
    38404: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_2', ItemType.building, 1, 'Progressive nor_allied_outpost', 'Nor Building: Norscan District'),
    38405: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_3', ItemType.building, 2, 'Progressive nor_allied_outpost', 'Nor Building: Norscan Colony'),
    38406: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_1', ItemType.building, 0, 'Progressive pro_nor_settlement_major', 'Nor Building: Warrior Gathering'),
    38407: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_2', ItemType.building, 1, 'Progressive pro_nor_settlement_major', 'Nor Building: Warband Camp'),
    38408: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_3', ItemType.building, 2, 'Progressive pro_nor_settlement_major', 'Nor Building: Clan Enclave'),
    38409: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_4', ItemType.building, 3, 'Progressive pro_nor_settlement_major', 'Nor Building: Tribal Stronghold'),
    38410: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_5', ItemType.building, 4, 'Progressive pro_nor_settlement_major', 'Nor Building: Greater Tribal Stronghold'),
    38411: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_1', ItemType.building, 0, 'Progressive pro_nor_settlement_minor', 'Nor Building: Norse Encampment'),
    38412: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_2', ItemType.building, 1, 'Progressive pro_nor_settlement_minor', 'Nor Building: Norse Moot'),
    38413: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_3', ItemType.building, 2, 'Progressive pro_nor_settlement_minor', 'Nor Building: Norse Village'),
    38414: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_iron_1', ItemType.building, 0, 'Progressive nor_resource_iron', 'Nor Building: Iron Mine'),
    38415: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_marble_1', ItemType.building, 0, 'Progressive nor_resource_marble', 'Nor Building: Marble Quarry'),
    38416: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_obsidian_1', ItemType.building, 0, 'Progressive nor_resource_obsidian', 'Nor Building: Obsidian Quarry'),
    38417: ItemData(IC.useful, 1, 'wh_main_nor_beasts_1', ItemType.building, 0, 'Progressive nor_beasts', 'Nor Building: Warhound Kennels'),
    38418: ItemData(IC.useful, 1, 'wh_main_nor_beasts_2', ItemType.building, 1, 'Progressive nor_beasts', 'Nor Building: Warwolf Dens'),
    38419: ItemData(IC.useful, 1, 'wh_main_nor_beasts_3', ItemType.building, 2, 'Progressive nor_beasts', 'Nor Building: Cave of Dark Offerings'),
    38420: ItemData(IC.useful, 1, 'wh_main_nor_chaos_1', ItemType.building, 0, 'Progressive nor_chaos', 'Nor Building: Chaos Totem'),
    38421: ItemData(IC.useful, 1, 'wh_main_nor_chaos_2', ItemType.building, 1, 'Progressive nor_chaos', 'Nor Building: Altar of the Bloodfathers'),
    38422: ItemData(IC.useful, 1, 'wh_main_nor_creatures_1', ItemType.building, 0, 'Progressive nor_creatures', 'Nor Building: Wyrmchasm'),
    38423: ItemData(IC.useful, 1, 'wh_main_nor_creatures_2', ItemType.building, 1, 'Progressive nor_creatures', 'Nor Building: Storm-Beaten Cliffs'),
    38424: ItemData(IC.useful, 1, 'wh_main_nor_creatures_3', ItemType.building, 2, 'Progressive nor_creatures', 'Nor Building: Glacial Passages'),
    38425: ItemData(IC.useful, 1, 'wh_main_nor_garrison_1', ItemType.building, 0, 'Progressive nor_garrison', 'Nor Building: Guard Shack'),
    38426: ItemData(IC.useful, 1, 'wh_main_nor_garrison_2', ItemType.building, 1, 'Progressive nor_garrison', 'Nor Building: Watchtower'),
    38427: ItemData(IC.useful, 1, 'wh_main_nor_garrison_3', ItemType.building, 2, 'Progressive nor_garrison', 'Nor Building: Marauding Militia'),
    38428: ItemData(IC.useful, 1, 'wh_main_nor_loot_1', ItemType.building, 0, 'Progressive nor_loot', 'Nor Building: Loot Pile'),
    38429: ItemData(IC.useful, 1, 'wh_main_nor_loot_2', ItemType.building, 1, 'Progressive nor_loot', 'Nor Building: Trophies of Battle'),
    38430: ItemData(IC.useful, 1, 'wh_main_nor_loot_3', ItemType.building, 2, 'Progressive nor_loot', 'Nor Building: Plunder Hall'),
    38431: ItemData(IC.useful, 1, 'wh_main_nor_military_1', ItemType.building, 0, 'Progressive nor_military', 'Nor Building: Proving Pits'),
    38432: ItemData(IC.useful, 1, 'wh_main_nor_military_2', ItemType.building, 1, 'Progressive nor_military', 'Nor Building: Raiding Camps'),
    38433: ItemData(IC.useful, 1, 'wh_main_nor_military_3', ItemType.building, 2, 'Progressive nor_military', 'Nor Building: Warriorsâ€™ Hall'),
    38434: ItemData(IC.useful, 1, 'wh_main_nor_offerings_1', ItemType.building, 0, 'Progressive nor_offerings', 'Nor Building: Ice Troll Lair'),
    38435: ItemData(IC.useful, 1, 'wh_main_nor_offerings_2', ItemType.building, 1, 'Progressive nor_offerings', 'Nor Building: Frozen Cairn Field'),
    38436: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_1', ItemType.building, 0, 'Progressive nor_outpost_experience', 'Nor Building: Tattooist'),
    38437: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_2', ItemType.building, 1, 'Progressive nor_outpost_experience', 'Nor Building: Flesh Brander'),
    38438: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_3', ItemType.building, 2, 'Progressive nor_outpost_experience', 'Nor Building: Flesh Carver'),
    38439: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_1', ItemType.building, 0, 'Progressive nor_outpost_garrison', 'Nor Building: Guard Shack'),
    38440: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_2', ItemType.building, 1, 'Progressive nor_outpost_garrison', 'Nor Building: Watchtower'),
    38441: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_3', ItemType.building, 2, 'Progressive nor_outpost_garrison', 'Nor Building: Marauding Militia'),
    38442: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_1', ItemType.building, 0, 'Progressive nor_outpost_growth', 'Nor Building: Ruinous Altar'),
    38443: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_2', ItemType.building, 1, 'Progressive nor_outpost_growth', 'Nor Building: Chaos Shrine'),
    38444: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_3', ItemType.building, 2, 'Progressive nor_outpost_growth', 'Nor Building: Sacrificial Pyre'),
    38445: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_1', ItemType.building, 0, 'Progressive nor_outpost_income', "Nor Building: Whorl of Raiders' Remains"),
    38446: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_2', ItemType.building, 1, 'Progressive nor_outpost_income', 'Nor Building: Marauder Blood-Grove'),
    38447: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_3', ItemType.building, 2, 'Progressive nor_outpost_income', 'Nor Building: Trove Temple of Champions'),
    38448: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_1', ItemType.building, 0, 'Progressive nor_outpost_major_human', 'Nor Building: Coastal Enclave'),
    38449: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_2', ItemType.building, 1, 'Progressive nor_outpost_major_human', 'Nor Building: Tribal Anchorage'),
    38450: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_3', ItemType.building, 2, 'Progressive nor_outpost_major_human', 'Nor Building: Manmade Fjord'),
    38451: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_1', ItemType.building, 0, 'Progressive nor_outpost_military', 'Nor Building: Sparring Fields'),
    38452: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_2', ItemType.building, 1, 'Progressive nor_outpost_military', "Nor Building: Raiders' Camp"),
    38453: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_3', ItemType.building, 2, 'Progressive nor_outpost_military', "Nor Building: Chieftain's Hall"),
    38454: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_1', ItemType.building, 0, 'Progressive nor_outpost_stables', 'Nor Building: Shieling'),
    38455: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_2', ItemType.building, 1, 'Progressive nor_outpost_stables', 'Nor Building: Corral'),
    38456: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_3', ItemType.building, 2, 'Progressive nor_outpost_stables', 'Nor Building: Ruinous Stables'),
    38457: ItemData(IC.useful, 1, 'wh_main_nor_port_1', ItemType.building, 0, 'Progressive nor_port', 'Nor Building: Norsca Wharf'),
    38458: ItemData(IC.useful, 1, 'wh_main_nor_port_2', ItemType.building, 1, 'Progressive nor_port', 'Nor Building: Longship Builder'),
    38459: ItemData(IC.useful, 1, 'wh_main_nor_port_3', ItemType.building, 2, 'Progressive nor_port', 'Nor Building: Raiding Port'),
    38460: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_1', ItemType.building, 0, 'Progressive nor_settlement_major', 'Nor Building: Warrior Gathering'),
    38461: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_2', ItemType.building, 1, 'Progressive nor_settlement_major', 'Nor Building: Warband Camp'),
    38462: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_3', ItemType.building, 2, 'Progressive nor_settlement_major', 'Nor Building: Clan Enclave'),
    38463: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_4', ItemType.building, 3, 'Progressive nor_settlement_major', 'Nor Building: Tribal Stronghold'),
    38464: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_5', ItemType.building, 4, 'Progressive nor_settlement_major', 'Nor Building: Greater Tribal Stronghold'),
    38465: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_1', ItemType.building, 0, 'Progressive nor_settlement_minor', 'Nor Building: Norse Encampment'),
    38466: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_2', ItemType.building, 1, 'Progressive nor_settlement_minor', 'Nor Building: Norse Moot'),
    38467: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_3', ItemType.building, 2, 'Progressive nor_settlement_minor', 'Nor Building: Norse Village'),
    38468: ItemData(IC.useful, 1, 'wh_main_nor_slaves_1', ItemType.building, 0, 'Progressive nor_slaves', 'Nor Building: Fur Stash'),
    38469: ItemData(IC.useful, 1, 'wh_main_nor_slaves_2', ItemType.building, 1, 'Progressive nor_slaves', 'Nor Building: Beast Tanner'),
    38470: ItemData(IC.useful, 1, 'wh_main_nor_slaves_3', ItemType.building, 2, 'Progressive nor_slaves', "Nor Building: Slaver's Camp"),
    38471: ItemData(IC.useful, 1, 'wh_main_nor_smith_1', ItemType.building, 0, 'Progressive nor_smith', 'Nor Building: Smithy'),
    38472: ItemData(IC.useful, 1, 'wh_main_nor_smith_2', ItemType.building, 1, 'Progressive nor_smith', 'Nor Building: Ruinous Kiln'),
    38473: ItemData(IC.useful, 1, 'wh_main_nor_smith_3', ItemType.building, 2, 'Progressive nor_smith', 'Nor Building: Dark Furnace'),
    38474: ItemData(IC.useful, 1, 'wh_main_nor_stables_1', ItemType.building, 0, 'Progressive nor_stables', 'Nor Building: Shieling'),
    38475: ItemData(IC.useful, 1, 'wh_main_nor_stables_2', ItemType.building, 1, 'Progressive nor_stables', 'Nor Building: Corral'),
    38476: ItemData(IC.useful, 1, 'wh_main_nor_stables_3', ItemType.building, 2, 'Progressive nor_stables', 'Nor Building: Ruinous Stables'),
    38477: ItemData(IC.useful, 1, 'wh_main_nor_walls_1', ItemType.building, 0, 'Progressive nor_walls', 'Nor Building: Bloody Bulwark'),
    38478: ItemData(IC.useful, 1, 'wh_main_nor_walls_2', ItemType.building, 1, 'Progressive nor_walls', 'Nor Building: Skull-Laden Embankment'),
    38479: ItemData(IC.useful, 1, 'wh_main_nor_walls_3', ItemType.building, 2, 'Progressive nor_walls', 'Nor Building: Wall of Carcasses'),
    38480: ItemData(IC.useful, 1, 'wh_main_nor_worship_1', ItemType.building, 0, 'Progressive nor_worship', 'Nor Building: Ruinous Altar'),
    38481: ItemData(IC.useful, 1, 'wh_main_nor_worship_2', ItemType.building, 1, 'Progressive nor_worship', 'Nor Building: Chaos Shrine'),
    38482: ItemData(IC.useful, 1, 'wh_main_nor_worship_3', ItemType.building, 2, 'Progressive nor_worship', 'Nor Building: {{tr:building_culture_variants_name_wh_main_nor_worship_4wh_dlc08_nor_norsca}}'),
    38483: ItemData(IC.useful, 1, 'wh_main_nor_worship_4', ItemType.building, 3, 'Progressive nor_worship', 'Nor Building: Vitki Temple')
}

techs: dict[int, ItemData] = {
    38800: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_20', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Burning of the Wood Elves'),
    38801: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_21', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of the Forest'),
    38802: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_02', ItemType.tech, 2, 'Progressive tech_nor', "Nor Tech: Metalworker's Anvil"),
    38803: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_05', ItemType.tech, 3, 'Progressive tech_nor', "Nor Tech: Crafter's Barding"),
    38804: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_02', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Devastation of the Dark Elves'),
    38805: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_03', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Dark Sorcery'),
    38806: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_07', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Destruction of Bretonnia'),
    38807: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_08', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Grain & Grape'),
    38808: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_01', ItemType.tech, 0, 'Progressive tech_nor', 'Nor Tech: War Tools'),
    38809: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_03', ItemType.tech, 1, 'Progressive tech_nor', "Nor Tech: Bladeworker's Hammer"),
    38810: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_06', ItemType.tech, 2, 'Progressive tech_nor', "Nor Tech: Horsemaster's Clinchers"),
    38811: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_04', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Butchering of the High Elves'),
    38812: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_05', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of the Court'),
    38813: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_06', ItemType.tech, 3, 'Progressive tech_nor', 'Nor Tech: Marauders of the West'),
    38814: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_09', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Demise of Tilea'),
    38815: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_10', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of War & Coin'),
    38816: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_chaos_dwarfs_capital', ItemType.tech, 6, 'Progressive ie_tech', 'Nor Tech: Secrets of Labour & Industry'),
    38817: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_chaos_dwarfs', ItemType.tech, 5, 'Progressive ie_tech', 'Nor Tech: Demolition of the Chaos Dwarfs'),
    38818: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_04', ItemType.tech, 2, 'Progressive tech_nor', "Nor Tech: Axemaker's Stone"),
    38819: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_07', ItemType.tech, 3, 'Progressive tech_nor', "Nor Tech: Butcher's Captives"),
    38820: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_06', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Pillaging of the Lizardmen'),
    38821: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_07', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of the Ancients'),
    38822: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_02', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Longer Hulls'),
    38823: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_11', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Ravaging of the Dwarfs'),
    38824: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_12', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Mining & Machinery'),
    38825: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_cathay_capital', ItemType.tech, 6, 'Progressive ie_tech', 'Nor Tech: Secrets of Yin & Yang'),
    38826: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_cathay', ItemType.tech, 5, 'Progressive ie_tech', 'Nor Tech: Collapse of Grand Cathay'),
    38827: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_starter', ItemType.tech, 4, 'Progressive ie_tech', 'Nor Tech: A Land Beyond the Mountains'),
    38828: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_01', ItemType.tech, 3, 'Progressive tech_nor', 'Nor Tech: Scavengers of the New World'),
    38829: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_01', ItemType.tech, 0, 'Progressive tech_nor', "Nor Tech: Sea Marauder's Tools"),
    38830: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_03', ItemType.tech, 1, 'Progressive tech_nor', 'Nor Tech: Corpulent Sails'),
    38831: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_05', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Champions of War'),
    38832: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_ogre_kingdoms', ItemType.tech, 5, 'Progressive ie_tech', 'Nor Tech: Smashing the Ogre Kingdoms'),
    38833: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_ogre_kingdoms_capital', ItemType.tech, 6, 'Progressive ie_tech', 'Nor Tech: Secrets of Mountains & Valleys'),
    38834: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_02', ItemType.tech, 1, 'Progressive tech_nor', 'Nor Tech: Chaos Surge'),
    38835: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_03', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Ice-Blooded Strength'),
    38836: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_08', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Annihilation of the Skaven'),
    38837: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_09', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of the Under-Empire'),
    38838: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_04', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Stronger Oars'),
    38839: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_14', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Razing of the Empire'),
    38840: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_15', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Steel & Magic'),
    38841: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_01', ItemType.tech, 0, 'Progressive tech_nor', 'Nor Tech: Monster Hunter'),
    38842: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_04', ItemType.tech, 1, 'Progressive tech_nor', 'Nor Tech: Blood-Fuelled Hunger'),
    38843: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_05', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Baying to Morrslieb'),
    38844: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_10', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Plundering of the Tomb Kings'),
    38845: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_11', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Past Dynasties'),
    38846: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_13', ItemType.tech, 3, 'Progressive tech_nor', 'Nor Tech: Raiders of the East'),
    38847: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_16', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Ruination of the Vampire Counts'),
    38848: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_17', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Necromancy'),
    38849: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_06', ItemType.tech, 1, 'Progressive tech_nor', 'Nor Tech: One with Beasts'),
    38850: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_07', ItemType.tech, 2, 'Progressive tech_nor', 'Nor Tech: Master of Beasts'),
    38851: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_20', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Blockading the Vampire Coast'),
    38852: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_21', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of the Deep'),
    38853: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_18', ItemType.tech, 4, 'Progressive tech_nor', 'Nor Tech: Slaughtering of the Greenskins'),
    38854: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_19', ItemType.tech, 5, 'Progressive tech_nor', 'Nor Tech: Secrets of Gork & Mork'),
    38855: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_hate_kislev', ItemType.tech, 4, 'Progressive ie_tech', 'Nor Tech: Desolation of Kislev'),
    38856: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_kislev_capital', ItemType.tech, 5, 'Progressive ie_tech', 'Nor Tech: Secrets of the Ice')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    39300: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_nor', ItemType.building, 1, None, 'Progressive Nor Building: Foreign Slot Discovery Nor'),
    39301: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_nor', ItemType.building, 2, None, 'Progressive Nor Building: Foreign Slot Discovery Nor'),
    39302: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_nor', ItemType.building, 3, None, 'Progressive Nor Building: Foreign Slot Discovery Nor'),
    39303: ItemData(IC.useful, 1, 'Progressive nor_allied_outpost', ItemType.building, 1, None, 'Progressive Nor Building: Allied Outpost'),
    39304: ItemData(IC.useful, 2, 'Progressive nor_allied_outpost', ItemType.building, 2, None, 'Progressive Nor Building: Allied Outpost'),
    39305: ItemData(IC.useful, 3, 'Progressive nor_allied_outpost', ItemType.building, 3, None, 'Progressive Nor Building: Allied Outpost'),
    39306: ItemData(IC.useful, 1, 'Progressive pro_nor_settlement_major', ItemType.building, 1, None, 'Progressive Nor Building: Pro Settlement Major'),
    39307: ItemData(IC.useful, 2, 'Progressive pro_nor_settlement_major', ItemType.building, 2, None, 'Progressive Nor Building: Pro Settlement Major'),
    39308: ItemData(IC.useful, 3, 'Progressive pro_nor_settlement_major', ItemType.building, 3, None, 'Progressive Nor Building: Pro Settlement Major'),
    39309: ItemData(IC.useful, 4, 'Progressive pro_nor_settlement_major', ItemType.building, 4, None, 'Progressive Nor Building: Pro Settlement Major'),
    39310: ItemData(IC.useful, 5, 'Progressive pro_nor_settlement_major', ItemType.building, 5, None, 'Progressive Nor Building: Pro Settlement Major'),
    39311: ItemData(IC.useful, 1, 'Progressive pro_nor_settlement_minor', ItemType.building, 1, None, 'Progressive Nor Building: Pro Settlement Minor'),
    39312: ItemData(IC.useful, 2, 'Progressive pro_nor_settlement_minor', ItemType.building, 2, None, 'Progressive Nor Building: Pro Settlement Minor'),
    39313: ItemData(IC.useful, 3, 'Progressive pro_nor_settlement_minor', ItemType.building, 3, None, 'Progressive Nor Building: Pro Settlement Minor'),
    39314: ItemData(IC.useful, 1, 'Progressive nor_resource_iron', ItemType.building, 1, None, 'Progressive Nor Building: Iron'),
    39315: ItemData(IC.useful, 1, 'Progressive nor_resource_marble', ItemType.building, 1, None, 'Progressive Nor Building: Marble'),
    39316: ItemData(IC.useful, 1, 'Progressive nor_resource_obsidian', ItemType.building, 1, None, 'Progressive Nor Building: Obsidian'),
    39317: ItemData(IC.useful, 1, 'Progressive nor_beasts', ItemType.building, 1, None, 'Progressive Nor Building: Beasts'),
    39318: ItemData(IC.useful, 2, 'Progressive nor_beasts', ItemType.building, 2, None, 'Progressive Nor Building: Beasts'),
    39319: ItemData(IC.useful, 3, 'Progressive nor_beasts', ItemType.building, 3, None, 'Progressive Nor Building: Beasts'),
    39320: ItemData(IC.useful, 1, 'Progressive nor_chaos', ItemType.building, 1, None, 'Progressive Nor Building: Chaos'),
    39321: ItemData(IC.useful, 2, 'Progressive nor_chaos', ItemType.building, 2, None, 'Progressive Nor Building: Chaos'),
    39322: ItemData(IC.useful, 1, 'Progressive nor_creatures', ItemType.building, 1, None, 'Progressive Nor Building: Creatures'),
    39323: ItemData(IC.useful, 2, 'Progressive nor_creatures', ItemType.building, 2, None, 'Progressive Nor Building: Creatures'),
    39324: ItemData(IC.useful, 3, 'Progressive nor_creatures', ItemType.building, 3, None, 'Progressive Nor Building: Creatures'),
    39325: ItemData(IC.useful, 1, 'Progressive nor_garrison', ItemType.building, 1, None, 'Progressive Nor Building: Garrison'),
    39326: ItemData(IC.useful, 2, 'Progressive nor_garrison', ItemType.building, 2, None, 'Progressive Nor Building: Garrison'),
    39327: ItemData(IC.useful, 3, 'Progressive nor_garrison', ItemType.building, 3, None, 'Progressive Nor Building: Garrison'),
    39328: ItemData(IC.useful, 1, 'Progressive nor_loot', ItemType.building, 1, None, 'Progressive Nor Building: Loot'),
    39329: ItemData(IC.useful, 2, 'Progressive nor_loot', ItemType.building, 2, None, 'Progressive Nor Building: Loot'),
    39330: ItemData(IC.useful, 3, 'Progressive nor_loot', ItemType.building, 3, None, 'Progressive Nor Building: Loot'),
    39331: ItemData(IC.useful, 1, 'Progressive nor_military', ItemType.building, 1, None, 'Progressive Nor Building: Military'),
    39332: ItemData(IC.useful, 2, 'Progressive nor_military', ItemType.building, 2, None, 'Progressive Nor Building: Military'),
    39333: ItemData(IC.useful, 3, 'Progressive nor_military', ItemType.building, 3, None, 'Progressive Nor Building: Military'),
    39334: ItemData(IC.useful, 1, 'Progressive nor_offerings', ItemType.building, 1, None, 'Progressive Nor Building: Offerings'),
    39335: ItemData(IC.useful, 2, 'Progressive nor_offerings', ItemType.building, 2, None, 'Progressive Nor Building: Offerings'),
    39336: ItemData(IC.useful, 1, 'Progressive nor_outpost_experience', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Experience'),
    39337: ItemData(IC.useful, 2, 'Progressive nor_outpost_experience', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Experience'),
    39338: ItemData(IC.useful, 3, 'Progressive nor_outpost_experience', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Experience'),
    39339: ItemData(IC.useful, 1, 'Progressive nor_outpost_garrison', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Garrison'),
    39340: ItemData(IC.useful, 2, 'Progressive nor_outpost_garrison', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Garrison'),
    39341: ItemData(IC.useful, 3, 'Progressive nor_outpost_garrison', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Garrison'),
    39342: ItemData(IC.useful, 1, 'Progressive nor_outpost_growth', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Growth'),
    39343: ItemData(IC.useful, 2, 'Progressive nor_outpost_growth', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Growth'),
    39344: ItemData(IC.useful, 3, 'Progressive nor_outpost_growth', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Growth'),
    39345: ItemData(IC.useful, 1, 'Progressive nor_outpost_income', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Income'),
    39346: ItemData(IC.useful, 2, 'Progressive nor_outpost_income', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Income'),
    39347: ItemData(IC.useful, 3, 'Progressive nor_outpost_income', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Income'),
    39348: ItemData(IC.useful, 1, 'Progressive nor_outpost_major_human', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Major Human'),
    39349: ItemData(IC.useful, 2, 'Progressive nor_outpost_major_human', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Major Human'),
    39350: ItemData(IC.useful, 3, 'Progressive nor_outpost_major_human', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Major Human'),
    39351: ItemData(IC.useful, 1, 'Progressive nor_outpost_military', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Military'),
    39352: ItemData(IC.useful, 2, 'Progressive nor_outpost_military', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Military'),
    39353: ItemData(IC.useful, 3, 'Progressive nor_outpost_military', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Military'),
    39354: ItemData(IC.useful, 1, 'Progressive nor_outpost_stables', ItemType.building, 1, None, 'Progressive Nor Building: Outpost Stables'),
    39355: ItemData(IC.useful, 2, 'Progressive nor_outpost_stables', ItemType.building, 2, None, 'Progressive Nor Building: Outpost Stables'),
    39356: ItemData(IC.useful, 3, 'Progressive nor_outpost_stables', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Stables'),
    39357: ItemData(IC.useful, 1, 'Progressive nor_port', ItemType.building, 1, None, 'Progressive Nor Building: Port'),
    39358: ItemData(IC.useful, 2, 'Progressive nor_port', ItemType.building, 2, None, 'Progressive Nor Building: Port'),
    39359: ItemData(IC.useful, 3, 'Progressive nor_port', ItemType.building, 3, None, 'Progressive Nor Building: Port'),
    39360: ItemData(IC.useful, 1, 'Progressive nor_settlement_major', ItemType.building, 1, None, 'Progressive Nor Building: Settlement Major'),
    39361: ItemData(IC.useful, 2, 'Progressive nor_settlement_major', ItemType.building, 2, None, 'Progressive Nor Building: Settlement Major'),
    39362: ItemData(IC.useful, 3, 'Progressive nor_settlement_major', ItemType.building, 3, None, 'Progressive Nor Building: Settlement Major'),
    39363: ItemData(IC.useful, 4, 'Progressive nor_settlement_major', ItemType.building, 4, None, 'Progressive Nor Building: Settlement Major'),
    39364: ItemData(IC.useful, 5, 'Progressive nor_settlement_major', ItemType.building, 5, None, 'Progressive Nor Building: Settlement Major'),
    39365: ItemData(IC.useful, 1, 'Progressive nor_settlement_minor', ItemType.building, 1, None, 'Progressive Nor Building: Settlement Minor'),
    39366: ItemData(IC.useful, 2, 'Progressive nor_settlement_minor', ItemType.building, 2, None, 'Progressive Nor Building: Settlement Minor'),
    39367: ItemData(IC.useful, 3, 'Progressive nor_settlement_minor', ItemType.building, 3, None, 'Progressive Nor Building: Settlement Minor'),
    39368: ItemData(IC.useful, 1, 'Progressive nor_slaves', ItemType.building, 1, None, 'Progressive Nor Building: Slaves'),
    39369: ItemData(IC.useful, 2, 'Progressive nor_slaves', ItemType.building, 2, None, 'Progressive Nor Building: Slaves'),
    39370: ItemData(IC.useful, 3, 'Progressive nor_slaves', ItemType.building, 3, None, 'Progressive Nor Building: Slaves'),
    39371: ItemData(IC.useful, 1, 'Progressive nor_smith', ItemType.building, 1, None, 'Progressive Nor Building: Smith'),
    39372: ItemData(IC.useful, 2, 'Progressive nor_smith', ItemType.building, 2, None, 'Progressive Nor Building: Smith'),
    39373: ItemData(IC.useful, 3, 'Progressive nor_smith', ItemType.building, 3, None, 'Progressive Nor Building: Smith'),
    39374: ItemData(IC.useful, 1, 'Progressive nor_stables', ItemType.building, 1, None, 'Progressive Nor Building: Stables'),
    39375: ItemData(IC.useful, 2, 'Progressive nor_stables', ItemType.building, 2, None, 'Progressive Nor Building: Stables'),
    39376: ItemData(IC.useful, 3, 'Progressive nor_stables', ItemType.building, 3, None, 'Progressive Nor Building: Stables'),
    39377: ItemData(IC.useful, 1, 'Progressive nor_walls', ItemType.building, 1, None, 'Progressive Nor Building: Walls'),
    39378: ItemData(IC.useful, 2, 'Progressive nor_walls', ItemType.building, 2, None, 'Progressive Nor Building: Walls'),
    39379: ItemData(IC.useful, 3, 'Progressive nor_walls', ItemType.building, 3, None, 'Progressive Nor Building: Walls'),
    39380: ItemData(IC.useful, 1, 'Progressive nor_worship', ItemType.building, 1, None, 'Progressive Nor Building: Worship'),
    39381: ItemData(IC.useful, 2, 'Progressive nor_worship', ItemType.building, 2, None, 'Progressive Nor Building: Worship'),
    39382: ItemData(IC.useful, 3, 'Progressive nor_worship', ItemType.building, 3, None, 'Progressive Nor Building: Worship'),
    39383: ItemData(IC.useful, 4, 'Progressive nor_worship', ItemType.building, 4, None, 'Progressive Nor Building: Worship')
}

progTechs: dict[int, ItemData] = {
    39400: ItemData(IC.useful, 15, "Progressive tech_nor", ItemType.tech, 15, None, "Progressive Nor Tech"),
}

special: dict[int, ItemData] = {

}