from BaseClasses import ItemClassification as IC
from worlds.tww3.item_types import ItemType, ItemData, specialItemData

# @formatter:off
units: dict[int, ItemData] = {
    38000: ItemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Marauders'),
    38001: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_spearman_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Marauder Spearmen'),
    38002: ItemData(IC.useful, 1, 'wh_main_nor_inf_chaos_marauders_1', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Marauders (Great Weapons)'),
    38003: ItemData(IC.useful, 1, 'wh3_dlc27_nor_inf_marauder_bearmen', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Marauder Bearmen'),
    38004: ItemData(IC.useful, 1, 'wh3_dlc27_nor_inf_marauder_bearmen_greatweapons', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Marauder Bearmen (Great Weapons)'),
    38005: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_berserkers_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Marauder Berserkers'),
    38006: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_0', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Marauder Champions'),
    38007: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_champions_1', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Marauder Champions (Great Weapons)'),
    38008: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_0', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Skin Wolves'),
    38009: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_skinwolves_1', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Skin Wolves (Armoured)'),
    38010: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_trolls', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Norscan Trolls'),
    38011: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_ice_trolls_0', ItemType.unit, 2, 'Progressive nor_inf', 'Nor Unit: Norscan Ice Trolls'),
    38012: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Fimir Warriors'),
    38013: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_fimir_1', ItemType.unit, 4, 'Progressive nor_inf', 'Nor Unit: Fimir Warriors (Great Weapons)'),
    38014: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_0', ItemType.unit, 1, 'Progressive nor_rng', 'Nor Unit: Marauder Hunters'),
    38015: ItemData(IC.useful, 1, 'wh_dlc08_nor_inf_marauder_hunters_1', ItemType.unit, 1, 'Progressive nor_rng', 'Nor Unit: Marauder Hunters (Javelins)'),
    38016: ItemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_0', ItemType.unit, 1, 'Progressive nor_cav', 'Nor Unit: Marauder Horsemen'),
    38017: ItemData(IC.useful, 1, 'wh_main_nor_cav_marauder_horsemen_1', ItemType.unit, 2, 'Progressive nor_cav', 'Nor Unit: Marauder Horsemen (Throwing Axes)'),
    38018: ItemData(IC.useful, 1, 'wh_dlc08_nor_cav_marauder_horsemasters_0', ItemType.unit, 3, 'Progressive nor_cav', 'Nor Unit: Marauder Horsemasters'),
    38019: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_kurgan_horsemen_dualweapons', ItemType.unit, 3, 'Progressive nor_cav', 'Nor Unit: Kurgan Horsemen (Dual Weapons)'),
    38020: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_kurgan_horsemen_greatweapons', ItemType.unit, 3, 'Progressive nor_cav', 'Nor Unit: Kurgan Horsemen (Great Weapons)'),
    38021: ItemData(IC.useful, 1, 'wh_main_nor_cav_chaos_chariot', ItemType.unit, 1, 'Progressive nor_veh', 'Nor Unit: Marauder Chariots'),
    38022: ItemData(IC.useful, 1, 'wh_dlc08_nor_cav_marauder_warwolves_chariot_0', ItemType.unit, 2, 'Progressive nor_veh', 'Nor Unit: Marauder Ice Wolf Chariots'),
    38023: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_0', ItemType.unit, 1, 'Progressive nor_bst', 'Nor Unit: Norscan Warhounds'),
    38024: ItemData(IC.useful, 1, 'wh_main_nor_mon_chaos_warhounds_1', ItemType.unit, 1, 'Progressive nor_bst', 'Nor Unit: Norscan Warhounds (Poison)'),
    38025: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_marauder_warwolves_0', ItemType.unit, 2, 'Progressive nor_bst', 'Nor Unit: Norscan Ice Wolves'),
    38026: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_norscan_giant_0', ItemType.unit, 3, 'Progressive nor_bst', 'Nor Unit: Norscan Giant'),
    38027: ItemData(IC.useful, 1, 'wh3_dlc27_nor_mon_cursd_ettin', ItemType.unit, 4, 'Progressive nor_bst', "Nor Unit: Curs'd Ettin"),
    38028: ItemData(IC.useful, 1, 'wh3_dlc27_nor_mon_cursd_ettin_runecaller', ItemType.unit, 4, 'Progressive nor_bst', "Nor Unit: Curs'd Ettin (Runecaller)"),
    38029: ItemData(IC.useful, 1, 'wh_dlc08_nor_feral_manticore', ItemType.unit, 3, 'Progressive nor_bst', 'Nor Unit: Feral Manticore'),
    38030: ItemData(IC.useful, 1, 'wh3_dlc27_nor_mon_dread_maw', ItemType.unit, 3, 'Progressive nor_bst', 'Nor Unit: Dread Maw'),
    38031: ItemData(IC.useful, 1, 'wh3_dlc27_nor_mon_chimera', ItemType.unit, 4, 'Progressive nor_bst', 'Nor Unit: Chimera'),
    38032: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_0', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Chaos Frost Dragon'),
    38033: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_0', ItemType.unit, 4, 'Progressive nor_bst', 'Nor Unit: Feral Mammoth'),
    38034: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_1', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: War Mammoth'),
    38035: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_2', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: War Mammoth (Warshrine)'),
    38036: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cha_fimir_noble', ItemType.unit, 1, 'Progressive nor_hro', 'Nor Unit: Fimir Noble'),
    38037: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_skin_wolf_werekin_0', ItemType.unit, 2, 'Progressive nor_hro', 'Nor Unit: Skin Wolf Werekin'),
    38038: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_metal_0', ItemType.unit, 2, 'Progressive nor_hro', 'Nor Unit: Shaman-Sorcerer (Metal)'),
    38039: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_fire_0', ItemType.unit, 2, 'Progressive nor_hro', 'Nor Unit: Shaman-Sorcerer (Fire)'),
    38040: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_shaman_sorcerer_death_0', ItemType.unit, 2, 'Progressive nor_hro', 'Nor Unit: Shaman-Sorcerer (Death)'),
    38041: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_shadow_0', ItemType.unit, 3, 'Progressive nor_hro', 'Nor Unit: Fimir Balefiend (Shadows)'),
    38042: ItemData(IC.useful, 1, 'wh_dlc08_nor_cha_fimir_balefiend_fire_0', ItemType.unit, 3, 'Progressive nor_hro', 'Nor Unit: Fimir Balefiend (Fire)'),
    38043: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_war_mammoth_ror_1', ItemType.unit, 4, 'Progressive nor_bst', 'Nor Unit: The Great Mawherd of Bloodfjord (Feral Mammoths)'),
    38044: ItemData(IC.useful, 1, 'wh3_dlc27_nor_mon_chimera_ror', ItemType.unit, 4, 'Progressive nor_bst', 'Nor Unit: Bloodshriek Chimera (Chimera)'),
    38045: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_ror_0', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: The Cold-Voider (Chaos Frost Dragon)'),
    38046: ItemData(IC.useful, 1, 'wh3_dlc27_nor_inf_chaos_marauders_great_weapons_ror', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Worshippers of the Crow (Marauders - Great Weapons)'),
    38047: ItemData(IC.useful, 1, 'wh_pro04_nor_inf_chaos_marauders_ror_0', ItemType.unit, 1, 'Progressive nor_inf', 'Nor Unit: Icehorn Marauders (Marauders)'),
    38048: ItemData(IC.useful, 1, 'wh_dlc08_nor_mon_frost_wyrm_ror_0', ItemType.unit, 1, 'Progressive nor_cav', 'Nor Unit: Riders of the Mighty Serpent (Marauder Horsemen)'),
    38049: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_marauder_horsemen_ror', ItemType.unit, 1, 'Progressive nor_bst', 'Nor Unit: Beasts of Tashnar (Norscan Warhounds)'),
    38050: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_chaos_chariot_ror', ItemType.unit, 1, 'Progressive nor_veh', 'Nor Unit: Followers of the Great Eagle (Marauder Chariots)'),
    38051: ItemData(IC.useful, 1, 'wh_pro04_nor_inf_marauder_berserkers_ror_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Brutes of the Hound (Marauder Berserkers)'),
    38052: ItemData(IC.useful, 1, 'wh_pro04_nor_mon_skinwolves_ror_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Maws of Savagery (Skin Wolves - Armoured)'),
    38053: ItemData(IC.useful, 1, 'wh_pro04_nor_mon_fimir_ror_0', ItemType.unit, 3, 'Progressive nor_inf', 'Nor Unit: Mist Stalkers (Fimir Warriors)'),
    38054: ItemData(IC.useful, 1, 'wh_pro04_nor_mon_war_mammoth_ror_0', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Soulcrusher (War Mammoth)'),
    38055: ItemData(IC.useful, 1, 'wh_dlc08_nor_art_hellcannon_battery', ItemType.unit, 1, 'Progressive nor_art', 'Nor Unit: The Ice-Forged Legion (Hellcannons)'),
    38056: ItemData(IC.useful, 1, 'wh_dlc03_bst_inf_cygor_0', ItemType.unit, 1, 'Progressive nor_art', 'Nor Unit: Cygor'),
    38057: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_cockatrice', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Cockatrice'),
    38058: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_jabberslythe_0', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: JabberSlythe'),
    38059: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Preyton'),
    38060: ItemData(IC.useful, 1, 'wh2_dlc17_bst_mon_ghorgon_0', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Ghorgon'),
    38061: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_toad_dragon', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Toad Dragon'),
    38062: ItemData(IC.useful, 1, 'wh_dlc01_chs_mon_dragon_ogre_shaggoth', ItemType.unit, 5, 'Progressive nor_bst', 'Nor Unit: Dragon Ogre Shaggoth'),
}

buildings: dict[int, ItemData] = {
    38400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Patrols'),
    38401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Trackers'),
    38402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_nor_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_nor', 'Nor Building: Marauder Outposts'),
    38403: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_1', ItemType.building, 0, 'Progressive nor_allied_outpost', 'Nor Building: Norscan Outpost'),
    38404: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_2', ItemType.building, 1, 'Progressive nor_allied_outpost', 'Nor Building: Norscan District'),
    38405: ItemData(IC.useful, 1, 'wh3_main_nor_allied_outpost_3', ItemType.building, 2, 'Progressive nor_allied_outpost', 'Nor Building: Norscan Colony'),
    38406: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_1', ItemType.building, 0, 'Progressive nor_settlement_major', 'Nor Building: Warrior Gathering'),
    38407: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_2', ItemType.building, 1, 'Progressive nor_settlement_major', 'Nor Building: Warband Camp'),
    38408: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_3', ItemType.building, 2, 'Progressive nor_settlement_major', 'Nor Building: Clan Enclave'),
    38409: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_4', ItemType.building, 3, 'Progressive nor_settlement_major', 'Nor Building: Tribal Stronghold'),
    38410: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_major_5', ItemType.building, 4, 'Progressive nor_settlement_major', 'Nor Building: Greater Tribal Stronghold'),
    38411: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_1', ItemType.building, 0, 'Progressive nor_settlement_minor', 'Nor Building: Norse Encampment'),
    38412: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_2', ItemType.building, 1, 'Progressive nor_settlement_minor', 'Nor Building: Norse Moot'),
    38413: ItemData(IC.useful, 1, 'wh3_main_pro_nor_settlement_minor_3', ItemType.building, 2, 'Progressive nor_settlement_minor', 'Nor Building: Norse Village'),
    38414: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_iron_1', ItemType.building, 0, 'Progressive nor_resource_iron', 'Nor Building: Iron Mine'),
    38415: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_marble_1', ItemType.building, 0, 'Progressive nor_resource_marble', 'Nor Building: Marble Quarry'),
    38416: ItemData(IC.useful, 1, 'wh_dlc08_nor_resource_obsidian_1', ItemType.building, 0, 'Progressive nor_resource_obsidian', 'Nor Building: Obsidian Quarry'),
    38417: ItemData(IC.useful, 1, 'wh_main_nor_beasts_1', ItemType.building, 0, 'Progressive nor_beasts', 'Nor Building: Warhound Kennels'),
    38418: ItemData(IC.useful, 1, 'wh_main_nor_beasts_2', ItemType.building, 1, 'Progressive nor_beasts', 'Nor Building: Warwolf Dens'),
    38419: ItemData(IC.useful, 1, 'wh_main_nor_beasts_3', ItemType.building, 2, 'Progressive nor_beasts', 'Nor Building: Cave of Dark Offerings'),
    38420: ItemData(IC.useful, 1, 'wh_main_nor_chaos_1', ItemType.building, 0, 'Progressive nor_chaos', 'Nor Building: Chaos Totem'),
    38421: ItemData(IC.useful, 1, 'wh_main_nor_chaos_2', ItemType.building, 1, 'Progressive nor_chaos', 'Nor Building: Altar of the Bloodfathers'),
    38422: ItemData(IC.useful, 1, 'wh_main_nor_chaos_2b', ItemType.building, 1, 'Progressive nor_chaos', 'Nor Building: Shamanic Tribute'),
    38423: ItemData(IC.useful, 1, 'wh_main_nor_chaos_3', ItemType.building, 2, 'Progressive nor_chaos', 'Nor Building: Shamanic Pyre'),
    38424: ItemData(IC.useful, 1, 'wh_main_nor_creatures_0', ItemType.building, 0, 'Progressive nor_creatures', 'Nor Building: Fog-Shrouded Fens'),
    38425: ItemData(IC.useful, 1, 'wh_main_nor_creatures_1', ItemType.building, 1, 'Progressive nor_creatures', 'Nor Building: Wyrmchasm'),
    38426: ItemData(IC.useful, 1, 'wh_main_nor_creatures_2', ItemType.building, 2, 'Progressive nor_creatures', 'Nor Building: Storm-Beaten Cliffs'),
    38427: ItemData(IC.useful, 1, 'wh_main_nor_creatures_2b', ItemType.building, 2, 'Progressive nor_creatures', 'Nor Building: Henge of Totems'),
    38428: ItemData(IC.useful, 1, 'wh_main_nor_creatures_3', ItemType.building, 3, 'Progressive nor_creatures', 'Nor Building: Glacial Passages'),
    38429: ItemData(IC.useful, 1, 'wh_main_nor_garrison_1', ItemType.building, 0, 'Progressive nor_garrison', 'Nor Building: Guard Shack'),
    38430: ItemData(IC.useful, 1, 'wh_main_nor_garrison_2', ItemType.building, 1, 'Progressive nor_garrison', 'Nor Building: Watchtower'),
    38431: ItemData(IC.useful, 1, 'wh_main_nor_garrison_3', ItemType.building, 2, 'Progressive nor_garrison', 'Nor Building: Marauding Militia'),
    38432: ItemData(IC.useful, 1, 'wh_main_nor_garrison_3b', ItemType.building, 2, 'Progressive nor_garrison', 'Nor Building: Feral Wardens'),
    38433: ItemData(IC.useful, 1, 'wh_main_nor_loot_1', ItemType.building, 0, 'Progressive nor_loot', 'Nor Building: Loot Pile'),
    38434: ItemData(IC.useful, 1, 'wh_main_nor_loot_2', ItemType.building, 1, 'Progressive nor_loot', 'Nor Building: Trophies of Battle'),
    38435: ItemData(IC.useful, 1, 'wh_main_nor_loot_2b', ItemType.building, 1, 'Progressive nor_loot', 'Nor Building: Hoard Pit'),
    38436: ItemData(IC.useful, 1, 'wh_main_nor_loot_3', ItemType.building, 2, 'Progressive nor_loot', 'Nor Building: Plunder Hall'),
    38437: ItemData(IC.useful, 1, 'wh_main_nor_loot_3b', ItemType.building, 2, 'Progressive nor_loot', 'Nor Building: Barrow Hoard'),
    38438: ItemData(IC.useful, 1, 'wh_main_nor_military_1', ItemType.building, 0, 'Progressive nor_military', 'Nor Building: Proving Pits'),
    38439: ItemData(IC.useful, 1, 'wh_main_nor_military_2', ItemType.building, 1, 'Progressive nor_military', 'Nor Building: Raiding Camps'),
    38440: ItemData(IC.useful, 1, 'wh_main_nor_military_3', ItemType.building, 2, 'Progressive nor_military', "Nor Building: Warriors' Hall"),
    38441: ItemData(IC.useful, 1, 'wh3_dlc27_nor_military_3b', ItemType.building, 2, 'Progressive nor_military', "Nor Building: Raiders' Bazaar"),
    38442: ItemData(IC.useful, 1, 'wh3_dlc27_nor_military_4', ItemType.building, 3, 'Progressive nor_military', "Nor Building: Chieftain's Hall"),
    38443: ItemData(IC.useful, 1, 'wh_main_nor_offerings_1', ItemType.building, 0, 'Progressive nor_offerings', 'Nor Building: Ice Troll Lair'),
    38444: ItemData(IC.useful, 1, 'wh_main_nor_offerings_2', ItemType.building, 1, 'Progressive nor_offerings', 'Nor Building: Frozen Cairn Field'),
    38445: ItemData(IC.useful, 1, 'wh_main_nor_port_1', ItemType.building, 0, 'Progressive nor_port', 'Nor Building: Norsca Wharf'),
    38446: ItemData(IC.useful, 1, 'wh_main_nor_port_2', ItemType.building, 1, 'Progressive nor_port', 'Nor Building: Longship Builder'),
    38447: ItemData(IC.useful, 1, 'wh_main_nor_port_3', ItemType.building, 2, 'Progressive nor_port', 'Nor Building: Raiding Port'),
    38448: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_1', ItemType.building, 0, 'Progressive nor_settlement_major', 'Nor Building: Warrior Gathering'),
    38449: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_2', ItemType.building, 1, 'Progressive nor_settlement_major', 'Nor Building: Warband Camp'),
    38450: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_3', ItemType.building, 2, 'Progressive nor_settlement_major', 'Nor Building: Clan Enclave'),
    38451: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_4', ItemType.building, 3, 'Progressive nor_settlement_major', 'Nor Building: Tribal Stronghold'),
    38452: ItemData(IC.useful, 1, 'wh_main_nor_settlement_major_5', ItemType.building, 4, 'Progressive nor_settlement_major', 'Nor Building: Greater Tribal Stronghold'),
    38453: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_1', ItemType.building, 0, 'Progressive nor_settlement_minor', 'Nor Building: Norse Encampment'),
    38454: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_2', ItemType.building, 1, 'Progressive nor_settlement_minor', 'Nor Building: Norse Moot'),
    38455: ItemData(IC.useful, 1, 'wh_main_nor_settlement_minor_3', ItemType.building, 2, 'Progressive nor_settlement_minor', 'Nor Building: Norse Village'),
    38456: ItemData(IC.useful, 1, 'wh_main_nor_slaves_1', ItemType.building, 0, 'Progressive nor_slaves', 'Nor Building: Fur Stash'),
    38457: ItemData(IC.useful, 1, 'wh_main_nor_slaves_2', ItemType.building, 1, 'Progressive nor_slaves', 'Nor Building: Beast Tanner'),
    38458: ItemData(IC.useful, 1, 'wh_main_nor_slaves_3', ItemType.building, 2, 'Progressive nor_slaves', "Nor Building: Slaver's Camp"),
    38459: ItemData(IC.useful, 1, 'wh3_dlc27_nor_slaves_4', ItemType.building, 3, 'Progressive nor_slaves', 'Nor Building: Longhouse Under-Hall'),
    38460: ItemData(IC.useful, 1, 'wh_main_nor_smith_1', ItemType.building, 0, 'Progressive nor_smith', 'Nor Building: Smithy'),
    38461: ItemData(IC.useful, 1, 'wh_main_nor_smith_2', ItemType.building, 1, 'Progressive nor_smith', 'Nor Building: Ruinous Kiln'),
    38462: ItemData(IC.useful, 1, 'wh_main_nor_smith_3', ItemType.building, 2, 'Progressive nor_smith', 'Nor Building: Dark Furnace'),
    38463: ItemData(IC.useful, 1, 'wh_main_nor_stables_1', ItemType.building, 0, 'Progressive nor_stables', 'Nor Building: Shieling'),
    38464: ItemData(IC.useful, 1, 'wh_main_nor_stables_2', ItemType.building, 1, 'Progressive nor_stables', 'Nor Building: Corral'),
    38465: ItemData(IC.useful, 1, 'wh_main_nor_stables_3', ItemType.building, 2, 'Progressive nor_stables', 'Nor Building: Ruinous Stables'),
    38466: ItemData(IC.useful, 1, 'wh_main_nor_walls_1', ItemType.building, 0, 'Progressive nor_walls', 'Nor Building: Bloody Bulwark'),
    38467: ItemData(IC.useful, 1, 'wh_main_nor_walls_2', ItemType.building, 1, 'Progressive nor_walls', 'Nor Building: Skull-Laden Embankment'),
    38468: ItemData(IC.useful, 1, 'wh_main_nor_walls_3', ItemType.building, 2, 'Progressive nor_walls', 'Nor Building: Wall of Carcasses'),
    38469: ItemData(IC.useful, 1, 'wh_main_nor_walls_4', ItemType.building, 3, 'Progressive nor_walls', 'Nor Building: Figurehead Palisade'),
    38470: ItemData(IC.useful, 1, 'wh_main_nor_worship_1', ItemType.building, 0, 'Progressive nor_worship', 'Nor Building: Ruinous Altar'),
    38471: ItemData(IC.useful, 1, 'wh_main_nor_worship_2', ItemType.building, 1, 'Progressive nor_worship', 'Nor Building: Chaos Shrine'),
    38472: ItemData(IC.useful, 1, 'wh_main_nor_worship_3', ItemType.building, 2, 'Progressive nor_worship', 'Nor Building: Vitki Temple')
    #38436: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_1', ItemType.building, 0, 'Progressive nor_outpost_experience', 'Nor Building: Tattooist'),
    #38437: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_2', ItemType.building, 1, 'Progressive nor_outpost_experience', 'Nor Building: Flesh Brander'),
    #38438: ItemData(IC.useful, 1, 'wh_main_nor_outpost_experience_3', ItemType.building, 2, 'Progressive nor_outpost_experience', 'Nor Building: Flesh Carver'),
    #38439: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_1', ItemType.building, 0, 'Progressive nor_outpost_garrison', 'Nor Building: Guard Shack'),
    #38440: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_2', ItemType.building, 1, 'Progressive nor_outpost_garrison', 'Nor Building: Watchtower'),
    #38441: ItemData(IC.useful, 1, 'wh_main_nor_outpost_garrison_3', ItemType.building, 2, 'Progressive nor_outpost_garrison', 'Nor Building: Marauding Militia'),
    #38442: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_1', ItemType.building, 0, 'Progressive nor_outpost_growth', 'Nor Building: Ruinous Altar'),
    #38443: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_2', ItemType.building, 1, 'Progressive nor_outpost_growth', 'Nor Building: Chaos Shrine'),
    #38444: ItemData(IC.useful, 1, 'wh_main_nor_outpost_growth_3', ItemType.building, 2, 'Progressive nor_outpost_growth', 'Nor Building: Sacrificial Pyre'),
    #38445: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_1', ItemType.building, 0, 'Progressive nor_outpost_income', "Nor Building: Whorl of Raiders' Remains"),
    #38446: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_2', ItemType.building, 1, 'Progressive nor_outpost_income', 'Nor Building: Marauder Blood-Grove'),
    #38447: ItemData(IC.useful, 1, 'wh_main_nor_outpost_income_3', ItemType.building, 2, 'Progressive nor_outpost_income', 'Nor Building: Trove Temple of Champions'),
    #38448: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_1', ItemType.building, 0, 'Progressive nor_outpost_major_human', 'Nor Building: Coastal Enclave'),
    #38449: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_2', ItemType.building, 1, 'Progressive nor_outpost_major_human', 'Nor Building: Tribal Anchorage'),
    #38450: ItemData(IC.useful, 1, 'wh_main_nor_outpost_major_human_3', ItemType.building, 2, 'Progressive nor_outpost_major_human', 'Nor Building: Manmade Fjord'),
    #38451: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_1', ItemType.building, 0, 'Progressive nor_outpost_military', 'Nor Building: Sparring Fields'),
    #38452: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_2', ItemType.building, 1, 'Progressive nor_outpost_military', "Nor Building: Raiders' Camp"),
    #38453: ItemData(IC.useful, 1, 'wh_main_nor_outpost_military_3', ItemType.building, 2, 'Progressive nor_outpost_military', "Nor Building: Chieftain's Hall"),
    #38454: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_1', ItemType.building, 0, 'Progressive nor_outpost_stables', 'Nor Building: Shieling'),
    #38455: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_2', ItemType.building, 1, 'Progressive nor_outpost_stables', 'Nor Building: Corral'),
    #38456: ItemData(IC.useful, 1, 'wh_main_nor_outpost_stables_3', ItemType.building, 2, 'Progressive nor_outpost_stables', 'Nor Building: Ruinous Stables'),
}

techs: dict[int, ItemData] = {
    38800: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_20', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Burning of the Wood Elves'),
    38801: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_07', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Destruction of Bretonnia'),
    38802: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_16', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Ruination of the Vampire Counts'),
    38803: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_11', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Ravaging of the Dwarfs'),
    38804: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_hate_kislev', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Desolation of Kislev'),
    38805: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_14', ItemType.tech, 1, 'Progressive tech_nor_old_world', 'Nor Tech: Razing of the Empire'),
    38806: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_02', ItemType.tech, 1, 'Progressive tech_nor_new_world', 'Nor Tech: Devastation of the Dark Elves'),
    38807: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_04', ItemType.tech, 1, 'Progressive tech_nor_new_world', 'Nor Tech: Butchering of the High Elves'),
    38808: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_06', ItemType.tech, 1, 'Progressive tech_nor_new_world', 'Nor Tech: Pillaging of the Lizardmen'),
    38809: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_20', ItemType.tech, 1, 'Progressive tech_nor_new_world', 'Nor Tech: Blockading the Vampire Coast'),
    38810: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_10', ItemType.tech, 1, 'Progressive tech_nor_badlands', 'Nor Tech: Plundering of the Tomb Kings'),
    38811: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_08', ItemType.tech, 1, 'Progressive tech_nor_badlands', 'Nor Tech: Annihilation of the Skaven'),
    38812: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_18', ItemType.tech, 1, 'Progressive tech_nor_badlands', 'Nor Tech: Slaughtering of the Greenskins'),
    38813: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_chaos_dwarfs', ItemType.tech, 1, 'Progressive tech_nor_beyond', 'Nor Tech: Demolition of the Chaos Dwarfs'),
    38814: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_cathay', ItemType.tech, 1, 'Progressive tech_nor_beyond', 'Nor Tech: Collapse of Grand Cathay'),
    38815: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_darklands_hate_ogre_kingdoms', ItemType.tech, 1, 'Progressive tech_nor_beyond', 'Nor Tech: Smashing the Ogre Kingdoms'),
    38816: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_slaanesh', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: As the serpent '),
    38817: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_khorne', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: Running With the Hound'),
    38818: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_tzeentch', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: Dreams Become Real'),
    38819: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_nurgle', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: The Cold and the Crow'),
    38820: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_norsca', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: Masters of the North'),
    38821: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_beastmen', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: Hunting of the Beastmen '),
    38822: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cul_chaos', ItemType.tech, 1, 'Progressive tech_nor_wastes', 'Nor Tech: True Warriors of Chaos '),
    38823: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_02', ItemType.tech, 1, 'Progressive tech_nor_customs', 'Nor Tech: Chaos Surge'),
    38824: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_03', ItemType.tech, 2, 'Progressive tech_nor_customs', "Nor Tech: Bladeworker's Hammer"),
    38825: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_04', ItemType.tech, 2, 'Progressive tech_nor_customs', "Nor Tech: Axemaker's Stone"),
    38826: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_05', ItemType.tech, 3, 'Progressive tech_nor_customs', "Nor Tech: Crafter's Barding"),
    38827: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_06', ItemType.tech, 3, 'Progressive tech_nor_customs', "Nor Tech: Horsemaster's Clinchers"),
    38828: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_02', ItemType.tech, 4, 'Progressive tech_nor_customs', "Nor Tech: Metalworker's Anvil"),
    38829: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_05', ItemType.tech, 5, 'Progressive tech_nor_customs', 'Nor Tech: Champions of War'),
    38830: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_nocturnality', ItemType.tech, 1, 'Progressive tech_nor_customs', 'Nor Tech: Natural Selection'),
    38831: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_06', ItemType.tech, 2, 'Progressive tech_nor_customs', 'Nor Tech: One with Beasts'),
    38832: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_elder_trolls', ItemType.tech, 2, 'Progressive tech_nor_customs', 'Nor Tech: Elder Trolls'),
    38833: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_04', ItemType.tech, 3, 'Progressive tech_nor_customs', 'Nor Tech: Blood-Fuelled Hunger'),
    38834: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_leading', ItemType.tech, 3, 'Progressive tech_nor_customs', 'Nor Tech: Occasional Appeasement'),
    38835: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_tough_skin', ItemType.tech, 4, 'Progressive tech_nor_customs', 'Nor Tech: Violent Evolution'),
    38836: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_taming', ItemType.tech, 1, 'Progressive tech_nor_customs', 'Nor Tech: Secrets of Taming'),
    38837: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_05', ItemType.tech, 2, 'Progressive tech_nor_customs', 'Nor Tech: Baying to Morrslieb'),
    38838: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_great_deal', ItemType.tech, 2, 'Progressive tech_nor_customs', 'Nor Tech: Gigantic Armaments'),
    38839: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_01', ItemType.tech, 3, 'Progressive tech_nor_customs', 'Nor Tech: Monster Hunter'),
    38840: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_lumbering', ItemType.tech, 3, 'Progressive tech_nor_customs', 'Nor Tech: Everliving Spite'),
    38841: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_hardened_tusks', ItemType.tech, 4, 'Progressive tech_nor_customs', 'Nor Tech: Deadly Prey'),
    38842: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_07', ItemType.tech, 5, 'Progressive tech_nor_customs', 'Nor Tech: Master of Beasts'),
    38843: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_rally_tribes', ItemType.tech, 5, 'Progressive tech_nor_customs', 'Nor Tech: Rally the Tribes'),
    38844: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_feasting', ItemType.tech, 6, 'Progressive tech_nor_customs', 'Nor Tech: Seat at the Table'),
    38845: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_nw_03', ItemType.tech, 7, 'Progressive tech_nor_customs', 'Nor Tech: Secrets of Dark Sorcery'),
    38846: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_creatures_03', ItemType.tech, 8, 'Progressive tech_nor_customs', 'Nor Tech: Ice-Blooded Strength'),
    38847: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_potions', ItemType.tech, 6, 'Progressive tech_nor_customs', 'Nor Tech: What the Blood Shows'),
    38848: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_shamans', ItemType.tech, 7, 'Progressive tech_nor_customs', 'Nor Tech: What the Shamans Know'),
    38849: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_mil_regenerating', ItemType.tech, 8, 'Progressive tech_nor_customs', 'Nor Tech: What Starts the War'),
    38850: ItemData(IC.useful, 1, 'wh3_main_ie_tech_nor_oldworld_kislev_capital', ItemType.tech, 9, 'Progressive tech_nor_customs', 'Nor Tech: Secrets of the Ice'),
    38851: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_watchtower', ItemType.tech, 1, 'Progressive tech_nor_tribal_1', 'Nor Tech: Untiring Sentries'),
    38852: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_palisade', ItemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Nor Tech: None Shall Enter'),
    38853: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_purpose', ItemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Nor Tech: Dark Purpose'),
    38854: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_crow', ItemType.tech, 2, 'Progressive tech_nor_tribal_1', 'Nor Tech: Beware the Crow'),
    38855: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_weapons', ItemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Nor Tech: Call of the Horn'),
    38856: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_cartographers', ItemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Nor Tech: Deliberate Service'),
    38857: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_envoy', ItemType.tech, 3, 'Progressive tech_nor_tribal_1', 'Nor Tech: A Reminder of Strength'),
    38858: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_campfire', ItemType.tech, 4, 'Progressive tech_nor_tribal_1', 'Nor Tech: A Taste of Bloody Triumph'),
    38859: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_ship_cam_advantage', ItemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Nor Tech: Rousing Advantage'),
    38860: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_worship', ItemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Nor Tech: The Eyes of the Four'),
    38861: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_01', ItemType.tech, 5, 'Progressive tech_nor_tribal_1', 'Nor Tech: War Tools'),
    38862: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_02', ItemType.tech, 6, 'Progressive tech_nor_tribal_1', 'Nor Tech: Longer Hulls'),
    38863: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_scavenge', ItemType.tech, 6, 'Progressive tech_nor_tribal_1', 'Nor Tech: Under Their Gaze'),
    38864: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_watchtower', ItemType.tech, 6, 'Progressive wh3_dlc27_tech_nor_cam_quartermasters', 'Nor Tech: Tools of War'),
    38865: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_leaders', ItemType.tech, 7, 'Progressive tech_nor_tribal_1', 'Nor Tech: Those Who Are Seen'),
    38866: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_other_22', ItemType.tech, 1, 'Progressive tech_nor_tribal_2', 'Nor Tech: Sagas of the Stars'),
    38867: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_pillagers', ItemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Nor Tech: Scourges of the World'),
    38868: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_walkers', ItemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Nor Tech: The Wanderers'),
    38869: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_large_traps', ItemType.tech, 2, 'Progressive tech_nor_tribal_2', 'Nor Tech: Norscan Hunter Traps'),
    38870: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_whispers', ItemType.tech, 3, 'Progressive tech_nor_tribal_2', 'Nor Tech: What is Taken'),
    38871: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_01', ItemType.tech, 3, 'Progressive tech_nor_tribal_2', "Nor Tech: Sea Marauder's Tools"),
    38872: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_northlands', ItemType.tech, 3, 'Progressive tech_nor_tribal_2', 'Nor Tech: Secrets of the Northlands'),
    38873: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_04', ItemType.tech, 4, 'Progressive tech_nor_tribal_2', 'Nor Tech: Stronger Oars'),
    38874: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_10', ItemType.tech, 5, 'Progressive tech_nor_tribal_2', 'Nor Tech: Secrets of War & Coin'),
    38875: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_marauders_07', ItemType.tech, 5, 'Progressive tech_nor_tribal_2', "Nor Tech: Butcher's Captives"),
    38876: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_wind', ItemType.tech, 5, 'Progressive tech_nor_tribal_2', 'Nor Tech: Winds of the North'),
    38877: ItemData(IC.useful, 1, 'wh_dlc08_tech_nor_other_03', ItemType.tech, 6, 'Progressive tech_nor_tribal_2', 'Nor Tech: Corpulent Sails'),
    38878: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_waters', ItemType.tech, 6, 'Progressive tech_nor_tribal_2', 'Nor Tech: Sail With the Waters'),
    38879: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_familiar', ItemType.tech, 6, 'Progressive wh3_dlc27_tech_nor_cam_quartermasters', 'Nor Tech: The Fourfold Voice'),
    38880: ItemData(IC.useful, 1, 'wh3_dlc27_tech_nor_cam_persistence', ItemType.tech, 7, 'Progressive tech_nor_tribal_2', 'Nor Tech: The Hound Watches')
}

progUnits: dict[int, ItemData] = {
    39200: ItemData(IC.useful, 5, "Progressive nor_inf", ItemType.unit, 5, "", "Progressive Nor Unit: Infantry"),
    39201: ItemData(IC.useful, 1, "Progressive nor_rng", ItemType.unit, 1, "", "Progressive Nor Unit: Ranged"),
    39202: ItemData(IC.useful, 3, "Progressive nor_cav", ItemType.unit, 3, "", "Progressive Nor Unit: Cavalry"),
    39203: ItemData(IC.useful, 1, "Progressive nor_art", ItemType.unit, 1, "", "Progressive Nor Unit: Artillery"),
    39204: ItemData(IC.useful, 2, "Progressive nor_veh", ItemType.unit, 2, "", "Progressive Nor Unit: Chariot"),
    39205: ItemData(IC.useful, 5, "Progressive nor_bst", ItemType.unit, 5, "", "Progressive Nor Unit: Beast"),
    39206: ItemData(IC.useful, 3, "Progressive nor_hro", ItemType.unit, 3, "", "Progressive Nor Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    39300: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_nor', ItemType.building, 3, None, 'Progressive Nor Building: Foreign Slot Discovery Nor'),
    39301: ItemData(IC.useful, 3, 'Progressive nor_allied_outpost', ItemType.building, 3, None, 'Progressive Nor Building: Allied Outpost'),
    39302: ItemData(IC.useful, 5, 'Progressive nor_settlement_major', ItemType.building, 5, None, 'Progressive Nor Building: Settlement Major'),
    39303: ItemData(IC.useful, 3, 'Progressive nor_settlement_major', ItemType.building, 3, None, 'Progressive Nor Building: Settlement Minor'),
    39304: ItemData(IC.useful, 1, 'Progressive nor_resource_iron', ItemType.building, 1, None, 'Progressive Nor Building: Iron'),
    39305: ItemData(IC.useful, 1, 'Progressive nor_resource_marble', ItemType.building, 1, None, 'Progressive Nor Building: Marble'),
    39306: ItemData(IC.useful, 1, 'Progressive nor_resource_obsidian', ItemType.building, 1, None, 'Progressive Nor Building: Obsidian'),
    39307: ItemData(IC.useful, 3, 'Progressive nor_beasts', ItemType.building, 3, None, 'Progressive Nor Building: Beasts'),
    39308: ItemData(IC.useful, 2, 'Progressive nor_chaos', ItemType.building, 2, None, 'Progressive Nor Building: Chaos'),
    39309: ItemData(IC.useful, 3, 'Progressive nor_creatures', ItemType.building, 3, None, 'Progressive Nor Building: Creatures'),
    39310: ItemData(IC.useful, 3, 'Progressive nor_garrison', ItemType.building, 3, None, 'Progressive Nor Building: Garrison'),
    39311: ItemData(IC.useful, 3, 'Progressive nor_loot', ItemType.building, 3, None, 'Progressive Nor Building: Loot'),
    39312: ItemData(IC.useful, 3, 'Progressive nor_military', ItemType.building, 3, None, 'Progressive Nor Building: Military'),
    39313: ItemData(IC.useful, 2, 'Progressive nor_offerings', ItemType.building, 2, None, 'Progressive Nor Building: Offerings'),
    39314: ItemData(IC.useful, 3, 'Progressive nor_outpost_experience', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Experience'),
    39315: ItemData(IC.useful, 3, 'Progressive nor_outpost_garrison', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Garrison'),
    39316: ItemData(IC.useful, 3, 'Progressive nor_outpost_growth', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Growth'),
    39317: ItemData(IC.useful, 3, 'Progressive nor_outpost_income', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Income'),
    39318: ItemData(IC.useful, 3, 'Progressive nor_outpost_major_human', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Major Human'),
    39319: ItemData(IC.useful, 3, 'Progressive nor_outpost_military', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Military'),
    39320: ItemData(IC.useful, 3, 'Progressive nor_outpost_stables', ItemType.building, 3, None, 'Progressive Nor Building: Outpost Stables'),
    39321: ItemData(IC.useful, 3, 'Progressive nor_port', ItemType.building, 3, None, 'Progressive Nor Building: Port'),
    39322: ItemData(IC.useful, 3, 'Progressive nor_slaves', ItemType.building, 3, None, 'Progressive Nor Building: Slaves'),
    39323: ItemData(IC.useful, 3, 'Progressive nor_smith', ItemType.building, 3, None, 'Progressive Nor Building: Smith'),
    39324: ItemData(IC.useful, 3, 'Progressive nor_stables', ItemType.building, 3, None, 'Progressive Nor Building: Stables'),
    39325: ItemData(IC.useful, 3, 'Progressive nor_walls', ItemType.building, 3, None, 'Progressive Nor Building: Walls'),
    39326: ItemData(IC.useful, 4, 'Progressive nor_worship', ItemType.building, 4, None, 'Progressive Nor Building: Worship'),
    39327: ItemData(IC.useful, 3, 'Progressive nor_settlement_shrine', ItemType.building, 2, None, 'Progressive Nor Building: Altar'),
    39328: ItemData(IC.useful, 3, 'Progressive nor_shrine_raiding', ItemType.building, 2, None, 'Progressive Nor Building: Raiding'),
    39329: ItemData(IC.useful, 3, 'Progressive nor_shrine_recruitment', ItemType.building, 2, None, 'Progressive Nor Building: Desecrated Site'),
    39330: ItemData(IC.useful, 3, 'Progressive nor_shrine_replenishment', ItemType.building, 2, None, 'Progressive Nor Building: Replenishment'),
    39331: ItemData(IC.useful, 3, 'Progressive nor_shrine_garrison', ItemType.building, 1, None, 'Progressive Nor Building: Garrison')
}

progTechs: dict[int, ItemData] = {
    39400: ItemData(IC.useful, 9, "Progressive tech_nor_customs", ItemType.tech, 9, None, "Progressive Nor Tech: War Customs"),
    39401: ItemData(IC.useful, 7, "Progressive tech_nor_tribal_1", ItemType.tech, 7, None, "Progressive Nor Tech: Tribal Suffering Upper"),
    39402: ItemData(IC.useful, 7, "Progressive tech_nor_tribal_2", ItemType.tech, 7, None, "Progressive Nor Tech: Tribal Suffering Lower"),
    39403: ItemData(IC.useful, 1, "Progressive tech_nor_new_world", ItemType.tech, 1, None, "Progressive Nor Tech: The New World"),
    39404: ItemData(IC.useful, 1, "Progressive tech_nor_old_world", ItemType.tech, 1, None, "Progressive Nor Tech: The Old World"),
    39405: ItemData(IC.useful, 1, "Progressive tech_nor_badlands", ItemType.tech, 1, None, "Progressive Nor Tech: Badlands & Below"),
    39406: ItemData(IC.useful, 1, "Progressive tech_nor_wastes", ItemType.tech, 1, None, "Progressive Nor Tech: Chaos Wastes"),
    39407: ItemData(IC.useful, 1, "Progressive tech_nor_beyond", ItemType.tech, 1, None, "Progressive Nor Tech: Beyond the World's Edge"),
}

special: dict[int, specialItemData] = {
    39500: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_main_kho_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Khorne (Dual Weapons)'),
    39501: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_main_kho_mon_spawn_of_khorne_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Khorne'),
    39502: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    39503: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_main_nur_mon_spawn_of_nurgle_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Nurgle'),
    39504: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    39505: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_main_sla_mon_spawn_of_slaanesh_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Slaanesh'),
    39506: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Tzeentch (Halberds)'),
    39507: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_main_tze_mon_spawn_of_tzeentch_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Tzeentch'),
    39508: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_main_kho_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Khorne (Dual Weapons)'),
    39509: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_main_kho_mon_spawn_of_khorne_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Khorne'),
    39510: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    39511: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_main_nur_mon_spawn_of_nurgle_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Nurgle'),
    39512: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    39513: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_main_sla_mon_spawn_of_slaanesh_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Slaanesh'),
    39514: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors of Tzeentch (Halberds)'),
    39515: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_main_tze_mon_spawn_of_tzeentch_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn of Tzeentch'),
    39516: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh_main_chs_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Trolls'),
    39517: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh_main_chs_inf_chaos_warriors_1', ItemType.unit, 3, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Trolls (Armoured)'),
    39518: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh_main_chs_inf_chaos_warriors_2', ItemType.unit, 3, 'Progressive nor_inf', False, False, 'Nor Unit: Stone Trolls'),
    39519: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh_main_chs_inf_chaos_warriors_2', ItemType.unit, 3, 'Progressive nor_inf', False, False, 'Nor Unit: River Trolls'),
    39520: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh_main_chs_inf_chaos_warriors_2', ItemType.unit, 3, 'Progressive nor_inf', False, False, 'Nor Unit: Bile Trolls'),
    39521: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh_main_chs_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors'),
    39522: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh_main_chs_inf_chaos_warriors_1', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors (Halberds)'),
    39523: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh_main_chs_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Warriors (Great Weapons)'),
    39524: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh_main_chs_mon_chaos_spawn', ItemType.unit, 2, 'Progressive nor_inf', False, False, 'Nor Unit: Chaos Spawn'),
    39525: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_offerings_2b', ItemType.building, 1, 'Progressive nor_offerings', False, False, 'Nor Building: Colossal Offerings'),
    39526: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_offerings_3', ItemType.building, 2, 'Progressive nor_offerings', False, False, "Nor Building: Curs'd Cavern"),
    39527: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_offerings_2b', ItemType.building, 1, 'Progressive nor_offerings', False, False, 'Nor Building: Colossal Offerings'),
    39528: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_offerings_3', ItemType.building, 2, 'Progressive nor_offerings', False, False, "Nor Building: Curs'd Cavern"),
    39529: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_offerings_2b_throgg', ItemType.building, 1, 'Progressive nor_offerings', False, False, 'Nor Building: Colossal Offerings'),
    39530: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_offerings_3_throgg', ItemType.building, 2, 'Progressive nor_offerings', False, False, "Nor Building: Curs'd Cavern"),
    39531: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_garrison_1', ItemType.building, 0, 'Progressive nor_shrine_garrison', False, False, 'Nor Building: Marauding Militia'),
    39532: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Fanged Monolith'),
    39533: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Ravenous Monolith'),
    39534: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39535: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39536: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, "Nor Building: Butcher's Plinth"),
    39537: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39538: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39539: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39540: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39541: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39542: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Gorepit'),
    39543: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Coiling Monolith'),
    39544: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Undulant Monolith'),
    39545: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39546: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39547: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Heady Brazier'),
    39548: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39549: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39550: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39551: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39552: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39553: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Ophidian Arch'),
    39554: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Blighted Monolith'),
    39555: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Pestilent Monolith'),
    39556: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39557: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39558: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Flystone'),
    39559: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39560: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39561: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39562: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39563: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39564: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Blighted Vat'),
    39565: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Many-Faced Monolith'),
    39566: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Ever-Changing Monolith'),
    39567: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39568: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39569: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Twisting Spire'),
    39570: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39571: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39572: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39573: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39574: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39575: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, "Nor Building: Scryer's Hollow"),
    39576: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_garrison_1', ItemType.building, 0, 'Progressive nor_shrine_garrison', False, False, 'Nor Building: Marauding Militia'),
    39577: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Fanged Monolith'),
    39578: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Ravenous Monolith'),
    39579: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39580: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39581: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, "Nor Building: Butcher's Plinth"),
    39582: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39583: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39584: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39585: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39586: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39587: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_kho_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Gorepit'),
    39588: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Coiling Monolith'),
    39589: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Undulant Monolith'),
    39590: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39591: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39592: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Heady Brazier'),
    39593: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39594: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39595: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39596: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39597: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39598: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_sla_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Ophidian Arch'),
    39599: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Blighted Monolith'),
    39600: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Pestilent Monolith'),
    39601: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39602: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39603: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Flystone'),
    39604: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39605: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39606: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39607: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39608: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39609: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_nur_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Blighted Vat'),
    39610: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_major_human_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Many-Faced Monolith'),
    39611: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_major_human_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Ever-Changing Monolith'),
    39612: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39613: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39614: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Twisting Spire'),
    39615: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39616: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39617: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39618: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39619: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39620: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_nor_chaos_altar_tze_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, "Nor Building: Scryer's Hollow"),
    39621: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_1', ItemType.building, 0, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Unshaped Monolith'),
    39622: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_2', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Aberrant Monolith'),
    39623: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_minor_human_port_3', ItemType.building, 1, 'Progressive nor_settlement_shrine', False, False, 'Nor Building: Pandaemonic Monolith'),
    39624: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_raiding_1', ItemType.building, 0, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Trophies of Battle'),
    39625: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_raiding_2A', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Ravager Cairn'),
    39626: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_raiding_2B', ItemType.building, 1, 'Progressive nor_shrine_raiding', False, False, 'Nor Building: Glowering Totem'),
    39627: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_recruitment_1', ItemType.building, 0, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Skull-Rise'),
    39628: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_recruitment_2A', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Mock-God'),
    39629: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_recruitment_2B', ItemType.building, 1, 'Progressive nor_shrine_recruitment', False, False, 'Nor Building: Carcass-Heap'),
    39630: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_replenishment_1', ItemType.building, 0, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Bleeding Grounds'),
    39631: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_replenishment_2A', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Warhowl Barrow'),
    39632: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_nor_chaos_altar_und_replenishment_2B', ItemType.building, 1, 'Progressive nor_shrine_replenishment', False, False, 'Nor Building: Creeping Morass'),
    39633: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_tech_nor_ship_faction_wulfrik_deep_seafang', ItemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Nor Tech: Sail the Impossible Seas'),
    39634: specialItemData(IC.useful, 1, 'wh_dlc08_nor_norsca', 'wh3_dlc27_tech_nor_ship_faction_wulfrik_seafang', ItemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Nor Tech: The Ways of the Monstrous Horde'),
    39635: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_tech_nor_ship_faction_throgg_raiding', ItemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Nor Tech: Prophetic Seer-Craft'),
    39636: specialItemData(IC.useful, 1, 'wh_dlc08_nor_wintertooth', 'wh3_dlc27_tech_nor_ship_faction_throgg_troll_loyalty', ItemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Nor Tech: Loyalty to Royalty'),
    39637: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_tech_nor_ship_faction_sayl_betrayal', ItemType.unit, 5, 'Progressive tech_nor_tribal_1', False, False, 'Nor Tech: Prophetic Seer-Craft'),
    39638: specialItemData(IC.useful, 1, 'wh3_dlc27_nor_sayl', 'wh3_dlc27_tech_nor_ship_faction_sayl_faithlessness', ItemType.unit, 5, 'Progressive tech_nor_tribal_2', False, False, 'Nor Tech: Pacts of Enmity')
}