from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    44000: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_0', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Devoted Marauders of Slaanesh'),
    44001: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_1', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Devoted Marauders of Slaanesh (Spears)'),
    44002: ItemData(IC.useful, 1, 'wh3_main_sla_inf_marauders_2', ItemType.unit, 2, 'Progressive sla_inf', 'Sla Unit: Devoted Marauders of Slaanesh (Hellscourges)'),
    44003: ItemData(IC.useful, 1, 'wh3_dlc27_tze_inf_slaangors', ItemType.unit, 2, 'Progressive sla_inf', 'Sla Unit: Slaangors'),
    44004: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_forsaken_msla', ItemType.unit, 2, 'Progressive sla_inf', 'Sla Unit: Forsaken of Slaanesh'),
    44005: ItemData(IC.useful, 1, 'wh3_dlc27_sla_inf_devotees_of_slaanesh', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Devotees of Slaanesh'),
    44006: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_msla', ItemType.unit, 2, 'Progressive sla_inf', 'Sla Unit: Chaos Warriors of Slaanesh'),
    44007: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Chaos Warriors of Slaanesh (Hellscourges)'),
    44008: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_msla', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Chosen of Slaanesh'),
    44009: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_msla_hellscourges', ItemType.unit, 4, 'Progressive sla_inf', 'Sla Unit: Chosen of Slaanesh (Hellscourges)'),
    44010: ItemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_0', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Daemonettes of Slaanesh'),
    44011: ItemData(IC.useful, 1, 'wh3_main_sla_inf_daemonette_1', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Exalted Daemonettes of Slaanesh'),
    44012: ItemData(IC.useful, 1, 'wh3_main_sla_mon_fiends_of_slaanesh_0', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Fiends of Slaanesh'),
    44013: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh', ItemType.unit, 4, 'Progressive sla_inf', 'Sla Unit: Champions of Slaanesh'),
    44014: ItemData(IC.useful, 1, 'wh3_dlc27_sla_inf_devotees_of_slaanesh_crossbows', ItemType.unit, 1, 'Progressive sla_rng', 'Def Unit: Devotees of Slaanesh (Crossbows)'),
    44015: ItemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_0', ItemType.unit, 1, 'Progressive sla_cav', 'Sla Unit: Hellstriders of Slaanesh'),
    44016: ItemData(IC.useful, 1, 'wh3_main_sla_cav_hellstriders_1', ItemType.unit, 2, 'Progressive sla_cav', 'Sla Unit: Hellstriders of Slaanesh (Hellscourges)'),
    44017: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins', ItemType.unit, 2, 'Progressive sla_cav', 'Sla Unit: Marauder Horsemen of Slaanesh'),
    44018: ItemData(IC.useful, 1, 'wh3_main_sla_cav_seekers_of_slaanesh_0', ItemType.unit, 3, 'Progressive sla_cav', 'Sla Unit: Seekers of Slaanesh'),
    44019: ItemData(IC.useful, 1, 'wh3_main_sla_cav_heartseekers_of_slaanesh_0', ItemType.unit, 3, 'Progressive sla_cav', 'Sla Unit: Heartseekers of Slaanesh'),
    44020: ItemData(IC.useful, 1, 'wh3_dlc27_sla_cav_pleasureseekers', ItemType.unit, 5, 'Progressive sla_cav', 'Sla Unit: Pleasureseekers'),
    44021: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_msla', ItemType.unit, 4, 'Progressive sla_cav', 'Sla Unit: Chaos Knights of Slaanesh'),
    44022: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_msla_lances', ItemType.unit, 4, 'Progressive sla_cav', 'Sla Unit: Chaos Knights of Slaanesh (Lances)'),
    44023: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_msla', ItemType.unit, 1, 'Progressive sla_veh', 'Sla Unit: Chaos Chariots of Slaanesh'),
    44024: ItemData(IC.useful, 1, 'wh3_main_sla_veh_seeker_chariot_0', ItemType.unit, 1, 'Progressive sla_veh', 'Sla Unit: Seeker Chariots'),
    44025: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_msla', ItemType.unit, 1, 'Progressive sla_veh', 'Sla Unit: Chaos Warshrine of Slaanesh'),
    44026: ItemData(IC.useful, 1, 'wh3_main_sla_veh_hellflayer_0', ItemType.unit, 2, 'Progressive sla_veh', 'Sla Unit: Hellflayers'),
    44027: ItemData(IC.useful, 1, 'wh3_main_sla_veh_exalted_seeker_chariot_0', ItemType.unit, 2, 'Progressive sla_veh', 'Sla Unit: Exalted Seeker Chariot'),
    44028: ItemData(IC.useful, 1, 'wh3_main_sla_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive sla_bst', 'Sla Unit: Chaos Furies (Slaanesh)'),
    44029: ItemData(IC.useful, 1, 'wh3_main_sla_mon_spawn_of_slaanesh_0', ItemType.unit, 2, 'Progressive sla_bst', 'Sla Unit: Spawn of Slaanesh'),
    44030: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton', ItemType.unit, 3, 'Progressive sla_bst', 'Sla Unit: Preyton'),
    44031: ItemData(IC.useful, 1, 'wh3_main_sla_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive sla_bst', 'Sla Unit: Soul Grinder of Slaanesh'),
    44032: ItemData(IC.useful, 1, 'wh3_main_sla_mon_keeper_of_secrets_0', ItemType.unit, 4, 'Progressive sla_bst', 'Sla Unit: Keeper of Secrets'),
    44033: ItemData(IC.useful, 1, 'wh3_main_sla_cha_cultist_0', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Cultist of Slaanesh'),
    44034: ItemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_slaanesh_0', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Alluress (Slaanesh)'),
    44035: ItemData(IC.useful, 1, 'wh3_main_sla_cha_alluress_shadow_0', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Alluress (Shadows)'),
    44036: ItemData(IC.useful, 1, 'wh3_dlc27_chs_cha_exalted_hero_msla', ItemType.unit, 1, 'Progressive sla_inf', 'Sla Unit: Exalted Hero of Slaanesh'),
    44037: ItemData(IC.useful, 1, 'wh3_dlc27_sla_cha_druchii_anointed', ItemType.unit, 1, 'Progressive sla_hro', 'Sla Unit: Druchii Anointed'),
    44038: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_shadows_msla', ItemType.unit, 1, 'Progressive sla_hro', 'Sla Unit: Chaos Sorcerer of Slaanesh (Shadows)'),
    44039: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_slaanesh_msla', ItemType.unit, 1, 'Progressive sla_hro', 'Sla Unit: Chaos Sorcerer of Slaanesh (Slaanesh)'),

    44040: ItemData(IC.useful, 1, 'wh3_twa10_sla_inf_marauders_spears_ror', ItemType.unit, 2, 'Progressive sla_inf', 'Sla Unit: The Princes of Perfection (Devoted Marauders of Slaanesh - Spears)'),
    44041: ItemData(IC.useful, 1, 'wh3_twa08_sla_mon_keeper_of_secrets_0_ror', ItemType.unit, 5, 'Progressive sla_inf', 'Sla Unit: The Marquis of Masochism (Keeper of Secrets)'),
    44042: ItemData(IC.useful, 1, 'wh3_twa07_sla_cav_heartseekers_of_slaanesh_ror_0', ItemType.unit, 4, 'war_beast', 'Sla Unit: Eternal Entourage (Heartseekers of Slaanesh)'),
    44043: ItemData(IC.useful, 1, 'wh3_twa06_sla_inf_daemonette_ror_0', ItemType.unit, 3, 'Progressive sla_inf', 'Sla Unit: Bringers of Beguilement (Exalted Daemonettes of Slaanesh)'),
    44044: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_preyton_ror', ItemType.unit, 3, 'Progressive sla_bst', 'Sla Unit: Scourge of Arden (Preyton)'),
    44045: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_marauder_horsemen_ror', ItemType.unit, 2, 'Progressive sla_cav', 'Riders of the Mighty Serpent (Marauder Horsemen)'),
    44046: ItemData(IC.useful, 1, 'wh_pro04_chs_inf_chaos_warriors_ror_0', ItemType.unit, 2, 'Progressive sla_inf', 'Mirror Guard (Chaos Warriors)'),
    44047: ItemData(IC.useful, 1, 'wh3_dlc27_sla_veh_seeker_chariot_ror', ItemType.unit, 1, 'Progressive sla_veh', 'Heralds of Excess (Seeker Chariots)'),
    44048: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_msla_ror', ItemType.unit, 1, 'Progressive sla_veh', 'The Sibilant Slaughtercade (Chaos Chariots)'),
    44049: ItemData(IC.useful, 1, 'wh3_dlc27_sla_mon_champions_of_slaanesh_ror', ItemType.unit, 4, 'Progressive sla_inf', 'Pleasure Guard (Champions of Slaanesh)'),
    #44026: ItemData(IC.useful, 1, 'wh3_main_sla_cha_exalted_keeper_of_secrets_slaanesh_0', ItemType.unit, 0, 'Progressive sla_inf', 'Sla Unit: Exalted Keeper of Secrets (Slaanesh)'),
    #44027: ItemData(IC.useful, 1, 'wh3_main_sla_cha_exalted_keeper_of_secrets_shadow_0', ItemType.unit, 0, 'Progressive sla_inf', 'Sla Unit: Exalted Keeper of Secrets (Shadows)'),
}

buildings: dict[int, ItemData] = {
    44402: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_sla', 'Sla Building: Warpstone Locus'),
    44403: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_sla', 'Sla Building: Warpstone Traps'),
    44404: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_sla_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_sla', 'Sla Building: Guarded Warpstone'),
    44405: ItemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_1', ItemType.building, 0, 'Progressive sla_allied_outpost', 'Sla Building: Slaaneshi Outpost'),
    44406: ItemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_2', ItemType.building, 1, 'Progressive sla_allied_outpost', 'Sla Building: Slaaneshi District'),
    44407: ItemData(IC.useful, 1, 'wh3_main_sla_allied_outpost_3', ItemType.building, 2, 'Progressive sla_allied_outpost', 'Sla Building: Slaaneshi Colony'),
    44408: ItemData(IC.useful, 1, 'wh3_main_sla_barracks_1', ItemType.building, 0, 'Progressive sla_barracks', 'Sla Building: Temple of Decadence'),
    44409: ItemData(IC.useful, 1, 'wh3_main_sla_cav_1', ItemType.building, 0, 'Progressive sla_cav', 'Sla Building: Addiction Pens'),
    44410: ItemData(IC.useful, 1, 'wh3_main_sla_cav_2', ItemType.building, 1, 'Progressive sla_cav', 'Sla Building: The Yearning Cages'),
    44411: ItemData(IC.useful, 1, 'wh3_main_sla_cav_4', ItemType.building, 4, 'Progressive sla_cav', 'Sla Building: Darkling Grove'),
    44412: ItemData(IC.useful, 1, 'wh3_main_sla_chariots_1', ItemType.building, 0, 'Progressive sla_chariots', 'Sla Building: Divine Circus'),
    44413: ItemData(IC.useful, 1, 'wh3_main_sla_chariots_2', ItemType.building, 1, 'Progressive sla_chariots', 'Sla Building: Rapturous Circus'),
    44414: ItemData(IC.useful, 1, 'wh3_main_sla_chariots_3', ItemType.building, 2, 'Progressive sla_chariots', 'Sla Building: Exalted Circus'),
    44415: ItemData(IC.useful, 1, 'wh3_main_sla_cult_1', ItemType.building, 0, 'Progressive sla_cult', 'Sla Building: Devotee Enticement'),
    44416: ItemData(IC.useful, 1, 'wh3_main_sla_cult_2', ItemType.building, 0, 'Progressive sla_cult', 'Sla Building: Charm Offensive'),
    44417: ItemData(IC.useful, 1, 'wh3_main_sla_cult_3', ItemType.building, 0, 'Progressive sla_cult', 'Sla Building: Lure of Slaanesh'),
    44418: ItemData(IC.useful, 1, 'wh3_main_sla_cult_4', ItemType.building, 0, 'Progressive sla_cult', 'Sla Building: Ritual of the Disciples'),
    44419: ItemData(IC.useful, 1, 'wh3_main_sla_cult_corruption_1', ItemType.building, 0, 'Progressive sla_cult_corruption', 'Sla Building: Words of Temptation'),
    44420: ItemData(IC.useful, 1, 'wh3_main_sla_cult_corruption_2', ItemType.building, 0, 'Progressive sla_cult_corruption', 'Sla Building: Population Preparation'),
    44421: ItemData(IC.useful, 1, 'wh3_main_sla_cult_magus', ItemType.building, 0, 'Progressive sla_cult_extra', 'Sla Building: Cult Magus Chambers'),
    44422: ItemData(IC.useful, 1, 'wh3_main_sla_cult_special', ItemType.building, 0, 'Progressive sla_cult_extra', 'Sla Building: Ritual of Excess'),
    44423: ItemData(IC.useful, 1, 'wh3_main_sla_cult_teleport', ItemType.building, 0, 'Progressive sla_cult_extra', 'Sla Building: Ritual of Summoning'),
    44424: ItemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_1', ItemType.building, 0, 'Progressive sla_infra_corruption', 'Sla Building: Lodge of the Succubi'),
    44425: ItemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_2', ItemType.building, 1, 'Progressive sla_infra_corruption', "Sla Building: Bewitcher's Manse"),
    44426: ItemData(IC.useful, 1, 'wh3_main_sla_infra_corruption_3', ItemType.building, 2, 'Progressive sla_infra_corruption', 'Sla Building: Palace of the High Seductress'),
    44427: ItemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_1', ItemType.building, 0, 'Progressive sla_infra_devotee', 'Sla Building: Cult of Pleasure'),
    44428: ItemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_2', ItemType.building, 1, 'Progressive sla_infra_devotee', 'Sla Building: Cult of Pain'),
    44429: ItemData(IC.useful, 1, 'wh3_main_sla_infra_devotee_3', ItemType.building, 2, 'Progressive sla_infra_devotee', 'Sla Building: Cult of Agony'),
    44430: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_1', ItemType.building, 0, 'Progressive sla_infra_growth_income', 'Sla Building: Lavish Ciborium'),
    44431: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_2', ItemType.building, 1, 'Progressive sla_infra_growth_income', 'Sla Building: Grandiose Feretory'),
    44432: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_income_3', ItemType.building, 2, 'Progressive sla_infra_growth_income', 'Sla Building: Opulent Antiquity'),
    44433: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_1', ItemType.building, 0, 'Progressive sla_infra_growth_xp', 'Sla Building: Crystalline Pool'),
    44434: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_2', ItemType.building, 1, 'Progressive sla_infra_growth_xp', 'Sla Building: Eternal Mirror'),
    44435: ItemData(IC.useful, 1, 'wh3_main_sla_infra_growth_xp_3', ItemType.building, 2, 'Progressive sla_infra_growth_xp', 'Sla Building: Pellucid Globe'),
    44436: ItemData(IC.useful, 1, 'wh3_main_sla_infra_order_1', ItemType.building, 0, 'Progressive sla_infra_order', 'Sla Building: The Dance of Dreaming'),
    44437: ItemData(IC.useful, 1, 'wh3_main_sla_infra_order_2', ItemType.building, 1, 'Progressive sla_infra_order', 'Sla Building: The Pageant of Pain '),
    44438: ItemData(IC.useful, 1, 'wh3_main_sla_infra_order_3', ItemType.building, 2, 'Progressive sla_infra_order', 'Sla Building: Opera of Dawn & Dusk'),
    44439: ItemData(IC.useful, 1, 'wh3_main_sla_infra_order_4', ItemType.building, 3, 'Progressive sla_infra_order', "Sla Building: Rhan'k'adanra, the Final Dance"),
    44440: ItemData(IC.useful, 1, 'wh3_main_sla_keeper_1', ItemType.building, 0, 'Progressive sla_keeper', 'Sla Building: Sensuous Caress'),
    44441: ItemData(IC.useful, 1, 'wh3_main_sla_keeper_2', ItemType.building, 1, 'Progressive sla_keeper', 'Sla Building: Tormented Whisper'),
    44442: ItemData(IC.useful, 1, 'wh3_main_sla_marauders_1', ItemType.building, 0, 'Progressive sla_marauders', 'Sla Building: Scented Pavilion'),
    44443: ItemData(IC.useful, 1, 'wh3_main_sla_marauders_2', ItemType.building, 1, 'Progressive sla_marauders', 'Sla Building: Fragrant Pavilion'),
    44444: ItemData(IC.useful, 1, 'wh3_main_sla_port_1', ItemType.building, 0, 'Progressive sla_port', 'Sla Building: Infernal Harbour'),
    44445: ItemData(IC.useful, 1, 'wh3_main_sla_port_2', ItemType.building, 1, 'Progressive sla_port', 'Sla Building: Hell Port'),
    44446: ItemData(IC.useful, 1, 'wh3_main_sla_port_3', ItemType.building, 2, 'Progressive sla_port', 'Sla Building: Eye of Terror'),
    44447: ItemData(IC.useful, 1, 'wh3_main_sla_resource_animals_1', ItemType.building, 0, 'Progressive sla_resource_animals', 'Sla Building: Cultist Camp (Animals)'),
    44448: ItemData(IC.useful, 1, 'wh3_main_sla_resource_animals_2', ItemType.building, 1, 'Progressive sla_resource_animals', 'Sla Building: Cultist Outpost (Animals)'),
    44449: ItemData(IC.useful, 1, 'wh3_main_sla_resource_animals_3', ItemType.building, 2, 'Progressive sla_resource_animals', 'Sla Building: Cultist Enclave (Animals)'),
    44450: ItemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_1', ItemType.building, 0, 'Progressive sla_resource_dyes', 'Sla Building: Cultist Camp (Dyes)'),
    44451: ItemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_2', ItemType.building, 1, 'Progressive sla_resource_dyes', 'Sla Building: Cultist Outpost (Dyes)'),
    44452: ItemData(IC.useful, 1, 'wh3_main_sla_resource_dyes_3', ItemType.building, 2, 'Progressive sla_resource_dyes', 'Sla Building: Cultist Enclave (Dyes)'),
    44453: ItemData(IC.useful, 1, 'wh3_main_sla_resource_furs_1', ItemType.building, 0, 'Progressive sla_resource_furs', 'Sla Building: Cultist Camp (Furs)'),
    44454: ItemData(IC.useful, 1, 'wh3_main_sla_resource_furs_2', ItemType.building, 1, 'Progressive sla_resource_furs', 'Sla Building: Cultist Outpost (Furs)'),
    44455: ItemData(IC.useful, 1, 'wh3_main_sla_resource_furs_3', ItemType.building, 2, 'Progressive sla_resource_furs', 'Sla Building: Cultist Enclave (Furs)'),
    44456: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gems_1', ItemType.building, 0, 'Progressive sla_resource_gems', 'Sla Building: Cultist Camp (Gems)'),
    44457: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gems_2', ItemType.building, 1, 'Progressive sla_resource_gems', 'Sla Building: Cultist Outpost (Gems)'),
    44458: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gems_3', ItemType.building, 2, 'Progressive sla_resource_gems', 'Sla Building: Cultist Enclave (Gems)'),
    44459: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gold_1', ItemType.building, 0, 'Progressive sla_resource_gold', 'Sla Building: Cultist Camp (Gold)'),
    44460: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gold_2', ItemType.building, 1, 'Progressive sla_resource_gold', 'Sla Building: Cultist Outpost (Gold)'),
    44461: ItemData(IC.useful, 1, 'wh3_main_sla_resource_gold_3', ItemType.building, 2, 'Progressive sla_resource_gold', 'Sla Building: Cultist Enclave (Gold)'),
    44462: ItemData(IC.useful, 1, 'wh3_main_sla_resource_iron_1', ItemType.building, 0, 'Progressive sla_resource_iron', 'Sla Building: Cultist Camp (Iron)'),
    44463: ItemData(IC.useful, 1, 'wh3_main_sla_resource_iron_2', ItemType.building, 1, 'Progressive sla_resource_iron', 'Sla Building: Cultist Outpost (Iron)'),
    44464: ItemData(IC.useful, 1, 'wh3_main_sla_resource_iron_3', ItemType.building, 2, 'Progressive sla_resource_iron', 'Sla Building: Cultist Enclave (Iron)'),
    44465: ItemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_1', ItemType.building, 0, 'Progressive sla_resource_ivory', 'Sla Building: Cultist Camp (Tusks)'),
    44466: ItemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_2', ItemType.building, 1, 'Progressive sla_resource_ivory', 'Sla Building: Cultist Outpost (Tusks)'),
    44467: ItemData(IC.useful, 1, 'wh3_main_sla_resource_ivory_3', ItemType.building, 2, 'Progressive sla_resource_ivory', 'Sla Building: Cultist Enclave (Tusks)'),
    44468: ItemData(IC.useful, 1, 'wh3_main_sla_resource_marble_1', ItemType.building, 0, 'Progressive sla_resource_marble', 'Sla Building: Cultist Camp (Marble)'),
    44469: ItemData(IC.useful, 1, 'wh3_main_sla_resource_marble_2', ItemType.building, 1, 'Progressive sla_resource_marble', 'Sla Building: Cultist Outpost (Marble)'),
    44470: ItemData(IC.useful, 1, 'wh3_main_sla_resource_marble_3', ItemType.building, 2, 'Progressive sla_resource_marble', 'Sla Building: Cultist Enclave (Marble)'),
    44471: ItemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_1', ItemType.building, 0, 'Progressive sla_resource_medicine', 'Sla Building: Cultist Camp (Medicine)'),
    44472: ItemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_2', ItemType.building, 1, 'Progressive sla_resource_medicine', 'Sla Building: Cultist Outpost (Medicine)'),
    44473: ItemData(IC.useful, 1, 'wh3_main_sla_resource_medicine_3', ItemType.building, 2, 'Progressive sla_resource_medicine', 'Sla Building: Cultist Enclave (Medicine)'),
    44474: ItemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_1', ItemType.building, 0, 'Progressive sla_resource_obsidian', 'Sla Building: Cultist Camp (Obsidian)'),
    44475: ItemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_2', ItemType.building, 1, 'Progressive sla_resource_obsidian', 'Sla Building: Cultist Outpost (Obsidian)'),
    44476: ItemData(IC.useful, 1, 'wh3_main_sla_resource_obsidian_3', ItemType.building, 2, 'Progressive sla_resource_obsidian', 'Sla Building: Cultist Enclave (Obsidian)'),
    44477: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_1', ItemType.building, 0, 'Progressive sla_resource_pasture', 'Sla Building: Cultist Camp (Pasture)'),
    44478: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_2', ItemType.building, 1, 'Progressive sla_resource_pasture', 'Sla Building: Cultist Outpost (Pasture)'),
    44479: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pasture_3', ItemType.building, 2, 'Progressive sla_resource_pasture', 'Sla Building: Cultist Enclave (Pasture)'),
    44480: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_1', ItemType.building, 0, 'Progressive sla_resource_pottery', 'Sla Building: Cultist Camp (Pottery)'),
    44481: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_2', ItemType.building, 1, 'Progressive sla_resource_pottery', 'Sla Building: Cultist Outpost (Pottery)'),
    44482: ItemData(IC.useful, 1, 'wh3_main_sla_resource_pottery_3', ItemType.building, 2, 'Progressive sla_resource_pottery', 'Sla Building: Cultist Enclave (Pottery)'),
    44483: ItemData(IC.useful, 1, 'wh3_main_sla_resource_salt_1', ItemType.building, 0, 'Progressive sla_resource_salt', 'Sla Building: Cultist Camp (Salt)'),
    44484: ItemData(IC.useful, 1, 'wh3_main_sla_resource_salt_2', ItemType.building, 1, 'Progressive sla_resource_salt', 'Sla Building: Cultist Outpost (Salt)'),
    44485: ItemData(IC.useful, 1, 'wh3_main_sla_resource_salt_3', ItemType.building, 2, 'Progressive sla_resource_salt', 'Sla Building: Cultist Enclave (Salt)'),
    44486: ItemData(IC.useful, 1, 'wh3_main_sla_resource_spices_1', ItemType.building, 0, 'Progressive sla_resource_spices', 'Sla Building: Cultist Camp (Spices)'),
    44487: ItemData(IC.useful, 1, 'wh3_main_sla_resource_spices_2', ItemType.building, 1, 'Progressive sla_resource_spices', 'Sla Building: Cultist Outpost (Spices)'),
    44488: ItemData(IC.useful, 1, 'wh3_main_sla_resource_spices_3', ItemType.building, 2, 'Progressive sla_resource_spices', 'Sla Building: Cultist Enclave (Spices)'),
    44489: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wine_1', ItemType.building, 0, 'Progressive sla_resource_wine', 'Sla Building: Cultist Camp (Wine)'),
    44490: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wine_2', ItemType.building, 1, 'Progressive sla_resource_wine', 'Sla Building: Cultist Outpost (Wine)'),
    44491: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wine_3', ItemType.building, 2, 'Progressive sla_resource_wine', 'Sla Building: Cultist Enclave (Wine)'),
    44492: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wood_1', ItemType.building, 0, 'Progressive sla_resource_wood', 'Sla Building: Cultist Camp (Wood)'),
    44493: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wood_2', ItemType.building, 1, 'Progressive sla_resource_wood', 'Sla Building: Cultist Outpost (Wood)'),
    44494: ItemData(IC.useful, 1, 'wh3_main_sla_resource_wood_3', ItemType.building, 2, 'Progressive sla_resource_wood', 'Sla Building: Cultist Enclave (Wood)'),
    44495: ItemData(IC.useful, 1, 'wh3_main_sla_seekers_1', ItemType.building, 0, 'Progressive sla_seekers', 'Sla Building: Drifting Tower'),
    44496: ItemData(IC.useful, 1, 'wh3_main_sla_seekers_2', ItemType.building, 1, 'Progressive sla_seekers', 'Sla Building: Drifting Forge'),
    44497: ItemData(IC.useful, 1, 'wh3_main_sla_seekers_3', ItemType.building, 2, 'Progressive sla_seekers', 'Sla Building: Drifting Bastion'),
    44498: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_1_a', ItemType.building, 0, 'Progressive sla_settlement_major', 'Sla Building: Soul Keep'),
    44499: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_1', ItemType.building, 0, 'Progressive sla_settlement_major', 'Sla Building: Dimensional Tear'),
    44500: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_2_a', ItemType.building, 1, 'Progressive sla_settlement_major', 'Sla Building: Dark Bastion'),
    44501: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_2', ItemType.building, 1, 'Progressive sla_settlement_major', 'Sla Building: Dimensional Breach'),
    44502: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_3_a', ItemType.building, 2, 'Progressive sla_settlement_major', 'Sla Building: Infernal Citadel'),
    44503: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_3', ItemType.building, 2, 'Progressive sla_settlement_major', 'Sla Building: Dimensional Rift'),
    44504: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_4_a', ItemType.building, 3, 'Progressive sla_settlement_major', 'Sla Building: Daemonic Fortress'),
    44505: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_4', ItemType.building, 3, 'Progressive sla_settlement_major', 'Sla Building: Dimensional Nexus'),
    44506: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_5_a', ItemType.building, 4, 'Progressive sla_settlement_major', 'Sla Building: Chaos Dreadhold'),
    44507: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_major_5', ItemType.building, 4, 'Progressive sla_settlement_major', 'Sla Building: Dimensional Cascade'),
    44508: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_1', ItemType.building, 0, 'Progressive sla_settlement_minor', 'Sla Building: {{tr:building_culture_variants_name_wh3_main_sla_settlement_major_1wh3_main_sla_slaanesh}}'),
    44509: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_2', ItemType.building, 1, 'Progressive sla_settlement_minor', 'Sla Building: {{tr:building_culture_variants_name_wh3_main_sla_settlement_major_2wh3_main_sla_slaanesh}}'),
    44510: ItemData(IC.useful, 1, 'wh3_main_sla_settlement_minor_3', ItemType.building, 2, 'Progressive sla_settlement_minor', 'Sla Building: {{tr:building_culture_variants_name_wh3_main_sla_settlement_major_3wh3_main_sla_slaanesh}}'),
    44511: ItemData(IC.useful, 1, 'wh3_main_sla_walls_major_1', ItemType.building, 0, 'Progressive sla_walls_major', 'Sla Building: Daemonic Lurkers'),
    44512: ItemData(IC.useful, 1, 'wh3_main_sla_walls_major_2', ItemType.building, 1, 'Progressive sla_walls_major', 'Sla Building: Daemonic Gathering'),
    44513: ItemData(IC.useful, 1, 'wh3_main_sla_walls_major_3', ItemType.building, 2, 'Progressive sla_walls_major', 'Sla Building: Daemonic Locus'),
    44514: ItemData(IC.useful, 1, 'wh3_main_sla_walls_minor_1', ItemType.building, 0, 'Progressive sla_walls_minor', 'Sla Building: Fog of Revelation'),
    44515: ItemData(IC.useful, 1, 'wh3_main_sla_walls_minor_2', ItemType.building, 1, 'Progressive sla_walls_minor', 'Sla Building: Soporific Mist')
}

techs: dict[int, ItemData] = {
    44800: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_6', ItemType.tech, 1, 'Progressive tech_sla_perfume', 'Sla Tech: The Promise'),
    44801: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_1', ItemType.tech, 2, 'Progressive tech_sla_perfume', 'Sla Tech: Captivating Musk'),
    44802: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_2', ItemType.tech, 2, 'Progressive tech_sla_perfume', 'Sla Tech: Blissful Coquetry'),
    44803: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_1', ItemType.tech, 2, 'Progressive tech_sla_perfume', 'Sla Tech: Everlasting Gift'),
    44804: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_6', ItemType.tech, 2, 'Progressive tech_sla_perfume', 'Sla Tech: Darkling Disciples'),
    44805: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_delicious_agony', ItemType.tech, 3, 'Progressive tech_sla_perfume', 'Sla Tech: Delicious Agony '),
    44806: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_feats_of_cruelty', ItemType.tech, 1, 'Progressive tech_sla_odour', 'Sla Tech: Triumph and Torture'),
    44807: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_scent_of_agony', ItemType.tech, 2, 'Progressive tech_sla_odour', 'Sla Tech: Scent of Agony'),
    44808: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_5', ItemType.tech, 2, 'Progressive tech_sla_odour', 'Sla Tech: Seeking Affluence'),
    44809: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_4', ItemType.tech, 2, 'Progressive tech_sla_odour', 'Sla Tech: Enriching Toil'),
    44810: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_3', ItemType.tech, 2, 'Progressive tech_sla_odour', 'Sla Tech: Wanton Destruction'),
    44811: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_passionate_torment', ItemType.tech, 3, 'Progressive tech_sla_odour', 'Sla Tech: Passionate Surrender'),
    44812: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_sinful_bravery', ItemType.tech, 1, 'Progressive tech_sla_fragrance', 'Sla Tech: Sinful Sanctity'),
    44813: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_1', ItemType.tech, 2, 'Progressive tech_sla_fragrance', 'Sla Tech: Carnal Incense'),
    44814: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_5', ItemType.tech, 2, 'Progressive tech_sla_fragrance', 'Sla Tech: Mortal Lust'),
    44815: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_4', ItemType.tech, 2, 'Progressive tech_sla_fragrance', 'Sla Tech: The Divine'),
    44816: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_3', ItemType.tech, 2, 'Progressive tech_sla_fragrance', "Sla Tech: Dark Prince's Emanation"),
    44817: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_6', ItemType.tech, 3, 'Progressive tech_sla_fragrance', 'Sla Tech: Ill-Repute'),
    44818: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_2', ItemType.tech, 1, 'Progressive tech_sla_aroma', 'Sla Tech: Intoxicating Heroism'),
    44819: ItemData(IC.useful, 1, 'wh3_main_tech_sla_3_2', ItemType.tech, 2, 'Progressive tech_sla_aroma', 'Sla Tech: Eternal Pleasures'),
    44820: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_lessons_of_immorality', ItemType.tech, 2, 'Progressive tech_sla_aroma', 'Sla Tech: Lessons of Immorality'),
    44821: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_depraved_audacity', ItemType.tech, 2, 'Progressive tech_sla_aroma', 'Sla Tech: Depraved Audacity'),
    44822: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_3', ItemType.tech, 2, 'Progressive tech_sla_aroma', 'Sla Tech: Spreading Perfection'),
    44823: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_6', ItemType.tech, 3, 'Progressive tech_sla_aroma', 'Sla Tech: Invigorating Essence'),
    44824: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_2', ItemType.tech, 1, 'Progressive tech_sla_incense', 'Sla Tech: Alluring Sisters'),
    44825: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_lethal_seduction', ItemType.tech, 2, 'Progressive tech_sla_incense', 'Sla Tech: Locus of Seduction'),
    44826: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_masterful_beguilement', ItemType.tech, 2, 'Progressive tech_sla_incense', 'Sla Tech: Master Beguilement'),
    44827: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_yearning_to_obey', ItemType.tech, 2, 'Progressive tech_sla_incense', 'Sla Tech: Yearning to Obey'),
    44828: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_1', ItemType.tech, 2, 'Progressive tech_sla_incense', 'Sla Tech: Chromatic Servitude'),
    44829: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_inquisitive_servants', ItemType.tech, 3, 'Progressive tech_sla_incense', 'Sla Tech: Inquisitive Servants'),
    44830: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_1', ItemType.tech, 1, 'Progressive tech_sla_scent', 'Sla Tech: Aberrant Promiscuity'),
    44831: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_deviant_authority', ItemType.tech, 2, 'Progressive tech_sla_scent', 'Sla Tech: Deviant Authority'),
    44832: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_5', ItemType.tech, 2, 'Progressive tech_sla_scent', 'Sla Tech: Rigorous Chastisement'),
    44833: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_4', ItemType.tech, 2, 'Progressive tech_sla_scent', 'Sla Tech: Grateful Enslavement'),
    44834: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_3', ItemType.tech, 2, 'Progressive tech_sla_scent', 'Sla Tech: Euphoric Dominance'),
    44835: ItemData(IC.useful, 1, 'wh3_main_tech_sla_1_6', ItemType.tech, 3, 'Progressive tech_sla_scent', 'Sla Tech: Rampant Consumerism'),
    44836: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_the_princes_protection', ItemType.tech, 1, 'Progressive tech_sla_disciples', "Sla Tech: The Prince's Protection"),
    44837: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_staunch_fighters', ItemType.tech, 1, 'Progressive tech_sla_disciples', 'Sla Tech: Staunch Fighters'),
    44838: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_5', ItemType.tech, 2, 'Progressive tech_sla_disciples', 'Sla Tech: Glorious Doomriders'),
    44839: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_instinctive_reactions', ItemType.tech, 2, 'Progressive tech_sla_disciples', 'Sla Tech: Frustrated Affinity'),
    44840: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_4', ItemType.tech, 2, 'Progressive tech_sla_disciples', 'Sla Tech: Decadent Apostles'),
    44841: ItemData(IC.useful, 1, 'wh3_main_tech_sla_4_5', ItemType.tech, 2, 'Progressive tech_sla_disciples', 'Sla Tech: Soul Hunters'),
    44842: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_4', ItemType.tech, 3, 'Progressive tech_sla_disciples', 'Sla Tech: Darkling Delights'),
    44843: ItemData(IC.useful, 1, 'wh3_main_tech_sla_5_3', ItemType.tech, 3, 'Progressive tech_sla_disciples', 'Sla Tech: Blessed Young'),
    44844: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_marvelous_executioners', ItemType.tech, 3, 'Progressive tech_sla_disciples', 'Sla Tech: Marvelous Executioners'),
    44845: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_riders_of_hell', ItemType.tech, 3, 'Progressive tech_sla_disciples', 'Sla Tech: Riders of Hell'),
    44846: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_fiends_of_torment', ItemType.tech, 4, 'Progressive tech_sla_disciples', 'Sla Tech: Fiends of Torment'),
    44847: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_madness_and_mutation', ItemType.tech, 4, 'Progressive tech_sla_disciples', 'Sla Tech: Madness and Mutation'),
    44848: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_eternal_agony', ItemType.tech, 4, 'Progressive tech_sla_disciples', 'Sla Tech: Eternal Agony'),
    44849: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_warp_metal_hulks', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Warpmetal Absolute'),
    44850: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_seekers_of_pain_and_pleasure', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Seekers of Pain and Pleasure'),
    44851: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_unending_depravity', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Unending Depravity'),
    44852: ItemData(IC.useful, 1, 'wh3_main_tech_sla_2_2', ItemType.tech, 5, 'Progressive tech_sla_disciples', "Sla Tech: Blood God's Disgust"),
    44853: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_blasphemous_blessings', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Blasphemous Promises'),
    44854: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_champions_of_anguish', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Champions of Anguish'),
    44855: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_immense_force', ItemType.tech, 5, 'Progressive tech_sla_disciples', 'Sla Tech: Overbearing Force'),
    44856: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_daemonic_wave', ItemType.tech, 6, 'Progressive tech_sla_disciples', 'Sla Tech: Daemonic Wave'),
    44857: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_dazzling_sturdiness', ItemType.tech, 6, 'Progressive tech_sla_disciples', 'Sla Tech: Dazzling Sturdiness'),
    44858: ItemData(IC.useful, 1, 'wh3_dlc27_tech_sla_mortal_acolytes', ItemType.tech, 6, 'Progressive tech_sla_disciples', 'Sla Tech: Mortal Obsession'),
    44859: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_6', ItemType.tech, 7, 'Progressive tech_sla_disciples', 'Sla Tech: Pained Feaster'),
    44860: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_1', ItemType.tech, 7, 'Progressive tech_sla_disciples', 'Sla Tech: Rapturous Bliss'),
    44861: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_2', ItemType.tech, 7, 'Progressive tech_sla_disciples', "Sla Tech: Slaanesh's Lash"),
    44862: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_3', ItemType.tech, 7, 'Progressive tech_sla_disciples', "Sla Tech: Phantom's Goria"),
    44863: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_4', ItemType.tech, 7, 'Progressive tech_sla_disciples', 'Sla Tech: Shards Slicing'),
    44864: ItemData(IC.useful, 1, 'wh3_main_tech_sla_6_5', ItemType.tech, 7, 'Progressive tech_sla_disciples', 'Sla Tech: Frenzied Hysteria')
}

progUnits: dict[int, ItemData] = {
    45200: ItemData(IC.useful, 3, "Progressive sla_inf", ItemType.unit, 3, "", "Progressive Sla Unit: Infantry"),
    45201: ItemData(IC.useful, 1, "Progressive sla_rng", ItemType.unit, 1, "", "Progressive Sla Unit: Ranged"),
    45202: ItemData(IC.useful, 5, "Progressive sla_cav", ItemType.unit, 5, "", "Progressive Sla Unit: Cavalry"),
    45204: ItemData(IC.useful, 2, "Progressive sla_veh", ItemType.unit, 2, "", "Progressive Sla Unit: Chariot"),
    45205: ItemData(IC.useful, 4, "Progressive sla_bst", ItemType.unit, 4, "", "Progressive Sla Unit: Beast"),
    45206: ItemData(IC.useful, 1, "Progressive sla_hro", ItemType.unit, 1, "", "Progressive Sla Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    45300: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_sla', ItemType.building, 3, None, 'Progressive Sla Building: Foreign Slot Discovery Sla'),
    45301: ItemData(IC.useful, 3, 'Progressive sla_allied_outpost', ItemType.building, 3, None, 'Progressive Sla Building: Allied Outpost'),
    45302: ItemData(IC.useful, 1, 'Progressive sla_barracks', ItemType.building, 1, None, 'Progressive Sla Building: Barracks'),
    45303: ItemData(IC.useful, 1, 'Progressive sla_cav', ItemType.building, 1, None, 'Progressive Sla Building: Cav'),
    45304: ItemData(IC.useful, 2, 'Progressive sla_cav', ItemType.building, 2, None, 'Progressive Sla Building: Cav'),
    45305: ItemData(IC.useful, 4, 'Progressive sla_cav', ItemType.building, 4, None, 'Progressive Sla Building: Cav'),
    45306: ItemData(IC.useful, 5, 'Progressive sla_cav', ItemType.building, 5, None, 'Progressive Sla Building: Cav'),
    45307: ItemData(IC.useful, 3, 'Progressive sla_chariots', ItemType.building, 3, None, 'Progressive Sla Building: Chariots'),
    45308: ItemData(IC.useful, 1, 'Progressive sla_cult', ItemType.building, 1, None, 'Progressive Sla Building: Cult'),
    45309: ItemData(IC.useful, 1, 'Progressive sla_cult_corruption', ItemType.building, 1, None, 'Progressive Sla Building: Cult Corruption'),
    45310: ItemData(IC.useful, 1, 'Progressive sla_cult', ItemType.building, 1, None, 'Progressive Sla Building: Cult Extra'),
    45311: ItemData(IC.useful, 3, 'Progressive sla_infra_corruption', ItemType.building, 3, None, 'Progressive Sla Building: Infra Corruption'),
    45312: ItemData(IC.useful, 3, 'Progressive sla_infra_devotee', ItemType.building, 3, None, 'Progressive Sla Building: Infra Devotee'),
    45313: ItemData(IC.useful, 3, 'Progressive sla_infra_growth_income', ItemType.building, 3, None, 'Progressive Sla Building: Infra Growth Income'),
    45314: ItemData(IC.useful, 3, 'Progressive sla_infra_growth_xp', ItemType.building, 3, None, 'Progressive Sla Building: Infra Growth Xp'),
    45315: ItemData(IC.useful, 4, 'Progressive sla_infra_order', ItemType.building, 4, None, 'Progressive Sla Building: Infra Order'),
    45316: ItemData(IC.useful, 2, 'Progressive sla_keeper', ItemType.building, 2, None, 'Progressive Sla Building: Keeper'),
    45317: ItemData(IC.useful, 2, 'Progressive sla_marauders', ItemType.building, 2, None, 'Progressive Sla Building: Marauders'),
    45318: ItemData(IC.useful, 3, 'Progressive sla_port', ItemType.building, 3, None, 'Progressive Sla Building: Port'),
    45319: ItemData(IC.useful, 3, 'Progressive sla_resource_animals', ItemType.building, 3, None, 'Progressive Sla Building: Animals'),
    45320: ItemData(IC.useful, 3, 'Progressive sla_resource_dyes', ItemType.building, 3, None, 'Progressive Sla Building: Dyes'),
    45321: ItemData(IC.useful, 3, 'Progressive sla_resource_furs', ItemType.building, 3, None, 'Progressive Sla Building: Furs'),
    45322: ItemData(IC.useful, 3, 'Progressive sla_resource_gems', ItemType.building, 3, None, 'Progressive Sla Building: Gems'),
    45323: ItemData(IC.useful, 3, 'Progressive sla_resource_gold', ItemType.building, 3, None, 'Progressive Sla Building: Gold'),
    45324: ItemData(IC.useful, 3, 'Progressive sla_resource_iron', ItemType.building, 3, None, 'Progressive Sla Building: Iron'),
    45325: ItemData(IC.useful, 3, 'Progressive sla_resource_ivory', ItemType.building, 3, None, 'Progressive Sla Building: Ivory'),
    45326: ItemData(IC.useful, 3, 'Progressive sla_resource_marble', ItemType.building, 3, None, 'Progressive Sla Building: Marble'),
    45327: ItemData(IC.useful, 3, 'Progressive sla_resource_medicine', ItemType.building, 3, None, 'Progressive Sla Building: Medicine'),
    45328: ItemData(IC.useful, 3, 'Progressive sla_resource_obsidian', ItemType.building, 3, None, 'Progressive Sla Building: Obsidian'),
    45329: ItemData(IC.useful, 3, 'Progressive sla_resource_pasture', ItemType.building, 3, None, 'Progressive Sla Building: Pasture'),
    45330: ItemData(IC.useful, 3, 'Progressive sla_resource_pottery', ItemType.building, 3, None, 'Progressive Sla Building: Pottery'),
    45331: ItemData(IC.useful, 3, 'Progressive sla_resource_salt', ItemType.building, 3, None, 'Progressive Sla Building: Salt'),
    45332: ItemData(IC.useful, 3, 'Progressive sla_resource_spices', ItemType.building, 3, None, 'Progressive Sla Building: Spices'),
    45333: ItemData(IC.useful, 3, 'Progressive sla_resource_wine', ItemType.building, 3, None, 'Progressive Sla Building: Wine'),
    45334: ItemData(IC.useful, 3, 'Progressive sla_resource_wood', ItemType.building, 3, None, 'Progressive Sla Building: Wood'),
    45335: ItemData(IC.useful, 3, 'Progressive sla_seekers', ItemType.building, 3, None, 'Progressive Sla Building: Seekers'),
    45336: ItemData(IC.useful, 5, 'Progressive sla_settlement_major', ItemType.building, 5, None, 'Progressive Sla Building: Settlement Major'),
    45337: ItemData(IC.useful, 3, 'Progressive sla_settlement_minor', ItemType.building, 3, None, 'Progressive Sla Building: Settlement Minor'),
    45338: ItemData(IC.useful, 3, 'Progressive sla_walls_major', ItemType.building, 3, None, 'Progressive Sla Building: Walls Major'),
    45339: ItemData(IC.useful, 2, 'Progressive sla_walls_minor', ItemType.building, 2, None, 'Progressive Sla Building: Walls Minor')
}

progTechs: dict[int, ItemData] = {
    45400: ItemData(IC.useful, 3, "Progressive tech_sla_perfume", ItemType.tech, 3, None, "Progressive Sla Tech: Perfume of the Perverse"),
    45401: ItemData(IC.useful, 3, "Progressive tech_sla_odour", ItemType.tech, 3, None, "Progressive Sla Tech: Odour of Lustful Agony"),
    45402: ItemData(IC.useful, 3, "Progressive tech_sla_fragrance", ItemType.tech, 3, None, "Progressive Sla Tech: Fragrance of the Divine"),
    45403: ItemData(IC.useful, 3, "Progressive tech_sla_aroma", ItemType.tech, 3, None, "Progressive Sla Tech: Aroma of Intoxicating Heroism"),
    45404: ItemData(IC.useful, 3, "Progressive tech_sla_incense", ItemType.tech, 3, None, "Progressive Sla Tech: Incense of Chromatic Servitude"),
    45405: ItemData(IC.useful, 3, "Progressive tech_sla_scent", ItemType.tech, 3, None, "Progressive Sla Tech: Scent of Aberrant Promiscuity"),
    45406: ItemData(IC.useful, 8, "Progressive tech_sla_disciples", ItemType.tech, 8, None, "Progressive Sla Tech: Disciples"),
}

special: dict[int, ItemData] = {

}