from BaseClasses import ItemClassification as IC
from worlds.tww3.item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    46000: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_warriors_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Skeleton Warriors'),
    46001: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Skeleton Spearmen'),
    46002: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Nehekharan Warriors'),
    46003: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_1', ItemType.unit, 3, 'Progressive tmb_inf', 'Tmb Unit: Tomb Guard (Halberds)'),
    46004: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_0', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Tomb Guard'),
    46005: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_0', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Ushabti'),
    46006: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_0', ItemType.unit, 1, 'Progressive tmb_rng', 'Tmb Unit: Skeleton Archers'),
    46007: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_1', ItemType.unit, 2, 'Progressive tmb_rng', 'Tmb Unit: Ushabti (Great Bows)'),
    46008: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_0', ItemType.unit, 1, 'cavalry', 'Tmb Unit: Skeleton Horsemen'),
    46009: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0', ItemType.unit, 1, 'cavalry', 'Tmb Unit: Skeleton Horse Archers'),
    46010: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_0', ItemType.unit, 2, 'cavalry', 'Tmb Unit: Nehekharan Horsemen'),
    46011: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_0', ItemType.unit, 3, 'Progressive tmb_cav', 'Tmb Unit: Sepulchral Stalkers'),
    46012: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_0', ItemType.unit, 3, 'cavalry', 'Tmb Unit: Necropolis Knights'),
    46013: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_1', ItemType.unit, 4, 'cavalry', 'Tmb Unit: Necropolis Knights (Halberds)'),
    46014: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_art_screaming_skull_catapult_0', ItemType.unit, 1, 'Progressive tmb_art', 'Tmb Unit: Screaming Skull Catapults'),
    46015: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_art_casket_of_souls_0', ItemType.unit, 1, 'Progressive tmb_veh', 'Tmb Unit: Casket of Souls'),
    46016: ItemData(IC.useful, 1, 'wh2_pro06_tmb_mon_bone_giant_0', ItemType.unit, 2, 'Progressive tmb_art', 'Tmb Unit: Bone Giant'),
    46017: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_chariot_0', ItemType.unit, 1, 'Progressive tmb_veh', 'Tmb Unit: Skeleton Chariots'),
    46018: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_archer_chariot_0', ItemType.unit, 2, 'Progressive tmb_veh', 'Tmb Unit: Skeleton Archer Chariots'),
    46019: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_0', ItemType.unit, 1, 'Progressive tmb_bst', 'Tmb Unit: Carrion'),
    46020: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_tomb_scorpion_0', ItemType.unit, 2, 'Progressive tmb_bst', 'Tmb Unit: Tomb Scorpion'),
    46021: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_0', ItemType.unit, 3, 'Progressive tmb_bst', 'Tmb Unit: Necrosphinx'),
    46022: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_heirotitan_0', ItemType.unit, 3, 'Progressive tmb_bst', 'Tmb Unit: Hierotitan'),
    46023: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_tomb_prince_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Tomb Prince'),
    46024: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_necrotect_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Necrotect'),
    46025: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_shadow_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Liche Priest (Shadows)'),
    46026: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_nehekhara_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Liche Priest (Nehekhara)'),
    46027: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_light_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Liche Priest (Light)'),
    46028: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_death_0', ItemType.unit, 1, 'Progressive tmb_hro', 'Tmb Unit: Liche Priest (Death)'),
    46029: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_ror', ItemType.unit, 1, 'Progressive tmb_bst', 'Tmb Unit: The Flock of Djaf (Carrion)'),
    46030: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_ror', ItemType.unit, 2, 'Progressive tmb_rng', 'Tmb Unit: Chosen of the Gods (Ushabti - Great Bows)'),
    46031: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_ror', ItemType.unit, 3, 'Progressive tmb_cav', 'Tmb Unit: Eyes of the Desert (Sepulchral Stalkers)'),
    46032: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_ror', ItemType.unit, 3, 'Progressive tmb_bst', 'Tmb Unit: The Sphinx of Usekph (Necrosphinx)'),
    46033: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_ror', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: The Khepra Guard (Tomb Guard)'),
    46034: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_ror', ItemType.unit, 1, 'Progressive tmb_inf', "Tmb Unit: King Nekhesh's Scorpion Legion (Skeleton Spearmen)"),
    46035: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_ror', ItemType.unit, 1, 'Progressive tmb_rng', 'Tmb Unit: Blessed Legion of Phakth (Skeleton Archers)'),
    46036: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_ror', ItemType.unit, 1, 'Progressive tmb_inf', "Tmb Unit: Usirian's Legion of the Netherworld (Nehekharan Warriors)"),
    46037: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_ror', ItemType.unit, 2, 'cavalry', 'Tmb Unit: Storm Riders of Khsar (Nehekharan Horsemen)'),
    46038: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_ror', ItemType.unit, 3, 'cavalry', 'Tmb Unit: Venom Knights of Asaph (Necropolis Knights)')
}

buildings: dict[int, ItemData] = {
    46400: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'Tmb Building: Khemri (Crypts)'),
    46401: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'Tmb Building: Khemri (Mastaba)'),
    46402: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'Tmb Building: Khemri (Mausoleum)'),
    46403: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'Tmb Building: Khemri (Tomb City)'),
    46404: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'Tmb Building: Khemri (Necropolis)'),
    46405: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'Tmb Building: Lahmia (Crypts)'),
    46406: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'Tmb Building: Lahmia (Mastaba)'),
    46407: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'Tmb Building: Lahmia (Mausoleum)'),
    46408: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'Tmb Building: Lahmia (Tomb City)'),
    46409: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'Tmb Building: Lahmia (Necropolis)'),
    46410: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'Tmb Building: Pyramid of Nagash (Dormant)'),
    46411: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'Tmb Building: Pyramid of Nagash (Awakened)'),
    46412: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'Tmb Building: Pyramid of Nagash (Powered)'),
    46413: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'Tmb Building: Pyramid of Nagash (Charged)'),
    46414: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'Tmb Building: Pyramid of Nagash (Exalted)'),
    46415: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_1', ItemType.building, 0, 'Progressive tmb_cavalry', 'Tmb Building: Quicksand Swamp'),
    46416: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_2', ItemType.building, 1, 'Progressive tmb_cavalry', 'Tmb Building: Ancient Battle Site'),
    46417: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_3', ItemType.building, 2, 'Progressive tmb_cavalry', 'Tmb Building: Necroserpent Nest'),
    46418: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_4', ItemType.building, 3, 'Progressive tmb_cavalry', 'Tmb Building: Royal Menagerie'),
    46419: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_1', ItemType.building, 0, 'Progressive tmb_chariots', 'Tmb Building: Bone Shaper'),
    46420: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_2', ItemType.building, 1, 'Progressive tmb_chariots', 'Tmb Building: Brass Works'),
    46421: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_3', ItemType.building, 2, 'Progressive tmb_chariots', 'Tmb Building: Skull Repository'),
    46422: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_citadel_1', ItemType.building, 0, 'Progressive tmb_citadel', 'Tmb Building: Ruined Nehekharan Citadel'),
    46423: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_1', ItemType.building, 0, 'Progressive tmb_defence_major', 'Tmb Building: Skeletal Garrison'),
    46424: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_2', ItemType.building, 1, 'Progressive tmb_defence_major', 'Tmb Building: Sandstone Walls'),
    46425: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_3', ItemType.building, 2, 'Progressive tmb_defence_major', 'Tmb Building: Engraved Walls'),
    46426: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_1', ItemType.building, 0, 'Progressive tmb_defence_minor', 'Tmb Building: Desert Lookout'),
    46427: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_2', ItemType.building, 1, 'Progressive tmb_defence_minor', 'Tmb Building: Tower of Bone'),
    46429: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_estate_1', ItemType.building, 0, 'Progressive tmb_estate', 'Tmb Building: Royal Burial Chamber'),
    46430: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_1', ItemType.building, 0, 'Progressive tmb_growth', 'Tmb Building: Mortuary House'),
    46431: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_2', ItemType.building, 1, 'Progressive tmb_growth', 'Tmb Building: Regnant Catacombs'),
    46432: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_3', ItemType.building, 2, 'Progressive tmb_growth', 'Tmb Building: Grand Ossuary'),
    46433: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_hierotitan_1', ItemType.building, 0, 'Progressive tmb_hierotitan', 'Tmb Building: Damaged Hierotitan Statue'),
    46494: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_hierotitan_2', ItemType.building, 0, 'Progressive tmb_hierotitan', 'Tmb Building: Damaged Restored Statue'),
    46434: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_1', ItemType.building, 0, 'Progressive tmb_income', 'Tmb Building: Charnel Plaza'),
    46435: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_2', ItemType.building, 1, 'Progressive tmb_income', 'Tmb Building: Funerary District'),
    46436: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_3', ItemType.building, 2, 'Progressive tmb_income', 'Tmb Building: Avenue of Monuments'),
    46437: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_1', ItemType.building, 0, 'Progressive tmb_infantry', 'Tmb Building: Open Graves'),
    46438: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_2', ItemType.building, 1, 'Progressive tmb_infantry', 'Tmb Building: Crypt Barracks'),
    46439: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_3', ItemType.building, 2, 'Progressive tmb_infantry', 'Tmb Building: Royal Barracks'),
    46440: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_necrosphinx_1', ItemType.building, 0, 'Progressive tmb_necrosphinx', 'Tmb Building: Damaged Necrosphinx Statue'),
    46495: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_necrosphinx_2', ItemType.building, 0, 'Progressive tmb_necrosphinx', 'Tmb Building: Restored Necrosphinx Statue'),
    46441: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_1', ItemType.building, 0, 'Progressive tmb_port', 'Tmb Building: Bone Wharf'),
    46442: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_2', ItemType.building, 1, 'Progressive tmb_port', 'Tmb Building: Grave Port'),
    46443: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_3', ItemType.building, 2, 'Progressive tmb_port', 'Tmb Building: Undead Fleetport'),
    46444: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_1', ItemType.building, 0, 'Progressive tmb_public_order', 'Tmb Building: Obelisk'),
    46445: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_2', ItemType.building, 1, 'Progressive tmb_public_order', 'Tmb Building: Sepulchre'),
    46446: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_3', ItemType.building, 2, 'Progressive tmb_public_order', 'Tmb Building: Mortiferous Sanctuary'),
    46447: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_animals_1', ItemType.building, 0, 'Progressive tmb_resource_animals', 'Tmb Building: Taxidermist Tomb'),
    46448: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_dyes_1', ItemType.building, 0, 'Progressive tmb_resource_dyes', 'Tmb Building: Cinnabar Mining Pit'),
    46449: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_furs_1', ItemType.building, 0, 'Progressive tmb_resource_furs', 'Tmb Building: Tannery'),
    46450: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gems_1', ItemType.building, 0, 'Progressive tmb_resource_gems', 'Tmb Building: Gemstone Mine'),
    46451: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gold_1', ItemType.building, 0, 'Progressive tmb_resource_gold', 'Tmb Building: Gold Mine'),
    46452: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_iron_1', ItemType.building, 0, 'Progressive tmb_resource_iron', 'Tmb Building: Iron Mine'),
    46453: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_marble_1', ItemType.building, 0, 'Progressive tmb_resource_marble', 'Tmb Building: Marble Quarry'),
    46454: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_medicine_1', ItemType.building, 0, 'Progressive tmb_resource_medicine', 'Tmb Building: Alchemy Workshop'),
    46455: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_obsidian_1', ItemType.building, 0, 'Progressive tmb_resource_obsidian', 'Tmb Building: Obsidian Quarry'),
    46456: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pasture_1', ItemType.building, 0, 'Progressive tmb_resource_pasture', 'Tmb Building: Parched Oasis'),
    46457: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pottery_1', ItemType.building, 0, 'Progressive tmb_resource_pottery', "Tmb Building: Potter's Hut"),
    46458: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_salt_1', ItemType.building, 0, 'Progressive tmb_resource_salt', 'Tmb Building: Salt Mine'),
    46459: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_spices_1', ItemType.building, 0, 'Progressive tmb_resource_spices', 'Tmb Building: Caravan Master'),
    46460: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wine_1', ItemType.building, 0, 'Progressive tmb_resource_wine', 'Tmb Building: Vineyard'),
    46461: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wood_1', ItemType.building, 0, 'Progressive tmb_resource_wood', 'Tmb Building: Lumber Camp'),
    46462: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_scorpions_1', ItemType.building, 0, 'Progressive tmb_scorpions', 'Tmb Building: Scorpion Nest'),
    46463: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'Tmb Building: Crypts'),
    46464: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'Tmb Building: Mastaba'),
    46465: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'Tmb Building: Mausoleum'),
    46466: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'Tmb Building: Tomb City'),
    46467: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'Tmb Building: Necropolis'),
    46468: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_1', ItemType.building, 0, 'Progressive tmb_settlement_minor', 'Tmb Building: Crypts'),
    46469: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_2', ItemType.building, 1, 'Progressive tmb_settlement_minor', 'Tmb Building: Mastaba'),
    46470: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_3', ItemType.building, 2, 'Progressive tmb_settlement_minor', 'Tmb Building: Mausoleum'),
    46471: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_1', ItemType.building, 0, 'Progressive tmb_ushabti', 'Tmb Building: Statuary of Khemri'),
    46472: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_2', ItemType.building, 1, 'Progressive tmb_ushabti', 'Tmb Building: Statue of Phakth'),
    46473: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_warsphinx_1', ItemType.building, 0, 'Progressive tmb_warsphinx', 'Tmb Building: Ruined Warsphinx Statue'),
    46493: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_warsphinx_2', ItemType.building, 1, 'Progressive tmb_warsphinx', 'Tmb Building: Restored Warsphinx Statue'),
    46474: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Catacomb Watchers'),
    46475: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Vault Guards'),
    46476: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Tomb Patrol'),
    46489: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_1', ItemType.building, 0, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian Outpost'),
    46490: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_2', ItemType.building, 1, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian District'),
    46491: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_3', ItemType.building, 2, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian Colony'),
    46492: ItemData(IC.useful, 1, 'wh3_main_tmb_resource_ivory_1', ItemType.building, 0, 'Progressive tmb_resource_ivory', 'Tmb Building: Animal Store'),
}

techs: dict[int, ItemData] = {
    46800: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_1', ItemType.tech, 1, 'Progressive tech_tmb_1', 'Tmb Tech: Wisdom of the First Dynasty'),
    46801: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_1', ItemType.tech, 2, 'Progressive tech_tmb_1', 'Tmb Tech: Proclamation of the First Dynasty'),
    46802: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Patronage of the First Dynasty'),
    46803: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_1', ItemType.tech, 2, 'Progressive tech_tmb_1', 'Tmb Tech: Runic Inscriptions'),
    46804: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_2', ItemType.tech, 2, 'Progressive tech_tmb_1', 'Tmb Tech: The Ossuary Dirge'),
    46805: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_3', ItemType.tech, 2, 'Progressive tech_tmb_1', 'Tmb Tech: First Dynasty Plans'),
    46806: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Wakhaf of the First Dynasty'),
    46868: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Unremitting Devotion'),
    46807: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Priesthood of Ptra'),
    46808: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Apprenticeship of Pehenna'),
    46809: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_1', ItemType.tech, 3, 'Progressive tech_tmb_1', 'Tmb Tech: Patronage of Wakhaf'),
    46810: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_2', ItemType.tech, 1, 'Progressive tech_tmb_2', 'Tmb Tech: Wisdom of the Second Dynasty'),
    46811: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_2', ItemType.tech, 2, 'Progressive tech_tmb_2', 'Tmb Tech: Proclamation of the Second Dynasty'),
    46812: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Patronage of the Second Dynasty'),
    46813: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_1', ItemType.tech, 1, 'Progressive tech_tmb_2', 'Tmb Tech: The Quickening'),
    46814: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_2', ItemType.tech, 1, 'Progressive tech_tmb_2', 'Tmb Tech: Nomad Stock'),
    46815: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_3', ItemType.tech, 1, 'Progressive tech_tmb_2', 'Tmb Tech: Bone Edifice'),
    46816: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Rakhash of the Second Dynasty'),
    46869: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Ageless Colossi'),
    46817: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Priesthood of Neru'),
    46818: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Apprenticeship of Beka'),
    46819: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_2', ItemType.tech, 3, 'Progressive tech_tmb_2', 'Tmb Tech: Patronage of Queen Rasut'),
    46820: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_3', ItemType.tech, 1, 'Progressive tech_tmb_3', 'Tmb Tech: Wisdom of the Third Dynasty'),
    46821: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_3', ItemType.tech, 2, 'Progressive tech_tmb_3', 'Tmb Tech: Proclamation of the Third Dynasty'),
    46822: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Patronage of the Third Dynasty'),
    46823: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_1', ItemType.tech, 1, 'Progressive tech_tmb_3', 'Tmb Tech: The Boon of Ualatp'),
    46824: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_2', ItemType.tech, 1, 'Progressive tech_tmb_3', 'Tmb Tech: The Ritual of Sokth'),
    46825: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_3', ItemType.tech, 1, 'Progressive tech_tmb_3', 'Tmb Tech: Liche Administrators'),
    46826: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Thutep of the Third Dynasty'),
    46870: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Tireless Scavenging'),
    46827: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Priesthood of Djaf'),
    46828: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Apprenticeship of Thutmosa'),
    46829: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_3', ItemType.tech, 3, 'Progressive tech_tmb_3', 'Tmb Tech: Patronage of Khetep'),
    46830: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_4', ItemType.tech, 1, 'Progressive tech_tmb_4', 'Tmb Tech: Wisdom of the Fourth Dynasty'),
    46831: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_4', ItemType.tech, 2, 'Progressive tech_tmb_4', 'Tmb Tech: Proclamation of the Fourth Dynasty'),
    46832: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Patronage of the Fourth Dynasty'),
    46833: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_1', ItemType.tech, 1, 'Progressive tech_tmb_4', 'Tmb Tech: Pride in Service'),
    46834: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_2', ItemType.tech, 1, 'Progressive tech_tmb_4', 'Tmb Tech: Dark Brotherhood'),
    46835: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_3', ItemType.tech, 1, 'Progressive tech_tmb_4', 'Tmb Tech: Stronger Binding'),
    46836: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Lahmizzash of the Fourth Dynasty'),
    46871: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Magical Loci'),
    46837: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Priesthood of Khsar'),
    46838: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Apprenticeship of Hemiunus'),
    46839: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_4', ItemType.tech, 3, 'Progressive tech_tmb_4', 'Tmb Tech: Patronage of Lahmizzash'),
    46840: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_5', ItemType.tech, 1, 'Progressive tech_tmb_5', 'Tmb Tech: Wisdom of the Fifth Dynasty'),
    46841: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_5', ItemType.tech, 2, 'Progressive tech_tmb_5', 'Tmb Tech: Proclamation of the Fifth Dynasty'),
    46842: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Patronage of the Fifth Dynasty'),
    46843: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_1', ItemType.tech, 1, 'Progressive tech_tmb_5', 'Tmb Tech: Ancient Battle Sites'),
    46844: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_2', ItemType.tech, 1, 'Progressive tech_tmb_5', "Tmb Tech: Invocation of Qu'Aph"),
    46845: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_3', ItemType.tech, 1, 'Progressive tech_tmb_5', 'Tmb Tech: Ancient Quarries'),
    46846: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Setep of the Fifth Dynasty'),
    46872: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Coiling Alacrity'),
    46847: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Priesthood of Sokth'),
    46848: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Apprenticeship of Imhetop'),
    46849: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_5', ItemType.tech, 3, 'Progressive tech_tmb_5', 'Tmb Tech: Patronage of Setep'),
    46850: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_6', ItemType.tech, 1, 'Progressive tech_tmb_6', 'Tmb Tech: Wisdom of the Sixth Dynasty'),
    46851: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_6', ItemType.tech, 2, 'Progressive tech_tmb_6', 'Tmb Tech: Proclamation of the Sixth Dynasty'),
    46852: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_patronage_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Patronage of the Sixth Dynasty'),
    46853: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_1', ItemType.tech, 1, 'Progressive tech_tmb_6', 'Tmb Tech: Clothed in the Divine'),
    46854: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_2', ItemType.tech, 1, 'Progressive tech_tmb_6', 'Tmb Tech: Underworld Gate'),
    46855: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_3', ItemType.tech, 1, 'Progressive tech_tmb_6', 'Tmb Tech: The Lost Gold of Alkharad'),
    46856: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Alkhazzar II of the Sixth Dynasty'),
    46873: ItemData(IC.useful, 1, 'wh3_main_tech_tmb_faction_child_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Hearts of Stone'),
    46857: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Priesthood of Asaph'),
    46858: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Apprenticeship of Inenna'),
    46859: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_6', ItemType.tech, 3, 'Progressive tech_tmb_6', 'Tmb Tech: Patronage of Alkhazzar'),
    46860: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_legions_of_legend', ItemType.tech, 1, 'Progressive tech_tmb_herald', 'Tmb Tech: The Heralds Empowered'),
    46861: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_1', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of Rasetra'),
    46862: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_2', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of Djaf'),
    46863: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_3', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of Mahrak'),
    46864: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_4', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of the Sphinx'),
    46865: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_5', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of Zandri'),
    46866: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_6', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of Khemri'),
    46867: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_7', ItemType.tech, 2, 'Progressive tech_tmb_herald', 'Tmb Tech: Herald of the Scorpion')
}

progUnits: dict[int, ItemData] = {
    47200: ItemData(IC.useful, 3, "Progressive tmb_inf", ItemType.unit, 3, "", "Progressive Tmb Unit: Infantry"),
    47201: ItemData(IC.useful, 2, "Progressive tmb_rng", ItemType.unit, 2, "", "Progressive Tmb Unit: Ranged"),
    47202: ItemData(IC.useful, 4, "Progressive tmb_cav", ItemType.unit, 4, "", "Progressive Tmb Unit: Cavalry"),
    47203: ItemData(IC.useful, 2, "Progressive tmb_art", ItemType.unit, 2, "", "Progressive Tmb Unit: Artillery"),
    47204: ItemData(IC.useful, 2, "Progressive tmb_veh", ItemType.unit, 2, "", "Progressive Tmb Unit: Chariot"),
    47205: ItemData(IC.useful, 3, "Progressive tmb_bst", ItemType.unit, 3, "", "Progressive Tmb Unit: Beast"),
    47206: ItemData(IC.useful, 1, "Progressive tmb_hro", ItemType.unit, 1, "", "Progressive Tmb Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    47300: ItemData(IC.useful, 4, 'Progressive tmb_cavalry', ItemType.building, 4, None, 'Progressive Tmb Building: Cavalry'),
    47301: ItemData(IC.useful, 3, 'Progressive tmb_chariots', ItemType.building, 3, None, 'Progressive Tmb Building: Chariots'),
    47302: ItemData(IC.useful, 1, 'Progressive tmb_citadel', ItemType.building, 1, None, 'Progressive Tmb Building: Citadel'),
    47303: ItemData(IC.useful, 3, 'Progressive tmb_defence_major', ItemType.building, 3, None, 'Progressive Tmb Building: Defence Major'),
    47304: ItemData(IC.useful, 2, 'Progressive tmb_defence_minor', ItemType.building, 2, None, 'Progressive Tmb Building: Defence Minor'),
    47305: ItemData(IC.useful, 1, 'Progressive tmb_estate', ItemType.building, 1, None, 'Progressive Tmb Building: Estate'),
    47306: ItemData(IC.useful, 3, 'Progressive tmb_growth', ItemType.building, 3, None, 'Progressive Tmb Building: Growth'),
    47307: ItemData(IC.useful, 1, 'Progressive tmb_hierotitan', ItemType.building, 2, None, 'Progressive Tmb Building: Hierotitan'),
    47308: ItemData(IC.useful, 3, 'Progressive tmb_income', ItemType.building, 3, None, 'Progressive Tmb Building: Income'),
    47309: ItemData(IC.useful, 3, 'Progressive tmb_infantry', ItemType.building, 3, None, 'Progressive Tmb Building: Infantry'),
    47310: ItemData(IC.useful, 1, 'Progressive tmb_necrosphinx', ItemType.building, 2, None, 'Progressive Tmb Building: Necrosphinx'),
    47311: ItemData(IC.useful, 3, 'Progressive tmb_port', ItemType.building, 3, None, 'Progressive Tmb Building: Port'),
    47312: ItemData(IC.useful, 3, 'Progressive tmb_public_order', ItemType.building, 3, None, 'Progressive Tmb Building: Public Order'),
    47313: ItemData(IC.useful, 1, 'Progressive tmb_resource_animals', ItemType.building, 1, None, 'Progressive Tmb Building: Animals'),
    47314: ItemData(IC.useful, 1, 'Progressive tmb_resource_dyes', ItemType.building, 1, None, 'Progressive Tmb Building: Dyes'),
    47315: ItemData(IC.useful, 1, 'Progressive tmb_resource_furs', ItemType.building, 1, None, 'Progressive Tmb Building: Furs'),
    47316: ItemData(IC.useful, 1, 'Progressive tmb_resource_gems', ItemType.building, 1, None, 'Progressive Tmb Building: Gems'),
    47317: ItemData(IC.useful, 1, 'Progressive tmb_resource_gold', ItemType.building, 1, None, 'Progressive Tmb Building: Gold'),
    47318: ItemData(IC.useful, 1, 'Progressive tmb_resource_iron', ItemType.building, 1, None, 'Progressive Tmb Building: Iron'),
    47319: ItemData(IC.useful, 1, 'Progressive tmb_resource_marble', ItemType.building, 1, None, 'Progressive Tmb Building: Marble'),
    47320: ItemData(IC.useful, 1, 'Progressive tmb_resource_medicine', ItemType.building, 1, None, 'Progressive Tmb Building: Medicine'),
    47321: ItemData(IC.useful, 1, 'Progressive tmb_resource_obsidian', ItemType.building, 1, None, 'Progressive Tmb Building: Obsidian'),
    47322: ItemData(IC.useful, 1, 'Progressive tmb_resource_pasture', ItemType.building, 1, None, 'Progressive Tmb Building: Pasture'),
    47323: ItemData(IC.useful, 1, 'Progressive tmb_resource_pottery', ItemType.building, 1, None, 'Progressive Tmb Building: Pottery'),
    47324: ItemData(IC.useful, 1, 'Progressive tmb_resource_salt', ItemType.building, 1, None, 'Progressive Tmb Building: Salt'),
    47325: ItemData(IC.useful, 1, 'Progressive tmb_resource_spices', ItemType.building, 1, None, 'Progressive Tmb Building: Spices'),
    47326: ItemData(IC.useful, 1, 'Progressive tmb_resource_wine', ItemType.building, 1, None, 'Progressive Tmb Building: Wine'),
    47327: ItemData(IC.useful, 1, 'Progressive tmb_resource_wood', ItemType.building, 1, None, 'Progressive Tmb Building: Wood'),
    47328: ItemData(IC.useful, 1, 'Progressive tmb_scorpions', ItemType.building, 1, None, 'Progressive Tmb Building: Scorpions'),
    47329: ItemData(IC.useful, 5, 'Progressive tmb_settlement_major', ItemType.building, 5, None, 'Progressive Tmb Building: Settlement Major'),
    47330: ItemData(IC.useful, 3, 'Progressive tmb_settlement_minor', ItemType.building, 3, None, 'Progressive Tmb Building: Settlement Minor'),
    47331: ItemData(IC.useful, 2, 'Progressive tmb_ushabti', ItemType.building, 2, None, 'Progressive Tmb Building: Ushabti'),
    47332: ItemData(IC.useful, 1, 'Progressive tmb_warsphinx', ItemType.building, 2, None, 'Progressive Tmb Building: Warsphinx'),
    47333: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Foreign Slot Discovery Tmb'),
    47334: ItemData(IC.useful, 3, 'Progressive tmb_allied_outpost', ItemType.building, 3, None, 'Progressive Tmb Building: Allied Outpost'),
    47335: ItemData(IC.useful, 1, 'Progressive tmb_resource_ivory', ItemType.building, 1, None, 'Progressive Tmb Building: Ivory')
}

progTechs: dict[int, ItemData] = {
    47400: ItemData(IC.useful, 3, "Progressive tech_tmb_1", ItemType.tech, 3, None, "Progressive Tmb Tech: First Dynasty"),
    47401: ItemData(IC.useful, 3, "Progressive tech_tmb_2", ItemType.tech, 3, None, "Progressive Tmb Tech: Second Dynasty"),
    47402: ItemData(IC.useful, 3, "Progressive tech_tmb_3", ItemType.tech, 3, None, "Progressive Tmb Tech: Third Dynasty"),
    47403: ItemData(IC.useful, 3, "Progressive tech_tmb_4", ItemType.tech, 3, None, "Progressive Tmb Tech: Fourth Dynasty"),
    47404: ItemData(IC.useful, 3, "Progressive tech_tmb_5", ItemType.tech, 3, None, "Progressive Tmb Tech: Fifth Dynasty"),
    47405: ItemData(IC.useful, 3, "Progressive tech_tmb_6", ItemType.tech, 3, None, "Progressive Tmb Tech: Sixth Dynasty"),
    47406: ItemData(IC.useful, 2, "Progressive tech_tmb_herald", ItemType.tech, 2, None, "Progressive Tmb Tech: Heralds")

}

special: dict[int, specialItemData] = {
    47500: specialItemData(IC.useful, 1, "", "wh2_dlc09_ritual_crafting_tmb_army_capacity_25", ItemType.effect_faction, None, None, True, False, "Tmb Effect: +1 Army Capacity"),
    47501: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_inf_crypt_ghouls", ItemType.unit, 1, "Progressive tmb_inf", False, False, "Tmb Unit: Crypt Ghouls"),
    47502: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_cav_hexwraiths", ItemType.unit, 3, "Progressive tmb_cav", False, False, "Tmb Unit: Hexwraiths"),
    47503: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_mon_dire_wolves", ItemType.unit, 1, "Progressive tmb_bst", False, False, "Tmb Unit: Hexwraiths"),
    47504: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_mon_fell_bats", ItemType.unit, 1, "Progressive tmb_bst", False, False, "Tmb Unit: Hexwraiths"),
    46505: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_arkhan_burial_mound", ItemType.building, 0, "Progressive tmb_creatures", False, False, "Tmb Building: Grave Hill"),
    46506: specialItemData(IC.useful, 1, "wh2_dlc09_tmb_followers_of_nagash", "wh2_dlc09_tmb_arkhan_burial_mound_2", ItemType.building, 1, "Progressive tmb_creatures", False, False, "Tmb Building: Ancient Burial Mound"),
    46507: specialItemData(IC.useful, 2, "wh2_dlc09_tmb_followers_of_nagash", "Progressive tmb_creatures", ItemType.building, 2, "Progressive tmb_creatures", False, True, "Progressive Tmb Building: Dark Creatures")
}