from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    46000: ItemData(IC.useful, 1, 'wh2_pro06_tmb_mon_bone_giant_0', ItemType.unit, 4, 'Progressive tmb_rng', 'Tmb Unit: Bone Giant'),
    46001: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_chariot_0', ItemType.unit, 2, 'Progressive tmb_veh', 'Tmb Unit: Skeleton Chariots'),
    46002: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_veh_skeleton_archer_chariot_0', ItemType.unit, 3, 'Progressive tmb_veh', 'Tmb Unit: Skeleton Archer Chariots'),
    46003: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_ror', ItemType.unit, 3, 'Progressive tmb_rng', 'Tmb Unit: Chosen of the Gods (Ushabti â€“ Great Bows)'),
    46004: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_1', ItemType.unit, 3, 'Progressive tmb_rng', 'Tmb Unit: Ushabti (Great Bows)'),
    46005: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_ushabti_0', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Ushabti'),
    46006: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_tomb_scorpion_0', ItemType.unit, 3, 'Progressive tmb_inf', 'Tmb Unit: Tomb Scorpion'),
    46007: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_ror', ItemType.unit, 3, 'Progressive tmb_rng', 'Tmb Unit: Eyes of the Desert (Sepulchral Stalkers)'),
    46008: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_sepulchral_stalkers_0', ItemType.unit, 3, 'Progressive tmb_rng', 'Tmb Unit: Sepulchral Stalkers'),
    46009: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_ror', ItemType.unit, 5, 'Progressive tmb_inf', 'Tmb Unit: The Sphinx of Usekph (Necrosphinx)'),
    46010: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_necrosphinx_0', ItemType.unit, 5, 'Progressive tmb_inf', 'Tmb Unit: Necrosphinx'),
    46011: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_heirotitan_0', ItemType.unit, 5, 'Progressive tmb_inf', 'Tmb Unit: Hierotitan'),
    46012: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_ror', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: The Flock of Djaf (Carrion)'),
    46013: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_mon_carrion_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Carrion'),
    46014: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_ror', ItemType.unit, 3, 'Progressive tmb_inf', 'Tmb Unit: The Khepra Guard (Tomb Guard)'),
    46015: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_1', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Tomb Guard (Halberds)'),
    46016: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_tomb_guard_0', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Tomb Guard'),
    46017: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_warriors_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Skeleton Warriors'),
    46018: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_ror', ItemType.unit, 2, 'Progressive tmb_inf', "Tmb Unit: King Nekhesh's Scorpion Legion (Skeleton Spearmen)"),
    46019: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_spearmen_0', ItemType.unit, 1, 'Progressive tmb_inf', 'Tmb Unit: Skeleton Spearmen'),
    46020: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_ror', ItemType.unit, 2, 'Progressive tmb_rng', 'Tmb Unit: Blessed Legion of Phakth (Skeleton Archers)'),
    46021: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_skeleton_archers_0', ItemType.unit, 1, 'Progressive tmb_rng', 'Tmb Unit: Skeleton Archers'),
    46022: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_ror', ItemType.unit, 2, 'Progressive tmb_inf', "Tmb Unit: Usirian's Legion of the Netherworld (Nehekharan Warriors)"),
    46023: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_inf_nehekhara_warriors_0', ItemType.unit, 2, 'Progressive tmb_inf', 'Tmb Unit: Nehekharan Warriors'),
    46024: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_tomb_prince_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Tomb Prince'),
    46025: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_necrotect_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Necrotect'),
    46026: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_shadow_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Liche Priest (Shadows)'),
    46027: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_nehekhara_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Liche Priest (Nehekhara)'),
    46028: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_light_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Liche Priest (Light)'),
    46029: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cha_liche_priest_death_0', ItemType.unit, 0, 'Progressive tmb_inf', 'Tmb Unit: Liche Priest (Death)'),
    46030: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0', ItemType.unit, 1, 'cavalry', 'Tmb Unit: Skeleton Horse Archers'),
    46031: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_skeleton_horsemen_0', ItemType.unit, 1, 'cavalry', 'Tmb Unit: Skeleton Horsemen'),
    46032: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_ror', ItemType.unit, 2, 'cavalry', 'Tmb Unit: Storm Riders of Khsar (Nehekharan Horsemen)'),
    46033: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_nehekhara_horsemen_0', ItemType.unit, 2, 'cavalry', 'Tmb Unit: Nehekharan Horsemen'),
    46034: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_ror', ItemType.unit, 4, 'cavalry', 'Tmb Unit: Venom Knights of Asaph (Necropolis Knights)'),
    46035: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_1', ItemType.unit, 4, 'cavalry', 'Tmb Unit: Necropolis Knights (Halberds)'),
    46036: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cav_necropolis_knights_0', ItemType.unit, 3, 'cavalry', 'Tmb Unit: Necropolis Knights'),
    46037: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_art_screaming_skull_catapult_0', ItemType.unit, 2, 'Progressive tmb_art', 'Tmb Unit: Screaming Skull Catapults'),
    46038: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_art_casket_of_souls_0', ItemType.unit, 3, 'Progressive tmb_veh', 'Tmb Unit: Casket of Souls')
}

buildings: dict[int, ItemData] = {
    46400: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_1', ItemType.building, 0, 'Progressive special_settlement_khemri_tmb', 'Tmb Building: Khemri (Crypts)'),
    46401: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_2', ItemType.building, 1, 'Progressive special_settlement_khemri_tmb', 'Tmb Building: Khemri (Mastaba)'),
    46402: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_3', ItemType.building, 2, 'Progressive special_settlement_khemri_tmb', 'Tmb Building: Khemri (Mausoleum)'),
    46403: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_4', ItemType.building, 3, 'Progressive special_settlement_khemri_tmb', 'Tmb Building: Khemri (Tomb City)'),
    46404: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_khemri_tmb_5', ItemType.building, 4, 'Progressive special_settlement_khemri_tmb', 'Tmb Building: Khemri (Necropolis)'),
    46405: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_1', ItemType.building, 0, 'Progressive special_settlement_lahmia_tmb', 'Tmb Building: Lahmia (Crypts)'),
    46406: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_2', ItemType.building, 1, 'Progressive special_settlement_lahmia_tmb', 'Tmb Building: Lahmia (Mastaba)'),
    46407: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_3', ItemType.building, 2, 'Progressive special_settlement_lahmia_tmb', 'Tmb Building: Lahmia (Mausoleum)'),
    46408: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_4', ItemType.building, 3, 'Progressive special_settlement_lahmia_tmb', 'Tmb Building: Lahmia (Tomb City)'),
    46409: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_lahmia_tmb_5', ItemType.building, 4, 'Progressive special_settlement_lahmia_tmb', 'Tmb Building: Lahmia (Necropolis)'),
    46410: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_1', ItemType.building, 0, 'Progressive special_settlement_pyramid_of_nagash_tmb', 'Tmb Building: Pyramid of Nagash (Dormant)'),
    46411: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_2', ItemType.building, 1, 'Progressive special_settlement_pyramid_of_nagash_tmb', 'Tmb Building: Pyramid of Nagash (Awakened)'),
    46412: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_3', ItemType.building, 2, 'Progressive special_settlement_pyramid_of_nagash_tmb', 'Tmb Building: Pyramid of Nagash (Powered)'),
    46413: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_4', ItemType.building, 3, 'Progressive special_settlement_pyramid_of_nagash_tmb', 'Tmb Building: Pyramid of Nagash (Charged)'),
    46414: ItemData(IC.useful, 1, 'wh2_dlc09_special_settlement_pyramid_of_nagash_tmb_5', ItemType.building, 4, 'Progressive special_settlement_pyramid_of_nagash_tmb', 'Tmb Building: Pyramid of Nagash (Exalted)'),
    46415: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_1', ItemType.building, 0, 'Progressive tmb_cavalry', 'Tmb Building: Quicksand Swamp'),
    46416: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_2', ItemType.building, 1, 'Progressive tmb_cavalry', 'Tmb Building: Ancient Battle Site'),
    46417: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_3', ItemType.building, 2, 'Progressive tmb_cavalry', 'Tmb Building: Necroserpent Nest'),
    46418: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_cavalry_4', ItemType.building, 3, 'Progressive tmb_cavalry', 'Tmb Building: Royal Menagerie'),
    46419: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_1', ItemType.building, 0, 'Progressive tmb_chariots', 'Tmb Building: Bone Shaper'),
    46420: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_2', ItemType.building, 1, 'Progressive tmb_chariots', 'Tmb Building: Brass Works'),
    46421: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_chariots_3', ItemType.building, 2, 'Progressive tmb_chariots', 'Tmb Building: Skull Repository'),
    46422: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_citadel_1', ItemType.building, 0, 'Progressive tmb_citadel', 'Tmb Building: Ruined Nehekharan Citadel'),
    46423: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_1', ItemType.building, 0, 'Progressive tmb_defence_major', 'Tmb Building: Skeletal Garrison'),
    46424: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_2', ItemType.building, 1, 'Progressive tmb_defence_major', 'Tmb Building: Sandstone Walls'),
    46425: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_major_3', ItemType.building, 2, 'Progressive tmb_defence_major', 'Tmb Building: Engraved Walls'),
    46426: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_1', ItemType.building, 0, 'Progressive tmb_defence_minor', 'Tmb Building: Desert Lookout'),
    46427: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_minor_2', ItemType.building, 1, 'Progressive tmb_defence_minor', 'Tmb Building: Tower of Bone'),
    46428: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_defence_norsca_1', ItemType.building, 0, 'Progressive tmb_defence_norsca', 'Tmb Building: Frozen Lookout'),
    46429: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_estate_1', ItemType.building, 0, 'Progressive tmb_estate', 'Tmb Building: Royal Burial Chamber'),
    46430: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_1', ItemType.building, 0, 'Progressive tmb_growth', 'Tmb Building: Mortuary House'),
    46431: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_2', ItemType.building, 1, 'Progressive tmb_growth', 'Tmb Building: Regnant Catacombs'),
    46432: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_growth_3', ItemType.building, 2, 'Progressive tmb_growth', 'Tmb Building: Grand Ossuary'),
    46433: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_hierotitan_1', ItemType.building, 0, 'Progressive tmb_hierotitan', 'Tmb Building: Damaged Hierotitan Statue'),
    46434: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_1', ItemType.building, 0, 'Progressive tmb_income', 'Tmb Building: Charnel Plaza'),
    46435: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_2', ItemType.building, 1, 'Progressive tmb_income', 'Tmb Building: Funerary District'),
    46436: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_income_3', ItemType.building, 2, 'Progressive tmb_income', 'Tmb Building: Avenue of Monuments'),
    46437: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_1', ItemType.building, 0, 'Progressive tmb_infantry', 'Tmb Building: Open Graves'),
    46438: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_2', ItemType.building, 1, 'Progressive tmb_infantry', 'Tmb Building: Crypt Barracks'),
    46439: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_infantry_3', ItemType.building, 2, 'Progressive tmb_infantry', 'Tmb Building: Royal Barracks'),
    46440: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_necrosphinx_1', ItemType.building, 0, 'Progressive tmb_necrosphinx', 'Tmb Building: Damaged Necrosphinx Statue'),
    46441: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_1', ItemType.building, 0, 'Progressive tmb_port', 'Tmb Building: Bone Wharf'),
    46442: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_2', ItemType.building, 1, 'Progressive tmb_port', 'Tmb Building: Grave Port'),
    46443: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_port_3', ItemType.building, 2, 'Progressive tmb_port', 'Tmb Building: Undead Fleetport'),
    46444: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_1', ItemType.building, 0, 'Progressive tmb_public_order', 'Tmb Building: Obelisk'),
    46445: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_2', ItemType.building, 1, 'Progressive tmb_public_order', 'Tmb Building: Sepulchre'),
    46446: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_public_order_3', ItemType.building, 2, 'Progressive tmb_public_order', 'Tmb Building: Mortiferous Sanctuary'),
    46447: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_animals_1', ItemType.building, 0, 'Progressive tmb_resource_animals', 'Tmb Building: Taxidermist Tomb'),
    46448: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_dyes_1', ItemType.building, 0, 'Progressive tmb_resource_dyes', 'Tmb Building: Cinnabar Mining Pit'),
    46449: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_furs_1', ItemType.building, 0, 'Progressive tmb_resource_furs', 'Tmb Building: Tannery'),
    46450: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gems_1', ItemType.building, 0, 'Progressive tmb_resource_gems', 'Tmb Building: Gemstone Mine'),
    46451: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_gold_1', ItemType.building, 0, 'Progressive tmb_resource_gold', 'Tmb Building: Gold Mine'),
    46452: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_iron_1', ItemType.building, 0, 'Progressive tmb_resource_iron', 'Tmb Building: Iron Mine'),
    46453: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_marble_1', ItemType.building, 0, 'Progressive tmb_resource_marble', 'Tmb Building: Marble Quarry'),
    46454: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_medicine_1', ItemType.building, 0, 'Progressive tmb_resource_medicine', 'Tmb Building: Alchemy Workshop'),
    46455: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_obsidian_1', ItemType.building, 0, 'Progressive tmb_resource_obsidian', 'Tmb Building: Obsidian Quarry'),
    46456: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pasture_1', ItemType.building, 0, 'Progressive tmb_resource_pasture', 'Tmb Building: Parched Oasis'),
    46457: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_pottery_1', ItemType.building, 0, 'Progressive tmb_resource_pottery', "Tmb Building: Potter's Hut"),
    46458: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_salt_1', ItemType.building, 0, 'Progressive tmb_resource_salt', 'Tmb Building: Salt Mine'),
    46459: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_spices_1', ItemType.building, 0, 'Progressive tmb_resource_spices', 'Tmb Building: Caravan Master'),
    46460: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wine_1', ItemType.building, 0, 'Progressive tmb_resource_wine', 'Tmb Building: Vineyard'),
    46461: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_resource_wood_1', ItemType.building, 0, 'Progressive tmb_resource_wood', 'Tmb Building: Lumber Camp'),
    46462: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_scorpions_1', ItemType.building, 0, 'Progressive tmb_scorpions', 'Tmb Building: Scorpion Nest'),
    46463: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_1', ItemType.building, 0, 'Progressive tmb_settlement_major', 'Tmb Building: Crypts'),
    46464: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_2', ItemType.building, 1, 'Progressive tmb_settlement_major', 'Tmb Building: Mastaba'),
    46465: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_3', ItemType.building, 2, 'Progressive tmb_settlement_major', 'Tmb Building: Mausoleum'),
    46466: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_4', ItemType.building, 3, 'Progressive tmb_settlement_major', 'Tmb Building: Tomb City'),
    46467: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_major_5', ItemType.building, 4, 'Progressive tmb_settlement_major', 'Tmb Building: Necropolis'),
    46468: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_1', ItemType.building, 0, 'Progressive tmb_settlement_minor', 'Tmb Building: Crypts'),
    46469: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_2', ItemType.building, 1, 'Progressive tmb_settlement_minor', 'Tmb Building: Mastaba'),
    46470: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_settlement_minor_3', ItemType.building, 2, 'Progressive tmb_settlement_minor', 'Tmb Building: Mausoleum'),
    46471: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_1', ItemType.building, 0, 'Progressive tmb_ushabti', 'Tmb Building: Statuary of Khemri'),
    46472: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_ushabti_2', ItemType.building, 1, 'Progressive tmb_ushabti', 'Tmb Building: Statue of Phakth'),
    46473: ItemData(IC.useful, 1, 'wh2_dlc09_tmb_warsphinx_1', ItemType.building, 0, 'Progressive tmb_warsphinx', 'Tmb Building: Ruined Warsphinx Statue'),
    46474: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Catacomb Watchers'),
    46475: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Vault Guards'),
    46476: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_tmb_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_tmb', 'Tmb Building: Tomb Patrol'),
    46477: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_tmb_1', ItemType.building, 0, 'Progressive special_hag_graef_mines_tmb', 'Tmb Building: Face of Hag Graef'),
    46478: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_tmb_2', ItemType.building, 1, 'Progressive special_hag_graef_mines_tmb', 'Tmb Building: Eye of Hag Graef'),
    46479: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_tmb_3', ItemType.building, 2, 'Progressive special_hag_graef_mines_tmb', 'Tmb Building: Mines of Hag Graef'),
    46480: ItemData(IC.useful, 1, 'wh2_main_special_hag_graef_mines_tmb_4', ItemType.building, 3, 'Progressive special_hag_graef_mines_tmb', 'Tmb Building: The Dark Crag'),
    46481: ItemData(IC.useful, 1, 'wh2_main_special_lothern_port_tmb_1', ItemType.building, 0, 'Progressive special_lothern_port_tmb', 'Tmb Building: Straits of Lothern'),
    46482: ItemData(IC.useful, 1, 'wh2_main_special_lothern_port_tmb_2', ItemType.building, 1, 'Progressive special_lothern_port_tmb', 'Tmb Building: Harbour of Lothern'),
    46483: ItemData(IC.useful, 1, 'wh2_main_special_lothern_port_tmb_3', ItemType.building, 2, 'Progressive special_lothern_port_tmb', 'Tmb Building: Gates of Lothern'),
    46484: ItemData(IC.useful, 1, 'wh2_main_special_quintex_tmb_1', ItemType.building, 0, 'Progressive special_quintex_tmb', 'Tmb Building: Catacombs of Quintex'),
    46485: ItemData(IC.useful, 1, 'wh2_main_special_quintex_tmb_2', ItemType.building, 1, 'Progressive special_quintex_tmb', 'Tmb Building: Vaults of Quintex'),
    46486: ItemData(IC.useful, 1, 'wh2_main_special_quintex_tmb_3', ItemType.building, 2, 'Progressive special_quintex_tmb', 'Tmb Building: Sanctum of Quintex'),
    46487: ItemData(IC.useful, 1, 'wh3_main_special_the_great_desert_tmb_1', ItemType.building, 0, 'Progressive special_the_great_desert_tmb', 'Tmb Building: Lost Tomb Excavation'),
    46488: ItemData(IC.useful, 1, 'wh3_main_special_the_great_desert_tmb_2', ItemType.building, 1, 'Progressive special_the_great_desert_tmb', 'Tmb Building: Lost Tombs'),
    46489: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_1', ItemType.building, 0, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian Outpost'),
    46490: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_2', ItemType.building, 1, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian District'),
    46491: ItemData(IC.useful, 1, 'wh3_main_tmb_allied_outpost_3', ItemType.building, 2, 'Progressive tmb_allied_outpost', 'Tmb Building: Khemian Colony'),
    46492: ItemData(IC.useful, 1, 'wh3_main_tmb_resource_ivory_1', ItemType.building, 0, 'Progressive tmb_resource_ivory', 'Tmb Building: Animal Store'),
    46493: ItemData(IC.useful, 1, 'wh_main_bretonnia_legendary_bordeleaux_tmb_1', ItemType.building, 1, 'Progressive bretonnia_legendary_bordeleaux_tmb', 'Tmb Building: Bordeleaux Port'),
    46494: ItemData(IC.useful, 1, 'wh_main_bretonnia_legendary_bordeleaux_tmb_2', ItemType.building, 2, 'Progressive bretonnia_legendary_bordeleaux_tmb', 'Tmb Building: Bordeleaux Harbour'),
    46495: ItemData(IC.useful, 1, 'wh_main_bretonnia_legendary_bordeleaux_tmb_3', ItemType.building, 3, 'Progressive bretonnia_legendary_bordeleaux_tmb', 'Tmb Building: Manannâ€™s Dry Docks'),
    46496: ItemData(IC.useful, 1, 'wh_main_special_bordeleaux_vineyards_tmb_1', ItemType.building, 0, 'Progressive special_bordeleaux_vineyards_tmb', 'Tmb Building: Morceaux Valley Orchards'),
    46497: ItemData(IC.useful, 1, 'wh_main_special_bordeleaux_vineyards_tmb_2', ItemType.building, 1, 'Progressive special_bordeleaux_vineyards_tmb', 'Tmb Building: Morceaux Valley Vineyards'),
    46498: ItemData(IC.useful, 1, 'wh_main_special_bordeleaux_vineyards_tmb_3', ItemType.building, 2, 'Progressive special_bordeleaux_vineyards_tmb', 'Tmb Building: Morceaux Valley Vintners'),
    46499: ItemData(IC.useful, 1, 'wh_main_special_bordeleaux_vineyards_tmb_4', ItemType.building, 3, 'Progressive special_bordeleaux_vineyards_tmb', 'Tmb Building: Bordeleaux Wine Market'),
    46500: ItemData(IC.useful, 1, 'wh_main_special_erengrad_port_tmb_1', ItemType.building, 0, 'Progressive special_erengrad_port_tmb', 'Tmb Building: Erengrad Docks'),
    46501: ItemData(IC.useful, 1, 'wh_main_special_erengrad_port_tmb_2', ItemType.building, 1, 'Progressive special_erengrad_port_tmb', 'Tmb Building: Erengrad Harbour'),
    46502: ItemData(IC.useful, 1, 'wh_main_special_erengrad_port_tmb_3', ItemType.building, 2, 'Progressive special_erengrad_port_tmb', 'Tmb Building: Erengrad Port'),
    46503: ItemData(IC.useful, 1, 'wh_main_special_marienburg_port_tmb_1', ItemType.building, 0, 'Progressive special_marienburg_port_tmb', 'Tmb Building: Marienburg Docks'),
    46504: ItemData(IC.useful, 1, 'wh_main_special_marienburg_port_tmb_2', ItemType.building, 1, 'Progressive special_marienburg_port_tmb', 'Tmb Building: Marienburg Harbour'),
    46505: ItemData(IC.useful, 1, 'wh_main_special_marienburg_port_tmb_3', ItemType.building, 2, 'Progressive special_marienburg_port_tmb', 'Tmb Building: Marienburg Port')
}

techs: dict[int, ItemData] = {
    46800: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Wakhaf of the First Dynasty'),
    46801: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Rakhash of the Second Dynasty'),
    46802: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Thutep of the Third Dynasty'),
    46803: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_4', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Lahmizzash of the Fourth Dynasty'),
    46804: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_5', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Setep of the Fifth Dynasty'),
    46805: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_king_6', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Alkhazzar II of the Sixth Dynasty'),
    46806: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_1', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of Rasetra'),
    46807: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Ptra'),
    46808: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_5', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Sokth'),
    46809: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Beka'),
    46810: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_4', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Hemiunus'),
    46811: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Khetep'),
    46812: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_6', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Alkhazzar'),
    46813: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_2', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of Djaf'),
    46814: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Djaf'),
    46815: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_4', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Khsar'),
    46816: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Pehenna'),
    46817: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_6', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Inenna'),
    46818: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Queen Rasut'),
    46819: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_5', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Setep'),
    46820: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_3', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of Mahrak'),
    46821: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Neru'),
    46822: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_liche_priest_6', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Priesthood of Asaph'),
    46823: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Thutmosa'),
    46824: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_necrotect_5', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Apprenticeship of Imhetop'),
    46825: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Wakhaf'),
    46826: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_tomb_prince_4', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Patronage of Lahmizzash'),
    46827: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_1', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the First Dynasty'),
    46828: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_2', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the Second Dynasty'),
    46829: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_3', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the Third Dynasty'),
    46830: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_4', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the Fourth Dynasty'),
    46831: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_5', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the Fifth Dynasty'),
    46832: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_dynasty_6', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Wisdom of the Sixth Dynasty'),
    46833: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_4', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of the Sphinx'),
    46834: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_legions_of_legend', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Heralds Empowered'),
    46835: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Runic Inscriptions'),
    46836: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Quickening'),
    46837: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Boon of Ualatp'),
    46838: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Pride in Service'),
    46839: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Ancient Battle Sites'),
    46840: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Clothed in the Divine'),
    46841: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_5', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of Zandri'),
    46842: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Ossuary Dirge'),
    46843: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Nomad Stock'),
    46844: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Ritual of Sokth'),
    46845: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Dark Brotherhood'),
    46846: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_2', ItemType.tech, 1, 'Progressive tech_tmb', "Tmb Tech: Invocation of Qu'Aph"),
    46847: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Underworld Gate'),
    46848: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_6', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of Khemri'),
    46849: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_1_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: First Dynasty Plans'),
    46850: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_2_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Bone Edifice'),
    46851: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_3_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Liche Administrators'),
    46852: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_4_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Stronger Binding'),
    46853: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_5_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Ancient Quarries'),
    46854: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_campaign_bonus_6_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: The Lost Gold of Alkharad'),
    46855: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_extra_army_7', ItemType.tech, 0, 'Progressive tech_tmb', 'Tmb Tech: Herald of the Scorpion'),
    46856: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_1', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the First Dynasty'),
    46857: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_2', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the Second Dynasty'),
    46858: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_3', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the Third Dynasty'),
    46859: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_4', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the Fourth Dynasty'),
    46860: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_5', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the Fifth Dynasty'),
    46861: ItemData(IC.useful, 1, 'wh2_dlc09_tech_tmb_faction_target_6', ItemType.tech, 1, 'Progressive tech_tmb', 'Tmb Tech: Proclamation of the Sixth Dynasty')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    47300: ItemData(IC.useful, 1, 'Progressive special_settlement_khemri_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Settlement Khemri Tmb'),
    47301: ItemData(IC.useful, 2, 'Progressive special_settlement_khemri_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Settlement Khemri Tmb'),
    47302: ItemData(IC.useful, 3, 'Progressive special_settlement_khemri_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Settlement Khemri Tmb'),
    47303: ItemData(IC.useful, 4, 'Progressive special_settlement_khemri_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Special Settlement Khemri Tmb'),
    47304: ItemData(IC.useful, 5, 'Progressive special_settlement_khemri_tmb', ItemType.building, 5, None, 'Progressive Tmb Building: Special Settlement Khemri Tmb'),
    47305: ItemData(IC.useful, 1, 'Progressive special_settlement_lahmia_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Settlement Lahmia Tmb'),
    47306: ItemData(IC.useful, 2, 'Progressive special_settlement_lahmia_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Settlement Lahmia Tmb'),
    47307: ItemData(IC.useful, 3, 'Progressive special_settlement_lahmia_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Settlement Lahmia Tmb'),
    47308: ItemData(IC.useful, 4, 'Progressive special_settlement_lahmia_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Special Settlement Lahmia Tmb'),
    47309: ItemData(IC.useful, 5, 'Progressive special_settlement_lahmia_tmb', ItemType.building, 5, None, 'Progressive Tmb Building: Special Settlement Lahmia Tmb'),
    47310: ItemData(IC.useful, 1, 'Progressive special_settlement_pyramid_of_nagash_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Settlement Pyramid Of Nagash Tmb'),
    47311: ItemData(IC.useful, 2, 'Progressive special_settlement_pyramid_of_nagash_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Settlement Pyramid Of Nagash Tmb'),
    47312: ItemData(IC.useful, 3, 'Progressive special_settlement_pyramid_of_nagash_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Settlement Pyramid Of Nagash Tmb'),
    47313: ItemData(IC.useful, 4, 'Progressive special_settlement_pyramid_of_nagash_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Special Settlement Pyramid Of Nagash Tmb'),
    47314: ItemData(IC.useful, 5, 'Progressive special_settlement_pyramid_of_nagash_tmb', ItemType.building, 5, None, 'Progressive Tmb Building: Special Settlement Pyramid Of Nagash Tmb'),
    47315: ItemData(IC.useful, 1, 'Progressive tmb_cavalry', ItemType.building, 1, None, 'Progressive Tmb Building: Cavalry'),
    47316: ItemData(IC.useful, 2, 'Progressive tmb_cavalry', ItemType.building, 2, None, 'Progressive Tmb Building: Cavalry'),
    47317: ItemData(IC.useful, 3, 'Progressive tmb_cavalry', ItemType.building, 3, None, 'Progressive Tmb Building: Cavalry'),
    47318: ItemData(IC.useful, 4, 'Progressive tmb_cavalry', ItemType.building, 4, None, 'Progressive Tmb Building: Cavalry'),
    47319: ItemData(IC.useful, 1, 'Progressive tmb_chariots', ItemType.building, 1, None, 'Progressive Tmb Building: Chariots'),
    47320: ItemData(IC.useful, 2, 'Progressive tmb_chariots', ItemType.building, 2, None, 'Progressive Tmb Building: Chariots'),
    47321: ItemData(IC.useful, 3, 'Progressive tmb_chariots', ItemType.building, 3, None, 'Progressive Tmb Building: Chariots'),
    47322: ItemData(IC.useful, 1, 'Progressive tmb_citadel', ItemType.building, 1, None, 'Progressive Tmb Building: Citadel'),
    47323: ItemData(IC.useful, 1, 'Progressive tmb_defence_major', ItemType.building, 1, None, 'Progressive Tmb Building: Defence Major'),
    47324: ItemData(IC.useful, 2, 'Progressive tmb_defence_major', ItemType.building, 2, None, 'Progressive Tmb Building: Defence Major'),
    47325: ItemData(IC.useful, 3, 'Progressive tmb_defence_major', ItemType.building, 3, None, 'Progressive Tmb Building: Defence Major'),
    47326: ItemData(IC.useful, 1, 'Progressive tmb_defence_minor', ItemType.building, 1, None, 'Progressive Tmb Building: Defence Minor'),
    47327: ItemData(IC.useful, 2, 'Progressive tmb_defence_minor', ItemType.building, 2, None, 'Progressive Tmb Building: Defence Minor'),
    47328: ItemData(IC.useful, 1, 'Progressive tmb_defence_norsca', ItemType.building, 1, None, 'Progressive Tmb Building: Defence Norsca'),
    47329: ItemData(IC.useful, 1, 'Progressive tmb_estate', ItemType.building, 1, None, 'Progressive Tmb Building: Estate'),
    47330: ItemData(IC.useful, 1, 'Progressive tmb_growth', ItemType.building, 1, None, 'Progressive Tmb Building: Growth'),
    47331: ItemData(IC.useful, 2, 'Progressive tmb_growth', ItemType.building, 2, None, 'Progressive Tmb Building: Growth'),
    47332: ItemData(IC.useful, 3, 'Progressive tmb_growth', ItemType.building, 3, None, 'Progressive Tmb Building: Growth'),
    47333: ItemData(IC.useful, 1, 'Progressive tmb_hierotitan', ItemType.building, 1, None, 'Progressive Tmb Building: Hierotitan'),
    47334: ItemData(IC.useful, 1, 'Progressive tmb_income', ItemType.building, 1, None, 'Progressive Tmb Building: Income'),
    47335: ItemData(IC.useful, 2, 'Progressive tmb_income', ItemType.building, 2, None, 'Progressive Tmb Building: Income'),
    47336: ItemData(IC.useful, 3, 'Progressive tmb_income', ItemType.building, 3, None, 'Progressive Tmb Building: Income'),
    47337: ItemData(IC.useful, 1, 'Progressive tmb_infantry', ItemType.building, 1, None, 'Progressive Tmb Building: Infantry'),
    47338: ItemData(IC.useful, 2, 'Progressive tmb_infantry', ItemType.building, 2, None, 'Progressive Tmb Building: Infantry'),
    47339: ItemData(IC.useful, 3, 'Progressive tmb_infantry', ItemType.building, 3, None, 'Progressive Tmb Building: Infantry'),
    47340: ItemData(IC.useful, 1, 'Progressive tmb_necrosphinx', ItemType.building, 1, None, 'Progressive Tmb Building: Necrosphinx'),
    47341: ItemData(IC.useful, 1, 'Progressive tmb_port', ItemType.building, 1, None, 'Progressive Tmb Building: Port'),
    47342: ItemData(IC.useful, 2, 'Progressive tmb_port', ItemType.building, 2, None, 'Progressive Tmb Building: Port'),
    47343: ItemData(IC.useful, 3, 'Progressive tmb_port', ItemType.building, 3, None, 'Progressive Tmb Building: Port'),
    47344: ItemData(IC.useful, 1, 'Progressive tmb_public_order', ItemType.building, 1, None, 'Progressive Tmb Building: Public Order'),
    47345: ItemData(IC.useful, 2, 'Progressive tmb_public_order', ItemType.building, 2, None, 'Progressive Tmb Building: Public Order'),
    47346: ItemData(IC.useful, 3, 'Progressive tmb_public_order', ItemType.building, 3, None, 'Progressive Tmb Building: Public Order'),
    47347: ItemData(IC.useful, 1, 'Progressive tmb_resource_animals', ItemType.building, 1, None, 'Progressive Tmb Building: Animals'),
    47348: ItemData(IC.useful, 1, 'Progressive tmb_resource_dyes', ItemType.building, 1, None, 'Progressive Tmb Building: Dyes'),
    47349: ItemData(IC.useful, 1, 'Progressive tmb_resource_furs', ItemType.building, 1, None, 'Progressive Tmb Building: Furs'),
    47350: ItemData(IC.useful, 1, 'Progressive tmb_resource_gems', ItemType.building, 1, None, 'Progressive Tmb Building: Gems'),
    47351: ItemData(IC.useful, 1, 'Progressive tmb_resource_gold', ItemType.building, 1, None, 'Progressive Tmb Building: Gold'),
    47352: ItemData(IC.useful, 1, 'Progressive tmb_resource_iron', ItemType.building, 1, None, 'Progressive Tmb Building: Iron'),
    47353: ItemData(IC.useful, 1, 'Progressive tmb_resource_marble', ItemType.building, 1, None, 'Progressive Tmb Building: Marble'),
    47354: ItemData(IC.useful, 1, 'Progressive tmb_resource_medicine', ItemType.building, 1, None, 'Progressive Tmb Building: Medicine'),
    47355: ItemData(IC.useful, 1, 'Progressive tmb_resource_obsidian', ItemType.building, 1, None, 'Progressive Tmb Building: Obsidian'),
    47356: ItemData(IC.useful, 1, 'Progressive tmb_resource_pasture', ItemType.building, 1, None, 'Progressive Tmb Building: Pasture'),
    47357: ItemData(IC.useful, 1, 'Progressive tmb_resource_pottery', ItemType.building, 1, None, 'Progressive Tmb Building: Pottery'),
    47358: ItemData(IC.useful, 1, 'Progressive tmb_resource_salt', ItemType.building, 1, None, 'Progressive Tmb Building: Salt'),
    47359: ItemData(IC.useful, 1, 'Progressive tmb_resource_spices', ItemType.building, 1, None, 'Progressive Tmb Building: Spices'),
    47360: ItemData(IC.useful, 1, 'Progressive tmb_resource_wine', ItemType.building, 1, None, 'Progressive Tmb Building: Wine'),
    47361: ItemData(IC.useful, 1, 'Progressive tmb_resource_wood', ItemType.building, 1, None, 'Progressive Tmb Building: Wood'),
    47362: ItemData(IC.useful, 1, 'Progressive tmb_scorpions', ItemType.building, 1, None, 'Progressive Tmb Building: Scorpions'),
    47363: ItemData(IC.useful, 1, 'Progressive tmb_settlement_major', ItemType.building, 1, None, 'Progressive Tmb Building: Settlement Major'),
    47364: ItemData(IC.useful, 2, 'Progressive tmb_settlement_major', ItemType.building, 2, None, 'Progressive Tmb Building: Settlement Major'),
    47365: ItemData(IC.useful, 3, 'Progressive tmb_settlement_major', ItemType.building, 3, None, 'Progressive Tmb Building: Settlement Major'),
    47366: ItemData(IC.useful, 4, 'Progressive tmb_settlement_major', ItemType.building, 4, None, 'Progressive Tmb Building: Settlement Major'),
    47367: ItemData(IC.useful, 5, 'Progressive tmb_settlement_major', ItemType.building, 5, None, 'Progressive Tmb Building: Settlement Major'),
    47368: ItemData(IC.useful, 1, 'Progressive tmb_settlement_minor', ItemType.building, 1, None, 'Progressive Tmb Building: Settlement Minor'),
    47369: ItemData(IC.useful, 2, 'Progressive tmb_settlement_minor', ItemType.building, 2, None, 'Progressive Tmb Building: Settlement Minor'),
    47370: ItemData(IC.useful, 3, 'Progressive tmb_settlement_minor', ItemType.building, 3, None, 'Progressive Tmb Building: Settlement Minor'),
    47371: ItemData(IC.useful, 1, 'Progressive tmb_ushabti', ItemType.building, 1, None, 'Progressive Tmb Building: Ushabti'),
    47372: ItemData(IC.useful, 2, 'Progressive tmb_ushabti', ItemType.building, 2, None, 'Progressive Tmb Building: Ushabti'),
    47373: ItemData(IC.useful, 1, 'Progressive tmb_warsphinx', ItemType.building, 1, None, 'Progressive Tmb Building: Warsphinx'),
    47374: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Foreign Slot Discovery Tmb'),
    47375: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Foreign Slot Discovery Tmb'),
    47376: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Foreign Slot Discovery Tmb'),
    47377: ItemData(IC.useful, 1, 'Progressive special_hag_graef_mines_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Hag Graef Mines Tmb'),
    47378: ItemData(IC.useful, 2, 'Progressive special_hag_graef_mines_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Hag Graef Mines Tmb'),
    47379: ItemData(IC.useful, 3, 'Progressive special_hag_graef_mines_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Hag Graef Mines Tmb'),
    47380: ItemData(IC.useful, 4, 'Progressive special_hag_graef_mines_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Special Hag Graef Mines Tmb'),
    47381: ItemData(IC.useful, 1, 'Progressive special_lothern_port_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Lothern Port Tmb'),
    47382: ItemData(IC.useful, 2, 'Progressive special_lothern_port_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Lothern Port Tmb'),
    47383: ItemData(IC.useful, 3, 'Progressive special_lothern_port_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Lothern Port Tmb'),
    47384: ItemData(IC.useful, 1, 'Progressive special_quintex_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Quintex Tmb'),
    47385: ItemData(IC.useful, 2, 'Progressive special_quintex_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Quintex Tmb'),
    47386: ItemData(IC.useful, 3, 'Progressive special_quintex_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Quintex Tmb'),
    47387: ItemData(IC.useful, 1, 'Progressive special_the_great_desert_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special The Great Desert Tmb'),
    47388: ItemData(IC.useful, 2, 'Progressive special_the_great_desert_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special The Great Desert Tmb'),
    47389: ItemData(IC.useful, 1, 'Progressive tmb_allied_outpost', ItemType.building, 1, None, 'Progressive Tmb Building: Allied Outpost'),
    47390: ItemData(IC.useful, 2, 'Progressive tmb_allied_outpost', ItemType.building, 2, None, 'Progressive Tmb Building: Allied Outpost'),
    47391: ItemData(IC.useful, 3, 'Progressive tmb_allied_outpost', ItemType.building, 3, None, 'Progressive Tmb Building: Allied Outpost'),
    47392: ItemData(IC.useful, 1, 'Progressive tmb_resource_ivory', ItemType.building, 1, None, 'Progressive Tmb Building: Ivory'),
    47393: ItemData(IC.useful, 2, 'Progressive bretonnia_legendary_bordeleaux_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Bretonnia Legendary Bordeleaux Tmb'),
    47394: ItemData(IC.useful, 3, 'Progressive bretonnia_legendary_bordeleaux_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Bretonnia Legendary Bordeleaux Tmb'),
    47395: ItemData(IC.useful, 4, 'Progressive bretonnia_legendary_bordeleaux_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Bretonnia Legendary Bordeleaux Tmb'),
    47396: ItemData(IC.useful, 1, 'Progressive special_bordeleaux_vineyards_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Bordeleaux Vineyards Tmb'),
    47397: ItemData(IC.useful, 2, 'Progressive special_bordeleaux_vineyards_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Bordeleaux Vineyards Tmb'),
    47398: ItemData(IC.useful, 3, 'Progressive special_bordeleaux_vineyards_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Bordeleaux Vineyards Tmb'),
    47399: ItemData(IC.useful, 4, 'Progressive special_bordeleaux_vineyards_tmb', ItemType.building, 4, None, 'Progressive Tmb Building: Special Bordeleaux Vineyards Tmb'),
    47400: ItemData(IC.useful, 1, 'Progressive special_erengrad_port_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Erengrad Port Tmb'),
    47401: ItemData(IC.useful, 2, 'Progressive special_erengrad_port_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Erengrad Port Tmb'),
    47402: ItemData(IC.useful, 3, 'Progressive special_erengrad_port_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Erengrad Port Tmb'),
    47403: ItemData(IC.useful, 1, 'Progressive special_marienburg_port_tmb', ItemType.building, 1, None, 'Progressive Tmb Building: Special Marienburg Port Tmb'),
    47404: ItemData(IC.useful, 2, 'Progressive special_marienburg_port_tmb', ItemType.building, 2, None, 'Progressive Tmb Building: Special Marienburg Port Tmb'),
    47405: ItemData(IC.useful, 3, 'Progressive special_marienburg_port_tmb', ItemType.building, 3, None, 'Progressive Tmb Building: Special Marienburg Port Tmb')
}

progTechs: dict[int, ItemData] = {

}

special: dict[int, ItemData] = {

}