from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    48000: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mtze', ItemType.unit, 1, 'Progressive tze_inf', 'Tze Unit: Marauders of Tzeentch'),
    48001: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mtze_spears', ItemType.unit, 1, 'Progressive tze_inf', 'Tze Unit: Marauders of Tzeentch (Spears)'),
    48002: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_tzaangors', ItemType.unit, 2, 'Progressive tze_inf', 'Tze Unit: Tzaangors'),
    48003: ItemData(IC.useful, 1, 'wh3_main_tze_inf_forsaken_0', ItemType.unit, 2, 'Progressive tze_inf', 'Tze Unit: Forsaken of Tzeentch'),
    48004: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mtze', ItemType.unit, 3, 'Progressive tze_inf', 'Tze Unit: Chaos Warriors of Tzeentch'),
    48005: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', ItemType.unit, 3, 'Progressive tze_inf', 'Tze Unit: Chaos Warriors of Tzeentch (Halberds)'),
    48006: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mtze', ItemType.unit, 4, 'Progressive tze_inf', 'Tze Unit: Chosen of Tzeentch'),
    48007: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mtze_halberds', ItemType.unit, 4, 'Progressive tze_inf', 'Tze Unit: Chosen of Tzeentch (Halberds)'),
    48008: ItemData(IC.useful, 1, 'wh3_main_tze_mon_spawn_of_tzeentch_0', ItemType.unit, 3, 'Progressive tze_inf', 'Tze Unit: Spawn of Tzeentch'),
    48009: ItemData(IC.useful, 1, 'wh3_main_tze_inf_blue_horrors_0', ItemType.unit, 1, 'Progressive tze_rng', 'Tze Unit: Blue Horrors of Tzeentch'),
    48010: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_0', ItemType.unit, 2, 'Progressive tze_rng', 'Tze Unit: Pink Horrors of Tzeentch'),
    48011: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_1', ItemType.unit, 3, 'Progressive tze_rng', 'Tze Unit: Exalted Pink Horrors of Tzeentch'),
    48012: ItemData(IC.useful, 1, 'wh3_main_tze_mon_flamers_0', ItemType.unit, 3, 'Progressive tze_rng', 'Tze Unit: Flamers of Tzeentch'),
    48013: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_flamers_changebringers', ItemType.unit, 4, 'Progressive tze_rng', 'Tze Unit: Changebringers'),
    48014: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins', ItemType.unit, 1, 'Progressive tze_cav', 'Tze Unit: Marauder Horsemen of Tzeentch'),
    48015: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_centigors_great_weapons', ItemType.unit, 2, 'Progressive tze_cav', 'Tze Unit: Centigors of Tzeentch'),
    48016: ItemData(IC.useful, 1, 'wh3_main_tze_cav_chaos_knights_0', ItemType.unit, 3, 'Progressive tze_cav', 'Tze Unit: Chaos Knights of Tzeentch'),
    48017: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mtze_lances', ItemType.unit, 3, 'Progressive tze_cav', 'Tze Unit: Chaos Knights of Tzeentch (Lances)'),
    48018: ItemData(IC.useful, 1, 'wh3_main_tze_cav_doom_knights_0', ItemType.unit, 4, 'Progressive tze_cav', 'Tze Unit: Doom Knights of Tzeentch'),
    48019: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_mtze', ItemType.unit, 1, 'Progressive tze_veh', 'Tze Unit: Chaos Chariots of Tzeentch'),
    48020: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mtze', ItemType.unit, 2, 'Progressive tze_veh', 'Tze Unit: Chaos Warshrine of Tzeentch'),
    48021: ItemData(IC.useful, 1, 'wh3_main_tze_veh_burning_chariot_0', ItemType.unit, 3, 'Progressive tze_veh', 'Tze Unit: Burning Chariot of Tzeentch'),
    48022: ItemData(IC.useful, 1, 'wh3_main_tze_inf_chaos_furies_0', ItemType.unit, 1, 'Progressive tze_bst', 'Tze Unit: Chaos Furies (Tzeentch)'),
    48023: ItemData(IC.useful, 1, 'wh3_main_tze_mon_screamers_0', ItemType.unit, 2, 'Progressive tze_bst', 'Tze Unit: Screamers of Tzeentch'),
    48024: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_cockatrice', ItemType.unit, 3, 'Progressive tze_bst', 'Tze Unit: Cockatrice'),
    48025: ItemData(IC.useful, 1, 'wh3_main_tze_mon_exalted_flamer_0', ItemType.unit, 4, 'Progressive tze_bst', 'Tze Unit: Exalted Flamer of Tzeentch'),
    48026: ItemData(IC.useful, 1, 'wh3_main_tze_mon_soul_grinder_0', ItemType.unit, 5, 'Progressive tze_bst', 'Tze Unit: Soul Grinder of Tzeentch'),
    48027: ItemData(IC.useful, 1, 'wh3_main_tze_mon_lord_of_change_0', ItemType.unit, 5, 'Progressive tze_bst', 'Tze Unit: Lord of Change'),
    48028: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_mutalith_vortex_beast', ItemType.unit, 5, 'Progressive tze_bst', 'Tze Unit: Mutalith Vortex Beast'),
    48029: ItemData(IC.useful, 1, 'wh3_main_tze_cha_cultist_0', ItemType.unit, 1, 'Progressive tze_hro', 'Tze Unit: Cultist of Tzeentch'),
    48030: ItemData(IC.useful, 1, 'wh3_main_tze_cha_iridescent_horror_tzeentch_0', ItemType.unit, 2, 'Progressive tze_hro', 'Tze Unit: Iridescent Horror (Tzeentch)'),
    48031: ItemData(IC.useful, 1, 'wh3_main_tze_cha_iridescent_horror_metal_0', ItemType.unit, 2, 'Progressive tze_hro', 'Tze Unit: Iridescent Horror (Metal)'),
    48032: ItemData(IC.useful, 1, 'wh3_dlc24_chs_cha_exalted_hero_mtze', ItemType.unit, 2, 'Progressive tze_hro', 'Tze Unit: Exalted Hero of Tzeentch'),
    48033: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_tzeentch_mtze', ItemType.unit, 2, 'Progressive tze_hro', 'Tze Unit: Chaos Sorcerer of Tzeentch (Tzeentch)'),
    48034: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_metal_mtze', ItemType.unit, 2, 'Progressive tze_hro', 'Tze Unit: Chaos Sorcerer of Tzeentch (Metal)'),
    48035: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_pink_horrors_ror', ItemType.unit, 2, 'Progressive tze_rng', 'Tze Unit: The Sourguts (Pink Horrors of Tzeentch)'),
    48036: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_aspiring_champions_mtze_ror', ItemType.unit, 4, 'Progressive tze_inf', 'Tze Unit: The Severed Claw (Aspiring Champions)'),
    48037: ItemData(IC.useful, 1, 'wh3_twa10_tze_inf_blue_horrors_ror', ItemType.unit, 1, 'Progressive tze_rng', 'Tze Unit: The Chromatic Abominations (Blue Horrors of Tzeentch)'),
    48038: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_screamers_ror', ItemType.unit, 2, 'Progressive tze_bst', 'Tze Unit: Shrieking Skyrays (Screamers of Tzeentch)'),
    48039: ItemData(IC.useful, 1, 'wh3_dlc27_nor_cav_chaos_chariot_ror', ItemType.unit, 1, 'Progressive tze_veh', 'Tze Unit: Followers of the Great Eagle (Marauder Chariots)'),
    48040: ItemData(IC.useful, 1, 'wh_pro04_chs_mon_chaos_spawn_ror_0', ItemType.unit, 3, 'Progressive tze_inf', 'Tze Unit: Wyrd Spawn (Chaos Spawn)'),
    48041: ItemData(IC.useful, 1, 'wh3_twa06_tze_inf_pink_horrors_ror_0', ItemType.unit, 3, 'Progressive tze_rng', 'Tze Unit: Blazing Squealers (Exalted Pink Horrors of Tzeentch)'),
    48042: ItemData(IC.useful, 1, 'wh3_twa07_tze_cav_doom_knights_ror_0', ItemType.unit, 4, 'Progressive tze_inf', 'Tze Unit: Knights of Immolation (Doom Knights of Tzeentch)'),
    48043: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_mutalith_vortex_beast_ror', ItemType.unit, 5, 'Progressive tze_bst', 'Tze Unit: Aeson the Fallen (Mutalith Vortex Beast)'),
    48044: ItemData(IC.useful, 1, 'wh3_twa08_tze_mon_lord_of_change_0_ror', ItemType.unit, 5, 'Progressive tze_inf', 'Tze Unit: The Golden Griffin of Theurgy (Lord of Change)')
}

buildings: dict[int, ItemData] = {
    48402: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_tze_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_tze', 'Tze Building: Warpstone Locus'),
    48403: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_tze_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_tze', 'Tze Building: Warpstone Traps'),
    48404: ItemData(IC.useful, 1, 'wh3_main_foreign_slot_discovery_tze_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_tze', 'Tze Building: Guarded Warpstone'),
    48405: ItemData(IC.useful, 1, 'wh3_main_tze_allied_outpost_1', ItemType.building, 0, 'Progressive tze_allied_outpost', 'Tze Building: Tzeentchian Outpost'),
    48406: ItemData(IC.useful, 1, 'wh3_main_tze_allied_outpost_2', ItemType.building, 1, 'Progressive tze_allied_outpost', 'Tze Building: Tzeentchian District'),
    48407: ItemData(IC.useful, 1, 'wh3_main_tze_allied_outpost_3', ItemType.building, 2, 'Progressive tze_allied_outpost', 'Tze Building: Tzeentchian Colony'),
    48408: ItemData(IC.useful, 1, 'wh3_main_tze_caster_1', ItemType.building, 0, 'Progressive tze_caster', 'Tze Building: Cult of Deceits'),
    48409: ItemData(IC.useful, 1, 'wh3_main_tze_caster_2', ItemType.building, 1, 'Progressive tze_caster', 'Tze Building: Cult of Lies'),
    48410: ItemData(IC.useful, 1, 'wh3_main_tze_caster_3', ItemType.building, 2, 'Progressive tze_caster', 'Tze Building: Cult of Change'),
    48411: ItemData(IC.useful, 1, 'wh3_main_tze_corruption_1', ItemType.building, 0, 'Progressive tze_corruption', 'Tze Building: Stygian Well'),
    48412: ItemData(IC.useful, 1, 'wh3_main_tze_corruption_2', ItemType.building, 1, 'Progressive tze_corruption', 'Tze Building: Crystalline Arch'),
    48413: ItemData(IC.useful, 1, 'wh3_main_tze_corruption_3', ItemType.building, 2, 'Progressive tze_corruption', 'Tze Building: Warplinth'),
    48414: ItemData(IC.useful, 1, 'wh3_main_tze_cult_1', ItemType.building, 0, 'Progressive tze_cult', 'Tze Building: Complex Stratagems'),
    48415: ItemData(IC.useful, 1, 'wh3_main_tze_cult_2', ItemType.building, 0, 'Progressive tze_cult', 'Tze Building: Branching Plans'),
    48416: ItemData(IC.useful, 1, 'wh3_main_tze_cult_3', ItemType.building, 0, 'Progressive tze_cult', 'Tze Building: Intricate Preparations'),
    48417: ItemData(IC.useful, 1, 'wh3_main_tze_cult_4', ItemType.building, 0, 'Progressive tze_cult', 'Tze Building: Ritual of the Winds'),
    48418: ItemData(IC.useful, 1, 'wh3_main_tze_cult_corruption_1', ItemType.building, 0, 'Progressive tze_cult_corruption', 'Tze Building: Tzeentchian Trickery'),
    48419: ItemData(IC.useful, 1, 'wh3_main_tze_cult_corruption_2', ItemType.building, 0, 'Progressive tze_cult_corruption', "Tze Building: Tzeentch's Mastery"),
    48420: ItemData(IC.useful, 1, 'wh3_main_tze_cult_magus', ItemType.building, 0, 'Progressive tze_cult_extra', 'Tze Building: Cult Magus Chambers'),
    48421: ItemData(IC.useful, 1, 'wh3_main_tze_cult_special', ItemType.building, 0, 'Progressive tze_cult_extra', 'Tze Building: Ritual of Cults'),
    48422: ItemData(IC.useful, 1, 'wh3_main_tze_cult_teleport', ItemType.building, 0, 'Progressive tze_cult_extra', 'Tze Building: Ritual of Summoning'),
    48423: ItemData(IC.useful, 1, 'wh3_main_tze_flamer_0', ItemType.building, 0, 'Progressive tze_flamer', 'Tze Building: The Spark'),
    48424: ItemData(IC.useful, 1, 'wh3_main_tze_flamer_1', ItemType.building, 1, 'Progressive tze_flamer', 'Tze Building: Blue Bonfire'),
    48425: ItemData(IC.useful, 1, 'wh3_main_tze_flamer_2', ItemType.building, 2, 'Progressive tze_flamer', 'Tze Building: Pink Blaze'),
    48426: ItemData(IC.useful, 1, 'wh3_main_tze_flamer_3', ItemType.building, 3, 'Progressive tze_flamer', 'Tze Building: Iridescent Conflagration'),
    48427: ItemData(IC.useful, 1, 'wh3_main_tze_growth_corruption_1', ItemType.building, 0, 'Progressive tze_growth_corruption', 'Tze Building: Thaumaturgic Lode'),
    48428: ItemData(IC.useful, 1, 'wh3_main_tze_growth_corruption_2', ItemType.building, 1, 'Progressive tze_growth_corruption', 'Tze Building: Thaumaturgic Fissure'),
    48429: ItemData(IC.useful, 1, 'wh3_main_tze_growth_corruption_3', ItemType.building, 2, 'Progressive tze_growth_corruption', 'Tze Building: Thaumaturgic Reef'),
    48430: ItemData(IC.useful, 1, 'wh3_main_tze_growth_gold_1', ItemType.building, 0, 'Progressive tze_growth_gold', 'Tze Building: Web of Secrets'),
    48431: ItemData(IC.useful, 1, 'wh3_main_tze_growth_gold_2', ItemType.building, 1, 'Progressive tze_growth_gold', 'Tze Building: Lattice of Distortion'),
    48432: ItemData(IC.useful, 1, 'wh3_main_tze_growth_gold_3', ItemType.building, 2, 'Progressive tze_growth_gold', 'Tze Building: Weave of Time'),
    48433: ItemData(IC.useful, 1, 'wh3_main_tze_horror_barracks_1', ItemType.building, 0, 'Progressive tze_horror_barracks', 'Tze Building: Slither of Potential'),
    48434: ItemData(IC.useful, 1, 'wh3_main_tze_horror_barracks_2', ItemType.building, 1, 'Progressive tze_horror_barracks', 'Tze Building: Flicker of Potential'),
    48435: ItemData(IC.useful, 1, 'wh3_main_tze_horror_barracks_3', ItemType.building, 2, 'Progressive tze_horror_barracks', 'Tze Building: Moment of Potential'),
    48436: ItemData(IC.useful, 1, 'wh3_main_tze_library_1', ItemType.building, 0, 'Progressive tze_library', 'Tze Building: Hidden Library'),
    48437: ItemData(IC.useful, 1, 'wh3_main_tze_library_2', ItemType.building, 1, 'Progressive tze_library', 'Tze Building: Forgotten Scriptorium'),
    48438: ItemData(IC.useful, 1, 'wh3_main_tze_library_3', ItemType.building, 2, 'Progressive tze_library', 'Tze Building: Lost Athenaeum'),
    48439: ItemData(IC.useful, 1, 'wh3_main_tze_monster_barracks_1', ItemType.building, 0, 'Progressive tze_monster_barracks', 'Tze Building: Many-Eyed Tribute'),
    48440: ItemData(IC.useful, 1, 'wh3_main_tze_monster_barracks_2', ItemType.building, 1, 'Progressive tze_monster_barracks', "Tze Building: Puzzle-Maker's Hovel"),
    48441: ItemData(IC.useful, 1, 'wh3_main_tze_monster_barracks_3', ItemType.building, 2, 'Progressive tze_monster_barracks', 'Tze Building: Chapterhouse of Knowledge'),
    48442: ItemData(IC.useful, 1, 'wh3_main_tze_monster_barracks_4', ItemType.building, 3, 'Progressive tze_monster_barracks', "Tze Building: Doom's Hold"),
    48443: ItemData(IC.useful, 1, 'wh3_main_tze_mounted_1', ItemType.building, 0, 'Progressive tze_mounted', 'Tze Building: Transmogrification Locus'),
    48444: ItemData(IC.useful, 1, 'wh3_main_tze_mounted_2', ItemType.building, 1, 'Progressive tze_mounted', 'Tze Building: Inchoate Armoury'),
    48445: ItemData(IC.useful, 1, 'wh3_main_tze_mounted_3', ItemType.building, 2, 'Progressive tze_mounted', 'Tze Building: Inchoate Forge'),
    48446: ItemData(IC.useful, 1, 'wh3_main_tze_order_los_1', ItemType.building, 0, 'Progressive tze_order_los', 'Tze Building: A Convolution'),
    48447: ItemData(IC.useful, 1, 'wh3_main_tze_order_los_2', ItemType.building, 1, 'Progressive tze_order_los', 'Tze Building: Unending Maze'),
    48448: ItemData(IC.useful, 1, 'wh3_main_tze_order_los_3', ItemType.building, 2, 'Progressive tze_order_los', 'Tze Building: Silver Labyrinth'),
    48449: ItemData(IC.useful, 1, 'wh3_main_tze_port_1', ItemType.building, 0, 'Progressive tze_port', 'Tze Building: Infernal Harbour'),
    48450: ItemData(IC.useful, 1, 'wh3_main_tze_port_2', ItemType.building, 1, 'Progressive tze_port', 'Tze Building: Hell Port'),
    48451: ItemData(IC.useful, 1, 'wh3_main_tze_port_3', ItemType.building, 2, 'Progressive tze_port', 'Tze Building: Eye of Terror'),
    48452: ItemData(IC.useful, 1, 'wh3_main_tze_resource_animals_1', ItemType.building, 0, 'Progressive tze_resource_animals', 'Tze Building: Cultist Camp (Animals)'),
    48453: ItemData(IC.useful, 1, 'wh3_main_tze_resource_animals_2', ItemType.building, 1, 'Progressive tze_resource_animals', 'Tze Building: Cultist Outpost (Animals)'),
    48454: ItemData(IC.useful, 1, 'wh3_main_tze_resource_animals_3', ItemType.building, 2, 'Progressive tze_resource_animals', 'Tze Building: Cultist Enclave (Animals)'),
    48455: ItemData(IC.useful, 1, 'wh3_main_tze_resource_dyes_1', ItemType.building, 0, 'Progressive tze_resource_dyes', 'Tze Building: Cultist Camp (Dyes)'),
    48456: ItemData(IC.useful, 1, 'wh3_main_tze_resource_dyes_2', ItemType.building, 1, 'Progressive tze_resource_dyes', 'Tze Building: Cultist Outpost (Dyes)'),
    48457: ItemData(IC.useful, 1, 'wh3_main_tze_resource_dyes_3', ItemType.building, 2, 'Progressive tze_resource_dyes', 'Tze Building: Cultist Enclave (Dyes)'),
    48458: ItemData(IC.useful, 1, 'wh3_main_tze_resource_furs_1', ItemType.building, 0, 'Progressive tze_resource_furs', 'Tze Building: Cultist Camp (Furs)'),
    48459: ItemData(IC.useful, 1, 'wh3_main_tze_resource_furs_2', ItemType.building, 1, 'Progressive tze_resource_furs', 'Tze Building: Cultist Outpost (Furs)'),
    48460: ItemData(IC.useful, 1, 'wh3_main_tze_resource_furs_3', ItemType.building, 2, 'Progressive tze_resource_furs', 'Tze Building: Cultist Enclave (Furs)'),
    48461: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gems_1', ItemType.building, 0, 'Progressive tze_resource_gems', 'Tze Building: Cultist Camp (Gems)'),
    48462: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gems_2', ItemType.building, 1, 'Progressive tze_resource_gems', 'Tze Building: Cultist Outpost (Gems)'),
    48463: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gems_3', ItemType.building, 2, 'Progressive tze_resource_gems', 'Tze Building: Cultist Enclave (Gems)'),
    48464: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gold_1', ItemType.building, 0, 'Progressive tze_resource_gold', 'Tze Building: Cultist Camp (Gold)'),
    48465: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gold_2', ItemType.building, 1, 'Progressive tze_resource_gold', 'Tze Building: Cultist Outpost (Gold)'),
    48466: ItemData(IC.useful, 1, 'wh3_main_tze_resource_gold_3', ItemType.building, 2, 'Progressive tze_resource_gold', 'Tze Building: Cultist Enclave (Gold)'),
    48467: ItemData(IC.useful, 1, 'wh3_main_tze_resource_iron_1', ItemType.building, 0, 'Progressive tze_resource_iron', 'Tze Building: Cultist Camp (Iron)'),
    48468: ItemData(IC.useful, 1, 'wh3_main_tze_resource_iron_2', ItemType.building, 1, 'Progressive tze_resource_iron', 'Tze Building: Cultist Outpost (Iron)'),
    48469: ItemData(IC.useful, 1, 'wh3_main_tze_resource_iron_3', ItemType.building, 2, 'Progressive tze_resource_iron', 'Tze Building: Cultist Enclave (Iron)'),
    48470: ItemData(IC.useful, 1, 'wh3_main_tze_resource_ivory_1', ItemType.building, 0, 'Progressive tze_resource_ivory', 'Tze Building: Cultist Camp (Tusks)'),
    48471: ItemData(IC.useful, 1, 'wh3_main_tze_resource_ivory_2', ItemType.building, 1, 'Progressive tze_resource_ivory', 'Tze Building: Cultist Outpost (Tusks)'),
    48472: ItemData(IC.useful, 1, 'wh3_main_tze_resource_ivory_3', ItemType.building, 2, 'Progressive tze_resource_ivory', 'Tze Building: Cultist Enclave (Tusks)'),
    48473: ItemData(IC.useful, 1, 'wh3_main_tze_resource_marble_1', ItemType.building, 0, 'Progressive tze_resource_marble', 'Tze Building: Cultist Camp (Marble)'),
    48474: ItemData(IC.useful, 1, 'wh3_main_tze_resource_marble_2', ItemType.building, 1, 'Progressive tze_resource_marble', 'Tze Building: Cultist Outpost (Marble)'),
    48475: ItemData(IC.useful, 1, 'wh3_main_tze_resource_marble_3', ItemType.building, 2, 'Progressive tze_resource_marble', 'Tze Building: Cultist Enclave (Marble)'),
    48476: ItemData(IC.useful, 1, 'wh3_main_tze_resource_medicine_1', ItemType.building, 0, 'Progressive tze_resource_medicine', 'Tze Building: Cultist Camp (Medicine)'),
    48477: ItemData(IC.useful, 1, 'wh3_main_tze_resource_medicine_2', ItemType.building, 1, 'Progressive tze_resource_medicine', 'Tze Building: Cultist Outpost (Medicine)'),
    48478: ItemData(IC.useful, 1, 'wh3_main_tze_resource_medicine_3', ItemType.building, 2, 'Progressive tze_resource_medicine', 'Tze Building: Cultist Enclave (Medicine)'),
    48479: ItemData(IC.useful, 1, 'wh3_main_tze_resource_obsidian_1', ItemType.building, 0, 'Progressive tze_resource_obsidian', 'Tze Building: Cultist Camp (Obsidian)'),
    48480: ItemData(IC.useful, 1, 'wh3_main_tze_resource_obsidian_2', ItemType.building, 1, 'Progressive tze_resource_obsidian', 'Tze Building: Cultist Outpost (Obsidian)'),
    48481: ItemData(IC.useful, 1, 'wh3_main_tze_resource_obsidian_3', ItemType.building, 2, 'Progressive tze_resource_obsidian', 'Tze Building: Cultist Enclave (Obsidian)'),
    48482: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pasture_1', ItemType.building, 0, 'Progressive tze_resource_pasture', 'Tze Building: Cultist Camp (Pasture)'),
    48483: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pasture_2', ItemType.building, 1, 'Progressive tze_resource_pasture', 'Tze Building: Cultist Outpost (Pasture)'),
    48484: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pasture_3', ItemType.building, 2, 'Progressive tze_resource_pasture', 'Tze Building: Cultist Enclave (Pasture)'),
    48485: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pottery_1', ItemType.building, 0, 'Progressive tze_resource_pottery', 'Tze Building: Cultist Camp (Pottery)'),
    48486: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pottery_2', ItemType.building, 1, 'Progressive tze_resource_pottery', 'Tze Building: Cultist Outpost (Pottery)'),
    48487: ItemData(IC.useful, 1, 'wh3_main_tze_resource_pottery_3', ItemType.building, 2, 'Progressive tze_resource_pottery', 'Tze Building: Cultist Enclave (Pottery)'),
    48488: ItemData(IC.useful, 1, 'wh3_main_tze_resource_salt_1', ItemType.building, 0, 'Progressive tze_resource_salt', 'Tze Building: Cultist Camp (Salt)'),
    48489: ItemData(IC.useful, 1, 'wh3_main_tze_resource_salt_2', ItemType.building, 1, 'Progressive tze_resource_salt', 'Tze Building: Cultist Outpost (Salt)'),
    48490: ItemData(IC.useful, 1, 'wh3_main_tze_resource_salt_3', ItemType.building, 2, 'Progressive tze_resource_salt', 'Tze Building: Cultist Enclave (Salt)'),
    48491: ItemData(IC.useful, 1, 'wh3_main_tze_resource_spices_1', ItemType.building, 0, 'Progressive tze_resource_spices', 'Tze Building: Cultist Camp (Spices)'),
    48492: ItemData(IC.useful, 1, 'wh3_main_tze_resource_spices_2', ItemType.building, 1, 'Progressive tze_resource_spices', 'Tze Building: Cultist Outpost (Spices)'),
    48493: ItemData(IC.useful, 1, 'wh3_main_tze_resource_spices_3', ItemType.building, 2, 'Progressive tze_resource_spices', 'Tze Building: Cultist Enclave (Spices)'),
    48494: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wine_1', ItemType.building, 0, 'Progressive tze_resource_wine', 'Tze Building: Cultist Camp (Wine)'),
    48495: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wine_2', ItemType.building, 1, 'Progressive tze_resource_wine', 'Tze Building: Cultist Outpost (Wine)'),
    48496: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wine_3', ItemType.building, 2, 'Progressive tze_resource_wine', 'Tze Building: Cultist Enclave (Wine)'),
    48497: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wood_1', ItemType.building, 0, 'Progressive tze_resource_wood', 'Tze Building: Cultist Camp (Wood)'),
    48498: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wood_2', ItemType.building, 1, 'Progressive tze_resource_wood', 'Tze Building: Cultist Outpost (Wood)'),
    48499: ItemData(IC.useful, 1, 'wh3_main_tze_resource_wood_3', ItemType.building, 2, 'Progressive tze_resource_wood', 'Tze Building: Cultist Enclave (Wood)'),
    48500: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_1_a', ItemType.building, 0, 'Progressive tze_settlement_major', 'Tze Building: Soul Keep'),
    48501: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_1', ItemType.building, 0, 'Progressive tze_settlement_major', 'Tze Building: Dimensional Tear'),
    48502: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_2_a', ItemType.building, 1, 'Progressive tze_settlement_major', 'Tze Building: Dark Bastion'),
    48503: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_2', ItemType.building, 1, 'Progressive tze_settlement_major', 'Tze Building: Dimensional Breach'),
    48504: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_3_a', ItemType.building, 2, 'Progressive tze_settlement_major', 'Tze Building: Infernal Citadel'),
    48505: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_3', ItemType.building, 2, 'Progressive tze_settlement_major', 'Tze Building: Dimensional Rift'),
    48506: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_4_a', ItemType.building, 3, 'Progressive tze_settlement_major', 'Tze Building: Daemonic Fortress'),
    48507: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_4', ItemType.building, 3, 'Progressive tze_settlement_major', 'Tze Building: Dimensional Nexus'),
    48508: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_5_a', ItemType.building, 4, 'Progressive tze_settlement_major', 'Tze Building: Chaos Dreadhold'),
    48509: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_major_5', ItemType.building, 4, 'Progressive tze_settlement_major', 'Tze Building: Dimensional Cascade'),
    48510: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_minor_1', ItemType.building, 0, 'Progressive tze_settlement_minor', 'Tze Building: Soul Keep'),
    48511: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_minor_2', ItemType.building, 1, 'Progressive tze_settlement_minor', 'Tze Building: Dark Bastion'),
    48512: ItemData(IC.useful, 1, 'wh3_main_tze_settlement_minor_3', ItemType.building, 2, 'Progressive tze_settlement_minor', 'Tze Building: Infernal Citadel'),
    48513: ItemData(IC.useful, 1, 'wh3_main_tze_walls_major_1', ItemType.building, 0, 'Progressive tze_walls_major', 'Tze Building: Daemonic Lurkers'),
    48514: ItemData(IC.useful, 1, 'wh3_main_tze_walls_major_2', ItemType.building, 1, 'Progressive tze_walls_major', 'Tze Building: Daemonic Gathering'),
    48515: ItemData(IC.useful, 1, 'wh3_main_tze_walls_major_3', ItemType.building, 2, 'Progressive tze_walls_major', 'Tze Building: Daemonic Locus'),
    48516: ItemData(IC.useful, 1, 'wh3_main_tze_walls_minor_1', ItemType.building, 0, 'Progressive tze_walls_minor', 'Tze Building: Glittering Bartizan'),
    48517: ItemData(IC.useful, 1, 'wh3_main_tze_walls_minor_2', ItemType.building, 1, 'Progressive tze_walls_minor', 'Tze Building: Crystalline Walls')
}

techs: dict[int, ItemData] = {
    48800: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_7', ItemType.tech, 1, 'Progressive tech_tze_mutation', 'Tze Tech: Gift of Mutation'),
    48801: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_9', ItemType.tech, 2, 'Progressive tech_tze_mutation', 'Tze Tech: Way of Deceit'),
    48802: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_2', ItemType.tech, 3, 'Progressive tech_tze_mutation', 'Tze Tech: Glean Magic'),
    48803: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_7', ItemType.tech, 3, 'Progressive tech_tze_mutation', 'Tze Tech: Transmutation of Ore'),
    48804: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_6', ItemType.tech, 3, 'Progressive tech_tze_mutation', 'Tze Tech: Greater Locus of Change'),
    48805: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_8', ItemType.tech, 4, 'Progressive tech_tze_mutation', 'Tze Tech: Exalted Locus of Conjuration'),
    48806: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_4', ItemType.tech, 4, 'Progressive tech_tze_mutation', 'Tze Tech: Bolt of Change'),
    48807: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_5', ItemType.tech, 4, 'Progressive tech_tze_mutation', 'Tze Tech: Warpflame Formulae'),
    48808: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_3', ItemType.tech, 4, 'Progressive tech_tze_mutation', 'Tze Tech: Way of War'),
    48809: ItemData(IC.useful, 1, 'wh3_main_tech_tze_2_1', ItemType.tech, 5, 'Progressive tech_tze_mutation', 'Tze Tech: Scatter Loci'),
    48810: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_9', ItemType.tech, 1, 'Progressive tech_tze_transmog', 'Tze Tech: Locus of Transmogrification'),
    48811: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_5', ItemType.tech, 2, 'Progressive tech_tze_transmog', 'Tze Tech: Way of Time'),
    48812: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_4', ItemType.tech, 3, 'Progressive tech_tze_transmog', 'Tze Tech: Metallurgical Morphism'),
    48813: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_1', ItemType.tech, 3, 'Progressive tech_tze_transmog', 'Tze Tech: Pestilent Hatred'),
    48814: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_7', ItemType.tech, 4, 'Progressive tech_tze_transmog', 'Tze Tech: Way of Manipulation'),
    48815: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_9', ItemType.tech, 5, 'Progressive tech_tze_transmog', 'Tze Tech: Disc Taming'),
    48816: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_6', ItemType.tech, 6, 'Progressive tech_tze_transmog', 'Tze Tech: Persistent Change'),
    48817: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_3', ItemType.tech, 7, 'Progressive tech_tze_transmog', 'Tze Tech: Treason of Tzeentch'),
    48818: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_2', ItemType.tech, 8, 'Progressive tech_tze_transmog', 'Tze Tech: Storm of Fire'),
    48819: ItemData(IC.useful, 1, 'wh3_main_tech_tze_3_8', ItemType.tech, 9, 'Progressive tech_tze_transmog', 'Tze Tech: Stannic Deviance'),
    48820: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_1', ItemType.tech, 1, 'Progressive tech_tze_thaumatic', 'Tze Tech: Thaumatic Locus'),
    48821: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_1', ItemType.tech, 2, 'Progressive tech_tze_thaumatic', 'Tze Tech: Way of Scrying'),
    48822: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_8', ItemType.tech, 3, 'Progressive tech_tze_thaumatic', 'Tze Tech: Piercing Screams'),
    48823: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_6', ItemType.tech, 3, 'Progressive tech_tze_thaumatic', 'Tze Tech: Word Seeker'),
    48824: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_9', ItemType.tech, 4, 'Progressive tech_tze_thaumatic', 'Tze Tech: Way of Fate'),
    48825: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_3', ItemType.tech, 4, 'Progressive tech_tze_thaumatic', 'Tze Tech: Fluxion Constructs'),
    48826: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_2', ItemType.tech, 5, 'Progressive tech_tze_thaumatic', 'Tze Tech: Champions of Change'),
    48827: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_7', ItemType.tech, 5, 'Progressive tech_tze_thaumatic', 'Tze Tech: Eye Collecting'),
    48828: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_4', ItemType.tech, 6, 'Progressive tech_tze_thaumatic', 'Tze Tech: Iridescent Touch'),
    48829: ItemData(IC.useful, 1, 'wh3_main_tech_tze_1_5', ItemType.tech, 7, 'Progressive tech_tze_thaumatic', 'Tze Tech: Infernal Gateway'),
    48830: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_3', ItemType.tech, 1, 'Progressive tech_tze_cult', 'Tze Tech: Cult Whisperer'),
    48831: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_9', ItemType.tech, 2, 'Progressive tech_tze_cult', 'Tze Tech: Way of Prognostication'),
    48832: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_2', ItemType.tech, 3, 'Progressive tech_tze_cult', 'Tze Tech: Endless Mutation'),
    48833: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_7', ItemType.tech, 3, 'Progressive tech_tze_cult', 'Tze Tech: Blinding Iridescent'),
    48834: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_1', ItemType.tech, 4, 'Progressive tech_tze_cult', 'Tze Tech: Temporal Switch'),
    48835: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_3', ItemType.tech, 4, 'Progressive tech_tze_cult', 'Tze Tech: Locus of Contrivance'),
    48836: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_5', ItemType.tech, 5, 'Progressive tech_tze_cult', "Tze Tech: The Architect's Chosen"),
    48837: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_6', ItemType.tech, 5, 'Progressive tech_tze_cult', 'Tze Tech: Inscrutable Demagoguery'),
    48838: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_8', ItemType.tech, 6, 'Progressive tech_tze_cult', 'Tze Tech: Awaken the Sleeper'),
    48839: ItemData(IC.useful, 1, 'wh3_main_tech_tze_4_4', ItemType.tech, 7, 'Progressive tech_tze_cult', "Tze Tech: Tzeentch's Firestorm"),
    48840: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_2', ItemType.tech, 1, 'Progressive tech_tze_grimoire', 'Tze Tech: Fires of Change'),
    48841: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_4', ItemType.tech, 1, 'Progressive tech_tze_grimoire', 'Tze Tech: Arcane Surge'),
    48842: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_5', ItemType.tech, 1, 'Progressive tech_tze_grimoire', 'Tze Tech: Teleport'),
    48843: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_6', ItemType.tech, 1, 'Progressive tech_tze_grimoire', 'Tze Tech: Secret of Chrysopeia'),
    48844: ItemData(IC.useful, 1, 'wh3_main_tech_tze_0_8', ItemType.tech, 1, 'Progressive tech_tze_grimoire', 'Tze Tech: Way of Deception')
}

progUnits: dict[int, ItemData] = {
    49200: ItemData(IC.useful, 4, "Progressive tze_inf", ItemType.unit, 4, "", "Progressive Tze Unit: Infantry"),
    49201: ItemData(IC.useful, 4, "Progressive tze_rng", ItemType.unit, 4, "", "Progressive Tze Unit: Ranged"),
    49202: ItemData(IC.useful, 4, "Progressive tze_cav", ItemType.unit, 4, "", "Progressive Tze Unit: Cavalry"),
    49204: ItemData(IC.useful, 3, "Progressive tze_veh", ItemType.unit, 3, "", "Progressive Tze Unit: Chariot"),
    49205: ItemData(IC.useful, 5, "Progressive tze_bst", ItemType.unit, 5, "", "Progressive Tze Unit: Beast"),
    49206: ItemData(IC.useful, 2, "Progressive tze_hro", ItemType.unit, 2, "", "Progressive Tze Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    49300: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_tze', ItemType.building, 3, None, 'Progressive Tze Building: Foreign Slot Discovery Tze'),
    49301: ItemData(IC.useful, 3, 'Progressive tze_allied_outpost', ItemType.building, 3, None, 'Progressive Tze Building: Allied Outpost'),
    49302: ItemData(IC.useful, 3, 'Progressive tze_caster', ItemType.building, 3, None, 'Progressive Tze Building: Caster'),
    49303: ItemData(IC.useful, 3, 'Progressive tze_corruption', ItemType.building, 3, None, 'Progressive Tze Building: Corruption'),
    49304: ItemData(IC.useful, 1, 'Progressive tze_cult', ItemType.building, 1, None, 'Progressive Tze Building: Cult'),
    49305: ItemData(IC.useful, 1, 'Progressive tze_cult_corruption', ItemType.building, 1, None, 'Progressive Tze Building: Cult Corruption'),
    49306: ItemData(IC.useful, 1, 'Progressive tze_cult_extra', ItemType.building, 1, None, 'Progressive Tze Building: Cult Extra'),
    49307: ItemData(IC.useful, 4, 'Progressive tze_flamer', ItemType.building, 4, None, 'Progressive Tze Building: Flamer'),
    49308: ItemData(IC.useful, 3, 'Progressive tze_growth_corruption', ItemType.building, 3, None, 'Progressive Tze Building: Growth Corruption'),
    49309: ItemData(IC.useful, 3, 'Progressive tze_growth_gold', ItemType.building, 3, None, 'Progressive Tze Building: Growth Gold'),
    49310: ItemData(IC.useful, 3, 'Progressive tze_horror_barracks', ItemType.building, 3, None, 'Progressive Tze Building: Horror Barracks'),
    49311: ItemData(IC.useful, 3, 'Progressive tze_library', ItemType.building, 3, None, 'Progressive Tze Building: Library'),
    49312: ItemData(IC.useful, 4, 'Progressive tze_monster_barracks', ItemType.building, 4, None, 'Progressive Tze Building: Monster Barracks'),
    49313: ItemData(IC.useful, 3, 'Progressive tze_mounted', ItemType.building, 3, None, 'Progressive Tze Building: Mounted'),
    49314: ItemData(IC.useful, 3, 'Progressive tze_order_los', ItemType.building, 3, None, 'Progressive Tze Building: Order Los'),
    49315: ItemData(IC.useful, 3, 'Progressive tze_port', ItemType.building, 3, None, 'Progressive Tze Building: Port'),
    49316: ItemData(IC.useful, 3, 'Progressive tze_resource_animals', ItemType.building, 3, None, 'Progressive Tze Building: Animals'),
    49317: ItemData(IC.useful, 3, 'Progressive tze_resource_dyes', ItemType.building, 3, None, 'Progressive Tze Building: Dyes'),
    49318: ItemData(IC.useful, 3, 'Progressive tze_resource_furs', ItemType.building, 3, None, 'Progressive Tze Building: Furs'),
    49319: ItemData(IC.useful, 3, 'Progressive tze_resource_gems', ItemType.building, 3, None, 'Progressive Tze Building: Gems'),
    49320: ItemData(IC.useful, 3, 'Progressive tze_resource_gold', ItemType.building, 3, None, 'Progressive Tze Building: Gold'),
    49321: ItemData(IC.useful, 3, 'Progressive tze_resource_iron', ItemType.building, 3, None, 'Progressive Tze Building: Iron'),
    49322: ItemData(IC.useful, 3, 'Progressive tze_resource_ivory', ItemType.building, 3, None, 'Progressive Tze Building: Ivory'),
    49323: ItemData(IC.useful, 3, 'Progressive tze_resource_marble', ItemType.building, 3, None, 'Progressive Tze Building: Marble'),
    49324: ItemData(IC.useful, 3, 'Progressive tze_resource_medicine', ItemType.building, 3, None, 'Progressive Tze Building: Medicine'),
    49325: ItemData(IC.useful, 3, 'Progressive tze_resource_obsidian', ItemType.building, 3, None, 'Progressive Tze Building: Obsidian'),
    49326: ItemData(IC.useful, 3, 'Progressive tze_resource_pasture', ItemType.building, 3, None, 'Progressive Tze Building: Pasture'),
    49327: ItemData(IC.useful, 3, 'Progressive tze_resource_pottery', ItemType.building, 3, None, 'Progressive Tze Building: Pottery'),
    49328: ItemData(IC.useful, 3, 'Progressive tze_resource_salt', ItemType.building, 3, None, 'Progressive Tze Building: Salt'),
    49329: ItemData(IC.useful, 3, 'Progressive tze_resource_spices', ItemType.building, 3, None, 'Progressive Tze Building: Spices'),
    49330: ItemData(IC.useful, 3, 'Progressive tze_resource_wine', ItemType.building, 3, None, 'Progressive Tze Building: Wine'),
    49331: ItemData(IC.useful, 3, 'Progressive tze_resource_wood', ItemType.building, 3, None, 'Progressive Tze Building: Wood'),
    49332: ItemData(IC.useful, 5, 'Progressive tze_settlement_major', ItemType.building, 5, None, 'Progressive Tze Building: Settlement Major'),
    49333: ItemData(IC.useful, 3, 'Progressive tze_settlement_minor', ItemType.building, 3, None, 'Progressive Tze Building: Settlement Minor'),
    49334: ItemData(IC.useful, 3, 'Progressive tze_walls_major', ItemType.building, 3, None, 'Progressive Tze Building: Walls Major'),
    49335: ItemData(IC.useful, 2, 'Progressive tze_walls_minor', ItemType.building, 2, None, 'Progressive Tze Building: Walls Minor')
}

progTechs: dict[int, ItemData] = {
    49400: ItemData(IC.useful, 5, "Progressive tech_tze_mutation", ItemType.tech, 5, None, "Progressive Tze Tech: Mutation"),
    49401: ItemData(IC.useful, 9, "Progressive tech_tze_transmog", ItemType.tech, 9, None, "Progressive Tze Tech: Transmogrification"),
    49402: ItemData(IC.useful, 7, "Progressive tech_tze_thaumatic", ItemType.tech, 7, None, "Progressive Tze Tech: Thaumatic"),
    49403: ItemData(IC.useful, 7, "Progressive tech_tze_cult", ItemType.tech, 7, None, "Progressive Tze Tech: Cult"),
    49404: ItemData(IC.useful, 1, "Progressive tech_tze_grimoire", ItemType.tech, 1, None, "Progressive Tze Tech: Grimoire"),
}

special: dict[int, ItemData] = {

}