from BaseClasses import ItemClassification as IC
from worlds.tww3.item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    50000: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_0', ItemType.unit, 1, 'Progressive cst_inf', 'Pirate Unit: Zombie Pirate Deckhand Mob'),
    50001: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_1', ItemType.unit, 2, 'Progressive cst_inf', 'Pirate Unit: Zombie Pirate Deckhand Mob (Polearms)'),
    50002: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_syreens', ItemType.unit, 3, 'Progressive cst_inf', 'Pirate Unit: Syreens'),
    50003: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_mournguls_0', ItemType.unit, 2, 'Progressive cst_inf', 'Pirate Unit: Mournguls'),
    50004: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_0', ItemType.unit, 4, 'Progressive cst_inf', 'Pirate Unit: Depth Guard'),
    50005: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_1', ItemType.unit, 5, 'Progressive cst_inf', 'Pirate Unit: Depth Guard (Polearms)'),
    50006: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_0', ItemType.unit, 1, 'Progressive cst_rng', 'Pirate Unit: Zombie Pirate Gunnery Mob'),
    50007: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_3', ItemType.unit, 2, 'Progressive cst_rng', 'Pirate Unit: Zombie Pirate Gunnery Mob (Bombers)'),
    50008: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_1', ItemType.unit, 2, 'Progressive cst_rng', 'Pirate Unit: Zombie Pirate Gunnery Mob (Handgunners)'),
    50009: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_2', ItemType.unit, 3, 'Progressive cst_rng', 'Pirate Unit: Zombie Pirate Gunnery Mob (Hand Cannons)'),
    50010: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_deck_gunners_0', ItemType.unit, 4, 'Progressive cst_rng', 'Pirate Unit: Deck Gunners'),
    50011: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_0', ItemType.unit, 1, 'Progressive cst_cav', 'Pirate Unit: Deck Droppers'),
    50012: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_2', ItemType.unit, 2, 'Progressive cst_cav', 'Pirate Unit: Deck Droppers (Handgunners)'),
    50013: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_1', ItemType.unit, 2, 'Progressive cst_cav', 'Pirate Unit: Deck Droppers (Bombers)'),
    50014: ItemData(IC.useful, 1, 'wh2_dlc11_cst_art_mortar', ItemType.unit, 1, 'Progressive cst_art', 'Pirate Unit: Mortars'),
    50015: ItemData(IC.useful, 1, 'wh2_dlc11_cst_art_carronade', ItemType.unit, 2, 'Progressive cst_art', 'Pirate Unit: Carronades'),
    50016: ItemData(IC.useful, 1, 'wh2_dlc11_cst_art_queen_bess', ItemType.unit, 3, 'Progressive cst_art', 'Pirate Unit: Queen Bess'),
    50017: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_fell_bats', ItemType.unit, 1, 'Progressive cst_bst', 'Pirate Unit: Fell Bats'),
    50018: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_scurvy_dogs', ItemType.unit, 2, 'Progressive cst_bst', 'Pirate Unit: Scurvy Dogs'),
    50019: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_bloated_corpse_0', ItemType.unit, 2, 'Progressive cst_bst', 'Pirate Unit: Bloated Corpse'),
    50020: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_animated_hulks_0', ItemType.unit, 2, 'Progressive cst_bst', 'Pirate Unit: Animated Hulks'),
    50021: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_0', ItemType.unit, 3, 'Progressive cst_bst', 'Pirate Unit: Rotting Prometheans'),
    50022: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_0', ItemType.unit, 4, 'Progressive cst_rng', 'Pirate Unit: Rotting Prometheans (Gunnery Mob)'),
    50023: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_leviathan_0', ItemType.unit, 5, 'Progressive cst_bst', 'Pirate Unit: Rotting Leviathan'),
    50024: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_necrofex_colossus_0', ItemType.unit, 5, 'Progressive cst_bst', 'Pirate Unit: Necrofex Colossus'),
    50025: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_terrorgheist', ItemType.unit, 5, 'Progressive cst_bst', 'Pirate Unit: Death Shriek Terrorgheist'),
    50026: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cha_mourngul_haunter', ItemType.unit, 1, 'Progressive cst_hro', 'Pirate Unit: Mourngul Haunter'),
    50027: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cha_gunnery_wight_0', ItemType.unit, 1, 'Progressive cst_hro', 'Pirate Unit: Gunnery Wight'),
    50028: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cha_vampire_fleet_captain_0', ItemType.unit, 1, 'Progressive cst_hro', 'Pirate Unit: Vampire Fleet Captain (Vampires)'),
    50029: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cha_vampire_fleet_captain_death_0', ItemType.unit, 1, 'Progressive cst_hro', 'Pirate Unit: Vampire Fleet Captain (Death)'),
    50030: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cha_vampire_fleet_captain_deeps_0', ItemType.unit, 1, 'Progressive cst_hro', 'Pirate Unit: Vampire Fleet Captain (Deeps)'),
    50031: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_depth_guard_ror_0', ItemType.unit, 4, 'Progressive cst_inf', 'Pirate Unit: The Bloody Reaver Deck Guard (Depth Guard)'),
    50032: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_deck_gunners_ror_0', ItemType.unit, 4, 'Progressive cst_rng', 'Pirate Unit: Shadewraith Gunners (Deck Gunners)'),
    50033: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_deckhands_mob_ror_0', ItemType.unit, 1, 'Progressive cst_inf', 'Pirate Unit: The Tide of Skjold (Zombie Pirate Deckhand Mob)'),
    50034: ItemData(IC.useful, 1, 'wh2_dlc11_cst_inf_zombie_gunnery_mob_ror_0', ItemType.unit, 2, 'Progressive cst_rng', 'Pirate Unit: The Black Spot (Zombie Pirate Gunnery Mob - Handgunners)'),
    50035: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_mournguls_ror_0', ItemType.unit, 3, 'Progressive cst_inf', 'Pirate Unit: Night Terrors (Mournguls)'),
    50036: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_necrofex_colossus_ror_0', ItemType.unit, 5, 'Progressive cst_bst', 'Pirate Unit: Gallows Giant (Necrofex Colossus)'),
    50037: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_ror', ItemType.unit, 4, 'Progressive cst_bst', "Pirate Unit: The Lamprey's Revenge (Rotting Promethean Gunnery Mob)"),
    50038: ItemData(IC.useful, 1, 'wh2_dlc11_cst_cav_deck_droppers_ror_0', ItemType.unit, 2, 'Progressive cst_cav', 'Pirate Unit: Salt Lord Scuttlers (Deck Droppers - Bombers)')
}

buildings: dict[int, ItemData] = {
    50400: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_animals_1', ItemType.building, 0, 'Progressive cst_resource_animals', 'Pirate Building: Exotic Animal Market'),
    50401: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_dyes_1', ItemType.building, 0, 'Progressive cst_resource_dyes', "Pirate Building: Pigment Grinder's Shop"),
    50402: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_furs_1', ItemType.building, 0, 'Progressive cst_resource_furs', 'Pirate Building: Poaching Camp'),
    50403: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_gems_1', ItemType.building, 0, 'Progressive cst_resource_gems', 'Pirate Building: Gemstone Mine'),
    50404: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_gold_1', ItemType.building, 0, 'Progressive cst_resource_gold', 'Pirate Building: Gold Mine'),
    50405: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_iron_1', ItemType.building, 0, 'Progressive cst_resource_iron', 'Pirate Building: Iron Mine'),
    50406: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_marble_1', ItemType.building, 0, 'Progressive cst_resource_marble', "Pirate Building: Brimstone Cutter's Workshop"),
    50407: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_medicine_1', ItemType.building, 0, 'Progressive cst_resource_medicine', 'Pirate Building: Alchemy Workshop'),
    50408: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_obsidian_1', ItemType.building, 0, 'Progressive cst_resource_obsidian', 'Pirate Building: Obsidian Quarry'),
    50409: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_pasture_1', ItemType.building, 0, 'Progressive cst_resource_pasture', 'Pirate Building: Haunted Mill'),
    50410: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_pottery_1', ItemType.building, 0, 'Progressive cst_resource_pottery', 'Pirate Building: Clay Pit'),
    50411: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_salt_1', ItemType.building, 0, 'Progressive cst_resource_salt', 'Pirate Building: Salt Pans'),
    50412: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_spices_1', ItemType.building, 0, 'Progressive cst_resource_spices', 'Pirate Building: Eastern Bazaar'),
    50413: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_wine_1', ItemType.building, 0, 'Progressive cst_resource_wine', 'Pirate Building: Thorny Orchard'),
    50414: ItemData(IC.useful, 1, 'wh2_dlc11_cst_resource_wood_1', ItemType.building, 0, 'Progressive cst_resource_wood', "Pirate Building: Forester's Shack"),
    50415: ItemData(IC.useful, 1, 'wh2_dlc11_foreign_corruption_1', ItemType.building, 0, 'Progressive foreign_corruption', 'Pirate Building: Corrupted Tavern'),
    50416: ItemData(IC.useful, 1, 'wh2_dlc11_foreign_income_1', ItemType.building, 0, 'Progressive foreign_income', "Pirate Building: Picaroons' Hideout"),
    50417: ItemData(IC.useful, 1, 'wh2_dlc11_foreign_infamy_1', ItemType.building, 0, 'Progressive foreign_infamy', "Pirate Building: Pirates' Rest"),
    50418: ItemData(IC.useful, 1, 'wh2_dlc11_foreign_trade_1', ItemType.building, 0, 'Progressive foreign_trade', "Pirate Building: Smugglers' Cove"),
    50419: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_1', ItemType.building, 0, 'Progressive horde_def_aristocracy', 'Pirate Building: Dread Manse'),
    50420: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_aristocracy_2', ItemType.building, 1, 'Progressive horde_def_aristocracy', 'Pirate Building: Palace of Dread Knights'),
    50421: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_1', ItemType.building, 0, 'Progressive horde_def_exiles', 'Pirate Building: Den of Outlaws'),
    50422: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_exiles_2', ItemType.building, 1, 'Progressive horde_def_exiles', 'Pirate Building: House of Exiles'),
    50423: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_1', ItemType.building, 0, 'Progressive horde_def_residence', 'Pirate Building: Dark Elf Manors'),
    50424: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_2', ItemType.building, 1, 'Progressive horde_def_residence', 'Pirate Building: Dark Elf Residences'),
    50425: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_residence_3', ItemType.building, 2, 'Progressive horde_def_residence', 'Pirate Building: Estates of the Masters'),
    50426: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_1', ItemType.building, 0, 'Progressive horde_def_riders', 'Pirate Building: Reaver Stables'),
    50427: ItemData(IC.useful, 1, 'wh2_dlc11_horde_def_riders_2', ItemType.building, 1, 'Progressive horde_def_riders', "Pirate Building: Messengers' Lodgehouse"),
    50432: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_1', ItemType.building, 0, 'Progressive vampirecoast_settlement_major', 'Pirate Building: The Maelstrom (Dormant)'),
    50433: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_2', ItemType.building, 1, 'Progressive vampirecoast_settlement_major', 'Pirate Building: The Maelstrom (Stirring)'),
    50434: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_3', ItemType.building, 2, 'Progressive vampirecoast_settlement_major', 'Pirate Building: The Maelstrom (Active)'),
    50435: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_4', ItemType.building, 3, 'Progressive vampirecoast_settlement_major', 'Pirate Building: The Maelstrom (Powerful)'),
    50436: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_5', ItemType.building, 4, 'Progressive vampirecoast_settlement_major', 'Pirate Building: The Maelstrom (Raging)'),
    #50437: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_other_1', ItemType.building, 0, 'Progressive special_settlement_galleons_graveyard_other', 'Pirate Building: The Maelstrom'),
    #50438: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_other_1', ItemType.building, 0, 'Progressive special_settlement_galleons_graveyard_other', 'Pirate Building: The Maelstrom'),
    #50439: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_other_1', ItemType.building, 0, 'Progressive special_settlement_galleons_graveyard_other', 'Pirate Building: Pirate Building: The Maelstrom'),
    #50440: ItemData(IC.useful, 1, 'wh2_dlc11_special_settlement_galleons_graveyard_other_1', ItemType.building, 0, 'Progressive special_settlement_galleons_graveyard_other', 'Pirate Building: Pirate Building: The Maelstrom'),
    50442: ItemData(IC.useful, 1, 'wh2_dlc11_special_ship_harpoon_1', ItemType.building, 0, 'Progressive special_ship_harpoon', 'Pirate Building: Dart Launcher'),
    50443: ItemData(IC.useful, 1, 'wh2_dlc11_special_ship_harpoon_2', ItemType.building, 1, 'Progressive special_ship_harpoon', 'Pirate Building: Barb Launcher'),
    50444: ItemData(IC.useful, 1, 'wh2_dlc11_special_ship_harpoon_3', ItemType.building, 2, 'Progressive special_ship_harpoon', 'Pirate Building: Gaff Launcher'),
    50445: ItemData(IC.useful, 1, 'wh2_dlc11_special_ship_harpoon_4', ItemType.building, 3, 'Progressive special_ship_harpoon', 'Pirate Building: Trident Launcher'),
    50446: ItemData(IC.useful, 1, 'wh2_dlc11_special_ship_harpoon_5', ItemType.building, 4, 'Progressive special_ship_harpoon', 'Pirate Building: Harpoon Launcher'),
    50447: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_garrison_1', ItemType.building, 0, 'Progressive vampirecoast_defence_garrison', 'Pirate Building: Zombie Watch Posts'),
    50448: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_garrison_2', ItemType.building, 1, 'Progressive vampirecoast_defence_garrison', 'Pirate Building: Haunted Blockhouse'),
    50449: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_norsca_1', ItemType.building, 0, 'Progressive vampirecoast_defence_norsca', 'Pirate Building: Palisades'),
    50450: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_walls_1', ItemType.building, 0, 'Progressive vampirecoast_defence_walls', 'Pirate Building: Palisades'),
    50451: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_walls_2', ItemType.building, 1, 'Progressive vampirecoast_defence_walls', 'Pirate Building: Barricade of Debris'),
    50452: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_defence_walls_3', ItemType.building, 2, 'Progressive vampirecoast_defence_walls', 'Pirate Building: Parapets'),
    50453: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_corruption_1', ItemType.building, 0, 'Progressive vampirecoast_infrastructure_corruption', 'Pirate Building: Dead Pirateâ€™s Totems'),
    50454: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_corruption_2', ItemType.building, 1, 'Progressive vampirecoast_infrastructure_corruption', 'Pirate Building: Effigies of Undeath'),
    50455: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_corruption_3', ItemType.building, 2, 'Progressive vampirecoast_infrastructure_corruption', 'Pirate Building: Night Pyres'),
    50456: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_growth_1', ItemType.building, 0, 'Progressive vampirecoast_infrastructure_growth', 'Pirate Building: Tree & Noose'),
    50457: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_growth_2', ItemType.building, 1, 'Progressive vampirecoast_infrastructure_growth', 'Pirate Building: Lynching Post'),
    50458: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_growth_3', ItemType.building, 2, 'Progressive vampirecoast_infrastructure_growth', 'Pirate Building: Pirate Gallows'),
    50459: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_1', ItemType.building, 0, 'Progressive vampirecoast_infrastructure_income', 'Pirate Building: Slave Pits'),
    50460: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_2', ItemType.building, 1, 'Progressive vampirecoast_infrastructure_income', 'Pirate Building: Meat Market'),
    50461: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_other_1', ItemType.building, 0, 'Progressive vampirecoast_infrastructure_income_other', 'Pirate Building: Plunder Pile'),
    50462: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_other_2', ItemType.building, 1, 'Progressive vampirecoast_infrastructure_income_other', 'Pirate Building: Swag Sacks'),
    50463: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_other_3', ItemType.building, 2, 'Progressive vampirecoast_infrastructure_income_other', 'Pirate Building: Hoard of Booty'),
    50464: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_other_4', ItemType.building, 3, 'Progressive vampirecoast_infrastructure_income_other', 'Pirate Building: Bullion Coffers'),
    50465: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_income_other_5', ItemType.building, 4, 'Progressive vampirecoast_infrastructure_income_other', 'Pirate Building: Buried Treasure Chest'),
    50466: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_public_order_1', ItemType.building, 0, 'Progressive vampirecoast_infrastructure_public_order', 'Pirate Building: Scurvy Dog Pits'),
    50467: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_public_order_2', ItemType.building, 1, 'Progressive vampirecoast_infrastructure_public_order', 'Pirate Building: Midnight Gambling Den'),
    50468: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_infrastructure_public_order_3', ItemType.building, 2, 'Progressive vampirecoast_infrastructure_public_order', "Pirate Building: Buccaneer's Tavern"),
    50469: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_barracks_1', ItemType.building, 0, 'Progressive vampirecoast_military_barracks', 'Pirate Building: Lagoon of Drowned Sailors'),
    50470: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_barracks_2', ItemType.building, 1, 'Progressive vampirecoast_military_barracks', "Pirate Building: Deckhands' Boneyard"),
    50471: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_barracks_3', ItemType.building, 2, 'Progressive vampirecoast_military_barracks', 'Pirate Building: Tomb of First Mates'),
    50472: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_barracks_4', ItemType.building, 3, 'Progressive vampirecoast_military_barracks', "Pirate Building: Admirals' Mausoleum"),
    50473: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_flying_1', ItemType.building, 0, 'Progressive vampirecoast_military_flying', 'Pirate Building: Fell Hollows'),
    50474: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_flying_2', ItemType.building, 1, 'Progressive vampirecoast_military_flying', 'Pirate Building: Roosting Trees'),
    50475: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_flying_3', ItemType.building, 2, 'Progressive vampirecoast_military_flying', 'Pirate Building: Cave of Flying Horrors'),
    50476: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_flying_4', ItemType.building, 3, 'Progressive vampirecoast_military_flying', 'Pirate Building: Giant Feeding Cavern'),
    50477: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_ranged_1', ItemType.building, 0, 'Progressive vampirecoast_military_ranged', 'Pirate Building: Rusty Pistol-Trove'),
    50478: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_ranged_2', ItemType.building, 1, 'Progressive vampirecoast_military_ranged', 'Pirate Building: Hoard of Filched Firearms'),
    50479: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_ranged_3', ItemType.building, 2, 'Progressive vampirecoast_military_ranged', 'Pirate Building: Armoury of the Soulless'),
    50480: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_military_ranged_4', ItemType.building, 3, 'Progressive vampirecoast_military_ranged', "Pirate Building: Dead Pirates' Workshop"),
    50481: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_port_1', ItemType.building, 0, 'Progressive vampirecoast_port', "Pirate Building: Smugglers' Landing"),
    50482: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_port_2', ItemType.building, 1, 'Progressive vampirecoast_port', "Pirate Building: Smugglers' Jetty"),
    50483: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_port_3', ItemType.building, 2, 'Progressive vampirecoast_port', 'Pirate Building: Pirate Wharf'),
    50484: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_major_1', ItemType.building, 0, 'Progressive vampirecoast_settlement_major', 'Pirate Building: Slums of the Cursed'),
    50485: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_major_2', ItemType.building, 1, 'Progressive vampirecoast_settlement_major', 'Pirate Building: Haunted Shanty Town'),
    50486: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_major_3', ItemType.building, 2, 'Progressive vampirecoast_settlement_major', "Pirate Building: Dead Pirates' Holdout"),
    50487: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_major_4', ItemType.building, 3, 'Progressive vampirecoast_settlement_major', "Pirate Building: Dead Pirates' Lair"),
    50488: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_major_5', ItemType.building, 4, 'Progressive vampirecoast_settlement_major', "Pirate Building: Dead Pirates' Stronghold"),
    50489: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_minor_1', ItemType.building, 0, 'Progressive vampirecoast_settlement_minor', 'Pirate Building: Ghetto of the Cursed'),
    50490: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_minor_2', ItemType.building, 1, 'Progressive vampirecoast_settlement_minor', 'Pirate Building: Haunted Hovels'),
    50491: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_settlement_minor_3', ItemType.building, 2, 'Progressive vampirecoast_settlement_minor', "Pirate Building: Dead Pirates' Hamlet"),
    50492: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_anchor_1', ItemType.building, 0, 'Progressive vampirecoast_ship_anchor', 'Pirate Shipbuilding: Heavy Ballast'),
    50493: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_anchor_2', ItemType.building, 1, 'Progressive vampirecoast_ship_anchor', 'Pirate Shipbuilding: Stone Weight'),
    50494: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_anchor_3', ItemType.building, 2, 'Progressive vampirecoast_ship_anchor', 'Pirate Shipbuilding: Steel Anchor'),
    50495: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_cannons_1', ItemType.building, 0, 'Progressive vampirecoast_ship_cannons', 'Pirate Shipbuilding: Bombards'),
    50496: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_cannons_2', ItemType.building, 1, 'Progressive vampirecoast_ship_cannons', 'Pirate Shipbuilding: Carronades'),
    50497: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_cannons_3', ItemType.building, 2, 'Progressive vampirecoast_ship_cannons', 'Pirate Shipbuilding: Cannons'),
    50498: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_captains_cabin_1', ItemType.building, 0, 'Progressive vampirecoast_ship_captains_cabin', 'Pirate Shipbuilding: General Cabin'),
    50499: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_captains_cabin_2', ItemType.building, 1, 'Progressive vampirecoast_ship_captains_cabin', "Pirate Shipbuilding: Officers' Cabin"),
    50500: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_captains_cabin_3', ItemType.building, 2, 'Progressive vampirecoast_ship_captains_cabin', "Pirate Shipbuilding: Captain's Cabin"),
    50501: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_captains_cabin_4', ItemType.building, 3, 'Progressive vampirecoast_ship_captains_cabin', 'Pirate Shipbuilding: Sea Cabin'),
    50502: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_captains_cabin_5', ItemType.building, 4, 'Progressive vampirecoast_ship_captains_cabin', 'Pirate Shipbuilding: Great Cabin'),
    50503: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_crows_nest_1', ItemType.building, 0, 'Progressive vampirecoast_ship_crows_nest', 'Pirate Shipbuilding: Lookout Seat'),
    50504: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_crows_nest_2', ItemType.building, 1, 'Progressive vampirecoast_ship_crows_nest', 'Pirate Shipbuilding: Lookout Cradle'),
    50505: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_crows_nest_3', ItemType.building, 2, 'Progressive vampirecoast_ship_crows_nest', "Pirate Shipbuilding: Crow's Nest"),
    50506: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_crows_nest_4', ItemType.building, 3, 'Progressive vampirecoast_ship_crows_nest', "Pirate Shipbuilding: Crow's Castle"),
    50507: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_gunports_1', ItemType.building, 0, 'Progressive vampirecoast_ship_gunports', 'Pirate Shipbuilding: Holes in the Side'),
    50508: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_gunports_2', ItemType.building, 1, 'Progressive vampirecoast_ship_gunports', 'Pirate Shipbuilding: Portholes'),
    50509: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_gunports_3', ItemType.building, 2, 'Progressive vampirecoast_ship_gunports', 'Pirate Shipbuilding: Gunports'),
    50510: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_gunports_4', ItemType.building, 3, 'Progressive vampirecoast_ship_gunports', 'Pirate Shipbuilding: Shuttered Gunports'),
    50511: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_helm_1', ItemType.building, 0, 'Progressive vampirecoast_ship_helm', 'Pirate Shipbuilding: Tiller'),
    50512: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_helm_2', ItemType.building, 1, 'Progressive vampirecoast_ship_helm', 'Pirate Shipbuilding: Whipstaff'),
    50513: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_helm_3', ItemType.building, 2, 'Progressive vampirecoast_ship_helm', "Pirate Shipbuilding: Ship's Wheel"),
    50514: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hold_1', ItemType.building, 0, 'Progressive vampirecoast_ship_hold', "Pirate Shipbuilding: Ship's Hold"),
    50515: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hold_2', ItemType.building, 1, 'Progressive vampirecoast_ship_hold', 'Pirate Shipbuilding: Cargo Hold'),
    50516: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hold_3', ItemType.building, 2, 'Progressive vampirecoast_ship_hold', 'Pirate Shipbuilding: Bulk Cargo Hold'),
    50517: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hull_1', ItemType.building, 0, 'Progressive vampirecoast_ship_hull', 'Pirate Shipbuilding: Basic Wooden Hull'),
    50518: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hull_2', ItemType.building, 1, 'Progressive vampirecoast_ship_hull', 'Pirate Shipbuilding: Wooden Hull with Keel'),
    50519: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_hull_3', ItemType.building, 2, 'Progressive vampirecoast_ship_hull', 'Pirate Shipbuilding: Composite Hull'),
    50520: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_main_deck_1', ItemType.building, 0, 'Progressive vampirecoast_ship_main_deck', 'Pirate Shipbuilding: Spar Deck'),
    50521: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_main_deck_2', ItemType.building, 1, 'Progressive vampirecoast_ship_main_deck', 'Pirate Shipbuilding: Upper Deck'),
    50522: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_main_deck_3', ItemType.building, 2, 'Progressive vampirecoast_ship_main_deck', 'Pirate Shipbuilding: Weather Deck'),
    50523: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_main_deck_4', ItemType.building, 3, 'Progressive vampirecoast_ship_main_deck', 'Pirate Shipbuilding: Main Deck'),
    50524: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_sail_1', ItemType.building, 0, 'Progressive vampirecoast_ship_sail', 'Pirate Shipbuilding: Topgallant Royal'),
    50525: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_sail_2', ItemType.building, 1, 'Progressive vampirecoast_ship_sail', 'Pirate Shipbuilding: Skysail'),
    50526: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_ship_sail_3', ItemType.building, 2, 'Progressive vampirecoast_ship_sail', 'Pirate Shipbuilding: Moonraker'),
    50527: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_artillery_1', ItemType.building, 0, 'Progressive vampirecoast_support_artillery', 'Pirate Building: Munitions Hut'),
    50528: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_artillery_2', ItemType.building, 1, 'Progressive vampirecoast_support_artillery', 'Pirate Building: Cannonry Shed'),
    50529: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_artillery_3', ItemType.building, 2, 'Progressive vampirecoast_support_artillery', 'Pirate Building: Black Powder Depot'),
    50530: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_monsters_1', ItemType.building, 0, 'Progressive vampirecoast_support_monsters', 'Pirate Building: Desolate Shoal'),
    50531: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_monsters_2', ItemType.building, 1, 'Progressive vampirecoast_support_monsters', 'Pirate Building: Mangrove of Monsters'),
    50532: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_monsters_3', ItemType.building, 2, 'Progressive vampirecoast_support_monsters', 'Pirate Building: Cape of Conjuring'),
    50533: ItemData(IC.useful, 1, 'wh2_dlc11_vampirecoast_support_necrofex_1', ItemType.building, 0, 'Progressive vampirecoast_support_necrofex', 'Pirate Building: Great Altar of the Necrarchs')
}

techs: dict[int, ItemData] = {
    50800: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_00', ItemType.tech, 1, 'Progressive tech_cst_command', 'Pirate Tech: Command Crews'),
    50801: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_05', ItemType.tech, 2, 'Progressive tech_cst_command', 'Pirate Tech: Dominion Over Mortals'),
    50802: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_04', ItemType.tech, 2, 'Progressive tech_cst_command', 'Pirate Tech: Foreign Architects'),
    50803: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_08', ItemType.tech, 2, 'Progressive tech_cst_command', 'Pirate Tech: Protection Racket'),
    50804: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_10', ItemType.tech, 2, 'Progressive tech_cst_command', 'Pirate Tech: Quartermaster'),
    50805: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_00', ItemType.tech, 3, 'Progressive tech_cst_command', 'Pirate Tech: The Pirate Code'),
    50806: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_01', ItemType.tech, 3, 'Progressive tech_cst_command', 'Pirate Tech: Hardened Pirate Scum'),
    50807: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_14', ItemType.tech, 3, 'Progressive tech_cst_command', 'Pirate Tech: Silver Musket-Balls & Cutlasses'),
    50808: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_11', ItemType.tech, 3, 'Progressive tech_cst_command', 'Pirate Tech: First Mate'),
    50809: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_01', ItemType.tech, 4, 'Progressive tech_cst_command', 'Pirate Tech: Serrated Harpoon'),
    50810: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_07', ItemType.tech, 4, 'Progressive tech_cst_command', "Pirate Tech: Marines' Upkeep"),
    50811: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_09', ItemType.tech, 4, 'Progressive tech_cst_command', 'Pirate Tech: Raise the Masses'),
    50812: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_12', ItemType.tech, 4, 'Progressive tech_cst_command', 'Pirate Tech: Seascape Artist'),
    50813: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_02', ItemType.tech, 5, 'Progressive tech_cst_command', 'Pirate Tech: The Converted'),
    50814: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_05', ItemType.tech, 5, 'Progressive tech_cst_command', 'Pirate Tech: Unliving Reflexes'),
    50815: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_03', ItemType.tech, 5, 'Progressive tech_cst_command', 'Pirate Tech: Centuries in Command'),
    50816: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_command_06', ItemType.tech, 5, 'Progressive tech_cst_command', 'Pirate Tech: Unliving Labour Force'),
    50817: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_admirals_00', ItemType.tech, 1, 'Progressive tech_cst_admirals', "Pirate Tech: Admirals' Astrolabes"),
    50818: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_admirals_01', ItemType.tech, 2, 'Progressive tech_cst_admirals', 'Pirate Tech: Disreputable Admiral'),
    50819: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_admirals_02', ItemType.tech, 2, 'Progressive tech_cst_admirals', 'Pirate Tech: Infamous Admiral'),
    50820: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_admirals_03', ItemType.tech, 2, 'Progressive tech_cst_admirals', 'Pirate Tech: Notorious Admiral'),
    50821: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_admirals_04', ItemType.tech, 2, 'Progressive tech_cst_admirals', 'Pirate Tech: Dread Admiral'),
    50822: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_00', ItemType.tech, 1, 'Progressive tech_cst_firepower', 'Pirate Tech: Gunnery Crews'),
    50823: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_01', ItemType.tech, 2, 'Progressive tech_cst_firepower', 'Pirate Tech: Maintained Cannons'),
    50824: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_04', ItemType.tech, 2, 'Progressive tech_cst_firepower', 'Pirate Tech: Clean Yer Bores!'),
    50825: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_13', ItemType.tech, 2, 'Progressive tech_cst_firepower', 'Pirate Tech: Black Powder Oxides'),
    50826: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_09', ItemType.tech, 2, 'Progressive tech_cst_firepower', 'Pirate Tech: Throwing-Bombs'),
    50827: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_06', ItemType.tech, 3, 'Progressive tech_cst_firepower', 'Pirate Tech: Stolen Imperial Ordnance'),
    50828: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_02', ItemType.tech, 3, 'Progressive tech_cst_firepower', 'Pirate Tech: Magazine'),
    50829: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_02', ItemType.tech, 3, 'Progressive tech_cst_firepower', 'Pirate Tech: Percussion Caps'),
    50830: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_07', ItemType.tech, 3, 'Progressive tech_cst_firepower', 'Pirate Tech: Powder Monkey'),
    50831: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_03', ItemType.tech, 4, 'Progressive tech_cst_firepower', 'Pirate Tech: Trained Gun Hands'),
    50832: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_05', ItemType.tech, 4, 'Progressive tech_cst_firepower', 'Pirate Tech: Steadier Aim'),
    50833: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_05', ItemType.tech, 4, 'Progressive tech_cst_firepower', 'Pirate Tech: Forged-Steel Shot'),
    50834: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_firearms_08', ItemType.tech, 4, 'Progressive tech_cst_firepower', 'Pirate Tech: Master Gunner'),
    50835: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_00', ItemType.tech, 1, 'Progressive tech_cst_salvage', 'Pirate Tech: Salvage Crews'),
    50836: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_01', ItemType.tech, 2, 'Progressive tech_cst_salvage', 'Pirate Tech: Corrupt the Land'),
    50837: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_04', ItemType.tech, 2, 'Progressive tech_cst_salvage', 'Pirate Tech: Efficient Necromancy'),
    50838: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_piracy_03', ItemType.tech, 2, 'Progressive tech_cst_salvage', 'Pirate Tech: Salvaged Arsenal'),
    50839: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_10', ItemType.tech, 2, 'Progressive tech_cst_salvage', "Pirate Tech: Spell of the Necromancer's Apprentice"),
    50840: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_02', ItemType.tech, 3, 'Progressive tech_cst_salvage', 'Pirate Tech: Supernatural Regeneration'),
    50841: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_07', ItemType.tech, 3, 'Progressive tech_cst_salvage', 'Pirate Tech: Protection from the Elements'),
    50842: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_06', ItemType.tech, 3, 'Progressive tech_cst_salvage', 'Pirate Tech: Protective Hide'),
    50843: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_11', ItemType.tech, 3, 'Progressive tech_cst_salvage', 'Pirate Tech: Skull & Crossbones'),
    50844: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_03', ItemType.tech, 4, 'Progressive tech_cst_salvage', 'Pirate Tech: Straining at the Leash'),
    50845: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_08', ItemType.tech, 4, 'Progressive tech_cst_salvage', 'Pirate Tech: Reinforced Carcasses'),
    50846: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_09', ItemType.tech, 4, 'Progressive tech_cst_salvage', 'Pirate Tech: Enduring Reanimation'),
    50847: ItemData(IC.useful, 1, 'wh2_dlc11_tech_cst_vampiric_12', ItemType.tech, 4, 'Progressive tech_cst_salvage', "Pirate Tech: Ship's Carpenter")
}

progUnits: dict[int, ItemData] = {
    51200: ItemData(IC.useful, 5, "Progressive cst_inf", ItemType.unit, 5, "", "Progressive Pirate Unit: Infantry"),
    51201: ItemData(IC.useful, 4, "Progressive cst_rng", ItemType.unit, 4, "", "Progressive Pirate Unit: Ranged"),
    51202: ItemData(IC.useful, 2, "Progressive cst_cav", ItemType.unit, 2, "", "Progressive Pirate Unit: Cavalry"),
    51203: ItemData(IC.useful, 3, "Progressive cst_art", ItemType.unit, 3, "", "Progressive Pirate Unit: Artillery"),
    51205: ItemData(IC.useful, 5, "Progressive cst_bst", ItemType.unit, 5, "", "Progressive Pirate Unit: Beast"),
    51206: ItemData(IC.useful, 1, "Progressive cst_hro", ItemType.unit, 1, "", "Progressive Pirate Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    51300: ItemData(IC.useful, 1, 'Progressive cst_resource_animals', ItemType.building, 1, None, 'Progressive Pirate Building: Animals'),
    51301: ItemData(IC.useful, 1, 'Progressive cst_resource_dyes', ItemType.building, 1, None, 'Progressive Pirate Building: Dyes'),
    51302: ItemData(IC.useful, 1, 'Progressive cst_resource_furs', ItemType.building, 1, None, 'Progressive Pirate Building: Furs'),
    51303: ItemData(IC.useful, 1, 'Progressive cst_resource_gems', ItemType.building, 1, None, 'Progressive Pirate Building: Gems'),
    51304: ItemData(IC.useful, 1, 'Progressive cst_resource_gold', ItemType.building, 1, None, 'Progressive Pirate Building: Gold'),
    51305: ItemData(IC.useful, 1, 'Progressive cst_resource_iron', ItemType.building, 1, None, 'Progressive Pirate Building: Iron'),
    51306: ItemData(IC.useful, 1, 'Progressive cst_resource_marble', ItemType.building, 1, None, 'Progressive Pirate Building: Marble'),
    51307: ItemData(IC.useful, 1, 'Progressive cst_resource_medicine', ItemType.building, 1, None, 'Progressive Pirate Building: Medicine'),
    51308: ItemData(IC.useful, 1, 'Progressive cst_resource_obsidian', ItemType.building, 1, None, 'Progressive Pirate Building: Obsidian'),
    51309: ItemData(IC.useful, 1, 'Progressive cst_resource_pasture', ItemType.building, 1, None, 'Progressive Pirate Building: Pasture'),
    51310: ItemData(IC.useful, 1, 'Progressive cst_resource_pottery', ItemType.building, 1, None, 'Progressive Pirate Building: Pottery'),
    51311: ItemData(IC.useful, 1, 'Progressive cst_resource_salt', ItemType.building, 1, None, 'Progressive Pirate Building: Salt'),
    51312: ItemData(IC.useful, 1, 'Progressive cst_resource_spices', ItemType.building, 1, None, 'Progressive Pirate Building: Spices'),
    51313: ItemData(IC.useful, 1, 'Progressive cst_resource_wine', ItemType.building, 1, None, 'Progressive Pirate Building: Wine'),
    51314: ItemData(IC.useful, 1, 'Progressive cst_resource_wood', ItemType.building, 1, None, 'Progressive Pirate Building: Wood'),
    51315: ItemData(IC.useful, 1, 'Progressive foreign_corruption', ItemType.building, 1, None, 'Progressive Pirate Building: Foreign Corruption'),
    51316: ItemData(IC.useful, 1, 'Progressive foreign_income', ItemType.building, 1, None, 'Progressive Pirate Building: Foreign Income'),
    51317: ItemData(IC.useful, 1, 'Progressive foreign_infamy', ItemType.building, 1, None, 'Progressive Pirate Building: Foreign Infamy'),
    51318: ItemData(IC.useful, 1, 'Progressive foreign_trade', ItemType.building, 1, None, 'Progressive Pirate Building: Foreign Trade'),
    51319: ItemData(IC.useful, 2, 'Progressive horde_def_aristocracy', ItemType.building, 2, None, 'Progressive Pirate Building: Horde Def Aristocracy'),
    51320: ItemData(IC.useful, 2, 'Progressive horde_def_exiles', ItemType.building, 2, None, 'Progressive Pirate Building: Horde Def Exiles'),
    51321: ItemData(IC.useful, 3, 'Progressive horde_def_residence', ItemType.building, 3, None, 'Progressive Pirate Building: Horde Def Residence'),
    51322: ItemData(IC.useful, 2, 'Progressive horde_def_riders', ItemType.building, 2, None, 'Progressive Pirate Building: Horde Def Riders'),
    51323: ItemData(IC.useful, 5, 'Progressive special_ship_harpoon', ItemType.building, 5, None, 'Progressive Pirate Building: Special Ship Harpoon'),
    51324: ItemData(IC.useful, 2, 'Progressive vampirecoast_defence_garrison', ItemType.building, 2, None, 'Progressive Pirate Building: Vampirecoast Defence Garrison'),
    51325: ItemData(IC.useful, 3, 'Progressive vampirecoast_defence_walls', ItemType.building, 3, None, 'Progressive Pirate Building: Vampirecoast Defence Walls'),
    51326: ItemData(IC.useful, 3, 'Progressive vampirecoast_infrastructure_corruption', ItemType.building, 3, None, 'Progressive Pirate Building: Infrastructure Corruption'),
    51327: ItemData(IC.useful, 2, 'Progressive vampirecoast_infrastructure_growth', ItemType.building, 2, None, 'Progressive Pirate Building: Infrastructure Growth'),
    51328: ItemData(IC.useful, 3, 'Progressive vampirecoast_infrastructure_growth', ItemType.building, 3, None, 'Progressive Pirate Building: Infrastructure Growth'),
    51329: ItemData(IC.useful, 2, 'Progressive vampirecoast_infrastructure_income', ItemType.building, 2, None, 'Progressive Pirate Building: Infrastructure Income'),
    51330: ItemData(IC.useful, 5, 'Progressive vampirecoast_infrastructure_income_other', ItemType.building, 5, None, 'Progressive Pirate Building: Infrastructure Income Other'),
    51331: ItemData(IC.useful, 3, 'Progressive vampirecoast_infrastructure_public_order', ItemType.building, 3, None, 'Progressive Pirate Building: Infrastructure Public Order'),
    51332: ItemData(IC.useful, 4, 'Progressive vampirecoast_military_barracks', ItemType.building, 4, None, 'Progressive Pirate Building: Military Barracks'),
    51333: ItemData(IC.useful, 4, 'Progressive vampirecoast_military_flying', ItemType.building, 4, None, 'Progressive Pirate Building: Military Flying'),
    51334: ItemData(IC.useful, 4, 'Progressive vampirecoast_military_ranged', ItemType.building, 4, None, 'Progressive Pirate Building: Military Ranged'),
    51335: ItemData(IC.useful, 3, 'Progressive vampirecoast_port', ItemType.building, 3, None, 'Progressive Pirate Building: Port'),
    51336: ItemData(IC.useful, 5, 'Progressive vampirecoast_settlement_major', ItemType.building, 5, None, 'Progressive Pirate Building: Settlement Major'),
    51337: ItemData(IC.useful, 3, 'Progressive vampirecoast_settlement_minor', ItemType.building, 3, None, 'Progressive Pirate Building: Settlement Minor'),
    51338: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_anchor', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding: Ship Anchor'),
    51339: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_cannons', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding: Ship Cannons'),
    51340: ItemData(IC.useful, 5, 'Progressive vampirecoast_ship_captains_cabin', ItemType.building, 5, None, 'Progressive Pirate Shipbuilding: Ship Captains Cabin'),
    51341: ItemData(IC.useful, 4, 'Progressive vampirecoast_ship_crows_nest', ItemType.building, 4, None, 'Progressive Pirate Shipbuilding: Ship Crows Nest'),
    51342: ItemData(IC.useful, 4, 'Progressive vampirecoast_ship_gunports', ItemType.building, 4, None, 'Progressive Pirate Shipbuilding: Ship Gunports'),
    51343: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_helm', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding:  Ship Helm'),
    51344: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_hold', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding: Ship Hold'),
    51345: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_hull', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding: Ship Hull'),
    51346: ItemData(IC.useful, 4, 'Progressive vampirecoast_ship_main_deck', ItemType.building, 4, None, 'Progressive Pirate Shipbuilding: Ship Main Deck'),
    51347: ItemData(IC.useful, 3, 'Progressive vampirecoast_ship_sail', ItemType.building, 3, None, 'Progressive Pirate Shipbuilding: Ship Sail'),
    51348: ItemData(IC.useful, 3, 'Progressive vampirecoast_support_artillery', ItemType.building, 3, None, 'Progressive Pirate Building: Support Artillery'),
    51349: ItemData(IC.useful, 3, 'Progressive vampirecoast_support_monsters', ItemType.building, 3, None, 'Progressive Pirate Building: Support Monsters'),
    51350: ItemData(IC.useful, 1, 'Progressive vampirecoast_support_necrofex', ItemType.building, 1, None, 'Progressive Pirate Building: Support Necrofex')
}

progTechs: dict[int, ItemData] = {
    51400: ItemData(IC.useful, 5, "Progressive tech_cst_command", ItemType.tech, 5, None, "Progressive Pirate Tech: Command"),
    51401: ItemData(IC.useful, 4, "Progressive tech_cst_firepower", ItemType.tech, 4, None, "Progressive Pirate Tech: Firepower"),
    51402: ItemData(IC.useful, 2, "Progressive tech_cst_admirals", ItemType.tech, 2, None, "Progressive Pirate Tech: Admirals"),
    51403: ItemData(IC.useful, 4, "Progressive tech_cst_salvage", ItemType.tech, 4, None, "Progressive Pirate Tech: Salvage"),
}

special: dict[int, specialItemData] = {
    51500: specialItemData(IC.useful, 1, 'wh2_dlc11_cst_pirates_of_sartosa', 'wh2_dlc11_cst_inf_sartosa_militia_0', ItemType.unit, 1, 'Progressive cst_inf', False, False, 'Pirate Unit: Sartosa Militia'),
    51501: specialItemData(IC.useful, 1, 'wh2_dlc11_cst_pirates_of_sartosa', 'wh2_dlc11_cst_inf_sartosa_free_company_0', ItemType.unit, 1, 'Progressive cst_rng', False, False, 'Pirate Unit: Sartosa Free Company'),
    51502: specialItemData(IC.useful, 1, 'wh2_dlc11_cst_pirates_of_sartosa', 'wh3_main_ogr_inf_maneaters_0', ItemType.unit, 3, 'Progressive cst_inf', False, False, 'Pirate Unit: Maneaters'),
    51503: specialItemData(IC.useful, 1, 'wh2_dlc11_cst_pirates_of_sartosa', 'wh3_main_ogr_inf_maneaters_3', ItemType.unit, 3, 'Progressive cst_rng', False, False, 'Pirate Unit: Maneaters (Ogre Pistols)'),
}

#
#