from BaseClasses import ItemClassification as IC
from worlds.tww3.item_types import ItemType, ItemData

# @formatter:off
units: dict[int, ItemData] = {
    52011: ItemData(IC.useful, 1, 'wh_main_vmp_inf_zombie', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: Zombies'),
    52012: ItemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_1', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: Skeleton Spearmen'),
    52013: ItemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_0', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: Skeleton Warriors'),
    52016: ItemData(IC.useful, 1, 'wh_main_vmp_inf_crypt_ghouls', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: Crypt Ghouls'),
    52015: ItemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_0', ItemType.unit, 2, 'Progressive vmp_inf', 'Vmp Unit: Grave Guard'),
    52000: ItemData(IC.useful, 1, 'wh3_main_vmp_inf_grave_guard_2', ItemType.unit, 2, 'Progressive vmp_inf', 'Vmp Unit: Grave Guard (Halberds)'),
    52014: ItemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_1', ItemType.unit, 2, 'Progressive vmp_inf', 'Vmp Unit: Grave Guard (Great Weapons)'),
    52017: ItemData(IC.useful, 1, 'wh_main_vmp_inf_cairn_wraiths', ItemType.unit, 2, 'Progressive vmp_inf', 'Vmp Unit: Cairn Wraiths'),

    52018: ItemData(IC.useful, 1, 'wh2_dlc11_vmp_inf_crossbowmen', ItemType.unit, 1, 'Progressive vmp_rng', 'Vmp Unit: Sylvanian Crossbowmen'),
    52019: ItemData(IC.useful, 1, 'wh2_dlc11_vmp_inf_handgunners', ItemType.unit, 1, 'Progressive vmp_rng', 'Vmp Unit: Sylvanian Handgunners'),

    52041: ItemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_0', ItemType.unit, 1, 'Progressive vmp_cav', 'Vmp Unit: Black Knights'),
    52040: ItemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_3', ItemType.unit, 2, 'Progressive vmp_cav', 'Vmp Unit: Black Knights (Lances & Barding)'),
    52039: ItemData(IC.useful, 1, 'wh_main_vmp_cav_hexwraiths', ItemType.unit, 2, 'Progressive vmp_cav', 'Vmp Unit: Hexwraiths'),
    52001: ItemData(IC.useful, 1, 'wh3_main_vmp_blood_knights_sword_shield', ItemType.unit, 3, 'Progressive vmp_cav', 'Vmp Unit: Blood Knights'),
    52002: ItemData(IC.useful, 1, 'wh_dlc02_vmp_cav_blood_knights_0', ItemType.unit, 3, 'Progressive vmp_cav', 'Vmp Unit: Blood Knights (Lances)'),

    52048: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_0', ItemType.unit, 1, 'Progressive vmp_veh', 'Vmp Unit: Corpse Cart'),
    52047: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_1', ItemType.unit, 2, 'Progressive vmp_veh', 'Vmp Unit: Corpse Cart (Balefire)'),
    52046: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_2', ItemType.unit, 3, 'Progressive vmp_veh', 'Vmp Unit: Corpse Cart (Unholy Lodestone)'),
    52004: ItemData(IC.useful, 1, 'wh_main_vmp_veh_black_coach', ItemType.unit, 3, 'Progressive vmp_veh', 'Vmp Unit: Black Coach'),
    52045: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_mortis_engine_0', ItemType.unit, 4, 'Progressive vmp_veh', 'Vmp Unit: Mortis Engine'),

    52008: ItemData(IC.useful, 1, 'wh_main_vmp_mon_fell_bats', ItemType.unit, 1, 'Progressive vmp_bst', 'Vmp Unit: Fell Bats'),
    52009: ItemData(IC.useful, 1, 'wh_main_vmp_mon_dire_wolves', ItemType.unit, 1, 'Progressive vmp_bst', 'Vmp Unit: Dire Wolves'),
    52010: ItemData(IC.useful, 1, 'wh_main_vmp_mon_crypt_horrors', ItemType.unit, 2, 'Progressive vmp_bst', 'Vmp Unit: Crypt Horrors'),
    52003: ItemData(IC.useful, 1, 'wh2_dlc11_vmp_mon_mournguls_0', ItemType.unit, 3, 'Progressive vmp_bst', 'Vmp Unit: Mournguls'),
    52006: ItemData(IC.useful, 1, 'wh_main_vmp_mon_vargheists', ItemType.unit, 3, 'Progressive vmp_bst', 'Vmp Unit: Vargheists'),
    52005: ItemData(IC.useful, 1, 'wh_main_vmp_mon_varghulf', ItemType.unit, 4, 'Progressive vmp_bst', 'Vmp Unit: Varghulf'),
    52007: ItemData(IC.useful, 1, 'wh_main_vmp_mon_terrorgheist', ItemType.unit, 5, 'Progressive vmp_bst', 'Vmp Unit: Terrorgheist'),

    52020: ItemData(IC.useful, 1, 'wh_main_vmp_cha_wight_king_0', ItemType.unit, 1, 'Progressive vmp_hro', 'Vmp Unit: Wight King'),
    52029: ItemData(IC.useful, 1, 'wh_main_vmp_cha_necromancer_0', ItemType.unit, 1, 'Progressive vmp_hro', 'Vmp Unit: Necromancer'),
    52038: ItemData(IC.useful, 1, 'wh_main_vmp_cha_banshee', ItemType.unit, 2, 'Progressive vmp_hro', 'Vmp Unit: Banshee'),
    52027: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_0', ItemType.unit, 3, 'Progressive vmp_hro', 'Vmp Unit: Vampire (Death)'),
    52044: ItemData(IC.useful, 1, 'wh_dlc05_vmp_cha_vampire_shadows_0', ItemType.unit, 3, 'Progressive vmp_hro', 'Vmp Unit: Vampire (Shadows)'),

    52049: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_claw_of_nagash_0', ItemType.unit, 4, 'Progressive vmp_veh', 'Vmp Unit: The Claw of Nagash (Mortis Engine)'),
    52050: ItemData(IC.useful, 1, 'wh_dlc04_vmp_mon_direpack_0', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: The Direpack (Dire Wolves)'),
    52051: ItemData(IC.useful, 1, 'wh_dlc04_vmp_mon_devils_swartzhafen_0', ItemType.unit, 3, 'Progressive vmp_inf', 'Vmp Unit: The Devils of Swartzhafen (Vargheists)'),
    52052: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_tithe_0', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: The Tithe (Zombies)'),
    52053: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_sternsmen_0', ItemType.unit, 2, 'Progressive vmp_inf', 'Vmp Unit: The Sternsmen (Grave Guard)'),
    52054: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_konigstein_stalkers_0', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: The Konigstein Stalkers (Skeleton Warriors)'),
    52055: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_feasters_in_the_dusk_0', ItemType.unit, 1, 'Progressive vmp_inf', 'Vmp Unit: The Feasters in the Dusk (Crypt Ghouls)'),
    52056: ItemData(IC.useful, 1, 'wh_dlc04_vmp_cav_vereks_reavers_0', ItemType.unit, 2, 'Progressive vmp_cav', "Vmp Unit: Verek's Reavers (Black Knights - Lances & Barding)"),
    52057: ItemData(IC.useful, 1, 'wh_dlc04_vmp_cav_chillgheists_0', ItemType.unit, 2, 'Progressive vmp_cav', 'Vmp Unit: The Chillgheists (Hexwraiths)'),
}

buildings: dict[int, ItemData] = {
    52400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_vmp', 'Vmp Building: Crypt Keepers'),
    52401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_vmp', 'Vmp Building: Undercroft Sentries'),
    52402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_vmp', 'Vmp Building: Grave Guardians'),
    52432: ItemData(IC.useful, 1, 'wh2_main_vmp_raisedead', ItemType.building, 0, 'Progressive vmp_battlefield', 'Vmp Building: Awakened Battlefield'),
    52433: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_1', ItemType.building, 0, 'Progressive vmp_resource_animals', 'Vmp Building: Exotic Animal Tamer'),
    52434: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_2', ItemType.building, 1, 'Progressive vmp_resource_animals', 'Vmp Building: Exotic Animal Pen'),
    52435: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_3', ItemType.building, 2, 'Progressive vmp_resource_animals', 'Vmp Building: Exotic Animal Market'),
    52436: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_1', ItemType.building, 0, 'Progressive vmp_resource_gemstones', 'Vmp Building: Cursed Gemstone Mineshaft'),
    52437: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_2', ItemType.building, 1, 'Progressive vmp_resource_gemstones', 'Vmp Building: Hexed Gemstone Pit'),
    52438: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_3', ItemType.building, 2, 'Progressive vmp_resource_gemstones', 'Vmp Building: Haunted Gemstone Mine'),
    52439: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_1', ItemType.building, 0, 'Progressive vmp_resource_medicine', "Vmp Building: Herb Gatherer's Camp"),
    52440: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_2', ItemType.building, 1, 'Progressive vmp_resource_medicine', 'Vmp Building: Exotic Hothouse'),
    52441: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_3', ItemType.building, 2, 'Progressive vmp_resource_medicine', 'Vmp Building: Alchemy Workshop'),
    52442: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_1', ItemType.building, 0, 'Progressive vmp_resource_obsidian', 'Vmp Building: Obsidian Quarry'),
    52443: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_2', ItemType.building, 1, 'Progressive vmp_resource_obsidian', 'Vmp Building: Obsidian Trinket Maker'),
    52444: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_3', ItemType.building, 2, 'Progressive vmp_resource_obsidian', 'Vmp Building: Obsidian Amulet Carver'),
    52445: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_1', ItemType.building, 0, 'Progressive vmp_resource_spices', 'Vmp Building: Spice Market'),
    52446: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_2', ItemType.building, 1, 'Progressive vmp_resource_spices', 'Vmp Building: Spice Trading Post'),
    52447: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_3', ItemType.building, 2, 'Progressive vmp_resource_spices', 'Vmp Building: Eastern Bazaar'),
    52448: ItemData(IC.useful, 1, 'wh2_main_vmp_terrorgheists_1', ItemType.building, 0, 'Progressive vmp_terrorgheists', 'Vmp Building: Terrorgheist Lair'),
    52449: ItemData(IC.useful, 1, 'wh2_main_vmp_wraiths_1', ItemType.building, 0, 'Progressive vmp_wraiths', 'Vmp Building: Spirit Well'),
    52450: ItemData(IC.useful, 1, 'wh2_main_vmp_wraiths_2', ItemType.building, 1, 'Progressive vmp_wraiths', 'Vmp Building: Font of Nightmares'),
    52451: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_1', ItemType.building, 0, 'Progressive vmp_allied_outpost', 'Vmp Building: Undead Outpost'),
    52452: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_2', ItemType.building, 1, 'Progressive vmp_allied_outpost', 'Vmp Building: Undead District'),
    52453: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_3', ItemType.building, 2, 'Progressive vmp_allied_outpost', 'Vmp Building: Undead Colony'),
    52454: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_1', ItemType.building, 0, 'Progressive vmp_resource_ivory', 'Vmp Building: Animal Store'),
    52455: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_2', ItemType.building, 1, 'Progressive vmp_resource_ivory', 'Vmp Building: Tusk Market'),
    52456: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_3', ItemType.building, 2, 'Progressive vmp_resource_ivory', 'Vmp Building: Tusk Compound'),
    52457: ItemData(IC.useful, 1, 'wh_main_vmp_armoury_1', ItemType.building, 0, 'Progressive vmp_armoury', 'Vmp Building: Ancient Armoury'),
    52458: ItemData(IC.useful, 1, 'wh_main_vmp_armoury_2', ItemType.building, 1, 'Progressive vmp_armoury', 'Vmp Building: Reliquary'),
    52459: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_1', ItemType.building, 0, 'Progressive vmp_balefire', 'Vmp Building: Balefire Brazier'),
    52460: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_2', ItemType.building, 1, 'Progressive vmp_balefire', 'Vmp Building: Balefire Hearth'),
    52461: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_3', ItemType.building, 2, 'Progressive vmp_balefire', 'Vmp Building: Witch House'),
    52462: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_1', ItemType.building, 0, 'Progressive vmp_bindingcircle', 'Vmp Building: Defiled Cairn'),
    52463: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_2', ItemType.building, 1, 'Progressive vmp_bindingcircle', 'Vmp Building: Binding Circle'),
    52464: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_3', ItemType.building, 2, 'Progressive vmp_bindingcircle', 'Vmp Building: Lodestone of Darkness'),
    52465: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_2', ItemType.building, 0, 'Progressive vmp_cemetary', 'Vmp Building: Barrow'),
    52466: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_2', ItemType.building, 0, 'Progressive vmp_cemetary', 'Vmp Building: Barrow'),
    52467: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_3', ItemType.building, 1, 'Progressive vmp_cemetary', 'Vmp Building: Mausoleum'),
    52468: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_3', ItemType.building, 1, 'Progressive vmp_cemetary', 'Vmp Building: Mausoleum'),
    52469: ItemData(IC.useful, 1, 'wh_main_vmp_forest_1', ItemType.building, 0, 'Progressive vmp_forest', 'Vmp Building: Sinister Copse'),
    52470: ItemData(IC.useful, 1, 'wh_main_vmp_forest_2', ItemType.building, 1, 'Progressive vmp_forest', 'Vmp Building: Abyssal Wood'),
    52471: ItemData(IC.useful, 1, 'wh_main_vmp_forest_3', ItemType.building, 2, 'Progressive vmp_forest', 'Vmp Building: Sepulchral Grove'),
    52472: ItemData(IC.useful, 1, 'wh_main_vmp_garrison_1', ItemType.building, 0, 'Progressive vmp_garrison', 'Vmp Building: Corpse Pile'),
    52473: ItemData(IC.useful, 1, 'wh_main_vmp_garrison_2', ItemType.building, 1, 'Progressive vmp_garrison', 'Vmp Building: Grave Guard Watchtower'),
    52474: ItemData(IC.useful, 1, 'wh_main_vmp_necromancers_1', ItemType.building, 0, 'Progressive vmp_necromancers', 'Vmp Building: Forbidden Library'),
    52475: ItemData(IC.useful, 1, 'wh_main_vmp_necromancers_2', ItemType.building, 1, 'Progressive vmp_necromancers', "Vmp Building: Necromancer's Tower"),
    52476: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_1', ItemType.building, 0, 'Progressive vmp_boneyard', 'Vmp Building: Charnel Pit'),
    52477: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_2', ItemType.building, 1, 'Progressive vmp_boneyard', 'Vmp Building: Lychyard'),
    52478: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_3', ItemType.building, 2, 'Progressive vmp_boneyard', 'Vmp Building: Ossuary'),
    52479: ItemData(IC.useful, 1, 'wh_main_vmp_port_1', ItemType.building, 0, 'Progressive vmp_port', 'Vmp Building: Crumbling Wharf'),
    52480: ItemData(IC.useful, 1, 'wh_main_vmp_port_2', ItemType.building, 1, 'Progressive vmp_port', 'Vmp Building: Murky Harbour'),
    52481: ItemData(IC.useful, 1, 'wh_main_vmp_port_3', ItemType.building, 2, 'Progressive vmp_port', 'Vmp Building: Dark Port'),
    52482: ItemData(IC.useful, 1, 'wh_main_vmp_repression_1', ItemType.building, 0, 'Progressive vmp_repression', 'Vmp Building: Gibbet'),
    52483: ItemData(IC.useful, 1, 'wh_main_vmp_repression_2', ItemType.building, 1, 'Progressive vmp_repression', 'Vmp Building: Gallows'),
    52484: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_1', ItemType.building, 0, 'Progressive vmp_resource_dyes', 'Vmp Building: Red Pit'),
    52485: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_2', ItemType.building, 1, 'Progressive vmp_resource_dyes', 'Vmp Building: Blood Mines'),
    52486: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_3', ItemType.building, 2, 'Progressive vmp_resource_dyes', "Vmp Building: Pigment Grinder's Shop"),
    52487: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_1', ItemType.building, 0, 'Progressive vmp_resource_furs', 'Vmp Building: Hunting Grounds'),
    52488: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_2', ItemType.building, 1, 'Progressive vmp_resource_furs', 'Vmp Building: Poaching Camp'),
    52489: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_3', ItemType.building, 2, 'Progressive vmp_resource_furs', "Vmp Building: Flayer's Lair"),
    52490: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_1', ItemType.building, 0, 'Progressive vmp_resource_gold', 'Vmp Building: Tarnished Gold Shaft'),
    52491: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_2', ItemType.building, 1, 'Progressive vmp_resource_gold', 'Vmp Building: Tarnished Gold Mine'),
    52492: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_3', ItemType.building, 2, 'Progressive vmp_resource_gold', 'Vmp Building: Balefire Gold Smeltery'),
    52493: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_1', ItemType.building, 0, 'Progressive vmp_resource_iron', 'Vmp Building: Dark Iron Pit'),
    52494: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_2', ItemType.building, 1, 'Progressive vmp_resource_iron', 'Vmp Building: Zombie-Infested Iron Mine'),
    52495: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_3', ItemType.building, 2, 'Progressive vmp_resource_iron', 'Vmp Building: Scoured Iron Mine'),
    52497: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_1', ItemType.building, 0, 'Progressive vmp_resource_marble', "Vmp Building: Brimstone Cutter's Workshop"),
    52498: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_2', ItemType.building, 1, 'Progressive vmp_resource_marble', "Vmp Building: Tombstone Maker's Atelier"),
    52499: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_3', ItemType.building, 2, 'Progressive vmp_resource_marble', "Vmp Building: Gargoyle Sculptor's Garret"),
    52500: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_1', ItemType.building, 0, 'Progressive vmp_resource_pastures', 'Vmp Building: Cursed Fields'),
    52501: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_2', ItemType.building, 1, 'Progressive vmp_resource_pastures', 'Vmp Building: Wretched Farmstead'),
    52502: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_3', ItemType.building, 2, 'Progressive vmp_resource_pastures', 'Vmp Building: Haunted Mill'),
    52504: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_1', ItemType.building, 0, 'Progressive vmp_resource_pottery', 'Vmp Building: Flooded Clay Pit'),
    52505: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_2', ItemType.building, 1, 'Progressive vmp_resource_pottery', "Vmp Building: Urn Maker's Pottery"),
    52506: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_3', ItemType.building, 2, 'Progressive vmp_resource_pottery', 'Vmp Building: Screeching Kilns'),
    52507: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_1', ItemType.building, 0, 'Progressive vmp_resource_salt', 'Vmp Building: Brackish Pond'),
    52508: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_2', ItemType.building, 1, 'Progressive vmp_resource_salt', 'Vmp Building: Salt Marsh'),
    52509: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_3', ItemType.building, 2, 'Progressive vmp_resource_salt', 'Vmp Building: Desolate Salt Pans'),
    52510: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_1', ItemType.building, 0, 'Progressive vmp_resource_timber', "Vmp Building: Forester's Shack"),
    52511: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_2', ItemType.building, 1, 'Progressive vmp_resource_timber', 'Vmp Building: Ruined Sawmill'),
    52512: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_3', ItemType.building, 2, 'Progressive vmp_resource_timber', 'Vmp Building: Abandoned Wood Sheds'),
    52513: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_1', ItemType.building, 0, 'Progressive vmp_resource_wine', 'Vmp Building: Tangled Vine Patch'),
    52514: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_2', ItemType.building, 1, 'Progressive vmp_resource_wine', 'Vmp Building: Thorny Orchard'),
    52515: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_3', ItemType.building, 2, 'Progressive vmp_resource_wine', 'Vmp Building: Animated Winepress'),
    52516: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_1', ItemType.building, 0, 'Progressive vmp_settlement_major', 'Vmp Building: Crumbling Hamlet'),
    52518: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_2', ItemType.building, 1, 'Progressive vmp_settlement_major', 'Vmp Building: Corrupted Village'),
    52520: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_3', ItemType.building, 2, 'Progressive vmp_settlement_major', 'Vmp Building: Shady Township'),
    52522: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_4', ItemType.building, 3, 'Progressive vmp_settlement_major', 'Vmp Building: Accursed City'),
    52524: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_5', ItemType.building, 4, 'Progressive vmp_settlement_major', 'Vmp Building: Dark Castle'),
    52526: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_1', ItemType.building, 0, 'Progressive vmp_settlement_minor', 'Vmp Building: Crumbling Hamlet'),
    52528: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_2', ItemType.building, 1, 'Progressive vmp_settlement_minor', 'Vmp Building: Corrupted Village'),
    52530: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_3', ItemType.building, 2, 'Progressive vmp_settlement_minor', 'Vmp Building: Shady Township'),
    52532: ItemData(IC.useful, 1, 'wh_main_vmp_vampires_1', ItemType.building, 0, 'Progressive vmp_vampires', 'Vmp Building: Vampire Crypts'),
    52533: ItemData(IC.useful, 1, 'wh_main_vmp_vampires_2', ItemType.building, 1, 'Progressive vmp_vampires', "Vmp Building: Vampire's Keep"),
    52534: ItemData(IC.useful, 1, 'wh_main_vmp_walls_1', ItemType.building, 0, 'Progressive vmp_walls', 'Vmp Building: Ghost Fence'),
    52535: ItemData(IC.useful, 1, 'wh_main_vmp_walls_2', ItemType.building, 1, 'Progressive vmp_walls', 'Vmp Building: Skeletal Walls'),
    52536: ItemData(IC.useful, 1, 'wh_main_vmp_walls_3', ItemType.building, 2, 'Progressive vmp_walls', 'Vmp Building: Blasphemous Bulwark')
}

techs: dict[int, ItemData] = {
    52803: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_01', ItemType.tech, 1, 'Progressive tech_vmp_beasts', "Vmp Tech: De Noirot's Blasphemous Bestiary"),
    52804: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_02', ItemType.tech, 2, 'Progressive tech_vmp_beasts', 'Vmp Tech: Corruptor of the Forests'),
    52805: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_04', ItemType.tech, 3, 'Progressive tech_vmp_beasts', 'Vmp Tech: Leader of the Pack'),
    52806: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_06', ItemType.tech, 4, 'Progressive tech_vmp_beasts', 'Vmp Tech: Beastmaster'),
    52800: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_05', ItemType.tech, 4, 'Progressive tech_vmp_beasts', 'Vmp Tech: Invoke Animalistic Hunger'),
    52807: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_08', ItemType.tech, 5, 'Progressive tech_vmp_beasts', 'Vmp Tech: Fresh Prey Supply'),
    52808: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_09', ItemType.tech, 6, 'Progressive tech_vmp_beasts', 'Vmp Tech: Fuelled by Fear'),
    52813: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_03', ItemType.tech, 3, 'Progressive tech_vmp_beasts', 'Vmp Tech: Master of the Swarm'),
    52814: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_07', ItemType.tech, 5, 'Progressive tech_vmp_beasts', 'Vmp Tech: Blood Hunts'),

    52809: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_01', ItemType.tech, 1, 'Progressive tech_vmp_bones', 'Vmp Tech: The Book of Arkhan'),
    52810: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_02', ItemType.tech, 2, 'Progressive tech_vmp_bones', 'Vmp Tech: Raise Newly Dead'),
    52811: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_05', ItemType.tech, 3, 'Progressive tech_vmp_bones', 'Vmp Tech: Bond of Bones'),
    52812: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_08', ItemType.tech, 4, 'Progressive tech_vmp_bones', 'Vmp Tech: Risen Champions'),
    52815: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_03', ItemType.tech, 3, 'Progressive tech_vmp_bones', 'Vmp Tech: Bonds of Flesh'),
    52816: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_06', ItemType.tech, 4, 'Progressive tech_vmp_bones', 'Vmp Tech: Distribute Grave Gift'),
    52817: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_09', ItemType.tech, 5, 'Progressive tech_vmp_bones', 'Vmp Tech: Unearth Cursed Wightblades'),
    52818: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_04', ItemType.tech, 4, 'Progressive tech_vmp_bones', 'Vmp Tech: Rotten Gift'),
    52819: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_07', ItemType.tech, 5, 'Progressive tech_vmp_bones', 'Vmp Tech: Defiler of the Ancient Barrows'),
    52820: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_10', ItemType.tech, 6, 'Progressive tech_vmp_bones', 'Vmp Tech: Dread Animator'),
    52821: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_04a', ItemType.tech, 5, 'Progressive tech_vmp_bones', 'Vmp Tech: Master of the Putrid Horde'),
    52801: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_02a', ItemType.tech, 3, 'Progressive tech_vmp_bones', 'Vmp Tech: Risen Standard Bearers'),
    52802: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_05a', ItemType.tech, 4, 'Progressive tech_vmp_bones', 'Vmp Tech: Unnatural Strength'),

    52829: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_01', ItemType.tech, 1, 'Progressive tech_vmp_binding', 'Vmp Tech: Liber Necronomica'),
    52830: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_02', ItemType.tech, 2, 'Progressive tech_vmp_binding', 'Vmp Tech: Incantations of Ushoran'),
    52831: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_05', ItemType.tech, 3, 'Progressive tech_vmp_binding', 'Vmp Tech: Infuse the Tireless Hordes'),
    52832: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_08', ItemType.tech, 4, 'Progressive tech_vmp_binding', 'Vmp Tech: Unliving Siege Engines'),
    52839: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_04', ItemType.tech, 3, 'Progressive tech_vmp_binding', 'Vmp Tech: Soulbinder'),
    52840: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_07', ItemType.tech, 4, 'Progressive tech_vmp_binding', 'Vmp Tech: Nightmarish Reaping'),
    52841: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_10', ItemType.tech, 5, 'Progressive tech_vmp_binding', 'Vmp Tech: Spirit Shackles'),
    52822: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_06', ItemType.tech, 3, 'Progressive tech_vmp_binding', 'Vmp Tech: Strigoi Legacy'),
    52823: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_03', ItemType.tech, 4, 'Progressive tech_vmp_binding', 'Vmp Tech: Cannibalistic Rituals'),
    52824: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_09', ItemType.tech, 5, 'Progressive tech_vmp_binding', 'Vmp Tech: Enshrine Ancient Lords'),

    52833: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_01', ItemType.tech, 1, 'Progressive tech_vmp_blood', 'Vmp Tech: The Lahmian Book of Blood'),
    52834: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_02', ItemType.tech, 2, 'Progressive tech_vmp_blood', 'Vmp Tech: Serve in Life or in Death'),
    52835: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_03', ItemType.tech, 3, 'Progressive tech_vmp_blood', 'Vmp Tech: Baleful Rituals'),
    52836: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_06', ItemType.tech, 4, 'Progressive tech_vmp_blood', 'Vmp Tech: Spread Vampire Covens'),
    52837: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_08', ItemType.tech, 5, 'Progressive tech_vmp_blood', 'Vmp Tech: Blasphemous Disciples'),
    52838: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_11', ItemType.tech, 6, 'Progressive tech_vmp_blood', 'Vmp Tech: Puppet Master'),
    52842: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_05', ItemType.tech, 4, 'Progressive tech_vmp_blood', 'Vmp Tech: Hexensnacht Sacrifices'),
    52843: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_07', ItemType.tech, 5, 'Progressive tech_vmp_blood', 'Vmp Tech: Infiltrate Noble Houses'),
    52844: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_10', ItemType.tech, 6, 'Progressive tech_vmp_blood', 'Vmp Tech: Decipher Nehekhara Manuscripts'),
    52845: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_12', ItemType.tech, 7, 'Progressive tech_vmp_blood', 'Vmp Tech: Incantations of Nagash'),
    52825: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_04', ItemType.tech, 3, 'Progressive tech_vmp_blood', 'Vmp Tech: Blood is Power'),
    52826: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_06A', ItemType.tech, 4, 'Progressive tech_vmp_blood', 'Vmp Tech: Turning Knightly Orders'),
    52827: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_09', ItemType.tech, 6, 'Progressive tech_vmp_blood', 'Vmp Tech: Vampiric Revivification'),
    52828: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_09A', ItemType.tech, 7, 'Progressive tech_vmp_blood', 'Vmp Tech: Delusions of Grandeur'),
}

progUnits: dict[int, ItemData] = {
    53200: ItemData(IC.useful, 2, 'Progressive vmp_inf', ItemType.unit, 2, None, 'Progressive Vmp Unit: Infantry'),
    53201: ItemData(IC.useful, 1, 'Progressive vmp_rng', ItemType.unit, 1, None, 'Progressive Vmp Unit: Ranged'),
    53202: ItemData(IC.useful, 3, 'Progressive vmp_cav', ItemType.unit, 3, None, 'Progressive Vmp Unit: Cavalry'),
    53204: ItemData(IC.useful, 4, 'Progressive vmp_veh', ItemType.unit, 4, None, 'Progressive Vmp Unit: Chariot'),
    53205: ItemData(IC.useful, 5, 'Progressive vmp_bst', ItemType.unit, 5, None, 'Progressive Vmp Unit: Beast'),
    53206: ItemData(IC.useful, 3, 'Progressive vmp_hro', ItemType.unit, 3, None, 'Progressive Vmp Unit: Hero'),
}

progBuildings: dict[int, ItemData] = {
    23400: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_vmp', ItemType.building, 3, None, 'Progressive Vmp Building: Foreign Slot Discovery Vmp'),
    23401: ItemData(IC.useful, 1, 'Progressive vmp_battlefield', ItemType.building, 1, None, 'Progressive Vmp Building: Battlefield'),
    23402: ItemData(IC.useful, 3, 'Progressive vmp_resource_animals', ItemType.building, 3, None, 'Progressive Vmp Building: Animals'),
    23403: ItemData(IC.useful, 3, 'Progressive vmp_resource_gemstones', ItemType.building, 3, None, 'Progressive Vmp Building: Gemstones'),
    23404: ItemData(IC.useful, 3, 'Progressive vmp_resource_medicine', ItemType.building, 3, None, 'Progressive Vmp Building: Medicine'),
    23405: ItemData(IC.useful, 3, 'Progressive vmp_resource_obsidian', ItemType.building, 3, None, 'Progressive Vmp Building: Obsidian'),
    23406: ItemData(IC.useful, 3, 'Progressive vmp_resource_spices', ItemType.building, 3, None, 'Progressive Vmp Building: Spices'),
    23407: ItemData(IC.useful, 1, 'Progressive vmp_terrorgheists', ItemType.building, 1, None, 'Progressive Vmp Building: Terrorgheists'),
    23408: ItemData(IC.useful, 2, 'Progressive vmp_wraiths', ItemType.building, 2, None, 'Progressive Vmp Building: Wraiths'),
    23409: ItemData(IC.useful, 3, 'Progressive vmp_allied_outpost', ItemType.building, 3, None, 'Progressive Vmp Building: Allied Outpost'),
    23410: ItemData(IC.useful, 3, 'Progressive vmp_resource_ivory', ItemType.building, 3, None, 'Progressive Vmp Building: Ivory'),
    23411: ItemData(IC.useful, 2, 'Progressive vmp_armoury', ItemType.building, 2, None, 'Progressive Vmp Building: Armoury'),
    23412: ItemData(IC.useful, 3, 'Progressive vmp_balefire', ItemType.building, 3, None, 'Progressive Vmp Building: Balefire'),
    23413: ItemData(IC.useful, 3, 'Progressive vmp_bindingcircle', ItemType.building, 3, None, 'Progressive Vmp Building: Bindingcircle'),
    23414: ItemData(IC.useful, 2, 'Progressive vmp_cemetary', ItemType.building, 2, None, 'Progressive Vmp Building: Cemetary'),
    23415: ItemData(IC.useful, 3, 'Progressive vmp_forest', ItemType.building, 3, None, 'Progressive Vmp Building: Forest'),
    23416: ItemData(IC.useful, 2, 'Progressive vmp_garrison', ItemType.building, 2, None, 'Progressive Vmp Building: Garrison'),
    23417: ItemData(IC.useful, 2, 'Progressive vmp_necromancers', ItemType.building, 2, None, 'Progressive Vmp Building: Necromancers'),
    23418: ItemData(IC.useful, 3, 'Progressive vmp_boneyard', ItemType.building, 3, None, 'Progressive Vmp Building: Boneyard'),
    23419: ItemData(IC.useful, 3, 'Progressive vmp_port', ItemType.building, 3, None, 'Progressive Vmp Building: Port'),
    23420: ItemData(IC.useful, 2, 'Progressive vmp_repression', ItemType.building, 2, None, 'Progressive Vmp Building: Repression'),
    23421: ItemData(IC.useful, 3, 'Progressive vmp_resource_dyes', ItemType.building, 3, None, 'Progressive Vmp Building: Dyes'),
    23422: ItemData(IC.useful, 3, 'Progressive vmp_resource_furs', ItemType.building, 3, None, 'Progressive Vmp Building: Furs'),
    23423: ItemData(IC.useful, 3, 'Progressive vmp_resource_gold', ItemType.building, 3, None, 'Progressive Vmp Building: Gold'),
    23424: ItemData(IC.useful, 3, 'Progressive vmp_resource_iron', ItemType.building, 3, None, 'Progressive Vmp Building: Iron'),
    23425: ItemData(IC.useful, 3, 'Progressive vmp_resource_marble', ItemType.building, 3, None, 'Progressive Vmp Building: Marble'),
    23426: ItemData(IC.useful, 3, 'Progressive vmp_resource_pastures', ItemType.building, 3, None, 'Progressive Vmp Building: Pastures'),
    23427: ItemData(IC.useful, 3, 'Progressive vmp_resource_pottery', ItemType.building, 3, None, 'Progressive Vmp Building: Pottery'),
    23428: ItemData(IC.useful, 3, 'Progressive vmp_resource_salt', ItemType.building, 3, None, 'Progressive Vmp Building: Salt'),
    23429: ItemData(IC.useful, 3, 'Progressive vmp_resource_timber', ItemType.building, 3, None, 'Progressive Vmp Building: Timber'),
    23430: ItemData(IC.useful, 3, 'Progressive vmp_resource_wine', ItemType.building, 3, None, 'Progressive Vmp Building: Wine'),
    23431: ItemData(IC.useful, 5, 'Progressive vmp_settlement_major', ItemType.building, 5, None, 'Progressive Vmp Building: Settlement Major'),
    23432: ItemData(IC.useful, 3, 'Progressive vmp_settlement_minor', ItemType.building, 3, None, 'Progressive Vmp Building: Settlement Minor'),
    23433: ItemData(IC.useful, 2, 'Progressive vmp_vampires', ItemType.building, 2, None, 'Progressive Vmp Building: Vampires'),
    23434: ItemData(IC.useful, 3, 'Progressive vmp_walls', ItemType.building, 3, None, 'Progressive Vmp Building: Walls')
}

progTechs: dict[int, ItemData] = {
    53400: ItemData(IC.useful, 6, "Progressive tech_vmp_beasts", ItemType.tech, 6, None, "Progressive Vmp Tech: Beasts"),
    53401: ItemData(IC.useful, 6, "Progressive tech_vmp_bones", ItemType.tech, 6, None, "Progressive Vmp Tech: Bones"),
    53402: ItemData(IC.useful, 5, "Progressive tech_vmp_binding", ItemType.tech, 5, None, "Progressive Vmp Tech: Binding"),
    53403: ItemData(IC.useful, 7, "Progressive tech_vmp_blood", ItemType.tech, 7, None, "Progressive Vmp Tech: Blood"),
}

special: dict[int, ItemData] = {

}