from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    52000: ItemData(IC.useful, 1, 'wh3_main_vmp_inf_grave_guard_2', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Grave Guard (Halberds)'),
    52001: ItemData(IC.useful, 1, 'wh3_main_vmp_blood_knights_sword_shield', ItemType.unit, 4, 'cavalry', 'Cst Unit: Blood Knights'),
    52002: ItemData(IC.useful, 1, 'wh2_dlc11_vmp_cha_heinrich_kemmler_1', ItemType.unit, 0, 'cavalry', 'Cst Unit: Heinrich Kemmler'),
    52003: ItemData(IC.useful, 1, 'wh2_dlc11_cst_mon_mournguls_0', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Mournguls'),
    52004: ItemData(IC.useful, 1, 'wh_main_vmp_veh_black_coach', ItemType.unit, 3, 'Progressive cst_veh', 'Cst Unit: Black Coach'),
    52005: ItemData(IC.useful, 1, 'wh_main_vmp_mon_varghulf', ItemType.unit, 3, 'Progressive cst_inf', 'Cst Unit: Varghulf'),
    52006: ItemData(IC.useful, 1, 'wh_main_vmp_mon_vargheists', ItemType.unit, 3, 'Progressive cst_inf', 'Cst Unit: Vargheists'),
    52007: ItemData(IC.useful, 1, 'wh_main_vmp_mon_terrorgheist', ItemType.unit, 5, 'Progressive cst_inf', 'Cst Unit: Terrorgheist'),
    52008: ItemData(IC.useful, 1, 'wh_main_vmp_mon_fell_bats', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: Fell Bats'),
    52009: ItemData(IC.useful, 1, 'wh_main_vmp_mon_dire_wolves', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Dire Wolves'),
    52010: ItemData(IC.useful, 1, 'wh_main_vmp_mon_crypt_horrors', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Crypt Horrors'),
    52011: ItemData(IC.useful, 1, 'wh_main_vmp_inf_zombie', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: Zombies'),
    52012: ItemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_1', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: Skeleton Spearmen'),
    52013: ItemData(IC.useful, 1, 'wh_main_vmp_inf_skeleton_warriors_0', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: Skeleton Warriors'),
    52014: ItemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_1', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Grave Guard (Great Weapons)'),
    52015: ItemData(IC.useful, 1, 'wh_main_vmp_inf_grave_guard_0', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Grave Guard'),
    52016: ItemData(IC.useful, 1, 'wh_main_vmp_inf_crypt_ghouls', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Crypt Ghouls'),
    52017: ItemData(IC.useful, 1, 'wh_main_vmp_inf_cairn_wraiths', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: Cairn Wraiths'),
    52018: ItemData(IC.useful, 1, 'wh_main_vmp_cha_wight_king_2', ItemType.unit, 0, 'cavalry', 'Cst Unit: Wight King'),
    52019: ItemData(IC.useful, 1, 'wh_main_vmp_cha_wight_king_1', ItemType.unit, 0, 'cavalry', 'Cst Unit: Wight King'),
    52020: ItemData(IC.useful, 1, 'wh_main_vmp_cha_wight_king_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Wight King'),
    52021: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_lord_5', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire Lord'),
    52022: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_lord_3', ItemType.unit, 0, 'war_beast', 'Cst Unit: Vampire Lord'),
    52023: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_lord_2', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire Lord'),
    52024: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_lord_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Vampire Lord'),
    52025: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_2', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire (Death)'),
    52026: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_1', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire (Death)'),
    52027: ItemData(IC.useful, 1, 'wh_main_vmp_cha_vampire_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Vampire (Death)'),
    52028: ItemData(IC.useful, 1, 'wh_main_vmp_cha_necromancer_5', ItemType.unit, 0, 'cavalry', 'Cst Unit: Necromancer'),
    52029: ItemData(IC.useful, 1, 'wh_main_vmp_cha_necromancer_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Necromancer'),
    52030: ItemData(IC.useful, 1, 'wh_main_vmp_cha_master_necromancer_5', ItemType.unit, 0, 'cavalry', 'Cst Unit: Master Necromancer'),
    52031: ItemData(IC.useful, 1, 'wh_main_vmp_cha_master_necromancer_4', ItemType.unit, 0, 'cavalry', 'Cst Unit: Master Necromancer'),
    52032: ItemData(IC.useful, 1, 'wh_main_vmp_cha_master_necromancer_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Master Necromancer'),
    52033: ItemData(IC.useful, 1, 'wh_main_vmp_cha_mannfred_von_carstein_4', ItemType.unit, 0, 'cavalry', 'Cst Unit: Mannfred von Carstein'),
    52034: ItemData(IC.useful, 1, 'wh_main_vmp_cha_mannfred_von_carstein_3', ItemType.unit, 0, 'war_beast', 'Cst Unit: Mannfred von Carstein'),
    52035: ItemData(IC.useful, 1, 'wh_main_vmp_cha_mannfred_von_carstein_2', ItemType.unit, 0, 'cavalry', 'Cst Unit: Mannfred von Carstein'),
    52036: ItemData(IC.useful, 1, 'wh_main_vmp_cha_mannfred_von_carstein_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Mannfred von Carstein'),
    52037: ItemData(IC.useful, 1, 'wh_main_vmp_cha_heinrich_kemmler', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Heinrich Kemmler'),
    52038: ItemData(IC.useful, 1, 'wh_main_vmp_cha_banshee', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Banshee'),
    52039: ItemData(IC.useful, 1, 'wh_main_vmp_cav_hexwraiths', ItemType.unit, 3, 'cavalry', 'Cst Unit: Hexwraiths'),
    52040: ItemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_3', ItemType.unit, 3, 'cavalry', 'Cst Unit: Black Knights (Lances & Barding)'),
    52041: ItemData(IC.useful, 1, 'wh_main_vmp_cav_black_knights_0', ItemType.unit, 3, 'cavalry', 'Cst Unit: Black Knights'),
    52042: ItemData(IC.useful, 1, 'wh_dlc05_vmp_cha_vampire_shadows_2', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire (Shadows)'),
    52043: ItemData(IC.useful, 1, 'wh_dlc05_vmp_cha_vampire_shadows_1', ItemType.unit, 0, 'cavalry', 'Cst Unit: Vampire (Shadows)'),
    52044: ItemData(IC.useful, 1, 'wh_dlc05_vmp_cha_vampire_shadows_0', ItemType.unit, 0, 'Progressive cst_inf', 'Cst Unit: Vampire (Shadows)'),
    52045: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_mortis_engine_0', ItemType.unit, 3, 'Progressive cst_veh', 'Cst Unit: Mortis Engine'),
    52046: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_2', ItemType.unit, 2, 'Progressive cst_veh', 'Cst Unit: Corpse Cart (Unholy Lodestone)'),
    52047: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_1', ItemType.unit, 2, 'Progressive cst_veh', 'Cst Unit: Corpse Cart (Balefire)'),
    52048: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_corpse_cart_0', ItemType.unit, 1, 'Progressive cst_veh', 'Cst Unit: Corpse Cart'),
    52049: ItemData(IC.useful, 1, 'wh_dlc04_vmp_veh_claw_of_nagash_0', ItemType.unit, 4, 'Progressive cst_veh', 'Cst Unit: The Claw of Nagash (Mortis Engine)'),
    52050: ItemData(IC.useful, 1, 'wh_dlc04_vmp_mon_direpack_0', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: The Direpack (Dire Wolves)'),
    52051: ItemData(IC.useful, 1, 'wh_dlc04_vmp_mon_devils_swartzhafen_0', ItemType.unit, 3, 'Progressive cst_inf', 'Cst Unit: The Devils of Swartzhafen (Vargheists)'),
    52052: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_tithe_0', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: The Tithe (Zombies)'),
    52053: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_sternsmen_0', ItemType.unit, 3, 'Progressive cst_inf', 'Cst Unit: The Sternsmen (Grave Guard)'),
    52054: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_konigstein_stalkers_0', ItemType.unit, 1, 'Progressive cst_inf', 'Cst Unit: The Konigstein Stalkers (Skeleton Warriors)'),
    52055: ItemData(IC.useful, 1, 'wh_dlc04_vmp_inf_feasters_in_the_dusk_0', ItemType.unit, 2, 'Progressive cst_inf', 'Cst Unit: The Feasters in the Dusk (Crypt Ghouls)'),
    52056: ItemData(IC.useful, 1, 'wh_dlc04_vmp_cav_vereks_reavers_0', ItemType.unit, 3, 'cavalry', "Cst Unit: Verek's Reavers (Black Knights â€“ Lances & Barding)"),
    52057: ItemData(IC.useful, 1, 'wh_dlc04_vmp_cav_chillgheists_0', ItemType.unit, 4, 'cavalry', 'Cst Unit: The Chillgheists (Hexwraiths)'),
    52058: ItemData(IC.useful, 1, 'wh_dlc02_vmp_cav_blood_knights_0', ItemType.unit, 4, 'cavalry', 'Cst Unit: Blood Knights (Lances)')
}

buildings: dict[int, ItemData] = {
    52400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_vmp', 'Cst Building: Crypt Keepers'),
    52401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_vmp', 'Cst Building: Undercroft Sentries'),
    52402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_vmp_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_vmp', 'Cst Building: Grave Guardians'),
    52403: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_vmp_1', ItemType.building, 1, 'Progressive special_empire_fort_vmp', 'Cst Building: Occupied Fortress (Small Fort)'),
    52404: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_vmp_2', ItemType.building, 2, 'Progressive special_empire_fort_vmp', 'Cst Building: Occupied Fortress (Fort)'),
    52405: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_vmp_3', ItemType.building, 3, 'Progressive special_empire_fort_vmp', 'Cst Building: Occupied Fortress (Grand Fort)'),
    52406: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_vmp_4', ItemType.building, 4, 'Progressive special_empire_fort_vmp', 'Cst Building: Occupied Fortress (Imposing Fort)'),
    52407: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_vmp_5', ItemType.building, 5, 'Progressive special_empire_fort_vmp', 'Cst Building: Occupied Fortress (Impregnable Fort)'),
    52408: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_vmp_1', ItemType.building, 1, 'Progressive special_fortress_gate_eagle_vmp', 'Cst Building: Occupied Gate (Small Fortress)'),
    52409: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_vmp_2', ItemType.building, 2, 'Progressive special_fortress_gate_eagle_vmp', 'Cst Building: Occupied Gate (Fortress)'),
    52410: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_vmp_3', ItemType.building, 3, 'Progressive special_fortress_gate_eagle_vmp', 'Cst Building: Occupied Gate (Grand Fortress)'),
    52411: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_vmp_4', ItemType.building, 4, 'Progressive special_fortress_gate_eagle_vmp', 'Cst Building: Occupied Gate (Imposing Fortress)'),
    52412: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_vmp_5', ItemType.building, 5, 'Progressive special_fortress_gate_eagle_vmp', 'Cst Building: Occupied Gate (Impregnable Fortress)'),
    52413: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_vmp_1', ItemType.building, 1, 'Progressive special_fortress_gate_griffon_vmp', 'Cst Building: Occupied Gate (Small Fortress)'),
    52414: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_vmp_2', ItemType.building, 2, 'Progressive special_fortress_gate_griffon_vmp', 'Cst Building: Occupied Gate (Fortress)'),
    52415: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_vmp_3', ItemType.building, 3, 'Progressive special_fortress_gate_griffon_vmp', 'Cst Building: Occupied Gate (Grand Fortress)'),
    52416: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_vmp_4', ItemType.building, 4, 'Progressive special_fortress_gate_griffon_vmp', 'Cst Building: Occupied Gate (Imposing Fortress)'),
    52417: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_vmp_5', ItemType.building, 5, 'Progressive special_fortress_gate_griffon_vmp', 'Cst Building: Occupied Gate (Impregnable Fortress)'),
    52418: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_vmp_1', ItemType.building, 1, 'Progressive special_fortress_gate_phoenix_vmp', 'Cst Building: Occupied Gate (Small Fortress)'),
    52419: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_vmp_2', ItemType.building, 2, 'Progressive special_fortress_gate_phoenix_vmp', 'Cst Building: Occupied Gate (Fortress)'),
    52420: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_vmp_3', ItemType.building, 3, 'Progressive special_fortress_gate_phoenix_vmp', 'Cst Building: Occupied Gate (Grand Fortress)'),
    52421: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_vmp_4', ItemType.building, 4, 'Progressive special_fortress_gate_phoenix_vmp', 'Cst Building: Occupied Gate (Imposing Fortress)'),
    52422: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_vmp_5', ItemType.building, 5, 'Progressive special_fortress_gate_phoenix_vmp', 'Cst Building: Occupied Gate (Impregnable Fortress)'),
    52423: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_vmp_1', ItemType.building, 1, 'Progressive special_fortress_gate_unicorn_vmp', 'Cst Building: Occupied Gate (Small Fortress)'),
    52424: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_vmp_2', ItemType.building, 2, 'Progressive special_fortress_gate_unicorn_vmp', 'Cst Building: Occupied Gate (Fortress)'),
    52425: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_vmp_3', ItemType.building, 3, 'Progressive special_fortress_gate_unicorn_vmp', 'Cst Building: Occupied Gate (Grand Fortress)'),
    52426: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_vmp_4', ItemType.building, 4, 'Progressive special_fortress_gate_unicorn_vmp', 'Cst Building: Occupied Gate (Imposing Fortress)'),
    52427: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_vmp_5', ItemType.building, 5, 'Progressive special_fortress_gate_unicorn_vmp', 'Cst Building: Occupied Gate (Impregnable Fortress)'),
    52428: ItemData(IC.useful, 1, 'wh2_main_special_galbaraz_mourkain_vmp_1', ItemType.building, 0, 'Progressive special_galbaraz_mourkain_vmp', 'Cst Building: Ruins of Mourkain'),
    52429: ItemData(IC.useful, 1, 'wh2_main_special_shrine_of_khaine_vmp_1', ItemType.building, 1, 'Progressive special_shrine_of_khaine_vmp', 'Cst Building: The Plains of Bones'),
    52430: ItemData(IC.useful, 1, 'wh2_main_special_shrine_of_khaine_vmp_base', ItemType.building, 0, 'Progressive special_shrine_of_khaine_vmp', 'Cst Building: Abandoned Shrine of Widowmaker'),
    52431: ItemData(IC.useful, 1, 'wh2_main_vmp_defence_norsca_1', ItemType.building, 0, 'Progressive vmp_defence_norsca', 'Cst Building: Outpost Garrison'),
    52432: ItemData(IC.useful, 1, 'wh2_main_vmp_raisedead', ItemType.building, 0, 'Progressive vmp', 'Cst Building: Awakened Battlefield'),
    52433: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_1', ItemType.building, 0, 'Progressive vmp_resource_animals', 'Cst Building: Exotic Animal Tamer'),
    52434: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_2', ItemType.building, 1, 'Progressive vmp_resource_animals', 'Cst Building: Exotic Animal Pen'),
    52435: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_animals_3', ItemType.building, 2, 'Progressive vmp_resource_animals', 'Cst Building: Exotic Animal Market'),
    52436: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_1', ItemType.building, 0, 'Progressive vmp_resource_gemstones', 'Cst Building: Cursed Gemstone Mineshaft'),
    52437: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_2', ItemType.building, 1, 'Progressive vmp_resource_gemstones', 'Cst Building: Hexed Gemstone Pit'),
    52438: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_gemstones_3', ItemType.building, 2, 'Progressive vmp_resource_gemstones', 'Cst Building: Haunted Gemstone Mine'),
    52439: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_1', ItemType.building, 0, 'Progressive vmp_resource_medicine', "Cst Building: Herb Gatherer's Camp"),
    52440: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_2', ItemType.building, 1, 'Progressive vmp_resource_medicine', 'Cst Building: Exotic Hothouse'),
    52441: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_medicine_3', ItemType.building, 2, 'Progressive vmp_resource_medicine', 'Cst Building: Alchemy Workshop'),
    52442: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_1', ItemType.building, 0, 'Progressive vmp_resource_obsidian', 'Cst Building: Obsidian Quarry'),
    52443: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_2', ItemType.building, 1, 'Progressive vmp_resource_obsidian', 'Cst Building: Obsidian Trinket Maker'),
    52444: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_obsidian_3', ItemType.building, 2, 'Progressive vmp_resource_obsidian', 'Cst Building: Obsidian Amulet Carver'),
    52445: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_1', ItemType.building, 0, 'Progressive vmp_resource_spices', 'Cst Building: Spice Market'),
    52446: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_2', ItemType.building, 1, 'Progressive vmp_resource_spices', 'Cst Building: Spice Trading Post'),
    52447: ItemData(IC.useful, 1, 'wh2_main_vmp_resource_spices_3', ItemType.building, 2, 'Progressive vmp_resource_spices', 'Cst Building: Eastern Bazaar'),
    52448: ItemData(IC.useful, 1, 'wh2_main_vmp_terrorgheists_1', ItemType.building, 0, 'Progressive vmp_terrorgheists', 'Cst Building: Terrorgheist Lair'),
    52449: ItemData(IC.useful, 1, 'wh2_main_vmp_wraiths_1', ItemType.building, 0, 'Progressive vmp_wraiths', 'Cst Building: Spirit Well'),
    52450: ItemData(IC.useful, 1, 'wh2_main_vmp_wraiths_2', ItemType.building, 1, 'Progressive vmp_wraiths', 'Cst Building: Font of Nightmares'),
    52451: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_1', ItemType.building, 0, 'Progressive vmp_allied_outpost', 'Cst Building: Undead Outpost'),
    52452: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_2', ItemType.building, 1, 'Progressive vmp_allied_outpost', 'Cst Building: Undead District'),
    52453: ItemData(IC.useful, 1, 'wh3_main_vmp_allied_outpost_3', ItemType.building, 2, 'Progressive vmp_allied_outpost', 'Cst Building: Undead Colony'),
    52454: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_1', ItemType.building, 0, 'Progressive vmp_resource_ivory', 'Cst Building: Animal Store'),
    52455: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_2', ItemType.building, 1, 'Progressive vmp_resource_ivory', 'Cst Building: Tusk Market'),
    52456: ItemData(IC.useful, 1, 'wh3_main_vmp_resource_ivory_3', ItemType.building, 2, 'Progressive vmp_resource_ivory', 'Cst Building: Tusk Compound'),
    52457: ItemData(IC.useful, 1, 'wh_main_vmp_armoury_1', ItemType.building, 0, 'Progressive vmp_armoury', 'Cst Building: Ancient Armoury'),
    52458: ItemData(IC.useful, 1, 'wh_main_vmp_armoury_2', ItemType.building, 1, 'Progressive vmp_armoury', 'Cst Building: Reliquary'),
    52459: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_1', ItemType.building, 0, 'Progressive vmp_balefire', 'Cst Building: Balefire Brazier'),
    52460: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_2', ItemType.building, 1, 'Progressive vmp_balefire', 'Cst Building: Balefire Hearth'),
    52461: ItemData(IC.useful, 1, 'wh_main_vmp_balefire_3', ItemType.building, 2, 'Progressive vmp_balefire', 'Cst Building: Witch House'),
    52462: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_1', ItemType.building, 0, 'Progressive vmp_bindingcircle', 'Cst Building: Defiled Cairn'),
    52463: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_2', ItemType.building, 1, 'Progressive vmp_bindingcircle', 'Cst Building: Binding Circle'),
    52464: ItemData(IC.useful, 1, 'wh_main_vmp_bindingcircle_3', ItemType.building, 2, 'Progressive vmp_bindingcircle', 'Cst Building: Lodestone of Darkness'),
    52465: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_2', ItemType.building, 0, 'Progressive vmp_cemetary', 'Cst Building: Barrow'),
    52466: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_2', ItemType.building, 0, 'Progressive vmp_cemetary', 'Cst Building: Barrow'),
    52467: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_3', ItemType.building, 1, 'Progressive vmp_cemetary', 'Cst Building: Mausoleum'),
    52468: ItemData(IC.useful, 1, 'wh_main_vmp_cemetary_3', ItemType.building, 1, 'Progressive vmp_cemetary', 'Cst Building: Mausoleum'),
    52469: ItemData(IC.useful, 1, 'wh_main_vmp_forest_1', ItemType.building, 0, 'Progressive vmp_forest', 'Cst Building: Sinister Copse'),
    52470: ItemData(IC.useful, 1, 'wh_main_vmp_forest_2', ItemType.building, 1, 'Progressive vmp_forest', 'Cst Building: Abyssal Wood'),
    52471: ItemData(IC.useful, 1, 'wh_main_vmp_forest_3', ItemType.building, 2, 'Progressive vmp_forest', 'Cst Building: Sepulchral Grove'),
    52472: ItemData(IC.useful, 1, 'wh_main_vmp_garrison_1', ItemType.building, 0, 'Progressive vmp_garrison', 'Cst Building: Corpse Pile'),
    52473: ItemData(IC.useful, 1, 'wh_main_vmp_garrison_2', ItemType.building, 1, 'Progressive vmp_garrison', 'Cst Building: Grave Guard Watchtower'),
    52474: ItemData(IC.useful, 1, 'wh_main_vmp_necromancers_1', ItemType.building, 0, 'Progressive vmp_necromancers', 'Cst Building: Forbidden Library'),
    52475: ItemData(IC.useful, 1, 'wh_main_vmp_necromancers_2', ItemType.building, 1, 'Progressive vmp_necromancers', "Cst Building: Necromancer's Tower"),
    52476: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_1', ItemType.building, 0, 'Progressive vmp_ossuary', 'Cst Building: Charnel Pit'),
    52477: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_2', ItemType.building, 1, 'Progressive vmp_ossuary', 'Cst Building: Lychyard'),
    52478: ItemData(IC.useful, 1, 'wh_main_vmp_ossuary_3', ItemType.building, 2, 'Progressive vmp_ossuary', 'Cst Building: Ossuary'),
    52479: ItemData(IC.useful, 1, 'wh_main_vmp_port_1', ItemType.building, 0, 'Progressive vmp_port', 'Cst Building: Crumbling Wharf'),
    52480: ItemData(IC.useful, 1, 'wh_main_vmp_port_2', ItemType.building, 1, 'Progressive vmp_port', 'Cst Building: Murky Harbour'),
    52481: ItemData(IC.useful, 1, 'wh_main_vmp_port_3', ItemType.building, 2, 'Progressive vmp_port', 'Cst Building: Dark Port'),
    52482: ItemData(IC.useful, 1, 'wh_main_vmp_repression_1', ItemType.building, 0, 'Progressive vmp_repression', 'Cst Building: Gibbet'),
    52483: ItemData(IC.useful, 1, 'wh_main_vmp_repression_2', ItemType.building, 1, 'Progressive vmp_repression', 'Cst Building: Gallows'),
    52484: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_1', ItemType.building, 0, 'Progressive vmp_resource_dyes', 'Cst Building: Red Pit'),
    52485: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_2', ItemType.building, 1, 'Progressive vmp_resource_dyes', 'Cst Building: Blood Mines'),
    52486: ItemData(IC.useful, 1, 'wh_main_vmp_resource_dyes_3', ItemType.building, 2, 'Progressive vmp_resource_dyes', "Cst Building: Pigment Grinder's Shop"),
    52487: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_1', ItemType.building, 0, 'Progressive vmp_resource_furs', 'Cst Building: Hunting Grounds'),
    52488: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_2', ItemType.building, 1, 'Progressive vmp_resource_furs', 'Cst Building: Poaching Camp'),
    52489: ItemData(IC.useful, 1, 'wh_main_vmp_resource_furs_3', ItemType.building, 2, 'Progressive vmp_resource_furs', "Cst Building: Flayer's Lair"),
    52490: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_1', ItemType.building, 0, 'Progressive vmp_resource_gold', 'Cst Building: Tarnished Gold Shaft'),
    52491: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_2', ItemType.building, 1, 'Progressive vmp_resource_gold', 'Cst Building: Tarnished Gold Mine'),
    52492: ItemData(IC.useful, 1, 'wh_main_vmp_resource_gold_3', ItemType.building, 2, 'Progressive vmp_resource_gold', 'Cst Building: Balefire Gold Smeltery'),
    52493: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_1', ItemType.building, 0, 'Progressive vmp_resource_iron', 'Cst Building: Dark Iron Pit'),
    52494: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_2', ItemType.building, 1, 'Progressive vmp_resource_iron', 'Cst Building: Zombie-Infested Iron Mine'),
    52495: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_3', ItemType.building, 2, 'Progressive vmp_resource_iron', 'Cst Building: Scoured Iron Mine'),
    52496: ItemData(IC.useful, 1, 'wh_main_vmp_resource_iron_military', ItemType.building, 0, 'Progressive vmp_resource_iron', 'Cst Building: Unholy Forge'),
    52497: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_1', ItemType.building, 0, 'Progressive vmp_resource_marble', "Cst Building: Brimstone Cutter's Workshop"),
    52498: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_2', ItemType.building, 1, 'Progressive vmp_resource_marble', "Cst Building: Tombstone Maker's Atelier"),
    52499: ItemData(IC.useful, 1, 'wh_main_vmp_resource_marble_3', ItemType.building, 2, 'Progressive vmp_resource_marble', "Cst Building: Gargoyle Sculptor's Garret"),
    52500: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_1', ItemType.building, 0, 'Progressive vmp_resource_pastures', 'Cst Building: Cursed Fields'),
    52501: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_2', ItemType.building, 1, 'Progressive vmp_resource_pastures', 'Cst Building: Wretched Farmstead'),
    52502: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_3', ItemType.building, 2, 'Progressive vmp_resource_pastures', 'Cst Building: Haunted Mill'),
    52503: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pastures_timber_military', ItemType.building, 0, 'Progressive vmp_resource_pastures_timber', 'Cst Building: Dark Lair'),
    52504: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_1', ItemType.building, 0, 'Progressive vmp_resource_pottery', 'Cst Building: Flooded Clay Pit'),
    52505: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_2', ItemType.building, 1, 'Progressive vmp_resource_pottery', "Cst Building: Urn Maker's Pottery"),
    52506: ItemData(IC.useful, 1, 'wh_main_vmp_resource_pottery_3', ItemType.building, 2, 'Progressive vmp_resource_pottery', 'Cst Building: Screeching Kilns'),
    52507: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_1', ItemType.building, 0, 'Progressive vmp_resource_salt', 'Cst Building: Brackish Pond'),
    52508: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_2', ItemType.building, 1, 'Progressive vmp_resource_salt', 'Cst Building: Salt Marsh'),
    52509: ItemData(IC.useful, 1, 'wh_main_vmp_resource_salt_3', ItemType.building, 2, 'Progressive vmp_resource_salt', 'Cst Building: Desolate Salt Pans'),
    52510: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_1', ItemType.building, 0, 'Progressive vmp_resource_timber', "Cst Building: Forester's Shack"),
    52511: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_2', ItemType.building, 1, 'Progressive vmp_resource_timber', 'Cst Building: Ruined Sawmill'),
    52512: ItemData(IC.useful, 1, 'wh_main_vmp_resource_timber_3', ItemType.building, 2, 'Progressive vmp_resource_timber', 'Cst Building: Abandoned Wood Sheds'),
    52513: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_1', ItemType.building, 0, 'Progressive vmp_resource_wine', 'Cst Building: Tangled Vine Patch'),
    52514: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_2', ItemType.building, 1, 'Progressive vmp_resource_wine', 'Cst Building: Thorny Orchard'),
    52515: ItemData(IC.useful, 1, 'wh_main_vmp_resource_wine_3', ItemType.building, 2, 'Progressive vmp_resource_wine', 'Cst Building: Animated Winepress'),
    52516: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_1', ItemType.building, 0, 'Progressive vmp_settlement_major', 'Cst Building: Crumbling Hamlet'),
    52517: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_1', ItemType.building, 0, 'Progressive vmp_settlement_major', 'Cst Building: Crumbling Hamlet'),
    52518: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_2', ItemType.building, 1, 'Progressive vmp_settlement_major', 'Cst Building: Corrupted Village'),
    52519: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_2', ItemType.building, 1, 'Progressive vmp_settlement_major', 'Cst Building: Corrupted Village'),
    52520: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_3', ItemType.building, 2, 'Progressive vmp_settlement_major', 'Cst Building: Shady Township'),
    52521: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_3', ItemType.building, 2, 'Progressive vmp_settlement_major', 'Cst Building: Shady Township'),
    52522: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_4', ItemType.building, 3, 'Progressive vmp_settlement_major', 'Cst Building: Accursed City'),
    52523: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_4', ItemType.building, 3, 'Progressive vmp_settlement_major', 'Cst Building: Accursed City'),
    52524: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_5', ItemType.building, 4, 'Progressive vmp_settlement_major', 'Cst Building: Dark Castle'),
    52525: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_major_5', ItemType.building, 4, 'Progressive vmp_settlement_major', 'Cst Building: Dark Castle'),
    52526: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_1', ItemType.building, 0, 'Progressive vmp_settlement_minor', 'Cst Building: Crumbling Hamlet'),
    52527: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_1', ItemType.building, 0, 'Progressive vmp_settlement_minor', 'Cst Building: Crumbling Hamlet'),
    52528: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_2', ItemType.building, 1, 'Progressive vmp_settlement_minor', 'Cst Building: Corrupted Village'),
    52529: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_2', ItemType.building, 1, 'Progressive vmp_settlement_minor', 'Cst Building: Corrupted Village'),
    52530: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_3', ItemType.building, 2, 'Progressive vmp_settlement_minor', 'Cst Building: Shady Township'),
    52531: ItemData(IC.useful, 1, 'wh_main_vmp_settlement_minor_3', ItemType.building, 2, 'Progressive vmp_settlement_minor', 'Cst Building: Shady Township'),
    52532: ItemData(IC.useful, 1, 'wh_main_vmp_vampires_1', ItemType.building, 0, 'Progressive vmp_vampires', 'Cst Building: Vampire Crypts'),
    52533: ItemData(IC.useful, 1, 'wh_main_vmp_vampires_2', ItemType.building, 1, 'Progressive vmp_vampires', "Cst Building: Vampire's Keep"),
    52534: ItemData(IC.useful, 1, 'wh_main_vmp_walls_1', ItemType.building, 0, 'Progressive vmp_walls', 'Cst Building: Ghost Fence'),
    52535: ItemData(IC.useful, 1, 'wh_main_vmp_walls_2', ItemType.building, 1, 'Progressive vmp_walls', 'Cst Building: Skeletal Walls'),
    52536: ItemData(IC.useful, 1, 'wh_main_vmp_walls_3', ItemType.building, 2, 'Progressive vmp_walls', 'Cst Building: Blasphemous Bulwark')
}

techs: dict[int, ItemData] = {
    52800: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_05', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Invoke Animalistic Hunger'),
    52801: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_02a', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Risen Standard Bearers'),
    52802: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_05a', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Unnatural Strength'),
    52803: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_01', ItemType.tech, 0, 'Progressive tech_vmp', 'Cst Tech: De Noirotâ€™s Blasphemous Bestiary'),
    52804: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_02', ItemType.tech, 1, 'Progressive tech_vmp', 'Cst Tech: Corruptor of the Forests'),
    52805: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_04', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Leader of the Pack'),
    52806: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_06', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Beastmaster'),
    52807: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_08', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Fresh Prey Supply'),
    52808: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_09', ItemType.tech, 5, 'Progressive tech_vmp', 'Cst Tech: Fuelled by Fear'),
    52809: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_01', ItemType.tech, 0, 'Progressive tech_vmp', 'Cst Tech: The Book of Arkhan'),
    52810: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_02', ItemType.tech, 1, 'Progressive tech_vmp', 'Cst Tech: Raise Newly Dead'),
    52811: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_05', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Bond of Bones'),
    52812: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_08', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Risen Champions'),
    52813: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_03', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Master of the Swarm'),
    52814: ItemData(IC.useful, 1, 'wh_main_tech_vmp_beasts_07', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Blood Hunts'),
    52815: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_03', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Bonds of Flesh'),
    52816: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_06', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Distribute Grave Gift'),
    52817: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_09', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Unearth Cursed Wightblades'),
    52818: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_04', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Rotten Gift'),
    52819: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_07', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Defiler of the Ancient Barrows'),
    52820: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_10', ItemType.tech, 5, 'Progressive tech_vmp', 'Cst Tech: Dread Animator'),
    52821: ItemData(IC.useful, 1, 'wh_main_tech_vmp_bones_04a', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Master of the Putrid Horde'),
    52822: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_06', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Strigoi Legacy'),
    52823: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_03', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Cannibalistic Rituals'),
    52824: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_09', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Enshrine Ancient Lords'),
    52825: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_04', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Blood is Power'),
    52826: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_06A', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Turning Knightly Orders'),
    52827: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_09', ItemType.tech, 5, 'Progressive tech_vmp', 'Cst Tech: Vampiric Revivification'),
    52828: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_09A', ItemType.tech, 6, 'Progressive tech_vmp', 'Cst Tech: Delusions of Grandeur'),
    52829: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_01', ItemType.tech, 0, 'Progressive tech_vmp', 'Cst Tech: Liber Necronomica'),
    52830: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_02', ItemType.tech, 1, 'Progressive tech_vmp', 'Cst Tech: Incantations of Ushoran'),
    52831: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_05', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Infuse the Tireless Hordes'),
    52832: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_08', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Unliving Siege Engines'),
    52833: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_01', ItemType.tech, 0, 'Progressive tech_vmp', 'Cst Tech: The Lahmian Book of Blood'),
    52834: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_02', ItemType.tech, 1, 'Progressive tech_vmp', 'Cst Tech: Serve in Life or in Death'),
    52835: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_03', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Baleful Rituals'),
    52836: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_06', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Spread Vampire Covens'),
    52837: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_08', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Blasphemous Disciples'),
    52838: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_11', ItemType.tech, 5, 'Progressive tech_vmp', 'Cst Tech: Puppet Master'),
    52839: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_04', ItemType.tech, 2, 'Progressive tech_vmp', 'Cst Tech: Soulbinder'),
    52840: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_07', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Nightmarish Reaping'),
    52841: ItemData(IC.useful, 1, 'wh_main_tech_vmp_binding_10', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Spirit Shackles'),
    52842: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_05', ItemType.tech, 3, 'Progressive tech_vmp', 'Cst Tech: Hexensnacht Sacrifices'),
    52843: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_07', ItemType.tech, 4, 'Progressive tech_vmp', 'Cst Tech: Infiltrate Noble Houses'),
    52844: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_10', ItemType.tech, 5, 'Progressive tech_vmp', 'Cst Tech: Decipher Nehekhara Manuscripts'),
    52845: ItemData(IC.useful, 1, 'wh_main_tech_vmp_blood_12', ItemType.tech, 6, 'Progressive tech_vmp', 'Cst Tech: Incantations of Nagash')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    53300: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_vmp', ItemType.building, 1, None, 'Progressive Cst Building: Foreign Slot Discovery Vmp'),
    53301: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Foreign Slot Discovery Vmp'),
    53302: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Foreign Slot Discovery Vmp'),
    53303: ItemData(IC.useful, 2, 'Progressive special_empire_fort_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Empire Fort Vmp'),
    53304: ItemData(IC.useful, 3, 'Progressive special_empire_fort_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Special Empire Fort Vmp'),
    53305: ItemData(IC.useful, 4, 'Progressive special_empire_fort_vmp', ItemType.building, 4, None, 'Progressive Cst Building: Special Empire Fort Vmp'),
    53306: ItemData(IC.useful, 5, 'Progressive special_empire_fort_vmp', ItemType.building, 5, None, 'Progressive Cst Building: Special Empire Fort Vmp'),
    53307: ItemData(IC.useful, 6, 'Progressive special_empire_fort_vmp', ItemType.building, 6, None, 'Progressive Cst Building: Special Empire Fort Vmp'),
    53308: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_eagle_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Fortress Gate Eagle Vmp'),
    53309: ItemData(IC.useful, 3, 'Progressive special_fortress_gate_eagle_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Special Fortress Gate Eagle Vmp'),
    53310: ItemData(IC.useful, 4, 'Progressive special_fortress_gate_eagle_vmp', ItemType.building, 4, None, 'Progressive Cst Building: Special Fortress Gate Eagle Vmp'),
    53311: ItemData(IC.useful, 5, 'Progressive special_fortress_gate_eagle_vmp', ItemType.building, 5, None, 'Progressive Cst Building: Special Fortress Gate Eagle Vmp'),
    53312: ItemData(IC.useful, 6, 'Progressive special_fortress_gate_eagle_vmp', ItemType.building, 6, None, 'Progressive Cst Building: Special Fortress Gate Eagle Vmp'),
    53313: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_griffon_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Fortress Gate Griffon Vmp'),
    53314: ItemData(IC.useful, 3, 'Progressive special_fortress_gate_griffon_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Special Fortress Gate Griffon Vmp'),
    53315: ItemData(IC.useful, 4, 'Progressive special_fortress_gate_griffon_vmp', ItemType.building, 4, None, 'Progressive Cst Building: Special Fortress Gate Griffon Vmp'),
    53316: ItemData(IC.useful, 5, 'Progressive special_fortress_gate_griffon_vmp', ItemType.building, 5, None, 'Progressive Cst Building: Special Fortress Gate Griffon Vmp'),
    53317: ItemData(IC.useful, 6, 'Progressive special_fortress_gate_griffon_vmp', ItemType.building, 6, None, 'Progressive Cst Building: Special Fortress Gate Griffon Vmp'),
    53318: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_phoenix_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Fortress Gate Phoenix Vmp'),
    53319: ItemData(IC.useful, 3, 'Progressive special_fortress_gate_phoenix_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Special Fortress Gate Phoenix Vmp'),
    53320: ItemData(IC.useful, 4, 'Progressive special_fortress_gate_phoenix_vmp', ItemType.building, 4, None, 'Progressive Cst Building: Special Fortress Gate Phoenix Vmp'),
    53321: ItemData(IC.useful, 5, 'Progressive special_fortress_gate_phoenix_vmp', ItemType.building, 5, None, 'Progressive Cst Building: Special Fortress Gate Phoenix Vmp'),
    53322: ItemData(IC.useful, 6, 'Progressive special_fortress_gate_phoenix_vmp', ItemType.building, 6, None, 'Progressive Cst Building: Special Fortress Gate Phoenix Vmp'),
    53323: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_unicorn_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Fortress Gate Unicorn Vmp'),
    53324: ItemData(IC.useful, 3, 'Progressive special_fortress_gate_unicorn_vmp', ItemType.building, 3, None, 'Progressive Cst Building: Special Fortress Gate Unicorn Vmp'),
    53325: ItemData(IC.useful, 4, 'Progressive special_fortress_gate_unicorn_vmp', ItemType.building, 4, None, 'Progressive Cst Building: Special Fortress Gate Unicorn Vmp'),
    53326: ItemData(IC.useful, 5, 'Progressive special_fortress_gate_unicorn_vmp', ItemType.building, 5, None, 'Progressive Cst Building: Special Fortress Gate Unicorn Vmp'),
    53327: ItemData(IC.useful, 6, 'Progressive special_fortress_gate_unicorn_vmp', ItemType.building, 6, None, 'Progressive Cst Building: Special Fortress Gate Unicorn Vmp'),
    53328: ItemData(IC.useful, 1, 'Progressive special_galbaraz_mourkain_vmp', ItemType.building, 1, None, 'Progressive Cst Building: Special Galbaraz Mourkain Vmp'),
    53329: ItemData(IC.useful, 2, 'Progressive special_shrine_of_khaine_vmp', ItemType.building, 2, None, 'Progressive Cst Building: Special Shrine Of Khaine Vmp'),
    53330: ItemData(IC.useful, 1, 'Progressive special_shrine_of_khaine_vmp', ItemType.building, 1, None, 'Progressive Cst Building: Special Shrine Of Khaine Vmp'),
    53331: ItemData(IC.useful, 1, 'Progressive vmp_defence_norsca', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Defence Norsca'),
    53332: ItemData(IC.useful, 1, 'Progressive vmp', ItemType.building, 1, None, 'Progressive Cst Building: Vmp'),
    53333: ItemData(IC.useful, 1, 'Progressive vmp_resource_animals', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Animals'),
    53334: ItemData(IC.useful, 2, 'Progressive vmp_resource_animals', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Animals'),
    53335: ItemData(IC.useful, 3, 'Progressive vmp_resource_animals', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Animals'),
    53336: ItemData(IC.useful, 1, 'Progressive vmp_resource_gemstones', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Gemstones'),
    53337: ItemData(IC.useful, 2, 'Progressive vmp_resource_gemstones', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Gemstones'),
    53338: ItemData(IC.useful, 3, 'Progressive vmp_resource_gemstones', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Gemstones'),
    53339: ItemData(IC.useful, 1, 'Progressive vmp_resource_medicine', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Medicine'),
    53340: ItemData(IC.useful, 2, 'Progressive vmp_resource_medicine', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Medicine'),
    53341: ItemData(IC.useful, 3, 'Progressive vmp_resource_medicine', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Medicine'),
    53342: ItemData(IC.useful, 1, 'Progressive vmp_resource_obsidian', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Obsidian'),
    53343: ItemData(IC.useful, 2, 'Progressive vmp_resource_obsidian', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Obsidian'),
    53344: ItemData(IC.useful, 3, 'Progressive vmp_resource_obsidian', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Obsidian'),
    53345: ItemData(IC.useful, 1, 'Progressive vmp_resource_spices', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Spices'),
    53346: ItemData(IC.useful, 2, 'Progressive vmp_resource_spices', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Spices'),
    53347: ItemData(IC.useful, 3, 'Progressive vmp_resource_spices', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Spices'),
    53348: ItemData(IC.useful, 1, 'Progressive vmp_terrorgheists', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Terrorgheists'),
    53349: ItemData(IC.useful, 1, 'Progressive vmp_wraiths', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Wraiths'),
    53350: ItemData(IC.useful, 2, 'Progressive vmp_wraiths', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Wraiths'),
    53351: ItemData(IC.useful, 1, 'Progressive vmp_allied_outpost', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Allied Outpost'),
    53352: ItemData(IC.useful, 2, 'Progressive vmp_allied_outpost', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Allied Outpost'),
    53353: ItemData(IC.useful, 3, 'Progressive vmp_allied_outpost', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Allied Outpost'),
    53354: ItemData(IC.useful, 1, 'Progressive vmp_resource_ivory', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Ivory'),
    53355: ItemData(IC.useful, 2, 'Progressive vmp_resource_ivory', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Ivory'),
    53356: ItemData(IC.useful, 3, 'Progressive vmp_resource_ivory', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Ivory'),
    53357: ItemData(IC.useful, 1, 'Progressive vmp_armoury', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Armoury'),
    53358: ItemData(IC.useful, 2, 'Progressive vmp_armoury', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Armoury'),
    53359: ItemData(IC.useful, 1, 'Progressive vmp_balefire', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Balefire'),
    53360: ItemData(IC.useful, 2, 'Progressive vmp_balefire', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Balefire'),
    53361: ItemData(IC.useful, 3, 'Progressive vmp_balefire', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Balefire'),
    53362: ItemData(IC.useful, 1, 'Progressive vmp_bindingcircle', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Bindingcircle'),
    53363: ItemData(IC.useful, 2, 'Progressive vmp_bindingcircle', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Bindingcircle'),
    53364: ItemData(IC.useful, 3, 'Progressive vmp_bindingcircle', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Bindingcircle'),
    53365: ItemData(IC.useful, 1, 'Progressive vmp_cemetary', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Cemetary'),
    53366: ItemData(IC.useful, 2, 'Progressive vmp_cemetary', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Cemetary'),
    53367: ItemData(IC.useful, 1, 'Progressive vmp_forest', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Forest'),
    53368: ItemData(IC.useful, 2, 'Progressive vmp_forest', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Forest'),
    53369: ItemData(IC.useful, 3, 'Progressive vmp_forest', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Forest'),
    53370: ItemData(IC.useful, 1, 'Progressive vmp_garrison', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Garrison'),
    53371: ItemData(IC.useful, 2, 'Progressive vmp_garrison', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Garrison'),
    53372: ItemData(IC.useful, 1, 'Progressive vmp_necromancers', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Necromancers'),
    53373: ItemData(IC.useful, 2, 'Progressive vmp_necromancers', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Necromancers'),
    53374: ItemData(IC.useful, 1, 'Progressive vmp_ossuary', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Ossuary'),
    53375: ItemData(IC.useful, 2, 'Progressive vmp_ossuary', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Ossuary'),
    53376: ItemData(IC.useful, 3, 'Progressive vmp_ossuary', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Ossuary'),
    53377: ItemData(IC.useful, 1, 'Progressive vmp_port', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Port'),
    53378: ItemData(IC.useful, 2, 'Progressive vmp_port', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Port'),
    53379: ItemData(IC.useful, 3, 'Progressive vmp_port', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Port'),
    53380: ItemData(IC.useful, 1, 'Progressive vmp_repression', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Repression'),
    53381: ItemData(IC.useful, 2, 'Progressive vmp_repression', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Repression'),
    53382: ItemData(IC.useful, 1, 'Progressive vmp_resource_dyes', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Dyes'),
    53383: ItemData(IC.useful, 2, 'Progressive vmp_resource_dyes', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Dyes'),
    53384: ItemData(IC.useful, 3, 'Progressive vmp_resource_dyes', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Dyes'),
    53385: ItemData(IC.useful, 1, 'Progressive vmp_resource_furs', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Furs'),
    53386: ItemData(IC.useful, 2, 'Progressive vmp_resource_furs', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Furs'),
    53387: ItemData(IC.useful, 3, 'Progressive vmp_resource_furs', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Furs'),
    53388: ItemData(IC.useful, 1, 'Progressive vmp_resource_gold', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Gold'),
    53389: ItemData(IC.useful, 2, 'Progressive vmp_resource_gold', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Gold'),
    53390: ItemData(IC.useful, 3, 'Progressive vmp_resource_gold', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Gold'),
    53391: ItemData(IC.useful, 1, 'Progressive vmp_resource_iron', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Iron'),
    53392: ItemData(IC.useful, 2, 'Progressive vmp_resource_iron', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Iron'),
    53393: ItemData(IC.useful, 3, 'Progressive vmp_resource_iron', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Iron'),
    53394: ItemData(IC.useful, 1, 'Progressive vmp_resource_iron', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Iron'),
    53395: ItemData(IC.useful, 1, 'Progressive vmp_resource_marble', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Marble'),
    53396: ItemData(IC.useful, 2, 'Progressive vmp_resource_marble', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Marble'),
    53397: ItemData(IC.useful, 3, 'Progressive vmp_resource_marble', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Marble'),
    53398: ItemData(IC.useful, 1, 'Progressive vmp_resource_pastures', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Pastures'),
    53399: ItemData(IC.useful, 2, 'Progressive vmp_resource_pastures', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Pastures'),
    53400: ItemData(IC.useful, 3, 'Progressive vmp_resource_pastures', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Pastures'),
    53401: ItemData(IC.useful, 1, 'Progressive vmp_resource_pastures_timber', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Pastures Timber'),
    53402: ItemData(IC.useful, 1, 'Progressive vmp_resource_pottery', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Pottery'),
    53403: ItemData(IC.useful, 2, 'Progressive vmp_resource_pottery', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Pottery'),
    53404: ItemData(IC.useful, 3, 'Progressive vmp_resource_pottery', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Pottery'),
    53405: ItemData(IC.useful, 1, 'Progressive vmp_resource_salt', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Salt'),
    53406: ItemData(IC.useful, 2, 'Progressive vmp_resource_salt', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Salt'),
    53407: ItemData(IC.useful, 3, 'Progressive vmp_resource_salt', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Salt'),
    53408: ItemData(IC.useful, 1, 'Progressive vmp_resource_timber', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Timber'),
    53409: ItemData(IC.useful, 2, 'Progressive vmp_resource_timber', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Timber'),
    53410: ItemData(IC.useful, 3, 'Progressive vmp_resource_timber', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Timber'),
    53411: ItemData(IC.useful, 1, 'Progressive vmp_resource_wine', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Wine'),
    53412: ItemData(IC.useful, 2, 'Progressive vmp_resource_wine', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Wine'),
    53413: ItemData(IC.useful, 3, 'Progressive vmp_resource_wine', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Wine'),
    53414: ItemData(IC.useful, 1, 'Progressive vmp_settlement_major', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Settlement Major'),
    53415: ItemData(IC.useful, 2, 'Progressive vmp_settlement_major', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Settlement Major'),
    53416: ItemData(IC.useful, 3, 'Progressive vmp_settlement_major', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Settlement Major'),
    53417: ItemData(IC.useful, 4, 'Progressive vmp_settlement_major', ItemType.building, 4, None, 'Progressive Cst Building: Vmp Settlement Major'),
    53418: ItemData(IC.useful, 5, 'Progressive vmp_settlement_major', ItemType.building, 5, None, 'Progressive Cst Building: Vmp Settlement Major'),
    53419: ItemData(IC.useful, 1, 'Progressive vmp_settlement_minor', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Settlement Minor'),
    53420: ItemData(IC.useful, 2, 'Progressive vmp_settlement_minor', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Settlement Minor'),
    53421: ItemData(IC.useful, 3, 'Progressive vmp_settlement_minor', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Settlement Minor'),
    53422: ItemData(IC.useful, 1, 'Progressive vmp_vampires', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Vampires'),
    53423: ItemData(IC.useful, 2, 'Progressive vmp_vampires', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Vampires'),
    53424: ItemData(IC.useful, 1, 'Progressive vmp_walls', ItemType.building, 1, None, 'Progressive Cst Building: Vmp Walls'),
    53425: ItemData(IC.useful, 2, 'Progressive vmp_walls', ItemType.building, 2, None, 'Progressive Cst Building: Vmp Walls'),
    53426: ItemData(IC.useful, 3, 'Progressive vmp_walls', ItemType.building, 3, None, 'Progressive Cst Building: Vmp Walls')
}

progTechs: dict[int, ItemData] = {
    53500: ItemData(IC.useful, 15, "Progressive tech_vmp", ItemType.tech, 15, None, "Progressive Vmp Tech"),
}

special: dict[int, ItemData] = {

}