from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    60000: ItemData(IC.useful, 1, 'wh3_twa08_nur_mon_great_unclean_one_0_ror', ItemType.unit, 5, 'Progressive chs_inf', 'Cnu Unit: Uncle Furuncle (Great Unclean One)'),
    60001: ItemData(IC.useful, 1, 'wh3_main_nur_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive chs_rng', 'Cnu Unit: Soul Grinder of Nurgle'),
    60002: ItemData(IC.useful, 1, 'wh3_main_nur_mon_great_unclean_one_0', ItemType.unit, 4, 'Progressive chs_inf', 'Cnu Unit: Great Unclean One'),
    60003: ItemData(IC.useful, 1, 'wh3_main_nur_mon_beast_of_nurgle_0', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Beast of Nurgle'),
    60004: ItemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_1', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Exalted Plaguebearers of Nurgle'),
    60005: ItemData(IC.useful, 1, 'wh3_main_nur_inf_plaguebearers_0', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Plaguebearers of Nurgle'),
    60006: ItemData(IC.useful, 1, 'wh3_main_nur_inf_nurglings_0', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Nurglings'),
    60007: ItemData(IC.useful, 1, 'wh3_main_nur_cav_plague_drones_0', ItemType.unit, 3, 'cavalry', 'Cnu Unit: Plague Drones of Nurgle'),
    60008: ItemData(IC.useful, 1, 'wh3_main_dae_inf_chaos_furies_0', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Furies'),
    60009: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_toad_dragon', ItemType.unit, 5, 'Progressive chs_inf', 'Cnu Unit: Toad Dragon'),
    60010: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_soul_grinder_0_ror', ItemType.unit, 4, 'Progressive chs_rng', 'Cnu Unit: Noxbringer (Soul Grinder of Nurgle)'),
    60011: ItemData(IC.useful, 1, 'wh3_dlc25_nur_mon_bile_trolls', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Bile Trolls'),
    60012: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres_great_weapons', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Plague Ogres (Great Weapons)'),
    60013: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_plague_ogres', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Plague Ogres'),
    60014: ItemData(IC.useful, 1, 'wh3_dlc25_nur_inf_pestigors', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Pestigors'),
    60015: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights_ror', ItemType.unit, 5, 'war_beast', 'Cnu Unit: The Rotting Riders (Rot Knights)'),
    60016: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_rot_knights', ItemType.unit, 4, 'war_beast', 'Cnu Unit: Rot Knights'),
    60017: ItemData(IC.useful, 1, 'wh3_dlc25_nur_cav_plague_drones_1_ror', ItemType.unit, 4, 'cavalry', "Cnu Unit: The Angels of Decay (Plague Drones â€“ Death's Heads)"),
    60018: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_exalted_hero_mnur_rot_beast', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Exalted Hero of Nurgle'),
    60019: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_nurgle_mnur_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Nurgle)'),
    60020: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_nurgle_mnur_rot_beast', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Nurgle)'),
    60021: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_nurgle_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Nurgle)'),
    60022: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_nurgle_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer of Nurgle (Nurgle)'),
    60023: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_death_mnur_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Death)'),
    60024: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_death_mnur_rot_beast', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Death)'),
    60025: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_death_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer of Nurgle (Death)'),
    60026: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_sorcerer_death_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer of Nurgle (Death)'),
    60027: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_lord_mnur_rot_beast', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Lord of Nurgle'),
    60028: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_lord_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Lord of Nurgle'),
    60029: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_lord_mnur_chaos_chariot', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Lord of Nurgle'),
    60030: ItemData(IC.useful, 1, 'wh3_dlc25_chs_cha_chaos_lord_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Lord of Nurgle'),
    60031: ItemData(IC.useful, 1, 'wh3_dlc20_nur_cha_festus', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Festus the Leechlord'),
    60032: ItemData(IC.useful, 1, 'wh3_dlc20_nur_cha_cultist_mnur_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Cultist of Nurgle'),
    60033: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mnur', ItemType.unit, 3, 'war_beast', 'Cnu Unit: Chaos Warshrine of Nurgle'),
    60034: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_giant_mnur_ror', ItemType.unit, 5, 'Progressive chs_inf', 'Cnu Unit: Bilious Thunderguff (Chaos Giant)'),
    60035: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mnur_greatweapons', ItemType.unit, 4, 'Progressive chs_inf', 'Cnu Unit: Chosen of Nurgle (Great Weapons)'),
    60036: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mnur', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chosen of Nurgle'),
    60037: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Warriors of Nurgle (Great Weapons)'),
    60038: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mnur', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Warriors of Nurgle'),
    60039: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mnur_greatweapons', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Marauders of Nurgle (Great Weapons)'),
    60040: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mnur', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Marauders of Nurgle'),
    60041: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_exalted_hero_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Exalted Hero of Nurgle'),
    60042: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_exalted_hero_mnur_chaos_chariot', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Exalted Hero of Nurgle'),
    60043: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_exalted_hero_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Exalted Hero of Nurgle'),
    60044: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_daemon_prince_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Daemon Prince of Nurgle'),
    60045: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_daemon_prince', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Daemon Prince'),
    60046: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_shadows_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Shadows)'),
    60047: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_metal_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Metal)'),
    60048: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_shadows_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Shadows)'),
    60049: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_nurgle_mnur_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Nurgle)'),
    60050: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_nurgle_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Nurgle)'),
    60051: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_nurgle_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Nurgle)'),
    60052: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_metal_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Metal)'),
    60053: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_fire_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Fire)'),
    60054: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_death_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Death)'),
    60055: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_death_mnur_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Death)'),
    60056: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_death_mnur_chaos_steed', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Death)'),
    60057: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_lord_death_mnur', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord of Nurgle (Death)'),
    60058: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cha_chaos_sorcerer_death_warshrine', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Death)'),
    60059: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes', ItemType.unit, 2, 'war_beast', 'Cnu Unit: Marauder Horsemen of Nurgle (Throwing Axes)'),
    60060: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mnur_lances', ItemType.unit, 4, 'war_beast', 'Cnu Unit: Chaos Knights of Nurgle (Lances)'),
    60061: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mnur', ItemType.unit, 3, 'war_beast', 'Cnu Unit: Chaos Knights of Nurgle'),
    60062: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_mnur', ItemType.unit, 2, 'Progressive chs_veh', 'Cnu Unit: Chaos Chariots of Nurgle'),
    60063: ItemData(IC.useful, 1, 'wh_main_chs_mon_trolls', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Trolls'),
    60064: ItemData(IC.useful, 1, 'wh_main_chs_mon_giant', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chaos Giant'),
    60065: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_1', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Chaos Warhounds (Poison)'),
    60066: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_0', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Chaos Warhounds'),
    60067: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_spawn', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chaos Spawn'),
    60068: ItemData(IC.useful, 1, 'wh_main_chs_inf_chosen_1', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chosen (Great Weapons)'),
    60069: ItemData(IC.useful, 1, 'wh_main_chs_inf_chosen_0', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chosen'),
    60070: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_warriors_1', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Warriors (Halberds)'),
    60071: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Warriors'),
    60072: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_marauders_1', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Marauders (Great Weapons)'),
    60073: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_marauders_0', ItemType.unit, 1, 'Progressive chs_inf', 'Cnu Unit: Marauders'),
    60074: ItemData(IC.useful, 1, 'wh_main_chs_cha_lord_of_change_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Sarthorael the Everwatcher'),
    60075: ItemData(IC.useful, 1, 'wh_main_chs_cha_exalted_hero_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Exalted Hero'),
    60076: ItemData(IC.useful, 1, 'wh_main_chs_cha_exalted_hero_13', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Exalted Hero - Deprecated'),
    60077: ItemData(IC.useful, 1, 'wh_main_chs_cha_exalted_hero_12', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Exalted Hero'),
    60078: ItemData(IC.useful, 1, 'wh_main_chs_cha_exalted_hero_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Exalted Hero'),
    60079: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_metal_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Metal)'),
    60080: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_metal_11', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer (Metal) â€“ Merged with Chaos Steed'),
    60081: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_metal_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Metal)'),
    60082: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_metal_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer (Metal)'),
    60083: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_fire_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Fire)'),
    60084: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_fire_11', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer (Fire) â€“ Deprecated'),
    60085: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_fire_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Fire)'),
    60086: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_fire_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer (Fire)'),
    60087: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_death_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Death) â€“ Deprecated'),
    60088: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_death_11', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer (Death) â€“ Deprecated'),
    60089: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_death_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Death)'),
    60090: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_sorcerer_death_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer (Death)'),
    60091: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_lord_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Lord'),
    60092: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_lord_12', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Lord â€“ Deprecated'),
    60093: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_lord_11', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Lord'),
    60094: ItemData(IC.useful, 1, 'wh_main_chs_cha_chaos_lord_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Lord'),
    60095: ItemData(IC.useful, 1, 'wh_main_chs_cha_archaon_the_everchosen_1', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Archaon the Everchosen'),
    60096: ItemData(IC.useful, 1, 'wh_main_chs_cha_archaon_the_everchosen_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Archaon the Everchosen'),
    60097: ItemData(IC.useful, 1, 'wh_main_chs_cav_marauder_horsemen_1', ItemType.unit, 2, 'war_beast', 'Cnu Unit: Marauder Horsemen (Throwing Axes)'),
    60098: ItemData(IC.useful, 1, 'wh_main_chs_cav_marauder_horsemen_0', ItemType.unit, 2, 'war_beast', 'Cnu Unit: Marauder Horsemen'),
    60099: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_knights_1', ItemType.unit, 3, 'war_beast', 'Cnu Unit: Chaos Knights (Lances)'),
    60100: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_knights_0', ItemType.unit, 3, 'war_beast', 'Cnu Unit: Chaos Knights'),
    60101: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_chariot', ItemType.unit, 2, 'Progressive chs_veh', 'Cnu Unit: Chaos Chariots'),
    60102: ItemData(IC.useful, 1, 'wh_dlc06_chs_inf_aspiring_champions_0', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Aspiring Champions'),
    60103: ItemData(IC.useful, 1, 'wh_dlc06_chs_feral_manticore', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Feral Manticore'),
    60104: ItemData(IC.useful, 1, 'wh_dlc06_chs_cav_marauder_horsemasters_0', ItemType.unit, 2, 'war_beast', 'Cnu Unit: Marauder Horsemasters'),
    60105: ItemData(IC.useful, 1, 'wh_dlc01_chs_mon_trolls_1', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Trolls (Armoured)'),
    60106: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_forsaken_0', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Forsaken'),
    60107: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_chosen_2', ItemType.unit, 3, 'Progressive chs_inf', 'Cnu Unit: Chosen (Halberds)'),
    60108: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive chs_inf', 'Cnu Unit: Chaos Warriors (Great Weapons)'),
    60109: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_qb_lord_of_change_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Lord of Change'),
    60110: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_prince_sigvald_the_magnificent', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Prince Sigvald the Magnificent'),
    60111: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_kholek', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Kholek Suneater'),
    60112: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_exalted_hero_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Exalted Hero - Deprecated'),
    60113: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_exalted_hero_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Exalted Hero'),
    60114: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_shadows_3', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Shadows)'),
    60115: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_shadows_2', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer (Shadows) â€“ Deprecated'),
    60116: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_shadows_1', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer (Shadows)'),
    60117: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_shadows_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer (Shadows)'),
    60118: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_metal_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Metal)'),
    60119: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_4', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Shadows)'),
    60120: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_3', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Shadows)'),
    60121: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_2', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer Lord (Shadows) â€“ Deprecated'),
    60122: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_1', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Shadows)'),
    60123: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord (Shadows)'),
    60124: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_9', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Metal)'),
    60125: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Fire) â€“ Deprecated'),
    60126: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Fire) â€“ Deprecated'),
    60127: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_13', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer Lord (Metal) â€“ Deprecated'),
    60128: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_12', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Metal)'),
    60129: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Metal)'),
    60130: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord (Metal)'),
    60131: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_9', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Fire)'),
    60132: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Fire) â€“ Deprecated'),
    60133: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Fire) â€“ Deprecated'),
    60134: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_13', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer Lord (Fire) â€“ Deprecated'),
    60135: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_12', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Fire)'),
    60136: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Fire)'),
    60137: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord (Fire)'),
    60138: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_9', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Death)'),
    60139: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Death) â€“ Deprecated'),
    60140: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_7', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer Lord (Death) â€“ Deprecated'),
    60141: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_13', ItemType.unit, 0, 'cavalry', 'Cnu Unit: Chaos Sorcerer Lord (Death) â€“ Deprecated'),
    60142: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_12', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Death)'),
    60143: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Sorcerer Lord (Death)'),
    60144: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_lord_death_0', ItemType.unit, 0, 'Progressive chs_inf', 'Cnu Unit: Chaos Sorcerer Lord (Death)'),
    60145: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_fire_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Fire)'),
    60146: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_sorcerer_death_8', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Sorcerer (Death)'),
    60147: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_lord_9', ItemType.unit, 0, 'Progressive chs_veh', 'Cnu Unit: Chaos Lord â€“ Deprecated'),
    60148: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_lord_2', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Lord'),
    60149: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_chaos_lord_10', ItemType.unit, 0, 'war_beast', 'Cnu Unit: Chaos Lord'),
    60150: ItemData(IC.useful, 1, 'wh_dlc01_chs_cav_gorebeast_chariot', ItemType.unit, 3, 'Progressive chs_veh', 'Cnu Unit: Gorebeast Chariots')
}

buildings: dict[int, ItemData] = {
    60400: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_woc', 'Cnu Building: Rat Catcher Outpost'),
    60401: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_woc', "Cnu Building: Catchers' Camp"),
    60402: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_woc', 'Cnu Building: Vermin Slayers'),
    60403: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_1', ItemType.building, 0, 'Progressive settlement_woc_dark_fortress', 'Cnu Building: Chaos Keep'),
    60404: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_2', ItemType.building, 1, 'Progressive settlement_woc_dark_fortress', 'Cnu Building: Chaos Fort'),
    60405: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_3', ItemType.building, 2, 'Progressive settlement_woc_dark_fortress', 'Cnu Building: Dark Redoubt'),
    60406: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_4', ItemType.building, 3, 'Progressive settlement_woc_dark_fortress', 'Cnu Building: Dark Fortress'),
    60407: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_5', ItemType.building, 4, 'Progressive settlement_woc_dark_fortress', 'Cnu Building: Exalted Dark Fortress'),
    60408: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_corruption_1', ItemType.building, 0, 'Progressive woc_chaos_altar_corruption', 'Cnu Building: Twisted Relic'),
    60409: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_garrison_1', ItemType.building, 0, 'Progressive woc_chaos_altar_garrison', 'Cnu Building: Warband Camp'),
    60410: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_major_human_1', ItemType.building, 1, 'Progressive woc_chaos_altar_major_human', 'Cnu Building: Chaos Altar'),
    60411: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_recruit_1', ItemType.building, 0, 'Progressive woc_chaos_altar_recruit', 'Cnu Building: Bleeding Grounds'),
    60412: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_replenishment_1', ItemType.building, 0, 'Progressive woc_chaos_altar_replenishment', 'Cnu Building: Ritual Hut'),
    60413: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_1', ItemType.building, 0, 'Progressive woc_chaos_altar_special_gate_settlement', 'Cnu Building: Barricaded Chaos Altar'),
    60414: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_2', ItemType.building, 1, 'Progressive woc_chaos_altar_special_gate_settlement', 'Cnu Building: Reinforced Chaos Altar'),
    60415: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_3', ItemType.building, 2, 'Progressive woc_chaos_altar_special_gate_settlement', 'Cnu Building: Fortified Chaos Altar'),
    60416: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_1', ItemType.building, 0, 'Progressive woc_chaos_altar_special_gate_towers', 'Cnu Building: Lookout Post'),
    60417: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_2', ItemType.building, 1, 'Progressive woc_chaos_altar_special_gate_towers', 'Cnu Building: Chaos Stronghold'),
    60418: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_3', ItemType.building, 2, 'Progressive woc_chaos_altar_special_gate_towers', 'Cnu Building: Dark Bulwark'),
    60419: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_chaos_monsters_1', ItemType.building, 0, 'Progressive woc_dark_fortress_chaos_monsters', 'Cnu Building: Spawn Cave'),
    60420: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_chaos_monsters_2', ItemType.building, 1, 'Progressive woc_dark_fortress_chaos_monsters', 'Cnu Building: Monstrous Lair'),
    60421: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_1', ItemType.building, 0, 'Progressive woc_dark_fortress_growth', 'Cnu Building: Corpse Mound'),
    60422: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_2', ItemType.building, 1, 'Progressive woc_dark_fortress_growth', 'Cnu Building: Bone Pit'),
    60423: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_3', ItemType.building, 2, 'Progressive woc_dark_fortress_growth', 'Cnu Building: Flesh Tapestry'),
    60424: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_4', ItemType.building, 3, 'Progressive woc_dark_fortress_growth', 'Cnu Building: Skull Hall'),
    60425: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_1', ItemType.building, 0, 'Progressive woc_dark_fortress_income', 'Cnu Building: Raid Trophies'),
    60426: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_2', ItemType.building, 1, 'Progressive woc_dark_fortress_income', 'Cnu Building: Spoils of War'),
    60427: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_3', ItemType.building, 2, 'Progressive woc_dark_fortress_income', 'Cnu Building: Loot Heap'),
    60428: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_4', ItemType.building, 3, 'Progressive woc_dark_fortress_income', 'Cnu Building: Treasure House'),
    60429: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_1', ItemType.building, 0, 'Progressive woc_dark_fortress_knights', 'Cnu Building: Horse Barn'),
    60430: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_2', ItemType.building, 1, 'Progressive woc_dark_fortress_knights', 'Cnu Building: Ruinous Stalls'),
    60431: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_3', ItemType.building, 2, 'Progressive woc_dark_fortress_knights', 'Cnu Building: Chaos Stables'),
    60432: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_1', ItemType.building, 0, 'Progressive woc_dark_fortress_large_monsters', 'Cnu Building: Manticore Den'),
    60433: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_2', ItemType.building, 1, 'Progressive woc_dark_fortress_large_monsters', 'Cnu Building: Dark Cavern'),
    60434: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_3', ItemType.building, 2, 'Progressive woc_dark_fortress_large_monsters', "Cnu Building: Giant's Hollow"),
    60435: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_1', ItemType.building, 0, 'Progressive woc_dark_fortress_marauder', 'Cnu Building: Tribal Garrison'),
    60436: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_2', ItemType.building, 1, 'Progressive woc_dark_fortress_marauder', 'Cnu Building: Bloody Barracks'),
    60437: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_3', ItemType.building, 2, 'Progressive woc_dark_fortress_marauder', 'Cnu Building: Hall of Axes'),
    60438: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_1', ItemType.building, 0, 'Progressive woc_dark_fortress_shrine', 'Cnu Building: Chaos Shrine'),
    60439: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_2', ItemType.building, 1, 'Progressive woc_dark_fortress_shrine', "Cnu Building: Shaman's Temple"),
    60440: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_3', ItemType.building, 2, 'Progressive woc_dark_fortress_shrine', 'Cnu Building: Profane Sanctum'),
    60441: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_1', ItemType.building, 0, 'Progressive woc_dark_fortress_towers', 'Cnu Building: Haunted Tower'),
    60442: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_2', ItemType.building, 1, 'Progressive woc_dark_fortress_towers', 'Cnu Building: Guarded Tower'),
    60443: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_3', ItemType.building, 2, 'Progressive woc_dark_fortress_towers', 'Cnu Building: Armoured Tower'),
    60444: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_vassals_1', ItemType.building, 0, 'Progressive woc_dark_fortress_vassals', 'Cnu Building: Vassal Emissary'),
    60445: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_vassals_2', ItemType.building, 1, 'Progressive woc_dark_fortress_vassals', 'Cnu Building: Strategy Chamber'),
    60446: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_1', ItemType.building, 0, 'Progressive woc_dark_fortress_warriors', "Cnu Building: Fighters' Lodge"),
    60447: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_2', ItemType.building, 1, 'Progressive woc_dark_fortress_warriors', "Cnu Building: Guards' Barracks"),
    60448: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_3', ItemType.building, 2, 'Progressive woc_dark_fortress_warriors', "Cnu Building: Warriors' Hall"),
    60449: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_animals_1', ItemType.building, 0, 'Progressive woc_resource_animals', 'Cnu Building: Cultist Camp (Animals)'),
    60450: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_dyes_1', ItemType.building, 0, 'Progressive woc_resource_dyes', 'Cnu Building: Cultist Camp (Dyes)'),
    60451: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_furs_1', ItemType.building, 0, 'Progressive woc_resource_furs', 'Cnu Building: Cultist Camp (Furs)'),
    60452: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_gems_1', ItemType.building, 0, 'Progressive woc_resource_gems', 'Cnu Building: Cultist Camp (Gems)'),
    60453: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_gold_1', ItemType.building, 0, 'Progressive woc_resource_gold', 'Cnu Building: Cultist Camp (Gold)'),
    60454: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_iron_1', ItemType.building, 0, 'Progressive woc_resource_iron', 'Cnu Building: Cultist Camp (Iron)'),
    60455: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_ivory_1', ItemType.building, 0, 'Progressive woc_resource_ivory', 'Cnu Building: Cultist Camp (Tusks)'),
    60456: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_marble_1', ItemType.building, 0, 'Progressive woc_resource_marble', 'Cnu Building: Cultist Camp (Marble)'),
    60457: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_medicine_1', ItemType.building, 0, 'Progressive woc_resource_medicine', 'Cnu Building: Cultist Camp (Medicine)'),
    60458: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_obsidian_1', ItemType.building, 0, 'Progressive woc_resource_obsidian', 'Cnu Building: Cultist Camp (Obsidian)'),
    60459: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_pasture_1', ItemType.building, 0, 'Progressive woc_resource_pasture', 'Cnu Building: Cultist Camp (Pasture)'),
    60460: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_pottery_1', ItemType.building, 0, 'Progressive woc_resource_pottery', 'Cnu Building: Cultist Camp (Pottery)'),
    60461: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_salt_1', ItemType.building, 0, 'Progressive woc_resource_salt', 'Cnu Building: Cultist Camp (Salt)'),
    60462: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_spices_1', ItemType.building, 0, 'Progressive woc_resource_spices', 'Cnu Building: Cultist Camp (Spices)'),
    60463: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_wine_1', ItemType.building, 0, 'Progressive woc_resource_wine', 'Cnu Building: Cultist Camp (Wine)'),
    60464: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_wood_1', ItemType.building, 0, 'Progressive woc_resource_wood', 'Cnu Building: Cultist Camp (Wood)')
}

techs: dict[int, ItemData] = {
    60800: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_weapons', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Hideous Amputation'),
    60801: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_magic', ItemType.tech, 3, 'Progressive chs_nur', 'Cnu Tech: Human Trials'),
    60802: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_gift_slot_2', ItemType.tech, 4, 'Progressive chs_nur', 'Cnu Tech: Virulent Blessings'),
    60803: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_shared_gift_upgrade_summons', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Rampant Plaguebearers'),
    60804: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_military_1', ItemType.tech, 2, 'Progressive chs_nur', 'Cnu Tech: Rotten Relics'),
    60805: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_military_2', ItemType.tech, 6, 'Progressive chs_nur', 'Cnu Tech: Prayers of Sickness'),
    60806: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_daemonic_mounts', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Daemon Mounts'),
    60807: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_upgrades', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Inscribed Chaos Armour'),
    60808: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_chosen', ItemType.tech, 1, 'Progressive chs_und', 'Cnu Tech: Rite of Ascension'),
    60809: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_knights', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Profane Weaponry'),
    60810: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_beasts', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Unchained Beasts'),
    60811: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_diplomacy', ItemType.tech, 1, 'Progressive chs_und', 'Cnu Tech: Dark Diplomacy'),
    60812: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_gift_slot_3', ItemType.tech, 7, 'Progressive chs_nur', 'Cnu Tech: Doctor of Death'),
    60813: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_ultimate', ItemType.tech, 8, 'Progressive chs_nur', 'Cnu Tech: Blasphemous Summons'),
    60814: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_marks_nurgle', ItemType.tech, 3, 'Progressive chs_und', 'Cnu Tech: Rusted Branding Iron'),
    60815: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_shared_gift_upgrade_authority', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Rotten Altar'),
    60816: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_marauders', ItemType.tech, 0, 'Progressive chs_und', 'Cnu Tech: Scrutiny of the Dark Gods'),
    60817: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_gift_slot_2', ItemType.tech, 3, 'Progressive chs_und', 'Cnu Tech: Gaze of the Dark Gods'),
    60818: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_chariots', ItemType.tech, 1, 'Progressive chs_und', 'Cnu Tech: Charioteer'),
    60819: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_monsters', ItemType.tech, 3, 'Progressive chs_und', 'Cnu Tech: Giant Manacles'),
    60820: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_gift_slot_1', ItemType.tech, 3, 'Progressive chs_und', 'Cnu Tech: Daemonic Pact'),
    60821: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_building', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Erection of Ruinous Monuments'),
    60822: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_movement', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Infernal March'),
    60823: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_souls', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Culling of the Weak'),
    60824: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_mutants', ItemType.tech, 1, 'Progressive chs_und', 'Cnu Tech: A Thousand Twisted Blessings'),
    60825: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_corruption', ItemType.tech, 3, 'Progressive chs_und', 'Cnu Tech: Malignant Totems'),
    60826: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_shared_gift_upgrade_corruption', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Swamp of Souls'),
    60827: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_plagues', ItemType.tech, 6, 'Progressive chs_nur', 'Cnu Tech: Experimental Diseases'),
    60828: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_vassals', ItemType.tech, 2, 'Progressive chs_und', 'Cnu Tech: Slaves to Darkness'),
    60829: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_buildings', ItemType.tech, 3, 'Progressive chs_nur', 'Cnu Tech: Rancid Structures'),
    60830: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_gift_slot_1', ItemType.tech, 4, 'Progressive chs_nur', 'Cnu Tech: Maddening Gifts'),
    60831: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_shared_gift_upgrade_diplomacy', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Messenger of Decay'),
    60832: ItemData(IC.useful, 1, 'wh3_dlc20_chs_nur_festus_heroes_lords', ItemType.tech, 5, 'Progressive chs_nur', 'Cnu Tech: Powerful Patients')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    61300: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_woc', ItemType.building, 1, None, 'Progressive Cnu Building: Foreign Slot Discovery Woc'),
    61301: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_woc', ItemType.building, 2, None, 'Progressive Cnu Building: Foreign Slot Discovery Woc'),
    61302: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_woc', ItemType.building, 3, None, 'Progressive Cnu Building: Foreign Slot Discovery Woc'),
    61303: ItemData(IC.useful, 1, 'Progressive settlement_woc_dark_fortress', ItemType.building, 1, None, 'Progressive Cnu Building: Settlement Woc Dark Fortress'),
    61304: ItemData(IC.useful, 2, 'Progressive settlement_woc_dark_fortress', ItemType.building, 2, None, 'Progressive Cnu Building: Settlement Woc Dark Fortress'),
    61305: ItemData(IC.useful, 3, 'Progressive settlement_woc_dark_fortress', ItemType.building, 3, None, 'Progressive Cnu Building: Settlement Woc Dark Fortress'),
    61306: ItemData(IC.useful, 4, 'Progressive settlement_woc_dark_fortress', ItemType.building, 4, None, 'Progressive Cnu Building: Settlement Woc Dark Fortress'),
    61307: ItemData(IC.useful, 5, 'Progressive settlement_woc_dark_fortress', ItemType.building, 5, None, 'Progressive Cnu Building: Settlement Woc Dark Fortress'),
    61308: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_corruption', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Corruption'),
    61309: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_garrison', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Garrison'),
    61310: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_major_human', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Chaos Altar Major Human'),
    61311: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_recruit', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Recruit'),
    61312: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_replenishment', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Replenishment'),
    61313: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Settlement'),
    61314: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Settlement'),
    61315: ItemData(IC.useful, 3, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Settlement'),
    61316: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Towers'),
    61317: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Towers'),
    61318: ItemData(IC.useful, 3, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Chaos Altar Special Gate Towers'),
    61319: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_chaos_monsters', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Chaos Monsters'),
    61320: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_chaos_monsters', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Chaos Monsters'),
    61321: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_growth', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Growth'),
    61322: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_growth', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Growth'),
    61323: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_growth', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Growth'),
    61324: ItemData(IC.useful, 4, 'Progressive woc_dark_fortress_growth', ItemType.building, 4, None, 'Progressive Cnu Building: Woc Dark Fortress Growth'),
    61325: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_income', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Income'),
    61326: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_income', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Income'),
    61327: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_income', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Income'),
    61328: ItemData(IC.useful, 4, 'Progressive woc_dark_fortress_income', ItemType.building, 4, None, 'Progressive Cnu Building: Woc Dark Fortress Income'),
    61329: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_knights', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Knights'),
    61330: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_knights', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Knights'),
    61331: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_knights', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Knights'),
    61332: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Large Monsters'),
    61333: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Large Monsters'),
    61334: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Large Monsters'),
    61335: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_marauder', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Marauder'),
    61336: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_marauder', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Marauder'),
    61337: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_marauder', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Marauder'),
    61338: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_shrine', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Shrine'),
    61339: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_shrine', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Shrine'),
    61340: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_shrine', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Shrine'),
    61341: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_towers', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Towers'),
    61342: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_towers', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Towers'),
    61343: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_towers', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Towers'),
    61344: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_vassals', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Vassals'),
    61345: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_vassals', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Vassals'),
    61346: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_warriors', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dark Fortress Warriors'),
    61347: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_warriors', ItemType.building, 2, None, 'Progressive Cnu Building: Woc Dark Fortress Warriors'),
    61348: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_warriors', ItemType.building, 3, None, 'Progressive Cnu Building: Woc Dark Fortress Warriors'),
    61349: ItemData(IC.useful, 1, 'Progressive woc_resource_animals', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Animals'),
    61350: ItemData(IC.useful, 1, 'Progressive woc_resource_dyes', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Dyes'),
    61351: ItemData(IC.useful, 1, 'Progressive woc_resource_furs', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Furs'),
    61352: ItemData(IC.useful, 1, 'Progressive woc_resource_gems', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Gems'),
    61353: ItemData(IC.useful, 1, 'Progressive woc_resource_gold', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Gold'),
    61354: ItemData(IC.useful, 1, 'Progressive woc_resource_iron', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Iron'),
    61355: ItemData(IC.useful, 1, 'Progressive woc_resource_ivory', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Ivory'),
    61356: ItemData(IC.useful, 1, 'Progressive woc_resource_marble', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Marble'),
    61357: ItemData(IC.useful, 1, 'Progressive woc_resource_medicine', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Medicine'),
    61358: ItemData(IC.useful, 1, 'Progressive woc_resource_obsidian', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Obsidian'),
    61359: ItemData(IC.useful, 1, 'Progressive woc_resource_pasture', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Pasture'),
    61360: ItemData(IC.useful, 1, 'Progressive woc_resource_pottery', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Pottery'),
    61361: ItemData(IC.useful, 1, 'Progressive woc_resource_salt', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Salt'),
    61362: ItemData(IC.useful, 1, 'Progressive woc_resource_spices', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Spices'),
    61363: ItemData(IC.useful, 1, 'Progressive woc_resource_wine', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Wine'),
    61364: ItemData(IC.useful, 1, 'Progressive woc_resource_wood', ItemType.building, 1, None, 'Progressive Cnu Building: Woc Wood')
}

progTechs: dict[int, ItemData] = {

}

special: dict[int, ItemData] = {

}