from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    64000: ItemData(IC.useful, 1, 'wh3_twa08_tze_mon_lord_of_change_0_ror', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: The Golden Griffin of Theurgy (Lord of Change)'),
    64001: ItemData(IC.useful, 1, 'wh3_main_tze_mon_spawn_of_tzeentch_0', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Spawn of Tzeentch'),
    64002: ItemData(IC.useful, 1, 'wh3_main_tze_mon_soul_grinder_0', ItemType.unit, 4, 'Progressive chs_rng', 'Ctz Unit: Soul Grinder of Tzeentch'),
    64003: ItemData(IC.useful, 1, 'wh3_main_tze_mon_lord_of_change_0', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: Lord of Change'),
    64004: ItemData(IC.useful, 1, 'wh3_main_tze_mon_flamers_0', ItemType.unit, 2, 'Progressive chs_rng', 'Ctz Unit: Flamers of Tzeentch'),
    64005: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_1', ItemType.unit, 3, 'Progressive chs_rng', 'Ctz Unit: Exalted Pink Horrors of Tzeentch'),
    64006: ItemData(IC.useful, 1, 'wh3_main_tze_inf_pink_horrors_0', ItemType.unit, 2, 'Progressive chs_rng', 'Ctz Unit: Pink Horrors of Tzeentch'),
    64007: ItemData(IC.useful, 1, 'wh3_main_tze_inf_forsaken_0', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Forsaken of Tzeentch'),
    64008: ItemData(IC.useful, 1, 'wh3_main_tze_cav_doom_knights_0', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: Doom Knights of Tzeentch'),
    64009: ItemData(IC.useful, 1, 'wh3_main_tze_cav_chaos_knights_0', ItemType.unit, 3, 'war_beast', 'Ctz Unit: Chaos Knights of Tzeentch'),
    64010: ItemData(IC.useful, 1, 'wh3_main_dae_inf_chaos_furies_0', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Furies'),
    64011: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_mutalith_vortex_beast', ItemType.unit, 5, 'Progressive chs_inf', 'Ctz Unit: Mutalith Vortex Beast'),
    64012: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_flamers_changebringers', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: Changebringers'),
    64013: ItemData(IC.useful, 1, 'wh3_dlc24_tze_mon_cockatrice', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Cockatrice'),
    64014: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_tzaangors', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Tzaangors'),
    64015: ItemData(IC.useful, 1, 'wh3_dlc24_tze_inf_centigors_great_weapons', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Centigors of Tzeentch'),
    64016: ItemData(IC.useful, 1, 'wh3_dlc20_tze_cha_vilitch', ItemType.unit, 0, 'Progressive chs_inf', 'Ctz Unit: Vilitch the Curseling'),
    64017: ItemData(IC.useful, 1, 'wh3_dlc20_tze_cha_cultist_mtze_warshrine', ItemType.unit, 0, 'war_beast', 'Ctz Unit: Cultist of Tzeentch'),
    64018: ItemData(IC.useful, 1, 'wh3_dlc20_chs_mon_warshrine_mtze', ItemType.unit, 3, 'war_beast', 'Ctz Unit: Chaos Warshrine of Tzeentch'),
    64019: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mtze_halberds', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: Chosen of Tzeentch (Halberds)'),
    64020: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chosen_mtze', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chosen of Tzeentch'),
    64021: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Warriors of Tzeentch (Halberds)'),
    64022: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_warriors_mtze', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Warriors of Tzeentch'),
    64023: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mtze_spears', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Marauders of Tzeentch (Spears)'),
    64024: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_chaos_marauders_mtze', ItemType.unit, 1, 'Progressive chs_inf', 'Ctz Unit: Marauders of Tzeentch'),
    64025: ItemData(IC.useful, 1, 'wh3_dlc20_chs_inf_aspiring_champions_mtze_ror', ItemType.unit, 4, 'Progressive chs_inf', 'Ctz Unit: The Severed Claw (Aspiring Champions)'),
    64051: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins', ItemType.unit, 2, 'war_beast', 'Ctz Unit: Marauder Horsemen of Tzeentch'),
    64052: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_knights_mtze_lances', ItemType.unit, 4, 'war_beast', 'Ctz Unit: Chaos Knights of Tzeentch (Lances)'),
    64053: ItemData(IC.useful, 1, 'wh3_dlc20_chs_cav_chaos_chariot_mtze', ItemType.unit, 2, 'Progressive chs_veh', 'Ctz Unit: Chaos Chariots of Tzeentch'),
    64054: ItemData(IC.useful, 1, 'wh_main_chs_mon_trolls', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Trolls'),
    64055: ItemData(IC.useful, 1, 'wh_main_chs_mon_giant', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chaos Giant'),
    64056: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_1', ItemType.unit, 1, 'Progressive chs_inf', 'Ctz Unit: Chaos Warhounds (Poison)'),
    64057: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_warhounds_0', ItemType.unit, 1, 'Progressive chs_inf', 'Ctz Unit: Chaos Warhounds'),
    64058: ItemData(IC.useful, 1, 'wh_main_chs_mon_chaos_spawn', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chaos Spawn'),
    64059: ItemData(IC.useful, 1, 'wh_main_chs_inf_chosen_1', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chosen (Great Weapons)'),
    64060: ItemData(IC.useful, 1, 'wh_main_chs_inf_chosen_0', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chosen'),
    64061: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_warriors_1', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Warriors (Halberds)'),
    64062: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_warriors_0', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Warriors'),
    64063: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_marauders_1', ItemType.unit, 1, 'Progressive chs_inf', 'Ctz Unit: Marauders (Great Weapons)'),
    64064: ItemData(IC.useful, 1, 'wh_main_chs_inf_chaos_marauders_0', ItemType.unit, 1, 'Progressive chs_inf', 'Ctz Unit: Marauders'),
    64088: ItemData(IC.useful, 1, 'wh_main_chs_cav_marauder_horsemen_1', ItemType.unit, 2, 'war_beast', 'Ctz Unit: Marauder Horsemen (Throwing Axes)'),
    64089: ItemData(IC.useful, 1, 'wh_main_chs_cav_marauder_horsemen_0', ItemType.unit, 2, 'war_beast', 'Ctz Unit: Marauder Horsemen'),
    64090: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_knights_1', ItemType.unit, 3, 'war_beast', 'Ctz Unit: Chaos Knights (Lances)'),
    64091: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_knights_0', ItemType.unit, 3, 'war_beast', 'Ctz Unit: Chaos Knights'),
    64092: ItemData(IC.useful, 1, 'wh_main_chs_cav_chaos_chariot', ItemType.unit, 2, 'Progressive chs_veh', 'Ctz Unit: Chaos Chariots'),
    64093: ItemData(IC.useful, 1, 'wh_dlc06_chs_inf_aspiring_champions_0', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Aspiring Champions'),
    64094: ItemData(IC.useful, 1, 'wh_dlc06_chs_feral_manticore', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Feral Manticore'),
    64095: ItemData(IC.useful, 1, 'wh_dlc06_chs_cav_marauder_horsemasters_0', ItemType.unit, 2, 'war_beast', 'Ctz Unit: Marauder Horsemasters'),
    64096: ItemData(IC.useful, 1, 'wh_dlc01_chs_mon_trolls_1', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Trolls (Armoured)'),
    64097: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_forsaken_0', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Forsaken'),
    64098: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_chosen_2', ItemType.unit, 3, 'Progressive chs_inf', 'Ctz Unit: Chosen (Halberds)'),
    64099: ItemData(IC.useful, 1, 'wh_dlc01_chs_inf_chaos_warriors_2', ItemType.unit, 2, 'Progressive chs_inf', 'Ctz Unit: Chaos Warriors (Great Weapons)'),
    64100: ItemData(IC.useful, 1, 'wh_dlc01_chs_cha_qb_lord_of_change_0', ItemType.unit, 0, 'Progressive chs_inf', 'Ctz Unit: Lord of Change'),
    64141: ItemData(IC.useful, 1, 'wh_dlc01_chs_cav_gorebeast_chariot', ItemType.unit, 3, 'Progressive chs_veh', 'Ctz Unit: Gorebeast Chariots')
}

buildings: dict[int, ItemData] = {
    64400: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_woc', 'Ctz Building: Rat Catcher Outpost'),
    64401: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_woc', "Ctz Building: Catchers' Camp"),
    64402: ItemData(IC.useful, 1, 'wh3_dlc20_foreign_slot_discovery_woc_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_woc', 'Ctz Building: Vermin Slayers'),
    64403: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_1', ItemType.building, 0, 'Progressive settlement_woc_dark_fortress', 'Ctz Building: Chaos Keep'),
    64404: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_2', ItemType.building, 1, 'Progressive settlement_woc_dark_fortress', 'Ctz Building: Chaos Fort'),
    64405: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_3', ItemType.building, 2, 'Progressive settlement_woc_dark_fortress', 'Ctz Building: Dark Redoubt'),
    64406: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_4', ItemType.building, 3, 'Progressive settlement_woc_dark_fortress', 'Ctz Building: Dark Fortress'),
    64407: ItemData(IC.useful, 1, 'wh3_dlc20_settlement_woc_dark_fortress_5', ItemType.building, 4, 'Progressive settlement_woc_dark_fortress', 'Ctz Building: Exalted Dark Fortress'),
    64408: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_corruption_1', ItemType.building, 0, 'Progressive woc_chaos_altar_corruption', 'Ctz Building: Twisted Relic'),
    64409: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_garrison_1', ItemType.building, 0, 'Progressive woc_chaos_altar_garrison', 'Ctz Building: Warband Camp'),
    64410: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_major_human_1', ItemType.building, 1, 'Progressive woc_chaos_altar_major_human', 'Ctz Building: Chaos Altar'),
    64411: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_recruit_1', ItemType.building, 0, 'Progressive woc_chaos_altar_recruit', 'Ctz Building: Bleeding Grounds'),
    64412: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_replenishment_1', ItemType.building, 0, 'Progressive woc_chaos_altar_replenishment', 'Ctz Building: Ritual Hut'),
    64413: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_1', ItemType.building, 0, 'Progressive woc_chaos_altar_special_gate_settlement', 'Ctz Building: Barricaded Chaos Altar'),
    64414: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_2', ItemType.building, 1, 'Progressive woc_chaos_altar_special_gate_settlement', 'Ctz Building: Reinforced Chaos Altar'),
    64415: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_settlement_3', ItemType.building, 2, 'Progressive woc_chaos_altar_special_gate_settlement', 'Ctz Building: Fortified Chaos Altar'),
    64416: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_1', ItemType.building, 0, 'Progressive woc_chaos_altar_special_gate_towers', 'Ctz Building: Lookout Post'),
    64417: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_2', ItemType.building, 1, 'Progressive woc_chaos_altar_special_gate_towers', 'Ctz Building: Chaos Stronghold'),
    64418: ItemData(IC.useful, 1, 'wh3_dlc20_woc_chaos_altar_special_gate_towers_3', ItemType.building, 2, 'Progressive woc_chaos_altar_special_gate_towers', 'Ctz Building: Dark Bulwark'),
    64419: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_chaos_monsters_1', ItemType.building, 0, 'Progressive woc_dark_fortress_chaos_monsters', 'Ctz Building: Spawn Cave'),
    64420: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_chaos_monsters_2', ItemType.building, 1, 'Progressive woc_dark_fortress_chaos_monsters', 'Ctz Building: Monstrous Lair'),
    64421: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_1', ItemType.building, 0, 'Progressive woc_dark_fortress_growth', 'Ctz Building: Corpse Mound'),
    64422: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_2', ItemType.building, 1, 'Progressive woc_dark_fortress_growth', 'Ctz Building: Bone Pit'),
    64423: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_3', ItemType.building, 2, 'Progressive woc_dark_fortress_growth', 'Ctz Building: Flesh Tapestry'),
    64424: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_growth_4', ItemType.building, 3, 'Progressive woc_dark_fortress_growth', 'Ctz Building: Skull Hall'),
    64425: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_1', ItemType.building, 0, 'Progressive woc_dark_fortress_income', 'Ctz Building: Raid Trophies'),
    64426: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_2', ItemType.building, 1, 'Progressive woc_dark_fortress_income', 'Ctz Building: Spoils of War'),
    64427: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_3', ItemType.building, 2, 'Progressive woc_dark_fortress_income', 'Ctz Building: Loot Heap'),
    64428: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_income_4', ItemType.building, 3, 'Progressive woc_dark_fortress_income', 'Ctz Building: Treasure House'),
    64429: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_1', ItemType.building, 0, 'Progressive woc_dark_fortress_knights', 'Ctz Building: Horse Barn'),
    64430: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_2', ItemType.building, 1, 'Progressive woc_dark_fortress_knights', 'Ctz Building: Ruinous Stalls'),
    64431: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_knights_3', ItemType.building, 2, 'Progressive woc_dark_fortress_knights', 'Ctz Building: Chaos Stables'),
    64432: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_1', ItemType.building, 0, 'Progressive woc_dark_fortress_large_monsters', 'Ctz Building: Manticore Den'),
    64433: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_2', ItemType.building, 1, 'Progressive woc_dark_fortress_large_monsters', 'Ctz Building: Dark Cavern'),
    64434: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_large_monsters_3', ItemType.building, 2, 'Progressive woc_dark_fortress_large_monsters', "Ctz Building: Giant's Hollow"),
    64435: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_1', ItemType.building, 0, 'Progressive woc_dark_fortress_marauder', 'Ctz Building: Tribal Garrison'),
    64436: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_2', ItemType.building, 1, 'Progressive woc_dark_fortress_marauder', 'Ctz Building: Bloody Barracks'),
    64437: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_marauder_3', ItemType.building, 2, 'Progressive woc_dark_fortress_marauder', 'Ctz Building: Hall of Axes'),
    64438: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_1', ItemType.building, 0, 'Progressive woc_dark_fortress_shrine', 'Ctz Building: Chaos Shrine'),
    64439: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_2', ItemType.building, 1, 'Progressive woc_dark_fortress_shrine', "Ctz Building: Shaman's Temple"),
    64440: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_shrine_3', ItemType.building, 2, 'Progressive woc_dark_fortress_shrine', 'Ctz Building: Profane Sanctum'),
    64441: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_1', ItemType.building, 0, 'Progressive woc_dark_fortress_towers', 'Ctz Building: Haunted Tower'),
    64442: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_2', ItemType.building, 1, 'Progressive woc_dark_fortress_towers', 'Ctz Building: Guarded Tower'),
    64443: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_towers_3', ItemType.building, 2, 'Progressive woc_dark_fortress_towers', 'Ctz Building: Armoured Tower'),
    64444: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_vassals_1', ItemType.building, 0, 'Progressive woc_dark_fortress_vassals', 'Ctz Building: Vassal Emissary'),
    64445: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_vassals_2', ItemType.building, 1, 'Progressive woc_dark_fortress_vassals', 'Ctz Building: Strategy Chamber'),
    64446: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_1', ItemType.building, 0, 'Progressive woc_dark_fortress_warriors', "Ctz Building: Fighters' Lodge"),
    64447: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_2', ItemType.building, 1, 'Progressive woc_dark_fortress_warriors', "Ctz Building: Guards' Barracks"),
    64448: ItemData(IC.useful, 1, 'wh3_dlc20_woc_dark_fortress_warriors_3', ItemType.building, 2, 'Progressive woc_dark_fortress_warriors', "Ctz Building: Warriors' Hall"),
    64449: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_animals_1', ItemType.building, 0, 'Progressive woc_resource_animals', 'Ctz Building: Cultist Camp (Animals)'),
    64450: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_dyes_1', ItemType.building, 0, 'Progressive woc_resource_dyes', 'Ctz Building: Cultist Camp (Dyes)'),
    64451: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_furs_1', ItemType.building, 0, 'Progressive woc_resource_furs', 'Ctz Building: Cultist Camp (Furs)'),
    64452: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_gems_1', ItemType.building, 0, 'Progressive woc_resource_gems', 'Ctz Building: Cultist Camp (Gems)'),
    64453: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_gold_1', ItemType.building, 0, 'Progressive woc_resource_gold', 'Ctz Building: Cultist Camp (Gold)'),
    64454: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_iron_1', ItemType.building, 0, 'Progressive woc_resource_iron', 'Ctz Building: Cultist Camp (Iron)'),
    64455: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_ivory_1', ItemType.building, 0, 'Progressive woc_resource_ivory', 'Ctz Building: Cultist Camp (Tusks)'),
    64456: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_marble_1', ItemType.building, 0, 'Progressive woc_resource_marble', 'Ctz Building: Cultist Camp (Marble)'),
    64457: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_medicine_1', ItemType.building, 0, 'Progressive woc_resource_medicine', 'Ctz Building: Cultist Camp (Medicine)'),
    64458: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_obsidian_1', ItemType.building, 0, 'Progressive woc_resource_obsidian', 'Ctz Building: Cultist Camp (Obsidian)'),
    64459: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_pasture_1', ItemType.building, 0, 'Progressive woc_resource_pasture', 'Ctz Building: Cultist Camp (Pasture)'),
    64460: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_pottery_1', ItemType.building, 0, 'Progressive woc_resource_pottery', 'Ctz Building: Cultist Camp (Pottery)'),
    64461: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_salt_1', ItemType.building, 0, 'Progressive woc_resource_salt', 'Ctz Building: Cultist Camp (Salt)'),
    64462: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_spices_1', ItemType.building, 0, 'Progressive woc_resource_spices', 'Ctz Building: Cultist Camp (Spices)'),
    64463: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_wine_1', ItemType.building, 0, 'Progressive woc_resource_wine', 'Ctz Building: Cultist Camp (Wine)'),
    64464: ItemData(IC.useful, 1, 'wh3_dlc20_woc_resource_wood_1', ItemType.building, 0, 'Progressive woc_resource_wood', 'Ctz Building: Cultist Camp (Wood)')
}

techs: dict[int, ItemData] = {
    64800: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_weapons', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Ritual Staff'),
    64801: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_spells', ItemType.tech, 3, 'Progressive chs_tze', 'Ctz Tech: Twisted Tome'),
    64802: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_gift_slot_2', ItemType.tech, 4, 'Progressive chs_tze', 'Ctz Tech: Attuning Ritual'),
    64803: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_shared_gift_upgrade_summons', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Pink Horrors'),
    64804: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_military_1', ItemType.tech, 2, 'Progressive chs_tze', 'Ctz Tech: Temple of Tzeentch'),
    64805: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_military_2', ItemType.tech, 6, 'Progressive chs_tze', 'Ctz Tech: Enchanted Armour'),
    64806: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_daemonic_mounts', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Daemon Mounts'),
    64807: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_upgrades', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Inscribed Chaos Armour'),
    64808: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_chosen', ItemType.tech, 1, 'Progressive chs_und', 'Ctz Tech: Rite of Ascension'),
    64809: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_knights', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Profane Weaponry'),
    64810: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_beasts', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Unchained Beasts'),
    64811: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_diplomacy', ItemType.tech, 1, 'Progressive chs_und', 'Ctz Tech: Dark Diplomacy'),
    64812: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_gift_slot_3', ItemType.tech, 7, 'Progressive chs_tze', 'Ctz Tech: Chaos Moon'),
    64813: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_ultimate', ItemType.tech, 8, 'Progressive chs_tze', 'Ctz Tech: Unholy Intervention'),
    64814: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_marks_tzeentch', ItemType.tech, 3, 'Progressive chs_und', 'Ctz Tech: Arcane Branding Iron'),
    64815: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_shared_gift_upgrade_authority', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Mystical Banner'),
    64816: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_marauders', ItemType.tech, 0, 'Progressive chs_und', 'Ctz Tech: Scrutiny of the Dark Gods'),
    64817: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_gift_slot_2', ItemType.tech, 3, 'Progressive chs_und', 'Ctz Tech: Gaze of the Dark Gods'),
    64818: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_chariots', ItemType.tech, 1, 'Progressive chs_und', 'Ctz Tech: Charioteer'),
    64819: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_monsters', ItemType.tech, 3, 'Progressive chs_und', 'Ctz Tech: Giant Manacles'),
    64820: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_gift_slot_1', ItemType.tech, 3, 'Progressive chs_und', 'Ctz Tech: Daemonic Pact'),
    64821: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_building', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Erection of Ruinous Monuments'),
    64822: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_movement', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Infernal March'),
    64823: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_souls', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Culling of the Weak'),
    64824: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_mutants', ItemType.tech, 1, 'Progressive chs_und', 'Ctz Tech: A Thousand Twisted Blessings'),
    64825: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_corruption', ItemType.tech, 3, 'Progressive chs_und', 'Ctz Tech: Malignant Totems'),
    64826: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_shared_gift_upgrade_corruption', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Enchanted Idols'),
    64827: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_teleport', ItemType.tech, 6, 'Progressive chs_tze', 'Ctz Tech: Teleportation Stone'),
    64828: ItemData(IC.useful, 1, 'wh3_dlc20_chs_und_shared_vassals', ItemType.tech, 2, 'Progressive chs_und', 'Ctz Tech: Slaves to Darkness'),
    64829: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_buildings', ItemType.tech, 3, 'Progressive chs_tze', 'Ctz Tech: Arcane Construction'),
    64830: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_gift_slot_1', ItemType.tech, 4, 'Progressive chs_tze', 'Ctz Tech: Dark Meditation'),
    64831: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_shared_gift_upgrade_diplomacy', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Sacrificial Prophecy'),
    64832: ItemData(IC.useful, 1, 'wh3_dlc20_chs_tze_vilitch_heroes_lords', ItemType.tech, 5, 'Progressive chs_tze', 'Ctz Tech: Summoning Rite')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    65300: ItemData(IC.useful, 1, 'Progressive foreign_slot_discovery_woc', ItemType.building, 1, None, 'Progressive Ctz Building: Foreign Slot Discovery Woc'),
    65301: ItemData(IC.useful, 2, 'Progressive foreign_slot_discovery_woc', ItemType.building, 2, None, 'Progressive Ctz Building: Foreign Slot Discovery Woc'),
    65302: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_woc', ItemType.building, 3, None, 'Progressive Ctz Building: Foreign Slot Discovery Woc'),
    65303: ItemData(IC.useful, 1, 'Progressive settlement_woc_dark_fortress', ItemType.building, 1, None, 'Progressive Ctz Building: Settlement Woc Dark Fortress'),
    65304: ItemData(IC.useful, 2, 'Progressive settlement_woc_dark_fortress', ItemType.building, 2, None, 'Progressive Ctz Building: Settlement Woc Dark Fortress'),
    65305: ItemData(IC.useful, 3, 'Progressive settlement_woc_dark_fortress', ItemType.building, 3, None, 'Progressive Ctz Building: Settlement Woc Dark Fortress'),
    65306: ItemData(IC.useful, 4, 'Progressive settlement_woc_dark_fortress', ItemType.building, 4, None, 'Progressive Ctz Building: Settlement Woc Dark Fortress'),
    65307: ItemData(IC.useful, 5, 'Progressive settlement_woc_dark_fortress', ItemType.building, 5, None, 'Progressive Ctz Building: Settlement Woc Dark Fortress'),
    65308: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_corruption', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Corruption'),
    65309: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_garrison', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Garrison'),
    65310: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_major_human', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Chaos Altar Major Human'),
    65311: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_recruit', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Recruit'),
    65312: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_replenishment', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Replenishment'),
    65313: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Settlement'),
    65314: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Settlement'),
    65315: ItemData(IC.useful, 3, 'Progressive woc_chaos_altar_special_gate_settlement', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Settlement'),
    65316: ItemData(IC.useful, 1, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Towers'),
    65317: ItemData(IC.useful, 2, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Towers'),
    65318: ItemData(IC.useful, 3, 'Progressive woc_chaos_altar_special_gate_towers', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Chaos Altar Special Gate Towers'),
    65319: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_chaos_monsters', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Chaos Monsters'),
    65320: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_chaos_monsters', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Chaos Monsters'),
    65321: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_growth', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Growth'),
    65322: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_growth', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Growth'),
    65323: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_growth', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Growth'),
    65324: ItemData(IC.useful, 4, 'Progressive woc_dark_fortress_growth', ItemType.building, 4, None, 'Progressive Ctz Building: Woc Dark Fortress Growth'),
    65325: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_income', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Income'),
    65326: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_income', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Income'),
    65327: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_income', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Income'),
    65328: ItemData(IC.useful, 4, 'Progressive woc_dark_fortress_income', ItemType.building, 4, None, 'Progressive Ctz Building: Woc Dark Fortress Income'),
    65329: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_knights', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Knights'),
    65330: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_knights', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Knights'),
    65331: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_knights', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Knights'),
    65332: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Large Monsters'),
    65333: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Large Monsters'),
    65334: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_large_monsters', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Large Monsters'),
    65335: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_marauder', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Marauder'),
    65336: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_marauder', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Marauder'),
    65337: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_marauder', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Marauder'),
    65338: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_shrine', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Shrine'),
    65339: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_shrine', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Shrine'),
    65340: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_shrine', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Shrine'),
    65341: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_towers', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Towers'),
    65342: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_towers', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Towers'),
    65343: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_towers', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Towers'),
    65344: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_vassals', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Vassals'),
    65345: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_vassals', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Vassals'),
    65346: ItemData(IC.useful, 1, 'Progressive woc_dark_fortress_warriors', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dark Fortress Warriors'),
    65347: ItemData(IC.useful, 2, 'Progressive woc_dark_fortress_warriors', ItemType.building, 2, None, 'Progressive Ctz Building: Woc Dark Fortress Warriors'),
    65348: ItemData(IC.useful, 3, 'Progressive woc_dark_fortress_warriors', ItemType.building, 3, None, 'Progressive Ctz Building: Woc Dark Fortress Warriors'),
    65349: ItemData(IC.useful, 1, 'Progressive woc_resource_animals', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Animals'),
    65350: ItemData(IC.useful, 1, 'Progressive woc_resource_dyes', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Dyes'),
    65351: ItemData(IC.useful, 1, 'Progressive woc_resource_furs', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Furs'),
    65352: ItemData(IC.useful, 1, 'Progressive woc_resource_gems', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Gems'),
    65353: ItemData(IC.useful, 1, 'Progressive woc_resource_gold', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Gold'),
    65354: ItemData(IC.useful, 1, 'Progressive woc_resource_iron', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Iron'),
    65355: ItemData(IC.useful, 1, 'Progressive woc_resource_ivory', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Ivory'),
    65356: ItemData(IC.useful, 1, 'Progressive woc_resource_marble', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Marble'),
    65357: ItemData(IC.useful, 1, 'Progressive woc_resource_medicine', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Medicine'),
    65358: ItemData(IC.useful, 1, 'Progressive woc_resource_obsidian', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Obsidian'),
    65359: ItemData(IC.useful, 1, 'Progressive woc_resource_pasture', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Pasture'),
    65360: ItemData(IC.useful, 1, 'Progressive woc_resource_pottery', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Pottery'),
    65361: ItemData(IC.useful, 1, 'Progressive woc_resource_salt', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Salt'),
    65362: ItemData(IC.useful, 1, 'Progressive woc_resource_spices', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Spices'),
    65363: ItemData(IC.useful, 1, 'Progressive woc_resource_wine', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Wine'),
    65364: ItemData(IC.useful, 1, 'Progressive woc_resource_wood', ItemType.building, 1, None, 'Progressive Ctz Building: Woc Wood')
}

progTechs: dict[int, ItemData] = {

}

special: dict[int, ItemData] = {

}