from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    54000: ItemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_3', ItemType.unit, 0, 'cavalry', 'Wef Unit: Glade Captain'),
    54001: ItemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Glade Captain'),
    54002: ItemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Glade Captain'),
    54003: ItemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Glade Captain'),
    54004: ItemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats', ItemType.unit, 4, 'Progressive wef_inf', 'Wef Unit: Zoats'),
    54005: ItemData(IC.useful, 1, 'wh2_dlc16_wef_inf_bladesingers_0', ItemType.unit, 3, 'Progressive wef_inf', 'Wef Unit: Bladesingers'),
    54006: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cha_malicious_ancient_treeman_shadows_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Malevolent Ancient Treeman (Shadows)'),
    54007: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cha_malicious_ancient_treeman_life_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Malevolent Ancient Treeman (Life)'),
    54008: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cha_malicious_ancient_treeman_beasts_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Malevolent Ancient Treeman (Beasts)'),
    54009: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cha_ancient_treeman_coeddil_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Coeddil'),
    54010: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cav_great_stag_knights_0', ItemType.unit, 4, 'cavalry', 'Wef Unit: Great Stag Knights'),
    54011: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cav_glade_riders_2', ItemType.unit, 2, 'cavalry', 'Wef Unit: Glade Riders (Spears)'),
    54012: ItemData(IC.useful, 1, 'wh_dlc05_wef_mon_treeman_0', ItemType.unit, 4, 'Progressive wef_inf', 'Wef Unit: Treeman'),
    54013: ItemData(IC.useful, 1, 'wh_dlc05_wef_mon_treekin_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Tree Kin'),
    54014: ItemData(IC.useful, 1, 'wh_dlc05_wef_mon_great_eagle_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Great Eagle'),
    54015: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wildwood_rangers_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Wildwood Rangers'),
    54016: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_waywatchers_0', ItemType.unit, 3, 'Progressive wef_rng', 'Wef Unit: Waywatchers'),
    54017: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_1', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Wardancers (Asrai Spears)'),
    54018: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Wardancers'),
    54019: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_2', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Glade Guard (Hagbane Tips)'),
    54020: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_1', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Glade Guard (Starfire Shafts)'),
    54021: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_0', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Glade Guard'),
    54022: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_1', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Eternal Guard (Shields)'),
    54023: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_0', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Eternal Guard'),
    54024: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_dryads_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Dryads'),
    54025: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_1', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Deepwood Scouts (Swiftshiver Shards)'),
    54026: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_0', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Deepwood Scouts'),
    54027: ItemData(IC.useful, 1, 'wh_dlc05_wef_forest_dragon_0', ItemType.unit, 4, 'Progressive wef_inf', 'Wef Unit: Forest Dragon'),
    54028: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_waystalker_0', ItemType.unit, 0, 'Progressive wef_rng', 'Wef Unit: Waystalker'),
    54029: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_3', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Shadows)'),
    54030: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Spellsinger (Shadows)'),
    54031: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Shadows)'),
    54032: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Spellsinger (Shadows)'),
    54033: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_3', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Life)'),
    54034: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Spellsinger (Life)'),
    54035: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Life)'),
    54036: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Spellsinger (Life)'),
    54037: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_3', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Beasts)'),
    54038: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Spellsinger (Beasts)'),
    54039: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Spellsinger (Beasts)'),
    54040: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Spellsinger (Beasts)'),
    54041: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_orion_0', ItemType.unit, 0, 'Progressive wef_rng', 'Wef Unit: Orion'),
    54042: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_glade_lord_3', ItemType.unit, 0, 'war_beast', 'Wef Unit: Glade Lord'),
    54043: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_glade_lord_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Glade Lord'),
    54044: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_glade_lord_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Glade Lord'),
    54045: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_glade_lord_0', ItemType.unit, 0, 'Progressive wef_rng', 'Wef Unit: Glade Lord'),
    54046: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_female_glade_lord_3', ItemType.unit, 0, 'war_beast', 'Wef Unit: Glade Lord'),
    54047: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_female_glade_lord_2', ItemType.unit, 0, 'war_beast', 'Wef Unit: Glade Lord'),
    54048: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_female_glade_lord_1', ItemType.unit, 0, 'cavalry', 'Wef Unit: Glade Lord'),
    54049: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_female_glade_lord_0', ItemType.unit, 0, 'Progressive wef_rng', 'Wef Unit: Glade Lord'),
    54050: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_durthu_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Durthu'),
    54051: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_ancient_treeman_0', ItemType.unit, 0, 'Progressive wef_inf', 'Wef Unit: Ancient Treeman'),
    54052: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_1', ItemType.unit, 3, 'cavalry', 'Wef Unit: Wild Riders (Shields)'),
    54053: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_0', ItemType.unit, 3, 'cavalry', 'Wef Unit: Wild Riders'),
    54054: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_sisters_thorn_0', ItemType.unit, 3, 'cavalry', 'Wef Unit: Sisters of the Thorn'),
    54055: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_hawk_riders_0', ItemType.unit, 3, 'cavalry', 'Wef Unit: Hawk Riders'),
    54056: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_1', ItemType.unit, 2, 'cavalry', 'Wef Unit: Glade Riders (Hagbane Tips)'),
    54057: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_0', ItemType.unit, 2, 'cavalry', 'Wef Unit: Glade Riders')
}

buildings: dict[int, ItemData] = {
    54400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Undergrowth Lookouts'),
    54401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Woodland Trenches'),
    54402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Forest Caves'),
    54404: ItemData(IC.useful, 1, 'wh2_main_special_empire_fort_wef_1', ItemType.building, 1, 'Progressive special_empire_fort_wef', 'Wef Building: Occupied Fortress (Small Fort)'),
    54405: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_eagle_wef_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Occupied Gate (Small Fortress)'),
    54406: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_griffon_wef_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Occupied Gate (Small Fortress)'),
    54407: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_phoenix_wef_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Occupied Gate (Small Fortress)'),
    54408: ItemData(IC.useful, 1, 'wh2_main_special_fortress_gate_unicorn_wef_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Occupied Gate (Small Fortress)'),
    54409: ItemData(IC.useful, 1, 'wh2_main_special_salzenmund_laurelorn_wef_1', ItemType.building, 0, 'Progressive special_salzenmund_laurelorn_wef', 'Wef Building: Verdant Heart of Laurelorn'),
    54410: ItemData(IC.useful, 1, 'wh2_main_special_salzenmund_laurelorn_wef_1', ItemType.building, 0, 'Progressive special_salzenmund_laurelorn_wef', 'Wef Building: Ensorcelled Heart of Laurelorn'),
    54411: ItemData(IC.useful, 1, 'wh2_main_special_settlement_sartosa_wef_1', ItemType.building, 0, 'Progressive special_settlement_sartosa_wef', 'Wef Building: Occupied Sartosa'),
    54412: ItemData(IC.useful, 1, 'wh2_main_special_settlement_the_awakening_wef_1', ItemType.building, 0, 'Progressive special_settlement_the_awakening_wef', 'Wef Building: Occupied The Awakening'),
    54413: ItemData(IC.useful, 1, 'wh2_main_special_shrine_of_khaine_wef_1', ItemType.building, 0, 'Progressive special_shrine_of_khaine_wef', 'Wef Building: Shrine of Widowmaker'),
    54414: ItemData(IC.useful, 1, 'wh2_main_wef_oak_of_ages_occupied_1', ItemType.building, 1, 'Progressive wef_oak_of_ages_occupied', 'Wef Building: Oak of Ages (Pacified)'),
    54415: ItemData(IC.useful, 1, 'wh2_main_wef_resource_animals_1', ItemType.building, 0, 'Progressive wef_resource_animals', 'Wef Building: Exotic Animal Tamer'),
    54416: ItemData(IC.useful, 1, 'wh2_main_wef_resource_gems_1', ItemType.building, 0, 'Progressive wef_resource_gems', 'Wef Building: Gem Mine'),
    54417: ItemData(IC.useful, 1, 'wh2_main_wef_resource_medicine_1', ItemType.building, 0, 'Progressive wef_resource_medicine', "Wef Building: Herb Gatherer's Camp"),
    54418: ItemData(IC.useful, 1, 'wh2_main_wef_resource_obsidian_1', ItemType.building, 0, 'Progressive wef_resource_obsidian', 'Wef Building: Obsidian Quarry'),
    54419: ItemData(IC.useful, 1, 'wh2_main_wef_resource_spices_1', ItemType.building, 0, 'Progressive wef_resource_spices', 'Wef Building: Spice Market'),
    54420: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_1', ItemType.building, 0, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf Outpost'),
    54421: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_2', ItemType.building, 1, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf District'),
    54422: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_3', ItemType.building, 2, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf Colony'),
    54423: ItemData(IC.useful, 1, 'wh3_main_wef_resource_ivory_1', ItemType.building, 0, 'Progressive wef_resource_ivory', 'Wef Building: Animal Store'),
    54424: ItemData(IC.useful, 1, 'wh_dlc05_special_bordeleaux_port_wef_1', ItemType.building, 0, 'Progressive special_bordeleaux_port_wef', 'Wef Building: Elven Haven'),
    54425: ItemData(IC.useful, 1, 'wh_dlc05_special_erengrad_port_wef_1', ItemType.building, 0, 'Progressive special_erengrad_port_wef', 'Wef Building: Elven Haven'),
    54426: ItemData(IC.useful, 1, 'wh_dlc05_special_marienburg_port_wef_1', ItemType.building, 0, 'Progressive special_marienburg_port_wef', 'Wef Building: Elven Haven'),
    54427: ItemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_1', ItemType.building, 0, 'Progressive wef_agent_protection', 'Wef Building: Forest Lookouts'),
    54428: ItemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_2', ItemType.building, 1, 'Progressive wef_agent_protection', 'Wef Building: Forest Patrols'),
    54429: ItemData(IC.useful, 1, 'wh_dlc05_wef_armoury_1', ItemType.building, 0, 'Progressive wef_armoury', 'Wef Building: Asrai Forge'),
    54430: ItemData(IC.useful, 1, 'wh_dlc05_wef_armoury_2', ItemType.building, 1, 'Progressive wef_armoury', 'Wef Building: Asrai Armoury'),
    54431: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_1', ItemType.building, 0, 'Progressive wef_cavalry', 'Wef Building: Muster Stone'),
    54432: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_2', ItemType.building, 1, 'Progressive wef_cavalry', 'Wef Building: Grove of the Horse'),
    54433: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_2', ItemType.building, 1, 'Progressive wef_cavalry', 'Wef Building: '),
    54434: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_3', ItemType.building, 2, 'Progressive wef_cavalry', 'Wef Building: Pastures of Skymark'),
    54435: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_3', ItemType.building, 2, 'Progressive wef_cavalry', 'Wef Building: '),
    54436: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_4', ItemType.building, 3, 'Progressive wef_cavalry', 'Wef Building: Arboreal Paddock'),
    54437: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_4', ItemType.building, 3, 'Progressive wef_cavalry', 'Wef Building: '),
    54438: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_1', ItemType.building, 0, 'Progressive wef_flying', 'Wef Building: Eyrie'),
    54439: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_2', ItemType.building, 1, 'Progressive wef_flying', 'Wef Building: Warhawk Crags'),
    54440: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_3', ItemType.building, 2, 'Progressive wef_flying', 'Wef Building: Dragon Lair'),
    54441: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_1', ItemType.building, 0, 'Progressive wef_garrison', 'Wef Building: Guard Platform'),
    54442: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_2', ItemType.building, 1, 'Progressive wef_garrison', "Wef Building: Arbiter's Perch"),
    54443: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_3', ItemType.building, 2, 'Progressive wef_garrison', "Wef Building: Eternal Watcher's Garrison"),
    54444: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_1', ItemType.building, 0, 'Progressive wef_growth', "Wef Building: Trapper's Den"),
    54445: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_2', ItemType.building, 1, 'Progressive wef_growth', 'Wef Building: Game Lodge'),
    54446: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_3', ItemType.building, 2, 'Progressive wef_growth', "Wef Building: Hunter's Vault"),
    54447: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_1', ItemType.building, 0, 'Progressive wef_income', 'Wef Building: Grape Vines'),
    54448: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_2', ItemType.building, 1, 'Progressive wef_income', 'Wef Building: Vineyard'),
    54449: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_3', ItemType.building, 2, 'Progressive wef_income', 'Wef Building: Winery'),
    54450: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_4', ItemType.building, 3, 'Progressive wef_income', 'Wef Building: Wine Nexus'),
    54451: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_1', ItemType.building, 0, 'Progressive wef_melee', 'Wef Building: Selathoi Gallery'),
    54452: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_2', ItemType.building, 1, 'Progressive wef_melee', 'Wef Building: Tricksters Gallery'),
    54453: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_3', ItemType.building, 2, 'Progressive wef_melee', 'Wef Building: Forest Lookout'),
    54454: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Dormant)'),
    54455: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_2', ItemType.building, 2, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Withered)'),
    54456: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_3', ItemType.building, 3, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Budding)'),
    54457: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_4', ItemType.building, 4, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Thriving)'),
    54458: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_5', ItemType.building, 5, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Flourishing)'),
    54459: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_starlight_forge_1', ItemType.building, 0, 'Progressive wef_office_starlight_forge', 'Wef Building: Starlight Forge'),
    54461: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_the_wild_heath_1', ItemType.building, 0, 'Progressive wef_office_the_wild_heath', 'Wef Building: Crag Halls'),
    54463: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_wardancer_feast_halls_1', ItemType.building, 0, 'Progressive wef_office_wardancer_feast_halls', 'Wef Building: Moonspring Archives'),
    54464: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_wardancer_feast_halls_1', ItemType.building, 0, 'Progressive wef_office_wardancer_feast_halls', 'Wef Building: Moonspring Archives'),
    54465: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_wildwood_waystones_1', ItemType.building, 0, 'Progressive wef_office_wildwood_waystones', 'Wef Building: Wildwood Waystones'),
    54466: ItemData(IC.useful, 1, 'wh_dlc05_wef_office_wildwood_waystones_1', ItemType.building, 0, 'Progressive wef_office_wildwood_waystones', 'Wef Building: Wildwood Waystones'),
    54467: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_foraging_1', ItemType.building, 0, 'Progressive wef_outpost_foraging', 'Wef Building: Foraging Groves'),
    54468: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_major_human_1', ItemType.building, 0, 'Progressive wef_outpost_major_human', 'Wef Building: Asrai Lookout'),
    54469: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_recruitment_1', ItemType.building, 0, 'Progressive wef_outpost_recruitment', 'Wef Building: Worldroot Pathway'),
    54470: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_replenishment_1', ItemType.building, 0, 'Progressive wef_outpost_replenishment', 'Wef Building: Waystone'),
    54471: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_slaughter_1', ItemType.building, 0, 'Progressive wef_outpost_slaughter', 'Wef Building: Sacrificial Grounds'),
    54472: ItemData(IC.useful, 1, 'wh_dlc05_wef_port_1', ItemType.building, 0, 'Progressive wef_port', 'Wef Building: Elven Haven'),
    54473: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_1', ItemType.building, 0, 'Progressive wef_public_order', "Wef Building: Craftmen's Tree"),
    54474: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_2', ItemType.building, 1, 'Progressive wef_public_order', "Wef Building: Sculptor's Cavern"),
    54475: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_3', ItemType.building, 2, 'Progressive wef_public_order', "Wef Building: Artisan's Nexus"),
    54476: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_1', ItemType.building, 0, 'Progressive wef_ranged', 'Wef Building: Glade Guard Hide'),
    54477: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_2', ItemType.building, 1, 'Progressive wef_ranged', 'Wef Building: Deepwood Camp'),
    54478: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_3', ItemType.building, 2, 'Progressive wef_ranged', "Wef Building: Waywatcher's Perch"),
    54479: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_3', ItemType.building, 2, 'Progressive wef_ranged', 'Wef Building: '),
    54480: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_dyes_1', ItemType.building, 0, 'Progressive wef_resource_dyes', 'Wef Building: Cinnabar Mining Pit'),
    54481: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_furs_1', ItemType.building, 0, 'Progressive wef_resource_furs', 'Wef Building: Hunting Camp'),
    54482: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_gold_1', ItemType.building, 0, 'Progressive wef_resource_gold', 'Wef Building: Gold Mining Pit'),
    54483: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_iron_1', ItemType.building, 0, 'Progressive wef_resource_iron', 'Wef Building: Iron Mining Pit'),
    54484: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_marble_1', ItemType.building, 0, 'Progressive wef_resource_marble', 'Wef Building: Stone Cutter'),
    54485: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_pastures_1', ItemType.building, 0, 'Progressive wef_resource_pastures', 'Wef Building: Cattle Pastures'),
    54486: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_pottery_1', ItemType.building, 0, 'Progressive wef_resource_pottery', 'Wef Building: Clay Pit'),
    54487: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_salt_1', ItemType.building, 0, 'Progressive wef_resource_salt', 'Wef Building: Brine Mining Pit'),
    54488: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_timber_1', ItemType.building, 0, 'Progressive wef_resource_timber', "Wef Building: Woodman's Hut"),
    54489: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_wine_1', ItemType.building, 0, 'Progressive wef_resource_wine', 'Wef Building: Orchards'),
    54490: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_1', ItemType.building, 0, 'Progressive wef_settlement_major_main', 'Wef Building: Copse'),
    54491: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_2', ItemType.building, 1, 'Progressive wef_settlement_major_main', 'Wef Building: Glade'),
    54492: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_3', ItemType.building, 2, 'Progressive wef_settlement_major_main', 'Wef Building: Hollow'),
    54493: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_4', ItemType.building, 3, 'Progressive wef_settlement_major_main', 'Wef Building: Hall'),
    54494: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_5', ItemType.building, 4, 'Progressive wef_settlement_major_main', 'Wef Building: Great Hall'),
    54495: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_1', ItemType.building, 0, 'Progressive wef_spellsingers', 'Wef Building: Roots of Ghyran'),
    54496: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_2', ItemType.building, 1, 'Progressive wef_spellsingers', 'Wef Building: Branches of Ghur'),
    54497: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_3', ItemType.building, 2, 'Progressive wef_spellsingers', 'Wef Building: Canopy of Hysh'),
    54498: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_0', ItemType.building, 0, 'Progressive wef_temple_anath_raema', 'Wef Building: Sacred Grounds of Anath Raema'),
    54499: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_1', ItemType.building, 1, 'Progressive wef_temple_anath_raema', 'Wef Building: Temple of Anath Raema'),
    54500: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_1', ItemType.building, 1, 'Progressive wef_temple_anath_raema', 'Wef Building: Overgrown Temple of Anath Raema'),
    54501: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_ereth_khial_1', ItemType.building, 0, 'Progressive wef_temple_ereth_khial', 'Wef Building: Temple of Ereth Khial'),
    54502: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_ereth_khial_1', ItemType.building, 0, 'Progressive wef_temple_ereth_khial', 'Wef Building: Overgrown Temple of Ereth Khial'),
    54503: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_isha_1', ItemType.building, 0, 'Progressive wef_temple_isha', 'Wef Building: Temple of Isha'),
    54504: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', ItemType.building, 0, 'Progressive wef_temple_kurnous', 'Wef Building: Temple of Kurnous'),
    54505: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', ItemType.building, 0, 'Progressive wef_temple_kurnous', 'Wef Building: Overgrown Temple of Kurnous'),
    54506: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_1', ItemType.building, 0, 'Progressive wef_tree_spirits', 'Wef Building: Haunted Groves'),
    54507: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_1', ItemType.building, 0, 'Progressive wef_tree_spirits', 'Wef Building: Haunted Groves'),
    54508: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_1', ItemType.building, 0, 'Progressive wef_tree_spirits', 'Wef Building: Haunted Groves'),
    54509: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_2', ItemType.building, 1, 'Progressive wef_tree_spirits', 'Wef Building: Tribal Stones'),
    54510: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_2', ItemType.building, 1, 'Progressive wef_tree_spirits', 'Wef Building: Tribal Stones'),
    54511: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_2', ItemType.building, 1, 'Progressive wef_tree_spirits', 'Wef Building: Tribal Stones'),
    54512: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_3', ItemType.building, 2, 'Progressive wef_tree_spirits', 'Wef Building: Nimbus-Shrouded Copse'),
    54513: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_3', ItemType.building, 2, 'Progressive wef_tree_spirits', 'Wef Building: Nimbus-Shrouded Copse'),
    54514: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_3', ItemType.building, 2, 'Progressive wef_tree_spirits', 'Wef Building: Nimbus-Shrouded Copse'),
    54515: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_4', ItemType.building, 3, 'Progressive wef_tree_spirits', 'Wef Building: Moonstone Clearing'),
    54516: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_4', ItemType.building, 3, 'Progressive wef_tree_spirits', 'Wef Building: Moonstone Clearing'),
    54517: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_4', ItemType.building, 3, 'Progressive wef_tree_spirits', 'Wef Building: Moonstone Clearing')
}

techs: dict[int, ItemData] = {
    54800: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_isha', ItemType.tech, 3, 'Progressive tech_wef', 'Wef Tech: Isha, the Mother'),
    54801: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_mathlann', ItemType.tech, 4, 'Progressive tech_wef', 'Wef Tech: Mathlann, Lord of the Deeps'),
    54802: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_estreath', ItemType.tech, 5, 'Progressive tech_wef', 'Wef Tech: Estreath, Lord of Hunger'),
    54803: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_loec', ItemType.tech, 2, 'Progressive tech_wef', 'Wef Tech: Loec, the Trickster'),
    54804: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_ladrielle', ItemType.tech, 2, 'Progressive tech_wef', 'Wef Tech: Ladrielle, Lady of Mists'),
    54805: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_hoeth', ItemType.tech, 3, 'Progressive tech_wef', 'Wef Tech: Hoeth, Lord of Wisdom'),
    54806: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_kurnous', ItemType.tech, 4, 'Progressive tech_wef', 'Wef Tech: Kurnous, the Hunter'),
    54807: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_asuryan', ItemType.tech, 6, 'Progressive tech_wef', 'Wef Tech: Asuryan, the Creator'),
    54808: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_vaul', ItemType.tech, 1, 'Progressive tech_wef', 'Wef Tech: Vaul, the Maker'),
    54809: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_lileath', ItemType.tech, 5, 'Progressive tech_wef', 'Wef Tech: Lileath, the Maiden'),
    54810: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_cadai', ItemType.tech, 6, 'Progressive tech_wef', 'Wef Tech: Cadai'),
    54811: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_pine', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Pine'),
    54812: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_poplar', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Poplar'),
    54813: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_oak', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Oak'),
    54814: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_morai_heg', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Morai-Heg, the Crone'),
    54815: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_khaine', ItemType.tech, 6, 'Progressive tech_wef', 'Wef Tech: Khaine, the Bloody-Handed God'),
    54816: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_eagles', ItemType.tech, 1, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Eagle Lords'),
    54817: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_willow', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Willow'),
    54818: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_the_ancients', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Ancients'),
    54819: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_ash', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Ash'),
    54820: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_yew', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Yew'),
    54821: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_cypress', ItemType.tech, 0, 'Progressive tech_wef', 'Wef Tech: Wisdom of the Cypress'),
    54822: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_cytharai', ItemType.tech, 6, 'Progressive tech_wef', 'Wef Tech: Cytharai'),
    54823: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_ellinill', ItemType.tech, 1, 'Progressive tech_wef', 'Wef Tech: Ellinill, Lord of Destruction'),
    54824: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_ereth_khial', ItemType.tech, 5, 'Progressive tech_wef', 'Wef Tech: Ereth Khial, the Pale Queen'),
    54825: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_anath_raema', ItemType.tech, 2, 'Progressive tech_wef', 'Wef Tech: Anath Raema, the Savage Huntress'),
    54826: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_drakira', ItemType.tech, 2, 'Progressive tech_wef', 'Wef Tech: Drakira, Queen of Vengeance'),
    54827: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_eldrazor', ItemType.tech, 3, 'Progressive tech_wef', 'Wef Tech: Eldrazor, Lord of Blades'),
    54828: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_addaioth', ItemType.tech, 4, 'Progressive tech_wef', 'Wef Tech: Addaioth, Bringer of Fire'),
    54829: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_hekarti', ItemType.tech, 6, 'Progressive tech_wef', 'Wef Tech: Hekarti, Mistress of Magic'),
    54830: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_hukon', ItemType.tech, 3, 'Progressive tech_wef', 'Wef Tech: Hukon, the Sunderer'),
    54831: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_nethu', ItemType.tech, 4, 'Progressive tech_wef', 'Wef Tech: Nethu, Keeper of the Last Door'),
    54832: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_atharti', ItemType.tech, 5, 'Progressive tech_wef', 'Wef Tech: Atharti, Lady of Desire')
}

progUnits: dict[int, ItemData] = {

}

progBuildings: dict[int, ItemData] = {
    55302: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_wef', ItemType.building, 3, None, 'Progressive Wef Building: Foreign Slot Discovery Wef'),
    55305: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_eagle_wef', ItemType.building, 2, None, 'Progressive Wef Building: Special Fortress Gate Eagle Wef'),
    55306: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_griffon_wef', ItemType.building, 2, None, 'Progressive Wef Building: Special Fortress Gate Griffon Wef'),
    55307: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_phoenix_wef', ItemType.building, 2, None, 'Progressive Wef Building: Special Fortress Gate Phoenix Wef'),
    55308: ItemData(IC.useful, 2, 'Progressive special_fortress_gate_unicorn_wef', ItemType.building, 2, None, 'Progressive Wef Building: Special Fortress Gate Unicorn Wef'),
    55309: ItemData(IC.useful, 1, 'Progressive special_salzenmund_laurelorn_wef', ItemType.building, 1, None, 'Progressive Wef Building: Special Salzenmund Laurelorn Wef'),
    55310: ItemData(IC.useful, 1, 'Progressive special_settlement_sartosa_wef', ItemType.building, 1, None, 'Progressive Wef Building: Special Settlement Sartosa Wef'),
    55314: ItemData(IC.useful, 1, 'Progressive wef_resource_animals', ItemType.building, 1, None, 'Progressive Wef Building: Animals'),
    55315: ItemData(IC.useful, 1, 'Progressive wef_resource_gems', ItemType.building, 1, None, 'Progressive Wef Building: Gems'),
    55316: ItemData(IC.useful, 1, 'Progressive wef_resource_medicine', ItemType.building, 1, None, 'Progressive Wef Building: Medicine'),
    55317: ItemData(IC.useful, 1, 'Progressive wef_resource_obsidian', ItemType.building, 1, None, 'Progressive Wef Building: Obsidian'),
    55318: ItemData(IC.useful, 1, 'Progressive wef_resource_spices', ItemType.building, 1, None, 'Progressive Wef Building: Spices'),
    55321: ItemData(IC.useful, 3, 'Progressive wef_allied_outpost', ItemType.building, 3, None, 'Progressive Wef Building: Allied Outpost'),
    55322: ItemData(IC.useful, 1, 'Progressive wef_resource_ivory', ItemType.building, 1, None, 'Progressive Wef Building: Ivory'),
    55327: ItemData(IC.useful, 2, 'Progressive wef_agent_protection', ItemType.building, 2, None, 'Progressive Wef Building: Agent Protection'),
    55329: ItemData(IC.useful, 2, 'Progressive wef_armoury', ItemType.building, 2, None, 'Progressive Wef Building: Armoury'),
    55333: ItemData(IC.useful, 4, 'Progressive wef_cavalry', ItemType.building, 4, None, 'Progressive Wef Building: Cavalry'),
    55336: ItemData(IC.useful, 3, 'Progressive wef_flying', ItemType.building, 3, None, 'Progressive Wef Building: Flying'),
    55339: ItemData(IC.useful, 3, 'Progressive wef_garrison', ItemType.building, 3, None, 'Progressive Wef Building: Garrison'),
    55342: ItemData(IC.useful, 3, 'Progressive wef_growth', ItemType.building, 3, None, 'Progressive Wef Building: Growth'),
    55346: ItemData(IC.useful, 4, 'Progressive wef_income', ItemType.building, 4, None, 'Progressive Wef Building: Income'),
    55349: ItemData(IC.useful, 3, 'Progressive wef_melee', ItemType.building, 3, None, 'Progressive Wef Building: Melee'),
    55355: ItemData(IC.useful, 1, 'Progressive wef_office_starlight_forge', ItemType.building, 1, None, 'Progressive Wef Building: Office Starlight Forge'),
    55356: ItemData(IC.useful, 1, 'Progressive wef_office_the_wild_heath', ItemType.building, 1, None, 'Progressive Wef Building: Office The Wild Heath'),
    55357: ItemData(IC.useful, 1, 'Progressive wef_office_wardancer_feast_halls', ItemType.building, 1, None, 'Progressive Wef Building: Office Wardancer Feast Halls'),
    55358: ItemData(IC.useful, 1, 'Progressive wef_office_wildwood_waystones', ItemType.building, 1, None, 'Progressive Wef Building: Office Wildwood Waystones'),
    55359: ItemData(IC.useful, 1, 'Progressive wef_outpost_foraging', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Foraging'),
    55360: ItemData(IC.useful, 1, 'Progressive wef_outpost_major_human', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Major Human'),
    55361: ItemData(IC.useful, 1, 'Progressive wef_outpost_recruitment', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Recruitment'),
    55362: ItemData(IC.useful, 1, 'Progressive wef_outpost_replenishment', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Replenishment'),
    55363: ItemData(IC.useful, 1, 'Progressive wef_outpost_slaughter', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Slaughter'),
    55364: ItemData(IC.useful, 1, 'Progressive wef_port', ItemType.building, 1, None, 'Progressive Wef Building: Port'),
    55367: ItemData(IC.useful, 3, 'Progressive wef_public_order', ItemType.building, 3, None, 'Progressive Wef Building: Public Order'),
    55370: ItemData(IC.useful, 3, 'Progressive wef_ranged', ItemType.building, 3, None, 'Progressive Wef Building: Ranged'),
    55371: ItemData(IC.useful, 1, 'Progressive wef_resource_dyes', ItemType.building, 1, None, 'Progressive Wef Building: Dyes'),
    55372: ItemData(IC.useful, 1, 'Progressive wef_resource_furs', ItemType.building, 1, None, 'Progressive Wef Building: Furs'),
    55373: ItemData(IC.useful, 1, 'Progressive wef_resource_gold', ItemType.building, 1, None, 'Progressive Wef Building: Gold'),
    55374: ItemData(IC.useful, 1, 'Progressive wef_resource_iron', ItemType.building, 1, None, 'Progressive Wef Building: Iron'),
    55375: ItemData(IC.useful, 1, 'Progressive wef_resource_marble', ItemType.building, 1, None, 'Progressive Wef Building: Marble'),
    55376: ItemData(IC.useful, 1, 'Progressive wef_resource_pastures', ItemType.building, 1, None, 'Progressive Wef Building: Pastures'),
    55377: ItemData(IC.useful, 1, 'Progressive wef_resource_pottery', ItemType.building, 1, None, 'Progressive Wef Building: Pottery'),
    55378: ItemData(IC.useful, 1, 'Progressive wef_resource_salt', ItemType.building, 1, None, 'Progressive Wef Building: Salt'),
    55379: ItemData(IC.useful, 1, 'Progressive wef_resource_timber', ItemType.building, 1, None, 'Progressive Wef Building: Timber'),
    55380: ItemData(IC.useful, 1, 'Progressive wef_resource_wine', ItemType.building, 1, None, 'Progressive Wef Building: Wine'),
    55385: ItemData(IC.useful, 5, 'Progressive wef_settlement_major', ItemType.building, 5, None, 'Progressive Wef Building: Settlement Major'),
    55388: ItemData(IC.useful, 3, 'Progressive wef_spellsingers', ItemType.building, 3, None, 'Progressive Wef Building: Spellsingers'),
    55390: ItemData(IC.useful, 2, 'Progressive wef_temple_anath_raema', ItemType.building, 2, None, 'Progressive Wef Building: Temple Anath Raema'),
    55391: ItemData(IC.useful, 1, 'Progressive wef_temple_ereth_khial', ItemType.building, 1, None, 'Progressive Wef Building: Temple Ereth Khial'),
    55392: ItemData(IC.useful, 1, 'Progressive wef_temple_isha', ItemType.building, 1, None, 'Progressive Wef Building: Temple Isha'),
    55393: ItemData(IC.useful, 1, 'Progressive wef_temple_kurnous', ItemType.building, 1, None, 'Progressive Wef Building: Temple Kurnous'),
    55397: ItemData(IC.useful, 4, 'Progressive wef_tree_spirits', ItemType.building, 4, None, 'Progressive Wef Building: Tree Spirits')
}

progTechs: dict[int, ItemData] = {
    55400: ItemData(IC.useful, 15, "Progressive tech_wef", ItemType.tech, 15, None, "Progressive Wef Tech"),
}

special: dict[int, ItemData] = {

}