from BaseClasses import ItemClassification as IC
from .item_types import ItemType, ItemData, specialItemData
# @formatter:off
units: dict[int, ItemData] = {
    54023: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_0', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Eternal Guard'),
    54022: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_eternal_guard_1', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Eternal Guard (Shields)'),
    54018: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_0', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Wardancers'),
    54017: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wardancers_1', ItemType.unit, 2, 'Progressive wef_inf', 'Wef Unit: Wardancers (Asrai Spears)'),
    54005: ItemData(IC.useful, 1, 'wh2_dlc16_wef_inf_bladesingers_0', ItemType.unit, 3, 'Progressive wef_inf', 'Wef Unit: Bladesingers'),
    54015: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_wildwood_rangers_0', ItemType.unit, 3, 'Progressive wef_inf', 'Wef Unit: Wildwood Rangers'),

    54021: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_0', ItemType.unit, 1, 'Progressive wef_rng', 'Wef Unit: Glade Guard'),
    54019: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_2', ItemType.unit, 1, 'Progressive wef_rng', 'Wef Unit: Glade Guard (Hagbane Tips)'),
    54020: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_glade_guard_1', ItemType.unit, 1, 'Progressive wef_rng', 'Wef Unit: Glade Guard (Starfire Shafts)'),
    54026: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_0', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Deepwood Scouts'),
    54025: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_deepwood_scouts_1', ItemType.unit, 2, 'Progressive wef_rng', 'Wef Unit: Deepwood Scouts (Swiftshiver Shards)'),
    54016: ItemData(IC.useful, 1, 'wh_dlc05_wef_inf_waywatchers_0', ItemType.unit, 3, 'Progressive wef_rng', 'Wef Unit: Waywatchers'),

    54057: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_0', ItemType.unit, 1, 'Progressive wef_cav', 'Wef Unit: Glade Riders'),
    54056: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_glade_riders_1', ItemType.unit, 1, 'Progressive wef_cav', 'Wef Unit: Glade Riders (Hagbane Tips)'),
    54011: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cav_glade_riders_2', ItemType.unit, 1, 'Progressive wef_cav', 'Wef Unit: Glade Riders (Spears)'),
    54053: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_0', ItemType.unit, 2, 'Progressive wef_cav', 'Wef Unit: Wild Riders'),
    54052: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_wild_riders_1', ItemType.unit, 2, 'Progressive wef_cav', 'Wef Unit: Wild Riders (Shields)'),
    54055: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_hawk_riders_0', ItemType.unit, 2, 'Progressive wef_cav', 'Wef Unit: Hawk Riders'),
    54054: ItemData(IC.useful, 1, 'wh_dlc05_wef_cav_sisters_thorn_0', ItemType.unit, 3, 'Progressive wef_cav', 'Wef Unit: Sisters of the Thorn'),
    54010: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cav_great_stag_knights_0', ItemType.unit, 4, 'Progressive wef_cav', 'Wef Unit: Great Stag Knights'),

    54014: ItemData(IC.useful, 1, 'wh_dlc05_wef_mon_great_eagle_0', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Great Eagle'),
    54004: ItemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats', ItemType.unit, 3, 'Progressive wef_bst', 'Wef Unit: Zoats'),
    54027: ItemData(IC.useful, 1, 'wh_dlc05_wef_forest_dragon_0', ItemType.unit, 4, 'Progressive wef_inf', 'Wef Unit: Forest Dragon'),

    54003: ItemData(IC.useful, 1, 'wh2_twa02_wef_cha_glade_captain_0', ItemType.unit, 1, 'Progressive wef_hro', 'Wef Unit: Glade Captain'),
    54028: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_waystalker_0', ItemType.unit, 1, 'Progressive wef_hro', 'Wef Unit: Waystalker'),
    54032: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_shadows_0', ItemType.unit, 1, 'Progressive wef_hro', 'Wef Unit: Spellsinger (Shadows)'),
    54036: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_life_0', ItemType.unit, 1, 'Progressive wef_hro', 'Wef Unit: Spellsinger (Life)'),
    54040: ItemData(IC.useful, 1, 'wh_dlc05_wef_cha_spellsinger_beasts_0', ItemType.unit, 1, 'Progressive wef_hro', 'Wef Unit: Spellsinger (Beasts)'),

    54042: ItemData(IC.useful, 1, 'wh2_dlc16_wef_inf_dryads_ror_0', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Wraiths of the Frozen Heart (Dryads)'),
    54043: ItemData(IC.useful, 1, 'wh2_dlc16_wef_cav_great_stag_knights_ror_0', ItemType.unit, 4, 'Progressive wef_cav', 'Wef Unit: Lost Sylvan Knights (Great Stag Knights)'),
    54044: ItemData(IC.useful, 1, 'wh2_dlc16_wef_mon_zoats_ror_0', ItemType.unit, 3, 'Progressive wef_bst', 'Wef Unit: Enigmas of Ghyran (Zoats)'),
    54045: ItemData(IC.useful, 1, 'wh_pro04_wef_cav_wild_riders_ror_0', ItemType.unit, 2, 'Progressive wef_cav', 'Wef Unit: Wild Hunters of Kurnous (Wild Riders – Shields)'),
    54046: ItemData(IC.useful, 1, 'wh_pro04_wef_inf_eternal_guard_ror_0', ItemType.unit, 1, 'Progressive wef_inf', 'Wef Unit: Winterheart Guard (Eternal Guard – Shields)'),
    54047: ItemData(IC.useful, 1, 'wh_pro04_wef_inf_wardancers_ror_0', ItemType.unit, 2, 'Progressive wef_inf', "Wef Unit: Loec's Tricksters (Wardancers – Asrai Spears)"),
    54048: ItemData(IC.useful, 1, 'wh_pro04_wef_inf_waywatchers_ror_0', ItemType.unit, 3, 'Progressive wef_rng', 'Wef Unit: Hawk-Eyes of Drakira (Waywatchers)'),
    54049: ItemData(IC.useful, 1, 'wh_pro04_wef_inf_wildwood_rangers_ror_0', ItemType.unit, 3, 'Progressive wef_inf', 'Wef Unit: Wardens of Cythral (Wildwood Rangers)'),
    54050: ItemData(IC.useful, 1, 'wh_pro04_wef_mon_treekin_ror_0', ItemType.unit, 2, 'Progressive wef_bst', 'Wef Unit: Firebark Elders (Tree Kin)'),
}

buildings: dict[int, ItemData] = {
    54400: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_1', ItemType.building, 0, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Undergrowth Lookouts'),
    54401: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_2', ItemType.building, 1, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Woodland Trenches'),
    54402: ItemData(IC.useful, 1, 'wh2_main_foreign_slot_discovery_wef_3', ItemType.building, 2, 'Progressive foreign_slot_discovery_wef', 'Wef Building: Forest Caves'),
    54403: ItemData(IC.useful, 1, 'wh2_main_wef_resource_animals_1', ItemType.building, 0, 'Progressive wef_resource_animals', 'Wef Building: Exotic Animal Tamer'),
    54404: ItemData(IC.useful, 1, 'wh2_main_wef_resource_gems_1', ItemType.building, 0, 'Progressive wef_resource_gems', 'Wef Building: Gem Mine'),
    54405: ItemData(IC.useful, 1, 'wh2_main_wef_resource_medicine_1', ItemType.building, 0, 'Progressive wef_resource_medicine', "Wef Building: Herb Gatherer's Camp"),
    54406: ItemData(IC.useful, 1, 'wh2_main_wef_resource_obsidian_1', ItemType.building, 0, 'Progressive wef_resource_obsidian', 'Wef Building: Obsidian Quarry'),
    54407: ItemData(IC.useful, 1, 'wh2_main_wef_resource_spices_1', ItemType.building, 0, 'Progressive wef_resource_spices', 'Wef Building: Spice Market'),
    54408: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_1', ItemType.building, 0, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf Outpost'),
    54409: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_2', ItemType.building, 1, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf District'),
    54410: ItemData(IC.useful, 1, 'wh3_main_wef_allied_outpost_3', ItemType.building, 2, 'Progressive wef_allied_outpost', 'Wef Building: Wood Elf Colony'),
    54411: ItemData(IC.useful, 1, 'wh3_main_wef_resource_ivory_1', ItemType.building, 0, 'Progressive wef_resource_ivory', 'Wef Building: Animal Store'),
    54412: ItemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_1', ItemType.building, 0, 'Progressive wef_agent_protection', 'Wef Building: Forest Lookouts'),
    54413: ItemData(IC.useful, 1, 'wh_dlc05_wef_agent_protection_2', ItemType.building, 1, 'Progressive wef_agent_protection', 'Wef Building: Forest Patrols'),
    54414: ItemData(IC.useful, 1, 'wh_dlc05_wef_armoury_1', ItemType.building, 0, 'Progressive wef_armoury', 'Wef Building: Asrai Forge'),
    54415: ItemData(IC.useful, 1, 'wh_dlc05_wef_armoury_2', ItemType.building, 1, 'Progressive wef_armoury', 'Wef Building: Asrai Armoury'),
    54416: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_1', ItemType.building, 0, 'Progressive wef_cavalry', 'Wef Building: Muster Stone'),
    54417: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_2', ItemType.building, 1, 'Progressive wef_cavalry', 'Wef Building: Grove of the Horse'),
    54418: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_3', ItemType.building, 2, 'Progressive wef_cavalry', 'Wef Building: Pastures of Skymark'),
    54419: ItemData(IC.useful, 1, 'wh_dlc05_wef_cavalry_4', ItemType.building, 3, 'Progressive wef_cavalry', 'Wef Building: Arboreal Paddock'),
    54420: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_1', ItemType.building, 0, 'Progressive wef_flying', 'Wef Building: Eyrie'),
    54421: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_2', ItemType.building, 1, 'Progressive wef_flying', 'Wef Building: Warhawk Crags'),
    54422: ItemData(IC.useful, 1, 'wh_dlc05_wef_flying_3', ItemType.building, 2, 'Progressive wef_flying', 'Wef Building: Dragon Lair'),
    54423: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_1', ItemType.building, 0, 'Progressive wef_garrison', 'Wef Building: Guard Platform'),
    54424: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_2', ItemType.building, 1, 'Progressive wef_garrison', "Wef Building: Arbiter's Perch"),
    54425: ItemData(IC.useful, 1, 'wh_dlc05_wef_garrison_3', ItemType.building, 2, 'Progressive wef_garrison', "Wef Building: Eternal Watcher's Garrison"),
    54426: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_1', ItemType.building, 0, 'Progressive wef_growth', "Wef Building: Trapper's Den"),
    54427: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_2', ItemType.building, 1, 'Progressive wef_growth', 'Wef Building: Game Lodge'),
    54428: ItemData(IC.useful, 1, 'wh_dlc05_wef_growth_3', ItemType.building, 2, 'Progressive wef_growth', "Wef Building: Hunter's Vault"),
    54429: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_1', ItemType.building, 0, 'Progressive wef_income', 'Wef Building: Grape Vines'),
    54430: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_2', ItemType.building, 1, 'Progressive wef_income', 'Wef Building: Vineyard'),
    54431: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_3', ItemType.building, 2, 'Progressive wef_income', 'Wef Building: Winery'),
    54432: ItemData(IC.useful, 1, 'wh_dlc05_wef_income_4', ItemType.building, 3, 'Progressive wef_income', 'Wef Building: Wine Nexus'),
    54433: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_1', ItemType.building, 0, 'Progressive wef_melee', 'Wef Building: Selathoi Gallery'),
    54434: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_2', ItemType.building, 1, 'Progressive wef_melee', 'Wef Building: Tricksters Gallery'),
    54435: ItemData(IC.useful, 1, 'wh_dlc05_wef_melee_3', ItemType.building, 2, 'Progressive wef_melee', 'Wef Building: Forest Lookout'),
    54436: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_1', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Dormant)'),
    54437: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_2', ItemType.building, 2, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Withered)'),
    54438: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_3', ItemType.building, 3, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Budding)'),
    54439: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_4', ItemType.building, 4, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Thriving)'),
    54440: ItemData(IC.useful, 1, 'wh_dlc05_wef_oak_of_ages_5', ItemType.building, 5, 'Progressive wef_settlement_major', 'Wef Building: Oak of Ages (Flourishing)'),
    54445: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_foraging_1', ItemType.building, 0, 'Progressive wef_outpost_foraging', 'Wef Building: Foraging Groves'),
    54446: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_major_human_1', ItemType.building, 0, 'Progressive wef_outpost_major_human', 'Wef Building: Asrai Lookout'),
    54447: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_recruitment_1', ItemType.building, 0, 'Progressive wef_outpost_recruitment', 'Wef Building: Worldroot Pathway'),
    54448: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_replenishment_1', ItemType.building, 0, 'Progressive wef_outpost_replenishment', 'Wef Building: Waystone'),
    54449: ItemData(IC.useful, 1, 'wh_dlc05_wef_outpost_slaughter_1', ItemType.building, 0, 'Progressive wef_outpost_slaughter', 'Wef Building: Sacrificial Grounds'),
    54450: ItemData(IC.useful, 1, 'wh_dlc05_wef_port_1', ItemType.building, 0, 'Progressive wef_port', 'Wef Building: Elven Haven'),
    54451: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_1', ItemType.building, 0, 'Progressive wef_public_order', "Wef Building: Craftmen's Tree"),
    54452: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_2', ItemType.building, 1, 'Progressive wef_public_order', "Wef Building: Sculptor's Cavern"),
    54453: ItemData(IC.useful, 1, 'wh_dlc05_wef_public_order_3', ItemType.building, 2, 'Progressive wef_public_order', "Wef Building: Artisan's Nexus"),
    54454: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_1', ItemType.building, 0, 'Progressive wef_ranged', 'Wef Building: Glade Guard Hide'),
    54455: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_2', ItemType.building, 1, 'Progressive wef_ranged', 'Wef Building: Deepwood Camp'),
    54456: ItemData(IC.useful, 1, 'wh_dlc05_wef_ranged_3', ItemType.building, 2, 'Progressive wef_ranged', "Wef Building: Waywatcher's Perch"),
    54457: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_dyes_1', ItemType.building, 0, 'Progressive wef_resource_dyes', 'Wef Building: Cinnabar Mining Pit'),
    54458: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_furs_1', ItemType.building, 0, 'Progressive wef_resource_furs', 'Wef Building: Hunting Camp'),
    54459: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_gold_1', ItemType.building, 0, 'Progressive wef_resource_gold', 'Wef Building: Gold Mining Pit'),
    54460: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_iron_1', ItemType.building, 0, 'Progressive wef_resource_iron', 'Wef Building: Iron Mining Pit'),
    54461: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_marble_1', ItemType.building, 0, 'Progressive wef_resource_marble', 'Wef Building: Stone Cutter'),
    54462: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_pastures_1', ItemType.building, 0, 'Progressive wef_resource_pastures', 'Wef Building: Cattle Pastures'),
    54463: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_pottery_1', ItemType.building, 0, 'Progressive wef_resource_pottery', 'Wef Building: Clay Pit'),
    54464: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_salt_1', ItemType.building, 0, 'Progressive wef_resource_salt', 'Wef Building: Brine Mining Pit'),
    54465: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_timber_1', ItemType.building, 0, 'Progressive wef_resource_timber', "Wef Building: Woodman's Hut"),
    54466: ItemData(IC.useful, 1, 'wh_dlc05_wef_resource_wine_1', ItemType.building, 0, 'Progressive wef_resource_wine', 'Wef Building: Orchards'),
    54467: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_1', ItemType.building, 0, 'Progressive wef_settlement_major', 'Wef Building: Copse'),
    54468: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_2', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Glade'),
    54469: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_3', ItemType.building, 2, 'Progressive wef_settlement_major', 'Wef Building: Hollow'),
    54470: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_4', ItemType.building, 3, 'Progressive wef_settlement_major', 'Wef Building: Hall'),
    54471: ItemData(IC.useful, 1, 'wh_dlc05_wef_settlement_major_main_5', ItemType.building, 4, 'Progressive wef_settlement_major', 'Wef Building: Great Hall'),
    54472: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_1', ItemType.building, 0, 'Progressive wef_spellsingers', 'Wef Building: Roots of Ghyran'),
    54473: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_2', ItemType.building, 1, 'Progressive wef_spellsingers', 'Wef Building: Branches of Ghur'),
    54474: ItemData(IC.useful, 1, 'wh_dlc05_wef_spellsingers_3', ItemType.building, 2, 'Progressive wef_spellsingers', 'Wef Building: Canopy of Hysh'),
    54475: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_0', ItemType.building, 0, 'Progressive wef_temple_anath_raema', 'Wef Building: Sacred Grounds of Anath Raema'),
    54476: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_anath_raema_1', ItemType.building, 1, 'Progressive wef_temple_anath_raema', 'Wef Building: Temple of Anath Raema'),
    54477: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_ereth_khial_1', ItemType.building, 0, 'Progressive wef_temple_ereth_khial', 'Wef Building: Temple of Ereth Khial'),
    54478: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_isha_1', ItemType.building, 0, 'Progressive wef_temple_isha', 'Wef Building: Temple of Isha'),
    54479: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', ItemType.building, 0, 'Progressive wef_temple_kurnous', 'Wef Building: Temple of Kurnous'),
    54480: ItemData(IC.useful, 1, 'wh_dlc05_wef_temple_kurnous_1', ItemType.building, 0, 'Progressive wef_temple_kurnous', 'Wef Building: Overgrown Temple of Kurnous'),
    54481: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_1', ItemType.building, 0, 'Progressive wef_tree_spirits', 'Wef Building: Haunted Groves'),
    54482: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_2', ItemType.building, 1, 'Progressive wef_tree_spirits', 'Wef Building: Tribal Stones'),
    54483: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_3', ItemType.building, 2, 'Progressive wef_tree_spirits', 'Wef Building: Nimbus-Shrouded Copse'),
    54484: ItemData(IC.useful, 1, 'wh_dlc05_wef_tree_spirits_4', ItemType.building, 3, 'Progressive wef_tree_spirits', 'Wef Building: Moonstone Clearing'),
    54485: ItemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_1_wef', ItemType.building, 0, 'Progressive wef_settlement_major', 'Wef Building: Gaean Vale (Copse)'),
    54486: ItemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_2_wef', ItemType.building, 1, 'Progressive wef_settlement_major', 'Wef Building: Gaean Vale (Glade)'),
    54487: ItemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_3_wef', ItemType.building, 2, 'Progressive wef_settlement_major', 'Wef Building: Gaean Vale (Hollow)'),
    54488: ItemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_4_wef', ItemType.building, 3, 'Progressive wef_settlement_major', 'Wef Building: Gaean Vale (Hall)'),
    54489: ItemData(IC.useful, 1, 'wh_dlc05_special_settlement_gaean_vale_5_wef', ItemType.building, 4, 'Progressive wef_settlement_major', 'Wef Building: Gaean Vale (Great Hall)')
}

techs: dict[int, ItemData] = {
    54814: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_morai_heg', ItemType.tech, 1, 'Progressive tech_wef_cadai', 'Wef Tech: Morai-Heg, the Crone'),
    54808: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_vaul', ItemType.tech, 1, 'Progressive tech_wef_cadai', 'Wef Tech: Vaul, the Maker'),
    54823: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_ellinill', ItemType.tech, 1, 'Progressive tech_wef_cytharai', 'Wef Tech: Ellinill, Lord of Destruction'),
    54803: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_loec', ItemType.tech, 2, 'Progressive tech_wef_cadai', 'Wef Tech: Loec, the Trickster'),
    54825: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_anath_raema', ItemType.tech, 2, 'Progressive tech_wef_cytharai', 'Wef Tech: Anath Raema, the Savage Huntress'),
    54804: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_ladrielle', ItemType.tech, 2, 'Progressive tech_wef_cadai', 'Wef Tech: Ladrielle, Lady of Mists'),
    54826: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_drakira', ItemType.tech, 2, 'Progressive tech_wef_cytharai', 'Wef Tech: Drakira, Queen of Vengeance'),
    54800: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_isha', ItemType.tech, 3, 'Progressive tech_wef_cadai', 'Wef Tech: Isha, the Mother'),
    54830: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_hukon', ItemType.tech, 3, 'Progressive tech_wef_cytharai', 'Wef Tech: Hukon, the Sunderer'),
    54805: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_hoeth', ItemType.tech, 3, 'Progressive tech_wef_cadai', 'Wef Tech: Hoeth, Lord of Wisdom'),
    54827: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_eldrazor', ItemType.tech, 3, 'Progressive tech_wef_cytharai', 'Wef Tech: Eldrazor, Lord of Blades'),
    54801: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_mathlann', ItemType.tech, 4, 'Progressive tech_wef_cadai', 'Wef Tech: Mathlann, Lord of the Deeps'),
    54831: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_nethu', ItemType.tech, 4, 'Progressive tech_wef_cytharai', 'Wef Tech: Nethu, Keeper of the Last Door'),
    54806: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_kurnous', ItemType.tech, 4, 'Progressive tech_wef_cadai', 'Wef Tech: Kurnous, the Hunter'),
    54828: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_addaioth', ItemType.tech, 4, 'Progressive tech_wef_cytharai', 'Wef Tech: Addaioth, Bringer of Fire'),
    54802: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_estreath', ItemType.tech, 5, 'Progressive tech_wef_cadai', 'Wef Tech: Estreath, Lord of Hunger'),
    54832: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_atharti', ItemType.tech, 5, 'Progressive tech_wef_cytharai', 'Wef Tech: Atharti, Lady of Desire'),
    54809: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_lileath', ItemType.tech, 5, 'Progressive tech_wef_cadai', 'Wef Tech: Lileath, the Maiden'),
    54824: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_ereth_khial', ItemType.tech, 5, 'Progressive tech_wef_cytharai', 'Wef Tech: Ereth Khial, the Pale Queen'),
    54807: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_asuryan', ItemType.tech, 6, 'Progressive tech_wef_cadai', 'Wef Tech: Asuryan, the Creator'),
    54829: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_hekarti', ItemType.tech, 6, 'Progressive tech_wef_cytharai', 'Wef Tech: Hekarti, Mistress of Magic'),
    54810: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_cadai', ItemType.tech, 6, 'Progressive tech_wef_cadai', 'Wef Tech: Cadai'),
    54822: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_cytharai', ItemType.tech, 6, 'Progressive tech_wef_cytharai', 'Wef Tech: Cytharai'),
    54815: ItemData(IC.useful, 1, 'wh_dlc05_tech_2_khaine', ItemType.tech, 6, 'Progressive tech_wef_cytharai', 'Wef Tech: Khaine, the Bloody-Handed God'),

    54816: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_eagles', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Eagle Lords'),
    54811: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_pine', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Pine'),
    54812: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_poplar', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Poplar'),
    54817: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_willow', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Willow'),
    54818: ItemData(IC.useful, 1, 'wh_dlc05_tech_1_the_ancients', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Ancients'),
    54819: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_ash', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Ash'),
    54820: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_yew', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Yew'),
    54821: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_cypress', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Cypress'),
    54813: ItemData(IC.useful, 1, 'tech_dlc16_wef_ancients_oak', ItemType.tech, 1, 'Progressive tech_wef_wisdom', 'Wef Tech: Wisdom of the Oak'),
}

progUnits: dict[int, ItemData] = {
    55200: ItemData(IC.useful, 3, "Progressive wef_inf", ItemType.unit, 3, "", "Progressive Wef Unit: Infantry"),
    55201: ItemData(IC.useful, 3, "Progressive wef_rng", ItemType.unit, 3, "", "Progressive Wef Unit: Ranged"),
    55202: ItemData(IC.useful, 4, "Progressive wef_cav", ItemType.unit, 4, "", "Progressive Wef Unit: Cavalry"),
    55205: ItemData(IC.useful, 4, "Progressive wef_bst", ItemType.unit, 4, "", "Progressive Wef Unit: Beast"),
    55206: ItemData(IC.useful, 2, "Progressive wef_hro", ItemType.unit, 2, "", "Progressive Wef Unit: Hero")
}

progBuildings: dict[int, ItemData] = {
    55300: ItemData(IC.useful, 3, 'Progressive foreign_slot_discovery_wef', ItemType.building, 3, None, 'Progressive Wef Building: Foreign Slot Discovery Wef'),
    55301: ItemData(IC.useful, 1, 'Progressive wef_resource_animals', ItemType.building, 1, None, 'Progressive Wef Building: Animals'),
    55302: ItemData(IC.useful, 1, 'Progressive wef_resource_gems', ItemType.building, 1, None, 'Progressive Wef Building: Gems'),
    55303: ItemData(IC.useful, 1, 'Progressive wef_resource_medicine', ItemType.building, 1, None, 'Progressive Wef Building: Medicine'),
    55304: ItemData(IC.useful, 1, 'Progressive wef_resource_obsidian', ItemType.building, 1, None, 'Progressive Wef Building: Obsidian'),
    55305: ItemData(IC.useful, 1, 'Progressive wef_resource_spices', ItemType.building, 1, None, 'Progressive Wef Building: Spices'),
    55306: ItemData(IC.useful, 3, 'Progressive wef_allied_outpost', ItemType.building, 3, None, 'Progressive Wef Building: Allied Outpost'),
    55307: ItemData(IC.useful, 1, 'Progressive wef_resource_ivory', ItemType.building, 1, None, 'Progressive Wef Building: Ivory'),
    55308: ItemData(IC.useful, 2, 'Progressive wef_agent_protection', ItemType.building, 2, None, 'Progressive Wef Building: Agent Protection'),
    55309: ItemData(IC.useful, 2, 'Progressive wef_armoury', ItemType.building, 2, None, 'Progressive Wef Building: Armoury'),
    55310: ItemData(IC.useful, 4, 'Progressive wef_cavalry', ItemType.building, 4, None, 'Progressive Wef Building: Cavalry'),
    55311: ItemData(IC.useful, 3, 'Progressive wef_flying', ItemType.building, 3, None, 'Progressive Wef Building: Flying'),
    55312: ItemData(IC.useful, 3, 'Progressive wef_garrison', ItemType.building, 3, None, 'Progressive Wef Building: Garrison'),
    55313: ItemData(IC.useful, 3, 'Progressive wef_growth', ItemType.building, 3, None, 'Progressive Wef Building: Growth'),
    55314: ItemData(IC.useful, 4, 'Progressive wef_income', ItemType.building, 4, None, 'Progressive Wef Building: Income'),
    55315: ItemData(IC.useful, 3, 'Progressive wef_melee', ItemType.building, 3, None, 'Progressive Wef Building: Melee'),
    55320: ItemData(IC.useful, 1, 'Progressive wef_outpost_foraging', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Foraging'),
    55321: ItemData(IC.useful, 1, 'Progressive wef_outpost_major_human', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Major Human'),
    55322: ItemData(IC.useful, 1, 'Progressive wef_outpost_recruitment', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Recruitment'),
    55323: ItemData(IC.useful, 1, 'Progressive wef_outpost_replenishment', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Replenishment'),
    55324: ItemData(IC.useful, 1, 'Progressive wef_outpost_slaughter', ItemType.building, 1, None, 'Progressive Wef Building: Outpost Slaughter'),
    55325: ItemData(IC.useful, 1, 'Progressive wef_port', ItemType.building, 1, None, 'Progressive Wef Building: Port'),
    55326: ItemData(IC.useful, 3, 'Progressive wef_public_order', ItemType.building, 3, None, 'Progressive Wef Building: Public Order'),
    55327: ItemData(IC.useful, 3, 'Progressive wef_ranged', ItemType.building, 3, None, 'Progressive Wef Building: Ranged'),
    55328: ItemData(IC.useful, 1, 'Progressive wef_resource_dyes', ItemType.building, 1, None, 'Progressive Wef Building: Dyes'),
    55329: ItemData(IC.useful, 1, 'Progressive wef_resource_furs', ItemType.building, 1, None, 'Progressive Wef Building: Furs'),
    55330: ItemData(IC.useful, 1, 'Progressive wef_resource_gold', ItemType.building, 1, None, 'Progressive Wef Building: Gold'),
    55331: ItemData(IC.useful, 1, 'Progressive wef_resource_iron', ItemType.building, 1, None, 'Progressive Wef Building: Iron'),
    55332: ItemData(IC.useful, 1, 'Progressive wef_resource_marble', ItemType.building, 1, None, 'Progressive Wef Building: Marble'),
    55333: ItemData(IC.useful, 1, 'Progressive wef_resource_pastures', ItemType.building, 1, None, 'Progressive Wef Building: Pastures'),
    55334: ItemData(IC.useful, 1, 'Progressive wef_resource_pottery', ItemType.building, 1, None, 'Progressive Wef Building: Pottery'),
    55335: ItemData(IC.useful, 1, 'Progressive wef_resource_salt', ItemType.building, 1, None, 'Progressive Wef Building: Salt'),
    55336: ItemData(IC.useful, 1, 'Progressive wef_resource_timber', ItemType.building, 1, None, 'Progressive Wef Building: Timber'),
    55337: ItemData(IC.useful, 1, 'Progressive wef_resource_wine', ItemType.building, 1, None, 'Progressive Wef Building: Wine'),
    55338: ItemData(IC.useful, 5, 'Progressive wef_settlement_major', ItemType.building, 5, None, 'Progressive Wef Building: Settlement Major'),
    55339: ItemData(IC.useful, 3, 'Progressive wef_spellsingers', ItemType.building, 3, None, 'Progressive Wef Building: Spellsingers'),
    55340: ItemData(IC.useful, 2, 'Progressive wef_temple_anath_raema', ItemType.building, 2, None, 'Progressive Wef Building: Temple Anath Raema'),
    55341: ItemData(IC.useful, 1, 'Progressive wef_temple_ereth_khial', ItemType.building, 1, None, 'Progressive Wef Building: Temple Ereth Khial'),
    55342: ItemData(IC.useful, 1, 'Progressive wef_temple_isha', ItemType.building, 1, None, 'Progressive Wef Building: Temple Isha'),
    55343: ItemData(IC.useful, 1, 'Progressive wef_temple_kurnous', ItemType.building, 1, None, 'Progressive Wef Building: Temple Kurnous'),
    55344: ItemData(IC.useful, 4, 'Progressive wef_tree_spirits', ItemType.building, 4, None, 'Progressive Wef Building: Tree Spirits')
}

progTechs: dict[int, ItemData] = {
    55400: ItemData(IC.useful, 6, "Progressive tech_wef_cadai", ItemType.tech, 6, None, "Progressive Wef Tech: Cadai"),
    55401: ItemData(IC.useful, 6, "Progressive tech_wef_cytharai", ItemType.tech, 6, None, "Progressive Wef Tech: Cytharai"),
    55402: ItemData(IC.useful, 1, "Progressive tech_wef_wisdom", ItemType.tech, 1, None, "Progressive Wef Tech: Wisdom"),
}

special: dict[int, specialItemData] = {
    55500: specialItemData(IC.useful, 1, 'wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_inf_dryads_0', ItemType.unit, 1, 'Progressive wef_inf', False, False, 'Wef Unit: Dryads'),
    55501: specialItemData(IC.useful, 1, 'wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_cha_branchwraith_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Branchwraith'),
    55502: specialItemData(IC.useful, 1, 'wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_mon_treeman_0', ItemType.unit, 4, 'Progressive wef_bst', False, False, 'Wef Unit: Treeman'),
    55503: specialItemData(IC.useful, 1, 'wh_dlc05_wef_wood_elves', 'wh_dlc05_wef_mon_treekin_0', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Tree Kin'),
    55504: specialItemData(IC.useful, 1, 'wh_dlc05_wef_argwylon', 'wh_dlc05_wef_inf_dryads_0', ItemType.unit, 1, 'Progressive wef_inf', False, False, 'Wef Unit: Dryads'),
    55505: specialItemData(IC.useful, 1, 'wh_dlc05_wef_argwylon', 'wh_dlc05_wef_cha_branchwraith_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Branchwraith'),
    55506: specialItemData(IC.useful, 1, 'wh_dlc05_wef_argwylon', 'wh_dlc05_wef_mon_treeman_0', ItemType.unit, 4, 'Progressive wef_bst', False, False, 'Wef Unit: Treeman'),
    55507: specialItemData(IC.useful, 1, 'wh_dlc05_wef_argwylon', 'wh_dlc05_wef_mon_treekin_0', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Tree Kin'),
    55508: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_sisters_of_twilight', 'wh_dlc05_wef_inf_dryads_0', ItemType.unit, 1, 'Progressive wef_inf', False, False, 'Wef Unit: Dryads'),
    55509: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_sisters_of_twilight', 'wh_dlc05_wef_cha_branchwraith_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Branchwraith'),
    55510: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_sisters_of_twilight', 'wh_dlc05_wef_mon_treeman_0', ItemType.unit, 4, 'Progressive wef_bst', False, False, 'Wef Unit: Treeman'),
    55511: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_sisters_of_twilight', 'wh_dlc05_wef_mon_treekin_0', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Tree Kin'),
    55512: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_inf_malicious_dryads_0', ItemType.unit, 1, 'Progressive wef_inf', False, False, 'Wef Unit: Malevolent Dryads'),
    55513: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_malicious_treekin_0', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Malevolent Tree Kin'),
    55514: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_malicious_treeman_0', ItemType.unit, 4, 'Progressive wef_bst', False, False, 'Wef Unit: Malevolent Treeman'),
    55515: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_cha_malicious_branchwraith_beasts_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Malevolent Branchwraith (Beasts)'),
    55516: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_cha_malicious_branchwraith_life_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Malevolent Branchwraith (Life)'),
    55517: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_cha_malicious_branchwraith_shadows_0', ItemType.unit, 2, 'Progressive wef_hro', False, False, 'Wef Unit: Malevolent Branchwraith (Shadows)'),
    55518: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'tech_dlc16_wef_ancients_addaivoch', ItemType.tech, 1, 'Progressive tech_wef_wisdom', False, False, 'Wef Tech: Wisdom of Addaivoch'),
    55519: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'tech_dlc16_wef_ancients_wildwood', ItemType.tech, 1, 'Progressive tech_wef_wisdom', False, False, 'Wef Tech: Wisdom of the Wildwood'),
    55520: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_cave_bats', ItemType.unit, 1, 'Progressive wef_bst', False, False, 'Wef Unit: Cave Bats'),
    55521: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_feral_manticore', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Feral Manticore'),
    55522: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_giant_spiders_0', ItemType.unit, 1, 'Progressive wef_bst', False, False, 'Wef Unit: Giant Spiders'),
    55523: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_wolves_0', ItemType.unit, 1, 'Progressive wef_bst', False, False, 'Wef Unit: Giant Wolves'),
    55524: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh3_main_monster_feral_bears', ItemType.unit, 2, 'Progressive wef_bst', False, False, 'Wef Unit: Feral Bears'),
    55525: specialItemData(IC.useful, 1, 'wh2_dlc16_wef_drycha', 'wh2_dlc16_wef_mon_hawks_0', ItemType.unit, 1, 'Progressive wef_bst', False, False, 'Wef Unit: Great Hawks')
}